databendlabs/databend

- src/bendpy/src/context.rs
- src/bendpy/src/datablock.rs
- src/bendpy/src/dataframe.rs
- src/query/expression/src/utils/block_debug.rs
1. Fix SessionContext usage
2. Improve box render
Closes #issue
> feat(python): fix context

- .github/workflows/bindings_python.yml
> ci: fix inputs tag for python binding [skip ci]

- .github/workflows/bindings_python.yml
> ci: fix publish python binding to pypi

- src/common/exception/src/exception_code.rs
- src/query/service/src/interpreters/interpreter_view_alter.rs
- src/query/service/src/interpreters/interpreter_view_create.rs
- tests/sqllogictests/suites/base/05_ddl/05_0021_ddl_alter_view
1. use exists_table to replace list_tables.
2. add exception code : UnknownView(1026)
Closes #11428
> feat(query): optimize alter and create view when has lots of tables

- .github/workflows/production.yml
> chore: fix ee ci workflow

- src/query/storages/parquet/src/deserialize_transform.rs
> fix: intervals_to_bitmap() wrong assert.

- .github/workflows/production.yml
- Cargo.lock
- src/bendpy/Cargo.toml
- src/bendpy/README.md
- src/bendpy/src/context.rs
- src/bendpy/src/lib.rs
- src/query/service/src/sessions/session_ctx.rs
- src/query/service/src/sessions/session_mgr.rs
- src/query/service/src/sessions/session_type.rs
- src/query/service/tests/it/sessions/session_context.rs
> feat(python): support tenant 

- docs/doc/91-enterprise/10-enterprise-features.md
> docs: add link to ee for vacuum table feature

- .github/workflows/bindings_python.yml
> ci: fix ignore path [skip ci]

- src/query/sql/src/planner/binder/copy.rs
- tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_06_transform.result
- tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_06_transform.sh
> feat: support copy from URI with transform.

- .github/actions/build_linux/action.yml
> fix: support 64K pagesize on aarch64 [skip ci]

- src/query/expression/src/utils/block_debug.rs
- src/query/service/src/servers/http/v1/query/execute_state.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
reduce an extra plan_sql in http api
Closes #issue
> chore: reduce an extra plan_sql in http api

- docs/doc/12-load-data/01-load/06-data-load-transform.md
- updated tutorials with "transform data from uri"
Closes #issue
> docs: transform data from uri

- docs/doc/14-sql-commands/00-ddl/20-table/91-vacuum-table.md
added fail-safe.
Closes #issue
> docs: vacuum table updates

- src/query/storages/fuse/src/operations/read/native_rows_fetcher.rs
`Iterator::nth` will consume the preceding elements, we should reset the offset after calling this method.
> fix: fix lazy topn on native format.

- tests/sqllogictests/suites/query/02_function/02_0039_function_strings_sounds_like
Modify duplicated test case for SOUNDS LIKE syntax
Closes #11502
> fix: modify duplicated test case for SOUNDS LIKE syntax

- src/query/catalog/src/plan/internal_column.rs
- src/query/catalog/tests/it/partitions.rs
- src/query/storages/fuse/src/operations/read/fuse_rows_fetcher.rs
- src/query/storages/fuse/src/operations/read/native_rows_fetcher.rs
- src/query/storages/fuse/src/operations/read/parquet_rows_fetcher.rs
> chore(query): make row fetcher lazy read segments

- docs/doc/03-develop/01-python.md
- Add py connection parameters
> docs: add py connection parameters

- docs/doc/03-develop/01-python.md
rephrased newly added content about Python
Closes #issue
> docs: rephrase 

- docs/doc/03-develop/03-jdbc.md
update databend-jdbc version from 0.0.7 to 0.0.8
Closes #issue
> docs:Update 03-jdbc.md

- tests/sqllogictests/suites/tpcds/queries.test
chore(query): skip TPCDS q35
https://github.com/datafuselabs/databend/actions/runs/5035573607/jobs/9031555565?pr=11510
Closes #issue
> chore(query): skip TPCDS q35

- docs/public/templates/command-template.md
- docs/public/templates/function-template.md
Added doc templates for doc contributors. 
Included the code for EE banner and version symbol.
Closes #issue
> docs: doc templates

- website/blog/2023-05-21-databend-weekly-94.md
> docs(weekly): add this week in databend 94

- src/query/service/src/servers/mysql/mysql_interactive_worker.rs
- src/query/sql/src/planner/binder/binder.rs
- tests/sqllogictests/suites/base/07_use/07_0000_use_database
use db err need normalize ident db.
Closes #11491
> fix(query): fix use db err because of not normalize ident

- .github/workflows/benchmark.yml
> ci: fix checkout for benchmark in pr

- Cargo.lock
- Cargo.toml
- src/common/storage/src/metrics.rs
- src/common/storage/src/operator.rs
- src/common/storage/src/runtime_layer.rs
- src/meta/app/src/storage/storage_params.rs
- src/query/config/src/config.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
- src/query/sharing/src/layer.rs
This PR will bump version of opendal and add native COS support.
> feat(storage): Add native COS support

- Cargo.lock
- src/common/openai/Cargo.toml
- src/common/openai/src/completion.rs
- src/common/openai/src/embedding.rs
- src/common/openai/src/openai.rs
- src/common/openai/tests/it/openai.rs
- src/query/config/src/config.rs
- src/query/config/src/inner.rs
- src/query/expression/src/function.rs
- src/query/functions/src/scalars/vector.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/src/table_functions/openai/ai_to_sql.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
support azure openai to `[query]`:
```
openai_api_chat_base_url = "https://<name>.openai.azure.com/openai/deployments/<name>/"
openai_api_embedding_base_url = "https://<name>.openai.azure.com/openai/deployments/<name>/"
openai_api_version = "2023-03-15-preview"
```
Closes #issue
> feat: support azure openai api

- docs/doc/15-sql-functions/61-ai-functions/01-ai-to-sql.md
- docs/doc/15-sql-functions/61-ai-functions/02-ai-embedding-vector.md
- docs/doc/15-sql-functions/61-ai-functions/03-ai-text-completion.md
- docs/doc/15-sql-functions/61-ai-functions/04-ai-cosine-distance.md
- docs/doc/15-sql-functions/61-ai-functions/index.md
* add azure openai service notes
Closes #issue
> docs: add support for azure openai service

- docs/doc/01-guides/index.md
- docs/doc/11-integrations/00-api/10-put-to-stage.md
- docs/doc/12-load-data/00-stage/01-manage-stages.md
- docs/doc/12-load-data/00-stage/02-stage-files.md
> docs: minor fixes

- docs/doc/15-sql-functions/05-bitmap-functions/_category_.json
- docs/doc/15-sql-functions/05-bitmap-functions/index.md
added bitmap functions.
Closes #issue
> docs: bitmap functions

- src/meta/api/src/data_mask_api_impl.rs
fix: fix drop data mask bug
Closes #issue
> fix: fix drop data mask bug

- scripts/setup/dev_setup.sh
- src/query/ast/src/ast/expr.rs
- src/query/ast/src/ast/format/ast_format.rs
- src/query/ast/src/ast/format/syntax/expr.rs
- src/query/ast/src/parser/expr.rs
- src/query/ast/src/visitors/visitor.rs
- src/query/ast/src/visitors/visitor_mut.rs
- src/query/ast/src/visitors/walk.rs
- src/query/ast/src/visitors/walk_mut.rs
- src/query/ast/tests/it/testdata/query.txt
- src/query/ast/tests/it/testdata/statement.txt
- src/query/expression/src/types/decimal.rs
- src/query/expression/src/types/number.rs
- src/query/expression/src/values.rs
- src/query/service/src/pipelines/processors/transforms/window/transform_window.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/window_function/window_basic.test
- tests/sqllogictests/suites/query/window_function/window_wisconsin.test
- tests/suites/5_ee/02_data_mask/02_0000_data_mask.py
1. fix lag/lead default value when the column is nullable
2. fix count(*) can be used in window function
3. add more window function tests that derived from duckdb
4. fix lag function with partition by
Closes #issue
> fix: fix lag/lead default value when column is nullable

- src/query/storages/fuse/src/operations/merge_into/mutator/merge_into_mutator.rs
`MergeIntoOperationAggregator` should run the data block deserialization
task on thread dedicated to blocking operations (by using global io
instance's spawn_blocking)
In PR #11571, the above tweaks are removed by mistake.
Closes #issue
> fix: `MergeIntoOperationAggregator` should run data block deserialization task on dedicated thread

- tests/sqllogictests/suites/tpch/join.test
> chore: add large dataset test for iejoin

- src/query/expression/src/type_check.rs
- src/query/expression/src/utils/mod.rs
- src/query/sql/src/planner/optimizer/property/constraint.rs
> chore(expr): add cast_scalar util function

- website/.remarkrc.yml
> docs(website): fix yml lint

- docs/doc/10-deploy/02-deploying-databend.md
added support for deploying with tencent cos.
Closes #issue
> docs: tencent cos

- .github/workflows/dev-linux.yml
> ci: run sqllogic ydb with 8c16g

- .github/actions/build_linux/action.yml
- .github/workflows/reuse.linux.yml
> ci: fix artifacts for release build

- .github/workflows/reuse.linux.yml
> ci: fix syntax error in production ci

- tests/metactl/test-metactl-restore-new-cluster.sh
> ci: fix build profile for test script metactl restore

- docs/doc/100-faq/30-license-faqs.md
> docs: fix typos in 30-license-faqs.md

- .github/workflows/reuse.linux.yml
> ci: fix test condition for ee

- .github/actions/build_macos/action.yml
- .github/workflows/dev.yml
> ci: enable sccache for macos build

- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state_impl.rs
After 1 into if' inner, **unlock**, before `self.finalized_notify.notified()` is called, 2 finished, the 1 will wait in vain : ( 
The probability is very low....
Closes #issue
> fix: fix hash join hang

- Cargo.lock
- Cargo.toml
- src/common/io/Cargo.toml
- src/common/io/tests/it/cursor_ext/fast_read_text_ext.rs
- src/query/service/Cargo.toml
- src/query/service/src/interpreters/interpreter_insert.rs
- tests/sqllogictests/suites/query/02_function/02_0048_function_semi_structureds_parse_json
- fix parse json with escaped and UTF-8 characters
- upgrade `AhoCorasick` version
Closes #11656
> fix(query): fix parse json with escaped and UTF-8 characters

- src/query/service/src/catalogs/default/immutable_catalog.rs
> docs(catalog): correct information_schema is supported

- src/meta/service/src/api/grpc_server.rs
> chore: contributor-friendly error message

- website/src/plugins/fetch-databend-releases.js
> chore: Rewrite IGNORE_TEXT

- docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
added max_files option to copy into cmd
Closes #11666
> docs: max_files option

- src/meta/app/src/principal/user_info.rs
- src/query/management/src/user/user_mgr.rs
- src/query/management/tests/it/user.rs
- src/query/sql/src/planner/binder/ddl/account.rs
- src/query/users/src/user_mgr.rs
- src/query/users/tests/it/user_mgr.rs
- allow the root user to alter the password
- don't allow alter and drop configured user info
Closes #11641
> feat(query): Allow root user alter password

- docs/doc/14-sql-commands/20-query-syntax/01-query-select.md
Fixed comment: https://github.com/datafuselabs/databend/pull/11673#discussion_r1218803462
Closes #issue
> docs: column alias updates

- docs/doc/14-sql-commands/80-setting-cmds/03-set-var.md
- introduced deduplicate label.
- added support for COPY INTO 
Closes #issue
> docs: set var updates

- Cargo.lock
- Cargo.toml
- tests/sqllogictests/suites/query/02_function/02_0048_function_semi_structureds_parse_json
> fix(query): Fix json special and foreign characters display errors

- .github/workflows/benchmark.yml
- benchmark/clickbench/benchmark_cloud.sh
> ci: fix warehouse size for benchmark

- website/blog/2023-06-11-databend-weekly-97.md
> docs(weekly): add this week in databend 97

- src/query/expression/src/type_check.rs
- tests/sqllogictests/suites/base/20+_others/20_0014_result_scan
- tests/sqllogictests/suites/base/20+_others/20_0016_last_query_id
> fix: try to cast to target data type when `check_number`.

- docs/doc/03-develop/03-jdbc.md
> docs(JDBC): close statement after use.

- tests/sqllogictests/src/client/mysql_client.rs
The length of column types should not be equal to the length of rows.
> chore(sqllogictests): fix column types of MySQLClient

- docs/doc/14-sql-commands/10-dml/dml-insert.md
- docs/doc/14-sql-commands/10-dml/dml-replace.md
> docs: replace with stage attachments

- docs/doc/15-sql-functions/10-aggregate-functions/aggregate-array-agg.md
Minor updates for https://databend.rs/doc/sql-functions/aggregate-functions/aggregate-array-agg
Closes #issue
> docs: array_agg updates

- src/query/service/src/servers/http/v1/query/http_query_manager.rs
- src/query/service/src/sessions/session_mgr.rs
> feat: kill http query after timeout.

- src/query/catalog/src/table.rs
- src/query/service/src/table_functions/numbers/numbers_table.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/storages/fuse/src/fuse_table.rs
- src/query/storages/system/src/tables_table.rs
- tests/sqllogictests/suites/query/select.test
add number_of_blocks,number_of_segments for system.tables
Closes #issue
#11699
> feat: add number_of_blocks,number_of_segments for system.tables

- docs/doc/12-load-data/00-transform/05-querying-stage.md
- docs/doc/14-sql-commands/20-query-syntax/01-query-select.md
> docs: Column position

- src/query/formats/src/field_decoder/row_based.rs
make parsing of `2022-12-03 07:17:55`  3 to 4 times faster.
Closes #issue
> refactor: optimize decoding timestamp column.

- docs/doc/12-load-data/00-transform/05-querying-stage.md
Introduced table alias to query staged files
Closes #issue
> docs: table alias

- src/query/catalog/src/table.rs
- src/query/service/src/interpreters/interpreter_delete.rs
- src/query/service/src/interpreters/interpreter_update.rs
- src/query/service/src/test_kits/table_test_fixture.rs
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/sql/src/planner/binder/delete.rs
- src/query/sql/src/planner/binder/update.rs
- src/query/sql/src/planner/plans/update.rs
- src/query/storages/fuse/src/fuse_table.rs
- src/query/storages/fuse/src/operations/mutation/mutation_source.rs
- src/query/storages/fuse/src/operations/update.rs
- tests/sqllogictests/suites/base/03_common/03_0035_update
- tests/sqllogictests/suites/crdb/delete
Support subquery in update's selection position.
Part of https://github.com/datafuselabs/databend/issues/9455
> feat: support subquery in update statement

- docs/doc/14-sql-commands/10-dml/dml-delete-from.md
> docs: delete with subquery

- src/query/pipeline/transforms/src/processors/transforms/transform_async.rs
refactor(executor): parallel async tasks for async transform
Closes #issue
> refactor(executor): parallel async tasks for async transform

- src/binaries/meta/entry.rs
When starting up meta-service node, meta-service node tries to register
it self to the leader it knows.
But such a leader may already stepped down.
In such a case, wait for next leader and retry registering, instead of
just quitting with error.
- Fix: #11778
> refactor(meta-service): when starting up, retry registering node

- src/query/codegen/src/writes/arithmetics_type.rs
- src/query/codegen/src/writes/register.rs
- src/query/expression/src/evaluator.rs
- src/query/expression/src/function.rs
- src/query/expression/src/register.rs
- src/query/expression/src/utils/arithmetics_type.rs
- src/query/functions/src/scalars/arithmetic.rs
- src/query/functions/src/scalars/array.rs
- src/query/functions/src/scalars/bitmap.rs
- src/query/functions/src/scalars/boolean.rs
- src/query/functions/src/scalars/comparison.rs
- src/query/functions/src/scalars/control.rs
- src/query/functions/src/scalars/datetime.rs
- src/query/functions/src/scalars/decimal.rs
- src/query/functions/src/scalars/geo.rs
- src/query/functions/src/scalars/hash.rs
- src/query/functions/src/scalars/map.rs
- src/query/functions/src/scalars/math.rs
- src/query/functions/src/scalars/other.rs
- src/query/functions/src/scalars/string.rs
- src/query/functions/src/scalars/string_multi_args.rs
- src/query/functions/src/scalars/tuple.rs
- src/query/functions/src/scalars/variant.rs
- src/query/functions/src/scalars/vector.rs
> chore(expr): add FunctionCtx in calc_domain

- website/blog/2023-06-18-databend-weekly-98.md
> docs(weekly): add this week in databend 98

- docs/doc/15-sql-functions/110-semi-structured-functions/object-keys.md
modify an error sql
Closes #issue
> docs: Update object-keys.md

- src/query/service/src/test_kits/block_writer.rs
- src/query/service/tests/it/storages/fuse/bloom_index_meta_size.rs
- src/query/service/tests/it/storages/fuse/operations/mutation/recluster_mutator.rs
- src/query/service/tests/it/storages/fuse/operations/read_plan.rs
- src/query/service/tests/it/storages/fuse/statistics.rs
- src/query/storages/common/table-meta/benches/bench.rs
- src/query/storages/common/table-meta/src/meta/v2/segment.rs
- src/query/storages/common/table-meta/src/meta/v3/frozen/block_meta.rs
- src/query/storages/fuse/src/fuse_part.rs
- src/query/storages/fuse/src/io/write/block_writer.rs
- src/query/storages/fuse/src/operations/read_partitions.rs
- src/query/storages/fuse/src/statistics/accumulator.rs
Add optional create_on for segment block meta
Closes #issue
> feat(storage): add optional create_on for segment block meta

- src/query/sql/src/planner/plans/join.rs
change the broadcast join threshold, and make it sensitive to the cluster number.
Closes #issue
> chore: change broadcast join threshold

- docs/doc/12-load-data/00-transform/05-querying-stage.md
> docs: select $N from csv

- docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
> docs: on_error

- src/query/service/src/pipelines/processors/transforms/transform_hash_join.rs
fix(query): fix dead lock for join
fixes https://github.com/datafuselabs/databend/actions/runs/5307075175/jobs/9605817648?pr=11790
> fix(query): fix dead lock for join

- docs/doc/15-sql-functions/30-datetime-functions/datediff.md
> docs: datediff

- src/query/service/src/schedulers/fragments/fragmenter.rs
- src/query/sql/src/executor/physical_plan.rs
- src/query/sql/src/executor/physical_plan_visitor.rs
I find out the destinations attr is useless, so I'm trying to remove it, let me see the ci result first.
Closes #issue
> refactor : remove destinations

- .github/workflows/bindings_python.yml
- src/bendpy/pyproject.toml
- src/bendpy/src/context.rs
- src/bendpy/src/dataframe.rs
- src/bendpy/tests/basic.py
> feat(python): support mac os pypi crates

- .github/workflows/bindings_python.yml
> feat(python): support mac os pypi crates2

- src/query/expression/src/kernels/take_compact.rs
`take_compact` has a memory bug, we temporarily revert it.
Closes #issue
> fix(query): revert take compact

- .github/workflows/bindings_python.yml
> feat(python): add macos bindings3

- src/query/ee/src/background_service/background_service_handler.rs
> chore: should not regist session in non-background service

- tests/suites/5_ee/00_check/00_0014_license_info.py
- tests/suites/5_ee/00_check/00_0014_license_info.result
> chore: add integration tests to avoid session leak on start

- src/meta/service/tests/it/api/http/cluster_state_test.rs
> refactor(meta): `start()` does not block, retry until ready

- website/blog/2023-06-25-databend-weekly-99.md
> docs(weekly): add this week in databend 99

- src/query/ee/tests/it/aggregating_index/index_scan.rs
- src/query/service/src/interpreters/interpreter_index_refresh.rs
- src/query/sql/src/planner/semantic/aggregating_index_rewriter.rs
- src/query/storages/fuse/src/operations/agg_index_sink.rs
- tests/sqllogictests/suites/ee/02_ee_aggregating_index/base
> chore: add sqllogic tests for aggregating index.

- .github/workflows/cloud.yml
- .github/workflows/release.yml
- .github/workflows/reuse.benchmark.yml
> ci: build image for pr label ci-cloud

- .github/workflows/cloud.yml
> ci: fix build cloud docker image [skip ci]

- .github/actions/setup_build_tool/action.yml
> ci: disable crates cache [skip ci]

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows.md
- .github/workflows/pr.yml
> ci: add workflow for pr

- src/query/service/tests/it/interpreters/mod.rs
- src/query/service/tests/it/interpreters/union.rs
- tests/sqllogictests/suites/base/20+_others/20_0013_query_result_cache
> chore: add unit tests and sql logic tests for union query.

- .github/workflows/cloud.yml
> chore(ci): add note for pr docker image

- .github/workflows/bindings_python.yml
> chore(python): fix python release action

- src/meta/service/tests/it/grpc/metasrv_grpc_api.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_export.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_get_client_info.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_kv_api_restart_cluster.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_watch.rs
> chore(meta): simplify testing codes

- src/query/service/src/pipelines/pipeline_builder.rs
- src/query/sql/src/executor/physical_plan.rs
- src/query/sql/src/executor/physical_plan_builder.rs
- src/query/sql/src/executor/physical_plan_visitor.rs
- src/query/sql/src/planner/binder/sort.rs
- src/query/sql/src/planner/optimizer/heuristic/prune_unused_columns.rs
- src/query/sql/src/planner/plans/sort.rs
> feat: introduce projection in front of sort pipeline.

- docs/doc/10-deploy/02-deploying-databend.md
- docs/doc/10-deploy/05-deploying-local.md
- docs/doc/13-sql-clients/00-admin-users.md
- docs/doc/13-sql-clients/00-mysql.md
- scripts/distribution/configs/databend-query.toml
> docs: configure users

- src/query/storages/fuse/src/operations/gc.rs
> fix: purge add abort check

- .github/workflows/bindings_python.yml
- .github/workflows/cloud.yml
- .github/workflows/reuse.benchmark.yml
> ci: fix concurrency deadlock

- benchmark/clickbench/benchmark_cloud.sh
- benchmark/clickbench/benchmark_local.sh
> fix(benchmark): add default user to clickbench local

- docs/doc/12-load-data/00-transform/05-querying-stage.md
> docs: allow_anonymous parameter

- src/query/service/src/api/rpc/exchange/statistics_receiver.rs
- src/query/service/src/pipelines/executor/processor_async_task.rs
- src/query/service/src/servers/http/v1/query/execute_state.rs
fix(query): use panic message as error message
- Closes #11733
> fix(query): use panic message as error message

- docs/doc/14-sql-commands/00-ddl/40-stage/01-ddl-create-stage.md
> docs: create external stage with IAM user

- src/query/sql/src/planner/optimizer/hyper_dp/dphyp.rs
- tests/sqllogictests/suites/query/join.test
> fix: distinct aggregate is missed in dphyp

- src/meta/app/src/principal/user_stage.rs
- src/query/storages/fuse/src/operations/mutation/mutation_source.rs
- src/query/storages/fuse/src/operations/update.rs
- tests/sqllogictests/suites/ee/01_ee_system/01_0001_computed_column
> chore: modify some update codes

- src/meta/app/src/principal/user_stage.rs
- src/query/functions/src/lib.rs
- src/query/service/src/pipelines/processors/transforms/window/frame_bound.rs
- src/query/service/src/pipelines/processors/transforms/window/transform_window.rs
- src/query/service/src/pipelines/processors/transforms/window/window_function.rs
- src/query/sql/src/executor/physical_plan.rs
- src/query/sql/src/executor/physical_plan_builder.rs
- src/query/sql/src/planner/plans/window.rs
- tests/sqllogictests/suites/query/window_function/window_wisconsin.test
Impl `cume_dist` window function.
Tracking: #11148
> feat: cume_dist window function

- docs/doc/03-develop/04-rust.md
- Closes datafuselabs/databend#11955
> docs: update dsn in develop/Rust docs

- .github/workflows/reuse.linux.yml
- tests/helpers/native_client.py
- tests/suites/5_ee/00_check/00_0014_license_info.py
- tests/suites/5_ee/00_check/00_0014_license_info.result
- tests/suites/5_ee/01_vacuum/01_0000_ee_vacuum.py
- tests/suites/5_ee/01_vacuum/01_0001_ee_vacuum_kill_randomly.sh
- tests/suites/5_ee/02_data_mask/02_0000_data_mask.py
> ci: run ee test in PR

- docs/doc/13-integrations/00-jupyter.md
> docs: Jupyter updates

- .github/workflows/reuse.linux.yml
> ci: fix license for ee test

- docs/doc/14-sql-commands/00-ddl/20-table/20-ddl-drop-table.md
- docs/doc/14-sql-commands/00-ddl/20-table/40-ddl-truncate-table.md
added description about the PURGE option
> docs: truncate table updates

- benchmark/clickbench/benchmark_cloud.sh
> chore(benchmark): check settings before benchmark

- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_aggregate_spill_writer.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_group_by_spill_writer.rs
chore(query): use append mode for spill writer
> chore(query): use append mode for spill writer

- src/query/service/src/servers/http/clickhouse_handler.rs
- src/query/service/src/servers/http/middleware.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/load.rs
- src/query/service/src/servers/http/v1/query/page_manager.rs
no longer log each long pulling request.
too many logs for long running query.
askbend:summary
> chore: reduce http handler logs.

- src/query/service/src/auth.rs
- src/query/service/src/servers/http/middleware.rs
> fix(query): return 500 on META_SERVICE_ERROR for auth

- scripts/ci/ci-run-sqllogic-tests-cluster.sh
> chore: enable backtrace

- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_aggregate_spill_writer.rs
> feat: add more metrics for spill data sersiaze

- src/query/expression/src/kernels/filter.rs
- src/query/expression/src/row/row_converter.rs
- src/query/expression/src/types/bitmap.rs
- src/query/expression/src/types/string.rs
- src/query/expression/src/types/variant.rs
- src/query/expression/src/utils/display.rs
- src/query/expression/src/values.rs
- src/query/expression/tests/it/row.rs
- src/query/functions/src/scalars/hash.rs
- src/query/functions/src/scalars/other.rs
- src/query/functions/src/scalars/string.rs
- src/query/functions/src/scalars/string_multi_args.rs
- src/query/pipeline/transforms/src/processors/transforms/sort/rows/common.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state_impl.rs
> chore(query): make StringColumn check offsets in debug_assert

- .github/actions/build_linux/action.yml
- .github/workflows/cloud.yml
- .github/workflows/release.yml
- .github/workflows/reuse.linux.hive.yml
- .github/workflows/reuse.linux.yml
> ci: fix sha for building cloud image

- src/query/service/src/databases/system/system_database.rs
* disable system.users if disable_system_table_load
> chore: disable system.users if disable_system_table_load

- docs/doc/14-sql-commands/00-ddl/40-stage/01-ddl-create-stage.md
> docs: fix s3 iam policy for external stage

- Cargo.lock
- Cargo.toml
- src/query/ee/src/storages/fuse/operations/virtual_columns.rs
- src/query/functions/src/scalars/variant.rs
- src/query/functions/src/srfs/mod.rs
> feat(query): json path selector use less memory

- src/query/catalog/src/table.rs
- src/query/service/src/interpreters/interpreter_delete.rs
- src/query/service/src/interpreters/interpreter_insert.rs
- src/query/service/src/interpreters/interpreter_table_add_column.rs
- src/query/service/src/interpreters/interpreter_table_create.rs
- src/query/service/src/interpreters/interpreter_table_rename_column.rs
- src/query/sql/src/planner/binder/internal_column_factory.rs
- src/query/sql/src/planner/plans/mod.rs
- src/query/sql/src/planner/plans/update.rs
- src/query/storages/fuse/src/fuse_table.rs
- src/query/storages/fuse/src/operations/delete.rs
- src/query/storages/fuse/src/operations/update.rs
1. Add const PREDICATE_COLUMN_NAME as predicate column in update.
2. format codes, remove some unused codes.
> chore: add const PREDICATE_COLUMN_NAME

- src/query/sql/src/planner/binder/ddl/column.rs
- src/query/sql/src/planner/binder/ddl/database.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- tests/suites/0_stateless/20+_others/20_0012_privilege_access.result
- tests/suites/0_stateless/20+_others/20_0012_privilege_access.sh
show db/tab/col should not display no privelige object
- Closes #12082
> fix(query): show db/tab/col should not display no privelige object

- src/query/service/src/interpreters/access/privilege_access.rs
- src/query/sql/src/planner/binder/ddl/column.rs
- src/query/sql/src/planner/binder/ddl/database.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- tests/suites/0_stateless/20+_others/20_0012_privilege_access.result
- tests/suites/0_stateless/20+_others/20_0012_privilege_access.sh
> fix(query): use db no need to check privileges just need check grant objects

- docs/doc/15-sql-functions/122-window-functions/index.md
> docs: fix link

- docs/doc/13-sql-reference/41-access-control-privileges.md
- docs/doc/14-sql-commands/00-ddl/10-database/ddl-use-database.md
- added USE DATABASE command.
- added a note: Please note that you can use the [USE DATABASE](http://localhost:3000/doc/sql-commands/ddl/database/ddl-use-database) command to specify a database once you have any of the following privileges to the database or any privilege to a table in the database.
> docs: use db

- scripts/setup/dev_setup.sh
> chore: fix prepare package manager for dev setup

- src/common/exception/src/exception_code.rs
- src/query/service/tests/it/storages/fuse/operations/mutation/segments_compact_mutator.rs
- src/query/storages/fuse/src/operations/commit.rs
- src/query/storages/fuse/src/operations/common/processors/sink_commit.rs
- src/query/storages/fuse/src/operations/common/snapshot_generator.rs
> refactor: tidy up the error message of mutation conflicts

- src/query/storages/parquet/src/lib.rs
- src/query/storages/parquet/src/parquet_table/mod.rs
- src/query/storages/parquet/src/parquet_table/read.rs
https://github.com/datafuselabs/databend/issues/11553
> refactor: not use `max_storage_io_requests` in ParquetTable.

- src/query/storages/fuse/src/operations/recluster.rs
- src/query/storages/fuse/src/pruning/fuse_pruner.rs
> chore: use max_threads instead of max_storage_io_requests in recluster

- src/query/service/src/api/http/v1/instance_status.rs
I uses the /v1/status api to made an auto-suspend mechanism in my production.
Recently I noticed that there may existed some clock drift issue between the operator and the instances. The operator may thinks the instance is ready to be suspended (now() - last_query_timestamp > auto_suspend_secs), but the `now()` timestamp comes from the operator side, this may causes a mis-behaviour to suspend the instance earlier than it expected.
This PR added an `instance_timestamp` field in the `/v1/status` api, thus allow the operator to determining auto suspend by reading the instance's local time.
> chore(http): return instance_timestamp together in /v1/status

- src/common/arrow/Cargo.toml
> chore(query): bump native engine to 0.2.4

- src/meta/app/src/principal/user_grant.rs
- src/query/ee/src/background_service/background_service_handler.rs
- src/query/service/src/interpreters/access/management_mode_access.rs
- src/query/service/src/interpreters/access/privilege_access.rs
- src/query/sql/src/planner/binder/ddl/column.rs
- src/query/sql/src/planner/binder/ddl/database.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/sql/src/planner/plans/plan.rs
- src/query/storages/system/src/columns_table.rs
- src/query/storages/system/src/databases_table.rs
- src/query/storages/system/src/tables_table.rs
- src/query/users/src/role_mgr.rs
- tests/sqllogictests/suites/base/05_ddl/05_0006_ddl_grant_privilege
- tests/sqllogictests/suites/base/05_ddl/05_0018_ddl_revoke
- tests/sqllogictests/suites/base/05_ddl/05_0022_ddl_revoke
- tests/suites/0_stateless/20+_others/20_0012_privilege_access.result
- tests/suites/0_stateless/20+_others/20_0012_privilege_access.sh
1. system.databases/tables/columns should respect user GrantObject.
2. `public` role add new default privileges.
```rust
public.grants.grant_privileges(
&GrantObject::Database("default".to_string(), "information_schema".to_string()),
UserPrivilegeType::Select.into(),
);
```
3. RewriteKind::ShowTables/ShowColumns add item.
- Closes #12108
> feat(query): system tables respect user privileges

- src/common/storage/src/common_metrics/copy.rs
- src/query/storages/parquet/src/parquet_reader/reader.rs
* add `copy_read_part_cost_milliseconds` metric
> feat: add copy read part cost metrics

- Cargo.lock
- src/query/service/src/interpreters/interpreter_table_optimize.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0008_fuse_optimize_table
> fix: no need to recluster after compact segment

- src/meta/client/src/lib.rs
> fix: fix typo in comment

- src/query/service/src/interpreters/interpreter_table_optimize.rs
- src/query/sql/src/executor/table_read_plan.rs
- src/query/sql/src/planner/binder/binder.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/sql/src/planner/binder/scalar.rs
- src/query/sql/src/planner/binder/setting.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/sql/src/planner/expression_parser.rs
- src/query/sql/src/planner/plans/scalar_expr.rs
- src/query/sql/src/planner/semantic/type_check.rs
- src/query/storages/fuse/src/operations/common/processors/sink_commit.rs
- src/query/storages/fuse/src/table_functions/clustering_information/clustering_information.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0000_remote_create_table
- tests/sqllogictests/suites/base/09_fuse_engine/09_0015_remote_alter_cluster_key
- tests/sqllogictests/suites/mode/cluster/distributed_copy_into_table2_execption.test
Add valid check for cluster key
1. Aggregation、udf、window and subquery expression are forbidden.
2. A cluster key  expression must contain a column.
> feat(query): add valid check for cluster key

- src/query/storages/fuse/src/io/read/block/decompressor.rs
chore(query): fix data race for uncompressed buffer
> chore(query): fix data race for uncompressed buffer

- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/base/20+_others/20_0010_expression_string_like
> fix: like panic due to Chinese

- docs/doc/15-sql-functions/30-datetime-functions/toyyyymmddhh.md
> docs: to_yyyymmddhh function

- src/query/ast/src/ast/format/ast_format.rs
- src/query/ast/src/ast/format/syntax/query.rs
- src/query/ast/src/ast/query.rs
- src/query/ast/src/parser/query.rs
- src/query/sql/src/planner/binder/aggregate.rs
- src/query/sql/src/planner/binder/scalar_common.rs
- tests/sqllogictests/suites/base/03_common/03_0003_select_group_by
> feat(query): support group by all syntax

- docker/Dockerfile
- docker/debian/meta.Dockerfile
- docker/debian/query.Dockerfile
- docs/doc/13-sql-clients/01-bendsql.md
> chore: change service image to debian:bookworm

- docs/doc/14-sql-commands/00-ddl/40-stage/04-ddl-list-stage.md
- docs/doc/15-sql-functions/112-table-functions/list_stage.md
see https://github.com/datafuselabs/databend/pull/10658
> docs: list_stage table function.

- docs/doc/14-sql-commands/20-query-syntax/06-query-group-by.md
- docs/doc/15-sql-functions/112-table-functions/list_stage.md
> docs: group by updates

- docs/doc/12-load-data/02-load-db/kafka.md
> docs: kafka

- tests/sqllogictests/suites/base/03_common/03_0025_delete_from
- tests/sqllogictests/suites/base/03_common/03_0035_update
- tests/sqllogictests/suites/crdb/join
- tests/sqllogictests/suites/crdb/runtime_filter_join
- Part of https://github.com/datafuselabs/databend/issues/12191 & https://github.com/datafuselabs/databend/issues/12193
> chore(test): fix wrong join tests

- src/query/storages/fuse/src/operations/commit.rs
> chore: update table meta with updated_on

- Cargo.lock
- src/common/arrow/Cargo.toml
- tests/sqllogictests/suites/crdb/select
1. fix the wrong test
2. bump native format
- Closes #12191
> chore(query): fix wrong tests

- Cargo.lock
- Cargo.toml
- src/bendpy/Cargo.toml
- src/bendpy/src/dataframe.rs
- src/common/storage/Cargo.toml
- src/query/ee-features/background-service/Cargo.toml
- src/query/ee/Cargo.toml
- src/query/expression/Cargo.toml
- src/query/service/Cargo.toml
- src/query/service/src/servers/flight_sql/flight_sql_service/service.rs
- src/query/service/tests/it/servers/flight_sql/flight_sql_handler.rs
- src/query/storages/iceberg/Cargo.toml
- src/query/storages/iceberg/src/table.rs
> chore: bump arrow from 40.0.0 to 43.0.0.

- src/query/expression/src/convert_arrow_rs/schema/from_data_schema.rs
- src/query/expression/src/convert_arrow_rs/schema/from_table_schema.rs
- src/query/service/src/servers/flight_sql/flight_sql_service/query.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12224)
> chore(query): send write progress to client

- docs/doc/10-deploy/02-deploying-databend.md
changed storage type to "oss".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12226)
> docs: fix alibaba deploy

- src/query/storages/fuse/src/operations/common/mutation_accumulator.rs
- src/query/storages/fuse/src/operations/common/snapshot_generator.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12218)
> feat: abort insertion if schema change detected

- docs/doc/100-faq/_category_.json
- docs/doc/13-monitor/20-server-logs.md
- docs/doc/13-monitor/30-tracing.md
Moved the two FAQ topics to the **Monitor** chapter to simplify TOC.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12231)
> docs: moved faq 

- website/src/pages/index.tsx
Added a question mark to the end of  _What is Databend_**?**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12234)
> docs: homepage text

- tests/sqllogictests/suites/base/09_fuse_engine/09_0016_remote_alter_recluster
Fix  09_0016_remote_alter_recluster
- Closes #12246 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12247)
> fix(ci): flaky test

- docs/doc/14-sql-commands/00-ddl/20-table/91-vacuum-table.md
updated description for **RETAIN n HOURS**.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12257)
> docs: vacuum retain period updates

- src/common/tracing/src/config.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
chore: Change testing log level to WARN
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12258)
> chore: Change testing log level to WARN

- src/query/service/src/global_services.rs
clippy: vec_init_then_push
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12311)
> chore: fix clippy.

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
Vacuum agg index in meta server.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12310)
> feat(agg-index): vacuum agg index in meta server

- website/blog/2023-08-02-debezium.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12326)
> docs: blog for debezium-server-databend

- docs/doc/10-deploy/02-deploying-databend.md
oss don't need enable_virtual_host_style = true
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12232)
> docs: Update 02-deploying-databend.md

- src/query/storages/parquet/src/parquet_reader.rs
- src/query/storages/parquet/src/parquet_rs/convert.rs
- src/query/storages/parquet/src/parquet_rs/parquet_reader/reader.rs
- src/query/storages/parquet/src/parquet_rs/statistics.rs
- src/query/storages/parquet/src/processors/deserialize_transform.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12324)
> chore: add comments for ParquetReader and small refactor

- docs/doc/15-sql-functions/122-window-functions/lag.md
- docs/doc/15-sql-functions/122-window-functions/lead.md
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/window_function/window_basic.test
Polish lag/lead window function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12329)
> chore: polish lag/lead window function

- src/query/storages/parquet/src/parquet_rs/parquet_reader/reader.rs
- src/query/storages/parquet/src/parquet_rs/parquet_reader/row_group_reader.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12340)
> feat: read parquet row group with suitable batches.

- src/query/sql/src/planner/binder/lambda.rs
- src/query/sql/src/planner/expression_parser.rs
- src/query/sql/src/planner/semantic/lowering.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12345)
> chore: add `ColumnBinding` for lambda functions

- src/query/storages/fuse/src/operations/append.rs
- src/query/storages/fuse/src/operations/commit.rs
- tests/sqllogictests/suites/mode/cluster/distributed_copy_into_table2_execption.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12342)
> chore: move TransformSerializeSegment after resize 1

- Cargo.lock
- Cargo.toml
- waiting for release of: https://github.com/apache/incubator-opendal/pull/2767
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12344)
> chore(deps): upgrade opendal to f02d627

- docs/doc/14-sql-commands/00-ddl/20-table/90-alter-table-column.md
Updated ALTER TABLE COLUMN: Added the capability to change column type.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12354)
> docs: change column type

- docs/doc/12-load-data/00-stage/00-whystage.md
- docs/doc/12-load-data/00-stage/01-manage-stages.md
- docs/doc/12-load-data/00-stage/02-stage-files.md
- docs/doc/12-load-data/00-transform/05-querying-stage.md
- docs/doc/12-load-data/00-transform/06-querying-metadata.md
- docs/doc/12-load-data/00-transform/07-data-load-transform.md
- docs/doc/12-load-data/01-load/00-stage.md
- docs/doc/12-load-data/01-load/01-s3.md
- docs/doc/12-load-data/01-load/02-local.md
- docs/doc/12-load-data/01-load/04-http.md
- docs/doc/12-load-data/01-load/index.md
- docs/doc/12-load-data/02-load-db/addax.md
- docs/doc/12-load-data/02-load-db/airbyte.md
- docs/doc/12-load-data/02-load-db/datax.md
- docs/doc/12-load-data/02-load-db/vector.md
- docs/doc/12-load-data/09-unload.md
Updated links with **absolute paths** for easy sync up to Databend Cloud documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12357)
> docs: update links

- tests/sqllogictests/suites/query/join.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12371)
> chore: modify a slt slightly

- src/query/sql/src/planner/optimizer/optimizer.rs
- tests/sqllogictests/suites/mode/cluster/distributed_copy_into_table2_execption.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12374)
> chore: disable flaky test

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- Closes #12393
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12402)
> chore: fix missing user builder for devcontainer

- src/binaries/metabench/main.rs
- src/meta/service/src/api/grpc/grpc_service.rs
- src/meta/service/src/meta_service/raftmeta.rs
- src/meta/sled-store/Cargo.toml
- src/meta/sled-store/src/sled_tree.rs
Other changes:
- add logging to append_to_log() and its callees
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12397)
> chore: databend-metabench: add logging

- .github/workflows/release.yml
- Closes #12429
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12432)
> chore: include meta for hdfs pkg in release [skip ci]

- .github/workflows/bindings_python.yml
- Cargo.lock
- Cargo.toml
- src/query/expression/Cargo.toml
- src/query/expression/src/utils/display.rs
- src/query/expression/src/values.rs
- src/query/formats/Cargo.toml
- src/query/formats/src/output_format/json.rs
- src/query/functions/Cargo.toml
- src/query/functions/src/aggregates/aggregate_bitmap.rs
- src/query/functions/src/scalars/bitmap.rs
- src/query/functions/tests/it/aggregates/agg.rs
- for #12131
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12440)
> chore: revert #12011

- src/query/service/src/databases/share/share_database.rs
- src/query/service/src/interpreters/common/grant.rs
- src/query/service/src/interpreters/interpreter_table_drop.rs
- src/query/service/src/interpreters/interpreter_table_set_options.rs
- src/query/service/src/interpreters/interpreter_view_create.rs
- src/query/service/src/interpreters/interpreter_view_drop.rs
- src/query/sql/src/planner/binder/project.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/storages/system/src/columns_table.rs
- tests/sqllogictests/suites/base/01_system/01_0006_system_columns
- tests/suites/0_stateless/20+_others/20_0013_pretty_error.result
- tests/suites/1_stateful/09_http_handler/09_0001_json_response.result
- tests/suites/3_stateful_sharing/01_sharing/01_0000_basic_sharing.result
- Closes #12441
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12442)
> chore(query): unknowtable errmsg add db name

- docs/doc/14-sql-commands/00-ddl/101-network-policy/ddl-create-policy.md
- docs/doc/14-sql-commands/00-ddl/101-network-policy/index.md
- docs/doc/14-sql-commands/00-ddl/102-mask-policy/index.md
Fixed comments
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12450)
> docs: network policy updates

- src/query/catalog/src/plan/agg_index.rs
- src/query/catalog/src/plan/internal_column.rs
- src/query/expression/src/block.rs
- src/query/expression/src/lib.rs
- src/query/pipeline/core/tests/it/pipelines/processors/port_test.rs
- src/query/pipeline/sources/src/input_formats/impls/input_format_parquet.rs
- src/query/pipeline/sources/src/input_formats/input_format_text.rs
- src/query/service/src/api/rpc/exchange/exchange_transform_shuffle.rs
- src/query/service/src/api/rpc/exchange/serde/exchange_deserializer.rs
- src/query/service/src/api/rpc/exchange/serde/exchange_serializer.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/aggregate_meta.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/serde_meta.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_exchange_group_by_serializer.rs
- src/query/storages/common/pruner/src/block_meta.rs
- src/query/storages/common/table-meta/src/meta/v2/segment.rs
- src/query/storages/fuse/src/operations/common/mutation_log.rs
- src/query/storages/fuse/src/operations/mutation/mutation_meta.rs
- src/query/storages/fuse/src/operations/read/native_data_source.rs
- src/query/storages/fuse/src/operations/read/parquet_data_source.rs
- src/query/storages/fuse/src/operations/replace_into/meta/merge_into_operation_meta.rs
- src/query/storages/parquet/src/processors/parquet_source.rs
- src/query/storages/stage/src/parquet_file/block_batch.rs
- src/query/storages/stage/src/row_based_file/buffers.rs
By reusing the code in std library.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12453)
> chore: remove unsafe code

- src/query/sql/src/planner/binder/location.rs
feat: Add obs stage support
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12455)
> feat: Add obs stage support

- src/meta/proto-conv/src/config_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/main.rs
- src/meta/proto-conv/tests/it/user_proto_conv.rs
- src/meta/proto-conv/tests/it/user_stage.rs
- src/meta/proto-conv/tests/it/v051_obs_and_cos_storage.rs
- src/meta/protos/proto/config.proto
feat: Support obs and cos storage config in metasrv
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12467)
> feat: Support obs and cos storage config in metasrv

- docs/doc/12-load-data/00-transform/05-querying-stage.md
- docs/doc/13-sql-reference/51-connect-parameters.md
- docs/doc/14-sql-commands/00-ddl/40-stage/01-ddl-create-stage.md
- docs/doc/14-sql-commands/10-dml/dml-copy-into-location.md
- docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
This PR extracts the connection parameters commonly used in these cmds or features:
- create stage
- copy into table / location
- query staged files.
- catalog mgt. (to be added)
This PR also removes the obs configurations mentioned in the list above.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12470)
> docs: connection parameters

- src/query/service/src/schedulers/fragments/plan_fragment.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12479)
> fix: data skew when replace into reshuffle segments

- docs/doc/10-deploy/00-understanding-deployment-modes.md
- docs/doc/10-deploy/02-deploying-databend.md
- docs/doc/10-deploy/06-metasrv/10-query-config.md
- scripts/distribution/configs/databend-query.toml
- website/blog/2023-02-24-Deploy-databend-on-minio.md
- website/blog/2023-03-04-databend-v1.0-release.md
Removed mentions of obs support from documentation.
Added GCS, OSS, COS, HDFS, WebHDFS to `databend-query.toml`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12484)
> chore: remove obs

- .github/actions/artifact_download/action.yml
- .github/actions/artifact_upload/action.yml
- .github/workflows/cloud.yml
- .github/workflows/dev.yml
- .github/workflows/production.yml
- .github/workflows/release.yml
- .github/workflows/reuse.benchmark.yml
- .github/workflows/reuse.linux.hive.yml
- .github/workflows/reuse.linux.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12485)
> chore(ci): make runner provider variable

- src/meta/app/src/principal/file_format.rs
- src/meta/proto-conv/src/file_format_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/main.rs
- src/meta/proto-conv/tests/it/v032_file_format_params.rs
- src/meta/proto-conv/tests/it/v053_csv_format_params.rs
- src/meta/protos/proto/file_format.proto
- src/query/ast/src/parser/stage.rs
- src/query/ast/src/parser/token.rs
- src/query/formats/src/field_decoder/csv.rs
- tests/sqllogictests/suites/base/05_ddl/05_0016_ddl_stage
- tests/suites/1_stateful/05_formats/05_02_csv/05_02_07_csv_null_display.result
- tests/suites/1_stateful/05_formats/05_02_csv/05_02_07_csv_null_display.sh
- Closes https://github.com/datafuselabs/databend/issues/12491
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12493)
> feat: support CSV file format option `null_display`.

- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12497)
> fix: runner provider for benchmark [skip ci]

- src/query/ast/src/ast/format/ast_format.rs
- src/query/ast/src/ast/statements/table.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
- src/query/service/src/interpreters/interpreter_table_modify_column.rs
- tests/suites/0_stateless/17_altertable/17_0005_alter_table_modify_column_type.result
- tests/suites/0_stateless/17_altertable/17_0005_alter_table_modify_column_type.sh
1. modify column type support default type
2. test cases
- Closes https://github.com/datafuselabs/databend/issues/12483
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12498)
> feat: modify column type support default type

- .github/actions/artifact_upload/action.yml
- .github/actions/setup_build_tool/action.yml
- .github/actions/test_unit/action.yml
- .github/backup/dev-macos.yml
- .github/workflows/cloud.yml
- .github/workflows/dev.yml
- .github/workflows/production.yml
- .github/workflows/release.yml
- .github/workflows/reuse.benchmark.yml
- .github/workflows/reuse.linux.yml
- scripts/ci/ci-run-stateful-tests-large-data-s3.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12499)
> chore(ci): switch to gcp runners

- .github/workflows/reuse.linux.yml
- scripts/ci/ci-run-sqllogic-tests-cluster.sh
- Closes #10466
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12503)
> chore(ci): use larger runner for unit test

- tests/sqllogictests/suites/base/11_data_type/11_0006_data_type_decimal
- Fix https://github.com/datafuselabs/databend/pull/12487#issuecomment-1683340458
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12502)
> fix(query): add sqllogic test

- src/query/sql/src/planner/optimizer/heuristic/subquery_rewriter.rs
- tests/sqllogictests/suites/query/subquery.test
Fix function call in subquery
- Closes #12495
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12508)
> fix: fix function call in subquery

- src/query/ee/tests/it/aggregating_index/index_scan.rs
- Reuse table data for every test suite in one turn.
- Refresh index block by `REFRESH` command.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12518)
> chore: refactor aggregating index fuzz test.

- src/query/storages/hive/hive/src/hive_catalog.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12517)
> feat: add show databases and tables for hive catalog

- src/query/service/src/sessions/query_ctx.rs
- Closes https://github.com/datafuselabs/databend/issues/12490
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12527)
> feat: copy filter files with path only.

- Cargo.lock
- Cargo.toml
- scripts/ci/ci-run-stateful-tests-large-data-s3.sh
- src/query/functions/src/scalars/variant.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/variant.txt
- src/query/functions/tests/it/scalars/variant.rs
Added json_pretty function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12511)
> feat: add json_pretty func

- src/query/sql/src/planner/semantic/aggregating_index_rewriter.rs
- src/query/sql/src/planner/semantic/mod.rs
- tests/sqllogictests/suites/ee/02_ee_aggregating_index/02_0000_agg_index_base
Reverts datafuselabs/databend#12542
- Close #issue
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12548)
> refactor: Revert "chore: allow empty group by for agg index"

- src/query/service/src/pipelines/executor/executor_condvar.rs
correlated issue:  #12541
analyze the log in https://github.com/datafuselabs/databend/actions/runs/5926787851/job/16069268754 deeply, we found the thread is finished before the async task update_meta_server finish.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12547)
> fix: fix memory barrier

- .github/workflows/bindings_python.yml
- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12550)
> chore(ci): fix download artifacts [skip ci]

- .github/workflows/bindings_python.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12556)
> fix(ci): typo on release

- .github/workflows/bindings_python.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12557)
> fix(ci): typo on workflow

- tests/fuse-compat/test-fuse-compat.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12560)
> chore: add backtrace to fuse-compat test

- src/query/service/src/interpreters/interpreter_table_modify_column.rs
- tests/suites/0_stateless/17_altertable/17_0005_alter_table_modify_column_type.result
- tests/suites/0_stateless/17_altertable/17_0005_alter_table_modify_column_type.sh
chore: fix modify column type default value bug
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12559)
> chore: fix modify column type default value bug

- .github/workflows/cloud.yml
- .github/workflows/release.yml
- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12570)
> chore(ci): run benchmark on aws [skip ci]

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/util.rs
- src/query/management/src/role/role_mgr.rs
- src/query/users/src/user_api.rs
- New Feature
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12574)
> refactor: make KVApi more generic with ?Sized

- website/src/components/CustomerVoiceCard/index.tsx
- website/src/pages/download/styles.module.scss
Some Styles
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12586)
> chore: styles

- src/query/storages/fuse/src/operations/read_partitions.rs
- tests/sqllogictests/suites/base/03_common/03_0025_delete_from
feature(cluster): adaptive lazy partition for cluster
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12589)
> feat(query): adaptive lazy partition for cluster

- .github/actions/build_bindings_python/action.yml
- .github/actions/fuse_compat/action.yml
- .github/actions/test_compat/action.yml
- .github/actions/test_fuzz_standalone_linux/action.yml
- .github/actions/test_meta_cluster/action.yml
- .github/actions/test_sqllogic_management_mode_linux/action.yml
- .github/actions/test_sqllogic_standalone_macos/action.yml
- .github/actions/test_stateful_large_data/action.yml
- .github/actions/test_stateless_cluster_linux/action.yml
- .github/actions/test_stateless_cluster_macos/action.yml
- .github/actions/test_stateless_standalone_linux/action.yml
- .github/actions/test_stateless_standalone_macos/action.yml
- .github/actions/test_unit/action.yml
- .github/workflows/bindings_python.yml
- .github/workflows/reuse.linux.yml
- src/query/config/src/config.rs
- src/query/service/tests/it/configs.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
- tests/fuse-compat/util.sh
`query_enabled` is not working as expected currently.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12588)
> fix(query): query details log config

- docs/doc/10-deploy/02-deploying-databend.md
- docs/doc/10-deploy/03-expanding-to-a-databend-cluster.md
- docs/doc/10-deploy/05-deploying-local.md
- docs/doc/10-deploy/06-metasrv/10-metasrv-deploy.md
- docs/doc/10-deploy/06-metasrv/11-deploying-databend-on-kubernetes.md
- docs/doc/12-load-data/_category_.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12593)
> docs: next steps

- Cargo.lock
- Cargo.toml
- src/query/functions/src/scalars/variant.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/variant.txt
- src/query/functions/tests/it/scalars/variant.rs
- tests/sqllogictests/suites/query/02_function/02_0065_function_json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12602)
> feat: add json_strip_nulls

- Cargo.lock
- Cargo.toml
- src/binaries/Cargo.toml
- src/binaries/metactl/snapshot.rs
- src/meta/raft-store/Cargo.toml
- src/meta/raft-store/src/applier.rs
- src/meta/raft-store/src/ondisk/mod.rs
- src/meta/raft-store/src/sm_v002/leveled_store/level.rs
- src/meta/raft-store/src/sm_v002/leveled_store/level_data.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_store_test.rs
- src/meta/raft-store/src/sm_v002/leveled_store/map_api.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/sm_v002_test.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002_test.rs
- src/meta/raft-store/src/sm_v002/writer_v002.rs
- src/meta/service/src/store/store.rs
- src/meta/service/src/store/store_inner.rs
- src/meta/service/tests/it/meta_node/meta_node_replication.rs
- src/meta/service/tests/it/store.rs
- src/query/ee/Cargo.toml
- src/query/pipeline/sources/Cargo.toml
- src/query/service/Cargo.toml
- src/query/storages/common/table-meta/Cargo.toml
- src/query/storages/fuse/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12620)
> chore: make state machine methods async in order to adapt disk based snapshot in future

- tests/sqllogictests/suites/base/09_fuse_engine/09_0026_merge_into
close issue: https://github.com/datafuselabs/databend/issues/12616
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12617)
> fix: fix flaky test

- src/query/catalog/src/table.rs
- src/query/service/src/api/mod.rs
- src/query/service/src/api/rpc/flight_actions.rs
- src/query/service/src/api/rpc/flight_service.rs
- src/query/service/src/api/rpc/mod.rs
- src/query/service/src/api/rpc/packets/mod.rs
- src/query/service/src/api/rpc/packets/packet_truncate_table.rs
- src/query/service/src/interpreters/interpreter_table_truncate.rs
- src/query/storages/system/src/metrics_table.rs
- src/query/storages/system/src/table.rs
feat(cluster): implement truncate metrics for cluster
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12618)
> feat(cluster): implement truncate metrics for cluster

- docs/doc/10-deploy/10-node-config/02-query-config.md
added the [log.query] configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12624)
> docs: logging query details

- docs/doc/03-develop/03-jdbc.md
update jdbc to 0.1.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12623)
> docs: Update 03-jdbc.md

- Cargo.lock
- Cargo.toml
- tests/sqllogictests/suites/base/03_common/03_0026_insert_into_tuple
Fix nested decimal insert and select. cc @wubx 
- Closes #12591
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12627)
> fix: fix nested decimal insert and select

- Cargo.lock
- Cargo.toml
- src/query/functions/src/scalars/variant.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/variant.txt
- src/query/functions/tests/it/scalars/variant.rs
- tests/sqllogictests/suites/query/02_function/02_0065_function_json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12633)
> feat: added json_typeof

- Cargo.lock
- Cargo.toml
- src/common/building/Cargo.toml
- src/query/ast/src/ast/statements/table.rs
- src/tests/sqlsmith/Cargo.toml
- src/tests/sqlsmith/src/bin/main.rs
- src/tests/sqlsmith/src/lib.rs
- src/tests/sqlsmith/src/runner.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
- src/tests/sqlsmith/src/sql_gen/mod.rs
- src/tests/sqlsmith/src/sql_gen/query.rs
- src/tests/sqlsmith/src/sql_gen/sql_generator.rs
Initial implementation of SQLSmith with support for creating a test table and generating simple query statements.
part of #12576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12630)
> feat: Add sqlsmith tests for databend

- docs/doc/10-deploy/10-node-config/03-environment-variables.md
- docs/doc/14-sql-commands/00-ddl/40-stage/04-ddl-list-stage.md
- docs/doc/14-sql-commands/00-ddl/40-stage/05-ddl-remove-stage.md
- docs/doc/14-sql-commands/00-ddl/80-presign/presign.md
- added METASRV_CONFIG_FILE and CONFIG_FILE
- fixed comments
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12636)
> docs: Environment Variables updates

- src/query/ast/src/parser/query.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement-error.txt
- src/query/service/src/pipelines/pipeline_builder.rs
- src/query/service/src/pipelines/processors/transforms/transform_limit.rs
- tests/sqllogictests/suites/query/select.test
- Closes #12639
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12640)
> fix(query): check limit vec length

- src/tests/sqlsmith/src/runner.rs
- src/tests/sqlsmith/src/sql_gen/query.rs
- gen limit, part of #12576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12641)
> feat(sqlsmith): add limit test

- Cargo.lock
- src/query/ast/src/parser/statement.rs
- src/query/functions/src/scalars/arithmetic.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12646)
> chore: remove unnecessary condition for -u64

- Cargo.lock
- src/meta/service/Cargo.toml
- src/meta/service/src/metrics/meta_metrics.rs
- src/meta/service/src/metrics/mod.rs
- src/meta/service/src/metrics/registry.rs
- src/meta/service/tests/it/api/http/metrics.rs
- Closes #12648
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12650)
> refactor(meta): switch to the official prometheus client in metasrv

- src/query/service/src/interpreters/access/accessor.rs
- src/query/service/src/interpreters/access/management_mode_access.rs
- src/query/service/src/interpreters/access/privilege_access.rs
- src/query/sql/src/planner/binder/table.rs
- tests/sqllogictests/suites/management/management_calls
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12662)
> feat(query): under management mode no need to provide table statistics

- src/query/service/src/api/rpc/exchange/exchange_sink_writer.rs
- src/query/service/src/api/rpc/exchange/exchange_source_reader.rs
- src/query/service/src/api/rpc/exchange/metrics/exchange_metrics.rs
- src/query/service/src/api/rpc/exchange/metrics/mod.rs
- src/query/service/src/api/rpc/exchange/mod.rs
- src/query/service/src/api/rpc/packets/packet_data.rs
chore(cluster): add exchange read and write metrics
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12666)
> chore(cluster): add exchange read and write metrics

- src/query/service/src/local/display.rs
- src/query/service/src/local/executor.rs
- src/query/service/src/local/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12668)
> fix(query): fix display rows of bend-local

- tests/suites/1_stateful/07_stage_attachment/07_0000_insert_with_stage.result
- tests/suites/1_stateful/07_stage_attachment/07_0000_insert_with_stage.sh
- Closes https://github.com/datafuselabs/databend/issues/12673
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12674)
> ci: longer timeout to fix testing insert with stage.

- src/query/ast/src/ast/ast.rs
- src/query/ast/src/ast/expr.rs
- src/query/ast/src/ast/format/ast_format.rs
- src/query/ast/src/ast/format/syntax/expr.rs
- src/query/ast/src/ast/query.rs
- src/query/ast/src/ast/statements/database.rs
- src/query/ast/src/ast/statements/insert.rs
- src/query/ast/src/ast/statements/merge_into.rs
- src/query/ast/src/ast/statements/replace.rs
- src/query/ast/src/ast/statements/table.rs
- src/query/ast/src/ast/statements/view.rs
- src/query/ast/src/ast/statements/virtual_column.rs
- src/query/ast/src/parser/expr.rs
- src/query/ast/src/parser/query.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/src/util.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/expr.txt
- src/query/ast/tests/it/testdata/statement-error.txt
- src/query/ast/tests/it/testdata/statement.txt
- src/query/functions/tests/it/scalars/parser.rs
- src/query/sql/src/planner/binder/ddl/virtual_column.rs
- src/query/sql/src/planner/semantic/type_check.rs
- Close #issue
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12677)
> fix(ast): deny ambiguous column type: Nullable(int) NOT NULL

- src/query/functions/src/scalars/variant.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/variant.txt
- src/query/functions/tests/it/scalars/variant.rs
- tests/sqllogictests/suites/query/02_function/02_0065_function_json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12665)
> feat: added json_array

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12681)
> chore: fix release workflow [skip ci]

- .github/backup/backport.yml
- .github/backup/dev-macos.yml
- .github/workflows/bindings.python.yml
- .github/workflows/build_tool.yml
- .github/workflows/cloud.yml
- .github/workflows/i18n.yml
- .github/workflows/release.yml
- .github/workflows/reuse.benchmark.yml
- .github/workflows/reuse.linux.hive.yml
- .github/workflows/reuse.linux.yml
- .github/workflows/reuse.macos.yml
- .github/workflows/typos.yml
- website/blog/2023-06-11-databend-weekly-97.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12690)
> chore(ci): upgrade to actions/checkout@v4 [skip ci]

- Cargo.lock
- src/tests/sqlsmith/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12692)
> chore: update databend-driver to 0.6.4

- .cargo/config.toml
- .github/actions/build_macos/action.yml
- src/query/service/src/local/executor.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12709)
> fix(query): inject JEMALLOC_SYS_WITH_MALLOC_CONF in building darwin

- src/query/functions/src/aggregates/adaptors/aggregate_null_variadic_adaptor.rs
- tests/sqllogictests/suites/query/window_function/named_window_basic.test
- tests/sqllogictests/suites/query/window_function/window_basic.test
fix null variadic adaptor accumulate row with nullable columns.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12715)
> fix: fix null variadic adaptor accumulate row with nullable columns

- src/query/sql/src/planner/optimizer/rule/rewrite/rule_normalize_disjunctive_filter.rs
- tests/sqllogictests/suites/mode/standalone/explain/filter.test
- tests/sqllogictests/suites/mode/standalone/explain_native/filter.test
- Closes #12745
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12749)
> chore: refine `NormalizeDisjunctiveFilter`

- src/query/expression/src/values.rs
- src/tests/sqlsmith/src/runner.rs
- src/tests/sqlsmith/src/sql_gen/ddl.rs
- src/tests/sqlsmith/src/sql_gen/dml.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
- src/tests/sqlsmith/src/sql_gen/mod.rs
- src/tests/sqlsmith/src/sql_gen/query.rs
- src/tests/sqlsmith/src/sql_gen/sql_generator.rs
- Decimal data type generates random values
- Support generate join query
part of #12576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12769)
> feat(sqlsmith): Support generate join query

- src/query/pipeline/core/src/lib.rs
- src/query/pipeline/core/src/pipeline.rs
- src/query/service/src/pipelines/pipeline_builder.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/aggregate_exchange_injector.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_state.rs
chore(query): unified spill location prefix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12775)
> chore(query): unified spill location prefix

- src/query/ee/src/background_service/background_service_handler.rs
- src/query/ee/src/background_service/compaction_job.rs
- src/query/ee/src/background_service/session.rs
- tests/suites/6_background/00_target_tables/00_0000_target_tables.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12776)
> chore: resolve session leak in background service

- src/query/ast/src/parser/token.rs
- tests/sqllogictests/suites/stage/options/path
- Closes https://github.com/datafuselabs/databend/issues/12774
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12781)
> fix: not allow '('/')' in stage at_string.

- src/query/catalog/tests/it/testdata/partition-reshuffle.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12788)
> fix:  test case

- tests/sqllogictests/suites/mode/cluster/distributed_copy_into_table2.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12799)
> fix: fix test

- src/query/service/tests/it/storages/fuse/operations/mutation/recluster_mutator.rs
- src/query/storages/fuse/src/operations/mutation/recluster_mutator.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0008_fuse_optimize_table
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12789)
> chore: add test case and flaky test

- src/query/service/src/table_functions/others/suggested_background_tasks.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12801)
> chore: fix naming in call procedure

- src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/left_semi_join.rs
- tests/sqllogictests/suites/query/select.test
- Closes #12795 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12803)
> chore: fix right anti join

- src/query/expression/src/kernels/group_by_hash.rs
- src/query/service/src/local/display.rs
- tests/sqllogictests/suites/base/03_common/03_0003_select_group_by
- Closes #12785 #12794
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12797)
> fix(query): fix null column in group by

- docs/doc/12-load-data/00-transform/05-querying-stage.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12815)
> fix: fix syntax of Querying Staged Files.

- docs/doc/21-use-cases/01-analyze-ontime-with-databend-on-ec2-and-s3.md
fix Ontime DDL link in [this page ](https://databend.rs/doc/use-cases/analyze-ontime-with-databend-on-ec2-and-s3)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12836)
> docs: fix Ontime DDL hyperlink

- src/query/ast/src/ast/query.rs
- src/query/ast/src/parser/query.rs
- src/query/ast/tests/it/testdata/statement.txt
- tests/sqllogictests/suites/stage_parquet/options/select_options
- Closes #12735
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12838)
> feat: allow `select $1 from @s1 ()`

- src/query/ast/src/lib.rs
- src/query/ast/src/visitors/visitor_mut.rs
- src/query/sql/src/planner/binder/ddl/view.rs
- src/query/sql/src/planner/planner.rs
- src/query/sql/src/planner/semantic/mod.rs
- src/query/sql/src/planner/semantic/view_rewriter.rs
- tests/sqllogictests/suites/base/05_ddl/05_0021_ddl_alter_view
- tests/sqllogictests/suites/base/06_show/06_0001_show_create_table
rewrite view query that table_ref with None database
- Closes https://github.com/datafuselabs/databend/issues/12832
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12840)
> fix(query): rewrite view query when table_ref with None database

- src/query/ast/src/ast/expr.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
- src/tests/sqlsmith/src/sql_gen/func.rs
- src/tests/sqlsmith/src/sql_gen/mod.rs
- src/tests/sqlsmith/src/sql_gen/sql_generator.rs
- src/tests/sqlsmith/src/sql_gen/types.rs
- Support generating some factory scalar functions
- Support generating some aggregate functions
- Support generating some Exprs
Part of #12576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12844)
> feat(sqlsmith): Support generating factory scalar functions

- src/meta/service/src/configs/outer_v0.rs
- src/query/config/src/config.rs
- src/query/service/tests/it/configs.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12846)
> fix: allow setting log-xx-on to false

- src/query/sql/src/planner/optimizer/rule/rewrite/rule_infer_filter.rs
- src/query/sql/src/planner/plans/scalar_expr.rs
- src/query/sql/src/planner/semantic/lowering.rs
- tests/sqllogictests/suites/mode/standalone/explain/infer_filter.test
- tests/sqllogictests/suites/mode/standalone/explain_native/infer_filter.test
`[A > 10 and A = B]` => `[B > 10]`
`[A = B and B = C and A > 5 and C < 10]` => `[A > 5 and A < 10 and B > 5 and B < 10 and C > 5 and C < 10]`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12845)
> feat(planner): improve infer predicates

- Cargo.lock
- src/query/ast/src/ast/expr.rs
- src/query/functions/src/scalars/array.rs
- src/tests/sqlsmith/Cargo.toml
- src/tests/sqlsmith/src/runner.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
- src/tests/sqlsmith/src/sql_gen/func.rs
- src/tests/sqlsmith/src/sql_gen/query.rs
- src/tests/sqlsmith/src/sql_gen/sql_generator.rs
- src/tests/sqlsmith/src/sql_gen/types.rs
- Ignore reports of some known errors
- remove `INTERVAL` from `DATE_ADD` and `DATE_SUB` display
- `array_sort` return error for unsupported data types, avoiding panic
- fix some incorrectly generated SQL
Part of #12576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12858)
> feat(sqlsmith): Ignore reports of some known errors

- Cargo.lock
- src/common/storage/Cargo.toml
- src/common/storage/src/copy.rs
- src/common/storage/src/lib.rs
- src/query/pipeline/sources/src/input_formats/error_utils.rs
- src/query/pipeline/sources/src/input_formats/impls/input_format_csv.rs
- src/query/pipeline/sources/src/input_formats/impls/input_format_ndjson.rs
- src/query/pipeline/sources/src/input_formats/impls/input_format_tsv.rs
- src/query/pipeline/sources/src/input_formats/impls/input_format_xml.rs
- src/query/pipeline/sources/src/input_formats/input_context.rs
- src/query/pipeline/sources/src/input_formats/mod.rs
- src/query/pipeline/sources/src/lib.rs
- src/query/service/src/interpreters/interpreter_copy.rs
- tests/sqllogictests/suites/stage/formats/csv/csv_delimiter
- tests/sqllogictests/suites/stage/formats/csv/csv_on_error
- tests/sqllogictests/suites/stage/formats/csv/csv_types
- tests/sqllogictests/suites/stage/formats/ndjson/ndjson_on_error
- tests/sqllogictests/suites/stage/formats/tsv/tsv_on_error
- tests/sqllogictests/suites/stage/formats/xml/xml_on_error
- tests/sqllogictests/suites/stage/options/table_columns
- tests/suites/0_stateless/14_clickhouse_http_handler/14_0007_http_clickhouse_input_format_diagnostic.sh
- tests/suites/1_stateful/00_stage/00_0011_distributed_copy_into_table_exection_test.result
- tests/suites/1_stateful/00_stage/00_0011_distributed_copy_into_table_exection_test.sh
- Closes https://github.com/datafuselabs/databend/issues/12864
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12872)
> refactor: improve error message of copy.

- src/meta/api/src/schema_api_test_suite.rs
- Bug Fix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12875)
> fix: remove the db before testing dropping table

- src/query/service/tests/it/interpreters/union.rs
Reduce running time of `test_union_output_type` from 14 min to 5 min
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12869)
> refactor: get rid of duplicated task in union tests

- src/query/sql/src/planner/optimizer/rule/rewrite/rule_normalize_scalar.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
- src/query/sql/src/planner/optimizer/rule/utils/constant.rs
- tests/sqllogictests/suites/mode/standalone/explain/infer_filter.test
- tests/sqllogictests/suites/mode/standalone/explain_native/infer_filter.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12876)
> chore: push down false to both side of join

- src/query/ast/src/parser/expr.rs
- src/query/ast/src/parser/query.rs
- src/query/ast/src/parser/stage.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/testdata/statement-error.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12898)
> fix(parser): show more parser context

- src/bendpy/src/dataframe.rs
- src/common/http/src/http_shutdown_handlers.rs
1. shutdown http server with timeout  https://github.com/poem-web/poem/issues/661
2. export error in bendpy
- Closes #12857
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12903)
> chore(query): shutdown http server with timeout

- src/query/ast/src/ast/expr.rs
- src/query/ast/src/ast/format/ast_format.rs
- src/query/ast/src/ast/format/syntax/expr.rs
- src/query/ast/src/parser/expr.rs
- src/query/ast/src/visitors/visitor.rs
- src/query/ast/src/visitors/visitor_mut.rs
- src/query/ast/tests/it/testdata/expr.txt
- src/query/functions/tests/it/scalars/parser.rs
- src/query/sql/src/planner/semantic/type_check.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
- tests/sqllogictests/suites/base/03_common/03_0037_insert_into_map
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12912)
> fix(parser): allow expr in map liteal

- src/tests/sqlsmith/src/runner.rs
- src/tests/sqlsmith/src/sql_gen/func.rs
- src/tests/sqlsmith/src/sql_gen/types.rs
- Part of  #12576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12907)
> feat(sqlsmith): add other agg func

- src/tests/sqlsmith/src/runner.rs
- src/tests/sqlsmith/src/sql_gen/ddl.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
- src/tests/sqlsmith/src/sql_gen/func.rs
- src/tests/sqlsmith/src/sql_gen/query.rs
expressions
Support generates all factory scalar functions and expressions
part of #12576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12921)
> feat(sqlsmith): Support generates all factory scalar functions and expressions

- src/query/service/src/api/mod.rs
- src/query/service/src/api/rpc/flight_actions.rs
- src/query/service/src/api/rpc/flight_service.rs
- src/query/service/src/api/rpc/mod.rs
- src/query/service/src/api/rpc/packets/mod.rs
- src/query/service/src/api/rpc/packets/packet_kill_query.rs
- src/query/service/src/interpreters/interpreter_kill.rs
- src/query/storages/system/src/processes_table.rs
- chore(query): support cluster level process list
- chore(query): support cluster level kill query
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12927)
> chore(query): support cluster level process list

- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/window_function/window_basic.test
disallow scalar function with window
- Closes #12914
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12925)
> fix: fix disallow scalar function with window

- src/query/sql/src/planner/binder/select.rs
- tests/sqllogictests/suites/base/03_common/03_0005_select_filter
- tests/udf-server/README.md
- tests/udf-server/udf.py
- tests/udf-server/udf_test.py
- Closes  #12919   #12923
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12932)
> chore(query): add license for udf example codes

- src/query/expression/src/values.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/02_function/02_0061_function_array
fix array_distinct with nested array
- Closes #12720
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12917)
> fix: fix array_distinct with nested array

- src/query/service/src/table_functions/srf/range.rs
- src/tests/sqlsmith/src/runner.rs
- src/tests/sqlsmith/src/sql_gen/func.rs
- src/tests/sqlsmith/src/sql_gen/query.rs
- Part of https://github.com/datafuselabs/databend/issues/12576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12942)
> feat(sqlsmith): add table function

- src/query/service/src/servers/http/v1/query/http_query.rs
related bendsql fix https://github.com/datafuselabs/bendsql/pull/230
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12947)
> fix: add session info in final response.

- docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
- docs/doc/15-sql-functions/112-table-functions/list_stage.md
related pr https://github.com/datafuselabs/databend/pull/12935
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12951)
> docs: note about pattern in copy.

- src/query/functions/src/scalars/vector.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
- src/tests/sqlsmith/src/sql_gen/query.rs
- src/tests/sqlsmith/src/sql_gen/sql_generator.rs
- Support generate subquery and with clause
- Check `openai_api_key` for ai functions
Part of #12576
Closes #12719
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12956)
> feat(sqlsmith): Support generate subquery and with clause

- src/query/expression/src/types/decimal.rs
- src/query/functions/src/scalars/arithmetic.rs
- src/query/functions/src/scalars/decimal.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- tests/sqllogictests/suites/base/11_data_type/11_0006_data_type_decimal
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12967)
> feat(query): support decimal to int

- src/query/storages/fuse/src/operations/merge_into/processors/processor_merge_into_not_matched.rs
remove debug print
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12974)
> chore: remove debug print

- src/query/service/src/sessions/session_mgr.rs
fix(query): fix session manager dead lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12982)
> fix(query): fix session manager dead lock

- src/query/service/src/sessions/session_mgr.rs
chore(query): add comment for session destroy
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12984)
> chore(query): add comment for session destroy

- src/meta/app/src/principal/file_format.rs
- src/meta/proto-conv/src/file_format_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/main.rs
- src/meta/proto-conv/tests/it/v032_file_format_params.rs
- src/meta/proto-conv/tests/it/v059_csv_format_params.rs
- src/meta/protos/proto/file_format.proto
- src/query/ast/src/parser/stage.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement-error.txt
- src/query/ast/tests/it/testdata/statement.txt
- src/query/pipeline/sources/src/input_formats/impls/input_format_csv.rs
- tests/sqllogictests/suites/base/05_ddl/05_0016_ddl_stage
- tests/sqllogictests/suites/stage/formats/csv/csv_option_mismatch
- Closes https://github.com/datafuselabs/databend/issues/12976
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12990)
> feat: csv add option error_on_column_count_mismatch.

- src/query/sql/src/planner/binder/having.rs
- src/query/sql/src/planner/binder/select.rs
- src/query/sql/src/planner/binder/sort.rs
- tests/sqllogictests/suites/base/03_common/03_0004_select_order_by
- tests/sqllogictests/suites/base/03_common/03_0006_select_having
- tests/sqllogictests/suites/query/aggregate.test
- check the sort clause has an aggregate function
- check the having clause can't have a window function
Closes #12963
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13007)
> fix(query): fix sort and having has aggregate and window functions

- src/query/service/src/pipelines/pipeline_builder.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_coordinator.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/row.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12994)
> chore: refactor RowSpace and replace lock with atomic

- docs/doc/14-sql-commands/00-ddl/20-table/60-optimize-table.md
- docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
- docs/doc/14-sql-commands/10-dml/dml-replace.md
added description for the following settings related to distributed execution:
- enable_distributed_replace_into 
- enable_distributed_compact      
- enable_distributed_copy_into: https://databend.rs/doc/sql-commands/dml/dml-copy-into-table#distributed-copy-into
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13016)
> docs: distributed execution settings

- src/query/sql/src/planner/binder/select.rs
- tests/sqllogictests/suites/query/cte.test
- Closes https://github.com/datafuselabs/databend/issues/12962
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13037)
> fix: cte name with uppercase letters

- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/window_function/named_window_basic.test
- tests/sqllogictests/suites/query/window_function/window_basic.test
fix: srfs cannot be used in window function.
- Closes #13024
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13034)
> fix: fix window spec check

- src/query/sql/src/planner/binder/distinct.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/base/03_common/03_0022_select_distinct
- tests/sqllogictests/suites/base/03_common/03_0026_insert_into_tuple
fix get field with float value
fix distinct with window function
- Closes #13029
- Closes #13038
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13041)
> fix(query): fix get field with float value

- src/query/sql/src/planner/binder/binder.rs
- tests/sqllogictests/suites/query/materialized_cte.test
- Closes  https://github.com/datafuselabs/databend/issues/12958
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13046)
> fix: materialized cte is defined but not be used

- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/ee/01_ee_system/01_0002_virtual_column
fix get derived column as a virtual column
- Closes #13065
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13066)
> fix(query): fix get derived column as virtual column

- Cargo.lock
- src/common/compress/src/encode.rs
- src/common/compress/src/lib.rs
- src/query/storages/stage/Cargo.toml
- src/query/storages/stage/src/parquet_file/sink_processor.rs
- src/query/storages/stage/src/row_based_file/pipeline.rs
- src/query/storages/stage/src/row_based_file/sink_processor.rs
- src/query/storages/stage/src/stage_table.rs
- tests/sqllogictests/suites/stage/unload
see the new test file for example.
for efficiency if `max_file_size` is provided too, it now limits the size before compression.
I will try to improve this later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13067)
> feat: copy into location support compression.

- src/query/service/tests/it/sql/planner/format/mod.rs
- src/query/sql/src/planner/binder/delete.rs
- src/query/sql/src/planner/binder/having.rs
- src/query/sql/src/planner/binder/join.rs
- src/query/sql/src/planner/binder/select.rs
- src/query/sql/src/planner/format/display_plan.rs
- src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs
- src/query/sql/src/planner/optimizer/heuristic/subquery_rewriter.rs
- src/query/sql/src/planner/optimizer/hyper_dp/dphyp.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/derive_filter.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_eliminate_filter.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_infer_filter.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_merge_filter.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_normalize_disjunctive_filter.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_aggregate.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_eval_scalar.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_project_set.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_union.rs
- src/query/sql/src/planner/plans/filter.rs
- tests/sqllogictests/suites/mode/standalone/explain/prune_column.test
- tests/sqllogictests/suites/mode/standalone/explain/push_down_filter.test
- tests/sqllogictests/suites/mode/standalone/explain_native/prune_column.test
- tests/sqllogictests/suites/mode/standalone/explain_native/push_down_filter.test
Continue https://github.com/datafuselabs/databend/pull/13070, push down `t.id = 1` through `Aggregate`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13071)
> chore(planner): improve push down filter aggregate

- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_mut.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13084)
> chore: simplify names

- src/meta/client/src/grpc_client.rs
- src/meta/client/src/message.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13087)
> refactor: add local request-id to grpc-request

- src/meta/service/src/store/store_inner.rs
- src/meta/stoerr/src/meta_storage_errors.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13090)
> chore: simplify error handling in export()

- .github/workflows/bindings.python.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13093)
> chore(ci): maximize build space for python binding

- src/common/storage/src/metrics/merge_into.rs
- src/query/storages/fuse/src/operations/merge_into/mutator/matched_mutator.rs
- src/query/storages/fuse/src/operations/merge_into/processors/mod.rs
- src/query/storages/fuse/src/operations/merge_into/processors/processor_merge_into_matched_and_split.rs
- src/query/storages/fuse/src/operations/merge_into/processors/processor_merge_into_not_matched.rs
- src/query/storages/fuse/src/operations/merge_into/processors/processor_merge_into_split.rs
1. add deleted_blocks counter
2. add time recorder for merge_into_split, not_macthed_operation,matched_operation, accumulate, apply, 5 phases in all.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13098)
> chore: add more metrics for merge into

- .github/workflows/cloud.yml
- .github/workflows/reuse.linux.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13113)
> chore(ci): update build timeout to 60min

- src/query/storages/parquet/src/parquet_rs/parquet_reader/read_policy/predicate_and_topk.rs
- src/query/storages/parquet/src/parquet_rs/parquet_reader/read_policy/topk_only.rs
We prefetch columns for evaluating topk and predicates. However, not every prefetched column will be output. We should drop them after the evaluation and keep the columns need to be output (to reduce unnecessary memory consumption). 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13105)
> chore: drop useless prefetched columns at once.

- scripts/setup/dev_setup.sh
- scripts/setup/rust-tools.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13117)
> chore: use cargo quickinstall for check tools

- docs/doc/14-sql-commands/10-dml/dml-delete-from.md
- docs/doc/14-sql-commands/10-dml/dml-insert.md
- docs/doc/14-sql-commands/10-dml/dml-replace.md
* make some DML title more short
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13119)
> docs: update dml to short

- docs/doc/03-develop/04-rust.md
bump to newest rust driver
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13132)
> docs: update rust example

- .github/workflows/release.yml
- .github/workflows/reuse.linux.hive.yml
- .github/workflows/reuse.linux.yml
* change release timeout-minutes from 30 to 60
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13135)
> chore: fix release build timeout

- src/query/ast/tests/it/testdata/statement.txt
fix
`test parser::test_statement ... FAILED`
https://github.com/datafuselabs/databend/actions/runs/6447538059/job/17503910552
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13137)
> fix: update golden file

- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/storages/system/src/tables_table.rs
- src/tests/sqlsmith/src/reducer.rs
- src/tests/sqlsmith/src/sql_gen/query.rs
- tests/sqllogictests/suites/base/06_show/06_0008_show_table_status
- tests/sqllogictests/suites/base/12_time_travel/12_0001_system_tables_with_dropped_on
- tests/sqllogictests/suites/base/20+_others/20_0000_describe_table
- tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.result
- tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.result_filter
- Closes #13155
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13149)
> refactor(query): tables created_on and dropped_on modify to ts type

- src/meta/service/src/api/grpc/grpc_service.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13166)
> chore: move meta-service impl out of trait implementation

- .github/workflows/dev.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/reuse.linux.yml
- src/query/ee/tests/it/aggregating_index/index_refresh.rs
- src/query/ee/tests/it/aggregating_index/index_scan.rs
- src/query/functions/tests/it/scalars/mod.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13182)
> chore(ci): add job ready for merge check

- src/query/service/src/interpreters/interpreter_factory.rs
- src/query/service/src/interpreters/interpreter_replace.rs
- src/query/sql/src/planner/binder/copy_into_table.rs
- src/query/sql/src/planner/plans/plan.rs
my own mistake in  https://github.com/datafuselabs/databend/pull/13170, forgot to covert to draft or  leave a comment first,  merged while I`m fixing it.
- Closes https://github.com/datafuselabs/databend/issues/13175
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13183)
> fix: CopyIntoTablePlan should in Box.

- .github/workflows/pr.yml
- .github/workflows/reuse.linux.yml
- scripts/setup/rust-tools.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13186)
> chore(ci): fix pr check for merge group

- .github/workflows/bindings.python.yml
- .github/workflows/dev.yml
- .github/workflows/docs.yml
- README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13189)
> chore(ci): add ready check for docs

- docs/doc/15-sql-functions/30-datetime-functions/toweekofyear.md
added func TO_WEEK_OF_YEAR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13195)
> docs: TO_WEEK_OF_YEAR

- .github/workflows/reuse.linux.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13204)
> chore: enable cluster tpch test

- src/query/service/src/interpreters/common/query_log.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/execute_state.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/sessions/mod.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/src/sessions/query_ctx_shared.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13209)
> refactor: http handler returns the same duration as query_log.

- docs/doc/15-sql-functions/11-conditional-functions/index.md
added LEAST and GREATEST functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13220)
> docs: LEAST and GREATEST functions

- tests/sqllogictests/suites/query/spill.test
Disable spill test temporarily
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13224)
> chore: disable spill test

- .github/actions/build_bindings_python/action.yml
- .github/workflows/bindings.python.yml
- .github/workflows/dev.yml
- scripts/setup/dev_setup.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13225)
> chore(ci): build python binding with self hosted runner

- .github/actions/setup_bendsql/action.yml
- scripts/setup/dev_setup.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13226)
> chore(ci): fix build tool binstall arg

- .github/workflows/bindings.python.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13230)
> chore(ci): fix publishing python binding to pypi

- src/query/service/src/pipelines/processors/transforms/range_join/range_join_state.rs
Spit `right_table`, and make tasks number close to thread number. ~5x 
TPCH SF 0.01
Before
```
mysql> select count() from lineitem join orders on l_orderkey > o_orderkey and l_partkey < o_custkey;
+-----------+
| count()   |
+-----------+
| 169757135 |
+-----------+
1 row in set (7.55 sec)
Read 75175 rows, 1.15 MiB in 7.526 sec., 9.99 thousand rows/sec., 156.08 KiB/sec.
```
Now
```
mysql> select count() from lineitem join orders on l_orderkey > o_orderkey and l_partkey < o_custkey;
+-----------+
| count()   |
+-----------+
| 169757135 |
+-----------+
1 row in set (1.63 sec)
Read 75175 rows, 1.15 MiB in 1.601 sec., 46.96 thousand rows/sec., 733.67 KiB/sec.
```
- - -
This change …
> feat: speed up iejoin

- src/tests/sqlsmith/src/runner.rs
- src/tests/sqlsmith/src/sql_gen/ddl.rs
- src/tests/sqlsmith/src/sql_gen/dml.rs
add alter table sql smith impl.
- Closes https://github.com/datafuselabs/databend/issues/13050
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13231)
> feat: add alter table sql smith impl

- src/query/expression/src/evaluator.rs
- src/query/expression/src/expression.rs
- src/query/expression/src/function.rs
- src/query/expression/src/lib.rs
- src/query/service/src/interpreters/interpreter_index_refresh.rs
- src/query/service/src/pipelines/pipeline_builder.rs
- src/query/sql/src/evaluator/block_operator.rs
- src/query/sql/src/evaluator/cse.rs
- src/query/sql/src/evaluator/mod.rs
- src/query/sql/tests/block_operator.rs
- src/query/storages/fuse/src/operations/append.rs
- src/query/storages/fuse/src/operations/read_data.rs
- src/query/storages/fuse/src/operations/recluster.rs
Reverts datafuselabs/databend#13104
Performance degression by hashmap.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13248)
> chore: Revert "refactor: refactor apply_cse by using cached expr"

- docs/doc/15-sql-functions/30-datetime-functions/date_part.md
- docs/doc/15-sql-functions/30-datetime-functions/extract.md
- docs/doc/15-sql-functions/30-datetime-functions/toquarter.md
added datetime functions: **date_part**, **extract**, and **to_quarter**.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13252)
> docs: datetime functions

- src/query/service/src/interpreters/interpreter_merge_into.rs
compact should be behind the merge into lock release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13247)
> fix: fix compact lock

- src/tests/sqlsmith/src/runner.rs
- src/tests/sqlsmith/src/sql_gen/dml.rs
- Part of #12576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13243)
> feat(sqlsmith): support delete and update

- .github/workflows/bindings.python.yml
- .github/workflows/cloud.yml
- .github/workflows/release.yml
- .github/workflows/reuse.benchmark.yml
- benchmark/clickbench/benchmark_cloud.sh
- benchmark/clickbench/benchmark_local.sh
- benchmark/clickbench/benchmark_local_merge_into.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13249)
> chore: change benchmark result to server time

- src/query/expression/src/kernels/group_by_hash/method.rs
- src/query/expression/src/kernels/group_by_hash/method_dict_serializer.rs
- src/query/expression/src/kernels/group_by_hash/method_fixed_keys.rs
- src/query/expression/src/kernels/group_by_hash/method_serializer.rs
- src/query/expression/src/kernels/group_by_hash/method_single_string.rs
- src/query/expression/src/kernels/group_by_hash/mod.rs
- src/query/expression/src/kernels/group_by_hash/utils.rs
Restructure mod `group_by_hash`, split each method to separate file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13260)
> chore: restructure mod `group_by_hash`.

- src/query/expression/src/kernels/concat.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13263)
> chore: refine concat

- docs/doc/13-sql-reference/40-sql-identifiers.md
- docs/doc/15-sql-functions/30-datetime-functions/date_part.md
- docs/doc/15-sql-functions/30-datetime-functions/extract.md
- refactored sql identifiers about casing rules. 
- added DOW and DOY parameters to the EXTRACT and DATE_PART functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13273)
> docs: sql identifiers updates

- src/meta/client/src/grpc_client.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13268)
> chore: using loop to impl retry for meta-grpc client kv_api()

- src/query/sql/src/planner/binder/copy_into_table.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13282)
> refactor: de-duplicate bind_copy_into_table.

- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_coordinator.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- tests/sqllogictests/suites/query/spill.test
- Closes https://github.com/datafuselabs/databend/issues/13198 https://github.com/datafuselabs/databend/issues/13139
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13294)
> fix: fix spill flaky tests

- Cargo.lock
- Cargo.toml
- src/query/ast/src/ast/statements/merge_into.rs
- src/query/ast/src/parser/statement.rs
- src/query/expression/src/utils/display.rs
- src/tests/sqlsmith/src/runner.rs
- src/tests/sqlsmith/src/sql_gen/ddl.rs
- src/tests/sqlsmith/src/sql_gen/dml.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
- src/tests/sqlsmith/src/sql_gen/func.rs
- src/tests/sqlsmith/src/sql_gen/query.rs
- src/tests/sqlsmith/src/sql_gen/sql_generator.rs
- src/tests/sqlsmith/src/sql_gen/types.rs
- tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables
- Support generate merge into statement
- Support generate lambda function
- Add `expr_depth` to avoid generate too complex expression
- Rewrite some `MergeIntoStmt` display format
- Bump jsonb to 0.3.0
part of #12576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13300)
> feat(sqlsmith): Support generate merge into

- docs/doc/14-sql-commands/00-ddl/50-udf/index.md
fixed
fixed 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13306)
> docs: Update index.md

- src/query/functions/src/scalars/string.rs
- src/query/functions/tests/it/scalars/string.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/string.txt
- tests/sqllogictests/suites/query/02_function/02_0067_function_string_split
- Close #13286
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13303)
> feat(query): add string function: split and split_part

- src/query/pipeline/sources/src/input_formats/impls/input_format_ndjson.rs
- src/query/pipeline/sources/src/input_formats/impls/input_format_tsv.rs
- tests/sqllogictests/suites/stage/formats/ndjson/ndjson_default
- tests/sqllogictests/suites/stage/formats/tsv/tsv_default
part of https://github.com/datafuselabs/databend/issues/13275
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13321)
> feat: EMPTY as default for TSV and NDJSON.

- src/query/service/tests/it/servers/http/http_query_handlers.rs
https://github.com/datafuselabs/databend/issues/13308
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13325)
> ci: ignore test_query_log_killed.

- src/query/functions/src/scalars/string.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13326)
> chore(query): optimize split_part, avoid collect

- src/query/sql/src/planner/binder/aggregate.rs
- src/query/sql/src/planner/binder/bind_context.rs
- src/query/sql/src/planner/binder/binder.rs
- src/query/sql/src/planner/binder/ddl/index.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/sql/src/planner/binder/table.rs
- tests/data/parquet/timestamp/gen.py
- tests/sqllogictests/suites/ee/02_ee_aggregating_index/02_0000_agg_index_base
- tests/sqllogictests/suites/mode/standalone/ee/explain
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13302)
> refactor: separating bind_agg_indexes from bind_single_table

- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13338)
> chore(ci): always run local benchmark on aws

- docs/doc/10-deploy/10-node-config/03-environment-variables.md
Updated the description of query env variables as Databend also accepts env variables from storage services.
- Closes #13258
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13341)
> docs: query env variables

- .github/actions/benchmark_local/action.yml
- .github/workflows/bindings.python.yml
- .github/workflows/dev.yml
- benchmark/clickbench/hits/clear.sql
- benchmark/clickbench/tpch/clear.sql
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13355)
> chore(ci): do not clean on local benchmark

- docs/doc/01-guides/index.md
- website/docusaurus.config.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13361)
> docs: fix broken link and improve the index

- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/storages/system/src/processes_table.rs
chore(query) add node column for processes table
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13364)
> chore(query): add node column for processes table

- src/query/sql/src/executor/table_read_plan.rs
more status info during building `DataSourcePlan`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13368)
> chore:  more status info during building `DataSourcePlan`

- docs/doc/14-sql-commands/10-dml/dml-copy-into-location.md
- docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
- docs/doc/14-sql-commands/10-dml/dml-delete-from.md
- docs/doc/14-sql-commands/10-dml/dml-insert.md
- docs/doc/14-sql-commands/10-dml/dml-merge.md
- docs/doc/14-sql-commands/10-dml/dml-replace.md
- docs/doc/14-sql-commands/20-query-syntax/01-query-select.md
- docs/doc/14-sql-commands/40-show/show-create-database.md
- docs/doc/14-sql-commands/40-show/show-create-table.md
- docs/doc/14-sql-commands/40-show/show-databases.md
- docs/doc/14-sql-commands/40-show/show-functions.md
- docs/doc/14-sql-commands/40-show/show-metrics.md
- docs/doc/14-sql-commands/40-show/show-processlist.md
- docs/doc/14-sql-commands/40-show/show-table-functions.md
- docs/doc/14-sql-commands/40-show/show-users.md
- docs/doc/14-sql-commands/60-kill/kill-query.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13374)
> docs: pretty format some SQL

- src/common/storage/src/operator.rs
.temporarily disabling  opendal metric layer, seems buggy
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13373)
> chore: disable opendal metric layer

- docs/doc/14-sql-commands/10-dml/dml-insert.md
- docs/doc/14-sql-commands/10-dml/dml-replace.md
* remove `presign upload` from INSERT/REPLACE example, make it simple to use
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13376)
> docs: remove presign from insert/replace example make it simple

- docs/doc/13-sql-reference/20-system-tables/system-table-functions.md
1. fix typo.
2. update result.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13383)
> docs: update system-table-functions.md.

- src/query/service/src/test_kits/config.rs
- src/query/service/tests/it/servers/mysql/mysql_handler.rs
chore(query): disable trace in mysql handler unit test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13389)
> chore(query): disable trace in mysql handler unit test

- scripts/setup/rust-toolchain.toml
- scripts/setup/rust-tools.txt
Prepare to bump rust version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13390)
> chore: Bump rust version

- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13386)
> fix: hash join hang

- src/common/storage/src/operator.rs
- src/query/storages/iceberg/src/database.rs
fix: Fallback to us-east-1 region while not specifed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13406)
> fix: Fallback to us-east-1 region while not specifed

- src/query/service/src/pipelines/executor/executor_graph.rs
- src/query/service/src/pipelines/executor/pipeline_executor.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
chore(query): assert pipeline graph finished
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13417)
> chore(query): assert pipeline graph finished

- src/query/expression/src/kernels/take_chunks.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0026_merge_into
fix upcast column failed for variant and map type
- Closes #13367
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13420)
> fix(query): fix upcast column failed for variant and map type

- src/query/service/src/interpreters/interpreter_table_show_create.rs
- tests/sqllogictests/suites/base/05_ddl/05_0003_ddl_alter_table
- tests/sqllogictests/suites/base/05_ddl/05_0028_ddl_alter_table_add_drop_column
- tests/sqllogictests/suites/base/06_show/06_0001_show_create_table
- tests/suites/0_stateless/14_clickhouse_http_handler/14_0001_clickhouse_http.result
show create table result show not null/null constraints
- Closes #13435
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13442)
> chore: show create table show field null constraints

- Cargo.toml
- src/common/base/Cargo.toml
- src/common/grpc/Cargo.toml
- src/meta/client/Cargo.toml
- src/meta/client/src/grpc_client.rs
- src/meta/client/tests/it/grpc_client.rs
- src/meta/embedded/Cargo.toml
- src/meta/raft-store/Cargo.toml
- src/meta/service/Cargo.toml
- src/meta/service/tests/it/grpc/metasrv_grpc_handshake.rs
- src/meta/sled-store/Cargo.toml
- src/meta/types/Cargo.toml
- src/query/config/Cargo.toml
- src/query/expression/Cargo.toml
- src/query/formats/Cargo.toml
- src/query/functions/Cargo.toml
- src/query/service/Cargo.toml
- src/query/settings/Cargo.toml
- src/query/sql/Cargo.toml
- src/query/storages/common/table-meta/Cargo.toml
- src/query/storages/memory/Cargo.toml
- src/query/storages/system/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13448)
> chore: avoid re-create a meta-client after handshake

- docs/doc/13-sql-reference/50-file-format-options.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13456)
> docs: CSV/TSV not allow alphanumeric delimters.

- Cargo.lock
- src/query/ast/src/ast/statements/replace.rs
- src/query/expression/src/evaluator.rs
- src/query/expression/src/type_check.rs
- src/tests/sqlsmith/Cargo.toml
- src/tests/sqlsmith/src/runner.rs
- src/tests/sqlsmith/src/sql_gen/dml.rs
- src/tests/sqlsmith/src/sql_gen/sql_generator.rs
- support generates `replace into`
- support generates `hint`
- alow auto cast string to bitmap
- fix `check_expr` with `Null` and `Nullable` types
part of #12576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13455)
> feat(sqlsmith): Support generates `replace into` and `hint`

- src/meta/raft-store/src/sm_v002/leveled_store/map_api.rs
- src/meta/raft-store/src/sm_v002/marked/mod.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13469)
> chore: simplify state machine stream handling

- src/query/sql/src/executor/physical_plans/physical_window.rs
- tests/sqllogictests/suites/query/window_function/window_in_expr.test
Fix window function bug when window not in required.
cc @RinChanNOWWW if you have time :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13478)
> fix: fix window function bug when window not in required

- docs/doc/10-deploy/02-deploying-databend.md
- docs/doc/13-sql-reference/51-connect-parameters.md
- docs/doc/15-sql-functions/112-table-functions/index.md
- docs/doc/15-sql-functions/112-table-functions/inspect-parquet.md
- docs/doc/15-sql-functions/112-table-functions/list-stage.md
added function INSPECT_PARQUET.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13479)
> docs: inspect_parquet

- README.md
- docs/doc/00-overview/index.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13496)
> docs: upgrade Databend architecture image

- .github/actions/setup_bendsql/action.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13508)
> fix(ci): setup bendsql with retry

- docs/doc/12-load-data/00-transform/07-data-load-transform.md
- docs/doc/14-sql-commands/00-ddl/40-stage/01-ddl-create-stage.md
- docs/doc/14-sql-commands/10-dml/dml-copy-into-location.md
- docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
Updated FILE_FORMAT syntax wherever it appears for FORMAT_NAME option.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13512)
> docs: file format updates

- src/meta/api/src/schema_api.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/schema/least_visible_time.rs
- src/meta/app/src/schema/mod.rs
feat: add get_lvt API
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13517)
> feat: add get_lvt API

- tests/sqllogictests/suites/duckdb/issues/rigger/division_by_zero_error.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13521)
> chore(ci): comment flaky test

- Cargo.lock
- src/common/base/Cargo.toml
- src/common/base/src/base/mod.rs
- src/common/base/src/base/string.rs
- src/common/base/tests/it/main.rs
- src/common/base/tests/it/string.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/execute_state.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/page_manager.rs
* add new log to expried updated
* pretty the http log
* mask connection params
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13533)
> chore: pretty http handler log

- .github/actions/fuse_compat/action.yml
- .github/actions/setup_bendsql/action.yml
- .github/actions/test_ee_sqllogic_standalone_linux/action.yml
- .github/actions/test_ee_standalone_background_linux/action.yml
- .github/actions/test_ee_standalone_linux/action.yml
- .github/actions/test_fuzz_standalone_linux/action.yml
- .github/actions/test_sqllogic_cluster_linux/action.yml
- .github/actions/test_sqllogic_management_mode_linux/action.yml
- .github/actions/test_sqllogic_stage/action.yml
- .github/actions/test_sqllogic_standalone_linux/action.yml
- .github/actions/test_sqllogic_standalone_macos/action.yml
- .github/actions/test_stateful_cluster_linux/action.yml
- .github/actions/test_stateful_hive_standalone/action.yml
- .github/actions/test_stateful_large_data/action.yml
- .github/actions/test_stateful_sharing/action.yml
- .github/actions/test_stateful_standalone_linux/action.yml
- .github/actions/test_stateless_cluster_linux/action.yml
- .github/actions/test_stateless_cluster_macos/action.yml
- .github/actions/test_stateless_standalone_linux/action.yml
- .github/actions/test_stateless_standalone_macos/action.yml
- .github/workflows/reuse.benchmark.yml
- .github/workflows/reuse.linux.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13540)
> chore(ci): skip setup if bendsql installed

- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13542)
> chore(benchmark): show bench result with last month

- Cargo.lock
- tests/sqllogictests/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13538)
> chore: bump sqllogictest

- .github/actions/build_linux_sanitizer/action.yml
- .github/workflows/release.yml
- .github/workflows/reuse.linux.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13549)
> chore(ci): save release note for each release

- src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/derive_filter.rs
- tests/sqllogictests/suites/mode/standalone/explain/join.test
- Closes https://github.com/datafuselabs/databend/issues/13506
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13532)
> fix: fix derive filter optimization

- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
* remove some http handler hot path log
* pretty some htttp handler log
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13539)
> chore: reformat http handler query

- Cargo.lock
- Cargo.toml
- src/query/ast/src/ast/expr.rs
- src/query/ast/src/parser/expr.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/testdata/expr-error.txt
- src/query/ast/tests/it/testdata/statement-error.txt
- src/query/functions/src/scalars/variant.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/variant.txt
- src/query/functions/tests/it/scalars/variant.rs
- tests/sqllogictests/suites/query/02_function/02_0065_function_json
Added `?` `?|` `?&` operators. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13531)
> feat: add ?, ?|, ?& json operators

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/schema/lock.rs
- src/query/catalog/src/lock.rs
- src/query/storages/fuse/src/operations/commit.rs
set expire_at when `txn_op_put_with_expire`
- Closes #13053
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13569)
> fix(ci): flaky test with table lock

- src/query/expression/src/kernels/concat.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13584)
> chore: fix concat slice

- src/query/expression/src/kernels/concat.rs
- src/query/expression/src/kernels/filter.rs
- src/query/expression/src/kernels/take.rs
- src/query/expression/tests/it/kernel.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13587)
> chore(query): make kernels unit-test coverage wider

- src/query/expression/src/block.rs
- src/query/expression/src/kernels/concat.rs
- src/query/expression/src/types/array.rs
- src/query/expression/src/types/string.rs
- src/query/expression/src/utils/block_debug.rs
- src/query/expression/src/values.rs
- src/query/expression/tests/it/kernel.rs
- src/query/expression/tests/it/main.rs
- src/query/storages/fuse/src/operations/common/processors/transform_serialize_block.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13589)
> chore(query): add check_valid during Serializing block and debug_asserts

- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/02_function/02_0045_conditional_function_in.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13596)
> chore: dedup inlist array

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13608)
> chore(ci): fix generate release changelog

- src/query/service/src/interpreters/interpreter_merge_into.rs
Multiple cluster keys are parsed as a tuple,  #13547 didn't realize this and forget to unwrap the tuple. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13609)
> fix: cluster key in merge into filter

- src/binaries/metactl/main.rs
- src/common/tracing/src/config.rs
- src/meta/service/src/configs/outer_v0.rs
- src/query/config/src/config.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13611)
> fix(query): enable tracing from config

- scripts/ci/deploy/config/databend-query-node-1.toml
- src/query/service/src/interpreters/interpreter_merge_into.rs
- src/query/service/src/interpreters/interpreter_merge_into_static_filter.rs
- src/query/service/src/interpreters/mod.rs
- minor refactor of merge-into static filtering
- add some query context status messages
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13629)
> chore:  minor refactor of merge-into static filter 

- src/query/service/src/interpreters/interpreter_merge_into_static_filter.rs
Only when there is more than one cluster key, cluster keys will be parsed as a `Tuple`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13632)
> chore: fix cluster key in merge into filter

- .github/workflows/bindings.python.yml
- src/bendpy/pyproject.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13638)
> chore(bendpy): add description & publish without token

- src/query/service/src/pipelines/processors/transforms/range_join/ie_join_state.rs
- src/query/service/src/pipelines/processors/transforms/range_join/ie_join_util.rs
- tests/sqllogictests/suites/duckdb/join/iejoin/iejoin_issue_6861.test
- tests/sqllogictests/suites/duckdb/join/iejoin/iejoin_issue_7278.test
- tests/sqllogictests/suites/duckdb/join/iejoin/test_iejoin_east_west.test
- Closes https://github.com/datafuselabs/databend/issues/13621 https://github.com/datafuselabs/databend/issues/13620
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13633)
> fix: fix iejoin with null comparision

- .github/workflows/bindings.python.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13645)
> chore(ci): fix publish python binding artifacts

- src/query/service/src/pipelines/processors/transforms/range_join/ie_join_state.rs
- tests/sqllogictests/suites/duckdb/join/iejoin/complex_range_join.test
In the PR: https://github.com/datafuselabs/databend/pull/13633, null first was changed to true neglectful
- Closes https://github.com/datafuselabs/databend/issues/13651
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13653)
> chore: null first should be false in iejoin

- .github/actions/publish_binary/action.yml
- .github/workflows/reuse.benchmark.yml
- benchmark/clickbench/benchmark_cloud.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13654)
> chore: adjust benchmark warehouse size

- src/query/sql/src/planner/binder/project.rs
- src/query/storages/stage/src/stage_table.rs
- tests/sqllogictests/suites/stage/formats/csv/csv_select.test
- tests/sqllogictests/suites/stage/formats/tsv/tsv_select.test
- tests/sqllogictests/suites/stage/select_star.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13666)
> fix: fail to select * from parquet if any column name starts from "_".

- tests/sqllogictests/src/client/clickhouse_client.rs
- tests/sqllogictests/suites/base/06_show/06_0021_show_connections.test
https://github.com/datafuselabs/databend/pull/13658#issuecomment-1806686809
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13676)
> chore(ci): logic ci panic when ck handler return err resp

- scripts/distribution/configs/databend-meta.toml
- src/common/tracing/src/minitrace.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13682)
> fix(trace): remove redundant prefix for logging

- .github/workflows/reuse.linux.yml
- scripts/setup/dev_setup.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13694)
> chore(ci): disable fuzz test

- src/meta/service/src/grpc_helper.rs
- src/meta/service/src/meta_service/raft_service_impl.rs
- src/meta/service/src/metrics/meta_metrics.rs
- src/meta/service/src/network.rs
- src/meta/service/tests/it/api/http/metrics.rs
- src/meta/types/src/lib.rs
- src/meta/types/src/raft_types.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13683)
> refactor: raft network client: send_snapshot

- src/query/ast/src/ast/format/ast_format.rs
- src/query/ast/src/ast/format/syntax/query.rs
- src/query/ast/src/ast/query.rs
- src/query/ast/src/ast/statements/merge_into.rs
- src/query/ast/src/parser/query.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/query.txt
- src/query/sql/src/planner/binder/join.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs
- src/query/sql/src/planner/optimizer/heuristic/mod.rs
- src/query/sql/src/planner/optimizer/mod.rs
- src/query/sql/src/planner/semantic/distinct_to_groupby.rs
- src/tests/sqlsmith/src/sql_gen/query.rs
- tests/sqllogictests/suites/mode/standalone/explain/lateral.test
- tests/sqllogictests/suites/query/lateral.test
Implement lateral join with subquery.
Part of #13558
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13685)
> feat(planner): implement lateral join

- Cargo.lock
- src/common/storage/src/parquet2.rs
- src/query/storages/parquet/src/parquet_rs/parquet_table/table.rs
helpful to diagnose blocking when there are a lot of files and copy looks blocking
cc @wubx 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13700)
> chore: log begin/end of reading parquet file meta.

- tests/sqllogictests/suites/stage/formats/csv/csv_types.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13703)
> ci: test load unload complex types for csv format.

- tests/sqllogictests/suites/query/join_small_block_size.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13704)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13704)
> ci: fix flaky test by adding order by.

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13705)
> chore(ci): fix format for release note

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13706)
> chore(ci): remove asset for release note

- src/query/sql/src/planner/plans/window.rs
- tests/sqllogictests/suites/query/window_function/window_subquery.test
- Closes #13701
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13707)
> fix(planner): Fix relational property derivation of window function

- src/meta/app/src/principal/connection.rs
- src/query/catalog/src/table_context.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/tests/it/sql/exec/get_table_bind_test.rs
- src/query/service/tests/it/storages/fuse/operations/commit.rs
- src/query/sql/src/planner/binder/copy_into_table.rs
- src/query/sql/src/planner/binder/ddl/catalog.rs
- src/query/sql/src/planner/binder/ddl/connection.rs
- src/query/sql/src/planner/binder/ddl/stage.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/sql/src/planner/binder/location.rs
- src/query/sql/tests/location.rs
- tests/shell_env.sh
- tests/sqllogictests/suites/base/05_ddl/05_0033_ddl_connection.test
- tests/suites/1_stateful/00_stage/00_0012_stage_with_connection.result
- tests/suites/1_stateful/00_stage/00_0012_stage_with_connection.sh
- tests/suites/1_stateful/00_stage/00_0013_connection_errors.result
- tests/suites/1_stateful/00_stage/00_0013_connection_errors.sh
- tests/suites/1_stateful/02_query/02_0004_attach_table.result
- tests/suites/1_stateful/02_query/02_0004_attach_table.sh
syntax:
```
connection=(connection_name ='my_conn')
```
add tests for two recommended cases:
1.  external table / attach table
2. external stage
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13709)
> feat: use self-defined connection.

- Cargo.lock
- Cargo.toml
- src/query/ast/src/ast/expr.rs
- src/query/ast/src/parser/expr.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/testdata/expr-error.txt
- src/query/ast/tests/it/testdata/statement-error.txt
- src/query/functions/src/scalars/variant.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/variant.txt
- src/query/functions/tests/it/scalars/variant.rs
- tests/sqllogictests/suites/query/02_function/02_0065_function_json.test
Added `@>` `<@` json operators.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13713)
> feat: added @>,<@ json operators

- src/query/service/src/pipelines/executor/executor_graph.rs
- src/query/service/src/pipelines/executor/pipeline_executor.rs
- src/query/service/src/pipelines/executor/processor_async_task.rs
chore(executor): add debug for slow processor task
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13719)
> chore(executor): add debug for slow processor task

- src/query/ast/Cargo.toml
- src/query/ast/src/ast/statements/connection.rs
- src/query/ast/src/ast/statements/copy.rs
- src/query/ast/src/ast/statements/statement.rs
- src/query/ast/tests/it/testdata/statement.txt
- tests/suites/1_stateful/02_query/02_0005_attach_table_read_only.result
- tests/suites/1_stateful/02_query/02_0005_attach_table_read_only.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13714)
> feat: mask connection values in CreateConnection and AttachTable.

- benchmark/clickbench/benchmark_local.sh
- benchmark/clickbench/benchmark_local_merge_into.sh
- scripts/benchmark/run-meta-benchmark.sh
- scripts/ci/deploy/databend-query-cluster-3-nodes.sh
- scripts/ci/deploy/databend-query-management-mode.sh
- scripts/ci/deploy/databend-query-standalone-hive.sh
- scripts/ci/deploy/databend-query-standalone-native.sh
- scripts/ci/deploy/databend-query-standalone.sh
- src/meta/sled-store/src/db.rs
- tests/compat/test-compat.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13730)
> chore: output error when failing to open sled db

- src/query/service/src/servers/http/v1/query/page_manager.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
I mistakenly expect clients are well-implemented.
if not, should still get helpful information.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13742)
> refactor: improve http handler error message.

- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- Closes #13736
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13740)
> fix: flaky test case on test_affect

- src/meta/client/tests/it/grpc_server.rs
- src/meta/raft-store/src/ondisk/version_info.rs
- src/meta/raft-store/src/sm_v002/leveled_store/util.rs
- src/meta/raft-store/src/sm_v002/marked/mod.rs
- src/meta/service/src/version.rs
- src/meta/types/src/errors/meta_raft_errors.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13769)
> chore: remove several done TODO

- src/query/sql/src/planner/metadata.rs
- src/query/sql/src/planner/plans/eval_scalar.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/mode/standalone/ee/explain.test
- tests/sqllogictests/suites/query/lateral.test
Close #13756
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13767)
> fix(planner): Fix property derivation of `EvalScalar`

- src/meta/raft-store/src/applier.rs
- src/meta/raft-store/src/sm_v002/importer.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/state_machine/sm.rs
- src/meta/raft-store/src/state_machine/sm_kv_api_impl.rs
- src/meta/service/src/meta_service/meta_node.rs
- src/meta/service/src/network.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13771)
> chore: add doc comments to NetworkConnection

- src/common/arrow/src/native/compression/binary/mod.rs
- src/common/arrow/src/native/compression/boolean/mod.rs
- src/common/arrow/src/native/compression/double/mod.rs
- src/common/arrow/src/native/compression/integer/mod.rs
- src/common/arrow/src/native/util/env.rs
- src/common/arrow/src/native/util/mod.rs
- src/query/expression/src/block.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13773)
> chore(query): fix build warning in release mode

- src/query/storages/fuse/src/table_functions/fuse_encodings/fuse_encoding.rs
- src/query/storages/fuse/src/table_functions/fuse_encodings/fuse_encoding_table.rs
- src/query/storages/fuse/src/table_functions/table_args.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0027_func_fuse_encoding.test
- Closes #13634  issue
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13708)
> feat: improve table function fuse_encoding

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13780)
> chore(ci): fix generate changelog path

- src/query/sql/src/planner/optimizer/heuristic/decorrelate/flatten_plan.rs
- src/query/sql/src/planner/plans/project_set.rs
- tests/sqllogictests/suites/query/lateral.test
Close #13783 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13784)
> feat(planner): Support decorrelate `ProjectSet` operator

- src/query/ast/src/ast/statements/statement.rs
- src/query/ast/src/parser/expr.rs
- src/query/ast/src/parser/parser.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/src/util.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13791)
> chore: improve statement parser

- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/http_query_manager.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13795)
> chore: add kill reason to http handler

- src/query/functions/src/scalars/array.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables.test
- tests/sqllogictests/suites/query/02_function/02_0061_function_array.test
1. add `array_to_string`, `array_flatten` array functions
2. fix #13801
- Closes #13801
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13802)
> feat(query): add more array functions

- Cargo.lock
- src/query/service/src/interpreters/access/privilege_access.rs
- src/query/service/src/table_functions/infer_schema/infer_schema_table.rs
- src/query/service/src/table_functions/inspect_parquet/inspect_parquet_table.rs
- src/query/service/src/table_functions/list_stage/list_stage_table.rs
- src/query/service/tests/it/sql/planner/format/mod.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/sql/src/planner/dataframe.rs
- src/query/sql/src/planner/expression_parser.rs
- src/query/sql/src/planner/metadata.rs
- src/query/users/Cargo.toml
- src/query/users/src/visibility_checker.rs
- tests/suites/0_stateless/18_rbac/00_0012_stage_priv.result
- tests/suites/0_stateless/18_rbac/00_0012_stage_priv.sh
in issue: https://github.com/datafuselabs/databend/issues/13750
wait pr https://github.com/datafuselabs/databend/pull/13735 merged.
- Closes #https://github.com/datafuselabs/databend/issues/13750
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13788)
> fix(query): list stage and select from stage need check priv

- Cargo.lock
- src/binaries/meta/entry.rs
- src/binaries/metabench/main.rs
- src/binaries/metactl/main.rs
- src/binaries/query/entry.rs
- src/common/tracing/Cargo.toml
- src/common/tracing/src/config.rs
- src/common/tracing/src/init.rs
- src/common/tracing/src/lib.rs
- src/common/tracing/src/loggers.rs
- src/meta/process/src/examples.rs
- src/meta/raft-store/tests/it/testing.rs
- src/meta/service/src/configs/outer_v0.rs
- src/meta/service/tests/it/testing.rs
- src/meta/sled-store/tests/it/testing/mod.rs
- src/query/config/src/config.rs
- src/query/service/src/global_services.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
- Closes #13617
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13794)
> feat: support log with opentelemetry otlp

- src/query/functions/src/aggregates/aggregate_approx_count_distinct.rs
- src/query/functions/src/aggregates/aggregate_avg.rs
- src/query/functions/src/aggregates/aggregate_kurtosis.rs
- src/query/functions/src/aggregates/aggregate_quantile_cont.rs
- src/query/functions/src/aggregates/aggregate_quantile_disc.rs
- src/query/functions/src/aggregates/aggregate_skewness.rs
- src/query/functions/src/aggregates/aggregate_stddev.rs
- src/query/functions/src/aggregates/aggregate_sum.rs
- src/query/functions/tests/it/aggregates/testdata/agg.txt
- src/query/functions/tests/it/aggregates/testdata/agg_group_by.txt
- src/query/functions/tests/it/scalars/testdata/array.txt
- tests/sqllogictests/suites/query/02_function/02_0000_function_aggregate_mix.test
* kurtosis
* quantile cont
* quantile disc
* stddev
* approx count distinct
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13768)
> refactor: refactor other unary functions

- src/common/tracing/src/config.rs
- src/common/tracing/src/init.rs
- src/query/config/src/config.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13820)
> feat: add labels config for otlp logging

- src/query/pipeline/core/src/processors/port.rs
- src/query/service/src/pipelines/executor/executor_graph.rs
chore(cluster): add ports status for slow dump
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13822)
> chore(cluster): add ports status for slow dump

- .cargo/audit.toml
- src/common/tracing/Cargo.toml
- src/common/tracing/src/init.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13839)
> fix: endpoint for otlp exporter config

- src/query/ast/src/lib.rs
- src/query/ast/src/parser/expr.rs
- src/query/ast/tests/it/parser.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13849)
> chore(ast): make run_parser!() a function

- .github/actions/build_bindings_python/action.yml
- .github/workflows/bindings.python.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13856)
> chore(ci): fix build python binding

- src/common/http/src/debug/pprof.rs
- src/common/tracing/src/init.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13861)
> fix: filter logs from other modules

- src/query/service/src/interpreters/interpreter_explain.rs
- src/query/sql/src/planner/mod.rs
- src/query/sql/src/planner/plans/insert.rs
- tests/sqllogictests/suites/mode/standalone/explain/explain.test
- Closes https://github.com/datafuselabs/databend/issues/13871
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13876)
> chore: improve explain insert into with select

- src/query/service/src/interpreters/interpreter_explain.rs
- src/query/sql/src/planner/format/display_plan.rs
- tests/sqllogictests/suites/mode/standalone/explain/explain.test
- tests/sqllogictests/suites/mode/standalone/explain/explain_ddl.test
Close #13581
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13888)
> chore(planner): Refine explain output of statements

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13895)
> chore(ci): adjust release changelog

- scripts/setup/dev_setup.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13913)
> chore(ci): install zig for dev setup

- .github/actions/build_macos/action.yml
- scripts/setup/dev_setup.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13914)
> chore(ci): fix install ziglang for debian

- scripts/setup/dev_setup.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13933)
> chore(ci): fix install zig

- src/meta/app/src/principal/connection.rs
- src/query/ast/src/ast/statements/copy.rs
- src/query/service/src/interpreters/interpreter_connection_desc.rs
- src/query/service/src/interpreters/interpreter_connection_show.rs
- tests/sqllogictests/suites/base/05_ddl/05_0033_ddl_connection.test
- Closes #13860  issue
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13916)
> feat: mask admon_key_id && secret_access_key

- src/query/expression/src/kernels/concat.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13936)
> fix: wrong use `size_hint` in `concat_columns`

- src/query/expression/src/evaluator.rs
- tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables.test
fix create table tuple default value painc
- Closes #13940
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13946)
> fix(query): fix create table tuple default value painc

- Cargo.lock
- src/query/ee/src/test_kits/setup.rs
- src/query/service/src/test_kits/fixture.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13954)
> fix: build release warning

- src/binaries/metabench/main.rs
- src/binaries/metactl/main.rs
- src/common/tracing/src/config.rs
- src/common/tracing/src/init.rs
- src/common/tracing/src/lib.rs
- src/meta/service/src/configs/outer_v0.rs
- src/query/config/src/config.rs
- src/query/service/src/interpreters/common/query_log.rs
- src/query/service/src/interpreters/interpreter.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13987)
> feat(query): add config for query profile log

- src/query/functions/src/scalars/decimal.rs
- src/query/functions/tests/it/scalars/testdata/comparison.txt
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- tests/sqllogictests/suites/base/11_data_type/11_0006_data_type_decimal.test
- Closes #14000
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14001)
> fix(query): fix incorrect function name of decimal, neq --> noteq

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14003)
> chore(ci): workflow for stable release

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14007)
> chore(ci): fix note for stable release

- src/meta/api/src/schema_api.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/schema/table.rs
- src/query/catalog/src/catalog/interface.rs
- src/query/service/src/catalogs/default/database_catalog.rs
- src/query/service/src/catalogs/default/immutable_catalog.rs
- src/query/service/src/catalogs/default/mutable_catalog.rs
- src/query/service/tests/it/sql/exec/get_table_bind_test.rs
- src/query/service/tests/it/storages/fuse/operations/commit.rs
- src/query/storages/hive/hive/src/hive_catalog.rs
- src/query/storages/iceberg/src/catalog.rs
add get_table_name_by_id and get_db_name_by_id
- Part of https://github.com/datafuselabs/databend/issues/13319
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14006)
> feat(meta): support use id get table/db_name

- scripts/build/build-debug.sh
- src/meta/app/src/principal/user_stage.rs
- src/meta/proto-conv/src/stage_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/main.rs
- src/meta/proto-conv/tests/it/user_proto_conv.rs
- src/meta/proto-conv/tests/it/v025_user_stage.rs
- src/meta/proto-conv/tests/it/v035_user_stage.rs
- src/meta/proto-conv/tests/it/v042_s3_stage_new_field.rs
- src/meta/proto-conv/tests/it/v066_stage_create_on.rs
- src/meta/protos/proto/stage.proto
- src/query/service/src/interpreters/interpreter_user_stage_create.rs
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/sql/src/planner/binder/binder.rs
- src/query/storages/system/src/stages_table.rs
- tests/sqllogictests/suites/base/05_ddl/05_0016_ddl_stage.test
- tests/sqllogictests/suites/base/06_show/06_0011_show_stages.test
- Closes #12049
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14017)
> feat: add column create_on for stages table

- tests/suites/0_stateless/05_hints/05_0002_deduplicate_label.sh
- tests/suites/0_stateless/18_rbac/20_0012_privilege_access.sh
- Closes #14033
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14034)
> chore: fix test privilege access

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/util.rs
- src/meta/client/src/lib.rs
- src/meta/kvapi/src/kvapi/test_suite.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_watch.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14048)
> chore: simplify txn-op

- src/query/service/src/interpreters/common/query_log.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14074)
> fix(query): add missing server_version for query log

- src/query/service/src/interpreters/interpreter_merge_into.rs
- src/query/sql/src/planner/mod.rs
- src/query/sql/src/planner/plans/merge_into.rs
- src/query/sql/src/planner/plans/mod.rs
- src/query/storages/system/src/virtual_columns_table.rs
* fix typo by typos check
* refine the logic of the merge into status
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14081)
> chore: fix typo and refine the merge into status

- src/meta/README.md
- src/meta/proto-conv/tests/it/v002_share_account_meta.rs
- src/meta/proto-conv/tests/it/v002_share_meta.rs
- src/meta/proto-conv/tests/it/v002_table_meta.rs
- src/meta/proto-conv/tests/it/v005_database_meta.rs
- src/meta/proto-conv/tests/it/v005_share_meta.rs
- src/meta/proto-conv/tests/it/v006_copied_file_info.rs
- src/meta/proto-conv/tests/it/v010_table_meta.rs
- src/meta/proto-conv/tests/it/v012_table_meta.rs
- src/meta/proto-conv/tests/it/v023_table_meta.rs
- src/meta/proto-conv/tests/it/v024_table_meta.rs
- src/meta/proto-conv/tests/it/v026_schema.rs
- src/meta/proto-conv/tests/it/v027_schema.rs
- src/meta/proto-conv/tests/it/v028_schema.rs
- src/meta/proto-conv/tests/it/v029_schema.rs
- src/meta/proto-conv/tests/it/v033_table_meta.rs
- src/meta/proto-conv/tests/it/v034_schema.rs
- src/meta/proto-conv/tests/it/v038_empty_proto.rs
- src/meta/proto-conv/tests/it/v039_data_mask.rs
- src/meta/proto-conv/tests/it/v040_table_meta.rs
- src/meta/proto-conv/tests/it/v044_table_meta.rs
- src/meta/proto-conv/tests/it/v045_background.rs
- src/meta/proto-conv/tests/it/v048_background.rs
- src/meta/proto-conv/tests/it/v049_network_policy.rs
- src/meta/proto-conv/tests/it/v050_user_info.rs
- src/meta/proto-conv/tests/it/v051_obs_and_cos_storage.rs
- src/meta/proto-conv/tests/it/v057_hdfs_storage.rs
- src/meta/proto-conv/tests/it/v058_udf.rs
- src/meta/proto-conv/tests/it/v063_connection.rs
- src/meta/service/tests/it/tests/service.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14128)
> docs: add compatibility to meta/README.md

- src/query/service/src/pipelines/builders/builder_join.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
Make if enable join spill clear
Fixes: #14129
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14130)
> refactor: refine if enable join spill

- src/query/sql/src/planner/udf_validator.rs
- tests/sqllogictests/suites/base/05_ddl/05_0010_ddl_create_udf.test
Fixes #14088 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14104)
> feat: create function support lambda

- .github/actions/test_stateless_cluster_linux/action.yml
- .github/actions/test_stateless_cluster_macos/action.yml
- .github/actions/test_stateless_standalone_linux/action.yml
- .github/actions/test_stateless_standalone_macos/action.yml
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/sql/src/planner/binder/sort.rs
- src/query/sql/src/planner/optimizer/decorrelate/flatten_scalar.rs
- src/query/sql/src/planner/optimizer/decorrelate/subquery_rewriter.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/agg_index/query_rewrite.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_eval_scalar.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_scan.rs
- src/query/sql/src/planner/optimizer/s_expr.rs
- src/query/sql/src/planner/plans/scalar_expr.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/suites/0_stateless/18_rbac/18_0001_udf_priv.result
- tests/suites/0_stateless/18_rbac/18_0001_udf_priv.sh
1. add udf name(in meta) into UdfServerCall
2. chore: fix review suggestion in https://github.com/datafuselabs/databend/pull/14098\#discussion_r1433048221
3. visit_udf_server_call need store name in meta not handler func_name
Fixes #13725 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14105)
> fix(query): add udf name(in meta) into UdfServerCall

- src/query/expression/src/kernels/group_by.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14136)
> chore(expr): cleanup code for kernels/group_by

- src/query/ast/src/parser/statement.rs
- src/query/ast/src/parser/token.rs
- src/query/ee/tests/it/aggregating_index/index_refresh.rs
- src/query/ee/tests/it/aggregating_index/index_scan.rs
- src/query/service/src/interpreters/hook/refresh_hook.rs
- src/query/service/src/interpreters/interpreter_merge_into.rs
- src/query/service/src/interpreters/interpreter_replace.rs
- src/query/service/src/interpreters/interpreter_update.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- tests/sqllogictests/suites/ee/02_ee_aggregating_index/02_0000_async_agg_index_base.test
- tests/sqllogictests/suites/ee/02_ee_aggregating_index/02_0001_agg_index_projected_scan.test
- tests/sqllogictests/suites/ee/02_ee_aggregating_index/02_0002_sync_agg_index_base.test
- tests/sqllogictests/suites/mode/standalone/ee/explain_agg_index.test
Make sync agg index default, change the optional `sync` to `async`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14140)
> refactor: make sync agg index default

- src/query/ast/src/parser/statement.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement-error.txt
- src/query/ast/tests/it/testdata/statement.txt
1.  ownership only support grant or revoke to role
2.  ownership can not appear with other privileges
3.  ownership not support gloable object
4.  keyword UDF and FUNCTION is reserved_ident
Fixes #14148
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14160)
> fix(query): ownership only support grant or revoke to role

- tests/sqllogictests/suites/query/spill.test
- tests/sqllogictests/suites/tpcds/materialized_cte.test
- tests/sqllogictests/suites/tpcds/queries.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14170)
> chore: remove onlyif mysql in tests

- src/query/expression/src/evaluator.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14113)
> fix(expr): fix cast map column validity during evaluation

- tests/sqllogictests/suites/base/01_system/01_0012_system_temp_files.test
- tests/sqllogictests/suites/base/03_common/03_0038_spill_aggregator.test
- tests/sqllogictests/suites/base/05_ddl/05_0006_ddl_grant_privilege.test
- tests/sqllogictests/suites/base/05_ddl/05_0015_ddl_drop_role.test
- tests/sqllogictests/suites/base/05_ddl/05_0026_ddl_unset_settings.test
- tests/sqllogictests/suites/base/06_show/06_0003_show_settings.test
- tests/sqllogictests/suites/base/07_use/07_0000_use_database.test
- tests/sqllogictests/suites/base/10_drivers/10_0003_federated_query.test
- tests/sqllogictests/suites/query/02_function/02_0023_function_strings_quote.test
- tests/sqllogictests/suites/query/case_sensitivity/setting.test
- tests/sqllogictests/suites/query/case_sensitivity/system_table.test
- tests/sqllogictests/suites/query/select.test
Reverts datafuselabs/databend#14168
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14181)
> Revert "chore(query): remove some onlyif mysql in test"

- src/query/service/src/interpreters/access/privilege_access.rs
Determine whether to check the ownership based on the object type
Fixes https://github.com/datafuselabs/databend/issues/14209
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14210)
> refactor(query): Determine whether to check the ownership based on the object type

- Cargo.lock
- src/meta/app/src/principal/mod.rs
- src/meta/app/src/principal/ownership_info.rs
- src/meta/app/src/principal/user_grant.rs
- src/meta/app/src/principal/user_privilege.rs
- src/query/management/src/role/role_api.rs
- src/query/management/src/role/role_mgr.rs
- src/query/service/src/interpreters/access/privilege_access.rs
- src/query/service/src/interpreters/interpreter_database_create.rs
- src/query/service/src/interpreters/interpreter_database_drop.rs
- src/query/service/src/interpreters/interpreter_privilege_grant.rs
- src/query/service/src/interpreters/interpreter_table_create.rs
- src/query/service/src/interpreters/interpreter_table_drop.rs
- src/query/service/src/interpreters/interpreter_user_stage_create.rs
- src/query/service/src/interpreters/interpreter_user_stage_drop.rs
- src/query/service/src/interpreters/interpreter_user_udf_alter.rs
- src/query/service/src/interpreters/interpreter_user_udf_create.rs
- src/query/service/src/interpreters/interpreter_user_udf_drop.rs
- src/query/service/src/sessions/session.rs
- src/query/service/src/sessions/session_privilege_mgr.rs
- src/query/users/src/role_cache_mgr.rs
- src/query/users/src/role_mgr.rs
- tests/suites/0_stateless/18_rbac/18_0002_ownership_cover.result
- tests/suites/0_stateless/18_rbac/18_0002_ownership_cover.sh
ownership cover stage and udf
Fixes https://github.com/datafuselabs/databend/issues/14211
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14217)
> feat(query): ownership cover stage/udf

- src/query/expression/src/function.rs
Display the first error row correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14228)
> chore(query): fix first error row

- src/query/expression/tests/it/types.rs
- src/query/management/src/cluster/cluster_mgr.rs
- src/query/management/src/connection/connection_mgr.rs
- src/query/management/src/file_format/file_format_mgr.rs
- src/query/management/src/network_policy/network_policy_mgr.rs
- src/query/management/src/password_policy/password_policy_mgr.rs
- src/query/management/src/quota/quota_mgr.rs
- src/query/management/src/role/role_mgr.rs
- src/query/management/src/setting/setting_mgr.rs
- src/query/management/src/stage/stage_mgr.rs
- src/query/management/src/udf/udf_mgr.rs
- src/query/management/src/user/user_mgr.rs
- src/query/service/tests/it/auth.rs
- tests/sqllogictests/suites/base/05_ddl/05_0033_ddl_connection.test
* refine the error message of `src/query/management`
* add a unit test for timestamp format: `src/query/expression/tests/it/types.rs`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14242)
> chore: refine the error message for management api

- src/common/hashtable/src/traits.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14245)
> fix(query): fix missing hash fields for NonZeroU64

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14266)
> ci: docker image tag latest only on stable release

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14273)
> chore(ci): fix docker push tags

- src/query/service/src/interpreters/access/privilege_access.rs
AlterUdf and AlterShareTenants needs alter global priv
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14284)
> chore(query): AlterUdf and AlterShareTenants needs alter global priv

- src/query/ee/tests/it/aggregating_index/index_scan.rs
- src/query/service/tests/it/sql/planner/optimizer/agg_index_query_rewrite.rs
- src/query/sql/src/planner/binder/select.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/agg_index/query_rewrite.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_try_apply_agg_index.rs
- tests/sqllogictests/suites/mode/standalone/ee/explain_agg_index.test
Add basic sort support for agg index rewrite
Fixes #14262 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14270)
> feat(query): add basic sort support for agg index rewrite

- src/query/sql/src/planner/optimizer/rule/rewrite/agg_index/query_rewrite.rs
- tests/sqllogictests/suites/ee/02_ee_aggregating_index/02_0000_async_agg_index_base.test
Add select tests for agg index with order by
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14289)
> chore: add select tests for agg index with order by

- src/common/arrow/src/arrow/io/parquet/read/statistics/mod.rs
- src/query/storages/parquet/src/parquet2/parquet_table/partition.rs
- src/query/storages/parquet/src/parquet2/parquet_table/read.rs
- src/query/storages/parquet/src/parquet2/processors/deserialize_transform.rs
- src/query/storages/parquet/src/parquet2/pruning.rs
remove topk optimization in parquet2 because it's incorrect.
Fixes #14296
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14297)
> fix(query): remove topk optimization in parquet2

- .github/workflows/cloud.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14317)
> ci: ci-cloud build both amd64 & arm64

- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14319)
> chore: fix mark scan, test performance.

- src/query/service/src/interpreters/interpreter_table_create.rs
- src/query/service/src/interpreters/interpreter_table_show_create.rs
- tests/sqllogictests/suites/base/06_show/06_0001_show_create_table.test
Fixes #14291
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14321)
> fix(query): add comment in table meta

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14326)
> chore(ci): do not release macos build

- Cargo.lock
- src/meta/app/src/principal/file_format.rs
- src/meta/proto-conv/src/file_format_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/main.rs
- src/meta/proto-conv/tests/it/v032_file_format_params.rs
- src/meta/proto-conv/tests/it/v059_csv_format_params.rs
- src/meta/proto-conv/tests/it/v072_csv_format_params.rs
- src/meta/proto-conv/tests/it/v075_csv_format_params.rs
- src/meta/protos/proto/file_format.proto
- src/query/ast/src/parser/stage.rs
- src/query/ast/src/parser/token.rs
- src/query/formats/Cargo.toml
- src/query/formats/src/binary.rs
- src/query/formats/src/common_settings.rs
- src/query/formats/src/field_decoder/fast_values.rs
- src/query/formats/src/field_decoder/nested.rs
- src/query/formats/src/field_decoder/separated_text.rs
- src/query/formats/src/field_encoder/csv.rs
- src/query/formats/src/field_encoder/json.rs
- src/query/formats/src/field_encoder/values.rs
- src/query/formats/src/file_format_type.rs
- src/query/formats/src/lib.rs
- src/tests/sqlsmith/src/sql_gen/dml.rs
- tests/sqllogictests/suites/stage/formats/csv/csv_option_binary_format.test
- tests/sqllogictests/suites/stage/formats/csv/csv_option_header.test
-  `OUTPUT_HEADER` = `TRUE` | `FALSE`, default is `FALSE`
-  `BINARY_FORMA` =  `HEX`  | `BASE64`, default is `HEX`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14329)
> feat: CSV format add option binary_format and output_header.

- scripts/ci/deploy/config/databend-query-node-1.toml
- scripts/ci/deploy/config/databend-query-node-2.toml
- scripts/ci/deploy/config/databend-query-node-3.toml
- src/binaries/metabench/main.rs
- src/binaries/metactl/main.rs
- src/common/tracing/src/config.rs
- src/common/tracing/src/init.rs
- src/meta/service/src/configs/outer_v0.rs
- src/query/config/src/config.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
chore(query): add log prefix filter config
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14330)
> chore(query): add log prefix filter config

- tests/fuse-compat/compat-logictest/base/fuse_compat_read
to verify that the range index is kept compatible,  add queries that use the range index.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14322)
> chore: tweak fuse compat test

- src/meta/app/src/principal/user_privilege.rs
- src/query/service/src/interpreters/interpreter_privilege_grant.rs
- tests/sqllogictests/suites/base/05_ddl/05_0006_ddl_grant_privilege.test
grant all on *.* to role role_name need success.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14333)
> fix(query): grant all to role_name need succ

- .github/actions/setup_bendsql/action.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14351)
> chore(ci): fix bendsql version for macos

- src/query/sql/src/planner/optimizer/decorrelate/subquery_rewriter.rs
- tests/sqllogictests/suites/query/subquery.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14353)
> fix: clear the derived columns after flattening

- .github/release-report.jq
- .github/workflows/release.yml
- .github/workflows/reuse.macos.yml
- .github/workflows/reuse.sqllogic.yml
- tests/sqllogictests/suites/udf_server/udf_server_test.test
- tests/udf/udf_server.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14354)
> chore: test binary with udf

- src/meta/client/src/grpc_client.rs
In this commit, `MetaGrpcClient` worker spawns a new task to handle the
RPC, instead of blocking receiving and handling all incoming RPC
request.
This change increases concurrency to meta-service RPC.
- Fix: #14356
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14355)
> refactor: meta-client should not block by RPC

- src/query/functions/src/scalars/datetime.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- tests/sqllogictests/suites/query/02_function/02_0012_function_datetimes.test
Fixes #14346 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14352)
> feat(query): add function MONTHS_BETWEEN

- src/query/functions/src/scalars/string.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14363)
> refactor: migrate some string funcs

- src/meta/api/src/schema_api_impl.rs
This commit minimize the gap between the fetch and the update, so that
the chance of conflict is minimized.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14364)
> refactor: create-table fetch latest state after backoff sleep

- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/storages/fuse/src/operations/read/runtime_filter_prunner.rs
- tests/sqllogictests/suites/query/join/runtime_filter.test
- tests/sqllogictests/suites/tpch/join.test
1. support right join for runtime filter
2. support string type join key for runtime filter
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14359)
> feat: support runtime filter for right join and string join key

- src/query/service/src/pipelines/processors/transforms/hash_join/desc.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/sql/src/executor/physical_plans/physical_hash_join.rs
- src/query/sql/src/planner/optimizer/cascades/scheduler.rs
- src/query/sql/src/planner/optimizer/cascades/tasks/apply_rule.rs
- src/query/sql/src/planner/optimizer/cascades/tasks/explore_expr.rs
- src/query/sql/src/planner/optimizer/cascades/tasks/explore_group.rs
- src/query/sql/src/planner/optimizer/cascades/tasks/mod.rs
- src/query/sql/src/planner/optimizer/cascades/tasks/optimize_expr.rs
- src/query/sql/src/planner/optimizer/cascades/tasks/optimize_group.rs
- src/query/sql/src/planner/optimizer/cost/cost.rs
- src/query/sql/src/planner/plans/aggregate.rs
- tests/sqllogictests/suites/mode/cluster/explain_v2.test
- tests/sqllogictests/suites/mode/cluster/memo/aggregate_property.test
- tests/sqllogictests/suites/mode/cluster/memo/join_property.test
- tests/sqllogictests/suites/mode/cluster/memo/mix_property.test
- tests/sqllogictests/suites/mode/standalone/explain/explain.test
- tests/sqllogictests/suites/mode/standalone/explain/lateral.test
- tests/sqllogictests/suites/mode/standalone/explain/prune_column.test
- tests/sqllogictests/suites/mode/standalone/explain/subquery.test
- tests/sqllogictests/suites/mode/standalone/explain_native/prune_column.test
- tests/sqllogictests/suites/mode/standalone/explain_native/subquery.test
- tests/sqllogictests/suites/tpcds/queries.test
- tests/sqllogictests/suites/tpcds/tpcds_join_order.test
- tests/sqllogictests/suites/tpch/queries.test
- Executing task in-place until it's blocked to reduce scheduling overhead.
- Support cost lower bound pruning
- Minor refactor of `SharedCounter`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14350)
> chore(planner): refine cascades optimizer

- tests/sqllogictests/suites/base/01_system/01_0007_system_clustering_history.test
- tests/sqllogictests/suites/base/09_fuse_engine/09_0008_fuse_optimize_table.test
- tests/sqllogictests/suites/base/09_fuse_engine/09_0009_04_range_pruning.test
- tests/sqllogictests/suites/base/09_fuse_engine/09_0011_change_tracking.test
- tests/sqllogictests/suites/base/09_fuse_engine/09_0016_remote_alter_recluster.test
- tests/sqllogictests/suites/base/09_fuse_engine/09_0019_issue_8831.test
- tests/sqllogictests/suites/base/09_fuse_engine/09_0020_analyze.test
- tests/sqllogictests/suites/base/09_fuse_engine/09_0027_func_fuse_encoding.test
Disable table lock when compact and recluster in sqllogic test
https://github.com/datafuselabs/databend/actions/runs/7555112027/job/20569734934#step:13:548
https://github.com/datafuselabs/databend/actions/runs/7554138209/job/20570480133?pr=14361
https://github.com/datafuselabs/databend/actions/runs/7554474386/job/20567743771?pr=14066
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14366)
> fix: flaky test

- .github/PULL_REQUEST_TEMPLATE.md
- Cargo.lock
- src/query/service/Cargo.toml
- src/query/service/src/api/http/v1/mod.rs
- src/query/service/src/api/http/v1/system.rs
- src/query/service/src/api/http_service.rs
- src/query/service/tests/it/storages/fuse/bloom_index_meta_size.rs
- Fixes #14337
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14360)
> feat(query): admin api add system info

- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/util.rs
support min_max runtime filter for string type
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14372)
> feat: support min_max runtime filter for string type

- src/query/storages/stage/src/append/path.rs
- tests/suites/1_stateful/00_stage/00_0015_unload_output.result
- tests/suites/1_stateful/00_stage/00_0015_unload_output.sh
- Fixes https://github.com/datafuselabs/databend/issues/14373
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14375)
> fix: unexpected '/' in unload path.

- src/query/sql/src/planner/optimizer/property/selectivity.rs
- tests/sqllogictests/suites/mode/standalone/explain/filter.test
- tests/sqllogictests/suites/mode/standalone/explain/join.test
- tests/sqllogictests/suites/mode/standalone/explain_native/filter.test
- tests/sqllogictests/suites/mode/standalone/explain_native/join.test
- tests/sqllogictests/suites/tpcds/tpcds_join_order.test
Support constant folding for selectivity estimators.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14386)
> chore(planner): improve selectivity estimator

- src/query/service/src/interpreters/interpreter_vacuum_drop_tables.rs
…ch mode
fix: optimize vacuum drop table call schema gc_drop_tables API in batch mode
- Fixes #[https://github.com/datafuselabs/databend/issues/14394]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14395)
> fix: optimize vacuum drop table call schema gc_drop_tables API in batch mode

- src/common/storage/src/operator.rs
Allow users to configure tcp keepalive for opendal
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14385)
> feat: Allow users to configure tcp keepalive for opendal

- src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/outer_join_to_inner_join.rs
- tests/sqllogictests/suites/mode/standalone/explain/outer_to_inner.test
- tests/sqllogictests/suites/tpcds/tpcds_join_order.test
Outer to inner join is an important optimization rule. If z3 can't process, falling back to native implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14401)
> feat: support outer to inner join

- src/query/storages/fuse/src/operations/read/native_data_source_reader.rs
- src/query/storages/fuse/src/operations/read/parquet_data_source_reader.rs
chore: Add debug log for read parts numbers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14396)
> chore: Add debug log for read parts numbers

- src/query/service/src/pipelines/processors/transforms/processor_accumulate_row_number.rs
found by https://github.com/JackTan25/merge_into_performance and https://github.com/JackTan25/merge_into_performance_test_data_builder.
- Fixes https://github.com/datafuselabs/databend/issues/14417
performance https://github.com/JackTan25/merge_into_performance
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14416)
> fix: fix row number concat

- src/query/catalog/src/plan/pushdown.rs
- src/query/sql/src/executor/physical_plans/physical_table_scan.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/sql/src/planner/format/display_plan.rs
- src/query/sql/src/planner/plans/scan.rs
- src/query/storages/common/table_meta/src/table/stream_keys.rs
- src/query/storages/fuse/src/operations/mutation/mod.rs
- src/query/storages/fuse/src/operations/mutation/mutator/block_compact_mutator.rs
- src/query/storages/stream/src/stream_table.rs
1. modify the max block count in compact to 10_000.
2. rename ChangeAction to ChangeType
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14424)
> chore: modify the max block count in compact

- src/query/storages/common/cache/src/providers/table_data_cache.rs
Fix the variable names to make the code not confusing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14430)
> chore: fix cache variable name

- scripts/setup/rust-toolchain.toml
- scripts/setup/rust-tools.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14436)
> chore: bump rust toolchain for dev container

- scripts/setup/rust-toolchain.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14437)
> chore: bump rust version of build container

- src/query/sql/src/planner/binder/location.rs
- tests/sqllogictests/suites/base/05_ddl/05_0016_ddl_stage.test
Add COS location support
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14435)
> feat: Add COS location support

- src/query/service/src/spillers/spiller.rs
add buffer size in spill write
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14466)
> chore(query): add buffer size in spill write

- src/query/expression/src/types.rs
- src/query/expression/src/values.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14457)
> chore: avoid wildcard match on data type

- .github/workflows/production.yml
- scripts/ci/deploy/config/databend-query-node-1.toml
- src/query/config/src/config.rs
- src/query/settings/src/settings.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14475)
> fix(query): config value for session settings

- src/query/service/tests/it/storages/system.rs
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/sql/src/planner/binder/show.rs
- src/query/storages/system/src/functions_table.rs
- tests/sqllogictests/suites/base/06_show/06_0005_show_functions.test
- tests/sqllogictests/suites/mode/standalone/explain/prune_column.test
- tests/sqllogictests/suites/mode/standalone/explain_native/prune_column.test
After the merge with https://github.com/datafuselabs/databend/pull/14440, we have a separate table for storing and displaying UDFs' information, so it needs to be removed to ensure consistency.
- Related #14293 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14471)
> refactor: remove udf from system functions table

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14478)
> ci: fix previous tag for nightly release

- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- tests/sqllogictests/suites/query/spill.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14484)
> chore(query): fix hash join spill block size

- Cargo.lock
- src/common/tracing/Cargo.toml
- src/common/tracing/src/init.rs
- src/query/expression/src/property.rs
- src/query/expression/src/types/map.rs
- src/query/expression/src/utils/display.rs
- src/query/expression/src/values.rs
- src/query/storages/common/index/src/range_index.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14314)
> chore: update Domain::Map

- src/meta/app/src/principal/user_grant.rs
- src/meta/app/tests/it/user_grant.rs
- src/query/management/src/role/role_api.rs
- src/query/management/src/role/role_mgr.rs
- src/query/service/src/auth.rs
- src/query/service/src/interpreters/interpreter_role_grant.rs
- src/query/service/src/interpreters/interpreter_setting.rs
- src/query/service/src/interpreters/interpreter_show_grants.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/users/src/role_cache_mgr.rs
- src/query/users/src/role_mgr.rs
- src/query/users/src/user_api.rs
- src/query/users/tests/it/role_mgr.rs
Reverts datafuselabs/databend#14451
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14497)
> Revert "feat(rbac): ensure the builtin roles on auth"

- src/query/functions/src/scalars/decimal/cast.rs
- tests/sqllogictests/suites/base/11_data_type/11_0006_data_type_decimal.test
- Fixes #14469 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14489)
> fix: throw err when cast Decimal overflow

- tests/suites/0_stateless/00_dummy/00_0002_dummy_select_py.py
fix(query): replace mock_s3 with mock_aws
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14498)
> fix(query): replace mock_s3 with mock_aws

- Cargo.lock
- src/common/license/Cargo.toml
- src/common/license/src/license.rs
- src/query/ee/src/license/license_mgr.rs
- src/query/service/src/table_functions/others/license_info.rs
- tests/suites/5_ee/00_check/00_0014_license_info.py
- tests/suites/5_ee/00_check/00_0014_license_info.result
1. add `features` field on license_info() function
2. remove `test` feature during features display
3. sort features display in alphabetic order
4. empty features would display all features(as no limit constraint)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14509)
> chore: clean license message

- src/query/settings/src/settings_default.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14513)
> fix(query): add range for memory ratio settings

- src/query/sql/src/planner/binder/select.rs
- tests/sqllogictests/suites/mode/standalone/explain/window.test
support row fetcher with window function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14492)
> chore: support row fetcher with window function

- src/query/config/src/config.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14512)
> chore(query): mark obsoleted session settings in config

- src/query/sql/src/planner/binder/table.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14511)
> chore: remove unused codes

- src/meta/raft-store/src/log/raft_log.rs
- src/meta/sled-store/src/sled_tree.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14527)
> refactor: meta-service purge log in small chunks to avoid blocking

- src/meta/sled-store/Cargo.toml
- src/meta/sled-store/src/sled_tree.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14530)
> chore: sleep 5ms before next batch purge

- src/meta/app/src/principal/user_privilege.rs
- src/meta/proto-conv/src/share_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/user_from_to_protobuf_impl.rs
- src/query/ee/tests/it/aggregating_index/index_scan.rs
- src/query/service/src/interpreters/interpreter_setting.rs
- src/query/service/src/servers/http/clickhouse_handler.rs
- src/query/service/src/servers/http/v1/load.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/sessions/session_mgr.rs
- src/query/service/tests/it/sessions/session_setting.rs
- src/query/settings/src/settings.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/settings/tests/it/setting.rs
- src/query/sql/src/planner/binder/binder.rs
- src/query/users/src/role_mgr.rs
- src/query/users/src/user_api.rs
1. account_admin role generated in query
2. revert set_setting, change set sandbox_tenant logic in SettingInterpreter
This PR needs to prove all tests do not fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14514)
> refactor(query): account_admin role generate in query

- src/query/service/src/interpreters/interpreter_unsetting.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14537)
> fix(query): add warning for unset unknown setting

- src/query/pipeline/core/src/pipeline.rs
- src/query/pipeline/core/src/processors/profile.rs
- src/query/service/src/pipelines/builders/builder_exchange.rs
- src/query/sql/src/executor/physical_plan.rs
fix(executor): fix broken profile graph for cluster mode
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14554)
> fix(executor): fix broken profile graph for cluster mode

- .github/actions/benchmark_cloud/action.yml
- .github/workflows/reuse.benchmark_query_meta.yml
- benchmark/clickbench/README.md
- benchmark/clickbench/benchmark_local.sh
- benchmark/clickbench/internal/load.sh
- benchmark/clickbench/internal/queries.sql
add system tables/columns benchmark cloud
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14555)
> chore(ci): add system tables/columns benchmark cloud

- src/query/ast/src/ast/statements/connection.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement-error.txt
- src/query/ast/tests/it/testdata/statement.txt
- src/query/management/src/connection/connection_api.rs
- src/query/management/src/connection/connection_mgr.rs
- src/query/service/src/interpreters/interpreter_connection_create.rs
- src/query/sql/src/planner/binder/ddl/connection.rs
- src/query/sql/src/planner/plans/ddl/connection.rs
- src/query/users/src/connection.rs
- tests/sqllogictests/suites/base/05_ddl/05_0033_ddl_connection.test
Feature: add create or replace connection support #14579 
- Fixes #14579
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14580)
> feat: add create or replace connection support

- Cargo.lock
- src/query/pipeline/core/Cargo.toml
- src/query/pipeline/core/src/processors/profiles.rs
- src/query/service/src/interpreters/interpreter.rs
- src/query/sql/src/executor/format.rs
chore(executor): using human format for explain analyze profile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14578)
> chore(executor): using human format for explain analyze profile

- src/query/ast/src/ast/expr.rs
- src/query/ast/src/parser/expr.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/testdata/expr-error.txt
- src/query/ast/tests/it/testdata/statement-error.txt
- src/query/functions/src/scalars/variant.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/variant.txt
- src/query/functions/tests/it/scalars/variant.rs
- tests/sqllogictests/suites/query/02_function/02_0065_function_json.test
Added `#-` json operator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14584)
> feat: add #- json operator

- src/meta/service/src/network.rs
fix comment for observe_append_send_spent
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14586)
> fix: fix comment for observe_append_send_spent

- src/query/ast/src/parser/expr.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
- tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables.test
- Fixes #14573
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14590)
> fix(query): fix parse unsigned integer with number

- src/meta/app/src/principal/mod.rs
- src/meta/app/src/principal/user_defined_function.rs
- src/meta/app/src/schema/create_option.rs
- src/query/management/src/udf/udf_mgr.rs
- src/query/service/src/interpreters/interpreter_table_create.rs
- src/query/sql/src/planner/binder/ddl/account.rs
- src/query/sql/src/planner/binder/ddl/connection.rs
- src/query/sql/src/planner/binder/ddl/database.rs
- src/query/sql/src/planner/binder/ddl/stage.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/sql/src/planner/binder/udf.rs
- src/query/sql/src/planner/plans/ddl/database.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14589)
> refactor: refine UdfMgr

- src/query/service/src/interpreters/interpreter_replace.rs
- src/query/service/src/pipelines/builders/builder_append_table.rs
- src/query/service/src/pipelines/builders/builder_distributed_insert_select.rs
- src/query/service/src/pipelines/builders/builder_fill_missing_columns.rs
- src/query/service/src/pipelines/builders/builder_replace_into.rs
- src/query/service/src/test_kits/fixture.rs
- src/query/sql/src/executor/physical_plans/physical_replace_deduplicate.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0024_replace_into_issue_14593.test
- Fixes #14593
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14592)
> fix: incorrect schema may be used while executing `replace-into`

- src/query/ast/src/ast/format/syntax/ddl.rs
- src/query/ast/src/ast/statements/stream.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/src/parser/stream.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
- src/query/ee/src/stream/handler.rs
- src/query/sql/src/planner/binder/ddl/stream.rs
- src/query/sql/src/planner/plans/ddl/stream.rs
- tests/sqllogictests/suites/ee/01_ee_system/01_0003_stream.test
feat: add create or replace stream support
- Fixes #14595
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14596)
> feat: add create or replace stream support

- src/query/ast/src/ast/format/syntax/ddl.rs
- src/query/ast/src/ast/statements/view.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
- src/query/service/src/interpreters/interpreter_view_create.rs
- src/query/sql/src/planner/binder/ddl/view.rs
- src/query/sql/src/planner/plans/ddl/view.rs
- tests/sqllogictests/suites/base/05_ddl/05_0019_ddl_create_view.test
feat: add create or replace view support
- Fixes #14598
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14599)
> feat: add create or replace view support

- src/query/ast/src/parser/expr.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/expr.txt
- Fixes https://github.com/datafuselabs/databend/issues/14600
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14604)
> fix(ast): unexpected cut in not null

- src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/left_join.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14571)
> chore: refine hash join code

- .github/workflows/reuse.benchmark.yml
- benchmark/clickbench/benchmark_local.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14608)
> chore(ci): fix benchmark scripts

- Cargo.lock
- Cargo.toml
chore: Bump OpenDAL to pinned tag version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14601)
> chore: Bump OpenDAL to pinned tag version

- src/query/ast/src/ast/statements/statement.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/src/visitors/visitor.rs
- src/query/ast/src/visitors/visitor_mut.rs
- src/query/ast/src/visitors/walk.rs
- src/query/ast/src/visitors/walk_mut.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
- src/query/management/src/connection/connection_mgr.rs
- src/query/management/src/file_format/file_format_api.rs
- src/query/management/src/file_format/file_format_mgr.rs
- src/query/management/src/stage/stage_mgr.rs
- src/query/management/src/user/user_mgr.rs
- src/query/service/src/interpreters/interpreter_file_format_create.rs
- src/query/sql/src/planner/binder/binder.rs
- src/query/sql/src/planner/plans/ddl/file_format.rs
- src/query/users/src/file_format.rs
- tests/sqllogictests/suites/base/05_ddl/05_0030_ddl_file_format.test
feat: add create or replace file format support
- Fixes #14610
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14611)
> feat: add create or replace file format support

- benchmark/clickbench/internal/load.sh
- benchmark/clickbench/internal/queries.sql
benchmark system table query speed with a large test data
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14612)
> chore(ci): benchmark system table query speed with a large test data

- benchmark/clickbench/hits/load.sql
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14619)
> chore(ci): load benchmark data from hits_100m_obfuscated_v1

- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14620)
> chore(ci): remove dummy dataset for benchmark

- benchmark/clickbench/hits/create.sql
- benchmark/clickbench/hits/create_local.sql
- benchmark/clickbench/hits/load.sql
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14621)
> chore(ci): fix hits benchmark schema

- .github/workflows/reuse.benchmark.yml
- benchmark/clickbench/hits/create.sql
- benchmark/clickbench/hits/create_local.sql
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14625)
> chore(ci): tmp disable local hits benchmark

- benchmark/clickbench/internal/load.sh
benchmark test will set a BENDSQL_DSN, no need to use -u set user.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14627)
> chore(ci): fix internal test reduce bendsql warn

- .github/workflows/reuse.benchmark.yml
cc @xudong963 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14628)
> chore(ci): fix download benchmark results

- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14630)
> chore(ci): fix get dataset from benchmark result file

- src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge_base.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge_limit.rs
- src/query/sql/src/planner/optimizer/rule/factory.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_limit_sort.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_limit_window.rs
- tests/sqllogictests/suites/base/03_common/03_0042_select_large_limit.test
fix(query): try fix oom with large sort limit
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14629)
> fix(query): try fix oom with large sort limit

- src/query/sql/src/executor/format.rs
- tests/sqllogictests/suites/mode/standalone/explain/explain.test
- tests/sqllogictests/suites/mode/standalone/explain/join_reorder/chain.test
- tests/sqllogictests/suites/mode/standalone/explain_native/join_reorder/chain.test
- tests/sqllogictests/suites/tpcds/tpcds_join_order.test
- tests/sqllogictests/suites/tpch/queries.test
distinguish tables that have the same name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14632)
> chore: add table index to explain join

- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14633)
> chore(ci): fix download benchmark result

- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14638)
> chore(ci): fix new line in benchmark comment

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/schema/index.rs
- src/query/ast/src/ast/statements/index.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
- src/query/ee/tests/it/aggregating_index/index_refresh.rs
- src/query/service/src/interpreters/interpreter_index_create.rs
- src/query/sql/src/planner/binder/ddl/index.rs
- src/query/sql/src/planner/plans/ddl/index.rs
- tests/sqllogictests/suites/ee/05_ee_ddl/05_0000_ddl_create_drop_index.test
feat: add create or replace agg index support
- Fixes #14635
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14636)
> feat: add create or replace agg index support

- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14643)
> chore(ci): fix comment benchmark result

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14646)
> chore(ci): fix runner provider for release benchmark

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/schema/virtual_column.rs
- src/query/ast/src/ast/statements/virtual_column.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
- src/query/service/src/interpreters/interpreter_virtual_column_create.rs
- src/query/sql/src/planner/binder/ddl/virtual_column.rs
- src/query/sql/src/planner/plans/ddl/virtual_column.rs
- tests/sqllogictests/suites/ee/01_ee_system/01_0002_virtual_column.test
feat: add create or replace virtual column support
- Fixes #14648
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14649)
> feat: add create or replace virtual column support

- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14652)
> chore(ci): fix artifacts for benchmark archive

- src/meta/api/src/data_mask_api_impl.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/data_mask/mod.rs
- src/query/ast/src/ast/statements/data_mask.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
- src/query/sql/src/planner/binder/ddl/data_mask.rs
- src/query/sql/src/planner/plans/data_mask.rs
- tests/sqllogictests/suites/ee/05_ee_ddl/05_0001_ddl_data_mask.test
feat: add create or replace masking policy support
- Fixes #14655
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14656)
> feat: add create or replace masking policy support

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/api/src/share_api_impl.rs
- src/meta/api/src/share_api_test_suite.rs
- src/meta/app/src/share/share.rs
- src/query/ast/src/ast/statements/share.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
- src/query/sql/src/planner/binder/ddl/share.rs
- src/query/sql/src/planner/plans/share.rs
- tests/sqllogictests/suites/base/06_show/06_0020_show_share_endpoint.test
feat: add create or replace share endpoint support
- Fixes #14659
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14660)
> feat: add create or replace share endpoint support

- Cargo.lock
- src/common/tracing/Cargo.toml
- src/common/tracing/src/loggers.rs
- src/query/service/src/servers/server.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14539)
> fix: otlp logger runtime for graceful shutdown

- src/query/storages/fuse/src/operations/merge_into/mutator/matched_mutator.rs
- src/query/storages/fuse/src/operations/replace_into/mutator/merge_into_mutator.rs
- src/query/storages/fuse/src/operations/util.rs
`The spawn_blocking method will be removed, so we use another method.`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14664)
> chore: remove spawn_blocking for merge into and replace into

- Cargo.lock
- Cargo.toml
- src/query/storages/delta/Cargo.toml
chore(query): update async trait version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14667)
> chore(query): update async trait version

- scripts/setup/dev_setup.sh
add dev deps(libtiff and sqlite3) for proj crate
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14670)
> chore: add dev deps for proj crate

- scripts/setup/dev_setup.sh
add dev dep sqlite binary for proj crate
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14673)
> chore: add dev dep sqlite binary for proj crate

- src/query/service/src/pipelines/executor/pipeline_pulling_executor.rs
chore(executor): remove useless warn log
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14672)
> chore(executor): remove useless warn log

- docker/build-tool/gnu/Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14678)
> chore: install liblzma-dev for build-tool

- Cargo.lock
- Cargo.toml
- src/common/arrow/src/arrow/io/ipc/read/schema.rs
- src/common/arrow/src/arrow/io/ipc/write/common.rs
Update `arrow-format` to v1.4 version, thanks @everpcpc for re-generate `arrow-format`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14675)
> chore: upgrade arrow-format

- src/common/storage/src/operator.rs
- Fixes https://github.com/datafuselabs/databend/issues/14669
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14680)
> fix: Use stat instead of list for checking storage

- Makefile
- src/query/service/src/pipelines/executor/executor_graph.rs
- src/query/service/src/pipelines/executor/executor_tasks.rs
- src/query/service/src/pipelines/executor/executor_worker_context.rs
- src/query/service/src/pipelines/executor/pipeline_executor.rs
- src/query/service/src/pipelines/executor/processor_async_task.rs
- src/query/service/tests/it/pipelines/executor/executor_graph.rs
part of #14594
spilted graph part from #14594.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14681)
> refactor(executor): add graph information to prepare adding points

- src/query/functions/src/srfs/array.rs
- tests/sqllogictests/suites/query/02_function/02_0062_function_unnest.test
fix unnest variant array panic
- Fixes #14676
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14688)
> fix(query): fix unnest variant array panic

- src/binaries/metactl/main.rs
- src/binaries/metactl/reading.rs
- src/binaries/metactl/snapshot.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14698)
> chore: extract common functions from metactl

- src/meta/api/src/schema_api_impl.rs
- src/meta/app/src/data_mask/mod.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14724)
> refactor: schema_api::update_mask_policy

- src/query/service/src/interpreters/interpreter_table_create.rs
- tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables.test
fix: fix create or replace table as select bug
- Fixes #14727
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14730)
> fix: fix create or replace table as select bug

- src/common/storage/src/copy.rs
- src/query/pipeline/sources/src/input_formats/impls/input_format_csv.rs
- src/query/storages/stage/src/read/row_based/formats/csv/block_builder.rs
- tests/sqllogictests/suites/stage/formats/csv/csv_empty.test
give advise for fixing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14737)
> chore: polish error message.

- src/meta/types/src/change.rs
- src/query/management/src/role/role_mgr.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14741)
> chore: refactor RoleMgr

- .github/workflows/build_tool.yml
- .github/workflows/cloud.yml
- .github/workflows/release.yml
- docker/build-tool/musl/Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14751)
> chore: build-tool base for both arm64 & amd64

- scripts/setup/dev_setup.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14754)
> chore: fix setup protoc aarch64

- src/query/storages/fuse/src/operations/analyze.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14753)
> chore: fix compile error
