- docs/doc/13-sql-reference/10-data-types/20-data-type-time-date-types.md
- docs/doc/15-sql-functions/30-datetime-functions/todate.md
- docs/doc/15-sql-functions/30-datetime-functions/totimestamp.md
added specifier tables from https://docs.rs/chrono/latest/chrono/format/strftime/index.html
Closes #issue
> docs: date&time specifier list

- src/query/functions/src/scalars/bitmap.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- tests/sqllogictests/suites/query/02_function/02_0064_function_bitmap
Add `bitmap_or`, `bitmap_and`, `bitmap_xor`, `bitmap_not`, `bitmap_and_not` function. And fixed panic when calling `bitmap_max` and `bitmap_min` with empty bitmap.
Part of #11219
> feat: add bitmap logical operation functions

- src/meta/api/src/schema_api_impl.rs
- src/meta/app/src/schema/table.rs
- src/query/catalog/src/catalog/interface.rs
- src/query/catalog/src/database.rs
- src/query/service/src/catalogs/default/database_catalog.rs
- src/query/service/src/catalogs/default/immutable_catalog.rs
- src/query/service/src/catalogs/default/mutable_catalog.rs
- src/query/service/src/databases/default/default_database.rs
- src/query/service/src/databases/share/share_database.rs
- src/query/service/src/interpreters/interpreter_table_create.rs
- src/query/service/tests/it/storages/fuse/operations/commit.rs
- src/query/storages/hive/hive/src/hive_catalog.rs
- src/query/storages/iceberg/src/catalog.rs
- tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables
Add `CreateTableReply` in meta_api_impl, if the table exists we will not apply the insert.
Closes #11430
> fix(query): fix create table if not exists

- docs/doc/14-sql-commands/00-ddl/20-table/10-ddl-create-table.md
fixed "create external" example
Closes #11521
> docs: fix "create external" example

- src/bendpy/README.md
- src/bendpy/src/lib.rs
- src/bendpy/tests/basic.py
Example to enable disk cache:
```
❯ python
Python 3.7.16 (default, May 11 2023, 12:45:25) 
[GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os 
>>> os.environ["CACHE_DATA_CACHE_STORAGE"] = "disk"
>>> from databend import SessionContext 
>>> ctx = SessionContext()
>>> ctx.sql("select * from system.configs where name like '%data_cache%'")
┌────────────────────────────────────────────────────────────────────────────┐
│  group  │                   name                   │  value  │ description │
│  String │                  String                  │  String │    String   │ …
```
> feat(python): support configuration from env

- .github/workflows/benchmark.yml
- benchmark/clickbench/benchmark_cloud.sh
- benchmark/clickbench/benchmark_local.sh
Checking out merge commit on `pull_request_target` has security concerns, but we need this for benchmark.
Since only org members can label a pr to trigger a benchmark run, it is believed to be safe here.
Closes #issue
> ci: checkout merge commit on benchmark

- src/query/storages/fuse/src/operations/merge_into/mutator/merge_into_mutator.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0024_replace_into_issue_10861
For `replace into` stmt that specifies multiple `on conflicts` fields,  segments/blocks should be pruned if any of the fields could be pruned by range index (not all of them).
Closes #11557
> fix: multi-cols pruning of `replace into`

- src/query/service/src/servers/http/v1/query/http_query.rs
in the current design, the session settings will be persisted in the client side, and will be passed to the backend in the next request. 
but when we removed a setting, the memorized session settings from the client side will trigger an UnknownVariable error which breaks the query call.
this pr tries swallow the unknown variable error on we got a unknown session settings, and replaces it with a warning log. so this might make it easier for us to remove/change the session setting variables without being afraid of break the client calls.
> chore: warning the unknown session settings

- src/query/service/src/pipelines/processors/transforms/ie_join/ie_join_state.rs
- src/query/service/src/pipelines/processors/transforms/ie_join/ie_join_util.rs
- src/query/service/src/pipelines/processors/transforms/ie_join/mod.rs
- src/query/sql/src/executor/physical_plan_builder.rs
- src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
- tests/sqllogictests/suites/query/iejoin.test
Support more than two predicates for iejoin, such as
```sql
SELECT s1.rid, s2.rid
FROM west s1, west s2
WHERE s1.time > s2.time AND s1.cost < s2.cost AND s1.rid > s2.rid;
```
Predicates with more than two are placed in `other_conditions`
Closes #issue
> feat: support more than two predicates for iejoin

- src/query/functions/src/lib.rs
- src/query/service/src/pipelines/processors/transforms/window/transform_window.rs
- src/query/service/src/pipelines/processors/transforms/window/window_function.rs
- src/query/sql/src/executor/physical_plan.rs
- src/query/sql/src/executor/physical_plan_builder.rs
- src/query/sql/src/planner/binder/aggregate.rs
- src/query/sql/src/planner/binder/scalar_common.rs
- src/query/sql/src/planner/binder/scalar_visitor.rs
- src/query/sql/src/planner/binder/window.rs
- src/query/sql/src/planner/optimizer/heuristic/prune_unused_columns.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/derive_filter.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_eval_scalar.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_scan.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_union.rs
- src/query/sql/src/planner/plans/scalar_expr.rs
- src/query/sql/src/planner/plans/window.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/window_function/window_basic.test
- tests/sqllogictests/suites/query/window_function/window_bound.test
Add window function `first_value` and `last_value`.
Part of #11148
> feat: add window function first_value and last_value

- src/query/functions/src/lib.rs
- src/query/service/src/pipelines/processors/transforms/window/transform_window.rs
- src/query/service/src/pipelines/processors/transforms/window/window_function.rs
- src/query/sql/src/executor/physical_plan.rs
- src/query/sql/src/executor/physical_plan_builder.rs
- src/query/sql/src/planner/binder/aggregate.rs
- src/query/sql/src/planner/binder/scalar_common.rs
- src/query/sql/src/planner/binder/scalar_visitor.rs
- src/query/sql/src/planner/binder/window.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/derive_filter.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_eval_scalar.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_scan.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_union.rs
- src/query/sql/src/planner/plans/scalar_expr.rs
- src/query/sql/src/planner/plans/window.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/window_function/window_basic.test
- tests/sqllogictests/suites/query/window_function/window_wisconsin.test
- Support new window function `nth_value`.
- Unify `lead` and `lag` into one structure.
- Unify `first_value`, `last_value` and `nth_value` into one structure.
- Remove useless data structures.
Tracking in #11148
> feat: new window function `nth_value`.

- src/query/ast/src/ast/format/syntax/query.rs
- src/query/sql/src/planner/binder/bind_context.rs
- src/query/sql/src/planner/binder/select.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/sql/src/planner/binder/window.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/window_function/window_in_expr.test
In the past implementation, we rewritten window reference clause into window spec clause in the select list with the named window map. However, we only rewrite the top level of the expression. E.g. `select rank() over w` will be rewritten, but `select 1 + rank() over w` will not be rewritten, which will lead to panic during `type_check`. 
The modifications in this PR:
- Add the missing `explain syntax` for named window.
- Put named window map into bind context. We can refer to bind context during `type_check`. It will reduce many duplicate codes.
- Add tests of window functions in expressions.
Fix part of #11593
> fix: support named window in expression.

- src/query/sql/src/planner/udf_validator.rs
The params in `expr_params` but not in `parameters` are not declared, and the params in `parameters` but not in `expr_params` are not used.
> chore: rename variable name

- Cargo.lock
- src/query/expression/src/evaluator.rs
- src/query/service/src/api/rpc/flight_scatter_hash.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/common.rs
> chore(expr): remove run_auto_type

- src/query/sql/src/planner/optimizer/cascades/cascade.rs
- src/query/sql/src/planner/optimizer/group.rs
- src/query/sql/src/planner/optimizer/m_expr.rs
- src/query/sql/src/planner/optimizer/memo.rs
- src/query/sql/src/planner/optimizer/pattern_extractor.rs
- src/query/sql/src/planner/optimizer/property/builder.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/agg_index/query_rewrite.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/extract_or_predicates.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/outer_join_to_inner_join.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_fold_constant.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_fold_count_aggregate.rs
- src/query/sql/src/planner/optimizer/rule/transform/rule_eager_aggregation.rs
- src/query/sql/src/planner/optimizer/runtime_filter/mod.rs
- src/query/sql/src/planner/optimizer/s_expr.rs
- src/query/sql/src/planner/plans/aggregate.rs
- src/query/sql/src/planner/plans/dummy_table_scan.rs
- src/query/sql/src/planner/plans/eval_scalar.rs
- src/query/sql/src/planner/plans/exchange.rs
- src/query/sql/src/planner/plans/filter.rs
- src/query/sql/src/planner/plans/join.rs
- src/query/sql/src/planner/plans/limit.rs
- src/query/sql/src/planner/plans/operator.rs
- src/query/sql/src/planner/plans/pattern.rs
- src/query/sql/src/planner/plans/project_set.rs
- src/query/sql/src/planner/plans/runtime_filter_source.rs
- src/query/sql/src/planner/plans/scan.rs
- src/query/sql/src/planner/plans/sort.rs
- src/query/sql/src/planner/plans/union_all.rs
- src/query/sql/src/planner/plans/window.rs
- src/query/sql/src/planner/semantic/type_check.rs
- Use `Arc` to store relational properties to reduce clone
- Expand `Pattern` into complete `SExpr` in `PatternExtractor`
> chore(planner): Minor refactor property derivation

- src/query/expression/src/kernels/take_compact.rs
Remove `take_string_types` and replace it by `take_compact_arg_types`.
Closes #issue
> chore: remove take_string_types

- Cargo.lock
- Cargo.toml
- src/common/storage/src/operator.rs
- src/common/storage/src/runtime_layer.rs
feat: Bump OpenDAL to 0.37.0
Release note: https://github.com/apache/incubator-opendal/releases/tag/v0.37.0
Notable changes to databend:
- feat: Implement Timeout Layer
- fix(core): Don't wake up operator futures while not ready
> feat: Bump OpenDAL to 0.37.0

- src/meta/README.md
- src/meta/raft-store/src/state_machine/expire.rs
- src/meta/raft-store/src/state_machine/sm.rs
- src/meta/service/src/configs/outer_v0.rs
`ExpireValue` is the value part of the expiration index of generic-kv in
meta-service. To support snapshot read(in next PR), it must store
a `seq` number to indicate the freshness of the index entry.
This is a **compatible** change to the meta data.
> feat(meta): add `seq` to ExpireValue

- src/common/storage/src/operator.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/app/src/storage/storage_params.rs
- src/meta/service/src/configs/outer_v0.rs
- src/query/functions/src/scalars/comparison.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_state.rs
- src/query/sharing-endpoint/README.md
The timeout for the entire HTTP request is not needed after OpenDAL timeout layer has been added. Besides, this timeout didn't take the body size into consideration which could lead to connection retry.
> refactor: Remove HTTP timeout after OpenDAL timeout layer added

- src/query/pipeline/transforms/src/processors/transforms/transform_compact.rs
- src/query/service/src/pipelines/executor/executor_tasks.rs
1. when we get into compacted stage, input_port must be finished
2. we should reuse existed variable.
Closes #issue
> fix: fix code logic

- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/storages/information-schema/src/tables_table.rs
add some columns into information_schema.tables
Closes #11675
> feat(query): add some columns into information_schema.tables

- src/common/profile/src/span.rs
- src/query/service/src/api/rpc/exchange/exchange_manager.rs
- src/query/service/src/api/rpc/packets/packet_executor.rs
- src/query/service/src/interpreters/interpreter_explain.rs
- src/query/service/src/interpreters/interpreter_insert.rs
- src/query/service/src/pipelines/pipeline_builder.rs
- src/query/service/src/schedulers/fragments/query_fragment_actions.rs
- src/query/service/src/schedulers/scheduler.rs
This PR only adds a switch to enable profiling in cluster mode. It will be used to allow for distributed query profiling in the following work.
> chore(executor): Add a switch to enable profiling in cluster mode

- src/query/service/src/interpreters/interpreter_delete.rs
- src/query/sql/src/planner/binder/delete.rs
- src/query/sql/src/planner/format/display_plan.rs
- src/query/sql/src/planner/plans/delete.rs
- src/query/sql/src/planner/plans/mod.rs
- tests/sqllogictests/suites/mode/standalone/explain/delete.test
Before:
```
mysql> explain delete from t1 where a in (select b from t2) and a < 2;
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> feat: make explain delete work

- Cargo.lock
- Cargo.toml
- src/query/config/src/config.rs
- src/query/service/tests/it/configs.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
`alias` is not compatible with `flatten`, causing our config loading to break after updating serde. Pinning the serde version to `152` is not a viable solution as it would also affect many other projects that depend on serde.
This pull request removes all field aliases and instead inserts deprecated fields that will generate errors for users attempting to load the config.
> fix: Config not loaded after bump serde

- src/query/storages/fuse/src/operations/replace_into/mod.rs
- src/query/storages/fuse/src/operations/replace_into/mutator/merge_into_mutator.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0023_replace_into
while executing `replace into`, for data blocks that could not be pruned  by using range index,  this PR introduces an optimization similar to `prewhere`:
- first load the block data of columns  specified by the `on conflict` clause, and filter the rows
- only if rows of the block are partially deleted, we need to load the block data of other columns (if any), to generate the new block.
Closes #issue
> refactor: optimize replace into data block reading

- src/query/service/src/servers/mysql/mysql_interactive_worker.rs
- tests/sqllogictests/suites/query/issues/issue_11809.test
We will do some special checks for the queries from MySQL clients.
In case a query starts with some Unicode characters, e.g. comment like `--总共`, it may panic because of invalid index access of the string.
We may need a better way to skip the `INSERT` statement in the future.
Close #11809
> fix(planner): check unicode to prevent invalid string index access

- src/query/pipeline/sources/src/input_formats/impls/input_format_csv.rs
used in :
1. select $<column_position>
2. copy with on_error=continue
both need to tolerant more fields than expected, but too many fields maybe indicate something wrong in format options or the files. 
for CSV, this limitation also allows a more efficient implementation.
doc: https://github.com/datafuselabs/databend/pull/11813
reason
Closes #issue
> feat: CSV allow at most 1000 extra fields.

- src/common/io/src/cursor_ext/cursor_read_datetime_ext.rs
- tests/sqllogictests/suites/query/02_function/02_0012_function_datetimes_tz
* **Improved datetime handling** Added `LocalResult` import and replaced `unwrap()` method with `match` statement to handle DST and ambiguous local times.
* **Fixed syntax error and changed input format** Fixed syntax error in SELECT statement and changed input date format to timestamp using TO_TIMESTAMP function.
* **Returned current date and time** Returned the current date and time using TO_DATE function.
Closes #issue
> fix(query): consider DST when parse string to ts

- src/query/service/src/servers/http/middleware.rs
Currently the request log may print the headers into logs, this may introduce some security risks.
This PR sanitize the headers in the request log.
> fix: sanitize the headers in request log

- docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
> docs: support ON_ERROR=abort_N

- src/query/sql/src/planner/optimizer/heuristic/heuristic.rs
- src/query/sql/src/planner/optimizer/heuristic/prune_unused_columns.rs
- tests/sqllogictests/suites/mode/standalone/explain/lazy_read.test
`UnusedColumnPruner` should consider lazy columns and remove them from `require_columns`.
Closes #11831
> fix: consider lazy columns when pruning unused columns.

- src/query/storages/fuse/src/operations/mutation/mutation_source.rs
- tests/sqllogictests/suites/mode/cluster/distributed_delete.sql
Fix issue
- #11784 
Remove the internal column `row_id_col`  before performing row deletions, otherwise, the data block generated after deletion will be incorrect.
Closes #11784
> fix: deletion with sub query

- src/common/io/src/cursor_ext/cursor_read_string_ext.rs
- src/query/ast/src/parser/unescape.rs
- src/query/functions/tests/it/scalars/testdata/string.txt
- tests/sqllogictests/suites/base/03_common/03_0016_insert_into_values
- tests/sqllogictests/suites/base/03_common/03_0018_insert_into_variant
- tests/sqllogictests/suites/query/02_function/02_0023_function_strings_quote
- tests/sqllogictests/suites/query/02_function/02_0048_function_semi_structureds_parse_json
- tests/sqllogictests/suites/query/02_function/02_0051_function_semi_structureds_get
parse string ignores unescape `\"`, so that we can parse json string with `\"`.
for example 
```sql
mysql> select parse_json('"a\"b"');
+-----------------------+
| parse_json('"a\\"b"') |
+-----------------------+
| "a\"b"                |
+-----------------------+
1 row in set (0.04 sec)
```
Closes #issue
> fix(query): parse string ignores unescape `\"`

- src/query/catalog/src/table.rs
- src/query/sql/src/executor/physical_plan_builder.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/storages/fuse/src/fuse_table.rs
- src/query/storages/result_cache/src/table_function/table.rs
- tests/sqllogictests/suites/base/20+_others/20_0013_query_result_cache
Make `result_can_be_cached` as a property of the `Table` trait. And only result from fuse table can be cached now.
Closes #11820
> fix: only cache query result from fuse table.

- docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
Fixed file_format examples in COPY INTO.
Closes #issue
> docs: fix file_format for copy into

- Cargo.lock
- src/query/storages/common/cache/Cargo.toml
- src/query/storages/common/cache/src/providers/disk_cache.rs
- src/query/storages/common/cache/tests/it/providers/disk_cache.rs
chore: remove disk cache when query init
Closes #issue
> chore: remove disk cache when query init

- scripts/setup/dev_setup.sh
- scripts/setup/rust-toolchain.toml
- scripts/setup/rust-tools.txt
ci: Bump rust to latest toolchain
> ci: Bump rust to latest toolchain

- Cargo.lock
- src/query/pipeline/core/src/pipeline.rs
- src/query/pipeline/sources/Cargo.toml
- src/query/pipeline/sources/src/input_formats/impls/input_format_parquet.rs
- src/query/pipeline/sources/src/input_formats/input_format_text.rs
- src/query/pipeline/sources/src/input_formats/input_pipeline.rs
- src/query/pipeline/sources/src/input_formats/source_aligner.rs
- src/query/pipeline/sources/src/input_formats/transform_deserializer.rs
- src/query/service/src/api/rpc/exchange/exchange_sink.rs
- src/query/service/src/api/rpc/exchange/exchange_source.rs
- src/query/service/src/api/rpc/exchange/exchange_transform.rs
- src/query/service/src/interpreters/interpreter_index_refresh.rs
- src/query/service/src/pipelines/executor/pipeline_pushing_executor.rs
- src/query/service/src/pipelines/pipeline_builder.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_partition_bucket.rs
- src/query/service/tests/it/pipelines/executor/executor_graph.rs
- src/query/storages/fuse/src/operations/append.rs
- src/query/storages/fuse/src/operations/commit.rs
- src/query/storages/fuse/src/operations/compact.rs
- src/query/storages/fuse/src/operations/read/fuse_source.rs
- src/query/storages/fuse/src/operations/replace.rs
- src/query/storages/memory/src/memory_table.rs
- src/query/storages/parquet/src/parquet_table/read.rs
- src/query/storages/stage/src/stage_table.rs
copy used to use a channel to pass  row batch when there was no BlockMetaInfo, which is complicate and buggy.
Closes https://github.com/datafuselabs/databend/issues/10647
> refactor: copy use BlockMetaInfo to pass RowBatch.

- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state_impl.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/join_hash_table.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/result_blocks.rs
- src/query/service/src/pipelines/processors/transforms/transform_hash_join.rs
- tests/sqllogictests/suites/query/join.test
Continue: https://github.com/datafuselabs/databend/pull/11835
Closes #issue
> chore: fast path for left-related join if build side is empty

- Cargo.lock
- src/query/profile/src/prof.rs
- src/query/service/src/interpreters/interpreter_explain.rs
- src/query/service/src/pipelines/pipeline_builder.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_aggregate_final.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_group_by_final.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_partition_bucket.rs
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/sql/src/executor/format.rs
- src/query/sql/src/executor/physical_plan_builder.rs
- src/query/sql/src/executor/profile.rs
- src/query/storages/system/Cargo.toml
- src/query/storages/system/src/query_profile_table.rs
Improve table schema of `system.query_profile`.
Add the `operator_children` field to represent the topology relationship between plan operators.
Add the `operator_attribute` field to represent the attribute information of plan operators.
```
mysql> explain analyze select sum(a) from t group by a;
+--------------------------------------------------------------------------------------------------------------------------------------+
| explain                                                                                                                              |
+--------------------------------------------------------------------------------------------------------------------------------------+ …
```
> chore(planner): improve table schema of `system.query_profile`

- src/query/sql/src/planner/dataframe.rs
dataframe sort api need bind projection
Closes #issue
> fix(query): dataframe sort api need bind projection

- src/query/sql/src/planner/binder/select.rs
- tests/sqllogictests/suites/query/union.test
revert union part of https://github.com/datafuselabs/databend/pull/11349/
Closes #issue
> fix: union's schema type is invalid

- src/query/pipeline/transforms/src/processors/mod.rs
- src/query/pipeline/transforms/src/processors/profile_wrapper.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_sort.rs
- src/query/profile/src/proc.rs
- src/query/profile/src/prof.rs
- src/query/service/src/pipelines/pipeline_builder.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_partition_bucket.rs
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/sql/src/evaluator/block_operator.rs
- src/query/sql/src/executor/profile.rs
- src/query/storages/system/src/query_profile_table.rs
Part of #11874 
Add the following information to the query profile:
- input rows and bytes of an operator
- output rows and bytes of an operator
```myql
mysql> select * from system.query_profile;
+--------------------------------------+-------------+---------------+-------------------+----------------------------------------------------------------------------------------------------------------+--------------------------------+
| query_id                             | operator_id | operator_type | operator_children | execution_info                                                                                                 | operator_attribute             | …
```
> chore(planner): add more execution information in `system.query_profile`

- src/query/catalog/src/table.rs
- src/query/service/src/table_functions/async_crash_me.rs
- src/query/service/src/table_functions/infer_schema/infer_schema_table.rs
- src/query/service/src/table_functions/list_stage/list_stage_table.rs
- src/query/service/src/table_functions/numbers/numbers_table.rs
- src/query/service/src/table_functions/openai/ai_to_sql.rs
- src/query/service/src/table_functions/srf/range.rs
- src/query/service/src/table_functions/sync_crash_me.rs
- src/query/storages/fuse/src/fuse_table.rs
- src/query/storages/fuse/src/table_functions/clustering_information/clustering_information_table.rs
- src/query/storages/fuse/src/table_functions/fuse_blocks/fuse_block_table.rs
- src/query/storages/fuse/src/table_functions/fuse_segments/fuse_segment_table.rs
- src/query/storages/fuse/src/table_functions/fuse_snapshots/fuse_snapshot_table.rs
- src/query/storages/fuse/src/table_functions/fuse_statistics/fuse_statistic_table.rs
- src/query/storages/hive/hive/src/hive_table.rs
- src/query/storages/iceberg/src/table.rs
- src/query/storages/memory/src/memory_table.rs
- src/query/storages/null/src/null_table.rs
- src/query/storages/parquet/src/parquet_table/table.rs
- src/query/storages/random/src/random_table.rs
- src/query/storages/result_cache/src/table_function/table.rs
- src/query/storages/stage/src/stage_table.rs
- src/query/storages/system/src/log_queue.rs
- src/query/storages/system/src/table.rs
- src/query/storages/system/src/tracing_table.rs
> chore(query): fix typo

- src/query/storages/fuse/src/operations/read/fuse_rows_fetcher.rs
- src/query/storages/fuse/src/operations/read/native_rows_fetcher.rs
- src/query/storages/fuse/src/operations/read/parquet_rows_fetcher.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0025_lazy_read
The pipeline will panic because the number of columns is incorrect.
- Closes #11882
> fix: rows fetcher should complete the block if the input is empty.

- .github/workflows/release.yml
We assume that when tag exists, the corresponding release is already created manually.
> ci: only create release if tag not exists

- src/query/storages/fuse/src/operations/append.rs
- src/query/storages/parquet/src/parquet_reader/deserialize.rs
- src/query/storages/parquet/src/parquet_table/read.rs
1.  more sinks too  release memory faster
2.  assume more memory overhead per row group（x2）
cc @wubx 
> refactor: refine polices to prevent OOM when copy parquet with large  row groups.

- Cargo.lock
- src/query/service/src/interpreters/interpreter_explain.rs
- src/query/storages/result_cache/src/read/reader.rs
- tests/sqllogictests/suites/base/20+_others/20_0013_query_result_cache
- If the query will read result cache, we can get this information by `explain`.
- We can `explain pipeline` for all plans now, as we can get the pipeline by `interpreter.execute2`.
> feat: support explain query result cache reading.

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/schema/database.rs
- src/meta/app/src/schema/mod.rs
- src/meta/app/src/schema/table.rs
- src/query/service/src/catalogs/default/mutable_catalog.rs
feat: add arg in get_table_history to get all the drop tables
add `AllDroppedTables` option to get tables in drop db, and test cases.
> feat: add arg in get_table_history to get all the drop tables

- src/query/ee-features/aggregating-index/src/aggregating_index_handler.rs
- src/query/ee/src/aggregating_index/aggregating_index_handler.rs
- src/query/service/src/interpreters/interpreter_index_drop.rs
- src/query/service/src/interpreters/interpreter_index_refresh.rs
move refresh agg index to enterprise
> chore: move refresh agg index to enterprise

- src/query/expression/src/types/string.rs
- src/query/expression/src/values.rs
should not use `col.data.len()`, the `data` maybe shared(sliced).
> fix: wrong memory_size of StringColumn.

- src/query/sql/src/planner/binder/select.rs
- tests/sqllogictests/suites/mode/standalone/explain/lazy_read.test
- tests/sqllogictests/suites/query/cte.test
If there are derived columns in the select list‘s `used_columns`, we cannot use lazy materialization.
The derived columns may come from CTE (or others), we cannot build rows fetcher on them.
Closes #11974
> fix: if there are derived columns in the select list, we cannot use lazy materialization.

- src/common/metrics/src/lib.rs
- src/common/metrics/src/reset.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_aggregate_spill_writer.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_group_by_spill_writer.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_spill_reader.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_aggregate_partial.rs
- src/query/service/src/pipelines/processors/transforms/metrics/mod.rs
- src/query/service/src/pipelines/processors/transforms/metrics/transform_metrics.rs
- src/query/service/src/pipelines/processors/transforms/mod.rs
- src/query/storages/fuse/src/lib.rs
- src/query/storages/fuse/src/metrics/fuse_metrics.rs
- src/query/storages/system/src/metrics_table.rs
* **Metrics**: Added functions for incrementing various metrics related to transforms and spilling operations. Metrics are used to measure the time and size of write and read operations.
* **Fuse Metrics**: Removed unused `gauge` function and replaced `metrics_reset` with `reset_metrics` from `common_metrics` crate.
* **Metrics Table**: Added new module `metrics_table` to `system` crate, importing `reset_metrics` from `common_metrics` crate. Removed unused `metrics_reset` function and implemented `SyncSystemTable` trait for `MetricsTable` struct. Added `truncate` function to reset metrics using `reset_metrics`.
> feat: add metrics for spill

- src/meta/client/src/grpc_client.rs
- src/meta/service/src/meta_service/raftmeta.rs
- src/meta/service/tests/it/grpc/metasrv_connection_error.rs
- src/meta/service/tests/it/grpc/mod.rs
When a request is forwarded from a follower to the leader,
it should retry if a `NetworkError` is occurred.
In the case when the leader crashed, internal forwarding should retry
until a new leader is established.
Add tests to ensure meta-grpc-client survives crashed
nodes(leader/follower) and internal rpc survives crashed leader too.
> fix(meta-service): retry when forward-rpc fails

- src/query/ee/src/storages/fuse/operations/vacuum.rs
- src/query/storages/fuse/src/operations/gc.rs
add ignore_err in get_block_locations to avoid missing blocks and bloom indexes
> fix: add ignore_err in get_block_locations

- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_group_by_spill_writer.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_spill_reader.rs
- src/query/service/src/pipelines/processors/transforms/metrics/transform_metrics.rs
* add two new metrics: `aggregate_spill_data_deserialize_milliseconds` and `aggregate_spill_data_serialize_milliseconds`
> feat: add spill data de/se cost metrics

- src/common/base/src/lib.rs
- src/common/base/src/runtime/backtrace.rs
- src/common/base/src/runtime/mod.rs
- src/common/http/src/debug/stack.rs
- src/query/service/src/databases/system/system_database.rs
- src/query/service/src/table_functions/list_stage/table_args.rs
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/storages/system/src/backtrace_table.rs
- src/query/storages/system/src/lib.rs
Standalone only:
```
select * from system.backtrace
```
```
╼ <databend_query::servers::http::middleware::HTTPSessionEndpoint<poem::route::router::Route> as poem::endpoint::endpoint::Endpoint>::call::{{closure}} at src/query/service/src/servers/http/middleware.rs:191:5   └╼ <databend_query::servers::http::v1::http_query_handlers::query_handler as poem::endpoint::endpoint::Endpoint>::call::{{closure}}::query_handler::{{closure}} at src/query/service/src/servers/http/v1/http_query_handlers.rs:278:1      └╼ databend_query::servers::http::v1::query::http_query::HttpQuery::get_response_page::{{closure}} at src/query/service/src/servers/http/v1/query/http_query.rs:367:5         └╼ …
```
> feat: add system.backtrace table

- src/query/catalog/src/plan/partition.rs
- src/query/storages/system/src/backtrace_table.rs
- src/query/storages/system/src/table.rs
chore(query): read all node backtrace table info for cluster mode
> chore(query): read all node backtrace table info for cluster mode

- src/query/service/tests/it/storages/system.rs
- src/query/service/tests/it/storages/testdata/caches_table.txt
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/storages/system/src/backtrace_table.rs
- src/query/storages/system/src/caches_table.rs
- src/query/storages/system/src/metrics_table.rs
Cluster system tables:
* system.backtrace
* system.metrics
* system.caches
```
SELECT
*
FROM
system.caches
┌──────────────────────────────────────────────────────────────────────────────┐
│          node          │              name              │ num_items │  size  │
│         String         │             String             │   UInt64  │ UInt64 │
├────────────────────────┼────────────────────────────────┼───────────┼────────┤
│ BKMQbxhCoZO5yaGLrPG822 │ table_snapshot_cache           │         1 │      1 │
│ BKMQbxhCoZO5yaGLrPG822 │ table_snapshot_statistic_cache │         0 │      0 │
│ BKMQbxhCoZO5yaGLrPG822 │ segment_info_cache             │         2 │ 934730 │
│ BKMQbxhCoZO5yaGLrPG822 │ …
```
> feat: make system.caches/backtrace/metrics distributed and with node column

- src/common/openai/src/metrics.rs
* change openai metrics from gauge to counter, avoid reset by truncate system.metrics.
> chore: change openai metrics from gauge to counter

- src/common/storage/src/parquet.rs
- src/query/catalog/src/plan/datasource/datasource_info/parquet.rs
- src/query/pipeline/sources/src/input_formats/impls/input_format_parquet.rs
- src/query/service/src/servers/http/v1/query/page_manager.rs
- src/query/storages/parquet/src/parquet_part.rs
- src/query/storages/parquet/src/parquet_table/blocking.rs
- src/query/storages/parquet/src/parquet_table/non_blocking.rs
- src/query/storages/parquet/src/parquet_table/partition.rs
- src/query/storages/parquet/src/parquet_table/read.rs
- src/query/storages/parquet/src/parquet_table/table.rs
- src/query/storages/parquet/src/pruning.rs
@wubx hope this pr can further reduce the chance of OOM when loading parquet.
1. consider the memory already used.
2. small file can be as large as 100MB,  each ParquetSmallFilesPart should not be too large, let it be at most the largest of the normal  ParquetPart::RowGroup 
3. use compression ratio to estimate the uncompressed size of ParquetSmallFilesPart
4. consider the compressed size when calc num by memory limit,  there are cases the compression ratio is low.
> refactor: adjust calc of parallelism when load parquet.

- src/query/service/src/interpreters/interpreter_query_log.rs
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/storages/system/src/log_queue.rs
- src/query/storages/system/src/query_log_table.rs
* make system.query_log distributed, query any node will return the cluster query logs, it will be easier for users to collect the query logs
* add `node_id` new column to query_log
> feat: make the system.query_log distributed

- src/query/service/src/interpreters/access/management_mode_access.rs
SHOW ROLES is expected to be allowed in the management mode. but currently we'd get this issue if we try SHOW ROLES on management mode:
```
uery error: code: 1062, message: Access denied for operation:Ok(\"ShowRolesPlan\") in management-mode
```
> fix: allow SHOW ROLES in management mode

- src/query/config/src/inner.rs
this PR added a `sanitize` method on Debug for `QueryConfig` to avoid leak the business license or openai keys, etc.
> fix: sanitize the sensitive logs on the query instance start up

- src/query/storages/common/index/src/bloom_index.rs
- src/query/storages/common/index/tests/it/filters/bloom_filter.rs
If the average length of the string column exceeds 256 bytes, the bloom index for the column will not be established.
> chore(storage): add length check for string column in bloom index

- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/02_function/02_0051_function_semi_structureds_get
fix subquery json pushdown without table name
related #12045
> fix(query): fix subquery json pushdown without table name

- src/query/storages/fuse/src/operations/agg_index_sink.rs
- tests/sqllogictests/suites/ee/02_ee_aggregating_index/02_0000_agg_index_base
`consume` should return false to prevent early finish.
Big thanks @zhang2014 for the co-debug.
> fix: fix refresh index sink bug

- src/meta/service/src/meta_service/raftmeta.rs
```json
{
"id": 0,
"binary_version": "v1.2.9-nightly-88696aafc66f937e08e0f8465718592ef3dec4c9-simd(1.72.0-nightly-2023-07-25T02:04:35.187965000Z)",
"data_version": "V001",
}
```
> feat(meta-binary): return binary_version and data_version in admin API v1/cluster/status

- docs/doc/14-sql-commands/10-dml/dml-insert.md
- docs/doc/14-sql-commands/10-dml/dml-replace.md
- docs/doc/14-sql-commands/20-query-syntax/01-query-select.md
Removed cross-reference links that block the sync to Databend Cloud documentation. @flaneur2020 
> docs: remove cross-reference links

- src/query/service/src/pipelines/processors/transforms/hash_join/common.rs
- src/query/sql/src/executor/physical_join/hash_join.rs
- tests/sqllogictests/suites/mode/standalone/ee/explain
- tests/sqllogictests/suites/mode/standalone/explain/bloom_filter.test
- tests/sqllogictests/suites/mode/standalone/explain/explain.test
- tests/sqllogictests/suites/mode/standalone/explain/limit.test
- tests/sqllogictests/suites/mode/standalone/explain/subquery.test
- tests/sqllogictests/suites/mode/standalone/explain_native/limit.test
- tests/sqllogictests/suites/mode/standalone/explain_native/subquery.test
If the join type is left single, the `Datablock` on the build side of the hash join need to be Nullable.
> chore: fix left single join

- Cargo.lock
- src/query/constraint/Cargo.toml
- src/query/sql/Cargo.toml
chore: Bump z3 to remove build time warning
This PR will remove the warning during build time like the following:
```shell
warning: the following packages contain code that will be rejected by a future version of Rust: nom v5.1.2
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 2`
```
> chore: Bump z3 to remove build time warning

- src/query/sql/src/planner/binder/aggregate.rs
- src/query/sql/src/planner/binder/binder.rs
- src/query/sql/src/planner/binder/project.rs
- src/query/sql/src/planner/binder/sort.rs
For derived column, it doesn't have `database_name`, `table_name`, `table_index`, so let's simplify the method
> chore: refine `create_column_binding` method

- src/query/expression/src/evaluator.rs
When the block is large, the panic message will occupy the whole screen and be useless. I think the main usage is to check data type, so remove block from the panic message.
> chore: remove block from panic message

- src/meta/api/src/schema_api_impl.rs
chore: when vacuum dropped table, ignore when TableIdToName data not exist
> chore: when vacuum dropped table, ignore when TableIdToName data not exist

- src/query/service/src/pipelines/pipeline_builder.rs
- src/query/service/src/pipelines/processors/transforms/transform_materialized_cte.rs
- src/query/sql/src/executor/physical_plan.rs
- src/query/sql/src/executor/physical_plan_builder.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/sql/src/planner/optimizer/heuristic/prune_unused_columns.rs
- src/query/sql/src/planner/plans/cte_scan.rs
Follow up https://github.com/datafuselabs/databend/pull/12090
Prune unused columns for CteScan to reduce data block transfer which can bring potential performance improvement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12227)
> chore: prune columns for `CteScan`

- src/query/service/tests/it/storages/fuse/statistics.rs
- src/query/storages/fuse/src/statistics/reducers.rs
- src/query/storages/fuse/src/table_functions/fuse_blocks/fuse_block.rs
- src/query/storages/fuse/src/table_functions/fuse_columns/fuse_column.rs
- src/query/storages/fuse/src/table_functions/fuse_segments/fuse_segment.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0006_func_fuse_history
1. fix segment cluster statistics maybe enlarged when the table contain multi cluster keys
```
mysql> create table t(a int, b int) cluster by(a,b);
Query OK, 0 rows affected (0.07 sec)
mysql> insert into t values(1,4);
Query OK, 1 row affected (0.11 sec)
mysql> insert into t values(3,2);
Query OK, 1 row affected (0.11 sec)
mysql> optimize table t compact segment;
Query OK, 0 rows affected (0.10 sec)
```
The segment's cluster_statistics should be `{min: (1,4), max: (3,2)}`, but get `{min: (1,2), max: (3,4)}`
2. fix fuse_block/fuse_segment/fuse_column maybe panic bug.
```
Query OK, 0 rows affected (0.12 sec)
mysql> insert into t select number from numbers(12);
Query OK, …
```
> fix(storage): segment cluster statistics maybe enlarged

- src/query/storages/fuse/src/operations/replace_into/mutator/merge_into_mutator.rs
during execution of `replace-into` statement, value feed to  `metrics_inc_replace_block_number_after_pruning` should be the number of blocks left after pruning, not the number of segments left.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12229)
> fix: metrics_inc_replace_block_number_after_pruning

- Cargo.lock
- src/query/service/src/interpreters/common/metrics.rs
- src/query/service/src/interpreters/interpreter_replace.rs
- src/query/storages/fuse/src/metrics/fuse_metrics.rs
- src/query/storages/fuse/src/operations/replace_into/mutator/merge_into_mutator.rs
- src/query/storages/fuse/src/operations/replace_into/processors/processor_replace_into.rs
to better investigate the execution time of `replace into` performance, to following metrics added
- replace_into_time_execution_ms
time used by executing the whole replace-into statement (including compact and re-cluster)
- replace_into_time_mutation_ms
time used in executing the mutation (upsert) part of the replace-into statement
- replace_into_time_process_input_block_ms
time used in processing the input block
- replace_into_time_accumulated_merge_action_ms
time used in executing the accumulated_merge_action operation 
- replace_into_time_apply_deletion_ms
time used in executing the accumulated_merge_action operation 
- replace_into_number_accumulated_merge_action
the number of …
> chore: more metrics of `replace-into`

- Cargo.lock
- src/common/cache/Cargo.toml
- src/common/cache/src/cache/lru.rs
- src/common/cache/src/lib.rs
- src/query/storages/common/cache/src/providers/disk_cache.rs
- src/query/storages/common/cache/src/providers/memory_cache.rs
ritelinked and the upstream griddle have been abandoned. Let's migrate to hashlink.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12254)
> refactor: replace ritelinked with hashlink

- src/query/storages/parquet/src/parquet_reader.rs
- src/query/storages/parquet/src/parquet_rs/parquet_reader/reader.rs
- src/query/storages/parquet/src/processors/deserialize_transform.rs
part of https://github.com/datafuselabs/databend/issues/12245
this refactor only impl the mechanism, still read as one block.
need a police to choose a suitable batch_size in next pr.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12309)
> feat: allow read one row_group to multi Datablock.

- src/query/service/src/interpreters/access/privilege_access.rs
`SET ROLE` is a session-local statement (have same semantic with the `SET ROLE` in postgres: https://www.postgresql.org/docs/current/sql-set-role.html), it's not considered to be protected via the `GRANT` privilege.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12330)
> fix(rbac): do not check the privilege about SET ROLE

- src/query/catalog/src/table_context.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/tests/it/storages/fuse/operations/commit.rs
- src/query/storages/system/src/columns_table.rs
- src/query/storages/system/src/databases_table.rs
- src/query/storages/system/src/tables_table.rs
Currently the visibility check takes one user's granted roles and related roles. There's a minor difference between taking the currnet_available_roles:
On the case of external user authentication, the `role` is authenticated from the JWT token, but not the user's grant set. `get_current_available_roles` handles this behaviour, and collected the related roles together.
This PR also introduced a `GrantObjectVisibilityChecker` struct which may help reduce some duplicated logic among `tables_table.rs` `columns_table.rs` and `databases_table.rs`.
- - - …
> fix(rbac): let visibility check take current_available_roles as parameter

- Cargo.lock
- src/binaries/Cargo.toml
- src/binaries/metabench/main.rs
- src/meta/service/src/meta_service/raftmeta.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_api.rs
- src/meta/types/src/errors/meta_api_errors.rs
When starting up more than one uninitialized meta-nodes, there is
chance a node fails to start up because:
- concurrent node-registering to the cluster with `Raft::change_membership()`,
- and `databend-meta` does not deal with `ChangeMembershipError`.
In this patch `ChangeMembershipError` is caught and the registering-node
is retried, which make bringing up 3 empty meta node without problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12359)
> refactor(databend-meta): retry when change-membership error encountered upon startup

- src/query/service/src/interpreters/interpreter_catalog_show_create.rs
- src/query/service/src/interpreters/interpreter_factory.rs
- src/query/service/src/interpreters/mod.rs
- src/query/sql/src/planner/binder/ddl/catalog.rs
- src/query/sql/src/planner/plans/plan.rs
- tests/suites/1_stateful/10_iceberg/10_0000_create_and_show.result
- tests/suites/1_stateful/10_iceberg/10_0000_create_and_show.sh
Add a new SQL command `SHOW CREATE CATALOG`.
Usage:
```
> CREATE CATALOG iceberg_test
TYPE=ICEBERG
CONNECTION=(
URL='s3://testbucket/iceberg_test/'
AWS_KEY_ID='minioadmin'
AWS_SECRET_KEY='minioadmin'
ENDPOINT_URL='http://127.0.0.1:9000'
);
> SHOW CREATE catalog iceberg_test;
┌──────────────────────────────────────────────────────────────────────────────────────────────┐
│    Catalog   │   Type  │                                Option                               │
│    String    │  String │                                String                               │
├──────────────┼─────────┼─────────────────────────────────────────────────────────────────────┤
│ iceberg_test │ iceberg │ STORAGE PARAMS …
```
> feat: new SQL command `SHOW CREATE CATALOG`.

- Cargo.lock
- src/common/tracing/src/minitrace.rs
`tracing_appender::non_blocking()` will drop log messages if the channel
is full. Replace it with a `BufWriter<_>`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12385)
> fix(logging): log messages are lost with heavy load

- website/package.json
For the sake of document collaboration, we need to reintegrate Crowdin into our workflow.
Uploading translations needs to be integrated with Vercel builds to ensure that the latest content is always synchronized with Crowdin.
As we are not currently maintaining multilingual documents, downloading translations is for demonstration purposes only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12379)
> docs(website): add translation upload and download cmd

- src/query/sql/src/planner/optimizer/property/selectivity.rs
- src/query/sql/src/planner/plans/filter.rs
- src/query/sql/src/planner/plans/scan.rs
- tests/sqllogictests/suites/mode/standalone/explain/eliminate_outer_join.test
- tests/sqllogictests/suites/mode/standalone/explain/explain.test
- tests/sqllogictests/suites/mode/standalone/explain/join.test
- tests/sqllogictests/suites/tpch/queries.test
We update ndv in `update_other_statistic_by_selectivity`, currently ndv is multiplied by selectivity twice, but once is correct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12387)
> chore(planner): fix filter derive cardinality

- src/query/catalog/src/table_context.rs
- src/query/service/src/api/http/v1/instance_status.rs
- src/query/service/src/api/http/v1/processes.rs
- src/query/service/src/sessions/session_info.rs
- src/query/service/src/sessions/session_mgr.rs
- src/query/service/src/sessions/session_mgr_status.rs
- src/query/storages/system/src/processes_table.rs
I'm using /v1/status in to detect inactive query instances. There're few cases about the `running_queries_count > 0` but they are actually in "Idle" state. If a query instance is full of Idle sessions, it's actually safe to shutdown it to reduce cost.
This PR filtered out the `Idle` sessions in the `running_queries_count` field, and added another `active_sessions_count` field to represent the active connections count.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12384)
> feat: seperate running_queries_count and active_sessions_count in /v1/status

- docs/doc/14-sql-commands/00-ddl/102-mask-policy/create-mask-policy.md
- docs/doc/14-sql-commands/00-ddl/102-mask-policy/desc-mask-policy.md
- docs/doc/14-sql-commands/00-ddl/102-mask-policy/drop-mask-policy.md
- docs/doc/14-sql-commands/00-ddl/20-table/90-alter-table-column.md
- src/common/exception/src/exception_code.rs
- src/meta/app/src/app_error.rs
- src/meta/app/src/data_mask/mod.rs
- src/query/ast/src/ast/statements/data_mask.rs
- src/query/ast/src/parser/data_mask.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
- src/query/service/src/interpreters/interpreter_table_modify_column.rs
- src/query/sql/src/planner/binder/ddl/data_mask.rs
- tests/sqllogictests/suites/base/05_ddl/05_0001_ddl_create_database
- tests/sqllogictests/suites/ee/05_ee_ddl/05_0001_ddl_data_mask
- tests/suites/5_ee/02_data_mask/02_0000_data_mask.py
1. rename RETURN to RETURNS in masking policy rule; 
2. check masking policy rule input type and return type, add test case.
3. refactor error code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12406)
> chore: rename RETURN to RETURNS in masking policy rule; check masking policy rule input type and return type

- src/query/storages/fuse/src/io/read/bloom/block_filter_reader.rs
- src/query/storages/fuse/src/operations/replace_into/mutator/deletion_accumulator.rs
- src/query/storages/fuse/src/operations/replace_into/mutator/merge_into_mutator.rs
reorder the bloom filters according to the order of columns being pruned,  during execution of  bloom pruning in replace-into statement.
The order of bloom filters returned by `read_block_filter` may not be the same with columns passed into. (in fact, the number of filters returned may be less than the number of columns, if there were duplicated columns passed in).
thus, during bloom pruning of `replace-into`, if incorrect bloom filter is used, blocks may be pruned incorrectly,  and left duplicated rows in target table. (but no rows will be removed incorrectly).
- - - …
> fix: bloom pruning of `replace-into` may use incorrect bloom filter

- Cargo.lock
- src/query/ast/src/ast/statements/replace.rs
correct the formatting of `ReplaceStmt`,  
- show the correct on-conflict fields
- tweak the formats (adding and removing spaces)
e.g.
sql `replace into t (c, c1, c2) on(c) values (1,2,3)`
logged as
~~~
"query_text":"REPLACE INTO t(c, c1, c2) ON CONFLICT(c) VALUES (1,2,3)"
~~~
- Closes #12399
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12419)
> fix:  "Display" of "ReplaceStmt"

- src/query/catalog/src/table.rs
- src/query/storages/fuse/src/fuse_table.rs
remove  deprecated table method  `Table::replace_into`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12430)
> chore: remove deprecated table method `Table::replace_into`

- src/query/storages/fuse/src/operations/replace_into/mutator/merge_into_mutator.rs
doc bloom pruning in `replace into`.
just comments and renaming vars.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12431)
> chore: doc bloom pruning in `replace into`

- src/query/config/src/config.rs
- src/query/config/src/inner.rs
- src/query/service/tests/it/configs.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
- src/query/storages/common/cache-manager/src/cache_manager.rs
- introduce new config `table_bloom_index_filter_size`, which set the max bytes that the bloom filter cache used.
by default, the size is set to 2G (in bytes).
during the construction of the bloom filter cache, the new config will be used.
- config option `table_bloom_index_filter_size` is in the state of "deprecating", which will not be consulted during initialization of the bloom filter cache, but need not be removed from the config files (if it is explicitly specified in user's config files).
this config option is planned to be deprecated in the next stable release, and users may need to remove this option from config files if specified, otherwise, the query node will refuse to start.
- Closes …
> feat: introduce new config `table_bloom_index_filter_size`

- scripts/setup/dev_setup.sh
refactor: Remove thrift from dev_setup
We don't need to install thrift anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12436)
> refactor: Remove thrift from dev_setup

- src/query/expression/src/block.rs
- Closes #12445
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12446)
> fix: memory leak in unsafe code

- src/query/storages/common/table-meta/benches/bench.rs
- src/query/storages/common/table-meta/src/meta/v4/segment.rs
benchmark of unpacking `CompactSegmentInfo`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12457)
> chore:  bench  unpacking `CompactSegmentInfo`

- src/query/expression/src/evaluator.rs
- src/query/expression/src/utils/mod.rs
- src/query/expression/src/utils/variant_transform.rs
- src/query/expression/src/values.rs
- tests/sqllogictests/suites/udf-server/udf_server_test
- tests/udf-server/README.md
- tests/udf-server/udf.py
- tests/udf-server/udf_test.py
Part of #12177.
In this PR, we support all data types in databend except `BITMAP` for UDF Server.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12463)
> feat: support more data types for UDF Server

- src/query/service/src/interpreters/access/privilege_access.rs
The SHOW ROLES statement displays the available roles for the current session. It's available for every one, do not require the GRANT privilege.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12478)
> fix(rbac): do not require GRANT privilege on SHOW ROLES statement

- src/query/storages/system/src/background_jobs_table.rs
fix background_jobs panic
```sql
mysql> select * from system.background_jobs;
ERROR 1105 (HY000): PanicError. Code: 1104, Text = assertion failed: columns.iter().all(|c| c.len() == num_rows).
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12488)
> fix(storage): fix background_jobs panic

- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
The PR spilt `HashJoinStep` into `HashJoinBuildStep` and `HashJoinProbeStep`, to make it clear.
Add some comments for thoes steps.
In the future, we'll add more spilling-related steps to them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12501)
> chore: spilt `HashJoinStep` into `HashJoinBuildStep` and `HashJoinProbeStep`

- .github/actions/build_linux/action.yml
- .github/actions/build_macos/action.yml
- .github/actions/check/action.yml
- .github/actions/test_unit/action.yml
- Closes #10466
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12504)
> chore(ci): cargo build with -Zgitoxide

- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
adjust  MAX_COPIED_FILES_NUM (from 500) to 2000
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12506)
> chore: adjust MAX_COPIED_FILES_NUM (from 500) to 2000

- src/query/service/src/interpreters/interpreter_catalog_show_create.rs
```SQL
--- without storage params
CREATE CATALOG ctl TYPE=HIVE CONNECTION=(ADDRESS='127.0.0.1:9083');
--- with storage params
CREATE CATALOG ctl2 TYPE = HIVE CONNECTION =(
ADDRESS = '127.0.0.1:9083' URL = 's3://warehouse/' AWS_KEY_ID = 'admin' AWS_SECRET_KEY = 'password' ENDPOINT_URL = 'http://localhost:9000/'
)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12516)
> chore: add storage params to show create hive catalog

- Cargo.lock
- Cargo.toml
- Fix: #12513
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12520)
> refactor: upgrade minitrace to 0.5.1

- src/common/cache/src/cache.rs
- src/common/cache/src/cache/lru.rs
- src/common/cache/tests/it/cache/lru.rs
In the `Cache` trait, the `get_mut()` and `peek_mut()` methods return
mutable references that permit users to modify the stored value.
However, when the updated value is given back into the cache, the
eviction policy determined by `Meter` is not validated against these
changes. This could potentially lead to risks, such as the cache
surpassing its maximum capacity.
Given that these two APIs are currently unused, my suggestion is to
remove them to prevent potential misuse in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12519)
> refactor: eliminate ambiguous cache API

- src/binaries/query/entry.rs
- src/query/config/src/config.rs
- src/query/config/src/inner.rs
- src/query/service/src/clusters/cluster.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
today I met an issue that it takes a long period for a new databend-query instance to get ready for new connections:
as the logs shows, it toke 2 minutes to finally get a timeout on create a new rpc client.
this pr try to fix this hanging issue by adding a timeout config
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12529)
> feat(cluster): allow specify a client timeout on creating flight client

- src/query/ast/src/ast/format/ast_format.rs
- src/query/ast/src/ast/format/syntax/query.rs
- src/query/ast/src/ast/query.rs
- src/query/ast/src/parser/query.rs
- src/query/ast/src/visitors/walk.rs
- src/query/ast/src/visitors/walk_mut.rs
- src/query/ast/tests/it/testdata/query.txt
- src/query/catalog/src/plan/projection.rs
- src/query/sql/src/planner/binder/mod.rs
- src/query/sql/src/planner/binder/select.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/sql/src/planner/binder/values.rs
- Remove values from `TableReference` to simplify repetitive code and turn the Values source into a Subquery
- Add example comments for `Projection::InnerColumns`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12528)
> refactor: Remove values from TableReference

- docs/doc/13-monitor/10-metasrv-metrics.md
- docs/doc/14-sql-commands/00-ddl/20-table/90-alter-table-column.md
ALTER TABLE [IF EXISTS] [database.]<table_name> 
MODIFY COLUMN <column_name> <new_data_type> [DEFAULT <constant_value>][, COLUMN <column_name> <new_data_type> [DEFAULT <constant_value>], ...]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12558)
> docs: set default value on modifying column type

- src/binaries/query/ee_main.rs
- src/binaries/query/entry.rs
- src/binaries/query/oss_main.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12561)
> refactor: do not continue if query just runs cli command with `--cmd`

- docs/doc/14-sql-commands/00-ddl/70-clusterkey/dml-recluster-table.md
- docs/doc/15-sql-functions/111-system-functions/clustering_information.md
- src/query/storages/fuse/src/table_functions/clustering_information/clustering_information.rs
```sql
select * from clustering_information('default','t')\G
*************************** 1. row ***************************
cluster_key: ((a + 1))
total_block_count: 3
constant_block_count: 1
unclustered_block_count: 0
average_overlaps: 1.3333
average_depth: 2.0
block_depth_histogram: {"00002":3}
```
- Closes #12598
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12600)
> chore: rename cluster_by_keys to cluster_key

- docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
- website/yarn.lock
after https://github.com/datafuselabs/databend/pull/12594
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12605)
> docs: output of COPY INTO TABLE.

- Cargo.lock
- src/query/service/src/test_kits/table_test_fixture.rs
- src/query/service/tests/it/main.rs
- src/query/service/tests/it/storages/fuse/operations/mutation/block_compact_mutator.rs
- src/query/service/tests/it/storages/fuse/operations/mutation/recluster_mutator.rs
- src/query/service/tests/it/storages/fuse/operations/mutation/segments_compact_mutator.rs
- src/query/service/tests/it/storages/fuse/table.rs
- src/query/storages/fuse/Cargo.toml
- src/query/storages/fuse/src/operations/common/processors/transform_mutation_aggregator.rs
- src/query/storages/fuse/src/operations/mutation/mod.rs
- src/query/storages/fuse/src/operations/mutation/recluster_aggregator.rs
- src/query/storages/fuse/src/operations/mutation/recluster_mutator.rs
- src/query/storages/fuse/src/operations/recluster.rs
- src/query/storages/fuse/src/pruning/fuse_pruner.rs
- src/query/storages/fuse/src/pruning/mod.rs
- src/query/storages/fuse/src/table_functions/clustering_information/clustering_information.rs
Execute process:
1. read out a batch of segments (1000) .
2. based on the cluster stats of segment level, calculate and select the segments with the highest depth (limit max_threads * 4).
3. read the blocks, select the ones with the highest depth, and record the segments in which those blocks are located. 
4. do a recluster on the selected blocks to generate new blocks.
5. Sort the new blocks with the remaining blocks in the segments recorded in step 3, and generate new segments. 
6. In order to maintain the initial order as much as possible, replace the positions of the segments recorded in step 3 in the base snapshot with the newly generated segments. The extra newly generated segments are …
> refactor(storage): recluster with segment cluster stat

- src/query/service/src/servers/http/http_services.rs
- src/query/service/src/servers/http/metrics.rs
- src/query/service/src/servers/http/middleware.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
this pr add metrics for both errors & panics on query executions, thus may makes us easier to found out unexpected issues as fast as possible.
Closes #12628
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12629)
> feat(http): add metrics on panics & query

- src/query/catalog/src/plan/projection.rs
- src/query/catalog/tests/it/projection.rs
- src/query/ee/tests/it/aggregating_index/index_scan.rs
- src/query/storages/parquet/src/parquet2/parquet_table/read.rs
- src/query/storages/parquet/src/parquet2/pruning.rs
- src/query/storages/parquet/src/parquet_part.rs
- src/query/storages/parquet/src/parquet_rs/parquet_reader.rs
- src/query/storages/parquet/src/parquet_rs/parquet_table/partition.rs
- src/query/storages/parquet/src/parquet_rs/parquet_table/read.rs
- src/query/storages/parquet/src/parquet_rs/partition.rs
- src/query/storages/parquet/src/parquet_rs/pruning.rs
- src/query/storages/parquet/src/parquet_rs/source.rs
- src/query/storages/parquet/tests/it/parquet_rs/prune_pages.rs
- tests/suites/1_stateful/00_copy/00_0006_small_parquet.result
- tests/suites/1_stateful/00_copy/00_0006_small_parquet.sh
- Collect small parquet files. Read them together to reduce IO numbers.
- Estimate memory consumption and adjust pipeline parallelism to avoid OOM.
Tracking in #12465
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12637)
> feat: parquet_rs supports small files reading 

- docs/doc/12-load-data/00-transform/06-querying-metadata.md
- docs/doc/14-sql-commands/10-dml/dml-insert.md
- docs/doc/14-sql-commands/10-dml/dml-replace.md
- docs/doc/90-contributing/01-rfcs/20220704-presign.md
- src/query/service/src/servers/http/v1/stage.rs
- tests/suites/1_stateful/00_copy/00_0011_distributed_copy_into_table_exection_test.sh
- tests/suites/1_stateful/01_load/01_0001_upload_to_stage.sh
- tests/suites/1_stateful/09_http_handler/09_0002_query_log.sh
having underscore in the http header seems to be not HTTP standard, and easy to get troubles on various HTTP proxies like nginx.
this PR makes `upload_to_stage` also accepts `stage-name` and `x-databend-stage-name` as arguments, and adjusted the related docs to encourage using `stage-name` instead of `stage_name`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12656)
> chore(http): both accept stage_name and stage-name as args on upload_to_stage

- src/query/settings/src/settings_getter_setter.rs
fix typo of setting name, `repalce` should be `replace`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12730)
> chore: fix typo of setting name, `repalce` should be `replace`

- src/query/storages/parquet/src/parquet2/processors/deserialize_transform.rs
skip empty small files while deserializing parquet files.
- Closes #12725
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12726)
> fix: skip empty small files while deserializing parquet

- src/meta/raft-store/src/sm_v002/leveled_store/level_data.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_store_test.rs
- src/meta/raft-store/src/sm_v002/leveled_store/map_api.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/sm_v002_test.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002_test.rs
MapApi provides state machine read write APIs.
In order to distinguish between active memtable and read-only(static)
table(in memory or on-disk), `MetaApi` is split into a readonly API set
`MapApiRO` and the complete read-write API set `MapApi: MapApiRO`.
`MapApiRO` defines two methods `get()` and `range()`, while `MapApi`
provides `set()` methods.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12732)
> refactor: meta/state-machine: extract MapApiRO from MapApi

- Cargo.lock
- src/common/exception/Cargo.toml
chore: update backtrace to 0.3.69
- Closes https://github.com/datafuselabs/databend/issues/12612
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12751)
> chore: update backtrace to 0.3.69

- src/meta/raft-store/src/applier.rs
- src/meta/raft-store/src/sm_v002/leveled_store/level_data.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_store_test.rs
- src/meta/raft-store/src/sm_v002/leveled_store/map_api.rs
- src/meta/raft-store/src/sm_v002/marked/marked_test.rs
- src/meta/raft-store/src/sm_v002/marked/mod.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/sm_v002_test.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002_test.rs
In order to adapt to the on-disk map API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12761)
> refactor: change state machine api from ref based to value based

- Cargo.lock
- src/query/service/Cargo.toml
in opensrv-mysql v0.4.1, we fixed a memory safety issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12766)
> chore: bump opensrv-mysql to v0.4.1

- src/query/catalog/src/plan/partition.rs
- src/query/catalog/tests/it/partitions.rs
- src/query/catalog/tests/it/testdata/partition-reshuffle.txt
- src/query/service/src/schedulers/fragments/plan_fragment.rs
parts_per_executor = num_parts / num_executors
remain = num_parts % num_executors
part distribution:
| executor number| Part number of each executor |
| :---         |     :---:      |
| remain | parts_per_executor + 1 |
| num_executors - remain | parts_per_executor  |
For 10 partitions of 3 executors, the reshuffle result:
```
Before: [4,4,2]
Now:    [3,3,4]
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12784)
> chore: change partition reshuffle logic

- .github/actions/build_linux/action.yml
- .github/actions/setup_bendsql/action.yml
- .github/actions/test_sqllogic_stage/action.yml
- .github/workflows/cancel.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/reuse.benchmark.yml
- .github/workflows/reuse.linux.yml
- docs/doc/12-load-data/00-transform/07-data-load-transform.md
- docs/doc/13-integrations/mindsdb.md
- docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
- docs/doc/21-use-cases/01-analyze-ontime-with-databend-on-ec2-and-s3.md
- docs/doc/21-use-cases/05-analyze-hits-dataset-with-databend.md
- scripts/benchmark/run-meta-benchmark.sh
- scripts/ci/deploy/databend-query-cluster-3-nodes.sh
- scripts/ci/deploy/databend-query-management-mode.sh
- scripts/ci/deploy/databend-query-sharing.sh
- scripts/ci/deploy/databend-query-standalone-hive.sh
- scripts/ci/deploy/databend-query-standalone-native.sh
- scripts/ci/deploy/databend-query-standalone.sh
- tests/compat/test-compat.sh
- tests/fuse-compat/util.sh
- tests/meta-cluster/test-meta-cluster.sh
- tests/sqllogictests/scripts/prepare_stage.sh
- tests/sqllogictests/scripts/prepare_tpcds_data.sh
- tests/sqllogictests/scripts/prepare_tpch_data.sh
- tests/sqllogictests/suites/stage/copy_from_http
- tests/suites/1_stateful/04_mini_dataset/04_0000_mini_ontime.sh
- tests/suites/1_stateful/04_mini_dataset/04_0001_mini_hits.sh
- website/blog/2022-08-18-new-release.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12796)
> chore: adjust datasets for ci

- src/meta/raft-store/src/sm_v002/importer.rs
- src/meta/raft-store/src/sm_v002/leveled_store/level.rs
- src/meta/raft-store/src/sm_v002/leveled_store/level_data.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map_test.rs
- src/meta/raft-store/src/sm_v002/leveled_store/meta_api.rs
- src/meta/raft-store/src/sm_v002/leveled_store/static_leveled_map.rs
- src/meta/raft-store/src/sm_v002/leveled_store/util.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/sm_v002_test.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002_test.rs
Using a `Vec<Arc<LevelData>>` simplifies kway-merge.
And it adds flexibility to manage different types of `MapApi`
implementation.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12772)
> refactor: let Level manage multi level data instead of using a chain of Arc

- src/query/expression/src/type_check.rs
- src/query/functions/src/aggregates/aggregate_array_moving.rs
- src/query/functions/src/aggregates/aggregate_bitmap.rs
- src/query/functions/src/aggregates/aggregate_quantile_cont.rs
- src/query/functions/src/aggregates/aggregate_quantile_disc.rs
- src/query/functions/src/aggregates/aggregate_quantile_tdigest.rs
- src/query/functions/src/aggregates/aggregate_window_funnel.rs
- src/query/service/src/table_functions/numbers/numbers_table.rs
- src/query/service/src/table_functions/srf/range.rs
- src/query/sql/src/planner/semantic/type_check.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
- src/tests/sqlsmith/src/sql_gen/query.rs
- src/tests/sqlsmith/src/sql_gen/sql_generator.rs
- tests/sqllogictests/suites/query/02_function/02_0000_function_aggregate_mix
1. Generate Aggregate functions
2. Fix  #12782. : check_number() has already cast the expr internal. So there is no need to cast any more during external calls
- Closes #12782
- Part of  #12576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12783)
> feat(sqlsmith): add gen_agg_func

- src/query/sql/src/planner/binder/bind_context.rs
- src/query/sql/src/planner/binder/delete.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/sql/src/planner/binder/update.rs
- tests/sqllogictests/suites/base/03_common/03_0025_delete_from
```
mysql> delete from t where _row_id=1;
ERROR 1105 (HY000): SemanticError. Code: 1065, Text = Internal column `_row_id` is not allowed in current statement.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12833)
> fix: delete contain internal columns panic

- src/query/expression/src/kernels/sort.rs
- src/query/functions/tests/it/scalars/array.rs
- src/query/functions/tests/it/scalars/testdata/array.txt
- tests/sqllogictests/suites/query/02_function/02_0061_function_array
When the sorted array is an empty array or the sorted content is null, DataBlock::sort() will return Err. In such cases, unwrapping directly is not possible and requires handling.
- Closes #12718
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12827)
> fix: fix_sort_null_panic

- src/binaries/metabench/main.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/api/src/share_api_test_suite.rs
- src/meta/api/src/util.rs
- src/meta/app/src/schema/database.rs
- src/meta/app/src/schema/table.rs
- src/query/service/src/interpreters/interpreter_table_drop.rs
- src/query/service/src/interpreters/interpreter_view_alter.rs
- src/query/service/src/interpreters/interpreter_view_drop.rs
- src/query/service/tests/it/catalogs/database_catalog.rs
When dropping a table, it needs to update the count of all tables
belonging to a `tenant`.
Before this commit, it loads the `tenent` from a reversed mapping from
`database-id` to `tenant`.
In this commit, `tenent` is passed in to `schema-api` by callers.
So that when the reversed mapping is lacking(old data), it won't return
an UnknownDatabaseId error.
- Bug Fix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12847)
> fix: avoid relying on db-id-to-name mapping when dropping a table

- src/query/functions/src/scalars/map.rs
- src/query/functions/tests/it/scalars/map.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/map.txt
- tests/sqllogictests/suites/query/02_function/02_0051_function_semi_structureds_get
Fix `get` on map panic when map value is null.
- Closes #12721
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12893)
> fix: fix get map panic when map value is null

- Cargo.lock
- src/common/exception/src/exception.rs
- src/common/exception/src/exception_code.rs
- src/common/exception/src/exception_flight.rs
- src/common/exception/src/exception_into.rs
- src/common/exception/src/span.rs
- src/common/exception/tests/it/exception_flight.rs
- src/common/grpc/src/dns_resolver.rs
- src/common/storage/src/copy.rs
- src/query/ast/src/error.rs
- src/query/ast/src/parser/statement.rs
- src/query/pipeline/sources/src/input_formats/impls/input_format_csv.rs
- src/query/pipeline/sources/src/input_formats/impls/input_format_ndjson.rs
- src/query/pipeline/sources/src/input_formats/impls/input_format_tsv.rs
- src/query/pipeline/sources/src/input_formats/input_format_text.rs
- src/query/service/src/local/executor.rs
- src/query/service/src/local/helper.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/tests/it/pipelines/executor/pipeline_executor.rs
- tests/suites/0_stateless/14_clickhouse_http_handler/14_0007_http_clickhouse_input_format_diagnostic.result
- tests/suites/1_stateful/00_stage/00_0011_distributed_copy_into_table_exection_test.result
- tests/suites/1_stateful/00_stage/00_0011_distributed_copy_into_table_exection_test.sh
- tests/suites/1_stateful/07_stage_attachment/07_0001_replace_with_stage.result
- tests/suites/1_stateful/09_http_handler/09_0001_json_response.result
- tests/suites/1_stateful/09_http_handler/09_0003_error_detail.result
- tests/suites/1_stateful/09_http_handler/09_0003_error_detail.sh
e.g.
```
{
"code": 1046,
"message": "Number of columns in file (2) does not match that of the corresponding table (3)",
"detail": "at file 'select.csv', line 1"
}
```
ErrorCode is 136 bytes after add another string field ,clippy warn about it, so I let Range use u32 instead of usize to reduce size to 128 bytes, to be more efficent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12899)
> refactor: http handler return error position in detail field.

- tests/sqllogictests/src/client/http_client.rs
- tests/sqllogictests/suites/crdb/and_or
1.  format http error message, so the main part of it is the same as that of mysql/clickhouse handler.
2.  make full use of regex to match both code and message. note:   1. need `(?s)` to match multiline. 2. meta characters like `(` needs to be escaped.
if this pattern is ok, I will update the remaining sqllogictest files in next pr.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12904)
> ci: sqllogictest match both error code and error message.

- src/query/service/src/pipelines/pipeline_builder.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_aggregate_expand.rs
- src/query/service/src/pipelines/processors/transforms/window/window_function.rs
- src/query/sql/src/executor/format.rs
- src/query/sql/src/executor/physical_plan.rs
- src/query/sql/src/executor/physical_plan_builder.rs
- src/query/sql/src/executor/physical_plan_display.rs
- src/query/sql/src/executor/physical_plan_visitor.rs
- src/query/sql/src/executor/profile.rs
- src/query/sql/src/planner/binder/aggregate.rs
- src/query/sql/src/planner/binder/distinct.rs
- src/query/sql/src/planner/binder/project.rs
- src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs
- src/query/sql/src/planner/optimizer/heuristic/subquery_rewriter.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/agg_index/query_rewrite.rs
- src/query/sql/src/planner/plans/aggregate.rs
- src/query/sql/src/planner/semantic/grouping_check.rs
- tests/sqllogictests/suites/duckdb/sql/aggregate/group/group_by_grouping_sets.test
- tests/sqllogictests/suites/mode/standalone/explain/explain_grouping_sets.test
- tests/sqllogictests/suites/mode/standalone/explain_native/explain_grouping_sets.test
The main idea of the implementation of grouping sets and what this PR fixed are described in the comments above the definition of `GroupingSetsInfo`.
- Wrap grouping sets variables into one struct.
- Add a new field `dup_group_items`.
- Add detail comments about grouping sets.
- Only hold bound indices of aggregation functions' arguments in  `AggregateFunctionDesc`. The deleted field `args` is the column offsets of the input schema, postpone this generation until pipeline building (to be same with other indices like `group_bys`).
- Rewrite aggregation functions' arguments' descriptions (index and data type) to read duplicated columns instead of the original column (which will be filled with dummy …
> fix: support aggregation arguments in grouping sets.

- src/query/service/tests/it/storages/fuse/meta/snapshot.rs
- src/query/storages/common/table-meta/src/meta/mod.rs
- src/query/storages/common/table-meta/src/meta/v2/snapshot.rs
- src/query/storages/fuse/src/operations/gc.rs
This bug is caused by forgetting to convert the snapshot timestamp from v1 to v2. And thus the history snapshot is not purged in time, cause the oom.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12950)
> fix: purge oom

- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/window_function/window_basic.test
disallow nested general window function, after this pr:
```
root@localhost:8000/default> select last_value(last_value(a) over ()) over () from t;
APIError: ResponseError with 1065: error:
--> SQL:1:19
|
1 | select last_value(last_value(a) over ()) over () from t
|                   ^^^^^^^^^^^^^^^^^^^^^ window function calls cannot be nested
```
- Closes #12922
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12973)
> fix: disallow nested general window function

- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_coordinator.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
1. Add more comments for last refactor
2. remove unwrap
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12985)
> chore: add more comments for hash join and remove unwrap

- src/query/functions/src/scalars/variant.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/variant.txt
- src/query/functions/tests/it/scalars/variant.rs
- src/query/sql/src/planner/binder/copy.rs
- src/query/sql/src/planner/semantic/type_check.rs
- src/query/storages/fuse/src/operations/agg_index_sink.rs
- src/query/storages/fuse/src/operations/merge.rs
- src/query/storages/fuse/src/operations/read_partitions.rs
- src/query/storages/stage/src/parquet_file/sink_processor.rs
- src/query/storages/stage/src/row_based_file/sink_processor.rs
- tests/sqllogictests/suites/query/02_function/02_0048_function_semi_structureds_parse_json
- tests/sqllogictests/suites/query/02_function/02_0065_function_json
- tests/sqllogictests/suites/stage_parquet/parquet_field_types
- rewrite tuple cast to variant as `json_object_keep_null` function to using inner fields name as object keys
- add `try_json_object` and `try_json_object_keep_null` functions
- remove unused `clippy::too_many_arguments`
- Closes #12966
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12983)
> fix(query): fix copy tuple cast to variant lost field name

- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/inner_join.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
1. Whole `HashJoinState`, `HashJoinBuildState`, and `HashJoinProbeState` are in `Arc`, so no need to put their fields in `Arc`.
2. Replace some `Mutex/Lock` with `Atomic`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12988)
> chore: remove redundant `Arc` and use atomic to replace lock

- src/query/sql/src/planner/binder/table.rs
- tests/sqllogictests/suites/query/join.test
- Closes https://github.com/datafuselabs/databend/issues/12941
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13012)
> fix: TableReference::Join unreachable cause databend-query panic

- src/query/catalog/src/table_context.rs
- src/query/service/src/interpreters/interpreter_query_log.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_spill/probe_spill_state.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/src/sessions/query_ctx_shared.rs
- src/query/service/src/spillers/spiller.rs
- src/query/service/tests/it/spillers/spiller.rs
- src/query/service/tests/it/storages/fuse/operations/commit.rs
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/storages/system/src/query_log_table.rs
After executing hash join query with spilling, we can check how many bytes or rows are spilled to storage.
- Closes https://github.com/datafuselabs/databend/issues/12895
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13018)
> feat: add `join_spilled_bytes/rows` to query log

- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_coordinator.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- src/query/service/src/spillers/spiller.rs
- tests/sqllogictests/suites/query/spill.test
The probe collects the rows that are not in the build spilled partition and probe them directly against the build rows of the first round.
The PR will reduce heavy I/O operations.
From query log, we can see spilled bytes reduced.
```
create table t3 as select number as a from numbers(100000);
select a from t3 inner join numbers(10000000) on t3.a = number order by a;
```
Before all probe rows are spilled.
Now
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13035)
> feat: reduce probe spilled data and I/O

- .github/actions/publish_binary/action.yml
- .github/workflows/release.yml
- scripts/build/build-debug.sh
- scripts/ci/ci-run-sqlsmith-tests.sh
- src/tests/sqlsmith/Cargo.toml
* Make separate release category `testsuite` with `databend-sqllogictests` and `databend-sqlsmith`.
* Run sqlsmith for each release.
- Closes #13043
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13072)
> ci: test sqlsmith on release

- src/meta/raft-store/src/applier.rs
- src/meta/raft-store/src/lib.rs
- src/meta/raft-store/src/sm_v002/importer.rs
- src/meta/raft-store/src/sm_v002/leveled_store/level.rs
- src/meta/raft-store/src/sm_v002/leveled_store/level_data.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map_test.rs
- src/meta/raft-store/src/sm_v002/leveled_store/map_api.rs
- src/meta/raft-store/src/sm_v002/leveled_store/mod.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_mut.rs
- src/meta/raft-store/src/sm_v002/leveled_store/static_leveled_map.rs
- src/meta/raft-store/src/sm_v002/marked/mod.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/sm_v002_test.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002_test.rs
- Add trait `MapKey` and `MapValue` to define behavior of key values
that are used in `MapApi`.
- Add Ref and RefMut as container of reference to leveled data.
- Collect get() and range() implementation into function.
The MapApi trait can not be generalized to adapt arbitrary lifetime,
such as using `self` instead of `&self`: `MapApiRO { fn get(self, key) }`.
Because there is a known limitation with rust GAT and hihger ranked
lifetime: See: https://github.com/rust-lang/rust/issues/114046
```
error: implementation of `MapApiRO` is not general enough
--> src/meta/raft-store/src/sm_v002/sm_v002.rs:80:74
|
80 |       async fn get_kv(&self, key: &str) -> Result<GetKVReply, Self::Error> {
| …
```
> refactor: simplify MapApi

- src/meta/service/src/store/store.rs
- src/meta/service/src/store/store_inner.rs
- src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs
- src/meta/service/tests/it/store.rs
In this commit, wrap sled trees for `log` and `raft-state` with an async
lock. Before exporting, it has to acquire these locks to get a
consistent view of the state machine.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13085)
> refactor: it has to get a consistent view of the state machine when exporting meta-service data

- src/bendpy/src/lib.rs
- src/query/service/src/local/mod.rs
`bend-local` now respect env `DATABEND_DATA_PATH`, if it's set, meta and data will be persistent in that path.
```bash
❯ DATABEND_DATA_PATH=/tmp/abc/ ./target/debug/databend-query local -q "create table abc(a int); insert into abc values(3);"
❯ DATABEND_DATA_PATH=/tmp/abc/ ./target/debug/databend-query local -q "select * from abc"
3
```
`bendpy` will also respect this env, but you must set the env before import databend 
```python
import os
os.environ["DATABEND_DATA_PATH"] = "/tmp/def/"
from databend import SessionContext
...
```
- Closes #12992
- - - …
> feat(query): support DATABEND_DATA_PATH in bendpy and bend-local

- Cargo.lock
- Cargo.toml
- tests/sqllogictests/suites/base/11_data_type/11_0006_data_type_decimal
The arrow2 encode different precision of decimal with different physical types. The bug happened when we did fixed_len_bytes encoding.
For decimal 128, precision:
```
<=9  -> i32
<=18 -> i64
else -> fixed_len_bytes
``` 
For decimal 256, precision:
```
<=9  -> i32
<=18 -> i64
<=38 -> fixed_len_bytes of decimal 128
else -> fixed_len_bytes of decimal 256
```
- Closes #13058
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13074)
> fix: fix nested decimal read and write

- Cargo.lock
- Cargo.toml
- src/binaries/metactl/snapshot.rs
- src/meta/service/Cargo.toml
- src/meta/service/src/api/grpc/grpc_service.rs
- src/meta/service/src/lib.rs
- src/meta/service/src/store/store.rs
- src/meta/service/src/store/store_inner.rs
- Updated the `export()` function in `grpc_service.rs` to use crate
`futures-async-stream`, changed return type of the function to use a
`BoxStream` that yields a series of JSON strings, instead of returning
a big `Vec<String>`.
This allows for more efficient handling of asynchronous streams, which
can provide performance improvements.
Note that `export(self: Arc<Sefl>)` takes an `Arc<Self>` as argument
because the generated `gRPC` stream signature requires a `'static`
lifetime. As a result, the `export(&self)` can not be used:
```
type ExportStream: Stream<Item = Result<_, _>> + Send + 'static;
```
- Add dependency crate `futures-async-stream`;
- Enable unstable feature `#![feature(generators)]` …
> refactor: meta-service: re-implement export with Stream

- src/meta/client/tests/it/grpc_server.rs
- src/meta/service/src/api/grpc/grpc_service.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13099)
> chore: remove unused type ExportStream; Stream does not need to be Sync

- src/meta/raft-store/src/lib.rs
- src/meta/raft-store/src/sm_v002/leveled_store/level.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map_test.rs
- src/meta/raft-store/src/sm_v002/leveled_store/map_api.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/sm_v002_test.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13106)
> chore: add trait AsMap to get a handle of `MapApi<K>` for a specific type `K`

- src/meta/raft-store/src/key_spaces.rs
- src/meta/service/src/store/store_inner.rs
- src/meta/service/tests/it/store.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13112)
> chore: clean up useless comment about unused state-machine-id

- scripts/setup/dev_setup.sh
- Closes #13115
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13116)
> chore: use cargo quickinstall for check tools

- src/meta/raft-store/src/sm_v002/leveled_store/level.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map_test.rs
- src/meta/raft-store/src/sm_v002/leveled_store/mod.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_mut.rs
- src/meta/raft-store/src/sm_v002/leveled_store/static_levels.rs
- src/meta/raft-store/src/sm_v002/marked/marked_test.rs
- src/meta/raft-store/src/sm_v002/marked/mod.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/sm_v002_test.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13114)
> chore: rename StaticLeveledMap to StaticLevels; refactor Marked::new_xxx()

- src/meta/client/src/grpc_client.rs
- src/meta/client/src/grpc_metrics.rs
- src/meta/stoerr/src/meta_storage_errors.rs
- src/meta/types/src/errors/meta_api_errors.rs
- src/meta/types/src/errors/meta_client_errors.rs
- src/meta/types/src/errors/meta_errors.rs
- src/meta/types/src/errors/meta_network_errors.rs
have a full error message into metrics' labels is not effective to the prometheus storage, and have dangerous for the metrics scraper like this:
```
expected equal, got "expired\"" ("LNAME") while parsing: "databend_meta_grpc_client_request_fail_total{endpoint=\"meta-service-0.meta-service.databend-system.svc:9191\",request=\"PrefixList\",error=\"ConnectionError: source: tonic::status::Status: status: Cancelled, message: \"Timeout expired\""
```
this PR added a `name()` method to MetaError, and put the name into the label instead of `err.to_string()` to reduce the cardinality of the metric labels on error.
- - - …
> fix(metrics): avoid leaking meta_client's error messages into metrics

- src/meta/app/src/principal/user_stage.rs
- src/meta/proto-conv/src/stage_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/main.rs
- src/meta/proto-conv/tests/it/user_proto_conv.rs
- src/meta/proto-conv/tests/it/user_stage.rs
- src/meta/proto-conv/tests/it/v025_user_stage.rs
- src/meta/proto-conv/tests/it/v030_user_stage.rs
- src/meta/proto-conv/tests/it/v031_copy_max_file.rs
- src/meta/proto-conv/tests/it/v035_user_stage.rs
- src/meta/proto-conv/tests/it/v042_s3_stage_new_field.rs
- src/meta/proto-conv/tests/it/v051_obs_and_cos_storage.rs
- src/meta/proto-conv/tests/it/v057_hdfs_storage.rs
- src/meta/proto-conv/tests/it/v060_copy_options.rs
- src/meta/protos/proto/stage.proto
- src/query/ast/src/ast/statements/copy.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/testdata/statement-error.txt
- src/query/ast/tests/it/testdata/statement.txt
- src/query/service/src/interpreters/interpreter_copy.rs
- src/query/sql/src/planner/binder/copy.rs
- src/query/sql/src/planner/plans/copy.rs
- tests/sqllogictests/suites/base/05_ddl/05_0016_ddl_stage
- tests/sqllogictests/suites/base/06_show/06_0011_show_stages
- tests/sqllogictests/suites/stage/options/return_failed_only
Boolean that specifies whether to return only files that have failed to load in the statement result.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13122)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13122)
> feat: add copy option return_failed_only.

- src/meta/raft-store/src/sm_v002/leveled_store/level.rs
- src/meta/raft-store/src/sm_v002/leveled_store/map_api.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_mut.rs
These two functions are the foundation for multi level data access.
This commit generalizes them by allowing them to take
`IntoIterator<Item = impl MapApiRO>` as input levels,
instead of `Iterator<Item = Level>`.
And add tests to these two functions
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13124)
> refactor: generalize compacted_get() and compacted_range()

- src/meta/api/src/schema_api_test_suite.rs
- src/meta/api/src/util.rs
When listing tables, every `mget()` for table meta should not request for more than 256
tables, in order to prevent a too large response body that exceeds gPRC
body limit(16MB currently).
A test is added to ensure listing `30_000` tables works as expected.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13138)
> refactor: fetch table metas in small chunks

- src/query/sql/src/planner/plans/update.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0026_merge_into
for merge into, if target_table's fields are not null, when after bind_join,
it will change into nullable, so we need to cast this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13144)
> fix: fix_null_cast_bug

- Cargo.lock
- src/common/storage/Cargo.toml
- src/common/storage/src/operator.rs
fix: Rollback to warning instead of hard error
PR https://github.com/datafuselabs/databend/pull/13002 introduces a strict error when a stage lacks a region. However, this modification causes issues with numerous existing stages. This PR ensures their continued usability.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13143)
> fix: Rollback to warning instead of hard error when stage region is missing

- src/meta/api/src/schema_api_test_suite.rs
- src/meta/raft-store/tests/it/state_machine/schema_api_impl.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13147)
> refactor: creating 30,000 tables may timeout unit test, reduce it to DEFAULT_MGET_SIZE+20

- docs/doc/15-sql-functions/60-conversion-functions/index.md
Updated the description to "Converts an array of **positive** integers to a BITMAP value"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13146)
> docs: build_bitmap updates

- src/query/service/src/databases/system/system_database.rs
now we've removed the auth_string infomation in the `system.users` table and `SHOW USERS` statement, it's saft to have `system.users` enabled again. otherwise it would produce a confusing error message on `SHOW USERS` like this:
```
1025=>
error: 
--> SQL:1:12
|
1 | show users;
|              Unknown table `system`.`users` in catalog 'default'
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13171)
> fix(users): enable system.users table again

- src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs
- src/query/sql/src/planner/optimizer/hyper_dp/dphyp.rs
- tests/sqllogictests/suites/tpch/queries.test
For scalar subquery, we'll convert it to single join.
Single join is similar to left outer join, if there isn't matched row in the right side, we'll add NULL value for the right side.
for count aggregation function, NULL values should be 0.
But for count + other aggregations, we shouldn't consider NULL to 0.
- Closes https://github.com/datafuselabs/databend/issues/13108
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13179)
> fix: not only count aggregation function in subquery

- src/query/expression/src/utils/date_helper.rs
- src/query/functions/src/scalars/datetime.rs
- src/query/functions/tests/it/scalars/datetime.rs
- src/query/functions/tests/it/scalars/testdata/datetime.txt
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- tests/sqllogictests/suites/query/02_function/02_0012_function_datetimes
support scalar func : to_week_of_year
Function Name | Date Part Extracted from Input Date / Timestamp | Possible Values
-- | -- | --
to_week_of_year | Same as sf WEEKISO, except uses ISO semantics | 1 to 53
- Part of #13167
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13173)
> feat(query): add func: to_week_of_year

- src/query/ee/tests/it/aggregating_index/index_refresh.rs
- src/query/service/src/interpreters/common/refresh_aggregating_index.rs
- src/query/service/src/interpreters/interpreter_copy_into_table.rs
- src/query/service/src/interpreters/interpreter_insert.rs
* Generates sync agg index after `copy into`.
* Clean code for `hook_refresh_agg_index`.
* Add associated tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13152)
> feat: generate sync agg indexes after copy into

- src/meta/types/src/lib.rs
- src/meta/types/src/proto_ext/mod.rs
- src/meta/types/src/proto_ext/txn_ext.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13191)
> refactor: move extension protobuf methods to separate file

- src/query/sql/src/executor/format.rs
- tests/sqllogictests/suites/mode/standalone/explain/join_reorder/chain.test
- tests/sqllogictests/suites/mode/standalone/explain_native/join_reorder/chain.test
- tests/sqllogictests/suites/tpch/queries.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13212)
> chore: remove explain join estimated_rows

- src/query/ast/src/ast/expr.rs
- src/query/ast/src/ast/format/syntax/expr.rs
- src/query/ast/src/parser/expr.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/src/visitors/walk.rs
- src/query/ast/src/visitors/walk_mut.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/expr-error.txt
- src/query/ast/tests/it/testdata/expr.txt
- src/query/ast/tests/it/testdata/statement-error.txt
- src/query/sql/src/planner/semantic/type_check.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
- tests/sqllogictests/suites/base/20+_others/20_0001_planner
1. Databend has already support Extract, so we can convert date_part to extract
- Closes #13167
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13196)
> feat(query): support date_part function

- src/meta/service/src/grpc_helper.rs
- src/meta/service/src/lib.rs
- src/meta/service/src/meta_service/meta_service_impl.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13221)
> chore: move grpc helper functions to GrpcHelper

- src/query/service/src/interpreters/interpreter_index_refresh.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/storages/fuse/src/operations/common/processors/sink_commit.rs
1. fix when `ctx.segment_locs` is empty, do full `get_partitions`
2. if commit data is successful, add segments to query ctx for future use.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13234)
> fix: fix some bugs of refresh agg index

- Cargo.lock
- src/query/ast/src/ast/expr.rs
- src/query/sql/src/planner/semantic/type_check.rs
- src/query/storages/system/Cargo.toml
- src/query/storages/system/src/functions_table.rs
- Closes #13246
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13250)
> fix: add missing functions for `show functions`

- src/common/grpc/src/client_conf.rs
- src/meta/client/src/grpc_client.rs
- src/meta/service/src/lib.rs
- src/meta/service/src/message.rs
- src/meta/service/src/meta_service/forwarder.rs
- src/meta/service/src/meta_service/meta_leader.rs
- src/meta/service/src/meta_service/meta_service_impl.rs
- src/meta/service/src/meta_service/mod.rs
- src/meta/service/src/meta_service/raftmeta.rs
- src/meta/service/src/request_handling.rs
- src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs
- src/query/config/src/inner.rs
Introduce `Forwarder` as a container of various request forwarding
functions.
And treat `MetaLeader` as a container of various request handling
functions.
We also introduce trait `Handler` and `Forwarder` to define behavior of
these two containers.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13257)
> refactor: extract request handling to Handler and Forwarder

- src/meta/client/src/grpc_action.rs
- src/meta/client/src/grpc_client.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13265)
> chore: remove useless type param from kv_api

- src/meta/client/src/grpc_client.rs
- src/meta/service/src/api/grpc/grpc_service.rs
- src/meta/service/src/meta_service/meta_service_impl.rs
chore: remove unused type param Resp from grpc_client::ClientHandle::request()
chore: remove duplicated stream definition GrpcStream
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13278)
> chore: refactor meta grpc service

- src/query/sql/src/evaluator/cse.rs
- tests/sqllogictests/suites/base/issues/issue_13269.test
`if` is not same as normal function, they eval with validity, we not reuse expr in these two special functions to avoid bug.
- Closes #13269
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13271)
> fix: do not reuse expr when function are if

- src/meta/client/src/grpc_action.rs
- src/meta/client/src/grpc_client.rs
- src/meta/client/src/lib.rs
- src/meta/client/src/message.rs
- src/meta/client/tests/it/grpc_server.rs
- src/meta/service/src/api/grpc/grpc_service.rs
- src/meta/service/src/message.rs
- src/meta/service/src/meta_service/forwarder.rs
- src/meta/service/src/meta_service/meta_leader.rs
- src/meta/service/src/meta_service/meta_service_impl.rs
- src/meta/service/src/request_handling.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_kv_read_v1.rs
- src/meta/service/tests/it/grpc/mod.rs
- src/meta/service/tests/it/tests/mod.rs
- src/meta/types/proto/meta.proto
- src/meta/types/src/proto_ext/mod.rs
- src/meta/types/src/proto_ext/stream_item_ext.rs
- src/meta/types/src/seq_value.rs
In this commit, meta grpc service provides new api
`kv_read_v1() -> Stream<StreamItem>`. Service and client are both ready
but not yet used by databend-query yet.
This new API support `get` single kv, `mget` multiple kv and `list` kv
by a prefix. The result is returned in a stream.
Raft service also provides a `kv_read_v1()` API for internal forwarding
such a request to the leader.
Other changes: rename internal term `PrefixList -> List`.
- Fix: #13160
- New Feature
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13299)
> feat: add stream api for get, mget and list

- .github/actions/benchmark_cloud/action.yml
- Cargo.lock
- src/query/config/src/config.rs
- src/query/config/src/inner.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
- src/query/storages/common/cache-manager/Cargo.toml
- src/query/storages/common/cache-manager/src/cache_manager.rs
Adjust the default upper bound of table data cache population queue size to the value of `max_threads`.
The current default value (65535) is too aggressive and likely leads to OOM.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/12773)
> chore: adjust table data cache population queue size

- Cargo.lock
- Cargo.toml
- src/query/expression/src/evaluator.rs
- src/query/expression/src/function.rs
- src/query/expression/src/utils/arrow.rs
- src/query/expression/src/values.rs
- src/query/formats/tests/it/output_format_utils.rs
- src/query/functions/src/scalars/arithmetic.rs
- src/query/functions/src/scalars/datetime.rs
- src/query/functions/src/scalars/variant.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/common.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_state.rs
- src/query/service/src/pipelines/processors/transforms/range_join/ie_join_state.rs
- src/query/service/tests/it/servers/http/json_block.rs
- src/query/storages/parquet/src/parquet_rs/parquet_reader/topk.rs
After adding `Bitmap::new_constant` in https://github.com/jorgecarleitao/arrow2/pull/1579, we can use it to replace `constant_bitmap` and `extend_constant`, which can avoid doing a bitcount when converting `MutableBitmap` to `Bitmap`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13309)
> chore(query): using Bitmap::new_constant to replace constant_bitmap and extend_constant

- src/query/service/src/interpreters/interpreter_copy_into_table.rs
- src/query/service/src/interpreters/interpreter_merge_into.rs
- src/query/service/src/interpreters/interpreter_replace.rs
- src/query/sql/src/planner/binder/table.rs
* format the compact into one block
* add a time cost log for bind stage table
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13369)
> chore: format the code about compact and add a time cost for bind table

- src/query/storages/system/src/configs_table.rs
Make sure oss key in config table has been masked
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13388)
> fix: Make sure oss key in config table has been masked

- src/query/config/src/config.rs
- src/query/config/src/inner.rs
- src/query/service/src/clusters/cluster.rs
- src/query/service/src/global_services.rs
- src/query/service/src/test_kits/config.rs
* add a `node_id` to `InnerConfig.Query` for global using, now only cluster use the node_id
* prepare for https://github.com/datafuselabs/databend/pull/13381, tracing name will use node_id
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13391)
> chore: add a global node_id to config

- src/query/service/src/api/rpc_service.rs
- src/query/service/src/servers/flight_sql/flight_sql_server.rs
- src/query/service/tests/it/api/rpc_service.rs
- src/query/service/tests/it/servers/flight_sql/flight_sql_server.rs
- src/query/service/tests/it/servers/flight_sql/mod.rs
fix(query): check port used for rpc and flightsql servers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13398)
> fix(query): check port used for rpc and flightsql servers

- src/query/config/src/inner.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/sql/src/planner/optimizer/property/constraint.rs
- src/query/sql/src/planner/plans/scalar_expr.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/mode/standalone/explain/eliminate_outer_join.test
Support eliminating outer join with filter using timestamp comparison, e.g. `updated_at > '2023-01-01'`.
Part of #13236
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13397)
> feat(planner): improve outer join elimination

- src/common/tracing/src/minitrace.rs
- src/query/service/src/global_services.rs
* make the otlp worker threads max to 2
* `databend-query@CoI7y371WDDNFwrCCY4JN5-default` to `databend-query-CoI7y37@default` for short
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13402)
> chore: max the OTLP reporter to 2 threads

- src/query/storages/hive/hive/src/hive_catalog.rs
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13412)
> feat: Polish error output for thrift errors

- .github/actions/build_linux_sanitizer/action.yml
- .github/workflows/reuse.linux.yml
- src/common/arrow/src/lib.rs
- src/common/compress/src/lib.rs
- src/common/tracing/src/lib.rs
- src/meta/api/src/lib.rs
- src/meta/app/src/lib.rs
- src/meta/kvapi/src/lib.rs
- src/meta/store/src/lib.rs
- src/query/pipeline/sources/src/lib.rs
- src/query/pipeline/transforms/src/lib.rs
- src/query/storages/common/cache-manager/src/lib.rs
- src/query/storages/common/pruner/src/lib.rs
- src/query/storages/hive/hive/src/lib.rs
- src/query/storages/result_cache/src/lib.rs
Add build_linux_sanitizer with AddressSanitizer to check memory safety.
**NOTE:** compile with sanitizer will inject crates to codes, so we need delete `#![deny(unused_crate_dependencies)]` in some codes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13416)
> ci: add build_linux_sanitizer

- src/query/ast/src/ast/ast.rs
- src/query/ast/src/ast/statements/stage.rs
- src/query/ast/src/parser/stage.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement-error.txt
- src/query/ast/tests/it/testdata/statement.txt
- tests/sqllogictests/suites/base/05_ddl/05_0019_ddl_create_view
- tests/sqllogictests/suites/stage_parquet/options/select_options
- tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_05_query_uri.sh
change 
```
`select * from 's3://testbucket/admin/data/parquet/tuple.parquet' (aws_key_id => 'minioadmin', aws_secret_key => 'minioadmin', endpoint_url => 'http://127.0.0.1:9900/', file_format => 'parquet')"`
```
to 
```
select * from 's3://testbucket/admin/data/parquet/tuple.parquet' (connection => (aws_key_id = 'minioadmin', aws_secret_key = 'minioadmin', endpoint_url = 'http://127.0.0.1:9900/')
```
also Closes https://github.com/datafuselabs/databend/issues/13419
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13427)
> refactor: adjust syntax of select from uri.

- src/query/sql/src/executor/physical_plans/physical_hash_join.rs
- tests/sqllogictests/suites/query/join.test
The result block schema is: id1, val1, val2, id2(tail), the merged schema: id1, val1, id2, val2, id2(tail), for `t1.val >= t2.val`, the indexes of (val1, val2) are (1, 2) and (1, 3) respectively, but they should be the same.
- Closes #13443
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13446)
> chore(planner): fix probe to build

- .github/actions/build_linux_sanitizer/action.yml
readelf only on debug mode when do asan build
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13450)
> fix: readelf only on debug mode when do asan build

- src/meta/raft-store/src/sm_v002/leveled_store/level.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map.rs
- src/meta/raft-store/src/sm_v002/leveled_store/map_api.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_mut.rs
- src/meta/raft-store/src/sm_v002/leveled_store/static_levels.rs
When querying the meta-service state machine with a stream oriented API,
such as `list_kv()`, the gRPC server respond to the client with a
`BoxStream<'static, ...>`. Therefore state machine has to return a
`'static` stream too.
In this commit, A new Stream `EntryStream<K>` is introduced as a type of
the output type for `MapApi::range()`
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13461)
> refactor: state machine API MapApi::range() returns static lifetime stream

- src/meta/raft-store/src/applier.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/sm_v002_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13464)
> chore: remove obsolete non-stream API SMV002::prefix_list_kv()

- .github/CODEOWNERS
chore: Add soyeric128 as code owner of docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13465)
> chore: Add soyeric128 as code owner of docs

- src/binaries/metactl/snapshot.rs
- src/meta/raft-store/src/applier.rs
- src/meta/raft-store/src/sm_v002/leveled_store/level.rs
- src/meta/raft-store/src/sm_v002/leveled_store/sys_data.rs
- src/meta/raft-store/src/sm_v002/leveled_store/sys_data_api.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/sm_v002_test.rs
- src/meta/service/src/meta_service/meta_leader.rs
- src/meta/service/src/meta_service/meta_node.rs
- src/meta/service/src/store/store.rs
- src/meta/service/src/store/store_inner.rs
- src/meta/service/tests/it/meta_node/meta_node_replication.rs
- src/meta/service/tests/it/store.rs
Because its return value may be an expired record and should be considered as None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13466)
> chore: rename: SMV002::get_kv() to get_maybe_expired_kv()

- docs/doc/13-sql-reference/51-connect-parameters.md
- Summarized the connection parameter format (for example, = or =>) in SQLs (CREATE STAGE, COPY INTO, SELECT)
- Highlighted the differences that might confuse the users.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13470)
> docs: connection parameter format in sql

- src/meta/raft-store/src/sm_v002/leveled_store/map_api.rs
- src/meta/raft-store/src/sm_v002/leveled_store/util.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13472)
> chore: remove unused type param `V` from `Tuple<K, V>`

- scripts/benchmark/query/load/hits.sh
- scripts/benchmark/query/load/tpch10.sh
- scripts/benchmark/query/load/tpch100.sh
- tests/sqllogictests/scripts/prepare_stage.sh
- tests/suites/1_stateful/00_stage/00_0008_remove_external_stage.sh
- tests/suites/1_stateful/02_query/02_0001_create_table_with_external_location.sh
- tests/suites/1_stateful/02_query/02_0004_attach_table.result
- tests/suites/1_stateful/02_query/02_0004_attach_table.sh
- tests/suites/1_stateful/05_formats/05_01_compact/05_01_00_load_compact_copy.sh
- tests/suites/1_stateful/05_formats/05_01_compact/05_01_02_load_compact_copy_max_size.sh
- tests/suites/1_stateful/05_formats/05_01_compact/05_01_02_load_compact_copy_row_per_block.sh
- tests/suites/1_stateful/05_formats/05_04_tsv/05_04_01_tsv_multi_file.sh
- tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_05_query_uri.sh
- tests/suites/1_stateful/10_iceberg/10_0000_create_and_show.sh
- tests/suites/1_stateful/10_iceberg/10_0001_read.sh
- tests/suites/5_ee/01_vacuum/01_0002_ee_vacuum_drop_table.sh
- tests/suites/5_ee/04_attach_read_only/04_0001_check_mutations.sh
Change the test script:
* `aws_key_id` to `access_key_id`
* `aws_secret_key` to `secret_access_key`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13473)
> chore: aws_* to access_key_id/secret_access_key

- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- src/query/service/src/spillers/spiller.rs
- src/query/service/tests/it/spillers/spiller.rs
1. Increase partition number to eight
2. put `check_spill()` to proper position
3. simplify log
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13475)
> chore: adjust partition number for hash join spill

- src/binaries/metactl/snapshot.rs
- src/meta/raft-store/src/applier.rs
- src/meta/raft-store/src/ondisk/mod.rs
- src/meta/raft-store/src/sm_v002/leveled_store/level.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map_test.rs
- src/meta/raft-store/src/sm_v002/leveled_store/map_api.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_mut.rs
- src/meta/raft-store/src/sm_v002/leveled_store/static_levels.rs
- src/meta/raft-store/src/sm_v002/leveled_store/util.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/sm_v002_test.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002_test.rs
- src/meta/raft-store/src/sm_v002/writer_v002.rs
- src/meta/service/src/store/store.rs
- src/meta/service/src/store/store_inner.rs
- src/meta/service/tests/it/meta_node/meta_node_replication.rs
- src/meta/service/tests/it/store.rs
The `MapApi` serves as the API for the state machine, which will be
upgraded to support on-disk data storage. Consequently, to ensure
I/O errors are revealed to the calling function, `MapApi` should return
a `Result<T, io::Error>` instead of simply `T`.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13485)
> refactor: MapApi should return Result<T, io::Error>

- Cargo.toml
- src/query/config/src/background_config.rs
- src/query/config/src/config.rs
- tests/sqllogictests/Cargo.toml
This is the behavior that confused our users a lot:
```shell
--storage-oss-access-key-id <OSS_ACCESS_KEY_ID>
Access key id for OSS storage
[default: ]
--storage-oss-access-key-secret <OSS_ACCESS_KEY_SECRET>
Access Key Secret for OSS storage
[default: ]
--storage-oss-bucket <OSS_BUCKET>
Bucket for OSS
[default: ]
```
Our users believe that `OSS_ACCESS_KEY_ID` and `OSS_ACCESS_KEY_SECRET` here serve as the  environment name for this argument. However, it's not. It's just the value name for this arg and default to it's own field type. We are not using the `clap`'s env feature.
To avoid this confusion anymore, I submit this PR to change all args value name to `VALUE`. After this change, the output of …
> refactor: Alter all command line's value name to VALUE

- docs/doc/12-load-data/00-transform/05-querying-stage.md
Fixed https://databend.rs/doc/load-data/transform/querying-stage#example-2-filtering-files as the syntax was changed by https://github.com/datafuselabs/databend/pull/13427
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13488)
> docs: fix example selecting from URI

- src/query/expression/src/utils/serialize.rs
- tests/sqllogictests/suites/base/11_data_type/11_0006_data_type_decimal
string cast to decimal can't round if precision is small, for example:
```sql
mysql> select cast('1.16' as decimal(2,1));
+-------------------------------+
| cast('1.16' as decimal(2, 1)) |
+-------------------------------+
|                           1.1 |
+-------------------------------+
1 row in set (0.04 sec)
Read 1 rows, 1.00 B in 0.005 sec., 201.46 rows/sec., 201.46 B/sec.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13518)
> fix(query): fix string to decimal round

- src/query/sql/src/planner/binder/table.rs
`bind_single_table` is too big, we spilt it like:
```
match table_ref {
TableReference::Table { span, catalog, database, table, alias, travel_point, pivot: _, unpivot: _ } => {
self.bind_table(bind_context, span, catalog, database, table, alias, travel_point).await
}
TableReference::TableFunction { span, name, params, named_params, alias } => {
self.bind_table_function(bind_context, span, name, params, named_params, alias).await
}
TableReference::Subquery { span, subquery, alias } => {
self.bind_subquery(bind_context, span, subquery, alias).await
}
TableReference::Location { span, location, options, alias } => {
self.bind_location(bind_context, span, location, options, alias).await
}
....
```
- …
> chore: refactor the bind_single_table into many small functions

- Cargo.lock
- scripts/ci/deploy/config/databend-query-node-1.toml
- src/query/service/Cargo.toml
- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/spillers/spiller.rs
- src/query/service/tests/it/spillers/spiller.rs
Adjusting the memory check, currently the lineitem and partsupp tables for 15G tpch data can complete the join in 3G memory
```
select l.l_orderkey from partsupp as p join lineitem as l on p.ps_partkey = l.l_partkey ;
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13507)
> chore: improve memory accuracy for hash join spill

- src/query/expression/src/kernels/filter.rs
This bug has existed before https://github.com/datafuselabs/databend/pull/13497, we found it via `test_filter_boolean`, the reason for the error is that the `length`(usize) becomes a negative number during subtraction.
- Closes #13527 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13529)
> chore: fix filter offset

- src/query/service/src/interpreters/interpreter_role_set.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/sessions/session.rs
- src/query/service/src/sessions/session_ctx.rs
- src/query/service/src/sessions/session_privilege_mgr.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
An user may have multiple roles, sometimes we hope to restrict the role to limit the privilege we have. It'd be useful when you have a scheduler which hopes to execute multiple tasks in arbitary roles.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13537)
> feat: allow restricting a current role on starting a query

- src/query/service/src/pipelines/builders/builder_merge_into.rs
- src/query/service/src/pipelines/builders/builder_replace_into.rs
- src/query/service/src/pipelines/builders/mod.rs
- src/query/service/src/pipelines/pipeline_builder.rs
* `pipeline_builder.rs` is biger and biger, it's hard to maintain, spill out some module to files
* this PR is the part-2, spill out: 
- `builder_replace_into.rs`
- `builder_merge_into.rs`
* more spill out in the next PR
* part-1: https://github.com/datafuselabs/databend/pull/13571
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13572)
> chore: make pipeline builder more object [part-2]

- src/binaries/metactl/grpc.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13592)
> refactor: validate json string before output, when exporting data from running meta-service

- src/query/functions/src/cast_rules.rs
- src/query/functions/tests/it/scalars/testdata/array.txt
- tests/sqllogictests/README.md
- tests/sqllogictests/src/client/mod.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0029_random_fuzz.test
- tests/sqllogictests/suites/query/02_function/02_0000_function_arithmetic.test
- tests/suites/0_stateless/20+_others/20_0013_pretty_error.result
1. fuzz test insert from random
2. improve `CAST_FROM_STRING_RULES` which always cast string into large number types.
3. sql with regexp pattern`RAND_(\d+)_(\d+)` will be replaced by a random number from the range.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13595)
> chore(query): add fuzz test for insert

- src/query/storages/fuse/src/pruning/block_pruner.rs
With this PR,  `fuse_blocks_range_pruning_before_total` shows up after the execution of merge-into for the scenario given in #13598.  
~~~
mysql> select * from system.metrics where metric like '%blocks_range_pruning%' order by metric;
Empty set (0.05 sec)
Read 51 rows, 11.59 KiB in 0.036 sec., 1.4 thousand rows/sec., 318.87 KiB/sec.
mysql>
mysql> create table t (c int);
Query OK, 0 rows affected (0.33 sec)
mysql> insert into t values(10),(20);
Query OK, 2 rows affected (0.32 sec)
mysql> insert into t values(30),(40);
Query OK, 2 rows affected (0.31 sec)
mysql>
mysql> -- one segment, two blocks
mysql> optimize table t compact segment;
Query OK, 0 rows affected (0.28 sec)
mysql>
mysql>
mysql> create …
> fix: block pruning metric

- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/http_query_manager.rs
* make detach pairs with kill avoid session leak
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13606)
> chore: move http detach to kill

- src/query/sql/src/planner/binder/ddl/table.rs
system.tables_with_history col dropped_on is NULLABLE(TS)
- Closes #13623
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13625)
> fix(query): show drop table dropped_on need check null

- src/query/pipeline/core/src/processors/mod.rs
- src/query/pipeline/core/src/processors/processor.rs
- src/query/pipeline/core/src/processors/profile.rs
- src/query/service/src/pipelines/executor/executor_graph.rs
- src/query/service/src/pipelines/executor/executor_settings.rs
- src/query/service/src/pipelines/executor/executor_tasks.rs
- src/query/service/src/pipelines/executor/executor_worker_context.rs
- src/query/service/src/pipelines/executor/pipeline_executor.rs
- src/query/service/src/pipelines/executor/processor_async_task.rs
- src/query/service/tests/it/pipelines/executor/pipeline_executor.rs
feat(executor): processor level profile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13637)
> feat(executor): processor level profile(part 1)

- Cargo.lock
- Cargo.toml
- src/meta/raft-store/src/config.rs
- src/meta/service/src/configs/outer_v0.rs
- src/meta/service/src/meta_service/meta_node.rs
When streaming a snapshot chunk, it should repeatly `read_buf()` until
`snapshot_max_chunk_size` is full or read EOF.
Openraft does not require Leader/Candidate to be a voter.
Before this commit, Openraft's handling of non-voter leader is
inconsistent:
For a node that has a vote proposed by this node and is committed, and is not a voter:
- [`calc_server_state()`](https://github.com/datafuselabs/openraft/blob/97254a31c673e52429ee7187de96fd2ea2a5ce98/openraft/src/raft_state/mod.rs#L323) returns `Learner`.
- But [`is_leader()`](https://github.com/datafuselabs/openraft/blob/97254a31c673e52429ee7187de96fd2ea2a5ce98/openraft/src/raft_state/mod.rs#L353) returns true.
Since this commit, …
> feat: databend-meta add config raft.snapshot_chunk_size[=4MB]

- src/query/service/src/servers/http/middleware.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/http_query_context.rs
Currently there're cases we'd get 404 query id not found errors if:
1. query instance OOM Killed or crashed during the query execution
2. the query have successfully completed before we polled the next page when we set an extremely large result timeout
It's hard for us to distinguish between these two cases.
This PR added an `node_id` field in the HTTP response. The `node_id` changes every time the query instance restarted, so the client side can determine it's crashed if the node_id changed during a query.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13641)
> feat: return node_id on the http query response

- Cargo.lock
- src/meta/client/src/message.rs
- src/meta/kvapi/src/kvapi/api.rs
- src/meta/raft-store/Cargo.toml
- src/meta/raft-store/src/lib.rs
- src/meta/raft-store/src/sm_v002/leveled_store/arc_level_impl.rs
- src/meta/raft-store/src/sm_v002/leveled_store/level.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map.rs
- src/meta/raft-store/src/sm_v002/leveled_store/map_api.rs
- src/meta/raft-store/src/sm_v002/leveled_store/mod.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_mut.rs
- src/meta/raft-store/src/sm_v002/leveled_store/static_levels.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002_test.rs
- src/meta/raft-store/src/state_machine/expire.rs
A State Machine is a structure with multiple levels, with the top level
being writable.
The top writable level cannot be borrowed to create a static stream.
Thus the range result must be copied.
In this commit, we minimize the top level as much as possible.
Additionally, when querying a range from the static shared label, we avoid copying the result.
- Bug Fix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13649)
> fix: address the slow range() function in the state machine

- src/meta/raft-store/src/sm_v002/leveled_store/arc_level_impl.rs
- src/meta/raft-store/src/sm_v002/leveled_store/level.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map_test.rs
- src/meta/raft-store/src/sm_v002/leveled_store/map_api.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_mut.rs
- src/meta/raft-store/src/sm_v002/leveled_store/static_levels.rs
- src/meta/raft-store/src/sm_v002/marked/marked_test.rs
- src/meta/raft-store/src/sm_v002/marked/mod.rs
- src/meta/raft-store/src/sm_v002/sm_v002_test.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002_test.rs
- src/meta/sled-store/src/db.rs
Since `range()` returns a static stream, the input range argument must
also be static. Therefore it does not to support `K: Borrow<Q>` anymore.
Other changes:
- rename tomb_stone to tombstone.
- add path info when failing to open sled db.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13650)
> refactor: state machine range() does not need to accept borrowed key

- src/meta/client/src/grpc_client.rs
- Bug Fix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13660)
> fix: do not panic, instead, return an error when all retry attempts have been used up

- src/common/metrics/src/count.rs
- src/meta/service/src/grpc_helper.rs
- src/meta/service/src/network.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13663)
> chore: enable using a fn as metrics counter

- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
the role response behaviour when combined with #13537, may have a surprised side effect:
1. when user NOT set the restricted role with `session.role`, the http response still returns the current `session.role`
2. the client take the `session.role` returnted from the server, and pass it to the next query
3. the next query get restricted role by `public`, which causes permission denied.
this issue should be finally resolved by the `SECONDARY ROLE` seperation described in https://github.com/datafuselabs/databend/issues/13544
this PR revert the behaviour back before #13062 as a hotfix.
- - - …
> fix(rbac): revert the session role response behaviour in #13062 

- scripts/setup/dev_setup.sh
install graphviz for fuzzingbook:
seems that the latest `pygraphviz` needs to install graph-dev manually.
----
log of `linux / test_stateful_standalone`:
https://github.com/datafuselabs/databend/actions/runs/6846339185/job/18613028931?pr=13691
---
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13691)
> ci:  install `graphviz` for fuzzingbook (apt only)

- src/query/sql/Cargo.toml
- src/query/sql/src/planner/binder/ddl/catalog.rs
- src/query/sql/src/planner/binder/location.rs
Generally, the URI is in the pattern `hdfs://<namenode>/<path>`.
If <namenode> is empty (i.e. `hdfs:///<path>`),  use <namenode> configured somewhere else, e.g. in XML config file.
For databend user can specify <namenode> in connection options.
refer to https://www.vertica.com/docs/9.3.x/HTML/Content/Authoring/HadoopIntegrationGuide/libhdfs/HdfsURL.htm
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13687)
> fix: parsing of HDFS uri and connection.

- src/query/service/src/api/http_service.rs
Sometimes we may run into troubles on diagnosing graceful shutdown issues to check the backtraces after the process got sigterm. But unfortunately there's no way to dump the stack: all the ports will refuse the new connections after received sigterm.
this PR leaves the admin api port open even after got sigterm to allow us dump stacks until the final exit of the process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13724)
> chore(http): not closing the http admin api port on getting sigterm

- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
- tests/sqllogictests/suites/mode/standalone/explain/explain.test
For constant filter from `where` operator which doesn't contain a column, such as `'year' == ''`, `false`, directly push down both sides of join
**Issue from our customer**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13734)
> fix: fix push down constant filter to join

- src/binaries/meta/entry.rs
- src/meta/service/src/grpc_helper.rs
- src/meta/service/src/meta_service/raft_service_impl.rs
- src/meta/service/src/network.rs
- src/meta/service/src/version.rs
- src/meta/types/proto/meta.proto
- src/meta/types/src/proto_ext/mod.rs
- src/meta/types/src/proto_ext/snapshot_chunk_request_ext.rs
- tests/compat/README.md
This commit introduce a new feature thus it is a compatbile change.
- Databend-meta provides a new gRPC API `install_snapshot_v1()` to
receive snapshot chunk. The old API `install_snapshot()` does not
change.
On the client side, i.e., the leader, will try to send snapshot via v1
API. If an `Unimplement` error is received, it falls back to the
original `install_snapshot()` API.
Thus the compatibility is provided and rolling update is doable.
- Output raft API feature set upon startup. Such a feature set defines
the compatibility between meta-servers.
- New Feature
- - - …
> feat: add install_snapshot_v1(), avoid serializing big chunk data

- tests/suites/6_background/00_target_tables/00_0000_target_tables.sh
The test purpose is to make sure that once background compaction task is finished, query engine session would be reclaimed.
Enlarge the wait time for session termination should be a fair approach to mitigate  flaky test 
- Closes https://github.com/datafuselabs/databend/issues/13731
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13745)
> chore: fix flaky test on background service

- Cargo.lock
- Cargo.toml
- src/query/service/Cargo.toml
Recently, opensrv-mysql was released, so I tried to update the related dependencies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13748)
> chore: bump mysql related crates

- Cargo.lock
- Cargo.toml
- src/binaries/meta/entry.rs
- src/meta/service/src/version.rs
Enables "loosen-follower-log-revert" feature in openraft. It allows a
follower to safely restore to a consistent state with the leader by
cleaning up data and restarting, if inconsistencies arise.
Upgrade openraft to fix a panic occured during data reversion on
followers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13758)
> feat: meta: enable fixing data inconsistency by cleanup follower data

- src/query/service/src/interpreters/interpreter_view_alter.rs
- src/query/service/src/interpreters/interpreter_view_create.rs
- tests/sqllogictests/suites/base/05_ddl/05_0019_ddl_create_view.test
```sql
mysql> alter view v1 as select * from t where a>1;
ERROR 1105 (HY000): UnknownView. Code: 1026, Text = Unknown view 'default'.'v1'.
mysql> create view v as select * from t;
Query OK, 0 rows affected (0.26 sec)
mysql> create view v as select * from t;
ERROR 1105 (HY000): ViewAlreadyExists. Code: 2306, Text = default.v as view Already Exists.
mysql> create view if not exists v as select * from t;
Query OK, 0 rows affected (0.23 sec)
```
- Closes #13761
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13762)
> fix: create stream and alter view

- src/common/storage/src/copy.rs
- src/meta/app/src/principal/file_format.rs
- src/meta/proto-conv/src/file_format_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/main.rs
- src/meta/proto-conv/tests/it/v032_file_format_params.rs
- src/meta/proto-conv/tests/it/v064_ndjson_format_params.rs
- src/meta/protos/proto/file_format.proto
- src/query/ast/src/parser/stage.rs
- src/query/ast/src/parser/token.rs
- src/query/pipeline/sources/src/input_formats/impls/input_format_ndjson.rs
- src/query/service/tests/it/servers/http/clickhouse_handler.rs
- tests/data/ndjson/null.ndjson
- tests/sqllogictests/suites/stage/formats/ndjson/ndjson_default.test
idea:
- "absent/missing" in JSON is diff from "empty" from CSV
- in JSON, "absent/missing" != null
keys:
-  missing_field_as  = error | NULL | field_default | type_default,  error by default,  in case of wrong field names when creating table
-  null_field_as  =  field_default | NULL | type_default,  field_default by default
-  NULL means it is valid only for nullable column
- storge in meta as `optional string`
note these options do not affect the decode of variant/json.
they do not look inside  map/tuple too, for now.
Closes https://github.com/datafuselabs/databend/issues/13738   & on demand of user cc @wubx 
- - - …
> feat: ndjson add new option missing_field_as and null_field_as.

- src/query/expression/src/convert_arrow_rs/array.rs
- src/query/expression/src/convert_arrow_rs/record_batch.rs
- src/query/expression/src/values.rs
- src/query/service/src/pipelines/processors/transforms/transform_udf.rs
- src/query/storages/parquet/src/parquet_rs/parquet_reader/predicate.rs
- src/query/storages/parquet/src/parquet_rs/parquet_reader/read_policy/no_prefetch.rs
- src/query/storages/parquet/src/parquet_rs/parquet_reader/read_policy/predicate_and_topk.rs
- src/query/storages/parquet/src/parquet_rs/parquet_reader/read_policy/topk_only.rs
- src/query/storages/parquet/src/parquet_rs/parquet_reader/read_policy/utils.rs
- src/query/storages/parquet/src/parquet_rs/parquet_reader/reader/builder.rs
- src/query/storages/parquet/src/parquet_rs/parquet_reader/reader/full_reader.rs
- src/query/storages/parquet/src/parquet_rs/parquet_reader/utils.rs
- tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_00_basic.result
- tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_00_basic.sh
Fix `arrow_rs` read variant type, the schema in `RecordBatch` doesn't contain extended metadata, so we can't determine the type of `Variant` and `Bitmap`. Use an external schema instead to fix this bug.
- Closes #13759
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13774)
> fix(query): fix arrow_rs read variant type

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
feat: optimize vacuum drop impl
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13779)
> feat: optimize vacuum drop impl

- src/query/sql/src/planner/optimizer/heuristic/decorrelate/flatten_plan.rs
- src/query/sql/src/planner/optimizer/heuristic/subquery_rewriter.rs
- tests/sqllogictests/suites/mode/standalone/explain/explain.test
In scalar subquery, if the aggregation function comes from order by , no `if_not_null` conversion is needed.
- Closes https://github.com/datafuselabs/databend/issues/13776
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13782)
> fix: fix order by contains count in scalar subquery

- src/common/base/src/base/mod.rs
- src/common/base/src/base/take_mut.rs
- src/query/expression/src/types.rs
- src/query/expression/src/types/any.rs
- src/query/expression/src/types/array.rs
- src/query/expression/src/types/bitmap.rs
- src/query/expression/src/types/boolean.rs
- src/query/expression/src/types/date.rs
- src/query/expression/src/types/decimal.rs
- src/query/expression/src/types/empty_array.rs
- src/query/expression/src/types/empty_map.rs
- src/query/expression/src/types/generic.rs
- src/query/expression/src/types/map.rs
- src/query/expression/src/types/null.rs
- src/query/expression/src/types/nullable.rs
- src/query/expression/src/types/number.rs
- src/query/expression/src/types/string.rs
- src/query/expression/src/types/timestamp.rs
- src/query/expression/src/types/variant.rs
- src/query/functions/src/aggregates/aggregate_avg.rs
- src/query/functions/src/aggregates/aggregate_sum.rs
- src/query/functions/src/aggregates/aggregate_unary.rs
Add `try_upcast_column_builder` and `try_downcast_owned_builder` for ValueType, so the types like `NullableType` and `ArrayType` can downcast builder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13765)
> feat: add downcast_owned_builder

- src/query/sql/tests/location.rs
Use fixed regions in UT `test_parse_uri_location`.
Note that: the region auto detection feature no longer covered by this UT.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13786)
> chore: use fixed regions in UT `test_parse_uri_location`

- Cargo.lock
- src/query/catalog/src/table.rs
- src/query/service/src/table_functions/table_function_factory.rs
- src/query/sql/src/planner/semantic/type_check.rs
- src/query/storages/stream/Cargo.toml
- src/query/storages/stream/src/lib.rs
- src/query/storages/stream/src/stream_status_table_func.rs
- src/query/storages/stream/src/stream_table.rs
- tests/sqllogictests/suites/ee/01_ee_system/01_0004_stream_status.test
introduce new table function `stream_status`, which is indented to be used by the `task` framework.
This table function returns a resultset of one boolean column `has_data`, which indicates if the given stream has data to be consumed.
- A false return means no data awaits consumption in the stream (during function execution).
- A true return suggests potential data awaiting consumption, with a chance of false positives.
e.g.
~~~
mysql> create database test;
Query OK, 0 rows affected (0.18 sec)
mysql> use test;
Database changed
mysql> create table t (c int);
Query OK, 0 rows affected (0.54 sec)
mysql> alter table t set options(change_tracking=true);
Query OK, 0 rows affected (0.09 sec)
mysql> create …
> feat:  table function  `stream_status`

- src/query/service/src/servers/http/v1/query/http_query_manager.rs
fix(query): remove unexpected strong ref for http query
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13807)
> fix(query): remove unexpected strong ref for http query

- src/query/expression/src/schema.rs
- src/query/expression/src/values.rs
- src/query/expression/tests/it/column.rs
- src/query/expression/tests/it/main.rs
- src/query/expression/tests/it/schema.rs
chore: add arrow extention data type support
- Closes https://github.com/datafuselabs/databend/issues/13752
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13796)
> chore: add arrow extention data type support

- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/http_query_manager.rs
- src/query/service/src/servers/http/v1/query/mod.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
1.  remember at most 1000 removed query IDs 
2.  return 404 with body `{ "error": { "code": "404", "message": "query id <query> timeout on <node_id>" }` (tested)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13831)
> feat: http handler return reason for 404.

- src/meta/app/src/principal/user_stage.rs
- src/query/ast/src/ast/statements/copy.rs
- src/query/ast/src/parser/copy.rs
- src/query/ast/tests/it/testdata/statement.txt
- src/query/service/src/sessions/query_ctx.rs
- src/query/sql/src/planner/binder/copy_into_table.rs
- src/query/sql/src/planner/plans/copy_into_table.rs
- tests/sqllogictests/suites/stage/options/max_files.test
- tests/suites/1_stateful/00_stage/00_0004_copy_with_max_files.result
- tests/suites/1_stateful/00_stage/00_0004_copy_with_max_files.sh
committing too many `copied_files` once will lead to 
1.  error when package size exceeds some limit.
2.  performance problem with meta.
before a better solution is found. we can limit the number of files copied.
report error earlier is much better than got error after a long time when data are already copied, just not commited
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13770)
> feat: limit max copied files to 15000.

- .github/workflows/reuse.linux.yml
- .github/workflows/reuse.sqllogic.yml
- scripts/ci/ci-run-ee-sqllogic-tests.sh
- scripts/ci/ci-run-sqllogic-tests-cloud.sh
- scripts/ci/ci-run-sqllogic-tests-cluster.sh
- scripts/ci/ci-run-sqllogic-tests-management-mode.sh
- scripts/ci/ci-run-sqllogic-tests-native.sh
- scripts/ci/ci-run-sqllogic-tests-without-sandbox.sh
- scripts/ci/ci-run-sqllogic-tests.sh
- scripts/setup/dev_setup.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13851)
> chore(ci): remove test for clickhouse handler

- src/query/pipeline/core/src/processors/processor.rs
- src/query/service/src/pipelines/executor/executor_graph.rs
**Problem trying to address**:
Killing tasks in progress, such as the `replace-into` statement, may cause the query node to crash (SegmentFault).
------
**How to reproduce:**
_Single-node deployment (local fs storage is sufficient)_
- **Test table**: `create table t as select * from numbers(10000000)`
- **Continuously execute**: `replace into t on(number) select * from t`
- **Simultaneously** & continuously use the `kill query $QUERY_ID` command to kill the `replace-into` operations in progress
Usually, within half a minute (or faster), the query node will crash due to SIGSEGV.
------------------------
At least the following issue could lead to the previously described situation:
In the …
> fix: killing in-progress tasks causes query node to crash (Segment Fault)

- Cargo.lock
- src/query/ee/Cargo.toml
- src/query/ee/src/stream/handler.rs
- tests/sqllogictests/suites/ee/01_ee_system/01_0003_stream.test
Auto enable change tracking when create stream.
```sql
Query OK, 0 rows affected (0.11 sec)
Query OK, 1 row affected (0.21 sec)
mysql> create stream s on table t;
Query OK, 0 rows affected (0.17 sec)
mysql> set hide_options_in_show_create_table=0;
mysql> show create table t;
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table …
```
> feat: auto enable change tracking when create stream

- Cargo.lock
- Cargo.toml
- src/meta/service/src/grpc_helper.rs
- src/meta/service/src/meta_service/meta_node.rs
- src/meta/service/src/network.rs
- src/meta/types/src/grpc_config.rs
If an append-entries request is too large, inform Openraft to split it
into smaller chunks by returning a `PayloadTooLarge` error.
Upgrade openraft 0.8.4-alpha.10 to 0.9.0-alpha.1; Openraft change log:
- Fixed:
-   [4ad89fef](https://github.com/datafuselabs/openraft/commit/4ad89fefdf6060319d594d4a0fd6f37d6daf43ee) For single-threaded execution, there is no need for `Send`/`Sync` bounds.
- Changed:
-   [87c0d74f](https://github.com/datafuselabs/openraft/commit/87c0d74fb4941a87e7aaeb8961e0f9381d637eb9) remove `N, LS, SM` from `Raft<C, N, LS, SM>`.
- Added:
-   [961469c0](https://github.com/datafuselabs/openraft/commit/961469c05214059cd536457079b05a10343879e3) add `PayloadTooLarge` error.
- Improvement …
> refactor: auto split large append-entries RPC

- src/query/ast/src/parser/query.rs
- src/query/ast/tests/it/testdata/statement-error.txt
- tests/sqllogictests/suites/query/select.test
`from table select * `  equals to `select * from table`
The former one could be useful if the select list is very long which may help people notice which table did this SQL select from, this feature is enabled in DuckDB and clickhouse.
cc @soyeric128 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13859)
> chore(query): support from first query

- Cargo.lock
- src/query/functions/Cargo.toml
- src/query/functions/tests/it/scalars/testdata/geo_h3.txt
- tests/sqllogictests/suites/query/02_function/02_0060_function_geo_h3.test
Bump h3 to 0.4.0, the difference in the results is because they fixed "update precomputed average edge lengths (they were underestimated)." in 0.3.5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13874)
> chore: bump h3 from 0.3.0 to 0.4.0

- src/query/sql/src/planner/binder/location.rs
- src/query/sql/tests/location.rs
feat: Load credential while role_arn has been specified
Tested in our dev env:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13875)
> feat: Load credential while role_arn has been specified

- src/query/expression/src/evaluator.rs
- src/query/expression/src/function.rs
- src/query/sql/src/planner/binder/join.rs
- src/query/sql/src/planner/semantic/type_check.rs
- src/query/storages/system/src/table_functions_table.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
- tests/sqllogictests/suites/query/02_function/02_0061_function_array.test
- tests/sqllogictests/suites/query/join/join.test
- check join condition with aggregate and window functions
- lambda function params allow upper case letter
- table function names add SRF functions
- fix SQLSmith panic caused by MapAccessor
- simplify the writing of some evaluator run lambda codes
Closes #13868
Closes #13423
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13879)
> fix(query): fix check join condition with aggregate and window functions

- src/query/catalog/src/plan/stream_column.rs
- src/query/sql/src/executor/table_read_plan.rs
```
if parts.partitions.len() == 1 {
let part = parts.partitions[0].clone();
if let Ok(part) = StreamTablePart::from_part(&part) {
parts = part.inner();
base_block_ids = Some(part.base_block_ids());
}
}
```
` if let Ok(part) = StreamTablePart::from_part(&part) {` will always bring the error stack each time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13901)
> chore: change Result to Option to avoid bring error stack

- .github/actions/test_sqllogic_stage/action.yml
- src/query/service/src/table_functions/infer_schema/infer_schema_table.rs
- src/query/service/src/table_functions/infer_schema/table_args.rs
- src/query/sql/src/planner/binder/mod.rs
- tests/sqllogictests/suites/stage/formats/parquet/infer_schema.test
support `infer_schema(location => <uri>, connection_name => <connection_name>)`
- Closes #13749 issue
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13890)
> feat: support connection in stage related infer_schema

- src/meta/app/src/principal/user_stage.rs
- src/meta/proto-conv/src/stage_from_to_protobuf_impl.rs
- src/meta/proto-conv/tests/it/user_proto_conv.rs
- src/meta/proto-conv/tests/it/v025_user_stage.rs
- src/meta/proto-conv/tests/it/v035_user_stage.rs
- src/meta/proto-conv/tests/it/v042_s3_stage_new_field.rs
- src/query/service/src/interpreters/access/privilege_access.rs
- src/query/service/src/table_functions/infer_schema/infer_schema_table.rs
- src/query/service/src/table_functions/inspect_parquet/inspect_parquet_table.rs
- src/query/service/src/table_functions/list_stage/list_stage_table.rs
- src/query/storages/system/src/stages_table.rs
- tests/suites/0_stateless/18_rbac/20_0012_privilege_access.result
- tests/suites/0_stateless/18_rbac/20_0012_privilege_access.sh
- tests/suites/1_stateful/00_stage/00_0012_stage_priv.result
- tests/suites/1_stateful/00_stage/00_0012_stage_priv.sh
Added missing permission checks:
1. insert into table `query`
2. replace table on `query`
3. create table as `select query`
4. copy into table from `query`
The query needs to be checked. If there is no permission, the statement needs to report an error.
After the corresponding permission is added, the command can be executed normally.
This pr is the improvement of the permission check and will not cause breaking
- Closes #13727
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13845)
> fix(query): add some dml prvilege check

- src/query/pipeline/transforms/src/processors/transforms/mod.rs
- src/query/pipeline/transforms/src/processors/transforms/sort/rows/common.rs
- src/query/pipeline/transforms/src/processors/transforms/sort/rows/mod.rs
- src/query/pipeline/transforms/src/processors/transforms/sort/rows/simple.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_accumulating.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge_base.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge_limit.rs
- tests/sqllogictests/suites/mode/standalone/explain/sort.test
- tests/sqllogictests/suites/mode/standalone/explain/window.test
Use `TransformSortMergeBase` to unify the most logic of `TransformSortMerge` and `TransformSortMergeLimit`.
This is also a pre-task of implementing external sort.
`TransformSortMergeBase` will be wrapped in `AccumulatingTransformer`. It makes the transform can either outputs block or not while processing the input block:
- Common path: not output blocks until `on_finish`.
- Spill path: output block with spilling information in its block meta.
Tracking in #13889
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13927)
> refactor: abstract `TransformSortMergeBase` to unify merge sort logic.

- src/query/service/src/servers/http/clickhouse_handler.rs
- src/query/service/src/servers/http/v1/load.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/http_query_context.rs
- src/query/service/src/servers/http/v1/stage.rs
- src/query/service/src/servers/http/v1/suggestions.rs
- src/query/service/src/sessions/session_mgr.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- src/query/service/tests/it/servers/mysql/mysql_handler.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13931)
> fix: max_active_session does not work for http handler.

- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/window_function/expr_in_window.test
chore: fix lag default arg bug:
when query with `SELECT lag([456],8,[123]) OVER (PARTITION BY 10);`
```
panicked at src/query/expression/src/values.rs:2582:30:
internal error: entered unreachable code: unable append column(data type: Nullable(Number(UInt16))) into builder(data type: Number(UInt16))
```
because cast default expr `123` with `is_try` true.
- Closes https://github.com/datafuselabs/databend/issues/13865
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13937)
> chore: fix lag default arg bug

- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/spillers/spiller.rs
- tests/sqllogictests/suites/query/spill.test
1. make build and probe hash method consistent to make them hash values consistent
2. avoid to concat empty blocks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13942)
> fix: make build and probe hash method consistent in spill

- src/common/base/tests/it/runtime.rs
Fix https://github.com/datafuselabs/databend/actions/runs/7138773393/job/19440897142#step:4:2938
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13963)
> chore: fix runtime ut to tokio::time::sleep in async

- Cargo.lock
- Cargo.toml
- src/bendpy/Cargo.toml
- tests/suites/1_stateful/07_stage_attachment/07_0002_insert_with_stage_deduplicate.sh
**tokio: 1.26.0 to 1.35.0**
https://github.com/tokio-rs/tokio/releases/tag/tokio-1.35.0
- Closes #13966
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13967)
> chore: bump tokio from 1.26.0 to 1.35.0

- Cargo.lock
- src/common/io/Cargo.toml
- src/common/io/src/serialization.rs
- src/common/io/tests/it/main.rs
- src/common/io/tests/it/serialization.rs
- src/query/expression/tests/it/serde.rs
- src/query/functions/Cargo.toml
- src/query/functions/src/aggregates/aggregator_common.rs
- src/query/service/Cargo.toml
- src/query/service/src/api/rpc/exchange/serde/exchange_deserializer.rs
- src/query/service/src/api/rpc/exchange/serde/exchange_serializer.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_deserializer.rs
- src/query/service/tests/it/storages/fuse/meta/serialization_format_compatability.rs
**change bincode api to common/io**
* bump bincode to `version = "2.0.0-rc.3"`
* `src/query/storages/common/table_meta/Cargo.toml` still using `1.3.3` for table format it will remove later @dantengsky 
* bincode ABI is not stable, api breaking changes often, this PR shink them all to `bincode_serialize/deserialize`
- Closes #13968
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13973)
> chore: bincode api to common/io

- src/query/service/tests/it/sessions/session_setting.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- tests/sqllogictests/suites/base/06_show/06_0003_show_settings.test
- Closes #13893 issue
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/13992)
> feat: support maximum check

- src/query/settings/src/settings_default.rs
https://github.com/datafuselabs/databend/pull/13983 is not sync with main, so the settings range is missing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14009)
> fix: fix enable_refresh_virtual_column_after_write range

- src/binaries/meta/kvapi.rs
- src/meta/api/src/background_api_impl.rs
- src/meta/kvapi/src/kvapi/test_suite.rs
- src/meta/raft-store/src/applier.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map_test.rs
- src/meta/raft-store/src/sm_v002/marked/marked_test.rs
- src/meta/raft-store/src/sm_v002/marked/mod.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002_test.rs
- src/meta/raft-store/src/state_machine/sm.rs
- src/meta/raft-store/tests/it/state_machine/expire.rs
- src/meta/raft-store/tests/it/state_machine/mod.rs
- src/meta/service/tests/it/meta_node/meta_node_kv_api_expire.rs
- src/meta/types/src/cmd.rs
- src/meta/types/src/proto_ext/seq_v_ext.rs
- src/meta/types/src/seq_value.rs
- src/query/management/src/cluster/cluster_mgr.rs
- src/query/management/tests/it/cluster.rs
- src/query/storages/result_cache/src/meta_manager.rs
Make `KVMeta.expire_at` a private field for future refactoring.
Update accessing to it with via methods.
Several methods are added to `KVMeta` and `SeqValue`:
- `eval_expire_at_ms()` evaluate and return a absolute expire time in millisecond. The returned value is set to `u64::MAX` if not expire is set.
- `get_expire_at_ms()` return an `Option` of absolute expire time in millisecond.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14013)
> refactor: access KVMeta with methods instead of field

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14015)
> chore(ci): only publish deb & python binding on stable release

- src/binaries/metabench/main.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/api/src/share_api_test_suite.rs
- src/meta/app/src/schema/table.rs
- src/query/ee/src/stream/handler.rs
- src/query/service/src/interpreters/interpreter_table_drop.rs
- src/query/service/src/interpreters/interpreter_view_alter.rs
- src/query/service/src/interpreters/interpreter_view_drop.rs
- src/query/service/tests/it/catalogs/database_catalog.rs
chore: fix drop_table_by_id fail when TableIdToName cannot found
- Closes https://github.com/datafuselabs/databend/issues/13998
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14002)
> chore: fix drop_table_by_id fail when TableIdToName cannot found

- src/query/service/src/interpreters/common/util.rs
- src/query/service/src/interpreters/hook/compact_hook.rs
- src/query/service/src/interpreters/hook/mod.rs
- src/query/service/src/interpreters/hook/refresh_hook.rs
- src/query/service/src/interpreters/interpreter_copy_into_table.rs
- src/query/service/src/interpreters/interpreter_insert.rs
- src/query/service/src/interpreters/interpreter_merge_into.rs
- src/query/service/src/interpreters/interpreter_replace.rs
- src/query/service/src/interpreters/interpreter_update.rs
- src/query/service/src/interpreters/mod.rs
* move the functional ` interpreters/*_hook.rs` to `interpreters/hook/*`
* add more comments for funcs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14044)
> chore: move interpreter/*_hook.rs to hook/

- src/query/sql/src/planner/binder/show.rs
- tests/sqllogictests/suites/base/06_show/06_0003_show_settings.test
Fixes #14025 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14049)
> feat: add range for show settings

- src/common/tracing/src/init.rs
- src/common/tracing/src/loggers.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14050)
> fix: multiple otlp loggers conflict

- src/query/pipeline/core/src/pipeline.rs
- src/query/pipeline/core/src/processors/profile.rs
chore(executor): use null as root profile parent id
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14051)
> chore(executor): use null as root profile parent id

- src/query/ee/src/storages/fuse/operations/vacuum_drop_tables.rs
- src/query/ee/tests/it/storages/fuse/operations/vacuum.rs
Terminate the vacuum dropped tables operation without removing table metadata from the meta server in case of IO exceptions. 
This allows the vacuum process to be 'resumed', ensuring the eventual vacuuming of dropped tables/databases.
A minor refactor has been introduced to simplify unit test.
Fixes #14043
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14052)
> fix: abort vacuum if there are io execption

- src/meta/client/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14058)
> chore: update doc: since 1.2.258 `ttl` is supported by meta-service

- src/query/expression/src/schema.rs
- tests/sqllogictests/suites/ee/01_ee_system/01_0003_stream.test
mark  stream meta columns `change$action`, `change$is_update`, and `change$row_id` as Internal Columns,
so that test scenario of issue #14062 passes
~~~
mysql> create table t (c int);
Query OK, 0 rows affected (0.12 sec)
mysql> create stream s on table t ;
Query OK, 0 rows affected (0.12 sec)
mysql>
Query OK, 1 row affected (0.14 sec)
mysql>
mysql> select * from s where change$action = 'INSERT';
+------+
| c    |
+------+
|    1 |
+------+
1 row in set (0.09 sec)
Read 1 rows, 133.00 B in 0.038 sec., 26.02 rows/sec., 3.38 KiB/sec.
mysql>
mysql> select * from s where change$is_update = false;
+------+
| c    |
+------+
|    1 |
+------+
1 row in set (0.09 sec) …
> fix: treat change$* as internal columns

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
fix: fix get db without DbIdList key
- [*] Unit Test
- [*] Bug Fix (non-breaking change which fixes an issue)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14059)
> fix: fix get db without DbIdList key

- src/query/storages/fuse/src/io/read/block/decompressor.rs
fix(query): fix panic when drop UncompressedBuffer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14068)
> fix(query): fix panic when drop UncompressedBuffer

- README.md
There are two links in README which will lead to 404 NotFound pages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14090)
> docs: replace the wrong links in README

- src/query/expression/src/type_check.rs
- src/query/functions/src/scalars/decimal/math.rs
- src/query/functions/tests/it/scalars/math.rs
- src/query/functions/tests/it/scalars/testdata/math.txt
- src/query/sql/src/planner/semantic/type_check.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14087)
> chore(query): desugar round/truncate

- src/query/sql/src/planner/binder/ddl/table.rs
- tests/sqllogictests/suites/base/05_ddl/05_0003_ddl_rename_table.test
Rename table not allow modify catalog or database
It's no use to support this, It will cause other questions.
```sql
rename table db1.t1 to db2.t2
```
BTW alter table can also rename table, it also not support modify database.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14098)
> chore(query): Rename table not allow modify catalog or database

- src/common/exception/src/exception_code.rs
- src/query/sharing/src/share_endpoint.rs
- src/query/sql/src/planner/binder/table.rs
- tests/suites/3_stateful_sharing/01_sharing/01_0000_basic_sharing.result
1. handle error returned from resolve_data_source()
2. fix drop share database error
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14097)
> chore: handle error returned from resolve_data_source()

- src/query/pipeline/core/src/pipeline.rs
- src/query/service/src/pipelines/builders/builder_join.rs
- src/query/service/src/pipelines/builders/builder_union_all.rs
fix(executor): fix broken profile graph for union all
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14107)
> fix(executor): fix broken profile graph for union all

- src/common/metrics/src/metrics/http.rs
- src/query/service/src/servers/http/middleware.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/http_query_context.rs
http query request is expected to responded within 60s, but some times we get longer response durations. this PR correlated the slow request log with query id, thus may help diagnosis these timeout issues.
this pr also added a histogram metric `query_http_response_duration_seconds` to track the response duration of individual requests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14082)
> chore(query): add log on slow http query request

- src/query/service/src/pipelines/processors/transforms/transform_sort_spill.rs
- tests/suites/0_stateless/20+_others/20_0014_sort_spill.result
`TransformSortSpill` would merge multiple sorted streams into one sorted stream. 
The new implementation makes the last merge sort run not spill the result to storage but output to downstream in memory directly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14091)
> chore: the final merge sort run outputs blocks directly.

- src/query/catalog/src/table_context.rs
- src/query/service/src/interpreters/hook/compact_hook.rs
- src/query/service/src/interpreters/interpreter_copy_into_table.rs
- src/query/service/src/interpreters/interpreter_insert.rs
- src/query/service/src/interpreters/interpreter_merge_into.rs
- src/query/service/src/interpreters/interpreter_replace.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/tests/it/sql/exec/get_table_bind_test.rs
- src/query/service/tests/it/storages/fuse/operations/commit.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/storages/fuse/src/operations/common/snapshot_generator.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0023_replace_into.test
* use `enable_recluster_after_write` to control compact is not meaningful, plan to deprecated it in the future
* add `enable_compact_after_write` to control the compact after COPY/REPLACEINTO, this including recluster
* `*_auto_compact_after_write` to `*_need_compact_after_write`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14114)
> chore: refine enable_compact_after_write, enable_recluster_after_write need deprecated

- src/query/service/tests/it/storages/fuse/operations/mutation/block_compact_mutator.rs
- src/query/service/tests/it/storages/fuse/operations/mutation/segments_compact_mutator.rs
- src/query/storages/fuse/src/operations/compact.rs
- src/query/storages/fuse/src/operations/mutation/compact/block_compact_mutator.rs
- src/query/storages/fuse/src/operations/mutation/compact/segment_compact_mutator.rs
`CompactOptions::limit` is used by both compact segment and compact block, as the threshold of the number of segments to be compacted.
It is a little bit confusing, so rename it to `num_segment_limit`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14116)
> chore: rename `CompactOptions::limit` to `num_segment_limit`

- src/query/service/src/interpreters/hook/compact_hook.rs
add limit 3 (segments) for compact hook to prevent out-of-memory (OOM) issues when compaction is triggered on tables with a large volume of uncompacted data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14115)
> chore: add limit for compact hook

- src/query/ee/tests/it/aggregating_index/index_refresh.rs
- src/query/service/src/interpreters/hook/compact_hook.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/storages/fuse/src/operations/common/snapshot_generator.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0001_remote_insert.test
- tests/sqllogictests/suites/mode/cluster/distributed_copy_into_table2.test
* remove warn log from hook_compact, this maybe flood
*  `auto_compaction_threshold` -> `auto_compaction_imperfect_blocks_threshold`, make it more meaningful
*  collapsed hook_compact setting checks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14117)
> chore: remove the compact hook warn message and rename auto_compaction_threshold to auto_compaction_imperfect_blocks_threshold

- tests/sqllogictests/suites/base/01_system/01_0013_system_metrics.test
remove this flaky test:
```
onlyif mysql
query I
SELECT sum(to_int32(to_float32(value) > 5)) FROM system.metrics where metric = 'query_success_total'
----
0
```
Fixes #14120
Fixes #14103
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14123)
> chore: remove flaky test(cluster) in 01_0013_system_metrics.test

- src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge_base.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge_limit.rs
- src/query/service/src/pipelines/builders/builder_sort.rs
- src/query/service/src/pipelines/processors/transforms/transform_sort_spill.rs
- tests/suites/0_stateless/20+_others/20_0014_sort_spill.result
- tests/suites/0_stateless/20+_others/20_0014_sort_spill.sql
Top-N sort can also be spilled now.
Tracking in #13889
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14131)
> feat: make Top-N sort can be spilled.

- src/query/service/src/interpreters/hook/compact_hook.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
* remove the unused setting: `enable_recluster_after_write`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14146)
> chore: remove the unused setting:enable_recluster_after_write

- src/query/sql/src/planner/binder/select.rs
- src/query/sql/src/planner/semantic/virtual_column_rewriter.rs
- tests/sqllogictests/suites/mode/standalone/ee/explain_virtual_column.test
Only push down user-created virtual columns to avoid incorrect displays that may confuse users.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14147)
> chore(query): virtual columns not pushdown if not created

- src/meta/service/src/metrics/meta_metrics.rs
- src/meta/service/src/network.rs
Remove the manually implemented backoff logic from meta-service internal
`Network` module.
Add a new metric `append_sent_seconds` to observe time spent on sending
append-entries RPC between meta-service node.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14154)
> refactor: delegate backoff handling to Openraft

- src/binaries/metactl/grpc.rs
- src/meta/client/src/established_client.rs
- src/meta/client/src/grpc_action.rs
- src/meta/client/src/grpc_client.rs
- src/meta/client/src/lib.rs
- src/meta/client/src/message.rs
- src/meta/client/tests/it/grpc_client.rs
- src/meta/client/tests/it/grpc_server.rs
- src/meta/kvapi/src/kvapi/message.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_export.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_handshake.rs
- src/meta/types/src/errors/meta_client_errors.rs
Before this commit the connection pool stores raw connections `Channel`.
Before using one, the client handshake with the server everytime using a
channel.
In this commit, the handshake is moved into the connection pool and the
pool stores `MetaServiceClient` that already finished the handshake
phase.
Thus the client no longer needs to send a handshake RPC before using an
in-pool connection.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14161)
> refactor: move to meta-service handshake into pool

- src/query/storages/fuse/src/io/read/block/block_reader_native.rs
1. No need to assign value to `num_rows` more than once.
2. Add assert to ensure each array has the same length.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14164)
> refactor: build_block method

- src/query/service/src/api/rpc/exchange/data_exchange.rs
- src/query/service/src/api/rpc/exchange/exchange_manager.rs
- src/query/service/src/interpreters/interpreter_copy_into_table.rs
- src/query/service/src/interpreters/interpreter_index_refresh.rs
- src/query/service/src/schedulers/fragments/fragmenter.rs
- src/query/service/src/schedulers/fragments/mod.rs
- src/query/service/src/schedulers/fragments/plan_fragment.rs
- src/query/sql/src/executor/physical_plans/physical_copy_into.rs
- src/query/sql/src/executor/physical_plans/physical_exchange.rs
- src/query/sql/src/planner/format/display_rel_operator.rs
- src/query/sql/src/planner/optimizer/mod.rs
- src/query/sql/src/planner/optimizer/optimizer.rs
- src/query/sql/src/planner/optimizer/property/enforcer.rs
- src/query/sql/src/planner/plans/exchange.rs
- src/query/sql/src/planner/plans/join.rs
- src/query/sql/src/planner/plans/union_all.rs
- tests/sqllogictests/suites/crdb/limit.test
- tests/sqllogictests/suites/mode/cluster/distributed_compact.sql.test
- tests/sqllogictests/suites/mode/cluster/exchange.test
- tests/sqllogictests/suites/mode/standalone/limit.test
- tests/sqllogictests/suites/query/union.test
This pull request involves the restructuring of logic related to the exchange operator and random distribution.
In a cluster environment, where table data is partitioned across query nodes based on a specified scheme, each `TableScan` operator can inherently offer the `Distribution::Random` property. Consequently, there's no longer a necessity for an `Exchange::Random` operator to consistently enforce the `Distribution::Random` property.
Following the implementation of this pull request, the union-all and broadcast join operators will no longer be required to enforce the `Distribution::Random` for their respective children.
- - - …
> refactor(planner): Correct usage of exchange operator

- src/query/functions/src/scalars/arithmetic.rs
- tests/sqllogictests/suites/query/functions/cast.test
Fix the issue where cast domain values did not perform rounding operation resulting in incorrect cast results
Fixes #14156
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14158)
> fix(query): fix cast domain values did not perform rounding operation

- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14186)
> chore: rename hash join probe state name

- src/query/service/src/api/http/v1/mod.rs
- src/query/service/src/api/http/v1/stream_status.rs
- src/query/service/src/api/http_service.rs
```shell
✗ curl -sL -u root:  http://127.0.0.1:8081/v1/tenants/system/stream_status?stream_name=s&database=default
{"has_data":false,"params":{"database":"default","stream_name":"s"}}                                                             
✗ curl -sL -u root:  http://127.0.0.1:8081/v1/tenants/system/stream_status?stream_name=s1
UnknownTable. Code: 1025, Text = Unknown table 's1'.
✗ curl -sL -u root:  http://127.0.0.1:8081/v1/tenants/test_tenant/stream_status?stream_name=s
{"has_data":true,"params":{"database":null,"stream_name":"s"}}
```
- - - …
> feat: add stream_status http api

- src/query/catalog/Cargo.toml
- src/query/catalog/src/runtime_filter_info.rs
- src/query/catalog/src/table_context.rs
- src/query/service/Cargo.toml
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/tests/it/sql/exec/get_table_bind_test.rs
- src/query/service/tests/it/storages/fuse/operations/commit.rs
- src/query/storages/fuse/Cargo.toml
- src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs
- src/query/storages/fuse/src/operations/read/parquet_data_source_deserializer.rs
- src/query/storages/fuse/src/operations/read/runtime_filter_prunner.rs
- `Binaryfuse16` will reduce fp rate
- disabling feature `uniform-random` can reduce the cost of building bloom filter: https://github.com/ayazhafiz/xorf?tab=readme-ov-file#uniform-random
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14187)
> refactor: use `Binaryfuse16` and disable feature `uniform-random`

- Cargo.lock
- src/meta/api/Cargo.toml
- src/meta/api/src/background_api_impl.rs
- src/meta/api/src/data_mask_api_impl.rs
- src/meta/api/src/lib.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/share_api_impl.rs
- src/meta/api/src/txn_backoff.rs
- src/meta/api/src/util.rs
Introduce an exponential backoff strategy for meta-service transaction
retries to mitigate race conditions. Upon a transaction failure, the
system now initiates a delay before the next attempt, reducing the
likelihood of concurrent transaction conflicts.
The backoff intervals follow an exponential pattern, calculated as
`1.4^i * 10 milliseconds`, where `i` is the current retry count:
```
0ms, 10ms, 14ms, 20ms, 29ms, 42ms, 61ms, 89ms, 128ms, 184ms, 266ms, 383ms, 552ms, 794ms, 794ms, 794ms, ...
```
This change aims to improve the robustness of the transaction handling
by spacing out retries in the face of transient failures.
The number of attempt to retry is increased from 10 to 60.
- …
> refactor: Implement exponential backoff in meta-service txn retries

- src/query/expression/src/filter/select.rs
Solve the problem in https://github.com/datafuselabs/databend/pull/14190
| query | main      | pr        | 
| ----- | --------- | --------- |
| Q1    | 12.7  | 11.8 |
| Q3   | 5.1  | 4.2  |
| Q4    | 3.6  | 3.2  |
| Q6    | 5.3  | 4.2  |
| Q7    | 5.6   | 4.6  |
| Q10   | 7.9  | 6.2  |
| Q12    | 7.9  | 6.3  |
| Q14    | 4.1   | 3.5  |
| Q15   | 7.0  | 5.9  |
| Q19   | 11.3 | 9.6 |
| Q20   | 17.3  | 15.5  |
| Q21   | 8.2  | 6.7  |
**TPC-H SF100 External Parquet Q19 FlameGraph before:**
**TPC-H SF100 External Parquet Q19 FlameGraph after:**
- - - …
> chore(query): better handling of nullable columns during filter execution

- Cargo.lock
- Cargo.toml
- src/meta/client/src/lib.rs
- src/meta/service/Cargo.toml
- src/meta/service/src/version.rs
Since  1.2.279, compatibility layer `Compatible` for receiving error is
removed from meta-client.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14214)
> refactor: Define features provided by raft server and features required by raft client

- src/query/sql/src/planner/optimizer/optimizer.rs
- tests/sqllogictests/suites/mode/cluster/exchange.test
https://github.com/datafuselabs/databend/pull/14163/files#diff-a41c4bd239da9fa211688e4b794d66954fedbcf69449b9a578fefdfaf0af50c2R309
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14218)
> fix: disable distributed plan after disabling join reorder

- src/query/sql/src/planner/binder/ddl/table.rs
- tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.result
- tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.sql
Fixes #14152
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14219)
> feat: add owner field into show full tables

- src/query/expression/src/values.rs
- src/query/functions/tests/it/scalars/testdata/array.txt
- tests/sqllogictests/suites/crdb/conditional.test
fix: fix EmptyMap domain as undefine
Fixes #[https://github.com/datafuselabs/databend/issues/13869]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14226)
> fix: fix EmptyMap domain as undefine

- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/02_function/02_0062_function_unnest.test
_Unnest cannot contain aggregate or window functions; otherwise, an error should be returned._
```
select unnest(max(1));
error: APIError: ResponseError with 1065: error:
--> SQL:1:15
|
1 | select unnest(max(1))
|               ^^^^^^ aggregate functions can not be used in set-returning function
```
Fixes #[#13057]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14233)
> fix: aggregate and window function as the argument of unnest return unable to get field named

- src/query/service/src/interpreters/hook/hook.rs
- src/query/service/src/interpreters/hook/mod.rs
- src/query/service/src/interpreters/hook/refresh_hook.rs
- src/query/service/src/interpreters/interpreter_copy_into_table.rs
- src/query/service/src/interpreters/interpreter_insert.rs
- src/query/service/src/interpreters/interpreter_merge_into.rs
- src/query/service/src/interpreters/interpreter_replace.rs
- src/query/service/src/interpreters/interpreter_update.rs
- src/query/service/src/interpreters/mod.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
* add `enable_refresh_aggregating_index_after_write` setting
* add `HookOperator` to make the hook execute more simple:
```
let hook_operator = HookOperator::create(...);
hook_operator.execute().await; -- execute compact and refresh hook
hook_operator.execute_compact().await; 
hook_operator.execute_refresh().await; 
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14250)
> chore: refactor the hook

- src/query/sql/src/planner/semantic/aggregating_index_visitor.rs
- tests/sqllogictests/suites/mode/standalone/ee/explain_agg_index.test
`count(col)` will be rewritten to `count()` if col is NOT nullable, as create agg index will rewrite statement and don't know the col's datatype, we will provide both `count(col)` and `count()` for agg index, make query rewrite with agg index happy.
Fixes #14249 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14256)
> fix: fix count rewrite in agg index

- src/meta/client/src/grpc_client.rs
- src/meta/client/src/lib.rs
- src/meta/client/src/message.rs
- src/meta/client/tests/it/grpc_client.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_kv_read_v1.rs
For meta-service gRPC client: non stream oriented API `Get(r)`,
`MGet(r)`, `List(r)` are all replaced with stream oriented API.
Stream oriented API `StreamGet(r)` is replaced with `StreamMGet(r)`,
because `mget` is a superset of `get`.
`MetaGrpcClient::kv_api()` now only accepts `Upsert` request;
Remove fallback from `kv_read_v1(Streamed(List))` to `kv_api(List)`,
which added in `2023-10-20: since 1.2.176`, all read requests are called
via stream API.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14258)
> refactor: remove from `message::Request`: `Get(r)`, `MGet(r)`, `List(r)` and `StreamGet(r)`.

- src/binaries/metactl/snapshot.rs
- src/meta/raft-store/src/config.rs
- src/meta/service/src/configs/outer_v0.rs
- src/meta/service/src/meta_service/meta_node.rs
- src/meta/service/tests/it/tests/service.rs
- src/meta/types/src/endpoint.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14265)
> refactor: Endpoint: add parse(); make fields private

- Cargo.lock
- src/common/exception/Cargo.toml
- src/common/exception/src/exception_into.rs
- src/meta/stoerr/Cargo.toml
- src/meta/stoerr/src/meta_storage_errors.rs
- src/meta/types/Cargo.toml
- src/meta/types/src/errors/meta_api_errors.rs
- src/meta/types/src/errors/meta_errors.rs
- src/query/config/Cargo.toml
The `databend-common-exception` crate, which is a general-purpose
library, should not have a dependency on the business-specific
`databend-common-meta-types` crate.
With this commit, we've relocated the conversion logic for transforming
`Meta**` errors into `ErrorCode`. These conversions are now handled
within the meta-service related crates: `databend-common-meta-types` and
`databend-common-sto-error`.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14275)
> refactor: `common-exception` crate should be independent of `meta-types`

- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
Use raw formatted SQL instead of prettied one.
Previous, task SQL used the pretty_statement function and generate prettified SQL for further cloud service execution, but it seems like there are some SQL may parse in different way and unable to execute anymore. for example
```sql
copy into @stream_stage from (
SELECT
CASE
WHEN (RAND() * 10)::INT % 4 = 0 THEN 'a'
WHEN (RAND() * 10)::INT % 4 = 1 THEN 'b'
WHEN (RAND() * 10)::INT % 4 = 2 THEN 'c'
ELSE 'd'
END AS level
FROM numbers(500000)
) FILE_FORMAT = (
TYPE = PARQUET
);
```
its pretty formatted string is 
```sql …
```
> chore: use raw sql as task SQL instead of pretty one

- Cargo.lock
- src/binaries/metabench/main.rs
- src/binaries/metactl/grpc.rs
- src/binaries/metactl/main.rs
- src/common/base/src/future.rs
- src/meta/client/Cargo.toml
- src/meta/client/src/endpoints.rs
- src/meta/client/src/established_client.rs
- src/meta/client/src/grpc_client.rs
- src/meta/client/src/lib.rs
- src/meta/client/tests/it/grpc_client.rs
- src/meta/service/src/api/grpc/grpc_service.rs
- src/meta/service/src/meta_service/forwarder.rs
- src/meta/service/src/meta_service/meta_node.rs
- src/meta/service/src/meta_service/meta_node_kv_api_impl.rs
- src/meta/service/src/meta_service/raft_service_impl.rs
- src/meta/service/src/network.rs
- src/meta/service/src/request_handling.rs
- src/meta/service/src/store/store_inner.rs
- src/meta/service/tests/it/grpc/metasrv_connection_error.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_kv_api_restart_cluster.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_kv_read_v1.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_tls.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_transaction.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_watch.rs
- src/meta/service/tests/it/grpc/mod.rs
- src/meta/service/tests/it/tests/service.rs
- src/meta/types/src/endpoint.rs
- src/meta/types/src/grpc_helper.rs
New feature, compatible change.
When a meta-service follower receives a request, it forwards it to the
leader. This mechanism introduces additional latency.
In this commit:
- Meta-service responds the leader-address in gRPC
header(response metadata): "x-databend-meta-leader-grpc-endpoint",
if the meta-service node is a follower.
- Meta-client that receives such a reponse metadate then updates the
address for further connection to this perceived leader.
- Leader endpoint response is added to two API: `transaction()` and
`kv_read_v1()`, which are the most used by `SchemaApi`, and very
latency sensitive.
`upsert()` and `kv_read()`(v0 API) are not changed: `upsert()` will be
replaced with …
> feat: return latest leader addr if request is forwarded

- tests/suites/0_stateless/18_rbac/18_0002_ownership_cover.result
- tests/suites/0_stateless/18_rbac/18_0002_ownership_cover.sh
fix flaky 18_0002_ownership_cover
Fixes #14299
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14300)
> chore(flaky): fix flaky 18_0002_ownership_cover

- src/query/storages/system/src/tables_table.rs
Fix:
```
error: None, warnings: ["get database failed: default"] }, rows=0, next_page=None, sql='show tables'
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14309)
> chore: fix system table ctx warning and log more warnings to log

- src/query/sql/src/executor/format.rs
- src/query/sql/src/executor/physical_plans/physical_cte_scan.rs
- tests/sqllogictests/suites/mode/standalone/explain/materialized_cte.test
- tests/sqllogictests/suites/tpch/queries.test
add cardinality to CteScan explain
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14310)
> refactor: add cardinality to CteScan explain

- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/sql/src/planner/plans/join.rs
Provide a switch to compare the performance of shuffle join and broadcast join.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14361)
> chore: add a setting to enforce broadcast join

- src/query/service/src/servers/http/v1/query/http_query.rs
- tests/suites/1_stateful/07_stage_attachment/07_0003_insert_with_stage_file_format.result
- tests/suites/1_stateful/07_stage_attachment/07_0003_insert_with_stage_file_format.sh
consist with that in SQL:
keys are case-insensitive, but values depend (enum is insensitive, but string is sensetive).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14357)
> fix: keys in stage_attachment.file_format_options should be case-insensitive

- Cargo.lock
- src/meta/client/src/lib.rs
- src/meta/raft-store/src/applier.rs
- src/meta/raft-store/src/state_machine/sm.rs
- src/meta/types/proto/request.proto
- src/meta/types/src/proto_display.rs
Meta-service does not check `TxnPutRequest.prev_value` and
`TxnDeleteRequest.prev_value` any more, and always assumes it is true.
When a `Put` or `Delete` request is executed, the previous value before
`Put` will always be responded.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14371)
> refactor: do not use `TxnPutRequest|TxnDeleteRequest.prev_value`, always return previous value

- src/query/expression/src/types/number.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/agg_index/query_rewrite.rs
When we compare the `Range` of agg index, we need to compare the internal value of the `Scalar` instead of comparing `Scalar` directly, for example, both `NumberScalar(UInt8(1)) == NumberScalar(UInt32(1))` and `NumberScalar(UInt8(2)) > NumberScalar(UInt32(1))` should return `true`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14378)
> chore(query): improve agg index range comparison

- Cargo.lock
- src/query/config/src/config.rs
- src/query/config/src/inner.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
- src/query/settings/Cargo.toml
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/settings/tests/it/setting.rs
- add new settings `data_retention_time_in_days` and new config `data_retention_time_in_days_max `
* Setting `data_retention_time_in_days` default value is `1` days
* Config `data_retention_time_in_days_max` default is `90` days
* Setting range is `[0, config.query.data_retention_time_in_days_max]`
Like:
```
set data_retention_time_in_days=91;
WrongValueForVariable. Code: 2803, Text = Value 91 is not within the range [0, 90].
```
Config `config.query.data_retention_time_in_days_max=33`:
```
set data_retention_time_in_days=34;
WrongValueForVariable. Code: 2803, Text = Value 34 is not within the range [0, 33].
```
- - - …
> feat: add data_retention_time_in_days_max config and data_retention_time_in_days setting

- src/query/settings/src/settings_default.rs
- src/query/storages/fuse/src/operations/common/snapshot_generator.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0001_remote_insert.test
- tests/sqllogictests/suites/mode/cluster/distributed_copy_into_table2.test
set the default value of `auto_compaction_imperfect_blocks_threshold default value` to 50,  because now the hook compact has added a limit of 3, which has a minimal impact on writing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14390)
> chore: set auto_compaction_imperfect_blocks_threshold to 50

- src/query/functions/src/scalars/variant.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/variant.txt
- tests/sqllogictests/suites/query/02_function/02_0051_function_semi_structureds_get.test
- fix `json_extract_path_text`, `to_string`, `get_string` extract string for JSON string type, remove redundant quotes
- make `json_to_string` as alias of `to_string`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14389)
> fix(query): fix json cast to string with quote

- src/tests/sqlsmith/src/sql_gen/ddl.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
fix generate nested not null types caused panic
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14392)
> fix(sqlsmith): fix generate nested not null types caused panic

- Cargo.lock
- Cargo.toml
- src/common/storage/src/operator.rs
Enable async backtrace for opendal and decrease timeout to 10s
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14384)
> feat: Enable async backtrace for opendal

- Cargo.lock
- src/meta/app/Cargo.toml
- src/meta/app/src/principal/file_format.rs
- src/meta/app/src/principal/user_stage.rs
- tests/sqllogictests/suites/stage/formats/csv/csv_delimiter.test
- tests/sqllogictests/suites/stage/formats/csv/csv_option_escape.test
- tests/sqllogictests/suites/stage/formats/csv/csv_types.test
- tests/sqllogictests/suites/stage/formats/ndjson/ndjson_null_and_missing.test
I see no reason to allow any values.
less choice is good for:
1. avoid users to use what not intended (typo, or mistake when involving escaping). 
2. avoid users to use what is no recommended (e.g. avoid alphanumeric for delimiter)
3. may make the parser a little faster.
4. avoid some ambiguity when parsing (e.g. avoid alphanumeric for delimiter)
we can add to the whitelist when something is really needed.
- quote: ["\'", "\"", "`"]
- escape:  ["\\", ""]
- field_delimiter/record_delimiter:  one-byte, non-alphanumeric
and unify related error messages.
- - - …
> feat: more constrain for file format string options.

- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_scan.rs
- tests/sqllogictests/suites/mode/standalone/ee/explain_agg_index.test
- tests/sqllogictests/suites/mode/standalone/explain/eliminate_outer_join.test
- tests/sqllogictests/suites/mode/standalone/explain/explain.test
- tests/sqllogictests/suites/mode/standalone/explain/join.test
- tests/sqllogictests/suites/mode/standalone/explain/push_down_filter.test
- tests/sqllogictests/suites/mode/standalone/explain/subquery.test
- tests/sqllogictests/suites/mode/standalone/explain_native/join.test
- tests/sqllogictests/suites/mode/standalone/explain_native/push_down_filter.test
- tests/sqllogictests/suites/mode/standalone/explain_native/subquery.test
If `is_source_of_view` is false, we need to replace column alias name with original column name.
- Fixes #14410
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14415)
> chore(planner): fix push down filter scan

- Cargo.lock
- src/meta/api/Cargo.toml
- src/meta/api/src/testing.rs
- src/meta/api/src/util.rs
- src/meta/process/Cargo.toml
- src/meta/process/src/rewrite_kv.rs
- src/meta/proto-conv/Cargo.toml
- src/meta/proto-conv/src/file_format_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/from_to_protobuf.rs
- src/meta/proto-conv/src/lib.rs
- src/meta/proto-conv/src/stage_from_to_protobuf_impl.rs
- src/meta/proto-conv/tests/it/common.rs
- src/meta/proto-conv/tests/it/proto_conv.rs
- src/meta/proto-conv/tests/it/user_proto_conv.rs
- src/query/management/Cargo.toml
- src/query/management/src/serde/pb_serde.rs
add trait bound prost::Message+Default to FromToProto::PB;
and add FromToProtoEnum to define behavior converting enum. in protobuf enum is not a Message
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14423)
> refactor: Add trait FromToProtoEnum

- scripts/setup/dev_setup.sh
`cargo-audit` published a release [v0.18.3](
https://github.com/rustsec/rustsec/releases/tag/cargo-audit%2Fv0.18.3) which has dependency of GLIBC 2.34, while our CI image only have GLIBC 2.31.
To prevent downloading the incompatible tools, we will use `cargo install` for them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14438)
> chore: fix build tool installation

- src/query/config/src/config.rs
- src/query/config/src/inner.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/settings/src/settings.rs
- src/query/settings/src/settings_getter_setter.rs
- tests/sqllogictests/suites/base/05_ddl/05_0026_ddl_unset_settings.test
- tests/sqllogictests/suites/base/06_show/06_0003_show_settings.test
Support loading query settings from config as scope `LOCAL`.
Then we do not need to add every user setting to config struct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14441)
> feat(query): support session setting scope `LOCAL`

- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/sql/src/planner/optimizer/cascades/cascade.rs
- src/query/sql/src/planner/optimizer/cost/cost_model.rs
Introduce some settings to configure the cost factors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14445)
> chore: make cost factor configurable

- src/query/sql/src/planner/binder/delete.rs
- src/query/sql/src/planner/binder/join.rs
- src/query/sql/src/planner/optimizer/decorrelate/decorrelate.rs
- src/query/sql/src/planner/optimizer/decorrelate/flatten_plan.rs
- src/query/sql/src/planner/optimizer/decorrelate/subquery_rewriter.rs
- src/query/sql/src/planner/optimizer/optimizer.rs
to avoid agg shuffle under cluster mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14452)
> chore: only wrap logical get with distinct to eliminate duplicates rows for subquery in single mode

- src/binaries/Cargo.toml
- src/binaries/metactl/grpc.rs
- src/binaries/metactl/main.rs
- src/binaries/metactl/snapshot.rs
- src/meta/client/src/established_client.rs
- src/meta/client/src/grpc_client.rs
- src/meta/client/src/lib.rs
- src/meta/client/src/message.rs
- src/meta/client/tests/it/grpc_server.rs
- src/meta/service/src/api/grpc/grpc_service.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_export.rs
- src/meta/types/proto/meta.proto
Use `databend-metactl --export --export-chunk-size <n>` to export all meta
data with a stream in which each item contains at most `n` lines.
Specify smaller value for `--export-chunk-size` if got an `gRPC message
body too large error`.
`--export-chunk-size` requries v1.2.315 and will be ignored when
connecting to a older meta-service.
- New Feature
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14467)
> feat: meta-service: customize chunk size when export

- src/query/sql/src/planner/binder/table.rs
- tests/sqllogictests/suites/mode/standalone/explain/join_reorder/mark.test
`DummyTableScan` has statistics and reduce code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14461)
> refactor: replace `OneTable` with `DummyTableScan`

- scripts/ci/deploy/config/databend-query-node-1.toml
- src/query/service/tests/it/storages/fuse/io.rs
- src/query/storages/fuse/src/io/read/block/block_reader_parquet_deserialize.rs
Use `is_nested` rather than `has_children` to determine if populating the in-memory cache is necessary
- Fixes #14502
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14503)
> fix: should use `is_nested` while populating in-memory cache

- src/query/sql/src/planner/binder/table.rs
- tests/sqllogictests/suites/ee/01_ee_system/01_0003_stream.test
```sql
mysql> create table t3(a int, b int) ;
mysql> insert into t3 values(1, 1), (2, 2), (3, 3);
Query OK, 3 rows affected (0.04 sec)
mysql>  create stream s3 on table t3 append_only = false;
mysql> insert into t3 values(4, 4), (5, 5) ;
Query OK, 2 rows affected (0.04 sec)
mysql> delete from t3 where a = 2;
Query OK, 1 row affected (0.08 sec)
mysql> update t3 set a = 0 where b = 1;
Query OK, 1 row affected (0.09 sec)
mysql> update t3 set a = 6 where b = 5 ;
Query OK, 1 row affected (0.09 sec)
mysql> optimize table t3 compact;
Query OK, 4 rows affected (0.08 sec)
mysql> select a, b, change$action, change$is_update from …
```
> fix: wrong result with special stream alias

- Cargo.lock
- scripts/ci/deploy/config/databend-query-node-1.toml
- scripts/ci/deploy/config/databend-query-node-2.toml
- scripts/ci/deploy/config/databend-query-node-3.toml
- scripts/ci/deploy/config/databend-query-node-hive.toml
- scripts/ci/deploy/config/databend-query-node-native.toml
- scripts/ci/deploy/config/databend-query-node-share-1.toml
- scripts/ci/deploy/config/databend-query-node-share-2.toml
- scripts/ci/deploy/config/databend-query-node-share-3.toml
- src/common/tracing/Cargo.toml
- src/common/tracing/src/config.rs
- src/common/tracing/src/init.rs
- src/common/tracing/src/lib.rs
- src/common/tracing/src/loggers.rs
- src/common/tracing/src/structlog.rs
- src/meta/service/src/configs/outer_v0.rs
- src/query/config/src/config.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/http_query_context.rs
- src/query/service/src/servers/mysql/mysql_interactive_worker.rs
- src/query/service/src/sessions/session.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
Group logs by request and arrange by the call stack. 
To enable, set in config:
```toml
[log.structlog]
on = true
dir = "./.databend/structlog"
```
Normal log will not be affected.
Before:
After:
1. What is the proper name for this feature? The term [structured log](https://www.loggly.com/use-cases/what-is-structured-logging-and-how-to-use-it/) has been used to refer well-formatted and machine-friendly log format.
2. Can we improve the output format for optimizing clarity and conciseness?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14495)
> feat: add structlog

- .github/actions/fuse_compat/action.yml
- src/meta/app/src/principal/user_privilege.rs
- src/meta/proto-conv/src/share_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/user_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/main.rs
- src/meta/proto-conv/tests/it/v078_grantentry.rs
- tests/fuse-compat/README.md
- tests/fuse-compat/test-fuse-compat.sh
- tests/fuse-compat/test-fuse-forward-compat.sh
- tests/fuse-compat/util.sh
1. add ci test foreward compat test(now only test rbac)
2. UserPrivilegeType and ShareGrantObjectPrivilege deserialize use from_bits_truncate
Befero we use from_bits, in this pr, use from_bits_truncate
from_bits will cause breaking change. When add new bit, old query can not deserialize the new bit. And then return err.
https://docs.rs/enumflags2/0.7.7/enumflags2/struct.BitFlags.html#method.from_bits
https://docs.rs/enumflags2/0.7.7/enumflags2/struct.BitFlags.html#method.from_bits_truncate
I think we should ignore the new bit. So now call from_bits_truncate to deserialize bitflags.
- - - …
> fix(query): privilege type forward compat

- Cargo.lock
- Cargo.toml
- src/common/grpc/Cargo.toml
- src/common/grpc/src/dns_resolver.rs
- src/common/storage/Cargo.toml
- src/common/storage/src/lib.rs
- src/common/storage/src/operator.rs
refactor: Using reqwest-hickory-resolver as global dns client
Allowing opendal to share the same dns client (and it's cache)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14476)
> refactor: Using reqwest-hickory-resolver as global dns client

- src/query/service/src/pipelines/processors/transforms/window/transform_window.rs
- tests/sqllogictests/suites/query/window_function/window_basic.test
fix ranking function out of bounds when calculate partition end
- Fixes #14534 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14535)
> fix: fix ranking function out of bounds when calculate partition end

- src/query/service/src/interpreters/interpreter_unsetting.rs
- src/query/settings/src/settings.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_global.rs
- tests/sqllogictests/suites/base/05_ddl/05_0026_ddl_unset_settings.test
When a deprecated setting is set global to meta service, then we were unable to unset it after upgrading `databend-query`, leaving a warning flood.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14536)
> fix(query): do not check exists for unsetting

- Cargo.lock
- Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14538)
> chore: fix openraft version: use v0.9.0-alpha.5 instead of v0.9.0-alpha.4

- src/query/service/src/interpreters/common/query_log.rs
- src/query/service/src/servers/http/v1/query/execute_state.rs
- src/query/service/tests/it/storages/system.rs
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/storages/system/src/clusters_table.rs
- src/query/storages/system/src/query_log_table.rs
- tests/suites/1_stateful/02_query/02_0006_system_table_query_speed.py
* add `log_type_name` to system.log_query table, make the query log type more readable
* add `cluster` to system.cluster, make the node belongs to which cluster more readable
* change http handler `execute_steate.rs` stop log level from **info** to **warn** @youngsofun 
Fixes #14542
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14545)
> feat: system table add query_log.log_type_name and cluster.cluster_id

- src/query/ast/src/ast/statements/stage.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement-error.txt
- src/query/ast/tests/it/testdata/statement.txt
- src/query/management/src/stage/stage_api.rs
- src/query/management/src/stage/stage_mgr.rs
- src/query/management/tests/it/stage.rs
- src/query/service/src/interpreters/interpreter_user_stage_create.rs
- src/query/sql/src/planner/binder/ddl/stage.rs
- src/query/sql/src/planner/plans/ddl/stage.rs
- src/query/users/src/user_stage.rs
- tests/sqllogictests/suites/base/05_ddl/05_0016_ddl_stage.test
feat: add create or replace stage support
- Fixes #14547
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14548)
> feat: add create or replace stage support

- src/query/service/src/pipelines/builders/merge_into_join_optimizations.rs
- src/query/service/src/schedulers/fragments/fragmenter.rs
- src/query/sql/src/executor/physical_plan.rs
- src/query/sql/src/executor/physical_plans/physical_exchange_source.rs
as the tile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14557)
> chore: remove `get_table_index` method

- src/query/service/tests/it/sql/planner/format/mod.rs
- src/query/sql/src/executor/physical_plans/physical_hash_join.rs
- src/query/sql/src/planner/binder/join.rs
- src/query/sql/src/planner/optimizer/decorrelate/decorrelate.rs
- src/query/sql/src/planner/optimizer/decorrelate/flatten_plan.rs
- src/query/sql/src/planner/optimizer/decorrelate/subquery_rewriter.rs
- src/query/sql/src/planner/optimizer/distributed/distributed_merge.rs
- src/query/sql/src/planner/optimizer/hyper_dp/join_node.rs
- src/query/sql/src/planner/optimizer/optimizer.rs
- src/query/sql/src/planner/plans/join.rs
make runtime filter for broadcast rework.
In the [ticket](https://github.com/datafuselabs/databend/pull/14163/files#diff-b78732f8fc0770907b61ae326666380a1941512b5043a6cfca6cb7515b6dae84), the broadcast runtime filter is disabled unexpectedly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14559)
> chore: make runtime filter for broadcast rework

- src/query/service/src/pipelines/processors/transforms/aggregator/transform_aggregate_partial.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_group_by_partial.rs
fix(query): fix double panic if enable_experimental_aggregate_hashtable
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14576)
> fix(query): fix double panic if enable_experimental_aggregate_hashtable

- src/query/service/src/databases/default/default_database.rs
`list_table_infos` might access table's s3 storage on `refresh_table_info`. On the case of the external tables, one bad external table will break ALL the `list_table_infos` on the db.
This PR add a small error message on `list_table_infos`, we can find out the bad table with this additional infomation.
This PR 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14606)
> chore: add error message on refresh table info

- src/meta/api/src/kv_pb_api.rs
- src/meta/api/src/lib.rs
- src/query/management/src/udf/udf_mgr.rs
This commit introduces `KVPbApi`, an extension of `KVApi`, designed to
handle `kvapi::Key` type keys and values implementing `FromToProto`
trait. Unlike `KVApi`, which operates with raw bytes, `KVPbApi`
simplifies client interactions by abstracting the protobuf encode/decode
process.
The primary addition in this commit is:
- The `KVPbApi::get_pb()` method, allowing retrieval of protobuf
formatted values directly from the meta-service.
- New error types specific to `KVPbApi` usage
- Refactored `UdfMgr::get_udf()` method, using `KVPbApi` to streamline
the codebase.
- New Feature
- - - …
> feat: Add KVPbApi: protobuf support for meta-service

- src/query/pipeline/sources/src/async_source.rs
Before:
```
mysql> with t1 as materialized (select number as a from numbers(10)) select t2.a from t1 as t2 where t2.a in (select * from t1 as t3 where t2.a = t3.a);
Read 30 rows, 240.00 B in 0.027 sec., 1.13 thousand rows/sec., 8.80 KiB/sec.
```
Now
```
mysql> with t1 as materialized (select number as a from numbers(10)) select t2.a from t1 as t2 where t2.a in (select * from t1 as t3 where t2.a = t3.a);
Read 10 rows, 80.00 B in 0.012 sec., 801.46 rows/sec., 6.26 KiB/sec.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14602)
> chore: make materialized cte scan_progress accurate

- src/meta/api/src/kv_pb_api.rs
- src/query/management/src/udf/udf_api.rs
- src/query/management/src/udf/udf_mgr.rs
- src/query/users/src/user_udf.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14613)
> refactor: get_udf() does not need to specify Seq

- Cargo.lock
- src/meta/api/src/kv_pb_api.rs
- src/meta/kvapi/src/kvapi/item.rs
- src/meta/kvapi/src/kvapi/key.rs
- src/meta/kvapi/src/kvapi/mod.rs
- src/meta/types/src/proto_ext/seq_v_ext.rs
- src/query/management/Cargo.toml
- src/query/management/src/udf/udf_mgr.rs
`KVPbApi::list_pb()` lists key value pairs by a prefix `DirName<K>`, and
decodes key back to `kvapi::Key` and values back to `kvapi::Key::ValueType`.
`UdfMgr::get_udfs()` is simplified by using `list_pb()`.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14623)
> refactor: Add `KVPbApi::list_pb()`, simplify `UdfMgr::get_udfs()`

- src/meta/api/src/kv_pb_api.rs
- src/meta/api/src/kv_pb_api/codec.rs
- src/meta/api/src/kv_pb_api/errors.rs
- src/meta/api/src/kv_pb_api/mod.rs
- src/meta/api/src/kv_pb_api/upsert_pb.rs
- src/meta/types/src/change.rs
- src/meta/types/src/cmd/mod.rs
- src/meta/types/src/errors/meta_api_errors.rs
- src/meta/types/src/errors/meta_errors.rs
- src/query/management/src/udf/udf_mgr.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14631)
> refactor: Simplify UdfMgr::add_udf()

- src/query/service/src/pipelines/builders/builder_merge_into.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0036_merge_into_without_distributed_enable.test
for current merge into implementation, we will write the blocks from join, and the bottom's join result block size depends on the query source block and `65535` threshold control, these will cause too much little block writes which is not good for s3 latency, so we can improve this to improve merge into write s3 performance. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14637)
> chore: reduce small block writes (improve merge into write performance)

- src/meta/api/src/kv_pb_api/codec.rs
- src/meta/api/src/kv_pb_api/errors/decode_error.rs
- src/meta/api/src/kv_pb_api/errors/encode_error.rs
- src/meta/api/src/kv_pb_api/errors/mod.rs
- src/meta/api/src/kv_pb_api/errors/read_error.rs
- src/meta/api/src/kv_pb_api/errors/write_error.rs
- src/meta/api/src/kv_pb_api/mod.rs
- src/query/management/src/udf/udf_mgr.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14634)
> chore: move KVPbApi impl to seperate files

- Cargo.lock
- src/query/management/Cargo.toml
- src/query/management/src/errors.rs
- src/query/management/src/lib.rs
- src/query/management/src/udf/udf_api.rs
- src/query/management/src/udf/udf_mgr.rs
- src/query/management/tests/it/udf.rs
- src/query/users/src/user_api.rs
- src/query/users/src/user_udf.rs
This way the caller can distinguish between a logic error and a backend
meta-service error.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14640)
> refactor: UdfApi::drop_udf() return the dropped record instead of returning ErrorCode

- src/query/management/src/lib.rs
- src/query/management/src/udf/errors.rs
- src/query/management/src/udf/mod.rs
- src/query/management/src/udf/udf_mgr.rs
- src/query/users/src/user_api.rs
`UdfApi` has only one implementation `UdfMgr` and the abstraction layer
is the underlying `KVApi`. There is no need to introduce another
abstraction.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14642)
> refactor: Remove UdfApi, use UdfMgr directly

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/query/sql/src/executor/physical_plan.rs
chore(meta): remove tenant for table info
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14647)
> chore(meta): remove tenant for table info

- src/query/service/src/interpreters/interpreter_privilege_grant.rs
- src/query/service/src/sessions/session_privilege_mgr.rs
- src/query/users/src/role_cache_mgr.rs
- src/query/users/src/role_mgr.rs
- tests/suites/0_stateless/18_rbac/18_0002_ownership_cover.result
- tests/suites/0_stateless/18_rbac/18_0002_ownership_cover.sh
1. if has ownership but owner role not exists, the owner role will be set to account_admin
2. has_ownership should get ownership and role from meta
- Fixes #14572
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14597)
> fix(query):  account_admin should support grant ownership to new role after drop an created role

- src/query/service/src/pipelines/processors/transforms/hash_join/desc.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/service/src/schedulers/fragments/fragmenter.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/sql/src/executor/physical_plan_visitor.rs
- src/query/sql/src/executor/physical_plans/physical_hash_join.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0026_merge_into.test
- tests/sqllogictests/suites/query/join/runtime_filter.test
- tests/sqllogictests/suites/tpcds/queries.test
- tests/sqllogictests/suites/tpcds/tpcds_join_order.test
- tests/sqllogictests/suites/tpch/join.test
- tests/sqllogictests/suites/tpch/queries.test
Use cardinality to predicate the join selectivity, if exceeds the selectivity threshold, open bloom runtime filter.
- Fixes #14641
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14686)
> refactor: enables the bloom runtime filter to be turned on adaptively

- docker/build-tool/gnu/Dockerfile
install sqlite3 for build-tool
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14695)
> chore: install sqlite3 for build-tool

- src/query/functions/README.md
- src/query/functions/src/scalars/arithmetic.rs
- src/query/functions/tests/it/scalars/testdata/arithmetic.txt
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- tests/sqllogictests/suites/query/02_function/02_0000_function_arithmetic.test
add div0 divnull method
- Fixes #14106
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14693)
> feat: add div0 divnull method

- src/meta/app/src/tenant/mod.rs
- src/meta/app/src/tenant/tenant.rs
`Tenant` will used as a root key when exporting data belonging to a
tenant from meta-service.
All the data to export directly or indirectly belongs to `Tenant`.
- New Feature
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14704)
> feat: add a new `kvapi::Key` type: `Tenant`

- scripts/ci/deploy/databend-query-standalone-hive.sh
- scripts/ci/deploy/databend-query-standalone-native.sh
- scripts/ci/deploy/databend-query-standalone.sh
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- Fixes #14683
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14702)
> fix(query): filter response session settings with ScopeLevel::Session

- src/query/expression/src/filter/select.rs
- src/query/expression/src/filter/select_op.rs
- src/query/expression/src/filter/select_value/mod.rs
- src/query/expression/src/filter/select_value/select_column.rs
- src/query/expression/src/filter/select_value/select_column_scalar.rs
- src/query/expression/src/filter/select_value/select_scalar.rs
- src/query/expression/src/types.rs
When advancing PR #14689, it was found that the performance of the filter could be improved: when the comparison function is used as a return value, its `#[inline(always)]` will be ignored, after fixing this issue, the execution of the filter can be accelerated by ~ 40%
**Q1 filter before**
**Q1 filter after**
**Q3 filter before**
**Q3 filter after**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14715)
> chore(query): improve new filter execution

- src/common/metrics/src/metrics/storage.rs
- src/query/storages/fuse/src/operations/mutation/mutator/block_compact_mutator.rs
- src/query/storages/fuse/src/operations/mutation/mutator/recluster_mutator.rs
- src/query/storages/fuse/src/operations/recluster.rs
- new metrics
- fuse_compact_block_build_lazy_part_milliseconds (histogram)
- fuse_recluster_build_task_milliseconds (histo)
- fuse_recluster_segment_nums_scheduled (counter)
- While selecting the blocks with the highest depth
segments no longer processed one by one,  multiple segments might be squashed into one unit for selection, if the number of blocks of these segments reaches the value of setting FUSE_OPT_KEY_BLOCK_PER_SEGMENT.
- tweak(fix) the logic of `ReclusterMutator::segment_can_recluster`
the segment will be a candidate for recluster, only if it does not consist of constant blocks(only), or the number of blocks does not reach the value of setting FUSE_OPT_KEY_BLOCK_PER_SEGMENT.
- …
> chore: add metrics for compact and recluster

- src/meta/api/src/id_generator.rs
- src/meta/app/src/background/background_job.rs
- src/meta/app/src/background/background_task.rs
- src/meta/app/src/data_mask/mod.rs
- src/meta/app/src/principal/user_defined_function.rs
- src/meta/app/src/schema/catalog.rs
- src/meta/app/src/schema/database.rs
- src/meta/app/src/schema/index.rs
- src/meta/app/src/schema/lock.rs
- src/meta/app/src/schema/table.rs
- src/meta/app/src/schema/virtual_column.rs
- src/meta/app/src/share/share.rs
- src/meta/app/src/tenant/tenant.rs
- src/meta/kvapi/src/kvapi/key.rs
Keys in meta-service have hierarchical structure.
For example a database is the parent of a table.
The `kvapi::Key` should expose a structure that enables the traversal
from a `Tenant` to all associated data when exporting metadata for that
tenant.
- New Feature
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14716)
> feat: add `parent()` method to kvapi::Key to describe the hierarchical structure of meta-service data

- .github/actions/build_linux/action.yml
- .github/actions/build_linux_sanitizer/action.yml
- Cargo.lock
- docker/build-tool/base/Dockerfile
- scripts/setup/dev_setup.sh
- src/common/compress/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14711)
> chore: static features for async-compression deps

- src/query/functions/src/aggregates/aggregate_approx_count_distinct.rs
- src/query/functions/src/aggregates/aggregate_array_moving.rs
- src/query/functions/src/aggregates/aggregate_avg.rs
- src/query/functions/src/aggregates/aggregate_kurtosis.rs
- src/query/functions/src/aggregates/aggregate_min_max_any.rs
- src/query/functions/src/aggregates/aggregate_quantile_cont.rs
- src/query/functions/src/aggregates/aggregate_quantile_disc.rs
- src/query/functions/src/aggregates/aggregate_skewness.rs
- src/query/functions/src/aggregates/aggregate_stddev.rs
- src/query/functions/src/aggregates/aggregate_sum.rs
- src/query/functions/src/aggregates/aggregate_unary.rs
improve aggregate unary function via  reduce serde functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14729)
> chore(query): improve aggregate unary function

- src/query/expression/src/types.rs
- src/query/expression/src/types/any.rs
- src/query/expression/src/types/array.rs
- src/query/expression/src/types/binary.rs
- src/query/expression/src/types/bitmap.rs
- src/query/expression/src/types/boolean.rs
- src/query/expression/src/types/date.rs
- src/query/expression/src/types/decimal.rs
- src/query/expression/src/types/empty_array.rs
- src/query/expression/src/types/empty_map.rs
- src/query/expression/src/types/generic.rs
- src/query/expression/src/types/geometry.rs
- src/query/expression/src/types/map.rs
- src/query/expression/src/types/null.rs
- src/query/expression/src/types/nullable.rs
- src/query/expression/src/types/number.rs
- src/query/expression/src/types/string.rs
- src/query/expression/src/types/timestamp.rs
- src/query/expression/src/types/variant.rs
- src/query/functions/src/aggregates/aggregate_quantile_cont.rs
- src/query/functions/src/aggregates/aggregate_unary.rs
- tests/sqllogictests/suites/query/02_function/02_0000_function_aggregate_mix.test
support decimal for quantile_cont
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14726)
> refactor: support decimal for quantile_cont

- src/meta/app/src/background/background_job.rs
- src/meta/app/src/background/background_task.rs
- src/meta/app/src/data_mask/mod.rs
- src/meta/app/src/primitive.rs
- src/meta/app/src/principal/user_defined_function.rs
- src/meta/app/src/schema/catalog.rs
- src/meta/app/src/schema/database.rs
- src/meta/app/src/schema/index.rs
- src/meta/app/src/schema/lock.rs
- src/meta/app/src/schema/table.rs
- src/meta/app/src/schema/virtual_column.rs
- src/meta/app/src/share/share.rs
- src/meta/kvapi/src/kvapi/value.rs
- New Feature
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14735)
> feat: add kvapi::ValueType::dependency_keys() to retrieve relation such as table-name-to-table-id and table-id-to-table-meta

- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_state.rs
as the title
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14733)
> fix: check if global memory is negative

- src/query/ast/src/parser/statement.rs
- tests/sqllogictests/suites/base/issues/issue_14713.test
- Fixes #14713
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14736)
> feat: DESC[RIBE] [TABLE] <name>

- src/meta/app/src/principal/mod.rs
- src/meta/app/src/principal/user_grant.rs
- src/meta/kvapi/src/kvapi/key_parser.rs
- src/meta/types/src/non_empty.rs
- src/query/management/src/role/role_mgr.rs
- src/query/management/tests/it/role.rs
- src/query/users/src/user_api.rs
Encapsulate the logic of encoding/decoding role-grantee key into
`RoleGrantee`. `RoleGrantee` is a standard `kvapi::Key` implementation
so that the export program could rely on the `kvapi::Key` API to
traverse meta-data to fetch all data that belongs to a tenant.
Legacy issue:
- For `OwnershipObject::Database{ catalog_name, db_id }`, `catalog_name`
is not encoded into the key, we have to be compatible with this. The
solution is to encode a `"default"` catalog with
`database-by-id/<db-id>` prefix, and encode a non-default catalog with
`database-by-catalog-id/<catalog>/<db-id>` prefix.
The same for the `OwnershipObject::Table{ catalog_name, ... }`.
- For `OwnershipObject::Table{ catalog_name, …
> refactor: Add RoleGrantee to provide meta-service key for RoleMgr

- src/query/storages/fuse/src/fuse_table.rs
- src/query/storages/fuse/src/io/locations.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14762)
> chore(query): fix location ver

- src/query/sql/src/planner/binder/copy_into_table.rs
- tests/suites/1_stateful/07_stage_attachment/07_0003_insert_with_stage_file_format.result
- tests/suites/1_stateful/07_stage_attachment/07_0003_insert_with_stage_file_format.sh
CSV attachment is mainly used in Drivers for insert.
In the future, client should use EmptyFieldAs=STRING or FieldDefault to distinguish NULL and empty string.
However, old servers ds not support `missing_field_as`, so client can not add the option directly at now.
So we will get empty_field_as = NULL, which will raise error if there is empty string for non-nullable string field.
remove this after 
1. the old server is no longer supported 
2. Driver add the option "EmptyFieldAs=FieldDefault"
related pr https://github.com/datafuselabs/databend/pull/14335
- - - …
> fix: force attachment to use EmptyFieldAs::FieldDefault.

- src/query/service/src/interpreters/interpreter_user_stage_create.rs
fix: fix create or replace stage bug, only remove dir when success
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14766)
> fix: fix create or replace stage bug, only remove dir when success

- .github/actions/build_linux/action.yml
- .github/actions/build_linux_sanitizer/action.yml
- .github/actions/setup_docker/action.yml
- .github/workflows/reuse.linux.yml
- Cargo.toml
- docker/build-tool/alpine/Dockerfile
- docker/build-tool/dev/Dockerfile
- scripts/setup/run_build_tool.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14761)
> chore(ci): change build runner with target

- Cargo.lock
- Cargo.toml
- src/meta/service/src/network.rs
- src/meta/service/src/store/store.rs
Add feature flag `generic-snapshot-data`: when enabled, `SnapshotData`
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14769)
> refactor: upgrade Openraft v0.9.0-alpha.5..v0.9.0-alpha.6

- src/query/service/src/interpreters/interpreter_table_show_create.rs
- tests/sqllogictests/suites/base/06_show/06_0001_show_create_table.test
show create table with location
- Related: #14714 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14778)
> chore: show create table with location

- .github/actions/build_bindings_python/action.yml
- .github/actions/build_linux/action.yml
- .github/actions/build_linux_sanitizer/action.yml
- .github/workflows/bindings.python.yml
- .github/workflows/build_tool.yml
- .github/workflows/cloud.yml
- .github/workflows/reuse.linux.yml
- Cargo.lock
- Cargo.toml
- docker/build-tool/musl/Dockerfile
- docker/build-tool/musl/linker.sh
- scripts/setup/run_build_tool.sh
- src/binaries/Cargo.toml
- src/common/arrow/Cargo.toml
- src/query/constraint/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14786)
> chore: patch z3-sys & add musl build to ci

- tests/sqllogictests/suites/query/join/large_query.test
This test sometimes causes ci to fail, we temporarily reduce the number of tables of this test, we will recover this test after optimizing RecursiveOptimizer and Dphyp.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14797)
> chore(test): reduce the number of tables in large join test

- src/meta/app/src/background/background_job.rs
- src/meta/app/src/principal/mod.rs
- src/meta/app/src/principal/principal_identity.rs
- src/meta/app/src/principal/user_identity.rs
- src/meta/kvapi/src/kvapi/helper.rs
- src/meta/kvapi/src/kvapi/key_builder.rs
- src/meta/kvapi/src/kvapi/key_parser.rs
- src/query/management/src/user/user_mgr.rs
- src/query/management/tests/it/user.rs
The encoding is refined to prevent two records are encoeded into the
same key. Before this commit: `user="u", host="h'@'h"` and
`user="u'@'h", host="h"` will both be encoded into `"u'@'h'@'h"`.
To address this issue, the special chars `@` and `'` in `user` and
`host` are escaped before encoding the key.
Other changes:
- Add `kvapi::KeyBuilder::escape_specified()` and
`kvapi::KeyParser::unescape_specified()` to escape and unescape
specified chars.
---
- Fix: #14792
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14793)
> refactor: add TenantUserIdent as meta-service key to access user data

- src/meta/service/src/api/grpc/grpc_service.rs
- src/meta/service/tests/it/grpc/metasrv_grpc_get_client_info.rs
- src/meta/types/proto/meta.proto
- New Feature
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14805)
> feat: get_client_info() returns the server time in milliseconds

- Cargo.lock
- src/common/exception/src/exception_code.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/execute_state.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/http_query_manager.rs
- src/query/service/src/sessions/session.rs
- src/query/service/src/sessions/session_ctx.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/storages/common/txn/Cargo.toml
- src/query/storages/common/txn/src/manager.rs
- tests/sqllogictests/src/util.rs
- tests/sqllogictests/suites/base/14_transaction/14_0001_dedup_label.test
- tests/sqllogictests/suites/base/14_transaction/14_0003_merge_into.test
- tests/sqllogictests/suites/ee/01_ee_system/01_0005_txn_stream.test
- tests/sqllogictests/suites/stage/copy_into_txn.sql
https://github.com/datafuselabs/databend/issues/14789
1. `txn state` is send to client along with results for each request, client is supposed to carry it in next request.
2. at the end of a HTTP query,  if the txn state is active, the transaction mgr is saved to global map with query id as key, on next query of the session (and txn),, seeing the txn state is active, the transaction mgr is fetched and set to the new session.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14802)
> feat: http handler txn support.

- Cargo.lock
- Cargo.toml
- src/meta/client/src/lib.rs
No change, just method renamed.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14809)
> refactor: upgrade Openraft to v0.9.0-alpha.7

- .github/actions/setup_bendsql/action.yml
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- tests/suites/0_stateless/01_transaction/01_02_txn_basic.result
- tests/suites/0_stateless/01_transaction/01_02_txn_basic.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14826)
> ci: add tests for transaction.

- .github/actions/artifact_download/action.yml
- .github/workflows/bindings.python.yml
- .github/workflows/release.yml
- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14833)
> chore(ci): fix upload/download sha256sums artifacts

- Cargo.lock
- Cargo.toml
Openraft change log from v0.9.0-alpha.7 to v0.9.0-alpha.8:
The `RaftLogReaderExt::blocking_append()` method enables the caller to
append logs to storage in a blocking manner, eliminating the need to
create and await a callback. This method simplifies the process of
writing tests.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14832)
> refactor: upgrade openraft v0.9.0-alpha.7 to v0.9.0-alpha.8

- Cargo.lock
- src/query/expression/Cargo.toml
- src/query/expression/src/aggregate/aggregate_hashtable.rs
- src/query/expression/src/aggregate/payload.rs
- src/query/service/src/pipelines/builders/builder_aggregate.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/aggregate_exchange_injector.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/aggregate_meta.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/serde_meta.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_aggregate_serializer.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_deserializer.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_exchange_aggregate_serializer.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_exchange_group_by_serializer.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_group_by_serializer.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_spill_reader.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_aggregate_final.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_aggregate_partial.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_group_by_final.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_group_by_partial.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_partition_bucket.rs
- src/query/settings/src/settings_default.rs
- src/query/sql/src/executor/physical_plan_visitor.rs
- src/query/sql/src/executor/physical_plans/physical_aggregate_final.rs
- src/query/sql/src/executor/physical_plans/physical_aggregate_partial.rs
1. In the previous PR #14524, we implemented a new_agg_hashtable on singleton. In the partial phase, we sent the entire `PartitionedPayload`. While this approach is correct for singletons, it may cause scatter skew if used in the same manner on a cluster. To ensure compatibility with the cluster, we refactored the payload transmission method for new_agg_hashtable in the standalone version. Now, we send each individual `Payload` separately.
2. support new_agg_hashtable on cluster, to be enabled using: `set enable_experimental_aggregate_hashtable = 1;`
- - - …
> chore(query): modify new_agg_hashtable payload transmission method on singleton and support new_agg_hashtable on cluster

- src/query/expression/src/utils/date_helper.rs
- src/query/functions/src/scalars/datetime.rs
- tests/sqllogictests/suites/query/02_function/02_0012_function_datetimes.test
today_date get now with UTC::now, should need consider tz
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14841)
> fix(query): today, yesterday, tomorrow need consider tz

- src/query/sql/src/planner/optimizer/property/selectivity.rs
- tests/sqllogictests/suites/tpch/queries.test
- Fixes #14731 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14846)
> feat: impl like selectivity compution by probability predication

- src/query/ast/src/ast/statements/table.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
- src/query/service/src/interpreters/interpreter_table_vacuum.rs
- src/query/sql/src/planner/plans/ddl/table.rs
- tests/suites/5_ee/01_vacuum/01_0002_ee_vacuum_drop_table.sh
feat: add vacuum table dry run result table
- Fixes #14810
add `vacuum table dry run summary` grammar:
* when dry run without summary option, output column will be `file` and `file_size`;
* when dry run with summary option, output column will be `total_files` and `total_size`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14851)
> feat: add vacuum table dry run result table

- src/query/sql/src/planner/semantic/type_check.rs
`ConstantTableScan` can't be sent to nodes in the cluster, because it's in memory, so disable inlist to subquery optimization for the cluster.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14864)
> chore: disable inlist to subquery under cluster

- src/meta/app/src/principal/mod.rs
- src/meta/app/src/principal/user_stage_file_ident.rs
- src/meta/app/src/principal/user_stage_ident.rs
- src/meta/kvapi/src/kvapi/key.rs
- src/query/management/src/stage/stage_mgr.rs
Use kvapi::Key to define meta-service keys for StageMgr
- Fix: #14849
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14863)
> refactor: add StageIdent and StageFileIdent

- src/query/sql/src/planner/binder/select.rs
- src/query/sql/src/planner/metadata.rs
- tests/sqllogictests/suites/mode/standalone/explain/window.test
fix incorrect schema in window expr in subquery with lazy_materializa…
- Fixes #14894 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14895)
> fix: fix incorrect schema in window expr in subquery with lazy_materialization

- Cargo.lock
- src/query/ast/Cargo.toml
- src/query/ast/src/ast/expr.rs
- src/query/sql/src/planner/semantic/type_check.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14893)
> refactor(ast): remove databend-common-functions dependency

- src/query/ast/src/ast/statements/merge_into.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
When `Display`ing a "merge into" statement that specifies "insert *" as the unmatched branch, the output should show "insert *" rather than "insert values()".
may fix 
- https://github.com/datafuselabs/databend/issues/14890
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14892)
> fix: Display of `merge into ..  insert *` 

- src/query/management/src/role/role_mgr.rs
- src/query/management/src/serde/mod.rs
- src/query/management/src/serde/pb_serde.rs
- src/query/management/src/serde/quota.rs
When writing back upgraded json-to-pb data to meta-service,
it should return `MetaError`, instead of business error such as
`ErrorCode::UnknownRole`.
Add quota limit to `check_and_upgrade_to_pb`: for each API calls, it
upgrades upto 100 records. So that an API call won't be delay a lot.
After upgrading, it should returns the `seq` number after upgrading.
- Bug Fix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14899)
> fix: `check_and_upgrade_to_pb()` should return MetaError, add quota

- src/query/service/src/api/http/v1/mod.rs
- src/query/service/src/api/http/v1/settings.rs
- src/query/service/src/api/http_service.rs
- src/query/service/src/sessions/session_mgr.rs
- src/query/service/src/table_functions/others/license_info.rs
- src/query/settings/src/settings_global.rs
- tests/suites/6_background/00_target_tables/00_0000_target_tables.result
- tests/suites/6_background/00_target_tables/00_0000_target_tables.sh
feat(query): support settings admin api for global level settings
```shell
curl -XGET 'http://127.0.0.1:8080/v1/tenants/test_tenant/settings'    
curl -XPOST 'http://127.0.0.1:8080/v1/tenants/test_tenant/settings/max_threads' -H "Content-Type: application/json" --data "\"2\""
curl -XDELETE 'http://127.0.0.1:8080/v1/tenants/test_tenant/settings/max_threads'
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14901)
> feat(query): support settings admin api for global level settings

- src/query/config/src/config.rs
- src/query/config/src/inner.rs
- src/query/service/src/global_services.rs
- src/query/service/tests/it/storages/fuse/io.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
- src/query/storages/common/cache_manager/src/cache_manager.rs
https://github.com/datafuselabs/databend/issues/14866
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14896)
> feat: add a new ratio config instead of table_data_deserialized_data_bytes

- Cargo.lock
- Cargo.toml
- src/meta/service/src/meta_service/raft_service_impl.rs
Openraft 0.9.0 release:
https://github.com/datafuselabs/openraft/releases/tag/v0.9.0
Implement chunk-based snapshot transmission outside openraft core.
This makes it possible to switch to another snapshot transmission
protocol in a compatible manner.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14907)
> refactor: upgrade to openraft 0.9.0

- src/meta/app/src/tenant/mod.rs
- src/meta/app/src/tenant/tenant_quota_ident.rs
- src/meta/kvapi/src/kvapi/test_suite.rs
- src/query/management/src/quota/quota_mgr.rs
- src/query/service/src/interpreters/interpreter_database_create.rs
- src/query/service/src/interpreters/interpreter_table_create.rs
- src/query/service/src/interpreters/interpreter_user_create.rs
- src/query/service/src/interpreters/interpreter_user_stage_create.rs
- src/query/service/src/table_functions/others/tenant_quota.rs
- src/query/users/src/user_api.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14915)
> refactor: use kvapi::Key to define meta-service key for QuotaMgr

- src/meta/kvapi/src/kvapi/test_suite.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14927)
> chore: extend time tolerance for meta-service test

- src/query/service/src/interpreters/access/privilege_access.rs
- src/query/service/src/interpreters/interpreter_factory.rs
- src/query/service/src/interpreters/interpreter_privilege_grant.rs
- src/query/service/src/interpreters/interpreter_privilege_revoke.rs
- src/query/service/src/table_functions/infer_schema/parquet.rs
- src/query/service/src/table_functions/inspect_parquet/inspect_parquet_table.rs
- src/query/service/src/table_functions/list_stage/list_stage_table.rs
- tests/suites/0_stateless/18_rbac/18_0001_udf_priv.result
- tests/suites/0_stateless/18_rbac/18_0002_ownership_cover.result
- tests/suites/0_stateless/18_rbac/18_0003_db_visibility.result
- tests/suites/0_stateless/18_rbac/20_0012_privilege_access.result
- tests/suites/0_stateless/18_rbac/20_0015_set_role.result
- tests/suites/1_stateful/00_stage/00_0012_stage_priv.result
This PR minimizes additional meta calls in permission access as much as possible.
Now:
Considering that the user is a self created user which grant with the self created role
```sql
create role role1;
grant all on *.* to role1;
create user a identified by'123 'with DEFAULT_ROLE='role1';
grant role role1 to a;
```
In the case of successful HTTP auth, private related meta API calls: **2** times:
```rust
get_user_with_client_ip
update_user_login_result
```
`get_catalog` accessed n times
Database/Table Name `convert_to_id`, each table involves 2n meta calls.
`has_ownership` need get_ownership which accessed n times. And requires reload cache due to cache failure Call get_roles and a meta access …
> refactor: reduce meta call

- src/meta/app/src/principal/mod.rs
- src/meta/app/src/principal/network_policy_ident.rs
- src/query/management/src/network_policy/network_policy_mgr.rs
- src/query/service/src/interpreters/interpreter_network_policies_show.rs
- src/query/service/src/interpreters/interpreter_network_policy_alter.rs
- src/query/service/src/interpreters/interpreter_network_policy_create.rs
- src/query/service/src/interpreters/interpreter_network_policy_desc.rs
- src/query/users/src/network_policy.rs
- src/query/users/src/user_api.rs
- src/query/users/src/user_mgr.rs
- src/query/users/tests/it/network_policy.rs
- Fix: #14932
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14933)
> refactor: add NetworkPolicyIdent as NetworkPolicy meta-service key

- src/query/management/src/network_policy/network_policy_api.rs
- src/query/management/src/network_policy/network_policy_mgr.rs
- src/query/management/src/password_policy/password_policy_api.rs
- src/query/management/src/password_policy/password_policy_mgr.rs
- src/query/users/src/network_policy.rs
- src/query/users/src/password_policy.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14937)
> chore: use shorter name for management API

- Cargo.lock
- src/meta/app/src/principal/file_format.rs
- src/meta/proto-conv/src/file_format_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/main.rs
- src/meta/proto-conv/tests/it/v032_file_format_params.rs
- src/meta/proto-conv/tests/it/v083_ndjson_format_params.rs
- src/meta/protos/proto/file_format.proto
- src/query/ast/Cargo.toml
- src/query/ast/src/parser/stage.rs
- src/query/ast/src/parser/token.rs
- src/query/pipeline/sources/src/input_formats/impls/input_format_ndjson.rs
- tests/data/ndjson/null_if.ndjson
- tests/sqllogictests/suites/stage/formats/ndjson/ndjson_null_if.test
e.g.
```
copy into v from @data/ndjson/null_if.ndjson file_format = (type = 'ndjson' null_if = ('', 'Null')) force=true
```
all nullable field will check for `null_if` first ( e.g. `{"a_int_field":  ""}` will load `a_int_field` as null instead of report error
note this is diff from snowflake which apply t `null_if` to varchar field only.
cc @wubx 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14938)
> feat: ndjson support option null_if.

- src/query/catalog/src/catalog/interface.rs
- src/query/catalog/src/catalog/session_catalog.rs
- src/query/catalog/src/table.rs
- src/query/service/src/interpreters/common/stream.rs
- src/query/service/src/sessions/query_ctx_shared.rs
- src/query/storages/common/txn/src/manager.rs
- src/query/storages/stream/src/stream_table.rs
- src/query/storages/system/src/streams_table.rs
- tests/suites/5_ee/05_stream/05_0001_ee_stream_consume.result
- tests/suites/5_ee/05_stream/05_0001_ee_stream_consume.sh
When fetching the stream, retrieve and cache the source table metadata to ensure that the source table metadata remains consistent within the same query or transaction.
- Fixes #14936
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14935)
> fix: stream source can't get the same  tablemeta

- src/common/exception/src/exception_code.rs
- src/query/config/src/config.rs
- src/query/config/src/inner.rs
- src/query/service/src/sessions/queue_mgr.rs
- src/query/service/tests/it/sessions/queue_mgr.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
feat(query): add statement_queued_timeout_in_seconds setting for queries queue
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14945)
> feat(query): add statement_queued_timeout_in_seconds setting for queries queue

- src/query/service/src/pipelines/builders/builder_replace_into.rs
- src/query/storages/fuse/src/operations/append.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0011_change_tracking.test
When append and replace generating cluster stats, specify the data schema.
When generating cluster stats during append and replace operations, specify the data schema. 
This is because append and replace operations will ignore the change tracking field [when serialize block](https://github.com/datafuselabs/databend/blob/main/src/query/storages/fuse/src/operations/common/processors/transform_serialize_block.rs#L91-L95).
- Fixes #14955
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14956)
> fix: cluster table with change tracking enabled append panic

- src/query/sql/src/planner/optimizer/optimizer.rs
Since some join types cannot perform broadcast join, so `CommuteJoin` cannot be executed after `CascadesOptimizer`.
This bug was discovered by an existing test while advancing https://github.com/datafuselabs/databend/pull/14872.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14951)
> chore(planner): fix distributed query plan

- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/sql/src/executor/physical_plans/physical_hash_join.rs
- tests/sqllogictests/suites/tpch/queries.test
Due to the join spilling opened by default which makes `runtime filter` closed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14959)
> fix: enable runtime filter when `join_spilling_memory_ratio` !=0

- src/query/management/src/udf/udf_mgr.rs
- src/query/storages/system/src/user_functions_table.rs
- src/query/users/src/user_udf.rs
- src/query/users/tests/it/user_udf.rs
https://github.com/datafuselabs/databend/pull/12729/files#diff-9c992028e59caebc313d761b8488b17f142618fb89db64c51c1655689d68c41b
I think we can not upgrade the old json to pb. The best way is return error udf when `select * from system.user_functions` and then user need to re-create the udf.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14964)
> fix(query): Need return error udf_name when derialize from pb  failed.

- src/query/expression/src/evaluator.rs
- src/query/expression/src/filter/selector.rs
- src/query/expression/src/function.rs
- src/query/functions/src/scalars/control.rs
- src/query/functions/src/scalars/decimal/cast.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/sql/src/evaluator/cse.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/mode/standalone/explain/push_down_filter.test
- tests/sqllogictests/suites/mode/standalone/explain_native/push_down_filter.test
- tests/sqllogictests/suites/query/02_function/02_0072_error.test
- add `is_error`, `is_not_error` function 
```
🐳 :) select   is_error(from_base64('aj')),   is_not_error(from_base64('ac')), is_error(3);
┌─────────────────────────────────────────────────────────────────────────────┐
│ is_error(from_base64('aj')) │ is_not_error(from_base64('ac')) │ is_error(3) │
│           Boolean           │             Boolean             │   Boolean   │
├─────────────────────────────┼─────────────────────────────────┼─────────────┤
│ true                        │ false                           │ false       │
└─────────────────────────────────────────────────────────────────────────────┘
```
- add `error_or` function which returns the first none-error arg as value or …
> feat(query): add error_or function

- src/query/storages/stage/src/read/row_based/formats/csv/separator.rs
- src/query/storages/stage/src/read/row_based/processors/reader.rs
- src/query/storages/stage/src/read/row_based/processors/separator.rs
- tests/sqllogictests/suites/stage/formats/csv/csv_select.test
fortunately, this bug only happen when header is longer than the `input_read_buffer_size` (1M by default),  which rarely happen.
also fix progress by the way  https://github.com/datafuselabs/databend/issues/14973#issuecomment-2001999581
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14981)
> fix: csv read error with skip_header.

- Cargo.lock
- src/query/settings/Cargo.toml
- src/query/settings/src/settings_default.rs
- src/query/storages/system/src/settings_table.rs
- tests/suites/0_stateless/05_hints/05_0001_set_var.result
* Add range for all Number settings
* Improve some setting description
* Add timezone(String) range
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14985)
> chore: number range for settings

- src/query/ast/src/parser/input.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/sql/Cargo.toml
- src/query/sql/src/planner/planner.rs
- tests/sqllogictests/suites/query/02_function/02_0072_prql.test
support prql in databend
https://github.com/datafuselabs/databend/issues/14811
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14922)
> feat: support prql

- src/query/service/src/pipelines/processors/mod.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/service/tests/it/pipelines/builders/mod.rs
- src/query/service/tests/it/pipelines/builders/runtime_filter.rs
Add it to ensure runtime filter is enabled.
Explain will end before pipeline construction, so it's difficult to add the test to sqllogic test
> chore: add integration test for runtime filter

- Cargo.lock
- src/meta/api/src/crud/errors.rs
- src/meta/api/src/crud/mod.rs
- src/meta/app/src/lib.rs
- src/meta/app/src/principal/network_policy_ident.rs
- src/meta/app/src/principal/password_policy_ident.rs
- src/meta/app/src/principal/user_setting_ident.rs
- src/meta/app/src/principal/user_stage_ident.rs
- src/meta/app/src/tenant_key.rs
- src/meta/app/src/tenant_key_errors.rs
- src/query/users/Cargo.toml
- src/query/users/src/network_policy.rs
- src/query/users/src/password_policy.rs
> refactor: Add ExistError and UnknownError, TenantResource does not need to define error type any more

- Cargo.lock
- Cargo.toml
> chore: upgrade openraft to 0.9.1

- src/query/config/src/config.rs
- src/query/config/src/inner.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
* Change the config `max_running_queries` from `8` to `0`, disabled by default.
* Some codes are formatted by `make fmt`
> chore: max_running_queries from 8 to 0, disable the max running queries

- src/query/service/src/pipelines/builders/builder_on_finished.rs
- src/query/sql/src/planner/binder/binder.rs
- src/query/sql/src/planner/planner.rs
- src/query/sql/src/planner/plans/copy_into_table.rs
- src/query/storages/fuse/src/io/files.rs
- src/query/storages/fuse/src/operations/gc.rs
- tweak the batch size used in `remove_file_in_batch`
Instead of setting a fixed batch size of 1000 for file deletion, adjust the batch size based on the `max_threads` setting to allow for more parallel deletion of files, i.e. take "(number of files) / max_threads" as the size of batch. 
In latency-sensitive scenarios, adjusting the  batch size of object storage file deletion, may improve performance significantly:
before this PR (with customized log)
_ec2 query node + s3 in the same region_
~~~
src/query/storages/fuse/src/io/files.rs:85 deleted files, # of files 80, time used 774.073632ms
src/query/storages/fuse/src/io/files.rs:85 deleted files, # of files 60, time used 648.507035ms …
> chore: tweak deletion batch size & log messages

- src/query/pipeline/sources/src/lib.rs
- src/query/pipeline/sources/src/prefetch_async_source.rs
- src/query/storages/stage/src/read/row_based/processors/reader.rs
- src/query/storages/stage/src/read/row_based/read_pipeline.rs
- Fixes https://github.com/datafuselabs/databend/issues/14973
so for a large file read of next batch and processing of the prev can overlap.
make the whole time shorter especially for relative slow storage.
add PrefetchAsyncSourcer,  keep return `Async` (instead of `NEED_CONSUME`) until prefetch goal is reached or finished.
rely on some implementation details (correct me if  I am wrong @zhang2014 ): trigger of downstream processor dependent on `push_data`, not `NEED_CONSUME` event,  `NEED_CONSUME`  is  only used to change processor state to `IDLE`
the reason for https://github.com/datafuselabs/databend/issues/14973 is simple: the num of processors is not correctly set.
fixed.
but the …
> refactor(query): csv reader support prefetch

- tests/sqllogictests/suites/mode/standalone/explain/09_0039_target_build_merge_into_standalone.test
- tests/sqllogictests/suites/mode/standalone/explain/merge_into.test
we rollback target_build_optimization for merge into test. But we still reserve some join_spill_enabled tests.
> chore: rollback partial tests

- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/sql/src/planner/semantic/type_check.rs
for now, the inlist needs to over 1024, so we can change it into join, we add a setting in this pr for user to adjust it.
> chore: add a setting for inlist to join

- src/meta/app/src/principal/mod.rs
- src/meta/app/src/principal/user_setting_ident.rs
- src/meta/app/src/principal/user_stage_ident.rs
> chore: unify TIdent key format

- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/execute_state.rs
up to 10 secs to wait for the schema to be ready.
related to https://github.com/datafuselabs/bendsql/pull/363
> chore: the fist http resp wait longer to tolerant old bendsql clients.

- src/query/service/src/interpreters/interpreter_view_alter.rs
alter view only need to modify table option
> refactor: alter view only need to modify table option

- src/query/service/src/interpreters/interpreter_presign.rs
this pr add a small log about how many time got elapsed during the presign operation.
presign is expected to be an io-free operation, but sometimes it has a latency of 100+ms.
> chore: add log about presign elapsed

- src/query/service/src/interpreters/access/privilege_access.rs
- tests/suites/0_stateless/18_rbac/18_0004_view_privilege.result
- tests/suites/0_stateless/18_rbac/18_0004_view_privilege.sh
Note:
Select view no need to check the inner table privilege.
Because the user only can query view when the admin user grant select on the view to the user.
So the admin user needs to know why the user need access this view.
This pr is avoid that:
User only has create or alter on db. And then the user can query table as create or alter view. Like this:
```sql
--root
grant create on default.* to a;
--user a
create view v_t1 as select * from t1; -- If it can be success, the user can query table t1 according to query view v_t1. It maybe dangerous.
```
> feat(query): check view's inner table privilege when create or alter view

- src/query/settings/src/settings_default.rs
Default enable merge into.
The `set enable_experimental_merge_into = 1` in the test will remove after 2 release.
- Fixes #15033
> chore: default enalbe merge into

- src/meta/app/src/schema/table.rs
- src/meta/app/src/share/share.rs
- src/query/sql/src/executor/physical_plan.rs
- src/query/sql/src/executor/physical_plans/physical_aggregate_expand.rs
- src/query/sql/src/executor/physical_plans/physical_aggregate_final.rs
- src/query/sql/src/executor/physical_plans/physical_aggregate_partial.rs
- src/query/sql/src/executor/physical_plans/physical_commit_sink.rs
> refactor: remove innecessary serde

- src/query/service/src/servers/http/v1/http_query_handlers.rs
this pr made a small modificaton on logs, make it more clear about what is actually happening.
> chore(http): tune log on getting /v1/query/:id/kill

- src/query/settings/src/settings_default.rs
- tests/sqllogictests/suites/mode/standalone/explain/sort.test
- tests/sqllogictests/suites/mode/standalone/explain/window.test
This PR default enable spill in the settings:
1. `join_spilling_memory_ratio=60`
2. `aggregate_spilling_memory_ratio=60`
3. `sort_spilling_memory_ratio=60`
4. Add test for the spill enabled https://github.com/datafuselabs/databend/pull/15038/commits/e9b5f2e42553924646cdab029e1a493aa1fcfdd1
> chore: default enable aggregate/sort/join spill

- src/query/settings/src/settings_default.rs
table_lock_expire_secs: 15s
acquire_lock_timeout: 20s
- Fixes #15050
> chore: adjust the default value for table lock timeout

- src/common/storage/src/stage.rs
- tests/suites/1_stateful/00_stage/00_0002_copy_purge.result
- tests/suites/1_stateful/00_stage/00_0002_copy_purge_issue_15039.result
- tests/suites/1_stateful/00_stage/00_0002_copy_purge_issue_15039.sh
This PR introduces a modification to the handling of file paths in COPY INTO table statements. Specifically, when using statements like (files are explicitly specified by copy-option `files`):
~~~
copy into t from  @ts file_format = (type = CSV) files =('///a.csv') purge = true force = false;
~~~
The leading slashes in the file path (e.g., `///a.csv`) will now be trimmed before the file names are stored in the meta server (in this case `a.csv`). This change aligns with the behavior observed when using COPY INTO table statements that copy data from a location without specifying individual file names, such as:
~~~
copy into t from  @ts file_format = (type = CSV)  purge = true force = false;
~~~ …
> fix: trim leading '/'s for files specified in copy opt

- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/background/background_job.rs
- src/meta/app/src/background/background_task.rs
- src/meta/app/src/principal/connection_ident.rs
- src/meta/app/src/principal/network_policy_ident.rs
- src/meta/app/src/principal/password_policy_ident.rs
- src/meta/app/src/principal/role_ident.rs
- src/meta/app/src/principal/user_defined_file_format_ident.rs
- src/meta/app/src/principal/user_grant.rs
- src/meta/app/src/principal/user_identity.rs
- src/meta/app/src/principal/user_setting_ident.rs
- src/meta/app/src/principal/user_stage_file_ident.rs
- src/meta/app/src/principal/user_stage_ident.rs
- src/meta/app/src/tenant/tenant.rs
- src/meta/app/src/tenant/tenant_quota_ident.rs
- src/meta/app/src/tenant_key.rs
- src/query/management/src/role/role_mgr.rs
- src/query/service/src/api/http/v1/background_tasks.rs
> chore: use Tenant::new_literal() and new_nonempty() to avoid creating empty Tenant

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/api/src/util.rs
- src/meta/app/src/data_mask/mod.rs
- src/meta/app/src/schema/catalog.rs
- src/meta/app/src/schema/database.rs
- src/meta/app/src/schema/index.rs
- src/meta/app/src/schema/least_visible_time.rs
- src/meta/app/src/schema/lock.rs
- src/meta/app/src/schema/table.rs
- src/meta/app/src/schema/virtual_column.rs
- src/meta/app/src/share/share.rs
CatalogIdToName
DatabaseId
DatabaseIdToName
DatabaseNameIdent
DatamaskId
DatamaskNameIdent
DbIdListKey
IndexId
IndexIdToName
LeastVisibleTimeKey
MaskpolicyTableIdListKey
MaskpolicyTableIdListKey
ShareEndpointIdent
ShareNameIdent
TableLockKey
VirtualColumnNameIdent
> refactor: remove serde from kvapi::Key types

- src/query/service/src/interpreters/access/privilege_access.rs
- tests/suites/0_stateless/18_rbac/18_0007_privilege_access.result
- tests/suites/0_stateless/18_rbac/18_0007_privilege_access.sh
To use the OVERWRITE option on INSERT, you must use a role that has DELETE privilege on the table because OVERWRITE will delete the existing records in the table.
> fix: privilege check for insert statement

- src/meta/api/src/background_api_impl.rs
- src/meta/api/src/background_api_test_suite.rs
- src/meta/app/src/background/background_job.rs
- src/meta/app/src/background/job_ident.rs
- src/meta/app/src/background/mod.rs
- src/meta/app/src/background/task_creator.rs
- src/query/ee/src/background_service/background_service_handler.rs
- src/query/ee/src/background_service/compaction_job.rs
- src/query/ee/src/background_service/job_scheduler.rs
- src/query/ee/tests/it/background_service/job_scheduler.rs
- src/query/ee_features/background_service/src/background_service.rs
- src/query/service/src/table_functions/others/execute_background_job.rs
Define BackgroundJobIdent with `TIdent`, make
`BackgroundJobIdent.tenant` a `Tenant` instead of a plain `String`.
> refactor: use type `Tenant` for `BackgroundJobIdent.tenant`

- src/query/service/src/interpreters/interpreter.rs
- src/query/service/src/interpreters/mod.rs
- src/query/service/src/servers/http/clickhouse_handler.rs
- src/query/service/src/servers/http/v1/query/execute_state.rs
- src/query/service/src/servers/mysql/mysql_interactive_worker.rs
- src/query/service/src/table_functions/others/suggested_background_tasks.rs
- src/query/service/tests/it/api/http/status.rs
- tests/sqllogictests/suites/base/01_system/01_0002_system_query_log.test
There are two steps to execute a query:
1. Plan the SQL -- here error we can not write query_log
2. Execute the plan -- interpreter
This PR add a new function: `interpreter_plan_sql`, it's a wrap of `plan_sql`,  If `plan_sql` error occurs, we will log the query start and finished.
Where is use `interpreter_plan_sql`:
1. http handler
2. ClickHouse handler
3. MySQL handler
4. suggested_background_tasks.rs
- Fixes #15065
> fix: fix plan_sql error can not write query_log

- src/query/storages/fuse/src/pruning/block_pruner.rs
Make the block_pruning.rs more clear:
1. internal_column_pruning
2. inverted_index_pruning
3. block_pruning[_sync]
This PR only for refactoring.
> refactor: make the block pruning more clear

- src/query/service/src/pipelines/processors/transforms/hash_join/spill_common.rs
- tests/sqllogictests/suites/query/spill/basic_spill.test
> fix: make block data type be consistent with hash method

- src/query/settings/src/settings_default.rs
fix sql_dialect description info
- Fixes #14811
> fix: add prql description

- tests/sqllogictests/suites/query/window_function/expr_in_window.test
sqllogicaltest datatype mismatch in `expr_in_window.test`. `depname` should be type T not I.
> fix: sqllogicaltest datatype mismatch in `expr_in_window.test`

- src/query/service/src/api/rpc/packets/packet_executor.rs
- src/query/service/src/schedulers/fragments/query_fragment_actions.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/settings/src/settings.rs
There is no need to have the entire `Settings` in `QueryFragmentsPlanPacket`.
Only the `Settings.changes` is used.
And `Settings.tenant` can not be `serde` in future, ths
`QueryFragmentsPlanPacket` can not include a `Tenant` in it.
> refactor: `QueryFragmentsPlanPacket` should include just setting changes

- tests/sqllogictests/suites/query/window_function/window_basic.test
test duplicate in `window_basic.test`
Perhaps it would be better to have only one identical copy of the test in the test file.
- https://github.com/datafuselabs/databend/blob/main/tests/sqllogictests/suites/query/window_function/window_basic.test#L56-L99
- https://github.com/datafuselabs/databend/blob/main/tests/sqllogictests/suites/query/window_function/window_basic.test#L116-L159
> fix: test duplicate in `window_basic.test`

- Cargo.lock
- src/query/service/src/interpreters/interpreter_select.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/storages/result_cache/Cargo.toml
- src/query/storages/result_cache/src/write/sink.rs
- src/query/storages/result_cache/src/write/writer.rs
- tests/sqllogictests/suites/base/01_system/01_0011_system_query_cache.test
- tests/sqllogictests/suites/base/20+_others/20_0013_query_result_cache.test
- tests/sqllogictests/suites/base/20+_others/20_0014_result_scan.test
1. add query_result_cache_min_execute_secs settings. For a query to be cached, it must take at least this many seconds to fetch the first block. It helps to avoid caching queries that are too fast to execute or queries with streaming scan.
2. Increase wait_time_secs to be 10 secs.
- Fixes #15097
> feat(query): add query_result_cache_min_execute_secs

- src/meta/app/src/principal/user_grant.rs
- src/meta/app/tests/it/user_grant.rs
- src/query/service/src/interpreters/access/privilege_access.rs
- src/query/service/src/sessions/session.rs
- src/query/service/src/sessions/session_privilege_mgr.rs
- src/query/users/tests/it/role_mgr.rs
- src/query/users/tests/it/user_mgr.rs
- tests/suites/0_stateless/18_rbac/18_0007_privilege_access.result
- tests/suites/0_stateless/18_rbac/18_0007_privilege_access.sh
verify_privilege need fold same GrantEntry
E.g.
```sql
grant insert on default.* to role role1;
grant delete on default.t to u1;
grant role role1 to u1;
-- login in with u1; -- need success.
insert overwrite t values(100) 
```
> fix(query): verify_privilege need check privilege one by one

- src/query/pipeline/core/src/processors/profile.rs
chore(executor): remove duplicate profile statistics
> chore(executor): remove duplicate profile statistics

- src/query/ast/src/ast/format/ast_format.rs
- src/query/ast/src/ast/format/syntax/ddl.rs
- src/query/ast/src/ast/format/syntax/query.rs
- src/query/ast/src/ast/query.rs
- src/query/ast/src/ast/statements/stream.rs
- src/query/ast/src/ast/visitors/visitor.rs
- src/query/ast/src/ast/visitors/visitor_mut.rs
- src/query/ast/src/ast/visitors/walk.rs
- src/query/ast/src/ast/visitors/walk_mut.rs
- src/query/ast/src/parser/query.rs
- src/query/ast/src/parser/stream.rs
- src/query/ast/tests/it/testdata/statement.txt
- src/query/catalog/src/table.rs
- src/query/ee/src/stream/handler.rs
- src/query/sql/src/planner/binder/ddl/stream.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/sql/src/planner/plans/ddl/stream.rs
- src/query/storages/fuse/src/operations/navigate.rs
- tests/suites/5_ee/05_stream/05_0002_ee_stream_create.result
- tests/suites/5_ee/05_stream/05_0002_ee_stream_create.sh
```sql
SELECT ...
FROM ...
AT ( { SNAPSHOT => <snapshot_id> | TIMESTAMP => <timestamp> | (STREAM => '<name>')} );
```
```sql
OPTIMIZE TABLE <table_name> PURGE [BEFORE (SNAPSHOT => '<SNAPSHOT_ID>') 
| (STREAM => '<name>') | (TIMESTAMP => '<TIMESTAMP>'::TIMESTAMP)] 
[LIMIT <snapshot_count>]
```
```
Query OK, 1 row affected (0.04 sec)
mysql> insert into t values(2);
Query OK, 1 row affected (0.05 sec)
mysql> create or replace stream s on table t;
mysql> insert into t values(3);
Query OK, 1 row affected (0.11 sec)
mysql> select * from t at(stream=>s);
+------+
| a …
```
> feat: time travel support at stream

- src/meta/api/src/schema_api_test_suite.rs
- src/meta/api/src/share_api_test_suite.rs
- src/query/management/tests/it/user.rs
- src/query/service/src/interpreters/access/privilege_access.rs
- src/query/service/src/interpreters/common/query_log.rs
- src/query/service/src/interpreters/interpreter_data_mask_desc.rs
- src/query/service/tests/it/api/rpc_service.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- src/query/storages/fuse/src/operations/analyze.rs
errorcode use snake shape format
We have macro `build_exceptions` can expand code. Use macro keep code clean.
> chore(query): errorcode use snake shape format

- src/query/ee/src/stream/handler.rs
- src/query/storages/fuse/src/operations/navigate.rs
- tests/suites/5_ee/02_data_mask/02_0000_data_mask.py
- tests/udf/udf_server.py
Just clone the table seq when do navigate to, treat as a place holder
Set the table seq when create stream.
> chore: treat seq as place holder when navigate

- src/query/service/src/interpreters/interpreter_delete.rs
- src/query/sql/src/planner/binder/ddl/index.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/sql/src/planner/binder/insert.rs
- src/query/sql/src/planner/binder/replace.rs
- src/query/sql/src/planner/dataframe.rs
- src/query/sql/src/planner/optimizer/optimizer.rs
- src/query/sql/src/planner/planner.rs
In https://github.com/datafuselabs/databend/pull/15112, we read metadata in the optimizer phase, since async runtime cannot be nested, we need to make optimize function async.
> chore(planner): make optimize function async

- Cargo.lock
- src/query/ee/tests/it/aggregating_index/index_scan.rs
Increase the test stack from the default 2M to 20M to avoid stack overflow.
> chore: adjust stack size of flaky ut

- src/meta/api/src/data_mask_api_impl.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/data_mask/data_mask_name_ident.rs
- src/meta/app/src/data_mask/mask_policy_table_id_list_ident.rs
- src/meta/app/src/data_mask/mod.rs
- src/meta/app/src/tenant/mod.rs
- src/meta/app/src/tenant/tenant.rs
- src/meta/app/src/tenant_key.rs
- src/query/ast/src/parser/statement.rs
- src/query/ee/src/data_mask/data_mask_handler.rs
- src/query/ee_features/data_mask/src/data_mask_handler.rs
- src/query/service/src/interpreters/interpreter_data_mask_desc.rs
- src/query/service/src/interpreters/interpreter_table_modify_column.rs
- src/query/sql/src/executor/table_read_plan.rs
- src/query/sql/src/planner/binder/ddl/data_mask.rs
- src/query/sql/src/planner/plans/data_mask.rs
> refactor: use TIdent to unify kvapi key def for MaskPolicyTableIdListIdent and DataMaskNameIdent

- src/query/sql/src/planner/semantic/type_check.rs
to avoid stackoverflow of UT 
- aggregating_index::index_scan::test_fuzz_with_spill
- aggregating_index::index_scan::test_fuzz
disables the async_backtrace of method `TypeChecker::resolve`.
-----
A grep of gdb bt of aborted execution (before this PR)
~~~
home-dev:~/workspace/fuse-query$ grep src/query/ gdb.txt
#2  0x0000555560bf5d77 in databend_common_sql::planner::semantic::type_check::{impl#0}::resolve::{async_block#0} () at src/query/sql/src/planner/semantic/type_check.rs:218
#4  0x0000555560c2790d in databend_common_sql::planner::semantic::type_check::{impl#0}::resolve_function::{async_fn#0}::{async_block#0} () at src/query/sql/src/planner/semantic/type_check.rs:2185
#12 0x0000555560c27163 …
> chore: to avoid UT stackoverflow, disable async_backtrace of `TypeChecker::resolve`

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/api/src/util.rs
- src/meta/app/src/schema/virtual_column.rs
- src/query/service/src/interpreters/hook/refresh_hook.rs
- src/query/service/src/interpreters/interpreter_virtual_column_alter.rs
- src/query/service/src/interpreters/interpreter_virtual_column_create.rs
- src/query/service/src/interpreters/interpreter_virtual_column_drop.rs
- src/query/sql/src/planner/binder/ddl/virtual_column.rs
- src/query/sql/src/planner/semantic/virtual_column_rewriter.rs
- src/query/storages/system/src/virtual_columns_table.rs
> refactor: use Tenat in VirtualColumnNameIdent

- src/query/ast/src/parser/statement.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
user option DEFAULT_ROLE ignore ascii_case
- Fixes #15132
> fix(query):user option DEFAULT_ROLE ignore ascii_case

- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/execute_state.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- tests/sqllogictests/src/client/http_client.rs
final is not ACKed by client, so client should not depend on the final response,
for server:
1. when response with `next_uri` =  `.../final`, all states should already be delivered to the client the latest in this response.
2. `/final` SHOULD response with nothing but `next_uri` = `null`, BUT to tolerant old clients, we still keep some fields.
for clients:
check `next_uri` before referring to other fields of the response.
> chore: client should not depend on the final response.

- src/common/base/src/runtime/metrics/family_metrics/histogram.rs
- src/common/base/src/runtime/metrics/histogram.rs
- src/common/base/src/runtime/metrics/mod.rs
- src/common/base/src/runtime/metrics/registry.rs
- src/common/base/tests/it/metrics/registry.rs
chore(query): use i64 min max value as histogram bucket min max limit
> chore(query): use i64 min max value as histogram bucket min max limit

- src/query/expression/src/aggregate/aggregate_hashtable.rs
- src/query/settings/src/settings_default.rs
- tests/sqllogictests/suites/mode/cluster/exchange.test
- tests/sqllogictests/suites/mode/cluster/explain_v2.test
- tests/sqllogictests/suites/mode/cluster/group_shuffle.test
In the previous PR, we implemented a new aggregation hash table. Now, it supports both singleton and cluster environments, and we have also added support for spill. This PR includes performance tests and try to enable the new aggregation hash table.
> chore(query): turn on new agg hashtable

- src/query/service/src/servers/http/v1/query/execute_state.rs
- src/query/service/src/sessions/queue_mgr.rs
- src/query/service/tests/it/sessions/queue_mgr.rs
- src/query/sql/src/planner/plans/plan.rs
This PR:
- Add `CopyIntoTable` and `CopyIntoLocation` into query queue.
- Add `length()` to QueryQueueManager to get the queue length.
- Add more info logs to http handler.
- Fixes https://github.com/datafuselabs/databend/pull/15143/files#r1546928376
> chore: add CopyInto to query queue

- src/common/exception/src/exception_code.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/app/src/app_error.rs
- src/query/service/src/interpreters/interpreter_table_show_create.rs
- tests/sqllogictests/suites/ee/04_ee_inverted_index/04_0000_async_inverted_index_base.test
- Show create table support display inverted index.
- Add `DuplicatedIndexColumnId` error code to check column id duplicate in different inverted indexes.
- Add `IndexColumnIdNotFound` error code to check invalid column id.
for example:
```sql
mysql> CREATE TABLE t (id int, content string);
Query OK, 0 rows affected (0.49 sec)
mysql> CREATE INVERTED INDEX IF NOT EXISTS idx1 ON t(content) tokenizer = 'chinese';
Query OK, 0 rows affected (0.16 sec)
mysql> SHOW CREATE TABLE t;
+-------+----------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table …
```
> feat(query): show create table support display inverted index

- src/query/expression/src/types/boolean.rs
- src/query/functions/src/scalars/comparison.rs
- tests/sqllogictests/suites/query/filter.test
Currently the comparison result of `false >= false`/`false <= false` is false, but the result should be true.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15171)
> chore(query): fix boolean type comparison

- src/query/ast/src/parser/query.rs
- tests/sqllogictests/suites/ee/06_ee_stream/06_0004_stream_changes.test
disallowing the use of `end => '....'` within the changes clause, since  it does not make sense so much. 
```
mysql> create table t(a int)change_tracking=true;
Query OK, 0 rows affected (0.15 sec)
mysql> insert into t values(2);
Query OK, 1 row affected (0.15 sec)
Query OK, 1 row affected (0.16 sec)
mysql> create stream s on table t append_only = false;
Query OK, 0 rows affected (0.14 sec)
mysql> select * from t changes(information=>default) at(snapshot=>'c8aa4edd973246749520bc7c57c47e1a') end(stream=>s1);
ERROR 1105 (HY000): SyntaxException. Code: 1005, Text = error: 
--> SQL:1:100
|
1 | select * from t changes(information=>default) …
```
> fix: forbid end at stream syntax

- src/meta/api/src/background_api_impl.rs
- src/meta/api/src/background_api_test_suite.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/background/background_job.rs
- src/meta/app/src/background/background_task.rs
- src/meta/app/src/schema/catalog.rs
- src/meta/app/src/schema/index.rs
- src/meta/app/src/tenant/tenant.rs
- src/query/catalog/src/catalog/manager.rs
- src/query/service/src/api/http/v1/background_tasks.rs
- src/query/service/src/servers/flight_sql/flight_sql_service/catalog.rs
- src/query/sql/src/planner/binder/ddl/index.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/storages/system/src/background_jobs_table.rs
- src/query/storages/system/src/background_tasks_table.rs
- src/query/storages/system/src/catalogs_table.rs
- src/query/storages/system/src/databases_table.rs
- src/query/storages/system/src/indexes_table.rs
- src/query/storages/system/src/locks_table.rs
- src/query/storages/system/src/streams_table.rs
- src/query/storages/system/src/tables_table.rs
> refactor: use `Tenant` for `ListBackgroundTasksReq`

- Cargo.lock
- src/query/expression/src/values.rs
- src/query/expression/tests/it/kernel.rs
- src/query/expression/tests/it/main.rs
- src/query/service/src/interpreters/interpreter_table_create.rs
- src/query/service/tests/it/pipelines/filter/filter_executor.rs
- src/query/service/tests/it/pipelines/filter/random_filter_expr.rs
- src/query/storages/common/table_meta/src/table/table_keys.rs
- src/query/storages/random/Cargo.toml
- src/query/storages/random/src/random_table.rs
- src/tests/sqlsmith/src/sql_gen/dml.rs
Syntax:
```
create table t(a int, time timestamp) Engine=Random(1000);
select * from t; -- -- this will generate 1000 random values.
```
- Fixes #11863
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15167)
> feat: Support to add random seed on random engine

- Cargo.lock
- Cargo.toml
OpenDAL currently returns an empty credential when COS loading fails—for instance, if there's an error with COS IAM. As a result, this triggers a Permission Denied error on the Databend side.
This PR modifies OpenDAL's behavior to return a retryable error instead, allowing OpenDAL to internally retry the request.
> fix(storage): Don't return empty credential while loading failed

- src/query/config/src/config.rs
- src/query/config/src/inner.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
chore(query) max_running_queries from 0 to 8, enable the max running queries
> chore(query): max_running_queries from 0 to 8, enable the max running queries

- src/common/metrics/src/metrics/session.rs
- src/query/service/src/sessions/queue_mgr.rs
chore(query): add session_running_acquired_queries metric. record the number of running queries in the acquired queue
> chore(query): add session_running_acquired_queries metric

- .github/actions/fuse_compat/action.yml
- src/query/management/src/role/role_api.rs
- src/query/management/src/role/role_mgr.rs
- src/query/users/src/role_mgr.rs
- tests/fuse-compat/compat-logictest/rbac/fuse_compat_read
- tests/suites/0_stateless/18_rbac/18_0002_ownership_cover.result
- tests/suites/0_stateless/18_rbac/18_0008_privilege_ownership.result
- tests/suites/0_stateless/18_rbac/18_0008_privilege_ownership.sh
drop role will transfer role owns object to account_admin
E.g.
```sql
create role role1;
create user u1 identified by '123' with default_role='role1';
grant role role1 to u1;
```
use u1 create some database then, drop the role1. In ownership-kv, the object keys value is a dropped role role1.
If admin user wants to create a new role also named role1, the new role `role1` will directly has objects ownership. That maybe dangerous. 
So in this pr, add a check: dorp role will check the dropped role owns some object. If true, transfer the owner to account_admin.
Add forward/backward compat test.
drop role can execute in old version(1.0.307) and new version.
- - -
This …
> feat(rbac): drop role will transfer role owns object to account_admin

- src/query/sql/src/planner/binder/setting.rs
- tests/sqllogictests/suites/base/05_ddl/05_0026_ddl_unset_settings.test
E.g.
```sql
SET GLOBAL DATA_RETENTION_TIME_IN_DAYS=0; -- Need work
```
- Fixes #15197
> fix(query): set setting case insensitive

- src/query/catalog/src/catalog/interface.rs
- src/query/catalog/src/catalog/session_catalog.rs
- src/query/service/src/catalogs/default/database_catalog.rs
- src/query/service/src/catalogs/default/immutable_catalog.rs
- src/query/service/src/catalogs/default/mutable_catalog.rs
- src/query/service/src/interpreters/interpreter_show_grants.rs
- src/query/service/tests/it/sql/exec/get_table_bind_test.rs
- src/query/service/tests/it/storages/fuse/operations/commit.rs
- src/query/storages/hive/hive/src/hive_catalog.rs
- src/query/storages/iceberg/src/catalog.rs
- tests/suites/0_stateless/18_rbac/18_0005_show_grants_with_dropped.result
- tests/suites/0_stateless/18_rbac/18_0005_show_grants_with_dropped.sh
show grants panic when role/user has immute db/table privilege
The mutetable catalog mget need discard the immuteable db/table id.
If not, will generate vec out of index.
Easy way to reproduce
```sql
create role role3;
grant select on system.one to role role3;
show grants for role role3;
```
So in this pr, we split the db/table id in DatabaseCatalog
- Fixes #15187
> fix(query): show grants panic when role/user has immute db/table privilege

- src/common/io/src/geometry.rs
- src/query/functions/src/scalars/geometry.rs
- src/query/functions/tests/it/scalars/geometry.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/geometry.txt
- tests/sqllogictests/suites/query/functions/02_0060_function_geometry.test
feat:  Implement  ST_MAKEPOLYGON(). see alse [doc](https://docs.snowflake.com/en/sql-reference/functions/st_makepolygon).
other: remove to_geometry alias,becasue register_aliases() only depend on alias_name as key which will cause the  registered function to be overwritten.
```
pub fn register_aliases(&mut self, fn_name: &str, aliases: &[&str]) {
for alias in aliases {
self.aliases.insert(alias.to_string(), fn_name.to_string());
}
}
registry.register_aliases("st_geometryfromwkb", &[
"to_geometry",
]);
registry.register_aliases("st_geometryfromwkt", &[
"to_geometry",
]);
```
> feat(query): implement ST_MAKEPOLYGON

- Cargo.lock
- src/bendpy/Cargo.toml
- src/bendpy/src/context.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/principal/user_identity.rs
- src/meta/app/src/principal/user_stage_file_ident.rs
- src/meta/app/src/principal/user_stage_ident.rs
- src/meta/app/src/tenant/tenant_quota_ident.rs
- src/meta/app/src/tenant_key/ident.rs
- src/query/catalog/src/catalog/manager.rs
- src/query/service/src/catalogs/default/mutable_catalog.rs
- src/query/service/src/databases/database_factory.rs
- src/query/sql/src/planner/binder/ddl/index.rs
> refactor: simplify `DatabaseFactory`, just static dispatch

- src/query/sql/src/planner/optimizer/decorrelate/decorrelate.rs
- src/query/sql/src/planner/optimizer/decorrelate/subquery_rewriter.rs
- tests/sqllogictests/suites/mode/standalone/explain/subquery.test
- tests/sqllogictests/suites/mode/standalone/explain_native/subquery.test
- tests/sqllogictests/suites/query/subquery.test
When decorrelating uncorrelated exists subquery, if `is_conjunctive_predicate` is false, we need to generate `EvalScalar` instead of `Filter`.
```sql
drop table if exists t;
create table t(i int null);
insert into t values(1), (2), (3), (null);
select i, exists(select * from t where i > 10) from t;
```
Currently this SQL will get an incorrect result: empty result set, but the correct result should be:
```sql
┌─────────────────────────────────────────────────────────┐
│        i        │ exists (select * from t where i > 10) │
│ Nullable(Int32) │           Nullable(Boolean)           │
├─────────────────┼───────────────────────────────────────┤
│               1 │ false …
```
> chore(planner): fix decorrelate exists subquery

- src/query/service/src/databases/system/system_database.rs
- src/query/service/src/interpreters/access/privilege_access.rs
- src/query/service/src/interpreters/interpreter_table_describe.rs
- src/query/service/src/interpreters/interpreter_view_describe.rs
- src/query/service/src/interpreters/util.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/sql/src/planner/binder/ddl/view.rs
- src/query/storages/information_schema/src/views_table.rs
- src/query/storages/system/src/lib.rs
- src/query/storages/system/src/tables_table.rs
- tests/sqllogictests/suites/base/01_system/01_0003_information_schema.test
Add system tables: system.view and system.view_with_history
The view engine no need to display stat info.
And fuse engine does not have view_query.
After this pr merged, if user wants to show the views in one database, 
Only can according sql `show views [ from|in database ]`.
`show tables` only support show tables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15184)
> refactor: add view system tables

- src/query/service/src/interpreters/interpreter_table_modify_column.rs
- tests/sqllogictests/suites/base/05_ddl/05_0003_ddl_alter_table.test
```sql
create table t1(id varchar, id2 varchar);
Query OK, 0 rows affected (0.060 sec)
MySQL [(none)]> alter table t1 modify id varchar comment 'ss';
Query OK, 0 rows affected (0.246 sec)
MySQL [(none)]> alter table t1 modify id varchar comment 'ss', id2 varchar comment 's3';
Query OK, 0 rows affected (0.079 sec)
```
After alter:
```sql
show create table t1;
+-------+-----------------------------------------------------------------------+
| Table | Create Table                                                          |
+-------+-----------------------------------------------------------------------+
| t1    | CREATE TABLE t1 (
id VARCHAR NULL,
id2 VARCHAR NULL
) ENGINE=FUSE | …
```
> fix(query): alter modify col comment need modify when type not modify

- src/query/sql/src/planner/optimizer/decorrelate/flatten_plan.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_scan.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_limit_scan.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_prewhere.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_sort_scan.rs
- src/query/sql/src/planner/plans/operator.rs
Replace op name LogicalGet to Scan. 
- Fixes #15218
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15222)
> chore: old op LogicalGet modify to new op name Scan

- src/query/ee/src/storages/fuse/operations/vacuum_drop_tables.rs
- src/query/ee/tests/it/storages/fuse/operations/vacuum.rs
To enhance security, users would like to utilize their own external bucket location (stage) for the FUSE table. However, the [`VACUUM DROP TABLE`](https://docs.databend.com/sql/sql-commands/ddl/table/vacuum-drop-table) command does not affect this feature. 
This pull request aims to make the external location FUSE table function similarly to a standard location FUSE table.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15220)
> chore: vacuum drop table for external location table

- src/query/storages/common/index/src/range_index.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0009_04_range_pruning.test
fix nullable array domain
The previous domain of `nullable<array>` will generate stats of `null_count` = 0.
This is incorrect.
- Fixes #15170
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15224)
> chore(query): fix nullable array domain

- src/query/service/src/servers/http/middleware.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
currently the IP we got is retrieved from req.remote_addr, which represents the direct connection's IP address.
but when we deployed with having a proxy up front, it only reprents the proxy's IP.
this PR tries to retrieve the ip from headers including X-Real-IP, X-Forwarded-For, CF-Connecting-IP, these headers can help us retrieve the real ip of the client.
please note that the ip address from the headers are easy to be manipulated by middleman. we have to ensure the proxies are trustworthy, or the middleman may use a fake header to trick the network policy.
(however, it's necessary to trust the proxy in a cloud deployment IMHO.)
- - - …
> feat(http): get client ip from headers

- src/query/functions/src/scalars/map.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/map.txt
- src/query/storages/common/index/src/bloom_index.rs
- tests/sqllogictests/suites/base/03_common/03_0037_insert_into_map.test
for this query:
```sql
CREATE OR REPLACE TABLE t1(tags Map(String, String)) Engine = Fuse
statement ok
INSERT INTO t1 VALUES ({'region':'sg', 'az': '1'}),({'region':'sg', 'az': '2'}), ({'region':'hk', 'az': '1'}),({'region':'hk', 'az': '2'})
query I
SELECT to_int32(tags['az']) AS int_az FROM t1 WHERE tags['region'] = 'sg' ORDER BY int_az;
```
The `tags[az]` will call `map#get` with input data type `MapType<GenericType<0>, GenericType<1>>` and return data type `NullableType<GenericType<1>>`, however, if `GenericType<1>` is already a nullable type, this will return `Nullable<Nullable<XXX>>`.
When this return type pass to `to_int32`, the `try_downcast_column().unwrap()` will failed.
This PR add a …
> fix: fix map get return double nested nullable

- src/query/ast/src/parser/expr.rs
- src/query/ast/tests/it/testdata/statement-error.txt
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_prewhere.rs
- tests/sqllogictests/suites/mode/standalone/explain_native/prewhere_optimization.test
ScalarVisitor refactor push_down_prewhere
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15215)
> refactor: ScalarVisitor refactor push_down_prewhere

- src/query/service/src/interpreters/interpreter_execute_immediate.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- tests/sqllogictests/suites/base/15_procedure/15_0001_execute_immediate.test
```sql
set script_max_steps = 1000;
```
Related https://github.com/datafuselabs/databend/issues/14904
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15244)
> feat: add setting `script_max_steps`

- src/meta/api/src/schema_api_impl.rs
- src/meta/app/src/background/background_job.rs
- src/meta/app/src/data_mask/mod.rs
- src/meta/app/src/id_generator.rs
- src/meta/app/src/key_with_tenant.rs
- src/meta/app/src/principal/user_grant.rs
- src/meta/app/src/principal/user_identity.rs
- src/meta/app/src/schema/catalog.rs
- src/meta/app/src/schema/database.rs
- src/meta/app/src/schema/index.rs
- src/meta/app/src/schema/lock.rs
- src/meta/app/src/schema/table.rs
- src/meta/app/src/schema/virtual_column.rs
- src/meta/app/src/share/share.rs
- src/meta/app/src/tenant/tenant.rs
- src/meta/kvapi/src/kvapi/key.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15243)
> refactor: avoid using PREFIX directly. use method to build list-prefix

- src/query/expression/src/function.rs
- src/query/functions/src/scalars/datetime.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test
Added a new setting parse_datetime_ignore_remainder.
When enabled, this setting allows parsing strings into time according to the specified format and ignores any excess string.
This setting is disabled by default.
- Fixes #15257
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15260)
> feat(query): add new setting parse_datetime_ignore_remainder.

- src/query/management/src/role/role_mgr.rs
Before this pr, if the transaction execution of granting ownership fails, it will be retried immediately. 
This often leads to frequent failures when multiple connections are simultaneously executing grant ownership.
This is because the role key may cause conflicts. A better solution is to store object and privilege separately as key-value pairs.
However, this solution involves significant changes. This PR temporarily adjusts the retry mechanism(
Tthe role information will be reacquired with each retry, aiming to minimize conflicts.). 
No TxnRetryMaxTimes errors occurred during local testing.
```sql
create user a identified by '123' with DEFAULT_ROLE='role1';
create role role1;
grant role …
```
> refactor: grant_ownership retry logic

- src/meta/app/src/background/background_job.rs
- src/meta/app/src/data_mask/mod.rs
- src/meta/app/src/id_generator.rs
- src/meta/app/src/principal/user_grant.rs
- src/meta/app/src/principal/user_identity.rs
- src/meta/app/src/principal/user_stage_file_ident.rs
- src/meta/app/src/schema/catalog.rs
- src/meta/app/src/schema/database.rs
- src/meta/app/src/schema/index.rs
- src/meta/app/src/schema/lock.rs
- src/meta/app/src/schema/table.rs
- src/meta/app/src/schema/virtual_column.rs
- src/meta/app/src/share/share.rs
- src/meta/app/src/tenant/tenant.rs
- src/meta/app/src/tenant/tenant_quota_ident.rs
- src/meta/app/src/tenant_key/ident.rs
- src/meta/kvapi/src/kvapi/key.rs
- src/meta/kvapi/src/kvapi/mod.rs
The `kvapi::Key` trait encompasses various key behaviors, including
prefix, parent, and value type. The key codec functionality,
responsible for encoding and decoding components of a key, operates
independently of these behaviors. This is evident in scenarios like a
database identifier `(tenant, db_name)`, where `db_name` requires its
own distinct codec logic independent of the overarching key structure.
This commit introduces the `kvapi::KeyCodec` trait, which abstracts the
codec functionality with two primary methods: `encode_key()` and
`decode_key()`. This separation enhances modularity and aligns with
single responsibility principles, allowing for more targeted
implementations and testing …
> refactor: Extract `kvapi::KeyCodec` trait from `kvapi::Key`

- src/meta/api/src/share_api_impl.rs
- src/meta/api/src/share_api_test_suite.rs
- src/meta/api/src/util.rs
- src/meta/app/src/share/mod.rs
- src/meta/app/src/share/share.rs
- src/meta/app/src/share/share_consumer_ident.rs
Remove the logic of not embedding `share_id` if it is 0.
Because `share_id` is always non-zero.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15280)
> refactor: define `ShareConsumer` with `TIdent`

- src/query/ast/src/parser/common.rs
- src/query/ast/tests/it/testdata/expr-error.txt
Refine set sql_dialect error message: `set sql_dialect = experimental` -> `set sql_dialect = 'experimental'`.
- Related to #13800 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15282)
> chore(query): refine set sql_dialect error message

- Cargo.lock
- src/query/service/Cargo.toml
- src/query/service/src/pipelines/processors/transforms/transform_udf_script.rs
- tests/sqllogictests/suites/base/03_common/03_0013_select_udf.test
1. bump arrow-udf to extra lib
2. Add tests for udf-script working with varchar types.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15283)
> chore(query): bump arrow-udf to extra lib

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/background/job_ident.rs
- src/meta/app/src/background/task_ident.rs
- src/meta/app/src/principal/role_ident.rs
- src/meta/app/src/principal/udf_ident.rs
- src/meta/app/src/schema/catalog_name_ident.rs
- src/meta/app/src/schema/database.rs
- src/meta/app/src/schema/database_id_history_ident.rs
- src/meta/app/src/schema/database_name_ident.rs
- src/meta/app/src/schema/index_name_ident.rs
- src/meta/app/src/schema/mod.rs
- src/meta/app/src/share/share_consumer_ident.rs
- src/meta/app/src/share/share_name_ident.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15287)
> refactor: define DbIdListKey with TIdent, and rename it to DatabaseIdHistoryIdent

- Cargo.lock
- src/query/catalog/Cargo.toml
- src/query/config/Cargo.toml
- src/query/pipeline/sources/Cargo.toml
- src/query/pipeline/transforms/Cargo.toml
- src/query/settings/Cargo.toml
- src/query/storages/result_cache/Cargo.toml
The license for some packages in Databend is not set and appears as "UNKNOWN." This pull request adds the `license = { workspace = true }` attribute to address this issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15299)
> chore: add license to cargo.toml

- src/query/sql/src/planner/optimizer/rule/rewrite/push_down_filter_join/outer_join_to_inner_join.rs
- tests/sqllogictests/suites/mode/standalone/explain/push_down_filter/push_down_filter_join/push_down_filter_join_left_outer.test
- tests/sqllogictests/suites/mode/standalone/explain_native/push_down_filter/push_down_filter_join/push_down_filter_join_left_outer.test
In `can_filter_null`, if the function is `assume_not_null` or `remove_nullable`, we cannot replace the column bindings with `Scalar::Null`.
- Fixes #15256 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15298)
> chore(planner): fix can_filter_null

- Cargo.lock
- scripts/ci/deploy/databend-query-cluster-3-nodes.sh
- src/query/sql/src/planner/plans/join.rs
- tests/sqllogictests/suites/mode/cluster/memo/aggregate_property.test
- tests/sqllogictests/suites/mode/cluster/memo/join_property.test
- tests/sqllogictests/suites/mode/cluster/memo/mix_property.test
- tests/sqllogictests/suites/mode/cluster/window.test
`Serial` is bad for distribution execution, we should avoid it as much as possible.
Before
```
mysql> explain SELECT
->     e.name AS EmployeeName,
->     d.department_name AS DepartmentName,
->     e.salary AS Salary,
->     ROW_NUMBER() OVER (PARTITION BY d.department_id ORDER BY e.salary DESC) AS SalaryRank
-> FROM
->     employees e
-> JOIN
->     departments d ON e.department_id = d.department_id
-> ORDER BY
->     DepartmentName,
->     SalaryRank;
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| explain …
```
> chore: improve distributed plan

- src/query/service/src/sessions/query_ctx_shared.rs
- src/query/storages/stream/src/stream_table.rs
- tests/sqllogictests/suites/ee/06_ee_stream/06_0000_stream.test
```sql
Query OK, 0 rows affected (0.14 sec)
mysql> create stream s on table t;
Query OK, 0 rows affected (0.12 sec)
mysql> drop table t;
Query OK, 0 rows affected (0.17 sec)
mysql> select * from s;
ERROR 1105 (HY000): IllegalStream. Code: 2733, Text = Cannot get base table 'default'.'t' from stream 'default'.'s', cause: Unknown table 't'.
mysql> select * from s;
ERROR 1105 (HY000): IllegalStream. Code: 2733, Text = Base table 'default'.'t' dropped, cannot read from stream 'default'.'s'.
```
- - - …
> chore: correct stream error message

- src/query/formats/src/field_decoder/json_ast.rs
- tests/data/ndjson/cast_sample.ndjson
- tests/sqllogictests/suites/stage/formats/ndjson/ndjson_cast.test
NDJSON copy into allow cast bool and number to string, avoid panic if the value is not string
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15308)
> fix(query): NDJSON copy into allow cast bool and number to string

- src/meta/app/src/background/job_ident.rs
- src/meta/app/src/background/task_ident.rs
- src/meta/app/src/data_mask/data_mask_name_ident.rs
- src/meta/app/src/data_mask/mask_policy_table_id_list_ident.rs
- src/meta/app/src/principal/connection_ident.rs
- src/meta/app/src/principal/network_policy_ident.rs
- src/meta/app/src/principal/password_policy_ident.rs
- src/meta/app/src/principal/role_ident.rs
- src/meta/app/src/principal/udf_ident.rs
- src/meta/app/src/principal/user_defined_file_format_ident.rs
- src/meta/app/src/principal/user_setting_ident.rs
- src/meta/app/src/principal/user_stage_ident.rs
- src/meta/app/src/schema/catalog_name_ident.rs
- src/meta/app/src/schema/database_id_history_ident.rs
- src/meta/app/src/schema/database_name_ident.rs
- src/meta/app/src/schema/index_name_ident.rs
- src/meta/app/src/schema/sequence.rs
- src/meta/app/src/schema/table_lock_ident.rs
- src/meta/app/src/schema/virtual_column_ident.rs
- src/meta/app/src/share/share_consumer_ident.rs
- src/meta/app/src/share/share_end_point_ident.rs
- src/meta/app/src/share/share_name_ident.rs
- src/meta/app/src/tenant/tenant_quota_ident.rs
- src/meta/app/src/tenant_key/ident.rs
- src/meta/app/src/tenant_key/resource.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15321)
> refactor: TIdent add a flag to indicate if the tenant should be encoded into key

- src/query/service/src/interpreters/interpreter_insert.rs
- src/query/service/src/servers/http/clickhouse_handler.rs
- src/query/service/src/servers/http/v1/load.rs
- src/query/sql/src/planner/plans/insert.rs
- src/query/sql/src/planner/plans/plan.rs
as a convention in this project, the `schema` of a specific Plan should be the schema of output.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15330)
> fix: insert Plan should not have schema.

- src/meta/api/src/data_mask_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/data_mask/data_mask_id_ident.rs
- src/meta/app/src/data_mask/data_mask_name_ident.rs
- src/meta/app/src/data_mask/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15331)
> refactor: Define DataMaskIdIdent with TIdent

- src/meta/raft-store/src/applier.rs
- src/meta/raft-store/src/sm_v002/leveled_store/level.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/sm_v002_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15334)
> refactor: add right bound when listing expired keys to avoid unnecessary data copy

- src/query/ast/src/ast/statements/copy.rs
- src/query/ast/src/parser/copy.rs
- src/query/ast/tests/it/testdata/statement.txt
- src/query/sql/src/planner/binder/copy_into_location.rs
- src/query/sql/src/planner/binder/copy_into_table.rs
- tests/sqllogictests/suites/base/03_common/03_0028_copy_into_stage.test
feat(query): support with clause in copy into
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15343)
> feat(query): support with clause in copy into

- src/meta/raft-store/Cargo.toml
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/types/src/raft_snapshot_data.rs
Move the IO into a separate thread and use `std::io` instead of `tokio::io`.
Using `tokio::io` and a default buf size of 8KB, reading 1.4G snapshot takes 60 seconds.
Using `std::io` and a 16MB buffer, reading 1.4G snapshot takes 7 seconds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15345)
> refactor: improve install-snapshot performance

- src/meta/raft-store/src/applier.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/writer_v002.rs
- src/meta/service/src/store/store_inner.rs
Add short sleep to avoid starving sled IO.
This commit is meant to address the issue when building a snapshot,
other IO such as appending log to sled db is delay significantly.
Remove several unnecessary INFO level log.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15351)
> refactor: move snapshot building io to other task.

- src/query/service/src/servers/http/middleware.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/http_query_context.rs
- src/query/service/src/sessions/session.rs
- tests/sqllogictests/suites/base/06_show/06_0013_show_processlist.test
Fix show processlit host is null in HTTPQuery.
In HTTP auth , init the client addr.
- Fixes #15359
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15363)
> fix(query): show processlit host is null in HTTPQuery

- src/query/storages/parquet/src/parquet_rs/parquet_table/read.rs
Although `ParquetFilesPart`s are always staying at the end of `parts` when `do_read_partitions`,
but parts are reshuffled when `redistribute_source_fragment`, so let us check all of them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15360)
> fix: check all partitions for small files instead of the last only.

- src/query/catalog/src/table_context.rs
- src/query/service/src/interpreters/common/query_log.rs
- src/query/service/src/servers/admin/v1/queries_queue.rs
- src/query/service/src/servers/http/middleware.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/http_query_context.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/src/sessions/session.rs
- src/query/service/src/sessions/session_ctx.rs
- src/query/service/tests/it/sessions/session_context.rs
- src/query/storages/system/src/processes_table.rs
- src/query/storages/system/src/queries_queue.rs
- tests/sqllogictests/suites/base/06_show/06_0013_show_processlist.test
session_ctx.client_ip refactor to Option<String>
Old version client_ip: Option<SocketAddr>
This appears to be CK-compatible behavior. But the port should be meaningless information.
- Fixes #15367
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15368)
> refactor: session_ctx.client_ip refactor to Option<String>

- src/meta/kvapi/src/kvapi/dir_name.rs
- src/meta/kvapi/src/kvapi/key.rs
- src/meta/kvapi/src/kvapi/key_parser.rs
- src/meta/kvapi/src/kvapi/mod.rs
- src/meta/kvapi/src/kvapi/testing.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15365)
> refactor: move DirName to separate file; add peek() to KeyParser

- src/meta/raft-store/src/lib.rs
- src/meta/raft-store/src/sm_v002/leveled_store/level.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/utils.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15372)
> fix: when listing-kv, limit the right bound if possible

- src/query/storages/fuse/src/operations/common/generators/mutation_generator.rs
Correct the assertion to check that the row count remains unchanged during table compaction, instead of comparing it(new snapshot) to the pre-compaction snapshot. This change accounts for scenarios where the new snapshot results from a combination of compaction and insertion, potentially increasing the total number of rows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15380)
> chore: adjust row count assertion in table compaction

- src/common/storage/src/stage.rs
- src/query/service/src/interpreters/interpreter_user_stage_remove.rs
- tests/suites/1_stateful/00_stage/00_0004_copy_with_max_files.result
- tests/suites/1_stateful/00_stage/00_0004_copy_with_max_files.sh
remove stage use stream instead of load all paths into one Vec to avoid OOM.
00_0004_copy_with_max_files.sh is changed too, no longer rely on the order of list of backends . cc @Xuanwo 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15378)
> refactor: remove stage use stream to avoid OOM.

- Cargo.lock
- Cargo.toml
- src/meta/raft-store/Cargo.toml
- src/meta/raft-store/src/sm_v002/sm_v002.rs
To reduce delay caused by installing snapshot on startup.
The major work load is deserializing data, and this part of job is
dispatched into 16 threads in this commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15381)
> refactor: dispatch load to 16 threads when installing snapshot

- src/common/hashtable/src/traits.rs
- src/common/hashtable/src/utils.rs
- src/common/metrics/src/metrics/storage.rs
- src/meta/api/src/schema_api.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/raft-store/tests/it/state_machine/mod.rs
- src/query/catalog/src/catalog/interface.rs
- src/query/catalog/src/catalog/session_catalog.rs
- src/query/catalog/src/table.rs
- src/query/service/src/catalogs/default/database_catalog.rs
- src/query/service/src/catalogs/default/immutable_catalog.rs
- src/query/service/src/catalogs/default/mutable_catalog.rs
- src/query/service/src/interpreters/common/grant.rs
- src/query/service/src/interpreters/interpreter_merge_into.rs
- src/query/service/src/pipelines/builders/builder_merge_into.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/merge_into_hash_join_optimization.rs
- src/query/service/src/servers/admin/v1/stream_status.rs
- src/query/service/tests/it/sql/exec/get_table_bind_test.rs
- src/query/service/tests/it/storages/fuse/operations/commit.rs
- src/query/sql/src/planner/binder/merge_into.rs
- src/query/sql/src/planner/format/display_plan.rs
- src/query/sql/src/planner/optimizer/optimizer.rs
- src/query/sql/src/planner/plans/update.rs
- src/query/storages/fuse/src/operations/merge_into/mutator/matched_mutator.rs
- src/query/storages/fuse/src/operations/merge_into/processors/processor_merge_into_matched_and_split.rs
- src/query/storages/hive/hive/src/hive_catalog.rs
- src/query/storages/iceberg/src/catalog.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0035_merge_into_separate_pipeline_without_distributed_enable.test
- tests/sqllogictests/suites/base/09_fuse_engine/09_0036_merge_into_without_distributed_enable.test
Make `get` methods behave in a conventional way: return `None` if the
subject is not found.
Other changes:
Extend expire time to survive slow CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15388)
> refactor: get_table_by_id() returns an `Option<Seqv<TableMeta>>`

- src/meta/api/src/schema_api.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/service/src/metrics/meta_metrics.rs
- src/query/catalog/src/catalog/interface.rs
- src/query/catalog/src/catalog/session_catalog.rs
- src/query/service/src/catalogs/default/database_catalog.rs
- src/query/service/src/catalogs/default/immutable_catalog.rs
- src/query/service/src/catalogs/default/mutable_catalog.rs
- src/query/service/tests/it/sql/exec/get_table_bind_test.rs
- src/query/service/tests/it/storages/fuse/operations/commit.rs
- src/query/storages/hive/hive/src/hive_catalog.rs
- src/query/storages/iceberg/src/catalog.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15389)
> refactor: remove get_table_name_by_id()

- Cargo.lock
- Cargo.toml
- src/meta/service/src/meta_service/raft_service_impl.rs
- src/meta/service/tests/it/meta_node/meta_node_replication.rs
- src/meta/service/tests/it/tests/service.rs
- src/meta/types/src/grpc_helper.rs
This fix updates OpenRaft to version 0.9.8 to address an issue where,
upon receiving a `SnapshotMismatch` error, the snapshot should be resent
from the beginning. This ensures that the leader can correctly reset and
reinitiate the snapshot transmission process.
And meta-service should return `SnapshotMismatch` error instead of
returning an internal gRPC error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15391)
> fix: Respond with `SnapshotMismatch` error instead of internal error

- src/meta/kvapi/src/kvapi/message.rs
- src/meta/service/src/api/grpc/grpc_service.rs
- src/meta/types/src/lib.rs
- src/meta/types/src/proto_display.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15392)
> chore: if a txn log is too long, display only the first 5 items

- Cargo.lock
- Cargo.toml
Fix opendal upstream commit missing
We depends on commit https://github.com/Xuanwo/opendal/commit/53377ca873c2928ce519ca57a939f89af1a76c47, but the upstream has already merge it into main with breaking changes. This PR is used to make sure we can build as before.
We will bump opendal to 0.46 once upstream is ready.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15393)
> chore: Fix opendal upstream commit missing

- src/meta/service/src/meta_service/mod.rs
- src/meta/service/src/meta_service/raft_service_impl.rs
- src/meta/service/src/meta_service/snapshot_receiver.rs
- src/meta/service/tests/it/meta_node/meta_node_replication.rs
- src/meta/types/src/proto_ext/snapshot_chunk_request_ext.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15399)
> refactor: in snapshot-v2 protocol, move head to end to inform explicitly streaming end

- src/query/sql/src/planner/binder/merge_into.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0011_change_tracking.test
The bug fixed by this PR:
```sql
mysql> create table t3(a int, b int) cluster by(a+1) change_tracking=true ;
Query OK, 0 rows affected (0.15 sec)
mysql> insert into t3 values(1, 1), (3, 3), (2, 3);
Query OK, 3 rows affected (0.20 sec)
mysql> create table t4(a int, b int, c int) ;
Query OK, 0 rows affected (0.08 sec)
mysql> insert into t4 values(0, 1, 0), (3, 4, 3), (4, 5, 4) ;
Query OK, 3 rows affected (0.17 sec)
mysql> merge into t3 tt using t4 on tt.a = t4.a when matched and t4.a = 4 then delete when matched then update set tt.b = t4.c when not matched then insert values(t4.a, t4.c) ;
ERROR 1105 (HY000): Internal. Code: 1001, Text = row_version It's a bug.
``` …
> fix(storage): change tracking with alias update row_version bug in merge into

- src/meta/service/src/store/store_inner.rs
- src/meta/service/src/version.rs
Optimize the locking mechanism in the raft-log export process.
Previously, the lock was held until the export was fully completed. With
this refactor:
- For raft-log exports: Release the lock immediately after transferring logs to memory.
- For snapshot exports: Release the lock once the snapshot file is opened.
This change reduces the time the lock is held, potentially improving performance and concurrency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15417)
> refactor: Minimize lock duration during raft-log export

- src/query/service/src/pipelines/processors/transforms/aggregator/new_transform_partition_bucket.rs
fix bug on new agg singleton `TransformPartitionBucket' initialize_all_inputs, ensure all inputs pull all data that less than max partition count  and ensure partition count are same when all_inputs_init
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15418)
> fix(query): ensure all inputs pull all data that less than max partition count in new agg singleton

- src/meta/api/src/schema_api_impl.rs
- src/meta/app/src/schema/catalog.rs
- src/meta/app/src/schema/catalog_id.rs
- src/meta/app/src/schema/catalog_name_ident.rs
- src/meta/app/src/schema/mod.rs
- src/query/catalog/src/catalog/manager.rs
- src/query/service/src/interpreters/interpreter_catalog_create.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15429)
> refactor: define CatalogIdIdent with TIdent

- src/query/functions/src/scalars/array.rs
- src/query/functions/tests/it/scalars/testdata/array.txt
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- tests/sqllogictests/suites/query/functions/02_0061_function_array.test
- Modify the domain calculation of `array_concat`, `array_distinct`, `array_flatten` functions to avoid generic type domain panic.
- Reimplement `array_prepend` and `array_append` functions to support the case where the inner type is nullable.
* Fixes #15408
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15424)
> fix(query): fix `array_concat` function domain panic

- src/query/service/src/interpreters/access/privilege_access.rs
- src/query/service/src/interpreters/common/grant.rs
- src/query/service/src/interpreters/interpreter_user_stage_drop.rs
- src/query/settings/src/settings_default.rs
- src/query/sql/src/planner/binder/binder.rs
- tests/suites/0_stateless/18_rbac/18_0001_udf_priv.sh
- tests/suites/0_stateless/18_rbac/18_0002_ownership_cover.sh
- tests/suites/0_stateless/18_rbac/18_0007_privilege_access.sh
- tests/suites/1_stateful/00_stage/00_0012_stage_priv.sh
set enable_experimental_rbac_check default 1
In the default setting of enable_experimental_rbac_check
User can drop udf/stage that is owned by themself role.
Note:
Because of the flag `if exists`, need to get udf/stage in privilege_access.rs .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15436)
> refactor: set enable_experimental_rbac_check default 1

- src/query/sql/src/planner/plans/plan.rs
- tests/sqllogictests/suites/base/05_ddl/05_0023_exists_table.test
- Fixes https://github.com/datafuselabs/databend/issues/15420
the bug is due to https://github.com/datafuselabs/databend/pull/15330/files. 
before that pr,  for http handler, has_result_set=false does not matter as long as the plan return a none empty schema.
after that, they should  be consistent.
for mysql handler,  has_result_set always counts, this pr fix it too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15431)
> fix: ExistsTable should has_result_set.

- src/query/service/src/interpreters/interpreter_merge_into.rs
- src/query/service/src/pipelines/builders/builder_merge_into.rs
- src/query/service/src/pipelines/pipeline_builder.rs
- src/query/sql/src/executor/format.rs
- src/query/sql/src/executor/physical_plan.rs
- src/query/sql/src/executor/physical_plan_display.rs
- src/query/sql/src/executor/physical_plan_visitor.rs
- src/query/sql/src/executor/physical_plans/physical_merge_into.rs
- src/query/sql/src/planner/binder/merge_into.rs
- src/query/storages/fuse/src/operations/merge.rs
- src/query/storages/fuse/src/operations/merge_into/mutator/update_by_expr_mutator.rs
- src/query/storages/fuse/src/operations/merge_into/processors/processor_merge_into_split.rs
It's not necessary to introduce `MergeIntoSource` operator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15435)
> refactor: remove `MergeIntoSource` operator

- src/query/functions/src/scalars/map.rs
- src/query/functions/tests/it/scalars/map.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/map.txt
- tests/sqllogictests/suites/query/functions/02_0074_function_map.test
Implement `map_size` function
* Addresses part of #15295
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15444)
> feat(function): Implement map_size function

- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/storages/system/src/processes_table.rs
- tests/sqllogictests/suites/base/06_show/06_0013_show_processlist.test
add created_time column to processes table
- Fixes #15447
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15448)
> feat(query): add created_time column to processes table

- scripts/setup/rust-toolchain.toml
This PR will bump our rust version to `2024-02-08`, ths same commit to rust 1.78 to make  https://github.com/datafuselabs/databend/pull/15426 happy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15455)
> ci: Bump version to 2024-02-08 (the same commit with 1.78)

- src/query/storages/fuse/src/operations/read/runtime_filter_prunner.rs
* Change the flood log level from `info` to `debug`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15473)
> chore: change flood info log to debug

- src/query/service/src/interpreters/interpreter_select.rs
- src/query/service/src/servers/http/v1/query/execute_state.rs
- src/query/service/src/spillers/spiller.rs
- src/query/sql/src/planner/plans/copy_into_table.rs
* Remove breakline for some info logs, this will show the full log messages in the grafana.
* Remove some logs with query_id prefix. After the pull request https://github.com/datafuselabs/databend/pull/15466 , there's no need to manually add the query_id prefix to the log; it will be done automatically.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15476)
> chore: remove breakline for log

- src/query/ee/src/storages/fuse/operations/handler.rs
- src/query/ee/src/storages/fuse/operations/vacuum_drop_tables.rs
- src/query/ee/tests/it/storages/fuse/operations/vacuum.rs
- src/query/ee_features/vacuum_handler/src/vacuum_handler.rs
- src/query/service/src/interpreters/interpreter_vacuum_drop_tables.rs
feat: optimize vacuum drop table, execute in parallel
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15478)
> feat: optimize vacuum drop table, execute in parallel

- src/common/tracing/src/loggers.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/page_manager.rs
- src/query/service/src/sessions/query_ctx.rs
* `... INFO databend_query::sessions::query_ctx: src/query/service/src/sessions/query_ctx.rs:410 xx` to `...  INFO databend_query::sessions::query_ctx: query_ctx.rs:410 xx`
* remove some query_id from logs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15487)
> chore: log file_name name for short

- src/query/service/src/sessions/session.rs
- src/query/service/src/sessions/session_ctx.rs
- src/query/service/src/sessions/session_info.rs
- src/query/service/src/sessions/session_mgr.rs
- src/query/service/src/sessions/session_privilege_mgr.rs
Embrace idiomatic Rust practices by reducing unnecessary sharing. In
this case, since `SessionContext` is not shared among threads, there is
no need to wrap it in an `Arc`. This change streamlines the code and
enhances performance by eliminating unneeded atomic reference counting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15491)
> refactor: `SessionContext` doesn't require `Arc`

- src/query/functions/README.md
- src/query/functions/src/scalars/map.rs
- src/query/functions/tests/it/scalars/map.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/map.txt
- tests/sqllogictests/suites/query/functions/02_0074_function_map.test
- Addresses part of https://github.com/datafuselabs/databend/issues/15295
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15465)
> feat(functions): add map_contains_key scalar function

- scripts/setup/dev_setup.sh
Need this in #15494 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15501)
> feat(query): build image limit python 3.12.2

- src/common/storage/src/operator.rs
After opendal 0.46, io_timeout represents for a whole read request of nearly 4MiB, we should increase the io timeout to allow possible io idle time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15493)
> chore: Increase default io timeout for behavior changes

- src/query/storages/stage/src/read/row_based/formats/ndjson/block_builder.rs
- tests/sqllogictests/suites/stage/formats/ndjson/ndjson_on_error.test
The origin JSON error format "{} at line {} column {}" is misleading for NDJSON in DB context.
- rm `line {}`
- rename `column {}` to `pos {}`, 1-based to 0 based
- add info for size and next byte
Use test in case of changes of serde_json.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15502)
> chore: polish error message  NDJSON.

- .github/workflows/build_tool.yml
- scripts/setup/dev_setup.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15512)
> feat(query): pyenv 3.12.2

- src/query/catalog/src/table_context.rs
- src/query/service/src/pipelines/builders/builder_recluster.rs
- src/query/service/src/pipelines/builders/builder_sort.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/src/sessions/query_ctx_shared.rs
- src/query/service/tests/it/sql/exec/get_table_bind_test.rs
- src/query/service/tests/it/storages/fuse/operations/commit.rs
- src/query/settings/src/settings_default.rs
- src/query/storages/fuse/src/operations/mutation/mutator/recluster_mutator.rs
- tests/suites/1_stateful/02_query/02_0006_set_priority.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15490)
> chore: recluster disable sort spill

- src/query/settings/src/settings_default.rs
* `load_file_metadata_expire_hours` now is 12 hours
* For optimal COPY operations, it is recommended to use the following syntax: `COPY INTO <table> FROM FILES = ('file1', 'file2')`, no need s3 list. https://docs.databend.com/sql/sql-commands/dml/dml-copy-into-table#files
- Fixes #15500
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15514)
> chore: change load_file_metadata_expire_hours default from 24*7 to 12 hours

- src/query/ee/src/storages/fuse/io/snapshots.rs
- src/query/ee/src/storages/fuse/operations/vacuum_drop_tables.rs
- src/query/ee/src/storages/fuse/operations/vacuum_table.rs
- src/query/service/src/catalogs/default/mutable_catalog.rs
- src/query/service/src/interpreters/interpreter_table_recluster.rs
- src/query/storages/fuse/src/io/snapshots.rs
- src/query/storages/fuse/src/operations/analyze.rs
- src/query/storages/fuse/src/operations/changes.rs
- src/query/storages/fuse/src/operations/common/processors/sink_commit.rs
- src/query/storages/fuse/src/operations/common/processors/transform_mutation_aggregator.rs
- src/query/storages/fuse/src/operations/gc.rs
- src/query/storages/fuse/src/operations/mutation/mutator/block_compact_mutator.rs
- src/query/storages/fuse/src/operations/mutation/mutator/segment_compact_mutator.rs
- src/query/storages/fuse/src/operations/mutation/processors/recluster_aggregator.rs
- src/query/storages/fuse/src/operations/read_partitions.rs
- src/query/storages/fuse/src/operations/recluster.rs
- src/query/storages/parquet/src/parquet_rs/parquet_table/table.rs
- adjust the time part in the log to use `Duration` instead of specific precision time (e.g., seconds), to avoid imprecise log information such as '0s'.
- add timing log of some schema api
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15517)
> chore: adjust elapsed time of various log messages

- src/common/storage/src/operator.rs
opendal's backtrace output is not enabled, makes it hard to debug opendal related issues.
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15521)
> fix: Enable opendal backtrace output to help debug

- Cargo.lock
- src/binaries/Cargo.toml
- src/binaries/meta/entry.rs
- src/binaries/query/entry.rs
- src/common/metrics/src/lib.rs
- src/common/metrics/src/metrics/system.rs
- src/meta/service/src/metrics/meta_metrics.rs
- src/meta/service/src/version.rs
- src/query/config/src/lib.rs
- src/query/config/src/version.rs
```
❯ curl localhost:28002/v1/metrics
metasrv_server_version{component="metasrv",semver="v1.2.466-nightly",sha="e35722e0a5"} 1
```
```
❯ curl localhost:7070/metrics
databend_system_version{component="query",semver="v1.2.466-nightly",sha="e35722e0a5"} 1
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15522)
> feat: add version metrics for meta & query

- src/query/ast/src/ast/format/ast_format.rs
- src/query/ast/src/ast/visitors/visitor.rs
- src/query/ast/src/ast/visitors/walk.rs
- tests/sqllogictests/suites/mode/standalone/explain/explain.test
fix `explain ast  insert first/all`.
before this PR, explain ast of multiple table insert stmt panics, with this PR:
~~~
query T
EXPLAIN AST
INSERT FIRST
WHEN order_amount > 1000 THEN INTO cat.db1.t1(order_id, update_note) VALUES (order_id, 'PriorityHandling')
WHEN order_amount > 500 THEN INTO cat2.db2.t2 VALUES (order_id, 'ExpressHandling')
WHEN order_amount > 100 THEN
INTO cat3.db3.t3 VALUES (order_id, 'StandardHandling')
INTO cat3.db3.t4 VALUES (order_id, 'StandardHandling')
ELSE INTO processing_updates VALUES (order_id, 'ReviewNeeded')
SELECT order_id, order_amount FROM orders_placed;
----
INSERT FIRST (children 5)
├── WHEN (children 2)
│   ├── Function > (children 2)
│   │   ├── …
> fix: `explain ast` of  multi table insert stmt

- src/bendpy/src/context.rs
- src/query/ee/src/background_service/background_service_handler.rs
- src/query/ee/src/background_service/session.rs
- src/query/ee/src/storage_encryption/handler.rs
- src/query/ee/src/storage_quota/handler.rs
- src/query/service/src/auth.rs
- src/query/service/src/local/executor.rs
- src/query/service/src/servers/admin/v1/cluster.rs
- src/query/service/src/servers/flight/v1/flight_service.rs
- src/query/service/src/servers/flight_sql/flight_sql_service/session.rs
- src/query/service/src/servers/http/middleware.rs
- src/query/service/src/servers/mysql/mysql_handler.rs
- src/query/service/src/sessions/query_ctx_shared.rs
- src/query/service/src/sessions/session.rs
- src/query/service/src/sessions/session_ctx.rs
- src/query/service/src/sessions/session_mgr.rs
- src/query/service/src/test_kits/fixture.rs
- src/query/service/tests/it/auth.rs
- src/query/service/tests/it/sessions/session.rs
Due to the design principle that `SessionContext::current_tenant` should
not be modified at runtime, this commit transitions
`SessionContext::current_tenant` from a shared `RwLock<Option<Tenant>>`
to a non-shared `Option<Tenant>`.
Additionally, the process of constructing a `Session` has been divided
into two distinct steps:
1. Initially build an instance and set up initial values, including
`current_tenant`.
2. Convert the `Session` instance into a readonly `Arc<Session>` to
facilitate sharing across `QueryContext` and other components.
Other Changes:
- Methods of `Session` are now bound to `&self` instead of `&Arc<Self>`.
- The method `SessionCtx::set_current_tenant()` has been made private …
> refactor: `SessionContext::current_tenant` should not be changed at runtime

- Cargo.lock
- Cargo.toml
Updates the `minitrace` and `minitrace-opentelemetry` crate versions to `0.6.5` and removes the patch section for these crates in `Cargo.toml`.
- Updates the `minitrace` crate version to `0.6.5` and includes the `enable` feature.
- Updates the `minitrace-opentelemetry` crate version to `0.6.5`.
- Removes the previously specified git patch for both `minitrace` and `minitrace-opentelemetry` from the `[patch.crates-io]` section, aligning with the task to use the crates.io versions directly.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/datafuselabs/databend?shareId=879dc329-34ca-402e-add8-9d8310d6bc0b).
- - - …
> chore: Upgrade minitrace related crates to 0.6.5

- src/meta/raft-store/src/sm_v002/mod.rs
- src/meta/raft-store/src/sm_v002/writer_v002.rs
- src/meta/service/src/store/store_inner.rs
Prior to this commit, the snapshot writer would attempt to commit the
snapshot upon closure of the input channel, operating under the
assumption that the snapshot was fully written. This assumption is
flawed as the closure of the channel might be due to a process shutdown,
not completion of the snapshot.
To address this issue, this commit introduces a change where items sent
to the snapshot writer are encapsulated within a `WriteEntry`, which can
be either `Data(T)` or `Commit`. The snapshot is only considered
complete and ready for commit when a `Commit` variant is received. This
adjustment ensures that premature snapshot commits are avoided in cases
of early channel closures.
- - -
This …
> fix: Prevent premature snapshot commit on unfinished writes

- Cargo.lock
- src/query/storages/stage/Cargo.toml
- src/query/storages/stage/src/read/row_based/format.rs
- src/query/storages/stage/src/read/row_based/formats/tsv/block_builder.rs
- src/query/storages/stage/src/read/row_based/formats/tsv/format.rs
- src/query/storages/stage/src/read/row_based/formats/tsv/mod.rs
- src/query/storages/stage/src/read/row_based/formats/tsv/separator.rs
- src/query/storages/stage/src/stage_table.rs
1.  no longer tries to `read` big TSV in parallel to make it simple and always able to get row id, but still can be deserialized in parallel after cutting into RowBatches.
2.  simplify the handling of skip headers.
3.  minimal reallocating of file data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15506)
> refactor: migrate TSV input format to new framework.

- src/common/storage/src/parquet_rs.rs
- src/query/storages/fuse/src/operations/commit.rs
- src/query/storages/fuse/src/operations/common/processors/sink_commit.rs
instead of purging un-committed data of failed txn, leave them to purge/vacuum
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15535)
> chore: leave all un-committed data to purge/vacuum

- src/meta/service/src/metrics/meta_metrics.rs
- src/meta/service/src/store/store_inner.rs
add new metrics
* metasrv_server_snapshot_key_num
```
❯ curl localhost:28002/v1/metrics
metasrv_server_snapshot_key_num 2873
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15545)
> feat(metasrv): add metrics for snapshot key numbers

- Cargo.lock
- Cargo.toml
- src/binaries/Cargo.toml
- src/common/tracing/Cargo.toml
- src/common/tracing/src/init.rs
- src/meta/service/Cargo.toml
- src/query/service/Cargo.toml
chore: Remove tokio-console since we don't need it
This PR to git rid of different tonic versions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15546)
> chore: Remove tokio-console since we don't need it

- Cargo.lock
- Cargo.toml
- src/tests/sqlsmith/Cargo.toml
Bump databend client and geozero to latest version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15550)
> chore: Bump databend client and geozero to latest version

- Cargo.lock
- Cargo.toml
- src/binaries/Cargo.toml
- src/common/parquet2/Cargo.toml
- src/query/ast/Cargo.toml
- src/query/constraint/Cargo.toml
- src/query/functions/Cargo.toml
- src/query/service/Cargo.toml
- src/query/service/src/local/helper.rs
- src/query/service/src/servers/mysql/tls.rs
- src/query/service/tests/it/servers/mysql/mysql_handler.rs
- src/query/storages/common/index/Cargo.toml
- src/query/storages/fuse/Cargo.toml
This PR will bump rustls to 0.22. The only dep that needs rustls 0.21 is `sentry`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15552)
> chore: Bump rustls to 0.22

- src/query/service/src/sessions/query_ctx_shared.rs
- src/query/service/tests/it/sessions/query_ctx.rs
* Increase the maximum size of short_sql from 64 bytes to 10 kb. Some INSERT MERGE INTO queries can reach several kb in size. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15554)
> chore: change the short_sql from 64bytes to 10KB

- Cargo.lock
- Cargo.toml
- src/query/service/Cargo.toml
- src/query/service/src/servers/flight_sql/flight_sql_service/query.rs
During upgrading bendsql https://github.com/datafuselabs/bendsql/pull/422, I found that databend didn't send valid flightdata for server stats.
This PR fixed this by setting a valid data header instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15559)
> fix: FlightData must contain valid data header

- src/query/service/src/interpreters/interpreter.rs
- tests/sqllogictests/suites/base/01_system/01_0002_system_query_log.test
all success plan should generate hash
https://github.com/datafuselabs/databend/pull/15531/files#diff-5abf95c43975a311470a7a6e3e9aa84d35190852ee611e7923a41eda94ca0902R252-R254
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15560)
> chore(query): all queryies should generate hash

- src/meta/raft-store/src/sm_v002/snapshot_store.rs
- src/meta/types/src/raft_snapshot_data.rs
This commit resolves an issue where duplicate temporary file names were
generated when two install-snapshot requests were received in close
temporal proximity. This could potentially lead to conflicts and
erroneous behavior during snapshot installation.
Changes:
- Added logic to generate unique temporary file names for each
install-snapshot request to prevent naming conflicts.
- Additionally, this commit enhances error handling by including context
information in the `io::Error` returned from `SnapshotStoreV002`. This
improvement aids in better understanding the source and nature of
errors when they occur.
- - - …
> fix: Avoid duplicate temp file name for install-snapshot requests

- Cargo.lock
- src/query/config/src/config.rs
- src/query/config/src/inner.rs
- src/query/config/src/lib.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
- src/query/storages/common/cache/Cargo.toml
- src/query/storages/common/cache/src/providers/disk_cache.rs
- src/query/storages/common/cache/src/providers/table_data_cache.rs
- src/query/storages/common/cache/tests/it/providers/disk_cache.rs
- src/query/storages/common/cache_manager/src/cache_manager.rs
During query node restart, if the config item `data_cache_key_reload_policy` is set to "fuzzy", disk cache keys will be reloaded from the cache directory instead of directly removing previous cache data. This means that the cache data existing before the restart will NOT be deleted.
To accelerate the reloading,  sub directories of cache directory, will be processed in parallel. 
Note that during the reloading of cache keys, cache capacity will NOT be checked. Therefore, if `cache.disk.max_bytes` is decreased between restarts, no cached items on disk will be removed immediately. Instead, items will be removed when the first new item is put into the cache.
If `data_cache_key_reload_policy` is …
> feat: fuzzy table data disk cache key reload

- src/query/service/src/sessions/query_ctx_shared.rs
- src/query/service/tests/it/sessions/query_ctx.rs
* If a insert with many columns, short_sql doesn't have room enough, enlarger it from 10KB to 30 KB
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15575)
> chore: short_sql from 10KB to 30KB

- src/query/storages/common/index/src/bloom_index.rs
- tests/sqllogictests/suites/mode/standalone/explain/bloom_filter.test
- tests/sqllogictests/suites/mode/standalone/explain_native/bloom_filter.test
Ignore the `not`, `is_null` and `is_not_null` functions in bloom filter.
- Fixes #15570
- Fixes #15572
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15577)
> fix(query): fix bloom fitler using `is_null` and `not` function

- src/query/expression/src/filter/select_expr.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0009_01_bloom_in_pruning.test
- tests/sqllogictests/suites/query/filter.test
* fix filter with nested `not` expr return wrong result
* add some tests for bloom filter
- Fixes #15579
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15580)
> fix(query): fix filter with nested `not` expr return wrong result

- Cargo.lock
- scripts/distribution/configs/databend-query.toml
- src/binaries/query/entry.rs
- src/query/storages/common/cache/Cargo.toml
- src/query/storages/common/cache/src/providers/disk_cache.rs
- src/query/storages/common/cache/src/providers/disk_cache/disk_cache.rs
- src/query/storages/common/cache/src/providers/disk_cache/disk_cache_key.rs
- src/query/storages/common/cache/src/providers/disk_cache/disk_cache_lru.rs
- src/query/storages/common/cache/src/providers/disk_cache/mod.rs
- src/query/storages/common/cache/src/providers/mod.rs
- src/query/storages/common/cache/src/providers/table_data_cache.rs
- src/query/storages/common/cache/tests/it/providers/disk_cache.rs
- src/query/storages/common/cache_manager/src/cache_manager.rs
- src/query/storages/delta/Cargo.toml
* Add more unit test for cache restart load
* Refactory the cache reload logic, make the `parallel_scan` both for reset&fuzzy
* Spill `disk_cache.rs` into `disk_cache` dir
* Add `data_cache_key_reload_policy` config description to query.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15576)
> chore: disk cache load refine and reduce the info flood logs

- src/binaries/metactl/snapshot.rs
- src/meta/raft-store/src/key_spaces.rs
- src/meta/raft-store/src/ondisk/mod.rs
- src/meta/raft-store/src/sm_v002/mod.rs
- src/meta/raft-store/src/sm_v002/snapshot_stat.rs
- src/meta/raft-store/src/sm_v002/snapshot_store.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002.rs
- src/meta/raft-store/src/sm_v002/writer_v002.rs
- src/meta/service/src/metrics/meta_metrics.rs
- src/meta/service/src/store/store_inner.rs
This commit introduces several enhancements to the snapshot management
system:
- Improved Progress Logging for Snapshot Building
- **Introduction of `SMEntry`:**
- A new structure, `SMEntry`, has been introduced to represent all
variants of a state-machine record. `RaftStoreEntry` is a supper
set of `SMEntry` that includes both state machine record and log
records.
3. **Asynchronous Snapshot Writing:**
- Added the `spawn_writer_thread()` function to facilitate the
writing of snapshots in a separate thread, thereby improving the
performance.
- - - …
> refactor: Improve logging and snapshot management

- src/query/service/src/servers/mysql/mysql_interactive_worker.rs
- src/query/service/src/servers/mysql/writers/query_result_writer.rs
- tests/sqllogictests/suites/base/14_transaction/14_0004_rollback.test
MySQL implementation did not capture all errors, resulting in transactions not being rolled back when errors occurred.
- Fixes #15584
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15583)
> chore: fix error capture of mulit statement transaction in mysql session

- src/query/service/src/interpreters/common/mod.rs
- src/query/service/src/interpreters/common/stream.rs
- src/query/service/src/interpreters/interpreter_select.rs
- src/query/sql/src/planner/binder/binder.rs
- src/query/sql/src/planner/binder/insert.rs
- tests/sqllogictests/suites/ee/06_ee_stream/06_0002_stream_txn_consume.test
- The consuming (`with consume`) of stream should respect the semantics of transactions: if  transaction is aborted, the stream should roll back to its original state.
- Only the usage of `WITH CONSUME` in queries is allowed. Statements like `INSERT INTO t SELECT * FROM s WITH CONSUME` will fail with errors.
- Fixes #15581
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15582)
> fix: consume stream inside explicit txn

- src/meta/README.md
- src/meta/service/src/meta_service/raft_service_impl.rs
- src/meta/service/src/network.rs
- src/meta/service/src/version.rs
- src/meta/types/proto/meta.proto
- src/meta/types/src/grpc_helper.rs
**Compatibility Changes:**
This commit introduces changes to inter-meta-service compatibility,
although compatibility between databend-query and meta-service
remains unaffected.
**Details:**
- The initial snapshot transmission API, `install_snapshot` (v0), has
been removed from both the meta server and meta client sides.
- For clients, the use of `install_snapshot_v1()` transitions from
**OPTIONAL** to **REQUIRED**.
**Version Requirements:**
- Post this commit, the meta-server requires clients to be at least
version `1.2.212`, starting from which the clients began using
`install_snapshot_v1()`.
- Similarly, clients require the server to be at least version
`1.2.212`, which is the version where …
> refactor: Remove `install_snapshot` v0 meta-service API

- src/meta/raft-store/src/config.rs
- src/meta/service/src/configs/outer_v0.rs
- src/meta/service/src/meta_service/meta_leader.rs
- src/meta/service/src/meta_service/meta_node.rs
This commit introduces several optimizations and changes to the
meta-service cluster management:
- **Disallow Removing the Leader Directly:**
- It is now disallowed to remove the leader from the cluster directly,
because when leader is removed, the second step of removing a node can not be finished soon.
To properly remove a leader, the leader node should be shut down first.
After a new leader is established, use the command
`databend-meta --leave-id <old-leader-node-id> --leave-via <new-leader-node-raft-address>`
to remove the old leader from the cluster.
Now removing a leader resulted in the error `"can not leave id=<i> via itself"`.
- **Error Collection During Node Removal:**
- Errors that …
> refactor: Enhance Meta-Service Cluster Management

- Cargo.lock
- src/meta/service/src/meta_service/meta_node.rs
- src/meta/service/src/metrics/meta_metrics.rs
- src/meta/service/src/store/store_inner.rs
add metrics
* metasrv_server_db_size
```
❯ curl localhost:28002/v1/metrics
metasrv_server_snapshot_key_num 0
metasrv_server_db_size 2102662
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15595)
> feat(metasrv): add metrics for db_size

- Cargo.lock
- src/query/ee/src/storages/fuse/operations/vacuum_temporary_files.rs
* Add more logs for vaccum temp files in batch and final
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15597)
> chore: add more logs for vacuum temp files

- src/binaries/metactl/snapshot.rs
- src/meta/raft-store/src/key_spaces.rs
- src/meta/raft-store/src/ondisk/mod.rs
- src/meta/raft-store/src/sm_v002/snapshot_stat.rs
- src/meta/raft-store/src/sm_v002/snapshot_store.rs
- src/meta/raft-store/src/sm_v002/writer_v002.rs
- src/meta/service/src/store/store_inner.rs
- src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs
- src/meta/types/src/lib.rs
- src/meta/types/src/raft_snapshot_data.rs
This commit introduces a significant change in the snapshot management
process by separating the snapshot writing and committing phases:
- **Snapshot Writing Update:**
- The `WriterV002::spawn_writer_thread()` function now solely handles
the writing of snapshot data and flushing it to disk. The
responsibility of moving the snapshot from a temporary location to
the final path has been decoupled from this thread.
- **Enhanced Control Over Snapshot Final Path:**
- This change gives the caller more control over how to construct the
final path of the snapshot. For instance:
- When importing data from a previous version on disk, the final
path is constructed using the `last-applied-log-id` found in …
> refactor: Decouple Snapshot Write and Commit Operations

- src/query/service/src/servers/http/v1/query/http_query.rs
which leads to unexpected log like `transaction timeout after 14400 timeout`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15602)
> fix: TxnManager with state AutoCommit should not be saved in http manager.

- src/meta/raft-store/src/sm_v002/leveled_store/immutable.rs
- src/meta/raft-store/src/sm_v002/leveled_store/immutable_levels.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map.rs
- src/meta/raft-store/src/sm_v002/leveled_store/leveled_map_test.rs
- src/meta/raft-store/src/sm_v002/leveled_store/map_api.rs
- src/meta/raft-store/src/sm_v002/leveled_store/mod.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_.rs
- src/meta/raft-store/src/sm_v002/leveled_store/ref_mut.rs
- src/meta/raft-store/src/sm_v002/leveled_store/util.rs
- src/meta/raft-store/src/sm_v002/sm_v002.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002.rs
- src/meta/raft-store/src/sm_v002/snapshot_view_v002_test.rs
Add `ImmutableLevel` as a wrapper for `Arc<Level>`;
Rename corresponding fields
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15608)
> chore: Refine state machine v002

- src/query/sql/src/evaluator/cse.rs
- src/query/sql/src/planner/optimizer/decorrelate/subquery_rewriter.rs
- tests/sqllogictests/suites/udf_server/udf_server_test.test
fix subquery writer in udf
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15610)
> fix(query): fix subquery writer in udf

- src/query/service/src/interpreters/interpreter_table_analyze.rs
- src/query/service/tests/it/storages/fuse/operations/table_analyze.rs
The old snapshot does not have a `prev_table_seq`. During the execution of `ANALYZE TABLE`, it may result in the error: "The stream navigation at point has no table version".
To avoid this error, the program will check if `prev_table_seq` exists. If it does not, it will use a full analyze.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15614)
> fix: analyze table error

- src/query/service/src/interpreters/interpreter_txn_commit.rs
- src/query/storages/fuse/src/operations/common/processors/multi_table_insert_commit.rs
- src/query/storages/fuse/src/operations/common/processors/sink_commit.rs
more logs for commit actions, which logs the table/stream id, version, engine when txn is done (succ or failed).
There are duplicated code snippets. Let's address this later by refactoring to unify the updating of tables/streams and various commit paths.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15617)
> chore: more commit logs

- Cargo.lock
- Cargo.toml
This is a fix for https://github.com/nikis05/derive-visitor/issues/16. The solution pr is pending for review: https://github.com/nikis05/derive-visitor/pull/17.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15625)
> fix: update derive-vistor to unblock rustc upgrage

- src/query/service/src/sessions/query_ctx_shared.rs
- src/query/service/tests/it/sessions/query_ctx.rs
* the insert sql maybe very larger to kb, this pr reduce it to 128bytes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15626)
> chore: reduce the short_sql to 128bytes

- src/query/service/src/servers/http/v1/json_block.rs
- src/query/service/src/servers/http/v1/query/page_manager.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- Fixe   error "expect /final from client, got /page/0"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15624)
> fix: allow http client retry when lost response with next_uri=/final.

- src/common/tracing/src/loggers.rs
chore(query): add timeout for open telemetry logger
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15627)
> chore(query): add timeout for open telemetry logger

- Cargo.lock
- src/common/base/Cargo.toml
- src/common/base/src/base/mod.rs
- src/common/base/src/base/string.rs
- src/common/base/tests/it/string.rs
- src/query/service/Cargo.toml
- src/query/service/src/interpreters/interpreter.rs
- src/query/service/src/servers/http/clickhouse_handler.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/sessions/mod.rs
- src/query/service/src/sessions/query_ctx_shared.rs
- src/query/service/tests/it/sessions/query_ctx.rs
* spill out `short_sql` to `common/base/src/string.rs`
* Simple short_sql and add more unicode tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15633)
> chore: spill out short_sql to common/base/src/string.rs

- Cargo.lock
- Cargo.toml
- src/binaries/meta/entry.rs
- src/binaries/query/entry.rs
- src/common/tracing/src/config.rs
- src/common/tracing/src/init.rs
- src/common/tracing/src/lib.rs
- src/common/tracing/src/loggers.rs
- src/query/config/Cargo.toml
- src/query/config/src/config.rs
- src/query/service/tests/it/storages/testdata/configs_table_basic.txt
- add HTTP Binary protocol support for `OpenTelemetry` logger
- switch to batch exporter for `OpenTelemetry` logger
- flush all loggers when query shutdown
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15636)
> feat: otlp logging support http endpoint

- src/common/tracing/src/init.rs
- src/common/tracing/src/loggers.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15639)
> fix: missing service label for otlp logs

- src/meta/api/src/schema_api_impl.rs
- tests/sqllogictests/suites/base/05_ddl/05_0017_ddl_grant_role.test
delete some err check
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15640)
> fix(query): delete len check in mget_database/table_names_by_ids

- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/storages/fuse/src/operations/mutation/mod.rs
- src/query/storages/fuse/src/operations/mutation/mutator/block_compact_mutator.rs
**Key Features**:
1. Introduces the `compact_max_block_selection` setting.
2. Ensures compact operations respect this limit, enhancing control over resource usage and performance.
This setting allows users to manage and optimize compact operations more effectively by preventing the selection of an excessive number of blocks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15641)
> chore: add setting compact_max_block_selection

- src/query/expression/src/utils/udf_client.rs
currently on connectivity issues, all what we get is "transport error."
there must be some more infomation about the root cause behind it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15646)
> fix(udf): use Debug to display transport error on UDF server

- src/query/sql/src/planner/binder/bind_query/bind.rs
- src/query/sql/src/planner/binder/bind_query/bind_select.rs
- src/query/sql/src/planner/binder/bind_query/bind_set_expr.rs
- src/query/sql/src/planner/binder/bind_table_reference/bind_table_function.rs
- src/query/sql/src/planner/binder/select.rs
- src/query/sql/src/planner/plans/operator.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15648)
> refactor: refine cast reloperator error info
