- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/merge_into_hash_join_optimization.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_spill/mod.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_spill/transform_probe_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- tests/sqllogictests/suites/query/spill/basic_spill.test
Make spilled-related logic as independent as possible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14743)
> refactor: refactor hash join spill probe side

- docker/build-tool/alpine/Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14764)
> chore(ci): fix LIBCLANG_PATH for alpine build-tool

- src/query/functions/src/cast_rules.rs
- tests/sqllogictests/suites/query/02_function/02_0005_function_compare.test
- tests/sqllogictests/suites/query/02_function/02_0045_conditional_function_in.test
support string eq int
- Fixes #14756
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14759)
> chore(query): support string eq int

- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/mod.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/transform_build_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_spill/transform_probe_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- src/query/service/src/spillers/spiller.rs
- tests/sqllogictests/suites/query/spill/basic_spill.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14768)
> refactor: hash join build spilling

- .github/workflows/cloud.yml
- .github/workflows/release.yml
- .github/workflows/reuse.linux.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14773)
> chore: fix build for cloud

- src/query/service/src/pipelines/builders/builder_join.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_coordinator.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/transform_build_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/sql/src/planner/optimizer/optimizer.rs
- tests/sqllogictests/suites/query/spill/basic_spill.test
- Fixes #14771 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14781)
> refactor: refactor join spilling settings

- .github/release-report.jq
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14785)
> chore(ci): fix target for release

- docker/build-tool/musl/Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14790)
> chore: fix musl build dockerfile

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14791)
> chore: release add musl targets

- src/query/sql/src/planner/binder/merge_into.rs
rename merge into variable: `update_columns_star ` to `update_or_insert_columns_star `.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14806)
> chore: rename update_star_columns

- src/common/base/src/runtime/runtime_tracker.rs
- src/common/base/tests/it/memory/mem_stat.rs
- src/common/base/tests/it/memory/mod.rs
chore(query): add unit test for mem stat
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14812)
> chore(query): add unit test for mem stat

- .github/actions/artifact_failure/action.yml
- .github/actions/artifact_upload/action.yml
- .github/actions/benchmark_cloud/action.yml
- .github/actions/benchmark_local/action.yml
- .github/workflows/bindings.python.yml
- .github/workflows/links.yml
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14820)
> chore(ci): include nohup.out in failure artifact

- Cargo.lock
- src/query/ast/src/ast/statements/udf.rs
- src/query/sql/Cargo.toml
- src/query/sql/src/planner/binder/copy_into_table.rs
- src/query/sql/src/planner/binder/ddl/view.rs
- src/query/sql/src/planner/binder/select.rs
- src/query/sql/src/planner/semantic/view_rewriter.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14823)
> fix(ast): add missing #[drive(skip)]

- .github/workflows/dev.yml
- .github/workflows/production.yml
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14834)
> chore(ci): fix release artifacts conflict

- .github/actions/benchmark_cloud/action.yml
- .github/actions/benchmark_local/action.yml
- .github/workflows/release.yml
- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14837)
> chore(ci): fix artifacts for benchmark

- src/meta/kvapi/src/kvapi/test_suite.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14836)
> chore: tolerate inaccuracy of expire time for test

- tests/sqllogictests/suites/ee/01_ee_system/01_0003_stream.test
https://github.com/datafuselabs/databend/actions/runs/8159193155/job/22303705960#step:5:285
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14848)
> fix: flaky sqllogic test

- tests/suites/1_stateful/00_stage/00_0003_copy_with_max_files_parquet.result
- tests/suites/1_stateful/00_stage/00_0003_copy_with_max_files_parquet.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14855)
> ci: fix clippy tests.

- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/transform_build_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_spill/probe_spill_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_spill/transform_probe_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/spill_common.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- tests/sqllogictests/suites/spill/right_join_spill.test
- Part of #14732 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14853)
> feat: support right-related join spilling

- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/transform_build_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_spill/transform_probe_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/spillers/spiller.rs
- tests/sqllogictests/suites/spill/left_join_spill.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14860)
> fix: fix wrong results for left join spilling

- src/query/management/src/stage/stage_mgr.rs
- src/query/management/tests/it/stage.rs
- src/query/service/src/interpreters/common/grant.rs
- src/query/service/src/interpreters/interpreter_user_stage_create.rs
- src/query/service/src/interpreters/interpreter_user_stage_drop.rs
- src/query/service/src/servers/http/v1/stage.rs
- src/query/sql/src/planner/binder/copy_into_table.rs
- src/query/storages/system/src/stages_table.rs
- src/query/users/src/user_api.rs
- src/query/users/src/user_stage.rs
- Part of #14849
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14850)
> refactor: use NonEmptyString for creating StageMgr

- src/meta/service/tests/it/grpc/metasrv_grpc_kv_read_v1.rs
- Fix: #14857
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14868)
> chore: improve tolerance for expire test `test_kv_read_v1_on_follower`

- scripts/ci/deploy/config/databend-query-node-1.toml
- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/transform_build_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/mod.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- tests/sqllogictests/suites/mode/cluster/merge_into_non_equal_distributed.test
- tests/sqllogictests/suites/mode/standalone/explain/09_0039_target_build_merge_into_standalone.test
- tests/sqllogictests/suites/mode/standalone/explain/merge_into.test
- Part of #14732 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14843)
> chore: open join spilling by default

- src/query/management/src/stage/stage_mgr.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14871)
> refactor: use KVPbApi to simplify StageMgr

- src/meta/service/tests/it/meta_node/meta_node_kv_api_expire.rs
- Fix: #14879
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14880)
> chore: increase tolerance for expiration test

- benchmark/clickbench/benchmark_local.sh
- benchmark/clickbench/internal/load.sh
* Fix release ci err, because of https://github.com/datafuselabs/databend/pull/14862
* Use a created user a to test rbac benchmark.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14897)
> fix(ci): fix internal benchmark

- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/transform_build_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_spill/transform_probe_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/spill_common.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- src/query/service/src/spillers/spiller.rs
- tests/sqllogictests/suites/spill/cross_join.test
- part of #14732 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14887)
> feat: support cross join spilling

- Cargo.lock
- src/query/ast/src/ast/statements/table.rs
- src/query/ast/tests/it/testdata/statement.txt
- Fixes #14913
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14914)
> fix: Display of compact AST

- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/transform_build_spill.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14919)
> refactor: reduce hash join build spilling files

- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/transform_build_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_spill/transform_probe_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
- src/query/service/src/pipelines/processors/transforms/transform_sort_spill.rs
- src/query/service/src/spillers/spiller.rs
- src/query/service/tests/it/spillers/spiller.rs
- tests/sqllogictests/suites/spill/left_join_spill.test
- tests/sqllogictests/suites/spill/right_join_spill.test
Add step logs for hash join build side, if there is hang in the future, we can debug by the log.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14930)
> chore: add step logs for hash join build side

- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/json_block.rs
- src/query/service/src/servers/http/v1/query/execute_state.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/page_manager.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- src/query/service/tests/it/servers/http/json_block.rs
because query let querying stage may spend a lot time in binding, which is not friendly for http clients.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14908)
> refactor: http handler plan sql async.

- .github/workflows/merge_group.yml
- .github/workflows/pr.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14944)
> chore(ci): add pr summary check

- .github/workflows/pr.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14946)
> chore(ci): fix set failure for pr check

- .github/workflows/pr.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14947)
> chore(ci): fix description check

- .github/workflows/pr.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14948)
> chore(ci): fix event for pr assistant

- src/query/expression/src/kernels/topk.rs
- src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs
Improve `push_column_with_selection` to avoid `Bitmap` overhead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14954)
> chore(query): improve push_column_with_selection

- src/query/service/src/databases/system/system_database.rs
chore(query): add disable system tables
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14958)
> chore(query): add disable system tables

- src/query/ast/src/parser/statement.rs
- src/query/ast/src/parser/token.rs
- tests/sqllogictests/suites/base/14_transaction/14_0003_merge_into.test
Add an optional "TRANSACTION" clause, for the `begin` statement:
~~~
begin [transaction]
~~~
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14960)
> chore: tweak txn syntax

- src/query/service/src/api/http/v1/settings.rs
chore(query): add settings level for admin api
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14967)
> chore(query): add settings level for admin api

- src/query/functions/src/aggregates/aggregate_histogram.rs
- src/query/sql/src/planner/semantic/type_check.rs
- relative pr https://github.com/datafuselabs/databend/pull/14839
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14976)
> chore: improve histogram‘s implement and comments

- src/query/ast/src/parser/statement.rs
- tests/sqllogictests/suites/base/05_ddl/05_0003_ddl_alter_table.test
support parse mulity `modify column? ty`
- Fixes #14898
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14979)
> feat(query): support parse mulity `modify column? ty`

- .github/workflows/reuse.benchmark.yml
- benchmark/clickbench/update_results.py
> chore: fix sql seq for benchmark report

- .github/actions/benchmark_cloud/action.yml
- benchmark/clickbench/benchmark_cloud.sh
- benchmark/clickbench/benchmark_local.sh
> chore: print query detail for bench & fix prepare database for load bench

- src/meta/app/src/schema/database.rs
- src/meta/app/src/schema/table.rs
- src/meta/app/src/share/share.rs
> refactor: remove innecessary serde

- .github/workflows/cloud.yml
- .github/workflows/reuse.benchmark.yml
- benchmark/clickbench/benchmark_cloud.sh
- benchmark/clickbench/benchmark_local.sh
> chore: run load test with new label

- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/transform_build_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_spill/transform_probe_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- src/query/service/src/spillers/mod.rs
- src/query/service/src/spillers/spiller.rs
- src/query/service/src/spillers/spiller_buffer.rs
- Fixes https://github.com/datafuselabs/databend/issues/14963
> feat: add buffer for spiller

- src/query/service/src/pipelines/processors/transforms/transform_sort_spill.rs
- src/query/service/src/spillers/spiller.rs
chore(query): add spill profile for join
> chore(query): add spill profile for join

- src/query/storages/stage/src/read/row_based/processors/reader.rs
I mistakenly create new reader for each batch when refactoring（it is one reader for each split in the origin imply）
> refactor: spead up csv reader.

- src/query/pipeline/sources/src/input_formats/impls/input_format_csv.rs
- src/query/settings/src/settings_default.rs
reason: 
https://github.com/datafuselabs/databend/issues/14973
https://github.com/datafuselabs/databend/pull/14983
fix  a small bug about row id (shown in error msg) by the way.
> fix: wrong row id

- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/transform_build_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_spill/transform_probe_spill.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs
- src/query/service/src/spillers/spiller.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14942)
> refactor: reduce hash join probe spilled files

- src/meta/api/src/schema_api_impl.rs
- src/meta/app/src/schema/catalog.rs
- src/meta/app/src/schema/mod.rs
- src/query/catalog/src/catalog/manager.rs
- src/query/service/src/interpreters/interpreter_catalog_create.rs
- src/query/sql/src/executor/physical_plans/physical_commit_sink.rs
> refactor: remove serde from CatalogId and CatalogNameIdent

- src/query/sql/src/planner/binder/table.rs
- tests/sqllogictests/suites/base/issues/issue_13718.test
- Fixes https://github.com/datafuselabs/databend/issues/13718
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14663)
> fix: improve error hints when select * from xx.yy

- src/common/storage/src/stage.rs
- src/query/catalog/src/plan/datasource/datasource_info/stage.rs
- src/query/service/src/interpreters/interpreter_user_stage_remove.rs
- src/query/service/src/table_functions/list_stage/list_stage_table.rs
- src/query/sql/src/planner/binder/copy_into_table.rs
- src/query/sql/src/planner/plans/copy_into_table.rs
- src/query/storages/parquet/src/parquet_rs/parquet_table/partition.rs
- src/query/storages/parquet/src/parquet_rs/parquet_table/table.rs
- src/query/storages/stage/src/input_context_bridge.rs
- src/query/storages/stage/src/stage_table.rs
Implement concurrent stat to speedup the list files.
fix https://github.com/datafuselabs/databend/issues/15082
> feat: Implement concurrent stat

- src/meta/service/src/metrics/meta_metrics.rs
> feat(metasrv): add network metrics rpc_delay_ms

- src/query/sql/src/planner/binder/merge_into.rs
- src/query/sql/src/planner/plans/merge_into.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0033_distributed_merge_into_without_enable.test
- tests/sqllogictests/suites/base/09_fuse_engine/09_0034_pr13848_without_distributed_enable.test
- tests/sqllogictests/suites/base/09_fuse_engine/09_0036_merge_into_without_distributed_enable.test
- tests/sqllogictests/suites/base/09_fuse_engine/09_0037_target_build_merge_into_without_distributed_enable.test
> chore: remove rebinding merge into for insert-only

- Makefile
> chore: clean z3 and meta dir

- tests/sqllogictests/suites/query/window_function/named_window_basic.test
schema mismatch in `named_window_basic.test`.
> fix: schema mismatch in `named_window_basic.test`

- src/query/service/src/pipelines/executor/executor_graph.rs
- src/query/service/src/pipelines/executor/executor_settings.rs
- src/query/service/src/pipelines/executor/executor_worker_context.rs
- src/query/service/src/pipelines/executor/pipeline_complete_executor.rs
- src/query/service/src/pipelines/executor/pipeline_executor.rs
- src/query/service/src/pipelines/executor/pipeline_pulling_executor.rs
- src/query/service/src/pipelines/executor/pipeline_pushing_executor.rs
- src/query/service/src/pipelines/executor/queries_pipeline_executor.rs
- src/query/service/src/pipelines/executor/query_pipeline_executor.rs
- src/query/service/tests/it/pipelines/executor/executor_graph.rs
- src/query/service/tests/it/pipelines/executor/pipeline_executor.rs
**This PR should not affect currently used executor**
1. Move the logic related to specific queries from QueriesPipelineExecutor to PipelineExecutor
2. Add functionality to Graph for interrupting its execution; Executor should not terminate after Graph completion
3. Modify the logic for creating Graph in PipelineExecutor to prepare for future conversion to Server/Client mode
**Not ready to review. Still work in progress:**
1. refine error handle
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14965)
> refactor(executor): refactor queries executor to prepare

- Cargo.lock
- src/query/formats/src/field_decoder/json_ast.rs
- src/query/storages/stage/Cargo.toml
- src/query/storages/stage/src/lib.rs
- src/query/storages/stage/src/read/row_based/batch.rs
- src/query/storages/stage/src/read/row_based/format.rs
- src/query/storages/stage/src/read/row_based/formats/csv/block_builder.rs
- src/query/storages/stage/src/read/row_based/formats/csv/separator.rs
- src/query/storages/stage/src/read/row_based/formats/ndjson/block_builder.rs
- src/query/storages/stage/src/read/row_based/formats/ndjson/format.rs
- src/query/storages/stage/src/read/row_based/formats/ndjson/mod.rs
- src/query/storages/stage/src/read/row_based/formats/ndjson/separator.rs
- src/query/storages/stage/src/read/row_based/processors/block_builder.rs
- src/query/storages/stage/src/read/row_based/processors/separator.rs
- src/query/storages/stage/src/stage_table.rs
- tests/sqllogictests/suites/stage/formats/ndjson/ndjson_select.test
see https://github.com/datafuselabs/databend/pull/14645
this ndjson loader use 
1. new pipeline (who used to have performance issue but sovled)
1. new separator (cut file to rows),  faster (but not expected speed up overall time, ), with unit tests 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/14943)
> feat: refactor ndjson input format.

- src/meta/api/src/share_api_impl.rs
- src/meta/api/src/share_api_test_suite.rs
- src/meta/api/src/util.rs
- src/meta/app/src/app_error.rs
- src/meta/app/src/share/mod.rs
- src/meta/app/src/share/share.rs
- src/meta/app/src/share/share_end_point_ident.rs
- src/meta/proto-conv/src/share_from_to_protobuf_impl.rs
- src/query/service/src/interpreters/interpreter_share_endpoint_show.rs
- src/query/sharing/src/share_endpoint.rs
- src/query/sql/src/planner/binder/ddl/share.rs
- src/query/sql/src/planner/plans/share.rs
> refactor: define ShareEndpointIdent with TIdent

- src/meta/service/src/network.rs
> refactor: add peer info to network error context

- src/meta/api/src/share_api_impl.rs
- src/meta/api/src/share_api_test_suite.rs
- src/meta/api/src/util.rs
- src/meta/app/src/share/share.rs
- src/meta/app/src/tenant/tenant.rs
> refactor: add Tenant to ShareConsumer

- src/query/ast/src/ast/format/ast_format.rs
- src/query/ast/src/ast/format/syntax/ddl.rs
- src/query/ast/src/ast/query.rs
- src/query/ast/src/ast/visitors/walk.rs
- src/query/ast/src/ast/visitors/walk_mut.rs
- src/query/ast/src/parser/query.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/query.txt
- src/query/expression/src/type_check.rs
- src/query/sql/src/planner/binder/table.rs
- tests/sqllogictests/suites/base/12_time_travel/12_0004_time_travel_select_at.test
- tests/suites/0_stateless/12_time_travel/12_0004_time_travel_select_at.result
- tests/suites/0_stateless/12_time_travel/12_0004_time_travel_select_at.sh
```sql
SELECT ...
FROM ...
{
AT( { TIMESTAMP => <timestamp> | OFFSET => <time_difference> | SNAPSHOT => '<sid>' | STREAM => '<name>' } )
}
[ ... ]
```
**OFFSET => <time_difference>**
This parameter defines the time offset for Time Travel, specifying the number of seconds to go back from the current time. It should be in the form of `-N`, where `N` is an integer or an arithmetic expression representing the time difference in seconds. For example, `-60` denotes a travel of 60 seconds into the past, and `-60*60` represents a 1-hour(3600 seconds)  travel back in time.
```
Query OK, 0 rows affected (0.04 sec)
Query OK, 1 row affected …
```
> feat: time travel support at offset

- Cargo.lock
- Cargo.toml
reqsign doesn't handle list objects correctly that could trigger 403 errors if prefix contains upper cases. This PR fixed it.
>  fix(query): Signature not match while query has upper cases

- src/query/service/src/interpreters/interpreter_explain.rs
- src/query/sql/src/planner/format/display_plan.rs
- tests/sqllogictests/suites/mode/cluster/merge_into_non_equal_distributed.test
- tests/sqllogictests/suites/mode/standalone/explain/09_0039_target_build_merge_into_standalone.test
- tests/sqllogictests/suites/mode/standalone/explain/merge_into.test
Refactor explain merge into , collecting explain info after physical plan building
> refactor: explain merge into

- Cargo.lock
- Cargo.toml
- src/query/expression/Cargo.toml
- src/query/formats/Cargo.toml
- src/query/functions/Cargo.toml
> fix: geos-sys compile error #15200

- src/query/service/src/interpreters/interpreter.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/mysql/mysql_interactive_worker.rs
parser error need to log error
- Fixes #15213
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15219)
> chore(query): parser error need to log error

- src/query/service/src/sessions/queue_mgr.rs
fix(query): fix negative session_running_acquired_queries
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15223)
> fix(query): fix negative session_running_acquired_queries

- src/query/catalog/src/table_context.rs
- src/query/service/src/interpreters/common/query_log.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/src/sessions/query_ctx_shared.rs
- src/query/service/src/sessions/queue_mgr.rs
- src/query/service/tests/it/sql/exec/get_table_bind_test.rs
- src/query/service/tests/it/storages/fuse/operations/commit.rs
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/storages/system/src/query_log_table.rs
chore(query): add query queued duration for query log
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15225)
> chore(query): add query queued duration for query log

- src/meta/api/src/schema_api.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/schema/table.rs
- src/meta/kvapi/src/kvapi/key.rs
- src/meta/kvapi/src/kvapi/key_parser.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15251)
> refactor: remove unused `list_all_tables()`

- Cargo.lock
- tests/sqllogictests/Cargo.toml
- tests/sqllogictests/suites/base/15_procedure/15_0001_execute_immediate.test
- tests/sqllogictests/suites/duckdb/join/semianti/antijoin.test
- tests/sqllogictests/suites/duckdb/join/semianti/semijoin.test
- tests/sqllogictests/suites/duckdb/join_small_block/semianti/antijoin.test
- tests/sqllogictests/suites/duckdb/join_small_block/semianti/semijoin.test
- tests/sqllogictests/suites/query/functions/auto_parse.test
- tests/sqllogictests/suites/stage/formats/csv/csv_select.test
- tests/sqllogictests/suites/stage/formats/ndjson/ndjson_select.test
- tests/sqllogictests/suites/stage/select_star.test
- Fixes #14874 
update crate version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15242)
> chore: update sqllogictests crate to 0.19.1

- src/query/ast/src/ast/statements/delete.rs
- src/query/ast/src/parser/statement.rs
- src/query/sql/src/planner/binder/delete.rs
- src/tests/sqlsmith/src/sql_gen/dml.rs
- tests/sqllogictests/suites/query/cte/delete_cte.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15284)
> feat: support cte in delete

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/api/src/util.rs
- src/meta/app/src/schema/mod.rs
- src/meta/app/src/schema/virtual_column.rs
- src/meta/app/src/schema/virtual_column_ident.rs
- src/query/service/src/interpreters/interpreter_virtual_column_alter.rs
- src/query/service/src/interpreters/interpreter_virtual_column_create.rs
- src/query/service/src/interpreters/interpreter_virtual_column_drop.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15285)
> refactor: define VirtualColumnNameIdent with TIdent

- src/query/service/src/interpreters/interpreter_explain.rs
- src/query/sql/src/planner/binder/delete.rs
- src/query/sql/src/planner/plans/delete.rs
- tests/sqllogictests/suites/mode/standalone/explain/delete.test
Currently we divide delete explain information into two parts: DeletePlan (subquery) and DeletePlan (selection).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15290)
> chore(planner): improve delete explain

- src/query/ast/src/parser/dynamic_table.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
This PR introduces enhanced flexibility in the SQL table creation process by allowing the table creation options (target_lag, warehouse, refresh_mode, initialize) to be specified in any order. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15297)
> chore: Enhance Flexibility of Dynamic Table Creation by Allowing Options in Any Order

- Cargo.lock
- src/query/functions/src/scalars/geometry.rs
- src/query/sql/src/planner/binder/binder.rs
- src/query/sql/src/planner/binder/udf.rs
- tests/sqllogictests/suites/base/05_ddl/05_0010_ddl_create_udf.test
- fix udf name with upper case letters
- remove some unused codes
for example
```sql
root@localhost:8900/default> create or replace function SOME_NAME as (x) -> x * x;
CREATE
OR REPLACE FUNCTION SOME_NAME AS (x) -> x * x
0 row written in 4.197 sec. Processed 0 row, 0 B (0 row/s, 0 B/s)
root@localhost:8900/default> select some_name(3);
SELECT
some_name(3)
┌──────────────┐
│ some_name(3) │
│     UInt8    │
├──────────────┤
│            9 │
└──────────────┘
1 row read in 0.062 sec. Processed 1 row, 1 B (16.09 rows/s, 16 B/s)
root@localhost:8900/default> create or replace function `SOME_NAME` as (x) -> x + x;
CREATE
OR REPLACE FUNCTION `SOME_NAME` AS (x) -> x * x
0 row written in 0.312 sec. …
```
> fix(query): fix udf name with upper case letters

- src/query/service/src/interpreters/interpreter_delete.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15288)
> chore: enable distributed optimization for subquery in delete

- src/query/expression/src/evaluator.rs
- Fixes https://github.com/datafuselabs/databend/issues/15293
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15311)
> fix: don't constant fold giant expr

- src/query/service/src/interpreters/interpreter_delete.rs
improve delete pruner
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15316)
> chore(query): improve delete pruner

- src/query/sql/src/planner/optimizer/optimizer.rs
- tests/sqllogictests/suites/mode/cluster/merge_into_non_equal_distributed.test
- tests/sqllogictests/suites/mode/standalone/explain/09_0039_target_build_merge_into_standalone.test
- tests/sqllogictests/suites/mode/standalone/explain/merge_into.test
Fix the bug of missing statistics(target table) in merge into.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15320)
> chore(planner): fix merge into statistics

- src/common/storage/src/stage.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/testdata/statement-error.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15323)
> fix(typo): refering -> referring

- src/query/service/src/servers/http/v1/query/execute_state.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15329)
> refactor: http handler check has_result_set() before get schema of plan.

- Cargo.lock
- Cargo.toml
- src/meta/types/src/raft_types.rs
This update includes a fix for excessive log scanning during startup to
locate the membership configuration.
See: https://github.com/datafuselabs/openraft/commit/14d42e4f33581dc0ea9c4eeaf0ff00ebec85dbb2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15339)
> refactor: Upgrade Openraft to 0.9.7

- src/query/service/src/pipelines/processors/transforms/aggregator/new_transform_partition_bucket.rs
Add err message to capture new agg hashtable hang in cluster
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15344)
> chore: add err message to help capture new agg ht hang

- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/storages/fuse/src/operations/read/runtime_filter_prunner.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15350)
> chore: enhance runtime filter log

- Cargo.lock
- src/common/license/Cargo.toml
- src/common/license/src/license.rs
- src/query/ee/src/license/license_mgr.rs
- src/query/ee/tests/it/license/license_mgr.rs
- tests/suites/5_ee/00_check/00_0014_license_info.result
feat(query): support compute quota feature
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15336)
> feat(query): support compute quota feature

- src/query/service/src/auth.rs
- src/query/service/src/servers/flight_sql/flight_sql_service/session.rs
- src/query/service/src/servers/mysql/mysql_interactive_worker.rs
- src/query/users/src/user_mgr.rs
only has password policy update user login res
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15356)
> refactor: only has password policy update user login res

- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- tests/sqllogictests/suites/query/join/fast_return.test
Support fast return for hash join spill.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15364)
> chore(planner): support fast return for hash join spill

- tests/sqllogictests/suites/base/06_show/06_0013_show_processlist.test
https://github.com/datafuselabs/databend/actions/runs/8868281614/job/24347834524?pr=15368
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15369)
> chore(ci): fix flaky test;

- src/common/tracing/src/structlog.rs
structlog is functional again now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15370)
> fix: structlog should print non-zero-rooted tree

- src/meta/raft-store/src/utils.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15374)
> chore: add more thest to prefix_right_bound()

- src/query/functions/src/scalars/geometry.rs
- src/query/functions/tests/it/scalars/geometry.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/geometry.txt
- tests/sqllogictests/suites/query/functions/02_0060_function_geometry.test
feat:  Implement  ST_POINTN().
see alse [doc](https://docs.snowflake.com/en/sql-reference/functions/st_pointn).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15373)
> feat(query): implement ST_POINTN

- Cargo.lock
- Cargo.toml
- src/meta/service/src/meta_service/raft_service_impl.rs
- src/meta/service/tests/it/meta_node/meta_node_replication.rs
- src/meta/service/tests/it/testing.rs
- src/meta/types/proto/meta.proto
- src/meta/types/src/lib.rs
- src/meta/types/src/proto_ext/snapshot_chunk_request_ext.rs
- src/meta/types/src/raft_types.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15395)
> feat: Add: stream based snapshot API install_snapshot_v2() to meta-service

- .github/workflows/bindings.python.yml
fix python binding release
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15407)
> fix: uplodate artifact name conflict for python

- src/common/storage/src/lib.rs
- src/common/storage/src/stage.rs
- src/query/service/src/table_functions/list_stage/list_stage_table.rs
list stage use stream to avoid OOM.
- Fixes https://github.com/datafuselabs/databend/issues/15305
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15405)
> refactor: list stage use stream to avoid OOM.

- src/query/service/src/interpreters/interpreter_merge_into.rs
- src/query/service/src/pipelines/pipeline_builder.rs
fix(executor): fix broken merge into source profiling
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15415)
> fix(executor): fix broken merge into source profiling

- src/meta/api/src/schema_api_impl.rs
- src/meta/app/src/schema/catalog.rs
- src/meta/app/src/schema/catalog_id_ident.rs
- src/meta/app/src/schema/catalog_id_to_name_ident.rs
- src/meta/app/src/schema/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15432)
> refactor: define CatalogIdToNameIdent with TIdent

- src/query/ee/src/storages/fuse/operations/handler.rs
- src/query/ee/src/storages/fuse/operations/vacuum_temporary_files.rs
- src/query/ee/tests/it/storages/fuse/operations/vacuum.rs
- src/query/ee_features/vacuum_handler/src/vacuum_handler.rs
- src/query/pipeline/core/src/pipeline.rs
- src/query/service/src/interpreters/hook/mod.rs
- src/query/service/src/interpreters/hook/vacuum_hook.rs
- src/query/service/src/interpreters/interpreter.rs
- src/query/service/src/interpreters/interpreter_vacuum_temporary_files.rs
- src/query/service/src/pipelines/builders/builder_aggregate.rs
- src/query/service/src/pipelines/builders/builder_sort.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/aggregate_exchange_injector.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/build_spill_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_spill/probe_spill_state.rs
- src/query/service/tests/it/spillers/spiller.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/sql/src/planner/plans/ddl/table.rs
- src/query/storages/system/src/temp_files_table.rs
- tests/sqllogictests/suites/ee/03_ee_vacuum/03_0000_vacuum_temporary_files.test
refactor(query): enable little vacuum after query finish
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15434)
> refactor(query): enable little vacuum after query finish

- src/common/tracing/src/structlog.rs
- src/query/functions/src/scalars/array.rs
- src/query/functions/tests/it/scalars/array.rs
- src/query/functions/tests/it/scalars/testdata/array.txt
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- Fixes https://github.com/datafuselabs/databend/issues/15408
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15437)
> fix(functions): improve array_prepend and array_append

- src/query/service/src/interpreters/interpreter_table_optimize.rs
- src/query/service/src/interpreters/interpreter_table_recluster.rs
- src/query/service/src/pipelines/builders/builder_recluster.rs
- src/query/sql/src/executor/physical_plans/physical_recluster_sink.rs
- src/query/storages/fuse/src/operations/mutation/mutator/block_compact_mutator.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0011_change_tracking.test
ignore stream column compare in block compact mutator
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15446)
> chore: ignore stream column compare in block compact mutator

- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_eval_scalar.rs
use scalarvisitor replace predicate recursive
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15449)
> refactor: use scalarvisitor replace predicate recursive

- src/query/sql/src/planner/binder/binder.rs
- src/query/sql/src/planner/plans/copy_into_table.rs
1. add query id
2. add total file size to copy
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15463)
> chore: polish log for copy.

- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
refactor(query): remove useless settings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15461)
> refactor(query): remove useless settings

- .github/actions/setup_docker/action.yml
- .github/workflows/build_tool.yml
- .github/workflows/release.yml
* update deprecated actions
* fix dependency for build tool job
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15470)
> chore(ci): update deprecated actions

- src/common/base/src/runtime/error_info.rs
- src/common/base/src/runtime/mod.rs
- src/common/base/src/runtime/profile/profile.rs
- src/common/base/src/runtime/runtime_tracker.rs
- src/query/pipeline/core/src/processors/profile.rs
- src/query/service/src/pipelines/executor/executor_graph.rs
feat(executor): record errors info into profiling log
Thanks @dqhl76 work on collecting error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15472)
> feat(executor): record errors info into profiling log

- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0000_remote_create_table.test
fix create table with cluster by get map type panic
- Fixes #15474
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15475)
> fix(query): fix create table with cluster by get map type panic

- src/query/service/src/servers/flight_sql/flight_sql_service/catalog.rs
- src/query/storages/system/src/streams_table.rs
- src/query/storages/system/src/tables_table.rs
remove incorrect usage of `Box::leak` which may cause memory leak
- Fixes #15467
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15481)
> chore: remove incorrect usage of `Box::leak`

- src/query/service/src/interpreters/interpreter_select.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/transform_build_spill.rs
- src/query/service/src/servers/http/v1/query/execute_state.rs
- src/query/sql/src/planner/plans/copy_into_table.rs
Change the log info:
* src/query/service/src/pipelines/processors/transforms/hash_join/build_spill/transform_build_spill.rs
* src/query/sql/src/planner/plans/copy_into_table.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15482)
> chore: fix copy/spill log message

- Cargo.lock
- Cargo.toml
- src/common/metrics/Cargo.toml
- src/common/metrics/src/metrics/storage.rs
- src/common/storage/Cargo.toml
- src/common/tracing/Cargo.toml
- src/meta/client/Cargo.toml
- src/meta/service/Cargo.toml
- src/query/service/Cargo.toml
- src/query/storages/fuse/Cargo.toml
- src/query/storages/fuse/src/operations/mutation/mutator/segment_compact_mutator.rs
This PR intends to upgrade opentelemetry to latest version and remove not used metrics crate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15484)
> chore: Upgrade opentelemetry and remove metrics crate

- src/query/config/src/version.rs
- src/query/service/src/servers/http/http_services.rs
- src/query/service/src/servers/http/middleware.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/login.rs
- src/query/service/src/servers/http/v1/mod.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/http_query_context.rs
- tests/suites/1_stateful/09_http_handler/09_0004_login.result
- tests/suites/1_stateful/09_http_handler/09_0004_login.sh
most  SQL drivers require to establish a  Connection on which statement is executed.
To filter into this pattern better, this PR introduces the `/v1/login` endpoint.
```
struct LoginRequest {
pub database: Option<String>,
pub role: Option<String>,
pub secondary_roles: Option<Vec<String>>,
pub settings: Option<BTreeMap<String, String>>,
}
struct LoginResponse {
pub version: String,
pub error: Option<QueryError>,
}
```
1. The client knows the version of the server, thus can implement backward compatibility.
2. `connect()` is a much better place than `execute()` to report some errors. e.g.
1. Auth fail
2. The server may reject clients that are too old
3. wrong db, role, settings
Ideally, login …
> feat: http handler add endpoint /v1/login/.

- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_spill_reader.rs
- src/query/sql/src/evaluator/cse.rs
1. Adjust the CSE info log level to debug; I think this log is no need info.
2. Modify the spill read bucket log to batch progress in order to reduce excessive logging.
- Fixes #15485
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15492)
> chore: fix some flood logs with batch progress

- src/common/base/src/runtime/mod.rs
- src/meta/client/src/grpc_client.rs
- src/meta/service/src/api/grpc/grpc_service.rs
chore(meta): tracking query id for meta log
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15497)
> chore(meta): tracking query id for meta log

- scripts/setup/dev_setup.sh
pyenv to 3.9 
- Fixes #15508 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15511)
> chore(query): pyenv to 3.9

- scripts/setup/dev_setup.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15516)
> refactor(query): revert dev_setup

- src/query/ast/Cargo.toml
- src/query/ast/src/ast/statements/copy.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/sql/src/planner/semantic/type_check.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15519)
> refactor: remove databend-common-base from databend-common-ast

- src/query/sql/src/planner/binder/binder.rs
- src/query/sql/src/planner/binder/copy_into_location.rs
- src/query/sql/src/planner/binder/insert.rs
- src/query/sql/src/planner/binder/insert_multi_table.rs
- src/query/sql/src/planner/binder/merge_into.rs
- src/query/sql/src/planner/binder/replace.rs
- tests/sqllogictests/suites/base/05_ddl/05_0022_ddl_desc_view.test
- tests/sqllogictests/suites/udf_server/udf_server_test.test
allow udf server in insert source
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15523)
> refactor(query): allow udf server in insert source

- src/meta/raft-store/src/sm_v002/writer_v002.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15532)
> chore: reduce snapshot building progress logging

- Cargo.lock
- Cargo.toml
- src/query/expression/Cargo.toml
- bump opensrv to 0.7.0
- remove unused micromarshal patch
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15551)
> chore: remove unused micromarshal patch

- src/query/catalog/src/table.rs
- src/query/catalog/src/table_context.rs
- src/query/ee/src/stream/handler.rs
- src/query/expression/src/kernels/sort.rs
- src/query/expression/tests/it/sort.rs
- src/query/service/src/interpreters/interpreter_table_analyze.rs
- src/query/service/tests/it/storages/fuse/operations/gc.rs
- src/query/service/tests/it/storages/fuse/operations/navigate.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/sql/src/planner/dataframe.rs
- src/query/storages/fuse/src/fuse_table.rs
- src/query/storages/fuse/src/operations/changes.rs
- src/query/storages/fuse/src/operations/navigate.rs
- src/query/storages/fuse/src/operations/revert.rs
support aborting table navigation: table navigation respects query context aborting action.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15549)
> chore: support aborting table navigation

- src/query/service/src/sessions/queue_mgr.rs
- src/query/service/tests/it/sessions/queue_mgr.rs
chore(query): add more heavy actions query type
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15556)
> chore(query): add more heavy actions query type

- src/meta/api/src/schema_api_impl.rs
- src/query/ast/src/ast/format/ast_format.rs
- src/query/ast/src/ast/format/syntax/ddl.rs
- src/query/ast/src/ast/statements/table.rs
- src/query/ast/src/ast/visitors/visitor.rs
- src/query/ast/src/ast/visitors/visitor_mut.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
- src/query/ee/tests/it/inverted_index/pruning.rs
- src/query/service/src/interpreters/interpreter_table_create.rs
- src/query/service/src/interpreters/interpreter_table_index_create.rs
- src/query/service/src/test_kits/fixture.rs
- src/query/service/tests/it/sql/planner/optimizer/agg_index_query_rewrite.rs
- src/query/service/tests/it/storages/fuse/operations/clustering.rs
- src/query/service/tests/it/storages/fuse/pruning.rs
- src/query/sql/src/planner/binder/ddl/dynamic_table.rs
- src/query/sql/src/planner/binder/ddl/index.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/sql/src/planner/plans/ddl/table.rs
- src/tests/sqlsmith/src/runner.rs
- src/tests/sqlsmith/src/sql_gen/ddl.rs
- tests/sqllogictests/suites/ee/04_ee_inverted_index/04_0000_inverted_index_base.test
create table support add inverted index
```sql
mysql> CREATE TABLE t (
->   id int,
->   content string,
->   INVERTED INDEX idx1 (content) tokenizer = 'chinese' filters = 'english_stop,english_stemmer,chinese_stop'
-> );
Query OK, 0 rows affected (0.11 sec)
mysql> show create table t;
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                            | …
```
> feat(query): create table support add inverted index

- Cargo.lock
- src/common/building/Cargo.toml
chore: Reduce the duplicated clap and gix
Only dep related changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15564)
> chore: Reduce the duplicated clap and gix

- src/query/sql/src/planner/optimizer/filter/normalize_disjunctive_filter.rs
- tests/sqllogictests/suites/query/issues/issue_15569.test
- Fixes https://github.com/datafuselabs/databend/issues/15569
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15587)
> fix: fix normalize disjunctive filter

- Cargo.lock
- Cargo.toml
- src/tests/sqlsmith/Cargo.toml
Bump jsonb version 0.4.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15589)
> chore: Bump jsonb version 0.4.0

- src/meta/README.md
- src/meta/service/src/version.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15593)
> chore: udpate doc for meta-service compat change

- src/common/tracing/src/loggers.rs
Reverts datafuselabs/databend#15627
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15631)
> Revert "chore(query): add timeout for open telemetry logger"

- tests/sqllogictests/scripts/prepare_tpcds_data.sh
- tests/sqllogictests/scripts/prepare_tpch_data.sh
copy is maintained better then streaming load.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15681)
> ci: tcph/tpcds use copy instead of streaming load for prepare data.

- src/query/storages/fuse/src/operations/mutation/processors/recluster_aggregator.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15684)
> chore: fix wrong print status

- src/query/ast/src/ast/expr.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
- tests/sqllogictests/suites/udf_server/user_functions_table.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15685)
> fix: display expr considering associativity

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15687)
> chore(ci): fix release workflow

- .github/actions/artifact_download/action.yml
- .github/actions/artifact_upload/action.yml
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15688)
> chore(ci): fix sqllogic test for release

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15689)
> chore(ci): fix pack for release

- .github/actions/artifact_download/action.yml
- .github/actions/artifact_upload/action.yml
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15691)
> chore(ci): fix artifact upload/download for gcs

- src/meta/api/src/schema_api_test_suite.rs
chore: add unit test of vacuum orphan table meta data
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15690)
> chore: add unit test of vacuum orphan table meta data

- .github/actions/setup_build_tool/action.yml
- .github/actions/test_stateful_hive_standalone/action.yml
- .github/workflows/release.yml
- .github/workflows/reuse.linux.yml
- src/common/building/src/lib.rs
- src/query/service/tests/it/metrics.rs
* add build env `DATABEND_RELEASE_VERSION`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15692)
> chore(ci): fix checkout and version on release build

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15697)
> chore(ci): fix release notify template

- src/query/service/src/interpreters/interpreter_table_show_create.rs
- src/query/service/src/interpreters/mod.rs
- src/query/service/src/servers/admin/v1/tenant_tables.rs
chore(query): add create query in admin tables api
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15694)
> chore(query): add create query in admin tables api

- .github/actions/publish_binary/action.yml
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15698)
> chore(ci): fix publish service image

- .github/actions/setup_bendsql/action.yml
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15699)
> chore(ci): fix run benchmark after release

- .github/scripts/bump_version.js
- .github/scripts/check_pr_description.js
- .github/scripts/check_pr_title.js
- .github/scripts/notify_release.js
- .github/workflows/cloud.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15701)
> chore(ci): ci-cloud build with python-udf

- .github/scripts/notify_release.js
- .github/workflows/pr.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15702)
> chore(ci): checkout code for pr check

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
previous bug: change `key_table_id_list` in txn loop, so when txn loop try again, the `key_table_id_list` is not correct, make assert fail.
fix this bug and add a concurrent commit table meta data unit test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15703)
> fix: add unit test of concurrent commit table meta data

- src/meta/service/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15705)
> refactor: enable mem-profiling for meta-service

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15708)
> chore(ci): fix download artifacts for docker_all_in_one

- src/query/storages/fuse/src/io/read/snapshot_history_reader.rs
- src/query/storages/fuse/src/table_functions/fuse_snapshots/fuse_snapshot.rs
more log for table history traversing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15710)
> chore: more log for table history traversing

- .github/workflows/cloud.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15712)
> chore(ci): fix download artifacts for cloud build

- .github/workflows/cloud.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15713)
> chore(ci): fix dockerfile for cloud service image build

- .github/scripts/notify_release.js
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15714)
> chore(ci): fix checking release status from jobs

- src/query/pipeline/core/src/finished_chain.rs
- src/query/pipeline/core/src/lib.rs
- src/query/pipeline/core/src/pipeline.rs
- src/query/service/src/interpreters/hook/compact_hook.rs
- src/query/service/src/interpreters/hook/refresh_hook.rs
- src/query/service/src/interpreters/interpreter.rs
- src/query/service/src/interpreters/interpreter_index_refresh.rs
- src/query/service/src/interpreters/interpreter_select.rs
- src/query/service/src/interpreters/interpreter_table_create.rs
- src/query/service/src/interpreters/interpreter_table_optimize.rs
- src/query/service/src/pipelines/builders/builder_on_finished.rs
- src/query/service/src/pipelines/executor/mod.rs
- src/query/service/src/pipelines/executor/pipeline_executor.rs
- src/query/service/src/pipelines/executor/pipeline_pulling_executor.rs
- src/query/service/src/pipelines/executor/query_pipeline_executor.rs
- src/query/service/src/servers/flight/v1/exchange/exchange_manager.rs
- src/query/service/src/sessions/query_ctx_shared.rs
- src/query/service/tests/it/pipelines/executor/pipeline_executor.rs
- tests/suites/1_stateful/09_http_handler/09_0005_kill.result
- tests/suites/1_stateful/09_http_handler/09_0005_kill.sh
fix(executor): fix query log lost for http kill
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15715)
> fix(executor): fix query log lost for http kill

- src/query/service/src/schedulers/scheduler.rs
- src/query/sql/src/executor/physical_plans/physical_limit.rs
- tests/sqllogictests/suites/query/union.test
1. union doesn't need to add project operator
2. union doesn't support lazy materialization.
- Fixes https://github.com/datafuselabs/databend/issues/15719 https://github.com/datafuselabs/databend/issues/15718
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15727)
> fix: fix union and lazy materialization

- src/query/sql/src/planner/optimizer/filter/infer_filter.rs
- tests/sqllogictests/suites/mode/standalone/explain/infer_filter.test
- tests/sqllogictests/suites/mode/standalone/explain_native/infer_filter.test
Fix merge predicates with different data types, use common data type to update predicates.
- Fixes #15717
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15725)
> chore(planner): fix merge predicates with different data types

- docker/service/meta.Dockerfile
- docker/service/query.Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15728)
> chore: add databend user to docker service images

- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15735)
> chore(ci): fix download artifacts for local benchmark

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15737)
> chore(ci): setup python3.12 for local benchmark

- src/meta/proto-conv/src/ownership_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/user_from_to_protobuf_impl.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15739)
> refactor: split None and Owner/Grantobject

- README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15744)
> docs: delete repeat summary

- .github/scripts/notify_release.js
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15748)
> chore(ci): fix check release status

- .github/scripts/notify_release.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15750)
> chore(ci): fix release notify icon

- src/meta/service/src/meta_service/raft_service_impl.rs
- src/meta/service/src/store/raft_log_storage_impl.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15740)
> chore: output raft log index range for purge logging

- src/common/storage/src/operator.rs
feat: Add http config for all storage services
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15757)
> feat: Add http config for all storage services

- Cargo.lock
- Cargo.toml
fix(storage): Fix a potential data loss while concurrent write
Related https://github.com/apache/opendal/pull/4707
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15759)
> fix(storage): Fix a potential data loss while concurrent write

- src/query/expression/src/filter/select_expr.rs
- src/query/expression/src/types/decimal.rs
- src/query/functions/src/scalars/decimal/comparison.rs
- src/query/functions/tests/it/scalars/testdata/comparison.txt
- src/query/storages/common/index/src/bloom_index.rs
- tests/sqllogictests/suites/base/11_data_type/11_0006_data_type_decimal.test
- tests/sqllogictests/suites/mode/standalone/explain/outer_to_inner.test
fix decimal cmp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15764)
> fix(query): fix decimal cmp

- src/query/sql/src/planner/binder/bind_table_reference/bind_table.rs
- tests/sqllogictests/suites/query/cte/name_conflict.test
- Fixes https://github.com/datafuselabs/databend/issues/15755
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15771)
> chore: add error info when table name is misleading

- src/query/service/src/pipelines/processors/transforms/transform_cast_schema.rs
- tests/sqllogictests/suites/stage/formats/parquet/auto_cast.test
- tests/suites/0_stateless/17_altertable/17_0005_alter_table_modify_column_type.result
- Fixes https://github.com/datafuselabs/databend/issues/15768
-->
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15770)
> fix: auto cast fail error in copy should show the related columns #15768

- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/sql/src/planner/planner.rs
- src/query/sql/src/planner/semantic/count_set_ops.rs
- src/query/sql/src/planner/semantic/mod.rs
- tests/sqllogictests/suites/query/union.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15777)
> chore: limit the count of set operation

- src/query/ast/src/parser/stage.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement-error.txt
- src/query/ast/tests/it/testdata/statement.txt
- tests/suites/1_stateful/00_stage/00_0008_remove_external_stage.sh
- Fixes https://github.com/datafuselabs/databend/issues/9658
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15780)
> feat: rm CREDENTIALS as alias of CONNECTION.

- src/meta/client/src/grpc_client.rs
- src/meta/client/src/grpc_metrics.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15784)
> chore: replace manually incr/decr with couter guard

- src/query/service/src/servers/http/v1/query/http_query.rs
the planing progress runs in a separate task spwaned by a handler， if it panics，the handle will hang
this pr catch this kind of panic and turn it into a error in http response.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15785)
> fix: http handler handle panic when starting query.

- .github/actions/io_delay_chaos/action.yml
- .github/workflows/meta.yml
- .github/workflows/release.yml
- scripts/ci/ci-setup-chaos-meta.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15787)
> fix(ci): meta chaos dockerfile path

- src/common/exception/src/exception_code.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/api/src/util.rs
- src/meta/app/src/app_error.rs
share table meta data can only be accessed from `share endpoint`, remove redundant code and test case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15793)
> chore: remove code about access share table into from meta service

- src/query/service/src/servers/http/v1/load.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- tests/sqllogictests/scripts/prepare_spill_data.sh
- tests/suites/1_stateful/01_streaming_load/01_0000_streaming_load.sh
- tests/suites/1_stateful/01_streaming_load/01_0003_streaming_variant_load.sh
- tests/suites/1_stateful/01_streaming_load/01_0004_streaming_parquet_int96.sh
- tests/suites/1_stateful/01_streaming_load/01_0005_streaming_on_error.sh
- tests/suites/1_stateful/05_formats/05_01_compact/05_01_01_load_compact_streaming_load.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15794)
> fix: add settings enable_streaming_load, default 0.

- .github/workflows/release.yml
chore: remove meta chaos from release action
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15796)
> chore: remove meta chaos from release action

- src/meta/README.md
- src/meta/raft-store/src/ondisk/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15799)
> chore: update doc about meta compatibility

- src/query/sql/src/planner/semantic/async_function_rewriter.rs
- tests/sqllogictests/suites/base/05_ddl/05_0036_sequence.test
fix: fix sequence used in function calls, add test cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15814)
> fix: fix sequence used in function calls

- src/query/service/src/interpreters/interpreter_replace.rs
- src/query/service/src/interpreters/interpreter_table_recluster.rs
- src/query/settings/src/settings_default.rs
1. recluster final ignore error 
2. replace add table lock.
3. Default value `table_lock_expire_secs`: 20s, `acquire_lock_timeout`: 30s
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15815)
> chore: recluster final ignore error

- .github/actions/build_linux/action.yml
- .github/actions/test_compat_meta_meta/action.yml
- .github/actions/test_compat_meta_query/action.yml
- .github/workflows/reuse.linux.yml
- tests/compat/meta_meta/README.md
- tests/compat/meta_meta/test_meta_meta.sh
- tests/compat/util.sh
This test start version-A databend-meta as the leader, feed some data,
build snapshot, and then join a version-B databend-meta to the cluster,
feed some other data, and ensure these two nodes be able to work
together correctly by checking the exported data from these two running
nodes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15823)
> refactor: add meta-meta compat test

- .github/actions/test_compat_meta_meta/action.yml
- src/meta/binaries/README.md
- tests/compat/meta_meta/test_meta_meta.sh
- tests/compat/util.sh
- Fix: #15825
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15826)
> chore: fix scripts in meta-meta compatibility test

- .github/scripts/notify_failure.js
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15829)
> chore(ci): add reporter for meta chaos test

- src/query/functions/src/scalars/other.rs
- src/query/sql/src/planner/expression_parser.rs
- tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15840)
> fix: function uuid() should be non_deterministic.

- src/query/service/src/interpreters/interpreter_merge_into.rs
- src/query/service/src/pipelines/builders/builder_merge_into.rs
- src/query/service/src/pipelines/processors/transforms/processor_deduplicate_row_number.rs
- src/query/sql/src/executor/physical_plans/physical_merge_into.rs
- src/query/sql/src/planner/binder/merge_into.rs
- src/query/sql/src/planner/optimizer/distributed/distributed_merge.rs
- src/query/sql/src/planner/optimizer/optimizer.rs
- src/query/sql/src/planner/plans/merge_into.rs
- tests/sqllogictests/suites/mode/cluster/merge_into_non_equal_distributed.test
remove `AddRowNumber` if source is physical table and reconstruct pipeline in merge into
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15828)
> chore(query): remove addRowNumber if source is physical table

- src/query/sql/src/planner/binder/ddl/view.rs
- tests/sqllogictests/suites/base/01_system/01_0003_information_schema.test
- tests/sqllogictests/suites/base/06_show/06_0023_show_views.test
- tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.result
- tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.sql
show view just display view name
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15841)
> chore(query): show view just display view name

- Cargo.lock
- Cargo.toml
Fix build of arrow-udf
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15846)
> chore: Fix build of arrow-udf

- scripts/ci/meta-chaos/ci-io-delay-meta-test.sh
chore: change meta chaos io delay param
* delay: `50ms` -> `20ms`
* percent: `10` -> `5`
* apply chaos seconds: `5` -> `2`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15852)
> chore: change meta chaos io delay param

- .github/workflows/reuse.linux.yml
- .github/workflows/reuse.sqllogic.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15854)
> chore(ci): fix duplicate failure artifact name

- Cargo.lock
- src/query/pipeline/transforms/Cargo.toml
- src/query/pipeline/transforms/src/processors/transforms/transform_retry_async.rs
chore(query): add retry logs#[Link the issue here]
-->
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15862)
> chore(query): add retry logs

- docker/service/query.Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15875)
> chore: install gdb for query service image

- src/query/sql/src/planner/semantic/aggregate_rewriter.rs
- tests/sqllogictests/suites/query/aggregate.test
Change rewrite rule from:
```
sum(c + expr) --> c * count() + sum(expr)
```
to 
```
sum(c + expr) --> c * count(expr) + sum(expr)
```
fixes #15867 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15870)
> fix(query): fix sum rewriter

- src/query/service/src/pipelines/processors/transforms/transform_recursive_cte_source.rs
- tests/sqllogictests/suites/query/cte/basic_r_cte.test
- tests/sqllogictests/suites/query/cte/r_cte_alias_name.test
- tests/sqllogictests/suites/query/cte/r_cte_tutorial.test
- tests/sqllogictests/suites/query/cte/r_cte_union_all.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15883)
> chore: fix recursive cte hang

- src/query/pipeline/core/src/finished_chain.rs
- src/query/service/src/pipelines/executor/executor_graph.rs
chore(executor): avoid lock poisoning for pipeline executor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15887)
> chore(executor): avoid lock poisoning for pipeline executor

- src/query/sql/src/planner/optimizer/optimizer.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15890)
> chore: add log to show if enable distributed optimization

- src/query/service/src/interpreters/interpreter_insert.rs
https://github.com/datafuselabs/databend/issues/15888
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15892)
> chore: print the select plan of insert query

- Cargo.lock
- Cargo.toml
- src/query/ast/Cargo.toml
- src/query/ast/src/span.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15894)
> chore: replace patched codespan-reporting with rspack-codespan-reporting

- .github/workflows/bindings.python.yml
- .github/workflows/cloud.yml
- .github/workflows/dev.yml
- .github/workflows/meta.yml
- .github/workflows/production.yml
- .github/workflows/release.yml
- tests/logging/test-logs.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15903)
> chore(ci): switch runner to aws

- Cargo.lock
- src/query/ast/Cargo.toml
https://crates.io/crates/databend-common-ast
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15905)
> feat: publish databend-common-ast to crates.io

- src/query/sql/src/planner/optimizer/property/selectivity.rs
- tests/sqllogictests/suites/mode/standalone/explain/selectivity/modulo.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15917)
> refactor: improve modulo predicate selectivity

- .github/workflows/reuse.benchmark.yml
- benchmark/clickbench/hits/load.sql
- benchmark/clickbench/index.jinja
- benchmark/clickbench/tpch/load.sql
- scripts/benchmark/query/load/hits.sh
- scripts/benchmark/query/load/tpch10.sh
- scripts/benchmark/query/load/tpch100.sh
- scripts/ci/ci-setup-chaos-meta.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15920)
> chore: update domain for datasets & benchmark

- src/query/sql/src/planner/optimizer/property/builder.rs
- src/query/sql/src/planner/optimizer/property/enforcer.rs
fix(query): fix cluster mode stack overflow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15927)
> fix(query): fix cluster mode stack overflow

- tests/sqllogictests/suites/crdb/update.test
issue 17791 has been fixed in https://github.com/datafuselabs/databend/pull/15526,  add test case of issue 15791
- Fixes #15791
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15931)
> chore: add test case of issue 15791

- src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/left_join.rs
function `process_left_or_full_join_null_block` input param `matched_idx` actually is `unmatched_idx`, this may confused code reader.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15933)
> chore: fix param typo in function process_left_or_full_join_null_block

- src/query/service/src/pipelines/processors/transforms/hash_join/desc.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs
- src/query/sql/src/executor/physical_plans/physical_hash_join.rs
- src/query/sql/src/executor/physical_plans/physical_join.rs
- src/query/sql/src/planner/binder/bind_query/bind_value.rs
- src/query/sql/src/planner/binder/bind_table_reference/bind_join.rs
- src/query/sql/src/planner/binder/binder.rs
- src/query/sql/src/planner/binder/merge_into.rs
- src/query/sql/src/planner/format/display_rel_operator.rs
- src/query/sql/src/planner/optimizer/decorrelate/decorrelate.rs
- src/query/sql/src/planner/optimizer/decorrelate/flatten_plan.rs
- src/query/sql/src/planner/optimizer/decorrelate/subquery_rewriter.rs
- src/query/sql/src/planner/optimizer/filter/deduplicate_join_condition.rs
- src/query/sql/src/planner/optimizer/filter/pull_up_filter.rs
- src/query/sql/src/planner/optimizer/hyper_dp/dphyp.rs
- src/query/sql/src/planner/optimizer/hyper_dp/join_node.rs
- src/query/sql/src/planner/optimizer/optimizer.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_commute_join.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_semi_to_inner_join.rs
- src/query/sql/src/planner/optimizer/rule/transform/rule_commute_join_base_table.rs
- src/query/sql/src/planner/optimizer/rule/transform/rule_eager_aggregation.rs
- src/query/sql/src/planner/optimizer/rule/transform/rule_left_exchange_join.rs
- src/query/sql/src/planner/optimizer/rule/transform/util.rs
- src/query/sql/src/planner/optimizer/s_expr.rs
- src/query/sql/src/planner/plans/join.rs
- tests/sqllogictests/suites/query/lateral.test
Use `JoinEquiCondition` to combine `left_conditions`, `right_condition` and `is_null_equal`.
Fixes #15886
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15924)
> chore(planner): refactor join equi conditions

- src/query/sql/src/planner/binder/bind_query/bind_value.rs
fix(query): fix stackoverflow for ci release mode
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15944)
> fix(query): fix stackoverflow for ci release mode

- src/meta/protos/proto/database.proto
ownership number is 36 but reserved 30.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15955)
> fix(meta): fix reserved number err

- src/query/storages/orc/src/chunk_reader_impl.rs
avoid another Copy introduced by `into_futures_async_read`.
according to advise of Xuanwo (author of OpenDAL).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15967)
> refactor: optimize OrcChunkReader.

- Cargo.lock
- Cargo.toml
now using https://github.com/youngsofun/datafusion-orc/commits/pub_and_io
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15968)
> fix: update orc-rust to fix error when read columns of array<float>.

- src/meta/app/src/principal/file_format.rs
- src/meta/proto-conv/src/file_format_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/main.rs
- src/meta/proto-conv/tests/it/v097_orc_format_params.rs
- src/meta/protos/proto/file_format.proto
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/statement.txt
this pr only add the meta and parser part, to make it easier to review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15974)
> feat: orc add option missing_field_as.

- src/query/functions/src/scalars/geometry.rs
- src/query/functions/tests/it/scalars/geometry.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/functions/tests/it/scalars/testdata/geometry.txt
- tests/sqllogictests/suites/query/functions/02_0060_function_geometry.test
feat:  Implement  st_length/st_distance https://github.com/datafuselabs/databend/issues/15413
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15982)
> feat(query): implement st_length/st_distance

- tests/sqllogictests/suites/base/01_system/01_0012_system_temp_files.test
- tests/suites/0_stateless/20+_others/20_0014_sort_spill.sql
chore(query): fix cluster ci failure if set license
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15999)
> chore(query): fix cluster ci failure if set license

- src/query/sql/src/planner/binder/ddl/index.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/base/05_ddl/05_0028_ddl_alter_table_add_drop_column.test
fix drop table column with quotes
- Fixes #16005
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16006)
> fix(query): fix drop table column with quotes

- Cargo.lock
- src/query/ast/Cargo.toml
- src/query/ast/src/ast/query.rs
- src/query/ast/src/lib.rs
- src/query/ast/src/parser/query.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16009)
> chore: update nom-rule

- src/query/ast/Cargo.toml
I suggest people to take a look at this lib, and found no link to the github repo in crates.io, so added it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16010)
> chore: add repo link in databend-common-ast lib

- src/query/pipeline/transforms/src/processors/transforms/sort/merger.rs
- src/query/pipeline/transforms/src/processors/transforms/sort/spill.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge_base.rs
- src/query/service/src/pipelines/builders/builder_sort.rs
- src/query/service/src/pipelines/processors/transforms/range_join/ie_join_state.rs
- src/query/service/src/pipelines/processors/transforms/transform_sort_spill.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
feat(query): add setting sort_spilling_batch_bytes
```
select number::string, number + 1, row_number() over (order by number + 1 desc )  from numbers(1000000000)  ignore_result;
....
8.1M    .databend/stateless_test_data/_query_spill/test_tenant/a4503b65-e564-4b45-ad73-a87be3b62ff4/mffWLkGeQRKwqhOhcjcvU5
8.1M    .databend/stateless_test_data/_query_spill/test_tenant/a4503b65-e564-4b45-ad73-a87be3b62ff4/mhAa28xt2O89h5UjLctEQ
8.1M    .databend/stateless_test_data/_query_spill/test_tenant/a4503b65-e564-4b45-ad73-a87be3b62ff4/mIzoaBSeM4pRGpkwXN7Sc1
8.1M    .databend/stateless_test_data/_query_spill/test_tenant/a4503b65-e564-4b45-ad73-a87be3b62ff4/Mj6YXjEIqtvdBcTAI93wy1
8.1M …
```
> feat(query): add setting sort_spilling_batch_bytes

- scripts/setup/rust-toolchain.toml
Part of https://github.com/datafuselabs/databend/pull/16026
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16033)
> ci: Build runner for nightly-2024-07-02

- src/query/service/src/interpreters/access/privilege_access.rs
- tests/suites/0_stateless/20+_others/20_0019_set_cache_capacity_privilege_check.result
- tests/suites/0_stateless/20+_others/20_0019_set_cache_capacity_privilege_check.sh
add privilege checking for system table function `fuse_amend`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16045)
> chore: add privilege checking for `fuse_amend`

- Cargo.lock
- src/binaries/query/ee_main.rs
- src/binaries/query/oss_main.rs
- src/common/tracing/Cargo.toml
- src/common/tracing/src/crash_hook.rs
- src/common/tracing/src/lib.rs
- src/common/tracing/src/panic_hook.rs
refactor(query): add crash handler for databend-query
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16054)
> refactor(query): add crash handler for databend-query

- src/query/formats/src/field_encoder/helpers/number_helpers.rs
- tests/sqllogictests/suites/query/functions/02_0014_function_maths.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16052)
> fix: output format missing '-' for '-Infinity'.

- src/query/management/src/role/role_mgr.rs
Now revoke ownership will revoke ownership privilege from old role and then delete the ownership kv.
If more session with same role execute drop object that has ownership will failed. Because of revoke timeout.
In this pr we do some optimize:
1. if role does not store object's ownership skip revoke ownership from role
2. TXN_MAX_RETRY_TIMES incrase 60 times
Fix: https://github.com/datafuselabs/databend/issues/16048
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16047)
> fix(query): if role not store ownership skip revoke ownership from role

- src/query/settings/src/settings_default.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16059)
> chore(query): enable distributed merge into by default

- .github/PULL_REQUEST_TEMPLATE.md
- Cargo.lock
- scripts/ci/deploy/config/databend-query-node-1.toml
- src/common/tracing/Cargo.toml
- src/common/tracing/src/loggers.rs
- fixes: https://github.com/datafuselabs/databend/issues/16037
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16064)
> feat: log file with local time

- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/storages/information_schema/src/views_table.rs
- tests/sqllogictests/suites/base/01_system/01_0003_information_schema.test
- fixes: #16063 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16065)
> fix(query): pad information_schema.views.view_definition

- .github/workflows/release.yml
chore: fix share test integration missing query binary
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16071)
> chore: fix share test integration missing query binary

- Cargo.lock
- Cargo.toml
- src/query/functions/src/scalars/variant.rs
- src/query/functions/src/srfs/variant.rs
Bump jsonb version 0.4.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16073)
> chore: Bump jsonb version 0.4.1

- src/query/storages/fuse/src/operations/merge_into/mutator/matched_mutator.rs
- tests/sqllogictests/suites/ee/01_ee_system/01_0001_computed_column.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16086)
> chore(query): fix merge into virtual computed field

- Cargo.lock
- src/common/storage/src/lib.rs
- src/query/expression/src/type_check.rs
- src/query/expression/src/types/variant.rs
- src/query/storages/common/stage/Cargo.toml
- src/query/storages/common/stage/src/lib.rs
- src/query/storages/common/stage/src/read/cast.rs
- src/query/storages/common/stage/src/read/columnar/projection.rs
- src/query/storages/common/stage/src/read/mod.rs
- tests/sqllogictests/suites/stage/formats/parquet/auto_cast.test
currently, for convenient,  there are auto cast if type not match, when loading columns with known types, 
there is almost no limit to this auto cast. this pr try to allow only useful and unambiguous auto-casts. To assist users in achieving a correct schema more swiftly and avoiding potential mistakes.
principles(strong to weak):
1. must forbid it if a cast result maybe unexpected. e.g.  there are many ways to cast binary to string.
2. just allow it if a cast looks useful and would easily fail at runtime if the cast is wrong.
3. tend to forbid if a cast never fail, but lost infos, e.g.  bitmap to string, int64 to bool
see the comments for detail explanation …
> feat: limit auto cast when loading from column store.

- src/query/sql/src/planner/plans/limit.rs
- src/query/sql/src/planner/plans/window.rs
- tests/sqllogictests/suites/mode/cluster/window.test
- tests/sqllogictests/suites/mode/standalone/explain/fold_count.test
- tests/sqllogictests/suites/mode/standalone/explain/prune_column.test
- tests/sqllogictests/suites/mode/standalone/explain_native/prune_column.test
fix incorrect derive_stats for window and limit plan
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16087)
> fix(query): fix incorrect derive_stats for window and limit plan

- src/query/service/src/servers/http/v1/query/execute_state.rs
- tests/sqllogictests/suites/base/20+_others/20_0018_http_handler.test
the bug was introduced in https://github.com/datafuselabs/databend/pull/12370.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16089)
> fix: error message in data.

- src/meta/service/src/api/grpc_server.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16104)
> refactor: meta-service wait at most 1 second to shutdown

- Cargo.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16110)
> chore(code): update the version of object_store in Cargo.lock

- src/query/expression/src/schema.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_prewhere.rs
- tests/sqllogictests/suites/query/filter.test
Fixes: #16107
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16108)
> chore(query): disable inner columns in prewhere

- src/common/io/src/format_settings.rs
- src/query/formats/src/output_format/json.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/page_manager.rs
- src/query/service/src/servers/http/v1/string_block.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- src/query/service/tests/it/servers/http/json_block.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- tests/cloud_control_server/simple_server.py
- for: #16111
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16120)
> feat(query): support json null for nullable response

- src/query/sql/src/planner/optimizer/statistics/collect_statistics.rs
fix(query): fix stackoverflow in collect_statistics
https://github.com/datafuselabs/databend/actions/runs/10085126740/job/27885831221
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16123)
> fix(query): fix stackoverflow in collect_statistics

- Cargo.lock
- Cargo.toml
- src/common/base/Cargo.toml
- src/common/tracing/Cargo.toml
- src/common/tracing/src/crash_hook.rs
use the signal stack to collect error info if stackoverflow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16122)
> chore(query): add sigaltstack for signal handler 

- src/query/pipeline/core/src/processors/processor.rs
- src/query/pipeline/sinks/tests/it/async_mpsc_sink.rs
- src/query/pipeline/sinks/tests/it/sync_mpsc_sink.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_aggregate_final.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_group_by_final.rs
- src/query/service/src/pipelines/processors/transforms/window/partition_by/transform_window_partition_sort.rs
- src/query/storages/result_cache/src/write/sink.rs
chore(query): remove useless box processor implementation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16128)
> chore(query): remove useless box processor impl

- src/meta/raft-store/src/applier.rs
- src/meta/service/src/store/store_inner.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16138)
> fix: deadlock with export() and build_snapshot()

- src/common/storage/src/statistics.rs
- src/common/tracing/src/panic_hook.rs
- src/query/storages/fuse/src/table_functions/fuse_statistics/fuse_statistic.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0020_analyze.test
- fixes: https://github.com/datafuselabs/databend/issues/16116
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16141)
> feat: add histogram info to fuse_statistic table

- src/query/service/src/servers/admin/admin_service.rs
- src/query/service/src/servers/admin/v1/user_functions.rs
- src/query/storages/system/src/user_functions_table.rs
feat(query): add user function admin api
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16146)
> feat(query): add user function admin api

- src/query/service/src/servers/admin/admin_service.rs
- src/query/service/src/servers/admin/v1/user_functions.rs
chore(query): move udf admin api to management mode
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16155)
> chore(query): move udf admin api to management mode

- src/query/ast/src/parser/common.rs
- src/query/ast/src/parser/expr.rs
- src/query/ast/src/parser/query.rs
- src/query/ast/tests/it/testdata/expr-error.txt
- src/query/ast/tests/it/testdata/query-error.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16156)
> chore: improve parser

- src/query/service/src/locks/lock_holder.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16158)
> chore: reduce the sleep range during lock holder

- src/query/service/src/interpreters/interpreter_table_add_column.rs
- src/query/service/src/interpreters/interpreter_update.rs
- src/query/service/tests/it/storages/fuse/operations/alter_table.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/sql/src/planner/expression_parser.rs
- src/query/sql/src/planner/plans/ddl/table.rs
- tests/sqllogictests/suites/base/03_common/03_0027_insert_default.test
- tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables.test
- tests/sqllogictests/suites/base/05_ddl/05_0028_ddl_alter_table_add_drop_column.test
add column support default value have indeterministic expression
for example
```sql
mysql> create table t(a int, b string);
Query OK, 0 rows affected (0.66 sec)
mysql> insert into t values(1, 'a'),(2, 'b'),(3, 'c');
Query OK, 3 rows affected (0.41 sec)
mysql> alter table t add column c timestamp not null default now();
Query OK, 3 rows affected (0.54 sec)
mysql> select * from t;
+------+------+----------------------------+
| a    | b    | c                          |
+------+------+----------------------------+
|    1 | a    | 2024-07-31 03:30:10.498338 |
|    2 | b    | 2024-07-31 03:30:10.498338 |
|    3 | c    | 2024-07-31 03:30:10.498338 |
+------+------+----------------------------+
3 …
```
> fix(query): fix add column default value is indeterministic expression

- src/query/service/src/interpreters/interpreter.rs
- src/query/service/src/interpreters/interpreter_explain.rs
- src/query/service/src/pipelines/executor/executor_graph.rs
`EXPLAIN ANALYZE` cannot show statistics data correctly.
```
root@localhost:8000/default> explain analyze SELECT number FROM numbers_mt(5) WHERE number < 2;
EXPLAIN ANALYZE
SELECT
number
FROM
numbers_mt(5)
WHERE
number < 2
Exchange
├── output columns: [numbers_mt.number (#0)]
├── exchange type: Merge
└── Filter
├── output columns: [numbers_mt.number (#0)]
├── filters: [numbers_mt.number (#0) < 2]
├── estimated rows: 0.00
├── cpu time: 78.458µs
├── output rows: 2
├── output bytes: 16.00 B
└── TableScan
├── table: default.system.numbers_mt
├── output columns: [number (#0)]
├── read rows: 5
├── read size: < 1 KiB
├── partitions total: 1
├── …
```
> fix: explain analyze lack of statistics 

- src/query/service/src/interpreters/access/privilege_access.rs
reduce get table meta call
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16170)
> fix(query): reduce get table meta call

- src/query/expression/src/converts/meta/index_scalar.rs
- src/query/expression/tests/it/meta_scalar.rs
- src/query/storages/common/table_meta/src/meta/v2/segment.rs
- src/query/storages/common/table_meta/src/meta/v2/statistics.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16180)
> fix: properly ignore column statistic from meta v2 if string contains non-utf8

- src/query/storages/system/src/tables_table.rs
- src/query/storages/system/src/util.rs
- tests/sqllogictests/suites/base/01_system/01_0001_system_tables.test
support optimize or filter in system.tables
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16165)
> fix(query): support optimize or filter in system.tables

- src/query/service/src/pipelines/processors/transforms/transform_udf_script.rs
chore(query): skip empty block for udf script
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16182)
> chore(query): skip empty block for udf script

- src/query/storages/system/src/tables_table.rs
- tests/sqllogictests/suites/base/01_system/01_0001_system_tables.test
Optimize system.tables speed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16183)
> refactor(query): if projection not query stat/owner will not get table_stats/ownership when access system.tables 

- src/query/service/src/pipelines/processors/transforms/transform_udf_script.rs
fix wasm udf runtime create with code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16191)
> fix(query): fix wasm udf runtime create with code

- src/query/expression/src/utils/date_helper.rs
- src/query/functions/src/scalars/datetime.rs
- tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test
- tests/sqllogictests/suites/query/functions/02_0075_function_datetimes_tz.test
to_year/monday... should respect dst
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16195)
> fix(query): to_year/monday... should respect dst

- src/common/cache/src/cache.rs
- src/common/cache/src/cache/lru.rs
- src/query/ee/src/storages/fuse/operations/vacuum_table.rs
- src/query/storages/common/cache/src/cache.rs
- src/query/storages/common/cache/src/providers/disk_cache/disk_cache.rs
- src/query/storages/common/cache/src/providers/disk_cache/disk_cache_lru.rs
- src/query/storages/common/cache/src/providers/memory_cache.rs
- src/query/storages/common/cache/src/providers/table_data_cache.rs
- src/query/storages/common/cache/src/read/cached_reader.rs
- src/query/storages/common/cache/src/read/readers.rs
- src/query/storages/common/cache_manager/src/cache_manager.rs
- src/query/storages/common/cache_manager/src/caches.rs
- src/query/storages/fuse/src/io/read/meta/meta_readers.rs
- src/query/storages/fuse/src/operations/gc.rs
- src/query/storages/system/src/caches_table.rs
refactor(query): remove useless hash builder
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16203)
> refactor(query): remove useless hash builder

- scripts/ci/ci-run-ee-tests-standalone-fake-time-minio.sh
- src/query/expression/src/converts/meta/index_scalar.rs
- src/query/storages/common/table_meta/src/meta/statistics.rs
- src/query/storages/common/table_meta/src/meta/v2/statistics.rs
- src/query/storages/fuse/src/operations/replace_into/mutator/mutator_replace_into.rs
- tests/cloud_control_server/simple_server.py
Remove minmax in statistics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16197)
> chore: remove unused minmax

- .github/workflows/build_tool.yml
- .github/workflows/release.yml
- .github/workflows/reuse.linux.yml
Maintaining a `MUSL` build target is complex. Users should be guided towards container-based deployment instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16205)
> chore(ci): disable musl build

- src/query/expression/src/function.rs
- src/query/functions/src/cast_rules.rs
- src/query/functions/src/scalars/mod.rs
- src/query/functions/src/scalars/string.rs
- src/query/functions/tests/it/scalars/string.rs
- src/query/functions/tests/it/scalars/testdata/string.txt
closes https://github.com/datafuselabs/databend/issues/16150
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16210)
> feat: allow casting int to uint for string functions

- src/common/base/src/future.rs
- src/meta/client/src/grpc_client.rs
- src/meta/service/src/api/grpc/grpc_service.rs
- src/meta/service/src/meta_service/raft_service_impl.rs
- src/meta/service/src/network.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16211)
> chore: refine TimedFutre wrapper

- Cargo.lock
- Cargo.toml
- src/common/base/Cargo.toml
- src/common/base/src/display/display_unix_epoch.rs
- src/common/base/src/display/mod.rs
- src/meta/raft-store/src/applier.rs
- src/meta/raft-store/src/state_machine/sm.rs
- src/meta/types/Cargo.toml
- src/meta/types/src/proto_display.rs
- src/query/ee/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16212)
> refactor: display unix timestamp for human

- src/query/sql/src/planner/binder/bind_table_reference/bind_table.rs
- tests/sqllogictests/suites/base/05_ddl/05_0019_ddl_create_view.test
- fixes: #16145
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16223)
> fix(query): cannot use fully qualified names with views

- src/meta/service/src/meta_service/meta_node.rs
- src/meta/service/src/meta_service/meta_node_status.rs
- src/meta/service/src/meta_service/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16229)
> chore: refine meta-service

- src/common/base/src/display/display_slice.rs
- src/common/base/src/display/mod.rs
- src/common/license/src/display_jwt_claims.rs
- src/common/license/src/lib.rs
- src/common/license/src/license.rs
- src/query/service/src/table_functions/others/license_info.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16244)
> chore: impl Display for `LicenseInfo` and `JWTClaims<T>`

- Cargo.lock
- scripts/ci/ci-setup-chaos-meta.sh
- tests/metactl/test-metactl-restore-new-cluster.sh
- tests/metactl/test-metactl.sh
- tests/metactl/update-metactl-test.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16263)
> chore: update command for metactl in tests

- src/query/storages/fuse/src/fuse_table.rs
more logs for attached table refreshing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16261)
> chore: more logs for attached table refreshing

- Cargo.lock
- Cargo.toml
- src/query/storages/iceberg/Cargo.toml
Use tagged iceberg crates
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16278)
> chore: Use tagged iceberg crates

- src/query/expression/src/function.rs
- src/query/functions/src/scalars/other.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- tests/sqllogictests/suites/mode/standalone/explain/table_sample.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16275)
> chore: add a setting to decide if table sample is deterministic

- .github/workflows/release.yml
- for: https://github.com/datafuselabs/databend/issues/16284
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16285)
> chore(ci): tmp disable sharing test

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/util.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16289)
> chore: replace condition and if_then with txn in txn methods

- src/query/storages/system/src/log_queue.rs
fix(query): enable distribute query for system query log table
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16300)
> fix(query): enable distribute query for system log table

- src/query/sql/src/planner/optimizer/statistics/collect_statistics.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16303)
> chore: remove the log about if histogram exists

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16334)
> chore(ci): adjust release time

- src/query/catalog/src/plan/partition.rs
- src/query/service/src/servers/flight/v1/exchange/exchange_manager.rs
- src/query/storages/system/src/backtrace_table.rs
- src/query/storages/system/src/caches_table.rs
- src/query/storages/system/src/malloc_stats_totals_table.rs
- src/query/storages/system/src/metrics_table.rs
- src/query/storages/system/src/processes_table.rs
- src/query/storages/system/src/queries_profiling.rs
- src/query/storages/system/src/table.rs
- tests/sqllogictests/suites/mode/cluster/explain_v2.test
fix(query): fix wrong result for join system tables in cluster mode
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16342)
> fix(query): fix wrong result for join system tables in cluster mode

- src/query/expression/src/evaluator.rs
- src/query/functions/src/scalars/array.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/functions/02_0002_function_try_cast.test
- tests/sqllogictests/suites/query/functions/02_0061_function_array.test
fixes #14331
fixes #14488
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16341)
> fix(query): fix try cast

- Cargo.lock
- src/meta/api/src/kv_app_error.rs
- src/meta/api/src/txn_backoff.rs
- src/meta/stoerr/Cargo.toml
- src/meta/stoerr/src/meta_bytes_error.rs
- src/meta/stoerr/src/meta_storage_errors.rs
- src/meta/types/src/errors/meta_client_errors.rs
- src/meta/types/src/errors/meta_errors.rs
- src/meta/types/src/errors/meta_handshake_errors.rs
- src/meta/types/src/errors/meta_startup_errors.rs
- src/meta/types/src/errors/rpc_errors.rs
- src/query/management/src/role/role_mgr.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16347)
> chore: remove unused serde impl

- src/query/service/src/pipelines/processors/transforms/window/transform_window.rs
- tests/sqllogictests/suites/tpcds/spill.test
Fix window index out of range.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16352)
> chore(query): fix window index out of range

- benchmark/clickbench/internal/load.sh
- benchmark/clickbench/internal/queries/03.sql
add internal performance test:
query system.tables_with_history
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16369)
> chore(ci): add internal test

- src/query/storages/iceberg/src/catalog.rs
Our parser doesn't allow users to write `s3.region` in options. Instead, users must use
`"s3.region"`, but it's stored as is which makes the behavior in wrong. We need to remove the quotes here.
We only do this while building catalog so this won't affect existing catalogs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16404)
> fix(iceberg): Handling options like "s3.region"

- src/meta/api/src/schema_api_impl.rs
- src/meta/app/src/app_error.rs
- src/meta/app/src/schema/catalog.rs
- src/meta/app/src/schema/catalog_id_ident.rs
- src/meta/app/src/schema/catalog_name_ident.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16406)
> refactor: simplify catalog API

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/api/src/util.rs
- src/meta/app/src/schema/table.rs
- src/query/service/src/databases/default/default_database.rs
- src/query/service/src/locks/table_lock/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16416)
> refactor: remove unused `TableInfo.tenant`

- src/query/service/src/interpreters/access/privilege_access.rs
- tests/suites/0_stateless/18_rbac/18_0007_privilege_access.result
- tests/suites/0_stateless/18_rbac/18_0007_privilege_access.sh
The columns permission of the system library is misjudged.
- fixes: 16430
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16431)
> fix(query): The columns permission of the system library is misjudged.

- src/query/service/src/pipelines/builders/builder_aggregate.rs
- src/query/service/src/pipelines/builders/builder_window.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/aggregator_params.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_spill_reader.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_partition_bucket.rs
- src/query/service/src/pipelines/processors/transforms/window/partition_by/transform_window_partition_spill_reader.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
chore(query): limit max concurrency of spill io requests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16442)
> chore(query): limit max concurrency of spill io requests

- Cargo.lock
- src/common/tracing/Cargo.toml
- src/common/tracing/src/init.rs
- src/common/tracing/src/loggers.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16470)
> fix: revert log format breakage from #16249

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16477)
> chore(ci): remove hdfs release

- src/meta/api/src/schema_api_impl.rs
- src/meta/app/src/schema/database.rs
- src/meta/app/src/schema/database_id_history_ident.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16487)
> refactor: SchemaApi::get_database_history()

- src/meta/api/src/schema_api.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/schema/database.rs
- src/meta/app/src/schema/mod.rs
- src/query/service/src/catalogs/default/mutable_catalog.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16488)
> refactor: test SchemaApi::get_tenant_history_database()

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
- src/meta/app/src/schema/table.rs
- src/meta/kvapi/src/kvapi/mod.rs
- src/meta/kvapi/src/kvapi/pair.rs
- src/query/service/src/interpreters/interpreter_vacuum_drop_tables.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16495)
> refactor: simplify `DroppedId`. Replace manual comparison with string comparison

- Cargo.lock
- Cargo.toml
fix https://github.com/datafuselabs/databend/issues/16490
the branch we used is simply rebased to the main 
1. to fix the issue fast, so we can get ride of datafusion as dep right now, and avoid other potential dep problems.
2. because the changes in the branch is temporary not suitable to pr to upstream.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16491)
> refactor: update dependency datafusion-orc.

- src/query/functions/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16509)
> chore(query): replace to datafuse-extras/dtparse

- Cargo.lock
- src/common/compress/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16513)
> chore: update source repo for async-compression

- src/meta/api/src/lib.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/util.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16516)
> refactor: remove get_pb_value()

- Cargo.lock
- Cargo.toml
chore(query): move recursion & backtrace crate to datafuse-extras
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16520)
> chore(query): move recursion & backtrace crate to datafuse-extras

- src/query/sql/src/planner/expression_parser.rs
- src/query/sql/src/planner/metadata.rs
- src/query/sql/src/planner/optimizer/statistics/collect_statistics.rs
- tests/sqllogictests/suites/base/05_ddl/05_0003_ddl_alter_table.test
- tests/sqllogictests/suites/mode/standalone/explain/bloom_filter.test
- tests/sqllogictests/suites/mode/standalone/explain/explain.test
- tests/sqllogictests/suites/mode/standalone/explain/prewhere_optimization.test
- tests/sqllogictests/suites/mode/standalone/explain_native/bloom_filter.test
- tests/sqllogictests/suites/mode/standalone/explain_native/explain.test
- tests/sqllogictests/suites/mode/standalone/explain_native/prewhere_optimization.test
Use column id as column `leaf_index`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16537)
> fix(query): fix column leaf_index

- src/common/base/src/lib.rs
- src/common/base/src/vec_ext.rs
- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/util.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16538)
> refactor: gc_dropped_db_by_id()

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/20_bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/actions/publish_binary/action.yml
- .github/actions/publish_deb/action.yml
- .github/actions/setup_bendsql/action.yml
- .github/scripts/notify_release.js
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16546)
> chore: update repo for workflows

- Cargo.lock
- Cargo.toml
- tests/sqllogictests/suites/query/functions/02_0005_function_compare.test
* fix json object compare cause panic
* Bump jsonb 0.4.3
- fixes: #16554
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16555)
> fix(query): fix json object compare cause panic

- src/query/service/src/locks/lock_manager.rs
1. check lock revision before watch delete to make sure we can get the delete event.
2. Fix the acquire lock timeout settings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16590)
> chore: check lock revision before watch delete

- src/query/ast/src/parser/common.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/expr-error.txt
- src/query/ast/tests/it/testdata/stmt-error.txt
- src/query/ast/tests/it/testdata/stmt.txt
chore(query): improve variable parser
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16599)
> chore(query): improve variable parser

- tests/sqllogictests/suites/mode/standalone/explain/table_sample.test
1. Remove dup tests
2. Make tests stable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16600)
> chore: refine table sample tests

- src/query/service/src/servers/http/middleware/session.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16644)
> refactor: some http APIs do not need sticky.

- src/query/pipeline/transforms/src/processors/transforms/sort/algorithm.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_k_way_merge_sort.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_multi_sort_merge.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge.rs
- src/query/service/src/pipelines/builders/builder_sort.rs
- src/query/service/src/pipelines/processors/transforms/transform_sort_spill.rs
- src/query/settings/src/settings_default.rs
- tests/sqllogictests/suites/query/join_small_block_size.test
benchmark  #15979
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16649)
> chore(query):  enable loser tree merge sort default

- src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
chore(query): remove hash join build detail status
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16674)
> chore(query): remove hash join build detail status

- src/meta/raft-store/src/ondisk/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16679)
> chore: upon startup, meta-service output human-readable error if trying to open future version on-disk data

- src/query/sql/src/planner/planner.rs
- tests/sqllogictests/suites/base/03_common/03_0016_insert_into_values.test
- tests/sqllogictests/suites/base/03_common/03_0045_insert_values_with_comment.test
fix: insert long sql again
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16684)
> fix: insert long sql again

- src/query/functions/src/aggregates/aggregate_kurtosis.rs
- src/query/functions/src/aggregates/aggregate_skewness.rs
- tests/sqllogictests/suites/query/functions/02_0000_function_aggregate_mix.test
chore: returns nan for aggregate_kurtosis and aggregate_skewness
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16688)
> chore(query): returns nan for aggregate_kurtosis and aggregate_skewness

- src/query/expression/src/evaluator.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16691)
> refactor: refine cast variant to map

- Cargo.lock
- src/common/tracing/Cargo.toml
- src/common/tracing/src/init.rs
- src/common/tracing/src/loggers.rs
backport PR #16249 to Release/v1.2.636 rc2. which revert log format
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16705)
> chore: backport PR #16249 to Release/v1.2.636 rc2

- src/query/ast/src/parser/token.rs
- tests/sqllogictests/suites/base/14_transaction/14_0005_snapshots.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16707)
> chore: remove transaction keyword

- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/mod.rs
- src/query/service/src/servers/http/v1/verify.rs
- tests/suites/1_stateful/09_http_handler/09_0007_token.py
Verify endpoint to replace current `select 1` / `ping` methods.
```
❯ curl -uroot: -XPOST http://localhost:8000/v1/verify | jq
{
"tenant": "test_tenant",
"user": "root",
"roles": [
"account_admin"
]
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16665)
> feat(query): add api /v1/verify

- src/query/service/src/servers/admin/v1/processes.rs
- src/query/service/src/servers/admin/v1/tenant_tables.rs
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/storages/system/src/processes_table.rs
chore(query): add current_query_id and database id for admin api
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16703)
> chore(query): add current_query_id and database id for admin api

- src/query/expression/src/converts/meta/index_scalar.rs
chore: index scalar support read-only variant 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16719)
> chore(query): index scalar support variant

- tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test
- tests/sqllogictests/suites/query/functions/02_0075_function_datetimes_tz.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16739)
> chore: remove flaky test

- Cargo.lock
- Cargo.toml
- src/query/service/Cargo.toml
This PR will remove not used dep `config`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16746)
> chore: Remove not used dep `config`

- Cargo.lock
- src/common/metrics/src/metrics/storage.rs
- src/common/storage/Cargo.toml
- src/common/storage/src/http_client.rs
* add new metrics `storage_http_requests_count` with host & method
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16769)
> feat(metrics): new storage_http_requests_count

- docker/it-hive/hive-docker-compose.yml
- docker/it-iceberg-rest/docker-compose.yaml
- tests/sqllogictests/scripts/docker-compose-iceberg-tpch.yml
- fixes: #16788
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16789)
> chore: remove obsolete version

- src/meta/README.md
- src/meta/raft-store/src/ondisk/data_version.rs
- src/meta/raft-store/src/ondisk/version_info.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16800)
> chore: update meta-service version info and compatibility doc

- src/common/tracing/src/init.rs
fix(query): fix broken file log layout
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16803)
> fix(query): fix broken file log layout

- README.md
Add stream to README
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16810)
> docs: add stream to readme

- src/common/tracing/src/init.rs
- src/common/tracing/src/loggers.rs
chore(query): keep queries detail and profile log format
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16822)
> chore(query): keep queries detail and profile log format

- src/meta/api/src/schema_api_impl.rs
- src/query/ast/src/ast/statements/database.rs
- src/query/ast/src/ast/statements/statement.rs
- src/query/ast/src/ast/statements/table.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/stmt.txt
- src/query/catalog/src/catalog/interface.rs
- src/query/service/src/catalogs/default/database_catalog.rs
- src/query/service/src/catalogs/default/immutable_catalog.rs
- src/query/service/src/catalogs/default/mutable_catalog.rs
- src/query/service/src/catalogs/default/session_catalog.rs
- src/query/service/src/databases/system/system_database.rs
- src/query/service/src/interpreters/access/management_mode_access.rs
- src/query/service/src/interpreters/access/privilege_access.rs
- src/query/service/tests/it/sql/exec/get_table_bind_test.rs
- src/query/service/tests/it/storages/fuse/operations/commit.rs
- src/query/service/tests/it/storages/system.rs
- src/query/service/tests/it/storages/testdata/columns_table.txt
- src/query/service/tests/it/storages/testdata/databases_with_history_table.txt
- src/query/sql/src/planner/binder/binder.rs
- src/query/sql/src/planner/binder/ddl/database.rs
- src/query/sql/src/planner/plans/plan.rs
- src/query/storages/hive/hive/src/hive_catalog.rs
- src/query/storages/iceberg/src/catalog.rs
- src/query/storages/system/src/databases_table.rs
- src/query/storages/system/src/lib.rs
- tests/sqllogictests/suites/base/06_show/06_0009_show_databases.test
- tests/suites/0_stateless/18_rbac/18_0003_db_visibility.result
- tests/suites/0_stateless/18_rbac/18_0003_db_visibility.sh
Support `SHOW DROP DATABASES [FROM <database>] [<show_limit>]`
Add new system table databases_with_history
Fix: #16801
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16811)
> feat(query): support SHOW DROP DATABASES

- src/query/pipeline/transforms/src/processors/transforms/transform_compact_no_split_builder.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0016_remote_alter_recluster.test
- tests/sqllogictests/suites/base/09_fuse_engine/09_0041_auto_compaction.test
This PR addresses the issue of potential fragmentation during the recluster process, preventing the system from entering an infinite recluster loop. 
By optimizing the reclustering logic, this update minimizes the likelihood of producing excessively **small fragments**, enhancing system stability and effectively preventing infinite loop issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16831)
> fix(storage): recluster endless loop

- src/query/storages/fuse/src/io/read/block/block_reader_merge_io_async.rs
Rename `ColumnCacheKeyBuilder::cache_cache` to `ColumnCacheKeyBuilder::cache_key`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16838)
> chore: fix typo in `ColumnCacheKeyBuilder`

- src/query/service/src/schedulers/scheduler.rs
- src/query/service/src/servers/flight/flight_service.rs
- src/query/service/src/servers/flight/v1/actions/init_query_env.rs
- src/query/service/src/servers/flight/v1/actions/init_query_fragments.rs
- src/query/service/src/servers/flight/v1/actions/start_prepared_query.rs
- src/query/service/src/servers/flight/v1/exchange/exchange_manager.rs
- src/query/service/src/servers/flight/v1/exchange/statistics_sender.rs
fix(cluster): fix the possibility of connection leak when the cluster state is broken.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16842)
> fix(cluster): fix the possibility of connection leak when the cluster state is broken.

- src/query/service/src/schedulers/scheduler.rs
- src/query/service/src/servers/flight/v1/actions/init_query_env.rs
- src/query/service/src/servers/flight/v1/actions/init_query_fragments.rs
- src/query/service/src/servers/flight/v1/actions/start_prepared_query.rs
- src/query/service/src/servers/flight/v1/exchange/exchange_manager.rs
- src/query/service/src/servers/flight/v1/exchange/statistics_sender.rs
backport PR #16842 to release/v1.2.636-rc4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16845)
> fix(cluster): fix the possibility of connection leak when the cluster state is broken. (#16842)

- src/query/service/src/clusters/cluster.rs
chore(cluster): disable parallel commit of cluster tasks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16851)
> chore(cluster): disable parallel commit of cluster tasks

- src/query/service/src/clusters/cluster.rs
backport PR #16851:
chore(cluster): disable parallel commit of cluster tasks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16852)
> chore(cluster): disable parallel commit of cluster tasks (#16851)

- Cargo.lock
- src/common/storage/Cargo.toml
- src/common/storage/src/http_client.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16849)
> fix(query): check storage request method with arg list-type

- src/common/tracing/src/loggers.rs
chore(query): remove useless new line for query log
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16860)
> chore(query): remove useless new line for query log

- src/query/storages/common/cache/src/read/cached_reader.rs
- src/query/storages/common/cache/src/read/loader.rs
- src/query/storages/fuse/src/io/snapshots.rs
- src/query/storages/fuse/src/table_functions/fuse_time_travel_size.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16863)
> chore: add some log

- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/storages/fuse/src/operations/read_partitions.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0102_distributed_pruning.sql
chore(query): add distributed pruning settings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16864)
> feat(query): add distributed pruning settings

- .github/actions/setup_license/action.yml
- .github/workflows/cloud.yml
- .github/workflows/dev.yml
- .github/workflows/production.yml
- .github/workflows/reuse.sqllogic.yml
- Cargo.toml
- src/binaries/query/ee_main.rs
- src/query/service/Cargo.toml
- src/query/service/tests/it/servers/mysql/mysql_handler.rs
enable CI for release/* branches
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16896)
> chore: enable ci workflow for branch "realease/*"

- Cargo.lock
sync cargo lock file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16905)
> chore: sync cargo lock

- tests/sqllogictests/suites/base/09_fuse_engine/09_0041_auto_compaction.test
https://github.com/databendlabs/databend/actions/runs/11964452217/job/33357430910
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16917)
> chore(ci): flaky test

- src/query/storages/fuse/src/operations/mutation/mutator/recluster_mutator.rs
more log for re-cluster operation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16915)
> chore: more recluster log

- src/query/storages/fuse/src/operations/read/parquet_rows_fetcher.rs
- src/query/storages/fuse/src/operations/read_partitions.rs
chore(query): add snapshot logs in read partitions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16918)
> chore(query): add snapshot logs in read partitions

- Cargo.lock
- Cargo.toml
- src/query/expression/src/kernels/group_by_hash/utils.rs
- src/query/service/src/servers/admin/admin_service.rs
- tests/suites/1_stateful/09_http_handler/09_0001_json_response.result
- tests/suites/1_stateful/09_http_handler/09_0001_json_response.sh
- fix flaky ci 09_0001_json_response.sh
add sleep, wait table drop success.
- bump rustls  version 0.23.18
- fixes: #16935
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16936)
> chore: bump rustls version 0.23.18

- src/query/pipeline/transforms/src/processors/transforms/sort/k_way_merge_sort_partition.rs
link #16923
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16934)
> chore: `k way merge sort` add boundary check to prevent process crash

- .github/workflows/release.yml
chore(ci): remove aarch64 musl in release
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16946)
> chore(ci): remove aarch64 musl in release

- .github/actions/publish_binary/action.yml
fix(ci): fix release dbg upload path
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16958)
> fix(ci): fix release dbg upload path

- .github/actions/setup_bendsql/action.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16965)
> chore(ci): upgrade bendsql

- src/query/sql/src/planner/binder/binder.rs
- src/query/storages/fuse/src/operations/changes.rs
- src/query/storages/fuse/src/operations/commit.rs
- src/query/storages/fuse/src/operations/common/processors/sink_commit.rs
- src/query/storages/stream/src/stream_table.rs
- src/query/storages/system/src/streams_table.rs
Refine error message for stream read offset snapshot.
```sql
mysql> select * from s;
ERROR 1105 (HY000): IllegalStream. Code: 2733, Text = Failed to read the offset snapshot: "1/95/_ss/3fa3378e5d5242579db5638d41b06b67_v4.mpk", maybe purged.
mysql> show full streams from default like 's';
+----------------------------+------+----------+---------+-----------+-------+---------+-------------+------------------------------------------------------------------------------------------------------+
| created_on                 | name | database | catalog | table_on  | owner | comment | mode        | invalid_reason                                                                                       | …
```
> chore(storage): refine error message for stream read offset snapshot

- Cargo.lock
- src/meta/app/src/principal/file_format.rs
- src/meta/app/src/principal/user_stage.rs
- src/query/ast/src/ast/statements/copy.rs
- src/query/ast/src/ast/statements/stage.rs
- src/query/ast/src/parser/copy.rs
- src/query/ast/src/parser/stage.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/testdata/stmt-error.txt
- src/query/ast/tests/it/testdata/stmt.txt
- src/query/catalog/src/table_context.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/src/sessions/query_ctx_shared.rs
- src/query/sql/src/planner/binder/bind_table_reference/bind_location.rs
- src/query/sql/src/planner/binder/copy_into_table.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/storages/common/stage/src/read/columnar/projection.rs
- src/query/storages/orc/src/copy_into_table/projection.rs
- src/query/storages/parquet/Cargo.toml
- src/query/storages/parquet/src/parquet_rs/copy_into_table/reader.rs
- src/query/storages/parquet/src/parquet_rs/copy_into_table/table.rs
- src/query/storages/parquet/src/parquet_rs/parquet_table/table.rs
- src/query/storages/parquet/src/parquet_rs/schema.rs
- tests/sqllogictests/suites/stage/options/case_sensitive_parquet.test
this pr support parquet format first,
for copy into table, add new copy option`COLUMN_MATCH_MODE = CASE_SENSITIVE | CASE_INSENSITIVE`, default is `CASE_INSENSITIVE`
for select from stage, add new parameter `case_sensitive=true|false` , default false
fixes #16897 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16963)
> feat: copy support option COLUMN_MATCH_MODE

- src/common/column/src/offset.rs
Solve the inconsistencies between code and comments which are proposed in #16973
- fixes: #16973
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16974)
> fix: solve some inconsistencies between code and comments

- src/query/storages/fuse/src/io/read/block/parquet/deserialize.rs
chore(query): remove block level info log
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16977)
> chore(query): remove block level info log

- tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test
- tests/sqllogictests/suites/query/functions/02_0075_function_datetimes_tz.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16980)
> chore(ci): fix some flaky test

- src/query/service/src/pipelines/processors/transforms/range_join/merge_join_state.rs
- src/query/service/src/pipelines/processors/transforms/range_join/transform_range_join.rs
- src/query/sql/src/executor/physical_plans/physical_join.rs
- src/query/sql/src/planner/binder/bind_table_reference/bind_join.rs
- tests/sqllogictests/suites/duckdb/join/iejoin/complex_range_join.test
- tests/sqllogictests/suites/duckdb/join/test_complex_range_join.test
- tests/sqllogictests/suites/duckdb/join_small_block/test_complex_range_join.test
- tests/sqllogictests/suites/mode/standalone/explain/join.test
- tests/sqllogictests/suites/mode/standalone/explain_native/join.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16988)
> chore(planner): refine physical join

- Cargo.lock
- scripts/setup/rust-toolchain.toml
chore(ci): rust toolchain 2024-11-28 build image
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17001)
> chore(ci): rust toolchain 2024-11-28 build image

- src/query/storages/system/Cargo.toml
- src/query/storages/system/src/tables_table.rs
Metadata query performance has regressed in some cases.  Suggest reverting to resolve quickly and fix properly next week.
Link pr: #16869
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17012)
> refactor: revert pr #16869

- .cargo/audit.toml
- src/query/service/src/pipelines/builders/builder_aggregate.rs
tweak `build_aggregate_partial`: reduce data might be exchanged during partial aggregation (assuming no spilling needed)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17038)
> refactor: tweak build_aggregate_partial

- .cargo/audit.toml
- src/query/expression/src/aggregate/mod.rs
- src/query/service/src/pipelines/builders/builder_aggregate.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
chore(query): add setting min_skip_partial_aggregation_capacity
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17040)
> chore(query): add setting min_skip_partial_aggregation_capacity

- src/query/storages/fuse/src/operations/read_data.rs
- src/query/storages/fuse/src/operations/read_partitions.rs
fix(query): fix thread leak
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17077)
> fix(query): fix thread leak

- src/query/sql/src/executor/table_read_plan.rs
- src/query/sql/src/planner/expression_parser.rs
- tests/sqllogictests/suites/query/case_sensitivity/name_hit.test
Fix name resolution bug in case-sensitive mode
- fixes: #17094 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17097)
> fix: name resolution bug in case-sensitive mode

- src/common/column/src/types/mod.rs
- src/common/column/src/types/native.rs
- src/common/io/tests/it/interval.rs
- src/common/native/src/write/primitive.rs
- src/query/functions/src/scalars/comparison.rs
- src/query/functions/src/scalars/interval.rs
- src/query/functions/tests/it/scalars/comparison.rs
- src/query/functions/tests/it/scalars/testdata/comparison.txt
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- tests/sqllogictests/suites/base/06_show/06_0005_show_functions.test
- tests/sqllogictests/suites/query/functions/02_0079_function_interval.test
- tests/sqllogictests/suites/query/functions/02_0080_function_interval_addsub.test
- fix: #17060
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17093)
> feat(query): support interval function

- src/query/service/src/interpreters/interpreter_vacuum_drop_tables.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17110)
> chore: add more log

- src/query/sql/src/planner/binder/bind_table_reference/bind_join.rs
- src/query/sql/src/planner/binder/select.rs
- tests/sqllogictests/suites/query/set_operator.test
Close: #17101
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17111)
> chore(planner): fix except and intersect operation

- src/query/ee/src/storages/fuse/operations/vacuum_temporary_files.rs
- src/query/ee_features/vacuum_handler/src/vacuum_handler.rs
- src/query/service/src/clusters/cluster.rs
- src/query/service/src/interpreters/hook/vacuum_hook.rs
- src/query/service/src/servers/flight/v1/exchange/statistics_receiver.rs
- src/query/service/src/servers/flight/v1/exchange/statistics_sender.rs
- src/query/service/src/servers/flight/v1/packets/packet_data_progressinfo.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/src/sessions/query_ctx_shared.rs
chore(query): improve hook vacuum temp after query
1. fetch spill meta files on parallel
2. exchange send/recv spill nums in progress info
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17125)
> chore(query): improve hook vacuum temp after query

- .github/actions/test_sqllogic_standalone_linux/action.yml
- .github/workflows/reuse.sqllogic.yml
- scripts/ci/ci-run-ee-sqllogic-tests.sh
- scripts/ci/ci-run-sqllogic-tests-cloud.sh
- scripts/ci/ci-run-sqllogic-tests-cluster.sh
- scripts/ci/ci-run-sqllogic-tests-minio.sh
- scripts/ci/ci-run-sqllogic-tests-native-minio.sh
- scripts/ci/ci-run-sqllogic-tests-native.sh
- scripts/ci/ci-run-sqllogic-tests.sh
- src/common/metrics/src/metrics/external_server.rs
- src/query/functions/src/lib.rs
- src/query/service/src/pipelines/processors/transforms/transform_udf_server.rs
- tests/sqllogictests/suites/udf_server/udf_server_test.test
chore(query): fix udf metrics
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17134)
> chore(query): fix udf metrics

- .github/actions/test_cloud_sqllogic_standalone_linux/action.yml
- .github/actions/test_ee_sqllogic_standalone_linux/action.yml
- .github/actions/test_sqllogic_standalone_linux_minio/action.yml
- .github/workflows/reuse.sqllogic.yml
- Cargo.lock
- Cargo.toml
- tests/sqllogictests/Cargo.toml
- tests/sqllogictests/src/client/mod.rs
- tests/sqllogictests/src/client/ttc_client.rs
- tests/sqllogictests/src/main.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0026_merge_into.test
- tests/sqllogictests/suites/base/09_fuse_engine/09_0036_merge_into_without_distributed_enable.test
feat: add ttc logical tests (tcp testing container)
internal docs:  https://datafuselabs.feishu.cn/wiki/TCx3wHNMSi6JjGkBKmAcz2NXn5d?from=from_copylink 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17160)
> feat(ci): add ttc (tcp testing container)

- .github/scripts/check_pr_title.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17189)
> chore(ci): auto add pr-backport label

- .github/scripts/check_pr_title.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17191)
> chore(ci): fix add label

- .github/actions/setup_build_tool/action.yml
- .github/workflows/reuse.linux.hive.yml
- .github/workflows/reuse.linux.yml
chore: debug sccache
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17205)
> chore(ci): upload sccache log for build (#17201)

- .github/actions/setup_build_tool/action.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17209)
> chore(ci): fix sccache log path

- .github/workflows/reuse.linux.hive.yml
- .github/workflows/reuse.linux.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17211)
> chore(ci): update sccache log artifact name

- src/common/storage/src/statistics.rs
- src/query/service/src/interpreters/interpreter_explain.rs
- src/query/service/src/interpreters/interpreter_factory.rs
- src/query/service/src/interpreters/interpreter_mutation.rs
- src/query/service/src/interpreters/interpreter_table_add_column.rs
- src/query/service/src/test_kits/fuse.rs
- src/query/sql/src/planner/optimizer/property/histogram.rs
- tests/sqllogictests/suites/mode/cluster/memo/aggregate_property.test
- tests/sqllogictests/suites/mode/cluster/memo/join_property.test
- tests/sqllogictests/suites/mode/cluster/memo/mix_property.test
- tests/sqllogictests/suites/mode/standalone/explain/eliminate_outer_join.test
- tests/sqllogictests/suites/mode/standalone/explain/join.test
- tests/sqllogictests/suites/mode/standalone/explain/lateral.test
- tests/sqllogictests/suites/mode/standalone/explain/selectivity/filter.test
- tests/sqllogictests/suites/mode/standalone/explain_native/explain.test
- tests/sqllogictests/suites/mode/standalone/explain_native/join.test
- tests/sqllogictests/suites/mode/standalone/explain_native/limit.test
- tests/suites/0_stateless/19_fuzz/19_0004_fuzz_filter.py
- tests/suites/0_stateless/19_fuzz/19_0004_fuzz_filter.result
* chore(planner): improve histogram cardinality estimation
* chore(test): update sqllogictest
* chore(test): add sqllogictest
* chore(test): update sqllogictest
* chore(test): add fuzz test
* chore(test): add physical plan info
* chore(test): update fuzz test
* chore(test): refine test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17210)
> chore(backport): improve histogram cardinality estimation (#17200)

- Cargo.lock
- src/common/column/Cargo.toml
- src/common/column/src/types/native.rs
- tests/sqllogictests/suites/query/functions/02_0079_function_interval.test
- fixes: #17214
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17215)
> fix(query): interval total microseconds add overflow check

- scripts/distribution/release-readme.txt
Replace databfuselabs to databendlabs
Rmove clickhouse
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17221)
> docs:Update release-readme.txt

- src/query/ast/src/ast/statements/warehouse.rs
- src/query/sql/src/planner/plans/ddl/warehouse.rs
fix(cluster): fix warehouse audit log not working with add cluster
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17219)
> fix(cluster): fix warehouse audit log not working with add cluster

- tests/suites/5_ee/01_vacuum/01_0001_ee_vacuum_kill_randomly.result
- tests/suites/5_ee/01_vacuum/01_0001_ee_vacuum_kill_randomly.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17222)
> chore: try fix flaky ci

- .github/scripts/bump_version.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17226)
> chore(ci): fix release find last tag

- .github/scripts/bump_version.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17227)
> chore(ci): fix release bump log

- .github/scripts/bump_version.js
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17228)
> chore(ci): stable release ignore patch versions

- .github/scripts/bump_version.js
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17232)
> chore(ci): better generate release

- .github/scripts/bump_version.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17238)
> chore(ci): fix release sha for backport

- tests/sqllogictests/src/util.rs
Starting the container may time out and return an error, but the container was actually started successfully, and retrying in this case will result in a conflict error. The PR checks if the container has started before retrying. If so, we stop the container first and try again to avoid the conflict error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17261)
> chore(sqllogictests): Check container and stop first to avoid conflict running

- .github/scripts/bump_version.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17277)
> chore(ci): fix release bump version

- .github/scripts/bump_version.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17278)
> chore(ci): fix release patch version

- .github/scripts/bump_version.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17281)
> chore(ci): fix gen next patch release

- .github/actions/pack_binaries/action.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17289)
> chore(ci): add bendsql binary to release

- Cargo.lock
- Cargo.toml
This PR is used to include a fix from opendal: https://github.com/apache/opendal/pull/5551
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17290)
> chore: Bump opendal to include a fix for gcs

- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/storages/fuse/src/operations/read_partitions.rs
- src/query/storages/fuse/src/pruning_pipeline/send_part_info_sink.rs
add enable_prune_cache setting
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17308)
> chore: add enable_prune_cache setting

- .github/actions/pack_binaries/action.yml
- .github/workflows/dev.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17335)
> chore(ci): fix pack binaries in release

- tests/suites/5_ee/01_vacuum/01_0001_ee_vacuum_kill_randomly.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17333)
> chore: fix flaky test

- src/query/functions/src/scalars/timestamp/src/datetime.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- tests/sqllogictests/suites/query/functions/02_0079_function_interval.test
timestamp_diff(TIMESTAMP, TIMESTAMP) -> INTERVAL
- fixes: #17270
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17381)
> feat(query): support timestamp diff return interval type

- src/query/ast/src/parser/expr.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/base/11_data_type/11_0006_data_type_decimal.test
fixes #17329 
fixes #17319
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17409)
> fix(query): fix resolve decimal

- src/query/service/src/pipelines/processors/transforms/window/transform_window.rs
- tests/sqllogictests/suites/query/window_function/window_ignore_nulls.test
- fixes: #17273
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17423)
> fix(query): if arg is Scalar::null or a null column ignore null will invalid

- .github/scripts/bump_version.js
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17429)
> ci: fix release type for nightly cron

- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/query/functions/02_0061_function_array.test
array function support variant type as argument
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17428)
> feat(query): array function support variant type as argument

- src/query/expression/src/evaluator.rs
- tests/sqllogictests/suites/base/03_common/03_0014_insert_into_select.test
fix variant value can not cast to not null type
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17434)
> fix(query): fix variant value can not cast to not null type

- src/common/metrics/src/metrics/storage.rs
- src/common/storage/src/http_client.rs
- ref: https://github.com/apache/opendal/issues/5325
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17431)
> feat(query): add bucket name to storage http request metrics

- src/query/expression/src/evaluator.rs
- src/query/expression/src/values.rs
- tests/sqllogictests/suites/base/03_common/03_0014_insert_into_select.test
refactor(query): refactor variant cast to types
continue of #17434 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17435)
> refactor(query): refactor variant cast to types

- benchmark/tpcds/README.md
- benchmark/tpcds/load_data.sh
- benchmark/tpch/README.md
- benchmark/tpch/gen_data.sh
- benchmark/tpch/load_data.sh
- benchmark/tpch/prepare_table.sh
- benchmark/tpch/tpch.sh
fix(doc): fix load tpcds tpch document
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17438)
> fix(doc): fix load tpcds tpch document

- src/query/ee/src/license/license_mgr.rs
- src/query/ee_features/resources_management/src/resources_management.rs
update enterprise edition license URL: https://docs.databend.com/guides/products/dee/
Ref: https://github.com/databendlabs/databend-docs/commit/dafc58f8d2bafce188dee640e67de7d17bf4c65f#diff-46fa28c436e4f25116a74ddb4afbbf1b2b30c5d5ba510f664e79f1a5c15420f8
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17445)
> chore: update enterprise edition license url

- .github/scripts/bump_version.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17454)
> ci: fix missing return for stable release

- .github/actions/publish_binary/action.yml
- .github/actions/publish_deb/action.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17456)
> ci: fix publish binary to R2

- src/query/pipeline/core/src/processors/shuffle_processor.rs
- src/query/service/src/pipelines/processors/transforms/window/partition/window_partition_partial_top_n_exchange.rs
- src/query/sql/src/executor/format.rs
- tests/sqllogictests/suites/mode/cluster/shuffle.test
- tests/sqllogictests/suites/mode/standalone/explain/window.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17453)
> fix(query): fix WindowPartitionTopNExchange painc with an empty block 

- .github/actions/publish_deb/action.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17486)
> ci: fix download deb packages

- .github/workflows/dev.yml
- scripts/distribution/deb/conf/distributions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17487)
> ci: fix gpg key for deb distribution

- src/tests/sqlsmith/src/runner.rs
- src/tests/sqlsmith/src/sql_gen/ddl.rs
- src/tests/sqlsmith/src/sql_gen/query.rs
- fixes: #12842
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17472)
> ci: add view sqlsmith test

- .github/workflows/reuse.benchmark.yml
chore(ci): fix benchmark comment failure
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17492)
> chore(ci): fix benchmark comment failure

- src/query/sql/src/planner/format/display_rel_operator.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/base/03_common/03_0047_select_udaf.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17500)
> fix(binder): different UDAF call must have unique display_name

- src/query/ee/src/license/license_mgr.rs
modify license url
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17513)
> chore: modify license url

- src/query/ast/src/ast/statements/explain.rs
- src/query/ast/src/ast/statements/statement.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/testdata/stmt.txt
- src/query/service/src/interpreters/interpreter_explain.rs
- src/query/sql/src/planner/binder/explain.rs
- src/query/sql/src/planner/optimizer/optimizer.rs
- tests/sqllogictests/suites/mode/standalone/explain/explain_verbose.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17518)
> feat(query): support `explain(DECORRELATED,verbose)`

- src/query/ast/src/ast/common.rs
- src/query/ast/src/ast/statements/table.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/stmt.txt
- tests/sqllogictests/src/util.rs
fix(query): fix display ast with quoted comments
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17529)
> fix(query): fix display ast with quoted comments

- src/query/storages/parquet/src/parquet_rs/copy_into_table/table.rs
- src/query/storages/parquet/src/parquet_rs/parquet_table/partition.rs
- src/query/storages/parquet/src/parquet_rs/parquet_table/table.rs
- src/query/storages/stage/src/stage_table.rs
- tests/sqllogictests/suites/stage/empty_file.test
this PR skip them when `read_partition`, because they should not be skipped in: 
-  list  stage,
-  remove stage
-  purge
-  copied files
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17522)
> feat: skip reading empty files when load/query location.

- src/query/storages/fuse/src/fuse_table.rs
remove timeout from snapshot hint refresh process, delegating timeout handling to the IO layer.
- fixes: #17531
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17532)
> refactor: remove timeout from snapshot hint refresh process

- .github/actions/pack_binaries/action.yml
- .github/actions/pack_deb/action.yml
- .github/actions/publish_binary/action.yml
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17544)
> ci: fix pack binaries

- src/query/sql/src/planner/binder/ddl/account.rs
- tests/sqllogictests/suites/management/management_calls.test
show roles rewrite kind is err
- fixes: #17517
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17547)
> fix(query): show roles rewrite kind is err

- src/query/storages/fuse/src/operations/common/processors/sink_commit.rs
If previous table snapshot not found during committing, report more user friendly error messages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17558)
> chore: polish error message in `CommitSink`

- src/query/sql/src/planner/binder/ddl/catalog.rs
- src/query/sql/src/planner/binder/ddl/column.rs
- src/query/sql/src/planner/binder/ddl/database.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/storages/iceberg/src/catalog.rs
- src/query/storages/information_schema/src/columns_table.rs
- src/query/storages/information_schema/src/key_column_usage_table.rs
- src/query/storages/information_schema/src/keywords_table.rs
- src/query/storages/information_schema/src/schemata_table.rs
- src/query/storages/information_schema/src/statistics_table.rs
- src/query/storages/information_schema/src/tables_table.rs
- src/query/storages/information_schema/src/views_table.rs
- src/query/storages/system/src/tables_table.rs
- tests/sqllogictests/suites/tpch_iceberg/utils.test
1. use unknown db return error
2. fix show tables outputs duplicated table names
3. fix in iceberg catalog select from other catalog error
4. information_schema view assign default catalog
5. show catalog support iceberg engine
- fixes: #17560
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17569)
> fix(query): show catalog support iceberg engine

- src/query/storages/fuse/src/table_functions/hilbert_clustering_information.rs
- tests/data/avro/gen.py
- tests/sqllogictests/suites/ee/07_hilbert_clustering/07_0000_recluster_final.test
Check cluster key id when check hilbert clustering information.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17577)
> fix(storage): hilbert cluster information

- .github/actions/setup_test/action.yml
- src/query/sql/src/planner/optimizer/filter/deduplicate_join_condition.rs
- src/query/sql/src/planner/optimizer/mod.rs
- src/query/sql/tests/optimizer/filter/deduplicate_join_condition_test.rs
- src/query/sql/tests/optimizer/filter/mod.rs
This PR add a unit test for deduplicate_join_condition.rs file, the cases include:
- Different data types in join conditions (INT32, INT64, FLOAT64)
- Multiple join conditions between the same tables
- Complex mixed join types with redundant conditions
- Edge case with empty join conditions after deduplication
No bugs found.
Parts of https://github.com/databendlabs/databend/issues/17551
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17585)
> chore(optimizer): deduplicate_join_condition unit tests

- src/query/expression/src/kernels/group_by_hash/method_fixed_keys.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
- src/query/sql/src/planner/optimizer/decorrelate/decorrelate.rs
- src/query/sql/src/planner/optimizer/decorrelate/subquery_rewriter.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/push_down_filter_join/mark_join_to_semi_join.rs
- tests/sqllogictests/suites/tpcds/queries.test
* Refactor `HashMethodFixedKeys::build_keys_vec` to centralize scattered unsafe in one place
* Fix `HashJoinBuildState::try_create` choosing incorrect hash_method
link #17516 #17539
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17588)
> fix: tpcds Q69 fail

- src/query/sql/src/planner/optimizer/mod.rs
- src/query/sql/tests/optimizer/filter/mod.rs
- src/query/sql/tests/optimizer/filter/normalize_disjunctive_filter_test.rs
Add normalize_disjunctive_filter unit tests, no bugs found.
Part of #17551 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17592)
> chore(optimizer): normalize_disjunctive_filter unit test

- src/query/catalog/src/catalog/interface.rs
- src/query/catalog/src/database.rs
- src/query/service/src/catalogs/default/database_catalog.rs
- src/query/service/src/catalogs/default/immutable_catalog.rs
- src/query/service/src/catalogs/default/mutable_catalog.rs
- src/query/service/src/catalogs/default/session_catalog.rs
- src/query/service/tests/it/sql/exec/get_table_bind_test.rs
- src/query/service/tests/it/storages/fuse/operations/commit.rs
- src/query/storages/hive/hive/src/hive_catalog.rs
- src/query/storages/iceberg/src/catalog.rs
- src/query/storages/iceberg/src/database.rs
- src/query/storages/system/src/tables_table.rs
optimize show tables from iceberg catalog
add new API list_tables_names return Vec<String>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17603)
> chore(query): optimize show tables from iceberg catalog

- src/meta/README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17606)
> chore(meta): add meta-meta compatibility chart svg

- src/query/storages/common/stage/src/read/cast.rs
bellow -> below
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17590)
> chore: update cast.rs

- src/query/service/tests/it/sql/planner/optimizer/data/README.md
- src/query/service/tests/it/sql/planner/optimizer/data/yaml/q1.yaml
- src/query/service/tests/it/sql/planner/optimizer/data/yaml/q3.yaml
- src/query/service/tests/it/sql/planner/optimizer/tpcds_test.rs
* snow_plan -> good_plan
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17611)
> chore(optimizer): snow_plan -> good_plan

- .github/workflows/dev.yml
- .github/workflows/main.yml
- .github/workflows/merge_group.yml
https://nvd.nist.gov/vuln/detail/CVE-2025-30066
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17613)
> ci: upgrade tj-actions/changed-files to v46

- src/query/service/src/servers/flight/v1/actions/init_query_env.rs
chore(cluster): remove useless log
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17614)
> chore(cluster): remove useless debug log

- Cargo.lock
- Cargo.toml
- src/query/ast/src/ast/statements/data_mask.rs
- src/query/ast/src/ast/statements/dictionary.rs
- src/query/ast/src/ast/statements/network_policy.rs
- src/query/ast/src/ast/statements/password_policy.rs
- src/query/ast/src/ast/statements/sequence.rs
- src/query/ast/src/ast/statements/stream.rs
- src/query/ast/src/ast/statements/task.rs
- src/query/service/src/interpreters/interpreter_dictionary_show_create.rs
- src/query/service/src/interpreters/interpreter_table_show_create.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/storages/system/src/columns_table.rs
- tests/sqllogictests/src/main.rs
- tests/sqllogictests/suites/base/06_show/06_0001_show_create_table.test
- tests/suites/0_stateless/02_ddl/02_0001_show_create_table.result
- tests/suites/0_stateless/02_ddl/02_0001_show_create_table.sh
fix https://github.com/databendlabs/bendsql/issues/608
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17615)
> fix(query): fix comment display

- src/query/storages/common/table_meta/src/meta/utils.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17636)
> fix: trim object preix error

- src/query/storages/system/src/databases_table.rs
- src/query/storages/system/src/tables_table.rs
optimize show tables with multi catalogs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17632)
> chore: optimize show tables with multi catalogs

- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/left_mark_join.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/probe_state.rs
- tests/sqllogictests/suites/query/join/left_mark.test
- tests/sqllogictests/suites/query/subquery.test
fix(query): fix incorrect left mark join schema
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17642)
> fix(query): fix incorrect left mark join schema

- .github/actions/pack_binaries/action.yml
Add bendsave in release so users can get it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17644)
> chore: Add bendsave in release

- src/meta/app/src/app_error.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17645)
> chore: make error message when CTAS committing failed more user-friendly

- tests/sqllogictests/src/error.rs
- tests/sqllogictests/src/main.rs
- tests/sqllogictests/src/util.rs
`testcontainers::core::client::docker_client_instance()` and `bollard::Docker::connect_with_local_defaults()` may return different docker client
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17665)
> ci: fix flaky ttc test 

- .github/workflows/cloud.yml
- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17674)
> ci: fix local benchmark artifact

- Cargo.lock
- src/query/sql/Cargo.toml
- src/query/sql/src/planner/optimizer/mod.rs
- src/query/sql/src/planner/optimizer/rule/mod.rs
- src/query/sql/src/planner/optimizer/rule/rewrite/mod.rs
- src/query/sql/tests/optimizer/rule/mod.rs
- src/query/sql/tests/optimizer/rule/push_down_filter_join_test.rs
- src/query/storages/common/cache/benches/read_cache_content.rs
Add  join filter pushdown tests(left join/right join/full join), some test case is inspried from TPC-DS.
- part of #17551 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17676)
> chore(optimizer): add rule/push_down_filter_join unit test

- src/common/base/src/http_client.rs
Enforce http client to use native tls to avoid been changed over features.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17686)
> fix: Enforce storage http client to use native tls

- Cargo.lock
- Cargo.toml
- src/common/base/Cargo.toml
- src/common/base/src/http_client.rs
- src/common/grpc/src/dns_resolver.rs
Some users have very bad infra setups that can fail to respond to a DNS query. This PR fixed this by:
- only query ipv4 addresses.
- Increase the cache size
- Set min_ttl for both positive and negative results.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17699)
> fix: DNS resolve error in some cases

- src/meta/types/src/cluster.rs
- src/meta/types/tests/it/cluster.rs
- src/query/catalog/src/plan/partition.rs
- src/query/catalog/tests/it/partitions.rs
- src/query/catalog/tests/it/testdata/partition-reshuffle.txt
- src/query/management/tests/it/warehouse.rs
- src/query/service/src/clusters/cluster.rs
- src/query/service/src/schedulers/fragments/fragmenter.rs
- src/query/service/src/schedulers/fragments/plan_fragment.rs
- src/query/service/src/test_kits/cluster.rs
chore(query): add cache id for distribute scheduler
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17708)
> chore(query): add cache id for distribute scheduler

- Cargo.lock
- src/query/storages/system/Cargo.toml
- src/query/storages/system/src/tables_table.rs
- tests/sqllogictests/suites/tpch_iceberg/utils.test
If only get name field we can mock a NullTable to optimize load table from iceberg
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17700)
> chore: optimize select name from system.tables

- src/query/sql/src/planner/binder/aggregate.rs
- src/query/sql/src/planner/binder/scalar_common.rs
- tests/sqllogictests/suites/base/03_common/03_0003_select_group_by.test
- tests/sqllogictests/suites/mode/standalone/explain/aggregate.test
- tests/sqllogictests/suites/mode/standalone/explain_native/aggregate.test
chore(query): allow group by constant literal
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17711)
> chore(query): allow group by constant literal

- docker/service/query.Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17715)
> ci: add hadoop envs for query image

- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17717)
> ci: tmp disable local benchmark

- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17718)
> ci: fix local benchmark

- src/query/expression/src/filter/selector.rs
- tests/sqllogictests/suites/base/20+_others/20_0010_expression_string_like.test
Fix: https://github.com/databendlabs/databend/issues/17723
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17722)
> fix(query): process_like directly unwrap is not safe

- scripts/build/build-pkg.sh
Add a script that allows users to package locally on CentOS 8 and Red Hat Enterprise 8.
- fixes: #17736 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17737)
> chore: add local build databend package

- src/query/ast/src/parser/expr.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/expr-error.txt
- src/query/ast/tests/it/testdata/expr.txt
- src/query/ast/tests/it/testdata/stmt-error.txt
- src/query/functions/src/scalars/mathematics/src/math.rs
- src/query/functions/src/scalars/timestamp/src/interval.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- tests/sqllogictests/suites/query/functions/02_0079_function_interval.test
1. Delete function epoch(int)->interval
2. add some date function alias
3. add trunc as truncate function alias
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17730)
> chore(query): delete no useful function epoch(Int64Type)->IntervalType

- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/sql/src/planner/optimizer/optimizer.rs
- src/query/sql/src/planner/optimizer/optimizer_api.rs
- src/query/sql/src/planner/optimizer/optimizers/cascades/cascade.rs
- src/query/sql/src/planner/optimizer/optimizers/cascades/tasks/explore_expr.rs
- src/query/sql/src/planner/optimizer/optimizers/cascades/tasks/explore_group.rs
- src/query/sql/src/planner/optimizer/optimizers/cascades/tasks/mod.rs
- src/query/sql/src/planner/optimizer/optimizers/cascades/tasks/optimize_expr.rs
- src/query/sql/src/planner/optimizer/optimizers/cascades/tasks/optimize_group.rs
- src/query/sql/src/planner/optimizer/optimizers/cascades/tasks/task.rs
- src/query/sql/src/planner/optimizer/optimizers/cascades/tasks/task_manager.rs
- src/query/sql/src/planner/optimizer/optimizers/hyper_dp/dphyp.rs
- src/query/sql/src/planner/optimizer/optimizers/hyper_dp/mod.rs
- src/query/sql/src/planner/optimizer/optimizers/mod.rs
- src/query/sql/src/planner/optimizer/optimizers/operator/decorrelate/subquery_decorrelator.rs
- src/query/sql/src/planner/optimizer/optimizers/recursive/recursive.rs
- src/query/sql/src/planner/optimizer/pipeline/pipeline.rs
- add new settings optimizer_skip_list for debug the optimizers affects
```
-- Comma-separated(,) list of optimizer names to skip during query optimization
set optimizer_skip_list='DPhpyOptimizer,xxOptimizer,yyOptimizer'; 
```
```
2025-04-10 18:01:03.761 | [0] WARN - 2f639bf3-1da2-4e83-9c26-96da6b14c59b -  Skipping optimizer: DPhpyOptimizer (found in optimizer_skip_list: DPhpyOptimizer)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17750)
> feat(optimizer): add optimizer skip list

- src/query/sql/src/planner/optimizer/optimizers/hyper_dp/dphyp.rs
- No logic changed, only refactoring dphyp.rs to make the functions more modular.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17753)
> refactor(optimizer): refine hyper_dp/dphyp.rs

- src/query/storages/stage/src/read/row_based/processors/decompressor.rs
add the path to detail of ErrorCode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17732)
> chore: show file path when copy decompress fail.

- src/query/sql/src/planner/binder/bind_mutation/mutation_expression.rs
- src/query/sql/src/planner/binder/binder.rs
- src/query/sql/src/planner/optimizer/ir/expr/s_expr.rs
- src/query/sql/src/planner/optimizer/optimizers/operator/decorrelate/subquery_decorrelator.rs
- src/query/sql/src/planner/plans/operator.rs
- src/query/sql/src/planner/plans/scalar_expr.rs
- Move out some functions from s_expr.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17767)
> refactor(optimizer): s_expr.rs

- src/query/service/tests/it/sql/planner/optimizer/ir/expr/mod.rs
- src/query/service/tests/it/sql/planner/optimizer/ir/expr/visitor.rs
- src/query/service/tests/it/sql/planner/optimizer/ir/mod.rs
- src/query/service/tests/it/sql/planner/optimizer/optimizers/operator/filter/deduplicate_join_condition_test.rs
- src/query/service/tests/it/sql/planner/optimizer/optimizers/operator/filter/infer_filter_test.rs
- src/query/service/tests/it/sql/planner/optimizer/optimizers/operator/filter/normalize_disjunctive_filter_test.rs
- src/query/service/tests/it/sql/planner/optimizer/optimizers/rule/filter_rules/push_down_filter_join_test.rs
- src/query/service/tests/it/sql/planner/optimizer/test_utils.rs
- src/query/sql/src/planner/optimizer/ir/expr/mod.rs
- src/query/sql/src/planner/optimizer/ir/expr/visitor.rs
- src/query/sql/src/planner/optimizer/ir/mod.rs
- Add SExpVisitor but not applied to the code
- Refactor the unit test of optimizer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17768)
> feat(optimizer): SExpr visitor

- tests/databend-test
- tests/sqllogictests/src/util.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17769)
> ci: fix test with ttc conainter

- tests/sqllogictests/src/util.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17772)
> ci: fix start test container

- src/query/functions/src/aggregates/aggregate_sum.rs
- Fix the boolean logic in the implementation to correctly handle decimal overflow checking in aggregate SUM operations.
- Rename the generic parameter from `OVERFLOW` to `SHOULD_CHECK_OVERFLOW` to better reflect its purpose.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17773)
> refactor: `DecimalSumState` overflow handling in SUM aggregation

- src/query/service/tests/it/sql/planner/optimizer/test_utils.rs
- src/query/service/tests/it/sql/planner/optimizer/tpcds_test.rs
- Refine the tpcds_test.rs to more readable
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17777)
> refactor(optimizer): refine the tpcds tests

- Cargo.lock
- Cargo.toml
- src/meta/raft-store/src/snapshot_config.rs
- src/meta/service/src/meta_service/meta_node.rs
- src/query/expression/src/types/timestamp.rs
- src/query/service/src/pipelines/builders/builder_on_finished.rs
- src/query/service/src/servers/admin/v1/system.rs
- src/query/sql/src/planner/planner.rs
part of #16706
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17776)
> chore: upgrade outdated dependencies 

- src/query/service/src/table_functions/mod.rs
- src/query/service/src/table_functions/system/mod.rs
- src/query/service/src/table_functions/system/table_statistics.rs
- src/query/service/src/table_functions/table_function_factory.rs
- tests/sqllogictests/suites/base/20+_others/20_0021_func_table_statistics.test
- Add `table_statistics(<database_name>[, table_name])` table to help debug optimizer
```
select * from table_statistics('mydb');
+----------+--------+--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| database | table  | engine | statistics_json                                                                                                                                                                                     |
+----------+--------+--------+------------------------------------------------------------------------------------- …
```
> feat(query): table_statistics(<database_name>[, table_name]) table functions

- .github/workflows/release.yml
- docker/service/query.Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17786)
> chore(ci): remove hdfs from docker image

- src/meta/app/src/principal/file_format.rs
- src/query/storages/stage/src/append/parquet_file/writer_processor.rs
- src/query/storages/stage/src/compression.rs
- tests/sqllogictests/src/util.rs
- tests/sqllogictests/suites/stage/formats/parquet/options/parquet_compression.test
- tests/sqllogictests/suites/stage/unload.test
fix(query): don't check file format in proto-conv
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17793)
> fix(query): don't check file format in proto-conv

- src/query/service/src/persistent_log/global_persistent_log.rs
chore: refine error handling in persistent log table
Retry on change part is meaningless.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17792)
> chore: refine error handling in persistent log table

- .github/actions/setup_build_tool/action.yml
- src/query/expression/src/sampler/fixed_rate_sampler.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17790)
> chore(ci): change the sccache log level to debug

- .github/workflows/cloud.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17796)
> ci: fix build feature for benchmark

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17799)
> ci: use larger runner for release

- Cargo.lock
- Cargo.toml
Bump opendal to 0.53.1 for better performance and tracing support.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17817)
> feat: Bump opendal to 0.53.1

- .github/actions/setup_build_tool/action.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17822)
> ci: fix check system info

- src/meta/semaphore/src/acquirer/acquirer.rs
- src/meta/semaphore/src/meta_event_subscriber/processor.rs
- src/meta/semaphore/src/meta_event_subscriber/subscriber.rs
- src/meta/semaphore/src/queue/semaphore_queue.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17831)
> chore: add more info logging to semaphore

- .github/actions/pack_deb/action.yml
- scripts/distribution/nfpm-meta.yaml
- scripts/distribution/nfpm-query-dbg.yaml
- scripts/distribution/nfpm-query.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17832)
> ci: fix pack deb

- Cargo.lock
- src/query/catalog/src/catalog/interface.rs
- src/query/service/src/catalogs/default/session_catalog.rs
- src/query/service/src/interpreters/interpreter_database_create.rs
- src/query/service/src/interpreters/interpreter_database_drop.rs
- src/query/service/src/interpreters/interpreter_table_create.rs
- src/query/service/src/interpreters/interpreter_table_drop.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/storages/hive/hive/src/hive_catalog.rs
- src/query/storages/iceberg/Cargo.toml
- src/query/storages/iceberg/src/catalog.rs
- src/query/storages/system/src/tables_table.rs
- tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables.test
- tests/sqllogictests/suites/tpch_iceberg/utils.test
1. external catalog should not create ownership kv
2. Default catalog can not create iceberg table engine
3. Iceberg catalog can not create table that engine is not equal Iceberg.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17837)
> fix(query): Default catalog can not create iceberg table engine

- src/common/storage/src/runtime_layer.rs
In the current Databend codebase, if OpenDAL's operations are not forwarded to the global IO runtime, all subsequent requests will hang. This PR addresses and resolves that issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17842)
> fix: Forward list operations to runtime to avoid hang

- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/stmt.txt
- tests/sqllogictests/suites/tpch_iceberg/table_function.test
main:
```sql
USE CATALOG <catalog_name>
```
PR:
```sql
[SET | USE] CATALOG <catalog_name>
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17844)
> chore:(query): support [SET | USE] CATALOG <catalog_name>

- src/query/service/src/servers/mysql/mysql_interactive_worker.rs
- src/query/service/src/sessions/session.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
Add sampled trace support.
This PR adds a new settings for databend which can control `trace_sample_rate`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17850)
> feat: Add sampled trace support

- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/execute_state.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
fix(query): Fix incorrect memory tracking in the HTTP handler
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17857)
> fix(query): Fix incorrect memory tracking in the HTTP handler

- src/query/service/src/pipelines/builders/builder_join.rs
- src/query/service/src/pipelines/pipeline_builder.rs
- No logic changes, only refactoring
This PR reorganizes the physical plan matching logic in the `build_pipeline` method to improve code clarity and maintainability:
```
Data Source Plans
Relational Operators
Data Movement & Distribution
Data Modification Operations
Data Maintenance Operations
Special Processing Operations
Invalid Plans
```
- part of https://github.com/databendlabs/databend/issues/17865
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17866)
> refactor(query): refactor physical plan organization in pipeline builder for better readability

- src/meta/store/src/lib.rs
- src/query/service/src/sessions/queue_mgr.rs
Based on PR https://github.com/databendlabs/databend/pull/17878, add time-based semaphore support for query queueing to optimize the work load on meta.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17879)
> chore(query): use time base semaphore

- src/common/exception/src/exception_code.rs
- src/query/management/src/lib.rs
- src/query/management/src/workload/mod.rs
- src/query/management/src/workload/workload_api.rs
- src/query/management/src/workload/workload_mgr.rs
- src/query/management/tests/it/workload.rs
This PR introduces atomic workload group metadata management, providing essential functionalities such as create, drop, rename, alter quotas, and get operations. These capabilities form the foundation for supporting workload SQL, ensuring consistent and reliable metadata handling. The implementation guarantees atomicity for all operations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17880)
> feat(query): atomic workload group metadata management

- benchmark/clickbench/benchmark_local.sh
- benchmark/clickbench/hits/load.sql
- benchmark/clickbench/tpch/load.sql
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17889)
> chore: fix loading data for benchmark

- benchmark/clickbench/tpch/load.sql
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17899)
> chore: fix load tpch100 for benchmark

- .github/actions/setup_docker/action.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17915)
> chore: fix release ghcr repo

- .github/workflows/cloud.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17916)
> chore(ci): fix permissions for cloud build

- .github/actions/setup_docker/action.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17917)
> chore: fix ci login for ghcr

- src/meta/api/src/schema_api_impl.rs
- src/meta/api/src/schema_api_test_suite.rs
By checking  that database meta being cleaned is marked as dropped, ensures proper behavior when `gc_dropped_db_by_id` and   `undrop_database` are executed concurrently on the same database.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17901)
> fix: Handle concurrent `gc_dropped_db_by_id` and `undrop_database` operations safely

- src/meta/app/src/schema/create_option.rs
- src/query/ast/src/ast/statements/task.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/stmt-error.txt
- src/query/ast/tests/it/testdata/stmt.txt
- src/query/functions/src/aggregates/aggregate_function_factory.rs
- src/query/functions/src/aggregates/aggregator.rs
- src/query/service/src/interpreters/interpreter_task_create.rs
- src/query/sql/src/planner/binder/ddl/task.rs
- src/query/sql/src/planner/plans/ddl/task.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/task/task_notification_test.test
Below is a brief changelog summary for the changes:
1. support `create or replace` for task 
2. some functions behavior changes:
- iff alias for if function
- `greatest` and `least` will return error if input args contains null
-  add `greatest_ignore_nulls` and `least_ignore_nulls` which ignore null (works as the previous behavior of greatest and least)
- add `var_pop`, `variance_pop` alias for function `covar_pop`
-  add `var_samp`, `variance_samp`` alias for function `covar_samp`
-  support `insert overwrite into` syntax, works same as `insert overwrite`
- - - …
> chore(query): add some function alias

- src/common/exception/src/exception_code.rs
- tests/sqllogictests/suites/ee/04_ee_inverted_index/04_0000_inverted_index_base.test
- tests/sqllogictests/suites/query/functions/02_0060_function_geometry.test
- tests/sqllogictests/suites/query/functions/02_0076_function_geography.test
This PR reorganizes error codes in `exception_code.rs` into logical categories with clear documentation:
- Grouped error codes by functional area (Database, Table, User Management, etc.)
- Added descriptive doc comments for all error codes
- Maintained original error code values for backward compatibility
- Added test to verify error code uniqueness
Fixed duplicate error codes:
- `1118`: Kept for `UnclusteredTable`, moved `ColumnReferencedByInvertedIndex` to `1111`
- `3001`/`3002`: Kept for storage errors, moved script errors to new codes:
- `ScriptSemanticError` moved from `3001` to `3128`
- `ScriptExecutionError` moved from `3002` to `3129`
- - - …
> chore(query): refine the exception code category

- Cargo.lock
- src/meta/store/Cargo.toml
- src/meta/store/src/lib.rs
- src/query/management/src/warehouse/warehouse_api.rs
- src/query/management/src/warehouse/warehouse_mgr.rs
- src/query/service/src/clusters/cluster.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17938)
> refactor: Simplify dereferencing logic in MetaStore and update async methods for better clarity

- src/query/service/tests/it/pipelines/filter/random_filter_expr.rs
- src/query/service/tests/it/sql/planner/optimizer/test_utils.rs
- src/query/sql/src/planner/binder/bind_context.rs
- src/query/sql/src/planner/binder/bind_table_reference/bind_table_function.rs
- src/query/sql/src/planner/binder/column_binding.rs
- src/query/sql/src/planner/binder/select.rs
- src/query/sql/src/planner/optimizer/optimizers/operator/aggregate/normalize_aggregate.rs
- src/query/storages/parquet/src/parquet_reader/reader/row_group_reader.rs
- src/query/storages/parquet/src/source.rs
- tests/sqllogictests/suites/query/lateral.test
continue #17535 
- Disable lazy topn optimization in srf lateral functions
- Disable parquet read data cache for stage source
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17945)
> fix(query): fix lazy topn in srf functions

- src/query/service/src/databases/system/system_database.rs
- src/query/service/tests/it/storages/system.rs
- src/query/sql/src/planner/binder/ddl/column.rs
- src/query/storages/system/src/columns_table.rs
- src/query/storages/system/src/tables_table.rs
- tests/sqllogictests/suites/tpch_iceberg/utils.test
In main branch :
```sql
root@localhost:8000/ctl/abc> show tables;
show tables
╭───────────────╮
│ Tables_in_abc │
│     String    │
├───────────────┤
│ t1            │
╰───────────────╯
1 row read in 0.050 sec. Processed 1 row, 254 B (20 rows/s, 4.96 KiB/s)
root@localhost:8000/ctl/abc> show columns from t1;
error: APIError: QueryFailed: [1003]Unknown database 'abc'
```
In PR:
```sql
root@localhost:8000/ctl/default> show columns from abc.t1;
show columns from abc.t1
╭────────────────────────────────────────────────────╮
│  Field │   Type  │  Null  │ Default │ Extra │  Key │
│ String │  String │ String │  String │  Null │ Null │
├────────┼─────────┼────────┼─────────┼───────┼──────┤
│ c1     │ …
```
> refactor: columns support display other catalog column info

- src/common/base/src/runtime/runtime_tracker.rs
- src/common/license/src/license.rs
- src/query/service/src/sessions/query_ctx.rs
Add and check the System History Enterprise Feature when querying system_history data, in preparation for enabling the System History functionality.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17961)
> chore(query): add system history enterprise feature

- .github/workflows/release.yml
- src/query/functions/src/lib.rs
- src/query/sql/src/planner/binder/window.rs
- src/query/sql/src/planner/semantic/grouping_check.rs
- tests/sqllogictests/suites/query/aggregate.test
fix(query): allow window expr in group by query
1. The commit enhances the query planner to support window expressions in group by queries, improving the flexibility and capability of SQL queries within the system.
2. Additional tests have been introduced to ensure the correctness of the new functionality.
3. enable bendpy releaser
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17962)
> fix(query): allow window expr in group by query

- src/query/service/src/auth.rs
- src/query/service/src/servers/http/middleware/panic_handler.rs
- src/query/service/src/servers/http/middleware/session.rs
- src/query/service/src/servers/http/v1/catalog/get_database_table.rs
- src/query/service/src/servers/http/v1/catalog/list_database_table_fields.rs
- src/query/service/src/servers/http/v1/catalog/list_database_tables.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/servers/http/v1/query/execute_state.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/http_query_context.rs
- src/query/service/src/servers/http/v1/query/http_query_manager.rs
- src/query/service/src/servers/http/v1/query/page_manager.rs
- src/query/service/src/servers/http/v1/session/client_session_manager.rs
- src/query/service/src/servers/http/v1/session/login_handler.rs
- src/query/service/src/servers/http/v1/session/logout_handler.rs
- src/query/service/src/servers/http/v1/session/refresh_handler.rs
- src/query/service/src/servers/http/v1/session/token.rs
- src/query/service/src/servers/http/v1/stage.rs
- src/query/service/src/servers/http/v1/streaming_load.rs
- src/query/service/src/servers/http/v1/users.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- src/query/sql/src/planner/binder/binder.rs
- src/query/storages/fuse/src/io/snapshots.rs
- tests/sqllogictests/scripts/prepare_iceberg_test_data.py
- tests/suites/0_stateless/18_rbac/18_0011_alter_own_username.sh
- tests/suites/1_stateful/09_http_handler/09_0005_kill.result
- tests/suites/1_stateful/09_http_handler/09_0006_route_error.result
- tests/suites/1_stateful/09_http_handler/09_0007_token.result
- Improve http related log and error message
```
[AUTH] ...
[HTTP-PANIC] ...
[HTTP-SESSION] ...
[HTTP-CATALOG] ...
[HTTP-QUERY] ...
[HTTP-STAGE] ...
[HTTP-STREAMING-LOAD] ...
[HTTP-USERS] ...
[FUSE-SNAPSHOT] ...
[SQL-BINDER] ...
```
- parts of https://github.com/databendlabs/databend/issues/17964
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17958)
> chore: improve the http handler log and error message

- .github/workflows/bindings.python.yml
- scripts/setup/dev_setup.sh
- src/common/cloud_control/src/task_client.rs
chore(query): add encoding/decoding size in task client
```
/// Grpc default configuration.
/// The hard limit of maximum message size the client or server can **send**.
pub const MAX_ENCODING_SIZE: usize = 32 * 1024 * 1024;
/// The hard limit of maximum message size the client or server can **receive**.
pub const MAX_DECODING_SIZE: usize = 32 * 1024 * 1024;
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17965)
> chore(query): add encoding/decoding size in task client

- src/query/ee/src/license/license_mgr.rs
- src/query/service/src/interpreters/interpreter.rs
Change license validation error log to ERROR level.
Several enterprise features don't affect functional correctness but impact performance significantly. Users have experienced unexplained performance degradation due to expired/miss-configured licenses.
This change helps users identify such issues faster.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17967)
> chore: improve license validation log message

- src/common/base/src/runtime/runtime.rs
chore(base): remove useless log for runtime
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17992)
> chore(base): remove useless log for runtime

- src/query/ee/src/storages/fuse/operations/vacuum_table_v2.rs
- src/query/service/src/interpreters/interpreter.rs
- src/query/service/src/interpreters/interpreter_select.rs
- src/query/service/src/pipelines/executor/pipeline_executor.rs
- src/query/service/src/pipelines/executor/processor_async_task.rs
- src/query/service/src/pipelines/executor/query_pipeline_executor.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_aggregate_partial.rs
- src/query/service/src/pipelines/processors/transforms/aggregator/transform_single_key.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/src/sessions/queue_mgr.rs
- src/query/service/tests/it/pipelines/executor/pipeline_executor.rs
- src/query/sql/src/executor/table_read_plan.rs
- src/query/sql/src/planner/planner.rs
- src/query/sql/src/planner/plans/copy_into_table.rs
- src/query/storages/fuse/src/fuse_table.rs
- src/query/storages/fuse/src/operations/mutation/mutator/block_compact_mutator.rs
- src/query/storages/fuse/src/operations/read/fuse_source.rs
- src/query/storages/fuse/src/operations/read_partitions.rs
- src/query/storages/fuse/src/operations/recluster.rs
- src/query/storages/fuse/src/pruning/fuse_pruner.rs
- tests/data/avro/gen_logical.py
- tests/metactl/test-metactl-restore-new-cluster.py
- tests/sqllogictests/scripts/prepare_iceberg_test_data.py
- tests/suites/1_stateful/00_stage/00_0004_copy_with_max_files.result
- Unifies and clarifies log and status messages with subsystem tags (e.g., `[FUSE-VACUUM2]`, `[INTERPRETER]`).
- Improves log&error&status message clarity.
- No functional or behavioral changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17993)
> chore(query): refine the log and error message

- src/meta/semaphore/src/queue/semaphore_queue.rs
Up to 1.2.742 datbend-meta might send a kv change event befoore
initialization events in a watch stream, which is a bug.
This cause the meta client side semaphore receives duplicated `add` kv
event, such as two `key=foo, None -> Some(val)` events. Such events
sequence inserts duplicated semaphore permit in the acquired queue and
waiting queue. And a `remove` kv event just remove one of the two
permit, which leads to a never permit that can never be released.
In this commit, when a duplciated seq permit is received, just skip it,
instead of insert it into `waiting` queue.
- - - …
> fix(meta-semaphore): skip dup seq semaphore permit

- src/query/storages/common/cache/src/manager.rs
backport: 
- pr #18002
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18009)
> fix(cache): fix improper config usage in cache manager (#18002)

- src/meta/service/src/api/grpc/grpc_service.rs
Before this commit, a watch stream is built in two steps:
- add a watch sender to the dispatcher,
- then send a bunch of kvs for initialization.
But there is a gap between these two steps. For example, a key might be
inserted between these two steps. In such a case, the client will receive
two `add` events, such as: `key=foo, None -> Some(val)`, one of them is
emitted when `key=foo` is added, the other is emitted by the
initialization process.
These two identical events will confuse the client in some use cases,
such as the meta-based semaphore does not expect two identical
events to be received.
In this commit, the two steps of setting up a watch stream are done
atomically, with the state …
> fix(meta-service): when setting up a watch stream, lock state machine

- src/query/service/src/servers/http/v1/session/client_session_manager.rs
1.  fix: temp table cleaner not work.
2. add related log 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18051)
> fix: temp table cleaner not work.

- src/common/tracing/src/predefined_tables/history_tables.rs
The log_history table is always included as the source table. If the user specifies a retention period for log_history, that user-defined retention will be applied. If no retention period is specified by the user, a default retention of 7 days (24 x 7 hours) will be used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18054)
> chore: allow user define `log_history` table's retention

- tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test
Link: https://github.com/databendlabs/databend/pull/18064
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18065)
> chore(query): add trunc logic test about Standardize Interval Kind String Representations

- src/common/base/src/runtime/runtime_tracker.rs
- src/common/base/src/runtime/workload_group.rs
- src/query/management/src/workload/mod.rs
- src/query/management/src/workload/workload_resource.rs
- src/query/service/src/history_tables/global_history_log.rs
- src/query/service/src/interpreters/interpreter.rs
- src/query/service/src/servers/flight/v1/actions/init_query_env.rs
- src/query/service/src/servers/flight/v1/packets/packet_publisher.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/src/sessions/queue_mgr.rs
- src/query/service/src/sessions/session.rs
- tests/suites/5_ee/09_workload_group/09_0000_workload_group.sh
feat(query): support max_concurrency quota for workload group
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18052)
> feat(query): support max_concurrency quota for workload group

- src/query/service/src/interpreters/interpreter.rs
Also log at warning level if license validation failed, to ensure the message could be propagated to client applications, e.g., BendSQL and MySQL interactive sessions, etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18066)
> chore: tweak license validation logging

- src/query/functions/src/scalars/string.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- tests/sqllogictests/suites/query/functions/02_0025_function_strings_locate.test
This PR implements Oracle-compatible `INSTR` string search functionality in Databend, supporting both three-parameter and four-parameter variants to enhance SQL compatibility with Oracle databases.
```sql
INSTR(string, substring [, pos] [, occurrence])
```
Finds the position of a substring within a string starting from a specified position.
**Parameters:**
- `string`: The input string to search within (can be NULL)
- `substring`: The substring to locate (can be NULL)
- `pos`: The starting position for the search (1-based index)
- Positive number: Search forward from left to right
- Negative number: Search backward from right to left
- Zero: Treated as 1 (start from beginning)
**Returns:**
- …
> chore(query): Implement Oracle-compatible `INSTR` Function in Databend

- src/query/service/src/interpreters/interpreter.rs
Tweaks license validation logs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18092)
> chore: tweak logs

- src/query/ast/src/ast/expr.rs
- src/query/ast/src/parser/expr.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/expr-error.txt
- src/query/ast/tests/it/testdata/expr.txt
- src/query/ast/tests/it/testdata/stmt-error.txt
- src/query/functions/src/scalars/comparison.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- src/query/sql/src/planner/optimizer/optimizers/operator/decorrelate/decorrelate.rs
- src/query/sql/src/planner/optimizer/optimizers/operator/decorrelate/subquery_decorrelator.rs
- src/query/sql/src/planner/plans/scalar_expr.rs
- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/mode/standalone/explain/subquery.test
Support Cases:
- `<subject> LIKE ANY (<pattern1> [, <pattern2> ... ] )`
- `<subject> LIKE ANY (SELECT ...)`
fixes: https://github.com/databendlabs/databend/issues/18091
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18099)
> feat: impl `like any`

- src/query/service/src/pipelines/builders/builder_aggregate.rs
- src/query/service/src/pipelines/builders/builder_exchange.rs
- src/query/service/src/pipelines/pipeline_builder.rs
fix(query): fixed a panic issue in the aggregate spill logic under cluster
The latest code can handle error cases covered by the test at `tests/sqllogictests/suites/base/03_common/03_0038_spill_aggregator.test`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18104)
> fix(query): fixed a panic issue in the aggregate spill logic under cluster

- .github/workflows/reuse.benchmark.yml
Run VACUUM  after each benchmark.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18109)
> ci: run vacuum after benchmark

- benchmark/clickbench/benchmark_cloud.sh
fix error
> Error: APIError: fail to POST https://***/v1/query: ResponseError: (400 Bad Request){"error":{"kind":"WarehouseHeaderRequired","message":"X-DATABEND-WAREHOUSE is required"}}
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18111)
> ci: fix dropping database with default warehouse

- src/query/ast/src/ast/expr.rs
- src/query/ast/src/parser/expr.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/query.txt
- src/query/ast/tests/it/testdata/script.txt
- src/query/ast/tests/it/testdata/stmt.txt
- src/query/sql/src/planner/semantic/aggregating_index_visitor.rs
- src/query/sql/src/planner/semantic/type_check.rs
- src/tests/sqlsmith/src/query_fuzzer.rs
- src/tests/sqlsmith/src/sql_gen/expr.rs
- tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables.test
fix(query): support count(t.*)
fixes #18101 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18113)
> fix(query): support count(t.*)

- src/query/functions/src/scalars/string.rs
- src/query/functions/src/srfs/mod.rs
- src/query/functions/src/srfs/string.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- tests/sqllogictests/suites/query/functions/02_0082_function_regexp_split_to_array.test
This PR introduces a new SQL function, `regexp_split_to_array`, to Databend.
**Key Changes:**
1.  **New Function: `regexp_split_to_array`**
*   **Syntax:** `regexp_split_to_array(string text, pattern text [, flags text])`
*   **Parameters:**
*   `string text`: The input string to be split.
*   `pattern text`: The regular expression pattern used for splitting the string.
*   `flags text` (optional): A string of flags to modify the regular expression's behavior.
*   **Functionality:** Splits the `string` into multiple segments based on the `pattern` and returns these segments as individual rows and columns in a array.
2.  **Supported `flags` Parameter:** Provides flexible regular expression …
> feat(query): Add regexp_split_to_array function

- .github/workflows/bindings.python.yml
- .github/workflows/cloud.yml
- .github/workflows/meta.yml
- .github/workflows/release.yml
- .github/workflows/reuse.benchmark.yml
- .github/workflows/reuse.linux.yml
- .github/workflows/reuse.sqllogic.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18135)
> ci: use different runner capacity for release

- .github/workflows/cloud.yml
- .github/workflows/dev.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18140)
> ci: fix argument for workflow

- src/query/functions/src/scalars/variant.rs
- src/query/functions/tests/it/scalars/testdata/function_list.txt
- tests/sqllogictests/suites/query/functions/02_0051_function_semi_structureds_get.test
- tests/sqllogictests/suites/stage/formats/avro/avro_decimal.test
In main:
```sql
SELECT typeof($1:testa_date), $1:testa_date FROM @data/t.avro ( FILE_FORMAT => avro, ) LIMIT 1
╭──────────────────────────────────────────────────────╮
│ typeof($1:testa_date) │         $1:testa_date        │
│         String        │       Nullable(Variant)      │
├───────────────────────┼──────────────────────────────┤
│ VARIANT NULL          │ "2022-06-11 11:42:14.120000" │
╰──────────────────────────────────────────────────────╯
1 row read in 0.213 sec. Processed 0 row, 75.26 KiB (0 row/s, 353.35 KiB/s)
```
In pr:
```sql
SELECT typeof($1:testa_date), $1:testa_date FROM @data/t.avro ( FILE_FORMAT => avro, ) LIMIT 1
╭──────────────────────────────────────────────────────╮
│ …
```
> feat(query): typeof(VariantType) will return internal field type

- scripts/distribution/configs/databend-meta.toml
- scripts/distribution/configs/databend-query.toml
Add some notes in example config.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18166)
> chore: add notes in example configs

- src/query/ast/src/ast/statements/table.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/stmt-error.txt
- src/query/ast/tests/it/testdata/stmt.txt
- src/query/service/src/interpreters/interpreter_table_modify_column.rs
- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/sql/src/planner/plans/ddl/table.rs
- tests/sqllogictests/suites/base/05_ddl/05_0003_ddl_alter_table.test
- tests/sqllogictests/suites/base/05_ddl/05_0028_ddl_alter_table_add_drop_column.test
- tests/suites/0_stateless/17_altertable/17_0005_alter_table_modify_column_type.sh
- tests/suites/5_ee/04_attach_read_only/04_0007_attach_table_entity_comment.result
- tests/suites/5_ee/04_attach_read_only/04_0007_attach_table_entity_comment.sh
Reverts databendlabs/databend#18181
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18192)
> Revert "fix(query): alter column comment can not change column type"

- .github/workflows/reuse.linux.yml
- Cargo.lock
- src/bendsave/src/storage.rs
- src/common/building/src/lib.rs
- src/query/ee/src/storage_encryption/handler.rs
- src/query/ee/src/storage_quota/handler.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/src/table_functions/others/license_info.rs
- src/query/settings/Cargo.toml
- src/query/settings/src/settings_getter_setter.rs
fix check embeded license.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18202)
> fix(query): check enterprise license embedded

- .github/scripts/retry_failed_jobs.js
Retry for cancelled jobs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18216)
> ci: log job status for retry

- .github/scripts/retry_failed_jobs.js
- .github/workflows/typos.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18221)
> ci: fix find related pr for workflow run

- src/query/service/src/pipelines/processors/transforms/transform_udf_script.rs
fix(query): fix recusive wrapper codes in python udf
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18219)
> fix(query): fix recusive wrapper codes in python udf

- .github/scripts/retry_failed_jobs.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18235)
> ci: fix get all jobs for retry

- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18244)
> ci: run benchmark on github runner

- src/meta/api/src/sequence_api_impl.rs
- src/meta/app/src/schema/sequence.rs
- src/meta/proto-conv/src/sequence_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/main.rs
- src/meta/proto-conv/tests/it/proto_conv.rs
- src/meta/proto-conv/tests/it/v132_remove_sequence_meta_start.rs
- src/meta/protos/proto/sequence.proto
- src/meta/service/tests/it/api/http/features.rs
- src/query/service/src/interpreters/interpreter_sequence_desc.rs
- src/query/service/src/table_functions/show_sequences/show_sequences_table.rs
- src/query/sql/src/planner/plans/ddl/sequence.rs
- tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show.result
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18245)
> refactor: remove unused field step from sequence meta

- Cargo.lock
- Cargo.toml
- src/common/compress/Cargo.toml
- src/common/compress/src/compress_algorithms.rs
- src/common/compress/src/decode.rs
- src/common/compress/src/encode.rs
- src/meta/app/src/principal/user_stage.rs
- src/meta/proto-conv/src/file_format_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/main.rs
- src/meta/proto-conv/tests/it/v133_stage_file_compression.rs
- src/meta/protos/proto/file_format.proto
- src/query/ast/src/parser/stage.rs
- src/query/ast/src/parser/token.rs
- src/query/sql/src/planner/semantic/type_check.rs
- src/query/storages/stage/src/append/row_based_file/writer_processor.rs
- src/query/storages/stage/src/compression.rs
- src/query/storages/stage/src/read/row_based/processors/decompressor.rs
- tests/sqllogictests/suites/stage/unload.test
- fixes: https://github.com/databendlabs/databend/issues/17039
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18257)
> feat: Add ZIP compression type

- src/query/sql/src/planner/binder/ddl/table.rs
- src/query/storages/common/table_meta/src/table/table_compression.rs
- tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables.test
- close https://github.com/databendlabs/databend/issues/17975
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18261)
> fix: check compression options when binding `CREATE TABLE` statement

- src/query/ast/src/ast/statements/insert.rs
- src/query/ast/src/parser/statement.rs
- src/query/service/src/interpreters/interpreter_insert.rs
- src/query/sql/src/planner/binder/copy_into_table.rs
- src/query/sql/src/planner/binder/ddl/stage.rs
- src/query/sql/src/planner/binder/insert.rs
- src/query/sql/src/planner/binder/replace.rs
- src/query/sql/src/planner/plans/insert.rs
- src/query/storages/stage/src/streaming_load.rs
- tests/sqllogictests/suites/stage/upload.test
- tests/suites/1_stateful/01_streaming_load/01_0001_streaming_load_ontime.sh
- tests/suites/1_stateful/01_streaming_load/01_0002_streaming_load_variant.sh
- tests/suites/1_stateful/01_streaming_load/01_0003_streaming_load_dedup.sh
- tests/suites/1_stateful/01_streaming_load/01_0004_streaming_load_error.sh
- tests/suites/1_stateful/01_streaming_load/01_0005_streaming_load_compact.sh
- tests/suites/1_stateful/01_streaming_load/01_0006_streaming_load_parquet.result
- tests/suites/1_stateful/01_streaming_load/01_0006_streaming_load_parquet.sh
- tests/suites/1_stateful/01_streaming_load/01_0007_streaming_load_placeholder.result
- tests/suites/1_stateful/01_streaming_load/01_0007_streaming_load_placeholder.sh
new syntax:
```
insert into <table> [values [(<column> [ , ... ] )]]  from @_databend_load  file_format = (...)
```
only use internally in these features:
which use `streaming load` or `upload + insert from stage` inside
1. **the breaking change**（not documented yet）: `from @_databend_load` clause is now required.
4. standalone`values` keyword is not required,   any more. 
5. if use  `upload + insert from stage`, driver is responsable to replace `_databend_load` with  stage name `_databend_load` is resevered
use this syntax internally: 
user provide SQL like `insert into <table> [values [(<column> [ , ... ] )]] ` as before, 
and driver internally serialize batch values to file and load to …
> feat: insert with stage support from and file_format clause.

- Cargo.lock
- Cargo.toml
- src/meta/api/src/sequence_api_impl.rs
- src/meta/api/src/sequence_nextval_impl.rs
- src/meta/client/src/lib.rs
- src/meta/kvapi-test-suite/Cargo.toml
- src/meta/kvapi-test-suite/src/lib.rs
- src/meta/kvapi-test-suite/src/test_suite.rs
- src/meta/kvapi/src/kvapi/mod.rs
- src/meta/service/Cargo.toml
- src/meta/service/tests/it/meta_node/meta_node_kv_api.rs
- src/meta/store/Cargo.toml
- src/meta/store/tests/it/kv_api.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18279)
> refactor(meta-service): move kvapi-test-suite to separate crate

- src/query/expression/src/converts/meta/index_scalar.rs
- src/query/expression/src/values.rs
- tests/compat_fuse/compat-logictest/base/fuse_compat_write
fix(query): add compatibility check for decimal64
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18280)
> fix(query): add compatibility check for decimal64

- .github/workflows/bindings.python.yml
- .github/workflows/cloud.yml
- .github/workflows/dev.yml
- .github/workflows/main.yml
- .github/workflows/meta.yml
- .github/workflows/release.yml
- .github/workflows/retry.yml
- .github/workflows/reuse.benchmark.yml
- .github/workflows/reuse.linux.yml
- .github/workflows/reuse.sqllogic.yml
Auto retry for `cloud.yml` and `release.yml`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18298)
> ci: auto retry more workflows

- .github/workflows/reuse.linux.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18299)
> ci: fix trailing space

- .github/workflows/release.yml
- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18306)
> ci: add local benchmark back

- src/query/sql/src/planner/semantic/type_check.rs
- tests/sqllogictests/suites/mode/standalone/explain/explain_like.test
- tests/sqllogictests/suites/mode/standalone/explain/selectivity/is_not_null.test
close https://github.com/databendlabs/databend/issues/18253
```sql
create table t_user(id int not null, name varchar(10));
insert into t_user values (10, 'alice'), (103, 'bod');
```
**previous**
```sql
EXPLAIN SELECT * FROM t_user WHERE name LIKE '%'
Filter
├── output columns: [t_user.id (#0), t_user.name (#1)]
├── filters: [is_true(like(t_user.name (#1), '%'))]
├── estimated rows: 2.00
└── TableScan
├── table: default.databend_database.t_user
├── output columns: [id (#0), name (#1)]
├── read rows: 2
├── read size: < 1 KiB
├── partitions total: 1
├── partitions scanned: 1
├── pruning stats: [segments: <range pruning: 1 to 1>, blocks: <range …
```
> feat(optimize): rewrite LIKE '%' (e.g., '%%', '%%%') as IS NOT NULL

- .github/workflows/reuse.benchmark.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18308)
> ci: fix artifact category for local benchmark

- src/common/storage/src/copy.rs
- src/common/storage/src/lib.rs
- src/query/storages/stage/src/read/avro/block_builder_processor.rs
- src/query/storages/stage/src/read/avro/decoder.rs
- src/query/storages/stage/src/read/error_handler.rs
- src/query/storages/stage/src/read/row_based/formats/csv/block_builder.rs
- src/query/storages/stage/src/read/row_based/formats/csv/separator.rs
- src/query/storages/stage/src/read/row_based/formats/ndjson/block_builder.rs
- src/query/storages/stage/src/read/row_based/formats/tsv/block_builder.rs
- tests/sqllogictests/suites/stage/formats/avro/avro_error.test
- tests/sqllogictests/suites/stage/formats/ndjson/ndjson_on_error.test
fix https://github.com/databendlabs/databend/issues/18292
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18329)
> chore: polish error message when read AVRO.

- src/query/sql/src/planner/binder/binder.rs
- src/query/sql/src/planner/binder/util.rs
- src/query/sql/src/planner/format/display.rs
- src/query/sql/src/planner/optimizer/ir/expr/s_expr.rs
- src/query/sql/src/planner/optimizer/ir/expr/visitor.rs
- src/query/sql/src/planner/plans/aggregate.rs
- src/query/sql/src/planner/plans/async_function.rs
- src/query/sql/src/planner/plans/eval_scalar.rs
- src/query/sql/src/planner/plans/exchange.rs
- src/query/sql/src/planner/plans/filter.rs
- src/query/sql/src/planner/plans/join.rs
- src/query/sql/src/planner/plans/mod.rs
- src/query/sql/src/planner/plans/mutation_source.rs
- src/query/sql/src/planner/plans/operator.rs
- src/query/sql/src/planner/plans/operator_macros.rs
- src/query/sql/src/planner/plans/optimize.rs
- src/query/sql/src/planner/plans/project_set.rs
- src/query/sql/src/planner/plans/scalar_expr.rs
- src/query/sql/src/planner/plans/scan.rs
- src/query/sql/src/planner/plans/udf.rs
- src/query/sql/src/planner/plans/window.rs
chore(query): refactor RelOperator
1. use macro to dispatch matches
2. use visitor to walk SExpr
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18336)
> chore(query): refactor RelOperator[part I]

- src/query/ast/src/parser/statement.rs
- src/query/catalog/src/table_args.rs
- src/query/storages/fuse/src/table_functions/fuse_vacuum_temporary_table.rs
#18307
```sql
root@localhost:8000/default> vacuum temporary tables limit 1;
vacuum temporary tables limit 1
╭─────────────────────────────────────────────────────────╮
│                          result                         │
│                          String                         │
├─────────────────────────────────────────────────────────┤
│ Ok: processed temporary tables from 1 inactive sessions │
╰─────────────────────────────────────────────────────────╯
1 row read in 0.043 sec. Processed 1 row, 67 B (23.26 rows/s, 1.52 KiB/s)
root@localhost:8000/default> vacuum temporary tables;
vacuum temporary tables
╭─────────────────────────────────────────────────────────╮
│ …
```
> chore: add VACUUM TEMPORARY TABLES command

- Cargo.lock
- src/meta/app/src/principal/user_defined_function.rs
- src/meta/proto-conv/src/udf_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/main.rs
- src/meta/proto-conv/tests/it/proto_conv.rs
- src/meta/proto-conv/tests/it/v058_udf.rs
- src/meta/proto-conv/tests/it/v079_udf_created_on.rs
- src/meta/proto-conv/tests/it/v081_udf_script.rs
- src/meta/proto-conv/tests/it/v124_udf_server_headers.rs
- src/meta/proto-conv/tests/it/v125_table_index.rs
- src/meta/proto-conv/tests/it/v135_udf_immutable.rs
- src/meta/protos/proto/udf.proto
- src/query/ast/src/ast/statements/udf.rs
- src/query/ast/src/parser/statement.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/testdata/stmt.txt
- src/query/expression/Cargo.toml
- src/query/expression/src/utils/udf_client.rs
- src/query/management/tests/it/udf.rs
- src/query/service/src/builtin/builtin_udfs.rs
- src/query/service/src/pipelines/processors/transforms/transform_udf_server.rs
- src/query/service/src/table_functions/others/udf.rs
- src/query/sql/src/executor/physical_plans/physical_mutation.rs
- src/query/sql/src/planner/binder/udf.rs
- src/query/sql/src/planner/semantic/type_check.rs
- src/query/storages/fuse/src/io/write/vector_index_writer.rs
- src/query/storages/system/src/user_functions_table.rs
- src/query/users/tests/it/user_udf.rs
- tests/sqllogictests/suites/udf_server/udf_server_test.test
This PR introduces enhancements to Databend's User-Defined Function (UDF) capabilities, focusing on performance optimization and bug fixes. Key changes include:
1.  **IMMUTABLE and VOLATILE UDF Declaration:**
*   Users can now specify the volatility of UDFs during creation using the `IMMUTABLE` or `VOLATILE` keywords.
*   `VOLATILE`(default): UDF might return different values for different rows, even for the same input (e.g. due to non-determinism and statefullness).
*   `IMMUTABLE`: UDF assumes that the function, when called with the same inputs, will always return the same result. This guarantee is not checked. Specifying `IMMUTABLE` for a UDF that returns different values for the same input …
> feat(query): Enhanced UDF Functionality with IMMUTABLE Support

- src/query/management/src/workload/workload_resource.rs
- src/query/service/src/servers/http/v1/http_query_handlers.rs
chore(query): add log if does not have workload group
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18374)
> chore(query): add log if does not have workload group

- src/query/expression/src/evaluator.rs
- tests/sqllogictests/suites/udf_server/udf_server_test.test
- tests/udf/udf_server.py
This PR fix cast array with nullable inner type to vector failed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18375)
> fix(query): Fix cast array to vector failed

- src/query/ast/benches/bench.rs
- src/query/ast/src/parser/expr.rs
- src/query/ast/tests/it/parser.rs
- src/query/ast/tests/it/testdata/expr.txt
- fixes: https://github.com/databendlabs/databend/issues/18356
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18386)
> feat: simplify function call parse

- .github/workflows/reuse.linux.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18403)
> ci: fix runner for test_private_tasks

- src/query/expression/src/filter/filter_executor.rs
- src/query/expression/src/function.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- tests/sqllogictests/suites/query/filter.test
- tests/sqllogictests/suites/query/filter_disable_selector.test
feat(query): add settings enable_selector_executor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18434)
> feat(query): add settings enable_selector_executor

- src/meta/binaries/metactl/main.rs
- src/meta/control/src/lua_support.rs
- tests/metactl/metactl_utils.py
- tests/metactl/subcommands/cmd_lua_grpc.py
- tests/metactl/subcommands/cmd_lua_sleep.py
- tests/metactl/subcommands/cmd_lua_spawn_concurrent.py
- tests/metactl/subcommands/cmd_lua_spawn_grpc.py
- tests/metactl/test_all_subcommands.py
- tests/metactl/utils.py
Add comprehensive async functionality to Lua environment:
- Implement async spawn() function using tokio::task::spawn_local
- Add async sleep() function with tokio::time::sleep
- Create LuaTask wrapper with proper join() method
- Use LocalSet for async Lua script execution in metactl
Test coverage includes:
- Basic spawn functionality with concurrent tasks
- Cross-task gRPC client operations
- Sleep timing verification
- Dynamic test discovery system
This enables concurrent Lua script execution within the async
runtime for improved performance and capability.
- - - …
> feat(meta): add async Lua spawn and sleep support with tests

- src/query/service/src/servers/http/v1/query/http_query.rs
- src/query/service/src/servers/http/v1/query/http_query_manager.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- tests/sqllogictests/src/util.rs
- tests/suites/1_stateful/09_http_handler/09_0006_route_error.sh
this fields are not used in drivers  (as field of some drivers older then 2024-04,  but not really used,  deserialized as null or "" is OK ),
so should not cause compatibility problem. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18442)
> refactor: move some fields of session to internal.

- src/query/settings/src/settings_default.rs
- src/query/settings/src/settings_getter_setter.rs
- src/query/sql/src/executor/physical_plan.rs
- src/query/sql/src/planner/optimizer/optimizers/rule/agg_rules/rule_grouping_sets_to_union.rs
- src/query/sql/src/planner/optimizer/optimizers/rule/factory.rs
1. refine cte profile
2. add a setting to control channel size of cte in `RuleGroupingSetsToUnion`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18467)
> chore: refine cte profile

- src/query/sql/src/executor/format.rs
- src/query/sql/src/planner/optimizer/statistics/collect_statistics.rs
- tests/sqllogictests/suites/mode/standalone/explain/explain_grouping_sets.test
- tests/sqllogictests/suites/mode/standalone/explain/materialized_cte.test
- tests/sqllogictests/suites/mode/standalone/explain/push_down_filter/push_down_filter_join/push_down_filter_self_join.test
- tests/sqllogictests/suites/tpch/join_order.test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18470)
> fix: collect statistics for MaterializeCTERef

- .github/actions/artifact_meta_container_failure/action.yml
- docker/meta-chaos/meta.Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18491)
> ci: fix cat logs for metachaos

- src/query/config/src/config.rs
- src/query/config/src/inner.rs
- src/query/service/src/clusters/cluster.rs
- src/query/service/tests/it/clusters.rs
fix(query): fix the 'not found' error caused by heartbeat loss on the local
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18512)
> fix(query): fix the 'not found' error caused by heartbeat loss on the local

- src/common/license/src/license.rs
- src/query/ee/src/license/license_mgr.rs
refactor(query): use default verify if the feature is not included in the license
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18517)
> refactor(query): use default verify if the feature is not included in the license

- src/query/service/src/interpreters/interpreter_explain.rs
- tests/sqllogictests/suites/ydb/select1-1.test
fix(query): panic if explaining complex joins
fix: https://github.com/databendlabs/databend/issues/18536
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18538)
> fix(query): panic if explaining complex joins

- scripts/devops-meta/collect_meta_logs.py
- src/meta/service/src/store/store_inner.rs
Add Python script to collect logs from databend-meta based on config file.
Supports both log_dir and [log.file].dir configuration formats with
validation to prevent conflicts. Includes automatic dependency installation
and detailed progress reporting for troubleshooting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18539)
> feat(scripts): add databend-meta log collection tool

- src/common/building/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18559)
> chore: change default telemetry endpoint

- src/meta/api/src/schema_api_test_suite.rs
- Consolidate Util usage in drop_table_without_tableid_to_name tests
- Simplify concurrent_commit_table_meta database setup
- Streamline table_drop_out_of_retention_time_history test setup
- Eliminate code duplication across schema-api tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18563)
> refactor: simplify database setup using Util across multiple test scenarios

- src/query/service/src/servers/http/middleware/session.rs
- src/query/service/src/servers/http/middleware/session_header.rs
- src/query/service/src/servers/http/v1/query/http_query.rs
- tests/suites/1_stateful/09_http_handler/09_0007_session.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18530)
> refactor: simplify session for worksheet.

- src/meta/api/src/schema_api_test_suite.rs
- db_table_gc_out_of_retention_time
- table_commit_table_meta orphan section
- table_update_row_access_policy
- table_update_mask_policy
- table_history_filter_with_limit
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18565)
> refactor: replace manual database setup with Util across multiple test cases

- src/common/base/src/runtime/workload_group.rs
- src/query/management/src/workload/workload_resource.rs
- src/query/service/src/sessions/queue_mgr.rs
- src/query/service/tests/it/sessions/queue_mgr.rs
refactor(query): add local semaphore for reduce meta's request
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18572)
> refactor(query): add local semaphore for reduce meta's request

- src/query/pipeline/core/src/finished_chain.rs
- src/query/pipeline/core/src/pipeline.rs
- src/query/pipeline/core/src/processors/duplicate_processor.rs
- src/query/pipeline/core/src/processors/port_trigger.rs
- src/query/pipeline/core/src/processors/resize_processor.rs
- src/query/pipeline/core/src/processors/sequence_group.rs
- src/query/pipeline/core/src/processors/shuffle_processor.rs
- src/query/pipeline/sinks/src/async_mpsc_sink.rs
- src/query/pipeline/sinks/src/async_sink.rs
- src/query/pipeline/sinks/src/sync_mpsc_sink.rs
- src/query/pipeline/sinks/src/sync_sink.rs
- src/query/pipeline/sinks/src/sync_sink_sender.rs
- src/query/service/src/pipelines/executor/executor_graph.rs
- src/query/service/src/schedulers/fragments/plan_fragment.rs
- src/query/service/src/servers/http/middleware/session_header.rs
- src/query/settings/src/settings.rs
- tests/suites/1_stateful/09_http_handler/09_0007_session.py
Replaced dangerous unwrap() calls with proper error handling to prevent service crashes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18571)
> chore: improve the unwrap error

- src/meta/api/src/schema_api_test_suite.rs
This comprehensive refactoring enhances the create_table_with utility method and applies it consistently across all test functions:
- Enhanced create_table_with to accept optional TableMeta parameter, eliminating duplicate customization patterns
- Converted all 20+ test functions to use the unified create_table_with approach
- Removed redundant CreateTableReq instantiation and field setting patterns
- Simplified parameter passing by using objects instead of individual parameters
- Applied early return patterns to reduce nesting depth
- Cleaned up unused imports and methods
The refactoring maintains identical functionality while significantly improving code maintainability and reducing …
> refactor: consolidate schema_api_test_suite CreateTableReq patterns with enhanced create_table_with

- src/query/service/src/sessions/queue_mgr.rs
Before:
```[QUERY-QUEUE] Waiting for resource scheduling```
After:
```
[QUERY-QUEUE] Waiting for local workload semaphore
[QUERY-QUEUE] Waiting for global workload semaphore
[QUERY-QUEUE] Waiting for warehouse resource scheduling
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18578)
> chore: improve the queue status

- src/common/base/src/runtime/workload_group.rs
- src/query/management/src/workload/workload_resource.rs
- src/query/service/src/sessions/queue_mgr.rs
- src/query/service/tests/it/sessions/queue_mgr.rs
refactor(query): add lock for meta semaphore request
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18579)
> refactor(query): add lock for meta semaphore request

- src/query/service/src/clusters/cluster.rs
- Add 'endpoints' field to meta_config section in telemetry payload
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18591)
> feat(telemetry): add meta endpoints information to telemetry data

- .github/scripts/retry_failed_jobs.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18604)
> ci: fix cancelled conclusion

- src/meta/raft-store/src/config.rs
- src/meta/service/src/configs/outer_v0.rs
- src/meta/service/src/message.rs
- src/meta/service/src/meta_service/meta_leader.rs
- src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18600)
> feat(meta-service): add a node to cluster as learner: databend-meta --join ... --learner

- .github/workflows/build_tool.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18611)
> ci: build build-tool on arm64

- scripts/setup/rust-tools.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18614)
> ci: remove nextest from dev image

- .github/workflows/cloud.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18628)
> ci: allow backport PRs to build cloud image

- .cargo/audit.toml
- Cargo.lock
- Cargo.toml
- src/binaries/query/entry.rs
- src/common/building/Cargo.toml
- src/common/building/src/lib.rs
- src/common/building/src/license.rs
- src/common/version/Cargo.toml
- src/common/version/src/lib.rs
- src/meta/binaries/meta/entry.rs
- migrating vergen to v9
- cleanup audit.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18617)
> chore: migrating vergen to v9

- src/query/service/src/history_tables/meta.rs
https://github.com/databendlabs/databend/actions/runs/17266535516/job/49007155799?pr=18619
https://github.com/databendlabs/databend/actions/runs/17258438274/job/48974707911
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18624)
> fix(test): flaky test from history table permit guard

- src/meta/raft-store/src/leveled_store/db_builder.rs
- src/meta/raft-store/src/leveled_store/leveled_map/acquire_compactor_test.rs
- src/meta/raft-store/src/leveled_store/leveled_map/compacting_data.rs
- src/meta/raft-store/src/leveled_store/leveled_map/compactor.rs
- src/meta/raft-store/src/leveled_store/leveled_map/leveled_map_data/mod.rs
- src/meta/raft-store/src/leveled_store/leveled_map/mod.rs
- src/meta/raft-store/src/sm_v003/compact_immutable_levels_test.rs
- src/meta/raft-store/src/sm_v003/compact_with_db_test.rs
- src/meta/raft-store/src/sm_v003/sm_v003.rs
- src/meta/service/src/store/store_inner.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18633)
> chore(meta-service): adjust internal structure for state machine

- src/query/sql/src/planner/optimizer/optimizers/rule/factory.rs
- src/query/sql/src/planner/optimizer/optimizers/rule/limit_rules/mod.rs
- src/query/sql/src/planner/optimizer/optimizers/rule/limit_rules/rule_merge_limit.rs
- src/query/sql/src/planner/optimizer/optimizers/rule/rule.rs
- tests/sqllogictests/suites/mode/standalone/explain/limit.test
- tests/sqllogictests/suites/mode/standalone/explain/merge_limit.test
- tests/sqllogictests/suites/mode/standalone/explain_native/limit.test
```
-- Before optimization:
SELECT * FROM (SELECT * FROM table LIMIT 10) LIMIT 5;
-- After optimization (same result, better performance):
SELECT * FROM table LIMIT 5;
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18636)
> feat(query): add rule_merge_limit

- .github/workflows/cloud.yml
- .github/workflows/main.yml
- .github/workflows/merge_group.yml
- .github/workflows/release.yml
- .github/workflows/reuse.linux.yml
- src/common/building/src/lib.rs
- src/common/version/src/lib.rs
- src/query/service/src/clusters/cluster.rs
- tests/nox/java_client/perpare.py
- tests/nox/noxfile.py
- tests/nox/python_client/test_basic.py
Add DATABEND_TELEMETRY_SOURCE environment variable to distinguish different build sources in telemetry data. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18653)
> ci: add telemetry source tracking for build environment identification

- .github/workflows/release.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18662)
> ci: fix download artifact for sqlsmith

- src/query/service/src/pipelines/processors/transforms/hash_join/runtime_filter/builder.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/runtime_filter/interface.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/runtime_filter/merge.rs
- src/query/sql/src/planner/binder/table.rs
- src/query/storages/fuse/src/operations/read/parquet_data_source_deserializer.rs
- src/query/storages/fuse/src/operations/read/parquet_data_transform_reader.rs
log build time, prune time and prune rows
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18674)
> chore: add some log for runtime filter

- .gitignore
- src/query/expression/src/aggregate/aggregate_hashtable.rs
- src/query/sql/src/planner/optimizer/optimizers/rule/agg_rules/rule_hierarchical_grouping_sets.rs
- tests/sqllogictests/suites/duckdb/sql/aggregate/group/group_by_grouping_sets.test
Fixed a critical bug in hierarchical grouping sets optimization where CTE schema ordering was inconsistent between definition and consumption, causing group_column type not match
errors when using subqueries with grouping sets.
- Sort GroupingLevel.columns by their position in agg.group_items for deterministic ordering
- Pass agg parameter to build_hierarchy_dag() to access group item ordering
- Debug Assertions: Added type checking in aggregate_hashtable.rs to catch schema mismatches early
- Added consistent schema ordering comments
- CTE Channel Size: Fixed missing channel_size configuration in MaterializedCTE nodes
- Debug Assertions: Added type checking in aggregate_hashtable.rs to catch …
> fix(query): fix incorrect order of group by items with CTE or subquery

- src/query/service/src/physical_plans/physical_mutation.rs
- tests/sqllogictests/suites/base/09_fuse_engine/09_0037_target_build_merge_into_without_distributed_enable.test
This PR addresses a bug encountered when using `MERGE INTO` with a `Variant Nullable` column in the source table and a `Int32 Not Null` column in target table, resulting in an "unable to cast type `Variant NULL` to type `Int32`" error.
The following test case demonstrates the issue and verifies the fix:
```sql
create or replace table t1(id string, raw_data variant, add_time timestamp, action string);
insert into t1 values
('1', '{"id":1, "float_col":1.1}', '2025-09-04 16:41:35.519000', 'insert'),
('2', '{"id":2, "float_col":2.1}', '2025-09-04 16:41:35.519000', 'insert'),
('2', '{"id":2, "float_col":2.2}', '2025-09-04 16:41:35.519000', 'delete');
create or replace table t2(id int not null, …
```
> fix(query): fix unable cast Variant Nullable type to Int32 type in MERGE INTO

- src/query/expression/src/values.rs
- src/query/service/src/physical_plans/physical_window.rs
- src/query/service/src/pipelines/processors/transforms/window/frame_bound.rs
- src/query/service/src/pipelines/processors/transforms/window/transform_window.rs
- tests/sqllogictests/suites/query/window_function/window_basic.test
Support Date and Timestamp for Range Between in WindowFunction
- when order by expr is a TIMESTAMP data type, the parameter of RANGE BETWEEN must be of Interval type
- when order by expr is a DATE data type, the parameter of RANGE BETWEEN must be of Interval or unsigned constant type
ref: https://docs.snowflake.com/en/sql-reference/functions-window-syntax
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18696)
> feat: impl Date & Timestamp on `RANGE BETWEEN`

- .github/actions/test_compat_client_cluster/action.yml
- scripts/ci/deploy/databend-query-cluster-3-nodes-nginx.sh
- tests/nox/noxfile.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18697)
> ci: run behave test of bendsql for compact.

- Cargo.lock
- Cargo.toml
- src/meta/raft-store/src/leveled_store/immutable.rs
- src/meta/raft-store/src/leveled_store/level.rs
- src/meta/raft-store/src/leveled_store/leveled_map/compacting_data.rs
- src/meta/raft-store/src/leveled_store/leveled_map/mod.rs
- src/meta/raft-store/src/sm_v003/sm_v003.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18731)
> feat: add Immutable::compact to merge two level

- src/meta/control/src/import.rs
- src/meta/service/src/api/grpc/grpc_service.rs
- src/meta/service/src/api/http/v1/features.rs
- src/meta/service/src/meta_service/meta_leader.rs
- src/meta/service/src/meta_service/meta_node.rs
- src/meta/service/src/meta_service/raft_service_impl.rs
- src/meta/service/src/store/meta_raft_log/impl_raft_log_storage.rs
- src/meta/service/src/store/meta_raft_log/mod.rs
- src/meta/service/src/store/meta_raft_state_machine/mod.rs
- src/meta/service/src/store/meta_raft_state_machine/raft_state_machine_impl.rs
- src/meta/service/src/store/mod.rs
- src/meta/service/src/store/store_inner.rs
- src/meta/service/tests/it/meta_node/meta_node_kv_api_expire.rs
- src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs
- src/meta/service/tests/it/meta_node/meta_node_replication.rs
- src/meta/service/tests/it/meta_node/t90_time_revert_cross_snapshot_boundary.rs
- src/meta/service/tests/it/store.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18746)
> refactor(meta-service): separate raft-log-store and raft-state-machine store

- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_spiller.rs
- src/query/service/src/spillers/adapter.rs
- src/query/service/src/spillers/block_reader.rs
- src/query/service/src/spillers/block_writer.rs
- src/query/service/src/spillers/mod.rs
- src/query/service/src/spillers/stream_writer.rs
refactor(query): stream style block writer for hash join spill
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18742)
> refactor(query): stream style block writer for hash join spill

- .github/actions/publish_debug_symbols/action.yml
- .github/workflows/release.yml
Add missing token.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18796)
> ci: fix publish debug symbols

- src/query/ast/src/parser/copy.rs
- src/query/ast/tests/it/testdata/stmt-error.txt
- src/query/sql/src/planner/binder/binder.rs
- src/query/sql/src/planner/binder/copy_into_table.rs
- tests/sqllogictests/suites/stage/transform_fn_check.test
1. forbid srf and ugaf
2. refine error message
3. add related tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18795)
> fix: forbid SRF in copy transform.

- src/query/users/src/jwt/jwk.rs
- tests/suites/1_stateful/02_query/02_0012_temp_table_external_session_cleanup.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18803)
> chore: log more info on jwks refresh

- tests/suites/5_ee/05_stream/05_0004_ee_stream_http_api.result
- tests/suites/5_ee/05_stream/05_0004_ee_stream_http_api.sh
remove checking of unstable http response elements from test case `05_0004_ee_stream_http_api`:
- stream_id
- table_id
- table_version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18810)
> chore: refine stream http api test
