src/query/service/src/interpreters/interpreter_explain.rs
src/query/service/src/interpreters/interpreter_factory.rs
src/query/service/src/interpreters/interpreter_merge_into.rs
src/query/service/src/pipelines/builders/builder_merge_into.rs
src/query/service/src/schedulers/fragments/fragmenter.rs
src/query/sql/src/executor/format.rs
src/query/sql/src/executor/physical_plans/physical_merge_into.rs
src/query/sql/src/planner/binder/merge_into.rs
src/query/sql/src/planner/optimizer/distributed/distributed_merge.rs
src/query/sql/src/planner/optimizer/optimizer.rs
src/query/sql/src/planner/optimizer/s_expr.rs
src/query/sql/src/planner/plans/merge_into.rs
src/query/storages/fuse/src/operations/merge_into/mutator/matched_mutator.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0033_distributed_merge_into_without_enable.test
tests/sqllogictests/suites/base/09_fuse_engine/09_0034_pr13848_without_distributed_enable.test
tests/sqllogictests/suites/base/09_fuse_engine/09_0035_merge_into_separate_pipeline_without_distributed_enable.test
tests/sqllogictests/suites/base/09_fuse_engine/09_0036_merge_into_without_distributed_enable.test
tests/sqllogictests/suites/base/09_fuse_engine/09_0037_target_build_merge_into_without_distributed_enable.test
tests/sqllogictests/suites/mode/cluster/merge_into_non_equal_distributed.test

1. support explain pipeline merge into
2. support explain fragments merge into
3. reduce the occurrence of `*distributed && !*change_join_order`
4. inner join can directly use broadcast join, don't need to add `RowNumber` operator
5. reduce the complexity of merge into optimizer.
6. improve merge into distribution plan, see the file `tests/sqllogictests/suites/mode/cluster/merge_into_non_equal_distributed.test`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15507)

refactor: refactor merge into optimizer and fix unexpected distribution plan

---

src/query/catalog/src/table_context.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/table_functions/show_grants/show_grants_table.rs
src/query/service/tests/it/sql/exec/get_table_bind_test.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
tests/suites/0_stateless/18_rbac/18_0005_show_grants_with_dropped.result
tests/suites/0_stateless/18_rbac/18_0005_show_grants_with_dropped.sh

1. modify identify display
2. show grants also need to check user roles
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15650)

fix(query): show grants also need to check user roles

---

Cargo.lock
src/common/base/src/runtime/defer.rs
src/common/base/src/runtime/mod.rs
src/query/pipeline/core/Cargo.toml
src/query/pipeline/core/src/pipeline.rs
src/query/service/src/pipelines/executor/pipeline_executor.rs

chore(executor): add some time tracking log
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15651)

chore(executor): add some time tracking log

---

src/query/expression/src/function.rs
src/query/expression/src/utils/date_helper.rs
src/query/functions/src/scalars/datetime.rs
src/query/service/src/sessions/query_ctx.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test

`now()`, `today()`, `yesterday()` and `tomorrow()` functions return constant value in a statement.
```sql
mysql> set timezone='UTC';
Query OK, 0 rows affected (0.02 sec)
mysql> select now(), now();
+----------------------------+----------------------------+
| now()                      | now()                      |
+----------------------------+----------------------------+
| 2024-05-28 09:22:57.995818 | 2024-05-28 09:22:57.995818 |
+----------------------------+----------------------------+
1 row in set (0.04 sec)
Read 1 rows, 1.00 B in 0.017 sec., 58.44 rows/sec., 58.44 B/sec.
mysql> set timezone='Asia/Shanghai';
mysql> select now(), now(); …
```

fix(query): fix current date/time functions return constant value in a statement.

---

scripts/ci/deploy/config/databend-query-node-1.toml
src/query/service/src/interpreters/interpreter_merge_into.rs
src/query/service/src/pipelines/builders/merge_into_join_optimizations.rs
src/query/sql/src/planner/binder/merge_into.rs
src/query/sql/src/planner/optimizer/optimizer.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0040_merge_into_issue_15643.test
tests/sqllogictests/suites/mode/standalone/explain/09_0039_target_build_merge_into_standalone.test
tests/sqllogictests/suites/mode/standalone/explain/merge_into.test

for merge-into stmt with both matched and not-matched branch, right join is used,
after got the joined result-set,  a column of the result-set is chosen as the "split" column, 
i.e. for rows of the split column, those are nulls are recognized as no-matched, and others as matched.
before this PR, an arbitrary column of target table is picked as the "split" column, which is unsafe, since 
the "arbitrary column" may have NULL values originally, which may lead to incorrectly treat a matched row
as unmatched, and  unexpected result (data duplication).
in this PR, we use `row_id` column to split the result-set into matched and not-matched parts
- Fixes #15643
- - - …

fix: merge into split

---

src/query/service/src/interpreters/access/privilege_access.rs
tests/suites/0_stateless/18_rbac/18_0002_ownership_cover.result
tests/suites/0_stateless/18_rbac/18_0002_ownership_cover.sh

db owner role can access all tables under this db.
If db owner drop the table that under db but not owned this role, the table's ownership also be revoked.
- Fixes #15612
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15634)

fix(query): db owner role can access all tables under this db

---

src/query/ee/src/storages/fuse/operations/handler.rs
src/query/ee/src/storages/fuse/operations/vacuum_temporary_files.rs
src/query/ee/tests/it/storages/fuse/operations/vacuum.rs
src/query/ee_features/vacuum_handler/src/vacuum_handler.rs
src/query/service/src/interpreters/hook/vacuum_hook.rs
src/query/service/src/interpreters/interpreter_vacuum_temporary_files.rs
src/query/settings/src/settings_default.rs

feat(query): support disable vacuum temporary files after query
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15673)

feat(query): support disable vacuum temporary files after query

---

docker/build-tool/musl/Dockerfile

re-enable musl-g++ link for musl build image. goes-sys seems to depend on it 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15679)

chore: re-enable musl-g++ link for musl build image

---

Cargo.lock
src/common/base/Cargo.toml
src/common/base/src/runtime/metrics/mod.rs
src/common/base/src/runtime/metrics/process_collector.rs
src/common/base/src/runtime/metrics/registry.rs
src/query/service/tests/it/metrics.rs

fixes #15538
this PR adds the following process metrics, they're considered as the standard process metrics:
```
process_cpu_seconds_total 138100.24
process_max_fds 1.048576e+06
process_open_fds 26
process_resident_memory_bytes 3.7982208e+07
process_start_time_seconds 1.70893894953e+09
process_virtual_memory_bytes 1.346695168e+09
process_virtual_memory_max_bytes 1.8446744073709552e+19
```
as `prometheus/rust-client` still has not builtin support for process collector, this PR adds a vanilla implementation which only works in linux. we can switch to the builtin implementation after https://github.com/prometheus/client_rust/issues/29 got resolved.
- - - …

feat(metrics): add process collector

---

src/query/expression/src/kernels/sort.rs
src/query/service/tests/it/storages/fuse/operations/mutation/recluster_mutator.rs
src/query/sql/src/planner/expression_parser.rs
src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/operations/append.rs
src/query/storages/fuse/src/operations/mutation/mutator/recluster_mutator.rs
src/query/storages/fuse/src/operations/recluster.rs
src/query/storages/fuse/src/statistics/cluster_statistics.rs
src/query/storages/fuse/src/table_functions/clustering_information/clustering_information.rs
src/query/storages/fuse/src/table_functions/table_args.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0008_fuse_optimize_table.test

This Pull Request (PR) addresses and fixes a bug where the condition `min > max` could occur after sorting and then truncating fields. The specific changes are as follows:
1. **Bug Fix**: The original logic could result in a `min > max` situation when truncating fields after sorting, causing incorrect behavior.
2. **Improvement**: To prevent this issue, when the cluster key is of string type, a `substr` expression is introduced. This change ensures that the substring operation is applied before sorting, thereby avoiding the mentioned bug.
By implementing this change, the process ensures that when dealing with string type cluster keys, the sorting and truncating operations are performed in the …

fix: failed to select blocks for recluster

---

src/binaries/meta/entry.rs
src/binaries/metactl/snapshot.rs
src/meta/embedded/src/meta_embedded.rs
src/meta/process/src/examples.rs
src/meta/process/src/process_meta_dir.rs
src/meta/raft-store/src/config.rs
src/meta/service/src/configs/outer_v0.rs
src/meta/sled-store/src/db.rs

Provide a config/CLI argument `sled_max_cache_size_mb` to specify the
max memory in MB sled is allowed to use. By default it is `10GB`.
Usage of letting meta-service use at most 64 GB for cache in `config.toml`:
```toml
[raft_config]
sled_max_cache_size_mb = 64000
```
- See: #15707
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15709)

feat: add meta-service config sled_max_cache_size_mb

---

src/meta/service/src/store/raft_log_storage_impl.rs
src/meta/sled-store/src/sled_tree.rs

Avoid batch purge otherwise sled allocate a huge amount of mem in a
short time that causes OOM.
This commit will slow down raft log purge. If there are any problems, revert this PR by merging this branch:
- https://github.com/drmingdrmer/databend/tree/83-revert-one-by-one-del
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15723)

refactor: delete raft log one by one.

---

src/query/service/src/servers/http/middleware.rs
src/query/service/src/servers/http/v1/http_query_handlers.rs
src/query/service/src/servers/http/v1/query/http_query_context.rs
src/query/service/src/servers/http/v1/query/http_query_manager.rs
src/query/service/tests/it/servers/http/http_query_handlers.rs
tests/suites/1_stateful/09_http_handler/09_0006_route_error.result
tests/suites/1_stateful/09_http_handler/09_0006_route_error.sh

also including the case that server restart (assert: always with new node_id).
we can tell it from query timeout at once.
- need to test with the clients
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15621)

refactor: more explicit error confirmation for http query route error.

---

src/meta/api/src/kv_pb_api/upsert_pb.rs
src/meta/raft-store/src/leveled_store/leveled_map_test.rs
src/meta/raft-store/src/leveled_store/util.rs
src/meta/raft-store/src/marked/internal_seq.rs
src/meta/types/src/cmd/mod.rs

**Problem Description:**
- During the scanning process of meta-service key-value stores (kvs),
the system merges kvs from multiple levels. It is designed not to
allow two identical tombstones with the same `seq` number. However, it
is possible to encounter this scenario if two consecutive
non-conditional delete operations are performed. These operations
insert a tombstone without incrementing the `seq`, even if a tombstone
already exists with the same `seq`.
**Solution Implemented:**
- The merging process of kvs has been adjusted to no longer use
`assert()` to enforce inequality for two tombstone records. This
change acknowledges that having two identical tombstones is both
possible and …

fix: Handle Duplicate Tombstones in Meta-Service List Operation

---

src/query/management/src/role/role_mgr.rs
src/query/management/src/serde/pb_serde.rs
src/query/service/src/interpreters/access/privilege_access.rs
src/query/service/src/sessions/session_privilege_mgr.rs
src/query/service/src/table_functions/show_grants/show_grants_table.rs
src/query/users/src/visibility_checker.rs
tests/sqllogictests/suites/base/05_ddl/05_0017_ddl_grant_role.test
tests/suites/0_stateless/18_rbac/18_0005_show_grants_with_dropped.result
tests/suites/0_stateless/18_rbac/18_0007_privilege_access.result

Due to the automatic granting of table ownership to the current user's role when creating a table, this may cause the value of a certain role to expand rapidly, thereby causing a meta OOM (Out of Memory). To fix this issue, the following modifications have been made in this PR:
1. Ownership is no longer update to the role.
2. The "show grants" statement will obtain the ownership permissions of the corresponding resource through the function "get_ownerships".
3. The new method for visibility check has added "get_ownerships" to obtain the ownership status of the object. As a result, "show tables/databases/stage/functions" will increase one meta access.
"use db/show tables/show streams" can only …

refactor: GrantEntry not store ownership privilege

---

src/query/service/src/test_kits/block_writer.rs
src/query/service/tests/it/storages/fuse/bloom_index_meta_size.rs
src/query/service/tests/it/storages/fuse/operations/mutation/recluster_mutator.rs
src/query/service/tests/it/storages/fuse/operations/mutation/segments_compact_mutator.rs
src/query/service/tests/it/storages/fuse/operations/read_plan.rs
src/query/service/tests/it/storages/fuse/statistics.rs
src/query/storages/common/table_meta/src/meta/v2/segment.rs
src/query/storages/common/table_meta/src/meta/v3/frozen/block_meta.rs
src/query/storages/fuse/src/io/write/block_writer.rs
src/query/storages/fuse/src/statistics/reducers.rs
src/query/storages/fuse/src/table_functions/fuse_blocks/fuse_block.rs
tests/sqllogictests/suites/ee/04_ee_inverted_index/04_0000_inverted_index_base.test

* add inverted index size to block meta and table statistic index size
* add inverted index to `fuse_block` table function
- part of #14825 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15752)

feat(query): add inverted index size to block meta

---

tests/sqllogictests/suites/base/issues/issue_15664.test

chore: add more test case about create table fail
the semantics of `table id list` is:
* only create success table id can be added;
* it is a stack.
so, after execute:
```
// return table id a
CREATE OR REPLACE TABLE test_table_2 as select 1;
// create table fail
CREATE OR REPLACE TABLE test_table_2 as select 1/0;
```
the last table id is `a`, so
```
UNDROP TABLE test_table_2
```
will fail, because `Table 'test_table_2' already exists`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15765)

chore: add more test case about create table fail

---

src/query/storages/fuse/src/operations/common/generators/append_generator.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0040_auto_compaction_issue_15760.test

off-by-one mistake during auto compaction:
The potentially previously left non-compacted segment should also be included.
Fixes: #15760
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15761)

fix: off by one mistake in auto compaction

---

Cargo.lock
Cargo.toml

chore: Pin opendal to released version
OpenDAL has released v0.47.0. This PR pinned opendal back to released version. No other changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15766)

chore: Pin opendal to released version

---

src/common/base/src/runtime/metrics/registry.rs

The internal `GlobalMetric::creator: Box<dyn Fn(usize) -> Box<dyn
Metric>>` could not be `Send` and result in undefined behavior.
In this commit add `Send` constrain to `GlobalMetric::creator`:
```
Box<dyn Fn(usize) -> Box<dyn Metric>>
```
becomes:
```
Box<dyn Fn(usize) -> Box<dyn Metric> + Send>
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15782)

refactor: remove unsafe impl Send+Sync for GlobalRegistry

---

src/query/functions/src/scalars/datetime.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test

If format ts or date with format err, the try function will retrun Null
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15775)

feat(query): support try_to_timestmap(string, string), try_to_date(string, string)

---

src/query/sql/src/planner/binder/bind_table_reference/bind_table.rs
src/query/sql/src/planner/binder/select.rs
src/query/sql/src/planner/binder/table.rs
tests/sqllogictests/suites/query/cte/r_cte_alias_name.test

add more alias name tests for r cte
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15788)

chore: add more alias name tests for recursive cte

---

scripts/ci/ci-setup-chaos-meta.sh
src/query/service/tests/it/storages/fuse/table_functions/clustering_information_table.rs
src/query/sql/src/planner/expression_parser.rs
src/query/storages/fuse/src/operations/mutation/mutator/recluster_mutator.rs
src/query/storages/fuse/src/table_functions/clustering_information/clustering_information.rs
src/query/storages/fuse/src/table_functions/clustering_information/clustering_information_table.rs
src/query/storages/fuse/src/table_functions/fuse_blocks/fuse_block_table.rs
src/query/storages/fuse/src/table_functions/fuse_columns/fuse_column_table.rs
src/query/storages/fuse/src/table_functions/fuse_segments/fuse_segment_table.rs
src/query/storages/fuse/src/table_functions/table_args.rs
tests/cloud_control_server/simple_server.py
tests/sqllogictests/suites/base/09_fuse_engine/09_0008_fuse_optimize_table.test
tests/sqllogictests/suites/base/09_fuse_engine/09_0014_func_clustering_information_function.test
tests/sqllogictests/suites/base/09_fuse_engine/09_0015_remote_alter_cluster_key.test
tests/sqllogictests/suites/base/09_fuse_engine/09_0016_remote_alter_recluster.test
tests/sqllogictests/suites/base/09_fuse_engine/09_0023_replace_into.test
tests/sqllogictests/suites/management/management_calls.test

1. enhances the `clustering_information` functionality by adding support for specifying cluster keys. 
By allowing users to specify cluster keys, they can now view the clustering information related to those keys. 
This feature provides valuable insights for users to define effective cluster keys.
2. Remove `unclustered_block_count`, add `timestamp` in `clustering_informaton`
3. recluster will resort the wrong clustered block first. 
```sql
mysql> create table t(a int, b int);
Query OK, 0 rows affected (0.13 sec)
mysql> insert into t values(1, 1),(2, 1);
Query OK, 2 rows affected (0.15 sec)
mysql> insert into t values(2, 2),(3, 2);
Query OK, 2 rows affected (0.16 sec)
mysql> select * from …
```

refactor: clustering_information support specify cluster keys

---

src/meta/client/src/grpc_client.rs
src/meta/client/src/message.rs

`ClientHandle::request_sync(req)` behave the same as the async version
`ClientHandle::request(req)`, which can be used in non-async
environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15786)

refactor: add non-async version of mete-client API request_sync

---

Cargo.lock
Cargo.toml
src/common/base/src/containers/pool.rs
src/common/base/src/display/display_option/mod.rs
src/common/base/src/display/mod.rs
src/common/base/src/future.rs
src/common/base/src/lib.rs
src/common/tracing/src/config.rs
src/common/tracing/src/init.rs
src/meta/raft-store/src/sm_v002/snapshot_store.rs
src/meta/service/Cargo.toml
src/meta/service/src/configs/outer_v0.rs
src/meta/service/src/meta_service/raft_service_impl.rs
src/meta/service/src/network.rs
src/meta/service/src/store/raft_log_storage_impl.rs
src/meta/service/src/store/raft_state_machine_impl.rs
src/meta/service/src/store/store_inner.rs
src/meta/types/Cargo.toml
src/meta/types/build.rs
src/meta/types/src/cluster.rs
src/meta/types/src/cmd/meta_spec.rs
src/meta/types/src/cmd/mod.rs
src/meta/types/src/endpoint.rs
src/meta/types/src/log_entry.rs
src/meta/types/src/match_seq.rs
src/meta/types/src/operation.rs
src/meta/types/src/raft_txid.rs
src/query/config/src/config.rs
src/query/service/tests/it/storages/testdata/configs_table_basic.txt

Use `limited_get_log_entries()` to limit the count of log entries in a
`AppendEntries` request by size.
With this approach, every AppendEntries request won't exceed 2MB.
This address the issue with static configured number of entries in a
`AppendEntries` can not limit the RPC size. Such too big AppendEntries
RPC may timeout.
Other changes:
- Only reuse a connection if there is no error returned from the last RPC.
When a raft RPC is finished, push the connection back for next RPC if it
returns an `Ok`. Otherwise it drops the connection and the next RPC will
re-create a new one. Such approach ensures no problematic connection
will be used.
- Improve raft connection and logging filter. Support …

refactor: adaptive entries count for `AppendEntriesRequest`

---

src/query/storages/fuse/src/operations/mutation/mutator/recluster_mutator.rs

reduce recluster depth threshold from 64 to 16.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15819)

chore: reduce recluster depth threshold

---

src/query/service/src/interpreters/interpreter_insert_multi_table.rs
src/query/service/src/pipelines/builders/builder_insert_multi_table.rs
src/query/sql/src/executor/physical_plans/physical_multi_table_insert.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0100_insert_multi_table_issue_15821.sql

no need to project before building the pipeline of multi-table insert's `Duplicate` plan.
Predicates of  `ChunkFilter` are "bound to" the output  schema of query, 
https://github.com/datafuselabs/databend/blob/6068e42ceb23c57add7331ddf665063aa5faa4e5/src/query/service/src/interpreters/interpreter_insert_multi_table.rs#L111-L121 
extra projection of the query result is not necessary (and may be harmful).
- Fixes #15821
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15822)

fix: multi-tbl insert with lateral flattern panics

---

src/meta/app/src/principal/file_format.rs
src/query/sql/src/planner/binder/copy_into_table.rs
src/query/storages/parquet/src/parquet_rs/copy_into_table/reader.rs
src/query/storages/parquet/src/parquet_rs/copy_into_table/table.rs
src/query/storages/stage/src/read/load_context.rs
src/query/storages/stage/src/read/row_based/formats/csv/block_builder.rs
tests/sqllogictests/suites/stage/formats/csv/csv_empty_uuid.test
tests/sqllogictests/suites/stage/formats/ndjson/ndjson_null_and_missing_uuid.test
tests/sqllogictests/suites/stage/formats/parquet/options/parquet_missing_uuid.test
tests/sqllogictests/suites/stage/formats/tsv/tsv_empty_uuid.test

fix: 
```
create table t_uuid(id string default uuid(), a int)
copy into t_uuid(id, a) from .. // panic!
```
the error cases for now we met is  insert with stage using csv.
as a hot fix, problem is not solved totally, but limited the error cases (when format option `(empty|missing)_field_as=field_default` is specified);
I will try to sovle it in another pr.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15837)

fix: uuid() as default value result in copy error.

---

Cargo.lock
Cargo.toml
src/query/service/src/pipelines/processors/transforms/transform_udf_script.rs

bump arrow-udf
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15836)

chore: bump arrow-udf

---

src/query/service/src/pipelines/processors/transforms/hash_join/desc.rs
src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs
src/query/service/src/schedulers/fragments/fragmenter.rs
src/query/sql/src/executor/physical_plan_visitor.rs
src/query/sql/src/executor/physical_plans/physical_hash_join.rs
src/query/sql/src/planner/binder/bind_query/bind_value.rs
src/query/sql/src/planner/binder/bind_table_reference/bind_join.rs
src/query/sql/src/planner/optimizer/decorrelate/decorrelate.rs
src/query/sql/src/planner/optimizer/decorrelate/flatten_plan.rs
src/query/sql/src/planner/optimizer/decorrelate/subquery_rewriter.rs
src/query/sql/src/planner/optimizer/filter/deduplicate_join_condition.rs
src/query/sql/src/planner/optimizer/filter/pull_up_filter.rs
src/query/sql/src/planner/optimizer/hyper_dp/dphyp.rs
src/query/sql/src/planner/optimizer/hyper_dp/join_node.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
src/query/sql/src/planner/plans/join.rs
tests/sqllogictests/suites/query/lateral.test

Support `is not distinct from` for the correlated columns of Expression Scan.
Close: #15722
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15838)

feat(query): support distinct from for hash join

---

src/query/functions/src/scalars/datetime.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test

1. to_timestmap should always return err if parse err
If do not want to see err in to_timestamp, could use try_to_timesmtap
2. to_timestmap(string, format), if not asign the string tz or format do not parse tz, the string use with current session timezone
- Fixes #https://github.com/datafuselabs/databend/issues/15849
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15850)

fix(query): to_timestmap should always return err if parse err

---

src/query/service/src/pipelines/processors/transforms/hash_join/result_blocks.rs

* variable `has_other_predicate` actually check `is_none`, so change name to `no_other_predicate`;
* refactor `match` a boolean expression to `if else`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15863)

chore: refactor name and match expression

---

src/common/io/src/cursor_ext/cursor_read_datetime_ext.rs
src/query/expression/src/types/date.rs
src/query/expression/src/types/timestamp.rs
src/query/functions/src/scalars/datetime.rs
src/query/functions/src/scalars/variant.rs
src/query/functions/tests/it/scalars/testdata/cast.txt
src/query/functions/tests/it/scalars/testdata/variant.txt
tests/sqllogictests/suites/base/03_common/03_0023_insert_into_array.test

string_to_date/ts should not ignore error
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15878)

chore(query): string_to_date/ts should not ignore error

---

src/query/ee/src/stream/handler.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/operations/changes.rs
src/query/storages/stream/src/stream_table.rs
src/query/storages/system/src/columns_table.rs
src/query/storages/system/src/streams_table.rs
tests/sqllogictests/suites/ee/06_ee_stream/06_0000_stream.test
tests/suites/0_stateless/12_time_travel/12_0005_changes_select.result
tests/suites/5_ee/05_stream/05_0002_ee_stream_create.result

When a column is added to the source table after the stream has been created, the stream continues to use the outdated schema saved at the time of its creation. This can lead to runtime errors where the stream fails to find fields that were added to the source table after the stream's creation.
To address this issue, we made the following changes:
1. **Remove Schema in Streams**:
- Streams no longer store the source table schema at creation time. Instead, they dynamically fetch the latest schema from the source table when needed.
2. **Update Schema Fetching Logic**:
- Modified the stream processing logic to always retrieve the current schema from the source table. This ensures that any changes …

fix: stream error after alter table

---

src/query/expression/src/kernels/concat.rs
src/query/expression/tests/it/kernel.rs
src/query/service/src/test_kits/block_writer.rs
src/query/storages/common/index/src/bloom_index.rs
src/query/storages/common/index/tests/it/filters/bloom_filter.rs
src/query/storages/fuse/src/io/write/block_writer.rs
tests/sqllogictests/suites/no_table_meta_cache/explain/auto_rebuild_missing_bloom_index.test
tests/sqllogictests/suites/no_table_meta_cache/explain_native/auto_rebuild_missing_bloom_index.test

1.   DataBlock::concat is optimized when all block is scalar for some column.
2.  building of bloom index only take one block as input for now,  so no need to concat,  so the `convert_to_full` can be removed too.
3.  not need to generate bloom index for scalar column, it will never be used since range index is checked first.
part of https://github.com/datafuselabs/databend/issues/15908
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15910)

refactor: optimize building bloom index for scalar.

---

src/query/users/src/jwt/jwk.rs
src/query/users/src/jwt/mod.rs
src/query/users/tests/it/jwt/authenticator.rs

Currently we have a 1 minute timeout to refresh the keys from JWKS endpoint. However when the JWKS rotated, it will causes the databend-query not available within this 1 minute.
This PR made the following changes:
1. when we got key id not found, retry fetching the jwks immediately
2. when we got network issue while requesting jwks uri, fallback to the cached jwks when possible
3. when the keys were changed, add a log 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15921)

fix(jwks): refresh the jwks store on key id not found

---

src/query/storages/fuse/src/operations/mutation/mutator/block_compact_mutator.rs
src/query/storages/fuse/src/operations/mutation/mutator/recluster_mutator.rs

When ReclusterTasks::Compact, limit the number of selected segments and blocks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15926)

chore(storage): limit compact num when recluster

---

.github/workflows/reuse.linux.yml

fail twice in one pr:
```
Error: The action has timed out.
```
https://github.com/datafuselabs/databend/actions/runs/9736238538/job/26866849240?pr=15935
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15936)

ci: longer timeout for test_stateless_standalone.

---

src/query/service/src/pipelines/processors/transforms/window/transform_window.rs
tests/sqllogictests/suites/query/window_function/expr_in_window.test

In function `are_peers`, If lhs.block is smaller than first_block, `are_peers` directly returns false.
Because peer_group_start maybe the same as the partition start.
Fix : https://github.com/datafuselabs/databend/issues/15916
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15949)

fix(query): window panic when max_block_size is small

---

src/meta/README.md
src/meta/binaries/metabench/main.rs
src/meta/raft-store/src/sm_v003/adapter.rs
src/meta/service/src/version.rs
src/meta/types/src/proto_ext/txn_ext.rs
tests/compat/meta_meta/test_meta_meta.sh

V002 snapshot stores expire index(with prefix `exp-/`) after kvs(with prefix `kv--/`).
When upgrade, the kvs must be cached so that the the output V003
snapshot has correct key order.
Other changes:
- databend-metabench support `ttl_ms` to specify the time to last for a key
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15947)

fix: when upgrade snapshot v002 to v003, put kvs after expire index

---

src/query/storages/fuse/src/table_functions/fuse_statistics/fuse_statistic.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0020_analyze.test

Before:
```
mysql> select * from FUSE_STATISTIC('tpcds', 'store_sales');
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| column_distinct_values                                                                                                                                                                                                                             |
+--------------------------------------------------------------------------------------------------------------------------------------- …
```

refactor: fuse statistics table function

---

src/query/service/src/servers/admin/admin_service.rs
src/query/service/src/servers/admin/v1/query_profiling.rs
src/query/service/src/servers/flight/v1/actions/flight_actions.rs
src/query/service/src/servers/flight/v1/actions/get_profile.rs
src/query/service/src/servers/flight/v1/actions/mod.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/service/src/sessions/session.rs

Support get PlanProfile from admin API if the query is still running: `/v1/queries/:query_id/profiling`
This PR is part one. It only support the running query. If the query finish very quickly, it cannot get the result.
For the next part, It will maintain a cache queue for the latest 50 (could be config) queries's profile.
Example: `GET http://localhost:8080/v1/queries/46f89e47-9e27-4ca9-b87c-868d80678ec0/profiling`
RESPONSE:
<details>
{
"query_id": "46f89e47-9e27-4ca9-b87c-868d80678ec0",
"profiles": [
{
"id": 6,
"name": "AggregatePartial",
"parent_id": 4,
"title": "max(number), sum(number)",
"labels": [
{
"name": "Aggregate Functions",
"value": [
"max(number)",
"sum(number)"
]
},
{
"name": …

feat: support real-time retrieval of profiles from admin API (part 1)

---

src/query/storages/system/src/columns_table.rs
tests/sqllogictests/suites/ee/06_ee_stream/06_0000_stream.test

When a stream is invalid, the show columns command attempts to retrieve column information and fails, throwing an error. This happens because the command relies on the stream to fetch the latest schema of the source table. If the stream is invalid, it cannot provide the necessary schema information, leading to an error.
If an invalid stream is detected, the command now returns an empty result instead of raising an error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15964)

fix(storage): stream show columns maybe error

---

src/query/ast/src/parser/expr.rs

this pr https://github.com/datafuselabs/databend/pull/15126/files limit it to is_ascii_alphanumeric()
but we often need '_'.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15965)

feat: allow tuple field name to contain '_'.

---

src/query/service/src/interpreters/access/privilege_access.rs
tests/suites/0_stateless/18_rbac/18_0011_alter_own_username.result
tests/suites/0_stateless/18_rbac/18_0011_alter_own_username.sh

alter user support modify current password
Note: 
* If alter with auth_option, it should check privilege.
* in bendsql alter current user's password will return err, because bendsql will call auth in poll, after password modified, in next poll the auth failed, it will return err. But it is not databend-query bug.
* 
```
```
- Fixes https://github.com/datafuselabs/databend/issues/15961
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15962)

feat(query): alter user support modify current password

---

Cargo.lock
src/query/storages/hive/hive/Cargo.toml
src/query/storages/hive/hive/src/hive_catalog.rs
src/query/storages/hive/hive/src/utils.rs

Upgrade hive_metastore
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15976)

chore: Bump hive_metastore to 0.1.0

---

src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/base/03_common/03_0013_select_udf.test

continue PR #15957 
udf function support lambda arguments
- Fixes #15272
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15981)

fix(query): udf function support lambda arguments

---

src/query/expression/src/utils/udf_client.rs
src/query/pipeline/transforms/src/processors/transforms/transform_retry_async.rs
src/query/service/src/pipelines/builders/builder_udf.rs
src/query/service/src/pipelines/processors/transforms/transform_udf_server.rs

* add tenant&queryid to udf client in `TransformUdfServer`, enabling the external UDF server to track with the client, so we can do the billing based on the tenant and track the error via the queryid.
With this PR, the header works, from the UDF server(with the special databend_udf.py):
```
2024-07-06 13:37:39,519 - udfs.translate - INFO - [Tenant: ['txy004'] | QueryID: ['1e05f3bc-9f74-4951-8c08-d1cfd7049e28']] Batch 1 token count: 41
2024-07-06 13:37:39,519 - udfs.translate - INFO - [Tenant: ['txy004'] | QueryID: ['1e05f3bc-9f74-4951-8c08-d1cfd7049e28']] Translation complete. Total tokens used: 41
```
- - - …

feat: add tenant&queryid to udf client

---

src/query/storages/system/src/user_functions_table.rs
src/query/users/src/user_udf.rs
tests/sqllogictests/suites/udf_server/udf_builtin.test
tests/sqllogictests/suites/udf_server/user_functions_table.test
tests/suites/0_stateless/20+_others/20_0016_udf_timestamp.result

show user functions should display built-in udfs
- Fixes #https://github.com/datafuselabs/databend/pull/15938
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15990)

chore(query): show user functions should display built-in udfs

---

src/common/metrics/src/metrics/cache.rs
src/query/service/tests/it/storages/testdata/caches_table.txt
src/query/storages/common/cache/src/cache.rs
src/query/storages/common/cache/src/lib.rs
src/query/storages/common/cache/src/providers/mod.rs
src/query/storages/common/cache/src/providers/table_data_cache.rs
src/query/storages/common/cache_manager/src/cache_manager.rs
src/query/storages/fuse/src/io/read/block/block_reader_merge_io_async.rs
src/query/storages/system/src/caches_table.rs

refactor: rename metrics & tweak system.caches table
- Column names of `system.caches` changed to 
~~~
+------------------------+--------------------------------------------+-----------+------+
| node                   | name                                       | num_items | size |
+------------------------+--------------------------------------------+-----------+------+
| pEkQjwILMUbTu1GSJ0Vla1 | disk_cache_table_data                      |         0 |    0 |
| pEkQjwILMUbTu1GSJ0Vla1 | memory_cache_bloom_index_file_meta_data    |         0 |    0 |
| pEkQjwILMUbTu1GSJ0Vla1 | memory_cache_bloom_index_filter            |         0 |    0 |
| pEkQjwILMUbTu1GSJ0Vla1 | …

refactor: rename metrics & tweak system.caches table

---

src/common/hashtable/src/utils.rs
src/common/hashtable/tests/it/main.rs

Fix the incorrect `fast_memcmp` function, we just compared the last 16 bytes if the first 16 bytes are equal.
This pr fixes the bug and compares the bytes by 16 bytes step.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16008)

fix(query): fix incorrect fast_memcmp function

---

src/common/io/src/cursor_ext/cursor_read_datetime_ext.rs
src/common/io/src/cursor_ext/mod.rs
src/common/io/src/format_settings.rs
src/common/io/tests/it/cursor_ext/read_datetime_ext.rs
src/query/expression/src/function.rs
src/query/expression/src/types/date.rs
src/query/expression/src/types/timestamp.rs
src/query/formats/src/common_settings.rs
src/query/formats/src/field_decoder/fast_values.rs
src/query/formats/src/field_decoder/json_ast.rs
src/query/formats/src/field_decoder/nested.rs
src/query/formats/src/field_decoder/separated_text.rs
src/query/formats/src/file_format_type.rs
src/query/formats/src/output_format/json.rs
src/query/functions/src/scalars/datetime.rs
src/query/functions/src/scalars/variant.rs
src/query/service/src/sessions/query_ctx.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test

Time conversion handles invalid DST by adding an hour. Accuracy not guaranteed.(disable by default)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16022)

feat(query): add new setting enable_dst_hour_fix

---

src/query/formats/src/common_settings.rs
src/query/formats/src/field_decoder/fast_values.rs
src/query/formats/src/field_decoder/nested.rs
src/query/formats/src/field_decoder/separated_text.rs
src/query/formats/src/field_encoder/csv.rs
tests/sqllogictests/suites/stage/formats/csv/csv_option_nan_inf.test

also:
- Add tests for CSV handling of NaN and Infinity values
- Remove unused code in CSV decoder
reasoning
1.  the name `Nan_Display` sound like a Unload-only option.
2.   `nan`, `inf`, `infinity` (case insensitive) should cover most cases. we can add `nan_if` like `null_if` until really need it. 
need doc change after merge : `Nan_Display` should be Unload only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16028)

feat: Change 'inf' to 'Infinity' when unloading CSV/TSV

---

src/query/service/tests/it/storages/testdata/columns_table.txt
src/query/storages/system/src/queries_profiling.rs
tests/sqllogictests/suites/base/01_system/01_0014_system_queries_profiling.test

```
root@localhost:8000/default> select errors from system.queries_profiling where query_id = (select query_id from system.query_log where query_text='SELECT sleep(3.1)') AND plan_id = 0;
SELECT
errors
FROM
system.queries_profiling
WHERE
query_id = (
SELECT
query_id
FROM
system.query_log
WHERE
query_text = 'SELECT sleep(3.1)'
)
AND plan_id = 0
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐ …
```

chore: add `errors` column and more tests for `system.queries_profiling` table

---

src/common/io/src/cursor_ext/cursor_read_datetime_ext.rs
src/common/io/tests/it/cursor_ext/read_datetime_ext.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test

if enable_dst_hour_fix, return earliest time, else return lastest time
```
// e.g.
// naive_datetime 1990-09-16T01:00:00 in Aisa/Shanghai
// t1.offset.fix = +09:00, t2.offset.fix = +08:00
// t1: 1990-09-16T01:00:00CDT, t2: 1990-09-16T01:00:00CST
// So if enable_dst_hour_fix = true return t1.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16046)

fix(query): fix ambiguous time

---

src/query/service/src/databases/share/dummy_share_database.rs
src/query/service/src/databases/share/mod.rs
src/query/service/src/databases/share/share_database.rs

feat: back compatibility of old share db.
old share db SQL schema is `create database from <share_name>`,and new share db schema is `create database from <share_name> using <share_endpoint>`.
for back compatibility, when `using_share_endpoint` is none, return `DummyShareDatabase` instead, which cannot do anything and make `show databases` worked.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16056)

feat: back compatibility of old share db

---

.github/actions/setup_license/action.yml
.github/workflows/reuse.linux.yml
.github/workflows/reuse.sqllogic.yml
Cargo.toml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16061)

chore(ci): setup license with mask

---

src/query/storages/information_schema/src/tables_table.rs
tests/sqllogictests/suites/base/01_system/01_0003_information_schema.test

information_schema.tables support display view engine
- Fixes #16039
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16058)

chore(query): information_schema.tables support display view engine

---

Cargo.lock
src/query/expression/src/function.rs
src/query/functions/Cargo.toml
src/query/functions/src/scalars/datetime.rs
src/query/service/src/sessions/query_ctx.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
tests/sqllogictests/suites/query/functions/02_0075_function_datetimes_tz.test

Strict datetime parser. Only support ISO 8601 as Default format.The best practice is to turn this parameter on.(enable by default)
if disbale the setting `enable_strict_datetime_parser` , to_date/timestamp(expr) will use crate [`dtparse`](https://github.com/TCeason/dtparse/tree/master) try to convert string to date/timestamp.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16067)

feat(query): add setting enable_strict_datetime_parser

---

src/query/sql/src/planner/optimizer/property/selectivity.rs
tests/sqllogictests/suites/mode/standalone/explain/explain.test
tests/sqllogictests/suites/mode/standalone/explain/join.test
tests/sqllogictests/suites/mode/standalone/explain/push_down_filter/push_down_filter_join/push_down_filter_join_full_outer.test
tests/sqllogictests/suites/mode/standalone/explain/push_down_filter/push_down_filter_join/push_down_filter_join_inner.test
tests/sqllogictests/suites/mode/standalone/explain/push_down_filter/push_down_filter_join/push_down_filter_join_left_outer.test
tests/sqllogictests/suites/mode/standalone/explain/push_down_filter/push_down_filter_join/push_down_filter_join_semi_anti.test
tests/sqllogictests/suites/mode/standalone/explain/push_down_filter/push_down_filter_scan.test
tests/sqllogictests/suites/mode/standalone/explain/range_pruner.test
tests/sqllogictests/suites/mode/standalone/explain/selectivity/pr_16069.test
tests/sqllogictests/suites/mode/standalone/explain/union.test
tests/sqllogictests/suites/mode/standalone/explain_native/explain.test
tests/sqllogictests/suites/mode/standalone/explain_native/join.test
tests/sqllogictests/suites/mode/standalone/explain_native/push_down_filter/push_down_filter_join/push_down_filter_join_full_outer.test
tests/sqllogictests/suites/mode/standalone/explain_native/push_down_filter/push_down_filter_join/push_down_filter_join_inner.test
tests/sqllogictests/suites/mode/standalone/explain_native/push_down_filter/push_down_filter_join/push_down_filter_join_left_outer.test
tests/sqllogictests/suites/mode/standalone/explain_native/push_down_filter/push_down_filter_join/push_down_filter_join_semi_anti.test
tests/sqllogictests/suites/mode/standalone/explain_native/push_down_filter/push_down_filter_scan.test
tests/sqllogictests/suites/mode/standalone/explain_native/range_pruner.test
tests/sqllogictests/suites/mode/standalone/explain_native/union.test
tests/sqllogictests/suites/tpcds/tpcds_join_order.test

Improve selectivity accuracy, use ndv instead of default value.
```sql
root@localhost:8000/tpch_test> SELECT
count()
FROM
orders
WHERE
o_orderdate >= to_date('1993-10-01')
AND o_orderkey > 100;
SELECT
count()
FROM
orders
WHERE
o_orderdate >= to_date('1993-10-01')
AND o_orderkey > 100
┌─────────┐
│ count() │
│  UInt64 │
├─────────┤
│  110480 │
└─────────┘
```
Before:
```sql
EXPLAIN
SELECT
count()
FROM
orders
WHERE
o_orderdate >= to_date('1993-10-01')
AND o_orderkey > 100
AggregateFinal
├── output columns: [count() (#9)]
├── group by: []
├── aggregate functions: [count()]
├── estimated rows: 1.00
└── AggregatePartial
├── group by: []
├── aggregate …
```

feat: improve selectivity accuracy

---

src/query/pipeline/transforms/src/processors/transforms/sort/algorithm.rs
src/query/pipeline/transforms/src/processors/transforms/sort/cursor.rs
src/query/pipeline/transforms/src/processors/transforms/sort/merger.rs
src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge.rs
src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge_base.rs
src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge_limit.rs
tests/sqllogictests/suites/query/window_function/named_window_basic.test

Simply disable peek top2 for loser tree, but it seems to work? NEED more test case.
link #15925
[pprof.samples.cpu.heap.pb.gz](https://github.com/user-attachments/files/16100670/pprof.samples.cpu.heap.pb.gz)
[pprof.samples.cpu.loser.pb.gz](https://github.com/user-attachments/files/16100671/pprof.samples.cpu.loser.pb.gz)
tpc-h 10G
select * from orders order by o_orderdate desc, o_totalprice desc ignore_result;
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/15979)

feat: optimize loser tree, disable peek top2

---

src/query/functions/src/scalars/datetime.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test

When enable parse_datetime_ignore_remainder if timestamp is some, no need to init any parsed.
- fixes: #16077
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16078)

fix(query): if timestamp is some, no need to init parsed

---

scripts/ci/deploy/databend-query-share.sh
src/query/service/src/table_functions/table_function_factory.rs
src/query/storages/fuse/src/operations/mutation/mutator/recluster_mutator.rs
src/query/storages/fuse/src/table_functions/clustering_statistics/clustering_stat.rs
src/query/storages/fuse/src/table_functions/clustering_statistics/clustering_stat_table.rs
src/query/storages/fuse/src/table_functions/clustering_statistics/mod.rs
src/query/storages/fuse/src/table_functions/mod.rs
tests/cloud_control_server/simple_server.py
tests/sqllogictests/suites/base/09_fuse_engine/09_0014_func_clustering_information_function.test
tests/suites/0_stateless/18_rbac/18_0006_mysql_auth.py
tests/suites/1_stateful/02_query/02_0008_profile.py

Show cluster statistics in every blocks.
```
mysql> create table t09_0014(a int, b int) cluster by(b,a);
Query OK, 0 rows affected (0.16 sec)
mysql> insert into t09_0014 values(0,3),(1,1);
Query OK, 2 rows affected (0.15 sec)
mysql> insert into t09_0014 values(1,3),(2,1);
Query OK, 2 rows affected (0.17 sec)
mysql> insert into t09_0014 values(4,4) ;
Query OK, 1 row affected (0.21 sec)
mysql> select *  from t09_0014 order by b, a;
+------+------+
| a    | b    |
+------+------+
|    1 |    1 |
|    2 |    1 |
|    0 |    3 |
|    1 |    3 |
|    4 |    4 |
+------+------+
5 rows in set (0.15 sec)
Read 5 rows, 46.00 B in 0.062 sec., 80.16 rows/sec., 737.45 B/sec.
mysql> select * from …
```

feat(storage): add table function clustering_statistics

---

src/query/service/src/sessions/session_mgr.rs

fix(query): fix session manager dead lock if call instance status
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16088)

fix(query): fix session manager dead lock if call instance status

---

src/query/catalog/src/plan/partition.rs
src/query/catalog/tests/it/partitions.rs
src/query/catalog/tests/it/testdata/partition-reshuffle.txt

PartitionsShuffleKind::ConsistentHash support 
`PartitionsShuffleKind::ConsistentHash` has a significant load skew compared to `PartitionsShuffleKind::Mod`, so we need to figure out when `PartitionsShuffleKind::ConsistentHash` is better than `PartitionsShuffleKind::Mod`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16094)

feat(query): PartitionsShuffleKind::ConsistentHash support 

---

src/query/service/src/servers/admin/v1/instance_status.rs

I'm writing a controller which may use the queue length as the key indicator to auto scale the cluster. it'd be helpful to have this metric visible in the /v1/status api.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16112)

feat(http): expose queries queue length to /v1/status

---

benchmark/clickbench/internal/queries/00.sql
src/query/storages/system/src/columns_table.rs
src/query/storages/system/src/locks_table.rs
src/query/storages/system/src/notification_history_table.rs
src/query/storages/system/src/streams_table.rs
src/query/storages/system/src/tables_table.rs
src/query/storages/system/src/task_history_table.rs
src/query/storages/system/src/util.rs
tests/sqllogictests/suites/base/01_system/01_0001_system_tables.test
tests/sqllogictests/suites/ee/03_ee_vacuum/03_0000_vacuum_ctas.test

Note:
If len of table_ids gt 10, also use list_table
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16098)

refactor(query): If table_id is specified, use it directly

---

src/common/tracing/src/crash_hook.rs
src/common/tracing/src/panic_hook.rs

chore(query): limit frames size for capture backtrace
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16118)

chore(query): limit frames size for capture backtrace

---

src/query/ee/src/storages/fuse/mod.rs
src/query/ee/src/storages/fuse/operations/handler.rs
src/query/ee/src/storages/fuse/operations/vacuum_drop_tables.rs
src/query/ee/tests/it/storages/fuse/operations/vacuum.rs

During the deletion of objects from a dropped table (in parallel), errors from `remove_all` should be propagated instead of being swallowed.
If errors are not propagated, the vacuum operation might proceed to purge metadata from the meta-server while some table data remains unpurged. This would make it impossible to fully complete the `vacuum` action for those dropped tables.
-------
- For the convenience of testing, the `do_vacuum_drop_tables` function has been split into two functions: `vacuum_drop_tables_by_table_info` and `vacuum_drop_tables`
- Properly propagates errors encountered during the parallel deletion of objects of target tables.
- Test `vacuum_drop_tables_by_table_info` using a …

fix: vacuum dropped table in parallel

---

src/query/service/src/servers/admin/v1/instance_status.rs
src/query/service/src/sessions/session_mgr.rs
src/query/service/src/sessions/session_mgr_status.rs

this metric may help the controller to make some decision when there's some session is suspected to be leaked.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16131)

chore(http): exposes max_running_query_executed_time in /v1/status

---

benchmark/clickbench/internal/queries/00.sql
src/query/storages/system/src/tables_table.rs
src/query/storages/system/src/util.rs
tests/sqllogictests/suites/base/01_system/01_0001_system_tables.test

add new api find_eq_and_or_filter, support visitor or filter
in [databend/src/query/storages/system/src/task_history_table.rs at 022009fb39eb5c367c48814e2e08752239a8](https://github.com/datafuselabs/databend/blob/022009fb39eb5c367c48814e2e08752239a8c826/src/query/storages/system/src/task_history_table.rs#L155) ,
```
find_eq_filter(&expr, &mut |col_name, scalar| {
if col_name == "name" {
if let Scalar::String(s) = scalar {
task_name = Some(s.clone());
}
}
Ok(())
});
```
So in this pr, if we directly modify find_eq_filter let it support `or filter` will cause this SQL err:
select xx from task_history where name ='t1' or name = 't2';
So we add a new API.
- - - …

chore(query): optimize tables query speed

---

src/query/storages/system/src/tables_table.rs
src/query/storages/system/src/util.rs
tests/sqllogictests/suites/base/01_system/01_0001_system_tables.test

Because of https://github.com/datafuselabs/databend/pull/16144/files#r1696995697, we need revert pr https://github.com/datafuselabs/databend/pull/16144
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16148)

fix(query): revert find_eq_and_or_filter

---

src/query/catalog/src/table.rs
src/query/service/src/table_functions/numbers/numbers_table.rs
src/query/service/tests/it/storages/fuse/operations/mutation/segments_compact_mutator.rs
src/query/sql/src/executor/physical_plans/physical_hash_join.rs
src/query/sql/src/planner/optimizer/statistics/collect_statistics.rs
src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/operations/changes.rs
src/query/storages/hive/hive/src/hive_table.rs
src/query/storages/orc/src/table.rs
src/query/storages/parquet/src/parquet_rs/parquet_table/table.rs
src/query/storages/stream/src/stream_table.rs
src/query/storages/system/src/columns_table.rs
src/query/storages/system/src/tables_table.rs

- Tweak method `table_statistics` of trait Table
Allows retrieving stale table statistics. 
For read-only attached tables, this means there is no need to read snapshots from the attached location to get fresh statistics. There are no changes for other types of tables.
- `system.columns`
Disabled the table information refreshment in the catalog used during table dumping
- `system.tables`
Allows using stale statistics  while gathering statistics from tables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16152)

refactor: tweak `table_statistics` of trait Table

---

src/query/settings/src/settings_default.rs

`table_lock_expire_secs` set default value to 30 s.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16154)

chore: reset table_lock_expire_secs default value

---

src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/mode/cluster/explain_v2.test
tests/sqllogictests/suites/mode/standalone/explain/explain.test
tests/sqllogictests/suites/query/select.test

fix in operator convert to subquery cast failed, list values data type wrap nullable so that expression and list values can have common data type.
- fixes: #16143
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16159)

fix(query): fix in operator convert to subquery cast failed

---

Cargo.lock
Cargo.toml

Openraft v0.10.0-alpha.2 introduced a bug that when a Leader sees higher
vote, it update its local vote and this updated vote will be considered
as **granted** to a future candidate, resulting in that a candidate that
does not have up to date log can become the Leader and cause data loss.
This bug is fixed in:
- https://github.com/datafuselabs/openraft/pull/1220
Upgrading should be done ASAP.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16175)

fix: meta-service: data inconsistency risk

---

src/query/service/src/pipelines/builders/builder_udf.rs
src/query/service/src/pipelines/processors/transforms/transform_udf_script.rs

Create multiple udf js runtimes to execute in parallel to avoid blocking caused by js udf runtime locks.
Using the internal test sql, the execution time was reduced from 216.769 seconds to 36.534 seconds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16174)

refactor(query): Optimize udf js runtime to avoid lock blocking

---

src/query/ast/src/ast/statements/statement.rs
src/query/ast/src/ast/visitors/walk.rs
src/query/ast/src/ast/visitors/walk_mut.rs
src/query/ast/src/parser/statement.rs
src/query/ast/src/parser/token.rs
src/query/service/src/interpreters/access/privilege_access.rs
src/query/service/src/interpreters/interpreter_explain.rs
src/query/service/src/interpreters/interpreter_factory.rs
src/query/service/src/sessions/queue_mgr.rs
src/query/sql/src/executor/format.rs
src/query/sql/src/executor/mod.rs
src/query/sql/src/planner/binder/binder.rs
src/query/sql/src/planner/optimizer/optimizer.rs
src/query/sql/src/planner/plans/plan.rs
tests/sqllogictests/suites/mode/standalone/explain/explain_analyze_partial.test

`explain analyze partial` will only output infos about real output rows and estimate rows which is helpful to debug the cardinality estimator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16185)

feat: explain analyze output partial infos to debug cardinality estimator

---

Cargo.lock
Cargo.toml
src/meta/service/src/api/http/v1/ctrl.rs
src/meta/service/src/api/http_service.rs
src/meta/service/src/meta_service/raft_service_impl.rs
src/meta/service/src/network.rs
src/meta/service/tests/it/api/http/transfer_leader.rs
src/meta/service/tests/it/store.rs
src/meta/service/tests/it/testing.rs
src/meta/types/build.rs
src/meta/types/proto/meta.proto
src/meta/types/proto/raft.proto
src/meta/types/src/lib.rs
src/meta/types/src/proto_ext/mod.rs
src/meta/types/src/proto_ext/raft_types_ext.rs
src/meta/types/src/proto_ext/transfer_leader_request_ext.rs
src/meta/types/src/raft_types.rs

This commit introduce a new admin API(at `admin_api_address`, by default
`127.0.0.1:28002`) to force the current Leader to transfer leadership to
another node.  The url of this command is
"/v1/ctrl/trigger_transfer_leader?to=<new_leader_node_id>".
Such request returns nothing no matter leadership is successfully
transferred or not.
If the node receives this request is not the leader it does nothing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16198)

feat: transfer leader command for meta-service

---

src/query/storages/common/table_meta/src/meta/v2/segment.rs
src/query/storages/common/table_meta/src/meta/v2/statistics.rs
tests/compat_fuse/compat-logictest/base/fuse_compat_read
tests/compat_fuse/compat-logictest/base/fuse_compat_write

Improve backward compatibility of table column statistics.
While converting table column statistics from legacy versions, ignore newly modified fields (instead of panic).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16200)

fix: backward compatibility of table statistics

---

src/meta/service/src/api/http/v1/ctrl.rs

- The query `to=<next_leader_id>` can be absent in the transfer
leadership request, such as:
```
curl -vqs '<admin_api_address>/v1/ctrl/trigger_transfer_leader'
```
In this case, the next node in the cluster will be used as the default
value for query `to`.
- Add 200 OK response indicating an accepted tranfer leadership
request. The response is a json contains current node id `from`, the
node id to transfer leadership to: `to`, and all of the voter ids in
the cluster `voter_ids`, such as:
```
curl -vqs '127.0.0.1:28101/v1/ctrl/trigger_transfer_leader'
< HTTP/1.1 200 OK
< content-type: application/json; charset=utf-8
< content-length: 37
{"from":1,"to":2,"voter_ids":[1,2,3]}
```
- Add 404 …

feat: meta-service transfer_leader: add response and default value

---

src/query/ast/src/ast/statements/statement.rs
src/query/ast/src/parser/common.rs
src/query/ast/tests/it/testdata/statement.txt
src/query/management/src/role/role_mgr.rs
src/query/service/src/interpreters/interpreter_unset.rs
tests/sqllogictests/suites/base/05_ddl/05_0026_ddl_unset_settings.test
tests/sqllogictests/suites/query/set.test

default unset settings is unset session level setting. Same with set setting
**Note:**
Now unset settings is unset session settings;
If you wants to unset global setting, must call query `UNSET GLOBAL <setting_name>`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16214)

refactor: support unset session|global

---

src/meta/api/src/crud/mod.rs
src/meta/app/src/tenant_key/errors.rs
src/meta/types/src/change.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16225)

refactor: CrudMgr::update should return only when the value is changed

---

src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
src/query/sql/src/executor/physical_plans/physical_mutation.rs
src/query/sql/src/planner/binder/bind_mutation/bind.rs
src/query/sql/src/planner/binder/bind_mutation/merge.rs
src/query/sql/src/planner/binder/bind_mutation/mod.rs
src/query/sql/src/planner/binder/bind_mutation/mutation_expression.rs
src/query/sql/src/planner/binder/mod.rs
src/query/sql/src/planner/optimizer/distributed/distributed_merge.rs
src/query/sql/src/planner/optimizer/distributed/mod.rs
src/query/sql/src/planner/optimizer/optimizer.rs
src/query/sql/src/planner/planner.rs
src/query/sql/src/planner/plans/join.rs
src/query/sql/src/planner/plans/mutation.rs
tests/sqllogictests/suites/mode/cluster/distributed_merge_into.test
tests/sqllogictests/suites/mode/cluster/merge_into_non_equal_distributed.test
tests/sqllogictests/suites/mode/standalone/explain/merge_into.test

1. Distributed merge into does not shuffle row id when target shuffle inner join source.
2. Add tests for distributed merge into.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16228)

chore(planner): fix distributed merge into

---

src/query/expression/src/block.rs
src/query/expression/tests/it/block.rs
tests/sqllogictests/suites/stage/formats/parquet/options/parquet_missing_uuid.test
tests/suites/0_stateless/05_hints/05_0001_set_var.result
tests/suites/0_stateless/18_rbac/18_0007_privilege_access.result
tests/suites/1_stateful/00_stage/00_0012_stage_priv.result
tests/suites/1_stateful/07_stage_attachment/07_0000_insert_with_stage.result
tests/suites/1_stateful/07_stage_attachment/07_0001_replace_with_stage.result
tests/suites/1_stateful/07_stage_attachment/07_0002_insert_with_stage_deduplicate.result

memory_size of block_entry.value::Scalar is not correct
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16230)

fix: block_entry.memory_size

---

src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/window_function/expr_in_window.test
tests/sqllogictests/suites/query/window_function/window_ignore_nulls.test
tests/sqllogictests/suites/query/window_function/window_wisconsin.test
tests/sqllogictests/suites/query/window_function/window_wisconsin_block_size_1.test

cume_dist: The cumulative distribution: (number of partition rows preceding or peer with current row) / total partition rows.
So it's frame caluse should be unbounded.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16242)

fix(query): cume_dist() always return unbounded frame

---

Cargo.lock
src/query/service/src/table_functions/openai/ai_to_sql.rs
tests/suites/5_ee/04_attach_read_only/02_0006_attach_table_ro_issue_16121.result
tests/suites/5_ee/04_attach_read_only/02_0006_attach_table_ro_issue_16121.sh

Disable table info refreshing during execution of `ai_to_sql`. Attached tables may not be able to refresh table info successfully.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16240)

chore: disable table info refreshing for `ai_to_sql`

---

src/query/service/src/servers/http/v1/query/execute_state.rs
src/query/service/src/servers/http/v1/query/http_query.rs
src/query/service/src/sessions/session.rs
src/query/service/src/sessions/session_ctx.rs
src/query/service/tests/it/servers/http/http_query_handlers.rs
tests/sqllogictests/src/util.rs
tests/sqllogictests/suites/query/set.test

part of https://github.com/datafuselabs/databend/issues/16135
the last versions of drivers should be able to work directly.
`bendsql-cli` seems to have problem when meeting `$a`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16239)

feat: http handler support set variable.

---

Cargo.lock
src/meta/binaries/Cargo.toml
src/meta/binaries/metactl/admin.rs
src/meta/binaries/metactl/export_from_disk.rs
src/meta/binaries/metactl/export_from_grpc.rs
src/meta/binaries/metactl/import.rs
src/meta/binaries/metactl/main.rs
src/meta/binaries/metactl/upgrade.rs
tests/suites/1_stateful/09_http_handler/09_0007_token.py

```
databend-meta command line tools
Usage: databend-metactl [OPTIONS] [COMMAND]
Commands:
status                 
export                 
import                 
transfer-leader        
bench-client-num-conn  
help                   Print this message or the help of the given subcommand(s)
Options:
--log-level <LOG_LEVEL>                  [default: INFO]
--grpc-api-address <GRPC_API_ADDRESS>    DEPRECATE: use subcommand instead [env: METASRV_GRPC_API_ADDRESS=] [default: 127.0.0.1:9191]
--import                                 DEPRECATE: use subcommand instead
--export                                 DEPRECATE: use subcommand instead
--raft-dir <RAFT_DIR>                    DEPRECATE: use …
```

refactor(metactl): change to subcommands & support transfer-leader

---

src/meta/app/src/principal/user_auth.rs
src/query/sql/src/planner/binder/ddl/account.rs
tests/suites/0_stateless/18_rbac/18_0006_mysql_auth.py
tests/suites/0_stateless/18_rbac/18_0006_mysql_auth.result

If the administrator sets `MUST_CHANGE_PASSWORD` as true, the option takes effect immediately. The User must change the password at the next login.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16243)

fix(query): fix alter user set `MUST_CHANGE_PASSWORD`

---

src/query/service/tests/it/servers/http/http_query_handlers.rs
src/query/service/tests/it/storages/testdata/columns_table.txt
src/query/sql/src/planner/binder/ddl/table.rs
src/query/storages/information_schema/src/tables_table.rs
src/query/storages/system/src/tables_table.rs
tests/suites/0_stateless/18_rbac/18_0007_privilege_access.result

1. system.tables add a new column `table_type` If table engine is FUSE, value is `BASE TABLE` else value is `VIEW`
2. system.tables store view name, decrease information_schema.tables call union;
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16246)

refactor(query): decrease information_schema.tables call union

---

src/query/catalog/src/table.rs
src/query/service/tests/it/storages/fuse/statistics.rs
src/query/service/tests/it/storages/statistics/column_statistics.rs
src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/statistics/column_statistic.rs

Introduce a new method `accurate_columns_ranges` to the `Table` trait, which returns the "accurate" ranges of the given columns.
The bounds of the column ranges are derived from the segment information of the given table, making them tight. However, for string-type columns, the bounds may have been truncated, which is indicated by the `may_be_truncated` field in the `Bound` struct.
`accurate_columns_ranges` is intended to be used later in the optimization of queries like `SELECT MIN/MAX(col) FROM t`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16247)

refactor: introduce new method `accurate_columns_ranges` to `Table`

---

.github/workflows/reuse.linux.yml

Disable fake time test, since this job is run on self-hosted, may bring troubles to other jobs run on self-hosted.
Maybe we could patch `libfaketime` and let it support jemalloc?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16269)

chore: comment out fake_time test

---

src/query/storages/common/table_meta/src/meta/v2/mod.rs
src/query/storages/common/table_meta/src/meta/v2/segment.rs
src/query/storages/common/table_meta/src/meta/v2/statistics.rs
src/query/storages/common/table_meta/src/meta/v4/segment.rs
src/query/storages/common/table_meta/src/meta/v4/snapshot.rs

https://github.com/datafuselabs/databend/pull/16192 caused column statistics lost, many queries in TPC-H SF100 OOM (**Databend Cloud XSMALL**).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16271)

chore(query): revert #16192

---

scripts/ci/deploy/databend-query-management-mode.sh
scripts/ci/deploy/databend-query-standalone-hive.sh
scripts/ci/deploy/databend-query-standalone-logging.sh
scripts/ci/deploy/databend-query-standalone-native.sh
scripts/ci/deploy/databend-query-standalone.sh
src/meta/api/src/lib.rs
src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/api/src/util.rs
src/meta/app/src/schema/table.rs
src/query/service/src/pipelines/builders/builder_copy_into_table.rs

The use of absolute expiration time can lead to issues due to local time
discrepancies when calling `SchemaAPI`. If the local time lags behind
the meta-service leader's time, records may expire prematurely.
By switching to a relative expiration time (`ttl`), the expiration is
calculated by the meta-service leader, which synchronizes the time
through the Raft log. This ensures that records expire correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16268)

refactor: replace absolute expiration time with relative TTL in schema API

---

src/common/storage/src/operator.rs

Utilize a global request client to share the connection pool. This change can prevent users from creating too many short-lived connections, which could exhaust the entire local port range in extreme cases.
NOTE: this is the default behavior of aws-sdk-sdk and we have already uses the same http client in our `DataOperator`. This change makes sure that all stage, external location table can use the same client.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16276)

refactor: Use global http client to share the connection pool

---

src/query/service/src/interpreters/hook/compact_hook.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0040_auto_compaction_issue_15760.test

`auto_compaction_segments_limit`: default is 3. The maximum number of segments that can be compacted automatically triggered after write(replace-into/merge-into).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16298)

chore: add setting auto_compaction_segments_limit

---

src/meta/api/src/background_api_impl.rs
src/meta/api/src/schema_api_impl.rs
src/meta/api/src/share_api_impl.rs
src/meta/api/src/util.rs
src/meta/raft-store/src/marked/mod.rs
src/meta/types/src/seq_value.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16308)

refactor: adopt `get_pb()` for get_background_task

---

src/query/ee/src/storages/fuse/operations/vacuum_drop_tables.rs

Limit parallelism to a maximum of 3 when vacuuming dropped tables.
- for each vacuum task, the tables passed to it will be processed sequentially
- while removing one table's data, at most 1000 objects will be deleted (in batch)
- let's assume that the rate limit is 3500 (individual) objects per second:
A parallelism degree of up to 3 appears to be safe.
fixes: #16311
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16312)

refactor: Reduce parallelism when vacuuming dropped tables 

---

src/query/ast/src/ast/common.rs
src/query/ast/src/ast/visitors/walk.rs
src/query/sql/src/planner/binder/bind_context.rs
src/query/sql/src/planner/binder/bind_query/bind_select.rs
src/query/sql/src/planner/binder/bind_table_reference/bind_table_function.rs
src/query/sql/src/planner/binder/project_set.rs
src/query/sql/src/planner/binder/table.rs
src/query/sql/src/planner/optimizer/decorrelate/flatten_plan.rs
src/query/sql/src/planner/plans/project_set.rs
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/functions/02_0065_function_json.test

refactor bind set returning functions
- refactor bind set returning functions
- fix set returning function can't find alias columns
```sql
root@0.0.0.0:48000/default> SELECT parse_json('{"k": [1, 2, 3]}') config, json_array_elements(config:k);
SELECT parse_json('{"k": [1, 2, 3]}') AS config, json_array_elements(config:k)
┌───────────────────────────────────────────────┐
│     config    │ json_array_elements(config:k) │
│    Variant    │       Nullable(Variant)       │
├───────────────┼───────────────────────────────┤
│ {"k":[1,2,3]} │ 1                             │
│ {"k":[1,2,3]} │ 2                             │
│ {"k":[1,2,3]} │ 3                             │ …
```

refactor(query): refactor bind set returning functions

---

src/query/sql/src/planner/binder/location.rs
src/query/sql/tests/location.rs

https://github.com/datafuselabs/databend/issues/16304
@Xuanwo is this a mistake or for some reason?  It is surprising that this bug didn’t cause any issues before.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16321)

fix: uri path used as both path and root.

---

src/meta/api/src/kv_app_error.rs
src/meta/app/src/app_error.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16324)

refactor: kv-app-errors does not need serde

---

src/query/sql/src/planner/binder/ddl/table.rs
tests/sqllogictests/suites/base/06_show/06_0001_show_create_table.test
tests/sqllogictests/suites/ee/03_ee_vacuum/03_0000_vacuum_ctas.test

Check essential permissions(put/get/list/del/stat) when creating table with external location.
- The permission check might fail due to reasons other than the permissions themselves
Such as network communication issues that could not be resolved in time. In such cases, it will still be considered a permission checking failure.
- A specified verification key `_v_d77aa11285c22e0e1d4593a035c98c0d` will be left at the external location.   
Please note that running `vacuum drop table` will **not** remove this key from the external location.  There might be multiple tables under the sample external location.
- fixes: #16293
- - - …

feat: Check essential permissions when creating table with external location 

---

src/query/ee/src/storages/fuse/operations/vacuum_drop_tables.rs
src/query/ee/tests/it/storages/fuse/operations/vacuum.rs

When vacuuming dropped tables in dry-run mode, if the targets being `stat` do not exist, the vacuum operation should continue rather than quit.
- fixes: #16291
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16322)

fix: vacuum dry run should carry on when target objects are missing

---

src/query/pipeline/core/src/finished_chain.rs
src/query/pipeline/core/src/lib.rs
src/query/service/src/servers/flight/v1/exchange/exchange_manager.rs

fix(query): fix session leak in ctas
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16337)

fix(query): fix session leak in ctas

---

.gitignore
Cargo.lock
src/meta/api/src/schema_api_test_suite.rs
src/meta/api/src/share_api_test_suite.rs
src/meta/app/src/schema/table.rs
src/meta/binaries/metabench/main.rs
src/query/ee/src/stream/handler.rs
src/query/service/src/interpreters/interpreter_table_drop.rs
src/query/service/src/interpreters/interpreter_view_drop.rs
src/query/service/tests/it/catalogs/database_catalog.rs
src/query/sql/src/planner/binder/ddl/table.rs
src/query/storages/common/blocks/Cargo.toml
src/query/storages/common/blocks/src/memory.rs
src/query/storages/common/session/Cargo.toml
src/query/storages/common/session/src/temp_table.rs
src/query/storages/memory/Cargo.toml
src/query/storages/memory/src/memory_table.rs
tests/sqllogictests/suites/temp_table/temp_memory_tables.sql

As title.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16332)

chore: support temporary table with memory engine

---

src/meta/api/src/background_api_impl.rs
src/meta/api/src/data_mask_api.rs
src/meta/api/src/data_mask_api_impl.rs
src/meta/api/src/kv_app_error.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/api/src/util.rs
src/meta/app/src/app_error.rs
src/meta/app/src/background/background_job_id_ident.rs
src/meta/app/src/background/job_ident.rs
src/meta/app/src/data_mask/mod.rs
src/meta/app/src/tenant_key/errors.rs
src/meta/app/src/tenant_key/ident.rs
src/query/ee/src/data_mask/data_mask_handler.rs
src/query/sql/src/planner/plans/data_mask.rs

Before this commit, only the `name->id` is removed when replacing column
mask, this would cause column mask records leaked as a junk in
meta-service.
Other changes: simplify data mask and background job API implementation
with KVPbApi routines.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16328)

fix: When Replacing column mask, old `name->id->value` should be completely deleted

---

src/meta/api/src/schema_api.rs
src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/app/src/app_error.rs
src/meta/app/src/schema/catalog.rs
src/meta/app/src/schema/catalog_id_ident.rs
src/meta/app/src/schema/catalog_id_to_name_ident.rs
src/meta/app/src/schema/catalog_name_ident.rs
src/meta/app/src/tenant_key/ident.rs
src/query/catalog/src/catalog/manager.rs

- `create` now returns the created ID.
- `drop` now returns the deleted ID.
- Removed the use of `ErrorCode` for `Unknown` and `Exist` errors to
simplify error handling for callers.
- Adopted a map-like API for the `create` and `drop` operations,
improving usability and consistency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16338)

refactor: Catalog Manager API improvements for create and drop operations

---

src/query/sql/src/planner/plans/scan.rs
tests/sqllogictests/suites/mode/standalone/explain/table_sample.test

- fixes:  https://github.com/datafuselabs/databend/issues/16323
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16330)

fix: reduce sample possibility to avoid flaky test

---

src/query/service/src/servers/http/v1/session/login_handler.rs
src/query/service/src/servers/http/v1/session/renew_handler.rs
src/query/service/src/sessions/session_ctx.rs
tests/suites/1_stateful/09_http_handler/09_0007_token.result

so client can choose to try renew before request, in case some requests is not easy to retry (e.g.  upload a a stream as a file).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16313)

feat: login and renew return session_token_validity_in_secs too.

---

src/query/expression/src/utils/display.rs
src/query/sql/src/planner/expression_parser.rs
tests/sqllogictests/suites/base/03_common/03_0041_insert_into_binary.test
tests/suites/1_stateful/09_http_handler/09_0000_invalid_utf8.result

fix(query): fix binary default string
fixes #14721 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16345)

fix(query): fix binary default string

---

src/query/sql/src/planner/binder/scalar_common.rs
tests/sqllogictests/suites/mode/standalone/explain/push_down_filter/push_down_filter_join/push_down_filter_self_join.test

test's before plan:
```
MaterializedCTE
├── output columns: [t1.a (#0), t1.b (#1)]
├── UnionAll
│   ├── output columns: [t1.a (#0), t1.b (#1)]
│   ├── estimated rows: 20.00
│   ├── TableScan
│   │   ├── table: default.default.t1
│   │   ├── output columns: [a (#0), b (#1)]
│   │   ├── read rows: 10
│   │   ├── read size: < 1 KiB
│   │   ├── partitions total: 1
│   │   ├── partitions scanned: 1
│   │   ├── pruning stats: [segments: <range pruning: 1 to 1>, blocks: <range pruning: 1 to 1>]
│   │   ├── push downs: [filters: [], limit: NONE]
│   │   └── estimated rows: 10.00
│   └── TableScan
│       ├── table: default.default.t2
│       ├── output …
```

fix: push filter down join with materialized cte

---

scripts/ci/ci-run-sqllogic-tests.sh

When specific tests to run are specified, the temp table tests should not be executed. 
```
$ ./scripts/ci/ci-run-sqllogic-tests.sh tpcds
Starting standalone DatabendQuery and DatabendMeta
databend-query: no process found
databend-meta: no process found
The databend-query is not killed. force killing.
databend-query: no process found
Start databend-meta...
Waiting on databend-meta 10 seconds...
nohup: appending output to 'nohup.out'
... connecting to :9191
OK :9191 is listening
Start databend-query...
Waiting on databend-query 10 seconds...
nohup: appending output to 'nohup.out'
... connecting to :8000
OK :8000 is listening
Run suites using argument: --run_dir tpcds
Starting databend-sqllogic …
```

chore: separate test run for temp_table suite

---

src/meta/api/src/background_api.rs
src/meta/api/src/background_api_impl.rs
src/meta/api/src/background_api_test_suite.rs
src/meta/api/src/base_api.rs
src/meta/api/src/schema_api.rs
src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/api/src/util.rs
src/meta/app/src/app_error.rs
src/meta/app/src/background/job_ident.rs
src/meta/app/src/tenant_key/resource.rs
src/meta/kvapi/src/kvapi/mod.rs
src/meta/kvapi/src/kvapi/pair.rs
src/query/service/src/catalogs/default/mutable_catalog.rs
src/query/storages/system/src/background_jobs_table.rs

Add `BaseApi::get_id_value()` and `BaseApi::list_id_value()` to
implement generic get and list for `name->id->value` meta data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16357)

refactor: simplify SchemaApi::list_indexes(), get_index() list_background_jobs()

---

Cargo.lock

The ci is blocked by gix-path.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16365)

chore(code): update the version of gix-path in Cargo.lock

---

src/meta/api/src/name_id_value_api.rs
src/meta/api/src/schema_api.rs
src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/app/src/app_error.rs
src/meta/app/src/schema/dictionary.rs
src/meta/app/src/schema/dictionary_id_ident.rs
src/meta/app/src/schema/dictionary_identity.rs
src/meta/app/src/schema/dictionary_name_ident.rs
src/meta/app/src/schema/mod.rs
src/query/catalog/src/catalog/interface.rs
src/query/service/src/catalogs/default/database_catalog.rs
src/query/service/src/catalogs/default/immutable_catalog.rs
src/query/service/src/catalogs/default/mutable_catalog.rs
src/query/service/src/catalogs/default/session_catalog.rs
src/query/service/src/catalogs/share/share_catalog.rs
src/query/service/src/interpreters/interpreter_dictionary_create.rs
src/query/service/src/interpreters/interpreter_dictionary_drop.rs
src/query/service/src/interpreters/interpreter_dictionary_show_create.rs
src/query/service/tests/it/sql/exec/get_table_bind_test.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/storages/hive/hive/src/hive_catalog.rs
src/query/storages/iceberg/src/catalog.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16371)

refactor: simplify dictionary API

---

src/meta/api/src/kv_pb_api/errors/mod.rs
src/meta/api/src/kv_pb_api/errors/read_error.rs
src/meta/api/src/kv_pb_api/mod.rs
src/meta/api/src/name_id_value_api.rs
src/meta/api/src/schema_api_impl.rs
src/meta/types/src/errors/meta_network_errors.rs

If a `mget()` operation such as `get_pb_stream()` or `get_pb_values()`
returns less item than the input keys, it returns an error rather than
silently close the stream. This helps the caller to detect early closed
stream error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16377)

refactor: Add item count check to `KVPbApi::get_pb_stream()`

---

scripts/ci/ci-run-sqllogic-tests.sh
src/query/catalog/src/table_context.rs
src/query/service/src/auth.rs
src/query/service/src/interpreters/interpreter.rs
src/query/service/src/servers/http/middleware.rs
src/query/service/src/servers/http/v1/query/execute_state.rs
src/query/service/src/servers/http/v1/session/client_session_manager.rs
src/query/service/src/servers/mysql/mysql_interactive_worker.rs
src/query/service/src/servers/mysql/mysql_session.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sessions/session.rs
src/query/service/src/sessions/session_ctx.rs
src/query/service/tests/it/sql/exec/get_table_bind_test.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/sql/src/planner/binder/ddl/table.rs
src/query/storages/common/session/src/temp_table.rs
tests/sqllogictests/src/client/http_client.rs
tests/sqllogictests/src/main.rs
tests/sqllogictests/src/util.rs
tests/sqllogictests/suites/stage/copy_into_temp_table.sql
tests/sqllogictests/suites/temp_table/create_temp_tables.sql
tests/sqllogictests/suites/temp_table/temp_memory_tables.sql

1.	Implement a mechanism to clear data on S3 in case of a crash. Both MySQL and HTTP sessions need to write an ID to metadata with a TTL (time-to-live) and refresh it at regular intervals. The MySQL handler uses a daemon task for each connection, starting when the first query is made. The HTTP handler does it when renewing token.
2.	Both handlers need to clear data when a session ends to free up memory.
3.	The HTTP handler needs to clone the `temp_tbl_mgr` into the global ClientSessionManager and inject it into the session object when the next query arrives. 
4.	Consequently, the HTTP handler needs to release it (and clean up data) when a session times out.  only keep clones that are not …

feat: http handler support temp table.

---

src/meta/api/src/schema_api.rs
src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/query/catalog/src/catalog/interface.rs
src/query/catalog/src/database.rs
src/query/service/src/catalogs/default/database_catalog.rs
src/query/service/src/catalogs/default/immutable_catalog.rs
src/query/service/src/catalogs/default/mutable_catalog.rs
src/query/service/src/catalogs/default/session_catalog.rs
src/query/service/src/catalogs/share/share_catalog.rs
src/query/service/src/databases/default/default_database.rs
src/query/service/src/databases/share/dummy_share_database.rs
src/query/service/src/databases/share/share_database.rs
src/query/service/tests/it/sql/exec/get_table_bind_test.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/storages/hive/hive/src/hive_catalog.rs
src/query/storages/iceberg/src/catalog.rs
src/query/storages/system/src/tables_table.rs
src/query/storages/system/src/util.rs
tests/sqllogictests/suites/base/06_show/06_0019_show_drop_tables.test

1. add get_single_table_history api
2. optimize show drop tables
3. get_table_history -> get_tables_history
Performance
```
==> Running Q2: internal/queries/02.sql
select name from system.tables where name in ('t_1', 't_2');
3
Q2[1] succeeded in 0.045 seconds
Q2[2] succeeded in 0.044 seconds
Q2[3] succeeded in 0.046 seconds
==> Running Q3: internal/queries/03.sql
select name from system.tables_with_history where name in ('t_1', 't_2');
3
Q3[1] succeeded in 0.046 seconds
Q3[2] succeeded in 0.045 seconds
Q3[3] succeeded in 0.046 seconds
```
- - - …

refactor(query): optimize show drop tables

---

Cargo.lock
src/meta/embedded/Cargo.toml
src/meta/embedded/tests/it/main.rs
src/meta/embedded/tests/it/schema_api_impl.rs
src/meta/embedded/tests/it/testing.rs
src/meta/kvapi/src/kvapi/api.rs
src/meta/raft-store/src/state_machine/sm.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16384)

chore: add logging for embedded meta test

---

src/query/pipeline/transforms/src/processors/transforms/sort/cursor.rs
src/query/pipeline/transforms/src/processors/transforms/sort/rows/common.rs
src/query/pipeline/transforms/src/processors/transforms/sort/rows/mod.rs
src/query/pipeline/transforms/src/processors/transforms/sort/rows/simple.rs
src/query/pipeline/transforms/src/processors/transforms/transform_multi_sort_merge.rs
src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge.rs
src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge_base.rs
src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge_limit.rs
src/query/pipeline/transforms/tests/it/merger.rs
src/query/service/src/pipelines/processors/transforms/transform_sort_spill.rs

Simplified sort simple rows implementation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16382)

chore(query): Simplified sort simple rows implementation

---

Cargo.lock
src/query/service/src/pipelines/processors/transforms/transform_udf_server.rs

make external server parallel by batch `external_server_request_batch_rows`
1. let's create a udf benchmark function 'wait', it will sleep 0.1 second per row.
```
@udf(input_types=["INT"], result_type="INT")
def wait(x):
time.sleep(0.1)
return x
```
2. let's select from this udf function 
```
🐳 :) select wait(number) from numbers(30) ignore_result;
0 row read in 3.059 sec. Processed 30 row, 240B (9.81 rows/s, 78B/s)
🐳 :) explain pipeline select wait(number) from numbers(30) ignore_result;
EmptySink × 1
UdfTransform × 1
CompoundBlockOperator(Map) × 1
NumbersSourceTransform × 1
```
The source is only one block, so it will execute the data row by …

feat(query): make external server parallel by batch

---

src/meta/api/src/data_mask_api_impl.rs
src/meta/api/src/schema_api_impl.rs
src/meta/app/src/schema/database.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16395)

refactor: replace get_pb_value() with get_pb()

---

Cargo.lock
src/query/sql/src/planner/binder/bind_table_reference/bind_table.rs

fix clippy err
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16397)

chore(ci): fix cargo clippy

---

src/common/base/src/runtime/profile/profiles.rs
src/common/metrics/src/lib.rs
src/common/metrics/src/metrics/external_server.rs
src/common/metrics/src/metrics/mod.rs
src/query/service/src/interpreters/interpreter_explain.rs
src/query/service/src/pipelines/processors/transforms/transform_udf_server.rs

chore(query): add external server request profile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16400)

chore(query): add external server request profile

---

Cargo.lock
src/query/service/Cargo.toml
src/query/service/src/pipelines/builders/builder_udf.rs
src/query/service/src/pipelines/processors/transforms/transform_udf_server.rs
src/query/settings/src/settings_default.rs

chore(query): 
1. external_server_request_retry_times can be zero
2. don't retry when h2 error occurs
3. use backon to retry the subblock 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16405)

chore(query): refactor udf retry

---

src/common/metrics/src/metrics/external_server.rs
src/query/service/src/pipelines/processors/transforms/transform_udf_server.rs

chore(query): add connect duration metric for udf
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16407)

chore(query): add connect duration metric for udf

---

src/query/sql/src/executor/format.rs
tests/sqllogictests/suites/mode/standalone/explain/explain_analyze_partial.test

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16408)

chore: add join type for explain analyze partial

---

src/query/service/src/sessions/query_ctx.rs
src/query/storages/iceberg/src/catalog.rs

Non-default catalog doesn't have table functions, we should avoid calling them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16410)

fix: non-default catalog should not call get_table_function 

---

Cargo.lock
src/query/service/src/auth.rs
src/query/service/src/servers/http/http_services.rs
src/query/service/src/servers/http/middleware.rs

so client has more choose of when to call it.
the response is not sensitive (addrs) 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16392)

feat: discovery_nodes not need auth.

---

Cargo.lock

`cargo audit` block CI, try solve it
```Run cargo audit --db ./target/advisory-db
==> build-tool using image runner/build-tool:dev-nightly-2024-07-02
Fetching advisory database from `[https://github.com/RustSec/advisory-db.git`](https://github.com/RustSec/advisory-db.git%60)
Loaded 658 security advisories (from ./target/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (1413 crate dependencies)
Crate:     quinn-proto
Version:   0.11.6
Title:     `Endpoint::retry()` calls can lead to panicking
Date:      2024-09-02
ID:        RUSTSEC-2024-0373
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0373
Severity:  7.5 (high)
Solution:  Upgrade to >=0.11.7
```
- - - …

chore: bump quinn-proto to 0.11.8 for cargo audit pass

---

src/query/sql/src/planner/optimizer/join/single_to_inner.rs

fix(query): fix stack overflow for optimizer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16420)

fix(query): fix stack overflow for optimizer

---

src/meta/api/src/name_id_value_api.rs

`mget_id_value_compat([names])` fetch a list of `name->id->value` from
meta-service with exact 2 mget() operations.
This method can be used to optimize batch get operations. For example to
get a list of `(DatabaseNameIdent, DatabaseId, DatabaseMeta)`.
This method requires the id type to be a `Id<xxxId>` type.
- Part of #16421
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16425)

refactor: add mget_id_value_compat()

---

src/query/service/src/locks/lock_manager.rs
src/query/service/src/sessions/query_ctx.rs

List lock revisions are returned in big-endian order, we need to sort them in ascending numeric order.
```
a4074603-bd1b-404e-bfc3-9a9617ff529b 2024-09-10T11:54:05.238526+08:00  WARN 
databend_query::locks::lock_manager: lock_manager.rs:135 list_lock_revisions reply: 
[(103, LockMeta { user: "root", node: "j3MoOFeUWV7kdHDgmWxxR2", query_id: "e67d5d9a-3e7f-466b-b923-2264077ce8ae", created_on: 2024-09-10T03:54:05.195603634Z, acquired_on: Some(2024-09-10T03:54:05.204791839Z), lock_type: TABLE, extra_info: {} }), 
(106, LockMeta { user: "root", node: "j3MoOFeUWV7kdHDgmWxxR2", query_id: "a4074603-bd1b-404e-bfc3-9a9617ff529b", created_on: 2024-09-10T03:54:05.228411910Z, acquired_on: None, lock_type: …
```

fix: table lock flaky test

---

Cargo.lock
src/query/catalog/src/catalog/interface.rs
src/query/service/src/catalogs/default/database_catalog.rs
src/query/service/src/catalogs/default/immutable_catalog.rs
src/query/service/src/catalogs/default/mutable_catalog.rs
src/query/service/src/catalogs/default/session_catalog.rs
src/query/service/tests/it/sql/exec/get_table_bind_test.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/storages/hive/hive/src/hive_catalog.rs
src/query/storages/iceberg/src/catalog.rs
src/query/storages/system/src/columns_table.rs
src/query/storages/system/src/databases_table.rs
src/query/storages/system/src/tables_table.rs
src/query/users/Cargo.toml
src/query/users/src/visibility_checker.rs
tests/suites/0_stateless/18_rbac/18_0013_column_privilege.result
tests/suites/0_stateless/18_rbac/18_0013_column_privilege.sh

Optimize:
in system table engine , we can only get database that current user can be visibility.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16421)

refactor(query): first check privilege in SystemEngine get_full_data

---

src/meta/service/src/configs/outer_v0.rs
src/meta/service/src/meta_service/raft_service_impl.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16438)

chore: log remote addr when meta-service raft API recevies a message

---

src/common/building/src/lib.rs
src/query/service/src/sessions/query_ctx.rs

Load DATABEND_ENTERPRISE_LICENSE_EMBEDDED while building
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16440)

feat: Load DATABEND_ENTERPRISE_LICENSE_EMBEDDED while building

---

src/meta/api/src/schema_api.rs
src/meta/api/src/schema_api_impl.rs
src/meta/app/src/schema/mod.rs
src/meta/app/src/schema/table.rs
src/query/catalog/src/catalog/interface.rs
src/query/catalog/src/database.rs
src/query/service/src/catalogs/default/database_catalog.rs
src/query/service/src/catalogs/default/immutable_catalog.rs
src/query/service/src/catalogs/default/mutable_catalog.rs
src/query/service/src/catalogs/default/session_catalog.rs
src/query/service/src/databases/default/default_database.rs
src/query/service/tests/it/sql/exec/get_table_bind_test.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/storages/hive/hive/src/hive_catalog.rs
src/query/storages/iceberg/src/catalog.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16446)

refactor: simplify vacuum drop table handling

---

src/query/pipeline/core/src/processors/shuffle_processor.rs
src/query/pipeline/core/tests/it/pipelines/processors/shuffle.rs

refactor(executor): use event cause to refactor shuffle processor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16445)

refactor(executor): use event cause to refactor shuffle processor

---

src/query/service/tests/it/servers/http/http_query_handlers.rs
src/query/service/tests/it/storages/testdata/columns_table.txt
src/query/storages/system/src/tables_table.rs
tests/suites/0_stateless/18_rbac/18_0007_privilege_access.result

add column: system.tables.total_columns
Fix: #16449
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16447)

chore(query): add column: system.tables.total_columns

---

src/query/storages/iceberg/src/table.rs

Table desc should allow nested db_name
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16414)

fix(iceberg): Table desc should allow nested db_name

---

src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/app/src/schema/table.rs
src/query/service/src/interpreters/interpreter_vacuum_drop_tables.rs

- Replace `None` limit with `usize::MAX` to simplify capacity checking
logic.
- Replace `None` retention time with `DateTime::MAX_UTC`.
- Rename `TableInfoFilter` variants to reflect its purpose more
precisely.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16450)

refactor: cleanup logic to get tables to vacuum

---

src/query/catalog/src/table_context.rs
src/query/service/src/interpreters/hook/compact_hook.rs
src/query/service/src/interpreters/interpreter_insert_multi_table.rs
src/query/service/src/pipelines/builders/builder_recluster.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/service/tests/it/sql/exec/get_table_bind_test.rs
src/query/service/tests/it/storages/fuse/conflict.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
src/query/storages/fuse/src/operations/common/generators/append_generator.rs
src/query/storages/fuse/src/operations/common/generators/mutation_generator.rs
src/query/storages/fuse/src/operations/common/generators/snapshot_generator.rs
src/query/storages/fuse/src/operations/common/generators/truncate_generator.rs
src/query/storages/fuse/src/operations/common/processors/multi_table_insert_commit.rs
src/query/storages/fuse/src/operations/common/processors/sink_commit.rs
tests/sqllogictests/suites/base/09_fuse_engine/090101_multi_table_insert_auto_compact.sql

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16443)

feat: Auto compact(re-cluster) for multiple table insertion statement

---

tests/sqllogictests/scripts/prepare_tpcds_data.sh
tests/sqllogictests/scripts/prepare_tpch_data.sh
tests/sqllogictests/suites/stage/copy_from_http.test
tests/suites/1_stateful/04_mini_dataset/04_0000_mini_ontime.sh
tests/suites/1_stateful/04_mini_dataset/04_0001_mini_hits.sh

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16455)

chore(ci): fix dataset domain

---

tests/sqllogictests/suites/base/09_fuse_engine/09_0036_merge_into_without_distributed_enable.test

fix flaky test `tests/sqllogictests/suites/base/09_fuse_engine/09_0036_merge_into_without_distributed_enable.test`, by using different stage names for http/mysql handlers
- fixes: #16456
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16457)

fix: flaky test 09_0036_merge_into_without_dist

---

src/query/expression/src/kernels/mod.rs
src/query/expression/src/kernels/sort.rs
src/query/expression/src/kernels/sort_compare.rs
src/query/expression/src/types.rs
src/query/expression/src/types/any.rs
src/query/expression/src/types/binary.rs
src/query/expression/src/types/bitmap.rs
src/query/expression/src/types/boolean.rs
src/query/expression/src/types/date.rs
src/query/expression/src/types/decimal.rs
src/query/expression/src/types/empty_array.rs
src/query/expression/src/types/empty_map.rs
src/query/expression/src/types/generic.rs
src/query/expression/src/types/geography.rs
src/query/expression/src/types/geometry.rs
src/query/expression/src/types/null.rs
src/query/expression/src/types/nullable.rs
src/query/expression/src/types/number.rs
src/query/expression/src/types/string.rs
src/query/expression/src/types/timestamp.rs
src/query/expression/src/types/variant.rs
src/query/expression/src/utils/mod.rs
src/query/expression/src/utils/visitor.rs
src/query/expression/src/values.rs
src/query/expression/tests/it/sort.rs
src/query/service/src/pipelines/processors/transforms/transform_sort_spill.rs

1. Introduce ColumnVisitor trait and SortCompare
2. Optimize kernel sort performance (Now we are using column vertical sort, which removes virtual call in sort compare functions)
Sort Performance with 2~3 order column test example, gain about 40%~50%
```
select l_partkey, l_returnflag from (select * from tpch_test.lineitem limit 10000000) order by l_partkey desc, l_returnflag asc ignore_result;
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16458)

refactor(query): sort kernel optimization

---

src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/app/src/schema/table.rs
src/query/service/src/pipelines/builders/builder_copy_into_table.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16454)

refactor: refactor vacuum

---

src/meta/api/src/schema_api_test_suite.rs
src/meta/api/src/sequence_api.rs
src/meta/api/src/sequence_api_impl.rs
src/meta/app/src/app_error.rs
src/meta/app/src/schema/sequence.rs
src/query/service/src/catalogs/default/mutable_catalog.rs

- Change return type from Result to Option<Sequence>
- Return None when sequence is not found
- This allows callers to easily distinguish between "not found" and other errors
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16463)

chore: simplify get_sequence() and get_sequence_next_value()

---

src/meta/api/src/schema_api_impl.rs
tests/suites/0_stateless/02_ddl/02_0000_create_drop_view.py
tests/suites/1_stateful/09_http_handler/09_0007_token.py

When executing `DROP TABLE IF EXISTS`, if the table metadata contains a `drop_on` flag, indicating that the table has already been marked for deletion, no error will be returned. This ensures the operation is idempotent, preventing unnecessary errors from being raised if the table has already been dropped.
- fixes: #16188
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16465)

fix: Multi-thread recreate view/table gives error

---

src/query/pipeline/core/src/lib.rs
src/query/pipeline/core/src/pipeline.rs
src/query/pipeline/core/src/processors/mod.rs
src/query/pipeline/core/src/processors/processor.rs
src/query/pipeline/core/src/processors/shuffle_processor.rs

chore(executor): support for data exchange between different processors within the pipeline
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16467)

chore(executor): support for data exchange between different processors within the pipeline

---

src/query/service/src/pipelines/executor/executor_graph.rs
src/query/service/tests/it/pipelines/executor/executor_graph.rs

chore(executor): more edge detail for executing graph
before:
```
digraph {
0 [ label = "system.one" ]
1 [ label = "CompoundBlockOperator(Map)" ]
2 [ label = "CompoundBlockOperator(Project)" ]
3 [ label = "PullingExecutorSink" ]
0 -> 1 [ ]
1 -> 2 [ ]
2 -> 3 [ ]
}
```
after
```
digraph {
0 [ label = "system.one" ]
1 [ label = "CompoundBlockOperator(Map)" ]
2 [ label = "CompoundBlockOperator(Project)" ]
3 [ label = "PullingExecutorSink" ]
0 -> 1 [ 0 -> 0]
1 -> 2 [ 0 -> 0]
2 -> 3 [ 0 -> 0]
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16468)

chore(executor): more edge detail for executing graph

---

src/common/tracing/src/init.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16469)

fix: log query detail and profile with identical format

---

src/meta/api/src/name_id_value_api.rs
src/meta/app/src/schema/database.rs
src/meta/proto-conv/src/database_from_to_protobuf_impl.rs
src/meta/proto-conv/src/util.rs
src/meta/proto-conv/tests/it/main.rs
src/meta/proto-conv/tests/it/proto_conv.rs
src/meta/proto-conv/tests/it/v002_database_meta.rs
src/meta/proto-conv/tests/it/v055_table_meta.rs
src/meta/proto-conv/tests/it/v074_table_db_meta.rs
src/meta/proto-conv/tests/it/v096_database_meta.rs
src/meta/proto-conv/tests/it/v101_database_meta.rs
src/meta/proto-conv/tests/it/v110_database_meta_gc_in_progress.rs
src/meta/protos/proto/database.proto

If `gc_in_progress` is set, no un-drop can be done on this database.
Because the related data may already have been deleted.
This commit does not use this flag yet, and will be used in next commit.
- Part of #16433
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16464)

refactor: add DatabaseMeta.gc_in_progress

---

src/meta/api/src/kv_pb_crud_api.rs
src/meta/api/src/name_value_api.rs
src/meta/api/src/schema_api_impl.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16484)

refactor: add KVPbCrudApi::crud_try_insert() and crud_try_upsert()

---

src/meta/api/src/kv_pb_api/mod.rs
src/meta/api/src/schema_api_impl.rs
src/meta/app/src/schema/database_name_ident.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16485)

refactor: SchemaApi::list_databases()

---

src/binaries/query/entry.rs
src/common/exception/src/exception_code.rs
src/common/license/src/license.rs
src/common/license/src/license_manager.rs
src/query/ee/src/license/license_mgr.rs

Extract the code that is unrelated to cluster quotas from https://github.com/datafuselabs/databend/pull/15865.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16492)

refactor(query): refactor license manager

---

src/meta/api/src/schema_api_impl.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16499)

chore: simplify get_gc_table_info()

---

src/meta/api/src/util.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16503)

refactor: get_tableinfos_by_ids()

---

Cargo.lock
Cargo.toml
src/query/functions/src/lib.rs
src/query/sql/src/planner/binder/aggregate.rs
src/query/sql/src/planner/binder/project.rs
src/query/sql/src/planner/binder/select.rs
src/query/sql/src/planner/planner_cache.rs
src/query/sql/src/planner/semantic/async_function_rewriter.rs
src/query/sql/src/planner/semantic/udf_rewriter.rs
src/query/storages/common/index/Cargo.toml
src/query/storages/fuse/Cargo.toml
tests/sqllogictests/suites/query/functions/02_0077_function_dict_get.test

- The plan of search function, async function and udf contains some arguments defined in meta, which may be modified by user at any time. If the plan is cached, the modified arguments cannot take effect and a wrong result will be displayed. Therefore, sql containing these types of functions is made non-cacheable.
- allow async function execute in where clause
- fix async function as name could not be displayed 
- replace `tantivy`, `tantivy-jieba`, `ethnum` to `datafuse-extras`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16510)

fix(query): fix planner cache cause modify async function does not take effect

---

src/query/expression/src/utils/block_thresholds.rs
src/query/service/src/interpreters/hook/compact_hook.rs
src/query/service/src/interpreters/interpreter_table_recluster.rs
src/query/service/src/pipelines/builders/builder_recluster.rs
src/query/service/src/pipelines/builders/builder_sort.rs
src/query/storages/fuse/src/operations/mutation/mutator/recluster_mutator.rs
src/query/storages/fuse/src/operations/recluster.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0016_remote_alter_recluster.test
tests/sqllogictests/suites/base/09_fuse_engine/09_0041_auto_compaction.test
tests/suites/0_stateless/02_ddl/02_0000_create_drop_view.py

1. avoid scan all segments when do hook recluster
2. recluster will compact the small block and segments.
3. insert will trigger compact and recluster.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16498)

chore(storage): hook recluster avoid scan all segments

---

src/query/service/src/catalogs/default/mutable_catalog.rs

This PR addresses a potential error in the "list databases" functionality, which could disrupt the display of all databases.
Like say we removed `SHARE`, the error will:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16514)

feat(catalog): ignore error when listing databases

---

src/query/service/src/schedulers/scheduler.rs
tests/sqllogictests/suites/query/union.test

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16515)

fix: `ignore_result` doesn't have an effect on union

---

src/common/storage/src/operator.rs

Output whole error message with source while retry.
This PR will make users to debug errors happened during retry easier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16519)

refactor: Output whole error message with source while retry

---

src/query/ast/src/parser/common.rs

fix https://github.com/datafuselabs/databend/issues/16521
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16522)

feat: limit stage name to plain_identifier

---

src/meta/app/src/principal/procedure.rs
src/query/ast/src/ast/statements/procedure.rs
src/query/ast/src/parser/statement.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/stmt.txt
src/query/management/src/procedure/procedure_mgr.rs
src/query/service/src/interpreters/interpreter_procedure_create.rs
src/query/service/src/interpreters/interpreter_procedure_drop.rs
src/query/sql/src/planner/binder/ddl/procedure.rs
src/query/sql/src/planner/plans/ddl/procedure.rs
src/query/users/src/user_procedure.rs
tests/sqllogictests/suites/base/15_procedure/15_0002_procedure.test

Part of https://github.com/datafuselabs/databend/issues/16501
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/databend/16500)

feat(query): Procedure support drop if exists and create or replace

---

src/query/functions/src/scalars/datetime.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test

date_add support week as unit.
SELECT DATE_ADD('week', 1, TODAY())=DATE_ADD('day', 7, TODAY())
- fixes:  https://github.com/databendlabs/databend/issues/16402
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16530)

feat(query): DATE_ADD Functions to support week as a unit

---

src/query/sql/src/executor/physical_plan.rs
tests/sqllogictests/suites/base/03_common/03_0046_copy_into_from_stage.test

fix(query): fix copy into table with disable distributed copy into
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16529)

fix(query): fix copy into table with disable distributed copy into

---

src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/app/src/schema/mod.rs
src/meta/app/src/schema/table.rs
src/query/service/src/interpreters/interpreter_vacuum_drop_tables.rs

- Replace `TableInfoFilter` with `Range<Option<DateTime<Utc>>>` for more flexible filtering
- Simplify `ListDroppedTableReq` struct and add builder methods
- Update schema_api_impl and tests to use new ListDroppedTableReq API
- Adjust vacuum logic in interpreter_vacuum_drop_tables to use new API
- Minor code cleanup and documentation improvements
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16531)

refactor: dropped table listing and GC

---

src/meta/api/src/schema_api_impl.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16539)

fix: Only when all tables are included, the db can be dropped

---

src/meta/api/src/schema_api_impl.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16540)

refactor: SchemaAPI::do_get_table_history

---

src/common/base/src/base/string.rs
src/common/base/tests/it/string.rs
src/query/service/src/interpreters/interpreter.rs
src/query/service/src/servers/http/clickhouse_handler.rs
src/query/service/src/servers/http/v1/query/http_query.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
src/query/settings/tests/it/setting.rs

New setting for short length sql.
- fixes: #16462 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16502)

feat: short sql length setting

---

src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/app/src/schema/table.rs
src/query/service/src/interpreters/interpreter_vacuum_drop_tables.rs

There is no need to store tables inside `DroppedId::Db`:
the tables belonging to a DB for gc can still be stored in `DroppedId::Table`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16542)

refactor: `DroppedId` for listing db/tables for gc

---

src/meta/api/src/schema_api_impl.rs
src/meta/app/src/schema/mod.rs
src/meta/app/src/schema/table.rs
src/meta/app/src/schema/table_niv.rs

`SchemaApi` can not provide enough information to build a valid
`TableInfo`, such as, it does not know about catalog type and database
type. Therefore `get_history_tables_for_gc()` should just return `table
name, table id and the table meta` to its caller to let the build a
`TableInfo` if needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16545)

refactor: `get_history_tables_for_gc()` should not return `TableInfo`, but just table name, id and values

---

src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/app/src/schema/table.rs
src/query/service/src/catalogs/default/mutable_catalog.rs

`SchemaApi` can not provide enough information such as `CatalogInfo` and
`DatabaseType`. Therefore `SchemaApi` should not build a `TableInfo`,
leave such task to its caller.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16548)

fix: move TableInfo building out of SchemaApi

---

src/meta/api/src/schema_api_impl.rs
src/query/ee/src/storages/fuse/operations/vacuum_drop_tables.rs
src/query/ee/tests/it/storages/fuse/operations/vacuum.rs
src/query/ee_features/vacuum_handler/src/vacuum_handler.rs
src/query/service/src/interpreters/interpreter_vacuum_drop_tables.rs

Database-name in string can not be used to identify a database.
A database can be renamed and leads to a undefined behaviors.
In this commit, when a table is failed to vacuum, mark the belonging
database as failed by database-id, instead of by database-name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16553)

fix: identify failed vacuum db by id

---

src/meta/api/src/lib.rs
src/meta/api/src/schema_api.rs
src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/api/src/util.rs
src/query/service/src/databases/default/default_database.rs

Make this method return `TableNIV` instead of `TableInfo`. TableInfo
includes information that `SchemaApi` can not provide.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16572)

refactor: simplify get_tables_history()

---

src/common/base/src/base/dma.rs

Direct io syscall not available on mac, so we need a fallback.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16574)

fix: direct io syscall not available on mac

---

src/query/sql/src/planner/optimizer/decorrelate/decorrelate.rs
src/query/sql/src/planner/optimizer/decorrelate/subquery_rewriter.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
src/query/sql/src/planner/semantic/distinct_to_groupby.rs
tests/sqllogictests/suites/mode/standalone/explain/explain.test
tests/sqllogictests/suites/mode/standalone/explain/limit.test
tests/sqllogictests/suites/mode/standalone/explain/prune_column.test
tests/sqllogictests/suites/mode/standalone/explain/subquery.test
tests/sqllogictests/suites/mode/standalone/explain_native/limit.test
tests/sqllogictests/suites/mode/standalone/explain_native/prune_column.test
tests/sqllogictests/suites/mode/standalone/explain_native/subquery.test
tests/sqllogictests/suites/query/window_function/window_with_subquery.test

Because we introduced single to inner join optimization, so we don't need to maintain the method `rewrite_uncorrelated_scalar_subquery` instead of rewriting to single join directly.
Then we can solve the issue15977.
Note: `select count(distinct a) over (partition by 1) from t1;` `PARTITION BY 1` is a special syntax that actually means **no partitioning**, i.e., all rows are treated as a partition. So `partition by (select b from t2)` is not semantic if it returns more than one row but if returns only one row, it's valid, meaning **no partitioning**.
- fixes: https://github.com/databendlabs/databend/issues/15977
- - - …

fix: window in scalar subquery returns wrong results

---

src/meta/api/src/schema_api.rs
src/meta/api/src/schema_api_impl.rs
src/query/service/src/databases/default/default_database.rs

In cases where the `database-id` is already known, use this method to
get a table as replacement of `get_table()`. `get_table()` re-fetch
database-id by database-name, thus leads to additional unnecessary delay
and potential consistency issues, because a database may already be
renamed, and using the original database-name just gets the wrong
database instance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16582)

refactor: add SchemaApi::get_table_in_db

---

src/query/service/src/interpreters/interpreter_connection_show.rs
src/query/service/src/interpreters/interpreter_data_mask_desc.rs
src/query/service/src/interpreters/interpreter_database_show_create.rs
src/query/service/src/interpreters/interpreter_file_format_show.rs
src/query/service/src/interpreters/interpreter_network_policies_show.rs
src/query/service/src/interpreters/interpreter_network_policy_desc.rs
src/query/service/src/interpreters/interpreter_notification_desc.rs
src/query/service/src/interpreters/interpreter_password_policy_desc.rs
src/query/service/src/interpreters/interpreter_role_show.rs
src/query/service/src/interpreters/interpreter_table_describe.rs
src/query/service/src/interpreters/interpreter_table_show_create.rs
src/query/service/src/interpreters/interpreter_task_describe.rs
src/query/service/src/interpreters/interpreter_tasks_show.rs
src/query/service/src/interpreters/interpreter_view_describe.rs

Data definition language is a syntax for creating and modifying database objects such as tables, indices, and users.
SHOW / DESC is not ddl.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16583)

chore(query): SHOW/DESC is not DDL

---

src/query/sql/src/planner/optimizer/rule/rewrite/rule_eliminate_union.rs
tests/sqllogictests/suites/mode/standalone/explain/union.test
tests/sqllogictests/suites/query/union.test

- fixes: https://github.com/databendlabs/databend/issues/16564
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16584)

fix: avoid eliminating the left child of union in `RuleEliminateUnion`

---

src/meta/api/src/schema_api.rs
src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/query/service/src/databases/default/default_database.rs

It does not need to accept a `database-name` argument just for building
an error.
It does not need to return application level error: if a table is not
found, just return an empty list.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16586)

refactor: SchemaApi::get_table_meta_history()

---

src/query/ast/src/ast/quote.rs
src/query/ast/src/parser/statement.rs
src/query/ast/tests/it/testdata/stmt-error.txt

part of https://github.com/databendlabs/databend/issues/16570
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16578)

refactor: fix error message.

---

src/query/sql/src/executor/physical_plans/physical_mutation.rs
src/query/sql/src/planner/optimizer/optimizer.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0042_merge_into_issue_16581.test
tests/sqllogictests/suites/base/09_fuse_engine/09_0042_merge_into_issue_16588.test
tests/sqllogictests/suites/mode/cluster/merge_into_non_equal_distributed.test
tests/sqllogictests/suites/mode/standalone/explain/merge_into.test

The reason is that the condition is false, after `RuleEliminateFilter`, it is converted to `ConstantTableScan`, which makes the fileds in mutation invalid.
```sql
mysql> create table s(a int);
mysql> merge into s using t on 1 != 1 when matched and s.a>0 then update * when not matched then insert *;
+-------------------------+------------------------+
| number of rows inserted | number of rows updated |
+-------------------------+------------------------+
|                       0 |                      0 |
+-------------------------+------------------------+
1 row in set (0.15 sec)
Read 0 …
```

fix: merge into panic

---

src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs

list_dictionaries should not ignore db_id
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16587)

fix(query): list_dictionaries should not ignore db_id

---

tests/sqllogictests/suites/mode/standalone/explain/clustering.test

https://github.com/databendlabs/databend/actions/runs/11284527924/job/31386412732#step:4:344
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16596)

chore(ci): flaky test

---

src/query/storages/iceberg/src/table.rs
src/query/storages/iceberg/src/table_source.rs

Make sure iceberg able to load via REST catalog.
This PR fixes an issue that prevents iceberg table been constructed correctly. After this PR, iceberg table is able to read successfully:
I will add full tpch test upon iceberg later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16593)

fix(iceberg): Make sure iceberg table has been loaded

---

src/query/storages/common/table_meta/src/meta/mod.rs
src/query/storages/common/table_meta/src/meta/utils.rs
src/query/storages/fuse/src/io/locations.rs
src/query/storages/fuse/src/io/read/block/parquet/arrow_parquet.rs
src/query/storages/fuse/src/io/read/block/parquet/deserialize.rs
src/query/storages/fuse/src/io/read/block/parquet/mod.rs
src/query/storages/fuse/src/io/read/virtual_column/virtual_column_reader_parquet.rs

add compatibility for reading non-standard decimal256 format.
to be detailed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16585)

fix: add compatibility for reading non-standard decimal256 format

---

src/query/expression/src/converts/arrow/from.rs
src/query/storages/iceberg/src/table.rs

- fixes https://github.com/databendlabs/databend/issues/16594
Iceberg Engine doesn't support `prewhere` yet. Enabling prewhere in wrong will lead to read our schema has less fields than expected.
After this fix, we can run tpch now:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16597)

fix: Disable `prewhere` for iceberg table for now

---

Cargo.lock
src/common/parquet2/src/encoding/delta_length_byte_array/encoder.rs
src/query/ast/src/ast/expr.rs
src/query/ast/src/ast/format/syntax/expr.rs
src/query/ast/src/parser/expr.rs
src/query/ast/src/parser/token.rs
src/query/ast/tests/it/testdata/expr-error.txt
src/query/ast/tests/it/testdata/stmt-error.txt
src/query/expression/src/types/timestamp.rs
src/query/expression/src/utils/date_helper.rs
src/query/functions/src/scalars/datetime.rs
src/query/functions/tests/it/scalars/datetime.rs
src/query/functions/tests/it/scalars/parser.rs
src/query/functions/tests/it/scalars/testdata/datetime.txt
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test

related to #16534
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16560)

feat(query): add date_diff function

---

src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/left_join.rs
tests/sqllogictests/suites/query/join/left_outer.test

Introduced in https://github.com/databendlabs/databend/pull/16359.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16601)

fix(query): fix left outer join wrong result

---

src/query/sql/src/planner/binder/bind_mutation/mutation_expression.rs
src/query/sql/src/planner/binder/bind_table_reference/bind_join.rs
src/query/sql/src/planner/optimizer/decorrelate/decorrelate.rs
src/query/sql/src/planner/optimizer/decorrelate/flatten_plan.rs
src/query/sql/src/planner/optimizer/decorrelate/subquery_rewriter.rs
src/query/sql/src/planner/optimizer/optimizer.rs
tests/sqllogictests/suites/query/subquery.test

- fixes: https://github.com/databendlabs/databend/issues/16563
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16606)

fix: subquery returns wrong results under cluster

---

Cargo.lock
Makefile
src/common/base/src/base/dma.rs
src/common/base/src/base/mod.rs
src/query/expression/src/utils/arrow.rs
src/query/service/Cargo.toml
src/query/service/src/lib.rs
src/query/service/src/pipelines/builders/builder_window.rs
src/query/service/src/pipelines/processors/transforms/window/partition/transform_window_partition_collect.rs
src/query/service/src/spillers/mod.rs
src/query/service/src/spillers/spiller.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
src/query/storages/common/cache/src/lib.rs
src/query/storages/common/cache/src/temp_dir.rs
tests/sqllogictests/suites/query/window_function/window_partition_spill.test

Changes:
1. Instead of serializing blocks first and then copying them to the dio buffer, the serialization of blocks is written directly to the aligned dio buffer.
2. Instead of freeing memory after the entire file is written, the buffer is freed incrementally as the file is written.
3. The spill file is compressed with LZ4 to dramatically reduce io.
4. Introduced settings `enable_dio` to disable direct io, i.e. use buffer io to read and write files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16580)

feat(query): Reduce serialisation memory usage when spilling to local disk

---

src/query/ast/src/ast/query.rs
src/query/ast/src/parser/query.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/stmt.txt
src/query/catalog/src/plan/pushdown.rs
src/query/sql/src/executor/physical_plans/physical_table_scan.rs
src/query/sql/src/planner/binder/bind_table_reference/bind_table.rs
src/query/sql/src/planner/binder/bind_table_reference/bind_table_function.rs
src/query/sql/src/planner/binder/table.rs
src/query/sql/src/planner/optimizer/dynamic_sample/filter_selectivity_sample.rs
src/query/sql/src/planner/optimizer/statistics/collect_statistics.rs
src/query/sql/src/planner/plans/scan.rs
src/query/storages/fuse/src/pruning/fuse_pruner.rs
tests/sqllogictests/suites/mode/standalone/explain/table_sample.test

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16613)

feat: support sampling table with block and row level simultaneously

---

src/query/settings/src/settings_default.rs
src/query/storages/fuse/src/operations/mutation/mutator/recluster_mutator.rs

reset recluster block size, to avoid oom.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16623)

chore: reset recluster block size

---

scripts/ci/deploy/config/databend-query-node-1.toml
src/common/base/src/base/watch_notify.rs
src/query/service/src/locks/lock_holder.rs

Replaces `tokio::sync::Notify` with `WatchNotify` which is safe to `nofity_one` before `Notified` future has been  polled, otherwise, we risk not being able to release the lock in time. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16611)

fix: lock mgr may failed to release lock in time

---

Cargo.lock
src/query/ee/tests/it/inverted_index/index_refresh.rs
src/query/ee/tests/it/inverted_index/pruning.rs
src/query/storages/common/index/src/inverted_index.rs
src/query/storages/common/index/src/lib.rs
src/query/storages/fuse/Cargo.toml
src/query/storages/fuse/src/io/read/inverted_index/inverted_index_reader.rs
src/query/storages/fuse/src/io/write/inverted_index_writer.rs
src/query/storages/fuse/src/pruning/inverted_index_pruner.rs
tests/sqllogictests/suites/ee/04_ee_inverted_index/04_0000_inverted_index_base.test

- Inverted index support calculate the score
- Restore the inverted index test that was commented out
continue #16589
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16609)

refactor(storage): inverted index support calculate the score

---

src/query/expression/src/types/date.rs
src/query/expression/src/types/timestamp.rs
src/query/expression/src/utils/date_helper.rs
src/query/expression/src/values.rs
src/query/formats/src/field_decoder/fast_values.rs
src/query/formats/src/field_decoder/json_ast.rs
src/query/formats/src/field_decoder/nested.rs
src/query/formats/src/field_decoder/separated_text.rs
src/query/functions/src/scalars/datetime.rs
src/query/functions/tests/it/scalars/testdata/cast.txt
src/query/functions/tests/it/scalars/testdata/datetime.txt
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test

If Date/Timestamp is invalide, convert it to Date/TimestampMIN
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16634)

fix(query): check_timestamp/date -> clamp_timestamp/date

---

src/query/service/src/interpreters/hook/vacuum_hook.rs

chore(query): add warn log if vacuum temporary file is error
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16646)

chore(query): add warn log if vacuum temporary file is error

---

src/query/sql/src/planner/optimizer/dynamic_sample/dynamic_sample.rs
src/query/sql/src/planner/plans/aggregate.rs
src/query/sql/src/planner/plans/limit.rs
src/query/sql/src/planner/plans/project_set.rs
src/query/sql/src/planner/plans/union_all.rs
tests/sqllogictests/suites/tpch/sample.test

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16629)

chore: resolve todo in dynamic sample

---

Cargo.lock
src/query/expression/Cargo.toml
src/query/expression/src/utils/arrow.rs
src/query/expression/tests/it/serde.rs
src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_aggregate_spill_writer.rs
src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_spill_reader.rs

This may be able to fix #16651
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16655)

chore(query): replace `arrow2` with `arrow-rs` in `serialize_column` and `deserialize_column`

---

src/query/pipeline/transforms/src/processors/transforms/sort/spill.rs
src/query/pipeline/transforms/src/processors/transforms/transform_sort_merge_base.rs
src/query/service/src/pipelines/builders/builder_sort.rs
src/query/service/src/pipelines/processors/transforms/transform_sort_spill.rs
src/query/service/src/spillers/serialize.rs
tests/sqllogictests/suites/query/order.test

fixes: #16660
`SortSpillMetaWithParams` is not allowed to be cloned, but `DataBlock::concat` will clone it, so we need take out the meta from block before spilling.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16658)

fix(query):  sort spilling use arrow file format painc

---

src/query/service/src/interpreters/interpreter_table_create.rs
tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables.test

create table need fail if storage format is invalid
`CREATE TABLE members (name VARCHAR, age INT) STORAGE_FORMAT = 'abc'` need err.
Fix: #16662 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16663)

fix(query): create table need fail if storage format is invalid

---

src/query/sql/src/planner/binder/binder.rs
src/query/sql/src/planner/binder/explain.rs
tests/sqllogictests/suites/mode/standalone/explain/explain.test

forbiden explain explain statement
explain explain select ... should be error
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16654)

fix(query): forbid explain explain statement

---

src/query/sql/src/planner/planner.rs
tests/sqllogictests/suites/base/03_common/03_0045_insert_values_with_comment.test

We should use `try` to catch block error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16678)

fix(query): insert with long sql parse error

---

src/query/ast/src/ast/statements/explain.rs
src/query/ast/src/ast/statements/statement.rs
src/query/ast/src/parser/statement.rs
src/query/ast/src/parser/token.rs
src/query/service/src/interpreters/interpreter_explain.rs
src/query/sql/src/planner/optimizer/optimizer.rs
tests/sqllogictests/suites/mode/standalone/explain/subquery.test

Decorrelating subquery makes huge changes to the query plan, `explain decorrelated plan` outputs the query plan after decorrelating subquery which is helpful for debugging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16681)

feat: support explain decorrelated plan

---

src/query/settings/src/settings_default.rs

Using a small-sized warehouse (16c) for testing, 3,000 segments were randomly generated. Pruning was performed using different values for max_storage_io_requests. The results show that when max_storage_io_requests=64, the performance is close to optimal.
```sql
deploy@(bench-vacuum2-1)/default> set max_storage_io_requests = 16;
SET max_storage_io_requests = 16
0 row read in 0.027 sec. Processed 0 row, 0 B (0 row/s, 0 B/s)
deploy@(bench-vacuum2-1)/default> explain select * from test_order where id > 1;
EXPLAIN SELECT * FROM test_order WHERE id > 1
Filter
├── output columns: [test_order.id (#0), test_order.id1 (#1), test_order.id2 (#2), …
```

chore: adjust default value of setting `max_storage_io_requests`

---

Cargo.lock
Cargo.toml
src/query/expression/src/evaluator.rs
src/query/functions/src/scalars/variant.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/functions/tests/it/scalars/testdata/variant.txt
src/query/functions/tests/it/scalars/variant.rs
tests/sqllogictests/suites/query/functions/02_0002_function_cast.test
tests/sqllogictests/suites/query/functions/02_0065_function_json.test

- support `json_object_delete` function
- support `json_object_pick` function
- allow cast variant to map<string, variant>
for example
```sql
MySQL [(none)]> SELECT json_object_delete('{"a":1,"b":2,"d":4}'::variant, 'a', 'c');
+--------------------------------------------------------------+
| json_object_delete('{"a":1,"b":2,"d":4}'::VARIANT, 'a', 'c') |
+--------------------------------------------------------------+
| {"b":2,"d":4}                                                |
+--------------------------------------------------------------+
1 row in set (0.167 sec)
MySQL [(none)]> SELECT json_object_pick('{"a":1,"b":2,"d":4}'::variant, 'a', 'c'); …
```

feat(query): support `json_object_delete` and `json_object_pick` function

---

src/query/service/src/servers/flight/flight_service.rs
src/query/service/src/servers/flight_sql/flight_sql_server.rs

display port number on error from bind to port failure
- fixes: [#[16673]](https://github.com/databendlabs/databend/issues/16673)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16695)

chore: display port number on error from bind to port failure

---

src/common/base/src/mem_allocator/jemalloc.rs

In `JEAllocator::grow_zeroed/shrink`,   when je  `rallocx` returns NULL,  stop proceeding, returns `AllocError` error directly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16692)

fix: `JEAllocator` should properly handle nullptr returned

---

src/query/expression/src/kernels/sort.rs
src/query/expression/tests/it/sort.rs
src/query/functions/src/scalars/array.rs
src/query/pipeline/transforms/src/processors/transforms/sort/rows/simple.rs
src/query/pipeline/transforms/tests/it/merger.rs
src/query/service/src/pipelines/builders/builder_aggregate.rs
src/query/service/src/pipelines/builders/builder_insert_multi_table.rs
src/query/service/src/pipelines/builders/builder_recluster.rs
src/query/service/src/pipelines/builders/builder_sort.rs
src/query/service/src/pipelines/builders/builder_window.rs
src/query/service/src/pipelines/processors/mod.rs
src/query/service/src/pipelines/processors/transforms/range_join/ie_join_state.rs
src/query/service/src/pipelines/processors/transforms/range_join/merge_join_state.rs
src/query/service/src/pipelines/processors/transforms/transform_sort_spill.rs
src/query/service/src/pipelines/processors/transforms/window/mod.rs
src/query/service/src/pipelines/processors/transforms/window/transform_window.rs
src/query/service/tests/it/pipelines/transforms/sort/k_way.rs
src/query/service/tests/it/pipelines/transforms/sort/spill.rs
src/query/storages/fuse/src/operations/append.rs

The vast majority of places don't need `SortColumnDescription.is_nullable`, resulting in the field often being unreliable, and unreliability is a breeding ground for bugs, so remove this field.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16699)

chore: remove `SortColumnDescription.is_nullable`

---

src/meta/app/src/storage/storage_params.rs

Ensures that the ·detect_region· operation will time out if it cannot be fulfilled within 10 seconds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16709)

chore: add timeout for `detect_region` operation to prevent hanging request

---

src/query/catalog/src/database.rs
src/query/service/src/table_functions/table_function_factory.rs
src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/table_functions/fuse_time_travel_size.rs
src/query/storages/fuse/src/table_functions/mod.rs
src/query/storages/fuse/src/table_functions/table_args.rs
tests/sqllogictests/suites/base/06_show/06_0014_show_table_functions.test
tests/suites/0_stateless/20+_others/20_0020_fuse_time_travel_size.result
tests/suites/0_stateless/20+_others/20_0020_fuse_time_travel_size.sh

Calculate the table's total storage space to guide users or the cloud in prioritizing vacuum for larger tables.
```
root@localhost:8000/db2> select database_name, table_name, humanize_size(time_travel_size) from fuse_time_travel_size();
SELECT
database_name, table_name, humanize_size(time_travel_size)
FROM
fuse_time_travel_size()
┌──────────────────────────────────────────────────────────────┐
│ database_name │ table_name │ humanize_size(time_travel_size) │
│     String    │   String   │              String             │
├───────────────┼────────────┼─────────────────────────────────┤
│ db1           │ t1         │ 1.91 KiB                        │
│ db2           │ t2         │ 1.91 KiB …
```

feat: support calculating table storage size(including time travel)

---

src/common/tracing/src/config.rs

This pr is not resolve the issue #16702, just display limit in FileConfig. Facilitate problem locating
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16713)

chore: display log.file.limit and prefix_filter

---

src/query/sql/src/planner/optimizer/property/selectivity.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16725)

chore: avoid returning error during computing binary comparison selectivity

---

src/query/catalog/src/plan/agg_index.rs
src/query/expression/src/block.rs
src/query/pipeline/core/tests/it/pipelines/processors/port_test.rs
src/query/pipeline/transforms/src/processors/transforms/sort/k_way_merge_sort_partition.rs
src/query/pipeline/transforms/src/processors/transforms/sort/spill.rs
src/query/pipeline/transforms/src/processors/transforms/transform_compact_block.rs
src/query/pipeline/transforms/src/processors/transforms/transform_k_way_merge_sort.rs
src/query/service/src/pipelines/processors/transforms/aggregator/aggregate_meta.rs
src/query/service/src/pipelines/processors/transforms/aggregator/serde/transform_exchange_group_by_serializer.rs
src/query/service/src/pipelines/processors/transforms/window/partition/window_partition_meta.rs
src/query/service/src/servers/flight/v1/exchange/exchange_transform_shuffle.rs
src/query/service/src/servers/flight/v1/exchange/serde/exchange_deserializer.rs
src/query/service/src/servers/flight/v1/exchange/serde/exchange_serializer.rs
src/query/storages/fuse/src/operations/mutation/meta/mutation_meta.rs
src/query/storages/fuse/src/operations/read/native_data_source.rs
src/query/storages/fuse/src/operations/read/parquet_data_source.rs
src/query/storages/orc/Cargo.toml
src/query/storages/orc/src/strip.rs
src/query/storages/stage/src/append/parquet_file/block_batch.rs
src/query/storages/stage/src/append/row_based_file/buffers.rs
src/query/storages/stage/src/read/row_based/batch.rs

The node local BlockMetaInfo definition has too much repetitive code, and the lack of explanatory information can be misleading.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16716)

chore: Simplifying BlockMetaInfo Definitions

---

Cargo.lock
src/common/base/src/runtime/mod.rs
src/common/base/src/runtime/runtime.rs
src/meta/client/Cargo.toml
src/meta/client/src/established_client.rs
src/meta/client/src/grpc_client.rs
src/query/service/src/servers/http/clickhouse_handler.rs
src/query/service/src/servers/http/v1/query/http_query.rs
src/query/service/src/servers/mysql/mysql_interactive_worker.rs
src/query/service/src/sessions/query_ctx.rs
src/query/storages/fuse/src/io/read/bloom/block_filter_reader.rs
src/query/storages/fuse/src/io/read/inverted_index/inverted_index_loader.rs

Move the reference to the dedicated runtime `rt` from `MetaGrpcClient`
to `ClientHandle`.
`rt` is a reference to the dedicated runtime for running
`MetaGrpcClient`.
If all ClientHandle are dropped, the runtime will be destroyed.
This `rt` previously is stored in `MetaGrpcClient`, which leads to a deadlock:
- When all `ClientHandle` are dropped, the two workers `worker_loop()` and `auto_sync_interval()`
will quit.
- These two futures both held a reference to `MetaGrpcClient`.
- The last of these(say, `F`) two will drop `MetaGrpcClient.rt` and `Runtime::_dropper`
will block waiting for the runtime to shut down.
- But `F` is still held, deadlock occurs.
Other changes:
- `Runtime::try_spawn` and …

fix: MetaGrpcClient deadlock when drop

---

Cargo.lock
src/query/storages/common/index/src/index.rs
src/query/storages/common/index/src/range_index.rs
src/query/storages/common/table_meta/Cargo.toml
src/query/storages/common/table_meta/src/meta/statistics.rs
src/query/storages/common/table_meta/src/meta/v2/statistics.rs

This PR modifies the serialization process for the ColumnStatistics map to exclude columns of unsupported types.
When merging snapshots or block metadata, column statistics may include legacy types that are no longer supported. If these columns are not excluded, serialization will fail.
The changes introduced in [#16719](https://github.com/databendlabs/databend/pull/16719) allow legacy type scalars to be de-serialized. If these legacy columns are present in the column statistics during serialization, they will be excluded to prevent runtime errors.
- - - …

refactor: refine column statistic map serialization

---

src/query/sql/src/planner/optimizer/dynamic_sample/filter_selectivity_sample.rs
src/query/sql/src/planner/optimizer/property/selectivity.rs
src/query/sql/src/planner/plans/filter.rs
src/query/sql/src/planner/plans/scan.rs
tests/sqllogictests/suites/mode/standalone/explain/eliminate_outer_join.test
tests/sqllogictests/suites/mode/standalone/explain/nullable_prune.test
tests/sqllogictests/suites/mode/standalone/explain/selectivity/is_not_null.test
tests/sqllogictests/suites/mode/standalone/explain_native/nullable_prune.test

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16730)

feat: implement `is_not_null` selectivity based on null count in stats

---

src/meta/service/src/api/grpc_server.rs
src/meta/service/src/meta_service/meta_node.rs
src/meta/service/tests/it/grpc/metasrv_grpc_kv_api_restart_cluster.rs

Before c44ea20bd9a224310ceda536710525a7de086d49, MetaGrpcClient just
auto reconnect if the target meta-service server is restarted.
After c44ea20bd9a224310ceda536710525a7de086d49, the client behavior
changed, if no timeout is set, the client reconnect to the restarted
server but it hangs forever.
In this commit, in the test: test_kv_api_restart_cluster_token_expired,
give the client a fixed timeout to survive a server restart.
- Fix: https://github.com/databendlabs/databend/pull/16704#issuecomment-2443463631
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16733)

refactor: MetaGrpcClient needs to specify timeout to auto-reconnect to restarted server

---

Cargo.lock
Cargo.toml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16700)

refactor: replace direct GitHub dependencies with published crates.io versions

---

src/query/expression/src/utils/date_helper.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test
tests/sqllogictests/suites/query/functions/02_0075_function_datetimes_tz.test

Before fix:
```sql
:) select version();
SELECT version()
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                            version()                                           │
│                                             String                                             │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Databend Query v1.2.574-nightly-bd380eeeea(rust-1.81.0-nightly-2024-10-29T08:01:25.246023988Z) │
└────────────────────────────────────────────────────────────────────────────────────────────────┘
1 row read in 0.074 sec. Processed 1 row, 1B (13.45 …
```

fix: date_add/sub need respect timezone

---

src/binaries/Cargo.toml
src/common/base/Cargo.toml
src/common/base/src/mem_allocator/mmap.rs
src/common/base/src/mem_allocator/mod.rs
src/meta/service/Cargo.toml
src/query/service/Cargo.toml
src/query/service/src/databases/system/system_database.rs
src/query/storages/system/Cargo.toml
src/query/storages/system/src/lib.rs

Tweaks cargo features  so that when the "jemalloc" feature is not enabled, binaries will no longer contain jemalloc symbols. 
This helps us avoid issues caused by jemalloc when using sanitizers or Valgrind.
- `jemalloc` is enabled by default. 
- to disable it:  `cargo b --no-default-features -F simd`.
in this case, `mem_allocator::StdAllocator` will be used as the  "fallback allocator" of `MmapAllocator`
during query node starting up,  memory allocator name will no longer be jemalloc:
~~~
...
Memory:
limit: unlimited
allocator: std
config: 
...
~~~
- - - …

chore: tweak cargo feature "jemalloc"

---

src/query/ee/src/storages/fuse/operations/vacuum_table.rs
src/query/storages/fuse/src/io/locations.rs
tests/suites/5_ee/01_vacuum/01_003_vacuum_table_only_orphans.result
tests/suites/5_ee/01_vacuum/01_003_vacuum_table_only_orphans.sh

If only orphans left, the vacuum should continue working as expected (purge all the orphans).
Instead of using prefix extracted from the "path" of object belong to the GC root, using block/bloom_filter_index/segment prefix directly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16743)

chore: refine vacuum

---

.cargo/audit.toml
.github/workflows/dev.yml
src/query/ee/src/storages/fuse/operations/vacuum_table.rs
src/query/ee/tests/it/aggregating_index/index_refresh.rs
src/query/storages/fuse/src/io/locations.rs
tests/suites/0_stateless/18_rbac/18_0011_alter_own_username.result
tests/suites/0_stateless/18_rbac/18_0011_alter_own_username.sh
tests/suites/5_ee/01_vacuum/01_003_vacuum_table_only_orphans.result
tests/suites/5_ee/01_vacuum/01_003_vacuum_table_only_orphans.sh

backport PR  https://github.com/databendlabs/databend/pull/16743 to release/v1.2.636-rc3.
If only orphans left, the vacuum should continue working as expected (purge all the orphans).
Instead of using prefix extracted from the "path" of object belong to the GC root, using block/bloom_filter_index/segment prefix directly.
Different from PR #16743 (which is being merged into main branch):
1. the block name is (kept as) prefixed with 'g' in this PR, as PR https://github.com/databendlabs/databend/pull/16585 has not been merged into main yet (or will not be).
https://github.com/databendlabs/databend/pull/16744/files#diff-9d4aa60a0f7398a38f14b3c0ba1009a992cd2cd5b65f1e00642f5f1ba5d430d8R109
related …

chore: refine vacuum (backport PR #16743 to release/v1.2.636-rc3)

---

src/query/service/src/servers/http/v1/query/page_manager.rs
src/query/service/tests/it/servers/http/http_query_handlers.rs

may lost a row starting from the 3rd page, when
1. total size > 20MB.
2. avg row size > 1050B.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16748)

fix: HTTP handle lost rows when result set is wide and large.

---

src/common/arrow/src/arrow/compute/merge_sort/mod.rs
src/common/arrow/src/arrow/compute/sort/lex_sort.rs
src/common/io/src/cursor_ext/cursor_read_bytes_ext.rs
src/query/script/src/ir.rs
src/query/storages/common/table_meta/src/meta/v2/statistics.rs
tests/sqllogictests/suites/no_table_meta_cache/col_stats_of_all_null.test

In [PR #16728](https://github.com/databendlabs/databend/pull/16728), statistics for columns with unsupported data types are excluded. 
However,  the data type is inferred from the the scalar, instead of the the type of column, thus, an edge case may arise for columns that contain only NULL values:
For such columns, both the min and max scalar values are NULL, causing them to be incorrectly classified as "supported_stat_type" and subsequently excluded. This leads to issues during pruning because `RangePruner` cannot prune these columns without available statistics.
Although the table data is safe, and the correctness of filtering also retained,  the execution of pruning may be inefficient: …

fix: keep column statistics of all NULL column

---

src/common/arrow/src/arrow/compute/merge_sort/mod.rs
src/common/arrow/src/arrow/compute/sort/lex_sort.rs
src/common/io/src/cursor_ext/cursor_read_bytes_ext.rs
src/query/script/src/ir.rs
src/query/storages/common/table_meta/src/meta/v2/statistics.rs
tests/sqllogictests/suites/no_table_meta_cache/col_stats_of_all_null.test

**backport** https://github.com/databendlabs/databend/pull/16753 to release/v1.2.636-rc3
------------------
In [PR #16728](https://github.com/databendlabs/databend/pull/16728), statistics for columns with unsupported data types are excluded. 
However,  the data type is inferred from the the scalar, instead of the the type of column, thus, an edge case may arise for columns that contain only NULL values:
For such columns, both the min and max scalar values are NULL, causing them to be incorrectly classified as "supported_stat_type" and subsequently excluded. This leads to issues during pruning because `RangePruner` cannot prune these columns without available statistics.
Although the table data …

fix: (backport to 636-rc3) keep column statistics of all NULL column (#16753)

---

src/query/ee/tests/it/storages/fuse/operations/vacuum.rs
src/query/storages/common/io/src/files.rs

`Files::remove_file_in_batch` should not swallow errors
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16761)

fix: `Files::remove_file_in_batch` should not swallow errors

---

Cargo.lock
src/query/ee/Cargo.toml
src/query/ee/tests/it/storages/fuse/operations/vacuum.rs
src/query/storages/common/io/src/files.rs

backport PR #16761 to `release/v1.2.636 rc3`
Fixes:
`Files::remove_file_in_batch` should not swallow errors
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16762)

chore: backport PR #16761 `release/v1.2.636 rc3`

---

src/query/storages/common/io/src/files.rs

The default concurrency for batch file deletion during orphan data cleanup was set too high. To mitigate the 503 errors, the default concurrency limit has been adjusted to a maximum of 3. (follow the practice of https://github.com/databendlabs/databend/pull/16312)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16770)

chore: tweak batch deletion concurrency

---

src/query/storages/common/io/src/files.rs

backport PR #16770  to `release/v1.2.636-rc3`
* chore: tweak batch deletion concurrency
* chore: tweak remove file in batch thread pool size
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16772)

chore: (backport to 636-rc3) tweak batch deletion concurrency (#16770)

---

src/query/expression/src/utils/udf_client.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16782)

fix(query): add tls config for udf client

---

Cargo.lock
Cargo.toml

using [patched opendal](https://github.com/datafuse-extras/opendal-for-release-v1.2.636/commit/6c490a00e1a128edbbc15017cef47d010c3a47c0).
which categories the XML dersierialization errors as recoverable and is based on opendal v0.49.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16784)

chore: using patched opendal based on v0.49.0

---

Cargo.lock
Cargo.toml
src/query/service/src/auth.rs
src/query/service/src/servers/http/middleware/session.rs
src/query/service/src/servers/http/v1/session/client_session_manager.rs
src/query/service/src/servers/http/v1/session/login_handler.rs
src/query/service/src/servers/http/v1/session/logout_handler.rs
src/query/service/src/servers/http/v1/session/refresh_handler.rs
src/query/service/src/servers/http/v1/session/token.rs
tests/sqllogictests/Cargo.toml
tests/sqllogictests/src/client/gloable_cookie_store.rs
tests/sqllogictests/src/client/global_cookie_store.rs
tests/sqllogictests/src/client/http_client.rs
tests/sqllogictests/src/client/mod.rs
tests/sqllogictests/suites/temp_table/alter_temp_tables.sql
tests/suites/1_stateful/09_http_handler/09_0007_token.py
tests/suites/1_stateful/09_http_handler/09_0007_token.result

related feature not in use yet, so the pr is safe.
find something need improvement when working with the clients.
1.  session token use the session id generated when processing cookie and stored in context
2.  small refactor of request login and refresh  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16786)

fix: token and cookie session id miss match.

---

src/query/storages/fuse/src/fuse_table.rs

To avoid redundant extraction of snapshot location from hint file, a snapshot location cache is added at the table instance level for tables that are attached to another table.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16795)

chore: add snapshot location cache for attached table

---

src/meta/raft-store/src/ondisk/upgrade_to_v004.rs

Because upgrade-cleaning would remove the entire dir.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16805)

fix: re-ensure dir before upgrading

---

src/meta/raft-store/src/ondisk/upgrade_to_v004.rs

Otherwise non-consecutive log indexes, such as `[5..100], [200..]` will
panic the upgrading sub-routine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16809)

refactor: when upgrading, do not import already purged garbage log entries

---

src/query/service/tests/it/storages/fuse/operations/navigate.rs
src/query/storages/fuse/src/operations/navigate.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0008_fuse_optimize_table.test
tests/suites/0_stateless/20+_others/20_0011_purge_before.result
tests/suites/0_stateless/20+_others/20_0011_purge_before.sh

On tables that have undergone a FLASHBACK operation, this assumption is broken:
```
// Take the prev snapshot as base snapshot to avoid get orphan snapshot.
```
In this PR, the garbage collection (GC) root is determined by starting from the current snapshot and traversing backward to the target time point using the `prev` relation between snapshots. This approach enhances safety (allowing tables modified by the `ALTER ... FLASHBACK` operation to be handled correctly) but may require traversing a (much) longer history of the table being purged.
- - - …

fix: purge may not work on tables after a flash back operation

---

src/query/service/tests/it/storages/fuse/operations/navigate.rs
src/query/storages/fuse/src/operations/navigate.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0008_fuse_optimize_table.test
tests/suites/0_stateless/20+_others/20_0011_purge_before.result
tests/suites/0_stateless/20+_others/20_0011_purge_before.sh

Backport PR #16812
On tables that have undergone a FLASHBACK operation, this assumption is broken:
```
// Take the prev snapshot as base snapshot to avoid get orphan snapshot.
```
In this PR, the garbage collection (GC) root is determined by starting from the current snapshot and traversing backward to the target time point using the `prev` relation between snapshots. This approach enhances safety (allowing tables modified by the `ALTER ... FLASHBACK` operation to be handled correctly) but may require traversing a (much) longer history of the table being purged.
- - - …

fix: (backport) purge may not work on tables after a flash back operation (#16812)

---

src/query/service/src/interpreters/interpreter_vacuum_drop_tables.rs
tests/sqllogictests/suites/ee/03_ee_vacuum/03_0002_vacuum_views.test

Purge dropped view's metadata during `vacuum` operation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16819)

chore: purge dropped view metadata during vacuum

---

Cargo.toml
src/query/functions/src/scalars/other.rs

Change UUID functions([GEN_RANDOM_UUID](https://docs.databend.com/sql/sql-functions/uuid-functions/gen-random-uuid)/[UUID](https://docs.databend.com/sql/sql-functions/uuid-functions/uuid))output format from v4 to v7 for improved performance and ordering
* **Time-ordered**: v7 includes timestamp, making IDs chronologically sortable
* **Uniqueness**: Same uniqueness guarantees as v4 with added time component
* **Sequential**: Improves database insert performance vs random v4 values
Before (v4): `9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d` (random)
After (v7):  `018df296-2bcd-7000-9876-000000000000` (time-ordered)
* No changes needed for existing v4 UUID usage
* New IDs will be sortable by creation …

feat: uuid function from v4 to v7

---

src/query/catalog/src/table_context.rs
src/query/service/src/pipelines/builders/builder_column_mutation.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/tests/it/sql/exec/get_table_bind_test.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs

remove unused codes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16834)

chore: remove unused codes

---

src/query/storages/fuse/src/io/read/block/block_reader_merge_io_async.rs

`Range` returned by merged reading should not be used as the corresponding parts of table data cache key,
instead `offset` and `len` of column meta should be used.
`range.start`  is not stable and can vary for the same column depending on the query's projection.
For instance:
- `SELECT col1, col2 FROM t;`
- `SELECT col2 FROM t;`
may result in different ranges for `col2`, this can lead to cache missing or INCONSISTENCIES
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16837)

fix: incorrect table data disk cache key

---

src/query/service/src/pipelines/processors/transforms/group_by/aggregator_groups_builder.rs
tests/sqllogictests/suites/base/03_common/03_0003_select_group_by.test
tests/sqllogictests/suites/base/03_common/03_0003_select_group_by_old.test

fix(query): fix aggregator_groups_builder to work with string view when working with
```
set enable_experimental_aggregate_hashtable = 0;
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16843)

fix(query): fix aggregator_groups_builder to work with string view

---

Cargo.lock
src/common/base/Cargo.toml
src/common/base/src/base/dma.rs
src/common/base/src/base/mod.rs
src/common/base/src/lib.rs
src/query/service/src/spillers/spiller.rs

Fix incorrect cap,
Modify the implementation to match the [Allocator api](https://doc.rust-lang.org/std/alloc/trait.Allocator.html#memory-fitting)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16829)

fix: replace risky `dma_buffer_as_vec` implementations

---

Cargo.lock
Cargo.toml
src/meta/app/src/schema/catalog.rs
src/meta/proto-conv/src/catalog_from_to_protobuf_impl.rs
src/meta/proto-conv/src/util.rs
src/meta/proto-conv/tests/it/v111_add_glue_as_iceberg_catalog_option.rs
src/meta/protos/proto/catalog.proto
src/query/service/Cargo.toml
src/query/service/src/interpreters/interpreter_catalog_show_create.rs
src/query/sql/Cargo.toml
src/query/sql/src/planner/binder/ddl/catalog.rs
src/query/storages/common/cache/Cargo.toml
src/query/storages/iceberg/Cargo.toml
src/query/storages/iceberg/src/catalog.rs
tests/sqllogictests/suites/glue/queries.test

- This pull request enables AWS Glue to be used as a connection type when creating an Apache Iceberg catalog.
- Started work on this because I noticed there was support for REST & Hive, but not AWS Glue.
- fixes: #[https://github.com/databendlabs/databend/issues/16793]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16824)

feat: add aws glue as an iceberg connection type

---

Cargo.lock
src/meta/raft-store/src/state_machine_api_ext.rs
src/meta/service/Cargo.toml
src/meta/service/src/meta_service/meta_leader.rs

Return Stream to client instead of collecting results into Vec first.
This change eliminates unnecessary buffering of ListKV results in
databend-meta server, reducing memory usage and improving response
times. The direct streaming approach better matches current usage
patterns and removes legacy collection behavior.
Although a large ListKV response body won't block the databend-meta
server, but it will still block on the client side.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16868)

refactor: make ListKV non-blocking by returning stream directly

---

src/binaries/tool/table_meta_inspector.rs

enable stderr logging for `table_meta_inspector`, otherwise errors like deserialization failures will not be shown.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16865)

chore: enable stderr logging for `table_meta_inspector`

---

Cargo.lock
src/meta/app/src/principal/mod.rs
src/meta/app/src/principal/user_grant.rs
src/query/catalog/src/table_context.rs
src/query/service/src/interpreters/access/privilege_access.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sessions/session.rs
src/query/service/src/sessions/session_privilege_mgr.rs
src/query/service/src/table_functions/infer_schema/parquet.rs
src/query/service/src/table_functions/inspect_parquet/inspect_parquet_table.rs
src/query/service/src/table_functions/list_stage/list_stage_table.rs
src/query/service/src/table_functions/show_grants/show_grants_table.rs
src/query/service/tests/it/sql/exec/get_table_bind_test.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/storages/system/Cargo.toml
src/query/storages/system/src/columns_table.rs
src/query/storages/system/src/databases_table.rs
src/query/storages/system/src/indexes_table.rs
src/query/storages/system/src/stages_table.rs
src/query/storages/system/src/streams_table.rs
src/query/storages/system/src/tables_table.rs
src/query/storages/system/src/user_functions_table.rs

1. moved SYSTEM_TABLES_ALLOW_LIST to src/meta/app/src/principal/user_grant.rs. I also refactored the get_visibility_checker function and added a new parameter: ignore_ownership.
2. The purpose of this parameter is to optimize the performance of querying table information from system.tables. When this parameter is set, we can skip listing all ownerships and directly fetch a single ownership object, then perform only one get operation, thus reducing query time. In short, this change aims to improve the efficiency of querying table information from system.tables by avoiding unnecessary operations on the list of ownerships.
- - - …

refactor: optimize query system.tables when query single table

---

Cargo.lock
Cargo.toml

- Fixed in: https://github.com/drmingdrmer/raft-log/commit/2693db500efe3862d775ed986f46824a7c5660e9
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16876)

fix: raft-log wont write when exceeding 256M

---

.github/workflows/bindings.python.yml
.github/workflows/cloud.yml
.github/workflows/meta.yml
.github/workflows/release.yml
.github/workflows/reuse.benchmark.yml
.github/workflows/reuse.linux.hive.yml
.github/workflows/reuse.linux.yml
.github/workflows/reuse.sqllogic.yml
Cargo.lock
Cargo.toml
src/query/service/Cargo.toml
tests/sqllogictests/suites/query/set.test
tests/sqllogictests/suites/tpch_iceberg/prune.test

The issue described in [#16892](https://github.com/databendlabs/databend/issues/16892), is caused by a read-after-use bug in the `opersrv` crate (ver 0.7).
Valgrind identifies that, during the connection establishment between the MariaDB JDBC client and Databend's MySQL service, memory freed by `opensrv_mysql::packet_reader::PacketReader` is being accessed, leading to the failure of MySQL connection establishment (failed to process the input MySQL protocol command correctly).
Fortunately, this issue has been fixed by [@discord9](https://github.com/discord9) in [PR #67](https://github.com/databendlabs/opensrv/pull/67). As a result, in this PR, the `opensrv` version used has been updated to …

chore: bump opensrv

---

Cargo.lock
Cargo.toml
src/meta/raft-store/src/raft_log_v004/mod.rs
src/meta/service/src/meta_service/meta_node.rs
src/meta/service/src/metrics/meta_metrics.rs

- "raft_log_cache_items"                 : number of items in raft log cache;
- "raft_log_cache_used_size"             : size of used space in raft log cache;
- "raft_log_wal_open_chunk_size"         : size of open chunk in raft log wal;
- "raft_log_wal_offset"                  : global offset of raft log WAL;
- "raft_log_wal_closed_chunk_count"      : number of closed chunks in raft log WAL;
- "raft_log_wal_closed_chunk_total_size" : total size of closed chunks in raft log WAL;
Example output of these new metrics:
```text
metasrv_server_raft_log_cache_items                 35496
metasrv_server_raft_log_cache_used_size             659024620
metasrv_server_raft_log_wal_open_chunk_size …
```

feat: databend-meta adds more metrics about raft-log

---

Cargo.lock
src/meta/binaries/metactl/main.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/meta_service/meta_node.rs
src/meta/service/src/meta_service/meta_node_status.rs
src/meta/types/build.rs
src/meta/types/proto/meta.proto

These new metrics are added to gRPC API `GetClusterStatus` and
corresponding databend-metactl CLI command.
Newly added metrics are:
```
$ databend-metactl status
RaftLog:
- CacheItems: 287
- CacheUsedSize: 4959439
- WALTotalSize: 4378076
- WALOpenChunkSize: 4378058
- WALOffset: 4378076
- WALClosedChunkCount: 1
- WALClosedChunkTotalSize: 18
- WALClosedChunkSizes:
- ChunkId(00_000_000_000_000_000_000): 18
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16899)

refactor: add new raft-log metrics to "metactl status" response

---

src/query/service/src/interpreters/hook/compact_hook.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0041_auto_compaction.test

This PR fixes an issue where the write progress could become inconsistent when compaction was triggered after a write. Previously, compaction failures would cause an early return, skipping the reset of write progress and resulting in incorrect output. 
After the fix, the write progress will consistently reflect the result of the write operation, regardless of whether the compaction succeeds or fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16901)

fix(storge): write progress in compact hook

---

src/meta/binaries/meta/entry.rs
src/meta/binaries/metactl/export_from_disk.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/configs/outer_v0.rs
src/meta/service/src/lib.rs
src/meta/service/src/meta_service/forwarder.rs
src/meta/service/src/meta_service/meta_leader.rs
src/meta/service/src/meta_service/meta_node.rs
src/meta/service/src/meta_service/raft_service_impl.rs
src/meta/service/src/store/mod.rs
src/meta/service/src/store/store.rs
src/meta/service/src/store/store_inner.rs
src/meta/service/tests/it/configs.rs
src/meta/service/tests/it/meta_node/meta_node_kv_api_expire.rs
src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs
src/meta/service/tests/it/meta_node/meta_node_replication.rs
src/meta/service/tests/it/store.rs
src/meta/service/tests/it/tests/meta_node.rs

`config_id` is used for separate sled-db key spaces for parallel tests.
Since sled db is removed, this `config_id` is useless.
Try initialize instead of check `is_open` flag.
This flag may not be accurate: the raft storage is opend but no
initialization is done yet.
And remove trait `Opened` and refactor related struct names
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16902)

chore: remove unused config_id from RaftConfig

---

src/meta/api/src/schema_api_impl.rs

Guarantee atomic operations in `create_lock_revision` by combining the generation and insertion of revision into a single txn to prevent lock conflicts.
- Fixes #16906
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16907)

fix: ensure atomicity in create_lock_revision

---

Cargo.lock
src/query/storages/common/session/src/temp_table.rs
tests/sqllogictests/suites/temp_table/rename_temp_tables.sql
tests/sqllogictests/suites/temp_table/temporary_tables_table.sql

The table meta of temp table is not cleared totally when it is replaced due to `create or replace` statement, which causes it to be displayed in the system tables. Thanks @xudong963 for reporting this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16911)

fix: dropped temporary table should not be shown in system.temporary_tables

---

src/common/column/src/buffer/immutable.rs
src/common/column/tests/it/buffer/immutable.rs
src/query/expression/benches/bench.rs
src/query/service/src/pipelines/processors/transforms/hash_join/desc.rs
tests/sqllogictests/suites/query/join/join.test

1.  join predict use cast_expr_to_non_null_boolean
2. Improve `Buffer` index value
```
bench_kernels/function_buffer_index_unchecked_iterator/10240
time:   [4.5793 µs 4.6071 µs 4.6383 µs]
change: [-48.367% -47.735% -47.131%] (p = 0.00 < 0.05)
Performance has improved.
Found 11 outliers among 100 measurements (11.00%)
```
closes #16916 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16937)

fix(query): join predict use cast_expr_to_non_null_boolean

---

src/query/expression/src/utils/date_helper.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test

- fixes: #16928
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16929)

fix(query):  add_hours function may panic if the argument is too big

---

src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
src/query/sql/src/planner/binder/bind_table_reference/bind_table.rs
tests/sqllogictests/suites/mode/standalone/explain/explain_cte.test

Add `enable_materialized_cte` settings to set whether to enable materialized cte.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16950)

chore(binder): add enable_materialized_cte settings

---

src/meta/app/src/schema/table.rs
src/query/ee/src/fail_safe/handler.rs
src/query/ee/src/storages/fuse/operations/vacuum_table.rs
src/query/service/src/interpreters/common/stream.rs
src/query/service/src/test_kits/check.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/service/tests/it/storages/fuse/operations/gc.rs
src/query/service/tests/it/storages/fuse/operations/navigate.rs
src/query/storages/common/table_meta/src/table/table_keys.rs
src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/operations/changes.rs
src/query/storages/fuse/src/operations/gc.rs
src/query/storages/fuse/src/operations/navigate.rs
src/query/storages/fuse/src/operations/revert.rs
src/query/storages/fuse/src/table_functions/function_template/fuse_table_meta_func.rs
src/query/storages/fuse/src/table_functions/fuse_snapshot.rs
src/query/storages/fuse/src/table_functions/fuse_time_travel_size.rs
src/query/storages/stream/src/stream_table.rs

During instantiating attach table instance, "lock" table's snapshot location( which is extracted from the last_snapshot_hint file), by
- putting the snapshot location extracted from hint file into table_info's options as the value of opt key `OPT_KEY_SNAPSHOT_LOCATION`
- for those table instances that created "from" the above  table_info, they will use the same snapshot location
NOTE:
[`databend_common_base::runtime::Runtime::block_on`] (not tokio's) is used to execute async code within a sync context. It seems to be safe (not blocking other async tasks), but I am not quite sure.
@zhang2014  Please help review this usage.
- - - …

fix: lock attach table's snapshot location 

---

Cargo.lock
src/meta/api/src/schema_api_test_suite.rs
src/meta/app/src/schema/virtual_column.rs
src/meta/proto-conv/src/util.rs
src/meta/proto-conv/src/virtual_column_from_to_protobuf_impl.rs
src/meta/proto-conv/tests/it/main.rs
src/meta/proto-conv/tests/it/v041_virtual_column.rs
src/meta/proto-conv/tests/it/v111_add_glue_as_iceberg_catalog_option.rs
src/meta/proto-conv/tests/it/v112_virtual_column.rs
src/meta/protos/proto/virtual_column.proto
src/query/catalog/src/plan/pushdown.rs
src/query/ee/src/storages/fuse/operations/virtual_columns.rs
src/query/ee/src/virtual_column/virtual_column_handler.rs
src/query/ee/tests/it/storages/fuse/operations/virtual_columns.rs
src/query/ee_features/virtual_column/Cargo.toml
src/query/ee_features/virtual_column/src/virtual_column.rs
src/query/sql/src/executor/physical_plans/physical_table_scan.rs
src/query/sql/src/planner/binder/bind_context.rs
src/query/sql/src/planner/binder/bind_query/bind_select.rs
src/query/sql/src/planner/binder/ddl/virtual_column.rs
src/query/sql/src/planner/binder/table.rs
src/query/sql/src/planner/plans/ddl/virtual_column.rs
src/query/sql/src/planner/semantic/type_check.rs
src/query/sql/src/planner/semantic/virtual_column_rewriter.rs
src/query/storages/fuse/src/io/read/block/block_reader_native_deserialize.rs
src/query/storages/fuse/src/io/read/virtual_column/virtual_column_reader_parquet.rs
src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs
src/query/storages/system/src/virtual_columns_table.rs
src/tests/sqlsmith/src/sql_gen/ddl.rs
tests/sqllogictests/suites/ee/01_ee_system/01_0002_virtual_column.test

allow virtual column cast to other type, avoiding jsonb value deserialization to improve performance.
- fix meta proto-conv v111 add glue meta test
- virtual column proto add `data_types` field
- allow virtual column cast to other types, this can avoids jsonb value deserialization to improve performance
From the following example, we can see that the execution time has been reduced from 291.674 sec to 235.888 sec, and the amount of data read has been reduced from 11.01 GiB to 9.16 GiB
```sql
root@0.0.0.0:48000/default> CREATE OR REPLACE TABLE user_activity_logs AS
SELECT 
number % 100000000 AS id,
JSON_OBJECT(
'id', CAST(number % 100000000 AS STRING),
'email', CONCAT('user', CAST(number % …
```

feat(query): virtual column allow cast to other type

---

src/meta/binaries/metactl/import.rs
src/meta/process/src/process_meta_dir.rs
src/meta/raft-store/src/config.rs
src/meta/raft-store/src/ondisk/mod.rs
src/meta/raft-store/src/ondisk/upgrade_to_v004.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/configs/outer_v0.rs
src/meta/service/tests/it/configs.rs
src/meta/service/tests/it/grpc/metasrv_grpc_watch.rs
src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs
src/meta/service/tests/it/tests/service.rs

- Fix: #16942
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16966)

refactor: make test_watch_expired_events() less sensitive to inaccurate time

---

Cargo.lock

[0.7.3: Security update, unsoundness in RingBuffer](https://github.com/KillingSpark/zstd-rs/releases/tag/v0.7.3)  
```
cargo audit --db ./target/advisory-db
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 689 security advisories (from ./target/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (1346 crate dependencies)
Crate:     ruzstd
Version:   0.7.2
Title:     `ruzstd` uninit and out-of-bounds memory reads
Date:      2024-11-28
ID:        RUSTSEC-2024-0400
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0400
Solution:  Upgrade to >=0.7.3
```
This block our CI
- - - …

chore: bump ruzstd from 0.7.2 to 0.7.3

---

src/query/service/src/pipelines/processors/transforms/transform_dictionary.rs
tests/sqllogictests/src/mock_source/mysql_source.rs
tests/sqllogictests/suites/query/functions/02_0077_function_dict_get.test

**Previous Impl**: For the Column type, loop through the Column and get the values from MySQL **one by one** via sqlx.
**Current Impl**: We change the sql query to fetch data **in batches** via sqlx.
```sql
-- pre sql
SELECT {value} FROM {table} WHERE {key} = ? LIMIT 1; 
-- cur sql
SELECT {key},{value} FROM {table} WHERE {key} in ({key1,key2,...});
```
The performance comparison is shown in the following table.
| **strategy \ key count \ elapsed time(seconds)** | 1w     | 10w      | 100w     |
| ------------------------------------------------ | ------ | -------- | -------- |
| **Previous Impl (one by one)**                   | 26.839 | 1122.486 | \        |
| **Current Impl (in batches)** …

feat(query): speed up fetching mysql data from dictionaries via batch processing.

---

src/query/pipeline/transforms/src/processors/transforms/sort/k_way_merge_sort_partition.rs
src/query/pipeline/transforms/src/processors/transforms/sort/list_domain.rs

- fixes: #16923
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16979)

fix: fix segfault  in list_domain

---

src/query/service/src/pipelines/processors/transforms/transform_dictionary.rs
tests/sqllogictests/src/mock_source/mysql_source.rs
tests/sqllogictests/suites/query/functions/02_0077_function_dict_get.test

The problem of `NULL` values in the table has been resolved using `Option`, where `NULL` in the table is replaced with `None`.
- fixes: #16976 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16978)

fix(query): fix bug while mysql external dictionary table contains null values

---

src/query/ast/src/parser/query.rs
src/query/sql/src/planner/binder/sort.rs
tests/sqllogictests/suites/base/03_common/03_0004_select_order_by.test

close #16914
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16967)

fix(sqlparser): fix order by followed by scalar

---

src/query/functions/src/lib.rs
src/query/sql/src/planner/binder/aggregate.rs
src/query/sql/src/planner/binder/bind_query/bind_select.rs
src/query/sql/src/planner/binder/bind_table_reference/bind_table_function.rs
src/query/sql/src/planner/binder/distinct.rs
src/query/sql/src/planner/binder/project_set.rs
src/query/sql/src/planner/binder/select.rs
src/query/sql/src/planner/expression_parser.rs
src/query/sql/src/planner/plans/scalar_expr.rs
src/query/sql/src/planner/semantic/grouping_check.rs
src/query/sql/src/planner/semantic/type_check.rs
src/query/sql/src/planner/semantic/window_check.rs
tests/sqllogictests/suites/base/03_common/03_0003_select_group_by.test
tests/sqllogictests/suites/base/09_fuse_engine/09_0000_remote_create_table.test
tests/sqllogictests/suites/mode/standalone/explain/project_set.test

- group by item allow set returning functions.
- refactor binding set returning function, rewrite as column then analyze to simplify the process.
fixes: #16873
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16986)

fix(query): group by item allow set returning functions

---

src/query/service/src/servers/http/middleware/session.rs
tests/suites/1_stateful/09_http_handler/09_0009_cookie.py

http handler set cookie only when `cookie_enabled=true`, otherwise, may lead to problem when client enabled cookie by mistake
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16992)

fix: http handler set cookie only when cookie_enabled=true.

---

src/query/storages/fuse/src/table_functions/fuse_time_travel_size.rs

If an error occurs when reading the latest snapshot, the function will continue execution instead of stopping. And the error will be recorded in the result set.
For example:
```
root@localhost:8000/default> select * from fuse_time_travel_size('test_fuse_time_travel_size');
SELECT * FROM fuse_time_travel_size('test_fuse_time_travel_size')
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│        database_name       │ …
```

chore: adjust fuse_time_travel_size()

---

.cargo/audit.toml
Cargo.toml

https://rustsec.org/advisories/RUSTSEC-2024-0402
Crate:     hashbrown
Version:   0.15.0
Title:     Borsh serialization of HashMap is non-canonical
Date:      2024-10-11
ID:        RUSTSEC-2024-0402
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0402
we are using
```
hashbrown = { version = "0.15.0", default-features = false }
hashbrown_v0_14 = { package = "hashbrown", version = "0.14.0", default-features = false, features = ["ahash"] }
```
only version 0.15.0 is affected,  but many libs dep on this version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/16998)

ci: ignore RUSTSEC-2024-0402.

---

Cargo.lock
src/query/service/src/servers/http/v1/query/http_query.rs
src/query/storages/common/session/src/temp_table.rs
tests/suites/1_stateful/09_http_handler/09_0008_forward.py

the bug happen only client do not poll pages until query finish or server crashed (server restart or client connect to another server in cluster) before that.
1. start a long running query
```
🐳 :) select * from numbers(1000000000000) ignore_result;
```
2. restart  server before it end
3. start any new query in the same client session
```
🐳 :) select * from numbers(1000000000000) ignore_result;
error: APIError: QueryFailed: [4004]there are temp tables in session, but the request routed to the wrong server: current server is mTXoTYwSLlABvFt2h4zn41, the last is s0yzbB3qCV8WUp7Feq69w3.
```
- - - …

fix: need_sticky field was incorrectly set to true.

---

scripts/setup/rust-tools.txt
src/query/catalog/src/plan/pushdown.rs
src/query/sql/src/executor/physical_plans/physical_table_scan.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0039_topk_sorter.test

chore(query): fix topk in native format
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17003)

chore(query): fix topk in native

---

src/query/service/src/servers/http/middleware/session.rs
tests/suites/1_stateful/09_http_handler/09_0009_cookie.py

we used to assume client only care about name and value (ignore domain and path).
this fix is to  avoid accumulation of cookies of diff paths if client enabled cookie mistakenly but not ignore path.
however, we can not set domain freely, because it will not work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17008)

refactor: set path of cookie.

---

src/meta/api/src/schema_api_impl.rs

And fix the issue that when db-meta is not found, the returned db-name
should be set to None too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17011)

refactor: auto split large mget_database_names_by_ids into chunks with `KVPbApi::get_pb_values_vec()`

---

Cargo.lock
src/query/service/src/catalogs/default/database_catalog.rs
src/query/service/src/catalogs/default/immutable_catalog.rs
src/query/service/src/table_functions/show_grants/show_grants_table.rs
src/query/storages/system/src/streams_table.rs
tests/suites/0_stateless/18_rbac/18_0007_privilege_access.result

refactor call `mget_database_names_by_ids` and `mget_table_names_by_ids` remove duplicate ids to avoid too many parameters.
fix reorder of the returned names, the order of the returned names are same as the parameter id.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17013)

refactor: mget db names and table names remove duplicate ids to avoid too many parameters

---

src/meta/kvapi/src/kvapi/test_suite.rs
src/meta/types/src/proto_ext/txn_ext.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17033)

chore: add more test to meta-service txn value-matching

---

src/query/service/src/clusters/cluster.rs
src/query/settings/src/settings_default.rs

chore(cluster): disable parallel commit for cluster task
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17034)

chore(cluster): disable parallel commit for cluster task

---

src/query/storages/fuse/src/operations/read_data.rs
src/query/storages/fuse/src/operations/read_partitions.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17035)

chore: improve error handling in partition sending loop

---

.github/workflows/release.yml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17041)

chore(ci): remove musl release

---

src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_union.rs
tests/sqllogictests/suites/query/cte/r_cte_union_all.test

- fixes: https://github.com/databendlabs/databend/issues/17027
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17031)

fix: filter push down union in r cte

---

Cargo.lock
Cargo.toml
src/meta/raft-store/src/raft_log_v004/codec_wrapper.rs
src/meta/service/src/store/store_inner.rs

When EXT4 is mounted with data=writeback, data and metadata (file length)
can be written to disk in arbitrary order, potentially leaving trailing
zeros in the WAL tail.
Fix: Truncate zero bytes starting from the first un-decodable WALRecord
and treat the chunk as successfully opened.
This issue is fixed in the dependent crate:
- https://github.com/drmingdrmer/raft-log/commit/757542bfc6f862184ee6f40a2d98c8222653767f
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17042)

fix: handle trailing zeros in Raft log WAL with EXT4 writeback mode

---

src/meta/client/src/lib.rs
src/meta/kvapi/src/kvapi/test_suite.rs
src/meta/raft-store/src/applier.rs
src/meta/types/proto/meta.proto
src/meta/types/src/cmd/mod.rs
src/meta/types/src/proto_display.rs
src/meta/types/src/proto_ext/txn_ext.rs

Enable transaction conditions based on the number of keys matching a prefix.
Example:
```rust
let txn = TxnRequest {
condition: vec![ TxnCondition::match_keys_with_prefix("key/", Eq, 3) ],
//...
}
```
This allows transactions to proceed only when a prefix matches an expected
number of keys, providing atomic prefix-based cardinality checks.
This commit involves a databend-meta server side change:
- Add `txn_condition::Target::KeysWithPrefix`.
To provide compatibility, any change to the client that uses this
feature must update the compatibility doc and upgrade the databend-meta
cluster first.
- - - …

feat: add key prefix count assertions to transactions

---

src/query/sql/src/planner/binder/ddl/table.rs
tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables.test

- fixes: #16794
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17052)

feat(query): null type infer as Nullabel(String) by default in create as statement

---

src/query/ast/src/ast/expr.rs
src/query/ast/src/lib.rs
src/query/sql/src/planner/binder/bind_query/bind.rs
src/query/sql/src/planner/binder/bind_table_reference/bind_table.rs
src/query/sql/src/planner/binder/bind_table_reference/bind_table_function.rs
src/query/sql/src/planner/binder/binder.rs
src/query/sql/src/planner/binder/ddl/table.rs
src/query/sql/src/planner/binder/table.rs
src/query/sql/src/planner/dataframe.rs
src/query/sql/src/planner/expression_parser.rs
src/query/sql/src/planner/metadata.rs
src/query/sql/src/planner/plans/plan.rs
tests/sqllogictests/suites/mode/cluster/create_table.test
tests/sqllogictests/suites/mode/standalone/explain/explain_ddl.test
tests/sqllogictests/suites/query/cte/cte.test

Fixes: #17043
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17046)

chore(binder): fix bind materialized cte

---

.cargo/audit.toml
src/common/base/Cargo.toml

Disable (remove) cargo feature `tikv-jemalloc-sys/unprefixed_malloc_on_supported_platforms` to prevent `lz4-sys` from using jemalloc's `calloc`, as significant performance regressions were observed in the flight RPC compression between version 636 and version 307.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17062)

chore: (v1.2.636-rc8.1) disable unprefixed_malloc_on_supported_platforms

---

Cargo.lock
Cargo.toml

remove println in https://github.com/datafuse-extras/dtparse/pull/2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17073)

chore: bump dtparse

---

src/query/catalog/src/table_context.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/tests/it/sql/exec/get_table_bind_test.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/service/tests/it/storages/fuse/pruning_pipeline.rs
src/query/storages/fuse/src/operations/read_partitions.rs

fix(query): fix thread leak and remove all usage
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17081)

fix(query): fix thread leak and remove all usage

---

src/query/ast/src/ast/query.rs
src/query/catalog/src/table_context.rs
src/query/service/src/interpreters/common/stream.rs
src/query/service/src/interpreters/interpreter_copy_into_location.rs
src/query/service/src/interpreters/interpreter_copy_into_table.rs
src/query/service/src/interpreters/interpreter_insert.rs
src/query/service/src/interpreters/interpreter_insert_multi_table.rs
src/query/service/src/interpreters/interpreter_mutation.rs
src/query/service/src/interpreters/interpreter_replace.rs
src/query/service/src/interpreters/interpreter_select.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/sql/src/planner/binder/bind_query/bind.rs
src/query/sql/src/planner/binder/bind_table_reference/bind_table.rs
src/query/sql/src/planner/binder/bind_table_reference/bind_table_function.rs
src/query/sql/src/planner/binder/binder.rs
src/query/sql/src/planner/binder/table.rs
src/query/sql/src/planner/dataframe.rs
src/query/sql/src/planner/expression_parser.rs
src/query/sql/src/planner/metadata.rs
src/query/storages/common/table_meta/src/table/stream_keys.rs
src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/operations/changes.rs
src/query/storages/stream/src/stream_table.rs
tests/sqllogictests/suites/ee/06_ee_stream/06_0008_stream_issue_17058

Use materialized cte for standard stream to fix the error.
The change query for stream:
_PostgreSQL Dialect_
```sql
WITH
_change$6763a8db AS materialized (
SELECT
"a",
"b",
a_change$action,
a_change$row_id,
d_a,
d_b,
d_change$action,
d_change$row_id
FROM
(
SELECT
"a",
"b",
_row_version,
'INSERT' AS a_change$action,
if(
is_not_null (_origin_block_id),
concat(
to_uuid (_origin_block_id),
lpad(hex(_origin_block_row_num), 6, '0')
),
_change_insert$6763a8db._base_row_id
) AS a_change$row_id
FROM
DEFAULT.s AS _change_insert$6763a8db
) AS A 
FULL OUTER JOIN (
SELECT
"a" AS d_a,
"b" AS d_b,
_row_version,
'DELETE' AS d_change$action,
if(
is_not_null (_origin_block_id),
concat(
to_uuid …
```

fix: change tracking stream failed

---

src/query/sql/src/planner/binder/bind_table_reference/bind_join.rs
src/query/sql/src/planner/binder/scalar_common.rs
tests/sqllogictests/suites/mode/cluster/explain_v2.test
tests/sqllogictests/suites/mode/cluster/shuffle.test
tests/sqllogictests/suites/mode/standalone/explain/expression_scan.test
tests/sqllogictests/suites/mode/standalone/explain/join_reorder/chain.test
tests/sqllogictests/suites/mode/standalone/explain/lateral.test
tests/sqllogictests/suites/mode/standalone/explain/limit.test
tests/sqllogictests/suites/mode/standalone/explain/push_down_filter/push_down_filter_join/push_down_filter_self_join.test
tests/sqllogictests/suites/mode/standalone/explain_native/expression_scan.test
tests/sqllogictests/suites/mode/standalone/explain_native/join_reorder/chain.test
tests/sqllogictests/suites/mode/standalone/explain_native/limit.test
tests/sqllogictests/suites/query/join/left_outer.test

bind join left and right column wrap nullable will cause not null column have a nullable data type, and evaluator checks the data type of the column data when it is executed. If the data type does not match, the check fails and panic occurs. After the modification, add additional `EvalScalar` plan to generate derived nullable columns if join operator need.
- fixes: #17067
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17069)

fix(query): fix join on not null column cause panic

---

src/query/ast/src/ast/statements/table.rs
src/query/service/src/interpreters/common/table_option_validation.rs
src/query/service/src/interpreters/interpreter_table_create.rs
src/query/service/src/interpreters/interpreter_table_set_options.rs
src/query/service/src/interpreters/interpreter_table_show_create.rs
tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables.test
tests/sqllogictests/suites/base/06_show/06_0001_show_create_table.test

1. Check if the table option is valid according to the engine. For example, for the Fuse engine, both `location` and `seed` are invalid options.
2. When using `SHOW CREATE TABLE`, the external location for the Fuse engine will no longer be displayed as "LOCATION = ", to distinguish it from the table option location.
Close #17075.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17076)

fix: check if the table option is valid according to the engine

---

tests/sqllogictests/suites/mode/cluster/shuffle.test
tests/sqllogictests/suites/mode/standalone/explain/push_down_filter/push_down_filter_join/push_down_filter_self_join.test

https://github.com/databendlabs/databend/actions/runs/12412305993/job/34653486149
https://github.com/databendlabs/databend/actions/runs/12412305993/job/34653489505
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17090)

fix(ci): flaky test

---

src/common/column/src/types/native.rs
tests/sqllogictests/suites/query/functions/02_0079_function_interval.test

Casting days to u32 before casting to i128 to prevent sign extension. 
Casting microseconds to u64 before casting to i128 to prevent sign extension.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17086)

fix(query): Correct sign extension handling in months_days_micros struct

---

Cargo.lock
src/meta/api/src/schema_api_impl.rs
src/meta/api/src/sequence_api_impl.rs
src/meta/binaries/metabench/main.rs
src/meta/client/src/lib.rs
src/meta/kvapi/Cargo.toml
src/meta/kvapi/src/kvapi/test_suite.rs
src/meta/process/src/kv_processor.rs
src/meta/raft-store/src/applier.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/tests/it/grpc/metasrv_grpc_transaction.rs
src/meta/service/tests/it/grpc/metasrv_grpc_watch.rs
src/meta/types/build.rs
src/meta/types/proto/meta.proto
src/meta/types/src/cmd/mod.rs
src/meta/types/src/proto_display.rs
src/meta/types/src/proto_ext/txn_ext.rs
src/meta/types/tests/it/main.rs
src/meta/types/tests/it/txn_serde.rs
src/query/management/src/role/role_mgr.rs
src/query/management/src/stage/stage_mgr.rs

Since this commit, application is allowed to specify a complex bool
expressions as the transaction predicate.
For example, the transaction will execute as if running the following
pseudo codes:
```
if (a == 1 || b == 2) && (x == 3 || y == 4) { ops1 }
else if (x == 2 || y == 1) { ops2 }
else if (y == 3 && z == 4) { ops3 }
else { ops4 }
```
```rust
let eq = |key: &str, val: &str| TxnCondition::eq_value(sample(key), b(val));
TxnRequest{
operations: vec![
BoolExpression::new(
Some(eq("a", 1).or(eq("b", 2))
.and(eq("x", 3).or(eq("y", 4)))),
ops1),
BoolExpression::new(
Some(eq("x", 2).or(eq("y", 1))),
ops2),
],
condition: vec![eq("y", 3), eq("z", 4)],
if_then: ops3,
else_then: ops4, 
}
```
For …

feat: databend-meta transaction support generic bool-expression and else-if chain

---

src/query/sql/src/executor/physical_plans/physical_union_all.rs
tests/sqllogictests/suites/ee/06_ee_stream/06_0000_stream.test
tests/sqllogictests/suites/mode/standalone/explain/push_down_filter/push_down_filter_eval_scalar.test
tests/sqllogictests/suites/mode/standalone/explain/union.test
tests/sqllogictests/suites/mode/standalone/explain_native/push_down_filter/push_down_filter_eval_scalar.test

Fix panic bug in Union All due to incorrect **output projection**.
This PR addresses a panic issue that occurs when executing a **Union All** operation. The root cause of the bug was that the out project for Union All was not correctly set, leading to panic.
```sql
mysql> create table t1(a int, b int);
Query OK, 0 rows affected (0.18 sec)
mysql> insert into t1 values(1,1),(2,2);
+-------------------------+
| number of rows inserted |
+-------------------------+
|                       2 |
+-------------------------+
1 row in set (0.19 sec)
Read 2 rows, 18.00 B in 0.112 sec., 17.82 rows/sec., 160.42 B/sec.
mysql> create table t2(a int, b int);
mysql> insert …
```

fix(query): union all panic in mysql client

---

src/common/base/src/runtime/runtime.rs
src/query/service/src/pipelines/builders/builder_compact.rs
src/query/service/src/pipelines/builders/builder_mutation_source.rs
src/query/storages/fuse/src/operations/read_data.rs
src/query/storages/fuse/src/operations/read_partitions.rs

to make it more clean when debugging runtime problems.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17084)

refactor: set name for all runtime worker threads.

---

src/query/service/src/sessions/query_ctx.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
tests/sqllogictests/suites/ee/06_ee_stream/06_0006_stream_batch_limit.test

Introduce new settings `stream_consume_batch_size_hint`,  
- by default, it is set to 0. in this case,  `stream_consume_batch_size_hint` has no effects
if `stream_consume_batch_size_hint` is set to a non-zero value, streams will reference this setting during the process of capturing change sets and will try to keep the number of rows in the captured change set close to the specified value.
-  `MAX_BATCH_SIZE` specified in the[ WITH clause ](https://docs.databend.com/sql/sql-commands/query-syntax/with-stream-hints) have a higher priority
e.g. 
~~~
statement ok
create table t_settings (c int);
statement ok
CREATE STREAM s_t_settings ON TABLE t_settings;
statement ok
INSERT INTO t_settings …

feat: new settings `stream_consume_batch_size_hint`

---

src/query/ast/src/parser/expr.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/expr.txt
tests/sqllogictests/suites/query/functions/02_0079_function_interval.test

```sql
select interval '1 year';
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17105)

feat(query): support interval 'string'

---

scripts/ci/deploy/config/databend-query-node-1.toml
src/query/config/src/config.rs
src/query/service/tests/it/configs.rs

1. Fix default values of `SpillConfig` may not take effect
2. Enable local spill in ci logic test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17113)

fix(query): fix default values of `SpillConfig` may not take effect

---

src/query/ast/src/ast/statements/table.rs
src/query/ast/src/parser/statement.rs
src/query/ast/tests/it/testdata/stmt.txt
src/query/service/src/interpreters/interpreter_vacuum_drop_tables.rs
src/query/sql/src/planner/binder/ddl/table.rs
src/query/sql/src/planner/plans/ddl/table.rs

This reverts PR:
- #17110
- #17022
Fixes: #17124
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17123)

feat: support vacuum leaked table data (#17022)-Revert

---

Cargo.lock
Cargo.toml
tests/data/udf/to_array.js
tests/sqllogictests/src/mock_source/mysql_source.rs
tests/sqllogictests/suites/udf_native/03_0001_udf_js.test

bump `arrow-udf` to fix the bug udf script function return type is arrow `DataType::LargeList` caused failed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17127)

fix(query): fix udf script return type is arrow `DataType::LargeList` caused failed

---

src/query/service/src/servers/mysql/mod.rs
src/query/service/src/sessions/query_ctx.rs
tests/sqllogictests/suites/query/case_sensitivity/query.test

The original MySQL protocol version reported by Databend was deemed too low, triggering security vulnerability alerts .
To address this, the reported MySQL protocol version has been changed to 8.0.90.  This higher version number is intended to avoid security scans that flag older versions as vulnerable.
This change was implemented by modifying the relevant configuration or code within Databend that controls the reported MySQL protocol version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17118)

chore(query): bump federated mysql version

---

Cargo.lock
Cargo.toml
src/query/expression/src/expression.rs
src/query/expression/src/kernels/group_by.rs
src/query/expression/src/types.rs
src/query/expression/src/utils/block_debug.rs
src/query/expression/tests/it/input_columns.rs
src/query/functions/src/scalars/map.rs
src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs

part of #16706
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17120)

chore(query): bump enum-as-inner 0.6

---

src/query/service/src/interpreters/interpreter_table_analyze.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0020_analyze.test

quote the column name.
- fixes #17129 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17131)

fix: analyze table contain keyword bug

---

src/meta/app/src/schema/table.rs
src/meta/proto-conv/src/table_from_to_protobuf_impl.rs
src/meta/proto-conv/tests/it/proto_conv.rs
src/meta/proto-conv/tests/it/v002_table_meta.rs
src/meta/proto-conv/tests/it/v010_table_meta.rs
src/meta/proto-conv/tests/it/v012_table_meta.rs
src/meta/proto-conv/tests/it/v023_table_meta.rs
src/meta/proto-conv/tests/it/v024_table_meta.rs
src/meta/proto-conv/tests/it/v033_table_meta.rs
src/meta/proto-conv/tests/it/v040_table_meta.rs
src/meta/proto-conv/tests/it/v044_table_meta.rs
src/meta/proto-conv/tests/it/v055_table_meta.rs
src/meta/proto-conv/tests/it/v074_table_db_meta.rs
src/meta/proto-conv/tests/it/v080_geometry_datatype.rs
src/meta/proto-conv/tests/it/v082_table_index.rs
src/meta/proto-conv/tests/it/v085_table_index.rs
src/meta/proto-conv/tests/it/v086_table_index.rs
src/meta/proto-conv/tests/it/v094_table_meta.rs
src/meta/proto-conv/tests/it/v107_geography_datatype.rs
src/meta/proto-conv/tests/it/v114_interval_datatype.rs
src/meta/protos/proto/table.proto
src/query/ee/src/attach_table/handler.rs
src/query/service/src/interpreters/interpreter_cluster_key_alter.rs
src/query/service/src/interpreters/interpreter_cluster_key_drop.rs
src/query/service/src/interpreters/interpreter_table_create.rs
src/query/service/src/interpreters/interpreter_table_show_create.rs
src/query/service/tests/it/storages/fuse/operations/clustering.rs
src/query/storages/system/src/tables_table.rs

Add annotate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17135)

chore: rename default_cluster_key_id to cluster_key_seq

---

src/common/tracing/src/init.rs

after this fix,  with the following configuration, only Databend’s own logs will be retained in the log.
```
[log]
[log.file]
...
prefix_filter = "databend_,openraft"
```
cc @wubx 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17136)

fix(log): prefix_filter not working.

---

Cargo.lock
Cargo.toml
src/common/grpc/Cargo.toml
src/common/grpc/src/dns_resolver.rs
src/query/ee/Cargo.toml
src/query/ee/src/fail_safe/handler.rs
src/query/ee_features/fail_safe/Cargo.toml
src/query/ee_features/fail_safe/src/handler.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
src/query/storages/fuse/src/table_functions/fuse_amend.rs

Since `fuse_amend` is currently implemented using the AWS Rust SDK, some behaviors may be inconsistent with other components based on OpenDAL, especially in on-premise deployment. e.g.
- Different default TLS cert verification strategy
For instance, if the HTTPS service's certificate is a CA certificate (rather than an end-entity certificate), OpenDAL (using OpenSSL) will not reject the connection. However, the default configuration of the AWS Rust SDK (using Rustls) will reject such certificates. Other similar issues may also occur.
- The configuration of the endpoint URL may require a more flexible approach in on-premise deployment
For on-premise deployments of s3-compatible services, the …

refactor: make `fuse_amend` implementation more convenient for on-premise deployments

---

Cargo.toml

If not add features client and TCP, will return error when run `cargo c --timings` under `src/query/functions`
```
➜  functions git:(main) ✗ cargo c --timings        
warning: patch for `backtrace` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
Checking databend-common-hashtable v0.1.0 (/data1/eason/databend/src/common/hashtable)
Checking databend-common-grpc v0.1.0 (/data1/eason/databend/src/common/grpc)
Checking databend-common-openai v0.1.0 (/data1/eason/databend/src/common/openai)
error[E0433]: failed to resolve: could not find `client` in `hyper_v014`
--> src/common/grpc/src/dns_resolver.rs:35:17 …
```

chore: fix cargo check

---

Cargo.lock
src/tests/sqlsmith/Cargo.toml
src/tests/sqlsmith/src/lib.rs
src/tests/sqlsmith/src/query_fuzzer.rs
src/tests/sqlsmith/src/runner.rs
src/tests/sqlsmith/src/sql_gen/query.rs

Generate fuzz query based on a `Statement`, the `Expr`s in the previous `Statement` will be collected and randomly add to the new fuzzed `Statement`. This will create a lot of interesting combinations to find potential bugs.
This PR just implements the basic fuzz functionality, we still need to find some suitable seed SQL to execute.
part of: #17130
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17153)

feat(sqlsmith): Support generate fuzz query sql

---

Cargo.lock
Cargo.toml
src/common/storage/Cargo.toml
src/common/storage/src/metrics.rs
src/common/storage/src/runtime_layer.rs
src/common/storage/src/stage.rs
src/query/ee/src/storages/fuse/operations/vacuum_drop_tables.rs
src/query/ee/src/storages/fuse/operations/vacuum_temporary_files.rs
src/query/ee/tests/it/storages/fuse/operations/vacuum.rs
src/query/service/src/interpreters/interpreter_table_vacuum.rs
src/query/storages/common/io/src/files.rs
src/query/storages/fuse/src/io/snapshots.rs
src/query/storages/fuse/src/operations/navigate.rs
src/query/storages/fuse/src/table_functions/fuse_time_travel_size.rs
src/query/storages/hive/hive/src/hive_table.rs
src/query/storages/system/src/temp_files_table.rs

Bump OpenDAL to 0.51 to get databend ready for the following new features.
This PR just upgrade opendal and didn't change any logic yet.
The biggest change is opendal won't call `stat` during `list` anymore. So for services like `fs` that doesn't return content_length in list, we will need an extra stat for them. This change doesn't affect services like s3.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17161)

refactor: Bump OpenDAL to 0.51

---

src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/functions/02_0051_function_semi_structureds_get.test
tests/sqllogictests/suites/query/functions/02_0062_function_unnest.test
tests/sqllogictests/suites/query/functions/02_0065_function_json.test
tests/sqllogictests/suites/query/functions/02_0068_function_flatten.test

- fixes: #17154
- This PR changed behavior to return a semantic error instead of panic for SRFs in WHERE and HAVING clauses.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17167)

fix(query): return semantic error for SRFs in WHERE and HAVING clauses

---

src/meta/api/src/schema_api.rs
src/meta/api/src/schema_api_impl.rs
src/query/catalog/src/catalog/interface.rs
src/query/service/src/catalogs/default/database_catalog.rs
src/query/service/src/catalogs/default/immutable_catalog.rs
src/query/service/src/catalogs/default/mutable_catalog.rs
src/query/service/src/catalogs/default/session_catalog.rs
src/query/service/src/table_functions/show_grants/show_grants_table.rs
src/query/service/tests/it/sql/exec/get_table_bind_test.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/storages/hive/hive/src/hive_catalog.rs
src/query/storages/iceberg/src/catalog.rs
src/query/storages/system/src/streams_table.rs
src/query/storages/system/src/tables_table.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17166)

refactor: Optimize When Querying the tables_history Table with the Condition table_id = n

---

src/meta/api/src/schema_api_impl.rs
src/query/service/src/interpreters/interpreter_vacuum_drop_tables.rs

more logging for the execution of `vacuum drop table` stmt.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17168)

chore: more logging for `vacuum drop table` execution

---

Cargo.lock
src/query/expression/src/aggregate/payload.rs
src/query/functions/src/aggregates/aggregate_distinct_state.rs

fix(query): check state is allocated or not when oom 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17179)

fix(query): check state is allocated or not when oom

---

src/query/storages/parquet/src/parquet_rs/copy_into_table/reader.rs
src/query/storages/parquet/src/parquet_rs/meta.rs
src/query/storages/parquet/src/parquet_rs/parquet_reader/reader/builder.rs
src/query/storages/parquet/src/parquet_rs/parquet_reader/reader/full_reader.rs
src/query/storages/parquet/src/parquet_rs/parquet_table/read.rs
src/query/storages/parquet/src/parquet_rs/source.rs
tests/sqllogictests/suites/stage/formats/parquet/error_diff_schema.test

before this pr, when try loading small parquet files with diff schema, user may encounter error like
```
error: APIError: QueryFailed: [1104]index out of bounds: the len is 4 but the index is 4.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17175)

chore: check schema for small parquet file too.

---

src/query/sql/src/planner/binder/bind_query/bind.rs
tests/sqllogictests/suites/query/cte/cte.test

Close: #17181
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17183)

chore(binder): fix bind cte

---

.github/scripts/bump_version.js
.github/workflows/dev.yml
.github/workflows/main.yml
.github/workflows/release.yml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17185)

chore(ci): support backport release

---

src/query/management/src/warehouse/warehouse_mgr.rs
src/query/management/tests/it/warehouse.rs
src/query/service/src/clusters/cluster.rs

fix(cluster): fix unassign warehouse nodes failure
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17195)

fix(cluster): fix unassign warehouse nodes failure

---

src/common/base/src/base/mod.rs
src/common/base/src/base/progress.rs
src/query/service/src/interpreters/hook/vacuum_hook.rs
src/query/service/src/servers/flight/v1/exchange/statistics_sender.rs
src/query/service/src/servers/flight/v1/packets/packet_data_progressinfo.rs
src/query/service/src/servers/http/v1/query/execute_state.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/service/src/spillers/spiller.rs
tests/sqllogictests/src/main.rs

feat(query): support send spill file stats to client
https://github.com/databendlabs/bendsql/pull/565
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17186)

feat(query): support send spill file stats to client

---

src/query/management/src/warehouse/warehouse_mgr.rs
src/query/management/tests/it/warehouse.rs
src/query/service/src/interpreters/interpreter_factory.rs

fix(cluster): fix recovery suspended warehouse
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17193)

fix(cluster): skip the recovery for warehouses that are not running state.

---

.github/actions/test_compat_fuse/action.yml
tests/compat_fuse/compat-logictest/udf/fuse_compat_read
tests/compat_fuse/compat-logictest/udf/fuse_compat_write

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17184)

chore: add udf compat ci

---

src/query/storages/system/src/tables_table.rs
tests/suites/0_stateless/18_rbac/18_0003_db_visibility.result
tests/suites/0_stateless/18_rbac/18_0003_db_visibility.sh

```sql
create user a identified by '123' with default_role='a';
create role a;
create database a;
grant ownership on a.* to role a;
grant role a to a;
create table a.b(id int);
create role b;
grant ownership on a.b to role b;
-- login with user a
-- this query should return right result
select name, owner from system.tables where database = 'a'and name = 'b'
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17202)

fix: system.tables table visibility

---

.github/actions/setup_build_tool/action.yml
.github/workflows/reuse.linux.hive.yml
.github/workflows/reuse.linux.yml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17201)

chore(ci): upload sccache log for build

---

src/common/storage/src/statistics.rs
src/query/service/src/interpreters/interpreter_explain.rs
src/query/service/src/interpreters/interpreter_factory.rs
src/query/service/src/interpreters/interpreter_mutation.rs
src/query/service/src/interpreters/interpreter_table_add_column.rs
src/query/service/src/test_kits/fuse.rs
src/query/sql/src/planner/optimizer/property/histogram.rs
tests/sqllogictests/suites/mode/cluster/memo/aggregate_property.test
tests/sqllogictests/suites/mode/cluster/memo/join_property.test
tests/sqllogictests/suites/mode/cluster/memo/mix_property.test
tests/sqllogictests/suites/mode/standalone/explain/eliminate_outer_join.test
tests/sqllogictests/suites/mode/standalone/explain/join.test
tests/sqllogictests/suites/mode/standalone/explain/lateral.test
tests/sqllogictests/suites/mode/standalone/explain/selectivity/filter.test
tests/sqllogictests/suites/mode/standalone/explain_native/explain.test
tests/sqllogictests/suites/mode/standalone/explain_native/join.test
tests/sqllogictests/suites/mode/standalone/explain_native/limit.test
tests/suites/0_stateless/19_fuzz/19_0004_fuzz_filter.py
tests/suites/0_stateless/19_fuzz/19_0004_fuzz_filter.result

Improve histogram cardinality estimation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17200)

chore(planner): improve histogram cardinality estimation

---

Cargo.toml

As title.
Fix the following warning:
```
warning: patch for `backtrace` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17204)

chore: Fix warning for backtrace while compiling

---

scripts/ci/deploy/config/databend-query-node-1.toml
src/common/cache/src/cache.rs
src/common/cache/src/cache/lru.rs
src/query/service/src/interpreters/access/privilege_access.rs
src/query/service/src/table_functions/table_function_factory.rs
src/query/storages/common/cache/src/manager.rs
src/query/storages/common/cache/src/providers/memory_cache.rs
src/query/storages/fuse/src/table_functions/mod.rs
src/query/storages/fuse/src/table_functions/set_cache_capacity.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0043_set_cache_cap.sql 
tests/suites/0_stateless/20+_others/20_0021_set_cache_capacity_privilege_check.result
tests/suites/0_stateless/20+_others/20_0021_set_cache_capacity_privilege_check.sh

bring back function `system$set_cache_capacity`  (https://github.com/databendlabs/databend/pull/16016)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17196)

chore: bring back function `set_cache_capacity`

---

src/query/expression/src/property.rs
src/query/expression/src/utils/column_from.rs
src/query/expression/src/values.rs
src/query/sql/src/planner/binder/bind_query/bind_select.rs
src/query/sql/src/planner/semantic/type_check.rs
src/tests/sqlsmith/src/bin/main.rs
src/tests/sqlsmith/src/query_fuzzer.rs
src/tests/sqlsmith/src/runner.rs
src/tests/sqlsmith/src/sql_gen/ddl.rs
src/tests/sqlsmith/src/sql_gen/dml.rs
src/tests/sqlsmith/src/sql_gen/expr.rs
src/tests/sqlsmith/src/sql_gen/func.rs
src/tests/sqlsmith/src/sql_gen/query.rs
src/tests/sqlsmith/src/sql_gen/sql_generator.rs
src/tests/sqlsmith/src/sql_gen/types.rs

fuzz query supports the `fuzz-path` argument, which can specify the test file path and generate more complex SQL by reading the existing `sqllogictest` as a seed case for fuzz.
The following example read all sqllogic tests in the `query/functions` folder and fuzz the SQL from there.
```sql
./target/debug/databend-sqlsmith --port 48000 --fuzz-path ./tests/sqllogictests/suites/query/functions
2025-01-08T11:35:16.095205Z  INFO databend_sqlsmith::runner: orig sql: SELECT sum(number) AS salary, number%3 AS user_name FROM numbers_mt(10000) GROUP BY user_name ORDER BY salary ASC
2025-01-08T11:35:16.099655Z  INFO databend_sqlsmith::runner: fuzz sql: SELECT number % 3 AS salary, number % (3 - 953) AS …
```

feat(sqlsmith): fuzz query support sqllogic test cases

---

src/query/storages/stage/src/append/parquet_file/writer_processor.rs

fix(query): stick the created_by infos in parquet writer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17220)

fix(query): stick the created_by infos in parquet writer

---

.github/actions/artifact_upload/action.yml
Cargo.toml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17253)

chore(ci): presign artifact for download

---

src/query/service/src/interpreters/access/privilege_access.rs
tests/suites/0_stateless/18_rbac/18_0007_privilege_access.result
tests/suites/0_stateless/18_rbac/18_0007_privilege_access.sh

query setting, session setting, set variable will not check privileges
fix: #17242 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17255)

refactor: only set global settings need to check super privilege

---

src/query/sql/src/executor/physical_plans/physical_constant_table_scan.rs
src/query/sql/src/planner/metadata.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_eliminate_filter.rs
tests/sqllogictests/suites/query/issues/issue_17158.test

The `build_limit` method of `PhysicalPlanBuilder` excludes lazy columns and adds them back in RowFetch, including the row_id_col in the table scan but not in the constant table scan. So, I directly add the lazy columns to the `output_schema` of the constant table scan.
- fixes: #17158 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17258)

fix(query): fix lazy columns missed in constant table scan

---

src/meta/api/src/name_id_value_api.rs
src/meta/api/src/schema_api_impl.rs
src/meta/kvapi/src/kvapi/value.rs
src/query/management/src/procedure/procedure_mgr.rs
tests/suites/5_ee/01_vacuum/01_004_vacuum_drop_aggregating_index.result
tests/suites/5_ee/01_vacuum/01_004_vacuum_drop_aggregating_index.sh

The `create or replace index` operation may cause an index to be dropped, and such dropped indexes should also be recorded in `__fd_marked_deleted_index`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17263)

fix: vacuum index not work if index is dropped by create or replace

---

src/query/ast/src/parser/expr.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/expr.txt
tests/sqllogictests/suites/query/window_function/window_basic.test

window function support params
for example
```sql
root@0.0.0.0:48000/default> CREATE TABLE empsalary (depname string, empno bigint, salary int, enroll_date date);
root@0.0.0.0:48000/default> INSERT INTO empsalary VALUES ('develop', 10, 5200, '2007-08-01'), ('sales', 1, 5000, '2006-10-01'), ('personnel', 5, 3500, '2007-12-10'), ('sales', 4, 4800, '2007-08-08'), ('personnel', 2, 3900, '2006-12-23'), ('develop', 7, 4200, '2008-01-01'), ('develop', 9, 4500, '2008-01-01'), ('sales', 3, 4800, '2007-08-01'), ('develop', 8, 6000, '2006-10-01'), ('develop', 11, 5200, '2007-08-15');
SELECT depname, empno, quantile_cont(0.8)(salary) OVER (PARTITION BY depname ORDER BY empno) FROM empsalary ORDER BY …
```

fix(query): window function support params

---

tests/databend-test

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17288)

chore: databend-test print more stderr

---

src/query/service/src/pipelines/pipeline_builder.rs
src/query/service/src/pipelines/processors/transforms/mod.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sessions/query_ctx_shared.rs

fix(query): only call once finish callback of unload_spill_meta
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17293)

refactor(query): only call once finish callback

---

Cargo.lock
Cargo.toml
src/query/sql/src/evaluator/block_operator.rs
src/query/sql/src/planner/binder/copy_into_table.rs
src/query/sql/src/planner/expression_parser.rs
src/query/storages/common/stage/src/read/columnar/projection.rs
src/query/storages/orc/src/copy_into_table/processors/decoder.rs
src/query/storages/orc/src/copy_into_table/projection.rs
src/query/storages/parquet/src/parquet_rs/copy_into_table/reader.rs
tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables.test

1. temp orc support fill missing tuple field, including `tuple and array(tuple)`
2. speed up orc load by reading each stripe in one IO.
3. fix cluster key bug https://github.com/databendlabs/databend/issues/17251
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17247)

feat: orc support fill missing tuple field

---

src/query/sql/src/planner/binder/copy_into_table.rs
src/query/sql/src/planner/plans/copy_into_table.rs
src/query/storages/parquet/src/parquet_rs/parquet_table/table.rs

add a log by the way which will be helpful for debugging https://github.com/databendlabs/databend/issues/17284
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17300)

fix: copy into table collect files twice some times.

---

src/query/catalog/src/catalog/interface.rs
src/query/sql/src/planner/binder/binder.rs

revelant issue: #17306
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17307)

chore: make error message of conflicting transactions more user-friendly

---

src/query/sql/src/planner/planner.rs
src/query/storages/parquet/src/parquet_rs/parquet_table/table.rs

the bug may lead to performance regression  when loading many small parquet files, for useless collection of statics of all parquet files.
introduced in https://github.com/databendlabs/databend/pull/17045/files#diff-5da9a5a6e26ef54156ba5550ed3dd65e7116c89b38aeb90a3b5156a4f8955caaL265
only affect version 688
maybe related to   [17284](https://github.com/databendlabs/databend/issues/17284).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17302)

fix: set query_kind earlier to ensure it takes effect.

---

src/query/storages/parquet/src/parquet_rs/meta.rs

- fixes: https://github.com/databendlabs/databend/issues/17312 and https://github.com/databendlabs/databend/issues/17284
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17313)

fix: use full path as cache key for parquet meta.

---

src/query/pipeline/transforms/src/processors/transforms/transform_accumulating_async.rs
src/query/storages/fuse/src/operations/read/fuse_rows_fetcher.rs
src/query/storages/fuse/src/operations/read/native_rows_fetcher.rs
src/query/storages/fuse/src/operations/read/parquet_rows_fetcher.rs

improve fuse row fetch, use accumulating to reduce row fetch io times
random hits data on 2 local nodes
```
select *  from hits where UserID % 10000 = 1 limit 100;    1.5s --> 0.2s
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17309)

chore(query): improve fuse row fetch, use accumulating

---

src/query/ast/src/parser/expr.rs
src/tests/sqlsmith/src/bin/main.rs
src/tests/sqlsmith/src/lib.rs
src/tests/sqlsmith/src/runner.rs
src/tests/sqlsmith/src/sql_gen/ddl.rs
src/tests/sqlsmith/src/sql_gen/dml.rs
src/tests/sqlsmith/src/sql_gen/func.rs
src/tests/sqlsmith/src/sql_gen/types.rs
src/tests/sqlsmith/src/util.rs

Fuzz test support read Sqlite and Duckdb test, we can use test SQLs in Sqlite and Duckdb to generate fuzz SQLs.
for example:
```
➜  databend git:(feat-sqlsmith-log) ✗ ./target/debug/databend-sqlsmith --port 48000 --fuzz-path ../sqlite/test
2025-01-16T04:06:51.884668Z  INFO databend_sqlsmith::runner: orig sql:  DROP TABLE IF EXISTS t2;
2025-01-16T04:06:51.885408Z  INFO databend_sqlsmith::runner: fuzz sql: DROP TABLE IF EXISTS t2
2025-01-16T04:06:51.907046Z  INFO databend_sqlsmith::runner: orig sql:  CREATE TABLE t2(a INTEGER , b INTEGER);
2025-01-16T04:06:51.907878Z  INFO databend_sqlsmith::runner: fuzz sql: CREATE TABLE t2 (a Int32, b Int32)
```
```
➜  databend git:(feat-sqlsmith-log) ✗ …
```

feat(sqlsmith): fuzz test support read Sqlite and Duckdb test

---

src/query/service/src/interpreters/interpreter_table_analyze.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0044_issue_17314.sql 

Use the snapshot schema when analyze table.
- fixes: #17314 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17321)

fix: column not found in analyze

---

src/query/functions/src/scalars/timestamp/src/datetime.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test

unsupport datetime format item should not return panic error
- fix #17318
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17323)

fix(query): unsupport datetime format item should not return panic error

---

Cargo.lock
src/query/pipeline/transforms/src/processors/transforms/transform_compact_builder.rs
src/query/pipeline/transforms/src/processors/transforms/transform_compact_no_split_builder.rs
src/query/pipeline/transforms/src/processors/transforms/transform_dummy.rs
src/query/service/src/interpreters/hook/compact_hook.rs
src/query/service/src/pipelines/builders/builder_recluster.rs
src/query/sql/src/executor/physical_plan.rs
src/query/sql/src/executor/physical_plan_visitor.rs
src/query/sql/src/planner/binder/ddl/table.rs
src/query/storages/fuse/Cargo.toml
src/query/storages/fuse/src/operations/mutation/mutator/recluster_mutator.rs
src/query/storages/system/src/streams_table.rs
tests/suites/1_stateful/07_stage_attachment/07_0000_insert_with_stage.result
tests/suites/1_stateful/07_stage_attachment/07_0001_replace_with_stage.result
tests/suites/1_stateful/07_stage_attachment/07_0002_insert_with_stage_deduplicate.result

1. enable sort spill in alter recluster to avoid oom. hook compact keep disable spill.
2. fix hilbert clustering with quoted key bug.
3. Adjusts the Transform Compact operator to exclude null columns when calculating block memory size.
4. FIx hilbert clustering in cluster mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17236)

chore: enable sort spill in recluster

---

src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_window.rs
src/query/sql/src/planner/plans/window.rs
tests/sqllogictests/suites/mode/standalone/explain/window.test

- fixes: #17338
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17353)

fix(query): disallow push down filters that use columns in window order by columns or function argument columns

---

src/query/service/src/interpreters/interpreter_procedure_drop.rs
src/query/sql/src/planner/binder/ddl/procedure.rs
src/query/sql/src/planner/plans/ddl/procedure.rs
tests/sqllogictests/suites/base/15_procedure/15_0002_procedure.test

in call procedure binder, will parse arg's datatype.
in create procedure will store the arg typename.
If not Standardize the type's display, may cause confusing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17325)

fix(query): procedure support string type

---

src/query/ast/src/parser/statement.rs
src/query/service/src/interpreters/common/table.rs
src/query/service/src/interpreters/interpreter_table_add_column.rs
src/query/service/src/interpreters/interpreter_table_modify_column.rs
src/query/sql/src/planner/binder/ddl/table.rs
tests/sqllogictests/suites/base/05_ddl/05_0028_ddl_alter_table_add_drop_column.test
tests/sqllogictests/suites/ee/05_ee_ddl/05_0003_ddl_create_add_computed_column.test

Support add stored computed column
- fixes: #14403
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17347)

feat(ddl): Support add stored computed column

---

src/query/storages/fuse/src/operations/replace.rs
src/query/storages/fuse/src/operations/replace_into/meta/mod.rs
src/query/storages/fuse/src/operations/replace_into/meta/replace_into_operation_meta.rs
src/query/storages/fuse/src/operations/replace_into/mutator/mod.rs
src/query/storages/fuse/src/operations/replace_into/mutator/replace_into_mutator.rs
src/query/storages/fuse/src/operations/replace_into/mutator/replace_into_operation_agg.rs
src/query/storages/fuse/src/operations/replace_into/processors/mod.rs
src/query/storages/fuse/src/operations/replace_into/processors/processor_replace_into.rs
src/query/storages/fuse/src/operations/replace_into/processors/processor_unbranched_replace_into.rs
src/query/storages/fuse/src/operations/replace_into/processors/transform_replace_into_mutation_aggregator.rs

Initially, `REPLACE INTO` was designed as a simplified implementation of `MERGE INTO`, with the expectation that it would gradually evolve into a full-fledged implementation of `MERGE INTO`, as a result, many `MERGE INTO` related terms exist in the components of `REPLACE INTO` impl.
However, `MERGE INTO` now has its own independent impl, the remaining `MERGE INTO` related terms in the impl of `REPLACE INTO` can be misleading.
Therefore, in this PR, we have renamed all `MERGE INTO` related terms in the impl of `REPLACE INTO` to avoid confusion.
- - - …

refactor: rename components of the `replace into` impl

---

tests/sqllogictests/src/main.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17363)

chore(ci): fix intergration  ttc-go

---

src/query/ast/src/parser/query.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/stmt.txt
tests/sqllogictests/suites/query/select.test

Support `from <table> to simplify select * from <table>`
- fixes: #16617
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17372)

feat(query): support Support from <table> to simplify select * from <table>

---

src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_build.rs
tests/sqllogictests/suites/query/join/join.test

Fix hash join hang.
fixes #17351
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17389)

chore(query): fix hash join hang

---

src/query/ast/src/ast/expr.rs
src/query/ast/src/parser/expr.rs
src/query/functions/src/scalars/timestamp/src/datetime.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/sql/src/planner/semantic/type_check.rs
src/tests/sqlsmith/src/sql_gen/expr.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test

- fixes: #17384
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17385)

feat(query): support extract EPOCH from timestamp

---

Cargo.lock
src/query/storages/fuse/src/operations/read/fuse_rows_fetcher.rs
src/query/storages/fuse/src/operations/read/native_rows_fetcher.rs
src/query/storages/fuse/src/operations/read/parquet_rows_fetcher.rs

chore(query): row fetch will be fetched by distinct block batch
If the distinct block num exceeds max_threads in row_fetcher, it will process and flush the states.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17391)

chore(query): row fetch will be fetched by distinct block batch

---

src/query/sql/src/planner/expression_parser.rs
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/functions/02_0061_function_array.test

We use the number of bound columns as the column index of the lambda column, but since the column index may be discontinuous, e.g. if there is a not null column in the join table, a new nullable wrapper is generated to replace the original column, and a new column index is generated. In this case, the parameter of lambda function will got a wrong column index and cause resolve lambda function fail, this PR fixes this bug.
- fixes: #17400
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17402)

fix(query): fix lambda function bind column failed

---

src/query/expression/src/utils/date_helper.rs
src/query/functions/src/scalars/timestamp/src/datetime.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test

create or replace table t(mine_date date, birth_date date);
insert into t values('2022-01-01', '2022-01-01'),('2022-01-01', '2022-02-01'),('2022-02-01', '2022-01-01');
SELECT MONTHS_BETWEEN(mine_date, birth_date) as demo_age FROM t GROUP BY  mine_date;
return errirL
:) SELECT MONTHS_BETWEEN(mine_date, birth_date) as demo_age FROM t GROUP BY  mine_date;
error: APIError: QueryFailed: [1104]attempt to multiply with overflow
SELECT max(MONTHS_BETWEEN(mine_date, birth_date))/12 as demo_age FROM t GROUP BY  mine_date;
panicked at src/query/expression/src/utils/[date_helper.rs:246](http://date_helper.rs:246/):14:
called `Result::unwrap()` on an `Err` value: parameter 'days' with value 1 is not in the …

fix(query): fix months_between overflow error

---

src/query/ast/src/parser/expr.rs
src/query/functions/src/scalars/string.rs
src/query/functions/tests/it/scalars/string.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/functions/tests/it/scalars/testdata/string.txt
tests/sqllogictests/suites/query/functions/02_0020_function_strings_ltrim.test
tests/sqllogictests/suites/query/functions/02_0021_function_strings_rtrim.test
tests/sqllogictests/suites/query/functions/02_0055_function_strings_trim.test

https://docs.snowflake.com/en/sql-reference/functions/trim#examples
- fixes: #16798
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17375)

fix(query): Align TRIM functions semantically with Snowflake

---

src/common/column/src/types/native.rs
src/query/functions/src/aggregates/aggregate_sum.rs
tests/sqllogictests/suites/base/11_data_type/11_0007_data_type_interval.test

- fixes: #17374
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17379)

feat(query): interval support agg func sum

---

src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test

:) select date_trunc('week', '2025-02-05 00:01:00');
select
date_trunc('week', '2025-02-05 00:01:00')
┌─────────────────────────────────────────┐
│ DATE_TRUNC(WEEK, '2025-02-05 00:01:00') │
│                   Date                  │
├─────────────────────────────────────────┤
│ 2025-02-03                              │
└─────────────────────────────────────────┘
- fixes: #17404
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17407)

feat(query): support DATE_TRUNC('WEEK', EXPR)->DATE

---

src/query/expression/src/utils/udf_client.rs

this pr added a small context information about udf error. allow readers easier to recgonize it's an issue about udf function call.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17414)

chore(udf): tune the log message about udf decode error

---

src/query/storages/common/cache/src/caches.rs
src/query/storages/common/cache/src/lib.rs
src/query/storages/fuse/src/operations/replace_into/mutator/replace_into_operation_agg.rs

refine `replace into` by caching individual BlockMeta
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17368)

refactor: refine `replace into` by caching individual BlockMeta

---

.github/workflows/links.yml
README.md

fix(ci): fix Link Checker
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17416)

fix(ci): fix Link Checker

---

src/query/users/src/jwt/authenticator.rs
src/query/users/src/jwt/jwk.rs
src/query/users/tests/it/jwt/jwk.rs
src/query/users/tests/it/jwt/mod.rs

currently, we maintain a cache for the jwks keys, and use the cache to validate the jwt authentications.
however, the jwks endpoint may rotate at any time. if the client rotated with the latest jwt, we may get a key not found 401 error on jwt authentication until the next jwks refresh (by default, it's 30s).
this error can be auto-recovered after 30s, but we want to go a step further about this to make it not noticeable for users with retry.
this pr added a retry for refreshing the jwks endpoint after a key not found error. and to avoid flooding the jwks endpoint, it limited a retry_interval.
there's also a risk that the server rotates the jwks first, but the client still uses the older jwt. …

feat(auth): auto retry on jwks key not found

---

src/query/ast/src/ast/expr.rs
src/query/ast/src/parser/expr.rs
src/query/ast/src/parser/token.rs
src/query/functions/src/scalars/timestamp/src/interval.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/base/11_data_type/11_0007_data_type_interval.test

- fixes: #17392
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17417)

feat(query): Allow extract parts from interval type

---

Cargo.lock
Cargo.toml

chore: Use tagged version of opendal
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17419)

chore: Use tagged version of opendal

---

src/query/functions/src/scalars/timestamp/src/datetime.rs
src/query/functions/tests/it/scalars/testdata/datetime.txt
src/query/functions/tests/it/scalars/testdata/function_list.txt
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test

- fixes: #13686
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17422)

fix(query): to_yyyymmddhhmmss only support timestamp type

---

src/query/sql/src/planner/semantic/grouping_check.rs
tests/sqllogictests/suites/query/aggregate.test

fix(query): group checker subquery
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17420)

fix(query): group checker subquery

---

src/meta/binaries/meta/entry.rs
src/meta/binaries/metactl/main.rs
src/meta/binaries/metaverifier/main.rs
src/meta/process/src/examples.rs

Previously, the logging guard was held with `let _guard = ...`, which
caused it to be dropped when the `main` function returned. This could
lead to an error when other threads, still running and depending on the
logging guard for log output, attempt to log after the guard has been
dropped.
By using `Box::leak()`, the logging guard is ensured to remain valid for
the entire lifetime of the program, preventing such errors.
- Fix: #16676
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17425)

chore: use Box::leak() to ensure logging guard lives for the program's lifetime

---

src/query/ast/src/parser/expr.rs
src/query/ast/src/parser/token.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/expr.txt
tests/sqllogictests/suites/mode/standalone/explain/aggregate.test
tests/sqllogictests/suites/mode/standalone/explain_native/aggregate.test

- fixes: #16628
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17455)

fix(parser): allow timestamp as a function name

---

src/query/sql/src/executor/physical_plans/physical_table_scan.rs
src/query/sql/src/planner/binder/select.rs
tests/sqllogictests/suites/base/03_common/03_0004_select_order_by.test
tests/sqllogictests/suites/mode/standalone/explain/sort.test

If `order by` contains derived columns, set the `limit` for push down to None, because limit pruner will ignore some blocks, which will lead to incorrect result. Also, if `order by` contains derived columns, do not generate a `RowFetch` plan, because not pushing down the `limit` will make the `RowFetch` optimisation meaningless.
for example, create a table and insert some values to two blocks.
```sql
root@0.0.0.0:48000/default> create table t1(id int);
0 row written in 0.237 sec. Processed 0 row, 0 B (0 row/s, 0 B/s)
root@0.0.0.0:48000/default> insert into t1 select number as id from numbers(10);
┌─────────────────────────┐
│ number of rows inserted │
│          UInt64         │ …
```

fix(query): fix order by derived column with limit return wrong values

---

src/query/ast/src/ast/statements/table.rs
src/query/ast/src/parser/statement.rs
src/query/ast/tests/it/testdata/stmt.txt
src/query/ee/src/attach_table/handler.rs
src/query/ee/tests/it/inverted_index/pruning.rs
src/query/service/src/interpreters/interpreter_table_show_create.rs
src/query/service/src/pipelines/processors/transforms/transform_recursive_cte_source.rs
src/query/service/src/test_kits/fixture.rs
src/query/service/tests/it/sql/planner/optimizer/agg_index_query_rewrite.rs
src/query/service/tests/it/storages/fuse/operations/clustering.rs
src/query/service/tests/it/storages/fuse/pruning.rs
src/query/service/tests/it/storages/fuse/pruning_pipeline.rs
src/query/sql/src/planner/binder/ddl/table.rs
src/query/sql/src/planner/plans/ddl/table.rs
src/query/storages/fuse/src/constants.rs
src/query/storages/fuse/src/fuse_table.rs
tests/suites/5_ee/04_attach_read_only/02_0004_attach_table.result
tests/suites/5_ee/04_attach_read_only/02_0004_attach_table.sh

Allow optionally specifying which columns to include in the 'Attach table' statement.
e.g.
To create a table named `test_tbl` that attaches to the path 's3://databend-toronto/1/556/' and includes only the columns `col1` and `col2`, you can use the following SQL statement:
~~~
ATTACH TABLE `test_tbl`  (col1, col2) 's3://databend-toronto/1/556/';
~~~
------
Suppose the table `base` is being attached:
~~~
create or replace table base(c1 string, c2 string, c3 string, c4 string) ...
~~~
-  Try Including columns which do not exist in the `base` table will fail
e.g.   `attach table attach_tbl (c2, c_not_exist) ....` will fail
- Dropping non-included columns from `base` does not matter
e.g.
~~~
-- …

feat: support specifying columns to include in the "Attach table" statement

---

src/query/config/src/mask.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17467)

fix(query): spill config should be mask

---

src/query/functions/src/scalars/variant.rs
src/query/functions/tests/it/scalars/testdata/variant.txt
src/query/functions/tests/it/scalars/variant.rs
tests/sqllogictests/suites/query/functions/02_0051_function_semi_structureds_get.test

Variant get string function automatically converts json null to SQL NULL to avoid cast failures caused by null values.
for example:
```sql
root@0.0.0.0:48000/default> select cast(parse_json('{"key1":null}')->>'key1' as integer);
┌───────────────────────────────────────────────────────┐
│ CAST(parse_json('{"key1":null}') ->> 'key1' AS Int32) │
│                    Nullable(Int32)                    │
├───────────────────────────────────────────────────────┤
│                                                  NULL │
└───────────────────────────────────────────────────────┘
1 row read in 0.024 sec. Processed 1 row, 1 B (41.67 rows/s, 41 B/s)
```
- fixes: #17433
- - - …

fix(query): fix variant get string function auto cast null to SQL NULL

---

src/query/service/src/interpreters/interpreter_metrics.rs

```
11: core::panicking::panic_const::panic_const_sub_overflow
at /rustc/6b6a867ae9eac4e78d041ac4ee84be1072a48cf7/library/core/src/panicking.rs:182:21
12: databend_query::interpreters::interpreter_metrics::InterpreterMetrics::record_query_detail
at /home/coldwater/Projects/github.com/databendlabs/databend/src/query/service/src/interpreters/interpreter_metrics.rs:52:33
13: databend_query::interpreters::interpreter_metrics::InterpreterMetrics::record_query_finished
at /home/coldwater/Projects/github.com/databendlabs/databend/src/query/service/src/interpreters/interpreter_metrics.rs:120:9
```
- - - …

fix: InterpreterMetrics could subtract with overflow

---

src/query/service/src/interpreters/interpreter_copy_into_table.rs
src/query/service/src/interpreters/interpreter_replace.rs
tests/suites/5_ee/04_attach_read_only/02_0005_attach_table_read_only.result
tests/suites/5_ee/04_attach_read_only/02_0005_attach_table_read_only.sh

Check table mutability in `copy into`:
If table is created with `ATTACH` stmt, copy into it will fail with message like `Modification not permitted: Table 'attach_read_only' is READ ONLY ...`
- fixes: #17479
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17480)

fix: check table mutability in `copy into`

---

src/meta/app/src/storage/storage_params.rs

Add `DEFAULT_DETECT_REGION_TIMEOUT_SEC`, `endpoint` to the error message when s3 region detection:
```
ErrorCode::StorageOther(format!(
"detect region timeout: {}s, endpoint: {}, elapsed: {}",
DEFAULT_DETECT_REGION_TIMEOUT_SEC,
endpoint,
e
))
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17482)

refactor: s3 region auto detect error add timeout/endpoint

---

src/query/catalog/src/catalog/interface.rs
src/query/service/src/catalogs/default/mutable_catalog.rs
src/query/service/src/catalogs/default/session_catalog.rs
src/query/service/tests/it/sql/exec/get_table_bind_test.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/storages/hive/hive/src/hive_catalog.rs
tests/sqllogictests/suites/base/05_ddl/05_0029_ddl_create_catalog.test

If we have a hive catalog, the query will never works:
```
show table status from tpcds_1000; -- fuse engine database
error: APIError: QueryFailed: [1002]disable_table_info_refresh not implemented
```
Root cause is here:
https://github.com/databendlabs/databend/blob/0199277f72264d38657d08544cc89691fd73c383/src/query/catalog/src/catalog/interface.rs#L144-L149
This PR impl the `disable_table_info_refresh ` for hive catalog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17484)

fix: impl hive disable_table_info_refresh for hive to avoid error when show table status from

---

src/query/sql/src/planner/binder/bind_query/bind_select.rs
src/query/sql/src/planner/planner.rs
src/query/sql/src/planner/semantic/aggregate_rewriter.rs
tests/sqllogictests/suites/query/pivot.test

- fixes: #16557
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17483)

fix(binder): AggregateRewriter should skip the rewrite of Pivot.aggregate

---

src/query/ee/src/storages/fuse/operations/vacuum_temporary_files.rs

- Restructure log messages for better readability and consistency
- Add clear labels for vacuum methods (by meta file/by list dir)
- Standardize progress information format across different vacuum operations"
old:
```
Total progress: {} files removed, now vacuum removed {} temp files from meta: {}(elapsed: {} seconds)
```
now:
```
Vacuum temporary files progress(by meta file): Total removed: {}, Current batch: {} (from '{}'), Dir: '{}', Time: {} sec
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17494)

chore: add more log info(like temp dir) for the vacuum temp files hook

---

src/query/ast/src/ast/quote.rs
src/query/ast/src/ast/statements/table.rs
src/query/ast/src/parser/statement.rs
src/query/ast/src/parser/token.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/stmt.txt
src/query/expression/src/utils/display.rs
src/query/service/src/interpreters/interpreter_dictionary_show_create.rs
src/query/service/src/interpreters/interpreter_table_show_create.rs
src/query/service/src/servers/admin/v1/tenant_tables.rs
src/query/sql/src/planner/binder/copy_into_location.rs
src/query/sql/src/planner/binder/ddl/table.rs
src/query/sql/src/planner/plans/ddl/table.rs
tests/sqllogictests/suites/base/06_show/06_0001_show_create_table.test

https://github.com/databendlabs/databend/issues/17256
```shell
CREATE TABLE `t1`(a int not null, b int not null, c int not null) bloom_index_columns='a,b,c' COMPRESSION='zstd' STORAGE_FORMAT='native';
SHOW CREATE TABLE `t1` WITH QUOTED_IDENTIFIERS
*************************** 1. row ***************************
Table: t1
Create Table: CREATE TABLE "t1" (
"a" INT NOT NULL,
"b" INT NOT NULL,
"c" INT NOT NULL
) ENGINE=FUSE
1 row showcreate in 0.053 sec. Processed 0 row, 0 B (0 row/s, 0 B/s)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17505)

feat: `SHOW CREATE TABLE` add quote for ident

---

src/query/ee/src/attach_table/handler.rs
src/query/service/src/interpreters/interpreter_table_add_column.rs
src/query/service/src/interpreters/interpreter_table_drop_column.rs
src/query/service/src/test_kits/check.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/storages/fuse/src/constants.rs
src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/io/locations.rs
src/query/storages/fuse/src/operations/commit.rs
src/query/storages/fuse/src/operations/mod.rs
src/query/storages/fuse/src/operations/revert.rs
src/query/storages/fuse/src/operations/snapshot_hint.rs
tests/suites/5_ee/04_attach_read_only/04_0007_attach_table_entity_comment.result
tests/suites/5_ee/04_attach_read_only/04_0007_attach_table_entity_comment.sh

Adjust the format of the snapshot hint file so that during the `attach table` process, the comment information of the attached table and fields can be retrieved.
- **Adjustment to the snapshot hint file format**  
A new version of the hint file format is introduced. In this new version, not only is the path to the latest snapshot recorded, but the comments for tables and fields are also included.  
The new version of the hint file is named `last_snapshot_location_hint_v2` and is serialized in JSON format.  
- **Adjustment to the `attach table` implementation**  
During the process of attaching the target table, the system will prioritize detecting and using the new version of the hint file. If …

feat: (semi-)sync table/field comments  with  the table being attached

---

Cargo.lock
Cargo.toml

Bump raft-log crate version to 0.2.7
Features:
- Reuse last healthy closed chunk when reopening raft-log;
In order to avoid too many chunk if it reopen too many times.
- Add compatibility test for raft log format v0.2.6
- Generate sample data for current version
- Verify reading existing v0.2.6 data
- Validate file contents and naming consistency
raft-log crate changes: https://github.com/drmingdrmer/raft-log/compare/v0.2.6...v0.2.7
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17510)

feat(raft-log): enhance raft-log reliability and add compatibility tests

---

src/query/catalog/src/plan/datasource/datasource_info/stage.rs
src/query/catalog/src/plan/datasource/datasource_plan.rs
src/query/catalog/src/plan/internal_column.rs
src/query/expression/src/schema.rs
src/query/service/src/interpreters/interpreter_copy_into_location.rs
src/query/service/src/pipelines/builders/builder_recluster.rs
src/query/service/src/sessions/query_ctx.rs
src/query/sql/src/executor/table_read_plan.rs
src/query/sql/src/planner/binder/copy_into_table.rs
src/query/sql/src/planner/binder/internal_column_factory.rs
src/query/storages/fuse/src/operations/read_data.rs
src/query/storages/stage/src/read/load_context.rs
src/query/storages/stage/src/read/row_based/format.rs
src/query/storages/stage/src/read/row_based/formats/csv/block_builder.rs
src/query/storages/stage/src/read/row_based/formats/ndjson/block_builder.rs
src/query/storages/stage/src/read/row_based/formats/tsv/block_builder.rs
src/query/storages/stage/src/read/row_based/processors/block_builder.rs
src/query/storages/stage/src/read/row_based/read_pipeline.rs
src/query/storages/stage/src/stage_table.rs
tests/sqllogictests/scripts/prepare_stage.sh
tests/sqllogictests/suites/stage/formats/csv/csv_metadata.test
tests/sqllogictests/suites/stage/formats/ndjson/ndjson_metadata.test
tests/sqllogictests/suites/stage/formats/tsv/tsv_metadata.test

this pr only add support of  `metadata$filename` and  `metadata$file_row_number` for csv/tsv/ndjson
e.g. 
```
select metadata$filename, $1, metadata$file_row_number  from @data_s3/ndjson/ts.ndjson (file_format=>'ndjson')
create or replace table t(file_name string, c2 string,  row int, c1 int)
copy into t from (select metadata$filename, $2, metadata$file_row_number + 1, $1 from @data_s3/tsv/no_newline.tsv) file_format=(type=tsv)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17512)

feat: csv/tsv/ndjson support querying file meta data.

---

src/query/storages/common/table_meta/src/table/table_prefix.rs
src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/operations/snapshot_hint.rs
src/query/storages/fuse/src/table_functions/fuse_time_travel_size.rs

Refining some `fuse_time_travel_size` related logs, tracking the name of db/table being processed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17515)

chore: refine some fuse_time_travel_size related logs

---

src/query/service/src/interpreters/interpreter_table_modify_column.rs
src/query/service/src/interpreters/interpreter_table_modify_comment.rs
src/query/service/src/interpreters/interpreter_table_rename_column.rs
tests/suites/5_ee/04_attach_read_only/02_0004_attach_table.result
tests/suites/5_ee/04_attach_read_only/02_0004_attach_table.sh
tests/suites/5_ee/04_attach_read_only/04_0007_attach_table_entity_comment.result
tests/suites/5_ee/04_attach_read_only/04_0007_attach_table_entity_comment.sh

Re-generates last-snapshot-hint file during the following `alter table` operations:
- alter table rename column
- alter table modify table / column comments
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17511)

refactor: re-generate hint file after alter table operations

---

src/query/service/tests/it/parquet_rs/prune_row_groups.rs
src/query/storages/delta/src/table.rs
src/query/storages/hive/hive/src/hive_table.rs
src/query/storages/parquet/src/parquet_rs/copy_into_table/table.rs
src/query/storages/parquet/src/parquet_rs/parquet_reader/reader/builder.rs
src/query/storages/parquet/src/parquet_rs/parquet_reader/reader/full_reader.rs
src/query/storages/parquet/src/parquet_rs/parquet_table/partition.rs
src/query/storages/parquet/src/parquet_rs/parquet_table/read.rs
src/query/storages/parquet/src/parquet_rs/parquet_table/table.rs
src/query/storages/parquet/src/parquet_rs/partition.rs
src/query/storages/parquet/src/parquet_rs/pruning.rs
src/query/storages/parquet/src/parquet_rs/source.rs
src/query/storages/result_cache/src/table_function/table.rs
tests/sqllogictests/suites/stage/formats/parquet/parquet_metadata.test

continuation of https://github.com/databendlabs/databend/pull/17512
limited by the interface of arrow parquet reader, if filter is used,  we cannot get the `file_row_number`.
so this pr simply abandoned the filter and topk pushdown when the `file_row_number` is queried.
but the filter of rowgroup partitions still work.
this does not affect copy  since filter and topk is not allowed in copy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17527)

feat: support query metadata from parquet.

---

src/query/sql/src/planner/binder/binder.rs
src/query/sql/src/planner/binder/ddl/account.rs
src/query/sql/src/planner/binder/util.rs
tests/sqllogictests/suites/base/05_ddl/05_0004_ddl_create_user.test
tests/sqllogictests/suites/base/05_ddl/05_0014_ddl_create_role.test

Not support:
```sql
create user/role 'a\b';
create user/role 'a\f';
```
Because \b and \f will be rewrite as \u{0008} and \u{000C}.
The show result will be strange.
in  main:
```sql
:)  create role  'a"b';
error: APIError: QueryFailed: [2217]Illegal Role Name: Illegal role name [a"b], not support username contain ' or "
:)  create role  "a'b";
error: APIError: QueryFailed: [2217]Illegal Role Name: Illegal role name [a'b], not support username contain ' or "
:)  create user  "a'b" identified by '123';
error: APIError: QueryFailed: [2218]Illegal Username: Illegal user name [a'b], not support username contain ' or "
:)  create user  'a"b' identified by '123';
error: APIError: QueryFailed: …
```

fix(query): user/role name not support \b and \f

---

src/meta/raft-store/src/leveled_store/leveled_map/map_api_impl.rs
src/meta/raft-store/src/leveled_store/map_api.rs
src/meta/raft-store/src/marked/marked_test.rs
src/meta/raft-store/src/marked/mod.rs
src/meta/raft-store/src/marked/seq_tombstone.rs
src/meta/raft-store/src/state_machine_api_ext.rs
src/meta/types/src/eval_expire_time.rs
src/meta/types/src/lib.rs
src/meta/types/src/seq_value/kv_meta.rs
src/meta/types/src/seq_value/seq_value_trait.rs

This change renames the `EvalExpireTime` trait to `Expirable` and its method
`eval_expire_at_ms()` to `expiry_ms()` for improved clarity and consistency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17540)

chore: rename `EvalExpireTime` to `Expirable` for better semantics

---

src/query/service/src/table_functions/show_grants/show_grants_table.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
tests/sqllogictests/suites/base/06_show/06_0007_show_roles.test

1. add new setting enable_expand_roles (enable by default)
2. Supports the folding of show grants results for roles and users
3. modify table function show_grants's field grants type. Nullable(String) -> String
e.g.
```sql
drop role if exists a;
drop role if exists b;
drop user if exists a;
create user a identified by '123';
create or replace table t(id int);
create role a;
grant ownership on default.t to role a;
grant select on default.t to role a;
grant insert on *.* to role a;
create or replace table t1(id int);
create role b;
grant ownership on default.t1 to role b;
grant select on *.* to role b;
grant role b to role a;
grant role a to a;
grant create database on *.* to a;
```
In default …

feat(query): Supports folding of show grants results for roles and users

---

src/meta/raft-store/src/leveled_store/db_map_api_ro_impl.rs
src/meta/raft-store/src/leveled_store/db_map_api_ro_test.rs
src/meta/raft-store/src/leveled_store/immutable.rs
src/meta/raft-store/src/leveled_store/immutable_levels.rs
src/meta/raft-store/src/leveled_store/key_spaces_impl.rs
src/meta/raft-store/src/leveled_store/level.rs
src/meta/raft-store/src/leveled_store/leveled_map/leveled_map_test.rs
src/meta/raft-store/src/leveled_store/leveled_map/map_api_impl.rs
src/meta/raft-store/src/leveled_store/map_api.rs
src/meta/raft-store/src/leveled_store/map_api/map_api_ro_impl.rs
src/meta/raft-store/src/leveled_store/rotbl_codec.rs
src/meta/raft-store/src/mem_meta.rs
src/meta/raft-store/src/sm_v003/compact_with_db_test.rs
src/meta/raft-store/src/sm_v003/sm_v003_kv_api.rs
src/meta/raft-store/src/sm_v003/sm_v003_test.rs
src/meta/raft-store/src/state_machine_api_ext.rs
src/meta/types/src/eval_expire_time.rs
src/meta/types/src/seq_value/kv_meta.rs
src/meta/types/src/seq_value/seq_value_trait.rs

This commit refactors the handling of map keys and their encoding/decoding:
- **`MapKey` Trait**:
The `MapKey` trait, which already existed, now strictly defines the
behavior of a map key without requiring codec-related logic.
- **New Traits**:
Introduced `MapKeyEncode` and `MapKeyDecode` traits to encapsulate
encoding and decoding behavior separately from the `MapKey` trait.
- Refactored `MapApiRO` and `MapApi` traits:
- These traits no longer depend on encoding/decoding logic, focusing
solely on map key behavior.
- Removed `K: Borrow<Q>` from the `get<Q>()` method:
- While `Q` was intended to allow flexible borrowing (e.g., `&str` as
a borrowed type of `String`), it added unnecessary …

refactor(meta): simplify map key handling and improve naming consistency

---

src/query/sql/src/planner/optimizer/decorrelate/decorrelate.rs
src/query/sql/src/planner/optimizer/decorrelate/flatten_plan.rs
tests/sqllogictests/suites/query/subquery.test

- fixes: https://github.com/databendlabs/databend/issues/17476
```sql
insert into t1 values (0);
insert into t2 values (0);
SELECT 1 FROM t1
WHERE t1.i1 = (
SELECT t1.i1
FROM t2 UNION
SELECT dt1.i1
FROM (t1 AS dt1)
);
┌───────┐
│   1   │
│ UInt8 │
├───────┤
│     1 │
└───────┘
explain SELECT 1 FROM t1
WHERE t1.i1 = (
SELECT t1.i1
FROM t2 UNION
SELECT dt1.i1
FROM (t1 AS dt1)
);
EvalScalar
├── output columns: [1 (#4)]
├── expressions: [1]
├── estimated rows: 2.00
└── HashJoin
├── output columns: []
├── join type: INNER
├── build keys: [t1.i1 (#0)]
├── probe keys: [scalar_subquery_3 (#3)]
├── keys is null equal: [false]
├── filters: []
├── estimated …
```

fix: agg input does not match union output when subquery

---

src/query/service/src/pipelines/processors/transforms/transform_recursive_cte_source.rs
src/query/sql/src/planner/binder/bind_query/bind.rs
src/query/sql/src/planner/binder/bind_query/bind_set_expr.rs
src/query/sql/src/planner/binder/select.rs
tests/sqllogictests/suites/query/cte/cte.test

- fixes: https://github.com/databendlabs/databend/issues/17295
```sql
WITH RECURSIVE
closure(x) AS (VALUES(1)
UNION all SELECT a from t1, closure where t1.a = closure.x
UNION all SELECT a from t2, closure where t2.a = closure.x
) SELECT x FROM closure;
┌────────┐
│    x   │
│ UInt64 │
├────────┤
│      1 │
└────────┘
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17554)

fix: with recursive bind table panic

---

src/common/storage/src/stage.rs
src/query/service/src/pipelines/builders/builder_copy_into_table.rs
src/query/service/src/table_functions/list_stage/list_stage_table.rs
src/query/storages/parquet/src/parquet_rs/meta.rs
src/query/storages/parquet/src/parquet_rs/parquet_table/partition.rs
src/query/storages/parquet/src/parquet_rs/parquet_table/table.rs
tests/suites/1_stateful/00_stage/00_0010_parquet_meta_cache.result
tests/suites/1_stateful/00_stage/00_0010_parquet_meta_cache.sh

1. copy from parquet disable cache
2. select from parquet add dedup_key (md5 or mtime or query id) into cache key 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17556)

fix: parquet meta cache key include md5 or mtime or query_id.

---

src/meta/raft-store/src/applier.rs
src/meta/raft-store/src/state_machine_api.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/meta_service/meta_node.rs
src/meta/service/src/watcher/dispatch/command.rs
src/meta/service/src/watcher/dispatch/dispatcher.rs
src/meta/service/src/watcher/dispatch/dispatcher_handle.rs
src/meta/service/src/watcher/dispatch/mod.rs
src/meta/service/src/watcher/watch_stream/mod.rs
src/meta/service/src/watcher/watch_stream/sender.rs
src/meta/service/src/watcher/watch_stream/stream.rs
src/meta/service/tests/it/grpc/metasrv_grpc_watch.rs
src/meta/types/src/proto_ext/watch_ext.rs

- Split watcher module into three main components:
- Dispatcher: receives and dispatches events to watchers
- Stream: handles sending events to clients
- Data types: defines core structures and interfaces
- Reduce dependency on `databend_common_meta_types` crate, to make it
easier to become a standalone crate.
- Introduce dedicated `Update` struct for key-value events
- Refine doc for StateMachineApi
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17557)

chore: reorganize meta service watcher module

---

src/query/sql/src/planner/optimizer/optimizer.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0045_merge_into_issue_16581.test

A query like `SELECT * FROM (VALUES ('1', 'add', '11'))` will be optimized into a ConstantTableScan, which may further lead to the UPDATE being optimized into a DELETE by the optimizer.
This PR makes the optimization rule more precise, only rewriting merge into with an empty ConstantScan to delete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17571)

fix: The update in MERGE INTO was mistakenly optimized as a delete

---

src/query/functions/src/aggregates/aggregate_string_agg.rs
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/functions/02_0000_function_aggregate_mix.test

`string_agg` will convert argment if it is not of `DataType::String`
```sql
create table t3(x int null, b boolean null);
insert into t3 values
(3, true),
(2, false),
(1, null),
(0, true);
select string_agg(x + 1, '|') from t3;
----
4|3|2|1
select string_agg(b, '|') from t3;
----
true|false|true
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17570)

feat: `string_agg` is compatible with multiple types as arguments instead of just String

---

Cargo.lock
src/common/io/src/constants.rs
src/query/ee/src/storages/fuse/operations/handler.rs
src/query/ee/src/storages/fuse/operations/vacuum_table.rs
src/query/ee/src/storages/fuse/operations/vacuum_table_v2.rs
src/query/ee_features/vacuum_handler/Cargo.toml
src/query/ee_features/vacuum_handler/src/vacuum_handler.rs
src/query/service/src/interpreters/common/table_option_validation.rs
src/query/service/src/sessions/query_ctx.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
src/query/storages/fuse/Cargo.toml
src/query/storages/fuse/src/operations/common/processors/sink_commit.rs
tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables.test
tests/sqllogictests/suites/ee/03_ee_vacuum/03_0003_vacuum2.test
tests/sqllogictests/suites/ee/03_ee_vacuum/03_0004_auto_vacuum.test
tests/sqllogictests/suites/ee/03_ee_vacuum/03_0005_vacuum_transient.test

- **Purpose**: When enabled, automatically vacuums historical table objects (metadata and data) based on retention period settings immediately after a new table version is committed.
- **Behavior**: Operates on a best-effort basis—vacuum errors, if any, are ignored.
- **Default**: Disabled.
- **Example**:
```sql
SET enable_auto_vacuum = 1;
-- After this insert commits, historical data in table 't' is vacuumed per retention settings.
INSERT INTO t VALUES (...);
Notes:
- Only functional in auto-commit mode. Support for explicit transactions will be added later.
- Retention period considerations:
Small retention periods are safe but may impact dependent features
- Streams relying on historical …
```

feat: auto vacuum

---

src/common/io/src/constants.rs
src/query/catalog/src/plan/partition.rs
src/query/catalog/src/table.rs
src/query/ee/src/hilbert_clustering/handler.rs
src/query/expression/src/utils/block_thresholds.rs
src/query/pipeline/transforms/src/processors/transforms/transform_compact_builder.rs
src/query/pipeline/transforms/src/processors/transforms/transform_compact_no_split_builder.rs
src/query/service/src/interpreters/common/table_option_validation.rs
src/query/service/src/pipelines/builders/builder_recluster.rs
src/query/service/tests/it/storages/fuse/operations/mutation/block_compact_mutator.rs
src/query/service/tests/it/storages/fuse/operations/mutation/recluster_mutator.rs
src/query/service/tests/it/storages/fuse/operations/mutation/segments_compact_mutator.rs
src/query/service/tests/it/storages/fuse/statistics.rs
src/query/storages/common/table_meta/src/meta/utils.rs
src/query/storages/fuse/src/constants.rs
src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/io/read/meta/meta_readers.rs
src/query/storages/fuse/src/io/write/write_settings.rs
src/query/storages/fuse/src/operations/common/processors/transform_mutation_aggregator.rs
src/query/storages/fuse/src/operations/common/processors/transform_serialize_segment.rs
src/query/storages/fuse/src/operations/compact.rs
src/query/storages/fuse/src/operations/mutation/mutator/block_compact_mutator.rs
src/query/storages/fuse/src/operations/mutation/mutator/recluster_mutator.rs
src/query/storages/fuse/src/operations/mutation/processors/compact_source.rs
src/query/storages/fuse/src/operations/recluster.rs
src/query/storages/fuse/src/statistics/reducers.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0008_fuse_optimize_table.test

Introduces a new option, `file_size`, which allows to specify the desired size of Parquet files when blocks are written. The default value is set to `10M`. This option is primarily used during the `recluster` operation to control the size of the resulting blocks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17580)

chore(storage): add block file size

---

src/common/storage/src/stage.rs

when query from parquet files, we use a in memory cache for metadata of parquet files.
the original implementation only use file path as key of cache, which may leads to error when file is overwritten （read the metadata of the old file ）.
recently,  I fixed it by using `(path, content_md5/mtime )` as key.
this pr fix the key again: 
1. remove mtime,   because the accuracy of last_modified  is in seconds for S3, not enough to distinguish 2 files.
2. add etag, because in opendal the `content_md5()` is not always set to etag when etag exists.
- - - …

fix: parquet meta cache key should not use mtime.

---

src/query/sql/src/executor/physical_plans/physical_union_all.rs
src/query/sql/src/planner/binder/util.rs
tests/sqllogictests/suites/query/cte/cte.test

- fixes: https://github.com/databendlabs/databend/issues/17432
```sql
CREATE OR REPLACE TABLE some_table (
id INTEGER NOT NULL,
"data" VARCHAR(50),
parent_id INTEGER
);
INSERT INTO some_table (id, "data", parent_id) VALUES  (1, 'd1', NULL),(2, 'd2', 1),(3, 'd3', 1),(4, 'd4', 3),(5, 'd5', 3);
WITH RECURSIVE some_cte(id, "data", parent_id) AS
(SELECT some_table.id AS id, some_table."data" AS "data", some_table.parent_id AS parent_id
FROM some_table
WHERE some_table."data" IN ('d2', 'd3', 'd4') UNION ALL SELECT some_table_1.id AS id, some_table_1."data" AS "data", some_table_1.parent_id AS parent_id
FROM some_table AS some_table_1, some_cte AS c1
WHERE some_table_1.id = c1.parent_id)
SELECT …
```

fix: the output columns of cte related columns lack the columns required by cte itself

---

Cargo.lock
Cargo.toml
src/meta/control/src/import.rs
src/meta/raft-store/src/sm_v003/compact_immutable_levels_test.rs
src/meta/raft-store/src/sm_v003/compact_with_db_test.rs
src/meta/raft-store/src/sm_v003/sm_v003.rs
src/meta/raft-store/src/state_machine/testing.rs
src/meta/service/src/meta_service/meta_node.rs
src/meta/service/src/meta_service/raft_service_impl.rs
src/meta/service/src/store/raft_log_storage_impl.rs
src/meta/service/src/store/raft_state_machine_impl.rs
src/meta/service/src/store/store_inner.rs
src/meta/service/tests/it/store.rs
src/meta/types/src/proto_ext/raft_types_ext.rs
src/meta/types/src/raft_types.rs

Major changes since v0.10.0-alpha.7 to v0.10.0-alpha.9 :
- Added:
-   [9178ef8f](https://github.com/databendlabs/openraft/commit/9178ef8f1d49de0c85fb835d559d53c5876b2c64) Retrieve Key Log IDs via `RaftLogReader::get_key_log_ids()`.
-   [636664de](https://github.com/databendlabs/openraft/commit/636664dec5fda5b396b7a366801e7a02f1e23225) Abstract Term.
-   [d1bd8a24](https://github.com/databendlabs/openraft/commit/d1bd8a24bb9c7578a247c3738a2966d99b8cb783) Abstract `LeaderId` and `CommittedLeaderId`.
-   [a7899729](https://github.com/databendlabs/openraft/commit/a7899729d9658171b48dffd4f4ba96382d28cd62) Abstract `Vote`.
-   [c6a01749](https://github.com/databendlabs/openraft/commit/c6a0174986ea8c03 …

refactor(meta): upgrade OpenRaft to v0.10.0-alpha.9

---

Cargo.lock
Cargo.toml
src/common/native/tests/it/native/io.rs
src/query/expression/src/types/variant.rs
src/query/expression/src/utils/display.rs
src/query/expression/src/utils/variant_transform.rs
src/query/expression/src/values.rs
src/query/expression/tests/it/row.rs
src/query/formats/src/field_encoder/json.rs
src/query/formats/src/field_encoder/values.rs
src/query/functions/src/aggregates/aggregate_json_array_agg.rs
src/query/functions/src/aggregates/aggregate_json_object_agg.rs
src/query/functions/src/scalars/comparison.rs
src/query/functions/src/scalars/geographic/src/geometry.rs
src/query/functions/src/scalars/variant.rs
src/query/functions/src/srfs/variant.rs
src/query/pipeline/transforms/src/processors/transforms/sort/rows/common.rs
src/query/storages/common/index/src/bloom_index.rs
src/query/storages/fuse/src/io/write/inverted_index_writer.rs
src/tests/sqlsmith/src/sql_gen/expr.rs

This PR introduces a significant refactoring of Databend's JSON processing functions. The primary changes of this refactoring are to:
**Key Changes**
*   **Enhance Code Maintainability:**  Transition from using raw `&[u8]` byte slices to the `RawJsonb` struct for representing JSONB data. This provides a more structured and type-safe approach, improving code readability and reducing the risk of errors.
*   **Refactoring of Existing Functions:**  Existing JSON functions have been refactored to work seamlessly with the `RawJsonb` struct. This ensures that existing functionality is preserved while taking advantage of the new data representation.
*   **Unlock Future Optimizations:**  The `RawJsonb` …

refactor(query): refactor json functions

---

src/query/service/src/servers/http/middleware/mod.rs
src/query/service/src/servers/http/middleware/session.rs
src/query/service/src/servers/http/v1/http_query_handlers.rs
src/query/service/src/servers/http/v1/query/http_query.rs
src/query/service/src/servers/http/v1/query/http_query_manager.rs
tests/suites/1_stateful/09_http_handler/09_0010_heartbeat.py
tests/suites/1_stateful/09_http_handler/09_0010_heartbeat.result

Each query and its result will be cleared when there is no data pulling request within a certain period of time. However, the data pulling request depends on the consumption of the client users. If there is a long interval in consumption, an unexpected timeout error will be received. 
this pr extend heartbeat api to keep alive of the query result
1. query return `result_timeout` in response.
2. client is expected to send heartbeat request (in background) when it is about to timeout.
-  before that, client should check the version of server to make sure heartbeat is supported. 
3.  heartbeat for queries can be batched, and are grouped by node_id,  the server receiving  HB from client is …

feat: heartbeat to avoid query result timeout. 

---

src/query/expression/src/block.rs
src/query/expression/src/values.rs
src/query/expression/tests/it/kernel.rs
src/query/pipeline/transforms/src/processors/transforms/transform_compact_builder.rs
src/query/pipeline/transforms/src/processors/transforms/transform_compact_no_split_builder.rs
src/query/service/src/pipelines/processors/transforms/window/partition/data_processor_strategy.rs
src/query/service/src/test_kits/fixture.rs
src/query/service/src/test_kits/fuse.rs
src/query/storages/common/index/src/bloom_index.rs
src/query/storages/fuse/src/io/write/block_writer.rs
tests/sqllogictests/scripts/prepare_iceberg_tpch_data.py
tests/sqllogictests/suites/base/09_fuse_engine/09_0006_func_fuse_history.test
tests/suites/1_stateful/09_http_handler/09_0010_heartbeat.py
tests/suites/5_ee/01_vacuum/01_0002_ee_vacuum_drop_table.sh
tests/suites/5_ee/01_vacuum/01_003_vacuum_table_only_orphans.result
tests/suites/5_ee/01_vacuum/01_003_vacuum_table_only_orphans.sh

1. optimization to the Bloom index construction process. Specifically, it skips building a Bloom index for columns that contain only a single unique value or are entirely composed of NULL values. Because we donot need to generate bloom index, it will never be used since range index is checked first.
2. Calculate the block's memory without convert to full column.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17625)

chore: optimize building bloom index for null

---

src/query/functions/src/scalars/variant.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/functions/tests/it/scalars/testdata/variant.txt
src/query/functions/tests/it/scalars/variant.rs
tests/sqllogictests/suites/query/functions/02_0065_function_json.test

close https://github.com/databendlabs/databend/issues/17627
```sql
-- Create a simple table with JSON data
CREATE TABLE users (user_data VARIANT);
-- Insert two records: one with a null phone number, one with a value
INSERT INTO users 
SELECT PARSE_JSON('{"name": "Alice", "phone": null}');
INSERT INTO users 
SELECT PARSE_JSON('{"name": "Bob", "phone": "555-1234"}');
-- Compare regular access vs using STRIP_NULL_VALUE
SELECT 
user_data:name AS name,
user_data:phone AS original_phone,      -- JSON null appears as 'null'
STRIP_NULL_VALUE(user_data:phone) AS phone_number  -- Converts JSON null to SQL NULL
FROM users;
-- Result:
-- +----------+----------------+--------------+
-- | NAME     | …
```

feat: impl function `strip_null_value` for Variant

---

src/query/storages/common/cache/benches/read_cache_content.rs
src/query/storages/common/cache/src/providers/disk_cache/disk_cache_lru.rs

Disk cache failed to build on macOS.
No `O_NOATIME` on macOS, let's focus on Linux for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17643)

fix: disk cache failed to build on macOS

---

src/query/expression/src/values.rs
src/query/service/src/interpreters/interpreter_table_modify_column.rs
tests/suites/0_stateless/17_altertable/17_0005_alter_table_modify_column_type.result
tests/suites/0_stateless/17_altertable/17_0005_alter_table_modify_column_type.sh

1. fix modify column data type null to not null failed, using `remove_nullable` function to remove null value from the original column.
2. nullable random column values remove unused underlaying values.
- fixes: https://github.com/databendlabs/databend/issues/17648
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17650)

fix(ddl): fix modify column data type null to not null failed

---

Cargo.lock
src/query/functions/src/scalars/timestamp/Cargo.toml
src/query/functions/src/scalars/timestamp/src/datetime.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test

in main :
set timezone='Asia/Shanghai'
select to_date('9999-12-31', '%Y-%m-%d') will return error.
Because jiff crate in Asia/Shanghai only support Max timestamp 9999-12-30 16:00:00
And this function append time part combain a new datetime.
In pr: backport to chrono crate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17652)

fix(query): to_date(9999-12-31, format_string) should success

---

src/common/io/src/constants.rs
src/query/catalog/src/table.rs
src/query/expression/src/utils/block_thresholds.rs
src/query/expression/tests/it/block.rs
src/query/expression/tests/it/block_thresholds.rs
src/query/expression/tests/it/main.rs
src/query/pipeline/transforms/src/processors/transforms/transform_compact_builder.rs
src/query/service/src/interpreters/common/table_option_validation.rs
src/query/service/src/interpreters/interpreter_table_recluster.rs
src/query/service/src/pipelines/builders/builder_hilbert_partition.rs
src/query/service/src/pipelines/builders/builder_recluster.rs
src/query/service/src/pipelines/processors/transforms/window/partition/data_processor_strategy.rs
src/query/service/tests/it/storages/fuse/operations/mutation/block_compact_mutator.rs
src/query/service/tests/it/storages/fuse/operations/mutation/recluster_mutator.rs
src/query/service/tests/it/storages/fuse/statistics.rs
src/query/sql/src/executor/physical_plans/physical_recluster.rs
src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/operations/mutation/mutator/block_compact_mutator.rs
src/query/storages/fuse/src/operations/mutation/mutator/recluster_mutator.rs
src/query/storages/stage/src/read/block_builder_state.rs
src/query/storages/stage/src/read/row_based/processors/block_builder.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0008_fuse_optimize_table.test
tests/sqllogictests/suites/base/09_fuse_engine/09_0011_change_tracking.test

1. **Dynamically calculate optimal rows per block**  
Introduced logic to compute the optimal number of rows per block based on total data size, row count, and compressed size. This ensures that generated blocks meet both performance and storage efficiency thresholds.
2. **Fix potential fragmentation in Hilbert recluster**  
Resolved an issue where Hilbert-based reclustering could result in fragmented small blocks, affecting downstream compaction and performance.
3. **Enable effective compaction after modifying `block_size_thresholds`**  
Adjustments to `BlockThresholds` now properly propagate into the block compaction logic, ensuring compact operations behave as expected after threshold …

chore: calc rows per block for recluster

---

src/query/service/src/interpreters/access/management_mode_access.rs
src/query/service/src/interpreters/interpreter_explain.rs
src/query/service/tests/it/sql/planner/optimizer/data/yaml/q1.yaml
src/query/service/tests/it/sql/planner/optimizer/data/yaml/q3.yaml
src/query/service/tests/it/sql/planner/optimizer/tpcds_test.rs
src/query/sql/src/lib.rs
src/query/sql/src/planner/format/display.rs
src/query/sql/src/planner/format/display_plan.rs
src/query/sql/src/planner/format/display_rel_operator.rs
src/query/sql/src/planner/format/mod.rs
src/query/sql/src/planner/mod.rs
src/query/sql/src/planner/plans/insert.rs
src/query/sql/src/planner/plans/replace.rs
tests/sqllogictests/suites/mode/cluster/explain_v2.test
tests/sqllogictests/suites/mode/standalone/explain/explain.test
tests/sqllogictests/suites/mode/standalone/explain/explain_sequence.test
tests/sqllogictests/suites/mode/standalone/explain/explain_verbose.test
tests/sqllogictests/suites/mode/standalone/explain/insert.test
tests/sqllogictests/suites/mode/standalone/explain/subquery.test
tests/sqllogictests/suites/mode/standalone/explain/table_sample.test
tests/sqllogictests/suites/mode/standalone/explain/window.test
tests/sqllogictests/suites/mode/standalone/explain_native/explain.test

```
explain(verbose) optimized select date from (select *, 'year' as date from t1 left join t2 on t1.a = t2.b) where date = '';
EvalScalar
├── scalars: [t1.a (#0) AS (#0), t2.b (#1) AS (#1), 'year' AS (#2)]
├── output columns: [default.t1.a (#0), default.t2.b (#1), derived.date (#2)]
├── outer columns: []
├── used columns: [default.t1.a (#0), default.t2.b (#1), derived.date (#2)]
├── cardinality: 0.000
├── precise cardinality: N/A
├── statistics
└── Join(Left)
├── build keys: [t2.b (#1)]
├── probe keys: [t1.a (#0)]
├── other filters: []
├── output columns: [default.t1.a (#0), default.t2.b (#1)]
├── outer columns: []
├── used columns: [default.t1.a (#0), default.t2.b (#1)]
├── cardinality: …
```

chore: missing column index for output columns in explain verbose

---

src/meta/app/src/principal/file_format.rs
src/meta/proto-conv/src/file_format_from_to_protobuf_impl.rs
src/meta/proto-conv/src/util.rs
src/meta/proto-conv/tests/it/main.rs
src/meta/proto-conv/tests/it/v032_file_format_params.rs
src/meta/proto-conv/tests/it/v066_stage_create_on.rs
src/meta/proto-conv/tests/it/v093_parquet_format_params.rs
src/meta/proto-conv/tests/it/v123_parquet_format_params.rs
src/meta/protos/proto/file_format.proto
src/query/ast/src/parser/stage.rs
src/query/storages/stage/src/append/parquet_file/writer_processor.rs
tests/sqllogictests/suites/stage/formats/parquet/options/parquet_compression.test
tests/sqllogictests/suites/stage/formats/parquet/options/select_options.test

before this pr，zstd is used for unloading to parquet files.
this pr add a file format option ` compression = zstd | snappy`  to file format parquet.
unlike the `compression` option of other formats(ndjson/csv):
1. it is used only when unloading, instead of both load and unload
2. is it used for compression of internal block of file, instead of the whole file
3. the default is zstd instead of none
for example
```
copy into @data/unload/ from (select * from numbers(3)) file_format=(type = parquet compression=snappy)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/1766 …

feat: support specifying compression when unloading to parquet.

---

.github/workflows/release.yml
docker/service/query.Dockerfile

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17671)

ci: release target with hdfs

---

src/query/functions/src/scalars/string_multi_args.rs
src/query/functions/tests/it/scalars/regexp.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/functions/tests/it/scalars/testdata/regexp.txt
tests/sqllogictests/suites/query/functions/02_0081_function_string_regexp_extract.test

- fixes: https://github.com/databendlabs/databend/issues/17655
```shell
select regexp_extract('foo-bar-baz', '([a-z]+)-([a-z]+)-([a-z]+)', 0)
----
foo-bar-baz
SELECT regexp_extract('hello_world_rust', '(\w+)_([\w]+)_(\w+)', ['part1', 'part2', 'part3']);
----
{"part1": "hello", "part2": "world", "part3": "rust"}
select regexp_extract_all('Order-123-456 Order-789-012', 'Order-(\d+)-(\d+)', 2)
----
["456", "012"]
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17658)

feat: impl function: `regexp_extract` & `regexp_extract_all`

---

src/common/exception/src/exception_into.rs

chore: Always print detailed error from opendal
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17681)

chore: Always print detailed error from opendal

---

src/query/storages/stage/src/append/parquet_file/writer_processor.rs
tests/sqllogictests/suites/stage/formats/parquet/options/parquet_missing_uuid.test
tests/suites/1_stateful/00_stage/00_0005_copy_into_location.result
tests/suites/1_stateful/00_stage/00_0017_copy_into_parquet.sh
tests/suites/1_stateful/00_stage/00_0019_sequence_as_default.result

1.  encoding is not specified, Arrow Parquet will automatically select a suitable encoding for the physical type.
2. enable dictionary encoding, which is the default behavior of Arrow Parquet and generally makes the file smaller.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17688)

chore: use default encoding of parquet columns instead of plain.

---

src/query/sql/src/planner/binder/bind_context.rs
src/query/sql/src/planner/binder/bind_table_reference/bind_join.rs
tests/sqllogictests/suites/mode/standalone/ee/explain_virtual_column.test

Fixed the issue that the existing virtual column was not success fully applied when bind join and eq condition was of variant type
```sql
explain select t1.a, t1.v['b'] from t1 left outer join t2 on t1.v['b'] = t2.a where t1.v['a'][0] = 1;
HashJoin
├── output columns: [t1.a (#0), t1.v['b'] (#4)]
├── join type: RIGHT OUTER
├── build keys: []
├── probe keys: []
├── keys is null equal: []
├── filters: [TRY_CAST(v['b'] (#4) AS Int32 NULL) = t2.a (#2)]
├── estimated rows: 0.00
├── TableScan(Build)
│   ├── table: default.test_virtual_db.t1
│   ├── output columns: [a (#0), v['b'] (#4)]
│   ├── read rows: 1
│   ├── read size: < 1 KiB
│   ├── partitions total: 1
│   ├── partitions scanned: 1
│   ├── …
```

fix(query): fix variant failed to successfully apply virtual column in bind join

---

src/common/tracing/src/lib.rs
src/common/tracing/src/remote_log.rs
src/common/tracing/tests/it/remote_log.rs

follow up: #17598
Add force collect to fix log data loss.
```
root@localhost:8000/default> select * from persistent_system.query_log order by timestamp desc limit 1;
-[ RECORD 1 ]-----------------------------------
timestamp: 2025-04-02 13:11:22.354154
path: databend_query::entry: entry.rs:426
target: databend_query::entry
log_level: INFO
cluster_id: test_cluster
node_id: TR5fixys6tAWEot24JEZ61
warehouse_id: NULL
query_id: NULL
message: Shutdown server.
fields: {}
1 row read in 0.097 sec. Processed 705 row, 5.59 KiB (7.26 thousand row/s, 57.62 KiB/s)
```
- - - …

fix: persistent log table may loss records when shutdown

---

src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/query.txt
src/query/storages/iceberg/src/table.rs
tests/sqllogictests/suites/tpch_iceberg/table_function.test

```sql
select * from lineitem at (timestamp=>'2025-03-12 23:18:22.665000'::Timestamp) limit 1;
select * from lineitem at (snapshot=>'4524280171191816067') limit 1;
```
Note:
If timestamp is less or bigger than min snapshot ts will return error.
If snapshot id is not exists will return error.
Fix: #17563 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17693)

feat(query): support query iceberg table by version

---

src/query/service/tests/it/persistent_log/global_persistent_log.rs

Why flaky: A random time was added to the interval to prevent one node from continuously obtaining the lock, so using a precise interval here might cause flaky tests. Therefore, I added a waiting period to ensure all operations have been completed.
**I rerun this case for 20 times locally, it should be stable now.**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17701)

fix: flaky unit test `test_persistent_log_write`

---

src/query/management/src/role/role_api.rs
src/query/management/src/role/role_mgr.rs
src/query/service/src/interpreters/access/privilege_access.rs
src/query/service/src/interpreters/interpreter_create_warehouses.rs
src/query/service/src/interpreters/interpreter_database_create.rs
src/query/service/src/interpreters/interpreter_drop_warehouses.rs
src/query/service/src/interpreters/interpreter_user_stage_create.rs
src/query/service/src/sessions/session_privilege_mgr.rs
src/query/service/src/table_functions/show_grants/show_grants_table.rs
src/query/storages/system/src/streams_table.rs
src/query/storages/system/src/tables_table.rs
src/query/users/src/role_mgr.rs
src/query/users/src/user_api.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17683)

chore: minor refine on RoleMgr

---

src/common/storage/src/parquet_rs.rs
src/query/storages/orc/src/table.rs

enable user to find the invalid file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17716)

chore: show file path when copy meet invalid parquet file.

---

src/query/storages/common/cache/src/providers/hybrid_cache.rs

fix the following flaky test:
~~~
running 1 test
test providers::hybrid_cache::tests::test_hybrid_cache_evict ... FAILED
failures:
failures:
providers::hybrid_cache::tests::test_hybrid_cache_evict
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 13 filtered out; finished in 0.01s
~~~
In test case `test_hybrid_cache_evict`, we should also wait until the disk cache item being tested stabilized.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17735)

fix: flaky hybrid cache test

---

.github/actions/test_compat_fuse/action.yml
src/meta/app/src/principal/user_privilege.rs
src/query/service/src/interpreters/access/privilege_access.rs
src/query/users/src/visibility_checker.rs
tests/sqllogictests/suites/base/05_ddl/05_0017_ddl_grant_role.test
tests/suites/0_stateless/18_rbac/18_0014_use_db_priv_check.result
tests/suites/0_stateless/18_rbac/18_0014_use_db_priv_check.sh

In this pr usage privileges is a database level privilege.
use Usage privilege optimize USEDB Plan
```sql
grant usage on <db_name>.* to role role1;
grant role1 to u1;
grant role1 to u2;
...
```
the u1,u2... will not list ownerships when execute use <db_name>;
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17679)

chore: use Usage privilege optimize USEDB Plan

---

src/meta/client/src/grpc_client.rs
src/meta/raft-store/src/applier.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/api/grpc_server.rs
src/meta/service/src/meta_service/meta_node.rs
src/meta/service/src/util.rs
src/meta/service/tests/it/grpc/metasrv_grpc_kv_api_restart_cluster.rs
src/meta/service/tests/it/tests/service.rs

MetaServiceImpl is not dropped when there is an alive connection.
Thus it can not hold a Strong reference to MetaNode.
Otherwise when stopping, `MetaNode` is not dropped.
This might prevent releasing other resources held by MetaNode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17743)

refactor: use Weak ref to break cyclic references

---

src/query/storages/fuse/src/table_functions/fuse_time_travel_size.rs

Tested in an environment where the storage backend is S3:
```SQL
select * from fuse_time_travel_size('tpcds_sf100');
```
1.940s -> 0.343s
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17745)

chore: increase the concurrency of fuse_time_travel_size

---

scripts/setup/rust-toolchain.toml

Databend's toolchain is too old to build some new deps.
```shell
error[E0658]: use of unstable library feature `ptr_fn_addr_eq`
--> /home/xuanwo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.24.1/src/internal_tricks.rs:53:9
|
53 |         std::ptr::fn_addr_eq(f, g)
|         ^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #129322 <https://github.com/rust-lang/rust/issues/129322> for more information
= help: add `#![feature(ptr_fn_addr_eq)]` to the crate attributes to enable
= note: this compiler was built on 2024-11-27; consider upgrading it if it is out of date
```
- - - …

chore: Bump rust toolchain

---

src/common/exception/src/exception_backtrace.rs
src/common/grpc/src/dns_resolver.rs
src/common/grpc/src/grpc_token.rs
src/meta/client/src/grpc_client.rs
src/meta/client/src/message.rs
src/meta/client/tests/it/grpc_client.rs
src/meta/service/tests/it/grpc/metasrv_grpc_handshake.rs
src/meta/types/src/errors/meta_client_errors.rs
src/meta/types/src/errors/meta_handshake_errors.rs

`MetaHandshakeError` does not have to contain a source error if its not
caused by other error.
Now `watch()` returns `MetaHandshakeError` if the protocol does support
a watch request.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17755)

refactor(meta-client): Improve `MetaHandshakeError`

---

src/common/license/src/license.rs
src/common/license/src/license_manager.rs
src/query/ee/src/license/license_mgr.rs

Add helper methods to trait `LicenseManager`
- `is_license_valid`
Returns `true` if `self.parse_license` return OK(_), otherwise `false`
- `check_license`
Returns `Err(e)` if `self.parse_license` return Err(e), otherwise `Ok(())`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17761)

refactor: add helper methods to trait `LicenseManager`

---

.typos.toml
src/query/ast/src/ast/expr.rs
src/query/ast/src/parser/expr.rs
src/query/ast/src/parser/token.rs
src/query/expression/src/utils/date_helper.rs
src/query/functions/src/scalars/timestamp/src/datetime.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test

Add new interval kind:
```
ISODOW, YEARWEEK, MILLENNIUM
```
Extract, date_part and date_diff support more DATE PART.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17759)

feat: function extract, date_part,date_diff support more date part

---

Cargo.lock
Cargo.toml
src/meta/cache/Cargo.toml
src/meta/cache/README.md
src/meta/cache/src/cache.rs
src/meta/cache/src/cache_data.rs
src/meta/cache/src/errors/connection_closed.rs
src/meta/cache/src/errors/either.rs
src/meta/cache/src/errors/mod.rs
src/meta/cache/src/errors/unsupported.rs
src/meta/cache/src/event_watcher.rs
src/meta/cache/src/lib.rs
src/meta/service/Cargo.toml
src/meta/service/tests/it/grpc/t52_metasrv_grpc_cache.rs

Crate `databend-common-meta-cache` provide a process-wide in memory
cache for databend-meta service.
It stores a continous range of key values locally and watches the
updates on a remote databend-meta and continously apply new changes to
local store.
The cache may be obsolete if the connection to the datbend-meta service
is unstable. Although in the background it keep trying to re-connecting.
This cache requires at least databend-meta 1.2.677; if the server is
older the cache returns a `Unsupported` error when accessing it.
Usage:
```rust
let client = MetaGrpcClient::try_create(/*..*/);
let cache = Cache::new(
client,
"your/cache/key/space/in/meta/service",
"your-app-name-for-logging", …
```

feat(meta-client): add `cache` crate for databend-meta service

---

src/query/functions/src/aggregates/aggregate_avg.rs

Fixed a typo in the AVG aggregation function where DecimalSumState was incorrectly used instead of DecimalAvgState.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17774)

fix: correct state type for Decimal256 AVG aggregation 

---

Cargo.lock
src/query/service/src/servers/mysql/mysql_session.rs

- fixes https://github.com/databendlabs/databend/issues/17797
We used to set `non_blocking = false` by hand to use this stream in a blocking mysql server. But now, mysql server supportes async. Let's try removing it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17798)

fix: Remove set nonblocking = false for mysql tcp stream

---

.github/workflows/reuse.linux.yml

https://github.com/databendlabs/databend/actions/runs/14541941648/job/40805342069?pr=17812
Rerun 3 times, but report action timeout
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17813)

chore(ci): add ci test_stateless_cluster_linux timeout minute to 18

---

src/query/service/src/servers/http/v1/http_query_handlers.rs
src/query/service/src/servers/http/v1/query/execute_state.rs
src/query/service/src/servers/http/v1/query/http_query.rs
src/query/service/src/sessions/queue_mgr.rs

The following Send/Sync implementation does not provide any safety
guarantee.
```
unsafe impl Send for AcquireQueueGuard {}
unsafe impl Sync for AcquireQueueGuard {}
```
In this commit, by removing potential `Sync` access to internal data in
`HttpQuery`, `AcquireQueueGuard` does not need to be `Sync` any more.
Therefore there is no need to add unsafe Send/Sync impl to it.
Because `Arc<T>: Send` requires `T: Sync`, but `Arc<Mutex<T>>: Send`
does not require `T: Sync`, we replace `Arc<T>` with `Arc<Mutex<T>>`,
to eliminate the `Sync` requirement.
Therefore, `AcquireQueueGuard` is only required to be `Send`.
- - - …

refactor(query): remove unsafe implementation of Send and Sync for AcquireQueueGuard

---

src/meta/semaphore/src/acquirer/acquirer.rs
src/query/service/src/sessions/queue_mgr.rs
src/query/service/tests/it/sessions/queue_mgr.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17825)

chore: add logging to semphore leaser

---

src/query/expression/src/kernels/topk.rs
src/query/expression/src/types.rs
src/query/expression/src/types/any.rs
src/query/expression/src/types/array.rs
src/query/expression/src/types/binary.rs
src/query/expression/src/types/bitmap.rs
src/query/expression/src/types/boolean.rs
src/query/expression/src/types/date.rs
src/query/expression/src/types/decimal.rs
src/query/expression/src/types/empty_array.rs
src/query/expression/src/types/empty_map.rs
src/query/expression/src/types/generic.rs
src/query/expression/src/types/geography.rs
src/query/expression/src/types/geometry.rs
src/query/expression/src/types/interval.rs
src/query/expression/src/types/map.rs
src/query/expression/src/types/null.rs
src/query/expression/src/types/nullable.rs
src/query/expression/src/types/number.rs
src/query/expression/src/types/string.rs
src/query/expression/src/types/timestamp.rs
src/query/expression/src/types/variant.rs
src/query/functions/src/scalars/array.rs

* Removed the upcast_gat method from various ValueType implementations to simplify the trait.
* Updated the try_downcast_scalar method signature.
* Adjusted related methods in TopKSorter to align with the changes in ValueType trait.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17836)

chore(query): remove `upcast_gat` method

---

src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
src/query/sql/src/executor/physical_plans/physical_join_filter.rs
tests/sqllogictests/suites/mode/standalone/explain/join_reorder/chain.test

A new setting `enable_runtime_filter` has been added in this PR and is set to 1 by default. The runtime filter can be disabled by executing:
```SQL
SET enable_runtime_filter = 0;
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17869)

chore: add a setting to disable runtime filter

---

src/query/sql/src/planner/optimizer/optimizers/operator/decorrelate/decorrelate.rs
src/query/sql/src/planner/optimizer/optimizers/operator/decorrelate/subquery_decorrelator.rs
src/query/sql/src/planner/plans/join.rs
src/query/sql/src/planner/plans/operator.rs
tests/sqllogictests/suites/query/subquery.test

In the previous implementation, the subquery decorrelator did not handle correlated subqueries in join conditions.
In this PR:
* Support decorrelating correlated subqueries in `join.equi_conditions`. Example: `SELECT * FROM t1 JOIN t2 ON t1.a = (SELECT a FROM t3 WHERE b = t2.b)`
* Support decorrelating correlated subqueries in inner join `non_equi_conditions`. Example: `SELECT * FROM t1 JOIN t2 ON EXISTS (SELECT a FROM t3 WHERE a = t1.a AND b = t2.b)
`
* Do not support decorrelating correlated subqueries in `non_equi_conditions` for other join types
fixes: #17815
- - - …

feat(optimizer): part support decorrelating correlated subqueries in join conditions

---

src/query/management/src/warehouse/warehouse_mgr.rs
src/query/management/tests/it/warehouse.rs

feat(cluster): support fuzzy match for warehouse unassign node
Support case:
```
-- Unset node group when create warehouse
CREATE WAREHOUSE test_warehouse WITH warehouse_size = 10; -- 3 log node group, 7 other node group
-- Use node group when unassign node
ALTER WAREHOUSE test_warehouse UNASSIGN NODES (UNASSIGN 1 NODES FROM log_node FOR default);
```
```
-- set node group when create warehouse
CREATE WAREHOUSE test_warehouse (ASSIGN 1 NODES FROM log_node, ASSIGN 2 NODES FROM infra_node);
-- unassign node without node group
ALTER WAREHOUSE test_warehouse UNASSIGN NODES (UNASSIGN 2 FOR default);
```
- - - …

feat(cluster): support fuzzy match for warehouse unassign node

---

src/meta/binaries/metabench/main.rs
src/meta/client/src/grpc_client.rs
src/meta/semaphore/src/acquirer/acquirer.rs
src/meta/semaphore/src/acquirer/mod.rs
src/meta/semaphore/src/acquirer/stat.rs
src/meta/semaphore/src/semaphore.rs
src/meta/service/tests/it/grpc/t51_metasrv_grpc_semaphore.rs

Previously, the semaphore sequence (`seq`) generation relied on a
generator key in the meta-service. This approach required a
compare-and-swap (CAS) loop, where:
1. A `seq` was generated from the generator key.
2. The semaphore permit key (derived from the `seq`) was inserted into
the meta-service, before the generator key is updated again by other
processes.
Under high concurrency, this method caused frequent conflicts during the
CAS loop, leading to repeated retries and increased latency.
- Replaced the existing sequence generation logic with a timestamp-based
policy.
- The new approach directly uses the current timestamp as the `seq`
value and attempts to insert it into the meta-service.
- …

feat(meta-client-semaphore): generate semaphore sequence using timestamps to reduce conflicts

---

src/common/storage/src/statistics.rs
src/query/sql/src/planner/optimizer/ir/stats/histogram.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0020_analyze.test

- Implements histogram calculations for string (Bytes) data types
- Adds type_name() method to Datum for better error messages
old:  `Unsupported datum type: Bytes([56, 46, 48]), Bytes([57, 57, 57, 55])`
now: `1001=>Unsupported datum type for histogram calculation: 8.0 (type: String), 9997 (type: String). Only numeric types are supported.`
- Enables accurate cardinality estimation for string predicates
- [] Other (please describe): only add log
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17873)

fix(optimizer): histogram calculations for string (Bytes) data types

---

src/query/service/src/pipelines/builders/builder_hilbert_partition.rs
src/query/service/src/pipelines/builders/builder_sort.rs
src/query/service/src/pipelines/builders/builder_window.rs
src/query/service/src/pipelines/processors/transforms/transform_merge_sort.rs
src/query/service/src/pipelines/processors/transforms/transform_merge_sort/sort_spill.rs
src/query/service/src/spillers/spiller.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs

1. Reduce num_merge .
2. The `sort_input_data` will spill blocks earlier. 
3. Add configuration `sort_spilling_to_disk_bytes_limit` to allow sort spill to local .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17883)

fix(query): sort will still be OOM even if spill is enabled

---

Cargo.lock
src/meta/api/src/txn_backoff.rs
src/meta/store/Cargo.toml
src/meta/store/src/lib.rs
src/meta/store/src/local.rs
src/meta/store/tests/it/kv_api.rs
src/meta/store/tests/it/main.rs
src/query/management/tests/it/warehouse.rs
src/query/management/tests/it/workload.rs
src/query/service/src/sessions/queue_mgr.rs
src/query/service/tests/it/sessions/queue_mgr.rs

- Replaced the in-memory meta-store with a meta-service running in a
temporary directory for testing purposes.
- The in-memory meta-store was limited in functionality and did not
provide a complete feature set.
- The new approach ensures full functionality during testing by
simulating a real meta-service.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17821)

refactor: start a meta-service as local meta for testing

---

tests/sqllogictests/suites/mode/standalone/ee/explain_ngram_index.test

Fix the issue that ci fails after merging https://github.com/databendlabs/databend/pull/17852
The error is caused by the row number estimation problem of the SQL statement `EXPLAIN SELECT id, content FROM t1 WHERE content LIKE 'A picture%'`, which is affected by https://github.com/databendlabs/databend/pull/17873 (Affects the results of `SelectivityEstimator::compute_binary_comparison_selectivity`)
This SQL statement will be rewritten as `EXPLAIN SELECT id, content FROM t1 WHERE content content >= 'A picture' and content < 'A picturf'`this test has nothing to do with ngram index.
- - - …

chore: remove useless logic test on `explain_ngram_index.test`

---

src/query/functions/src/srfs/variant.rs
src/query/sql/src/executor/physical_plans/physical_eval_scalar.rs
tests/sqllogictests/suites/mode/standalone/explain/project_set.test
tests/sqllogictests/suites/query/lateral.test

This PR enhances the performance of the `FLATTEN` function in Databend, specifically addressing the issue of potential Out-of-Memory (OOM) errors caused by data replication.
**Background:**
The `FLATTEN` function is a set-returning function that transforms nested JSON data into a tabular format. It generates six new columns: `seq`, `key`, `path`, `index`, `value`, and `this`. The `this` column contains the original JSON data. Due to the nature of set-returning functions, the number of rows can significantly increase, leading to substantial data duplication in the `this` column and potential OOM issues.
PR #13935 introduced column pruning for `FLATTEN`, which avoids generating data for columns …

refactor(query): Optimize `FLATTEN` function with filter condition

---

src/query/functions/src/cast_rules.rs
src/query/functions/src/scalars/array.rs
src/query/functions/tests/it/scalars/array.rs
src/query/functions/tests/it/scalars/string.rs
src/query/functions/tests/it/scalars/testdata/array.txt
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/functions/tests/it/scalars/testdata/string.txt
tests/sqllogictests/suites/ee/05_ee_ddl/05_0003_ddl_create_add_computed_column.test

1. auto cast int to string for concat functions
2. add `array_intersection` function which outputs array with element both in arg0 and arg1.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17891)

chore(query): auto cast int to string for concat functions

---

src/query/service/src/interpreters/common/table_option_validation.rs
src/query/service/src/interpreters/interpreter_table_create.rs
src/query/service/src/interpreters/interpreter_table_set_options.rs
src/query/storages/fuse/src/constants.rs
src/query/storages/fuse/src/operations/common/processors/sink_commit.rs
tests/sqllogictests/suites/ee/03_ee_vacuum/03_0006_table_opt_auto_vacuum.test

troduces a new table option `enable_auto_vacuum` that controls whether a table automatically triggers vacuum operations during mutations. 
It can be:
- Specified during table creation
- Modified for existing tables via `ALTER TABLE` stmt
~~~
create or replace table t (c int)  enable_auto_vacuum = 1;
~~~
~~~
alter table t set options(enable_auto_vacuum = 1);
~~~
This table option has a higher priority than the session/global setting of the same name:
~~~
ALTER TABLE t SET OPTIONS(enable_auto_vacuum = 1);
SET enable_auto_vacuum = 0;
-- This mutation WILL trigger the vacuum operation
INSERT INTO t VALUES(1);
~~~
~~~
ALTER TABLE t SET OPTIONS(enable_auto_vacuum = 0);
SET enable_auto_vacuum = 1;
-- …

feat: new table option `enable_auto_vacuum`

---

src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
src/query/storages/fuse/src/fuse_table.rs
tests/sqllogictests/suites/ee/03_ee_vacuum/03_0007_setting_num_snapshot_to_keep.test

Adds new settings `data_retention_num_snapshots_to_keep`, which specifies how many snapshots to retain during vacuum operations.
- Overrides setting 'data_retention_time_in_days'
- If set to 0, this setting will be ignored
Docs of this new setting (and new table option of https://github.com/databendlabs/databend/pull/17884) will be updated in another PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17893)

feat: new settings `data_retention_num_snapshots_to_keep`

---

src/common/storage/src/operator.rs

**Move Timeout Layer Attachment to Ensure Cancel Safety and Reentrancy**
This PR adjusts the timing of when the timeout layer is added in the `build_operator` function (`src/common/storage/src/operator.rs`). The timeout layer is now attached earlier in the operator construction process.
**Key Points:**
- **Moved the timeout layer attachment:** The timeout layer is now added as the very first layer, before other layers are applied.
- **Reason:** The timeout layer requires its internal state to be cancel safe. By attaching it first, we ensure that all subsequent operations are protected, and that the operator remains reentrant after a timeout occurs.
- **Effect:** This change guarantees that …

fix(storage): Move timeout layer before to ensure cancel safety

---

Cargo.lock
Cargo.toml
src/meta/README.md
src/meta/client/src/lib.rs
src/meta/semaphore/src/meta_event_subscriber/processor.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/meta_service/watcher.rs
src/meta/service/tests/it/grpc/metasrv_grpc_watch.rs
src/meta/types/proto/meta.proto
src/meta/types/src/proto_display/watch_display.rs
src/meta/types/src/proto_ext/watch_ext.rs

When a watch requires initialization flush, the server now sends a flag
message indicating when the initialization phase is completed.
With this flag, the `cache` module can determine whether data has been
fully initialized and is ready to serve, improving reliability of the
caching system.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17900)

feat(meta-service): add initialization complete flag for watch

---

src/query/ee/tests/it/storages/fuse/operations/virtual_columns.rs
src/query/ee/tests/it/storages/fuse/operations/virtual_columns_builder.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
src/query/sql/src/planner/binder/bind_mutation/mutation_expression.rs
src/query/sql/src/planner/binder/bind_query/bind_select.rs
src/query/sql/src/planner/metadata/metadata.rs
src/query/sql/src/planner/semantic/type_check.rs
src/query/storages/fuse/src/io/write/virtual_column_builder.rs
src/query/storages/fuse/src/pruning/block_pruner.rs
src/query/storages/fuse/src/pruning/virtual_column_pruner.rs
src/query/storages/fuse/src/statistics/accumulator.rs
tests/sqllogictests/suites/ee/01_ee_system/01_0002_virtual_column.test
tests/sqllogictests/suites/mode/standalone/ee/explain_virtual_column.test

This PR addresses several issues related to virtual columns in Databend, focusing on stability and correctness.
**Key Changes:**
1.  **Fix: Virtual Column Binder Cast Issue:**
*   Addresses a bug where virtual columns could not be found during the binding process due to cast rewrite virtual column.
2.  **Fix: Merge Into Stream Column Deletion:**
*   Resolves an issue in `MERGE INTO` statements where deleting a stream column could incorrectly lead to the deletion of a virtual column. This fix ensures that only the intended stream column is removed, preserving the integrity of virtual columns.
3.  **Improvement: Virtual Column Data Read Validation:**
*   Implements a check for row counts when …

fix(query): fix virtual column bind column

---

src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_spiller.rs

The value of `join_spilling_partition_bits` can be set from 0 to 64. The operation `hash >> (32 - bits)` may overflow, leading to a panic in debug mode and undefined behavior in release mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17906)

fix: overflow error in get_partition_id()

---

src/query/ast/benches/bench.rs
src/query/ast/src/parser/expr.rs
src/query/ast/tests/it/testdata/stmt-error.txt

Databend may take a very long time to parse multiple layers of function calls
```sql
select ROUND(6378.138 * 2 * ASIN(SQRT(POW(SIN((IF(1 = 2, NULL, 10) * PI() / 180 - 40.051816 * PI() / 180) / 2), 2))) * 1000, 0) distance;
Before: 
1 row read in 25.504 sec. Processed 1 row, 1 B (0.04 row/s, 0 B/s)
After:
1 row read in 1.115 sec. Processed 1 row, 1 B (0.90 row/s, 0 B/s)
```
This is because there are many similar matching patterns when parsing function calls, and simple function calls need to fail to match complex expressions before entering. This will cause multiple nested simple function calls to fail to match correctly (the matching order is the last pattern).
This PR simplifies the matching …

feat(parse): Simplify the matching pattern when parse function, avoid exponential backtracking

---

Cargo.lock
src/meta/app/src/data_id.rs
src/meta/client/src/client_handle.rs
src/meta/client/src/established_client.rs
src/meta/client/src/grpc_action.rs
src/meta/client/src/grpc_client.rs
src/meta/client/src/lib.rs
src/meta/client/src/message.rs
src/meta/client/src/required.rs
src/meta/service/tests/it/grpc/metasrv_grpc_watch.rs
src/meta/store/Cargo.toml
src/meta/store/src/lib.rs
src/meta/types/src/errors/meta_client_errors.rs
src/meta/types/src/errors/meta_errors.rs

This method requires the databend-meta server to respond a
`is_initialization` flag in each watch response for the client to
distinguish between initialization events and key-value change events.
This feature is required by the cache mod.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17944)

feat(meta-client): add `watch_with_initialization()` method

---

Cargo.lock
Cargo.toml
src/meta/service/tests/it/store.rs

When raft-log entries are purged, it should also be removed from the
cache, since they will never be read again.
This will just minimize the cache usage even it is configured with large
max-items or capacity.
We have added a test to ensure the behavoir of the raft-log cache.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17951)

fix(meta-service): evict cache for purge raft-log

---

src/query/service/src/sessions/query_ctx.rs
src/query/storages/stage/src/read/avro/avro_to_jsonb.rs
src/query/storages/stage/src/read/avro/block_builder_processor.rs
src/query/storages/stage/src/read/avro/decoder.rs
tests/sqllogictests/suites/stage/formats/avro/avro_query.test

In https://github.com/databendlabs/databend/pull/17548 we introduced the `COPY INTO <table>` feature for Avro files. This PR completes the Avro loading functionality by adding support for:
1. Direct querying of Avro files
2. COPY with transformation
3. Accessing metadata columns `metadata$filename` and `metadata$file_row_number`
After these changes, Avro files behave very similarly to NDJSON files when reading:
1. **COPY without transformation**:
- Assumes top-level schema is a record and matches fields by name
- More efficient for bulk loading
- Doesn't require all files to have identical schema:
- Field order doesn't matter
- Supports file format option `missing_field_as = ERROR | …

feat: support select from AVRO files.

---

src/query/storages/system/src/query_log_table.rs

Format query_start_time and query_end_time to local time RFC3339 with timezone.
- ref: https://github.com/databendlabs/databend/issues/17859
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17963)

fix(query): use local time for query log

---

Cargo.lock
src/query/service/src/interpreters/interpreter.rs
src/query/service/src/interpreters/interpreter_txn_commit.rs
src/query/sql/Cargo.toml
src/query/sql/src/planner/binder/binder.rs
src/query/sql/src/planner/binder/mod.rs
src/query/sql/src/planner/mod.rs

Code for multi-statement transaction commits was located in the `databend-common-sql` crate, which made it difficult to reference fuse-related crates. So move transaction commit relevant code to interpreter
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17976)

refactor: move transaction commit relevant code to interpreter

---

src/meta/semaphore/src/queue/semaphore_queue.rs

Before this commit, when a smaller seq semaphore is inserted after a
larger seq one, the smaller one may not be acquired because the capacity
is exhausted. This might lead to a deadlock:
For example, `A` has seq 1, `B` has seq 2. the capacity is 1.
- Process `A` received sem `B` first, then sem `A`;
- Process `B` received sem `A` first, then sem `B`.
```text
|             acquired    waiting
| Process A:  [ B ]       [ A ]
| Process B:  [ A ]       [ B ]
```
And then two processes blocks each other:
- Process `A` await sem `B` to be removed from `acquired` queue, which await Process `B` to remove sem `B`.
- Process `B` await sem `A` to be removed from `acquired` queue, which await Process `A` …

fix(meta-semaphore): deadlock between meta-service semaphores

---

src/query/storages/common/cache/src/cache.rs
src/query/storages/common/cache/src/manager.rs
src/query/storages/common/cache/src/providers/disk_cache/disk_cache_lru.rs
src/query/storages/common/cache/src/providers/disk_cache_builder.rs
src/query/storages/common/cache/src/providers/hybrid_cache.rs
src/query/storages/common/cache/src/providers/memory_cache.rs
src/query/storages/common/table_meta/src/meta/current/mod.rs
src/query/storages/common/table_meta/src/meta/v4/mod.rs

Preparing for the related part of `memory_gc_handle`
https://github.com/databendlabs/databend/blob/7fd47b98354ec729ad37c03c863e86ebcf1f64b7/src/query/service/src/global_services.rs#L204-L213
Add new method ` pub fn CacheManager::release_cache_memory(&self, clearance_level: CacheClearanceLevel) -> ()`
~~~
/// Releases memory occupied by caches
///
/// This method is used to free up memory resources by clearing various caches
/// in the system. The extent of cache clearing depends on the specified clearance level.
///
/// # Parameters
/// * `clearance_level` - Determines how aggressively to clear caches:
///   * `CacheClearanceLevel::Basic`: Clears caches that may consume significant memory
/// …

chore: add `release_cache_memory` to CacheManager

---

.github/actions/test_sqllogic_iceberg_tpch/action.yml
Cargo.lock
Cargo.toml
src/query/storages/iceberg/src/partition.rs
src/query/storages/iceberg/src/table.rs
src/query/storages/parquet/src/parquet_part.rs
src/query/storages/parquet/src/parquet_reader/read_policy/no_prefetch.rs
src/query/storages/parquet/src/parquet_reader/reader/builder.rs
src/query/storages/parquet/src/parquet_reader/reader/row_group_reader.rs
src/query/storages/parquet/src/source.rs
tests/sqllogictests/scripts/prepare_iceberg_test_data.py
tests/sqllogictests/suites/tpch_iceberg/base.test

When reading the Iceberg Table, identify Position Deletes and skip the deleted data.
After the Iceberg table is set to merge on read, deleting data will generate multiple delete files. 
For example:
`DELETE FROM iceberg.test.test_positional_merge_on_read_deletes WHERE number > 9` This sql will generate the delete file: 00000-2-09da4c32-2cd8-4d90-b4e2-2ed02928a009-00001-deletes.parquet, used to indicate the data that needs to be marked as deleted in the related data files.
This PR will generate corresponding `RowSelection` in the Iceberg Table's `plan_files` for the corresponding delete files in the data file to skip the data on `ParquetSource`.
dep: …

feat: Iceberg Table supports delete positions of merge on read when reading

---

src/query/sql/src/planner/binder/bind_query/bind.rs
tests/sqllogictests/suites/tpch_iceberg/queries.test

The introduction of Iceberg catalog support in Databend means that internally-generated CTEs can no longer be directly created under the DEFAULT catalog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/17989)

chore(query): generate cte tmp tbl should in current_catalog

---

src/query/storages/common/cache/src/manager.rs

Make sure test data has been written disk key:
The on-disk cache is populated asynchronously, we need to
wait until the populate-queue is empty. At that time, at least
the first cache item  should be written into the on-disk cache.
- fixes: #17998
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18000)

fix: flaky test `test_release_cache_memory`

---

src/query/storages/common/cache/src/manager.rs

Correct the implementation to properly respect configuration parameters for block metadata caching. 
Previously, the configuration values for `segment_block_metas_count` and `block_meta_count` were not being correctly applied. 
Added test case to verify proper configuration handling.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18002)

fix(cache): fix improper config usage in cache manager

---

src/meta/raft-store/src/ondisk/upgrade_to_v004.rs

NFS may hold the resource for longer thus there might be an error such
as:
```
Error: std::io::error::Error: std::io::error::Error: Device or resource busy (os error 16);
when:(remove dir /var/lib/databend/raft/heap;
when remove V003 raft-log store based on sled: '/var/lib/databend/raft')
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18018)

refactor(meta): sleep a second before removing dir when cleaning up sled during upgrade

---

Cargo.lock
src/bendsave/Cargo.toml
src/bendsave/src/main.rs

In this commit, add `--version` / `-V` to `bendsave` to output its built
version:
```text
./target/debug/databend-bendsave --version
bendsave v1.2.743-nightly-59f0b3f41f(rust-1.88.0-nightly-2025-05-28T02:46:42.024829000Z)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18020)

refactor: bendsave should be able to output its built version

---

src/query/ast/src/parser/expr.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/expr.txt
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test

```sql
LAST_DAY( <date_or_timetamp_expr> [ , <date_part> ] )
```
The interval type for which to find the last day. Accepted values are week, month, quarter, and year.
default with: month
- fixes: #18021
- 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18022)

chore(query): last_day support default interval type

---

src/query/expression/src/function.rs
src/query/storages/iceberg/src/partition.rs
src/query/storages/parquet/src/copy_into_table/reader.rs
src/query/storages/parquet/src/lib.rs
src/query/storages/parquet/src/parquet_part.rs
src/query/storages/parquet/src/parquet_reader/predicate.rs
src/query/storages/parquet/src/parquet_reader/read_policy/no_prefetch.rs
src/query/storages/parquet/src/parquet_reader/read_policy/policy.rs
src/query/storages/parquet/src/parquet_reader/read_policy/predicate_and_topk.rs
src/query/storages/parquet/src/parquet_reader/read_policy/topk_only.rs
src/query/storages/parquet/src/parquet_reader/reader/builder.rs
src/query/storages/parquet/src/parquet_reader/reader/row_group_reader.rs
src/query/storages/parquet/src/source.rs
tests/sqllogictests/scripts/docker-compose-iceberg-tpch.yml
tests/sqllogictests/scripts/iceberg-driver/.gitignore
tests/sqllogictests/scripts/iceberg-driver/Dockerfile
tests/sqllogictests/scripts/iceberg-driver/README.md
tests/sqllogictests/scripts/iceberg-driver/pom.xml
tests/sqllogictests/scripts/iceberg-driver/src/main/java/org/example/Driver.java
tests/sqllogictests/scripts/prepare_iceberg_test_data.py
tests/sqllogictests/suites/tpch_iceberg/base.test

When reading IcebergTable, the deleted data is filtered out by the File component predicate of Equality Delete.
Equality Delete File Format:
The corresponding Field contains constants with the same value, which are deleted.
Tips: 
Equality Delete is currently only supported in Iceberg Java, so the Iceberg Driver is introduced
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18015)

feat: Iceberg Table supports equality delete of merge on read when reading

---

tests/sqllogictests/suites/ee/03_ee_vacuum/03_0004_auto_vacuum.test

- Tweak test case settings Since vacuum2 is active by default now, in the test case that expects all historical data that no longer referenced by the lasted snapshot to be vacuumed, data_retention_time_in_days should be set to zero.
- Change handler constraint from 'mysql' to 'http' By now, CI only guarantees that all EE suites could be tested using http handler, the 'mysql' handler may only be applied to some of the EE tests.
- Cleanup test stage before each test case to ensure clean state
- fixes: #18037
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18038)

fix: flay test `03_0004_auto_vacuum.test`

---

src/query/functions/src/aggregates/aggregate_function_factory.rs
tests/sqllogictests/suites/query/functions/02_0000_function_aggregate_mix.test

These two cases do not execute OrderBy because they return early and do not use `AggregateFunctionSortAdaptor`
```
select city, string_agg(var, '|') within group(order by var )
from (values ('a', '123'), ('a', '456'), ('b', 'aaa'), ('b', 'bbb')) t(city, var)
group by city;
select city,string_agg(var,'|') within group(order by var) as t
from (
select 'a' as city,'123' as var
union all
select 'a' as city,'456' as var
union all
select 'b' as city,'aaa' as var
union all
select 'b' as city,'bbb' as var
) t
group by city;
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18 …

fix: when the WithIn Function arguments all are not `Nullable`, `OrderBy` fails

---

src/query/expression/Cargo.toml
src/query/expression/src/function.rs
src/query/expression/src/utils/date_helper.rs
src/query/functions/src/scalars/timestamp/src/datetime.rs
src/query/settings/src/settings_default.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test

date_format_style default value modify to Oracle
refactor date_format_style default value MySQL -> Oracle
- Implemented "longest match first" strategy by descending pattern length sort  
- Added word boundary checks for `MON` to prevent false matches (e.g., distinguish "MON" from "MONTH")  
- Case-insensitive matching for PostgreSQL formats (e.g., `YYYY`/`HH12`)  
- Strict case preservation for strftime literals (e.g., `%Y`/`%B`)  
- Pre-allocated output buffer (capacity = input length + safety margin)  
- Byte-indexed operations to minimize UTF-8 decoding overhead  
- Automatic escaping of `%` symbols in input (e.g., `%%Y` → `%%Y`)  
- Unmatched content preserved verbatim for lossless …

refactor: Optimize PostgreSQL to strftime Format

---

src/common/tracing/src/config.rs
src/query/sql/src/planner/optimizer/optimizer_api.rs
src/query/sql/src/planner/optimizer/optimizer_context.rs
src/query/sql/src/planner/optimizer/optimizers/recursive/recursive.rs
src/query/sql/src/planner/optimizer/optimizers/rule/rule.rs
src/query/sql/src/planner/optimizer/pipeline/mod.rs
src/query/sql/src/planner/optimizer/pipeline/pipeline.rs
src/query/sql/src/planner/optimizer/pipeline/trace/mod.rs
src/query/sql/src/planner/optimizer/pipeline/trace/trace.rs

- `SET optimizer_skip_list = 'CascadesOptimizer,PushDownFilterJoin,EliminateFilter'`, the optimizer will not apply CascadesOptimizer, PushDownFilterJoin& EliminateFilter Rules.
- Enhance the optimizer trace log: `set enable_optimizer_trace=1`
<details>
<summary>Optimizer Trace Example</summary>
```
========== OPTIMIZERS SUMMARY TRACE ==========
[✓] 0: SubqueryDecorrelatorOptimizer (259.42µs)
[✗] 1: RuleStatsAggregateOptimizer (39.58µs)
[✗] 2: CollectStatisticsOptimizer (1.02ms)
[✗] 3: RuleNormalizeAggregateOptimizer (45.67µs)
[✓] 4: PullUpFilterOptimizer (346.29µs)
[✓] 5: RecursiveRuleOptimizer[EliminateSort,EliminateUnion,...(28)] (423.78ms)
└── Rules: 7/30 Applied (23%)
Rules Summary:
[✗] …
```

chore(optimizer): enhance the optimizer trace

---

src/common/base/src/runtime/runtime_tracker.rs

Use Arc::clone instead of TrackingPayload::clone to reduce unnecessary clone overhead during task switching. This is trivial.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18047)

chore(base): avoid deep clone for tracker

---

src/query/service/src/servers/http/v1/query/execute_state.rs
src/query/service/src/servers/http/v1/query/http_query.rs
src/query/service/src/sessions/session.rs
src/query/service/tests/it/servers/http/http_query_handlers.rs
src/tests/sqlsmith/src/http_client.rs
tests/sqllogictests/src/util.rs
tests/sqllogictests/suites/base/20+_others/20_0014_result_scan.test

**Problem**:
HTTP sessions in Databend are ephemeral - they terminate after each query completes. This prevents HTTP clients from using `RESULT_SCAN` and `last_query_id()` functions, which rely on session-stored query history. These features currently only work with persistent MySQL protocol connections.
**Solution**:
This PR enables HTTP clients to maintain query history by storing `last_query_id` and result cache metadata in the HTTP configuration, allowing state transfer between requests.
**Changes**:
1. **Session State Enhancement**:
- Added `last_query_ids` and `last_query_result_cache_keys` arrays to `ExecutorSessionState` (stores last 64 queries)
- Enabled query history persistence for …

feat(query): support result_scan and last_query_id in http handler

---

src/query/sql/src/planner/binder/select.rs
src/query/sql/src/planner/optimizer/optimizers/rule/union_rules/rule_eliminate_union.rs
tests/sqllogictests/suites/mode/standalone/explain/union.test
tests/sqllogictests/suites/query/union.test

- Fix Union Column Binding and Union Elimination Rule
This PR addresses two issues in the SQL query planner related to UNION operations:
Column Binding Fix in UNION Operations:
1. Moves column binding logic for the left side of a UNION operation to happen immediately after processing each column
Ensures left column bindings are correctly reused when no type coercion is needed
2. Prevents potential issues with column binding references in complex UNION queries
3. Union Elimination Rule Enhancement:
Adds a safety check in the RuleEliminateUnion to verify that union's output indexes match the left child's output indexes
Prevents incorrect query plan transformations when the output indexes don't …

fix(query): reuse the left's column binding in union as possible

---

src/query/ast/src/ast/statements/insert.rs
src/query/ast/src/parser/statement.rs
src/query/sql/src/planner/binder/ddl/stage.rs
src/query/sql/src/planner/binder/insert.rs
tests/suites/1_stateful/01_streaming_load/01_0001_streaming_load_ontime.sh
tests/suites/1_stateful/01_streaming_load/01_0002_streaming_load_variant.sh
tests/suites/1_stateful/01_streaming_load/01_0003_streaming_load_dedup.sh
tests/suites/1_stateful/01_streaming_load/01_0004_streaming_load_error.sh
tests/suites/1_stateful/01_streaming_load/01_0005_streaming_load_compact.sh
tests/suites/1_stateful/01_streaming_load/01_0006_streaming_load_parquet.sh

new syntax `insert into <table> from @streaming_load file_format=(...)`
note since original insert do not support `from clause`,   `from clause` is only used for streaming load.
forbid user to create stage named `streaming_load`
- fixes: https://github.com/databendlabs/databend/issues/18036
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18062)

feat: adjust syntax of streaming load insert SQL.

---

src/query/storages/system/src/columns_table.rs
tests/suites/0_stateless/18_rbac/18_0013_column_privilege.result
tests/suites/0_stateless/18_rbac/18_0013_column_privilege.sh

This PR fixes system.columns returning incomplete results when users have partial grants and queries include multi-database conditions like WHERE database IN (...). 
The root cause was the old filtering mechanism, find_eq_filter, failing to correctly process such complex filters. 
By replacing it with find_eq_or_filter, the system now accurately identifies and displays all accessible metadata, significantly improving system.columns reliability for users with granular access rights.
- fixes: #18056
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18063)

fix(query): system.columns will return empty result when `where database in (y,x)`

---

src/query/ast/src/ast/statements/replace.rs
src/query/ast/src/parser/statement.rs
src/query/ast/tests/it/testdata/stmt.txt
src/query/sql/src/planner/binder/replace.rs
src/query/sql/src/planner/planner.rs
src/tests/sqlsmith/src/sql_gen/dml.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0023_replace_into.test

This PR addresses a bug in the parsing of `REPLACE INTO` statements, specifically when they contain long `WHERE` clauses.
**Problem:**
To prevent excessively long SQL queries from slowing down the parser, the `REPLACE INTO` parser initially attempts to parse only the first 128 tokens. If this initial parse fails, the parser then attempts to parse the complete SQL statement. However, in certain scenarios, the truncated SQL (the first 128 tokens) could be parsed *successfully* without errors, but with a different semantic meaning than the original, complete SQL statement. This leads to incorrect results.
**Example:**
The following SQL statement demonstrates the issue:
```sql
replace into test …
```

fix(query): fix replace into partial parse insert source

---

src/query/sql/src/planner/binder/select.rs
src/query/sql/src/planner/dataframe.rs
tests/sqllogictests/suites/query/union.test

```sql
select * from (select 1 n) t2
where exists (
select 1 from (select * from numbers(5) union select * from numbers(5)) t where t.number = t2.n
);
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18097)

fix(bind): parent `BindContext` missing when binding union

---

src/query/expression/src/function.rs
src/query/expression/src/type_check.rs
src/query/functions/src/cast_rules.rs
src/query/functions/src/scalars/mod.rs
src/query/functions/src/scalars/string.rs
src/query/functions/tests/it/scalars/string.rs
src/query/functions/tests/it/scalars/testdata/string.txt

fix(query): add dynamic cast rules
Dynamic Cast Rules Implementation
This PR introduces dynamic cast rules to Databend's type system, enhancing the flexibility of type casting operations. Here's a summary of the changes:
Now `concat`, `concat_ws` will try to auto-cast other types into string type.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18103)

fix(query): add dynamic cast rules

---

src/meta/app/src/storage/storage_params.rs

We have a runtime check for `disable_credential_loader`, but its value is stored in metasrv and won't be updated when `role_arn` changes.
Before:
- changing role_arn doesn't work for existing external table.
After:
- changing role_arn works for existing external table.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18115)

fix(storage): disable_credential_loader not been updated while role_arn set

---

src/meta/api/src/reply.rs
src/meta/api/src/util.rs
src/meta/client/src/lib.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/types/proto/meta.proto
src/meta/types/src/proto_display/mod.rs
src/meta/types/src/proto_ext/txn_ext.rs
src/query/management/src/role/role_mgr.rs
src/query/management/src/stage/stage_mgr.rs

The `error` field is not used since 1.2.676; and is removed in this
commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18112)

refactor(meta-server): remove TxnReply::error

---

src/query/ast/src/ast/expr.rs
src/query/ast/src/parser/expr.rs
src/query/ast/src/parser/token.rs
src/query/functions/src/scalars/timestamp/src/datetime.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test

`iw` is ISOWeek.
`hh24` is hour.
In main will return parse err:
```sql
SELECT TRUNC(DATE '2024-01-01', 'IW');
select TRUNC('2025-06-09 10:11:12'::Datetime, 'HH24');
```
In pr:
```sql
query T
SELECT TRUNC('2024-01-01'::Date, 'IW');
----
2024-01-01
query T
select TRUNC('2025-06-09 10:11:12'::Datetime, 'HH24');
----
2025-06-09 10:00:00.000000
```
- fixes: https://github.com/databendlabs/databend/issues/18106
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18114)

feat(query): Interval kin support iw and hh24

---

src/query/sql/src/planner/binder/bind_mutation/bind.rs
src/query/sql/src/planner/binder/copy_into_table.rs
src/query/sql/src/planner/binder/insert.rs
src/query/sql/src/planner/binder/insert_multi_table.rs
tests/sqllogictests/suites/base/03_common/03_0016_insert_into_values.test
tests/sqllogictests/suites/base/03_common/03_0035_update.test
tests/sqllogictests/suites/base/03_common/03_0046_copy_into_from_stage.test
tests/suites/5_ee/04_attach_read_only/02_0005_attach_table_read_only.result
tests/suites/5_ee/04_attach_read_only/02_0005_attach_table_read_only.sh

- Add `try_resolve_field_in_schema` function to provide better error messages when columns don't exist
- Include database and table name in error messages (e.g., Table "db.tbl" does not have a column with name "column")
- Update mutation operations (UPDATE, INSERT, COPY INTO) to use the new error handling
- Add test cases for column not exist error scenarios in:
- UPDATE statement
- INSERT statement
- COPY INTO statement
Without this PR:
~~~
mysql> insert into test(id, c_not_exist) values(1,2);
ERROR 1105 (HY000): BadArguments. Code: 1006, Text = Unable to get field named "c_not_exist". Valid fields: ["id", "payload", "file_name", "create_date", "processed_date", "retry_count", "load_id", …

chore: improve error messages for non-existent columns in mutation operations

---

src/query/service/src/interpreters/interpreter_insert.rs
src/query/service/src/servers/http/v1/streaming_load.rs
src/query/sql/src/planner/binder/copy_into_table.rs
src/query/sql/src/planner/binder/insert.rs
src/query/sql/src/planner/binder/replace.rs
src/query/sql/src/planner/plans/copy_into_table.rs
src/query/sql/src/planner/plans/insert.rs
tests/suites/1_stateful/01_streaming_load/01_0006_streaming_load_parquet.result
tests/suites/1_stateful/01_streaming_load/01_0006_streaming_load_parquet.sh
tests/suites/1_stateful/01_streaming_load/01_0007_streaming_load_placeholder.result
tests/suites/1_stateful/01_streaming_load/01_0007_streaming_load_placeholder.sh

`insert with stage` already support this,   streaming load  need to support it too, in order to serve as an alternative of `insert with stage`
```
create table user (id string default uuid(), name string, age int, load_date date)
curl  -H "sql:insert into user(name, age,  load_date) values (?, ?, '2025-01-02') upload=@/tmp/name_age.csv "-u root: -XPUT http://localhost:8000/v1/streaming_load
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18129)

feat: streaming load support values with placeholder.

---

src/meta/client/src/lib.rs
src/meta/kvapi/src/kvapi/test_suite.rs
src/meta/raft-store/src/applier.rs
src/meta/types/proto/request.proto
src/meta/types/src/proto_display/mod.rs
src/meta/types/src/proto_ext/txn_ext.rs

TxnPutResponse now returns both the value before and after the put
operation. Each returned value is a `SeqV` struct containing the
sequence number and value in bytes.
This is a backward-compatible change as protobuf-based clients
will ignore the new field.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18136)

feat(meta-service): return current seq-value in txn-put response

---

src/meta/kvapi/src/kvapi/test_suite.rs
src/query/expression/src/utils/mod.rs
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/functions/02_0058_function_ifnull.test

disable the shrink constant when it is a generic type argument of a function
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18145)

fix(bind): disable the shrink constant when it is a generic type argument of a function

---

src/common/storage/src/runtime_layer.rs

Presign is not spwaned on IO runtime before. This can lead to our SQL hang sometimes. This PR fixed it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18149)

fix(storage): Fix presign is not spawned on IO runtime

---

src/query/expression/src/utils/date_helper.rs
src/query/functions/src/scalars/timestamp/src/datetime.rs
src/query/functions/src/scalars/timestamp/src/interval.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test
tests/sqllogictests/suites/query/functions/02_0079_function_interval.test

1. support age function
**Syntax**
```sql
-- Subtract arguments, producing a “symbolic” result that uses years and months, rather than just days
age ( timestamp, timestamp ) → interval
-- Subtract argument from current_date (at midnight)
age ( timestamp ) → interval
```
e.g.
```sql
set timezone='America/New_York';
select age('2025-04-10'::date, '1957-06-13'::date);
----
67 years 9 months 27 days
select age('1957-06-13'::timestamp);
----
67 years 11 months 28 days
```
2. fix to_month(IntervalType);
In main:
```sql
select to_month(to_interval('12 months'))
----
12
```
In pr:
```sql
select to_month(to_interval('12 months'))
----
0
```
3. fix date convert timestamp
In main:
```sql
set …
```

feat(query): support `age` function

---

src/query/storages/stage/src/streaming_load.rs

since there are only one source, a few processor is fast enough and avoid both oom and small DataBlocks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18147)

chore: limit num of threads used by streaming load.

---

scripts/distribution/configs/databend-meta.toml
scripts/distribution/configs/databend-query.toml

Fixes` for example configs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18165)

chore: update ports in example config to default

---

src/query/service/src/catalogs/default/session_catalog.rs
src/query/service/src/interpreters/interpreter_table_create.rs
src/query/service/src/interpreters/mod.rs
src/query/service/src/servers/http/middleware/session.rs
src/query/service/src/servers/http/v1/http_query_handlers.rs
src/query/service/src/servers/http/v1/query/execute_state.rs
src/query/service/src/servers/http/v1/query/http_query.rs
src/query/service/src/servers/http/v1/session/client_session_manager.rs
src/query/service/src/servers/http/v1/session/consts.rs
src/query/service/tests/it/servers/http/http_query_handlers.rs
src/query/storages/common/session/src/temp_table.rs
tests/suites/1_stateful/09_http_handler/09_0009_cookie.py
tests/suites/1_stateful/09_http_handler/09_0011_concurrent_query.result
tests/suites/1_stateful/09_http_handler/09_0011_concurrent_query.sh

This PR introduces more robust temporary table management and reduces potential session invalidation issues caused by concurrent queries.
- **More robust implementation with slight efficiency tradeoff**
- Moved temporary table add/remove operations (to/from manager) to the interpreter level
- Now occurs immediately after temp table creation/dropping (instead of being handled by HTTP handler)
- Removed `INUSE` session state
- Rationale: This state indicated a query was running on the session (no refresh needed)
- Problem: Could lead to permanent cleanup failures if not properly reset in edge cases
- New approach: Refresh attempted on each request instead
- **Problem**: Concurrent queries (when …

refactor: simply management of tmp table in session.

---

Cargo.lock
src/query/management/Cargo.toml
src/query/management/tests/it/role.rs
src/query/management/tests/it/user.rs

Rewrite `user_api` tests with a fully functional `MetaStore`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18174)

refactor(query-management): rewrite `user_api` tests without mock

---

src/query/ee/src/storages/fuse/operations/ngram_index.rs
src/query/ee/tests/it/ngram_index/index_refresh.rs
src/query/storages/common/index/src/filters/bloom_filter.rs
src/query/storages/common/index/src/filters/xor8/mod.rs
src/query/storages/common/index/src/filters/xor8/xor8_filter.rs
src/query/storages/fuse/src/io/mod.rs
src/query/storages/fuse/src/io/read/bloom/block_filter_reader.rs
src/query/storages/fuse/src/io/read/bloom/column_filter_reader.rs
src/query/storages/fuse/src/io/write/bloom_index_writer.rs
src/query/storages/fuse/src/io/write/mod.rs
src/query/storages/fuse/src/io/write/stream/block_builder.rs

fix: 
- Refresh ngram index only evicts the meta cache before
- The cache key does not distinguish between bloom index and ngram index.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18170)

fix: Bloom filter not updated after refresh

---

src/meta/raft-store/src/leveled_store/key_spaces_impl.rs
src/meta/raft-store/src/leveled_store/leveled_map/compacting_data.rs
src/meta/raft-store/src/leveled_store/map_api.rs
src/meta/service/src/meta_service/meta_node.rs
src/meta/service/src/meta_service/meta_node_kv_api_impl.rs
src/meta/service/src/meta_service/meta_node_status.rs
src/meta/service/src/metrics/meta_metrics.rs
src/meta/service/src/store/store_inner.rs
src/meta/service/tests/it/api/http/cluster_state_test.rs
src/meta/service/tests/it/api/http/metrics.rs
src/meta/types/src/sys_data.rs

This commit counts the user keys and the expirable keys when building a
snapshot, and save these two number in the snapshot meta data.
These two values are:
- reported to metrics(http API `/v1/metrics`) under the keys:
- `snapshot_primary_index_count`
- `snapshot_expire_index_count`
- and can be retrieved in the cluster-status http
API(`/v1/cluster/status`), in the key `snapshot_key_space_stat`, which
is a `BTreeMap` of `String` to `u64`:
```
"snapshot_key_space_stat": {
"exp-": 1,
"kv--": 5
},
```
Also refactors MetaKvApi implementation into a standalone struct for
better separation of concerns.
This commit is Non-Breaking despite on-disk format modification.
- - - …

feat(meta-service): add expirable keys stat to metrics and cluster-status API

---

Cargo.lock
Cargo.toml
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/meta_service/meta_node.rs
src/meta/service/src/meta_service/meta_node_kv_api_impl.rs
src/meta/service/src/meta_service/mod.rs
src/meta/service/tests/it/meta_node/meta_node_kv_api.rs
src/meta/service/tests/it/meta_node/meta_node_kv_api_expire.rs
src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs

But not when it is added to or removed from the `Dispatcher`.
Because a sender can be removed more than once, since internally the
dispatcher is a span-map, it stores multiple instance of a sender.
- See: https://github.com/databendlabs/watcher/pull/7
This should fix the negative watcher number issue:
This commit extracts the implementation of `KVApi` to a standalone
struct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18182)

fix(meta-service): watcher metrics should be updated when sender is created and dropped

---

src/query/expression/src/aggregate/group_hash.rs
src/query/expression/src/aggregate/payload_flush.rs
src/query/expression/src/aggregate/payload_row.rs
src/query/expression/src/kernels/group_by_hash/method_fixed_keys.rs
src/query/expression/src/types/decimal.rs
src/query/expression/src/types/nullable.rs
src/query/functions/src/aggregates/adaptors/aggregate_sort_adaptor.rs
src/query/functions/src/aggregates/aggregate_arg_min_max.rs
src/query/functions/src/aggregates/aggregate_array_agg.rs
src/query/functions/src/aggregates/aggregate_array_moving.rs
src/query/functions/src/aggregates/aggregate_count.rs
src/query/functions/src/aggregates/aggregate_covariance.rs
src/query/functions/src/aggregates/aggregate_distinct_state.rs
src/query/functions/src/aggregates/aggregate_histogram.rs
src/query/functions/src/aggregates/aggregate_json_array_agg.rs
src/query/functions/src/aggregates/aggregate_json_object_agg.rs
src/query/functions/src/aggregates/aggregate_markov_tarin.rs
src/query/functions/src/aggregates/aggregate_quantile_tdigest.rs
src/query/functions/src/aggregates/aggregate_quantile_tdigest_weighted.rs
src/query/functions/src/aggregates/aggregate_retention.rs
src/query/functions/src/aggregates/aggregate_scalar_state.rs
src/query/functions/src/aggregates/aggregate_st_collect.rs
src/query/functions/src/aggregates/aggregate_string_agg.rs
src/query/functions/src/aggregates/aggregate_unary.rs
src/query/functions/src/aggregates/aggregate_window_funnel.rs
src/query/functions/src/aggregates/aggregator_common.rs
src/query/service/src/pipelines/processors/transforms/aggregator/transform_aggregate_final.rs
tests/sqllogictests/suites/query/functions/02_0000_function_aggregate_list.test

- When decimal is used as an aggregate group by column (also distinct, union), decimal64 is used.
- Refactored `array_agg` and fixed zst support (since borsh doesn't support zst)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18171)

feat(query): when decimal is used as an aggregate group by column, decimal64 is used

---

src/query/service/src/pipelines/builders/builder_async_function.rs
src/query/service/src/pipelines/builders/builder_fill_missing_columns.rs
src/query/service/src/pipelines/builders/builder_mutation.rs
src/query/service/src/pipelines/processors/transforms/mod.rs
src/query/service/src/pipelines/processors/transforms/transform_async_function.rs
src/query/service/src/pipelines/processors/transforms/transform_branched_async_function.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
tests/sqllogictests/suites/base/05_ddl/05_0036_sequence.test
tests/sqllogictests/suites/stage/sequence_as_default.test

chore(query): 
1. make async function works within local counters
2. add settings `sequence_step_size`, default to 65536
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18178)

chore(query): make async function works within local counters

---

Cargo.lock
Cargo.toml
src/meta/raft-store/src/leveled_store/leveled_map/compacting_data.rs
src/meta/raft-store/src/state_machine_api_ext.rs
src/meta/raft-store/src/utils.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/meta_service/meta_node.rs

Fix blocking issue during initialization data transmission.
Problem:
When establishing a watch stream, the meta-service sends large amounts of
initialization data to the client. During this transmission, other events
are blocked until completion, including add-watcher commands.
This creates a deadlock: if initialization data is large, it blocks all
subsequent Dispatcher operations. When a second watch request arrives,
it must wait for the first one to complete sending all initialization data.
Since adding a new watcher requires holding the state machine lock,
multiple concurrent watch requests will block the state machine entirely,
causing timeouts for other requests.
Solution:
Make the …

refactor: implement cooperative state machine for range/list operations

---

src/query/expression/src/utils/date_helper.rs
src/query/functions/src/scalars/timestamp/src/datetime.rs
src/query/functions/src/scalars/timestamp/src/interval.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test

ADD_MONTHS returns slightly different results than DATEADD used with a MONTH component:
- For both ADD_MONTHS and DATEADD, if the result month has fewer days than the original day, the result day of the month is the last day of the result month.
- For ADD_MONTHS only, if the original day is the last day of the month, the result day of month will be the last day of the result month.
In main:
```sql
select add_months('2025-04-30',1)
----
2025-05-30
```
In PR:
```sql
select add_months('2025-04-30',1)
----
2025-05-31
```
- fixes: https://github.com/databendlabs/databend/issues/18200
- - - …

fix(query): add_months need to respect last day of month

---

src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/metrics/meta_metrics.rs
src/meta/service/tests/it/api/http/metrics.rs

Add two metrics:
- the number of items sent when sending watch stream initialization
data(all existent key-values),
- and the number of items sent when a key-value changed
```
metasrv_meta_network_watch_initialization_total 2753400
metasrv_meta_network_watch_change_total         2753394
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18209)

feat(meta-service): add metrics for watch stream

---

src/meta/client/src/grpc_action.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/metrics/meta_metrics.rs
src/meta/service/tests/it/api/http/metrics.rs

Previously, stream-based operations like `mget` and `list` were only counted
as single RPCs in our metrics system, despite potentially sending large
volumes of data. For example, a single `list` RPC fetching a large directory
would appear the same as a simple operation in our metrics.
This commit adds granular metrics to track the actual number of items sent
in stream operations with the following counters:
```
metasrv_meta_network_stream_get_item_sent_total
metasrv_meta_network_stream_mget_item_sent_total
metasrv_meta_network_stream_list_item_sent_total
```
- - - …

feat(meta-service): add metrics for stream access operations

---

src/meta/service/src/metrics/meta_metrics.rs
src/meta/service/src/metrics/mod.rs
src/meta/service/src/store/store_inner.rs
src/meta/service/tests/it/api/http/metrics.rs

Add two snapshot metrics:
- whether it is building snapshot,
- and the entries written to snapshot.
```
metasrv_raft_storage_snapshot_building                0
metasrv_raft_storage_snapshot_written_entries_total   123
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18212)

feat(meta-service): add metrics for snapshot building

---

.github/scripts/retry_failed_jobs.js

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18225)

ci: fix check failure jobs

---

src/meta/proto-conv/tests/it/main.rs
src/meta/proto-conv/tests/it/v129_vector_datatype.rs
src/query/functions/src/scalars/array.rs
src/query/functions/src/scalars/variant.rs
src/query/functions/tests/it/scalars/array.rs
src/query/functions/tests/it/scalars/testdata/array.txt
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/functions/tests/it/scalars/testdata/variant.txt
src/query/functions/tests/it/scalars/variant.rs
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/functions/02_0061_function_array.test
tests/sqllogictests/suites/query/functions/02_0065_function_json.test

This PR introduces a set of array functions to Databend, designed to enhance compatibility with Snowflake and provide more flexible array manipulation capabilities. These functions are implemented to seamlessly support both native `ARRAY` types and `VARIANT` types containing arrays.
**Functions:**
The following functions originally supported the Array type but not the Variant type:
*   `ARRAY_APPEND(array, element)`: Appends an element to the end of an array.
*   `ARRAY_CONTAINS(array, element)`: Returns true if the array contains the element.
*   `ARRAY_FLATTEN(array)`: Flattens a nested array into a single-dimensional array.
*   `ARRAY_INDEXOF(array, element)`: Returns the index of the first …

feat(query): Array Functions Supporting ARRAY and VARIANT Types

---

.github/scripts/retry_failed_jobs.js

Update instead of comment every time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18230)

ci: update comment for auto retry

---

src/query/service/src/sessions/session_ctx.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18236)

chore: avoid setting empty conf for Session

---

src/meta/app/src/data_id.rs
src/meta/client/src/lib.rs
src/meta/kvapi/src/kvapi/test_suite.rs
src/meta/process/src/kv_processor.rs
src/meta/raft-store/src/applier.rs
src/meta/types/build.rs
src/meta/types/proto/meta.proto
src/meta/types/proto/request.proto
src/meta/types/src/proto_display/mod.rs
src/meta/types/src/proto_ext/txn_ext.rs

`FetchAddU64` fetch the `u64` value of a key and add provided delta to
it, in one RPC.
The response `FetchAddU64Response` returns the key, the value before
update and the value after update.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18243)

feat(meta-service): add FetchAddU64 command to txn

---

Cargo.lock
src/common/storage/src/lib.rs
src/common/storage/src/operator.rs

This PR brings a fix from upstream crate `reqsign`: https://github.com/Xuanwo/reqsign/pull/572
In this PR, we use async lock instead to prevent concurrent update which lead to huge amount of STS requests been send while performing large queries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18265)

fix: Use async lock in reqsign to prevent concurrent update

---

src/query/expression/src/utils/mod.rs
src/query/functions/tests/it/scalars/arithmetic.rs

decimal64 not correct shrink_scalar
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18267)

fix(query): decimal64 not correct shrink_scalar

---

src/query/expression/src/expression.rs
src/query/expression/src/type_check.rs
src/query/expression/src/utils/filter_helper.rs
src/query/functions/tests/it/type_check.rs
src/query/storages/system/src/columns_table.rs
src/query/storages/system/src/indexes_table.rs
src/query/storages/system/src/tables_table.rs
src/query/storages/system/src/util.rs

fix(query): add find_leveled_eq_filters function
For filter in system tables like 
```
where catalog = 'x' and (database = 'a' or database = 'b' ) and table = 'c' and c like '%xxxx%'
```
We need to find that we only need to scan catalog "c"  and database "a" and "b"  and table "c" which improve the query performance by reducing meta key scan.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18264)

fix(query): add find_leveled_eq_filters function

---

src/query/ee/src/storages/fuse/operations/vacuum_table_v2.rs

Skipping vacuum inside explicit transaction
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18228)

fix: skipping vacuum inside explicit transaction

---

src/query/functions/src/scalars/comparison.rs
tests/sqllogictests/suites/mode/standalone/explain/explain_like.test

In Snowflake :
explain select * from t where id=1 or c like '%' the like expr will rewrite to `((OCTET_LENGTH(T.C)) >= 0)`
However, I think that if the column type is string/variant and not null, we can return true directly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18263)

refactor: String column like % can rewrite to true

---

src/meta/api/src/lib.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/api/src/sequence_api_impl.rs
src/meta/api/src/sequence_nextval_impl.rs
src/meta/app/src/app_error.rs
src/meta/app/src/schema/mod.rs
src/meta/app/src/schema/sequence.rs
src/meta/app/src/schema/sequence_storage.rs
src/meta/proto-conv/src/sequence_from_to_protobuf_impl.rs
src/meta/proto-conv/src/util.rs
src/meta/proto-conv/tests/it/main.rs
src/meta/proto-conv/tests/it/proto_conv.rs
src/meta/proto-conv/tests/it/v132_remove_sequence_meta_start.rs
src/meta/proto-conv/tests/it/v134_add_sequence_meta_storage_version.rs
src/meta/protos/proto/sequence.proto
src/meta/types/src/proto_display/mod.rs
src/meta/types/src/proto_ext/txn_ext.rs
src/query/service/src/interpreters/interpreter_sequence_create.rs
src/query/service/src/interpreters/interpreter_sequence_drop.rs

Introduce a new conflict-free sequence generator (storage version 1)
alongside the existing version 0 generator. The v1 generator eliminates
conflicts during concurrent sequence number generation by using a new
`FetchAddU64` operation instead of check-and-set semantics.
Key changes:
- V1 generator stores sequence values in external standalone keys
- Uses atomic FetchAddU64 operation for conflict-free updates
- V0 generator remains unchanged for backward compatibility
The FetchAddU64 operation performs in-place atomic updates without
requiring metadata assertions, eliminating conflicts between concurrent
sequence requests and improving throughput for sequence generation
workloads.
Both storage …

feat(meta): Add conflict-free sequence generator v1

---

src/query/storages/fuse/src/io/write/stream/column_statistics.rs
tests/sqllogictests/suites/base/issues/issue_18286.test

- fixes: #18286
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18287)

fix: handle Decimal64 properly in `column_update_hll_cardinality`

---

src/query/storages/fuse/src/fuse_table.rs
tests/sqllogictests/suites/ee/03_ee_vacuum/03_0018_transient_table.test

Currently transient table only ignores setting `data_retention_time_in_days`, it should ignore other retention period settings and table options as well:
- settings: `data_retention_num_snapshots_to_keep` 
- table options: `data_retention_period_in_hours` and `data_retention_num_snapshots_to_keep`
- fixes: #18293
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18295)

fix: transient should ignore retention period settings and table options

---

Cargo.lock
src/meta/client/Cargo.toml
src/meta/client/src/lib.rs
src/meta/client/src/required.rs
src/meta/kvapi-test-suite/src/test_suite.rs
src/meta/raft-store/src/leveled_store/leveled_map/leveled_map_test.rs
src/meta/raft-store/src/leveled_store/rotbl_seq_mark_impl.rs
src/meta/raft-store/src/sm_v003/compact_immutable_levels_test.rs
src/meta/raft-store/src/sm_v003/compact_with_db_test.rs
src/meta/service/tests/it/grpc/metasrv_grpc_kv_api_restart_cluster.rs
src/meta/service/tests/it/grpc/metasrv_grpc_kv_read_v1.rs
src/meta/service/tests/it/grpc/metasrv_grpc_watch.rs
src/meta/service/tests/it/meta_node/meta_node_kv_api_expire.rs
src/meta/types/proto/request.proto
src/meta/types/src/cmd/meta_spec.rs
src/meta/types/src/lib.rs
src/meta/types/src/proto_display/seqv_display.rs
src/meta/types/src/proto_display/watch_display.rs
src/meta/types/src/proto_ext/seq_v_ext.rs
src/meta/types/src/proto_ext/watch_ext.rs
src/meta/types/src/proto_ext/watch_ext/event_ext.rs
src/meta/types/src/seq_value/kv_meta.rs
src/meta/types/src/time.rs

Extend expiration time support to accept both seconds and milliseconds
while maintaining backward compatibility. The meta-service now stores
both time formats in the existing `expire_at` field and automatically
detects the format based on value magnitude.
Detection logic:
- Values > 100_000_000_000 are treated as milliseconds
- Values ≤ 100_000_000_000 are treated as seconds
This threshold corresponds to timestamps after ~1973, ensuring reliable
differentiation between the two formats while supporting both legacy
second-based expiration times and new millisecond-precision requirements.
This is a non-breaking change that maintains full backward compatibility
with existing configurations using …

feat(meta-service): Add millisecond precision for expiration times

---

src/query/storages/system/src/columns_table.rs
src/query/storages/system/src/databases_table.rs
src/query/storages/system/src/indexes_table.rs
src/query/storages/system/src/locks_table.rs
src/query/storages/system/src/notification_history_table.rs
src/query/storages/system/src/streams_table.rs
src/query/storages/system/src/tables_table.rs
src/query/storages/system/src/task_history_table.rs
src/query/storages/system/src/util.rs
tests/sqllogictests/suites/tpch_iceberg/utils.test

1. delete find_eq_filter
2. replace find_database_table_filter to extract_leveled_strings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18297)

refactor: replace find_database_table_filter to extract_leveled_strings

---

src/meta/raft-store/src/applier/mod.rs
src/meta/raft-store/src/sm_v003/sm_v003.rs
src/meta/raft-store/src/sm_v003/sm_v003_test.rs
src/meta/raft-store/src/state_machine_api.rs
src/meta/raft-store/src/state_machine_api_ext.rs
src/meta/service/tests/it/meta_node/mod.rs
src/meta/service/tests/it/meta_node/t90_time_revert_cross_snapshot_boundary.rs

Fix potential state machine inconsistencies caused by the non-persisted
`expire_cursor` field. While inconsistencies were rare, the transient
state could cause meta-service nodes to have divergent views of the
expiration processing state.
Root cause:
The `expire_cursor` was maintained as transient state outside the
replicated state machine, making it possible for nodes to have different
cursor positions after restarts or network partitions.
Solution:
Remove the non-persisted `expire_cursor` entirely to ensure all state
machine operations are fully deterministic and consistently replicated
across all meta-service nodes.
This change eliminates the race condition and guarantees state machine …

fix(meta-service): Remove transient `expire_cursor` to prevent state inconsistency

---

src/query/expression/src/utils/date_helper.rs
src/query/functions/src/scalars/timestamp/src/datetime.rs
tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test

1. in calc_date_to_timestamp if the date's tomorrow or yesterday can not be calc directly calc ts with offset.
select * from t;
╭────────────────╮
│       c1       │
│ Nullable(Date) │
├────────────────┤
│ 9999-12-31     │
╰────────────────╯
1 row read in 0.044 sec. Processed 1 row, 5 B (22.73 rows/s, 113 B/s)
In main:
```
root@localhost:8000/default/default> select to_string(c1,'%Y') from t;
error: APIError: QueryFailed: [1006]Calc tomorrow midnight with error parameter 'year' with value 1 is not in the required range of -9999..=9999 while evaluating function `to_timestamp('9999-12-31')` in expr `CAST(t.c1 (#0) AS Timestamp NULL)`, during run expr: `to_string(CAST(t.c1 (#0) AS Timestamp …
```

fix(query): to_string(DateColumn, format) should success if date = 9999-12-31

---

src/query/ast/src/ast/statements/table.rs
src/query/ast/tests/it/testdata/stmt.txt
src/query/storages/fuse/src/operations/changes.rs

With the introduction of the `auto_materialize_cte` optimization, Common Table Expressions (CTEs) in standard streams will now be automatically materialized, making the use of the materialized keyword unnecessary. 
In case of encountering the error `"can not use temp table in HTTP handler if cookie is not enabled"`, users can resolve the issue by disabling the `enable_auto_materialize_cte` setting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18327)

chore: remove materialized keyword for standard stream

---

scripts/selfhost/check_bad_tables.sh
scripts/selfhost/fetch_log.sh
src/query/catalog/src/plan/stream_column.rs
src/query/expression/src/schema.rs
src/query/service/src/pipelines/processors/transforms/transform_resort_addon_without_source_schema.rs
src/query/sql/src/executor/physical_plans/physical_add_stream_column.rs
src/query/sql/src/planner/binder/bind_mutation/bind.rs
src/query/sql/src/planner/binder/stream_column_factory.rs
src/query/sql/src/planner/execution/stream_column.rs
src/query/sql/src/planner/semantic/type_check.rs
src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/operations/changes.rs
src/query/storages/stream/src/stream_table.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0011_change_tracking.test
tests/sqllogictests/suites/ee/06_ee_stream/06_0000_stream.test
tests/sqllogictests/suites/ee/07_hilbert_clustering/07_0001_change_tracking.test
tests/sqllogictests/suites/query/functions/02_0005_function_compare.test

1. **Added `equal_null` function**: A new function that simplify NULL value comparisons. Users can now use this function in SQL queries to easily compare NULL values, improving code readability and simplicity.
```sql
> select equal_null(1, 1), equal_null(1,null), equal_null(null,null), equal_null(1,0);
╭────────────────────────────────────────────────────────────────────────────────────╮
│ equal_null(1, 1) │ equal_null(1, NULL) │ equal_null(NULL, NULL) │ equal_null(1, 0) │
│      Boolean     │       Boolean       │         Boolean        │      Boolean     │
├──────────────────┼─────────────────────┼────────────────────────┼──────────────────┤
│ true             │ false               │ true …
```

feat(storage): capture only changed rows in standard stream

---

src/query/expression/src/utils/filter_helper.rs
src/query/functions/tests/it/type_check.rs
tests/sqllogictests/suites/base/01_system/01_0001_system_tables.test

fix(query): fix find_leveled_eq_filters works with not in
fixes #18332
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18334)

fix(query): fix find_leveled_eq_filters works with not in

---

Cargo.lock
Cargo.toml
src/meta/raft-store/src/leveled_store/db_builder.rs
src/meta/raft-store/src/leveled_store/db_map_api_ro_test.rs
src/meta/raft-store/src/leveled_store/db_open_snapshot_impl.rs
src/meta/raft-store/src/sm_v003/compact_with_db_test.rs
src/meta/raft-store/src/sm_v003/open_snapshot.rs
src/meta/raft-store/src/sm_v003/received.rs
src/meta/raft-store/src/sm_v003/receiver_v003.rs
src/meta/raft-store/src/sm_v003/snapshot_loader.rs
src/meta/raft-store/src/sm_v003/snapshot_store_v003.rs
src/meta/raft-store/src/sm_v003/temp_snapshot_data.rs
src/meta/raft-store/src/sm_v003/writer_v003.rs
src/meta/raft-store/src/snapshot_config.rs
src/meta/service/src/meta_service/raft_service_impl.rs
src/meta/service/src/store/raft_state_machine_impl.rs
src/meta/types/src/snapshot_db.rs

**What's Changed for Users:**
- **Storage is now pluggable** - You'll need to provide a storage instance when creating or opening Rotbl files. This change makes it possible to use different storage backends beyond just the filesystem
- **Codec functionality moved** - The encoding/decoding features have been moved to a separate `codeq` library, which means better code sharing across projects
- **Better async support** - Fixed thread safety issues so Rotbl works more reliably in async applications
- **Improved backwards compatibility** - Added extensive testing to ensure your existing data files will always work with newer versions
**New Capabilities:**
- **Flexible storage backends** - The new …

refactor(meta-service): upgrade snapshot storage(rotbl)

---

src/query/ast/src/ast/statements/statement.rs
src/query/ast/src/ast/statements/user.rs
src/query/ast/src/parser/statement.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/stmt-error.txt
src/query/ast/tests/it/testdata/stmt.txt
src/query/service/src/interpreters/interpreter_role_set_secondary.rs
src/query/service/src/sessions/session_privilege_mgr.rs
src/query/service/tests/it/servers/http/http_query_handlers.rs
src/query/sql/src/planner/binder/ddl/role.rs
src/query/sql/src/planner/plans/ddl/account.rs
tests/suites/0_stateless/18_rbac/18_0009_set_role.result
tests/suites/0_stateless/18_rbac/18_0009_set_role.sh

Extending the SET SECONDARY ROLES command to allow users to specify a comma-separated list of desired secondary roles.
Syntax Example:
```sql
SET SECONDARY ROLES role_name_1, role_name_2;
```
- fixes: https://github.com/databendlabs/databend/issues/18325
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18337)

feat(query): Enhance SET SECONDARY ROLES to Specify Role Lists

---

.github/actions/publish_binary/action.yml
.github/actions/publish_deb/action.yml

R2 is unstable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18346)

ci: ignore upload R2 failure for release

---

scripts/selfhost/fetch_log.sh

fix: fetch log script need use the timestamp
The `event_date` field in the `query_history` table not include timezone information. Use `event_time` instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18352)

fix(script): fetch log script need use the timestamp

---

src/query/service/src/pipelines/builders/builder_join.rs
src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs
src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/cross_join.rs
tests/sqllogictests/suites/query/join/cross.test

The build side of HashJoin performs projection on the build block here. Cross join does not execute this path, causing column misalignment in the results.
https://github.com/databendlabs/databend/blob/4283b2d39757ecce23c7fd41573ddf215d245dd5/src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs#L559-L570
#18347
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18355)

fix: cross join return wrong column

---

src/query/settings/src/settings_default.rs

* Extend the default `short_sql_max_length` settings value from 128 to 2048
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18390)

chore: extend the short_sql_max_length to 2048

---

src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
src/query/sql/src/planner/planner.rs
src/query/sql/src/planner/plans/recluster.rs
tests/sqllogictests/suites/mode/cluster/enfore_local.test

chore(query): add enforce_local setting for disable distribute plan
```
set enforce_local = 1;
EXPLAIN SELECT number FROM numbers_mt(100000) GROUP BY number;
----
AggregateFinal
├── output columns: [numbers_mt.number (#0)]
├── group by: [number]
├── aggregate functions: []
├── estimated rows: 100000.00
└── AggregatePartial
├── group by: [number]
├── aggregate functions: []
├── estimated rows: 100000.00
└── TableScan
├── table: default.system.numbers_mt
├── output columns: [number (#0)]
├── read rows: 100000
├── read size: 781.25 KiB
├── partitions total: 2
├── partitions scanned: 2
├── push downs: [filters: [], limit: NONE]
└── estimated rows: 100000.00
```
- - - …

chore(query): add enforce_local setting for disable distribute plan

---

.github/workflows/reuse.linux.yml

`test_private_tasks` always fails in 2c8g, so try to improve the configuration
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18406)

ci: test_private_tasks uses 8c32g for testing

---

Cargo.lock
src/meta/proto-conv/Cargo.toml
src/meta/proto-conv/src/user_from_to_protobuf_impl.rs

When an older version of the application processes `UserGrantSet` data that contains `GrantEntry` objects with newly introduced `GrantObject` types, the `GrantEntry::from_pb` conversion can fail for those specific entries.
This commit modifies the `UserGrantSet::from_pb` function to gracefully handle such scenarios. If `GrantEntry::from_pb` returns an error (e.g., due to an unknown `GrantObject`), the error is now logged, and the problematic grant entry is skipped instead of causing the entire conversion to fail.
This ensures that users on older versions can still log in and use their available grants, providing better forward compatibility and robustness against evolving data schemas.
Without …

refactor(query): Gracefully handle unknown GrantEntry objects in UserGrantSet::from_pb

---

.github/workflows/reuse.linux.yml

test-private-task.sh currently always fails in CI and is temporarily closed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18408)

ci: temporarily close test_private_tasks

---

src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/stage/sequence_as_default.test

During the semantic analysis phase of the `nextval` function, the logic for generating `display_name` might not have fully considered SQL identifier quoting rules. If the sequence name was a reserved keyword or contained special characters, the generated `display_name` might not conform to SQL syntax, leading to inaccurate display or potential issues.
This change constructs the `display_name` by leveraging the `to_string()` method of the `ident` object returned by `normalize_identifier`. The `ident.to_string()` method already incorporates the logic for necessary identifier quoting according to SQL rules.
In main this will be failed:
```
root@localhost:8000/default/default> create or replace …
```

fix(query): AsyncFunctionCall::display_name should respect quota

---

src/query/expression/src/types.rs
src/query/expression/src/types/compute_view.rs
src/query/expression/src/types/decimal.rs
src/query/expression/src/types/number.rs
src/query/functions/src/aggregates/aggregate_string_agg.rs
src/query/functions/src/scalars/decimal/src/arithmetic.rs
src/query/functions/src/scalars/decimal/src/cast.rs
src/query/functions/src/scalars/decimal/src/math.rs
tests/sqllogictests/suites/query/functions/02_0000_function_aggregate_mix.test

```
select c1, string_agg(json_object('col', c2, 'no2', c3), ',') from convert_string group by c1;
----
a {"col":1,"no2":1},{"col":2,"no2":1},{"col":1,"no2":1},{"col":1,"no2":2},{"col":2,"no2":2}
b {"col":1,"no2":1},{"col":2,"no2":1},{"col":1,"no2":2}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18416)

fix: panic when the `string_agg` parameter is not of type string

---

Cargo.lock
Cargo.toml
src/meta/binaries/metactl/main.rs
tests/metactl/lua_util.lua
tests/metactl/subcommands/cmd_lua_grpc.py
tests/metactl/test_all_subcommands.py

Extend lua subcommand with gRPC client capabilities for meta operations:
- Add new_grpc_client() function to create gRPC client instances
- Implement async get() and upsert() methods with tuple error handling
- Export NULL constant to Lua environment for proper null handling
- Add comprehensive test suite for gRPC client functionality
- Support both stdin and file input modes for Lua scripts
The gRPC client returns (result, error) tuples following Lua conventions
and converts Rust structures to native Lua tables for better usability.
Example usage:
```lua
local client = new_grpc_client("127.0.0.1:9191")
-- Store a key-value pair
local result, err = client:upsert("my_key", "my_value")
if err …
```

feat(metactl): add lua grpc client functionality

---

Cargo.lock
Cargo.toml
src/meta/raft-store/src/applier/mod.rs
src/meta/raft-store/src/sm_v003/sm_v003.rs
src/meta/raft-store/src/state_machine_api_ext.rs
src/meta/raft-store/src/utils.rs

Update state-machine-api from v0.1.0 to v0.1.1 and improve expired
key cleanup efficiency:
- Add `cleanup_start_timestamp` tracking to avoid re-scanning processed
tombstone entries
- Simplify expired key removal logic by eliminating redundant checks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18441)

feat(meta): optimize expired key cleanup with time-range filtering

---

src/query/service/src/interpreters/access/privilege_access.rs
tests/suites/0_stateless/18_rbac/18_0007_privilege_access.result
tests/suites/0_stateless/18_rbac/18_0007_privilege_access.sh

only account_admin role can modify setting network_policy
User a without account_admin role should return error.
```sql
a@localhost:8000/default/default> SET global NETWORK_POLICY = '';
error: APIError: QueryFailed: [1063]Permission Denied: Setting of network_policy is restricted to account_admin role
a@localhost:8000/default/default> UNSET global NETWORK_POLICY;
error: APIError: QueryFailed: [1063]Permission Denied: Setting of network_policy is restricted to account_admin role
```
- fixes: #18454
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18456)

fix(query): only account_admin role can modify setting network_policy

---

Cargo.lock
Cargo.toml
src/query/expression/src/types/variant.rs
src/query/expression/src/utils/variant_transform.rs
src/query/expression/tests/it/row.rs
src/query/formats/src/field_decoder/fast_values.rs
src/query/formats/src/field_decoder/nested.rs
src/query/formats/src/field_decoder/separated_text.rs
src/query/functions/src/scalars/geographic/src/geometry.rs
src/query/functions/src/scalars/variant.rs
src/query/functions/tests/it/scalars/testdata/variant.txt
src/query/functions/tests/it/scalars/variant.rs

This PR optimizes `parse_json` performance by replacing the `BTreeMap` used for parsing JSON objects with a `Vec`.  The new implementation avoids the overhead of `BTreeMap` insertions, resulting in significant speedups.
Parsing large JSON objects shows substantial improvement:
*   **10M rows:** 10.617s -> 7.242s (~31% faster)
*   **100M rows:** 185.819s -> 73.034s (~60% faster)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18451)

refactor(query): Improve parse json performance

---

src/query/service/src/pipelines/processors/transforms/transform_udf_server.rs
src/query/sql/src/planner/optimizer/optimizer.rs
tests/sqllogictests/suites/udf_server/udf_server_test.test

This PR fix the bug when executing the udf function for update with WHERE filter condition
```sql
CREATE OR REPLACE FUNCTION url_len (VARCHAR) RETURNS BIGINT LANGUAGE python IMMUTABLE HANDLER = 'url_len' ADDRESS = 'http://0.0.0.0:8815';
CREATE OR REPLACE TABLE test(url STRING, length INT64);
INSERT INTO test (url) VALUES('databend.com'),('databend.cn');
UPDATE test SET length = url_len(url) WHERE length IS NULL;
error: APIError: QueryFailed: [1001]The number of columns in the data block does not match the number of fields in the table schema, block_columns: 3, table_schema_fields: 2
```
- - - …

fix(query): fix update set with udf and filter

---

src/common/compress/src/encode.rs

fix https://github.com/databendlabs/databend/issues/18484
the SQL can reproduce the bug, and passed after this pr.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18485)

fix: unload to zip support file larger than 4GB.

---

src/query/service/src/servers/http/v1/query/http_query.rs
src/query/storages/common/session/src/transaction.rs
tests/suites/1_stateful/09_http_handler/09_0008_forward.py

when execution fails, do the following at once, instead of waiting for commit/abort:
1.  release buffer memory
2. session leave the state of `sticky` 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18497)

refactor: polish handling of fail in transaction

---

src/query/expression/src/type_check.rs
src/query/functions/src/scalars/other.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/duckdb/sql/aggregate/group/group_by_grouping_sets.test

chore(query): fix grouping function in type checker
introduce a dummy function in register for 'grouping' function, it will be rewritten in `AggregateRewriter` later
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18502)

chore(query): fix grouping function in type checker

---

src/query/sql/src/executor/physical_plans/physical_aggregate_final.rs
src/query/sql/src/planner/plans/aggregate.rs
tests/sqllogictests/suites/tpcds/tpcds_agg.test

The patch makes the following changes:
1. aggregate.rs Modifications:
ignore group_by_shuffle_mode in grouping set query
2. New Test File: tpcds_agg.test:
Created a new test file at tests/sqllogictests/suites/tpcds/tpcds_agg.test.
The test includes setting a sandbox_tenant, using the tpcds database, setting the group_by_shuffle_mode to before_partial, including the Q5 test, and unsetting the group_by_shuffle_mode.
These changes enhance the Aggregate implementation by ignoring specific generated columns and introduce a new test to validate this behavior.
closes #18338
- - - …

fix(query): ignore group_by_shuffle_mode in grouping set query

---

.github/actions/test_compat_fuse/action.yml
src/meta/app/src/principal/mod.rs
src/query/ast/src/ast/statements/statement.rs
src/query/ast/src/parser/statement.rs
src/query/ast/tests/it/testdata/stmt.txt
src/query/management/src/role/role_api.rs
src/query/management/src/role/role_mgr.rs
src/query/service/src/interpreters/interpreter_role_create.rs
src/query/service/tests/it/storages/system.rs
src/query/sql/src/planner/binder/binder.rs
src/query/sql/src/planner/plans/ddl/account.rs
src/query/users/src/role_mgr.rs
src/query/users/src/user_api.rs
src/query/users/tests/it/role_cache_mgr.rs
src/query/users/tests/it/role_mgr.rs
tests/sqllogictests/suites/base/05_ddl/05_0014_ddl_create_role.test

support CREATE [ OR REPLACE ] <role_name>
```sql
statement ok
create role r1;
statement ok
grant select on *.* to role r1;
query T
show grants for role r1;
----
SELECT *.* NULL ROLE r1 GRANT SELECT ON *.* TO ROLE `r1`
statement ok
create or replace role r1;
query T
SELECT count() FROM show_grants('role', 'r1')
----
0
```
Note:
delete 306 307 and add 311 rbac compat test
In ths pr add replace role, and it's based on PB.
In 306/307(Before version-311) role is serde_json not support PB.
- fixes: #18499
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18500)

feat(query): support create or replace role

---

src/common/tracing/src/predefined_tables/history_tables.toml
src/query/service/src/history_tables/global_history_log.rs
src/query/service/src/history_tables/meta.rs

**fix: improve error handling in history table**
As a logging service, the history table should avoid exiting on recoverable errors. For issues such as storage being full or temporary network problems with storage, the system should keep retrying until the external service is healthy again.
**fix: `COPY INTO` should with `MAX_FILES` copy option**
If a lot of intermediate logging files stored in stage, the `COPY INTO` operation should enable a `MAX_FILES` option to avoid error: `Commit limit reached: 15,000 files for 'copy into table'`
- - - …

fix: improve error handling in history table

---

Cargo.lock
src/query/service/src/servers/http/middleware/session_header.rs
src/query/service/src/servers/http/v1/http_query_handlers.rs
tests/sqllogictests/Cargo.toml
tests/sqllogictests/src/client/global_cookie_store.rs
tests/sqllogictests/src/client/http_client.rs
tests/sqllogictests/src/client/mod.rs
tests/suites/1_stateful/09_http_handler/09_0007_session.py

1.  ignore X-DATABEND-SESSION if not enabled in caps
2.  http client in sql logic test use cookie instead of  X-DATABEND-SESSION 
3.  not check session id in state_handler
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18527)

refactor: polish session in HTTP handler

---

src/meta/control/src/import.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/api/http/v1/features.rs
src/meta/service/src/meta_service/meta_leader.rs
src/meta/service/src/meta_service/meta_node.rs
src/meta/service/src/store/lock_guards.rs
src/meta/service/src/store/mod.rs
src/meta/service/src/store/raft_state_machine_impl.rs
src/meta/service/src/store/store_inner.rs
src/meta/service/tests/it/meta_node/meta_node_kv_api_expire.rs
src/meta/service/tests/it/meta_node/meta_node_replication.rs
src/meta/service/tests/it/meta_node/t90_time_revert_cross_snapshot_boundary.rs
src/meta/service/tests/it/store.rs

Replace direct RwLock access with tracked guards that log lock
acquisition timing and purpose for better debugging visibility.
Key changes:
- Add new lock_guards.rs with WriteGuard and ReadGuard wrappers
- Replace state_machine.read/write() calls with get_state_machine_read/write()
- Add timing instrumentation with purpose tracking for all lock acquisitions
- Update all meta service components to use new guard pattern
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18534)

refactor(meta): add state machine lock guards with debugging

---

src/query/expression/src/function.rs
src/query/functions/src/scalars/binary.rs
src/query/service/src/sessions/query_ctx.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs
tests/sqllogictests/suites/query/functions/cast.test

When inserting parquet, the utf8 binary data of parquet may be mixed with base64 or hex, which makes it impossible to deserialize it in utf8.
example: 
```sql
copy into amazon_reviews_ngram from @data/ngram_test/amazon_reviews_2012.snappy.parquet file_format = (type = PARQUET);
```
The `amazon_reviews_2012.snappy.parquet` file contains a bit of base64, which causes the file to fail to be inserted successfully.
This pr provides the `enable_binary_to_utf8_lossy` option, which can be used to ignore abnormal utf8 using `string_from_lossy`
- - - …

chore: added the `enable_binary_to_utf8_lossy` option for inserting lossy utf8 data

---

Cargo.lock
Cargo.toml
src/meta/raft-store/src/sm_v003/writer_v003.rs
src/meta/service/src/store/lock_guards.rs
src/meta/service/src/store/store_inner.rs

Restructure load_block method to check cache before acquiring locks,
reducing contention and improving concurrent access performance.
- Add early cache check before lock acquisition
- Reduce lock scope to only critical sections
These changes improve cache hit performance and reduce lock contention
in multi-threaded scenarios.
Other changes:
- Refine state-machine locking log
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18541)

refactor(meta-service): optimize state machine block loading with early cache checks

---

src/query/ast/src/parser/common.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/expr-error.txt
src/query/ast/tests/it/testdata/stmt-error.txt
src/query/ast/tests/it/testdata/stmt.txt

chore(query): allow row as column ident
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18568)

chore(query): allow row as column ident

---

Cargo.lock
Cargo.toml
src/query/functions/tests/it/scalars/testdata/variant.txt
src/query/functions/tests/it/scalars/variant.rs
tests/sqllogictests/suites/query/functions/02_0048_function_semi_structureds_parse_json.test
tests/sqllogictests/suites/stage/formats/csv/csv_types.test

This PR extends the functionality of the `parse_json` function in Databend to include support for JSON5 syntax. This enhancement allows for more flexible and human-readable JSON parsing.
The following JSON5 features are now supported:
- **Hexadecimal Numbers:** The parser now recognizes and correctly parses hexadecimal number representations, including both integer and floating-point formats (e.g., `0xabc`, `0X123.56`).
- **NaN and Infinity:** Support for parsing `NaN` (Not a Number) and `Infinity` values, aligning with JSON5 specifications.
- **Single-Quoted Strings:** Strings can now be enclosed in single quotes (e.g., `'abcd'`).
- **Unquoted Object Keys:** Object keys within JSON objects …

feat(query): Enhance JSON parsing support extended json5 syntax

---

src/query/service/src/physical_plans/physical_plan.rs

This PR addresses the stack overflow issue introduced in commit c0f12f98 during the migration from enum-based to trait-based PhysicalPlan architecture. The issue manifested as SIGSEGV crashes in CI tests with 50+ repeated stack frames indicating infinite recursion in Clone operations.
- **Problem**: `#[recursive::recursive]` annotation on `Clone::clone()` method
- **Trigger**: The combination of `dyn_clone` trait objects + recursive annotation
- **Effect**: Infinite recursion when cloning complex physical plans
- **Evidence**: CI crash logs showing repeated `<unknown>@4f43b46` stack frames
- ✅ **Remove** `#[recursive::recursive]` from `Clone::clone()` method  
- ✅ **Preserve** other recursive …

fix(query): prevent stack overflow in PhysicalPlan recursion

---

src/common/exception/src/exception.rs
src/common/exception/tests/it/error_code_result_ext.rs
src/query/catalog/src/catalog/interface.rs
src/query/service/src/catalogs/iceberg/iceberg_catalog.rs
src/query/users/src/network_policy.rs
src/query/users/src/password_policy.rs
src/query/users/src/role_mgr.rs
src/query/users/src/user_stage.rs

Extend ErrorCodeResultExt trait with methods for all UNKNOWN_* error codes
including dictionary, role, network policy, stage, user, and others.
Refactor exists_* functions across catalog and user management to use
the enhanced API, replacing verbose match patterns with concise
.or_unknown_*()?.is_some() calls.
Extend error handling consistency by converting 5 methods in
iceberg_catalog.rs to use the ErrorCodeResultExt trait pattern.
- Replace verbose match statements with .or_unknown_database()/.or_unknown_table()
- Convert get_database, get_table_by_info, get_table, list_tables, list_tables_names
- Reduce boilerplate by ~25 lines while maintaining identical behavior
- Achieve consistent error …

refactor(exception): enhance ErrorCodeResultExt with comprehensive error codes

---

src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/metrics/meta_metrics.rs
src/meta/service/src/metrics/mod.rs
src/meta/service/tests/it/api/http/metrics.rs

- Remove deprecated rpc_delay_seconds metric completely
- Add rpc_delay_read_ms and rpc_delay_write_ms histograms for granular tracking
- Maintain backward compatibility with existing rpc_delay_ms histogram
- Categorize gRPC operations: transactions as Write, exports/status/info as Read
- Both new delay functions update the general rpc_delay_ms for backward compatibility
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18648)

feat: implement separate RPC delay metrics for read and write operations

---

src/meta/api/src/database_api.rs
src/meta/api/src/database_util.rs
src/meta/api/src/lib.rs
src/meta/api/src/schema_api.rs
src/meta/api/src/util.rs
src/meta/binaries/metabench/main.rs
src/query/service/src/catalogs/default/mutable_catalog.rs

Extract database operations into a separate trait following single
responsibility principle. This creates cleaner separation between
database and table operations.
- Create DatabaseApi trait with 9 database operations
- Add database_util module for database-specific utilities
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18650)

refactor(schema-api): extract DatabaseApi trait from SchemaApi

---

src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_build_state.rs
src/query/service/src/pipelines/processors/transforms/hash_join/runtime_filter/builder.rs
src/query/service/src/pipelines/processors/transforms/hash_join/runtime_filter/convert.rs
src/query/service/src/pipelines/processors/transforms/hash_join/runtime_filter/interface.rs
src/query/settings/src/settings_default.rs
src/query/settings/src/settings_getter_setter.rs

This PR refactors runtime filter handling to use configurable settings instead of hardcoded constants, and replaces manual nested OR expression construction with the or_filters function for better performance and cleaner code.
1. Replace Manual OR Expression Construction with or_filters
2. Make Runtime Filter Thresholds Configurable. If the number of rows on the build side exceeds the limit at runtime, runtime filter construction will be stopped
| Setting                          | Default  | 
|----------------------------------|----------|
| inlist_runtime_filter_threshold  | 1,024    |
| bloom_runtime_filter_threshold   | u64::MAX |
| min_max_runtime_filter_threshold | u64::MAX |
- - -
This …

refactor: refactor inlist runtime filter with  or_filters and add configurable runtime filter thresholds

---

src/query/expression/src/expression.rs
src/query/expression/src/utils/filter_helper.rs
src/query/sql/src/planner/binder/scalar_common.rs
src/query/sql/src/planner/optimizer/ir/stats/selectivity.rs
src/query/sql/src/planner/optimizer/optimizers/operator/decorrelate/decorrelate.rs
src/query/sql/src/planner/optimizer/optimizers/operator/filter/normalize_disjunctive_filter.rs
src/query/sql/src/planner/optimizer/optimizers/rule/factory.rs
src/query/sql/src/planner/optimizer/optimizers/rule/filter_rules/mod.rs
src/query/sql/src/planner/optimizer/optimizers/rule/filter_rules/rule_filter_flatten_or.rs
src/query/sql/src/planner/optimizer/optimizers/rule/filter_rules/rule_push_down_filter_join.rs
src/query/sql/src/planner/optimizer/optimizers/rule/join_rules/push_down_filter_join/extract_or_predicates.rs
src/query/sql/src/planner/optimizer/optimizers/rule/join_rules/push_down_filter_join/mark_join_to_semi_join.rs
src/query/sql/src/planner/optimizer/optimizers/rule/join_rules/rule_left_exchange_join.rs
src/query/sql/src/planner/optimizer/optimizers/rule/rule.rs
tests/sqllogictests/suites/mode/standalone/explain/explain.test
tests/sqllogictests/suites/mode/standalone/explain/filter.test
tests/sqllogictests/suites/mode/standalone/explain_native/explain.test
tests/sqllogictests/suites/query/functions/02_0046_function_logic.test

add `RuleFilterFlattenOr` is used to fold the outer `or` of the predicate in Filter into `or_filters`
Tips: 
example:
```sql
explain select number from numbers(6) where number = 1 or number = 5 or number = 3;
👇
explain select number from numbers(6) where or_filters(number = 1, number = 5, number = 3);
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18621)

feat: Add `RuleFilterFlattenOr`

---

src/meta/api/src/catalog_api.rs
src/meta/api/src/lib.rs
src/meta/api/src/schema_api.rs
src/meta/api/src/schema_api_test_suite.rs
src/query/catalog/src/catalog/manager.rs

Extract catalog operations into a separate trait following single
responsibility principle. This creates cleaner separation between
catalog and other schema operations, continuing the modularization
of the monolithic SchemaApi trait.
Key changes:
- Create `CatalogApi` trait in `src/meta/api/src/catalog_api.rs` with 4
catalog management methods (create, get, drop, list)
- Move catalog method implementations from `schema_api.rs` to the new
trait file while preserving all existing functionality
- Update `SchemaApi` trait bounds to include `CatalogApi` dependency
- - - …

refactor(schema-api): extract CatalogApi trait from SchemaApi

---

src/query/expression/src/utils/block_thresholds.rs
src/query/expression/tests/it/block_thresholds.rs
src/query/settings/src/settings_default.rs

1. Adjust the number of blocks based on block size thresholds. set `4 * min_bytes_per_block`(default 400M) to `max_bytes_per_block`(default 250M)
2. Enable distributed recluster 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18644)

chore: enable distributed recluster 

---

src/meta/api/src/database_api.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/api/src/table_api.rs
src/meta/app/src/schema/database.rs
src/meta/app/src/schema/table.rs
src/query/service/src/catalogs/default/mutable_catalog.rs
src/query/service/src/interpreters/interpreter_database_create.rs
src/query/service/src/interpreters/interpreter_table_create.rs
src/query/service/src/test_kits/fixture.rs
src/query/service/tests/it/storages/fuse/operations/create_or_replace_ownership_object.rs
src/query/service/tests/it/storages/fuse/operations/mod.rs
src/query/storages/common/session/src/temp_table.rs
src/query/storages/iceberg/src/catalog.rs
src/query/storages/iceberg/src/database.rs
tests/suites/0_stateless/18_rbac/18_0002_ownership_cover.sh

When using the CREATE OR REPLACE operation (such as replacing a database or table), the ownership key of the old object is not correctly deleted, resulting in confusion in permission management. This PR fixes this issue, ensuring that the ownership key of the old object is correctly removed when replacing the object.
More detailed info see: #18666
- CreateTable/DatabaseReplay add new item old_table/db_id.
- Only CreateOrReplace will make this item as Some(old_id) other case will directly return None.
- fixes: #18666
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18667) …

fix(rbac): create or replace ownership_object should delete the old ownership key

---

tests/sqllogictests/suites/base/05_ddl/05_0036_sequence.test
tests/suites/0_stateless/18_rbac/18_0016_seq_rbac.sh

Update the sqllogictest test cases
File: tests/sqllogictests/suites/base / 05 _ddl / 05 _0036_sequence test
Change
Test "CREATE SEQUENCE seq start = 1 increment = 1" and "CREATE SEQUENCE seq" side by side to ensure that both syntaxes can be executed correctly.
Ensure that the old version of the syntax (without the start and increment parameters) remains valid.
2. Update the RBAC test script
File: tests/suites/0_stateless/18_rbac/18_0016_seq_rbac.sh
Change
In the RBAC (Role-Based Access Control) scenario, test both the old and new versions of the CREATE SEQUENCE syntax simultaneously.
Ensure that different roles can correctly create sequences when enable_experimental_sequence_privilege_check is …

chore: add test about create sequence to keep old version

---

src/common/exception/src/exception_code.rs
src/meta/api/src/database_api.rs
src/meta/api/src/garbage_collection_api.rs
src/meta/app/src/app_error.rs
src/query/ee/tests/it/storages/fuse/operations/vacuum.rs
src/query/service/tests/it/storages/fuse/operations/mod.rs

- During vacuum dropped table, remove db_id_table_name kv pairs
- Utilize `DatabaseMeta::gc_in_progress` as a irreversible flag, once set to true, never flip back.
- during vacuuming dropped databases, `database_meta.gc_in_progress` will be set to true firstly, before removing any other database meta keys
- The db_id_table_name kv pairs are deleted in batch before other database meta keys are cleaned; thus if process crashed in the middle, the vacuum drop operation could be "roll forward" by retry.
- during `undrop database`, if `database_meta.gc_in_progress` is true, the operation will abort, and UnknowDatabse exception will be propagated to the frontend user
The kv txns used by `vacuum drop` …

fix: clean `db_id_table_name` during vacuuming dropped tables

---

Cargo.lock
src/query/functions/src/scalars/timestamp/Cargo.toml
src/query/functions/src/scalars/timestamp/src/datetime.rs
tests/sqllogictests/suites/query/functions/02_0002_function_cast.test

When executing an obviously incorrect expression like to_date('2010.10.'), the third-party parsing library dtparse will panic. This pr is used to handle panic and provide more humane error feedback.
example: 
```shell
set enable_strict_datetime_parser = 0;
SELECT to_date('2020.10.');
error: APIError: QueryFailed: [1104]index out of bounds: the len is 4 but the index is 4
SELECT to_date('2020.10.');
error: APIError: QueryFailed: [1006]cannot parse to type `DATE`. BadArguments. Code: 1006, Text = Date '2020.10.' is not recognized.. while evaluating function `to_date('2020.10.')` in expr `CAST('2020.10.' AS Date)`
```
- - - …

chore: catch `to_date`/`to_timestamp` unwrap

---

scripts/ci/ci-run-sqllogic-tests-cluster-nginx.sh
scripts/selfhost/fetch_meta_log.sh
scripts/selfhost/restore_logs.sh
src/query/service/src/sessions/queue_mgr.rs
src/query/service/tests/it/sessions/queue_mgr.rs
tests/nox/java_client/perpare.py
tests/nox/noxfile.py

Replace generic "[QUERY-QUEUE] Waiting for resource scheduling" messages with specific, actionable logs that show:
- **Configuration parameters**: `max_concurrency=5`, `max_running_queries=8`
- **Current usage**: `5/5 slots used`, `3 queries waiting`  
- **Clear status**: `[BLOCKED]` vs `[ACQUIRED]` with wait times
**Before:**
```
[QUERY-QUEUE] Waiting for resource scheduling
```
**After:**
```
[BLOCKED] Workload group 'analytics' local limit (max_concurrency=5): 5/5 slots used
[BLOCKED] Warehouse limit (max_running_queries=8): 8/8 slots used, 3 queries waiting
```
Users can now immediately identify bottlenecks and adjust the right configuration parameters.
- - -
This change is [<img …

feat: enhance resource scheduling logs with clear status and configuration details

---

src/query/ast/src/ast/statements/copy.rs
src/query/ast/src/parser/copy.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/stmt-error.txt
src/query/sql/src/planner/binder/copy_into_table.rs

rewrite parser for transform as
`copy into <table> from (select <columns> from <location>  <alias>) <copy_options>`
instead of `copy into <table> from (query) <copy_options>` and check query for limits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18681)

fix: forbid transform with where clause.

---

src/meta/binaries/metabench/main.rs
src/meta/semaphore/src/acquirer/permit.rs
src/meta/semaphore/src/errors/acquirer_closed.rs
src/meta/semaphore/src/errors/mod.rs
src/meta/semaphore/src/errors/processer_error.rs
src/meta/semaphore/src/meta_event_subscriber/processor.rs
src/meta/semaphore/src/meta_event_subscriber/subscriber.rs
src/meta/semaphore/src/semaphore.rs
src/meta/service/src/api/grpc_server.rs
src/meta/service/src/meta_service/meta_node.rs
src/meta/service/src/meta_service/runtime_config.rs
src/meta/service/tests/it/grpc/t51_metasrv_grpc_semaphore.rs

Refactor permit implementation to properly handle acquirer closure and
connection errors.
The permit now uses oneshot channels to detect when the underlying
permit entry is removed from meta-service, replacing the previous
BoxFuture. Because a future that is not polled will block the channel.
If the meta-service does not send an event for `permit_ttl * 1.5`,  the
connection will be re-established.
Add `AcquirerClosed` error type for client side close error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18690)

fix: meta-semaphore: re-connect when no event recevied

---

.github/actions/build_bindings_python/action.yml
.github/workflows/bindings.python.yml

- Fixed Python binding CI failures caused by virtual environment permission conflicts
- Added cleanup of existing `.venv` directories before creating new virtual environments
- Resolved Docker container vs GitHub runner permission mismatches
The Python binding CI was failing with "Permission denied" errors when trying to create virtual environments:
```
error: Failed to create virtual environment
Caused by: failed to create file `/runner/_work/databend/databend/src/bendpy/.venv/.gitignore`: Permission denied (os error 13)
```
This occurred because the maturin action runs in a Docker container with different user permissions than the GitHub runner, causing permission conflicts when subsequent …

fix(python-binding): resolve virtual environment permission conflicts in CI

---

.github/actions/test_private_tasks/action.yml

ci test-private-task recently encountered a warehouse test exception, which cannot be reproduced locally. Temporarily shut down the warehouse test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18709)

ci: Temporarily disable warehouse testing of private tasks

---

src/query/storages/stage/src/append/parquet_file/writer_processor.rs
tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_00_basic.result
tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_00_basic.sh

This PR fixes a compatibility issue when copying data to Parquet files. Without setting a default encoding, Decimal data might be encoded as `Delta_Byte_Array`, which could cause errors when opening this parquet file in other databases. Setting the encoding to `Plain` resolves this issue and ensures file compatibility. However, it also results in larger exported Parquet files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18724)

fix(query): Set Parquet default encoding to `PLAIN` to ensure data compatibility

---

src/query/functions/src/aggregates/aggregator.rs
tests/sqllogictests/suites/query/functions/02_0000_function_aggregate_min_max_any.test

Add ANY_VALUE as an alias for the ANY aggregate function to improve SQL compatibility.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18728)

feat: add ANY_VALUE as alias for ANY aggregate function

---

src/meta/api/src/database_api.rs
src/meta/api/src/database_util.rs
src/meta/api/src/schema_api.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/api/src/table_api.rs
src/meta/app/src/schema/database.rs
src/meta/app/src/schema/table.rs
src/meta/binaries/metabench/main.rs
src/query/ee/src/attach_table/handler.rs
src/query/ee/src/stream/handler.rs
src/query/service/src/catalogs/default/mutable_catalog.rs
src/query/service/src/interpreters/interpreter_database_create.rs
src/query/service/src/interpreters/interpreter_table_create.rs
src/query/service/src/interpreters/interpreter_view_create.rs
src/query/service/tests/it/catalogs/database_catalog.rs
src/query/service/tests/it/catalogs/immutable_catalogs.rs
src/query/service/tests/it/catalogs/test_error_handling.rs
src/query/sql/src/planner/plans/ddl/database.rs
src/query/storages/common/session/src/temp_table.rs
src/query/storages/iceberg/src/catalog.rs
src/query/storages/iceberg/src/database.rs

This PR refactors the code to ensure that the deletion of ownership keys and the replacement of tables/databases are performed within the same database transaction.
The goal is to maintain atomicity and data consistency, preventing partial failures that could lead to inconsistent states.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18739)

refactor: Make the ownership key deletion and table/database replace in the same transaction

---

src/query/service/src/servers/admin/v1/instance_status.rs
src/query/service/src/servers/http/v1/http_query_handlers.rs
src/query/service/src/sessions/session_mgr.rs
src/query/service/src/sessions/session_mgr_status.rs

update when
1.  post /v1/query
2. get /v1/query/<query_id>/<page_no> and found active HttpRequest
in /v1/status, return None if no query after start.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18750)

feat: /v1/status include last_query_request_at.

---

src/common/native/src/compression/binary/mod.rs

perf(native): preallocate zero offsets before compression
- preallocate shifted offsets in binary compression to avoid per-push bounds checks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18756)

refactor(native): preallocate zero offsets before compression

---

src/query/service/src/interpreters/util.rs
tests/compat_fuse/compat-logictest/rbac/fuse_compat_write
tests/sqllogictests/suites/base/15_procedure/15_0002_procedure.test
tests/sqllogictests/suites/base/15_procedure/15_0003_procedure_auto_commit.test
tests/sqllogictests/suites/base/15_procedure/15_0004_procedure_rollback.test
tests/sqllogictests/suites/base/15_procedure/15_0005_procedure_snapshots.test
tests/sqllogictests/suites/base/15_procedure/15_0006_procedure_merge_into.test
tests/sqllogictests/suites/base/15_procedure/15_0007_procedure_dedup_label.test
tests/sqllogictests/suites/base/15_procedure/15_0008_procedure_multi_transaction.test

1. By design, if a DDL statement is executed while a transaction is active, the DDL statement will implicitly commits the active transaction. This pr supports this behavior when ddl is in a procedure.
2.  Add stored procedure tests covering transaction scenarios including rollback behavior, snapshot management, merge operations, deduplication labels, and multi-procedure transactions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18753)

fix: auto commit of ddl not work when calling procedure in transaction

---

Cargo.lock
src/meta/api/src/garbage_collection_api.rs
src/meta/api/src/table_api.rs
src/query/ee/Cargo.toml
src/query/ee/tests/it/storages/fuse/operations/vacuum.rs

Tables implicitly dropped by the `create or replace` statement are not handled correctly:
The vacuum operation collects candidate tables according to the `drop_on` mark of table meta data, unfortunately, during `create or replace`, the table being replaced is NOT marked with `drop_on`.
In this PR,  table ids that have no `drop_on` marks, will also be selected as the candidates for vacuum, except it is the largest table id (of the same table name), which is the last visible table id that should be kept.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18751)

fix: vacuum tables that are dropped by `create or replace` statement

---

src/query/expression/src/evaluator.rs
tests/sqllogictests/suites/base/03_common/03_0025_delete_from.test

When `or_filters` has multiple parameters and all parameters are nullable columns, each parameter calculation will affect the `validity` of the subsequent parameters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18782)

fix: the result of the first parameter of `eval_or_filters` will affect the subsequent parameters

---

src/query/service/src/servers/admin/v1/instance_status.rs
src/query/service/src/servers/http/v1/query/http_query_manager.rs
src/query/service/tests/it/servers/admin/v1/status.rs

fix that last_query_started_at is None, but last_query_finished_at is not if receive kill/final on start before any query.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18792)

fix: /v1/status return  stop time without start time. 

---

src/meta/api/src/garbage_collection_api.rs
tests/sqllogictests/suites/ee/03_ee_vacuum/03_0020_issue_18794.test

The last table id in the TableIdHistoryIdent  KV pair, is NOT necessarily to be the largest one.
fixes: #18794 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18780)

fix: remove incorrect assertion in collecting dropped table ids

---

src/query/storages/system/src/columns_table.rs
tests/suites/0_stateless/18_rbac/18_0013_column_privilege.result
tests/suites/0_stateless/18_rbac/18_0013_column_privilege.sh

In main the code didn't properly handle db_id_opt from dbs_in_default_catalog, causing incorrect permission filtering for system.columns table queries.
This fix:
- Collects both database names and IDs from visibility checker
- Uses mget_database_names_by_ids to resolve missing names
- Properly filters databases with both name and ID information
- Fixes with column privilege checking
Fixes #18797
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18798)

fix(query): handle database ID properly in columns table permission check

---

src/meta/app/src/schema/table/mod.rs
src/meta/app/src/schema/table/ops.rs

- Created table/ops.rs with 5 TableMeta operation methods
- add_column: Add column with comment at specified index
- drop_column: Remove column by name
- fill_field_comments: Ensure field comments match schema length
- add_constraint: Add table constraint with validation
- drop_constraint: Remove table constraint with validation
- Moved table.rs to table/mod.rs (1485 lines)
- Added comprehensive unit tests (8 tests covering all methods)
Benefits:
- Clear separation between data structures and behaviors
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/databend/18816)

refactor(meta): extract TableMeta operations to dedicated ops module
