- .gitignore
- Makefile
- README.md
- docker/Dockerfile
eg:
```bash
$ docker run --rm  datafusedev/fuse-query
05:40:10 [ INFO] Options { log_level: "debug", num_cpus: 40, mysql_handler_port: 3307 }
05:40:10 [ INFO] Fuse-Query Cloud Compute Starts...
05:40:10 [ INFO] Usage: mysql -h127.0.0.1 -P3307
```
docker hub URL: https://hub.docker.com/r/datafusedev/fuse-query
> add run with docker example

- Cargo.toml
- benches/bench_main.rs
- benches/benchmarks/bench_aggregate.rs
- benches/benchmarks/mod.rs
- docs/sqlstatement/select.md
- docs/sqlstatement/set.md
- docs/system/system-tables.md
- src/contexts/context.rs
- src/contexts/options.rs
- src/datasources/system/numbers_stream.rs
- src/executors/executor_setting.rs
- src/servers/mysql/mysql_handler.rs
1. Improve numbers_mt generate source performance (About 2x improvement).
2. Introduce settings `mysql_listen_host`, defaults to `12.0.0.1` for security reason.
3. Set `max_block_size` to `65536` for better performance.
- fuse-query
```
mysql> SELECT count(number) FROM system.numbers_mt(10000000000);
+---------------+
| count(number) |
+---------------+
|   10000000000 |
+---------------+
1 row in set (0.28 sec)
mysql> SELECT max(number) FROM system.numbers_mt(10000000000);
| max(number) |
|  9999999999 |
1 row in set (0.45 sec)
mysql> SELECT avg(number) FROM system.numbers_mt(10000000000);
+--------------+
| avg(number)  |
+--------------+
| 4999999999.5 |
+--------------+
1 row in set (0.50 sec)
```
- ClickHouse 
```
:)  SELECT …
```
> Improve numbers_mt generate source performance 

- src/datasources/datasource.rs
- src/datasources/system/mod.rs
- src/datasources/system/one_table.rs
- src/datavalues/data_type.rs
- src/executors/executor_select_test.rs
- src/executors/executor_setting.rs
- src/planners/plan_parser.rs
- Add `system.one` table for dummy source.
- Queries without tables in from will add planer to read from this table, eg `select 1 + 1`
> [system-tables] Add system.one table

- src/datablocks/data_block.rs
- src/datasources/system/settings_table_test.rs
- src/datavalues/data_array_aggregate_test.rs
- src/datavalues/data_array_arithmetic_test.rs
- src/datavalues/data_array_comparison_test.rs
- src/datavalues/data_array_logic_test.rs
- src/datavalues/data_value_aggregate_test.rs
- src/datavalues/data_value_arithmetic_test.rs
- src/functions/aggregators/aggregator_test.rs
- src/functions/arithmetics/arithmetic_test.rs
- src/functions/comparisons/comparison_test.rs
- src/functions/logics/logic_test.rs
- src/processors/processor_empty_test.rs
- src/processors/processor_merge_test.rs
- src/rpcs/rpc/executor_service_test.rs
- src/rpcs/rpc/flight_service.rs
- src/rpcs/rpc/flight_service_test.rs
- src/rpcs/rpc/macros.rs
- src/rpcs/rpc/mod.rs
- src/transforms/transform_aggregator_partial.rs
- src/transforms/transform_aggregator_test.rs
- src/transforms/transform_filter_test.rs
- src/transforms/transform_limit_test.rs
- src/transforms/transform_projection_test.rs
- src/transforms/transform_remote_test.rs
- src/transforms/transform_source_test.rs
Add error for flight async service, if the pipeline error when exeucted, it will raise to the flight client.
- New Feature
#53 
None
> Add error for flight service async

- Makefile
- src/bin/fuse-query.rs
- src/clusters/cluster.rs
- src/clusters/cluster_test.rs
- src/clusters/node.rs
- src/functions/udfs/database_test.rs
- src/functions/udfs/to_type_name_test.rs
- src/functions/udfs/udf_example_test.rs
- src/planners/plan_scheduler_test.rs
- src/processors/pipeline_builder_test.rs
- src/rpcs/http/router.rs
- src/rpcs/http/v1/cluster.rs
- src/rpcs/http/v1/cluster_test.rs
- src/rpcs/http/v1/config.rs
- src/rpcs/http/v1/hello.rs
- src/rpcs/http/v1/mod.rs
- src/servers/mysql/mysql_handler.rs
- src/tests/service.rs
Steps:
* Start two FuseQuery servers with:
```
[node-1] ./target/release/fuse-query 
[node-2] ./target/release/fuse-query --http-api-address=127.0.0.1:8081 --metric-api-address=127.0.0.1:7071 --mysql-handler-port=3308 --rpc-api-address=127.0.0.1:9091
```
* Add nodes to cluster coordinator
```
[1] curl http://127.0.0.1:8080/v1/cluster/add -X POST -H "Content-Type: application/json" -d '{"name":"9090","address":"127.0.0.1:9090","cpus":8}'
[2] curl http://127.0.0.1:8080/v1/cluster/add -X POST -H "Content-Type: application/json" -d '{"name":"9091","address":"127.0.0.1:9091","cpus":8}'
```
- New Feature
#53 
UnitTest
> Distributed query engine PART-5

- src/rpcs/rpc/flight_service.rs
- src/rpcs/rpc/metrics.rs
- src/rpcs/rpc/mod.rs
http://127.0.0.1:7070/
flight_execute_cost{quantile="0"} 6.856427537
flight_execute_cost{quantile="0.5"} 6.856427537
flight_execute_cost{quantile="0.9"} 6.856427537
flight_execute_cost{quantile="0.95"} 6.856427537
flight_execute_cost{quantile="0.99"} 6.856427537
flight_execute_cost{quantile="0.999"} 6.856427537
flight_execute_cost{quantile="1"} 6.856427537
flight_execute_cost_sum 6.856427537
flight_execute_cost_count 1
- New Feature
#53 
None
> Add mertrics for flight service execute

- .github/workflows/fusequery-release.yml
Currently the fusequery-release action failed in https://github.com/datafuselabs/fuse-query/actions/runs/664914256/workflow
due to cargo build error:  
error running rustfmt: Os { code: 2, kind: NotFound, message: "No such file or directory" }
add rustfmt and clippy to toolchain should resolve the issue
resolve https://github.com/datafuselabs/fuse-query/issues/158
> [workflow] resolve release build fail

- Makefile
support to use custom docker hub and tag during build process
for example
```bash
make docker HUB=host TAG=beta1
```
it will build image host/fuse-query:beta1 in local environment(without push)
resolve https://github.com/datafuselabs/datafuse/issues/177
N/A
> [CI] support custom docker hub and tag

- rfcs/store/2021-03-23-store-design.md
With raft group and parquet, the design is simplified: no need to maintain column index manually; no block is required in a `partition`, etc.
> storage design: table->replicationgroup->partitions

- docs/overview/building-and-running.md
- fusequery/query/src/datasources/system/numbers_stream.rs
- Bug Fix
Fix segmentation fault in numbers_stream
SQL `select * from system.numbers_mt(0)` will trigger a segmentation fault. 
- Doc-Typo Fix 
Table name for test-drive specified in `overview/building-and-running.md` should be `numbers_mt`
>  Fix segmentation fault in numbers_stream

- fusequery/query/src/api/rpc/flight_client.rs
- fusequery/query/src/datasources/datasource.rs
IMHO, It's more natural and efficient (at least in case of lengthy stream) to map a stream into another one.
- Improvement
N/A
Related test cases passed, no extra tests.
> Returns `SendableDataBlockStream` by stream mapping

- common/datablocks/src/lib.rs
- common/datavalues/src/lib.rs
- common/functions/src/aggregators/mod.rs
- common/functions/src/arithmetics/mod.rs
- common/functions/src/comparisons/mod.rs
- common/functions/src/logics/mod.rs
- common/functions/src/udfs/mod.rs
- common/infallible/src/lib.rs
- common/streams/src/lib.rs
- fusequery/query/src/api/http/v1/mod.rs
- fusequery/query/src/api/rpc/mod.rs
- fusequery/query/src/clusters/mod.rs
- fusequery/query/src/datasources/local/mod.rs
- fusequery/query/src/datasources/system/mod.rs
- fusequery/query/src/interpreters/mod.rs
- fusequery/query/src/lib.rs
- fusequery/query/src/pipelines/processors/mod.rs
- fusequery/query/src/pipelines/transforms/mod.rs
- fusequery/query/src/sql/mod.rs
The #[cfg(test)] annotation on the tests module tells Rust to compile and run the test code only when you run cargo test, not when you run cargo build. 
More to https://doc.rust-lang.org/book/ch11-03-test-organization.html#the-tests-module-and-cfgtest
- Improvement
#232 
UnitTests
> Add #[cfg(test)] to _test mod

- fusequery/query/src/bin/fuse-query.rs
fix the startup info
- Bug Fix
No
checkout the info
before
```
[2021-04-07T09:52:48Z INFO  fuse_query] Metric API server listening on 127.0.0.1:7070
[2021-04-07T09:52:48Z INFO  fuse_query] HTTP API server listening on 127.0.0.1:7070
[2021-04-07T09:52:48Z INFO  fuse_query] RPC API server listening on 127.0.0.1:9090
[2021-04-07T09:52:48Z INFO  warp::server] Server::run; addr=127.0.0.1:8080
[2021-04-07T09:52:48Z INFO  warp::server] listening on http://127.0.0.1:8080 
```
after
```
[2021-04-07T09:46:41Z INFO  fuse_query] Metric API server listening on 127.0.0.1:7070
[2021-04-07T09:46:41Z INFO  fuse_query] HTTP API server listening on 127.0.0.1:8080
[2021-04-07T09:46:41Z INFO  fuse_query] RPC API server listening on 127.0.0.1:9090
[2021-04-07T09:46:41Z INFO  warp::server] Server::run; …
```
> fix http api port info

- Makefile
- charts/datafuse/.helmignore
- charts/datafuse/Chart.yaml
- charts/datafuse/templates/NOTES.txt
- charts/datafuse/templates/_helpers.tpl
- charts/datafuse/templates/configmap.yaml
- charts/datafuse/templates/deployment.yaml
- charts/datafuse/templates/hpa.yaml
- charts/datafuse/templates/ingress.yaml
- charts/datafuse/templates/service.yaml
- charts/datafuse/templates/serviceaccount.yaml
- charts/datafuse/templates/tests/test-connection.yaml
- charts/datafuse/values.yaml
- docs/overview/building-and-running.md
Adding a helm chart to deploy datafuse to k8s, 
-Build/Testing/Packaging Improvement
run
`make helm` and use mysql to connect to the NodePort following the helm Note:
```
NOTES:
1. connect to fuse-query mysql port:
export FUSE_MYSQL_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[0].nodePort}" services datafuse)
mysql -h127.0.0.1 -P$FUSE_MYSQL_PORT
export FUSE_HTTP_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[2].nodePort}" services datafuse)
curl http://127.0.0.1:$FUSE_HTTP_PORT/v1/configs
```
> add helm chart for datafuse

- fusequery/query/src/datasources/system/mod.rs
- fusequery/query/src/datasources/system/numbers_table_test.rs
Add a test to a current impl of `generate_parts`, to ensure that the impl on the store will have the same partitioning policy.
> [query] test: add test for NumbersTable::generate_parts

- common/flights/src/store_do_get.rs
- fusestore/store/Cargo.toml
- fusestore/store/proto/store_meta.proto
- fusestore/store/src/api/mod.rs
- fusestore/store/src/api/rpc/flight_service.rs
- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/api/rpc/mod.rs
- fusestore/store/src/api/rpc_service.rs
- fusestore/store/src/bin/fuse-store.rs
- fusestore/store/src/dfs/distributed_fs.rs
- fusestore/store/src/dfs/distributed_fs_test.rs
- fusestore/store/src/dfs/mod.rs
- fusestore/store/src/executor/action_handler.rs
- fusestore/store/src/executor/action_handler_test.rs
- fusestore/store/src/executor/mod.rs
- fusestore/store/src/fs/ifs.rs
- fusestore/store/src/fs/mod.rs
- fusestore/store/src/lib.rs
- fusestore/store/src/localfs/local_fs.rs
- fusestore/store/src/localfs/local_fs_test.rs
- fusestore/store/src/localfs/mod.rs
- fusestore/store/src/meta_service/meta.rs
- fusestore/store/src/meta_service/meta_service_impl.rs
- fusestore/store/src/meta_service/meta_service_impl_test.rs
- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/tests/mod.rs
- fusestore/store/src/tests/service.rs
- add a single node meta service to estimate framework design.
- add distributed fs, support only "add" operation. It writes the data file
locally and update changes to meta service.
- store flight service API: do_get() support pulling a file for replication.
- New Feature
- Refactor
> [store]: dfs with a naive central meta service.

- common/planners/src/plan_builder.rs
- fusequery/query/src/sql/plan_parser.rs
`SELECT name FROM system.tables ORDER BY database, name`
the last projection is: name, so the order by item `database` can not be found here.
Need push the `order by` front of the projection in common query.
But for the aggregation query, we keep after the aggregation projection.
- Bug Fix
Fixs #381 
> Fix up order by projection #381

- scripts/ci/fusequery-cluster-3-nodes.sh
- scripts/ci/fusequery-standalone.sh
Add timeout(10s) for CI port check
Fixes #456 
> Add timeout(10s) for CI port check

- tests/fuse-test
- tests/queries/0_stateless/00_0000_dummy_select_1.result
- tests/queries/0_stateless/00_0000_dummy_select_1.sql
- tests/queries/0_stateless/07_0000_use_database.result
- tests/queries/0_stateless/07_0000_use_database.sql
Support error message(stderr) to *.result, we can test error for normal case.
Fixes #403 
> fuse-test: Support error message(stderr) to *.result 

- Cargo.lock
- fusestore/store/Cargo.toml
- fusestore/store/proto/store_meta.proto
- fusestore/store/src/dfs/distributed_fs_test.rs
- fusestore/store/src/meta_service/meta_service_impl.rs
- fusestore/store/src/meta_service/meta_service_impl_test.rs
- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- fusestore/store/src/tests/logging.rs
- fusestore/store/src/tests/mod.rs
Using async-raft as a consensus engine to set up a strongly consistent kv
store as metadata service.
A store node maintains two services: meta API and flight API.
In this commit, the raft is backed with a pure memory store.
And unit test only covers single-node cluster and
one-leader-one-learner(non-voter) cluster.
```
flight-grpc     meta-grpc
|               |
'--.      .-----'
|      |
MetaNode
|     |
|    RaftNode
|  .--'   |
|  |      |
Storage   Network
```
- New Feature
Fix #490
> [store] meta data cluster impl with raft

- fusestore/store/src/meta_service/meta_service_impl.rs
- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- website/datafuse/docs/rfcs/store/2021-04-22-store-design.md
- Introduce `Cmd` to define meta-operation actions.
- Explains the organization of metadata-related components.
- Refactor: refine type names to reflect their actual purpose.
- New Feature
fixes #494
> [store] add Cmd to define meta OP. explain metadata components

- fusestore/store/src/dfs/distributed_fs.rs
- fusestore/store/src/lib.rs
- fusestore/store/src/meta_service/meta.rs
- fusestore/store/src/meta_service/meta_service_impl.rs
- fusestore/store/src/meta_service/meta_service_impl_test.rs
- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/placement.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- Add struct Meta containing all dfs meta data, such as file keys and
nodes in cluster.
- Provides 3 commands to write metadata: AddFile, SetFile and AddNode.
- Seperate keys and nodes read API: Meta::get_file() and Meta:get_node().
Writing to meta is still done with a single API, in the raft manner:
applying an raft log entry to the meta.
- Improvement
> [store] refactor: move meta into standalone struct.

- common/planners/src/plan_rewriter.rs
- common/runtime/src/runtime.rs
- fusequery/query/src/servers/mysql/mysql_handler.rs
Remove the unused max threads for tokio runtime in on_query
- Improvement
Unit Tests
> Remove the unused max threads for tokio runtime in on_query

- README.md
- website/datafuse/docs/overview/performance.md
Update FuseQuery v0.4.1 vs ClickHouse 21.4.6 performance comparsion
> Update FuseQuery v0.4.1 vs ClickHouse 21.4.6 performance comparsion

- fusestore/store/src/dfs/distributed_fs.rs
- fusestore/store/src/dfs/distributed_fs_test.rs
- fusestore/store/src/executor/action_handler_test.rs
- fusestore/store/src/meta_service/meta_service_impl.rs
- fusestore/store/src/meta_service/meta_service_impl_test.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- Dfs: operates meta through MetaNode, instead of through RPC.
- MetaNode: separate initialization functions:
- MetaNode::boot() to setup a new cluster with one node.
- MetaNode::boot_non_voter() to initialize a node that is going to
be added to an existent cluster.
- MetaNode::new() to start a initialized node that belongs to a
cluster.
- MetaNode: new() now gets everything ready. There is no need to start
meta-grpc manually.
- MetaNode: add several util func to operating on cluster info, such as
get_node_addr() and add_node().
- MetaNode: remove cached metrics data. Use raft metrics channel
instead, which provides blocking watch and data cache.
- MetaNode: add builder() to create a customizable constructor.
- MetaNode: support forwarded write to the remote leader. A non-leader node
use …
> [store] meta: support remote write; refactor boot()

- Cargo.lock
- common/exception/src/exception.rs
- fusequery/query/Cargo.toml
- fusequery/query/src/servers/clickhouse/clickhouse_handler.rs
Better exceptions for clickhouse server.
- Improvement
closes #537 
Unit tests.
> [exception] better exception

- Cargo.lock
- fusestore/store/Cargo.toml
- fusestore/store/proto/store_meta.proto
- fusestore/store/src/dfs/distributed_fs.rs
- fusestore/store/src/meta_service/meta.rs
- fusestore/store/src/meta_service/meta_service_impl.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- website/datafuse/docs/rfcs/store/2021-04-22-store-design.md
- Fix: update async-raft to an unmerged version to fix NonVoter restart bug:
A restarted NonVoter node should not be initialized with the role Follower.
See: https://github.com/async-raft/async-raft/pull/114
- Feature: add a channel(`applied_rx`) to raft store to watch applied index changes.
- Feature: add MetaNode::stop() to gracefully shut a node down.
- Refactor: Use string instead [u8] as raft message body, to make it easier to debug.
- Refactor: add more From/Into impl to simplify message transform.
- Refactor: add raft node id to tracing.
- Doc: describes cluster startup process.
- Test: add test of restarting a MetaNode, ensures state consistency, along with other lifecycle-related tests and consistency test.
- New Feature
- Bug Fix
- Improvement …
> [store] support restarting a MetaNode.

- common/planners/src/lib.rs
- common/planners/src/plan_aggregator_final.rs
- common/planners/src/plan_aggregator_partial.rs
- common/planners/src/plan_display.rs
- common/planners/src/plan_explain.rs
- common/planners/src/plan_expression.rs
- common/planners/src/plan_filter.rs
- common/planners/src/plan_having.rs
- common/planners/src/plan_limit.rs
- common/planners/src/plan_node.rs
- common/planners/src/plan_projection.rs
- common/planners/src/plan_select.rs
- common/planners/src/plan_sort.rs
- common/planners/src/plan_stage.rs
- common/planners/src/plan_visitor.rs
- common/planners/src/plan_walker.rs
- common/planners/src/plan_walker_test.rs
- fusequery/query/src/optimizers/optimizer_alias_push_down.rs
- fusequery/query/src/optimizers/optimizer_limit_push_down.rs
- fusequery/query/src/optimizers/optimizer_projection_push_down.rs
- fusequery/query/src/pipelines/processors/pipeline_builder.rs
- fusequery/query/src/planners/plan_scheduler.rs
This PR introduce a `PlanVisitor` that implements visitor pattern, which reference a rust-idiomatic visitor [syn](https://docs.rs/syn/1.0.72/syn/visit/index.html).
The motivation I file this PR is to provide a better way to implement optimizer. When I was trying to write some heuristic optimization rules, I found it's inconvenient to maintain state and partially delegate the logic of traversal to default implementation with current framework.
In this PR I provide a `PlanVisitor` trait and refactor the `ProjectionPushDown` optimization with visitor pattern which has passed regression unit test.
- Improvement
Unit Tests
> Introduce plan visitor to refine optimizer

- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- fusestore/store/src/tests/mod.rs
- fusestore/store/src/tests/seq.rs
- [store] test: use global mono-incr seq to generate port, to avoid port conflict during the concurrent test
- [store] refactor raftmeta test
- Improvement
Fixes #548
> [store] test: use global mono-incr seq to generate port, to avoid port conflict during the concurrent test

- Cargo.lock
- fusestore/store/Cargo.toml
async-raft merged the pr that fix follower-non-voter bug, update to track the latest rev.
- Improvement
> [store] update dep: async-raft tracks the latest self maintained version

- common/exception/src/exception.rs
- common/planners/src/plan_rewriter.rs
- fusequery/query/src/pipelines/transforms/transform_filter.rs
- fusequery/query/src/sql/plan_parser.rs
- fusequery/query/src/sql/sql_common.rs
fix typo
rename `ErrorCodes::SyntexException` to `ErrorCodes::SyntaxException`
- Other
Fixes #578
> fix typo `ErrorCodes::SyntexException`

- .github/workflows/performance-tests-standalone.yml
- Cargo.lock
- common/arrow/Cargo.toml
Change arrow to crate.io instead of git sha
- Improvement
Fixes #602 
Unit Tests
> Change arrow to crate.io instead of git sha

- .github/workflows/performance-tests-standalone.yml
- Bug Fix
Fixes #issue
Unit Tests
> Fix self build runner cargo dependency errros in Performance test

- Cargo.lock
- fusestore/store/Cargo.toml
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
Fixed several consistency issues:
- The applied index should not be set before the corresponding log
applied to state machine: https://github.com/async-raft/async-raft/pull/117
- An `append_entries` request should get a `ConflictOpt` response even
when it is a heartbeat rpc, i.e., no logs in the message:
https://github.com/async-raft/async-raft/pull/122
- Logs will be lost if raft replication switch from LaggingState to
LineRateState. When coming back to LineRateState, a leader should try
to collect all logs from storage:
https://github.com/async-raft/async-raft/pull/123
- When removing a candidate from raft group, the leader does not stop
sending log to it.  https://github.com/async-raft/async-raft/pull/124
- Bug Fix
- Improvement
#271
> [store] improve raft and simplify test cases

- fusequery/query/src/pipelines/transforms/transform_groupby_partial.rs
Fix some hotpath codes to improve the performance
Fix the performance drop introduced in #550
- Improvement
Fixes #619
Performances tests
> [groupby] fix some hotpath codes for performance

- fusequery/query/src/sql/plan_parser.rs
A simple fix that removes dummy metadata while constructing the plan for the `create table .... ` statement.
Fixes #581
Covered by existing tests
> Fixed #581 : dummy metadata removed

- Cargo.lock
- common/arrow/Cargo.toml
- fusestore/store/src/meta_service/raftmeta_test.rs
fix: corgo recompiles every crate no matter file changes
`arrow-flight/build.rs` depends on an absent file, in a standalone crate:
>    println!("cargo:rerun-if-changed=../format/Flight.proto");
which causes this crate(and other crates depend on it, i.e., every crate in datafuse!) to be re-built every single time no matter whether a file changed.
See https://github.com/rust-lang/cargo/pull/8927/files#diff-197a732275c32bdbdb079bdd92ac8a4ba585ee556ea978e9e661804eb76ce9eeR229-R232
>  * A build script prints `cargo:rerun-if-changed=foo` where `foo` is a file that
>    doesn't exist and nothing generates it. In this case Cargo will keep running
>    the build script thinking it will generate the file but nothing ever does. The
>    fix is to avoid printing `rerun-if-changed` in this scenario. …
> Fix unexpected recompile

- docker/Dockerfile
- docker/bootstrap.sh
integrate fusestore into current docker container, supposed to use for testing only because eventually, query and store should be deployed in seperate containers
Fixes #issue
resolve https://github.com/datafuselabs/datafuse/issues/639
Unit Tests
> standalone docker for testing

- fusequery/query/src/bin/fuse-query.rs
fuse-query process exit when any handler error
- Improvement
Fixes #677 
Unit Tests
> fuse-query process exit when any handler error

- Cargo.lock
- Cargo.toml
- common/building/Cargo.toml
- common/building/src/lib.rs
- fusequery/query/Cargo.toml
- fusequery/query/build.rs
- fusequery/query/src/configs/config.rs
- fusequery/query/src/datasources/system/contributors_table.rs
- fusestore/store/src/bin/fuse-store.rs
- fusestore/store/src/configs/config.rs
- `common/building` setup common building environment for both Query and Store.
- Generate the commit version in building phase, not in config parsing
phase any more.
- Add prefix `FUSE_` to our own env vars.
- Improvement
#271
> [building] refine: building helper crate: common/building

- Cargo.lock
- common/flights/src/dns_resolver_test.rs
- fusestore/store/Cargo.toml
- Use the master branch to ensure that at least it is available - https://github.com/drmingdrmer/async-raft
- Clean up warnings during testing - unused import
Fixes #688 
No test plan.
> [building] refine: fix dep and clean useless code

- .github/PULL_REQUEST_TEMPLATE.md
- .github/labeler.yml
- README.md
Add not for changelog label, fusebots will not show in the release CHNAGELOG.
Fixes #708 
Unit Tests
> Add pr-not-for-changelog label

- Cargo.lock
- common/datavalues/src/data_array_scatter.rs
- common/exception/src/exception.rs
- common/exception/src/exception_test.rs
- common/exception/src/lib.rs
- fusestore/store/Cargo.toml
- fusestore/store/src/api/rpc_service.rs
- fusestore/store/src/configs/config.rs
Usage:
```
use common_exception::ToErrorCodes;
let x = Err(std::fmt::Error {}).map_err_to_code(ErrorCodes::UnknownException, ||"");
assert_eq!( "Code: 1000, displayText = Error.", format!("{}", x.unwrap_err()));
```
#271
> [common/exception] add a trait `ToErrorCode` to let a user easily convert Result::Err to ErrorCodes error

- common/exception/src/exception.rs
- common/exception/src/exception_test.rs
- concat ErrorCodes with its `cause` in display_text, instead of using field `cause`
- add chained error test.
- Improvement
Remove unpreferred usage of `cause` mentioned in  #713
> [common/exception] concat ErrorCodes with its `cause` in display_text, instead of using `cause`

- common/exception/src/exception.rs
- common/planners/src/plan_statistics.rs
- fusestore/store/src/dfs/distributed_fs.rs
- fusestore/store/src/dfs/distributed_fs_test.rs
- fusestore/store/src/executor/action_handler_test.rs
- fusestore/store/src/fs/ifs.rs
- fusestore/store/src/localfs/local_fs.rs
- fusestore/store/src/localfs/local_fs_test.rs
- [common/exceptions] add 2 store errors.
- [store] `read_all()` returns ErrorCodes instead of anyhow::Error.
- [store] `read_all()` check file meta before returning file content.
- Improvement
#271
> [common/planners] simplify Statistics with Default

- fusestore/store/src/dfs/distributed_fs.rs
- fusestore/store/src/executor/action_handler_test.rs
- fusestore/store/src/localfs/local_fs.rs
- trace LocalFS and Dfs API at debug level.
- extract common code setting up a dfs to standalone function.
- Improvement
#271
> [store] refine: add tracing to FS-related API

- fusestore/store/src/meta_service/meta.rs
- fusestore/store/src/meta_service/meta_service_impl_test.rs
- fusestore/store/src/meta_service/meta_test.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- fusestore/store/src/tests/service.rs
- Add new storage `sequences` to Meta. Introduce a corresponding new
command `Cmd::IncrSeq`, to generate mono-incr sequence numbers.
This feature enables Store to generate a globally unique u64 number,
for a unique block/partition name.
`test_meta_server_incr_seq` shows how to use this feature.
- Simplify meta test cases by letting the state-machine test and the
meta service test share a common test case set.
- Remove unused codes etc.
- New Feature
#271
> [store/meta] feature: generate unique auto-incr number

- fusestore/store/src/meta_service/meta_service_impl_test.rs
- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- fusestore/store/src/meta_service/state_machine_test.rs
The meta server is no more than a state machine with log management.
Thus the command sequence that applies to the state-machine should also apply
to the meta server and both result in the same state.
The common test cases are extracted and are shared by both sets of
tests.
- Improvement
#271
> [store/meta] refine: the same test cases should be applied to both state-machine and the meta server

- Cargo.lock
- common/arrow/Cargo.toml
Just add simd feature for common-arrow to provide a way to enable `arrow/simd` support.
Related #329 #750
Unit Tests
> [common/arrow] add simd feature

- fusestore/store/src/dfs/distributed_fs_test.rs
- fusestore/store/src/executor/action_handler_test.rs
- fusestore/store/src/meta_service/meta_service_impl_test.rs
- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- fusestore/store/src/meta_service/state_machine.rs
- fusestore/store/src/tests/mod.rs
- fusestore/store/src/tests/service.rs
- move connection check to shared sub mod `tests`.
- Improvement
#271
> [store/dfs] test: add deep path test

- common/aggregate_functions/src/aggregate_combinator_distinct.rs
- fusestore/store/src/data_part/appender.rs
- fusestore/store/src/dfs/distributed_fs.rs
- fusestore/store/src/dfs/distributed_fs_test.rs
- fusestore/store/src/executor/action_handler.rs
- fusestore/store/src/fs/ifs.rs
- fusestore/store/src/localfs/local_fs.rs
- fusestore/store/src/localfs/local_fs_test.rs
> [store] refactor: IFileSystem API uses ref to str instead of String

- common/building/src/lib.rs
- fusequery/query/src/bin/fuse-query.rs
- fusequery/query/src/configs/config.rs
- fusequery/query/src/configs/config_test.rs
- fusestore/store/src/bin/fuse-store.rs
- fusestore/store/src/configs/config.rs
- fusestore/store/src/configs/config_test.rs
- fusestore/store/src/configs/mod.rs
Inside `build.rs`, the env vars such as `VERGEN_BUILD_SEMVER` is written
only to stdout thus it is impossible to reuse these vars to compose
`FUSE_COMMIT_VERSION`.
This patch fixes the issue by building `FUSE_COMMIT_VERSION` with a
`lazy_static` block from env vars in runtime.
- Bug Fix
https://github.com/datafuselabs/datafuse/pull/782#issuecomment-857051879
> [common/building] fix: fuse version should be built outside build.rs

- fusestore/store/proto/store_meta.proto
- fusestore/store/src/meta_service/meta_service_impl.rs
- fusestore/store/src/meta_service/meta_service_impl_test.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- Add `RetryableError` to indicate that the caller could choose to retry
an operation.
Non-retryable errors are returned in an `anyhow::Error`.
- The `write` family API(methods of `MetaNode` methods of
`MetaService`) returns two level result:
```
Result<
Result<ClientResponse, RetryableError>,
anyhow::Error
>
```
An `anyhow::Error` indicates something wrong and can not be dealt by
the program, such as a Storage error.
And it is converted to a `tonic::Status` error when responding grpc
client.
The inner `Result` should be well handled by the caller.
- To support the above protocol, another field `error` is added to
`RaftMes`, in order to transport an `RetryableError`
- Some of the `From` trait for …
> [store/meta] feature: deal with ForwardToLeader. Now every node can accept an meta write operation.

- common/datavalues/src/data_array_comparison.rs
- common/datavalues/src/data_array_comparison_test.rs
- common/datavalues/src/data_value_operator.rs
- common/datavalues/src/macros.rs
- common/functions/src/comparisons/comparison.rs
- common/functions/src/comparisons/comparison_like.rs
- common/functions/src/comparisons/comparison_not_like.rs
- common/functions/src/comparisons/comparison_test.rs
- common/functions/src/comparisons/mod.rs
- tests/suites/0_stateless/02_0005_function_compare.result
- tests/suites/0_stateless/02_0005_function_compare.sql
support `like` and `not like` function
- New Feature
Fixes #784
Unit Tests
> Support like & not like

- docker/bootstrap.sh
Without the new line, kubernetes deploy will encounter issue
standard_init_linux.go:219: exec user process caused: exec format error 
- Bug Fix
Fixes #issue
Unit Tests
> fix container deploy err

- Cargo.lock
- common/flights/Cargo.toml
- common/profiling/Cargo.toml
- common/runtime/Cargo.toml
- common/streams/Cargo.toml
- fusequery/benchmarks/nyctaxi/Cargo.toml
- fusequery/query/Cargo.toml
- fusestore/store/Cargo.toml
- fusestore/store/src/meta_service/meta_service_impl_test.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
After the lovely bot bumped tokio to v1.7.0, some ut cases hang (for far more than 60s). 
Backtrace shows that tokio is blocked while shutting down the runtime:
~~~
#12 0x0000562b2d0f1d2e in tokio::park::thread::CachedParkThread::block_on (self=0x7f4c623ee140,
f=0x7f4c623ee970)
at .../tokio-1.7.0/src/park/thread.rs:267
#13 0x0000562b2d0cce90 in tokio::runtime::enter::Enter::block_on (self=0x7f4c623ee1b0, f=0x7f4c623ee970)
at .../tokio-1.7.0/src/runtime/enter.rs:151
#14 0x0000562b2d096143 in tokio::runtime::blocking::shutdown::Receiver::wait (self=0x7f4c623ee970,
timeout=...)
at .../tokio-1.7.0/src/runtime/blocking/shutdown.rs:67
#15 0x0000562b2d094032 in …
> Fix: unit test hang after tokio version bumped to 1.7.0

- Makefile
- docker/perf-tool/Dockerfile
Support to run perf tool in a standalone docker image, easier for CI and testings
Fixes #issue
Unit Tests
> [Build/CI] perf-tool container

- fusequery/query/src/sql/sql_parser_test.rs
- fusequery/query/src/sql/sql_statement.rs
Fix style check in latest rust version.
```
error: very complex type used. Consider factoring parts into `type` definitions
--> fusequery/query/src/sql/sql_statement.rs:126:18
|
126 |         let res: IResult<&[u8], (&[u8], &[u8], &[u8], &[u8], &[u8], &[u8])> =
|                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
```
- Improvement
Unit Tests
> [sql] update hint parser for better format

- Cargo.lock
- fusestore/store/Cargo.toml
- fusestore/store/src/meta_service/meta_service_impl_test.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- Upgrade to tokio 1.7.1, revert redudent MetaNode::stop() before
exiting a test case.
- Upgrade async-raft to v0.6.2-alph, with fixes to member-change algo.
Now async-raft depends on tokio-1.7.1 too.
> fix: when handle_update_match_index(), non-voter should also be
> considered, because when member change a non-voter is also count as a
> quorum member
> fix: when calc quorum, the non-voter should be count
> Counting only the follower(nodes) as quorum for new config(c1) results
> in unexpected log commit.
> E.g.: change from 012 to 234, when 3 and 4 are unreachable, the first
> log of joint should not be committed.
- Upgrade tonic from 0.4 to 0.4.3
- Add tracing init to meta server tests.
#271
> [store] with tokio 1.7.1 it is ok to remove the workaround patches.

- fusequery/query/src/api/http_service.rs
- fusequery/query/src/bin/fuse-query.rs
- fusequery/query/src/metrics/metric_service.rs
- fusequery/query/src/metrics/metric_service_test.rs
- fusequery/query/src/metrics/mod.rs
Support graceful shutdown for Metrics API
- Improvement
Related #832
> ISSUES-832 support graceful shutdown for Metrics API

- Cargo.lock
- fusestore/store/Cargo.toml
- fusestore/store/src/meta_service/meta_service_impl_test.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
Oh yeah 65 LOC reduced! :DDD
- Improvement
#271
> [store] refine: use native waiting util to watch raft metrics changes.

- Cargo.lock
- common/exception/Cargo.toml
- common/exception/src/exception.rs
- common/exception/src/exception_test.rs
- fusequery/query/src/api/rpc/mod.rs
So that FuseQuery and FuseStore talks the same error exchange protocol.
- ErrorCode serialization in Query now depends on this feature.
- New Feature
#271
> [common/exceptions] feature: add convertion from and to tonic::Status

- .github/workflows/pr-audit.yml
- Cargo.lock
- README.md
- common/arrow/Cargo.toml
- common/datavalues/Cargo.toml
- common/datavalues/src/data_value_kernel.rs
- add pr-audit workflow (will fail now, but it works)
- check dependency status (auto & quick, but not accurate enough)
Related #852
No test plan.
> [security] Basic Audit

- Cargo.lock
- common/exception/src/exception.rs
- common/flights/Cargo.toml
- common/flights/src/store_client.rs
- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/configs/config.rs
- fusestore/store/src/tests/service.rs
- Add a transitional method that use ErrorCode instead of anyhow::Error.
- Fix: Config::default() should not try to parse cli args. Otherwise it
reads the cargo test arguments and result in an unexpected argument
error.
Add another method Config::empty() to build a default instance.
- New Feature
#271 
#774
> [store] feature: flight: add get_database()

- .gitignore
- Cargo.lock
- common/tracing/Cargo.toml
- common/tracing/src/lib.rs
- common/tracing/src/logging.rs
- fusequery/benchmarks/nyctaxi/src/bin/nyctaxi.rs
- fusequery/query/Cargo.toml
- fusequery/query/src/bin/fuse-query.rs
- fusequery/query/src/configs/config.rs
- fusequery/query/src/configs/config_test.rs
- fusequery/query/src/datasources/system/mod.rs
- fusequery/query/src/datasources/system/system_database.rs
- fusequery/query/src/datasources/system/tables_table_test.rs
- fusequery/query/src/datasources/system/tracing_table.rs
- fusequery/query/src/datasources/system/tracing_table_stream.rs
- fusequery/query/src/datasources/system/tracing_table_test.rs
- fusequery/query/src/servers/mysql/mysql_session.rs
- fusequery/query/src/sessions/context.rs
- fusequery/query/src/sessions/session.rs
- fusequery/query/src/sessions/sessions.rs
- fusequery/query/src/sessions/status.rs
- fusequery/query/src/tests/context.rs
- tests/data/logs/fuse-query.2021-06-25-04
Start fuse-query with TRACE:
```
FUSE_QUERY_LOG_LEVEL="TRACE" ./target/debug/fuse-query
```
Make some logs:
```
datafuse :) SELECT max(number) FROM numbers_mt(10000) GROUP BY number % 3, number % 4;
```
Analyze on system.tracing example:
```
datafuse :) select max(pid) from system.tracing group by hostname;
SELECT max(pid)
FROM system.tracing
GROUP BY hostname
Query id: 38359d89-0196-42f7-b47c-d7689fc38007
┌─max(pid)─┐
│   123240 │
└──────────┘
```
- New Feature
Fixes #873
Unit Tests
> ISSUE-873: system.tracing table

- common/metatypes/src/lib.rs
- fusestore/store/src/meta_service/meta.rs
- fusestore/store/src/meta_service/meta_test.rs
- fusestore/store/src/meta_service/raftmeta.rs
The underlaying data structure impl of an general purpose  distributed KV storage service.
The `value` in this kv service is versioned, i.e. every written value has a corresponding globally unique `sequence` number bound to it. Thus CAS can be done by specifying the expected version to modify.
RPC API is coming soon in next pr~ :DDD
- New Feature
#271
#883 
#900
> [store/meta] feature: add "unclassified" namespace to meta to store everything else a user need.

- common/infallible/src/exit_guard.rs
- common/infallible/src/lib.rs
- fusequery/query/src/servers/mysql/mysql_session.rs
try fix cannot destroy session when panic for MySQLHandler
- Improvement
#899
> ISSUE-899 try fix cannot destroy session when panic for MySQL

- common/exception/src/exception.rs
- common/exception/src/exception_test.rs
- common/exception/src/lib.rs
- common/exception/tests/prelude_test.rs
> [common/exception] feature: add convertion from &Status

- common/exception/src/exception.rs
- common/exception/src/exception_test.rs
Since the Err() does not have to be an `Error`, but instead, any type should be OK.
- Improvement
> [common/exception] refine: ToErrorCode should not expect E to be an std::error::Error in "Result<T, E>"

- common/exception/src/exception.rs
- fusestore/store/src/meta_service/meta.rs
- fusestore/store/src/meta_service/raftmeta.rs
> [store] refactor: raftmeta: use common/exception::ErrorCode instead of anyhow::Error if possible

- fusestore/store/src/bin/fuse-store.rs
- fusestore/store/src/configs/config.rs
* Tracing to rotate file by hour
* Default log directory is _log
- Improvement
Fixes #945 
Unit Tests
> ISSUE-945: add tracing to file for store

- fusestore/store/src/dfs/distributed_fs.rs
- fusestore/store/src/executor/kv_handlers.rs
- fusestore/store/src/meta_service/applied_state.rs
- fusestore/store/src/meta_service/cmd.rs
- fusestore/store/src/meta_service/errors.rs
- fusestore/store/src/meta_service/log_entry.rs
- fusestore/store/src/meta_service/meta_service_impl.rs
- fusestore/store/src/meta_service/meta_service_impl_test.rs
- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/raft_txid.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- fusestore/store/src/meta_service/state_machine.rs
- fusestore/store/src/meta_service/state_machine_test.rs
- Rename:
```
ClientRequest -> LogEntry
ClientResponse -> AppliedState
```
move the following types to  standalone files:
- applied_state.rs
- cmd.rs
- log_entry.rs
- raft_txid.rs
Nothing really changed.
- Improvement
#271
> [store] refactor terms

- .github/actions-rs/grcov.yml
- Cargo.lock
- Cargo.toml
- README.md
- common/allocators/Cargo.toml
- common/allocators/src/lib.rs
- fusequery/query/Cargo.toml
- fusequery/query/src/bin/fuse-benchmark.rs
- fusequery/query/src/bin/fuse-query.rs
- website/datafuse/docs/overview/performance.md
add allocators and set fuse-query default malloc to snmalloc
snmalloc has 30%+ performance improve for the group by case.
```
0. Rust default
datafuse :) SELECT max(number), sum(number) FROM numbers_mt(1000000000) GROUP BY sipHash(number % 3), sipHash(number % 4)
SELECT
max(number),
sum(number)
FROM numbers_mt(1000000000)
GROUP BY
sipHash(number % 3),
sipHash(number % 4)
Query id: 4c1de62c-4120-4843-b15c-8552909278cb
┌─max(number)─┬───────sum(number)─┐
│   999999991 │ 41666666416666667 │
│   999999993 │ 41666666583333333 │
│   999999997 │ 41666666916666666 │
│   999999988 │ 41666666166666668 │
│   999999999 │ 41666667083333334 │
│   999999995 │ 41666666749999999 │
│   999999998 │ 41666667000000000 │
│ …
```
> ISSUE-822: add allocators and set fuse-query default malloc to snmalloc

- fusequery/query/Cargo.toml
Allocator feature disable by default
- Bug Fix
fixes #982
> Allocator feature disable by default

- common/flights/src/impls/kv_api_impl.rs
- common/flights/src/store_do_action.rs
- common/management/Cargo.toml
- common/management/src/user/user_mgr.rs
- common/management/src/user/user_mgr_test.rs
- common/metatypes/src/lib.rs
- common/store-api/src/kv_api.rs
- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/executor/action_handler.rs
- fusestore/store/src/executor/kv_handlers.rs
- fusestore/store/src/meta_service/cmd.rs
- fusestore/store/src/meta_service/state_machine.rs
- fusestore/store/src/meta_service/state_machine_test.rs
The fully functional UpsertKV now supports all write operations.
Since a sequence number is always positive:
- `MatchSeq::Exact(0)` to perform an add-if-absent operation.
- `MatchSeq::Exact(n)` to perform an update on some specified version.
- `MatchSeq::GE(1)` to perform an update-any operation.
- `MatchSeq::Any` to perform an update or insert that always takes effect.
59 LOC reduced! 
- Improvement
#271
> [store]: refactor: Cmd::UpsertKV use MatchSeq to specify what seq to match

- Cargo.lock
- common/metatypes/Cargo.toml
- common/metatypes/src/errors.rs
- common/metatypes/src/lib.rs
- common/metatypes/src/match_seq.rs
- common/metatypes/src/match_seq_test.rs
> [common/metatypes] feature: complete MatchSeq: add display, matching impl, errors etc

- website/datafuse/docs/overview/building-and-running.md
Add default host and port for `clickhouse client`.
In our configs (like fusequery-docker.toml or fusequery-node-1.toml):
```
clickhouse_handler_host = "0.0.0.0"
clickhouse_handler_port = 9001
```
Fixes #issue
No
> [docs] add default host & port for clickhouse cli

- common/management/src/user/user_api.rs
- common/management/src/user/user_mgr.rs
> [store] refactor: simplify user-apis with map_err_to_code() and MatchSeq

- common/management/src/user/user_mgr.rs
- common/metatypes/src/lib.rs
- common/metatypes/src/match_seq.rs
- common/metatypes/src/match_seq_test.rs
- fusestore/store/src/meta_service/state_machine.rs
> [common/metatypes] feature: make match_seq() a generic method

- common/flights/src/impls/kv_api_impl.rs
- fusestore/store/src/executor/kv_handlers.rs
- fusestore/store/src/meta_service/cmd.rs
- fusestore/store/src/meta_service/state_machine.rs
- fusestore/store/src/meta_service/state_machine_test.rs
Fix:
- Fix: When seq mismatch, DeleteKVByKey should return (prev, prev), not
(prev, None) to indicate that nothing changed.
Test:
- Add `test_state_machine_apply_non_dup_generic_kv_delete`: to test
delete-kv on meta data.
- Upsert test: `test_state_machine_apply_non_dup_generic_kv`:
add a case of `MatchSeq::GE`
Refactor:
- Cmd::DeleteKVByKey replace `Option<u64>` with MatchSeq to specify the expected seq.
- Rename DeleteByKeyKV to DeleteKVByKey
- Improvement
#271
> [store] test: add test for meta-op DeleteKV

- .github/workflows/cargo.yml
- .github/workflows/datafuse-build.yml
- .github/workflows/stateless-tests-cluster.yml
- .github/workflows/stateless-tests-standalone.yml
- .github/workflows/unit-tests.yml
add basic build cache
need to add secrets.CACHE_RESET_KEY to control the cache version.
for example, clippy time is reduced from `5m 48s` to `25.74s`. 
Fixes #913 
No
> [ci] add basic build cache

- .github/workflows/cargo.yml
- .github/workflows/datafuse-build.yml
- .github/workflows/stateless-tests-cluster.yml
- .github/workflows/stateless-tests-standalone.yml
- .github/workflows/unit-tests.yml
Re-org key, and add restore-key. Try to improve cache hit rate.
old: `***-Linux-cargo-clippycache-ae1203a62a2ad511e54e1c3cad857e1726ab79cea7be7ade4916d96640e11a9f`
new: `Linux-cargo-clippycache-***-ae1203a62a2ad511e54e1c3cad857e1726ab79cea7be7ade4916d96640e11a9f, Linux-cargo-clippycache-***-, Linux-cargo-clippycache-, Linux-cargo-`
Fixes #issue
No.
> [ci] restroe friendly

- common/datavalues/src/arrays/arithmetic.rs
- common/datavalues/src/arrays/kernels/take.rs
- common/datavalues/src/arrays/ops/apply.rs
- common/datavalues/src/series/arithmetic.rs
- common/datavalues/src/series/date_wrap.rs
- common/datavalues/src/series/series_impl.rs
- common/datavalues/src/series/wrap.rs
- common/datavalues/src/vec.rs
- fusequery/query/src/datasources/system/numbers_stream.rs
The performance gains about 50%.
without snallocate
```
SELECT max(number),sum(number) FROM numbers_mt(1000000000) GROUP BY number % 3, number % 4, number % 5
60 rows in set. Elapsed: 5.058 sec. Processed 1.00 billion rows, 8.01 GB (197.71 million rows/s., 1.58 GB/s.)
```
with snallocate
```
SELECT max(number),sum(number) FROM numbers_mt(1000000000) GROUP BY number % 3, number % 4, number % 5
60 rows in set. Elapsed: 3.860 sec. Processed 1.00 billion rows, 8.01 GB (259.06 million rows/s., 2.07 GB/s.)
```
- Improvement
Fixes #issue
Unit Tests
> improve modulo functions and number streams

- Cargo.lock
- fusestore/store/Cargo.toml
- fusestore/store/src/configs/config.rs
- fusestore/store/src/meta_service/raftmeta.rs
Changes are here: https://github.com/datafuse-extras/async-raft/compare/v0.6.2-alpha.1...datafuse-extras:v0.6.2-alpha.4
**Change**:
- change: merge term and index to `xxx_log_id`: LogId in several public types:
- Entry
- InitialState
- AppendEntriesRequest
- RaftCore
- CurrentSnapshotData
- SnapshotUpdate::SnapshotComplete
- InstallSnapshotRequest
- change: use snapshot-id to identify a snapshot stream
A snapshot stream should be identified by some id, since the server end
should not assume messages are arrived in the correct order.
Without an id, two `install_snapshot` request belonging to different
snapshot data may corrupt the snapshot data, explicitly or even worse,
silently.
- Add SnapshotId to …
> [store]: upgrade to async-raft 0.6.2-alpha.4, fix bugs and improve:

- Cargo.lock
- fusestore/store/Cargo.toml
- fusestore/store/src/meta_service/raftmeta.rs
Simplify snapshot API, data types, fix snapshot bug:
https://github.com/datafuse-extras/async-raft/compare/v0.6.2-alpha.4...datafuse-extras:v0.6.2-alpha.5
**Fix**:
- fix: after 2 log compaction, membership should be able to be extract from prev compaction log
- fix: when `finalize_snapshot_installation`, memstore should not load membership from its old log that are going to be overridden by snapshot.
**Change**:
- change: reduce one unnecessary snapshot serialization
- Change: `get_current_snapshot()`: remove double-serialization:
convert MemStoreSnapshot to CurrentSnapshotData instead of serializing
MemStoreSnapshot:
Before:
```
MemStoreSnapshot.data = serialize(state-machine)
CurrentSnapshotData.data …
```
> [store] refine: upgrade async-raft to 0.6.2-alpha.5

- fusequery/query/src/bin/fuse-benchmark.rs
Add dns resolver for fuse-benchmark
- New Feature
fixes https://github.com/datafuselabs/datafuse/issues/1052
Unit Tests
> dns resolver for fuse-benchmark

- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/dfs/distributed_fs_test.rs
- fusestore/store/src/executor/action_handler_test.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- fusestore/store/src/tests/service.rs
> [store] test: when creating MetaNode, the guard(in StoreTestContext) for the temp dir storing raft state must be kept during every case

- fusestore/store/src/meta_service/meta_store_test.rs
- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/raftmeta.rs
MetaStore is the store of a raft node.
In this commit it oly impl RaftState reopen. Log and state machine are
still pure in-memory impl.
- New Feature
- Improvement
#271
> [store] feature: reopen a MetaStore

- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/raft_state.rs
- fusestore/store/src/meta_service/sled_serde.rs
> [store] refactor: move trait RaftStateSerde to SledSerde and make it public for other component that needs to access sled db

- Cargo.lock
- fusestore/store/Cargo.toml
- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/node_id.rs
- fusestore/store/src/meta_service/node_id_test.rs
- fusestore/store/src/meta_service/raft_state.rs
- fusestore/store/src/meta_service/sled_serde.rs
- fusestore/store/src/meta_service/sled_serde_test.rs
- Add: SledOrderedSerde to impl a ser/de that respect the original value order.
E.g. serde_json does not preserve the order of u64:
9 -> [57], 10 -> [49, 48]
While BigEndian encoding preserve the order.
A value that is used as sled db key must be serialized with order
preserved.
`SledSerde` impl the ser/de that does not require order preservation.
- Add: SledRangeSerde to serialize a `Range` to sled db range, in order
to simplify range query or range modification.
- Change: ser/de NodeId with order preserved.
- Move NodeId into standalone file `node_id.rs`, impl order-preserved
serialization for NodeId.
- New Feature
#271
> [store] feature: ser/de with value order preserved

- fusestore/store/src/meta_service/raft_state_test.rs
- fusestore/store/src/tests/service.rs
> [store] test: add new_sled_test_context() to create a context for sled related test

- fusestore/store/src/meta_service/cmd.rs
- fusestore/store/src/meta_service/log_entry.rs
- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/raft_log.rs
- fusestore/store/src/meta_service/raft_log_test.rs
- Add: RaftLog, which uses a sled::Tree as backend storage and provides
several log access API: last(), append(), range_get() and
range_delete()
- Refactor: impl PartialEq for make a Entry<_> to simplify testing.
- New Feature
#271
#1065
> [store] feature: add RaftLog: a sled db backed raft log storage

- fusestore/store/src/meta_service/raft_log.rs
- fusestore/store/src/meta_service/raftmeta.rs
> [store] feature: MetaStore uses sled db backed RaftLog to store logs

- Cargo.lock
- common/profiling/Cargo.toml
- fusequery/query/Cargo.toml
- fusequery/query/src/servers/mysql/mysql_handler_test.rs
- Bump mysql (Due to dependency conflict, also update nom)
- Bump pprof
Of course, we also need to upgrade mysql-srv to reduce repeated dependencies. I will advance this work.
?
Unit Tests
> Bump mysql, nom and pprof

- Cargo.lock
- fusestore/store/Cargo.toml
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/state_machine.rs
- fusestore/store/src/meta_service/state_machine_test.rs
By using `LogId{term, index}` instead of a single index, some
unnecessary log queries are reduce: such as when craeting snapshot,
no need to walk through logs to find the term of the last applied log.
- Improvement
#271
> [store] refactor: upgrade to async-raft 0.6.2-alpha.6: use LogId to track last applied log

- fusequery/query/src/configs/config_test.rs
Ignore the tests about `from_args` and `from_args_with_toml` in cargo test. 
cc @ariesdevil @sundy-li , please help review.
Relate #1096 
Unit Tests
> Split query config tests and ignore some of them

- fusequery/query/src/servers/clickhouse/interactive_worker.rs
attach query info to ClickHouse session context
- Bug Fix
Fixes #1074
Unit Tests
> fix show processlist not show extra_info in ClickHouse client

- fusestore/store/src/tests/mod.rs
- fusestore/store/src/tests/service.rs
> [store] refactor: use mono-incr port instead of rand port, to avoid potential port conflict during test

- Cargo.lock
- common/datablocks/Cargo.toml
- common/datablocks/src/data_block_debug.rs
- common/datavalues/Cargo.toml
- common/datavalues/src/series/series_debug.rs
Switch to comfy-table from prettytable. In addition, comfy-table is still actively maintained.
- Improvement
Fixes #1095
Unit Tests
> [deps] switch to comfy-table from prettytable

- Makefile
- docker/release/Dockerfile
- installer/install-datafuse.sh
- scripts/install.sh
Instroduce install.sh for datafuse 
will install fuse-query and fuse-store in ~/.datafuse/bin by default and supports to detect on different platforms
```bash
Usage: $this [-b] bindir [-d] [tag]
-b sets bindir or installation directory, Defaults to {HOME}/.datafuse/bin
-d turns on debug logging
[tag] is a tag from
https://github.com/datafuselabs/datafuse/releases
If tag is missing, then the latest will be used.
```
for example
```bash
./install.sh v0.4.33-nightly will download given tag release to ~/.datafuse/bin directory if operating system and platform supported
```
if there is no version given, it will download the latest release
I have tested manually on M1 chip, works fine …
> [Build/Testing/CI]install.sh and docker release

- fusestore/store/src/executor/action_handler_test.rs
- fusestore/store/src/executor/meta_handlers.rs
- fusestore/store/src/meta_service/state_machine.rs
Add missing drop database test for action_handler
- Improvement
Fixes https://github.com/datafuselabs/datafuse/issues/774
Unit Tests
> Add drop database test for action_handler

- .github/workflows/datafuse-docker.yml
- Makefile
- docker/release/Dockerfile
- website/datafuse/docs/overview/building-and-running.md
Currently, we have already build release in multi-arch platform(linux/arm64, linux/amd64, linux/arm/v7, linux/arm/v6) and support to install fuse-query and fuse-store in one install script(https://github.com/datafuselabs/datafuse/pull/1121), thus far we can migrate from original datafusedev to datafuselabs docker host with those platform supports.
We should check the following part integrate well with this update
1. website installation page should update
2. Makefile should change default docker host to datafuselabs
3. CI part should change secret.DOCKERHUB_NAMESPACE conform to the renaming
- Website
- Other 
fixes …
> [Doc/Build/Testing] rename fuse-query to datafuse

- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/raft_log.rs
- fusestore/store/src/meta_service/sled_tree.rs
- fusestore/store/src/meta_service/sled_tree_test.rs
- Add: SledTree: sled::Tree only support serialized key and value.
Since we have several tree-like data: raft log, nodes in state machine
or DFS keys. A generalized typed tree SledTree will simplify the impl
of all these sled tree based data structures.
- Refactor: re-impl RaftLog with SledTree.
- New Feature
#271
#1080
> [store] feature: add SledTree<K, V> to provided typed access to sled tree.

- fusestore/store/src/meta_service/sled_tree.rs
- fusestore/store/src/meta_service/sled_tree_test.rs
> [store] feature: SledTree: add range_keys() to retrieve keys in a range

- fusequery/query/benches/suites/mod.rs
I get some warnings in vscode, so I try to fix it by remove the unused module.
```
module `session_ref` is private  private module
unused import: `fuse_query::servers::MySQLConnection`\n\nnote: `#[warn(unused_imports)]` on by default
```
- Bug Fix
> [fix] remove the unused module

- fusestore/store/src/meta_service/raft_log.rs
- fusestore/store/src/meta_service/sled_tree.rs
- fusestore/store/src/meta_service/sled_tree_test.rs
> [store] feature: SledTree::insert() returns the last set one if it overrides

- common/flights/src/impls/meta_api_impl.rs
- common/flights/src/store_do_action.rs
- common/store-api/src/lib.rs
- common/store-api/src/meta_api.rs
- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/executor/action_handler.rs
- fusestore/store/src/executor/meta_handlers.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/state_machine.rs
- adds version info to database metadata, which will be increased by one for each successful modification of the database metadata.
- extends store_api::meta_api for synchronizing database metadata by version
- New Feature
Part of #992 
Closes #1168
Unit Tests
> db meta versioning & Store API for syncing db meta

- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/raft_types.rs
- fusestore/store/src/meta_service/sled_vartype_tree.rs
- fusestore/store/src/meta_service/sled_vartype_tree_test.rs
- fusestore/store/src/meta_service/sledkv.rs
- fusestore/store/src/meta_service/state_machine.rs
SledVarTypeTree is a candidate as raft state machine store.
Storing all state(such as last applied log index or internal seq number counter) in one tree makes transactional update or snapshot creation much easier.
- New Feature
#271
#1080
> [store] feature: add SledVarTypeTree to store more than one types of key-value in one sled::Tree.

- Cargo.lock
- fusestore/store/Cargo.toml
- fusestore/store/src/api/http/debug/home.rs
- fusestore/store/src/api/http/debug/mod.rs
- fusestore/store/src/api/http/debug/pprof.rs
- fusestore/store/src/api/http/mod.rs
- fusestore/store/src/api/http/router.rs
- fusestore/store/src/api/http/v1/config.rs
- fusestore/store/src/api/http/v1/mod.rs
- fusestore/store/src/api/http_service.rs
- fusestore/store/src/api/mod.rs
- fusestore/store/src/bin/fuse-store.rs
- fusestore/store/src/configs/config.rs
Add admin REST api:
1. debug: http://127.0.0.1:8181/debug
2. configs: http://127.0.0.1:8181/v1/configs
Others could be add if required.
- New Feature
Fixes #1157
Unit Tests
> STORE-1157: add admin REST api

- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/sled_vartype_tree.rs
- fusestore/store/src/meta_service/sled_vartype_tree_test.rs
> [store] feature: SledVarTypeTree::as_type() borrows the tree and limit accesses to a specified namespace

- common/tracing/src/logging.rs
Currently the log level is hard coded in common/tracing.
It need to be turned on by env variable `RUST_LOG`.
When output to stdout, use pretty format:
- Bug Fix
> [common/tracing] fix: enable setting tracing level from env: RUST_LOG=debug

- Cargo.lock
- fusequery/query/Cargo.toml
- fusestore/store/Cargo.toml
bump msql-srv & structopt-toml
Fixes #1092 
Unit Tests
> [deps] bump deps to fix RUSTSEC-2020-0036

- fusestore/store/src/tests/mod.rs
- fusestore/store/src/tests/service.rs
> [store] refactor: when testing, generate unique address for services

- Cargo.lock
- common/flights/src/impls/kv_api_impl.rs
- common/flights/src/store_client.rs
- common/tracing/Cargo.toml
- common/tracing/src/lib.rs
- common/tracing/src/logging.rs
- common/tracing/src/tracing_to_jaeger.rs
- fusestore/store/src/api/rpc/flight_service.rs
- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/meta_service/meta_service_impl.rs
- fusestore/store/src/meta_service/network.rs
- fusestore/store/src/meta_service/raft_log.rs
- fusestore/store/src/meta_service/sled_tree.rs
- fusestore/store/src/tests/mod.rs
- fusestore/store/src/tests/service.rs
Start a local jaeger server and report tracing data and view it:
```
docker run -d -p6831:6831/udp -p6832:6832/udp -p16686:16686 jaegertracing/all-in-one:latest
FUSE_JAEGER=on RUST_LOG=trace cargo test
open http://localhost:16686/
```
-   Add: report tracing data to opentelemetry server(jaeger) with env
`FUSE_JAEGER=on`
-   Add tracing::instrument to store flight server and meta server.
-   Inject tracing span to tonic request on the client side
and extract them on the server side to form a complete tracing.
-   Add tracing to SledTree
TODO: 
- Sometimes the spans messes up with the parent-child relationship. Maybe caused by abnormal thread switching?
- Chaining the span when a work was sent through …
> [common/tracing] feature: report distributed tracing stat to jaeger

- fusestore/store/src/configs/config.rs
- fusestore/store/src/meta_service/raft_log.rs
- fusestore/store/src/meta_service/raft_log_test.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/sled_tree.rs
- fusestore/store/src/meta_service/sled_tree_test.rs
- fusestore/store/src/meta_service/sled_vartype_tree.rs
- fusestore/store/src/meta_service/sled_vartype_tree_test.rs
- fusestore/store/src/tests/service.rs
Sled tree wrappers provides an option to not to fsync after write
operation.
This should only be used in testing environment.
For more details about the slow fsync issue:
https://github.com/drmingdrmer/sledtest
- Bug Fix
> [store] fix: do not fsync sled data in unittets. File::sync_all() takes 10 ~ 30 ms, at worst 500 ms on a Mac

- Cargo.lock
- common/tracing/Cargo.toml
- common/tracing/src/logging.rs
solve #1228
use batch mode to speed up tracing data sending
- Improvement
Fixes #issue
Unit Tests
> ISSUE 1228: Use batch mode to speed up tracing data sending

- fusestore/store/src/meta_service/raft_log.rs
- fusestore/store/src/meta_service/raftmeta.rs
> [store] refactor: impl RaftLog with SledVarTypeTree. Nothing really changed.

- fusecli/cli/src/cmds/processor.rs
cli add history
- New Feature
#938 
Unit Tests
> FEATURE-938: datafuse cli add history

- Cargo.lock
- Cargo.toml
- common/exception/src/exception.rs
- common/stoppable/Cargo.toml
- common/stoppable/src/lib.rs
- common/stoppable/src/stop_handle.rs
- common/stoppable/src/stoppable.rs
- common/stoppable/src/stoppable_test.rs
FuseStore needs a graceful shutdown too. 
- New Feature
> [common/stoppable] feature: borrow codes from fuse-query to make a shared graceful shutdown impl

- Cargo.lock
- common/stoppable/src/stoppable_test.rs
- fusestore/store/Cargo.toml
> [store] refactor: upgrade async-raft to 0.6.2-alpha.7: reduce log level to warn for RPC failures

- scripts/ci/wait_tcp.py
- scripts/deploy/fusequery-cluster-3-nodes.sh
- scripts/deploy/fusequery-standalone.sh
> [tests] refactor: use python script to wait for a listening port; improve portability on mac

- fusecli/cli/src/cmds/config.rs
- fusecli/cli/src/cmds/status_test.rs
Use default values of `Config` in unit test instead of Config::from_args
- Improvement
Fixes #1278
Unit Tests
> issue# 1278 Use default values of Config in unit test

- common/functions/src/scalars/hashes/siphash.rs
Since SipHash have alias, it should use the `display_name`.
- Fix SipHash display name
None
None
> fix: use display_name for siphash

- common/exception/src/exception.rs
- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/api/rpc_service.rs
- fusestore/store/src/bin/fuse-store.rs
- fusestore/store/src/configs/config.rs
- fusestore/store/src/meta_service/raft_log.rs
- fusestore/store/src/meta_service/raft_state.rs
- fusestore/store/src/meta_service/raft_state_test.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- fusestore/store/src/meta_service/sled_util.rs
- fusestore/store/src/tests/mod.rs
- fusestore/store/src/tests/service.rs
- scripts/ci/wait_tcp.py
- scripts/deploy/fusequery-cluster-3-nodes.sh
- scripts/deploy/fusequery-standalone.sh
- Feature: support 3 server startup mode:
For production:
- `fuse-store --boot true`: initialized a store server and init a cluster of only 1 node.
- `fuse-store`: start an initialized fuse-store.
For testing:
- `fuse-store --single true`: testing mode: open an initialized fuse store or create a new one. Most single-store test should use this mode.
Most unittests run in `single` mode.
Fix: #1134
- Test: test restarting a fuse-store.
When testing, a fuse-store should not try to boot an already booted
node.
- Fix: potential corruption in test: holds TempDir guard.
- Feature: StoreServer::start spawns another task to serve.
- Feature: Stop a StoreServer by sending a message to a channel. Part of #1186
- …
> [store] feature: fuse-store support restart

- .gitignore
- Makefile
- fusecli/README.md
- fusecli/cli/e2e/e2e.py
Introduce BDD driven test framework for fusecli, using abseil test and asyncio as implementation
- New Feature
fixes https://github.com/datafuselabs/datafuse/issues/1298
Unit Tests
> [Datafuse CLI] e2e framework for fusecli

- fusequery/query/src/api/rpc_service.rs
- fusequery/query/src/api/rpc_service_test.rs
- fusequery/query/src/bin/fuse-query.rs
- fusequery/query/src/sessions/sessions.rs
- Bug Fix
Fixes #1304
Unit Tests
> remove `conf` from RpcService by using session_mgr's conf 

- Cargo.lock
- fusecli/cli/Cargo.toml
- fusecli/cli/src/cmds/config.rs
- fusecli/cli/src/cmds/env.rs
- fusecli/cli/src/cmds/mod.rs
- fusecli/cli/src/cmds/packages/list.rs
- fusecli/cli/src/cmds/packages/mod.rs
- fusecli/cli/src/cmds/packages/package.rs
- fusecli/cli/src/cmds/processor.rs
* Add `package list`
* Rename namespace to group
Example:
```
[test] > package list
+-----------------+-----------------------------------------------+
| Version         | Path                                          |
+-----------------+-----------------------------------------------+
| v0.4.69-nightly | /home/bohu/.datafuse/test/bin/v0.4.69-nightly |
+-----------------+-----------------------------------------------+
| v0.4.68-nightly | /home/bohu/.datafuse/test/bin/v0.4.68-nightly |
+-----------------+-----------------------------------------------+
```
- New Feature
#938 
Unit Tests
> CLI-938: package list command

- fusecli/README.md
- fusecli/cli/src/cmds/mod.rs
- fusecli/cli/src/cmds/packages/list.rs
- fusecli/cli/src/cmds/packages/mod.rs
- fusecli/cli/src/cmds/packages/package.rs
- fusecli/cli/src/cmds/packages/switch.rs
- fusecli/cli/src/cmds/status.rs
- fusecli/cli/src/cmds/status_test.rs
* Add datafuse-cli package switch for switching the active datafuse to a specified version
Example:
```
[test] > package list
+-----------------+-----------------------------------------------+---------+
| Version         | Path                                          | Current |
+-----------------+-----------------------------------------------+---------+
| v0.4.69-nightly | /home/bohu/.datafuse/test/bin/v0.4.69-nightly |         |
+-----------------+-----------------------------------------------+---------+
| v0.4.68-nightly | /home/bohu/.datafuse/test/bin/v0.4.68-nightly | ✅      |
+-----------------+-----------------------------------------------+---------+
[test] > package switch v0.4.69-nightly
✅ …
```
> CLI-938: add datafuse-cli package switch command

- Cargo.lock
- common/arrow/Cargo.toml
- common/datablocks/src/data_block_debug.rs
- common/datavalues/src/series/series_debug.rs
- fusecli/cli/Cargo.toml
- fusecli/cli/src/cmds/packages/list.rs
- fusestore/store/src/tests/service.rs
remove prettytable-rs, all in comfy-table
- prettytable-rs to comfy-table
- ✅ -> utf-8 `☑`, this will make the comfy-table align correctly
- the format is adjusted to be more compact and consistent with the output of the fusequery 
- Improvement
Related #1126 #1095 https://github.com/jorgecarleitao/arrow2/pull/251
Unit Tests
> [deps] all in comfy-table

- Cargo.lock
- fusecli/cli/Cargo.toml
- fusecli/cli/src/cmds/status.rs
- fusecli/cli/src/cmds/status_test.rs
> [cli] fix: status test should use different temp dir or next time it reads the old data left by previous test

- fusestore/store/src/meta_service/meta_store_test.rs
- fusestore/store/src/meta_service/placement.rs
- fusestore/store/src/meta_service/raft_log.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/sled_vartype_tree.rs
- fusestore/store/src/meta_service/sled_vartype_tree_test.rs
- fusestore/store/src/meta_service/state_machine.rs
- fusestore/store/src/meta_service/state_machine_test.rs
> [store] refactor: remove MetaStore::{open,new}, open_create() is enough

- fusestore/store/src/meta_service/meta_store_test.rs
- fusestore/store/src/meta_service/raft_state.rs
- fusestore/store/src/meta_service/raft_state_test.rs
- fusestore/store/src/meta_service/raftmeta.rs
> [store] refactor: add a field `is_open` to MetaStore and RaftState to indicate if it is opened from a previously saved state

- fusestore/store/src/meta_service/raft_state.rs
> [store] refactor: RaftState: cleanup open-create: separate info extraction and staet initialization

- fusequery/query/src/interpreters/interpreter_explain.rs
- fusequery/query/src/interpreters/interpreter_explain_test.rs
- tests/suites/0_stateless/02_0004_function_name_display.result
- tests/suites/0_stateless/02_0004_function_name_display_cluster.result
- tests/suites/0_stateless/03_0004_select_order_by.result
- tests/suites/0_stateless/03_0004_select_order_by_cluster.result
- tests/suites/0_stateless/03_0005_select_filter.result
- tests/suites/0_stateless/03_0005_select_filter_cluster.result
- tests/suites/0_stateless/04_0000_explain.result
- tests/suites/0_stateless/04_0000_explain_cluster.result
- tests/suites/0_stateless/04_0001_explain_pipeline.result
- tests/suites/0_stateless/08_0000_optimizer.result
- tests/suites/0_stateless/08_0000_optimizer_cluster.result
Regard the explain result of a plan to multiple rows rather than a single row so that we can have the complete borderline when the mysql client outputs `EXPLAIN` results.
Before the PR:
```
mysql> explain select max(number) from numbers(1000) group by number%3;
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| explain …
```
> ISSUE-1191: fix mysql client borderline missing for EXPLAIN statement

- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/raft_log.rs
- fusestore/store/src/meta_service/raft_state.rs
- fusestore/store/src/meta_service/raft_state_kv.rs
- fusestore/store/src/meta_service/raft_types.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/sled_key_space.rs
- fusestore/store/src/meta_service/sled_serde.rs
- fusestore/store/src/meta_service/sled_tree.rs
- fusestore/store/src/meta_service/sled_tree_test.rs
- fusestore/store/src/meta_service/state_machine.rs
- fusestore/store/src/meta_service/state_machine_meta.rs
- fusestore/store/src/meta_service/state_machine_test.rs
```
SledVarTypeTree -> SledTree
AsType -> AsKeySpace
SledKV -> SledKeySpace
```
- Improvement
- #271
> [store] refactor: nothing really changed

- fusestore/store/src/meta_service/raftmeta_test.rs
When testing raft related componennt, sometimes the leadership is taken
by other node, i.e., the original leader may not send a heartbeat
quickly enought.
Thus when reading the latest log index, first we have to reload the
leader id, then read log index from it.
Instead of reading log index directly from the default leader node-0.
- Bug Fix
- #271
Fix: #1360
> [store] fix: read latest log index from active leader

- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/executor/kv_handlers.rs
- fusestore/store/src/meta_service/cmd.rs
- fusestore/store/src/meta_service/state_machine.rs
- fusestore/store/src/meta_service/state_machine_test.rs
- fusestore/store/src/tests/service.rs
Previously, if an `Add` action failed, due to mismatching `seq`, it
returns `(previous value, None)`.
From now on it returns `(previous value, previous value)` to indicate
nothing change.
**Why**:
The previous solution can not distinguish the result from a successful
`delete` and the result from a failed `add`.
Thus the caller has to examine the context to determine if the return
value is a success. E.g., by considering the action(`add` or `delete`).
With the new solution, the caller knows if it succeeded by only a simple comparison on
`res.prev` and `res.result`.
- #271
- #1080 
- #1139
> [store] change: MetaNode::upsertKV return two equal value if no modification is applied

- common/flights/src/impls/mod.rs
- common/flights/src/impls/session_api_impl.rs
- common/flights/src/lib.rs
- common/flights/src/store_do_action.rs
- common/store-api/src/lib.rs
- common/store-api/src/session_api.rs
- fusestore/store/src/executor/action_handler.rs
- fusestore/store/src/executor/mod.rs
- fusestore/store/src/executor/session_handlers.rs
[store_api] blank implementation for kill session action 
For the time being, Store will do nothing for this action; this API is mainly for Query to wire up all the business logics relevant to kill a session.
- New Feature
Fixes #1297
Unit Tests
> kill query action of  store_api

- common/flights/src/impls/kv_api_impl.rs
- common/flights/src/store_do_action.rs
- common/management/src/user/user_mgr.rs
- common/management/src/user/user_mgr_test.rs
- common/store-api/src/kv_api.rs
- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/executor/action_handler.rs
- fusestore/store/src/executor/kv_handlers.rs
61 LOC reduced:DDD
- Improvement
- #271
- #1080
> [store] refactor: use UpsertKV to impl delete operation.

- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/raft_state.rs
- fusestore/store/src/meta_service/raft_state_kv.rs
- fusestore/store/src/meta_service/raft_types.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/sled_key_space.rs
- fusestore/store/src/meta_service/sled_tree.rs
- fusestore/store/src/meta_service/sled_tree_test.rs
- fusestore/store/src/meta_service/state_machine.rs
- fusestore/store/src/meta_service/state_machine_meta.rs
- fusestore/store/src/meta_service/state_machine_test.rs
- Fix: SledTree::last() should set both left and right bound for a key
space.
- Add: StateMachine: add util functions to get a key space.
- Improvement
- #271
- #1080 
- #1385
> [store] refactor: move all key space definitions to `sled_key_space.rs`

- fusequery/query/src/catalogs/impls/database_catalog.rs
- fusequery/query/src/catalogs/impls/remote_meta_store_client.rs
- fusequery/query/src/catalogs/meta_store_client.rs
- fusequery/query/src/configs/config.rs
- fusequery/query/src/sessions/sessions.rs
A minor refactoring:
- Remove `remote_factory` from struct `DatabaseCatalog`
Preparation for introducing "Embedded Catalog" (mainly for unit testing), and decomposing of LocalDatabase
- Improvement
Fixes #1394 
Unit Tests
> Remove `remote_factory` from struct `DatabaseCatalog`

- .github/workflows/datafuse-perf-docker.yml
Add performance docker build into CI
Unit Tests
> [Build/CI] add build perf-tool to CI

- fusestore/store/src/meta_service/sled_tree.rs
- fusestore/store/src/meta_service/sled_tree_test.rs
> [store] feature: add SledTree::remove() to delete a single elt.

- fusestore/store/src/meta_service/raft_types.rs
- fusestore/store/src/meta_service/sled_key_space.rs
- fusestore/store/src/meta_service/state_machine.rs
- New Feature
- #271
- #1080 
fix: #1386
> [store] feature: raft state machine stores generic-kv in sled

- fusestore/store/src/meta_service/raft_log.rs
- fusestore/store/src/meta_service/raft_log_test.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- fusestore/store/src/meta_service/sled_tree.rs
- fusestore/store/src/meta_service/sled_tree_test.rs
Nothing really changed.
- Improvement
- #271
- #1080
> [store] refactor: extract common function flush_async

- tests/perfs/compare.py
Zero divident error occured when mibps become zero
- Bug Fix
Fixes #issue
Unit Tests
> handle zero divident error in compare.py

- common/flights/src/impls/kv_api_impl.rs
- common/management/src/user/user_mgr.rs
- common/management/src/user/user_mgr_test.rs
- common/metatypes/src/lib.rs
- common/store-api/src/kv_api.rs
- store/src/api/rpc/flight_service_test.rs
- store/src/executor/kv_handlers.rs
- store/src/meta_service/applied_state.rs
- store/src/meta_service/cmd.rs
- store/src/meta_service/raft_types.rs
- store/src/meta_service/raftmeta.rs
- store/src/meta_service/sled_key_space.rs
- store/src/meta_service/state_machine.rs
- store/src/meta_service/state_machine_test.rs
Add: UpsertKV adds another `meta` field to specify value meta.  One of
the meta is `expire_at`, which is a timestamp since 1970.  Reading on an
expired entry always returns None, e.g. when reading directly from
StateMachine or when reanding it for an update(apply a raft log).
- New Feature
- #271
- #1402 
- fix: #1422
> [store] feature: generic kv support auto expiring an entry.

- store/src/meta_service/sled_tree.rs
- store/src/meta_service/sled_tree_test.rs
- store/src/meta_service/state_machine.rs
fix: #1427
- New Feature
- Improvement
- #271
- #1080
> [store]: refactor: use SledTree:scan_prefix() to impl kv list

- common/exception/src/exception.rs
- store/src/dfs/distributed_fs.rs
- store/src/executor/kv_handlers.rs
- store/src/fs/ifs.rs
- store/src/localfs/local_fs.rs
- store/src/localfs/local_fs_test.rs
- store/src/meta_service/placement.rs
- store/src/meta_service/raftmeta.rs
- store/src/meta_service/raftmeta_test.rs
- store/src/meta_service/state_machine.rs
- store/src/meta_service/state_machine_test.rs
> [store] refactor:  use common_exception::Result to replace anyhow

- store/Cargo.toml
- store/src/meta_service/raft_state.rs
- store/src/meta_service/raft_state_kv.rs
- store/src/meta_service/raft_state_test.rs
Because membership log is not applied to state machine,
Before logs are removed, the membership need to be saved.
The async-raft::MemStore saves it in a removed log slot,
which may mess up the replication:
Replication has chance sending this pointer log that was an client data.
Although, the presence of snapshot meta does not mean there is a valid snapshot data.
Since snapshot data is not saved on disk.
A snapshot meta only guarantees no smaller snapshot will be installed
when installing snapshot, and no membership config is lost when removing
logs that are included in snapshot.
- New Feature
- #271
- #1080
> [store]: feature: RaftState: stores the last snapshot meta. To avoid potential repliation bug.

- website/datafuse/docs/development/how-to-write-aggregate-functions.md
- website/datafuse/mkdocs.yml
> [docs] Add how-to-write-aggregate-functions

- Cargo.lock
- store/Cargo.toml
- store/src/meta_service/applied_state.rs
- store/src/meta_service/raftmeta.rs
- store/src/meta_service/state_machine.rs
- store/src/meta_service/state_machine_meta.rs
- store/src/meta_service/state_machine_test.rs
pass all logs to apply_entry_to_state_machine(), not just Normal logs.
Pass `Entry<D>` to `apply_entry_to_state_machine()`, not just the only
`EntryPayload::Normal(normal_log)`.
Thus the state machine is able to save the membership changes if it
prefers to.
Why:
In practice, a snapshot contains info about all applied logs, including
the membership config log.
Before this change, the state machine does not receive any membership
log thus when making a snapshot, one needs to walk through all applied
logs to get the last membership that is included in state machine.
By letting the state machine remember the membership log applied,
the snapshto creation becomes more convinient and intuitive: it does not …
> [store] feature: applies all logs to raft state machine.

- store/src/meta_service/raft_state.rs
- store/src/meta_service/raft_state_kv.rs
- store/src/meta_service/raft_state_test.rs
It is a bad idea to work around the problem that state machine does not
save membership config.
Solving the problem where it is introduced saves a lot troubles.
I should not have ever tried.
The better solution is: #1479
- Improvement
- #271
- #1080
> [store] refactor: remove RaftState::write_snapshot_meta().

- common/functions/src/scalars/logics/logic.rs
`variadic_arguments` of LogicFunction should be Some((1, 2)).
- Bug Fix:  `variadic_arguments` of LogicFunction should be Some((1, 2))
Fixes #issue
Unit Tests
> fix: variadic_arguments of LogicFunction should be Some((1, 2))

- Cargo.lock
- store/Cargo.toml
- store/src/meta_service/raftmeta.rs
- store/src/meta_service/raftmeta_test.rs
> [store] refactor: use btreeset to replace hashset, to ease debugging

- cli/src/error.rs
Signed-off-by: koushiro <koushiro.cqx@gmail.com>
use `#[from]` attribute of `thiserror::Error` proc macro, and remove some boilerplate code
- None
Unit Tests
> use `#[from]` attribute of `thiserror::Error` proc macro

- query/src/optimizers/metrics.rs
- query/src/optimizers/mod.rs
- query/src/optimizers/optimizer.rs
Signed-off-by: Alkaid <alkaid@AlkaiddeMacBook-Pro.local>
Add a histogram metric for optimizer. We can use this metric to know the P99,P90....e.t.c used time by optimizer.
- Other 
Fixes #issue
Unit Tests
> Add optimize histogram metric

- query/src/sql/parser/ast/ast_display_test.rs
- query/src/sql/parser/ast/query.rs
- query/src/sql/parser/transformer/transform_sqlparser.rs
- query/src/sql/parser/transformer/transform_sqlparser_test.rs
Part of #1218 
Minor change, refactor `FROM` clause, use `CROSS JOIN` to replace comma seperated `TableReference`.
- Improvement
> parser: Fold table references in FROM clause

- common/exception/src/exception.rs
- store/src/configs/config.rs
- store/src/meta_service/meta_store_test.rs
- store/src/meta_service/mod.rs
- store/src/meta_service/raft_log.rs
- store/src/meta_service/raft_state.rs
- store/src/meta_service/raftmeta.rs
- store/src/meta_service/raftmeta_test.rs
- store/src/meta_service/state_machine.rs
- store/src/meta_service/state_machine_test.rs
- store/src/meta_service/testing.rs
-   Feature: create snapshot from a consistent view of the state machine.
Everything that is needed in a snapshot now is in a single
sled::Tree. `sled::Tree::iter()` returns a consistent snapshot view
of the tree,  which is used to build a snapshot for transfer.
-   Feature: when installing a snapshot, a new sled::Tree is created.
When all key-values are fed into it, a pointer sled::Tree record
`StateMachineId` is udpate to point to the new state machine.
This way a state machine is replaced atomically.
These actions are not done in a transaction. The old state machine
may be left a garbage, which will be cleaned up next time server
starts.
- New Feature
- #271
- #1080
> [store] feature: support snapshot replication.

- query/src/servers/clickhouse/interactive_worker.rs
- query/src/servers/clickhouse/writers/mod.rs
- query/src/servers/clickhouse/writers/query_writer.rs
1. Log error in `datafuse_query::servers::clickhouse::writers::query_writer::QueryWriter::write_error` so we can see error stacktrace in datafuse-query's log.
2. Add query string into error message when `datafuse_query::servers::clickhouse::writers::query_writer::QueryWriter::write` returns an error. Similar to #1353.
- Improvement
Fixes #1329
Manual test
> [clickhouse-handler] print error stacktrace in clickhouse-handler

- Cargo.lock
- common/tracing/src/lib.rs
- common/tracing/src/logging.rs
- store/Cargo.toml
- store/src/api/rpc/flight_service_test.rs
- store/src/configs/config.rs
- store/src/executor/action_handler_test.rs
- store/src/meta_service/meta_service_impl_test.rs
- store/src/meta_service/meta_store_test.rs
- store/src/meta_service/raft_log_test.rs
- store/src/meta_service/raft_state_test.rs
- store/src/meta_service/raftmeta.rs
- store/src/meta_service/raftmeta_test.rs
- store/src/meta_service/sled_tree_test.rs
- store/src/meta_service/state_machine.rs
- store/src/meta_service/state_machine_test.rs
- store/src/tests/service.rs
change-membership should be log driven but not channel driven
https://github.com/datafuse-extras/async-raft/compare/v0.6.2-alpha.9...datafuse-extras:v0.6.2-alpha.10
A membership change involves two steps: the joint config phase and the
final config phase.
Each phase has a corresponding log invovled.
Previously the raft setup several channel to organize this workflow,
which makes the logic hard to understand and introduces complexity when
restarting or leadership transfered: it needs to re-establish the channels and tasks.
According to the gist of raft, all workflow should be log driven.
Thus the new approach:
- Write two log(the joint and the final) at once it recevies a
change-membership request.
- All …
> [store]: refactor: upgrade raft to 0.6.2-alpha.10

- query/src/sql/parser/ast/ast_display_test.rs
- query/src/sql/parser/ast/expression.rs
- query/src/sql/parser/ast/mod.rs
- query/src/sql/parser/ast/query.rs
- query/src/sql/parser/ast/statement.rs
- query/src/sql/parser/transformer/transform_sqlparser.rs
Part of #1218 .
Use qualified fields instead of `Vec<Identifier>` to make AST more semantic.
- Improvement
Unit Tests
> parser: refine object names with qualified type

- Cargo.lock
- common/management/Cargo.toml
- common/management/src/user/user_mgr_test.rs
- common/tracing/Cargo.toml
- bump opentelemetry related dependencies
- use common_runtime only
Fix #1380 #1383 #1498 
Unit Tests
> [deps] bump opentelemetry related dependencies

- .github/workflows/unit-tests.yml
- Cargo.lock
- Cargo.toml
- common/exception/src/exception.rs
- common/stoppable/src/stoppable_test.rs
- common/tracing/Cargo.toml
- common/tracing/src/lib.rs
- common/tracing/src/logging.rs
- query/Cargo.toml
- query/src/interpreters/interpreter_database_create_test.rs
- store/Cargo.toml
- store/src/api/rpc/flight_service_test.rs
- store/src/api/rpc/tls_flight_service_test.rs
- store/src/api/rpc_service.rs
- store/src/executor/action_handler_test.rs
- store/src/meta_service/meta_service_impl.rs
- store/src/meta_service/meta_service_impl_test.rs
- store/src/meta_service/meta_store_test.rs
- store/src/meta_service/raft_log_test.rs
- store/src/meta_service/raft_state_test.rs
- store/src/meta_service/raftmeta.rs
- store/src/meta_service/raftmeta_test.rs
- store/src/meta_service/sled_tree_test.rs
- store/src/meta_service/state_machine.rs
- store/src/meta_service/state_machine_test.rs
- store/src/tests/service.rs
- Improve CI: run unittest with RUST_BACKTRACE=full and RUST_LOG=debug
- Upload artifect for debugging when there is a failure
- Refactor: elaborate error log;
Record source an backtrace when converting anyhow::Error to ErrorCode
When running unittest, with heavy cpu load, heartbeat message has chance
to be delayed too much.
When this happens, a follower tries to elect itself and revert the
current leader to a follower state.
This causes the leader to discard every in progress request it has
received. And the client receives an **inappropriate** error
`RaftError::Shuttingdown`.
This is actually not a bug.
In such case in practise, a client should re-fetch the latest leader
and retry.
For a unittest, we …
> [store] test: fix the RaftError::Shutdown issue

- .gitignore
- common/tracing/src/logging.rs
- enable file jaegertracing
```
$ > FUSE_JAEGER=on RUST_LOG=trace OTEL_BSP_SCHEDULE_DELAY=1 make run
$ > docker run -d -p6831:6831/udp -p6832:6832/udp -p16686:16686 jaegertracing/all-in-one:latest
```
- New Feature
- Improvement
Fixes #issue
Unit Tests
> [tracing] enable file jaegertracing

- Cargo.lock
- cli/Cargo.toml
- common/datablocks/Cargo.toml
- common/datavalues/Cargo.toml
- common/functions/Cargo.toml
- common/progress/Cargo.toml
- common/tracing/Cargo.toml
- query/Cargo.toml
- store/Cargo.toml
Checked by cargo-udeps:
```
unused dependencies:
`common-datablocks v0.1.0 (/home/bohu/github/datafuselabs/datafuse/common/datablocks)`
└─── dependencies
└─── "common-infallible"
`common-datavalues v0.1.0 (/home/bohu/github/datafuselabs/datafuse/common/datavalues)`
└─── dependencies
├─── "paste"
└─── "unsafe_unwrap"
`common-functions v0.1.0 (/home/bohu/github/datafuselabs/datafuse/common/functions)`
└─── dependencies
└─── "bumpalo"
`common-progress v0.1.0 (/home/bohu/github/datafuselabs/datafuse/common/progress)`
└─── dependencies
└─── "common-exception"
`common-tracing v0.1.0 (/home/bohu/github/datafuselabs/datafuse/common/tracing)`
└─── dependencies
└─── "common-runtime"
`datafuse-cli v0.1.0 …
```
> Remove unused deps checked by cargo-udeps

- Cargo.lock
- store/Cargo.toml
- store/src/configs/config.rs
- store/src/meta_service/meta_store_test.rs
- store/src/meta_service/raftmeta.rs
- store/src/meta_service/raftmeta_test.rs
- fix: RaftCore.entries_cache is inconsistent with storage. removed it.
- When leader changes, `entries_cache` is cleared.
Thus there may be cached entries wont be applied to state machine.
- When applying finished, the applied entries are not removed from the
cache.
Thus there could be entries being applied more than once.
- fix: snapshot replication does not need to send a last 0 size chunk
- Improvement
- #271
- #1080
- fix: https://github.com/datafuselabs/datafuse/issues/1564#issuecomment-903370204
> [store] refactor: add snapshot-pointer for leader to indicate replication to switch to snapshot replication

- cli/src/cmds/status_test.rs
Avoid to parse arguments during unit tests.
Previously
```bash
cargo test -p datafuse-cli -- --skip foo
```
cannot work, now it should work normally
- Bug Fix
fixes https://github.com/datafuselabs/datafuse/issues/1574
Unit Tests
> [CLI/Bug Fix] fix unit test arg parse

- Cargo.lock
- common/arrow/Cargo.toml
- common/datavalues/src/arrays/arithmetic.rs
- common/datavalues/src/arrays/comparison.rs
- common/datavalues/src/arrays/ops/agg.rs
- common/datavalues/src/arrays/ops/if_test.rs
- common/datavalues/src/arrays/upstream_traits.rs
- query/src/datasources/local/parquet_table.rs
- query/src/tests/parquet.rs
- store/src/data_part/appender.rs
- store/src/data_part/appender_test.rs
- store/src/executor/action_handler.rs
bump arrow2
- Improvement
Fixes #1573
Unit Tests
> bump arrow2

- common/datavalues/src/columns/conditional.rs
- common/datavalues/src/series/arithmetic.rs
- common/datavalues/src/series/comparison.rs
- common/datavalues/src/series/date_wrap.rs
- common/datavalues/src/series/wrap.rs
- common/datavalues/src/types/data_type_coercion.rs
- common/functions/src/scalars/conditionals/if_test.rs
- tests/suites/0_stateless/02_0010_function_if.result
- tests/suites/0_stateless/02_0010_function_if.sql
```
mysql> select toTypeName(if(number % 3 = 0, toUInt32(1), toInt32(3))) from numbers(10) limit 1;
+-------------------------------------------------------------+
| toTypeName(if(((number % 3) = 0), toUInt32(1), toInt32(3))) |
+-------------------------------------------------------------+
| Int64                                                       |
+-------------------------------------------------------------+
mysql> select if(number, toUInt32(1), toInt32(3)) from numbers(10) limit 1;
ERROR 1105 (HY000): Code: 10, displayText = If function requires the first argument must be Boolean.
mysql> select toTypeName( if( number % 3 = 0 , toUInt64(1) , …
```
> Regulate the arguments type of if function

- query/benches/suites/mod.rs
- query/src/api/rpc/flight_dispatcher_test.rs
- query/src/api/rpc/flight_service_test.rs
- query/src/catalogs/impls/database_catalog.rs
- query/src/datasources/local/default_database.rs
- query/src/datasources/local/local_database.rs
- query/src/datasources/local/local_factory.rs
- query/src/datasources/local/mod.rs
- query/src/datasources/tests.rs
- query/src/servers/clickhouse/clickhouse_handler_test.rs
- query/src/servers/mysql/mysql_handler_test.rs
- query/src/sessions/sessions.rs
- query/src/tests/catalog.rs
- query/src/tests/context.rs
- query/src/tests/mod.rs
- query/src/tests/number.rs
- query/src/tests/sessions.rs
This PR including:
* Move out datasource database register from catalog, to the place who needs register them, like `SessionManager::from_conf` in sessions/sessions.rs.
* Move some functions to tests mod which only test needs, such as: `DatabaseCatalog::try_create` and `SessionManager::try_create`
- Improvement
Fixes N/A
Unit Tests
> Move the local/system register out catalog

- common/streams/src/stream_take.rs
Remove unused `use std::option::Option::None;` declaration
No issue
Unit Tests
> [common/streams] remove unused declaration

- common/datavalues/src/types/data_type_coercion.rs
- common/functions/src/scalars/arithmetics/arithmetic.rs
- tests/suites/0_stateless/02_0012_function_datetimes.result
- tests/suites/0_stateless/02_0012_function_datetimes.sql
Support date/datetime arithmetic operations
```
mysql> select now() + 1;
+---------------------+
| (now() + 1)         |
+---------------------+
| 2021-08-31 01:55:50 |
+---------------------+
1 row in set (0.02 sec)
mysql>  select today()  + number from numbers(10) order by number;
+--------------------+
| (today() + number) |
+--------------------+
| 2021-08-31         |
| 2021-09-01         |
| 2021-09-02         |
| 2021-09-03         |
| 2021-09-04         |
| 2021-09-05         |
| 2021-09-06         |
| 2021-09-07         |
| 2021-09-08         |
| 2021-09-09         |
+--------------------+
10 rows in set (0.07 sec)
```
- Improvement
Fixes #issue
Unit Tests
> Support date/datetime arithmetic operations

- .github/workflows/datafuse-release.yml
- Cross.toml
- Makefile
- docker/build-tool/arm64/Dockerfile
- docker/build-tool/armv6/Dockerfile
- docker/build-tool/armv7/Dockerfile
resolve cross compile dependency issues during release
https://github.com/ZhiHanZ/datafuse/runs/3481834157?check_suite_focus=true
fixes https://github.com/datafuselabs/datafuse/issues/1688
Unit Tests
> [Build/CI] cross compile for arm-based architecture

- .github/actions-rs/grcov.yml
ignore the datafuse cli code coverage
Fixes N/A
Unit Tests
> CI: ignore the datafuse cli code coverage

- common/infallible/src/mutex.rs
- common/infallible/src/rwlock.rs
- common/streams/src/sources/source_csv.rs
- common/streams/src/sources/source_values.rs
- query/src/pipelines/transforms/group_by/aggregator.rs
- query/src/pipelines/transforms/group_by/aggregator_state.rs
- query/src/pipelines/transforms/transform_group_by_partial.rs
Implement send and sync for all type is unsafe(our previous understanding of send and sync is problematic)
Thanks https://github.com/jorgecarleitao/arrow2/pull/368#issuecomment-911724890
- Bug Fix
> Fixed send and sync for mutex and rwlock

- store/src/meta_service/raftmeta_test.rs
> [store] fix: extend timeout add more working threads to let tests pass

- Makefile
Signed-off-by: jyz0309 <45495947@qq.com>
Delete Intermediate files generated by `make test`, which are not deleted by `make clean`
- Improvement
Fixes #1668 
Unit Tests
> Delete Intermediate files generated by `make test`

- common/flights/src/impls/kv_api_impl.rs
- common/flights/src/store_do_action.rs
- common/management/src/namespace/namespace_mgr_test.rs
- common/management/src/user/user_mgr_test.rs
- common/metatypes/src/lib.rs
- common/store-api/src/kv_api.rs
- store/src/api/rpc/flight_service_test.rs
- store/src/executor/action_handler.rs
- store/src/executor/kv_handlers.rs
- store/src/meta_service/cmd.rs
- store/src/meta_service/raftmeta_test.rs
- store/src/meta_service/state_machine.rs
- store/src/meta_service/state_machine_test.rs
- store/src/meta_service/testing.rs
- New Feature
- #271
- #1080
fix: #1402
fix: #1426
> [store] feature: add flight action API update_kv_meta() that only update the value meta, e.g. the expire time, leaving the value as is.

- common/functions/src/scalars/dates/date.rs
- common/functions/src/scalars/dates/date_function_test.rs
- common/functions/src/scalars/dates/mod.rs
- common/functions/src/scalars/dates/number_function.rs
1. fix toYYYYMM function unit tests.
2. using apply_cast_numeric instead iter.
3. constant path improvement.
- Improvement
Fixes #853 
Unit Tests
> Improvement:  Date/DateTime toYYYYMM function

- query/src/catalogs/catalog.rs
- query/src/catalogs/database_engine.rs
- query/src/catalogs/impls/database_catalog.rs
- query/src/datasources/example/example_databases.rs
- query/src/datasources/local/local_databases.rs
- query/src/datasources/remote/remote_databases.rs
- query/src/datasources/system/system_databases.rs
Support function `get_db_engines` and `engine_desc`
- Improvement
Fixes #1722
> support get_db_engines and engine_desc

- common/building/src/lib.rs
use eamil to uniq authors
- Improvement
see https://github.com/datafuselabs/datafuse/issues/949#issuecomment-872700656 , email is relatively private, so ...
Unit Tests
> [improve] use eamil to uniq authors

- common/functions/src/scalars/dates/date.rs
- common/functions/src/scalars/dates/date_function_test.rs
- common/functions/src/scalars/dates/mod.rs
- common/functions/src/scalars/dates/number_function.rs
- tests/suites/0_stateless/02_0012_function_datetimes.result
- tests/suites/0_stateless/02_0012_function_datetimes.sql
- website/datafuse/docs/sqlstatement/datetime-functions/toyyyymmdd.md
- website/datafuse/docs/sqlstatement/datetime-functions/toyyyymmddhhmmss.md
1. add toYYYYMMDDhhmmss and toYYYYMMDD function .
2. add doc.
- New Feature
Fixes #issue
Unit Tests
> Add toYYYYMMDDhhmmss function

- Cargo.lock
- common/management/Cargo.toml
- common/management/src/namespace/local_kv_store.rs
- common/management/src/namespace/local_kv_store_test.rs
- common/management/src/namespace/mod.rs
- store/src/meta_service/raft_db.rs
For use in unitest:
1. initialize sled::Db in a temp dir.
1. create a LocalKVStore with unique name for every test case:
```rust
fn test_xxx() {
let t = tempfile::tempdir().expect("create temp dir to sled db");
init_temp_sled_db(t);
let kv1 = LocalKVStore::new_temp();
let kv2 = LocalKVStore::new_temp();
}
```
For use in production:
```rust
init_sled_db("sled-db-dir");
let kv1 = LocalKVStore::new("name-of-the-underlying-sled-tree");
let kv2 = LocalKVStore::new("another-name-of-the-underlying-sled-tree");
```
Caveat: Two LocalKVStore instances with the same `name` reference to the same underlying sled::Tree.
- New Feature
fix: #1737
> [common/management] feature: add LocalKVStore: a KVApi impl backed with a sled tree, for testing purpose mainly

- store/src/meta_service/raft_log.rs
- store/src/meta_service/raft_state.rs
- store/src/meta_service/sled_tree.rs
- store/src/meta_service/sled_tree_test.rs
- store/src/meta_service/state_machine.rs
> [store] refactor: SledTree::open need not to be async

- query/src/servers/clickhouse/interactive_worker_base.rs
- query/src/servers/mysql/mysql_interactive_worker.rs
Add  interpreter name label for the METRIC_INTERPRETER_USEDTIME.
- Improvement
Unit Tests
```
interpreter_usedtime{interpreter="CreateDatabaseInterpreter",quantile="0"} 0.08251562
interpreter_usedtime{interpreter="CreateDatabaseInterpreter",quantile="0.5"} 0.08251562
interpreter_usedtime{interpreter="CreateDatabaseInterpreter",quantile="0.9"} 0.08251562
interpreter_usedtime{interpreter="CreateDatabaseInterpreter",quantile="0.95"} 0.08251562
interpreter_usedtime{interpreter="CreateDatabaseInterpreter",quantile="0.99"} 0.08251562
interpreter_usedtime{interpreter="CreateDatabaseInterpreter",quantile="0.999"} 0.08251562
interpreter_usedtime{interpreter="CreateDatabaseInterpreter",quantile="1" …
```
> Add label for METRIC_INTERPRETER_USEDTIME

- README.md
README.md Datafuse -> Databend
Fixes N/A
Unit Tests
> README: Datafuse -> Databend

- common/runtime/src/runtime.rs
- common/runtime/src/runtime_test.rs
- query/src/datasources/database/remote/remote_meta_backend.rs
This PR introduce a new function `block_on` in runtime, it moves from `query/src/datasources/database/remote/remote_meta_backend.rs ` do_block.
This may be helpful for https://github.com/datafuselabs/databend/issues/1830
- New Feature
Fixes #1831 
Unit Tests
> RUNTIME-1831: add block_on with timeout

- website/databend/mkdocs.yml
add sql planner framework RFC
Fixes N/A
Unit Tests
> DOC: add sql planner framework RFC to website

- common/functions/src/scalars/arithmetics/arithmetic.rs
- common/functions/src/scalars/arithmetics/arithmetic_test.rs
- query/src/sql/plan_parser.rs
- query/src/sql/plan_parser_test.rs
Add arithemetic support for interval type
>      Date16  [+|-] Interval
>      Date32  [+|-] Interval
>      DateTime32 [+|-] Interval
- New Feature
Fixes #issue
Unit Tests
> Add arithmetic support for interval type

- common/datavalues/src/types/serializations/boolean.rs
- common/datavalues/src/types/serializations/date.rs
- common/datavalues/src/types/serializations/date_time.rs
- common/datavalues/src/types/serializations/number.rs
- common/datavalues/src/types/serializations/string.rs
Apply member same order as trait
- Improvement
Fixes N/A
Unit Tests
> COMMON: apply member same order as trait

- Cargo.lock
- common/io/src/lib.rs
- common/io/src/utils.rs
- common/io/src/utils_test.rs
- query/Cargo.toml
- query/src/servers/mysql/mysql_interactive_worker.rs
- query/src/servers/mysql/writers/query_result_writer.rs
Add mysql progress output
```
mysql> select avg(number) from numbers(100000);
| avg(number) |
|     49999.5 |
Read 100000 rows, 800 KB in 0.004 sec., 25 million rows/sec., 200 MB/sec.
```
- New Feature
Fixes #issue
Unit Tests
> Add mysql progress output

- Cargo.lock
- Cargo.toml
- common/uniq_id/Cargo.toml
- common/uniq_id/src/lib.rs
- store/Cargo.toml
- store/src/tests/mod.rs
- store/src/tests/service.rs
> [common/uniq-di] feature: make unique-id generating a common lib

- common/functions/src/scalars/dates/date_test.rs
- store/src/api/http/v1/config_test.rs
- store/src/api/http_service_test.rs
- store/src/configs/config.rs
Since it overrides the `default()` provided by StructOptToml, there could be unexpected side effect.
Use `Config::empty()` to create a default instance without reading CLI
arguments.
- Improvement
- #271
- #1834
> [store] refactor: remove Config::default().

- .github/workflows/unit-tests.yml
Raft that is used in meta service is sensitive to time.
In a CI a unit test sometimes is delayed by one or two minutes and then fails due to timeout.
To reduce the max number of parallel test to run, may reduce the chance unit test delays each other.
- Improvement
#1881
> [ci] refactor: limit number of test running thread to 2.

- Cargo.lock
- query/Cargo.toml
Fix protocol seq in AuthSwitchRequest 
```
❯ mysql --version
mysql  Ver 8.0.19 for osx10.14 on x86_64 (Homebrew)
❯ mysql --host 192.168.101.40 --user default --port 3307
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: DatabendQuery v-0.1.0-13d03b2-simd(1.57.0-nightly-2021-09-20T03:42:02.090437433+00:00) 0
Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.
Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
mysql> select 1;
+------+
| 1    |
+------+
|    1 | …
```
> Fix protocol seq in AuthSwitchRequest 

- query/src/catalogs/impls/catalog/metastore_catalog.rs
- query/src/catalogs/impls/meta_backends/embedded_meta_backend.rs
- query/src/catalogs/impls/meta_backends/remote_meta_backend.rs
- tests/suites/0_stateless/05_0001_ddl_create_database.sql
- EmbededMetaBackend should return DatabaseAlreadyExists instead
of UnknownDatabase if database already exist
- RemoteMetabackend should evaluate the inner result returned from
`do_block`
- `create_database` of EmbeddedMetaBackend should acquire a lock
for both checking and inserting, not a read lock for checking and a
write lock for inserting
- enable `if_not_exists`, when creating `default` db
currently, there is no pre built db in the remote meta backend.
instead,  a `default` database is registered by EACH query node.
To avoid the conflicts of creating the same "default" database,
we enable the if_not_exists flag when registering the default db.
Thank @zhang2014 for reminding me that the err code is …
> bug fix: incorrect err-code returned for create db

- Cargo.lock
- metasrv/src/api/flight_server.rs
- metasrv/src/api/mod.rs
- metasrv/src/bin/metasrv.rs
- metasrv/src/tests/service.rs
> [metasrv] refactor: rename MetaServer to FlightServer

- metasrv/src/lib.rs
- metasrv/src/tests/mod.rs
- metasrv/src/tests/service.rs
- metasrv/src/tests/tls_constants.rs
- metasrv/tests/flight/main.rs
- metasrv/tests/flight/metasrv_flight_api.rs
- metasrv/tests/flight/metasrv_flight_tls.rs
- Improvement
- According to #1866
Rust-crate-style tests guide: https://matklad.github.io/2021/02/27/delete-cargo-integration-tests.html
> [metasrv] refactor: organized integration test in the rust-crate style: move flight api test into metasrv/tests/

- common/runtime/src/runtime_test.rs
> [common/runtime] fix: extend duration to test timeout, hoping it may fix the flaky failure of test block_on

- Cargo.lock
- Cargo.toml
- common/management/Cargo.toml
- common/store-api/Cargo.toml
- kvlocal/Cargo.toml
- kvlocal/src/lib.rs
- kvlocal/src/local_kv_store.rs
- kvlocal/src/local_kv_store_test.rs
Currently the dependency graph is:
```
.----- common/management
|      |
|      v
|  .-- kvlocal
|  |   |
|  |   v
|  |   metasrv
|  |   |
|  |   v
+--|-> common/store-api-sdk
|  |   |
|  |   v
`--+-> common/store-api
```
```
cargo tree -i kvlocal
kvlocal v0.1.0
└── common-management v0.1.0
└── databend-query v0.1.0
├── databend-cli v0.1.0
└── fuzz v0.1.0
cargo tree -i common-store-api
common-store-api v0.1.0
├── common-management v0.1.0
│   └── databend-query v0.1.0
│       ├── databend-cli v0.1.0
│       └── fuzz v0.1.0
├── common-store-api-sdk v0.1.0
│   ├── common-management v0.1.0
│   ├── databend-query v0.1.0
│   ├── databend-store v0.1.0
│   │   └── databend-cli v0.1.0
│   └── metasrv v0.1.0
│ …
```
> [kv] refactor: move local kv into standalone crate /kvlocal to break potential cyclic dependency

- Cargo.lock
- common/store-api-sdk/src/lib.rs
- kvlocal/src/lib.rs
- query/Cargo.toml
- query/src/catalogs/impls/catalog/metastore_catalog.rs
- query/src/catalogs/impls/meta_backends/remote_meta_backend.rs
- query/src/common/config_converter.rs
- query/src/common/mod.rs
- query/src/common/store_api_provider.rs
- query/src/datasources/database/default/default_database.rs
- query/src/datasources/database/default/default_database_factory.rs
- query/src/datasources/table/remote/remote_table.rs
- query/src/datasources/table_engine.rs
- StoreApiProvider is moved to databend-query
It is a temp workaround (otherwise, we should merge all the api sdk
into query) of the dependency issues.
- While returning KVApi from StoreApiProvider, if conf.meta.address is
empty, an instance of LocalKVStore is provided
- Improvement
Unit Tests
> StoreApiProvider uses local kv store if conf.meta.address is empty

- kvlocal/src/local_kv_store.rs
- metasrv/src/raft/state_machine/sm.rs
- metasrv/src/raft/state_machine/state_machine_test.rs
> [metasrv] refactor: StateMachine::apply_cmd() just need a Cmd but not an Entry

- metasrv/src/meta_service/log_entry.rs
- metasrv/src/meta_service/network.rs
- metasrv/src/raft/log/raft_log.rs
- metasrv/src/raft/sled_impl.rs
- metasrv/src/raft/sled_key_spaces.rs
- metasrv/src/raft/state/raft_state.rs
- metasrv/src/raft/state_machine/sm.rs
- metasrv/src/sled_store/seq_num.rs
- metasrv/src/sled_store/sled_key_space.rs
- metasrv/src/sled_store/sled_tree_test.rs
`sled_store` should just provide key space trait.
The key spaces that `metasrv` need should not be inside `sled_store`.
- Improvement
- #1877
> [metasrv] refactor: move key space impl into metasrv/raft

- metasrv/src/configs/mod.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/raft/log/raft_log.rs
- metasrv/src/raft/log/raft_log_test.rs
- metasrv/src/raft/state/raft_state.rs
- metasrv/src/raft/state/raft_state_test.rs
- metasrv/src/raft/state_machine/sm.rs
- metasrv/src/raft/state_machine/state_machine_test.rs
- metasrv/src/raft/testing.rs
- metasrv/src/tests/service.rs
- store/src/configs/config.rs
> [metasrv] refactor: reorganize config and testing utils

- common/io/Cargo.toml
add Apache 2.0 license to common-io
- Improvement
Fixes #1956
None
> [improvement] add Apache 2.0 license to common-io

- query/src/datasources/table/fuse/io/block_appender.rs
- query/src/datasources/table/fuse/meta/table_snapshot.rs
- query/src/datasources/table/fuse/util/statistic_helper.rs
Add new attribute `row_count` to struct `ColStats`.
cc @zhyass, if anything does not meet the requirements of the indexing layer, pls inform me 
- Improvement
None
Unit Tests
> add `row_count` to struct `ColStats`

- common/store-api-sdk/src/store_client_conf.rs
- query/Cargo.toml
- query/src/bin/databend-query.rs
- query/src/common/storeapi/config_converter.rs
- query/src/configs/config.rs
- query/src/configs/config_log.rs
- query/src/configs/config_meta.rs
- query/src/configs/config_query.rs
- query/src/configs/config_storage.rs
- query/src/configs/config_test.rs
- query/src/configs/macros.rs
- query/src/configs/mod.rs
- query/src/datasources/database/system/configs_table.rs
- query/src/datasources/database/system/configs_table_test.rs
- query/src/servers/mysql/mysql_interactive_worker.rs
- query/src/sessions/context.rs
- scripts/deploy/config/databend-query-node-1.toml
- scripts/deploy/config/databend-query-node-2.toml
- scripts/deploy/config/databend-query-node-3.toml
1. Split config one file into: config_meta.rs, config_log.rs, config_storage.rs
2. Add `storage` config group, remove `store` config group
3. Add `DFS/DISK/S3` sub config group
4. Update stateless config toml
5. Remove block_service_config from common/store-api-sdk/src/store_client_conf.rs
6. Remove unused config tests
- Improvement
Fixes #1987
Unit Tests
> CONFIG-1987: storage config

- docker/stateless/run.sh
- scripts/ci/ci-run-stateless-tests-cluster.sh
- scripts/ci/ci-run-stateless-tests-standalone.sh
- tests/databend-test
1. ./databend-test --mode 'standalone' --skip '^09_*' 
2. Skip the remote stateless test, for #1994 
Fixes #1995 
Unit Tests
> TEST-1995: databend-test --skip support regex rule

- common/datavalues/src/types/data_type.rs
- common/functions/src/scalars/arithmetics/arithmetic_test.rs
- common/functions/src/scalars/dates/date_function_test.rs
- common/functions/src/scalars/dates/date_test.rs
- common/functions/src/scalars/dates/interval_function.rs
- common/functions/src/scalars/dates/interval_function_test.rs
- common/functions/src/scalars/dates/number_function.rs
- common/functions/src/scalars/dates/round_function.rs
- common/functions/src/scalars/dates/week_date.rs
- query/src/servers/mysql/mysql_interactive_worker.rs
- query/src/sql/sql_common.rs
- website/databend/docs/sqlstatement/data-types/data-type-time-date-types.md
- To be compatible with ClickHouse's [Date32](https://clickhouse.com/docs/en/sql-reference/data-types/date32/), it supports negative numbers.
- Add new aliases for SQL datatypes:
"DATE16" => Ok(DataType::Date16),
"DATE32" => Ok(DataType::Date32),
"DATETIME" => Ok(DataType::DateTime32(None)),
"DATETIME32" => Ok(DataType::DateTime32(None)),
related cc @ygf11  @dust1  @junli1026 
- Improvement
Fixes #issue
Unit Tests
> Make date32 physical type to be int32

- query/src/configs/config_storage.rs
- query/src/configs/config_test.rs
- scripts/deploy/config/databend-query-node-1.toml
- scripts/deploy/config/databend-query-node-2.toml
- scripts/deploy/config/databend-query-node-3.toml
1. Remove the dfs storage type from config
- Improvement
Fixes #2003 
Unit Tests
> CONFIG-2003: Remove dfs storage type

- query/src/pipelines/processors/processor_merge.rs
- query/src/pipelines/processors/processor_mixed.rs
- query/src/pipelines/processors/processor_mixed_test.rs
The merge stream logic is shared by both merge processor and mixed processor. The change is to move them into one function.
- Improvement
Fixes #issue
Unit Tests
> Merge processor - extract common code and put them into a functoin

- common/meta-apis/api/src/meta_api.rs
- common/store-api-sdk/src/impl_flights/meta_api_impl.rs
- query/src/catalogs/impls/meta_backends/remote_meta_backend.rs
> [query] refactor: rename get_table_ext to get_table_by_id; They are the same

- common/meta-apis/api/src/meta_api.rs
- common/meta-apis/vo/src/lib.rs
- common/store-api-sdk/src/impl_flights/meta_api_impl.rs
- dfs/src/api/rpc/flight_service_test.rs
- dfs/src/executor/action_handler_test.rs
- dfs/src/executor/meta_handlers.rs
- query/src/catalogs/impls/meta_backends/embedded_meta_backend.rs
- query/src/catalogs/impls/meta_backends/remote_meta_backend.rs
- query/src/catalogs/meta_backend.rs
- query/src/catalogs/mod.rs
- query/src/datasources/database/default/default_database.rs
- query/src/datasources/database/example/example_database.rs
- query/src/datasources/table/csv/csv_table.rs
- query/src/datasources/table/csv/csv_table_test.rs
- query/src/datasources/table/fuse/table.rs
- query/src/datasources/table/memory/memory_table.rs
- query/src/datasources/table/memory/memory_table_test.rs
- query/src/datasources/table/null/null_table.rs
- query/src/datasources/table/null/null_table_test.rs
- query/src/datasources/table/parquet/parquet_table.rs
- query/src/datasources/table/parquet/parquet_table_test.rs
- query/src/datasources/table/remote/remote_table.rs
- query/src/datasources/table_engine.rs
> [query] refactor: merge GetTableActionResult and TableInfo into one struct TableInfo; fix: #2015

- common/meta-apis/api/src/meta_api.rs
- common/meta-apis/vo/src/lib.rs
- common/store-api-sdk/src/impl_flights/meta_api_impl.rs
- dfs/src/api/rpc/flight_service_test.rs
- dfs/src/api/rpc/tls_flight_service_test.rs
- kvsrv/tests/flight/kvsrv_flight_tls.rs
- query/src/catalogs/impls/meta_backends/remote_meta_backend.rs
- query/src/catalogs/meta_backend.rs
> [common/meta-api] Refactor: MetaApi always use `&str` as argument type instead of `String`

- common/meta-apis/api/src/meta_api.rs
- common/meta-apis/vo/src/lib.rs
- common/store-api-sdk/src/impl_flights/meta_api_impl.rs
- common/store-api-sdk/src/store_do_action.rs
- dfs/src/api/rpc/flight_service_test.rs
- dfs/src/executor/action_handler_test.rs
- dfs/src/executor/meta_handlers.rs
> [common/meta-api] refactor: MetaApi::drop_table() does not need a return value type. use () for it

- Cargo.lock
- Cargo.toml
- kvsrv/Cargo.toml
- kvsrv/src/bin/metasrv.rs
- kvsrv/src/configs/config.rs
- kvsrv/src/executor/action_handler.rs
- kvsrv/src/executor/meta_handlers.rs
- kvsrv/src/executor/mod.rs
- scripts/deploy/databend-query-cluster-3-nodes.sh
- scripts/deploy/databend-query-standalone.sh
- add database metadata action handlers to crate `kvsrv`
- change the binary of crate `kvsrv` to `databend-meta`
default flight service port of `databend-meta` changed to 9191
- adapts scripts to `databend-meta`
-----------------
- crate `dfs` is removed from cargo workspaces, but codes are left there
- crate `kvsrv` is NOT renamed (to `meta` or something else which I am not sure)
these two items are left to subsequent PRs
- Improvement
Fixes #issue
Unit Tests
> Move meta handlers to crate kvsrv

- Cargo.lock
- Cargo.toml
- common/base/Cargo.toml
- common/catalog/Cargo.toml
- common/catalog/src/lib.rs
- common/catalog/src/table_snapshot.rs
- common/functions/src/aggregates/aggregate_combinator_test.rs
- query/Cargo.toml
- query/src/datasources/table/fuse/io/block_appender.rs
- query/src/datasources/table/fuse/io/segment_reader.rs
- query/src/datasources/table/fuse/io/snapshot_reader.rs
- query/src/datasources/table/fuse/meta/meta_info_reader.rs
- query/src/datasources/table/fuse/meta/mod.rs
- query/src/datasources/table/fuse/table.rs
- query/src/datasources/table/fuse/util/index_helpers.rs
- query/src/datasources/table/fuse/util/statistic_helper.rs
- Improvement
- #2055 
- #2059
- fix: #2060
> [common/catalog] refactor: move TableSnapshot into crate common/catalog, so that a plan could have a reference to table info

- common/catalog/src/table_snapshot.rs
- query/src/datasources/table/fuse/table.rs
- New Feature
- Improvement
- #2046
- #2059
> [query] refactor: remove FuseTable method: save_snapshot() and save_segment(). An impl of trait Table should not deal with the IO

- Cargo.lock
- common/base/src/lib.rs
- common/base/src/runtime.rs
- common/kv-apis/api/Cargo.toml
- common/kv-apis/api/src/kv_api_sync.rs
- common/kv/src/kv.rs
- common/store-api-sdk/Cargo.toml
- common/store-api-sdk/src/store_client.rs
- query/src/api/rpc/flight_dispatcher.rs
- query/src/catalogs/impls/meta_backends/remote_meta_backend.rs
- query/src/datasources/dal/blob_accessor.rs
- query/src/datasources/table/fuse/io/reader_util.rs
- query/src/pipelines/processors/processor_merge.rs
- query/src/pipelines/processors/processor_mixed.rs
- query/src/pipelines/transforms/transform_create_sets.rs
- query/src/servers/clickhouse/clickhouse_handler.rs
- query/src/servers/clickhouse/clickhouse_session.rs
- query/src/servers/clickhouse/interactive_worker_base.rs
- query/src/servers/mysql/mysql_handler.rs
- query/src/sessions/context.rs
Rename DatabendQueryContext::execute_task to `try_spawn` and let
DatabendQueryContext impl `TrySpawn` so that a crate that just needs
`DatabendQueryContext` to spawn a task for it does not need to depend
on databend-query any more.
- New Feature
- #2046
- #2059
- fix: #2061
> [common/base] feature: introduce trait `TrySpawn` to define methods to spawn an async task

- common/meta/embedded/src/kv_api_impl.rs
- common/meta/embedded/src/lib.rs
- common/meta/embedded/src/meta_embedded.rs
> [common/meta/embedded] refactor: move kv_api impl into standalone file

- scripts/deploy/config/databend-query-embedded-meta.toml
This is a CI bug:
Step1: Merge #2528
Step2: Merge #2534
Step3: #2534 's new file scripts/deploy/config/databend-query-embedded-meta.toml missing the config field `azure_storage_blob` who refined in the #2528  
CI failed:
https://github.com/datafuselabs/databend/runs/4052571595?check_suite_focus=true
Fixes #issue
Unit Tests
> CI: fix embedded config missing field azure_storage_blob

- cli/src/cmds/clusters/cluster.rs
- cli/src/cmds/clusters/create.rs
- cli/src/cmds/clusters/create_test.rs
- cli/src/cmds/clusters/stop.rs
- cli/src/cmds/clusters/view.rs
- cli/src/cmds/command.rs
- cli/src/cmds/comments/comment.rs
- cli/src/cmds/config.rs
- cli/src/cmds/helps/help.rs
- cli/src/cmds/packages/package.rs
- cli/src/cmds/processor.rs
- cli/src/cmds/queries/query.rs
- cli/src/cmds/ups/up.rs
- cli/src/cmds/versions/version.rs
this PR tries make a re-org on the Command trait:
1) add fn subcommands(): allowing a command nests multiple subcommands, easier to make the `clap::App` and dispatch the subcommand
2) add two template methods exec() and exec_subcommand()
currently this PR only changed the `cluster` command and its subcommands, if the idea is ok, i'd continue work on other commands like `package`. 
before: https://github.com/datafuselabs/databend/blob/ba278730fd2a5d95e0a223bcbd3482bde7c15cd5/cli/src/cmds/clusters/cluster.rs
after: https://github.com/datafuselabs/databend/blob/c18100d1a46e9ec17e131803ca55c57398e4bf16/cli/src/cmds/clusters/cluster.rs
benefits:
- we could seperate the concerns on "parsing cmdline" (in the …
> [bendctl] introduce fn subcommands() to the Command trait

- cli/src/cmds/clusters/cluster.rs
- cli/src/cmds/clusters/create.rs
- cli/src/cmds/clusters/stop.rs
- cli/src/cmds/clusters/view.rs
- cli/src/cmds/config.rs
- cli/src/cmds/helps/help.rs
- cli/src/cmds/packages/fetch.rs
- cli/src/cmds/packages/package.rs
- cli/src/cmds/packages/switch.rs
- cli/src/cmds/processor.rs
- cli/src/cmds/queries/query.rs
- cli/src/cmds/ups/up.rs
- cli/src/cmds/writer.rs
- website/databend/docs/cli/cli.md
1. Refine the message hints
2. Introduce more writers: write_ok/write_err/write_rocket/write_warn
3. Apply the same order as `Command` trait order
- Improvement
Unit Tests
> CLI: Refine the writer format and the message hints

- Makefile
update the file descriptor limit to avoid `too many open files (os error 24) on macos`
- Bug Fix
Fixes #2433
Unit Tests
> fix: update file descriptor limit for debug test

- cli/src/cmds/clusters/cluster.rs
- cli/src/cmds/clusters/create.rs
- cli/src/cmds/clusters/stop.rs
- cli/src/cmds/clusters/view.rs
- cli/src/cmds/command.rs
- cli/src/cmds/config.rs
- cli/src/cmds/helps/help.rs
- cli/src/cmds/packages/fetch.rs
- cli/src/cmds/packages/list.rs
- cli/src/cmds/packages/package.rs
- cli/src/cmds/packages/switch.rs
- cli/src/cmds/queries/query.rs
- cli/src/cmds/ups/up.rs
- cli/src/cmds/versions/version.rs
this PR continue the work from #2530 on the package commands.
- make the package subcommands impl the Command trait
- change the return value of `about()` to `&'static str`, removes duplicated description string in the `about` fn and the clap definition 
- Improvement
Unit Tests
> [bendctl] continue #2530 on the package subcommands

- Makefile
fix `ulimit: too many arguments` 
- Bug Fix
Fixes #2551
Unit Tests
> [fix]: resolve ulimit error in makefile

- common/base/src/runtime.rs
- common/macros/src/async_entrypoint.rs
- query/src/servers/mysql/mysql_handler.rs
fix server hang when use wait in entrypoint
- Bug Fix
Fixes #2542
> ISSUE-2542 fix server hang when use wait in entrypoint

- docker/release/Dockerfile
fix release docker file,  I think cache key is not the root  issue, root issue is the default name changed from test to local
- Bug Fix
Fixes https://github.com/datafuselabs/databend/issues/2556
Unit Tests
> [Release] fix release docker file

- .github/workflows/unit-tests.yml
use locked deps when installing grcov
Fixes #2583 
Unit Tests
> [ci] work around grcov build break

- common/dal/src/impls/local.rs
trying to fix :
- issue #2579
- issue #2416
- issue #2468
by explicitly flush tokio files.
According to the discussion  https://github.com/tokio-rs/tokio/issues/2307, and comments
https://github.com/tokio-rs/tokio/issues/2307#issuecomment-618712495, 
https://github.com/tokio-rs/tokio/issues/2307#issuecomment-596336451
imo, we should explicitly flush the tokio files,  implicit `drop` is not enough in our case.
not sure if this will fix the above issues ultimately. I suggest leaving those issues open for a period of time, till they do disappear.
- Bug Fix
Unit Tests
> fixing dal reader flaky tests

- common/datavalues/src/series/series_impl.rs
- common/functions/src/scalars/maths/math.rs
- common/functions/src/scalars/maths/mod.rs
- common/functions/src/scalars/maths/trigonometric.rs
- common/functions/src/scalars/maths/trigonometric_test.rs
Add trigonometric func.
```
mysql> SELECT SIN(PI());
+------------------------------------+
| SIN(PI())                          |
+------------------------------------+
| 0.00000000000000012246467991473532 |
+------------------------------------+
Read 1 rows, 1 B in 0.000 sec., 2.46 thousand rows/sec., 2.46 KB/sec.
mysql> SELECT TAN(PI());
+-------------------------------------+
| TAN(PI())                           |
+-------------------------------------+
| -0.00000000000000012246467991473532 |
+-------------------------------------+
Read 1 rows, 1 B in 0.000 sec., 2.44 thousand rows/sec., 2.44 KB/sec.
mysql> SELECT TAN(PI()+1);
+--------------------+
| …
```
> [function] add trigonometric func

- Cargo.lock
- common/functions/Cargo.toml
- common/functions/src/scalars/maths/crc32.rs
- common/functions/src/scalars/maths/crc32_test.rs
- common/functions/src/scalars/maths/math.rs
- common/functions/src/scalars/maths/mod.rs
Add crc32 function.
```
mysql> SELECT CRC32('MySQL');
+----------------+
| CRC32('MySQL') |
+----------------+
|     3259397556 |
+----------------+
1 row in set (0.09 sec)
Read 1 rows, 1 B in 0.001 sec., 953.33 rows/sec., 953.33 B/sec.
mysql> SELECT CRC32('mysql');
+----------------+
| CRC32('mysql') |
+----------------+
|     2501908538 |
+----------------+
Read 1 rows, 1 B in 0.000 sec., 2.06 thousand rows/sec., 2.06 KB/sec.
mysql> SELECT CRC32(NULL);
| CRC32(NULL) |
|        NULL |
Read 1 rows, 1 B in 0.001 sec., 1.79 thousand rows/sec., 1.79 KB/sec.
mysql> SELECT CRC32(12);
+------------+
| CRC32(12)  | …
```
> [function] add crc32 function

- .github/workflows/stateless-tests-standalone.yml
- scripts/ci/ci-run-stateless-tests-standalone-s3.sh
- add ci script "scripts/ci/ci-run-stateless-tests-standalone-s3.sh".
- devs can also use this script to launch a local stateless-test 
- Improvement
Fixes #2601
Unit Tests
> ISSUE-2601: add scripts/ci/ci-run-stateless-tests-standalone-s3.sh

- query/src/catalogs/impls/catalog/system_catalog.rs
- query/src/datasources/database/system/columns_table.rs
- query/src/datasources/database/system/columns_table_test.rs
- query/src/datasources/database/system/mod.rs
- query/src/datasources/database/system/tables_table_test.rs
this PR adds a system.columns table allowing user to query the table schema easily, like `infomation_schema.columns` in mysql & `system.columns` in clickhouse. in the future, we could display more column statistics inside it, like: https://clickhouse.com/docs/en/operations/system-tables/columns/
there're something not quite sure about:
- there's already a `DESCRIBE db.table` syntax which dumps a table schema in a formatted way, the result schema is different yet, do we need unify the schema between them? (it seems that the output of `infomation_schema.columns` has more infomation than `DESCRIBE {table}` in mysql)
- do we need add a `SHOW COLUMNS FROM {table}` statement like in mysql? it seems duplicated …
> Add system.columns table

- common/planners/src/plan_builder_scan.rs
- common/planners/src/plan_node.rs
- common/planners/src/plan_scan.rs
- common/planners/src/plan_scan_test.rs
- query/src/datasources/table/csv/csv_table_test.rs
- query/src/datasources/table_func/numbers_table_test.rs
- query/src/optimizers/optimizer_statistics_exact.rs
- query/src/sql/plan_parser.rs
> [common/planners] refactor: remove unused fields: TableScanInfo::{table_name, table_args} ScanPlan::table_args

- .github/CODEOWNERS
Use the [Github feature](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax) to add reviewers automatically when a PR is created.
Teams are listed at [here](https://github.com/orgs/datafuselabs/teams), also you can drop you in multiple teams if you need.
Unit Tests
> feat: add reviewers automatically

- common/management/src/user/user_api.rs
- common/management/src/user/user_mgr.rs
- common/management/src/user/user_mgr_test.rs
- common/meta/types/src/lib.rs
- common/meta/types/src/user.rs
- common/planners/src/plan_user_create.rs
- query/src/interpreters/interpreter_factory.rs
- query/src/interpreters/interpreter_user_create.rs
- query/src/interpreters/interpreter_user_create_test.rs
- query/src/interpreters/mod.rs
- query/src/sql/plan_parser.rs
- query/src/sql/sql_parser.rs
- query/src/sql/sql_parser_test.rs
- query/src/sql/sql_statement.rs
- query/src/users/user.rs
- query/src/users/user_mgr.rs
- query/src/users/user_mgr_test.rs
- tests/suites/0_stateless/05_0004_ddl_create_user.sql
1. `CREATE USER 'test'@'localhost' IDENTIFIED BY 'password';`
2. The `host` should add to user info in another PR
- New Feature
Fixes #2630 
Unit Tests
> USER-2630: create user

- common/functions/src/scalars/maths/angle.rs
- common/functions/src/scalars/maths/math.rs
- common/functions/src/scalars/maths/mod.rs
- common/functions/tests/it/scalars/maths/angle.rs
- common/functions/tests/it/scalars/maths/mod.rs
Add angle function for math.
```
mysql> SELECT DEGREES(PI());
+---------------+
| DEGREES(PI()) |
+---------------+
|           180 |
+---------------+
Read 1 rows, 1 B in 0.000 sec., 3.22 thousand rows/sec., 3.22 KB/sec.
mysql> SELECT DEGREES(PI() / 2);
+---------------------+
| DEGREES((PI() / 2)) |
+---------------------+
|                  90 |
+---------------------+
Read 1 rows, 1 B in 0.001 sec., 1.94 thousand rows/sec., 1.94 KB/sec.
+--------------------+
| RADIANS(90)        |
+--------------------+
| 1.5707963267948966 |
+--------------------+
1 row in set (0.08 sec)
Read 1 rows, 1 B in 0.001 sec., 867.02 rows/sec., 867.02 B/sec.
mysql> SELECT …
```
> [function] add angle function for math

- common/cache/Cargo.toml
- common/cache/src/cache.rs
- common/cache/tests/it/cache.rs
- common/cache/tests/it/cache/lru.rs
- common/cache/tests/it/disk_cache.rs
- common/cache/tests/it/main.rs
apply the new test style to common_cache
Part of  #1866
Unit Tests
> [test] apply the new test style to common_cache

- Cargo.lock
- metasrv/Cargo.toml
- metasrv/src/api/http/debug/home.rs
- metasrv/src/api/http/debug/pprof.rs
- metasrv/src/api/http/v1/config.rs
- metasrv/src/api/http/v1/config_test.rs
- metasrv/src/api/http/v1/health.rs
- metasrv/src/api/http/v1/health_test.rs
- metasrv/src/api/http_service.rs
- query/Cargo.toml
- query/src/api/http/debug/home.rs
- query/src/api/http/debug/pprof.rs
- query/src/api/http/v1/cluster.rs
- query/src/api/http/v1/cluster_test.rs
- query/src/api/http/v1/config.rs
- query/src/api/http/v1/config_test.rs
- query/src/api/http/v1/health.rs
- query/src/api/http/v1/health_test.rs
- query/src/api/http/v1/logs.rs
- query/src/api/http/v1/logs_test.rs
- query/src/api/http_service.rs
- query/src/common/service/http_shutdown_handles.rs
- query/src/metrics/metric_service.rs
- query/src/servers/http/http_services.rs
- query/src/servers/http/v1/statement.rs
- query/src/servers/http/v1/statement_test.rs
Migrate `databend-query` and `databend-metasrv` from `axum` to `poem`
- Improvement
Fixes #2666 
Unit Tests
> Migrate to Poem

- query/src/datasources/table_func/numbers_stream.rs
- query/src/datasources/table_func/numbers_table.rs
- query/src/pipelines/transforms/mod.rs
When order-by and limit are set, we just return top-n rows for every scan part.
- Improvement
Fixes #2617
Unit Tests
> number table apply top-n (order-by and limit)

- metasrv/src/meta_service/meta_service_impl_test.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/meta_service/raftmeta_test.rs
> [metasrv] refactor: remove redundant method MetaNode::boot_non_voter()

- query/src/sql/plan_parser.rs
- query/src/sql/sql_parser.rs
- query/src/sql/sql_statement.rs
- website/databend/docs/sqlstatement/show-commands/show-users.md
- website/databend/mkdocs.yml
Add `show users` statement.
```
mysql> SHOW USERS;
+------+-----------+----------+-----------+
| name | hostname  | password | auth_type |
+------+-----------+----------+-----------+
| test | localhost | password |         3 |
+------+-----------+----------+-----------+
```
- Improvement
Fixes https://github.com/datafuselabs/databend/issues/2687
Unit Tests
> [query] add show uses statement

- Cargo.lock
- metasrv/Cargo.toml
- metasrv/src/any_error/any_error_impl.rs
- metasrv/src/any_error/any_error_test.rs
- metasrv/src/any_error/mod.rs
By converting std::Error to AnyError, structured error can be serialized
and transferred.
The **type** of an error is not kept. However, AnyError stores the
`description`, `source` and `backtrace` info.
E.g., to define a structured error:
```rust
pub enum MetaError {
#[error(transparent)]
ConnectionError(#[from] ConnectionError),
...
}
pub struct ConnectionError {
msg: String,
#[source]
source: AnyError,
}
impl ConnectionError {
pub fn new(source: tonic::transport::Error, msg: String) -> Self {
Self { msg, source: AnyError::new(&source), }
}
}
// Usage:
let err:MetaError = ConnectionError::new(tonic_err, "when connecting to 1.2.3.4").into()
```
- New Feature
> [common/exception] feature: add AnyError as a representation of std error for transmit

- Cargo.lock
- common/meta/raft-store/src/config.rs
- metasrv/Cargo.toml
- metasrv/proto/meta.proto
- metasrv/src/api/flight_server.rs
- metasrv/src/meta_service/errors.rs
- metasrv/src/meta_service/message.rs
- metasrv/src/meta_service/meta_leader.rs
- metasrv/src/meta_service/meta_service_impl.rs
- metasrv/src/meta_service/mod.rs
- metasrv/src/meta_service/network.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/meta_service/raftmeta_test.rs
- metasrv/src/proto/meta.rs
- metasrv/tests/flight/metasrv_flight_api.rs
- Feature: add cli arg `--join addr1,addr2...` to join a new node to a
metasrv cluster.
- Feature: add RPC `forward` to forward a request to other metasrv node.
It is used to proxy an admin request to a known leader.
- Refactor: add `MetaError` which is serializable and structured, to
express errors a meta server emits.
`MetaErro` can be transmitted between metasrv nodes.
- Refactor: add `MetaLeader` as a container of admin API.
- Refactor: simplify From/Into for `RaftMes`
- Test: add unit test of `join`ing node to cluster.
- part of #2668
- New Feature
> [metasrv] feature: add `join` API to join a node to cluster.

- common/management/src/user/user_api.rs
- common/meta/types/src/lib.rs
- common/meta/types/src/user_quota.rs
- common/meta/types/src/user_quota_test.rs
- query/src/datasources/database/system/users_table_test.rs
- query/src/interpreters/interpreter_user_create.rs
- query/src/users/user.rs
1. Only add `quota` to a user, it's no limited for now.
- New Feature
Fixes #2704 
Unit Tests
> USER-2704: Add user quota to user info

- query/src/datasources/index/range_filter_test.rs
- query/src/datasources/table/fuse/meta/table_snapshot.rs
- query/src/datasources/table/fuse/table.rs
- query/src/datasources/table/fuse/table_do_read.rs
- query/src/datasources/table/fuse/table_do_read_partitions.rs
- query/src/datasources/table/fuse/table_test.rs
- query/src/datasources/table/fuse/util/statistic_helper.rs
Statistics returned by `Table::read_partitions` should take push-down projections into account
- add field `in_memory_size` to `ColStats`
the value of this field is obtained by using `DataColunm::get_array_memory_size`
@sundy-li please take a look, is this method supposed to be used in this case?
- `Statistics` returned by `Table::to_partitions` takes `Extras::projection` into account
bytes of pruned columns will NOT be accumulated into `Statistics::read_bytes`
- Bug Fix
Fixes #2672
Unit Tests
> ISSUE-2672:  statistics returned by `Table::read_partitions` should take push-down projections into account

- metasrv/proto/meta.proto
- metasrv/src/meta_service/message.rs
- metasrv/src/meta_service/meta_service_impl.rs
- metasrv/src/proto/meta.rs
> [metasrv] refactor: use RaftRequest as a request type, use RaftReply as reply type for raft communication

- common/management/src/namespace/namespace_mgr.rs
- common/management/src/user/user_mgr.rs
- common/management/src/user/user_mgr_test.rs
- common/meta/api/src/kv_api.rs
- common/meta/api/src/kv_api_test_suite.rs
- common/meta/api/src/lib.rs
- common/meta/embedded/src/kv_api_impl.rs
- common/meta/flight/src/flight_action.rs
- common/meta/flight/src/impls/kv_api_impl.rs
- metasrv/src/executor/action_handler.rs
- metasrv/src/executor/kv_handlers.rs
- metasrv/tests/flight/metasrv_flight_api.rs
> [common/meta/api] refactor: remove api update_kv_meta(), upsert_kv() is quite enough

- metasrv/src/meta_service/message.rs
- metasrv/src/meta_service/meta_leader.rs
- metasrv/src/meta_service/meta_service_impl.rs
- metasrv/src/meta_service/meta_service_impl_test.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/meta_service/raftmeta_test.rs
> [metasrv] refactor: move write_to_local_leader() to MetaLeader

- Cargo.lock
- common/base/Cargo.toml
- common/base/src/http_shutdown_handlers.rs
- metasrv/Cargo.toml
- metasrv/src/api/http_service.rs
- query/Cargo.toml
- query/src/api/http_service.rs
- query/src/common/service/http_shutdown_handles.rs
Bump poem from `1.0.21` to `1.0.23`.
- Improvement
Fixes #2736
Unit Tests
> Bump poem from `1.0.21` to `1.0.23`.

- common/datablocks/Cargo.toml
- common/datablocks/src/lib.rs
- common/datablocks/tests/it/data_block.rs
- common/datablocks/tests/it/kernels/data_block_concat.rs
- common/datablocks/tests/it/kernels/data_block_filter.rs
- common/datablocks/tests/it/kernels/data_block_group_by.rs
- common/datablocks/tests/it/kernels/data_block_group_by_hash.rs
- common/datablocks/tests/it/kernels/data_block_scatter.rs
- common/datablocks/tests/it/kernels/data_block_slice.rs
- common/datablocks/tests/it/kernels/data_block_sort.rs
- common/datablocks/tests/it/kernels/data_block_take.rs
- common/datablocks/tests/it/kernels/mod.rs
- common/datablocks/tests/it/main.rs
apply the new test style to common-datablocks
- Improvement
Related #1866
Unit Tests
> [test] apply the new test style to common-datablocks

- cli/src/cmds/clusters/add.rs
- cli/src/cmds/clusters/create.rs
- cli/src/cmds/status.rs
- cli/tests/it/clusters/create.rs
- common/exception/src/exception.rs
- common/management/src/cluster/cluster_api.rs
- common/management/src/cluster/cluster_mgr.rs
- common/management/src/cluster/cluster_mgr_test.rs
- common/management/src/cluster/mod.rs
- common/management/src/lib.rs
- common/meta/types/src/cluster.rs
- docker/databend-query-docker.toml
- query/src/bin/databend-query.rs
- query/src/clusters/cluster.rs
- query/src/configs/config_query.rs
- query/src/configs/config_test.rs
- query/src/datasources/database/system/configs_table_test.rs
- query/src/users/user_mgr.rs
- query/src/users/user_mgr_test.rs
- scripts/deploy/config/databend-query-embedded-meta.toml
- scripts/deploy/config/databend-query-node-1.toml
- scripts/deploy/config/databend-query-node-2.toml
- scripts/deploy/config/databend-query-node-3.toml
This PR mainly change the config/query field:
1. namespace -> cluster_id
2. tenant -> tenant_id
- Improvement
Fixes #2742 
Fixes #2746 
Unit Tests
> ISSUE-2472: namespace -> cluster, tenant -> tenant_id

- .gitignore
- common/base/src/stop_handle.rs
- metasrv/src/api/flight_server.rs
- metasrv/src/meta_service/meta_service_impl_test.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/meta_service/raftmeta_test.rs
- metasrv/src/store/meta_raft_store_test.rs
- metasrv/src/tests/service.rs
- metasrv/tests/flight/metasrv_flight_api.rs
- metasrv/tests/flight/metasrv_flight_tls.rs
> [metasrv] refactor: remove unused temp-dir in test-context

- common/base/src/progress.rs
- query/src/servers/http/http_services.rs
- query/src/servers/http/mod.rs
- query/src/servers/http/v1/block_to_json.rs
- query/src/servers/http/v1/block_to_json_test.rs
- query/src/servers/http/v1/http_query_handlers.rs
- query/src/servers/http/v1/http_query_handlers_test.rs
- query/src/servers/http/v1/mod.rs
- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/http/v1/query/http_query.rs
- query/src/servers/http/v1/query/http_query_manager.rs
- query/src/servers/http/v1/query/mod.rs
- query/src/servers/http/v1/query/result_data_manager.rs
- query/src/servers/http/v1/statement.rs
- query/src/sessions/context.rs
- query/src/sessions/context_shared.rs
- query/src/sessions/sessions.rs
Add new endpoint /v1/query to support sql.
1. post query with JSON with format HttpQueryRequest, and return JSON with format QueryResponse
2. Pagination with long polling.
3. result data is embedded in QueryResponse.
4. return the following  4 URIs,   the client should rely on the endpoint  /v1/query and URIs returned in the response. the other endpoints may change without notices.
1. next: get the next page (together with progress) with long polling.   page N is released when Page N+1 is requested. 
2. state: return struct like QueryResponse,  but the data field is empty. short polling.
3. kill: kill running query
4. delete: kill running query and delete it …
> [query/server/http] Add /v1/query.

- metasrv/src/api/flight_server.rs
- metasrv/src/lib.rs
- metasrv/src/meta_service/meta_service_impl_test.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/meta_service/raftmeta_test.rs
- metasrv/src/store/meta_raft_store.rs
- metasrv/src/store/meta_raft_store_test.rs
- MetaNode::start() choose boot, open or join mode by `raft_config`.
- Add trait `Opened` to return whether an instance is created or opened
from some existent state.
`MetaRaftStore` and `MetaNode` impls `is_opened()`.
- Improvement
> [metasrv] refactor: add MetaNode::start() to start meta in boot, open or join mode etc.

- common/exception/src/exception.rs
- metasrv/src/api/flight_server.rs
- metasrv/src/bin/metasrv.rs
- metasrv/src/tests/service.rs
> [metasrv] refactor: build MetaNode outside FlightServer, let many service be able to reference the meta node

- metasrv/src/api/flight_server.rs
- metasrv/src/bin/metasrv.rs
- metasrv/src/tests/service.rs
- metasrv/tests/flight/metasrv_flight_api.rs
- Feature: FlightServer::start() blocks until listening is estabelisthed.
- Refactor: FlightServer::start() takes a ref to self instead of an
owned instance, to let user be able to call FlightServer::stop().
- Feature: impl force/graceful shutdown for FlightServer.
- Refactor: simplify FlightServer life cycle mng in tests.
> [metasrv] impl Stoppable for meta/FlightServer

- Makefile
- scripts/ci/ci-run-stateful-tests-standalone.sh
1. Fix the query tenant_id and cluster_id parameters
2. Change bendctl from debug to release for stateful test
- Improvement
Fixes #issue
Unit Tests
> Improve the stateful test from debug to release

- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/meta_service/raftmeta_test.rs
- metasrv/src/tests/service.rs
- metasrv/tests/flight/metasrv_flight_api.rs
> [metasrv] test: always disable fsync on mac, to let integration test pass on mac VM

- common/infallible/Cargo.toml
- common/infallible/tests/it/main.rs
- common/infallible/tests/it/mutex.rs
- common/infallible/tests/it/rwlock.rs
apply the new test style to common-infallible
- Improvement
Related #1866
Unit Tests
> [test] apply the new test style to common-infallible

- Cargo.lock
- common/functions/Cargo.toml
- common/functions/src/scalars/maths/ceil.rs
- common/functions/src/scalars/maths/floor.rs
- common/functions/src/scalars/maths/math.rs
- common/functions/src/scalars/maths/mod.rs
- common/functions/tests/it/scalars/maths/ceil.rs
- common/functions/tests/it/scalars/maths/floor.rs
- common/functions/tests/it/scalars/maths/mod.rs
Add ceil, ceiling, floor func
```sql
mysql> select ceil(123.6);
| ceil(123.6) |
|         124 |
Read 1 rows, 1 B in 0.002 sec., 477.44 rows/sec., 477.44 B/sec.
mysql> select ceil(123);
+-----------+
| ceil(123) |
+-----------+
|       123 |
+-----------+
Read 1 rows, 1 B in 0.003 sec., 301.25 rows/sec., 301.25 B/sec.
mysql> select ceiling('-12.3aa1');
+---------------------+
| ceiling('-12.3aa1') |
+---------------------+
|                 -12 |
+---------------------+
Read 1 rows, 1 B in 0.000 sec., 2.26 thousand rows/sec., 2.26 KB/sec.
mysql> select ceiling('+12.3aa1'); …
```
> [function] Add ceil, ceiling, floor func

- Makefile
Small fixes `build-release` rule in Makefile.
Fixes N/A
N/A
> Small fix: makefile rule build-release to build

- common/management/Cargo.toml
- common/management/src/lib.rs
- common/management/src/user/mod.rs
- common/management/tests/it/cluster.rs
- common/management/tests/it/main.rs
- common/management/tests/it/user.rs
[test] apply the new test style to common-management
- Improvement
Related #1866
Unit Tests
> [test] apply the new test style to common-management

- common/functions/src/scalars/arithmetics/arithmetic.rs
- common/functions/src/scalars/arithmetics/arithmetic_div.rs
- common/functions/src/scalars/arithmetics/arithmetic_minus.rs
- common/functions/src/scalars/arithmetics/arithmetic_modulo.rs
- common/functions/src/scalars/arithmetics/arithmetic_mul.rs
- common/functions/src/scalars/arithmetics/arithmetic_plus.rs
- common/functions/src/scalars/function.rs
- common/functions/src/scalars/mod.rs
- common/planners/src/plan_expression.rs
- common/planners/src/plan_expression_common.rs
- common/planners/src/plan_expression_rewriter.rs
- common/planners/src/plan_expression_sort.rs
- common/planners/src/plan_expression_visitor.rs
- common/planners/src/plan_rewriter.rs
- query/src/datasources/index/range_filter.rs
- query/src/optimizers/mod.rs
- query/src/optimizers/optimizer_constant_folding.rs
- query/src/optimizers/optimizer_top_n_push_down.rs
- query/src/optimizers/optimizer_top_n_push_down_test.rs
- query/src/optimizers/utils.rs
- query/src/pipelines/transforms/transform_sort_partial.rs
- query/src/sql/plan_parser.rs
Add monotonicity visitor for extracting the column from monotonic function. For example 'order by number+3' can be optimized to 'order by number', because 'number+3' -> f(x) = x+3    is a monotonic function.
The new added class is  applied for top-n optimizer in the PR. Thus query like "select number*number from numbers(100000000000) order by number+number+12 limit 10" will be optimized to only fetch top 10 rows -- will be fast.
```
mysql> select number*number from numbers(100000000000) order by number+number+12 limit 10;
+-------------------+
| (number * number) |
+-------------------+
|                 0 |
|                 1 |
|                 4 |
|                 9 |
|                16 |
| …
```
> Add monotonicity check visitor

- scripts/ci/ci-run-unit-tests.sh
Fix make test failure on macOS 12.0 https://github.com/rust-lang/rust/issues/90342
Fixes #issue
> Fix make test failure on macOS 12.0

- query/src/sql/sql_parser.rs
Make Fuse Engine as default table engine
- Improvement
Fixes #issue
Unit Tests
> Make Fuse Engine as default table engine

- Cargo.lock
- common/dal/Cargo.toml
- common/dal/src/data_accessor.rs
- common/dal/src/impls/aws_s3/s3.rs
- common/dal/src/impls/azure_blob/azure_blob_accessor.rs
- common/dal/src/impls/local.rs
- common/dal/src/lib.rs
- common/dal/src/metrics/constants.rs
- common/dal/src/metrics/dal_metrics.rs
- common/dal/src/metrics/mod.rs
- common/dal/src/metrics/stream_metrics.rs
- common/dal/tests/it/main.rs
- common/dal/tests/it/metrics/dal_metrics.rs
- common/dal/tests/it/metrics/mod.rs
- common/metrics/src/lib.rs
- common/metrics/src/recorder.rs
- query/Cargo.toml
- query/src/datasources/common/dal_builder.rs
- query/src/datasources/common/dal_builder_test.rs
- query/src/datasources/table/fuse/io/block_appender.rs
- query/src/sessions/context.rs
introduce a delegation of DAL  `DALWithMetric`, which intercepts input/output operations and spills simple statistics (bytes read/write) to metrics components
fixing 
- issue #2806
- Improvement
Fixes #2806
Unit Tests
> ISSUE-2806: Add metrics to dal operations (label with tenant_id and cluster_id) 

- query/src/configs/config_storage.rs
Set storage_type to `disk` by default, make databend-query works with fuse engine wihtout yaml file.
- Improvement
Fixes #issue
Unit Tests
> Set storage_type to disk by default

- .gitignore
- query/src/bin/databend-query.rs
- query/src/configs/config.rs
- query/src/configs/config_storage.rs
- query/src/configs/config_test.rs
1. Change the disk storage data_path to `_data`
2. Add a new function called `initial_dir` for the config data path initial
- Improvement
Fixes #2845 
Unit Tests
> ISSUE-2845: Initial the data directory

- common/functions/src/scalars/others/inet_ntoa.rs
- common/functions/src/scalars/others/mod.rs
- common/functions/src/scalars/others/other.rs
- common/functions/tests/it/scalars/others.rs
Add support for inet_ntoa(convert IPv4 bytes to string)
- [clickhouse IPv4NumToString/INET_NTOA](https://clickhouse.com/docs/en/sql-reference/functions/ip-address-functions/#ipv4numtostringnum)
- [MySQL INET_NTOA](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_inet-ntoa)
- [glibc inet_ntoa() - man7.org](https://man7.org/linux/man-pages/man3/inet_aton.3.html)
- New Feature
Fixes #2823
Unit Tests
> [function] Add support for inet_ntoa

- query/src/catalogs/impls/catalog/overlaid_catalog.rs
- query/src/catalogs/impls/catalog/system_catalog.rs
pre-check the whether  `dbname` of the deleted table belongs to the system database.
Fixes #2841
Unit Tests
> Improve the error for the drop table in system database

- common/base/src/http_shutdown_handlers.rs
- metasrv/src/api/flight_server.rs
- metasrv/src/api/http_service.rs
- metasrv/src/metrics/metric_service.rs
- Problem:
The current impl of 2-phase shutdown(graceful then force)
always blocks on `force.recv()`:
```rust
self.shutdown_handler.shutdown(true).await;
if let Some(mut force) = force {
log::info!("waiting for force");
let _ = force
.recv()
.await
.expect("Failed to recv the shutdown signal");
self.shutdown_handler.shutdown(false).await;
```
Thus when a graceful shutdown is actually finished,
it still does not return.
- Solution:
The shutdown handler has to wait for both the graceful shutdown join
handle and the force.recv(),
and receive the first returned one.
- This is one of the causes of that restarting a metasrv cluster does
not work. Because the running metasrv processes never quit.
- Bug Fix
> [metasrv] fix: graceful shutdown blocks for ever.

- common/exception/src/exception.rs
- query/src/servers/http/v1/http_query_handlers.rs
- query/src/servers/http/v1/http_query_handlers_test.rs
- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/http/v1/query/http_query.rs
- query/src/servers/http/v1/query/http_query_manager.rs
- query/src/servers/http/v1/query/result_data_manager.rs
- query/src/servers/http/v1/statement.rs
1. remove request_error  and use HTTP status codes like 404  with text messages for these errors.
2. extend error, include fields of ErrorCode
3. move progress into stats
4. rename delete_uri  to  final_uri to be in concert with next_uri, let the server decide what to do.
5.  user SHOULD get final_uri if next_uri is null(all fetched) or does not need the remaining data. 
6. serve as ack for the last page. (other page is acked by next_uri)
/v1/query was introduced in  https://github.com/datafuselabs/databend/pull/2688
Unit Tests
> Adjust response of /v1/query.

- query/src/pipelines/transforms/transform_expression_executor.rs
- query/src/pipelines/transforms/transform_expression_test.rs
result：
```
mysql> SELECT number + 1 AS number, number AS number1 FROM numbers(10);
+--------+---------+
| number | number1 |
+--------+---------+
|      6 |       5 |
|      2 |       1 |
|      8 |       7 |
|      9 |       8 |
|     10 |       9 |
|      1 |       0 |
|      4 |       3 |
|      3 |       2 |
|      7 |       6 |
|      5 |       4 |
+--------+---------+
10 rows in set (0.01 sec)
Read 10 rows, 80 B in 0.002 sec., 5.22 thousand rows/sec., 41.78 KB/sec.
```
- Bug Fix
Fixes #2857
Unit Tests
> [bugfix] fix issue 2857:Wrong query result when use alias

- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/raft-store/src/state_machine/state_machine_meta.rs
> [metasrv] refactor: use derive_more to simplify StateMachine meta value conversion

- common/functions/src/scalars/hashes/md5hash.rs
- common/functions/src/scalars/hashes/sha1hash.rs
- common/functions/tests/it/scalars/hashes.rs
- website/databend/docs/sqlstatement/hash-functions/md5hash.md
- website/databend/docs/sqlstatement/hash-functions/sha1hash.md
In addition to #2889 added support nullable value in SHA1 and MD5 func
- Improvement
Fixes #issue
Unit Tests
> Support nullable value in SHA1 and MD5 func

- common/meta/api/src/meta_api.rs
- common/meta/api/src/meta_api_test_suite.rs
- common/meta/embedded/src/meta_api_impl.rs
- common/meta/flight/src/flight_action.rs
- common/meta/flight/src/impls/meta_api_impl.rs
- common/meta/flight/tests/it/flight_client.rs
- common/meta/types/src/database.rs
- common/meta/types/src/lib.rs
- metasrv/src/executor/meta_handlers.rs
- query/src/catalogs/backends/impls/meta_remote.rs
- query/src/catalogs/impls/catalog/metastore_catalog.rs
> [common/meta] refactor: rename get_tables to list_tables

- query/src/catalogs/impls/catalog/mutable_catalog.rs
- query/src/datasources/context.rs
- query/src/datasources/database/fuse/database.rs
- query/src/datasources/database/mod.rs
- query/src/datasources/database/prelude.rs
- query/src/datasources/database_engine.rs
- query/src/datasources/database_engine_registry.rs
- query/src/datasources/database_engine_registry_test.rs
- query/src/datasources/mod.rs
- query/src/datasources/table/csv/csv_table.rs
- query/src/datasources/table/csv/csv_table_test.rs
- query/src/datasources/table/fuse/table.rs
- query/src/datasources/table/memory/memory_table.rs
- query/src/datasources/table/memory/memory_table_test.rs
- query/src/datasources/table/null/null_table.rs
- query/src/datasources/table/null/null_table_test.rs
- query/src/datasources/table/parquet/parquet_table.rs
- query/src/datasources/table/parquet/parquet_table_test.rs
- query/src/datasources/table_engine.rs
- query/src/tests/context.rs
- query/src/tests/mod.rs
1. Introduce `DataSourceContext` as the database creates entry
2. Add database engine register for MutableCatalog
- Improvement
Fixes #2948 
Unit Tests
> CATALOG-2948: Add database engine register for MutableCatalog

- query/src/sql/statements/mod.rs
- query/src/sql/statements/query/mod.rs
- query/src/sql/statements/query/query_normalizer.rs
- query/src/sql/statements/query/query_qualified_rewriter.rs
- query/src/sql/statements/statement_select.rs
Rename QueryNormalizeData to QueryASTIR
- Improvement
Fixes #issue
> Rename QueryNormalizeData to QueryASTIR

- common/functions/src/scalars/maths/log.rs
- common/functions/tests/it/scalars/maths/log.rs
Fix log function with constant column. cc @flaneur2020 
before
```
mysql> select number, log(number, 2) from numbers(10);
+--------+---------------------+
| number | log(number, 2)      |
+--------+---------------------+
|      7 |  0.3562071871080222 |
|      8 |  0.3562071871080222 |
|      9 |  0.3562071871080222 |
|      6 |  0.3868528072345416 |
|      4 |                 0.5 |
|      2 |                   1 |
|      3 |  0.6309297535714574 |
|      1 |                 inf |
|      5 | 0.43067655807339306 |
|      0 |                  -0 |
+--------+---------------------+
10 rows in set (0.01 sec)
mysql> select log(8, 2);
+---------------------+
| log(8, 2)           |
+---------------------+
| …
```
> [function] Fix log function with constant column

- scripts/deploy/databend-query-cluster-3-nodes.sh
- scripts/deploy/databend-query-standalone-embedded-meta.sh
- scripts/deploy/databend-query-standalone.sh
the servers may fail to shutdown some times (most time it is a bug). developers who use these scripts (maybe through 'make run')  may connect to the old server and encounter strange errors,  or find their changes not working.
and it may not be easily covered by tests, because this may happen after some ops on the servers.
1.  kill -9 to proceed
2. let the user be aware of this. user may report it or it is a bug introduced by the local change.
Unit Tests
> force kill databend-query/meta when fail to kill it.

- query/src/sessions/context_shared.rs
- query/src/sessions/mod.rs
- query/src/sessions/session.rs
- query/src/sessions/session_info.rs
- query/src/sessions/session_status.rs
- query/src/sessions/session_status_test.rs
- query/src/sessions/settings.rs
- tests/suites/0_stateless/03_0011_select_from_system_processes.result
- tests/suites/0_stateless/03_0011_select_from_system_processes.sql
This PR:
* Split session mutable status to single file and make all mutable operations to be fine-grained with RwLock, there is no deadlock happens
- Improvement
Fixes #2963 
Unit Tests
> SESSION-2963: Make session lock to be fine-grained

- cli/src/cmds/root.rs
use both log_level and log-level as option names,  the former seems a typo.
Fixes #2696
Unit Tests
> fix bendcli option names error.

- common/exception/src/exception.rs
- common/management/src/lib.rs
- common/management/src/stage/mod.rs
- common/management/src/stage/stage_api.rs
- common/management/src/stage/stage_mgr.rs
- common/management/src/user/user_mgr.rs
- common/management/tests/it/stage.rs
- common/management/tests/it/user.rs
- common/meta/types/src/lib.rs
- common/meta/types/src/user_stage.rs
- common/meta/types/tests/it/main.rs
- common/meta/types/tests/it/user_stage.rs
- query/src/users/mod.rs
- query/src/users/user_mgr.rs
- query/src/users/user_stage.rs
- query/src/users/user_stage_test.rs
* Add user stage api stored to metasrv,
* Add stage operations to query/users
this is part of #2976
- New Feature
Fixes #2980
Unit Tests
> MGR-2976: Add stage to management

- query/src/servers/http/v1/http_query_handlers_test.rs
- query/src/servers/http/v1/query/result_data_manager.rs
Add tests for http handler.  and limit rows per page to 10000 so the client can test on the pagination easily.
1.  pagination
2. insert
Unit Tests
> Add tests for http handler.

- .gitignore
it seems there'll generate a query/_data directory after runnint the stateless test in the localhost.
gitignore can ignore a directory by a `/` suffix, like `query/_data/`.
after adding this config in .gitignore, the `query/_data/` in untracked files disappears. 
- Improvement
Fixes #issue
Unit Tests
> gitignore the query/_data directory

- query/src/datasources/database/system/processes_table.rs
- query/src/servers/clickhouse/interactive_worker.rs
- query/src/servers/mysql/mysql_interactive_worker.rs
- query/src/sessions/session.rs
- query/src/sessions/session_info.rs
- query/src/sessions/session_status.rs
- query/src/sessions/session_status_test.rs
- query/src/sql/plan_parser_test.rs
this PR adds a user record in the session, which recorded on the authenticate phase of mysql & clickhouse. it also adds a user field in the `system.processes` table.
- Improvement
Fixes #2779
Unit Tests
> [ISSUE-2779] Add user in session

- common/functions/src/scalars/arithmetics/arithmetic.rs
- common/functions/src/scalars/arithmetics/arithmetic_div.rs
- common/functions/src/scalars/arithmetics/arithmetic_minus.rs
- common/functions/src/scalars/arithmetics/arithmetic_modulo.rs
- common/functions/src/scalars/arithmetics/arithmetic_mul.rs
- common/functions/src/scalars/arithmetics/arithmetic_plus.rs
- common/functions/src/scalars/function.rs
- common/functions/src/scalars/maths/abs.rs
- common/functions/src/scalars/mod.rs
- query/src/datasources/index/range_filter.rs
- query/src/optimizers/mod.rs
- query/src/optimizers/optimizer_top_n_push_down.rs
- query/src/optimizers/utils.rs
- query/src/optimizers/utils_test.rs
1. Add ranged monotonic check for arithmetic Plus/Minus
2. Add ranged monotonic check for function 'abs'
3. Integrate with range_filter 
4. unit test added to verify expression monotonic.
- Improvement
Fixes #issue
Unit Tests
> Apply monotonic function to range filter

- common/functions/src/scalars/udfs/current_user.rs
- common/functions/src/scalars/udfs/mod.rs
- common/functions/src/scalars/udfs/udf.rs
- common/planners/src/plan_expression.rs
- query/src/functions/context_function.rs
- query/src/functions/context_function_test.rs
- query/src/sessions/context.rs
- query/src/sessions/context_shared.rs
- tests/suites/0_stateless/02_0016_function_context.result
- tests/suites/0_stateless/02_0016_function_context.sql
this PR depends on https://github.com/datafuselabs/databend/pull/2986
this PR adds a current_user() function, to test the session's current user
- Improvement
Fixes #2994
Unit Tests
> ISSUE-2994: add function current_user()

- common/meta/embedded/src/meta_api_impl.rs
- common/meta/raft-store/src/state_machine/mod.rs
- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/raft-store/src/state_machine/sm_meta_api_impl.rs
- common/meta/raft-store/tests/it/state_machine/meta_api_impl.rs
- common/meta/raft-store/tests/it/state_machine/mod.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/store/meta_raft_store.rs
StateMachine already provided meta-api methods thus it is natural to
imopl MetaApi for it.
And this let other upper level mods be able to reuse it.
E.g., flight action handler do not need to re-impl MetaApi.
Now MetaEmbedded is purely a wrapper of StateMachine
- New Feature
> [common/meta/raft-store] feature: impl MetaAPI for StateMachine

- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/raft-store/src/state_machine/sm_meta_api_impl.rs
- common/meta/raft-store/tests/it/state_machine/mod.rs
- common/meta/types/src/database.rs
- metasrv/src/executor/meta_handlers.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/tests/it/meta_service/raftmeta.rs
Methods that are already impl-ed in `MetaApi for StateMachine` are removed.
- Improvement
> [metasrv] refactor: remove dup methods

- common/functions/src/scalars/arithmetics/arithmetic_div.rs
- common/functions/src/scalars/arithmetics/arithmetic_minus.rs
- common/functions/src/scalars/arithmetics/arithmetic_mul.rs
- common/functions/src/scalars/arithmetics/arithmetic_plus.rs
- common/functions/src/scalars/dates/date.rs
- common/functions/src/scalars/dates/number_function.rs
- common/functions/src/scalars/dates/week_date.rs
- common/functions/src/scalars/expressions/expression.rs
- common/functions/src/scalars/function_factory.rs
- common/functions/src/scalars/maths/abs.rs
- common/functions/src/scalars/maths/ceil.rs
- common/functions/src/scalars/maths/floor.rs
- common/functions/src/scalars/maths/sign.rs
Add maybe_monotonic feature for functions, maybe_monotonic indicate the function maybe monotonicity in a range of values, it can be used in range filter.
- New Feature
- Improvement
Fixes #3008
> ISSUE-3008: Add maybe_monotonic feature for functions

- common/management/src/cluster/cluster_mgr.rs
- common/meta/raft-store/src/state_machine/applied_state.rs
- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/raft-store/src/state_machine/sm_meta_api_impl.rs
- common/meta/raft-store/tests/it/state_machine/mod.rs
- common/meta/types/src/change.rs
- metasrv/src/executor/meta_handlers.rs
- metasrv/tests/it/meta_service/meta_service_impl.rs
- Refactor: internally, CreateTable returns the TableMeta that is saved into
metasrv.
- Refactor: remove an unused internal response type:
AppliedState::TableIdent
- New Feature
> [common/meta/types] feature: add `ident` to `Change` to indicate what resource is changed

- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/raft-store/src/state_machine/sm_meta_api_impl.rs
- common/meta/raft-store/tests/it/state_machine/mod.rs
- metasrv/src/executor/meta_handlers.rs
- Fix: when `db_name` exists in `database_lookup` table, it should not
continue on to create a db-meta record.
- Improvement
> [common/meta/raft-store] refactor: CreateDatabase returns DatabaseMeta as aninternal result

- docker/meta/Dockerfile
- docker/query/Dockerfile
Add basic ca-credential for DAL layer
Fixes #issue
Unit Tests
> [BUILD] add https credential for DAL

- query/src/datasources/database/github/repo_issues_table.rs
- query/src/datasources/database/github/repo_prs_table.rs
remove extra comma in labels and assigness display
- Improvement
Fixes #issue
Unit Tests
> remove extra comma in labels and assigness display

- common/building/src/lib.rs
- metasrv/src/lib.rs
- metasrv/src/proto.rs
- metasrv/tests/it/configs.rs
- metasrv/tests/it/flight/metasrv_flight_api.rs
- metasrv/tests/it/flight/metasrv_flight_tls.rs
- metasrv/tests/it/meta_service/meta_node.rs
- metasrv/tests/it/meta_service/meta_service_impl.rs
- metasrv/tests/it/meta_service/mod.rs
- metasrv/tests/it/store.rs
- metasrv/tests/it/tests/service.rs
> [metasrv] refactor: rename test function names

- common/datavalues/src/arrays/ops/agg.rs
```
:) select max(number) from numbers_mt(10000000000);
| max(number) |
|  9999999999 |
1 row in set (2.87 sec)
Read 10000000000 rows, 80 GB in 2.869 sec., 3.49 billion rows/sec., 27.89 GB/sec.
After: 
:) select max(number) from numbers_mt(10000000000);
| max(number) |
|  9999999999 |
1 row in set (0.54 sec)
Read 10000000000 rows, 80 GB in 0.529 sec., 18.92 billion rows/sec., 151.33 GB/sec.
```
- Improvement
Fixes #issue
Unit Tests
> Speed up min/max agg

- Cargo.lock
- common/meta/embedded/Cargo.toml
- common/meta/embedded/src/meta_embedded.rs
- common/meta/sled-store/src/db.rs
- query/src/bin/databend-query.rs
- query/src/catalogs/impls/mutable_catalog.rs
- query/src/common/meta/meta_client.rs
For production use of meta-embedded, use a persistent meta-data dir,
to avoid meta-data loss when `query` is restarted.
Let `query` create a process-wise global meta-store if the remote meta-store address is empty.
Then sub routines use this global meta-store.
Unit tests do not initialize such a process-wise global meta-store thus they still build a meta-store backed by a temp-dir.
- New Feature
> [common/meta/embedded] feature: for non-test use, init meta store in configured dir

- query/src/sql/sql_parser_test.rs
- tests/suites/0_stateful/12_0000_copy_s3.sql
- website/databend/docs/sqlstatement/data-loading/copy-data-from-stage.md
- website/databend/docs/sqlstatement/data-loading/http-streaming-load.md
- website/databend/mkdocs.yml
> Add docs for load

- query/src/configs/config_query.rs
Set table_engine_memory_enabled default value: true
- Improvement
Fixes #issue
> Set table_engine_memory_enabled default value

- .github/workflows/databend-base.yml
- .github/workflows/stateful-tests-standalone.yml
- .github/workflows/stateless-tests-cluster.yml
- .github/workflows/stateless-tests-standalone.yml
- .github/workflows/unit-tests.yml
the CI seems break in the main branch, error message:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotFound, error: "failed to invoke protoc (hint: https://docs.rs/prost-build/#sourcing-protoc): No such file or directory (os error 2)" }', common/meta/flight/build.rs:34:10
```
the cause might be something changed in the CI base image?
this PR is a quick-and-dirty fix on the CI break to avoid blocking the other pull requests, we'd better find out the root cause of this CI break.
- Bug Fix
Fixes #3208
Unit Tests
> try fix the CI error about protoc

- query/src/bin/databend-query.rs
Signed-off-by: fufesou <shuanglongchen@yeah.net>
Http usage always show 8001 though config changed when app is startting.
This PR change the print information.
http handler usage, change port along with the config #3239
> show http usage port in config

- query/src/sql/sql_parser.rs
- query/src/sql/sql_parser_test.rs
Add other table option for create table with comment.
- New Feature
related https://github.com/datafuselabs/databend/issues/2979
Unit Tests
> Add other table options for create table

- .cargo/config
- .github/workflows/databend-docker.yml
- .github/workflows/databend-performance-dispatch.yaml
- .github/workflows/databend-release.yml
- Makefile
use objcopy to reduce binary size
the principle is the same as in the previous programme.
Fixes #2677 
Unit Tests
> [makefile] use objcopy to reduce binary size

- query/src/interpreters/interpreter_show_create_table.rs
- query/src/interpreters/interpreter_show_create_table_test.rs
- query/src/storages/storage_table.rs
- tests/suites/0_stateless/06_0001_show_create_table.result
- tests/suites/0_stateless/06_0001_show_create_table.sql
show table options in `show create table`
```
mysql> create table t1(a Int32) comment='this is a comment';
mysql> show create table t1;
+-------+----------------------------------------------------------------------------+
| Table | Create Table                                                               |
+-------+----------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
`a` Int32,
) ENGINE=FUSE COMMENT='this is a comment' |
+-------+----------------------------------------------------------------------------+
```
- Improvement
Fixes [#issue](https://github.com/datafuselabs/databend/issues/3251)
Unit Tests
> show table options

- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/raft-store/src/state_machine/sm_kv_api_impl.rs
- common/meta/raft-store/src/state_machine/sm_meta_api_impl.rs
- common/meta/raft-store/tests/it/state_machine/mod.rs
- common/meta/sled-store/src/lib.rs
- common/meta/sled-store/src/sled_tree.rs
make `StateMachine::apply` use transaction to perform operations
- Improvement
#2422 
Unit Tests
> [metasrv] make `StateMachine::apply` use transaction to perform operations

- common/meta/raft-store/src/state_machine/sm.rs
- metasrv/src/api/http/v1/cluster_state.rs
- metasrv/src/api/http/v1/mod.rs
- metasrv/src/api/http_service.rs
- metasrv/src/bin/metasrv.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/store/meta_raft_store.rs
- metasrv/tests/it/api/http/clsuter_state_test.rs
- metasrv/tests/it/api/http/cluster_state_test.rs
- metasrv/tests/it/api/http/mod.rs
- metasrv/tests/it/api/http_service.rs
add http api, return the nodes list in the metasrc cluster
- New Feature
related #2702
Unit Tests
> [feature]: return nodes list in metasrv server

- query/src/storages/fuse/io/block_stream_writer.rs
- query/src/storages/fuse/io/block_stream_writer_test.rs
- query/src/storages/fuse/io/mod.rs
- query/src/storages/fuse/operations/append.rs
- query/src/storages/fuse/table.rs
Currently AppendOperationLogEntry is returned as array, the PR is to replace with stream.
- Improvement
Fixes #issue
Unit Tests
> Replace AppendOperationLogEntry  vec[] with stream

- .github/workflows/databend-docker.yml
"Build Perf Tool" looks really slow, this PR is a try to improve it.
- Improvement
> ci: Add cargo cache to imporve perf tool build speed

- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/sled-store/src/lib.rs
- common/meta/sled-store/src/sled_tree.rs
- common/meta/sled-store/src/store.rs
- common/meta/sled-store/tests/it/sled_txn_tree.rs
- Use AsTxnKeySpace::update_and_fetch() to impl seq number.
- Impl `Store` for `AsTxnKeySpace`.
- Remove update_and_fetch from TransactionSledTree. It is not acutally
used.
- Improvement
> [common/meta] refactor: add a trait Store to define local store API

- common/datavalues/src/arrays/string/mod.rs
- common/datavalues/src/arrays/string/transform.rs
* add string transform unsafe safety comments
* add `DFStringArray::from_data_unchecked` method
- Improvement
Fixes #issue
Unit Tests
> add string transform unsafe safety comments

- common/exception/src/exception.rs
- common/exception/src/lib.rs
- common/meta/api/src/meta_api_test_suite.rs
- common/meta/sled-store/src/sled_tree.rs
- metasrv/src/errors.rs
- metasrv/src/executor/meta_handlers.rs
- metasrv/src/meta_service/message.rs
- metasrv/src/meta_service/meta_leader.rs
- metasrv/tests/it/flight/metasrv_flight_api.rs
- metasrv/tests/it/flight/metasrv_flight_meta_api_leader_follower.rs
- metasrv/tests/it/flight/mod.rs
- Forward read request to achieve read-after-write consistency.
- `RequestHandler<GetDatabaseReq>` forward `GetDatabase` request to its internal
`MetaNode` to deal with it.
`MetaNode` will forward it to a known leader if it is not a leader.
- Make `SerializedError` a real Error. Use it as a temp workaround to
wrap an `ErrorCode` with `MetaError`.
TODO: internally, metasrv should not use ErrorCode to exchange errors.
`metasrv` has to express more info than an error, e.g.
`ForwardToLeader`.
- Test: MetaApiTestSuite: add
`database_create_get_drop_leader_follower()` to test write on leader
then read on follower.
- Refactor: remove apis from TransactionSledTree.
- fix: #3339
- New Feature
> [metasrv]: feature: a follower forward GetDatabase request to leader.

- scripts/build/build-tool-runner.sh
Fix build-tool-runner.sh not updated after #3353 
> scripts: Fix build-tool-runner not updated

- common/exception/tests/it/exception.rs
- common/meta/api/src/meta_api_test_suite.rs
> [common/meta/api] refactor: fixup test about returned error from forwarded GetDatabase

- cli/src/cmds/queries/query.rs
- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/http/v1/statement.rs
- query/tests/it/servers/http/http_query_handlers.rs
- query/tests/it/servers/http/statement.rs
1. HTTP handler allows set user in  JSON.
2. better Bendcli error handling when calling HTTP streaming load API.
3. better test for HTTP handler so we can see the real reason when CI fails.
postpone to maybe next pr:
1. choose the way to pass the user for the streaming load.
2. check user privilege and client address
3. user auth
Unit Tests
> Allow set user for HTTP handler (without auth now).

- common/meta/api/src/meta_api_test_suite.rs
- metasrv/tests/it/api/http/cluster_state_test.rs
- metasrv/tests/it/api/http_service.rs
- metasrv/tests/it/flight/metasrv_flight_api.rs
- metasrv/tests/it/flight/metasrv_flight_meta_api_leader_follower.rs
- metasrv/tests/it/flight/metasrv_flight_tls.rs
- metasrv/tests/it/meta_service/meta_node.rs
- metasrv/tests/it/meta_service/meta_service_impl.rs
- metasrv/tests/it/store.rs
- metasrv/tests/it/tests/service.rs
> [metasrv] refactor: simplify metasrv cluster starting up in tests.

- common/management/src/cluster/cluster_mgr.rs
- common/management/src/stage/stage_mgr.rs
- common/management/src/user/user_mgr.rs
- common/meta/raft-store/src/state_machine/applied_state.rs
- common/meta/types/src/change.rs
- common/meta/types/src/lib.rs
- metasrv/src/executor/meta_handlers.rs
> [common/meta/types] refactor: a AddResult returned by meta op should include an ID to indicate what has been changed

- docker/build-tool/aarch64/Dockerfile
> build: Install arm64 version of libssl and zlib1g

- metasrv/src/executor/meta_handlers.rs
- metasrv/src/meta_service/message.rs
- metasrv/src/meta_service/meta_leader.rs
- metasrv/src/meta_service/meta_service_impl.rs
- metasrv/src/meta_service/mod.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/tests/it/metasrv/meta_node.rs
- make forward_to_leader a u64, to support deep forward.
- Improvement
> [metasrv] refactor: rename AdminRequest to ForwardRequest

- .github/workflows/databend-docker.yml
- .github/workflows/databend-release.yml
This PR is an extension of https://github.com/datafuselabs/databend/pull/3391, fix an extra place of cross.
> ci: Fix build in databend-docker

- metasrv/src/api/flight_server.rs
- metasrv/tests/it/flight/metasrv_flight_meta_api.rs
- metasrv/tests/it/flight/metasrv_flight_meta_api_follower_follower.rs
- metasrv/tests/it/flight/metasrv_flight_meta_api_leader_follower.rs
- metasrv/tests/it/flight/metasrv_flight_meta_api_restart_cluster.rs
- metasrv/tests/it/flight/mod.rs
- metasrv/tests/it/meta_node/meta_node_all.rs
> [metasrv] test: write and read works after restarting the cluster

- website/databend/README.md
- website/databend/docusaurus.config.js
- fix the github repo link
- add a tip for installing dependencies
Fixes #issue
Unit Tests
> [website] fix the github repo link

- metasrv/tests/it/flight/metasrv_flight_meta_api_restart_cluster.rs
> [metasrv] test: extend waiting time from 3sec to 5sec to let restart-cluster test survive timeout failure

- metasrv/tests/it/flight/metasrv_flight_meta_api_restart_cluster.rs
> [metasrv] test: extends restart-cluster wait time to 10 sec

- Cargo.lock
- common/base/Cargo.toml
- metasrv/Cargo.toml
- query/Cargo.toml
- query/src/api/http/v1/logs.rs
Bump poem from `1.0.38` to `1.1.1`
This change will reduce some memory usage, but it will also reduce the performance of `logs_handler` slightly.
It also fixes incorrect results when the stream returns `Err`.
- Bug Fix
- Improvement
Unit Tests
> [metasrv] make `logs_handler` return a bytes stream.

- metasrv/src/lib.rs
- metasrv/src/meta_service/mod.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/network.rs
- metasrv/tests/it/flight/metasrv_flight_kv_api_restart_cluster.rs
- metasrv/tests/it/flight/metasrv_flight_meta_api.rs
- metasrv/tests/it/flight/mod.rs
Election timeout is 8~12 sec.
A raft node waits for a interval of election timeout before starting election
TODO: the raft should set the wait time by election_timeout. For now, just use a large timeout.
> [metasrv] refactor: extend timeout to 30 sec for restart test

- README.md
Remove Windows support info in Readme cause we have no planned support for Windows.
- Other
> Remove Windows support info in Readme

- query/src/sessions/context.rs
some says a good log is actionable, when we find a log, we'd better take action on it.
this log seems a bit verbose as the screenshot shows, we can lower the log level to debug?  
- Improvement
Fixes #issue
Unit Tests
> lower the log level about DatabendQueryContext

- metasrv/tests/it/flight/metasrv_flight_kv_api_restart_cluster.rs
> [metasrv] extend restart-cluster test timeout to 30 sec

- metasrv/tests/it/meta_node/meta_node_all.rs
> [metasrv] test: wait 10 sec for log to replicate

- Cargo.lock
- Cargo.toml
- common/containers/Cargo.toml
- common/containers/src/lib.rs
- common/containers/src/pool.rs
- common/containers/tests/main.rs
- common/containers/tests/pool.rs
- common/meta/api/src/kv_api_test_suite.rs
- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/sled-store/src/sled_tree.rs
- metasrv/Cargo.toml
- metasrv/src/api/flight_server.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/network.rs
- metasrv/tests/it/api/http/cluster_state_test.rs
- metasrv/tests/it/api/http_service.rs
- metasrv/tests/it/flight/metasrv_flight_api.rs
- metasrv/tests/it/flight/metasrv_flight_kv_api.rs
- metasrv/tests/it/flight/metasrv_flight_kv_api_cross_node.rs
- metasrv/tests/it/flight/metasrv_flight_kv_api_restart_cluster.rs
- metasrv/tests/it/flight/metasrv_flight_meta_api.rs
- metasrv/tests/it/flight/metasrv_flight_meta_api_follower_follower.rs
- metasrv/tests/it/flight/metasrv_flight_meta_api_leader_follower.rs
- metasrv/tests/it/flight/metasrv_flight_tls.rs
- metasrv/tests/it/meta_node/meta_node_all.rs
- metasrv/tests/it/store.rs
- metasrv/tests/it/tests/service.rs
- common_containers::Pool caches Channel and indexes them by addresses.
- Raft Network use Pool to reduce number of connections
- Add tracing logs address the time spent by metasrv tests.
- Increase thread number for metasrv tests.
- New Feature
> [common/containers] feature: add conn pool

- common/management/src/user/user_api.rs
- common/management/src/user/user_mgr.rs
- common/management/tests/it/user.rs
- common/meta/types/src/lib.rs
- common/meta/types/src/user_auth.rs
- common/meta/types/src/user_info.rs
- common/meta/types/tests/it/user_info.rs
- common/planners/src/plan_user_alter.rs
- common/planners/src/plan_user_create.rs
- query/src/interpreters/interpreter_user_alter.rs
- query/src/interpreters/interpreter_user_create.rs
- query/src/sql/sql_parser.rs
- query/src/sql/statements/statement_alter_user.rs
- query/src/sql/statements/statement_create_user.rs
- query/src/storages/system/users_table.rs
- query/src/users/user.rs
- query/src/users/user_mgr.rs
- query/tests/it/interpreters/interpreter_grant_privilege.rs
- query/tests/it/interpreters/interpreter_revoke_previlege.rs
- query/tests/it/interpreters/interpreter_user_alter.rs
- query/tests/it/interpreters/interpreter_user_drop.rs
- query/tests/it/sessions/session_status.rs
- query/tests/it/sql/sql_parser.rs
- query/tests/it/storages/system/users_table.rs
- query/tests/it/tests/context.rs
- query/tests/it/users/user_mgr.rs
Rename auth_type to password_type
- Improvement
Fixes #3480 
Unit Tests
> Rename auth_type to password_type

- common/meta/raft-store/src/state_machine/sm.rs
For #3284  with `Deref` impl, we can use `self.txn_tree` directly in `impl Store for AsTxnKeySpace` [methods](https://github.com/datafuselabs/databend/blob/7705b175e00b728d967a48a29d3fb52d02fbfad3/common/meta/sled-store/src/sled_tree.rs#L518-L566)
For #3285 I investigated some methods that can provide default arg value, but they are all not beautiful enough, so we can leave it for now.
- Improvement
Unit Tests
> [metasrv] refine some codes

- query/src/storages/fuse/table_functions/fuse_history_truncate.rs
- Improvement
Fixes #issue
Unit Tests
> Fix: missing field `created_on` in initializer of `common_meta_types::TableMeta`

- Cargo.lock
- cli/Cargo.toml
- common/meta/raft-store/Cargo.toml
- common/meta/raft-store/src/config.rs
- docker/bootstrap.sh
- metasrv/Cargo.toml
- metasrv/src/bin/metasrv.rs
- metasrv/src/configs/config.rs
- query/Cargo.toml
- query/src/bin/databend-benchmark.rs
- query/src/configs/config.rs
- query/src/configs/config_log.rs
- query/src/configs/config_meta.rs
- query/src/configs/config_query.rs
- query/src/configs/config_storage.rs
- scripts/deploy/databend-query-cluster-3-nodes.sh
- scripts/deploy/databend-query-standalone.sh
Signed-off-by: koushiro <koushiro.cqx@gmail.com>
use clap 3 to unify the cli arguments parsing
- Improvement
Close #3504 
Unit Tests
> use clap 3.0.0-rc.5 to unify the cli arg parsing

- common/meta/types/src/cluster.rs
- common/meta/types/src/user_info.rs
- common/meta/types/src/user_quota.rs
- common/meta/types/src/user_stage.rs
- common/meta/types/tests/it/user_info.rs
Signed-off-by: koushiro <koushiro.cqx@gmail.com>
improve `#[serde(default)]` attr usage for some types
- Improvement
Unit Tests
> improve `#[serde(default)]` attr usage for some types

- metasrv/src/api/http/debug/pprof.rs
- query/src/api/http/debug/pprof.rs
- website/databend/docs/dev/building/profiling.md
- make pprof work again
- remove browser flamegraph in doc
- Bug Fix
Fixes #2941 
Unit Tests
> [pprof] make pprof work again

- common/datablocks/src/kernels/data_block_filter.rs
- common/datablocks/tests/it/kernels/data_block_filter.rs
- query/src/pipelines/transforms/transform_filter.rs
Before:
```
:) SELECT sum(  number  )  FROM numbers_mt(1000000000)  where true;
+--------------------+
| sum(number)        |
+--------------------+
| 499999999500000000 |
+--------------------+
1 row in set (0.18 sec)
Read 1000000000 rows, 8 GB in 0.171 sec., 5.84 billion rows/sec., 46.69 GB/sec.
```
After:
```
:) SELECT sum(  number  )  FROM numbers_mt(1000000000) where true  ;
+--------------------+
| sum(number)        |
+--------------------+
| 499999999500000000 |
+--------------------+
1 row in set (0.07 sec)
Read 1000000000 rows, 8 GB in 0.070 sec., 14.2 billion rows/sec., 113.57 GB/sec.
```
- Improvement
Fixes #issue
Unit Tests
> Improve constant filter

- query/src/servers/clickhouse/interactive_worker_base.rs
In some case(SELECT min(number) FROM numbers_mt(1000000000);), 
`let mut data_stream = async_data_stream.await?;` is time consuming and block the `do_query` function to return, so the return value `rx` can not be consumed by clickhouse srv crate.
In this patch, we move execute and read streaming data all to a single thread, ensures that the whole function not blocked.
This is a show in debug model(progress works :D):
- Bug Fix
Fixes #1216
Unit Tests
> ISSUE-1216: Fix ClickHouse progress hang in some queries

- query/src/sql/parser/ast/ast_visitor.rs
- query/src/sql/parser/ast/mod.rs
Implement Visitor for SQL AST.
Now, there is just `expression visitor`.
- New Feature
Fixes #1511
Unit Tests
> Implement Visitor for SQL AST

- .github/ISSUE_TEMPLATE/30_bug-report.md
> [ci] refactor: explain timeout failure in metasrv unittest

- .cargo/audit.toml
temporarily ignore lru < 0.7.1
to fix it, need
- https://github.com/blackbeam/rust-mysql-simple/pull/298/
- or mysql_async 0.29.0
Related #3584 
Unit Tests
> [audit] temporarily ignore lru < 0.7.1

- .gitignore
This PR changes `.gitignore` pattern from `abc/*` to `abc/`.
After this change, our editor will show ignored folders correctly.
- Other
> misc: Ignore folder instead to make editor works correctly

- .mergify.yml
It's noisy for a PR author to keep receiving comments like the following.
https://github.com/datafuselabs/databend/pull/3606
The PR is not ready for merge yet, we don't need to trouble them.
This PR adds a new condition that only pings the author while the PR has been approved by two reviewers.
> ci: Only ping author after PR has been approved

- website/databend/docusaurus.config.js
I found that analytics.js had problems collecting data, and I checked the official documents and needed to do a migration.
Refer to these materials for details:
[https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs](url)
[https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-analytics](url)
[https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag](url)
and docusaurus options items are modified, specific reference: [https://github.com/facebook/docusaurus/pull/5832 ](url)
- Bug Fix
- Improvement
> fix: migrate from analytics.js to gtag.js

- .github/actions/build_debug/action.yml
- .github/actions/build_release/action.yml
- .github/actions/check/action.yml
- .github/actions/test_stateful_standalone/action.yml
- .github/actions/test_stateless_cluster/action.yml
- .github/actions/test_stateless_standalone/action.yml
- .github/actions/test_unit/action.yml
try to add sharedkey and resetkey
- `sharedkey`  an additional key that is stable over multiple jobs.
- `resetkey` use `v*` to control the cache version. If we need to reset the cache version, increment the number after `v`.
Fixes #issue
Unit Tests
> [ci] try to add sharedkey and resetkey

- scripts/ci/ci-run-performance-tests-standalone.sh
- tests/perfs/compare.py
- tests/perfs/perfs.py
- Bug Fix
- Other 
#3689
Format some python code(delete unused code), and make code a bit pythonic
as use `store_true` instead of default "False"
> [ci] Fix: perf maybe failed when run locally, issue #3689

- scripts/ci/wait_tcp.py
- scripts/deploy/databend-query-cluster-3-nodes.sh
- scripts/deploy/databend-query-standalone-embedded-meta.sh
- scripts/deploy/databend-query-standalone.sh
- tests/perfs/compare.py
- Improvement
As discussed in #3689 port the `wait_tcp.py` to Python3. 
And use `context manager` to make sure the sock close.
> feat: wait_tcp.py to python3

- query/src/sql/sql_parser.rs
- query/tests/it/sql/sql_parser.rs
Support `as` case-insensitive when create udf
- Bug Fix
Fixes #3698
Unit Tests
> ISSUE-3698: Support `as` case-insensitive when create udf

- Cargo.lock
- common/datavalues/src/arrays/boolean/mutable.rs
- common/datavalues/src/arrays/mutable.rs
- common/datavalues/src/arrays/primitive/mutable.rs
- common/datavalues/src/arrays/string/mutable.rs
- common/functions/src/aggregates/aggregate_arg_min_max.rs
- common/functions/src/aggregates/aggregate_avg.rs
- common/functions/src/aggregates/aggregate_combinator_distinct.rs
- common/functions/src/aggregates/aggregate_count.rs
- common/functions/src/aggregates/aggregate_covariance.rs
- common/functions/src/aggregates/aggregate_min_max.rs
- common/functions/src/aggregates/aggregate_stddev_pop.rs
- common/functions/src/aggregates/aggregate_sum.rs
- common/functions/src/aggregates/aggregate_window_funnel.rs
- common/functions/tests/it/aggregates/aggregate_combinator.rs
- common/functions/tests/it/aggregates/aggregate_function.rs
* improve `MutableBooleanArrayBuilder`, `MutablePrimitiveArrayBuilder` and `MutableStringArrayBuilder`, to push value directly rather then call `try_push` to avoid branch prediction cost
* add nullable generic builder support. For example, if we determine that a certain column is with no nullable value, we can have a more efficient arraybuilder, just like below:
```rust
// with no nullable value
let builder = MutableStringArrayBuilder::<false>::default(); // false means no nullable, true means the value may be null
builder.push(val);
```
- Improvement
Fixes #3692 
Unit Tests
> Improve origin array builder & make nullable/no-nullable builder support

- Cargo.lock
- query/Cargo.toml
A cargo GitHub dependency URL with trailing slash can't be fetched via ssh protocol. If someone has a git URL replacement configuration(https://github.com -> git@github.com: ), cargo build will fail. 
Fixes #3705
> ISSUE-3705 Fix "datafuse-extras/clickhouse_driver/ Repository not found."

- query/src/bin/databend-query.rs
Signed-off-by: jyz0309 <45495947@qq.com>
Show Metric API server router in log
- Improvement
Fixes #3444 
Unit Tests
> ISSUE-3444: Show Metric API server router in log

- .mergify.yml
- PR with label `pr-bugfix` will be put into queue with high priority.
Workflow:
```
PR created
|
`-----> + Pass CI task `check`
+ Approved by 2 reviewers
|
| mergify enqueue this PR
|
`------> queue:
PR-a: pr-bugfix ----> Merge when all checks passed
PR-b: pr-bugfix
...
PR-x:
PR-y:
..
```
- New Feature
> [ci] feature: enqueue PR if it passes basic check and approved by 2; merge PRs one by one when all checks passed.

- common/codegen/src/bin/codegen.rs
- common/codegen/src/writes/arithmetics_type.rs
- common/codegen/src/writes/mod.rs
Rename common/codegen result_type.rs -> arithmetics_type.rs
- Improvement
Fixes #issue
Unit Tests
> Rename common/codegen result_type.rs -> arithmetics_type.rs

- common/meta/types/src/user_grant.rs
- common/meta/types/src/user_privilege.rs
- common/meta/types/tests/it/user_grant.rs
- query/src/interpreters/interpreter_common.rs
- query/src/interpreters/interpreter_grant_privilege.rs
- query/src/interpreters/interpreter_revoke_privilege.rs
this PR introduces a `GrantObject::contains` method to compare grant objects, with this helper function, we can replace some adhoc logics like `verify_database_privilege`, `verify_global_privilege`, `verify_table_privilege` into a unified logic: the verified object should be smaller than the object inside grant entry.
- Improvement
Fixes #issue
Unit Tests
> refactor: simplify the grant verify logic

- website/databend/docs/dev/development/tracing.md
using `TOKIO_CONSOLE_BIND` to assign different binds
Fixes #3758 
Unit Tests
> [docs] add a tip for console bind

- common/meta/raft-store/src/state_machine/sm.rs
In `StateMachine` struct `apply_cmd` function, all the commands are handled in this function, make this function too long to read. This pr split the function into sub cmd handler functions, make code more clearly.
- Improvement
> Refactor: split the apply_cmd function to sub functions, make code more clearly

- Cargo.lock
- query/Cargo.toml
- query/src/servers/mysql/mysql_interactive_worker.rs
- tests/databend-test
- tests/helpers/client.py
- tests/suites/0_stateless/00_0000_dummy_select_py.py
[MySQL Python connector](https://github.com/mysql/mysql-connector-python) will send some queries that databend not supported now,
so the driver will not connect the databend.
* some test not fmt, modify them.
tests/databend-test
tests/helpers/client.py
tests/suites/0_stateless/00_0000_dummy_select_py.py
- Bug Fix
Fixes #3828 
Unit Tests
> ISSUE-3828 MySQL Driver Compalibility

- common/meta/raft-store/src/state_machine/sm.rs
remove the unused `_config` and `_db` in `StateMachine` struct.
- Improvement
Fixes #issue
Unit Tests
> Refactor: remove unused field in StateMachine struct

- common/planners/src/lib.rs
- common/planners/src/plan_expression_function.rs
- common/planners/tests/it/plan_expression_monotonicity.rs
- query/src/storages/index/range_filter.rs
- query/tests/it/storages/index/range_filter.rs
- tests/databend-test
- tests/helpers/client.py
- tests/suites/0_stateless/00_0000_dummy_select_py.py
Both `left` and `right` contain different columns.
```
left = right => min_left <= max_right and max_left >= min_right
left > right => max_left > min_right
left >= right => max_left >= min_right
left < right => min_left < max_right
left <= right => min_left <= max_right
```
- Improvement
Fixes #3850 
Unit Tests
> ISSUE-3850: Range filter support more multi-column expression scenarios

- Cargo.lock
- common/streams/Cargo.toml
- query/Cargo.toml
- tools/benchmark/Cargo.toml
Reduction of about 30 dependencies that need to be built
- bump clickhouse_driver
- crates.io - csv-async
https://github.com/datafuse-extras/clickhouse_driver/pull/4
https://github.com/datafuse-extras/clickhouse_driver/pull/2
Unit Tests
> [deps] bump clickhouse_driver

- query/src/interpreters/interpreter_stage_create.rs
- query/src/interpreters/interpreter_udf_create.rs
- query/src/users/user_mgr.rs
- query/src/users/user_stage.rs
- query/src/users/user_udf.rs
- query/tests/it/interpreters/interpreter_stage_create.rs
- query/tests/it/users/user_stage.rs
- query/tests/it/users/user_udf.rs
* Move if_not_exists to user mgr api
* Rename `failure` to `e`
- Improvement
Fixes #3858
Unit Tests
> ISSUE-3858: Move if_not_exists to user mgr api

- .gitignore
- Makefile
- docker/build-tool/Dockerfile
- scripts/setup/run_docker.sh
- tests/databend-test
1. support to run databend build && test with zero dependencies(only need to setup docker with proper permission write permission on /tmp and source code directory)
2. disable std io buffer during stateless tests(would introduce flaky issues on docker based environment, and should be compatible with currently setups)
3. support to cache intermediate results built from cargo, and use /tmp directory to get avoid of conflictions between native and docker based cargo environment
How to use
build binary artifacts
```bash
./scripts/setup/run_docker.sh  make build
```
run test
```bash
./scripts/setup/run_docker.sh  make test
```
debug or get into dev container
```bash
./scripts/setup/run_docker.sh …
```
> [Build/CI] introduce databend Dev container

- .github/actions/test_unit/action.yml
- common/dal/Cargo.toml
- common/dal/src/accessors/aws_s3/s3_input_stream.rs
- common/dal/tests/it/accessors/aws_s3.rs
- common/dal/tests/it/accessors/mod.rs
- tests/suites/0_stateless/09_0008_fuse_optimize_table.sql
fixes issue #3829:
previously, io errors inside s3_inputstream are not propagated properly. the underlying errors should not be wrapped into another error of kind `ErrorKind::Other` blindly.
- Bug Fix
Fixes #3829
Unit Tests
> ISSUE-3829: optimize table cause of meta data damage

- common/meta/api/src/meta_api_test_suite.rs
- common/meta/embedded/tests/it/meta_api_impl.rs
- common/meta/raft-store/src/state_machine/database_lookup.rs
- common/meta/raft-store/src/state_machine/sm_meta_api_impl.rs
- common/meta/raft-store/tests/it/state_machine/database_lookup.rs
- common/meta/raft-store/tests/it/state_machine/meta_api_impl.rs
- common/meta/raft-store/tests/it/state_machine/mod.rs
- common/meta/sled-store/src/sled_tree.rs
- metasrv/tests/it/grpc/metasrv_grpc_meta_api.rs
Fix bug that `list_databases` return all tenants' databases.
- Bug Fix
Fixes #3875 
Unit Tests
> [metasrv]fix: list_databases return all tenants' databases

- common/management/src/user/user_mgr.rs
- removes async move block in user_mgr.rs
- removes unnecessary kv_api.clone()
- Improvement
Fixes #issue
Unit Tests
> Factor out unnecessary async move

- Cargo.lock
- common/meta/grpc/Cargo.toml
- common/meta/grpc/src/grpc_action.rs
- common/meta/grpc/src/grpc_client.rs
- common/meta/grpc/tests/it/grpc_client.rs
- metasrv/src/api/grpc/grpc_service.rs
- metasrv/tests/it/grpc/metasrv_grpc_api.rs
- metasrv/tests/it/grpc/metasrv_grpc_kv_api.rs
- metasrv/tests/it/grpc/metasrv_grpc_kv_api_restart_cluster.rs
- metasrv/tests/it/grpc/metasrv_grpc_meta_api.rs
- metasrv/tests/it/grpc/metasrv_grpc_tls.rs
- metasrv/tests/it/tests/service.rs
- tests/databend-test
- tests/helpers/client.py
- tests/suites/0_stateless/00_0000_dummy_select_py.py
Bugfix: fix connection failed when metasrv restart that caused by token expired.
This fix reuse raft nodes connect pool that @drmingdrmer made.
- Bug Fix
Fixes #issue
Unit Tests
> [metasrv] fix connection failed when metasrv restart that caused by token expired

- scripts/setup/dev_setup.sh
Use mysql-connector-python instead of deprecated mysql-connector
ref: https://pypi.org/project/mysql-connector/
Fixes #issue
Unit Tests
> Use mysql-connector-python instead of deprecated mysql-connector

- .github/workflows/developing.yml
- .github/workflows/production.yml
Our unittest used to wait for build, but it doesn't need to in fact.
Unit Tests
> ci: Unittest don't need to wait for build

- .github/actions/test_unit/action.yml
- Makefile
- common/meta/raft-store/tests/it/testing.rs
- common/meta/sled-store/tests/it/testing/mod.rs
- common/tracing/src/lib.rs
- common/tracing/src/logging.rs
- metasrv/tests/it/tests/service.rs
- tests/databend-test
- tests/helpers/client.py
- tests/suites/0_stateless/00_0000_dummy_select_py.py
- Also log span id for easy grep.
- Clean `_logs*` in Makefile and Upload `_logs*/ artifact.
- Improvement
> [common/tracing] test: add span logging for metasrv

- query/src/servers/http/v1/load.rs
- Bug Fix
Fixes #issue
Unit Tests
> Support escape \t \n for field_delimitor & record_delimitor

- common/meta/raft-store/src/state_machine/sm.rs
- metasrv/src/meta_service/meta_leader.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/tests/it/store.rs
- tests/databend-test
> [metasrv] refactor: remove unnecessary MetaNode.metrics_rx

- metasrv/tests/it/store.rs
- tests/databend-test
> [metasrv] refactor: clean up meta-store test

- common/meta/api/src/kv_api.rs
- common/meta/api/src/kv_api_test_suite.rs
- common/meta/api/src/lib.rs
- metasrv/tests/it/grpc/metasrv_grpc_kv_api.rs
- metasrv/tests/it/grpc/metasrv_grpc_kv_api_restart_cluster.rs
- metasrv/tests/it/main.rs
- metasrv/tests/it/meta_node/meta_node_all.rs
- metasrv/tests/it/tests/service.rs
> [metasrv] refactor: add KVApiTestSuite::test_single_node() to run all single-node tests

- common/meta/api/src/kv_api.rs
- common/meta/api/src/kv_api_test_suite.rs
- metasrv/tests/it/meta_node/meta_node_all.rs
- metasrv/tests/it/meta_node/meta_node_kv_api.rs
- metasrv/tests/it/meta_node/mod.rs
- metasrv/tests/it/tests/mod.rs
- metasrv/tests/it/tests/service.rs
- Feature: generalize KVApi implementation for `Arc<dyn KVApi>` with `Deref`.
- Test: run cross node KVApi test on every 2 adjacent nodes in a
cluster.
This covers all test patterns such as write-leader-read-follower or
write-learner-read-learner.
- Test: remove old case by case KVApi tests that are already covered by `KVApiTestSuite`.
- Improvement
> [metasrv] refactor: test KVApi for MetaNode

- common/meta/grpc/src/grpc_action.rs
- common/meta/grpc/src/grpc_client.rs
- common/meta/grpc/src/kv_api_impl.rs
- common/meta/grpc/src/meta_api_impl.rs
- common/meta/grpc/tests/it/grpc_server.rs
- common/meta/types/proto/meta.proto
- metasrv/src/api/grpc/grpc_service.rs
- metasrv/src/meta_service/meta_service_impl.rs
- metasrv/src/meta_service/mod.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/network.rs
- metasrv/tests/it/meta_node/meta_node_all.rs
- metasrv/tests/it/tests/service.rs
- Refactor: rename MetaService to RaftService. It serves for internal
raft communications.
- Refactor: use RaftRequest/RaftReply for `read_msg()`.
- Refactor: rename `MetaServiceServer::do_get()` to `do_read()`.
- Improvement
> [metasrv] refactor: termninology

- common/datavalues2/src/columns/array/mod.rs
- common/datavalues2/src/columns/boolean/mod.rs
- common/datavalues2/src/columns/column.rs
- common/datavalues2/src/columns/null/mod.rs
- common/datavalues2/src/columns/nullable/mod.rs
- common/datavalues2/src/columns/primitive/mod.rs
- common/datavalues2/src/columns/string/mod.rs
- common/datavalues2/src/columns/struct_/mod.rs
- common/datavalues2/src/data_value.rs
add `Debug` impl for `Column` for better debugging, just like below:
```
PrimitiveColumn          typeid: UInt8   len: 2  data: [1, 2]
PrimitiveColumn          typeid: Float32         len: 2  data: [1, 2]
NullColumn       typeid: Null    len: 3  data: [NULL...]
BooleanColumn    typeid: Boolean         len: 3  data: [true, false, true]
StringColumn     typeid: String  len: 2  data: [aaa, bbb]
NullableColumn   typeid: Int32   len: 3  data: [NULL, NULL, 12]
ArrayColumn      typeid: Array   len: 3  data: [[test], [data, bend], [hello, world, NULL]]
StructColumn     typeid: Struct  len: 3  data: [[18869, 1], [18948, 2], [1, 3]]
```
- Improvement
Fixes #issue
Unit Tests
> impl Debug trait for Column

- common/functions/src/scalars/expressions/binary.rs
- common/functions/tests/it/scalars/expressions.rs
Signed-off-by: Alex Chi <iskyzh@gmail.com>
I made the same mistake when building my own Array type system. <del>To brief, if we constraint the `ColumnRef` to have `'a` lifetime, we have to create an expression every time we want to do evaluation:</del>
```rust
for (a, b) in columns_left.iter().zip(columns_right.iter()) {
let func = ScalarBinaryFunction::new(some_sql_func);
func.eval(a, b);
}
```
... instead of
```rust
let func = ScalarBinaryFunction::new(some_sql_func);
// if we keep the 'a bound, the following a, b must have the same lifetime of
// `'a` at this point, but this is impossible -- they will be dropped in each
// loop. This snippet will CE with the `'a` bound applied to `ColumnRef`.
for …
```
> chore(datavalue2): fix too-strong bound on ScalarBinaryExpression

- query/src/servers/http/v1/http_query_handlers.rs
kill query is a write operation, maybe we can send the kill request by the POST verb?
- Improvement
Fixes #issue
Unit Tests
> [HTTP API] also allow POST method on kill query

- common/datavalues2/src/convert/column_convert.rs
- common/functions/src/scalars/conditionals/if.rs
- common/functions/src/scalars/expressions/cast_with_type.rs
- common/functions/tests/it/scalars/conditionals.rs
- tests/suites/0_stateless/02_0002_function_cast.result
- tests/suites/0_stateless/02_0002_function_cast.sql
Signed-off-by: Veeupup <code@tanweime.com>
* modify `if` behavoior, in detail:
before:
`select if(null, 1, 2)` -> `null`
now:
`select if(null, 1, 2)` -> `2`
when considering with if, null will be used as `false`.
* fix `old-datavalues` column convert into nullable `new-datavalues` column bug
* A Special case:when casting `NullColumn` into `BooleanColumn`, it will return a `BooleanColumn` with full `false`. It will not affect other behaviors.
- Bug Fix
- Improvement
Fixes #issue
Unit Tests
> fix if with null & fix convert to nullable column bug

- common/planners/src/plan_expression.rs
- query/src/optimizers/optimizer_constant_folding.rs
- query/src/optimizers/optimizer_expression_transform.rs
- query/tests/it/optimizers/optimizer_constant_folding.rs
- query/tests/it/optimizers/optimizer_expression_transform.rs
CC @Veeupup , it's another bug, I just move `constant_cond_remove` from `constant_folding` to `expression_transform`. The problem `null value will be optimized as false` described in the issue #4004  is still exists.
I think doing this in the filter maybe has no effect.
This is the same problem as issue #2165
- Bug Fix
Fixes #4012 
Unit Tests
> Fix Unable to get field name bug

- common/management/src/lib.rs
- common/management/src/role/mod.rs
- common/management/src/role/role_api.rs
- common/management/src/role/role_mgr.rs
- common/management/src/stage/mod.rs
- common/management/src/stage/stage_api.rs
- common/management/src/stage/stage_mgr.rs
- common/management/src/udf/mod.rs
- common/management/src/udf/udf_api.rs
- common/management/src/udf/udf_mgr.rs
- common/management/src/user/user_api.rs
- common/management/src/user/user_mgr.rs
- query/src/sessions/query_ctx_shared.rs
- query/src/sessions/session.rs
- query/src/sessions/session_ctx.rs
- query/src/sessions/session_info.rs
- query/src/sessions/session_mgr.rs
- query/src/users/user_api.rs
- query/tests/it/sessions/session_context.rs
1. Rename `*MgrApi` to `*Api` in management
2. Rename `context_shared` to `query_context_shared`
- Improvement
PATCH-2 of #3933 
Unit Tests
> SESSIONS-3933: Refine function name [PATCH-2]

- Cargo.lock
- common/ast/Cargo.toml
- common/ast/src/error.rs
- common/ast/src/lib.rs
- common/ast/src/parser/mod.rs
- common/ast/src/parser/token.rs
- common/ast/tests/it/token.rs
As attempting to implement #866, and after some deep discussion with @leiysky, we've decided to reimplement the sql parser with nom. But, while the idiom of nom parses directly on `&str`, we, like most of the other sql parsers, need a tokenizer to achieve better error messaging and better maintainability of the parser.  So this is the PR to add the tokenizer as the first step of implementing the new sql parser.
I've investigated the tokenizer of `sqlparser-rs` and have tried to implement one using the crate `regex`. As the result, the crate [`logos`](https://crates.io/crates/logos) achieved higher performance while paying the least effort.
The lexer rules in this PR follow this [official reference …
> Add tokenizer for the new sql parser

- query/src/sessions/settings.rs
- query/src/sql/statements/statement_show_settings.rs
- query/src/storages/system/settings_table.rs
- query/tests/it/storages/system/settings_table.rs
- tests/suites/0_stateless/06_show/06_0003_show_settings.result
Add default value and type to settings:
```
mysql> set max_threads=1;
Query OK, 0 rows affected (0.02 sec)
Read 0 rows, 0 B in 0.001 sec., 0 rows/sec., 0 B/sec.
mysql> show settings;
+------------------------------------+---------+---------+--------------------------------------------------------------------------------------------------------------------------------------------+--------+
| name                               | value   | default | description                                                                                                                                | type   |
+------------------------------------+---------+---------+-------------------------------------------------- …
```
> SESSIONS-3933: Add default value and type to settings

- Cargo.lock
- common/ast/Cargo.toml
- common/ast/src/lib.rs
- common/ast/src/parser/ast/ast_visitor.rs
- common/ast/src/parser/ast/expression.rs
- common/ast/src/parser/rule/expr.rs
- common/ast/src/parser/rule/mod.rs
- common/ast/src/parser/rule/statement.rs
- common/ast/src/parser/rule/util.rs
- common/ast/src/parser/token.rs
- common/ast/src/parser/transformer/transform_sqlparser.rs
- common/ast/tests/it/ast.rs
- common/ast/tests/it/rule.rs
- common/ast/tests/it/token.rs
- common/ast/tests/it/transformer.rs
Implement the parser for expressions. 
The core technique used here to help arrange the operator precedence and associativity is called Pratt parser, which is also known as the Top-Down Operator-Precedence (TDOP) parser. I recommend this [tdop-tutorial](https://eli.thegreenplace.net/2010/01/02/top-down-operator-precedence-parsing) if you're interested in how it works.
Ref #866
Unit Tests
> Implement the parser for expression

- common/functions/src/scalars/function2_factory.rs
- common/functions/src/scalars/function_factory.rs
- common/functions/src/scalars/uuids/uuid.rs
- common/functions/src/scalars/uuids/uuid_creator.rs
- common/functions/src/scalars/uuids/uuid_verifier.rs
- common/functions/tests/it/scalars/uuids/uuid_creator.rs
- common/functions/tests/it/scalars/uuids/uuid_verifier.rs
Migrate uuid functions to datavalues2
- Improvement
Fixes #3977
Unit Tests
> Migrate uuid functions to datavalues2

- common/meta/raft-store/src/config.rs
- metasrv/src/bin/metasrv.rs
- metasrv/src/configs/config.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/tests/it/configs.rs
- metasrv/tests/it/grpc/metasrv_grpc_api.rs
- scripts/ci/deploy/databend-query-cluster-3-nodes.sh
`metasrv` automatically ignores initializing arguments such as
`--single` and `--join`, if metasrv is already initialized.
Thus when restarting, metasrv can just use the same CLI args as
initializing it.
- Improvement
> [metasrv] refactor: remove CLI arg "--boot". Use "--single" instead.

- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/types/src/meta_errors.rs
- common/meta/types/src/meta_errors_into.rs
- metasrv/src/store/meta_raft_store.rs
move some storage related errors to MetaStorageError
- Improvement
[Fixes #issue 4000](https://github.com/datafuselabs/databend/issues/4000)
Unit Tests
> Refactor: move some storage related errors to MetaStorageError

- common/meta/api/src/meta_api_test_suite.rs
- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/raft-store/src/state_machine/sm_meta_api_impl.rs
- common/meta/sled-store/src/sled_tree.rs
- common/meta/types/src/applied_state.rs
- common/meta/types/src/meta_storage_errors.rs
- scripts/ci/deploy/databend-query-cluster-3-nodes.sh
- tests/databend-test
- tests/helpers/client.py
- tests/suites/0_stateless/00_dummy/00_0002_dummy_select_py.py
When a application-error occurs, such as `UnknownDatabase`, the error
should pop up and finally return to the caller, instead of aborting the
transcation applying this meta log.
- Change: remove MetaStorageError::TransactionError, it is not actually
used. Add TransactionConflict to indicate a retry-able txn error.
- SledTree: txn() should distinguishes txn-abort error and txn-conflict
error.
- StateMachine: when applying an log, if the error is `AppError`, fill
it into `AppliedState` and it is finally returned to the caller.
- Test: add test creating table on a absent db, to ensure an error code
is returned instead of a txn failure.
Thanks to @wubx :DDD
- Bug Fix
> [metasrv] fix: app-error should not fail state machine txn

- common/planners/src/lib.rs
- common/planners/src/plan_admin_use_tenant.rs
- common/planners/src/plan_describe_stage.rs
- common/planners/src/plan_node.rs
- common/planners/src/plan_rewriter.rs
- common/planners/src/plan_user_udf_alter.rs
- common/planners/src/plan_user_udf_create.rs
- common/planners/src/plan_user_udf_drop.rs
- common/planners/src/plan_visitor.rs
- query/src/interpreters/access/management_mode_access.rs
- query/src/interpreters/interpreter_factory.rs
- query/src/interpreters/interpreter_stage_describe.rs
- query/src/interpreters/interpreter_udf_alter.rs
- query/src/interpreters/interpreter_udf_create.rs
- query/src/interpreters/interpreter_udf_drop.rs
- query/src/interpreters/interpreter_use_tenant.rs
- query/src/sql/statements/statement_alter_udf.rs
- query/src/sql/statements/statement_create_udf.rs
- query/src/sql/statements/statement_describe_stage.rs
- query/src/sql/statements/statement_drop_udf.rs
- query/src/sql/statements/statement_use_tenant.rs
1. **Group the planner, let add new planner more clearly**
2. **Rename stage and udf, add `_user_` to function name**
3. **plan_use_tenant.rs => plan_admin_use_tenant.rs**
- Improvement
PATCH-1 of #4091 
Unit Tests
> PLANNER-4091: Refine the plan order and udf/stage planner name [PATCH-1]

- Cargo.lock
- common/meta/raft-store/src/state/raft_state_kv.rs
- common/meta/raft-store/src/state_machine/log_meta.rs
- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/raft-store/src/state_machine/state_machine_meta.rs
- common/meta/sled-store/src/sled_key_space.rs
- common/meta/sled-store/src/sled_tree.rs
- common/meta/sled-store/tests/it/testing/fake_state_machine_meta.rs
- common/meta/types/Cargo.toml
- common/meta/types/src/error_context.rs
- common/meta/types/src/lib.rs
- common/meta/types/src/meta_storage_errors.rs
- metasrv/Cargo.toml
- metasrv/src/store/meta_raft_store.rs
- MetaStorageError::SledError() use AnyError to express the causing error.
This way the error message includes more context information and it
get rid of some manually error convertion job, by utilizing `From`.
- Feature: add trait `WithContext` to create a wrapper error that
includes additional context info. See: `WithContext::context()`
- Add MetaStorageError::SnapshotError, as a wrapper all snapshot errors.
Snapshot error is a **storage** level error and it does not have to be
a sub error of the top-level error `MetaError`.
- Remove MetaStorageError::TransactionAbort, because all abortion is
caused by MetaStorageError::AppError.
- Improvement
> [meta] refactor: cleanup MetaStorageError

- Cargo.lock
- common/grpc/Cargo.toml
- common/grpc/src/dns_resolver.rs
- common/grpc/src/lib.rs
- common/meta/grpc/src/grpc_client.rs
- common/meta/types/src/meta_errors.rs
- common/meta/types/src/meta_errors_into.rs
- common/meta/types/src/meta_network_errors.rs
- metasrv/src/api/grpc_server.rs
- metasrv/src/meta_service/raftmeta.rs
- query/src/catalogs/backends/meta_backend.rs
- query/src/common/meta/meta_client.rs
- query/tests/it/api/rpc_service.rs
- Remove conversion from ErrorCode to MetaError, which is a potential bug maker:
It can not find out missing matching branch at compile time.
- Remove MetaNetworkError::CannotConnectNode, it should be a sub error of ConnectionError
- Remove MetaError:TLSConfigurationFailure, it should be a sub error of MetaNetworkError
- Return Infallible if a method does not return any error
- fix: #4151
> [grpc] ConnectionFactory: returns structured error so that a depending mod does not need to deal with every error defined in ErrorCode

- tests/suites/1_stateful/01_load/01_0000_streaming_load.sh
- tests/suites/1_stateful/01_load/ontime.sha1sum.txt
add sha256 check for the data file download from the webserver to make sure the 01_0000_streaming_load.sh
not failed for file broken!
- Improvement
01_0000_streaming_load.sh
Fixes #4105
Unit Tests
> Enhancement: Add sha256sum check for ontime.csv

- common/functions/src/scalars/dates/date.rs
- common/functions/src/scalars/dates/interval_function.rs
- common/functions/src/scalars/dates/macros.rs
- common/functions/src/scalars/expressions/ctx.rs
- common/functions/src/scalars/function_factory.rs
- common/functions/src/scalars/hashes/hash.rs
- common/functions/src/scalars/maths/math.rs
- common/functions/src/scalars/strings/string.rs
- common/functions/src/scalars/udfs/udf.rs
- common/functions/src/scalars/uuids/uuid.rs
Remove the `BTreeMap`, use `precision` directly.
- Improvement
Fixes #issue
> Add precision in EvalContext

- common/streams/src/stream_limit_by.rs
- query/src/storages/fuse/io/block_reader.rs
- query/src/storages/fuse/operations/read.rs
do not need buffer since  "we execute exactly 1 seek and 1 read on them."
https://github.com/jorgecarleitao/arrow2/blob/3d528c99589e96f0539de4c07b11843fa22f23ac/examples/parquet_read_async.rs#L31
a buffer with column chunk length is allocated each time.
https://github.com/jorgecarleitao/arrow2/blob/3d528c99589e96f0539de4c07b11843fa22f23ac/src/io/parquet/read/row_group.rs#L126
thanks to @dantengsky 
https://github.com/datafuselabs/databend/pull/4212#discussion_r812863275
Unit Tests
> remove buffer in block_reader of fuse store

- common/meta/raft-store/src/log/raft_log.rs
- common/meta/raft-store/src/state/raft_state.rs
- metasrv/src/api/grpc/grpc_service.rs
- metasrv/src/meta_service/meta_service_impl.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/network.rs
- metasrv/src/store/meta_raft_store.rs
> [metasrv] refactor: lower down log level to debug for tracing::instrument to prevent potential "message too long" error when sending to jaeger

- query/src/interpreters/interpreter.rs
- query/src/interpreters/interpreter_select.rs
Add execute2 for Interpreter(useful for insert into select)
Fixes #issue
Unit Tests
> Add execute2 for Interpreter

- docs/dev/deploy/metasrv-deploy.md
- docs/dev/deploy/metasrv-export-import.md
> [metasrv] add doc for deploying metasrv cluster and backup/restore metasrv data

- query/src/storages/fuse/io/block_reader.rs
- query/src/storages/fuse/io/mod.rs
- query/src/storages/fuse/io/parallel_async_reader.rs
fix https://github.com/datafuselabs/databend/issues/4253#issuecomment-1055002355
use tokio::sync::Semaphore to limit the number of parallel readers create from the reader factory.
Fixes [#issue](https://github.com/datafuselabs/databend/issues/4253#issuecomment-1055002355)
Unit Tests
> limit parallelization when reading parquet columns.

- Cargo.lock
- common/contexts/Cargo.toml
- common/contexts/src/dal/dal_context.rs
- common/streams/Cargo.toml
- common/streams/tests/it/sources/source_parquet.rs
- query/Cargo.toml
- query/src/storages/fuse/io/block_reader.rs
- query/src/storages/fuse/io/meta_readers.rs
This PR will bump to opendal v0.1.3 which introduces new readers API: `ObserveReader`.
With this help, we can calculate the read cost time correctly.
Read more about opendal v0.1.3: https://github.com/datafuselabs/opendal/discussions/94
- Bug Fix
Fixes https://github.com/datafuselabs/databend/issues/4256
Unit Tests
> dal_context: Use ObserveReader to calculate metrics

- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/http/v1/query/http_query.rs
- query/tests/it/servers/http/http_query_handlers.rs
request blocked because the interpreter is called in handler task. move it to the spawned task.
it works for select which get a stream immediately and the caller wait on it. 
but errors show up for queries like COPY,  which return a useless stream after real work is done.  cc @ZhiHanZ 
Fix https://github.com/datafuselabs/databend/issues/4297
Unit Tests
long copy tested on my mac
> fix httphandler async query.

- metasrv/src/api/http/v1/cluster_state.rs
- metasrv/tests/it/api/http/cluster_state_test.rs
Return current leader when fetch cluster state
- Improvement
Fixes #4310 
Unit Tests
> [MetaSrv] Return current leader when fetch cluster state

- Cargo.lock
- query/Cargo.toml
- query/src/servers/mysql/mysql_interactive_worker.rs
- Bug Fix
Fixes #4179
Unit Tests
> fix hangs on authenticate

- common/management/src/cluster/cluster_api.rs
- common/management/src/cluster/cluster_mgr.rs
- common/management/tests/it/cluster.rs
- query/src/clusters/cluster.rs
fix cannot find node id after heartbeat failure
- Bug Fix
Fixes #4331
Unit Tests
> ISSUE-4331 fix cannot find node id after heartbeat failure

- query/src/servers/http/v1/http_query_handlers.rs
- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/http/v1/query/http_query.rs
1. return wall_time_ms only after execute finished, before that it is None/nil
2. use float instead of int
3. include parse and analyze time
Fixes #issue
Unit Tests
> polish wall_time_ms in http handler

- common/datablocks/src/kernels/data_block_group_by.rs
- common/datablocks/src/kernels/data_block_group_by_hash.rs
- common/datavalues/src/columns/group_hash.rs
- common/datavalues/src/types/deserializations/boolean.rs
- common/datavalues/src/types/deserializations/date.rs
- common/datavalues/src/types/deserializations/date_time.rs
- common/datavalues/src/types/deserializations/mod.rs
- common/datavalues/src/types/deserializations/null.rs
- common/datavalues/src/types/deserializations/nullable.rs
- common/datavalues/src/types/deserializations/number.rs
- common/datavalues/src/types/deserializations/string.rs
- query/src/pipelines/transforms/group_by/aggregator_groups_builder.rs
- query/src/pipelines/transforms/transform_group_by_final.rs
- tests/suites/0_stateless/03_dml/03_0003_select_group_by.result
- tests/suites/0_stateless/03_dml/03_0003_select_group_by.sql
- Improvement
Continue: #4158
Fixes #4079 
Unit Tests
> Support nullable group by

- Cargo.lock
- common/datablocks/Cargo.toml
- common/functions/Cargo.toml
- metasrv/Cargo.toml
- query/Cargo.toml
bump regex to 1.5.5.
see https://github.com/datafuselabs/databend/issues/4368
Fixes https://github.com/datafuselabs/databend/issues/4368
Unit Tests
> bump regex to 1.5.5.

- cli/src/cmds/queries/query.rs
- docs/user/03-api/http-handler.md
- query/src/servers/http/v1/http_query_handlers.rs
- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/http/v1/query/http_query.rs
- query/tests/it/servers/http/http_query_handlers.rs
1.  rename progress to scan_progress.  context also provide result_progress, but I guess client does not need it now.
3.  return elapsed time when running,  useful for client to calculate speed from progress
4.  rename wall_time_ms to running_time_ms. 
5.  polish description about running_time_ms in doc
@Chasen-Zhang @flaneur2020 
no issue
Unit Tests
> [http handler] rename response fields and return elapsed time when running.

- Cargo.lock
- common/metrics/Cargo.toml
- common/metrics/src/recorder.rs
- metasrv/Cargo.toml
- show default metrics recorder bind addr
- call `init_default_metrics_recorder` after set_panic_hook
- Improvement
- Other 
Fixes #4341 
Unit Tests
Some thoughts:
- Should we change `init_default_metrics_recorder` to return an error?
- Make `PrometheusBuilder` use listen addr from config?
> ISSUE-4341: Fix show init default recorder error

- cli/src/cmds/clusters/create.rs
- cli/src/cmds/status.rs
- cli/tests/it/clusters/view.rs
- cli/tests/it/query.rs
- cli/tests/it/status.rs
- docker/databend-query-docker.toml
- docs/user/01-sql-statement/08-system-tables/system-configs.md
- query/src/bin/databend-query.rs
- query/src/configs/config_query.rs
- query/tests/it/configs.rs
- query/tests/it/storages/system/configs_table.rs
- scripts/ci/deploy/config/databend-query-embedded-meta.toml
- scripts/ci/deploy/config/databend-query-management-mode.toml
- scripts/ci/deploy/config/databend-query-node-1.toml
- scripts/ci/deploy/config/databend-query-node-2.toml
- scripts/ci/deploy/config/databend-query-node-3.toml
- tests/databend-test
- tests/helpers/client.py
- tests/suites/0_stateless/00_dummy/00_0002_dummy_select_py.py
**Rename query.http_api_address-> admin_api_address**
Note:
keep the `flight_api_address` name
- Improvement
Fixes #4384
Fixes #4388
Unit Tests
> Rename query.http_api_address-> admin_api_address

- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/raft-store/src/state_machine/testing.rs
- common/meta/raft-store/tests/it/state_machine/mod.rs
- metasrv/src/store/meta_raft_store.rs
Because sled does not provide snapshot read.
> [metasrv] building snapshot has to protected by a write-lock.

- docs/doc/01-deploy/00_local.md
- docs/doc/01-deploy/01_s3.md
- docs/doc/01-deploy/02_minio.md
- docs/doc/01-deploy/03_cos.md
I think logging both stdout and stderr to file is the intention.
from lint:
SC2069: To redirect stdout+stderr, 2>&1 must be last (or use '{ cmd > file; } 2>&1' to clarify).
Fixes #issue
Unit Tests
> Redirect stderr to file too

- common/meta/api/src/meta_api_test_suite.rs
- common/meta/types/src/meta_storage_errors.rs
- query/tests/it/sql/plan_parser.rs
- query/tests/it/sql/statements/statement_copy.rs
Improve Unknown database error message
Before this pr:
mysql> create table test.test;
ERROR 1105 (HY000): Code: 1003, displayText = test.
After this pr:
mysql> create table test.test(id int);
ERROR 1105 (HY000): Code: 1003, displayText = Unknown database 'test'.
- Improvement
Fixes #4249 
start up services by running up.sh
<details>
<summary>Click to expand up.sh!</summary>
```sh
cat - > "/tmp/db-meta.toml" <<EOF
log_dir = "metadata/_logs"
admin_api_address = "127.0.0.1:8101"
grpc_api_address = "127.0.0.1:9101"
[raft_config]
id = 1
single = true
raft_dir = "metadata/datas"
EOF
cat - > "/tmp/db-query.toml" <<EOF
[log]
log_level = "INFO"
log_dir = "benddata/_logs"
[query]
admin_api_address = …
```
> Improve Unknown database error message

- docs/doc/01-deploy/00_local.md
- docs/doc/01-deploy/01_s3.md
- docs/doc/01-deploy/02_minio.md
- docs/doc/01-deploy/03_cos.md
Deploy: Upgrade from -v0.6.95 to -v0.6.96
Fixes #issue
Unit Tests
> Doc: Upgrade from -v0.6.95 to -v0.6.96

- common/datablocks/src/data_block.rs
- query/src/servers/clickhouse/writers/query_writer.rs
to_clickhouse_block always convert to full column if constant
- Bug Fix
Fixes #issue
Unit Tests
> fix(clickhouse): to_clickhouse_block always convert to full column if constant

- common/datavalues/src/columns/boolean/mod.rs
- common/datavalues/tests/it/columns/boolean.rs
- New Feature
Fixes #4374 
Unit Tests
> ISSUE-4374: Simd selected for BooleanColumn

- Cargo.lock
- common/base/Cargo.toml
- common/base/src/profiling.rs
Fix https://github.com/datafuselabs/databend/issues/830
pprof-rs doesn't support building on musl for a long time, I have a workaround for it https://github.com/tikv/pprof-rs/pull/110
Now, databend works on `musl`:
```rust
PKG_CONFIG_ALLOW_CROSS=1 cargo build --target x86_64-unknown-linux-musl
```
Please give this PR a test to make sure it also work on `macOS` too :heart: 
Unit Tests
> build: Fix musl support

- query/src/interpreters/interpreter_factory_interceptor.rs
- query/src/servers/http/v1/http_query_handlers.rs
- query/src/servers/http/v1/mod.rs
- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/http/v1/query/expirable.rs
- query/src/servers/http/v1/query/expiring_map.rs
- query/src/servers/http/v1/query/http_query.rs
- query/src/servers/http/v1/query/http_query_manager.rs
- query/src/servers/http/v1/query/mod.rs
- query/src/servers/http/v1/statement.rs
- query/src/sessions/mod.rs
- query/src/sessions/session.rs
- query/src/sessions/session_mgr.rs
- query/src/sessions/session_mgr_status.rs
- query/src/sessions/session_status.rs
- query/tests/it/servers/http/http_query_handlers.rs
support server-side-session for HTTP handler
it is useful for `use` or `set` commands.
to use it
1. for the first query, specify `session.max_idle_time` in secs
2. for the following query, use `session_id` from response to specify `session.id` .  Some Notes:
1. when `id` field is used, other fields in `session` is invaid.
2. currently not support queueing in server side, make sure last query response status is Succeeded or Failed before post, otherwise thHTTPtp request will fail with error message `last query on the session not finished`
Notes:
1.  exist code not affected
1.  timeout for sessions is also needed for clickhouse/MySQL, 
but they can be implemented more directly(maybe part of …
> support server-side-session for HTTP handler

- common/building/src/lib.rs
- query/src/bin/databend-query.rs
- query/src/configs/config.rs
- query/src/sessions/query_ctx.rs
Add git latest tag to the build version.
Old:
```
mysql> select version();
+----------------------------------------------------------------------------------------+
| version()                                                                              |
+----------------------------------------------------------------------------------------+
| DatabendQuery v-0.1.0-213b1f7-simd(1.61.0-nightly-2022-03-19T01:39:28.774417429+00:00) |
+----------------------------------------------------------------------------------------+
```
Now:
```
+-------------------------------------------------------------------------------------------------------+
| version() …
```
> chore(build): Add git latest tag to the build version

- scripts/kubernetes/meta-standalone.yaml
- scripts/kubernetes/query-cluster.yaml
use default ports for Kubernetes deploy example
Fixes #issue
Unit Tests
> docs: use default ports for kubernetes deploy example

- .github/actions/check/action.yml
- Cargo.lock
- rust-toolchain.toml
fix up the old toolchain compiler error
Fixes #issue
Unit Tests
> build(crossbeam): fix up the old toolchain compiler error

- Cargo.lock
- query/Cargo.toml
- query/src/servers/mysql/mysql_interactive_worker.rs
- query/src/sessions/session_ctx.rs
- query/tests/it/sessions/session.rs
https://github.com/datafuselabs/opensrv/pull/11
```
[N] ❯ mysql -h 127.0.0.1 -P3306 -u root test
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 8.0.26-v0.6.91-nightly-93522be-simd(rust-1.61.0-nightly-2022-03-26T12:14:56.337604171+00:00) 0
Copyright (c) 2000, 2022, Oracle and/or its affiliates.
Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
mysql> show …
```
> update opensrv for fix issue 4430

- docs/doc/06-contributing/04-rfcs/20210815-data-shuffle.md
- docs/doc/06-contributing/04-rfcs/20210913-join-framework-design.md
- docs/doc/06-contributing/04-rfcs/20210914-new-sql-planner-framework.md
- docs/doc/06-contributing/04-rfcs/20211202-plan-expression.md
- docs/doc/06-contributing/04-rfcs/20211203-performance-test.md
- docs/doc/06-contributing/04-rfcs/20211230-new-sql-planner-framework.md
- docs/doc/06-contributing/04-rfcs/20220117-new-datavalues-system.md
- docs/doc/06-contributing/04-rfcs/20220304-semi-structured-data-types.md
- docs/doc/06-contributing/04-rfcs/query/_category_.yml
move from query to the root of 04-rfcs
Fixes #issue
Unit Tests
> doc(rfc): move from query to the root of 04-rfcs

- common/datavalues/src/types/serializations/boolean.rs
- common/datavalues/src/types/serializations/mod.rs
- common/datavalues/src/types/serializations/number.rs
- common/datavalues/src/types/serializations/string.rs
- common/datavalues/src/types/serializations/variant.rs
- common/functions/src/scalars/expressions/cast_with_type.rs
- common/functions/src/scalars/semi_structureds/parse_json.rs
- common/functions/tests/it/scalars/expressions.rs
- common/functions/tests/it/scalars/semi_structureds.rs
- tests/suites/0_stateless/02_function/02_0048_function_semi_structureds_parse_json.result
- tests/suites/0_stateless/02_function/02_0048_function_semi_structureds_parse_json.sql
fix `parse_json` data type match error
```sql
mysql> select parse_json(todate32('2022-01-01'));
+------------------------------------+
| parse_json(todate32('2022-01-01')) |
+------------------------------------+
| 18993                              |
+------------------------------------+
```
- Bug Fix
[#4476](https://github.com/datafuselabs/databend/issues/4476)
Unit Tests
> fix(function): fix parse_json data type match

- docs/doc/06-contributing/02-good-pr.md
- website/docusaurus.config.js
- website/versioned_docs/version-0.7.0/03-reference/01-data-types/data-type-semi-structured-types.md
- website/versioned_docs/version-0.7.0/03-reference/02-functions/03-datetime-functions/tohour.md
- website/versioned_docs/version-0.7.0/03-reference/02-functions/03-datetime-functions/tomonday.md
- website/versioned_docs/version-0.7.0/03-reference/02-functions/03-datetime-functions/tosecond.md
- website/versioned_docs/version-0.7.0/03-reference/02-functions/03-datetime-functions/tostartofisoyear.md
- website/versioned_docs/version-0.7.0/03-reference/02-functions/03-datetime-functions/tostartofyear.md
- website/versioned_docs/version-0.7.0/06-contributing/01-building-from-source.md
- website/versioned_docs/version-0.7.0/06-contributing/02-good-pr.md
- website/versioned_docs/version-0.7.0/10-faq/06-how-to-write-scalar-functions.md
- website/versioned_docs/version-0.7.0/10-faq/07-how-to-write-aggregate-functions.md
```
yarn run docusaurus docs:version 0.7.0
modified:   ../docs/doc/06-contributing/02-good-pr.md
modified:   docusaurus.config.js
modified:   versioned_docs/version-0.7.0/03-reference/01-data-types/data-type-semi-structured-types.md
modified:   versioned_docs/version-0.7.0/03-reference/02-functions/03-datetime-functions/tohour.md
modified:   versioned_docs/version-0.7.0/03-reference/02-functions/03-datetime-functions/tomonday.md
modified:   versioned_docs/version-0.7.0/03-reference/02-functions/03-datetime-functions/tosecond.md
modified:   versioned_docs/version-0.7.0/03-reference/02-functions/03-datetime-functions/tostartofisoyear.md
modified: …
```
> doc(version): re-tagging v0.7.0

- query/src/pipelines/new/executor/executor_notify.rs
- query/src/pipelines/new/executor/executor_tasks.rs
Finished processor executor when no new task
- Improvement
part #3379
Unit Tests
> fix(processor): finish processor executor when no new task

- .github/actions/build_release/action.yml
- .github/actions/publish_image/action.yml
- .github/workflows/production.yml
* build production ci with build tool docker image
* remove deprecated management mode test
Fixes #issue
Unit Tests
> ci: production build with docker

- query/src/storages/null/null_table.rs
I am not sure what `NullSource` means exactly yet, but:
line 160~162 is unreachable code, compare read2 with read, this seems need to return one datablock
https://github.com/datafuselabs/databend/blob/f39cd40cec5ca15f624e9b0e364fe3aa8aa6a176/query/src/storages/null/null_table.rs#L156-L162
- Improvement
Fixes #issue
Unit Tests
> NullSource should return one data block?

- query/src/sessions/session_mgr.rs
During reload command, cluster would reload all configurations from config file and overlap settings from environment variable which is not desired, since environment variable are expected to be immutable
- Bug Fix
Fixes #issue
Unit Tests
> [Cloud] keep environment variable immutable during reload

- .github/actions/build_debug/action.yml
- .github/actions/build_release/action.yml
- .github/actions/setup_build_tool/action.yml
- .github/actions/test_unit/action.yml
- .github/workflows/databend-release.yml
- .github/workflows/platform.yml
- docker/build-tool/alpine/Dockerfile
- docker/build-tool/debian/Dockerfile
- docs/doc/10-faq/02-routine-maintenance.md
- scripts/setup/run_build_tool.sh
- scripts/setup/rust-toolchain.toml
Building the base build image with pull request is not safe, we need an extra step for toolchain upgrade.
for #4689
Unit Tests
> fix(ci): use specific toolchain tagged image

- common/datavalues/src/columns/take.rs
- docs/doc/21-load-data/00-local.md
- tests/suites/0_stateless/01_system/01_0000_system_numbers.result
- tests/suites/0_stateless/01_system/01_0000_system_numbers.sql
- Bug Fix
- Improvement
Fixes #4676
Unit Tests
> query(values): support take for null column && update streaming load docs 

- query/src/databases/information_schema/information_schema_database.rs
- query/src/storages/information_schema/mod.rs
- query/src/storages/information_schema/schemata_table.rs
- query/tests/it/storages/system/tables_table.rs
Support sys view information_schema.schemata
- Improvement
Fixes #4710
> add sys view information_schema.schemata

- common/range-set/src/range_key.rs
- common/range-set/src/range_set.rs
- common/range-set/tests/it/range_set_test.rs
remove Copy trait for RangeSet, since String dose not impl Copy
- Improvement
Fixes #issue
> Fix: remove Copy trait for RangeSet, since String dose not impl Copy

- .github/mergify.yml
We don't need to check the response of build: as our tests depends them.
Fix the following states:
Fixes #issue
> ci(mergify): Remove not needed check for build

- docs/doc/60-contributing/02-benchmarking.md
- 100,000,000,000 -> 10,000,000,000: Considering the time spent by perf, we use ten billion for testing
- ontime -> default.ontime: the default database prefix has been added to perf sql
ref https://github.com/datafuselabs/databend-perf/tree/main/benchmarks
Fixes #issue
> docs(benchmarking): fix sql

- docs/doc/21-load-data/00-local.md
Simplify the command format.
simplify the command uploading files
> docs(official site): simplify command uploading file

- docs/doc/30-reference/30-sql/10-dml/dml-copy.md
In the previous doc(deploy), the Query HTTP Handler listen on port `8081` (in the databend-query.toml). 
So, it's necessary to keep unified here.
> docs: unify query http handler port

- common/functions/src/scalars/expressions/cast_from_variant.rs
- common/functions/tests/it/scalars/expressions.rs
try_cast from variant return Null instead of Err
- Bug Fix
Fixes #4777
> fix(function): try_cast from varaint return Null instead of Err

- query/src/servers/mysql/mysql_interactive_worker.rs
passwordCharacterEncoding is  utf8mb4  by default https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-connection.html#cj-conn-prop_passwordCharacterEncoding
code refer to
https://github.com/mysql/mysql-server/blob/3290a66c89eb1625a7058e0ef732432b6952b435/mysys/crypt_genhash_impl.cc#L421
current opensrv impl make sure salt followed by "\0"
- Bug Fix
Fixes https://github.com/datafuselabs/databend/issues/4802
> fix(mysql_handler): salt characters should be ascii.

- query/src/api/http/v1/config.rs
- query/src/api/http_service.rs
- query/src/sessions/session.rs
- query/src/sessions/session_mgr.rs
- query/tests/it/api/http/config.rs
Fix `v1/config` not updated after reload config
- Bug Fix
Fixes https://github.com/datafuselabs/databend/issues/4819
> fix `v1/config` not updated after reload config

- query/src/storages/fuse/operations/read_partitions.rs
- query/src/storages/fuse/pruning/block_pruner.rs
- tests/suites/0_stateless/02_function/02_0045_conditional_function_in.sql
- tests/suites/0_stateless/02_function/02_0050_function_string_regexp_instr.sql
- tests/suites/0_stateless/03_dml/03_0004_select_order_by.result
- tests/suites/0_stateless/03_dml/03_0004_select_order_by.sql
- tests/suites/0_stateless/03_dml/03_0004_select_order_by_cluster.result
> query(fuse): limit push down respect orders

- query/src/storages/information_schema/tables_table.rs
add a column TABLE_COMMENT for information_schema.TABLES
- Improvement
Fixes #4829
> add a column TABLE_COMMENT for information_schema.TABLES

- scripts/setup/dev_setup.sh
add a new python dep `clickhouse_driver`
Fixes #4886
> chore(ci): add clickhouse_driver to dev_setup

- common/planners/src/plan_expression_common.rs
- tests/suites/0_stateless/02_function/02_0048_function_semi_structureds_parse_json.sql
fix panic caused by wrong arg numbers.
- Bug Fix
Fixes #4776
Fixes #4885
> fix(function): validate function args before get type

- docs/doc/20-develop/00-golang.md
since do not support prepared statements
set interpolateParams in golang development doc.
or user needs to avoid using placeholders and may take care to escape the value itself.
Fixes #issue
> Set interpolateParams in golang dev doc

- common/meta/types/src/cmd.rs
- common/meta/types/src/compatibility/cmd_00000000_20220413.rs
- common/meta/types/src/compatibility/mod.rs
- common/meta/types/src/lib.rs
- common/meta/types/tests/it/compatible.rs
- common/meta/types/tests/it/main.rs
Let metasvr be able to load the log-entry format before commit
34e89c99e4e35632718e9227f6549b3090eb0fb9,
in which the `Cmd` format changed.
To solve th compatible issue, an intermedia type is introduced, which is
a super set of the old and new type.
When loading a record, first load it into the superset type, then reduce
to the latest type.
- fix: #4890
- New Feature
> feature: metasrv has to be compatible with 20220413-34e89c99e4e35632718e9227f6549b3090eb0fb9

- common/management/tests/it/user.rs
- common/meta/types/src/role_info.rs
- common/meta/types/src/user_info.rs
- common/meta/types/tests/it/user_info.rs
- query/src/interpreters/interpreter_role_create.rs
- query/src/procedures/admins/bootstrap_tenant.rs
- query/src/users/auth/auth_mgr.rs
- query/src/users/auth/jwt/authenticator.rs
- query/src/users/auth/jwt/jwk.rs
- query/src/users/auth/mod.rs
- query/src/users/mod.rs
- query/src/users/user_mgr.rs
- query/tests/it/interpreters/interpreter_privilege_grant.rs
- query/tests/it/interpreters/interpreter_privilege_revoke.rs
- query/tests/it/interpreters/interpreter_role_grant.rs
- query/tests/it/interpreters/interpreter_role_revoke.rs
- query/tests/it/interpreters/interpreter_show_grant.rs
- query/tests/it/interpreters/interpreter_user_alter.rs
- query/tests/it/interpreters/interpreter_user_drop.rs
- query/tests/it/servers/http/http_query_handlers.rs
- query/tests/it/sessions/session_context.rs
- query/tests/it/storages/system/roles_table.rs
- query/tests/it/tests/context.rs
- query/tests/it/users/auth/auth_mgr.rs
- query/tests/it/users/auth/mod.rs
- query/tests/it/users/mod.rs
- query/tests/it/users/role_cache_mgr.rs
- query/tests/it/users/role_mgr.rs
Create user if not exists on JWT authenticate.
Specify the `create_user` struct in custom claims to create a user.
```rs
#[derive(Default, Deserialize, Serialize)]
pub struct CreateUser {
pub tenant_id: Option<String>,
pub roles: Vec<String>,
}
#[derive(Default, Deserialize, Serialize)]
pub struct CustomClaims {
pub create_user: Option<CreateUser>,
}
```
- New Feature
Fixes https://github.com/datafuselabs/databend/issues/4875
> feat: create user if not exists on JWT authenticate

- query/src/users/auth/auth_mgr.rs
- query/src/users/auth/jwt/authenticator.rs
- query/src/users/auth/jwt/mod.rs
- query/tests/it/servers/http/http_query_handlers.rs
- query/tests/it/users/auth/auth_mgr.rs
https://github.com/datafuselabs/databend/issues/4935
Rename CreateUser to EnsureUser. 
- Improvement
Fixes https://github.com/datafuselabs/databend/issues/4935
> rename CreateUser to EnsureUser

- .github/workflows/databend-release.yml
fix default image tag for debian
Fixes #issue
> ci: fix default image tag for debian

- common/ast/src/parser/ast/expression.rs
- common/ast/src/parser/ast/statement.rs
- common/ast/src/parser/rule/expr.rs
- common/ast/tests/it/rule.rs
- common/ast/tests/it/testdata/query.txt
- common/ast/tests/it/testdata/statement.txt
1. Trim spaces in `Explain` query
2. Add option precision in DataTime DataType
- Improvement
Fixes #4968
> feat(datatype): introduce precision in DateTime type

- query/src/interpreters/interpreter_table_show_create.rs
- query/src/sql/table_option_keys.rs
- query/tests/it/interpreters/interpreter_table_show_create.rs
- tests/suites/0_stateless/06_show/06_0001_show_create_table.result
* Add  snapshot_location back to show create table
* Trim the last `,`
```
"+-------+-------------------------------------+",
"| Table | Create Table                        |",
"+-------+-------------------------------------+",
"| t     | CREATE TABLE `t` (                  |",
"|       |   `a` INT,                          |",
"|       | ) ENGINE=fuse COMMENT='test create' |",
"+-------+-------------------------------------+",
->
"+-------+-------------------------------------+",
"| Table | Create Table                        |",
"+-------+-------------------------------------+",
"| t     | CREATE TABLE `t` (                  |",
"|       |   `a` INT                           |",
"|       | ) …
```
> chore(show): add snapshot_location back to show create table

- common/datavalues/benches/data_type.rs
- query/src/interpreters/interpreter_select_v2.rs
- query/src/interpreters/mod.rs
- query/src/servers/mysql/mysql_interactive_worker.rs
- query/src/sessions/session_settings.rs
- query/src/sql/exec/data_schema_builder.rs
- query/src/sql/exec/mod.rs
- query/src/sql/optimizer/heuristic/mod.rs
- query/src/sql/optimizer/optimize_context.rs
- query/src/sql/optimizer/s_expr.rs
- query/src/sql/planner/binder/bind_context.rs
- query/src/sql/planner/binder/project.rs
- query/src/sql/planner/binder/scalar.rs
- query/src/sql/planner/binder/select.rs
- query/src/sql/planner/mod.rs
- query/tests/it/storages/system/settings_table.rs
- tests/suites/0_stateless/06_show/06_0003_show_settings.result
Introduce a setting `enable_planner_v2` to enable new planner.
- New Feature
#3747
> feat(planner): Add switch to enable new planner

- tests/metactl/test-metactl.sh
- tools/metactl/src/main.rs
And minor refinements.
- Bug Fix
> [metactl] fix: by default do not export from a running meta node.

- query/src/servers/clickhouse/interactive_worker_base.rs
- query/src/servers/mysql/mysql_interactive_worker.rs
Currently `cluster select with new processor` is not ready, so add a determination of whether the cluster is empty to solid the code
- others
Fixes #issue
> minor(planner): add `context.get_cluster().is_empty()` condition to solid the code

- query/src/catalogs/impls/immutable_catalog.rs
- query/src/databases/system/system_database.rs
- query/src/storages/system/query_log_table.rs
- query/tests/it/storages/system/query_log_table.rs
use config item "--max-query-log-size" as the max_row setting of QueryLogTable.
the value specified for `max-query-log-size`, e.g.
`./target/debug/databend-query --max-query-log-size=100`
will be used as the value of filed `max_rows` of `QueryLogTable`
- Improvement
Fixes #5033
> ISSUE-5033: Use config item "--max-query-log-size" as the max_row setting of QueryLogTable

- common/ast/src/parser/statement.rs
- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/statement.txt
- make the semicolon on the statements optional
- Bug Fix
- Improvement
closes https://github.com/datafuselabs/databend/issues/5044
> fix(parser): allow to omit semicolon

- query/src/storages/fuse/operations/commit.rs
Cleanup the uncommitted files generated during OCC:
- snapshot files
- segment and block files if tx aborted
- Improvement
> chore(storage): Cleanup the uncommitted files generated during OCC

- query/src/servers/http/v1/http_query_handlers.rs
- query/src/servers/http/v1/query/execute_state.rs
although most errors can be found in query_log. log it anyway for：
1. some errors may not be covered in query_log 
2. more convenient to read for debug
3. log itself may be used for analysis
note：
1.  errors that lead to HTTP error code already logged in middleware
part of https://github.com/datafuselabs/databend/issues/4876
> feat(httphandler):  remove backtrace from response and log it.

- common/functions/src/rdoc/function_doc_asset.rs
Fix doc parser. 
- Bug Fix
When I fix #4615, PR: #4843, 
I find that the regular expression can't match titles with spaces such as "not like", "not regexp". 
And  the regular expression also can't match multiple titles. For example, in docs/doc/30-reference/20-functions/30-datetime-functions/addinterval.md, there is a line like "title_includes: addYears, addMonths, addDays, addHours, addMinutes, addSeconds", the regular expression can't match the space between "addYears," and "addMonths", so the parse result is not right. 
Fixes #4615
> fix doc parser

- query/src/interpreters/interpreter_use_database.rs
- query/src/servers/clickhouse/interactive_worker_base.rs
- tests/suites/0_stateless/07_use/07_0000_use_database.result
- tests/suites/0_stateless/07_use/07_0000_use_database.sql
fix clickhouse interactive_worker hang and does not send response to client.
1. set `cancel_clone` to `Relaxed` when `interpreter.execute` return a error;
2. make `process_select_query` return `Err` when things go wrong rather than always return `Ok(rx)`
- Bug Fix
Fixes #5005
> fix: clickhouse worker hang when interpreter fail to execute

- common/datavalues/src/columns/series.rs
- common/functions/tests/it/aggregates/aggregate_function.rs
Add a debug_assert to check unsafe operation, which would expose the problem in #5106 
#5106
> tiny improve: add a debug_assert to check unsafe operation

- query/src/sql/exec/data_schema_builder.rs
- query/src/sql/exec/expression_builder.rs
- query/src/sql/planner/binder/aggregate.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/binder/scalar.rs
- query/src/sql/planner/binder/scalar_visitor.rs
- query/src/sql/planner/binder/select.rs
- query/src/sql/planner/metadata.rs
- query/src/sql/planner/plans/scalar.rs
Support the following syntax
- `select sum(a) from t;`
- `select count(a) from t;`
- `select count() from t`;
- `select count(1) from t`;
-  `select count(*) from t`;
- `select count() from t group by a`;
- `select count(1) from t group by a`;
- New Feature
Fixes #issue
> feat(planner): support more aggregate syntax

- common/ast/src/ast/query.rs
- common/ast/src/parser/query.rs
- query/src/sql/exec/mod.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/binder/scalar.rs
- query/src/sql/planner/binder/select.rs
- query/src/sql/planner/plans/scalar.rs
Support `TableFunction`s in new planner, e.g. `numbers`.
- New Feature
Fixes #5134
> feat(planner): Support `TableFunction` in new planner

- common/meta/api/src/meta_api_test_suite.rs
- common/meta/grpc/src/meta_client_on_kv_impl.rs
- metasrv/tests/it/grpc/metasrv_grpc_meta_api_on_kv.rs
impl get_table_by_id with kv-txn
- New Feature
Fixes [Issue #5158](https://github.com/datafuselabs/databend/issues/5158)
> Feature: impl get_table_by_id with kv-txn

- common/meta/api/src/meta_api.rs
- common/meta/api/src/meta_api_test_suite.rs
- common/meta/embedded/src/meta_api_impl.rs
- common/meta/embedded/tests/it/meta_api_impl.rs
- common/meta/grpc/src/grpc_action.rs
- common/meta/grpc/src/meta_api_impl.rs
- common/meta/grpc/src/meta_client_on_kv_impl.rs
- common/meta/raft-store/src/state_machine/sm_meta_api_impl.rs
- common/meta/raft-store/tests/it/state_machine/meta_api_impl.rs
- common/meta/types/src/database.rs
- common/meta/types/src/lib.rs
- common/meta/types/src/message.rs
- common/meta/types/src/operation.rs
- common/meta/types/src/table.rs
- common/proto-conv/src/from_to_protobuf_impl.rs
- common/proto-conv/tests/it/proto_conv.rs
- metasrv/src/executor/action_handler.rs
- metasrv/src/executor/meta_handlers.rs
- metasrv/src/meta_service/meta_leader.rs
- metasrv/tests/it/grpc/metasrv_grpc_meta_api.rs
- query/src/catalogs/backends/meta_backend.rs
- query/src/catalogs/impls/mutable_catalog.rs
- query/src/storages/fuse/operations/commit.rs
- query/tests/it/storages/fuse/table.rs
> [metasrv] disable `share` APIs

- query/src/interpreters/access/management_mode_access.rs
- query/src/interpreters/access/mod.rs
- query/src/interpreters/interpreter_factory_interceptor.rs
- query/src/interpreters/mod.rs
- query/tests/it/interpreters/access/management_mode_access.rs
- query/tests/it/interpreters/access/mod.rs
- query/tests/it/interpreters/mod.rs
https://github.com/datafuselabs/databend/issues/5209
- New Feature
Fixes https://github.com/datafuselabs/databend/issues/5209
> add access check for management mode

- common/macros/src/lib.rs
Address warning about:
```shell
warning: function is never used: `token_stream_with_error`
--> common/macros/src/async_entrypoint.rs:19:4
|
19 | fn token_stream_with_error(mut tokens: TokenStream, error: syn::Error) -> TokenStream {
|    ^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: function is never used: `async_main`
--> common/macros/src/async_entrypoint.rs:24:8
|
24 | pub fn async_main(_args: TokenStream, item: TokenStream) -> TokenStream {
|        ^^^^^^^^^^
warning: function is never used: `async_test`
--> common/macros/src/async_entrypoint.rs:37:8
|
37 | pub fn async_test(_args: TokenStream, item: TokenStream) -> …
```
> chore: Make cargo clippy --all-targets happy

- query/src/sql/exec/data_schema_builder.rs
Remove conditional judgments
- Improvement
Fixes #issue
> chore(planner): make code neat with `DataField::new()`

- website/docusaurus.config.js
The new upgrade from Algolia enforce us to use databend-rs as prefix instead of name.
So we will migrate to `databend-rs-docs`.
> docs: Algolia enforce using databend-rs as prefix

- query/src/formats/format.rs
- query/src/formats/format_csv.rs
- query/src/formats/format_factory.rs
- query/src/formats/format_parquet.rs
- query/src/formats/mod.rs
- query/src/servers/http/v1/load.rs
- query/src/servers/http/v1/multipart_format.rs
- query/tests/it/formats/format_csv.rs
feat(format): support parquet input format
- New Feature
Fixes #issue
> feat(format): support parquet input format

- query/src/sql/exec/expression_builder.rs
- query/src/sql/exec/mod.rs
- query/src/sql/planner/binder/scalar_visitor.rs
- query/src/sql/planner/binder/sort.rs
- query/src/sql/planner/plans/mod.rs
- query/src/sql/planner/plans/scalar.rs
- query/src/sql/planner/plans/sort.rs
`OrderBy` doesn't do any evaluation, so it shouldn't be in `Scalar`.
Move all `OrderBy` related information to `SortPlan`.
- Improvement
Fixes #issue
> refine(planner): remove `OrderExpr` from Scalar

- docs/doc/30-reference/10-data-types/50-data-type-array-types.md
- docs/doc/30-reference/10-data-types/index.md
add `Array(T)` docs
We can provide two types of arrays.
- `Array(T)` is used to store data with the pre-defined inner data type, similar to [ClickHouse's `Array(T)`](https://clickhouse.com/docs/en/sql-reference/data-types/array). 
- The semi-structured `Array` is used to store JSON-type data.
Fixes #issue
> feat(doc): add Array(T) docs

- query/src/sql/exec/expression_builder.rs
- query/src/sql/planner/binder/aggregate.rs
- query/src/sql/planner/binder/bind_context.rs
- query/src/sql/planner/binder/join.rs
- query/src/sql/planner/binder/project.rs
- query/src/sql/planner/binder/scalar.rs
- query/src/sql/planner/binder/scalar_visitor.rs
- query/src/sql/planner/binder/select.rs
- query/src/sql/planner/binder/sort.rs
- query/src/sql/planner/plans/scalar.rs
- query/src/sql/planner/semantic/type_check.rs
Support planning subqueries. The execution part will be done in other PRs.
- New Feature
Part of #5210
> feature(planner): Support subqueries in new planner

- common/ast/src/ast/expr.rs
- common/ast/src/ast/mod.rs
- common/ast/src/ast/query.rs
- common/ast/src/ast/statement.rs
- common/ast/src/parser/error.rs
- common/ast/src/parser/expr.rs
- common/ast/src/parser/mod.rs
- common/ast/src/parser/query.rs
- common/ast/src/parser/statement.rs
- common/ast/src/parser/token.rs
- common/ast/src/parser/util.rs
- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/expr.txt
- common/ast/tests/it/testdata/query.txt
- common/ast/tests/it/testdata/statement.txt
- query/src/sql/planner/binder/aggregate.rs
- query/src/sql/planner/binder/bind_context.rs
- query/src/sql/planner/binder/join.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/binder/project.rs
- query/src/sql/planner/binder/scalar.rs
- query/src/sql/planner/binder/select.rs
- query/src/sql/planner/binder/sort.rs
- query/src/sql/planner/semantic/type_check.rs
- tests/suites/0_stateless/20+_others/20_0002_planner_v2_display_error.result
- tests/suites/0_stateless/20+_others/20_0002_planner_v2_display_error.sql
```diff
// V1
- ERROR 1105 (HY000) at line 4: Code: 1058, displayText = Unknown column aa.
- ERROR 1105 (HY000) at line 5: Code: 1015, displayText = SELECT * with no tables specified is not valid (while in analyze select projection).
// V2
+ ERROR 1105 (HY000) at line 4: Code: 1065, displayText = error: 
+   --> SQL:1:8
+   |
+ 1 | select aa from t
+   |        ^^ column doesn't exist
+ 
+ .
+ ERROR 1105 (HY000) at line 5: Code: 1065, displayText = error: 
+   --> SQL:1:1
+   |
+ 1 | select *
+   | ^^^^^^^^ SELECT * with no tables specified is not valid
+ 
+ .
```
- New Feature
> feat(planner): display error with source span

- .github/workflows/developing.yml
- .github/workflows/production.yml
- query/src/sessions/query_ctx.rs
- query/src/sessions/session_mgr.rs
- query/src/sql/statements/query/query_normalizer.rs
- query/src/users/user_api.rs
Reverts datafuselabs/databend#5294
> Revert "chore(query): introduce meta Runtime"

- common/ast/src/ast/expr.rs
- common/ast/src/ast/query.rs
- common/ast/src/ast/statement.rs
- common/ast/src/parser/error.rs
- common/ast/src/parser/expr.rs
- common/ast/src/parser/query.rs
- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/expr.txt
- common/ast/tests/it/testdata/query.txt
- common/ast/tests/it/testdata/statement.txt
- query/src/sql/planner/metadata.rs
- query/src/sql/planner/semantic/type_check.rs
- add source span information to the expr ast, which can be used to display type error in the type checker.
- New Feature
> feat(parser): add span for expression

- query/src/common/hashtable/hash_table_entity.rs
A trivial typo in query/src/common/hashtable/hash_table_entity.rs. There is no reference to this function so it has not caused problems before.
- Not for changelog
> fix: hashtable

- Cargo.lock
- common/contexts/Cargo.toml
- common/io/Cargo.toml
- common/streams/Cargo.toml
- query/Cargo.toml
fix(storage/azblob): Azblob API uri not constructed correctly
References: https://github.com/datafuselabs/opendal/discussions/273
- Bug Fix
> fix(storage/azblob): Azblob API uri not constructed correctly

- query/src/sql/exec/expression_builder.rs
- query/src/sql/planner/binder/limit.rs
- query/src/sql/planner/binder/select.rs
- query/src/sql/planner/plans/scalar.rs
- query/src/sql/planner/semantic/type_check.rs
- tests/suites/0_stateless/02_function/02_0012_function_datetimes_tz.sql
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
- Support `TRY_CAST`
- Support `EXTRACT`
- Support `INTERVAL` literal
- Fix unary operators
- New Feature
> feature(planner): Support some scalar expressions in new planner

- query/src/sql/planner/semantic/type_check.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
> feature(planner): Support context function in new planner

- Cargo.lock
- common/ast/Cargo.toml
- common/ast/src/ast/expr.rs
- common/ast/src/parser/expr.rs
- common/ast/tests/it/testdata/expr.txt
- common/datavalues/src/types/type_interval.rs
- common/proto-conv/src/data_from_to_protobuf_impl.rs
- common/protos/proto/datatype.proto
- query/src/sql/planner/semantic/type_check.rs
- remove `DateTimeField` and use datavalues::IntervalType instead
- Improvement
> chore(parser): use datavalues::IntervalType instead of DateTimeField

- metasrv/src/meta_service/meta_service_impl.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/metrics/meta_metrics.rs
- metasrv/src/metrics/mod.rs
- metasrv/src/store/meta_raft_store.rs
add more metrics in metasrv:`is_leader`, `leader_changes`,`applying_snapshot`,`proposals_applied`,`proposals_pending`,`proposals_failed`,`read_failed`.
- New Feature
part of [metrics API providing requests/sec, active watchers, outstanding(uncommitted) raft logs, number of raft logs, state machine size etc. · Issue #4938 · datafuselabs/databend](https://github.com/datafuselabs/databend/issues/4938)
> Feature: add more metrics in metasrv

- common/datavalues/src/columns/array/mutable.rs
- common/functions/src/aggregates/aggregate_retention.rs
- tests/suites/0_stateless/02_function/02_0000_function_aggregate_retention.sql
Now the get method of Array<T> is supported.
We can change the return type of retention function from Variant to Array<T>.
- New Feature
Fixes #5226
> feat(function): change retention return type from Variant to Array<T>

- metasrv/src/api/http/v1/metrics.rs
- metasrv/src/api/http/v1/mod.rs
- metasrv/src/api/http_service.rs
- metasrv/tests/it/api/http/metrics.rs
- metasrv/tests/it/api/http/mod.rs
Signed-off-by: RinChanNOWWW <hzy427@gmail.com>
Add new http api "/metrics" which returns the raft metrics.
Like:
```json
{
"running_state": {
"Ok": null
},
"id": 1,
"state": "Leader",
"current_term": 1,
"last_log_index": 2,
"last_applied": {
"term": 1,
"index": 2
},
"current_leader": 1,
"membership_config": {
"log_id": {
"term": 0,
"index": 0
},
"membership": {
"configs": [
[
1
]
],
"all_nodes": [
1
]
}
},
"snapshot": null,
"leader_metrics": {
"replication": {}
}
}
```
- New Feature
Fixes https://github.com/datafuselabs/databend/issues/4311
> feat(metasrv): add metrics to http service

- .github/mergify.yml
This PR fix mergify can't merge PR.
> ci: MacOS's stateless standalone has been disabled

- Cargo.lock
- query/src/pipelines/new/processors/transforms/aggregator/aggregator_single_key.rs
- query/src/sql/exec/mod.rs
1. `Limit` in the new planner had been introduced in https://github.com/datafuselabs/databend/pull/5301, so the ticket will solve the todo about `rows_limit`.
2. [directly use `layout` and `offsets_aggregate_states` in params](https://github.com/datafuselabs/databend/pull/5403/commits/e9836f4b58d9081f2111ea43b713ce418d445d11)
- Improvement
Fixes #issue
> improvement: add `rows_limit` for sort

- query/tests/it/servers/http/http_query_handlers.rs
fix https://github.com/datafuselabs/databend/pull/5409#issuecomment-1128379748
@Xuanwo 
the first HTTP request return as long as a page of 2 rows is generated, maybe before the SQL finish running and  `succeed` state is set, depending on the task scheduling,  although `select * from numbers(10)`  should run very fast.
> fix(test): fix httphandler flaky test.

- query/src/interpreters/interpreter_insert.rs
fixes(insert): fix drop dispatcher when commit insert query
- Bug Fix
Fixes #issue
> fixes(insert): fix drop dispatcher when commit insert query

- Cargo.lock
- common/arrow/Cargo.toml
- tests/suites/0_stateless/03_dml/03_0023_insert_into_array.result
- tests/suites/0_stateless/03_dml/03_0023_insert_into_array.sql
as [#984](https://github.com/jorgecarleitao/arrow2/pull/984) has merged, we can update arrow2 to fix array nullable write
- Bug Fix
Fixes #5427
> fix(data type): update arrow2 to fix array nullable write

- query/src/sql/planner/binder/join.rs
[Nice suggestion from @sundy-li ](https://github.com/datafuselabs/databend/pull/5423#discussion_r874779528)
- Improvement
Fixes #issue
> chore: replace `for {if...}` with `iterator  find`

- query/tests/it/servers/http/http_query_handlers.rs
See discussion: https://github.com/datafuselabs/databend/discussions/5415
- Bug Fix
> fix(query): Fix test_query_log when RUST_BACKTRACE is not set

- common/base/src/containers/pool.rs
- common/meta/grpc/src/grpc_client.rs
> [meta/client] workaround: temporarily disable conn pool until cross-runtime hanging is fixed

- tests/logictest/config.py
- tests/logictest/main.py
Allow to only run http handler logic test or mysql logic test, make http handler host configurable
Fixes #issue
> chore: add feature flagging for logic tst

- docs/doc/30-reference/30-sql/60-kill/kill-query.md
- query/src/interpreters/interpreter_kill.rs
- query/src/servers/mysql/mysql_interactive_worker.rs
- query/src/sessions/query_ctx.rs
- query/src/sessions/session.rs
- query/src/sessions/session_info.rs
- query/src/sessions/session_mgr.rs
- query/src/sql/parsers/parser_kill.rs
- query/src/storages/system/processes_table.rs
- query/tests/it/servers/mysql/mysql_handler.rs
- query/tests/it/sessions/session.rs
- query/tests/it/sessions/session_setting.rs
- scripts/ci/ci-run-stateful-tests-standalone-s3.sh
- tests/suites/1_stateful/02_query/02_0000_kill_query.py
MySQL Client support according to "Ctrl C" interrupt a long query.
Link to discussion: https://github.com/datafuselabs/databend/discussions/5405
- New Feature
Fixes #4871
> MySQL Handler Kill Query

- query/src/procedures/admins/bootstrap_tenant.rs
- query/tests/it/interpreters/interpreter_call.rs
- tests/logictest/main.py
Use hardcoded user with password is not the best practice and depreciated, we should only use `call admin$bootrap_tenant(tenantName)` to create necessary roles
- Improvement
Fixes #issue
> chore: remove unneccesary user creation during tenant boot call

- query/src/servers/http/v1/http_query_handlers.rs
- query/src/servers/http/v1/query/block_buffer.rs
- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/http/v1/query/page_manager.rs
- query/tests/it/servers/http/http_query_handlers.rs
1.  carry `bool done` aside block when `pop()` 
2.  notify when `stop_push()`
3.  not return data and next_url when error.
- Bug Fix
Fixes https://github.com/datafuselabs/databend/issues/5456
> fix(httphandler): req should return as soon as results is exhausted.

- query/src/sql/exec/mod.rs
- query/src/sql/optimizer/cascades/mod.rs
- query/src/sql/optimizer/heuristic/mod.rs
- query/src/sql/optimizer/m_expr.rs
- query/src/sql/optimizer/memo.rs
- query/src/sql/optimizer/pattern_extractor.rs
- query/src/sql/optimizer/rule/rule_implement_get.rs
- query/src/sql/optimizer/rule/rule_implement_hash_join.rs
- query/src/sql/optimizer/s_expr.rs
- query/src/sql/planner/binder/subquery.rs
- query/src/sql/planner/format/display_rel_operator.rs
- query/src/sql/planner/format/indent_format.rs
- query/src/sql/planner/format/mod.rs
- query/src/sql/planner/mod.rs
- query/tests/it/sql/mod.rs
- query/tests/it/sql/planner/format/mod.rs
- query/tests/it/sql/planner/mod.rs
Introduce a common formatting mechanism for tree stucture, so we can exploit it to imlement `EXPLAIN` and so on.
A indent format is implemented, here's an example:
```
PhysicalHashJoin: build keys: [plus(col1, 123)], probe keys: [col2]
Filter: [true]
PhysicalScan: catalog.database.table
PhysicalScan: catalog.database.table
```
- New Feature
Close #5491
> feature(planner): Common tree structure formatter for plan display

- scripts/kubernetes/minio-sample.yaml
Signed-off-by: hantmac <hantmac@outlook.com>
Add `StorageClass` and `PV` yaml for deploying databend in k8s cluster.
Fix `PVC` definition.
- Bug Fix
Fixes [ #issue](https://github.com/datafuselabs/databend/issues/5524)
> fix(scripts): deploy minio in k8s failed

- common/functions/src/scalars/semi_structureds/as_type.rs
- common/functions/src/scalars/semi_structureds/mod.rs
- common/functions/src/scalars/semi_structureds/semi_structured.rs
- common/functions/tests/it/scalars/semi_structureds/as_type.rs
- docs/doc/30-reference/20-functions/110-semi-structured-functions/as_type.md
- docs/doc/30-reference/20-functions/110-semi-structured-functions/get.md
- tests/suites/0_stateless/02_function/02_0056_function_semi_structureds_as.result
- tests/suites/0_stateless/02_function/02_0056_function_semi_structureds_as.sql
Support `as` function to cast the variant value to target data type.
Refer to snowflake's [as function](https://docs.snowflake.com/en/sql-reference/functions/as.html)  
include the following functions:
```sql
AS_BOOLEAN( <variant> )
AS_INTEGER( <variant> )
AS_FLOAT( <variant> )
AS_STRING( <variant> )
AS_ARRAY( <variant> )
AS_OBJECT( <variant> )
```
- New Feature
part of #5428
> feat(function): Support variant as function

- common/functions/src/scalars/contexts/context.rs
- common/functions/src/scalars/contexts/mod.rs
- common/functions/src/scalars/contexts/user.rs
- common/planners/src/plan_expression.rs
- query/src/common/context_function.rs
- query/src/sql/planner/semantic/type_check.rs
- query/tests/it/functions/context_function.rs
in MySQL only has function user()
We has already impl current_user so we can use this function.
```
select user();
+----------------+
| user()         |
+----------------+
| root@localhost |
+----------------+
```
- New Feature
Fixes #5023
> add func user()

- query/tests/it/servers/http/http_query_handlers.rs
Fixes https://github.com/datafuselabs/databend/runs/6598468390?check_suite_focus=true#step:3:3601
the error is fail to find `_res/7c612330-a880-4433-8172-8f018bc24e89/_t/meta_v1.json` when download
should make sure to write it first before response.
but this change will  make other tests flaky on ci.  ingore for now to seek better ways to test them
Fixes https://github.com/datafuselabs/databend/runs/6598468390?check_suite_focus=true#step:3:3601
> test(httphanlder): ignore flaky test.

- query/src/sessions/query_ctx_shared.rs
- query/src/sessions/session.rs
- query/src/sessions/session_mgr.rs
`RoleCacheMgr` should be a global object. Moving role_cache_manager to session manager.
- Bug Fix
Fixes https://github.com/datafuselabs/databend/issues/5474
> moving role_cache_manager to session manager

- Cargo.lock
- Cargo.toml
- common/ast/Cargo.toml
- common/exception/Cargo.toml
- common/functions/Cargo.toml
- query/Cargo.toml
- query/src/sql/statements/query/query_schema_joined_analyzer.rs
- query/src/storages/fuse/fuse_table.rs
- query/src/storages/fuse/io/read/meta_readers.rs
- query/src/storages/fuse/operations/navigate.rs
- query/src/storages/storage_table.rs
- query/tests/it/sql/parsers/mod.rs
- query/tests/it/sql/parsers/parser_select_table_at.rs
- query/tests/it/sql/parsers/parser_table.rs
- query/tests/it/storages/fuse/operations/navigate.rs
- tests/logictest/http_connector.py
- tests/logictest/logictest.py
- tests/suites/0_stateless/12_time_travel/12_0004_time_travel_select_at.result
- tests/suites/0_stateless/12_time_travel/12_0004_time_travel_select_at.sh
Basic `select at` syntax supports, **Legacy Parser ONLY**
`select * from t12_0004 at (snapshot => "98ec833d7806463ba71cfb6a13fa12c3");`
~~~
mysql> create table t12_0004(c int);
Query OK, 0 rows affected (0.09 sec)
Read 0 rows, 0.00 B in 0.045 sec., 0 rows/sec., 0.00 B/sec.
mysql> insert into t12_0004 values(1),(2);
Query OK, 0 rows affected (0.04 sec)
Read 2 rows, 8.00 B in 0.028 sec., 71.33 rows/sec., 285.32 B/sec.
mysql> insert into t12_0004 values(3);
Query OK, 0 rows affected (0.06 sec)
Read 1 rows, 4.00 B in 0.029 sec., 34.72 rows/sec., 138.89 B/sec.
mysql> select * from t12_0004;
+------+
| c    |
+------+
|    1 |
|    2 |
|    3 |
+------+
3 rows in set (0.04 sec)
Read 3 rows, 12.00 B in …
> feat: data time travel "select at"

- common/ast/src/ast/statement.rs
- common/ast/src/parser/statement.rs
- common/ast/tests/it/testdata/statement-error.txt
- common/ast/tests/it/testdata/statement.txt
- common/planners/src/plan_table_drop.rs
- query/src/interpreters/interpreter_table_drop.rs
- query/src/sql/parsers/parser_table.rs
- query/src/sql/statements/statement_drop_table.rs
- query/tests/it/sql/parsers/parser_table.rs
- query/tests/it/storages/fuse/operations/purge_drop.rs
- tests/suites/0_stateless/05_ddl/05_0000_ddl_drop_tables.sql
- tests/suites/0_stateless/13_ddl_incompatible/13_0001_ddl_drop_table_full.sql
`drop table .. all` **Legacy Parser ONLY**
Besides removing table metadata from KV server,  with the option `all`, the stmt will truncate table data and purge them as well.
- Improvement
Fixes #5613
> feat: `drop table .. all`

- common/ast/src/ast/statement.rs
- common/ast/src/parser/statement.rs
- common/ast/src/parser/token.rs
- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/statement.txt
`undrop table` & `show tables history` for new parser
- Improvement
Fixes #issue
> feat(parser): `undrop table` & `show tables history` for new parser

- query/src/sql/planner/semantic/type_check.rs
- query/tests/it/servers/http/http_query_handlers.rs
- query/tests/it/sql/parsers/parser_select_table_at.rs
- query/tests/it/storages/fuse/meta/snapshot.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
Support tuple in new planner, also fix clippy.
- New Feature
Close #5632
> feature(planner): Support tuple in new planner

- metasrv/src/api/grpc/grpc_service.rs
> [metasrv] do not assert protocol_version to be 0, to make it compatible with query that sends protocol_version

- common/meta/api/src/schema_api_test_suite.rs
Signed-off-by: RinChanNOWWW <hzy427@gmail.com>
Check db's seq after create/drop/rename table, requiring the db's seq before changing is lower than the new one after changing.
Fixes #5220
> test(meta): check db's seq after create/drop/rename table

- common/ast/src/parser/expr.rs
- common/ast/src/parser/token.rs
- common/ast/src/parser/util.rs
- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/expr-error.txt
- common/ast/tests/it/testdata/expr.txt
- Distinguish map access `[1]` and array literal `[1]` based on its previous element.
- Accept hexadecimal numbers in MySQL style like `0xff`.
- Make `DataTime` an alias of `Timestamp`.
- New Feature
- Bug Fix
Fixes https://github.com/datafuselabs/databend/issues/5643
> fix(parser): allow mysql-style hex number and single-item array

- query/src/sql/planner/binder/aggregate.rs
- query/src/sql/planner/binder/select.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
Support use alias group item in having clause, for example:
```sql
select a+1 as b from t group by b having b = 1;
```
- Improvement
Related to #5660
> improve(planner): Support use alias group item in `HAVING`

- common/exception/src/exception_code.rs
- query/src/sessions/session_mgr.rs
- query/tests/it/sessions/query_ctx.rs
- query/tests/it/storages/system/configs_table.rs
It is possible that our users will have misconfigured storage. They could misspell the endpoint URL, or their K8s config map is not updated, or AWS STS doesn't return the updated token.
This PR will add a check after constructing the OpenDAL operator to know whether the current storage is functional. If not, we will return the error directly instead of keep running.
- For local setup, users can check their config quicker instead of while they are running queries.
- For K8S and cloud setup, databend-query will be restarted automatically until all config updated or reach the deadline.
> Thanks to the new API `Operator::check()` introduced in `OpenDAL` v0.7 …
> feat(query): Fail fast if the underlying storage is not available

- metasrv/src/bin/metasrv.rs
- metasrv/src/configs/outer_v0.rs
Add another command: `--cmd show-config` to display the **effective** config
to metasrv.
The **effective** config can be thought as being built in 4 steps:
- Build the config instance `conf` initialized with default values.
- Apply config.toml to `conf`.
- Apply environment variable config to `conf`.
- Apply CLI arg config to `conf`.
> [metasrv] config: raft_advertise_host default value should by default be the host name of the running machine, instead of literal "localhost"

- common/meta/api/src/schema_api_test_suite.rs
Remove todos related to 'rename table' in schema_api_test_suite
Fixes #5688
> Remove schema_api_test_suite todos

- common/planners/src/plan_user_create.rs
- query/src/interpreters/interpreter_user_create.rs
- query/src/sql/statements/statement_create_user.rs
- tests/suites/0_stateless/05_ddl/05_0004_ddl_create_user.sql
add `if_not_exists` field in `CreateUserPlan` and pass it to `CreateUserInterpreter`.
- Bug Fix
Fixes #5582
> fix(user):  fix 'create user if not exists' fail when user exists

- query/src/sql/planner/binder/project.rs
- query/src/sql/planner/binder/select.rs
- query/src/sql/planner/binder/table.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
Fix issue that choosing wrong parameter as limit and offset in new planner.
- Bug Fix
> bugfix(planner): Fix `LIMIT` with offset

- .github/actions/test_compat/action.yml
- tests/compat/test-compat.sh
And for test-compat, only config one metasrv endpoints for it.
- Fix a query-config caused compatibility failure found in: #5732
> [metasrv] ci: test-compat downloads config file for old query

- query/src/users/auth/auth_mgr.rs
the builtin roles was initialized on CREATE USER statement, but it's not get initialized on creating user by jwt auth.
this PR initialize the builtin roles on the jwt auth, so the user created by JWT can be granted with the account_admin role.
- Bug Fix
Fixes #issue
> fix: ensure builtin roles on create user by jwt

- common/exception/src/exception.rs
- common/meta/types/src/lib.rs
- common/meta/types/src/meta_errors_into.rs
> [common/exception] refactor: add ErrorCode::set_backtrace() for keeping the original bt when converting MetaError to ErrorCode

- common/meta/types/src/operation.rs
- common/meta/types/src/seq_value.rs
This will make developers' live easier:
We will output `[binary]` in logs instead so that our logs will not be polluted by non-sense binaries, for example:
- New Feature
> feat(meta): Output [binary] in debug message instead

- .github/actions/publish_image/action.yml
- .github/workflows/databend-release.yml
- .github/workflows/production.yml
- docker/databend-query-docker.toml
The secret `DOCKERHUB_NAMESPACE` could be deleted.
Fixes #issue
> fix: push release image to datafuselabs/databend:latest

- metasrv/src/configs/outer_v0.rs
- query/src/config/outer_v0.rs
- tools/metactl/src/main.rs
```
$ ./target/debug/databend-meta --version
databend-meta v0.7.69-nightly-0fe675e-simd(1.63.0-nightly-2022-06-03T03:08:32.84573831Z)
$ ./target/debug/databend-meta -V
databend-meta v0.7.69-nightly-0fe675e-simd(1.63.0-nightly-2022-06-03T03:08:32.84573831Z)
$ ./target/debug/databend-metactl --version
databend-metactl v0.7.69-nightly-0fe675e-simd(1.63.0-nightly-2022-06-03T03:08:32.84573831Z)
$ ./target/debug/databend-metactl -V
databend-metactl v0.7.69-nightly-0fe675e-simd(1.63.0-nightly-2022-06-03T03:08:32.84573831Z)
$ ./target/debug/databend-query --version
databend-query v0.7.69-nightly-0fe675e-simd(rust-1.63.0-nightly-2022-06-03T02:31:31.187404703Z)
$ ./target/debug/databend-query -V …
```
> chore(improvement): --version or -V show the binary release commit info

- common/ast/src/ast/mod.rs
- common/ast/src/ast/statement.rs
- common/ast/src/parser/statement.rs
- common/ast/tests/it/testdata/statement-error.txt
- common/ast/tests/it/testdata/statement.txt
- common/planners/src/plan_table_create.rs
- query/src/interpreters/interpreter_factory_v2.rs
- query/src/sql/optimizer/mod.rs
- query/src/sql/planner/binder/ddl/mod.rs
- query/src/sql/planner/binder/ddl/table.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/plans/mod.rs
- query/src/sql/statements/statement_create_table.rs
- query/tests/it/storages/fuse/table_test_fixture.rs
- tests/suites/0_stateless/05_ddl/05_0000_ddl_create_tables_v2.result
- tests/suites/0_stateless/05_ddl/05_0000_ddl_create_tables_v2.sql
`CREATE TABLE ... AS SELECT ...` is blocked by #5780 
- New Feature
Close #5735
> feature(planner): Support `CREATE TABLE` statement in new planner

- common/proto-conv/src/config_from_to_protobuf_impl.rs
- common/proto-conv/src/data_from_to_protobuf_impl.rs
- common/proto-conv/src/database_from_to_protobuf_impl.rs
- common/proto-conv/src/lib.rs
- common/proto-conv/src/table_from_to_protobuf_impl.rs
- common/proto-conv/src/user_from_to_protobuf_impl.rs
- common/proto-conv/src/util.rs
- common/proto-conv/tests/it/proto_conv.rs
- common/proto-conv/tests/it/user_proto_conv.rs
- common/protos/proto/config.proto
- common/protos/proto/datatype.proto
- common/protos/proto/metadata.proto
- common/protos/proto/user.proto
**Non-breaking** meta-protobuf change.
This way to let old query be able to decide if it is safe to load data
written by a newer query executable.
- Fix: #5784
- New Feature
> [meta] feature: protobuf message has to persist `MIN_COMPATIBLE_VER` in it

- common/ast/src/parser/mod.rs
- query/src/sql/planner/semantic/type_check.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
as the tile
- New Feature
Fixes https://github.com/datafuselabs/databend/issues/5647
> feat(planner): support udf

- metasrv/src/meta_service/raftmeta.rs
- New Feature
- Bug Fix
- Improvement
Fixes #issue
> Remove subscribe_metrics todos.

- common/ast/src/ast/statement.rs
- common/ast/src/parser/statement.rs
- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/statement-error.txt
- common/ast/tests/it/testdata/statement.txt
- common/meta/types/src/user_auth.rs
- query/src/interpreters/interpreter_factory_v2.rs
- query/src/sql/optimizer/mod.rs
- query/src/sql/planner/binder/ddl/mod.rs
- query/src/sql/planner/binder/ddl/user.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/format/display_plan.rs
- query/src/sql/planner/plans/mod.rs
- tests/suites/0_stateless/05_ddl/05_0004_ddl_create_user_v2.sql
Migrate create user to new planner
- New Feature
Fixes #5777
> feature(planner): Migrate CREATE USER statement to new planner

- query/src/interpreters/interpreter_copy.rs
- query/src/interpreters/interpreter_select.rs
- query/src/interpreters/interpreter_select_v2.rs
- query/src/interpreters/stream/processor_executor_stream.rs
- query/src/pipelines/new/executor/pipeline_executor.rs
- query/src/pipelines/new/executor/pipeline_pulling_executor.rs
fixes(executor): support abort for pipeline executor stream
- Bug Fix
Fixes #4871
> fixes(executor): support abort for pipeline executor stream

- Cargo.lock
- Cargo.toml
- common/arrow/Cargo.toml
- common/arrow/src/parquet_write.rs
- common/datavalues/src/columns/object/mod.rs
- common/meta/app/Cargo.toml
- tests/suites/0_stateless/03_dml/03_0023_insert_into_array.sql
Fix read array(string) from fuse engine
- Upgrade `arrow2` to version 0.12.0
- Upgrade `parquet2` to version 0.13.0
- Bug Fix
Fixes #5564
> fix(query): Fix read array(string) from fuse engine

- Cargo.lock
- Cargo.toml
The modifications introduced in 
- pr #5806 
is highly suspicious to be not parquet standard compatible.
Luckily, the issue that pr #5806 trying to fix has already been fixed by parquet v0.13. 
Thus we switch to the patched branch of parquet v0.13:
https://github.com/datafuse-extras/parquet2/commits/parquet2-0.13-patch2
- Bug Fix
Fixes #issue
> fix: remove incompatible modification of chunk compression

- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/statement-error.txt
- common/ast/tests/it/testdata/statement.txt
- query/src/interpreters/interpreter_factory_v2.rs
- query/src/sql/optimizer/mod.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/format/display_plan.rs
- query/src/sql/planner/plans/mod.rs
- tests/suites/0_stateless/05_ddl/05_0007_ddl_drop_user_v2.sql
Migrate drop user to new planner
- New Feature
#5777
> feature(planner): Migrate DROP USER statement to new planner

- common/meta/types/proto/meta.proto
- docs/doc/50-manage/00-metasrv/50-metasrv-metrics.md
- metasrv/src/meta_service/meta_service_impl.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/metrics/meta_metrics.rs
- metasrv/src/metrics/mod.rs
- metasrv/src/network.rs
Feature: add metrics about metasrv network and docs
- New Feature
Fixes [#issue](https://github.com/datafuselabs/databend/issues/5841)
> Feature: add metrics about metasrv network and docs

- tests/logictest/http_connector.py
- tests/logictest/http_runner.py
http_connector gets a single response now and will fail the logic test when the HTTP handler returns empty data with a valid next_uri.
In order to fix this case, http_connector must fetch all results and combine them.
cc @youngsofun 
Fixes #issue
> fix: http_connector will fetch all results

- .github/actions/build_debug_hive/action.yml
- .github/actions/test_stateful_hive_standalone/action.yml
- .github/mergify.yml
- .github/workflows/developing.yml
- .github/workflows/production.yml
Implement https://github.com/datafuselabs/databend/discussions/5880
This PR:
- Make macOS checks optional, so we can merge a PR without waiting for macOS.
- Remove requirement of check before embarking into merge queue, reduce the time for mergeing
- Remove requirement of CI check, so all tasks can run concurrently.
> ci: Make macOS checks optional

- tests/logictest/http_connector.py
request waits at the server side for 1 secs by default.
additional sleep may make CI slow
Fixes #issue
> http handler in logic test do not need to sleep

- .github/workflows/production.yml
ci: Don't need to wait for macOS for publishing image
Fixes #issue
> ci: Don't need to wait for macOS for publishing image

- Cargo.lock
- query/Cargo.toml
- query/src/formats/format_factory.rs
- query/src/formats/output_format.rs
- query/src/formats/output_format_csv.rs
- query/src/formats/output_format_ndjson.rs
- query/src/servers/http/clickhouse_handler.rs
- query/tests/it/formats/format_factory.rs
- query/tests/it/formats/mod.rs
- query/tests/it/formats/output_format_tcsv.rs
- query/tests/it/servers/http/clickhouse_handler.rs
basic support for TsvWithNamesAndTypes,
1. use FormatFactory only for `name-> enum OutputFormatType` , more freedom and less code to handle the following:
- case_insensitive
- alias (TSV, TabSeperated), (NDJSON, JSONEachrow)
- "withName and withNameAndFormat" suffix
2. OutputFormatType is used as a unique id (no alias) to carry around(after sql parse) and ease ops like match, cmp, define capabilities
-  it also make it very clear to see all supported formats in the code.
4.  use OutputFormatType to create dyn OutputFormat
5.  TsvWithNamesAndTypes implemented with constant generics,  make the code more uniform thanks to @zhang2014 
- New Feature
Fixes #issue
> clickhouse http handler support TsvWithNamesAndTypes.

- query/src/interpreters/async_insert_queue.rs
1. bug fix: delete processing entry
2. bug fix: return err when server panic
cc @BohuTANG 
- Bug Fix
Fixes #5844 
https://github.com/datafuselabs/databend/pull/5567#issuecomment-1149339319
> fix(insert): server panic when exceeds max active sessions

- query/src/sql/planner/binder/bind_context.rs
- query/src/sql/planner/binder/join.rs
- query/tests/it/sql/optimizer/heuristic/mod.rs
- query/tests/it/sql/optimizer/heuristic/subquery.rs
- query/tests/it/sql/optimizer/heuristic/testdata/subquery.test
> bugfix(planner): Fix correlated subquery with joins

- scripts/ci/ci-run-stateless-tests-cluster.sh
- tests/suites/0_stateless/02_function/02_0057_function_nullif.result
- tests/suites/0_stateless/02_function/02_0057_function_nullif.sql
- add 02_0057_function_nullif.result
- skip nullif in cluster mode
Fixes #5937
> test(stateless): add 02_0057_function_nullif result

- docs/doc/30-reference/00-api/00-rest.md
- query/src/servers/http/v1/http_query_handlers.rs
- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/http/v1/query/http_query.rs
- query/src/servers/http/v1/query/mod.rs
- query/tests/it/servers/http/http_query_handlers.rs
```
"scan_progress": {
"rows": 100000000,
"bytes": 800000000
},
```
to 
```
"scan_progress": {
"rows": 100000000,
"bytes": 800000000
},
"write_progress": {
"rows": 0,
"bytes": 0
},
"result_progress": {
"rows": 0,
"bytes": 0 
},
```
Fixes #issue
> feat: http handler return write/result progress.

- query/src/storages/fuse/statistics/accumulator.rs
- query/tests/it/storages/fuse/statistics.rs
To avoid high cardinality, for each string column,  clustering uses only the first 5 bytes.  
- Improvement
Fixes #5981
> ISSUE-5981: truncate the string value for cluster statis

- query/src/pipelines/new/executor/pipeline_pulling_executor.rs
- query/src/servers/http/v1/query/page_manager.rs
- query/tests/it/servers/http/clickhouse_handler.rs
- query/tests/it/servers/http/http_query_handlers.rs
the first commit is most important.  it fixes the bug:
the original `try_pull_data` stop generating  data once `.executor.is_finished()`, 
but the channel may still contains data that is not consumed.
the bug can be reproduced by the unit tests I add in the pr.
mysql handler not suffer from this because it call stream::collect();
also refactored page_manager when debugging this.
- Bug Fix
Fixes https://github.com/databendcloud/databend-cloud-platform/issues/1536#issuecomment-1155203419
maybe this flaky test is related to the bug too https://github.com/datafuselabs/databend/pull/5936#issuecomment-1153707779
> bugfix:  ProcessorExecutorStream lost data 

- common/io/src/operator.rs
- query/src/interpreters/interpreter_common.rs
- query/tests/it/interpreters/interpreter_list.rs
refactor: List stage files recursively
- Improvement
> refactor: List stage files recursively

- query/src/interpreters/interpreter_explain_v2.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
After this pr:
```
mysql> explain select number + 1 as a from numbers(1) where number = 1;
+------------------------------------------+
| explain                                  |
+------------------------------------------+
| Project: [a]                             |
|     EvalScalar: [+(number, 1)]           |
|         Filter: [number = 1]             |
|             Scan: default.system.numbers |
+------------------------------------------+
4 rows in set (0.03 sec)
Read 0 rows, 0.00 B in 0.001 sec., 0 rows/sec., 0.00 B/sec.
mysql>
```
- Improvement
> improve(planner): Split `EXPLAIN` result by lines

- Cargo.lock
- common/ast/Cargo.toml
- common/base/Cargo.toml
- common/contexts/Cargo.toml
- common/management/Cargo.toml
- common/meta/api/Cargo.toml
- common/meta/embedded/Cargo.toml
- common/meta/raft-store/Cargo.toml
- common/streams/Cargo.toml
- metasrv/Cargo.toml
- query/Cargo.toml
- query/src/pipelines/new/processors/sinks/async_sink.rs
- query/src/pipelines/new/processors/sources/async_source.rs
- query/src/pipelines/new/processors/sources/mod.rs
- query/src/pipelines/new/processors/sources/stream_source.rs
- query/src/pipelines/new/processors/sources/stream_source_v2.rs
- query/src/storages/fuse/table_functions/clustering_informations/clustering_information_table.rs
- query/src/storages/fuse/table_functions/fuse_segments/fuse_segment_table.rs
- query/src/storages/fuse/table_functions/fuse_snapshots/fuse_snapshot_table.rs
- query/src/storages/github/github_table.rs
- query/src/storages/stage/stage_source.rs
- query/src/storages/system/table.rs
- query/src/table_functions/async_crash_me.rs
use unboxed_simple to simple GAT
- Improvement
Fixes #4408
Related https://github.com/wvwwvwwv/async-trait/pull/1
> refactor(async-trait): use unboxed_simple to simple GAT

- common/io/src/position.rs
Fix a minor compile error, if built with `-C target-cpu=native`, and the host has sse42 capability
- Not sure if CI has sse42
- unit test and stateless test works in the local dev box 
- CPU has sse42 flag
- release build with "-C target-cpu=native"
- Bug Fix
Fixes #6000
> Fix:  native build with sse42 capability

- query/src/storages/system/tables_table.rs
fix: cluster_key -> current_cluster_key
Fixes #issue
> fix: cluster_key -> current_cluster_key

- common/ast/src/ast/statement.rs
- common/ast/src/parser/statement.rs
- common/ast/src/parser/token.rs
- query/src/interpreters/interpreter_factory.rs
- query/src/interpreters/interpreter_factory_v2.rs
- query/src/interpreters/interpreter_show_roles.rs
- query/src/interpreters/interpreter_show_users.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/format/display_plan.rs
- query/src/sql/planner/plans/mod.rs
- tests/suites/0_stateless/06_show/06_0007_show_roles_v2.result
- tests/suites/0_stateless/06_show/06_0007_show_roles_v2.sql
- New Feature
https://github.com/datafuselabs/databend/issues/5777
> Migrate show users/roles statement to new planner

- Makefile
- common/ast/src/ast/statement.rs
- common/ast/src/parser/statement.rs
- common/ast/src/parser/token.rs
- common/ast/tests/it/testdata/statement.txt
- query/src/catalogs/default/mutable_catalog.rs
- query/src/sql/parsers/parser_table.rs
- query/src/sql/planner/binder/ddl/table.rs
- query/src/sql/sql_parser.rs
- query/src/storages/fuse/fuse_table.rs
- query/src/storages/fuse/operations/commit.rs
- query/src/storages/fuse/operations/gc.rs
- query/tests/it/sql/parsers/parser_copy.rs
- query/tests/it/sql/parsers/parser_optimize.rs
- query/tests/it/sql/parsers/parser_select_table_at.rs
- query/tests/it/sql/parsers/parser_table.rs
- query/tests/it/sql/sql_parser.rs
- tests/logictest/suites/gen/09_fuse_engine/09_0016_transient_table
- tests/suites/0_stateless/05_ddl/05_0000_ddl_create_tables.result
- tests/suites/0_stateless/05_ddl/05_0000_ddl_create_tables.sql
- tests/suites/0_stateless/05_ddl/05_0000_ddl_create_tables_v2.result
- tests/suites/0_stateless/05_ddl/05_0000_ddl_create_tables_v2.sql
- tests/suites/0_stateless/09_fuse_engine/09_0016_transient_table.result
- tests/suites/0_stateless/09_fuse_engine/09_0016_transient_table.sql
The new statement `CREATE TRANSIENT TABLE...`:
- for FUSE table, during commit, no historical data will be kept
or more precisely: GC will be triggered immediately after the commit
- for table engine other than fuse, nothing different
example: 
~~~
mysql> use default;
Database changed
mysql> CREATE TRANSIENT TABLE t (c bigint);
Read 0 rows, 0.00 B in 0.006 sec., 0 rows/sec., 0.00 B/sec.
Query OK, 0 rows affected (0.02 sec)
Read 1 rows, 8.00 B in 0.011 sec., 91.64 rows/sec., 733.14 B/sec.
mysql> insert into t values(2);
Query OK, 0 rows affected (0.04 sec)
Read 1 rows, 8.00 B in 0.013 sec., 78.42 rows/sec., 627.38 B/sec.
mysql> …
> feat: transient fuse table

- query/src/sql/planner/binder/aggregate.rs
- query/src/sql/planner/binder/sort.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
Support order by column ordinal:
```sql
mysql> select * from t1 order by 3;
ERROR 1105 (HY000): Code: 1065, displayText = error:
--> SQL:1:27
|
1 | select * from t1 order by 3
|                           ^ ORDER BY position 3 is not in select list
.
mysql> select * from t1 order by 2 desc;
+------+------+
| a    | b    |
+------+------+
|    2 |    3 |
|    1 |    2 |
+------+------+
2 rows in set (0.03 sec)
Read 2 rows, 16.00 B in 0.003 sec., 697.3 rows/sec., 5.45 KiB/sec.
mysql> select a from t1 order by 1 desc;
+------+
| a    |
+------+
|    2 |
|    1 |
+------+
2 rows in set (0.03 sec)
Read 2 rows, 16.00 B in 0.003 sec., 788.31 rows/sec., 6.16 KiB/sec.
```
- New Feature
Fixes #6023
> feat(planner): support ORDER BY column ordinal

- docker/build-tool/base/Dockerfile
- scripts/setup/dev_setup.sh
> fix(ci): java home in build tool

- scripts/setup/dev_setup.sh
add_profile should return 0 even if no items are found in `~/.profile`
- Bug Fix
Fixes #issue
> fix: add_profile shoud return 0 if no items found in profile

- query/src/interpreters/interpreter_factory_v2.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/binder/show.rs
- query/src/sql/planner/format/display_plan.rs
- query/src/sql/planner/plans/mod.rs
- tests/suites/0_stateless/06_show/06_0005_show_functions_v2.result
- tests/suites/0_stateless/06_show/06_0005_show_functions_v2.sql
Migrate `show functions` to new planner.
Migrate `show functions` to new planner.
Fixes #5899
> Migrate `show functions` to new planner

- Cargo.lock
- common/ast/Cargo.toml
- common/ast/src/ast/statement.rs
- common/ast/src/parser/statement.rs
- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/statement.txt
`INSERT INTO ... FORMAT ...` and `INSERT INTO ... VALUES` statements will stop the parser immediately and return the rest tokens by `InsertSource`. This is a hack to make it able to parse a large streaming insert statement.
- New Feature
> feature(parser): stop parsing at insert statement

- common/ast/src/ast/expr.rs
- common/ast/src/parser/expr.rs
- common/ast/src/parser/token.rs
- common/ast/tests/it/testdata/expr-error.txt
- query/src/sql/planner/semantic/type_check.rs
- tests/suites/0_stateless/02_function/02_0012_function_datetimes.sql
support `date_sub`
```sql
set enable_planner_v2=1;
select '===date_sub===';
select date_sub(to_date(18321), 1, YEAR);
select date_sub(to_date(18321), -1, YEAR);
select date_sub(to_date(18321), 1, SECOND);
create table t(a int);
insert into t values(1), (2);
select date_sub(to_date(18321), a, YEAR) from t;
drop table t;
set enable_planner_v2=0;
```
```
===date_sub===
2019-02-28
2021-02-28
2020-02-28 23:59:59.000000
2019-02-28
2018-02-28
```
- New Feature
Fixes #6014
> feat: support date_sub

- Cargo.lock
- common/meta/app/Cargo.toml
- common/meta/sled-store/Cargo.toml
- common/meta/types/Cargo.toml
- common/tracing/src/logging.rs
- metasrv/Cargo.toml
- metasrv/src/api/http/debug/jeprof.rs
- metasrv/src/api/http/debug/mod.rs
- metasrv/src/api/http_service.rs
- tools/metabench/Cargo.toml
- tools/metabench/src/main.rs
There two memory leak:
- Using span.enter() in a async block.
This inappropriate usage is in openraft.
Update openraft to `0.7.1-alpha.1` to solve it:
Openraft change log in this commit:
-   Fixed: [a0a94af7](https://github.com/datafuselabs/openraft/commit/a0a94af7612bd9aaae5a5404325887b16d7a96ae) span.enter() in async loop causes memory leak; by 张炎泼; 2022-06-17
It is explained in:
https://onesignal.com/blog/solving-memory-leaks-in-rust/
- Jaeger buffers tracing logs if the receiving server is not online:
Solve this issue by enabling jaeger by environment variable.
Other changes:
- Feature: add jemalloc memory profiling support: /debug/mem/pprof/profile.
See: …
> [meta] fix memory leak with tracing.

- query/bin/databend-query.rs
- query/src/servers/http/http_services.rs
Improve the endpoint to more readable.
Fixes #issue
> chore(log): make the databend server and port for human

- common/datavalues/src/types/serializations/number.rs
- common/io/src/format_settings.rs
- query/src/formats/output_format_json_each_row.rs
- query/tests/it/formats/mod.rs
- query/tests/it/formats/output_format_json_each_row.rs
- query/tests/it/formats/output_format_tcsv.rs
- query/tests/it/formats/output_format_utils.rs
following clickhouse conversion
1.  JSON write `null`
2.  tsv/csv write `nan`, `inf`
- New Feature
Fixes #issue
> feat(query): Configurable repr of float denormals in output formats.

- query/src/servers/http/v1/query/execute_state.rs
root_pipleline executor should be inited after the child pipelines are executed.
Fixes https://github.com/datafuselabs/databend/issues/6054
> fix(query): http handler pipeline execute.

- query/src/sql/exec/data_schema_builder.rs
- query/src/sql/optimizer/heuristic/decorrelate.rs
- query/src/sql/planner/metadata.rs
- query/tests/it/sql/optimizer/heuristic/subquery.rs
- query/tests/it/sql/optimizer/heuristic/testdata/subquery.test
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
Fix incorrect output schema of `SemiJoin` and `AntiJoin`.
And also fix incorrect predicate pushing.
- Bug Fix
Related to #6060
> bugfix(optimizer): Fix error of `EXISTS` subquery

- docs/doc/30-reference/30-sql/20-query-syntax/dml-select.md
- added syntax and examples for **order by column position**.
- added notes to the existing **order by** examples.
- added syntax for **order by column alias** as well, as I see an example already exists on the page.
Fixes #issue
> Doc: Order by column position

- docker/Dockerfile
- docker/stateless/Dockerfile
Add missing certificates dependencies to Dockerfile
- Bug Fix
Fixes #6134
> fix(docker): fix certificates dependencies

- query/src/storages/fuse/meta/v1/snapshot.rs
- tests/suites/0_stateless/12_time_travel/12_0004_time_travel_select_at.result
- tests/suites/0_stateless/12_time_travel/12_0004_time_travel_select_at.sh
- Adjust table snapshot timestamp precision to microsecond
- to be consistent with the precision of SQL timestamp expression 
- make time travel by timestamp user friendly
- Tweak stateless test script accordingly 
A Quick demo of usage: 
~~~sql
mysql> use default;
Database changed
mysql> create table demo(c varchar);
Query OK, 0 rows affected (0.06 sec)
mysql> insert into demo values('batch1.1'),('batch1.2');
mysql> insert into demo values('batch2.1');
Query OK, 0 rows affected (0.04 sec)
mysql> select timestamp from fuse_snapshot('default', 'demo'); --show snapshot timestamps
+----------------------------+
| timestamp                  | …
> Fix(storage): Adjust table snapshot timestamp precision to micro second

- Cargo.lock
- query/src/servers/mysql/writers/query_result_writer.rs
fix datatype different cause mysql session distroy.
Before Sundy's pr fix https://github.com/datafuselabs/databend/pull/5980 NULLIF function could cause MySQL session destory.
Because in `Series::check_get(col)?;`  return a err and 
1. not finish the RowWriter.
2. server does not send anything to the client.
So should use match arm, if find the expr return Err(e) , finish the RowWriter and then return Ok(()).
BTW, we should return Ok(()) because we should not destory the session when cause these err.
I has already rollback Sundy's pr and then test on my laptop. But I don't know how to test the pr on the newest commit version.
```SQL
'root'@mysqldb 21:27:39 [(none)]> set enable_planner_v2=1;
Query …
```
> Improvement(query): fix datatype different cause mysql session distroy

- website/docusaurus.config.js
This PR add `docs/public` as website static, so that we can refer to docs' images by `/img/api/api-handler-mysql.png`.
All content under `docs/public` will be copied to root of website.
> website: Add public as static

- query/src/procedures/systems/fuse_snapshot.rs
- query/src/storages/fuse/io/read/meta_readers.rs
- query/src/storages/fuse/table_functions/fuse_segments/fuse_segment.rs
- query/src/storages/fuse/table_functions/fuse_snapshots/fuse_snapshot.rs
- query/src/storages/fuse/table_functions/fuse_snapshots/fuse_snapshot_table.rs
- query/tests/it/interpreters/interpreter_call.rs
- tests/suites/0_stateless/09_fuse_engine/09_0017_func_fuse_snapshot_history_limit.result
- tests/suites/0_stateless/09_fuse_engine/09_0017_func_fuse_snapshot_history_limit.sh
limit push down for table `fuse_snapshot` & proc `system$fuse_snapshot`
- for "table function" `fuse_snapshot`
while fetching snapshots, the `limit` that has been pushed down will be respected: no longer traverse all the historical snapshots unconditionally
- For stored procedure `system$fuse_snapshot`
Anther optional argument is introduced, where the limit can be specified, e.g.
`call system$fuse_snapshot('default', 'tbl', 1)`
- Improvement
Fixes #issue
> Improvement: limit push down for table `fuse_snapshot` & proc `system$fuse_snapshot`

- common/tracing/src/logging.rs
- docs/doc/50-manage/00-metasrv/20-metasrv-add-remove-node.md
- metasrv/src/bin/metasrv.rs
- metasrv/src/meta_service/raftmeta.rs
- query/bin/databend-query.rs
- tools/metactl/src/main.rs
> [common/tracing] optionally disable stdout logging: metactl export data to stdout thus has to disable stdout logging

- common/tracing/src/logging.rs
> [common/tracing] fixup: by default stdout log should be output

- .github/mergify.yml
ci(mergify): Push PR into queue when it passed all checks
Fixes #issue
> ci(mergify): Push PR into queue when it passed all checks

- tests/metactl/test-metactl.sh
- Fix: The slepp time 0.5 is too short: metactl may start to export before databend-meta finishes starting up.
Which is found in:
https://github.com/datafuselabs/databend/pull/6225
https://github.com/datafuselabs/databend/runs/7050529664?check_suite_focus=true
- Bug Fix
> [metasrv] fix: add step instruction to tests/metactl/test-metactl;

- query/src/sql/planner/format/display_rel_operator.rs
- query/tests/it/sql/optimizer/heuristic/testdata/join.test
- query/tests/it/sql/optimizer/heuristic/testdata/select.test
- query/tests/it/sql/optimizer/heuristic/testdata/subquery.test
- tests/logictest/suites/gen/20+_others/20_0001_planner_v2
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
Adding table name for column to make explain clearer
- Improvement
Fixes #issue
> improve: add table name for column in `explain`

- Cargo.lock
- common/contexts/Cargo.toml
- common/io/Cargo.toml
- common/streams/Cargo.toml
- query/Cargo.toml
- query/src/interpreters/interpreter_common.rs
- query/src/servers/http/v1/stage.rs
- query/src/sessions/session_mgr.rs
- tests/suites/1_stateful/01_load/01_0001_upload_to_stage.result
- tests/suites/1_stateful/01_load_v2/01_0001_upload_to_stage.result
OpenDAL has released v0.9.1: https://github.com/datafuselabs/opendal/discussions/401
With this release, we will fix the following issues:
- Fix https://github.com/datafuselabs/databend/issues/6119
- Fix #6139 
- Fix #5993 
- Bug Fix
> Bump opendal to v0.9.1

- .github/mergify.yml
- .github/workflows/developing.yml
- Cargo.lock
- Cargo.toml
- common/base/Cargo.toml
After https://github.com/datafuselabs/databend/pull/6165, musl 1.2.3 is included in our build tools.
It is not possible to revert old commits as we have since modified them.
Fixes #issue
> chore(deps): bump pprof again for musl 1.2.3

- Cargo.lock
fix package debugid is specified twice in the lockfile in `main` branch
Fixes #issue
> chore(dep): fix package debugid is specified twice in the lockfile

- .github/mergify.yml
ci(mergify): Only embark PR while it's ready for review
> ci(mergify): Only embark PR while it's ready for review

- .github/mergify.yml
ci(mergify): Fix build_musl not used correctly
> ci(mergify): Fix build_musl not used correctly

- Makefile
Currently many makefile targets rely on the `build-debug` option, which is replaced
by `build` option and is useless now.
This commit updated dependencies in makefile.
- Bug Fix
Fixes no issue.
> [fix] update makefile's run options

- common/meta/grpc/src/grpc_client.rs
Remove unused `token` lock.
Always assign to `current_endpoint` even if `make_channel` return error.
- Improvement
Fixes #issue
> [metasrv] refactor grpc client

- common/datavalues/src/types/deserializations/nullable.rs
- common/io/src/buffer/buffer_read_datetime_ext.rs
- query/src/formats/format_csv.rs
Improve deserializer
1. support datetime`%Y-%m-%dT%H:%M:%S` pattern
2. fix nullable deserializer
- Bug Fix
Fixes #issue
> Improve(deserializer): fix nullable csv deser

- query/src/clusters/cluster.rs
- query/src/clusters/metrics.rs
Add some metrics for `databend-query/clusters`. Partially #5716 
Metrics added:
- HeartBeat failure count
- Error count in ClusterDiscovery
- Discovered node count in the cluster
Note: I am not sure if we need to add the labels for `cluster_id` and `tenant_id`. If so, we may need to add the corresponding fields to `ClusterDiscovery` and `ClusterHeartBeat` struct. 
Partially of #5716
> chore(metrics): add metrics for `databend-query/clusters`

- common/meta/api/src/kv_api.rs
- common/meta/api/src/lib.rs
- common/meta/api/src/schema_api_test_suite.rs
- common/meta/embedded/tests/it/schema_api_impl.rs
- common/meta/raft-store/tests/it/state_machine/schema_api_impl.rs
- metasrv/tests/it/grpc/metasrv_grpc_schema_api.rs
> [meta/schemaapi] refactor: introduce trait AsKVApi to upcast a SchemaApi to KVApi when a test needs both SchemaApi and KVApi
