- Cargo.lock
- common/arrow/Cargo.toml
- common/datavalues/Cargo.toml
- common/datavalues/benches/eq.rs
- common/datavalues/benches/if_else_then.rs
- common/datavalues/src/columns/boolean/mod.rs
- common/datavalues/src/columns/eq.rs
- common/datavalues/src/macros.rs
- common/datavalues/src/types/eq.rs
- common/datavalues/src/types/type_coercion.rs
- common/functions/src/scalars/comparisons/comparison.rs
- common/functions/src/scalars/comparisons/comparison_eq.rs
- common/functions/src/scalars/comparisons/comparison_gt.rs
- common/functions/src/scalars/comparisons/comparison_gt_eq.rs
- common/functions/src/scalars/comparisons/comparison_like.rs
- common/functions/src/scalars/comparisons/comparison_lt.rs
- common/functions/src/scalars/comparisons/comparison_lt_eq.rs
- common/functions/src/scalars/comparisons/comparison_not_eq.rs
- common/functions/src/scalars/comparisons/comparison_regexp.rs
- common/functions/src/scalars/comparisons/mod.rs
- common/functions/src/scalars/comparisons/utils.rs
- common/functions/tests/it/scalars/comparisons.rs
- rust-toolchain.toml
- tests/suites/0_stateless/02_function/02_0005_function_compare.result
- tests/suites/0_stateless/02_function/02_0005_function_compare.sql
Refactor the comparison function by using ScalarBinaryExpression
- Bug Fix
- Improvement
Fixes #4284 
Unit Tests
> ISSUE-4284: Refactor the comparison function

- query/src/functions/systems/fuse_history.rs
- query/src/servers/mysql/mysql_interactive_worker.rs
- query/src/storages/fuse/fuse_history.rs
- query/src/storages/fuse/table_functions/fuse_history_table.rs
- tests/databend-test
- tests/helpers/client.py
- tests/suites/0_stateless/00_dummy/00_0002_dummy_select_py.py
- Fix broken tracing spans  #4355 
- Bug Fix
Fixes #4355
Unit Tests
> ISSUE-4355: Fix broken tracing spans 

- common/management/src/role/role_mgr.rs
- common/meta/types/src/principal_identity.rs
- common/meta/types/src/role_identity.rs
- common/meta/types/src/role_info.rs
- query/src/interpreters/interpreter_role_create.rs
- query/src/sql/parsers/parser_user.rs
- query/tests/it/interpreters/interpreter_user_previlege_revoke.rs
- query/tests/it/interpreters/interpreter_user_privilege_grant.rs
- query/tests/it/sql/parsers/parser_user.rs
- query/tests/it/sql/plan_parser.rs
- query/tests/it/users/role_cache_mgr.rs
- query/tests/it/users/role_mgr.rs
- tests/suites/0_stateless/05_ddl/05_0014_ddl_create_role.sql
- tests/suites/0_stateless/05_ddl/05_0015_ddl_drop_role.sql
MySQL 8+ introduces roles, [role names](https://dev.mysql.com/doc/refman/8.0/en/role-names.html) have syntax and semantics similar to user names, but unlike hostname in an user name, a host part of role name is meaningless. 
Our role metadata is separated from user, so we don't need to refer to the implementation of MySQL.
In addition, we also distinguish between user and role operations at the SQL layer, [like snowflake](https://docs.snowflake.com/en/sql-reference/sql/grant-role.html):
```
GRANT * ON * TO [USER|ROLE] xxx;
GRANT ROLE TO [USER|ROLE] xxx;
```
This PR does the following two things:
- Remove host for role identity
- Add stateless test for create/drop role
- Improvement
Fixes #issue
Unit …
> Refactor role identity

- query/src/pipelines/new/executor/executor_worker_context.rs
Fix hang after async processor throw error
- Bug Fix
Fixes #issue
Unit Tests
> Fix hang after async processor throw error

- query/src/storages/fuse/fuse_part.rs
- query/src/storages/fuse/io/block_reader.rs
- query/src/storages/fuse/io/mod.rs
- query/src/storages/fuse/io/parallel_async_reader.rs
- query/src/storages/fuse/operations/read.rs
- query/src/storages/fuse/operations/read_partitions.rs
- query/tests/it/storages/fuse/operations/read_plan.rs
Implement new block reader for fuse engine
- Improvement
part #4345
Unit Tests
> Implement new block reader for fuse engine

- query/src/sessions/session_mgr.rs
change async rwlock to sync to avoid async drop
- Improvement
Unit Tests
> Change async rwlock to sync to avoid async drop

- docs/doc/01-deploy/00_local.md
- docs/doc/01-deploy/01_s3.md
> Add shell title for the config

- docs/doc/01-deploy/00_local.md
- docs/doc/01-deploy/01_s3.md
> Add Linux&MacOS&Arm deploy

- docs/doc/01-deploy/00_local.md
- docs/doc/01-deploy/01_s3.md
> Add deploy arch

- docs/doc/02-load-data/01-load-data-from-source/01_mysql.md
Add load data from MySQL
Fixes #issue
Unit Tests
> Doc: Add load data from MySQL

- docs/doc/02-develop/01-golang.md
- docs/doc/02-develop/_category_.yml
- docs/doc/02-load-data/01-load-data-from-source/00_s3.md
- docs/doc/02-load-data/01-load-data-from-source/01_mysql.md
- website/docusaurus.config.js
/doc/category/develop
Fixes #issue
Unit Tests
> Doc: Add developer

- docs/doc/02-develop/01-golang.md
- docs/doc/02-develop/02-python.md
- docs/doc/09-lessons/01-analyze-github-repo-with-databend.md
Doc: Add python to develop
Fixes #issue
Unit Tests
> Doc: Add python to develop

- README.md
- docs/doc/01-deploy/_category_.yml
- docs/doc/02-develop/01-golang.md
- docs/doc/02-develop/02-python.md
- docs/doc/02-load-data/01-load-data-from-source/01_s3.md
- docs/doc/02-load-data/01-load-data-from-source/02_mysql.md
- docs/doc/02-load-data/01-load-data-from-source/03_local.md
- docs/doc/index.md
- website/docusaurus.config.js
Doc: Add ann bar and refine the README
Part of #4360 
Unit Tests
> Doc: Add ann bar and refine the README

- query/src/sql/parsers/parser_table.rs
- query/tests/it/sql/parsers/parser_table.rs
- query/tests/it/sql/sql_parser.rs
- tests/suites/0_stateless/05_ddl/05_0000_ddl_create_tables.sql
Fix column name quotestyle
- Bug Fix
Fixes #4411 
Unit Tests
> Fix column name quotestyle

- docs/doc/01-deploy/00_local.md
- docs/doc/01-deploy/02_minio.md
Doc: Add MinIO deploy
Part of #4360 
Unit Tests
> Doc: Add MinIO deploy

- docs/doc/01-deploy/02_minio.md
- website/docusaurus.config.js
Refine the MinIO deploy
Fixes #issue
Unit Tests
> Doc: Refine the MinIO deploy

- docs/doc/01-deploy/00_local.md
- docs/doc/01-deploy/01_s3.md
- docs/doc/01-deploy/02_minio.md
- docs/doc/01-deploy/03_cluster_minio.md
- docs/doc/02-develop/01-golang.md
- docs/doc/02-develop/02-python.md
- docs/doc/02-load-data/01-load-data-from-source/01_s3.md
- docs/doc/02-load-data/01-load-data-from-source/02_mysql.md
- docs/doc/02-load-data/01-load-data-from-source/03_local.md
- docs/doc/07-performance/02_ec2-s3-performance.md
- docs/doc/09-lessons/01-analyze-github-repo-with-databend.md
- docs/doc/09-lessons/02-analyze-ontime-with-databend-on-ec2-and-s3.md
Add how to deploy cluster with MinIO storage
Part of #4360 
Unit Tests
> DOC-4360: Add cluster to deploy

- docs/doc/07-performance/01_local-vector-performance.md
- docs/doc/07-performance/02_ec2-s3-performance.md
- docs/doc/09-lessons/01-analyze-github-repo-with-databend.md
- docs/doc/09-lessons/02-analyze-ontime-with-databend-on-ec2-and-s3.md
Update s3 performance to 2fe1e36-simd(1.61.0-nightly-2022-03-13)
Fixes #issue
Unit Tests
> Doc: Update s3 performance

- docs/doc/03-reference/03-sql/01-ddl/01-user/_category_.yml
- docs/doc/03-reference/03-sql/01-ddl/01-user/user-create-user.md
- docs/doc/03-reference/03-sql/01-ddl/02-database/_category_.yml
- docs/doc/03-reference/03-sql/01-ddl/02-database/ddl-create-database.md
- docs/doc/03-reference/03-sql/01-ddl/02-database/ddl-drop-database.md
- docs/doc/03-reference/03-sql/01-ddl/03-table/_category_.yml
- docs/doc/03-reference/03-sql/01-ddl/04-stage/_category_.yml
- docs/doc/03-reference/03-sql/01-ddl/04-stage/ddl-create-stage.md
- docs/doc/03-reference/03-sql/01-ddl/04-stage/ddl-drop-stage.md
Refine the sidebar and the stage
Fixes #issue
Unit Tests
> Doc: Refine the sidebar and the stage

- docs/doc/01-deploy/01_s3.md
- docs/doc/01-deploy/03_cos.md
- docs/doc/01-deploy/04_cluster_minio.md
Add Tencent cloud COS deploy
Fixes #issue
Unit Tests
> Doc: Add Tencent cloud COS deploy

- docs/doc/01-deploy/00_local.md
- docs/doc/01-deploy/01_s3.md
- docs/doc/01-deploy/02_minio.md
- docs/doc/01-deploy/03_cos.md
- docs/doc/02-develop/02-python.md
Change linux to ubuntu
Fixes #issue
Unit Tests
> Doc: Change linux to ubuntu

- query/src/pipelines/transforms/group_by/aggregator_groups_builder.rs
- query/src/pipelines/transforms/group_by/aggregator_keys_iter.rs
- query/src/pipelines/transforms/group_by/aggregator_polymorphic_keys.rs
- tests/databend-test
- Bug Fix
Continue #4345
Unit Tests
> feat(groupby): fix groupby single string in new processor

- docs/doc/01-deploy/00_local.md
- docs/doc/01-deploy/01_s3.md
- docs/doc/01-deploy/02_minio.md
- docs/doc/01-deploy/03_cos.md
- docs/doc/01-deploy/04_cluster_minio.md
- docs/doc/02-load-data/02_mysql.md
- docs/doc/02-load-data/04_stage.md
Refine the title
Fixes #issue
Unit Tests
> Doc: Refine the title

- query/src/interpreters/interpreter_table_create.rs
- query/tests/it/interpreters/interpreter_table_create.rs
- tests/databend-test
- tests/suites/0_stateless/05_ddl/05_0000_ddl_create_tables.sql
Add new feature that avoid unkown engine names at the stage of `InterpreterCreateTable`.
- New Feature
Fixes issue https://github.com/datafuselabs/databend/issues/4441
Unit Tests
> create table validation

- docs/doc/02-develop/01-golang.md
- docs/doc/02-develop/02-python.md
Refine the develop doc
Fixes #issue
Unit Tests
> Doc: Refine the develop doc

- docs/doc/02-develop/01-golang.md
- docs/doc/02-develop/02-python.md
Repair docs: 2. develop go and python (if do not exist book_db database, it will be created new one)
- Bug Fix
Fixes #issue
Unit Tests
> repair the docs: 2.develop(go and python if not exist book_db database)

- docs/doc/01-deploy/00_local.md
- docs/doc/02-develop/02-python.md
fix the docs code error
For docs: develop python code Snippets has some problem with create database book_db #4516
Fixes #issue
For docs: develop python code Snippets has some problem with create database book_db #4516
Unit Tests
> fix the docs code error

- docs/doc/01-deploy/00_local.md
- docs/doc/01-deploy/01_s3.md
- docs/doc/01-deploy/02_minio.md
- docs/doc/01-deploy/03_cos.md
- docs/doc/06-contributing/02-building-from-source.md
Add building from source
Fixes #issue
Unit Tests
> Doc: Add building from source

- docs/doc/01-deploy/05_cluster_k8s_minio.md
- docs/doc/07-performance/02_ec2-s3-performance.md
> Doc: Fix some typo and what's caching for ec2-s3 performance

- tests/suites/2_management_mode/00_0005_management_mode_call.result
- tests/suites/2_management_mode/00_0005_management_mode_call.sql
Add bootstrap_tenant test in management mode
- Testing
Fixes #issue
Unit Tests
> [test] Add bootstrap_tenant test in management mode

- docs/doc/03-reference/03-sql/01-ddl/03-table/ddl-rename-table.md
Add rename table
Fixes #issue
Unit Tests
> Doc: Add rename table

- docs/doc/03-reference/04-api/00-rest.md
- docs/doc/03-reference/04-api/_category_.yml
compare with the original doc:
1. refactored.
2. add the introduction of using session.
3. add details of `QueryRequest`.
4. remove contents about `/v1/statement`
Fixes #issue
> Add docs for http handler.

- .github/workflows/databend-release.yml
- docker/distroless/meta.Dockerfile
- docker/distroless/query.Dockerfile
Build distroless image for meta/query service
Fixes #issue
Unit Tests
> ci: build distroless image for meta/query service

- docs/doc/01-deploy/02-cos.md
- docs/doc/01-deploy/03-oss.md
- docs/doc/01-deploy/04-wasabi.md
- docs/doc/01-deploy/06-cluster-k8s-minio.md
- docs/doc/07-performance/01-local-vector-performance.md
- docs/doc/07-performance/02-ec2-s3-performance.md
- docs/doc/07-performance/03-ec2-wasabi-performance.md
- docs/doc/07-performance/04-cvm-cos-performance.md
- docs/doc/09-learn/01-analyze-github-repo-with-databend.md
- docs/doc/09-learn/02-analyze-ontime-with-databend-on-ec2-and-s3.md
Refine the context
Fixes #issue
Unit Tests
> doc(performance): Refine the context

- scripts/setup/dev_setup.sh
support alpine linux for dev setup script
for: https://github.com/datafuselabs/databend/issues/3611
ref: https://github.com/datafuselabs/databend/pull/4536
Unit Tests
> chore: support apk for dev setup

- docs/doc/01-deploy/07-scw.md
- docs/doc/07-performance/07-scw-os-performance.md
- docs/doc/09-learn/02-analyze-ontime-with-databend-on-ec2-and-s3.md
add scaleway os deploy
Fixes #issue
Unit Tests
> doc(deploy): add scaleway os deploy

- .github/workflows/platform.yml
- scripts/setup/dev_setup.sh
fix missing checkout in platform workflow
Fixes #issue
Unit Tests
> ci: fix missing checkout in platform workflow

- docs/doc/07-performance/07-scw-os-performance.md
Scaleway performance test update
Fixes #issue
Unit Tests
> doc(scaleway): partitioning improvements

- query/src/interpreters/interpreter_copy.rs
after make it panic at `Progress.incr()`, I guess it AsyncSourcer already counts the scan rows.
```
55    8: common_base::progress::Progress::incr
56              at common/base/src/progress.rs:50:9
57    9: <databend_query::pipelines::new::processors::sources::async_source::AsyncSourcer<T> as databend_query::pipelines::new::processors::processor::Processor>::async_process::{{closure}}
58              at query/src/pipelines/new/processors/sources/async_source.rs:103:17
59   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
```
AsyncSourcer already counts the scan rows.
https://github.com/datafuselabs/databend/blob/4bcd94d46e22b10d93e62ed2a5ab4c66550d40e8/query/src …
> Fix duplicate count read rows

- docker/build-tool/alpine/Dockerfile
- docker/build-tool/debian/Dockerfile
- scripts/setup/dev_setup.sh
fix build tool dockerfile
Fixes [#4589](https://github.com/datafuselabs/databend/pull/4589#issuecomment-1079891857)
Unit Tests
> chore: fix install cargo-audit in alpine

- common/streams/src/sources/source_ndjson.rs
- query/src/servers/http/v1/load.rs
- Bug Fix
Fixes #issue
Unit Tests
> feat(stream): use async read_line in ndjson source

- website/docusaurus.config.js
- website/src/pages/index.tsx
doc(title): activate your Object Storage for sub-second analytics
Fixes #issue
Unit Tests
> doc(title): activate your Object Storage for sub-second analytics

- .github/workflows/databend-release.yml
- .github/workflows/platform.yml
- docker/build-tool/alpine/Dockerfile
- docker/build-tool/debian/Dockerfile
- docs/doc/06-contributing/01-building-from-source.md
- scripts/setup/cross_setup.sh
- scripts/setup/dev_setup.sh
- scripts/setup/run_build_tool.sh
separate build/dev docker build tools, add instructions for docker build usage
Fixes #issue
Unit Tests
> chore: separate build/dev docker tools

- common/functions/src/scalars/hashes/city64_with_seed.rs
- docs/doc/10-faq/06-how-to-write-scalar-functions.md
- docs/doc/10-faq/07-how-to-write-aggregate-functions.md
- Improvement
Fixes #issue
Unit Tests
> feat(docs): update how-to-writer-xxx-functions docs

- .github/workflows/platform.yml
- docker/build-tool/alpine/Dockerfile
- docker/build-tool/debian/Dockerfile
- scripts/setup/dev_setup.sh
- scripts/setup/run_build_tool.sh
* fix: merge operation tools to dev
* fix: condition for build multiarch image
* fix: change cargo home in container
* feat: support bypass env vars for build tool
* fix: set TERM for interactive build tool
for #4592
Unit Tests
> chore: merge operation tools to dev docker image

- Cargo.lock
- common/streams/src/sources/source_ndjson.rs
- query/Cargo.toml
- query/src/servers/http/clickhouse_handler.rs
- query/src/servers/http/v1/middleware.rs
- query/tests/it/servers/http/clickhouse_handler.rs
1.   better error message for NDJson,  show types.
2.  log HTTP handler requests (without the body, enough most time)
3.  clickhouse rest api support compression.
Fixes https://github.com/datafuselabs/databend/issues/4622
Unit Tests
> polish(clickhouse rest api):  error message, log and compression

- query/src/pipelines/new/executor/mod.rs
- query/src/pipelines/new/executor/pipeline_complete_executor.rs
- query/src/pipelines/new/executor/pipeline_pulling_executor.rs
- query/src/pipelines/new/executor/pipeline_pushing_executor.rs
feat(processor): support complete executor
- New Feature
part https://github.com/datafuselabs/databend/issues/3379
Unit Tests
> feat(processor): support complete executor

- website/docusaurus.config.js
- website/package.json
- website/yarn.lock
upgrade docusaurus and refine the footer
Fixes #issue
Unit Tests
> doc(website): upgrade docusaurus and refine the footer

- .github/workflows/databend-release.yml
- .gitignore
- docker/debian/meta.Dockerfile
- docker/debian/query.Dockerfile
- docker/distroless/meta.Dockerfile
- docker/distroless/query.Dockerfile
- scripts/build/build-k8s-runner.sh
* add missing docker login for image push
* make distroless image working
Fixes #issue
Unit Tests
> chore(ci): better build k8s runner images

- query/src/storages/fuse/io/write/block_writer.rs
Disable parquet statistics. 
- issue #4633  
- Improvement
Fixes #4633
Unit Tests
> ISSUE-4633:  disable parquet statistics generation

- query/src/pipelines/new/processors/resize_processor.rs
if a == b { b = a } ???
- Improvement
Fixes #issue
Unit Tests
> Remove ineffectual assignments

- README.md
- docs/doc/00-about/index.md
refine the readme
Fixes #issue
Unit Tests
> chore(doc): refine the readme

- docs/doc/01-deploy/00-local.md
- docs/doc/01-deploy/01-s3.md
- docs/doc/01-deploy/02-cos.md
- docs/doc/01-deploy/03-oss.md
- docs/doc/01-deploy/04-minio.md
- docs/doc/01-deploy/05-wasabi.md
- docs/doc/01-deploy/06-scw.md
- docs/doc/08-releases/v0.7.0.md
update binary to musl for deploy
Fixes #issue
Unit Tests
> chore(doc): update binary to musl for deploy

- docs/doc/09-learn/03-analyze-nginx-logs-with-databend-and-vector.md
add more comments for nginx access logs analyzing
Fixes #issue
Unit Tests
> chore(doc): add more comments for nginx access logs analyzing

- docs/doc/03-reference/00-api/00-rest.md
- docs/doc/03-reference/00-api/01-put-to-stage.md
- docs/doc/03-reference/03-sql/02-dml/dml-copy.md
* add copy from named stage
* add put to stage api
Fixes #issue
Unit Tests
> chore(doc): add copy from named stage

- docs/doc/20-develop/00-golang.md
- docs/doc/20-develop/02-nodejs.md
add node.js to develop
Fixes #issue
Unit Tests
> feat(doc): add node.js to develop

- docs/doc/30-reference/20-functions/110-semi-structured-functions/check_json.md
add `check_json` docs
Fixes #issue
> feat(doc): add check_json docs

- README.md
- docs/doc/00-overview/index.md
- docs/doc/30-reference/00-api/02-clickhouse-handler.md
- docs/doc/60-contributing/01-good-pr.md
better community and API 
Fixes #issue
> chore(doc): better community and API 

- docs/doc/30-reference/00-api/02-clickhouse-handler.md
add databend clickhouse http handler auth
Fixes #issue
> chore(doc): add databend clickhouse http handler auth

- docs/doc/10-deploy/00-local.md
- docs/doc/10-deploy/01-s3.md
- docs/doc/10-deploy/02-cos.md
- docs/doc/10-deploy/03-oss.md
- docs/doc/10-deploy/04-minio.md
- docs/doc/10-deploy/05-wasabi.md
- docs/doc/10-deploy/06-scw.md
> chore(doc): bump to 0.7.9

- .github/workflows/databend-release.yml
fix macos cross aarch64 release build for M1
ref: https://github.com/gnzlbg/jemallocator/blob/master/jemalloc-sys/README.md#environment-variables
Fixes #4719
> fix(ci): add jemalloc page size option for macos cross build

- .github/mergify.yml
Fix PR got merged even when tests are broken
> ci: Fix mergify status check

- query/src/servers/mysql/mysql_interactive_worker.rs
> query(mysql): disable read only mode

- common/contexts/src/dal/dal_context.rs
- common/contexts/src/dal/dal_runtime.rs
Fix https://github.com/datafuselabs/databend/issues/4741
- Improvement
> refactor(contexts): Improve logic for getting inner Accessor

- README.md
- docs/doc/00-overview/index.md
- docs/doc/60-contributing/02-benchmarking.md
- docs/doc/60-contributing/02-roadmap.md
feat(doc): add continuous benchmarking
Fixes #issue
> feat(doc): add continuous benchmarking

- README.md
- docs/doc/00-overview/index.md
> chore(doc): readme

- Cargo.lock
- common/contexts/Cargo.toml
- common/io/Cargo.toml
- common/streams/Cargo.toml
- query/Cargo.toml
Release note of opendal v0.5.2: https://github.com/datafuselabs/opendal/discussions/245
Fix https://github.com/datafuselabs/databend/issues/4759
- Bug Fix
> fix(query): Fix support for endpoint without scheme

- .github/workflows/databend-release.yml
Number of commits to fetch. 0 indicates all history for all branches and tags.
I think it will fix #4300
> chore(ci): try keep git history

- docs/doc/90-learn/02-analyze-nginx-logs-with-databend-and-vector.md
change nginx access log format to raw
Fixes #issue
> chore(doc): change nginx access log format to raw

- scripts/setup/dev_setup.sh
add sqlalchemy & pymysql to dev_setup
For: #4774
> chore(ci): add sqlalchemy & pymysql to dev_setup

- README.md
- docs/doc/30-reference/10-data-types/10-data-type-numeric-types.md
- docs/doc/30-reference/10-data-types/11-data-type-real-number.md
- docs/doc/30-reference/10-data-types/20-data-type-time-date-types.md
- docs/doc/30-reference/10-data-types/30-data-type-string-types.md
- docs/doc/30-reference/10-data-types/40-data-type-semi-structured-types.md
- docs/doc/30-reference/30-sql/00-ddl/20-table/ddl-create-table.md
merge float and int to one and add examples for semi-structured type
Fixes #issue
> chore(doc): merge float and int to one and add examples for semi-structured type

- README.md
- docs/doc/00-overview/index.md
- docs/doc/30-reference/10-data-types/40-data-type-semi-structured-types.md
add type casting for variant
Fixes #issue
> chore(doc): add type casting for variant

- docs/doc/20-develop/01-python.md
- docs/doc/30-reference/30-sql/00-ddl/30-user/01-user-create-user.md
add create user for deploy
Fixes #issue
> chore(doc): add create user for deploy

- common/ast/Cargo.toml
- common/functions/Cargo.toml
- common/functions/src/rdoc/function_docs.rs
- common/functions/src/scalars/strings/substring_index.rs
- common/macros/Cargo.toml
- common/metrics/Cargo.toml
- common/tracing/Cargo.toml
- metasrv/Cargo.toml
- query/src/pipelines/new/executor/pipeline_executor.rs
- query/src/pipelines/new/pipeline.rs
- query/src/sql/statements/query/query_normalizer.rs
- query/tests/it/sql/plan_parser.rs
- tests/suites/0_stateless/00_dummy/00_0000_dummy_select_1.sql
- tools/fuzz/Cargo.toml
- fix `select *`
- fix nightly clippy
- Bug Fix
Fixes #4728
> fix: `select *` shouldn't return results

- common/streams/src/sources/source_ndjson.rs
- common/streams/tests/it/sources/source_ndjson.rs
- query/src/servers/http/clickhouse_handler.rs
- query/src/servers/http/v1/load.rs
- query/src/storages/s3/s3_stage_source.rs
https://github.com/datafuselabs/databend/issues/4527#issue-1175166779
- Support json format for copy into statement.
Closes #4527
> feat: support json format for copy

- query/src/servers/mysql/mysql_federated.rs
- query/src/servers/mysql/mysql_interactive_worker.rs
add more federated command for some old drivers
- Improvement
Fixes #4803
> chore(mysql): add more federated command for some old drivers

- docs/doc/30-reference/30-sql/00-ddl/30-user/01-user-create-user.md
- docs/doc/30-reference/30-sql/00-ddl/30-user/02-user-drop-user.md
- docs/doc/30-reference/30-sql/00-ddl/30-user/03-user-alter-user.md
- docs/doc/30-reference/30-sql/00-ddl/30-user/04-user-create-role.md
- docs/doc/30-reference/30-sql/00-ddl/30-user/05-user-drop-role.md
- docs/doc/30-reference/30-sql/00-ddl/30-user/10-grant-privileges.md
- docs/doc/30-reference/30-sql/00-ddl/30-user/11-revoke-privileges.md
- docs/doc/30-reference/30-sql/00-ddl/30-user/20-grant-role.md
- docs/doc/30-reference/30-sql/00-ddl/30-user/21-revoke-role.md
add user/role grant and revoke
Fixes #issue
> chore(doc): add user/role grant and revoke

- query/src/servers/mysql/mysql_federated.rs
fix sqlalchemy <  1.4.30
- Improvement
Fixes #4803
> chore(mysql): fix sqlalchemy <  1.4.30

- docs/doc/20-develop/00-golang.md
- docs/doc/20-develop/01-python.md
- docs/doc/20-develop/02-nodejs.md
add create user to develop example
Fixes #issue
> chore(doc): add create user to develop example

- query/src/sql/statements/statement_create_database.rs
- tests/suites/0_stateless/05_ddl/05_0001_ddl_create_database.sql
create database db.t should fail.
- Bug Fix
Fixes #4832
> fix create database db.t not fail

- docs/doc/40-integrations/10-data-tool/00-vector.md
- docs/doc/40-integrations/20-gui-tool/00-jupyter.md
- docs/doc/40-integrations/20-gui-tool/01-dbeaver.md
add DBeaver gui tool
Fixes #issue
> chore(doc): add DBeaver gui tool

- Cargo.lock
- common/planners/Cargo.toml
- common/planners/src/plan_node_s3_stage_table.rs
- query/src/interpreters/interpreter_copy.rs
- query/src/sql/statements/statement_copy.rs
- query/src/storages/s3/s3_stage_source.rs
- query/src/storages/s3/s3_stage_table.rs
Change copy read files parallel.
Fixes #4308
> Change copy read files parallel.

- Makefile
Remove stateless test data dir
Fixes #4867
> Remove stateless test data dir

- common/meta/types/src/role_info.rs
- common/meta/types/src/user_grant.rs
- common/meta/types/src/user_info.rs
- query/src/interpreters/interpreter_show_grants.rs
- query/src/sessions/session.rs
- query/src/users/role_cache_mgr.rs
- query/tests/it/interpreters/interpreter_show_grant.rs
- query/tests/it/interpreters/mod.rs
- query/tests/it/users/role_cache_mgr.rs
Fix show grants from inherited role
- Bug Fix
Fixes https://github.com/datafuselabs/databend/issues/4815
> Fix show grants from inherited role

- Cargo.lock
- common/ast/Cargo.toml
- common/exception/Cargo.toml
- common/functions/Cargo.toml
- docs/doc/30-reference/10-data-types/10-data-type-numeric-types.md
- docs/doc/30-reference/10-data-types/20-data-type-time-date-types.md
- docs/doc/30-reference/10-data-types/30-data-type-string-types.md
- docs/doc/30-reference/10-data-types/31-data-type-logical-types.md
- docs/doc/30-reference/10-data-types/40-data-type-semi-structured-types.md
- docs/doc/30-reference/10-data-types/_category_.json
- docs/doc/30-reference/10-data-types/index.md
- query/Cargo.toml
- query/src/sql/sql_common.rs
- tests/suites/0_stateless/05_ddl/05_0000_ddl_create_tables.result
- tests/suites/0_stateless/05_ddl/05_0000_ddl_create_tables.sql
- tests/suites/0_stateless/09_fuse_engine/09_0001_remote_insert.sql
make data type syntax standardization:
1. numeric data type
2. date & time data type
3. boolean type
4. varchar type
- Improvement
Fixes #4877
> chore(data type): make data type syntax standardization

- docs/doc/30-reference/10-data-types/00-data-type-logical-types.md
- docs/doc/30-reference/10-data-types/10-data-type-numeric-types.md
- docs/doc/30-reference/10-data-types/20-data-type-time-date-types.md
- docs/doc/30-reference/10-data-types/30-data-type-string-types.md
- docs/doc/30-reference/10-data-types/40-data-type-semi-structured-types.md
- docs/doc/30-reference/10-data-types/index.md
- docs/doc/30-reference/20-functions/30-datetime-functions/_category_.json
refine the data type
Fixes #issue
> chore(doc): refine the data type

- docs/doc/30-reference/10-data-types/00-data-type-logical-types.md
- docs/doc/30-reference/10-data-types/10-data-type-numeric-types.md
- docs/doc/30-reference/10-data-types/20-data-type-time-date-types.md
- docs/doc/30-reference/10-data-types/30-data-type-string-types.md
- docs/doc/30-reference/10-data-types/40-data-type-semi-structured-types.md
- docs/doc/30-reference/10-data-types/index.md
add more details of semi-structured data types
Fixes #issue
> chore(doc): add more details of semi-structured data types

- docs/doc/30-reference/10-data-types/00-data-type-logical-types.md
- docs/doc/30-reference/10-data-types/10-data-type-numeric-types.md
- docs/doc/30-reference/10-data-types/20-data-type-time-date-types.md
- docs/doc/30-reference/10-data-types/index.md
- docs/doc/30-reference/20-functions/110-semi-structured-functions/check_json.md
- docs/doc/30-reference/20-functions/110-semi-structured-functions/get.md
- docs/doc/30-reference/20-functions/110-semi-structured-functions/get_ignore_case.md
- docs/doc/30-reference/20-functions/110-semi-structured-functions/get_path.md
- docs/doc/30-reference/20-functions/110-semi-structured-functions/parse_json.md
refine the semi-strucutred functions
Fixes #issue
> chore(doc): refine the semi-strucutred functions

- common/management/src/udf/udf_mgr.rs
- common/management/tests/it/udf.rs
- query/tests/it/sql/plan_parser.rs
Refine unknown udf error msg
- Improvement
Fixes #4836
> Refine unknown udf error msg

- docs/doc/50-operations/metasrv-add-remove-node.md
- docs/doc/50-operations/metasrv-backup-restore.md
- docs/doc/50-operations/metasrv-deploy.md
- docs/doc/50-operations/metasrv-upgrade.md
Explains how to deploy databend-meta cluster in standalone mode or
cluster mode.
With several minor refactor.
- part of #4920
> [metasrv] doc: add operations/deploy.md

- query/src/pipelines/new/executor/executor_graph.rs
fixes(processor): temp remove rwlock
Fixes #4942
> fixes(processor): temp remove rwlock

- docs/doc/50-operations/00-metasrv/10-metasrv-deploy.md
- docs/doc/50-operations/00-metasrv/20-metasrv-add-remove-node.md
- docs/doc/50-operations/00-metasrv/30-metasrv-upgrade.md
- docs/doc/50-operations/00-metasrv/40-metasrv-backup-restore.md
- docs/doc/50-operations/00-metasrv/_category_.json
- docs/doc/50-operations/10-admin/_category_.json
move meta service to metasrv dir
Fixes #issue
> chore(doc): move meta service to metasrv dir

- query/src/pipelines/new/processors/sources/async_source.rs
- query/src/storages/s3/s3_stage_source.rs
- tests/helpers/native_client.py
- tests/helpers/uexpect.py
- tests/suites/1_stateful/00_copy/00_0000_copy_from_stage2.py
1. Fix `StageSource` generate
2. Introduce `NativeClient` to testing infra, thus we can pass context settings among the test lifetime.
- Bug Fix
- Build/Testing/CI 
Fixes #4953
> feat(tests): add native mysql client uexpect

- query/src/servers/clickhouse/interactive_worker.rs
- query/src/servers/http/clickhouse_handler.rs
- query/src/servers/http/middleware.rs
- query/src/servers/http/v1/http_query_handlers.rs
- query/src/servers/http/v1/load.rs
- query/src/servers/http/v1/mod.rs
- query/src/servers/http/v1/query/http_query.rs
- query/src/servers/http/v1/query/http_query_context.rs
- query/src/servers/http/v1/query/http_query_manager.rs
- query/src/servers/http/v1/query/mod.rs
- query/src/servers/http/v1/stage.rs
- query/src/servers/http/v1/statement.rs
- query/src/sessions/query_ctx_shared.rs
- query/src/sessions/session.rs
- query/src/sessions/session_ctx.rs
- query/src/sessions/session_settings.rs
- query/src/users/auth/auth_mgr.rs
- query/src/users/auth/jwt/authenticator.rs
- query/tests/it/servers/http/http_query_handlers.rs
- query/tests/it/sessions/session.rs
- query/tests/it/users/auth/auth_mgr.rs
Introduce tenant_id in JWT CustomClaims
- Improvement
Fixes https://github.com/datafuselabs/databend/issues/4936
> improvement: introduce tenant_id in JWT CustomClaims

- docker/debian/meta.Dockerfile
- docker/debian/query.Dockerfile
tiny improve: to reduce docker image size
> chore(docker): tiny improve, reduce docker image size

- common/functions/src/scalars/semi_structureds/get.rs
- common/functions/src/scalars/semi_structureds/json_extract_path_text.rs
- common/functions/src/scalars/semi_structureds/mod.rs
- common/functions/src/scalars/semi_structureds/semi_structured.rs
- common/functions/tests/it/scalars/semi_structureds/json_extract_path_text.rs
- docs/doc/30-reference/20-functions/110-semi-structured-functions/json_extract_path_text.md
- tests/suites/0_stateless/02_function/02_0051_function_semi_structureds_get.result
- tests/suites/0_stateless/02_function/02_0051_function_semi_structureds_get.sql
Support `JSON_EXTRACT_PATH_TEXT` function
- New Feature
Fixes #4559
> feat(function): Support Semi-structured function json_extract_path_text

- query/src/pipelines/new/executor/executor_graph.rs
- query/src/pipelines/new/processors/port_trigger.rs
refactor(processor): replace panic with result
add error info for #4993
> refactor(processor): replace panic with result

- tests/poetry.lock
- tests/pyproject.toml
This PR updates poetry.lock to reflect new deps.
- Bug Fix
> fix: Poetry in tests not updated

- query/src/pipelines/transforms/group_by/aggregator.rs
refactor(stream): remove ptr_arg and useless comment
#5028
> refactor(stream): remove ptr_arg and useless comment

- query/src/pipelines/transforms/group_by/aggregator.rs
refactor(stream): remove obsolete comments
#5032
> refactor(stream): remove obsolete comments

- query/src/sessions/query_ctx_shared.rs
- query/src/sql/sql_common.rs
> feat(query): attach short sql in context

- Cargo.lock
- query/src/interpreters/interpreter_factory_interceptor.rs
- query/src/interpreters/interpreter_query_log.rs
- query/src/servers/clickhouse/interactive_worker_base.rs
- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/mysql/mysql_interactive_worker.rs
- query/tests/it/servers/http/http_query_handlers.rs
record parse errors.
execute error was done in https://github.com/datafuselabs/databend/pull/5057
part of https://github.com/datafuselabs/databend/issues/4876
> feat(query_log): record parse errors.

- docs/doc/50-operations/00-metasrv/10-metasrv-deploy.md
- docs/doc/50-operations/00-metasrv/15-metasrv-config.md
- docs/doc/50-operations/00-metasrv/20-metasrv-add-remove-node.md
- docs/doc/50-operations/00-metasrv/30-metasrv-backup-restore.md
- docs/doc/50-operations/00-metasrv/40-metasrv-upgrade.md
- docs/doc/50-operations/00-metasrv/_category_.json
- docs/doc/50-operations/10-backup-restore/10-backup-and-restore-schema.md
- docs/doc/50-operations/10-backup-restore/_category_.json
Better title for metasrv and add backup/restore using mydumper
Fixes #issue
> chore(doc): Better title for metasrv and add backup/restore using mydumper

- Cargo.lock
- query/Cargo.toml
- query/src/sql/exec/mod.rs
- query/src/sql/exec/util.rs
- query/src/sql/optimizer/cascades/mod.rs
- query/src/sql/optimizer/heuristic/mod.rs
- query/src/sql/optimizer/m_expr.rs
- query/src/sql/optimizer/pattern_extractor.rs
- query/src/sql/optimizer/rule/rule_implement_get.rs
- query/src/sql/optimizer/s_expr.rs
- query/src/sql/planner/binder/project.rs
- query/src/sql/planner/binder/select.rs
- query/src/sql/planner/plans/mod.rs
- query/tests/it/sql/optimizer/pattern_extractor.rs
> feat(plan): add enum-dispatch support to BasePlan to avoid downcast_ref

- scripts/setup/dev_setup.sh
add "instal_pgk thrift" to dev_setup.sh
> build(dev_setup): add "instal_pgk thrift" to dev_setup.sh

- scripts/setup/dev_setup.sh
This reverts commit 6d7fbcb963cf08e4212e4f630cae463173d873cf.
- Bug Fix
> hotfix(build): Revert "feat: add "instal_pgk thrift" to dev_setup.sh"

- common/functions/tests/it/scalars/dates/interval_function.rs
Signed-off-by: Veeupup <code@tanweime.com>
flaky test
- Bug Fix
Fixes #5093
> bug: fix interval_function flaky test

- scripts/setup/dev_setup.sh
> feat(build): add thrift to dev setup

- common/meta/api/src/kv_api_test_suite.rs
- common/meta/raft-store/src/state_machine/sm.rs
> [metasrv] Fix: in a txn, absent record by default has seq=0, and should be compared

- docs/doc/01-guides/_category_.json
- docs/doc/01-guides/index.md
- docs/doc/10-deploy/00-local.md
- docs/doc/10-deploy/10-cluster-minio.md
- docs/doc/10-deploy/11-cluster-k8s-minio.md
- docs/doc/100-faq/60-how-to-benchmark-with-hyperfine.md
- docs/doc/20-develop/00-golang.md
- docs/doc/20-develop/01-python.md
- docs/doc/20-develop/02-nodejs.md
- docs/doc/21-load-data/00-local.md
- docs/doc/21-load-data/01-s3.md
- docs/doc/21-load-data/02-stage.md
- docs/doc/21-load-data/03-mysql.md
- docs/doc/30-reference/00-api/01-mysql-handler.md
- docs/doc/30-reference/30-sql/00-ddl/30-user/10-grant-privileges.md
- docs/doc/30-reference/30-sql/00-ddl/30-user/20-grant-role.md
- docs/doc/40-integrations/10-data-tool/00-vector.md
- docs/doc/40-integrations/20-gui-tool/00-jupyter.md
- docs/doc/40-integrations/20-gui-tool/01-dbeaver.md
- docs/doc/60-contributing/00-building-from-source.md
- docs/doc/60-contributing/01-good-pr.md
- docs/doc/70-performance/01-ec2-s3-performance.md
- docs/doc/70-performance/02-cvm-cos-performance.md
- docs/doc/70-performance/03-ecs-oss-performance.md
- docs/doc/70-performance/04-ec2-wasabi-performance.md
- docs/doc/70-performance/05-scw-os-performance.md
- docs/doc/70-performance/06-qingcloud-qingstore-performance.md
- docs/doc/90-learn/00-analyze-github-repo-with-databend.md
- docs/doc/90-learn/01-analyze-ontime-with-databend-on-ec2-and-s3.md
- docs/doc/90-learn/02-analyze-nginx-logs-with-databend-and-vector.md
add how-to guides page
Fixes #issue
> chore(doc): add how-to guides page

- common/datablocks/src/data_block.rs
- common/datablocks/src/kernels/data_block_gather.rs
- common/datablocks/src/kernels/mod.rs
- common/datablocks/tests/it/kernels/data_block_gather.rs
- common/datablocks/tests/it/kernels/mod.rs
> feature(datablocks): add gather kernels for datablock

- common/functions/src/scalars/comparisons/comparison.rs
- common/functions/src/scalars/conditionals/if.rs
- common/functions/src/scalars/conditionals/in_basic.rs
- common/functions/src/scalars/dates/number_function.rs
- common/functions/src/scalars/expressions/cast.rs
- common/functions/src/scalars/expressions/cast_with_type.rs
- common/functions/src/scalars/expressions/expression.rs
- common/functions/src/scalars/function_monotonic.rs
- common/functions/src/scalars/hashes/city64_with_seed.rs
- common/functions/src/scalars/hashes/sha2hash.rs
- common/functions/src/scalars/logics/macros.rs
- common/functions/src/scalars/logics/not.rs
- common/functions/src/scalars/logics/xor.rs
- common/functions/src/scalars/strings/bin.rs
- common/functions/src/scalars/strings/hex.rs
- common/functions/src/scalars/strings/oct.rs
- common/functions/src/scalars/strings/regexp_instr.rs
- common/functions/src/scalars/strings/regexp_replace.rs
- common/functions/src/scalars/strings/regexp_substr.rs
- common/functions/src/scalars/strings/repeat.rs
- common/functions/src/scalars/strings/substring.rs
- common/functions/src/scalars/strings/substring_index.rs
- common/functions/tests/it/scalars/expressions.rs
- common/planners/src/plan_expression_chain.rs
- common/streams/tests/it/stream_cast.rs
- query/src/common/expression_evaluator.rs
- query/src/interpreters/interpreter_insert.rs
- query/src/pipelines/transforms/transform_sink.rs
Signed-off-by: leiysky <leiysky@outlook.com>
Add `from_type` for `CastFunction`.
- Improvement
Fixes #5123
> improve(function): Specialize `CastFunction` with from type

- common/functions/src/scalars/dates/number_function.rs
Signed-off-by: leiysky <leiysky@outlook.com>
- Improvement
> improve(function): Specialize `NumberFunction` with input type

- common/ast/src/udfs/udf_expr_visitor.rs
- query/src/sql/statements/analyzer_expr.rs
- tests/suites/0_stateless/02_function/02_0055_function_strings_trim.result
- tests/suites/0_stateless/02_function/02_0055_function_strings_trim.sql
Fix trim function not work. 
- Bug Fix
Fixes #5122
> fix: fix trim

- Cargo.lock
- common/meta/grpc/Cargo.toml
- common/meta/grpc/src/grpc_client.rs
- common/meta/grpc/src/lib.rs
- common/meta/grpc/src/meta_client_on_kv.rs
- common/meta/grpc/src/meta_client_on_kv_impl.rs
- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/types/src/database.rs
- common/meta/types/src/lib.rs
- common/meta/types/src/message.rs
- common/meta/types/src/proto_display.rs
- metasrv/src/meta_service/meta_leader.rs
- metasrv/src/meta_service/meta_node_kv_api_impl.rs
- metasrv/tests/it/grpc/metasrv_grpc_meta_api_on_kv.rs
- metasrv/tests/it/grpc/mod.rs
> [common/meta] impl create-db with protobuf and kv-txn API

- Cargo.lock
- common/meta/api/src/meta_api_test_suite.rs
- common/meta/grpc/Cargo.toml
- common/meta/grpc/src/lib.rs
- common/meta/grpc/src/meta_client_on_kv.rs
- common/meta/grpc/src/meta_client_on_kv_impl.rs
- metasrv/tests/it/grpc/metasrv_grpc_meta_api_on_kv.rs
Add several asssertion to list-db test.
KVApiKey provides deserializing key into structure KVApi key
> [metasrv] impl list-db with kv and txn

- common/meta/api/src/meta_api_test_suite.rs
- common/meta/embedded/tests/it/meta_api_impl.rs
- common/meta/grpc/src/meta_client_on_kv.rs
- common/meta/grpc/src/meta_client_on_kv_impl.rs
- common/meta/raft-store/tests/it/state_machine/meta_api_impl.rs
- common/meta/types/src/database.rs
- common/meta/types/src/lib.rs
- common/meta/types/src/table.rs
- metasrv/tests/it/grpc/metasrv_grpc_meta_api.rs
- metasrv/tests/it/grpc/metasrv_grpc_meta_api_on_kv.rs
- Move upsert_table_option test into standalone test
- fix: #5150
> [meta] impl create/get/drop table with kv-txn

- common/meta/api/src/meta_api_test_suite.rs
- common/meta/grpc/src/meta_client_on_kv_impl.rs
- metasrv/tests/it/grpc/metasrv_grpc_meta_api_on_kv.rs
> [metasrv] impl list-tables with kv-txn

- query/src/procedures/systems/fuse_segment.rs
- query/src/procedures/systems/mod.rs
- query/src/procedures/systems/system.rs
- query/src/storages/fuse/table_functions/fuse_segments/fuse_segment.rs
- query/src/storages/fuse/table_functions/fuse_segments/fuse_segment_table.rs
- query/src/storages/fuse/table_functions/fuse_segments/mod.rs
- query/src/storages/fuse/table_functions/fuse_segments/table_args.rs
- query/src/storages/fuse/table_functions/fuse_snapshots/fuse_snapshot_table.rs
- query/src/storages/fuse/table_functions/table_args.rs
- query/src/table_functions/table_function_factory.rs
- query/tests/it/storages/fuse/table_functions/fuse_snapshot_table.rs
- tests/suites/0_stateless/09_fuse_engine/09_0013_func_fuse_segement_function.result
- tests/suites/0_stateless/09_fuse_engine/09_0013_func_fuse_segement_function.sh
```
mysql>  call system$fuse_snapshot('default', 'test');
+----------------------------------+--------------------------------------------------+----------------+----------------------------------+---------------+-------------+-----------+--------------------+------------------+
| snapshot_id                      | snapshot_location                                | format_version | previous_snapshot_id             | segment_count | block_count | row_count | bytes_uncompressed | bytes_compressed |
+----------------------------------+--------------------------------------------------+----------------+----------------------------------+---------------+-------------+-----------+--------------------+----- …
```
> feat(fuse): add system$fuse_segment function

- common/meta/api/src/meta_api_test_suite.rs
- common/meta/grpc/src/meta_client_on_kv_impl.rs
- metasrv/tests/it/grpc/metasrv_grpc_meta_api_on_kv.rs
> [metasrv] impl rename-table with kv-txn

- common/meta/grpc/src/meta_client_on_kv_impl.rs
> [metasrv] refactor: remove specialized util methods, fix comments

- common/meta/api/src/meta_api_test_suite.rs
- common/meta/grpc/src/meta_client_on_kv_impl.rs
- metasrv/tests/it/grpc/metasrv_grpc_meta_api_on_kv.rs
Feature: impl upsert_table_option with kv-txn
- New Feature
Fixes [#issue](https://github.com/datafuselabs/databend/issues/5159)
> Feature: impl upsert_table_option with kv-txn

- common/meta/grpc/src/meta_client_on_kv_impl.rs
By updating the seq, a list-then-drop-all-table operation will be
blocked if new table are created just after listing-tables and before
deleting them.
This way an atomic drop-db-and-its-tables can be done.
- Fix: #5178
> [metasrv] create/drop/rename table has to update the seq of its belonging db.

- Cargo.lock
- common/contexts/Cargo.toml
- common/io/Cargo.toml
- common/streams/Cargo.toml
- query/Cargo.toml
- query/src/sessions/session_mgr.rs
Introduce opendal 0.6 and enable retry support
Part of #5215 
- New Feature
> feat: Introduce opendal 0.6 and enable retry support

- website/docusaurus.config.js
> chore(doc): add Continuous Benchmarking to menu

- common/ast/src/parser/error.rs
- common/ast/src/parser/statement.rs
- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/expr-error.txt
- common/ast/tests/it/testdata/query-error.txt
- common/ast/tests/it/testdata/statement-error.txt
- Bug Fix
Fixes https://github.com/datafuselabs/databend/pull/5230#issuecomment-1120383416
> fix(ast): improve helper message for error

- common/datavalues/src/types/deserializations/string.rs
fixes(format): fix string type csv truncate failure
- Bug Fix
Fixes #issue
> fixes(format): fix string type csv truncate failure

- scripts/setup/dev_setup.sh
feat(scripts/setup): Install jdk
Required by #5247 
> feat(scripts/setup): Install jdk

- query/src/servers/http/v1/load.rs
- query/src/servers/http/v1/multipart_format.rs
feat(format): add scan progress values
- Bug Fix
Fixes #issue
> feat(format): add scan progress values

- website/docusaurus.config.js
> docs: Update API key for algolia

- Cargo.lock
- common/hive-meta-store/Cargo.toml
- common/hive-meta-store/build.rs
- query/src/storages/fuse/fuse_table.rs
- query/src/storages/fuse/operations/commit.rs
- query/src/storages/fuse/table_functions/fuse_snapshots/fuse_snapshot_table.rs
- query/src/storages/memory/memory_table.rs
- query/src/storages/system/columns_table.rs
- query/src/storages/system/engines_table.rs
- query/src/storages/system/tables_table.rs
- query/tests/it/sql/statements/query/query_qualified_rewriter.rs
- clean up code
- during the building of crate `common-hive-meta-store`, if no `thrift` detected, give a meaningful message
- Improvement
> refine: of PR #4947 multi-catalog

- docs/doc/10-deploy/00-local.md
- docs/doc/10-deploy/01-s3.md
- docs/doc/10-deploy/02-cos.md
- docs/doc/10-deploy/03-oss.md
- docs/doc/10-deploy/04-minio.md
- docs/doc/10-deploy/05-wasabi.md
- docs/doc/10-deploy/06-scw.md
- docs/doc/10-deploy/07-qingstore.md
> chore(doc): musl -> gnu

- common/datavalues/src/types/deserializations/array.rs
- common/datavalues/src/types/deserializations/boolean.rs
- common/datavalues/src/types/deserializations/date.rs
- common/datavalues/src/types/deserializations/mod.rs
- common/datavalues/src/types/deserializations/null.rs
- common/datavalues/src/types/deserializations/nullable.rs
- common/datavalues/src/types/deserializations/number.rs
- common/datavalues/src/types/deserializations/string.rs
- common/datavalues/src/types/deserializations/timestamp.rs
- common/datavalues/src/types/deserializations/variant.rs
- common/io/src/buffer/checkpoint_reader.rs
- common/io/src/prelude.rs
- query/src/sql/statements/statement_insert.rs
- query/src/sql/statements/value_source.rs
- query/tests/it/sql/statements/value_source.rs
> chore(feature): refactor trait TypeDeserializer

- .github/actions/test_stateful_standalone/action.yml
- .github/actions/test_stateless_cluster_linux/action.yml
- .github/actions/test_stateless_cluster_macos/action.yml
- .github/actions/test_stateless_standalone_linux/action.yml
- .github/actions/test_stateless_standalone_macos/action.yml
- common/meta/api/src/schema_api_impl.rs
- common/meta/api/src/schema_api_test_suite.rs
> [meta/schema-api]: rename-table need to check table exist before returning OK

- common/meta/grpc/src/grpc_client.rs
Temporarily delete `todo` codes to fix panic bug
- Bug Fix
Fixes #issue
> Temporarily delete `todo` codes to fix panic bug

- scripts/setup/dev_setup.sh
> chore(doc): update dev_setup document

- .github/workflows/platform.yml
- scripts/setup/run_build_tool.sh
> fix(ci): docker image tag should not contain underscore

- .github/workflows/platform.yml
- docker/build-tool/dev/Dockerfile
- docker/build-tool/gnu/Dockerfile
- docker/build-tool/musl/Dockerfile
> fix(ci): typo for image & toolchain

- .github/workflows/build-tool.yml
- docker/build-tool/musl/musl.sh
> chore(ci): rename workflow platform to build-tool

- .github/actions/publish_image/action.yml
- .github/workflows/build-tool.yml
- .github/workflows/databend-release.yml
- docker/build-tool/musl/musl.sh
> chore(ci): upgrade build-push-action to v3 to support multiline tags

- .github/workflows/build-tool.yml
- docker/build-tool/dev/Dockerfile
- docker/build-tool/gnu/Dockerfile
- docker/build-tool/musl/Dockerfile
- scripts/setup/run_build_tool.sh
> fix(ci): docker build args

- .github/actions/setup_build_tool/action.yml
- .github/workflows/build-tool.yml
- docker/build-tool/musl/musl.sh
> fix(ci): docker build with multiple build args

- .github/workflows/build-tool.yml
- docker/build-tool/musl/Dockerfile
> fix(ci): add arg for dev & build context for musl

- .github/workflows/build-tool.yml
- docker/build-tool/base/Dockerfile
- docker/build-tool/dev/Dockerfile
> fix(ci): image tag typo & change build context

- .github/workflows/databend-release.yml
- docker/build-tool/base/Dockerfile
- docker/build-tool/gnu/Dockerfile
> fix(ci): clean release workflow & fix cargo config

- .github/workflows/databend-release.yml
> fix(ci): release build check rust flags

- docs/doc/10-deploy/00-local.md
- docs/doc/10-deploy/01-s3.md
- docs/doc/10-deploy/02-cos.md
- docs/doc/10-deploy/03-oss.md
- docs/doc/10-deploy/04-minio.md
- docs/doc/10-deploy/05-wasabi.md
- docs/doc/10-deploy/06-scw.md
- docs/doc/10-deploy/07-qingstore.md
> chore(doc): gnu -> musl

- docs/doc/10-deploy/08-azure.md
* Add azure blobl storage deploy
Fixes #issue
> chore(doc): add azure blob storage deploy

- README.md
- docs/doc/00-guides/index.md
* Add how to deploy azure blob storage to readme
Fixes #issue
> chore(readme): add how to deploy azure blob stroage

- .github/workflows/databend-release.yml
* remove redundent aws env
* fix copyobj on gnu
Fixes #issue
> fix(ci): copyobj on gnu

- docs/doc/10-deploy/08-azure.md
* remove root from query toml
Fixes #issue
> chore(doc): remove root from query toml

- README.md
- docs/doc/50-manage/01-query/10-query-config.md
- website/docusaurus.config.js
- website/src/pages/index.tsx
Add azblob config and title
Fixes #issue
> chore(doc): Add azblob config and title

- common/ast/src/ast/expr.rs
- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/statement.txt
- query/src/sql/planner/binder/limit.rs
- query/src/sql/planner/binder/project.rs
- query/src/sql/planner/metadata.rs
- query/src/sql/planner/semantic/type_check.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
- Support `MapAccess` to semi-structural data in the new planner.
- New Feature
Closes #5350
> feat(planner): support map access expression

- .github/workflows/databend-release.yml
> fix(ci): get release target

- query/src/storages/memory/memory_table.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
> bugfix(executor): Fix wrong result of memory table engine

- README.md
- docs/doc/00-overview/index.md
- website/docusaurus.config.js
- website/src/pages/index.tsx
> chore(doc): update readme

- docs/doc/90-learn/00-analyze-github-repo-with-databend.md
- docs/doc/90-learn/01-analyze-ontime-with-databend-on-ec2-and-s3.md
- docs/doc/90-learn/02-analyze-nginx-logs-with-databend-and-vector.md
> chore(doc): change the how to deploy for learn

- query/src/sql/planner/binder/aggregate.rs
- query/src/sql/planner/binder/join.rs
- query/src/sql/planner/binder/limit.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/binder/project.rs
- query/src/sql/planner/binder/select.rs
- query/src/sql/planner/binder/sort.rs
- query/src/sql/planner/semantic/type_check.rs
> chore(planner): Refine code structure

- docs/doc/30-reference/20-functions/10-aggregate-functions/aggregate-retention.md
> chore(doc): better retention example

- query/src/formats/format_csv.rs
- query/src/servers/http/v1/multipart_format.rs
fixes(format): fixes incorrect rows size for csv stream load
- Bug Fix
Fixes #issue
> fixes(format): fixes incorrect rows size for csv stream load

- README.md
- docs/doc/00-guides/index.md
- docs/doc/30-reference/20-functions/10-aggregate-functions/aggregate-retention.md
- docs/doc/90-learn/03-analyze-user-retention-with-databend.md
* Add user retention analysis to learn
Fixes #issue
> chore(doc): add user retention analysis to learn

- docs/doc/21-load-data/00-local.md
- docs/doc/21-load-data/02-stage.md
> doc add http  handler auth

- docs/doc/30-reference/20-functions/10-aggregate-functions/aggregate-windowfunnel.md
* Refine windows funnel
Fixes #issue
> chore(doc): windows funnel

- README.md
- docs/doc/00-guides/index.md
- docs/doc/90-learn/01-analyze-ontime-with-databend-on-ec2-and-s3.md
- docs/doc/90-learn/03-analyze-user-retention-with-databend.md
- docs/doc/90-learn/04-analyze-funnel-with-databend.md
* Add window funnel to learn
Fixes #issue
> chore(doc): add window funnel to learn

- docs/doc/50-manage/01-query/10-query-config.md
* Add endpoints configuration to query
Fixes #issue
> chore(doc): add endpoints configuration to query

- README.md
- docs/doc/00-guides/index.md
- docs/doc/90-learn/00-analyze-github-repo-with-databend.md
- docs/doc/90-learn/01-analyze-ontime-with-databend-on-ec2-and-s3.md
- docs/doc/90-learn/02-analyze-nginx-logs-with-databend-and-vector.md
- docs/doc/90-learn/03-analyze-user-retention-with-databend.md
- docs/doc/90-learn/04-analyze-funnel-with-databend.md
refine the user retention and funnel
Fixes #issue
> chore(doc): refine the user retention and funnel

- docs/doc/30-reference/20-functions/10-aggregate-functions/aggregate-windowfunnel.md
- docs/doc/90-learn/04-analyze-funnel-with-databend.md
> chore(doc): add funnel image

- common/exception/src/exception_code.rs
- query/src/pipelines/new/executor/executor_worker_context.rs
- query/src/table_functions/async_crash_me.rs
- query/src/table_functions/mod.rs
- query/src/table_functions/table_function_factory.rs
- tests/suites/0_stateless/20+_others/20_0003_async_crash_me_table.sql
fixes(processor): fix server hang when processor panic
- Bug Fix
Fixes #issue
> fixes(processor): fix server hang when processor panic

- Cargo.lock
- common/ast/Cargo.toml
- common/ast/src/ast/expr.rs
- common/ast/src/parser/expr.rs
- common/ast/src/udfs/udf_expr_visitor.rs
- common/datavalues/src/columns/builder.rs
- common/exception/Cargo.toml
- common/functions/Cargo.toml
- common/functions/src/scalars/conditionals/if.rs
- common/functions/src/scalars/semi_structureds/array_get.rs
- query/Cargo.toml
- tests/suites/0_stateless/02_function/02_0051_function_semi_structureds_get.result
- tests/suites/0_stateless/02_function/02_0051_function_semi_structureds_get.sql
map access support array and function
support empty array
- Improvement
Fixes #5305
> fix(function): map access support array and function

- query/src/pipelines/new/pipeline_builder.rs
- query/src/pipelines/new/processors/transforms/aggregator/aggregator_params.rs
- query/src/sql/exec/mod.rs
Delete redundancy code about `AggregatorParams`
- Improvement
Fixes #issue
> chore: delete redundancy code

- query/src/servers/clickhouse/interactive_worker_base.rs
fixes(handler): fix clickhouse handler dead loop when error
- Bug Fix
Fixes #5408
> fixes(handler): fix clickhouse handler dead loop when error

- query/src/interpreters/interpreter_insert.rs
chore(insert): add comment
https://github.com/datafuselabs/databend/pull/5424#discussion_r874522422
> chore(insert): add comment

- common/meta/grpc/src/grpc_client.rs
Remove unnecessary info log
- Improvement
Fixes #5444
> [Improving] remove unnecessary info log

- README.md
> docs: Add I'm feeling lucky

- tests/poetry.lock
- tests/pyproject.toml
Fix https://github.com/datafuselabs/databend/discussions/5469
> deps(tests): Fix toml is missing

- scripts/setup/rust-toolchain.toml
for: https://github.com/datafuselabs/databend/pull/5478
> chore: upgrade build toolchain to nightly-2022-05-19

- .github/actions/test_unit/action.yml
There was a change in tag on build tool dev image
for: https://github.com/datafuselabs/databend/pull/5478
> fix(ci): update unit test build tool image

- .github/workflows/projects.yml
ci: Add issues labeled `A-storage` into the storage project
Fixes #issue
> ci: Add issues labeled `A-storage` into storage project

- docs/doc/10-deploy/00-local.md
- docs/doc/10-deploy/01-s3.md
- docs/doc/10-deploy/02-cos.md
- docs/doc/10-deploy/03-oss.md
- docs/doc/10-deploy/04-minio.md
- docs/doc/10-deploy/05-wasabi.md
- docs/doc/10-deploy/06-scw.md
- docs/doc/10-deploy/07-qingstore.md
- docs/doc/10-deploy/08-azure.md
sql statement missing terminator
Fixes #issue
> doc(deploy): add sql statement terminator

- 文档/医生/30-参考/20 种功能/10 聚合函数/aggregate-avg-if.md
##Summary
Change the document function avgIf to avg_if
> Fix the documents avgIf to avg_if

- docs/doc/30-reference/20-functions/10-aggregate-functions/aggregate-avg-if.md
This PR reverts commit 635cb2ca2f733eb52b611ca81bc268df53d71bd1.
Fixes #5493
> docs: Revert changes introduced in #5493

- .github/workflows/developing.yml
- scripts/setup/rust-tools.txt
for: https://github.com/datafuselabs/databend/pull/5504
> chore: upgrade dev check tools

- .github/actions/check/action.yml
- Cargo.lock
- Makefile
- common/building/Cargo.toml
- common/building/src/git.rs
- common/building/src/lib.rs
Fixes: https://github.com/datafuselabs/databend/issues/5413
> chore: get building env with libgit2

- docs/doc/21-load-data/02-stage.md
fix stage.md typo: Books -> books
Fixes #issue
> chore(doc): fix stage.md typo

- query/src/servers/http/v1/json_block.rs
- query/src/servers/http/v1/query/execute_state.rs
- query/tests/it/servers/http/http_query_handlers.rs
- query/tests/it/servers/http/json_block.rs
> fix(httphandler): empty block and early return on fail 

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/developing.yml
- .licenserc.yaml
> chore: add devcontainer configs

- .github/crowdin.yml
- .github/workflows/i18n.yml
Part of https://github.com/datafuselabs/databend/issues/5542
> ci: Fix crowdin not configure correctly

- tests/suites/1_stateful/02_query/02_0000_kill_query.py
> fix flaky test

- query/src/servers/http/v1/http_query_handlers.rs
- query/tests/it/servers/http/http_query_handlers.rs
> feat(httphandler): support download with formats.

- common/meta/types/src/tenant_quota.rs
- query/src/interpreters/interpreter_user_stage_create.rs
- query/src/procedures/admins/tenant_quota.rs
- query/tests/it/interpreters/interpreter_call.rs
- query/tests/it/interpreters/interpreter_user_stage.rs
Add `max_stages` and `max_files_per_stage` in `TenantQuota`.
TODO
- check `max_files_per_stage` when upload file to stage
- Improvement
Fixes https://github.com/datafuselabs/databend/issues/5558
> add stage quota for tenant

- website/src/plugins/releaseVersion.jsx
> fix: copy bug

- docs/doc/30-reference/20-functions/10-aggregate-functions/aggregate-argmax.md
- docs/doc/30-reference/20-functions/10-aggregate-functions/aggregate-argmin.md
Updated description for ARG_MIN and ARG_MAX.
Fixes #issue
> documentation updates for aggregate functions

- Cargo.lock
- common/contexts/Cargo.toml
- common/io/Cargo.toml
- common/streams/Cargo.toml
- query/Cargo.toml
OpenDAL v0.6.3 will add the following improvements:
- feat(services/s3): Add retry in load_credential
- feat(services): Allow endpoint has trailing slash
- feat(services): Attach more context to error messages
- Bug Fix
> feat(query): Retry while meeting error during load_credential

- common/meta/api/src/schema_api_impl.rs
Feature: get_{db|table}_history ignore the data out of retention date(now use default retention time which is one day)
- New Feature
Fixes [#issue](https://github.com/datafuselabs/databend/issues/5596)
> Feature: get_{db|table}_history ignore the data out of retention date

- Cargo.lock
- tests/logictest/http_connector.py
- tests/logictest/logictest.py
- tools/metactl/Cargo.toml
- tools/metactl/src/main.rs
> [tools] metactl: add metasrv connecting bench cli command

- tests/suites/0_stateless/20+_others/20_0005_mysql_auth.py
> test(auth): add mysql auth stateless test.

- query/src/lib.rs
- query/src/sql/planner/semantic/type_check.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
as title
- New Feature
Fixes #5536
> feat(planner): support position function

- common/datavalues/src/types/type_factory.rs
- common/datavalues/src/types/type_null.rs
- common/datavalues/tests/it/columns/builder.rs
- common/functions/src/aggregates/adaptors/aggregate_null_adaptor.rs
- common/functions/src/scalars/conditionals/in_basic.rs
- common/functions/src/scalars/function_adapter.rs
- common/functions/src/scalars/semi_structureds/as_type.rs
- common/functions/src/scalars/semi_structureds/parse_json.rs
- common/functions/src/scalars/strings/concat_ws.rs
- common/functions/src/scalars/strings/elt.rs
- query/src/sql/planner/semantic/type_check.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
> improve(planner): Refine type checking of array expression

- query/src/sql/planner/binder/table.rs
- query/tests/it/servers/http/http_query_handlers.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
> feature(planner): Support read from view in new planner

- docs/doc/30-reference/30-sql/10-dml/dml-copy-into-location.md
Added the command COPY INTO <location>
Fixes #issue
> Documentation updates: unload into s3

- tests/compat/test-compat.sh
- fix permission error in #5655
> [ci] add exec permissionn to downloaded binaries

- query/src/procedures/systems/mod.rs
- query/src/procedures/systems/search_tables.rs
- query/src/procedures/systems/system.rs
- query/src/storages/system/tables_table.rs
Add call function `system$search_tables`
- New Feature
Fixes #issue
> add call function system$search_tables

- docs/doc/60-contributing/03-rfcs/20220530-user-friendly-releases.md
Releasing packages for different systems is unnecessary and can get trapped in other complications.
After a brief survey, we do not need to substantially change the existing release process. Just some additions needed.
[rendered](https://github.com/PsiACE/databend/blob/rfc-release/docs/doc/60-contributing/03-rfcs/20220530-user-friendly-releases.md)
cc @Xuanwo @wubx @soyeric128 for discussion
Related #5563
> RFC-5665: User Friendly Releases

- docs/doc/21-load-data/00-local.md
- docs/doc/21-load-data/01-s3.md
- docs/doc/30-reference/30-sql/10-dml/dml-copy-into-table.md
docs: Add compression related docs
> docs: Add compression related docs

- website/docusaurus.config.js
Let me test it first.
- Improvement
Fixes #5658
> feat: twitter card test

- common/ast/src/parser/statement.rs
- common/meta/types/src/user_auth.rs
- docs/doc/30-reference/30-sql/00-ddl/30-user/03-user-alter-user.md
- query/tests/it/interpreters/interpreter_privilege_grant.rs
- query/tests/it/interpreters/interpreter_privilege_revoke.rs
- query/tests/it/interpreters/interpreter_user_alter.rs
- query/tests/it/interpreters/interpreter_user_drop.rs
- query/tests/it/sql/parsers/parser_user.rs
- query/tests/it/storages/system/users_table.rs
- query/tests/it/users/user_mgr.rs
- tests/logictest/suites/gen/05_ddl/05_0004_ddl_create_user
- tests/logictest/suites/gen/05_ddl/05_0005_ddl_alter_user
- tests/logictest/suites/gen/05_ddl/05_0007_ddl_drop_user
- tests/suites/0_stateless/05_ddl/05_0004_ddl_create_user.sql
- tests/suites/0_stateless/05_ddl/05_0005_ddl_alter_user.sql
- tests/suites/0_stateless/05_ddl/05_0007_ddl_drop_user.sql
Remove plaintext password for safety.
- Improvement
Fixes https://github.com/datafuselabs/databend/issues/5612
> remove plaintext password

- .github/actions/publish_image/action.yml
>  Error: failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./databend-query": permission denied: unknown
ref: https://github.com/actions/upload-artifact/issues/38
- Bug Fix
Fixes #issue
> fix artifacts permissions

- docs/dev/30-subsystems/20-databend-meta/version.md
> [doc] explain when to upgrade versions for meta server and client

- .github/actions/publish_image/action.yml
> fix action missing shell

- Cargo.lock
- common/ast/Cargo.toml
- common/exception/Cargo.toml
- common/functions/Cargo.toml
- query/Cargo.toml
- tests/suites/1_stateful/00_copy/00_0000_copy_from_stage.result
- tests/suites/1_stateful/00_copy/00_0000_copy_from_stage.sh
> fix(query): fix AtString parser

- query/src/pipelines/new/processors/mod.rs
- query/src/pipelines/new/processors/transforms/hash_join/chaining_hash_table.rs
- query/src/pipelines/new/processors/transforms/hash_join/mod.rs
- query/src/pipelines/new/processors/transforms/hash_join/row.rs
- query/src/pipelines/new/processors/transforms/mod.rs
- query/src/sql/exec/mod.rs
As the title
- Improvement
Fixes https://github.com/datafuselabs/databend/issues/5598
> improve(planner): utilize with `HashMethodFixedKeys` in hash join

- README.md
- docker/README.md
Signed-off-by: Ryan Russell <git@ryanrussell.org>
Improves readability of `/docker/README.md`
> docs(docker): Improve docker/README.md Readability

- docs/doc/30-reference/30-sql/00-ddl/50-udf/ddl-create-function.md
* Add a complex example for UDF
Fixes #issue
> chore(doc): add a complex for UDF

- .github/actions/publish_binary/action.yml
> fix(ci): publish binary fetch tags with token

- common/meta/raft-store/src/config.rs
- metasrv/src/configs/outer_v0.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/tests/it/configs.rs
> Add cluster name to metasrv and meta-client

- query/src/procedures/admins/tenant_quota.rs
- query/tests/it/interpreters/interpreter_call.rs
Show tenant quota for current tenant.
- Improvement
Fixes #issue
> show tenant quota for current tenant

- metasrv/src/meta_service/raftmeta.rs
- metasrv/tests/it/meta_node/meta_node_all.rs
- New Feature
- Bug Fix
- Improvement
Fixes #5745
> Remove the init_cluster parameter in open_create_boot

- query/src/users/user_mgr.rs
- query/tests/it/users/auth/auth_mgr.rs
- query/tests/it/users/user_mgr.rs
Signed-off-by: hantmc <hantmac@outlook.com>
Optimize error message.
- Improvement
Fixes [#issue](https://github.com/datafuselabs/databend/issues/5635)
> fix(functions): optimize error message

- query/src/servers/mysql/mysql_interactive_worker.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
> feature(query): support errorcode hint in new planner

- README.md
> chore(readme): remove design overview and add try databend

- .github/actions/setup_build_tool/action.yml
- .github/actions/setup_docker/action.yml
- .github/workflows/build-tool.yml
- docker/build-tool/dev/Dockerfile
- scripts/setup/dev_setup.sh
> chore: push build-tool image to ecr

- .github/actions/setup_docker/action.yml
- scripts/setup/run_build_tool.sh
> fix: login to ecr with password

- .github/actions/setup_docker/action.yml
- scripts/setup/run_build_tool.sh
> fix(ci): public ecr should go with us-east-1

- .github/workflows/build-tool.yml
- scripts/setup/run_build_tool.sh
> fix: image tag for build-tool dev

- .github/workflows/databend-release.yml
> chore: publish release image to ecr

- .github/workflows/databend-release.yml
> fix: add permission for release workflow

- metasrv/src/meta_service/raftmeta.rs
> Make the stop function reentrant

- query/src/interpreters/interpreter_factory.rs
- query/src/interpreters/interpreter_factory_v2.rs
- query/src/interpreters/interpreter_show_metrics.rs
- query/src/interpreters/interpreter_show_processlist.rs
- query/src/interpreters/interpreter_show_settings.rs
- query/src/sql/optimizer/mod.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/format/display_plan.rs
- query/src/sql/planner/plans/mod.rs
> feature(planner): Support system `SHOW` statements

- tests/suites/1_stateful/02_query/02_0000_kill_query.py
Add test for abort pipeliner executor
Fixes #5805
> add test for abort pipeliner executor

- docs/doc/30-reference/30-sql/00-ddl/20-table/21-ddl-undrop-table.md
- docs/doc/30-reference/30-sql/40-show/show-tables.md
Doc updates for SHOW TABLES HISTORY
Fixes #issue
> Doc updates for SHOW TABLES HISTORY

- .github/actions/test_unit/action.yml
- .github/workflows/developing.yml
- .github/workflows/production.yml
> chore: move unittest to self-hosted runner

- common/ast/src/ast/statement.rs
- common/ast/src/parser/statement.rs
- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/statement.txt
- query/src/interpreters/interpreter_factory_v2.rs
- query/src/sql/optimizer/mod.rs
- query/src/sql/planner/binder/ddl/mod.rs
- query/src/sql/planner/binder/ddl/view.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/format/display_plan.rs
- query/src/sql/planner/plans/mod.rs
- tests/suites/0_stateless/05_ddl/05_0019_ddl_create_view_v2.sql
support `create view` in new planner
- New Feature
#5779
> feat(planner): support `create view` in new planner

- .github/actions/check/action.yml
- .github/actions/setup_build_tool/action.yml
- .github/actions/test_unit/action.yml
> fix: use ecr for self-hosted jobs

- query/src/interpreters/interpreter_user_stage_drop.rs
- tests/suites/1_stateful/00_copy/00_0001_upload_to_stage.sh
remove directory recursive in drop internal stage
- New Feature
Fixes #5615
> feat(stage): remove directory recursive in drop internal stage

- .github/workflows/production.yml
> fix: logic test missing with profile config

- common/exception/src/exception_code.rs
- common/meta/api/src/schema_api_impl.rs
- common/meta/types/src/app_error.rs
Improve: add schema api txn max retry times
- Improvement
Fixes #issue
> Improve: add schema api txn max retry times

- query/src/pipelines/new/processors/transforms/hash_join/chaining_hash_table.rs
- query/src/sql/exec/data_schema_builder.rs
- query/src/sql/planner/plans/logical_join.rs
Support semi join and anti join in new planner
- New Feature
Fixes #5794
> fix(planner): support semi and anti join in new planner

- query/src/servers/http/clickhouse_handler.rs
- query/src/storages/result/download.rs
- query/src/storages/stage/stage_table.rs
amend for my previous pr https://github.com/datafuselabs/databend/pull/5898
thanks to @sundy-li
> use serialize_prefix in download and stage_table.

- query/src/sql/optimizer/heuristic/mod.rs
- query/src/sql/optimizer/rule/factory.rs
- query/src/sql/optimizer/rule/mod.rs
- query/src/sql/optimizer/rule/rewrite/mod.rs
- query/src/sql/optimizer/rule/rewrite/rule_push_down_filter_join.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/binder/scalar_common.rs
- query/tests/it/sql/optimizer/heuristic/join.rs
- query/tests/it/sql/optimizer/heuristic/mod.rs
- query/tests/it/sql/optimizer/heuristic/select.rs
- query/tests/it/sql/optimizer/heuristic/testdata/join.test
- New Feature
Close #5633 #5911
> feature(optimizer): Support predicate push down through join

- website/blog/2022-03-28-databend-v0.7-release.md
- website/blog/2022-06-09-quick-deploy.md
Fix https://github.com/datafuselabs/databend/issues/5917
Also fix tags not displayed correctly.
> docs/blog: Fix front meta of posts

- .github/actions/publish_binary/action.yml
- .github/actions/publish_binary/databend-release-readme.txt
- .github/workflows/databend-release.yml
- docs/doc/60-contributing/03-rfcs/20220530-user-friendly-releases.md
- add a readme for release
- only release a databend-*.tar.gz , with bin and configs
Fixes #5681
> chore(ci): user friendly release

- tests/suites/0_stateless/03_dml/03_0003_select_group_by.result
- tests/suites/0_stateless/03_dml/03_0003_select_group_by.sql
Temporary disable group by test
Fixes #issue
> chore: disable group by test

- common/ast/src/ast/statement.rs
- common/ast/src/parser/statement.rs
- common/ast/src/parser/token.rs
- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/statement-error.txt
- common/ast/tests/it/testdata/statement.txt
- query/src/interpreters/interpreter_factory_v2.rs
- query/src/interpreters/interpreter_role_create.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/format/display_plan.rs
- query/src/sql/planner/plans/mod.rs
- tests/suites/0_stateless/05_ddl/05_0014_ddl_create_role_v2.sql
- tests/suites/0_stateless/05_ddl/05_0015_ddl_drop_role_v2.sql
Migrate CREATE/DROP ROLE statement to new planner
- Improvement
https://github.com/datafuselabs/databend/issues/5777
> Migrate CREATE/DROP ROLE statement to new planner

- docs/doc/30-reference/30-sql/70-system-tables/system-columns.md
modify doc for system-columns
Fixes #5948
> modify doc for system-columns

- .github/actions/build_debug/action.yml
- .github/actions/build_debug_hive/action.yml
- .github/actions/build_release/action.yml
- .github/workflows/databend-release.yml
- .github/workflows/developing.yml
- .github/workflows/production.yml
> fix: mkdir when pack binaries

- .github/workflows/databend-release.yml
> fix: strip-components for tar content change

- query/src/pipelines/new/processors/transforms/hash_join/chaining_hash_table.rs
- query/src/sql/optimizer/rule/rewrite/rule_push_down_filter_join.rs
- query/src/sql/planner/binder/join.rs
- query/src/sql/planner/binder/select.rs
- query/src/sql/planner/format/display_rel_operator.rs
- query/src/sql/planner/plans/logical_join.rs
- query/tests/it/sql/optimizer/heuristic/testdata/join.test
- query/tests/it/sql/optimizer/heuristic/testdata/select.test
- query/tests/it/sql/optimizer/heuristic/testdata/subquery.test
- query/tests/it/sql/planner/format/mod.rs
- tests/logictest/suites/gen/20+_others/20_0001_planner_v2
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
> improve(planner): Refine format of explain

- docs/doc/40-integrations/10-data-tool/00-vector.md
Signed-off-by: hantmc <hantmac@outlook.com>
fix vector docs
> docs(vector): fix vector docs

- .github/workflows/databend-release.yml
> fix(ci): wildcard extract in release

- Cargo.lock
- query/Cargo.toml
- query/src/servers/mysql/mysql_interactive_worker.rs
- tests/suites/0_stateless/20+_others/20_0008_mysql_client_command.py
fix status cause mysql client hang
- Bug Fix
Fixes #5894
> fix status cause mysql client hang

- docs/doc/30-reference/30-sql/00-ddl/20-table/60-optimize-table.md
Documentations for statement `optimize table`
Fixes #issue
> doc: document for statement `optimize table`

- query/src/servers/clickhouse/interactive_worker.rs
- query/src/servers/http/middleware.rs
- query/src/sessions/query_ctx.rs
- query/src/sessions/query_ctx_shared.rs
- query/src/sessions/session.rs
- query/src/users/auth/auth_mgr.rs
- query/tests/it/users/auth/auth_mgr.rs
- New Feature
Fixes https://github.com/datafuselabs/databend/issues/5888
> add tenant header for http handler

- docs/doc/30-reference/30-sql/20-query-syntax/dml-join.md
1. left outer join
2. right outer join
3. fix: queries can't produce results
Fixes #issue
> doc(join): add outer join

- query/src/storages/system/tables_table.rs
- query/tests/it/servers/http/http_query_handlers.rs
- query/tests/it/storages/system/tables_table.rs
- tests/logictest/suites/gen/01_system/01_0001_system_tables
- tests/logictest/suites/gen/09_fuse_engine/09_0000_remote_create_table
- tests/logictest/suites/gen/09_fuse_engine/09_0014_func_clustering_information_function
- tests/logictest/suites/gen/09_fuse_engine/09_0015_remote_alter_cluster_key
- tests/suites/0_stateless/01_system/01_0001_system_tables.result
- tests/suites/0_stateless/09_fuse_engine/09_0000_remote_create_table.result
- tests/suites/0_stateless/09_fuse_engine/09_0000_remote_create_table.sql
Add cluster_by field in system.tables
- Improvement
Fixes #issue
> Add cluster_by field in system.tables

- docs/doc/30-reference/30-sql/00-ddl/70-clusterkey/_category_.json
- docs/doc/30-reference/30-sql/00-ddl/70-clusterkey/dml-alter-cluster-key.md
- docs/doc/30-reference/30-sql/00-ddl/70-clusterkey/dml-drop-cluster-key.md
Added docs for ALTER & DROP CLUSTER KEY
Fixes #issue
> Doc: ALTER & DROP CLUSTER KEY

- common/datavalues/src/types/deserializations/string.rs
- query/tests/it/formats/format_csv.rs
> fix(csv): fix de_csv with escaped quoted

- common/ast/src/ast/statement.rs
- common/ast/tests/it/testdata/statement.txt
> fix display for create/drop role statement

- docs/doc/90-learn/02-analyze-nginx-logs-with-databend-and-vector.md
Signed-off-by: hantmc <hantmac@outlook.com>
Fix vector docs because the original sql will cause `1058: Unknown column count`.
> docs(vector): fix sql

- scripts/setup/dev_setup.sh
- issue #6018
- New Feature
Fixes #6018
> feat: export JAVA_HOME in dev_setup.sh

- docs/doc/30-reference/30-sql/80-setting-cmds/_category_.json
- docs/doc/30-reference/30-sql/80-setting-cmds/show-settings.md
Added docs for show settings cmd
Fixes #issue
> Doc: Show Settings

- scripts/setup/dev_setup.sh
A revert of PR
-  https://github.com/datafuselabs/databend/pull/6029
Since 
- https://github.com/datafuselabs/databend/pull/6030
already handled JAVA_HOME issue, and  more elegant
- Improvement
Fixes #issue
> fix: remove unnecessary update profile in dev_setup.sh

- common/ast/src/parser/mod.rs
- common/ast/src/parser/statement.rs
- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/statement.txt
- query/src/sql/planner/binder/show.rs
- query/src/sql/planner/binder/table.rs
- query/src/sql/planner/mod.rs
- query/tests/it/sql/optimizer/heuristic/mod.rs
> chore(parser): stop supporting multiple statements

- query/src/interpreters/interpreter_factory.rs
- query/src/interpreters/interpreter_factory_interceptor.rs
- query/src/interpreters/interpreter_factory_v2.rs
- query/src/interpreters/interpreter_query_log.rs
- query/src/sql/planner/plans/mod.rs
> feature(planner): Support query log for new planner

- docs/doc/10-deploy/01-s3.md
add arm deploy for ec2+s3
CI
Fixes #issue
> chore(doc): add arm deploy for ec2+s3

- docs/doc/30-reference/30-sql/30-query-operators/operators-set.md
added file for set operators (intersect & except)
Fixes #6033
> Doc: Set operators (intersect & except)

- query/src/servers/mysql/mysql_interactive_worker.rs
Signed-off-by: Veeupup <code@tanweime.com>
Improvement: Make useless MySQL extra info messages silent
- Improvement
Fixes #5926
> Improvement: Make useless MySQL extra info messages silent

- query/src/sql/optimizer/rule/rewrite/rule_eliminate_project.rs
- query/tests/it/sql/optimizer/heuristic/select.rs
- query/tests/it/sql/optimizer/heuristic/testdata/select.test
- query/tests/it/sql/optimizer/heuristic/testdata/subquery.test
Eliminate project operators if a project pass through all the input columns.
- Improvement
> improve(optimizer): Refine rule eliminate project

- metasrv/src/api/http_service.rs
- metasrv/src/metrics/meta_metrics.rs
- metasrv/src/metrics/mod.rs
revert meta /v1/health check
- Bug Fix
Fixes #issue
> revert meta /v1/health check

- docs/doc/30-reference/30-sql/20-query-syntax/dml-select.md
added col_alias & col_position for GROUP BY
Fixes #issue
> Doc: Group by column position

- query/src/sql/sql_common.rs
- query/tests/it/sql/mod.rs
- query/tests/it/sql/sql_common.rs
> chore(sql): fix short sql

- docs/doc/30-reference/20-functions/11-conditional-functions/multi_if.md
- docs/doc/30-reference/20-functions/11-conditional-functions/nullif.md
added description about enabling new Databend planner for MULTI_IF and NULLIF.
Fixes #issue
> Doc: updated MULTI_IF and NULLIF for new planner

- common/functions/src/scalars/contexts/context.rs
- query/src/common/context_function.rs
- query/src/storages/stage/stage_table.rs
- tests/suites/0_stateless/02_function/02_0003_function_database.result
- tests/suites/0_stateless/02_function/02_0003_function_database.sql
- tests/suites/1_stateful/00_copy/00_0000_copy_from_stage.result
- tests/suites/1_stateful/00_copy/00_0000_copy_from_stage.sh
- copy respect size_limit option
- support `current_user`, `current_database` function
- Improvement
Fixes #6091
> query(stage): respect size_limit option

- .github/actions/publish_binary/databend-scripts-for-release/start.sh
**old**
> or: curl -u root: --request POST '127.0.0.1:8001/v1/query/' --data-raw '{sql: \<your-query\>}'
**new**
> or: curl -u root: --request POST '127.0.0.1:8001/v1/query/' --data-raw '{"sql": "\<your-query\>"}' -H 'Content-Type: application/json'
Fixes #issue
> chore(release): fix the hint in start script

- Cargo.lock
- Cargo.toml
- apply my patch of rust-goldenfile
- check https://github.com/calder/rust-goldenfile/pull/7#issuecomment-1162006531 to see the display in our case
Fixes #6078
> chore(deps): issue-6078, try to make goldenfile results readable

- query/src/interpreters/interpreter_query_log.rs
the `event_time` of `query_log` is incorrect.
```sql
mysql> select * from system.query_log\G;
***************************[ 1. row ]***************************
log_type                 | 1
handler_type             | MySQL
tenant_id                | admin
cluster_id               |
sql_user                 | root
sql_user_quota           | UserQuota<cpu:0,mem:0,store:0>
sql_user_privileges      | GRANT ALL ON *.*, ROLES: []
query_id                 | c14c1501-8c20-4fc2-9c3b-c31cc7c83e31
query_kind               | UseDatabasePlan
query_text               | USE `default`;
event_date               | 2022-06-22
event_time               | 1970-01-20 03:58:04.057000
current_database         | default …
```
> fix(query): fix query_log incorrect event_time

- docs/doc/30-reference/30-sql/00-ddl/20-table/10-ddl-create-table.md
- docs/doc/30-reference/30-sql/00-ddl/70-clusterkey/dml-set-cluster-key.md
Ddoc updates: Set a clusterkey when creating a table
Fixes https://github.com/datafuselabs/databend/issues/6101
> Doc: Set a clusterkey when creating a table

- Cargo.lock
- Cargo.toml
- common/base/Cargo.toml
Try to build on musl
https://github.com/tikv/jemallocator/issues/30
https://github.com/tikv/pprof-rs/issues/138
> chore(deps): add a patch of pprof, tikv-jemalloc-sys 0.4.3

- docs/doc/30-reference/30-sql/20-query-syntax/dml-at.md
Added doc for AT timestamp.
Fixes #issue
> Doc: AT timestamp

- query/src/storages/fuse/operations/commit.rs
fix issue:
- #6161
- Improvement
Fixes #6161
> chore(log level): downgrade log level to DEBUG of TableVersionMismatched messages

- docs/doc/50-manage/00-metasrv/20-metasrv-add-remove-node.md
> [metasrv] doc: explain how to examine the meta cluster state

- docs/doc/10-deploy/20-databend-cloud.md
Minor fixes for the new cloud deploy page
Fixes #issue
> Doc: Minor fixes for cloud deploy

- tests/suites/0_stateless/09_fuse_engine/09_0017_func_fuse_snapshot_history_limit.sh
> chore(test): fix wc -l on macOS

- query/src/servers/http/clickhouse_handler.rs
- query/src/servers/http/middleware.rs
> chore(log): add  info logs for http handlers.

- docs/doc/10-deploy/20-databend-cloud.md
- website/src/pages/index.tsx
Add more info for cloud
Fixes #issue
> chore(doc): add more info for cloud

- .github/mergify.yml
- README.md
This PR will enable `speculative_checks` and `batch_size`
> ci(mergify): Enable speculative_checks and batch_size

- .github/workflows/developing.yml
ci: Only run the developing workflow on pull request
> ci: Only run developing workflow on pull request

- query/src/pipelines/new/processors/transforms/hash_join/chaining_hash_table.rs
- query/src/sql/exec/pipeline_builder.rs
- query/src/sql/optimizer/heuristic/decorrelate.rs
- query/tests/it/sql/optimizer/heuristic/subquery.rs
- query/tests/it/sql/optimizer/heuristic/testdata/subquery.test
> feature(planner): Decorrelate `EXISTS` subquery with non-equi condition

- docs/doc/30-reference/30-sql/10-dml/dml-delete-from.md
added doc for the DELETE FROM command.
Fixes #issue
> Doc: Delete-From

- .github/actions/build_linux/action.yml
- .github/actions/build_linux_hive/action.yml
- .github/actions/check/action.yml
- .github/actions/test_compat/action.yml
- .github/actions/test_meta_cluster/action.yml
- .github/actions/test_stateless_cluster_linux/action.yml
- .github/actions/test_stateless_standalone_linux/action.yml
- .github/actions/test_unit/action.yml
> fix(ci): use default image instead of ecr

- .github/mergify.yml
Use mergify to check PR description
> ci(mergify): Use mergify to check PR description

- .github/mergify.yml
ci(mergify): Make yamllint happy
Fixes #issue
> ci(mergify): Make yamllint happy

- docs/doc/30-reference/30-sql/20-query-syntax/dml-at.md
- docs/doc/30-reference/30-sql/20-query-syntax/dml-select.md
added doc for AT snapshot
Fixes #issue
> Doc: AT snapshot

- .github/actions/test_sqllogic_standalone_linux/action.yml
- .github/actions/test_sqllogic_standalone_macos/action.yml
- .github/actions/test_stateless_cluster_macos/action.yml
- .github/actions/test_stateless_standalone_macos/action.yml
- .github/mergify.yml
- .github/workflows/dev-linux.yml
- .github/workflows/dev-macos.yml
- .github/workflows/developing.yml
- docker/build-tool/alpine/Dockerfile
- docker/build-tool/dev/Dockerfile
- scripts/setup/dev_setup.sh
- tests/logictest/Dockerfile
> feat(ci): install sqllogic dependencies to build tool image

- docs/doc/30-reference/30-sql/20-query-syntax/dml-at.md
Fixed title format
Fixed title format.
Fixes #issue
> Doc: fixed title format

- scripts/setup/dev_setup.sh
> fix: missing arg in dev_setup

- common/meta/api/src/schema_api_impl.rs
- common/meta/app/src/schema/table.rs
> [meta/schema] refactor: add debug tracing log for every schema api

- .github/workflows/dev-linux.yml
> fix: self-hosted runner job schedule label case sensitive

- docs/doc/01-cloud/10-data-tool/_category_.json
- docs/doc/01-cloud/20-bi-tool/_category_.json
- docs/doc/01-cloud/_category_.json
- docs/doc/01-cloud/index.md
Add  databend cloud
Fixes #issue
> chore(doc): add databend cloud

- query/src/interpreters/interpreter_factory_v2.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/format/display_plan.rs
- query/src/sql/planner/plans/mod.rs
> Migrate DROP FUNCTION to new planner

- common/meta/api/src/kv_api.rs
- common/meta/api/src/kv_api_test_suite.rs
- common/meta/api/src/lib.rs
- common/meta/api/src/schema_api_test_suite.rs
- common/meta/embedded/tests/it/schema_api_impl.rs
- common/meta/raft-store/tests/it/state_machine/schema_api_impl.rs
- metasrv/tests/it/grpc/metasrv_grpc_kv_api.rs
- metasrv/tests/it/grpc/metasrv_grpc_schema_api.rs
- metasrv/tests/it/meta_node/meta_node_kv_api.rs
- metasrv/tests/it/tests/service.rs
> [meta/schemaapi] test: move test cases into an entry function to simplify testing for every implementation

- query/src/interpreters/mod.rs
- query/src/procedures/systems/mod.rs
- query/src/procedures/systems/sync_stage.rs
- query/src/procedures/systems/system.rs
- tests/suites/1_stateful/01_load/01_0003_sync_stage_file.result
- tests/suites/1_stateful/01_load/01_0003_sync_stage_file.sh
> feat: add call procedure for sync stage

- query/src/sql/exec/pipeline_builder.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
> fix(planner): limit returns error result

- tests/logictest/clickhouse_connector.py
Add additional headers for security issues.
Fixes #issue
> chore: logic test add clickhouse additional headers

- query/src/common/hashtable/hash_table.rs
- query/src/common/hashtable/hash_table_entity.rs
- query/src/common/hashtable/two_level_hash_table.rs
- query/tests/it/common/hashtable.rs
fix hashmap memory leak
- Bug Fix
Fixes #issue
Thanks for @usamoi , can you help review this?
> query(fix): fix hashmap memory leak

- Makefile
- scripts/setup/dev_setup.sh
- scripts/setup/rust-toolchain.toml
ci: Bump rust toolchain for build-tools
Fixes https://github.com/datafuselabs/databend/pull/6376
> ci: Bump rust toolchain for build-tools

- common/ast/src/ast/statements/call.rs
- common/ast/src/ast/statements/statement.rs
- common/ast/src/parser/statement.rs
- common/ast/src/parser/token.rs
- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/statement-error.txt
- common/ast/tests/it/testdata/statement.txt
- query/src/interpreters/interpreter_factory_v2.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/format/display_plan.rs
- query/src/sql/planner/plans/mod.rs
- tests/suites/1_stateful/01_load_v2/01_0003_sync_stage_file.result
- tests/suites/1_stateful/01_load_v2/01_0003_sync_stage_file.sh
Migrate call statement to new planner
- New Feature
Fixes #issue
> Migrate call statement to new planner

- common/ast/src/ast/statements/call.rs
> chore: Make clippy happy

- .github/PULL_REQUEST_TEMPLATE.md
- .github/mergify.yml
- docs/doc/60-contributing/01-good-pr.md
ci: Enable semantic PRs
Part of https://github.com/datafuselabs/databend/issues/6384
> ci: Enable semantic PRs

- .github/mergify.yml
ci: Fix typo in mergify
Fixes #issue
> ci: Fix typo in mergify

- .github/workflows/databend-auto-tag.yml
ci: Fix generated tag not pushed
> ci: Fix generated tag not pushed

- query/src/interpreters/interpreter_copy.rs
- query/src/interpreters/interpreter_copy_v2.rs
enable new pipeline for copy in cluster mode. Just remove the check, performance will not be improved.
Part of #6395
> chore(query):  enable new pipeline for copy in cluster mode

- metasrv/src/meta_service/raftmeta.rs
- scripts/setup/dev_setup.sh
- tests/logictest/clickhouse_connector.py
- tests/logictest/complete.py
- tests/logictest/config.py
- tests/logictest/logictest.py
- tests/logictest/main.py
> chore(metasrv): explain why "join" not work in log

- .github/workflows/databend-release.yml
ci: Don't start discussion while releasing
> ci: Don't start discussion while releasing

- Cargo.lock
- common/ast/Cargo.toml
- common/datavalues/src/columns/array/mod.rs
- common/datavalues/src/columns/array/mutable.rs
- common/datavalues/src/data_value.rs
- common/datavalues/src/types/type_array.rs
- common/exception/Cargo.toml
- common/functions/Cargo.toml
- common/functions/src/scalars/semi_structureds/array_get.rs
- query/Cargo.toml
- query/src/sql/sql_common.rs
- query/src/sql/statements/analyzer_expr.rs
- query/src/sql/statements/analyzer_expr_sync.rs
- tests/suites/0_stateless/03_dml/03_0023_insert_into_array.result
- tests/suites/0_stateless/03_dml/03_0023_insert_into_array.sql
- tests/suites/0_stateless/03_dml/03_0023_insert_into_array_v2.result
- tests/suites/0_stateless/03_dml/03_0023_insert_into_array_v2.sql
fix array inner type with null
Fixes #6397
> fix(query): fix array inner type with null

- .github/workflows/databend-release.yml
ci: Fix typo in test-tools release
> ci: Fix typo in test-tools release

- README.md
- docs/doc/00-guides/index.md
Fixed broken links to the new Deploy chapter
Fixes #issue
> docs: Fix deploy links

- docs/doc/30-reference/20-functions/122-window-functions/_category_.json
- docs/doc/30-reference/20-functions/122-window-functions/aggregate-window-functions.md
- docs/doc/30-reference/20-functions/index.md
Added doc for aggregate window functions.
Fixes #issue
> docs: Aggregate window functions

- docs/doc/10-deploy/00-understanding-deployment-modes.md
- docs/doc/10-deploy/02-deploying-databend.md
- docs/doc/10-deploy/03-expanding-to-a-databend-cluster.md
**Before**:
**This patch**:
Fixes #issue
> chore(doc): change ** to  for text more highlight

- query/src/sql/optimizer/heuristic/subquery_rewriter.rs
- query/src/sql/planner/binder/aggregate.rs
- query/src/sql/planner/binder/bind_context.rs
- query/src/sql/planner/binder/ddl/table.rs
- query/src/sql/planner/binder/mod.rs
- query/src/sql/planner/binder/project.rs
- query/src/sql/planner/binder/sort.rs
- query/src/sql/planner/binder/table.rs
- query/src/sql/planner/semantic/grouping_check.rs
- query/src/sql/planner/semantic/type_check.rs
- query/tests/it/common/evaluator/mod.rs
- query/tests/it/sql/planner/format/mod.rs
- tests/logictest/requirements.txt
- tests/logictest/suites/query/select.test
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
> feat(planner): Support qualified column name with database specified

- query/src/sql/planner/binder/bind_context.rs
- tests/logictest/suites/query/alias/case.test
> fix(planner): Fix case of table alias

- .github/workflows/dev-macos.yml
- docker/build-tool/musl/Dockerfile
> fix(build-tool): add symlink for musl-gcc

- query/src/pipelines/new/processors/resize_processor.rs
- query/tests/it/pipelines/new/processors/mod.rs
- query/tests/it/pipelines/new/processors/resize.rs
fix(processor): fix lost event in resize processor
fixes #5973 
fixes #6250
> fix(processor): fix lost event in resize processor

- common/meta/raft-store/src/state_machine/sm.rs
fix txn watch kv changed bug
Fixes #issue
> fix: fix txn watch kv changed bug

- docs/doc/30-reference/30-sql/00-ddl/80-presign/presign.md
Fixed some typos in the doc.
Fixes #issue
> chore: Fix typos

- common/ast/src/ast/expr.rs
- common/ast/src/parser/expr.rs
- common/ast/src/parser/token.rs
- common/ast/tests/it/testdata/expr-error.txt
- common/exception/src/exception_code.rs
- query/src/sql/planner/semantic/type_check.rs
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
- tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql
Add `date_trunc` function.
Fixes #6528
> feat(function): add date_trunc function

- query/src/pipelines/new/executor/pipeline_executor.rs
- query/src/pipelines/new/pipeline.rs
fix(processor): call on finished if has error before execute
Fixes #6511
> fix(processor): call on finished if has error before execute

- .github/actions/test_fuzz_standalone_linux/action.yml
- .github/workflows/dev-linux.yml
- scripts/ci/ci-run-fuzz-tests.sh
- scripts/setup/dev_setup.sh
Add fuzz test in development ci, fuzz fail will not block development workflow.
Fixes #issue
> chore: add fuzz ci

- docs/doc/30-reference/20-functions/30-datetime-functions/datetrunc.md
Added doc for the date_trunc command.
Fixes #issue
> docs: date_trunc

- docs/doc/30-reference/30-sql/00-ddl/20-table/10-ddl-create-table.md
Added doc for the TRANSIENT option to the CREATE TABLE page.
Also included some minor fixes for the page.
Fixes #issue
> docs: create transient table

- common/ast/tests/it/parser.rs
- common/ast/tests/it/testdata/statement.txt
- query/src/interpreters/interpreter_copy_v2.rs
- query/src/interpreters/interpreter_factory_v2.rs
- query/src/sql/exec/physical_plan_builder.rs
- query/src/sql/exec/util.rs
- query/src/sql/optimizer/mod.rs
- query/src/sql/planner/binder/copy.rs
- query/src/storages/stage/stage_table.rs
- tests/suites/1_stateful/00_copy_v2/00_0000_copy_from_stage.sh
- tests/suites/1_stateful/00_copy_v2/00_0000_copy_from_stage2.py
fix: Copy is able to run under new planner
> fix: Copy shoud be able to run under new planner

- .github/workflows/dev-linux.yml
- docker/build-tool/musl/Dockerfile
in case some jobs stuck for too long
Fixes #issue
> ci: add timeout to dev linux jobs

- common/meta/types/src/user_stage.rs
- common/proto-conv/src/user_from_to_protobuf_impl.rs
- common/protos/proto/user.proto
- query/src/storages/stage/stage_source.rs
Fixes https://github.com/datafuselabs/databend/issues/6555
> feat(query):  add StageFileFormatType::Tsv.

- common/meta/api/src/kv_api_utils.rs
- common/meta/api/src/lib.rs
- common/meta/api/src/share_api_impl.rs
- common/meta/api/src/share_api_keys.rs
- common/meta/api/src/share_api_test_suite.rs
- common/meta/app/src/share/mod.rs
- common/meta/app/src/share/share.rs
- common/meta/embedded/tests/it/schema_api_impl.rs
- common/meta/raft-store/tests/it/state_machine/schema_api_impl.rs
- metasrv/tests/it/grpc/metasrv_grpc_schema_api.rs
feat: add share id to share name map, add share test suites
Fixes #issue https://github.com/datafuselabs/databend/issues/6655
> feat: add share id to share name map, add share test suites

- docs/doc/10-deploy/00-understanding-deployment-modes.md
- docs/doc/10-deploy/02-deploying-databend.md
Add release target tab for the deploy.
Fixes #issue
> chore(doc): add release target tab for the deploy

- docs/doc/30-reference/30-sql/10-dml/dml-copy-into-table.md
Removed single quotes for stages from the COPY INTO FROM examples.
Fixes #issue
> docs: remove single quotes

- docs/doc/30-reference/10-data-types/40-data-type-semi-structured-types.md
Added more examples showing queries with OBJECTS
Fixes #issue
> docs: query with data of OBJECT type

- tests/logictest/clickhouse_connector.py
- tests/logictest/complete.py
- tests/logictest/gen_suites.py
- tests/logictest/http_connector.py
- tests/logictest/logictest.py
- tests/logictest/mysql_runner.py
Silence logic test logs, change statements log level to debug, issue #6596 
Fixes #issue
> chore: silence logic test logs

- tests/suites/0_stateless/09_fuse_engine/09_0018_min_max_index.result
- tests/suites/0_stateless/09_fuse_engine/09_0018_min_max_index.sql
- tests/suites/0_stateless/09_fuse_engine/09_0018_min_max_index_cluster.result
add stateless test case for pr #6731
> chore: add stateless test case for pr #6731

- docs/doc/30-reference/30-sql/10-dml/dml-copy-into-table-url.md
- docs/doc/30-reference/30-sql/10-dml/dml-copy-into-table.md
Added doc for COPY FROM URL
Fixes #issue
> docs: copy from url

- docs/doc/30-reference/30-sql/90-explain-cmds/_category_.json
- docs/doc/30-reference/30-sql/90-explain-cmds/explain-fragments.md
Added doc for EXPLAIN FRAGMENTS.
Fixes #issue
> docs: explain fragments

- query/src/servers/mysql/mysql_interactive_worker.rs
The MySQL `InteractiveWorker` session has the same lifetime as `InteractiveWorkerBase`'s, no need for redundant create `SessionRef`.
Fixes #issue
> chore(query): Remove unnecessary session ref

- docs/doc/30-reference/00-api/00-rest.md
> docs: client-side session in rest api.

- query/src/api/rpc/flight_client.rs
- query/src/api/rpc/flight_service.rs
- query/src/api/rpc_service.rs
- scripts/ci/deploy/databend-query-cluster-3-nodes.sh
chore(ci): enable backtrace in ci cluster test
Fixes #issue
> chore(ci): enable backtrace in ci cluster test

- query/src/pipelines/executor/executor_worker_context.rs
- query/src/pipelines/executor/mod.rs
- query/src/pipelines/executor/processor_async_task.rs
refactor(processor): refactor processor async task
prepare https://github.com/datafuselabs/databend/issues/2655
> refactor(processor): refactor processor async task

- query/src/interpreters/interpreter_setting.rs
- tests/logictest/complete.py
- tests/logictest/gen_suites.py
- tests/logictest/http_connector.py
- tests/logictest/http_runner.py
- tests/logictest/suites/gen/05_ddl/05_0016_ddl_stage
- tests/logictest/suites/gen/08_optimizer/08_0000_optimizer
> ci(test): use client-side session for http handler in logic tests

- common/meta/api/src/schema_api_impl.rs
- common/meta/api/src/schema_api_test_suite.rs
1. remove DatabaseIdToName keys from meta in GC;
2. remove TableIdToName keys from meta in GC.
Fixes #6667
> refactor: Purge mapping data in DB/table GC

- Cargo.lock
- common/expression/Cargo.toml
- common/expression/src/evaluator.rs
- common/expression/src/function.rs
- common/expression/src/values.rs
- common/expression/tests/it/main.rs
- common/expression/tests/it/parser.rs
- common/expression/tests/it/testdata/run-pass.txt
- common/expression/tests/it/testdata/tyck-fail.txt
> chore(expr): auto generate domain for test cases

- query/src/sql/optimizer/rule/rewrite/rule_normalize_disjunctive_filter.rs
Make code more elegant
No logical change
Fixes #issue
> refactor(planner): refine code in `RuleNormalizeDisjunctiveFilter`

- website/docusaurus.config.js
Disable language menu
Fixes #6721
> website: disable languae menu

- .github/mergify.yml
Fix https://github.com/datafuselabs/databend/issues/6788
> ci: Add post checks for PR conflicts

- docs/doc/20-develop/03-java.md
- docs/doc/50-manage/01-query/10-query-config.md
add java to develop
Fixes #6812
> docs: add java to develop

- query/src/servers/http/clickhouse_handler.rs
- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/mysql/mysql_interactive_worker.rs
- query/src/servers/utils.rs
Fixes https://github.com/datafuselabs/databend/issues/6817
> chore(query): add helper fn use_planner_v2().

- docs/doc/21-load-data/04-remote.md
- docs/doc/30-reference/30-sql/10-dml/dml-copy-into-table-url.md
- docs/doc/30-reference/30-sql/10-dml/dml-copy-into-table.md
added tutorial about loading remote data. 
Fixes #issue
> docs: load remote data

- common/ast/src/parser/token.rs
- common/ast/tests/it/testdata/expr-error.txt
- docs/doc/20-develop/03-java.md
> fix(planner): err return

- common/expression/src/values.rs
- common/functions-v2/src/scalars/control.rs
- common/functions-v2/src/scalars/mod.rs
- common/functions-v2/tests/it/scalars/control.rs
- common/functions-v2/tests/it/scalars/mod.rs
- common/functions-v2/tests/it/scalars/parser.rs
- common/functions-v2/tests/it/scalars/testdata/control.txt
Tracked in https://github.com/datafuselabs/databend/issues/6833
> feat(function-v2): implement multi_if

- README.md
- docs/doc/01-guides/index.md
Add how to load from remote files to guides
Fixes #issue
> chore: add how to load from remote files to guides

- query/src/interpreters/fragments/query_fragment_actions_display.rs
- query/src/interpreters/fragments/v2/fragmenter.rs
- query/src/sql/executor/mod.rs
- query/src/sql/executor/physical_plan_display.rs
feat(processor): implement explain fragments for new planner
Fixes #issue
> feat(processor): implement explain fragments for new planner

- tests/logictest/logictest.py
- tests/logictest/main.py
- tests/logictest/statistics.py
1. Add time statistics 
2. Do not stop until all test finished.
Fixes #6705 #6694
> ci: improve logic test

- Cargo.lock
- common/datavalues/src/data_schema.rs
- common/formats/src/format.rs
- common/formats/src/format_csv.rs
- common/formats/src/format_parquet.rs
- common/formats/src/format_tsv.rs
- common/formats/tests/it/format_csv.rs
- common/io/src/file_split.rs
- common/io/src/prelude.rs
- common/pipeline/Cargo.toml
- common/pipeline/src/processors/port.rs
- query/src/pipelines/processors/sources/deserializer.rs
- query/src/pipelines/processors/sources/file_splitter.rs
- query/src/pipelines/processors/sources/multi_file_splitter.rs
- query/src/servers/http/v1/parallel_format_source.rs
- query/src/servers/http/v1/sequential_format_source.rs
- query/tests/it/pipelines/processors/file_splitter.rs
to provide diagnostic info when failing to parse.
Fixes #issue
> feat(input format): pass FileSplit instead of Vec<u8>.  

- README.md
- docs/doc/01-guides/index.md
1. Changed title to "Tutorials".
2. Re-ordered the topics.
3. Rephrased some sub-titles. 
Fixes #issue
> docs: new guides page

- docs/doc/30-reference/30-sql/20-query-syntax/dml-select.md
Updated order by with nulls first & last
Fixes #issue
> docs: nulls first and last

- query/src/sql/planner/semantic/type_check.rs
- tests/logictest/suites/gen/20+_others/20_0001_planner_v2
Fixes https://github.com/datafuselabs/databend/issues/6876
> fix(planner): fix trim NULL

- query/src/servers/http/clickhouse_handler.rs
- tests/logictest/suites/gen/03_dml/03_0011_select_from_system_processes
- tests/logictest/suites/query/aggregate.test
- tests/logictest/suites/query/subquery.test
- tests/logictest/suites/select_0
Fixes https://github.com/datafuselabs/databend/issues/6887
> fix(query): session drop early in clickhouse handler

- docs/doc/60-contributing/03-rfcs/20220729-recluster.md
This PR will add a new RFC about recluster.
For more detailed principles and pictures, please refer to [snowflake auto clustering](https://sundy-li.github.io/posts/探索snowflake-auto-clustering/).
Fixes #issue
> feat(RFC): recluster

- docs/doc/10-deploy/02-deploying-databend.md
Add more storage config demo for the deploy
Fixes #issue
> chore(doc): add more storage config demo for the deploy

- docs/doc/90-learn/01-analyze-ontime-with-databend-on-ec2-and-s3.md
docs: Update out-dated ontime analyze docs
> docs: Update out-dated ontime analyze docs

- common/expression/src/display.rs
- common/expression/src/evaluator.rs
- common/expression/src/expression.rs
- common/expression/src/type_check.rs
- common/expression/src/values.rs
- common/expression/tests/it/testdata/run-pass.txt
- common/functions-v2/tests/it/scalars/testdata/control.txt
- common/functions-v2/tests/it/scalars/testdata/string.txt
> refactor(expr): use Scalar to store constant in Expr

- query/src/sql/planner/binder/bind_context.rs
- query/src/sql/planner/binder/sort.rs
- tests/logictest/suites/gen/20+_others/20_0001_planner_v2
fix and refactor case-senstive order by column binding 
Fixes #issue
> fix(query): fix order by column binding

- docs/doc/90-learn/01-analyze-ontime-with-databend-on-ec2-and-s3.md
Fixes https://github.com/datafuselabs/databend/issues/6910
> docs: Fix t_ontime.csv should be load using TSV format

- query/src/api/rpc/exchange/exchange_channel_receiver.rs
- query/src/api/rpc/exchange/exchange_channel_sender.rs
- query/src/api/rpc/exchange/exchange_manager.rs
- query/src/api/rpc/flight_service.rs
- query/src/api/rpc/packets/packet_data.rs
- query/src/pipelines/executor/executor_tasks.rs
- query/src/pipelines/executor/processor_async_task.rs
fix(cluster): fix cannot kill query in cluster mode
Fixes #6238
> fix(cluster): fix cannot kill query in cluster mode

- docs/doc/30-reference/20-functions/40-string-functions/trim.md
Updated the trim function.
Fixes #issue
> docs: Add docs for TRIM related functions

- docs/doc/21-load-data/00-local.md
- docs/doc/21-load-data/01-s3.md
- docs/doc/21-load-data/02-stage.md
- docs/doc/30-reference/00-api/01-mysql-handler.md
- docs/doc/30-reference/00-api/02-clickhouse-handler.md
Fixed image links in MD files.
Fixes #issue
> docs: fix image links

- query/src/catalogs/hive/hive_catalog.rs
explictly check table inputformat(only support parquet inputformat)
> feat(hive): explictly check table inputformat(only support parquet inputformat)

- Cargo.toml
Refer to: https://github.com/tikv/tikv/blob/master/Cargo.toml#L307
Fixes #issue
> chore(query): only enable overflow-checks in profile.test

- .github/mergify.yml
Any logictest failed will not merge.
Fixes #6982
> chore: fix mergify config

- docs/doc/30-reference/20-functions/11-conditional-functions/ifnull.md
- docs/doc/30-reference/20-functions/11-conditional-functions/is_distinct_from.md
- docs/doc/30-reference/20-functions/11-conditional-functions/multi_if.md
- docs/doc/30-reference/20-functions/11-conditional-functions/nullif.md
- docs/doc/30-reference/30-sql/20-query-syntax/dml-at.md
- docs/doc/30-reference/30-sql/20-query-syntax/dml-join.md
Removed step of "enabling planner v2" from doc
Fixes #issue
> docs: remove planner v2

- tests/logictest/suites/base/02_function/02_0002_function_cast
- tests/logictest/suites/base/02_function/02_0014_function_maths
- tests/logictest/suites/base/02_function/02_0022_function_strings_unhex
- tests/logictest/suites/base/02_function/02_0024_function_strings_base_64
- tests/logictest/suites/base/02_function/02_0028_function_strings_elt
- tests/logictest/suites/base/02_function/02_0048_function_semi_structureds_object_keys
- tests/logictest/suites/base/02_function/02_0048_function_semi_structureds_parse_json
- tests/logictest/suites/base/02_function/02_0051_function_semi_structureds_get
- tests/logictest/suites/base/02_function/02_0054_function_string_regexp_replace
- tests/logictest/suites/base/03_dml/03_0000_select_aliases
- tests/logictest/suites/base/20+_others/20_0001_planner_v2
- tests/logictest/suites/base/20+_others/20_0002_planner_v2_display_error
> fix(logic test): rm some 'onlyif mysql' and 'skipif clickhouse'.

- common/ast/src/ast/statements/explain.rs
- common/ast/src/ast/statements/statement.rs
- common/ast/src/parser/statement.rs
- common/ast/src/parser/token.rs
- query/src/interpreters/interpreter_explain_v2.rs
- query/src/sql/optimizer/mod.rs
- query/src/sql/planner/format/display_rel_operator.rs
- tests/logictest/suites/base/04_explain/04_0002_explain_v2
1. Support explain unoptimized plan
2. fix LogicalPlan display
Fixes #7065
> feat(planner): support explain raw query

- common/storages/preludes/src/system/tracing_table.rs
- common/tracing/src/lib.rs
- common/tracing/src/logging.rs
- query/src/interpreters/interpreter_query_log.rs
- query/src/sessions/query_ctx.rs
- query/src/sessions/session_mgr.rs
> feat: add query logger back to session manager

- tests/logictest/README.md
- tests/logictest/complete.py
Add auto complete tool for logictest, use to complete logictest suites by SQL files or logictest file.
Fixes #6709
> chore: add logictest complete tool

- query/src/interpreters/interpreter_select_v2.rs
- query/src/servers/http/v1/query/execute_state.rs
fix(processor): try fix invalid physical exchange plan for http handle
Fixes #issue
> fix(processor): try fix invalid physical exchange plan for http handle

- README.md
Fix the grammar errors in readme.md
> chore: Fix the grammar errors in readme.md

- docs/doc/30-reference/30-sql/20-query-syntax/dml-with.md
added doc about CTE
Fixes #issue
> docs: add doc about cte

- docs/doc/30-reference/30-sql/90-explain-cmds/explain-fragments.md
- docs/doc/30-reference/30-sql/90-explain-cmds/explain-raw.md
added doc about EXPLAIN RAW
Fixes #issue
> docs: add explain raw

- src/query/service/src/pipelines/processors/transforms/hash_join/join_hash_table.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/row.rs
- tests/logictest/suites/base/15_query/join.test
fix cross join error when build block is empty
Fixes #7149
> fix(planner): fix cross join empty gets error

- docs/doc/30-reference/30-sql/90-explain-cmds/explain-syntax.md
added doc for the EXPLAIN SYNTAX command
Fixes #issue
> docs: explain syntax

- Cargo.lock
- src/binaries/Cargo.toml
- src/meta/raft-store/src/config.rs
- src/meta/raft-store/src/state_machine/sm.rs
- src/meta/raft-store/tests/it/state_machine/mod.rs
- src/meta/service/src/meta_service/meta_leader.rs
- src/meta/service/tests/it/store.rs
- src/meta/sled-store/Cargo.toml
- src/meta/types/Cargo.toml
> refactor(openraft): upgrade openraft to release 0.7.1

- .github/workflows/databend-release.yml
ci: Fix releases on existing tags
> ci: Fix releases on existing tags

- Cargo.lock
- src/common/building/Cargo.toml
- src/common/building/src/lib.rs
- src/common/pipeline/sinks/Cargo.toml
- src/common/pipeline/sources/Cargo.toml
- src/common/pipeline/transforms/Cargo.toml
- src/common/storages/fuse/Cargo.toml
- src/common/storages/preludes/Cargo.toml
- src/query/service/Cargo.toml
- async-trait-fn 0.1.0
- cargo license 0.5.1
Fixes #6968 
Fixes #6969
> chore(deps): upstream first

- src/meta/grpc/src/grpc_client.rs
> chore: add log about auto sync started

- src/query/service/src/pipelines/processors/transforms/transform_expression_v2.rs
- src/query/service/src/sql/planner/binder/insert.rs
- tests/logictest/suites/crdb/overflow
use `Evaluator` to refactor `insert`
Fixes #issue
> refactor(planner): use Evaluator to refactor insert

- src/common/base/src/mem_allocator/mmap_allocator.rs
- src/query/ast/src/parser/expr.rs
- src/query/functions/src/scalars/conditionals/in_basic.rs
- tests/logictest/suites/base/02_function/02_0045_conditional_function_in
- tests/logictest/suites/base/20+_others/20_0001_planner_v2
fix some  minor bugs and building in ci
1.  Fix building in macos
2. Allow IntervalKind accept literal string
Fixes #7203
> refactor(query): fix some  minor bugs and building in ci

- docs/doc/10-deploy/04-deploying-databend-on-kubernetes.md
Minor fixes for k8s deploy
Fixes #issue
> docs: minor fixes for k8s deploy

- src/query/catalog/src/lib.rs
- src/query/catalog/src/table.rs
- src/query/catalog/src/table_mutator.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_block_compact.rs
- src/query/service/src/interpreters/interpreter_table_optimize.rs
- src/query/service/tests/it/storages/fuse/io.rs
- src/query/service/tests/it/storages/fuse/operations/mutation/recluster_mutator.rs
- src/query/storages/fuse-meta/src/meta/v1/segment.rs
- src/query/storages/fuse/src/fuse_table.rs
- src/query/storages/fuse/src/io/write/block_compactor.rs
- src/query/storages/fuse/src/lib.rs
- src/query/storages/fuse/src/operations/append.rs
- src/query/storages/fuse/src/operations/compact.rs
- src/query/storages/fuse/src/operations/mod.rs
- src/query/storages/fuse/src/operations/mutation/compact_mutator.rs
- src/query/storages/fuse/src/operations/mutation/recluster_mutator.rs
- src/query/storages/fuse/src/operations/recluster.rs
1. use pipline to refactor compact
2. Add TableMutator trait
Fixes #issue
> refactor(storage): use pipline to refactor compact

- tests/suites/0_stateless/13_tpch/13_0000_prepare.result
- tests/suites/0_stateless/13_tpch/13_0000_prepare.sh
https://github.com/datafuselabs/databend/runs/7969999341?check_suite_focus=true
Fixes #issue
> chore: fix `13_0000_prepare.sh` script

- docs/doc/30-reference/30-sql/80-setting-cmds/set-global.md
- docs/doc/30-reference/30-sql/80-setting-cmds/show-settings.md
doc for SET command
Fixes #issue
> docs: set command

- tests/logictest/suites/base/05_ddl/05_0000_ddl_create_tables
- tests/logictest/suites/base/05_ddl/05_0016_ddl_stage
- tests/logictest/suites/base/20+_others/20_0000_describe_table
Fix some statement with show and desc has results but use statement ok.
Fixes #7254
> chore: fix cases with desc and show

- tests/suites/0_stateless/14_clickhouse_http_handler/14_0001_clickhouse_http.result
- tests/suites/0_stateless/14_clickhouse_http_handler/14_0001_clickhouse_http.sh
> feat(test): add test for format

- src/meta/raft-store/src/state_machine/sm.rs
- src/meta/service/src/meta_service/raftmeta.rs
- src/meta/service/src/store/store_bare.rs
> refactor(meta-service): add cluster status "last_seq"; add info level logging for critical events

- docs/doc/30-reference/30-sql/30-query-operators/operators-set.md
added doc for UNION ALL.
Fixes #issue
> docs: union all

- tests/logictest/README.md
- tests/logictest/cleanup.py
- tests/logictest/complete.py
1. add auto-cleanup support
2. fix the wrong way of getting error_code, get code from error msg.
Fixes #issue
> chore: fix complete script

- Cargo.lock
- src/binaries/Cargo.toml
- src/meta/service/src/api/http/v1/cluster_state.rs
- src/meta/service/src/api/http/v1/ctrl.rs
- src/meta/service/src/api/http/v1/mod.rs
- src/meta/service/src/api/http_service.rs
- src/meta/sled-store/Cargo.toml
- src/meta/types/Cargo.toml
> feat(meta-service): admin api: /v1/ctrl/trigger_snapshot let the leader send a snapshot to every follower

- src/query/service/src/sql/planner/binder/join.rs
- tests/logictest/suites/base/15_query/case_sensitivity/join.test
- tests/logictest/suites/base/15_query/join.test
> fix(planner): Fix case sensitivity of `USING` clause

- docs/doc/30-reference/30-sql/00-ddl/20-table/60-optimize-table.md
added doc for recluster final 
Fixes #issue
> docs: recluster final

- src/meta/raft-store/src/state_machine/sm.rs
- src/meta/raft-store/src/state_machine/sm_kv_api_impl.rs
- src/meta/raft-store/src/state_machine/testing.rs
- src/meta/raft-store/tests/it/state_machine/mod.rs
- src/meta/service/src/meta_service/meta_node_kv_api_impl.rs
- src/meta/service/tests/it/meta_node/meta_node_all.rs
- src/meta/service/tests/it/meta_node/meta_node_expire.rs
- src/meta/types/src/cmd.rs
- src/meta/types/src/lib.rs
> refactor(meta): introduce UpserKV to simplify meta command

- src/meta/api/src/kv_api_test_suite.rs
- src/meta/raft-store/tests/it/state_machine/mod.rs
- src/meta/types/src/cmd.rs
- src/meta/types/src/kv_message.rs
- src/meta/types/src/lib.rs
- src/meta/types/src/with.rs
> refactor(meta): simplify UpsertKV message

- docs/doc/30-reference/30-sql/20-query-syntax/dml-json-path.md
add doc for json path
Fixes #7348
> docs: add doc for json path

- docs/doc/30-reference/30-sql/20-query-syntax/dml-at.md
added doc for fuse_snapshot
Fixes #5942
> docs: fuse_snapshot

- docs/doc/30-reference/30-sql/00-ddl/20-table/10-ddl-create-table.md
Added doc for snapshot_location
Fixes #7303
> docs: create table with snapshot

- docs/doc/21-load-data/00-local.md
- docs/doc/21-load-data/01-s3.md
- docs/doc/21-load-data/04-remote.md
- docs/doc/30-reference/30-sql/10-dml/dml-copy-into-location.md
- docs/doc/30-reference/30-sql/10-dml/dml-copy-into-table-url.md
- docs/doc/30-reference/30-sql/10-dml/dml-copy-into-table.md
added support for NDJSON
Fixes #issue
> docs: add support for NDJSON

- README.md
- docs/doc/00-overview/index.md
Readme: change v0.8 to v0.9
Fixes #issue
> docs: readme:change v0.8 to v0.9

- .github/actions/publish_binary/action.yml
- .github/workflows/databend-release.yml
> ci: configure aws credentials with role instead of key

- docs/doc/30-reference/30-sql/80-setting-cmds/show-settings.md
Updated show settings
Fixes #issue
> docs: max_execute_time

- docs/doc/30-reference/20-functions/30-datetime-functions/addinterval.md
- docs/doc/30-reference/20-functions/30-datetime-functions/subtractinterval.md
- docs/doc/30-reference/20-functions/30-datetime-functions/timeslot.md
- docs/doc/30-reference/20-functions/30-datetime-functions/toMonth.md
- docs/doc/30-reference/20-functions/30-datetime-functions/todayofmonth.md
- docs/doc/30-reference/20-functions/30-datetime-functions/todayofweek.md
- docs/doc/30-reference/20-functions/30-datetime-functions/todayofyear.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tohour.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tominute.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tomonday.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tosecond.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tostartofday.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tostartoffifteenminutes.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tostartoffiveminutes.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tostartofhour.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tostartofisoyear.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tostartofminute.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tostartofmonth.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tostartofquarter.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tostartofsecond.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tostartoftenminutes.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tostartofweek.md
- docs/doc/30-reference/20-functions/30-datetime-functions/tostartofyear.md
- docs/doc/30-reference/20-functions/30-datetime-functions/toyear.md
- docs/doc/30-reference/20-functions/30-datetime-functions/toyyyymm.md
- docs/doc/30-reference/20-functions/30-datetime-functions/toyyyymmdd.md
- docs/doc/30-reference/20-functions/30-datetime-functions/toyyyymmddhhmmss.md
changed title to uppercase for data&time functions
Fixes #issue
> docs: uppercase titles

- src/query/service/src/interpreters/async_insert_queue.rs
- src/query/service/src/lib.rs
- src/query/service/tests/it/interpreters/async_insert_queue.rs
refactor(async_insert): eliminate circular references
Fixes #issue
> refactor(async_insert): eliminate circular references

- src/query/expression/src/util.rs
- src/query/expression/src/values.rs
- src/query/functions-v2/tests/it/scalars/mod.rs
Part of https://github.com/datafuselabs/databend/issues/6547
> fix(expr): support serde for Scalar::Array

- docs/doc/30-reference/00-api/02-clickhouse-handler.md
> doc(clickhouse handler): update port in examples.

- docs/doc/30-reference/30-sql/40-show/show-settings.md
- docs/doc/30-reference/30-sql/70-system-tables/system-settings.md
- src/common/io/src/format_settings.rs
modify docs about settings
Fixes part of #7318
> docs: modify settings doc

- docs/doc/30-reference/30-sql/90-explain-cmds/explain.md
added doc for EXPLAIN command
Fixes #issue
> docs: explain

- docs/doc/30-reference/20-functions/30-datetime-functions/todate.md
- docs/doc/30-reference/20-functions/30-datetime-functions/todatetime.md
added to_date and to_datetime
Fixes #7363
> docs: to_date and to_datetime

- docs/doc/30-reference/30-sql/40-show/_category_.json
- docs/doc/30-reference/30-sql/40-show/show-tables.md
- docs/doc/30-reference/30-sql/50-list/_category_.json
- docs/doc/30-reference/30-sql/60-kill/_category_.json
1. added examples for SHOW FULL TABLES
2. refactored the SHOW TABLES document with new examples and argument descriptions.
3. removed the [EXTENDED] option, as it is deprecated. 
4. fixed some title formats.
Fixes #7404
> docs: show full tables

- src/meta/service/tests/it/meta_node/meta_node_all.rs
- src/meta/service/tests/it/meta_node/meta_node_expire.rs
- src/meta/service/tests/it/meta_node/meta_node_kv_api.rs
- src/meta/service/tests/it/tests/meta_node.rs
- src/meta/service/tests/it/tests/mod.rs
> chore(meta-service-test): refactor MetaNode tests, nothing really changed

- .github/actions/publish_binary/databend-release-readme.txt
- .github/actions/publish_binary/databend-scripts-for-release/start.sh
This may not be a good practice, but it can provide more detailed information.
Fixes #issue
> chore(scripts): print logging to provide more detailed information.

- docs/doc/30-reference/40-Identifier/sql-identifiers.md
> docs: fix typo err

- src/query/service/src/lib.rs
- src/query/service/src/sql/optimizer/heuristic/decorrelate.rs
- src/query/service/src/sql/optimizer/heuristic/subquery_rewriter.rs
- src/query/service/src/sql/planner/binder/aggregate.rs
- src/query/service/src/sql/planner/binder/bind_context.rs
- src/query/service/src/sql/planner/binder/ddl/table.rs
- src/query/service/src/sql/planner/binder/join.rs
- src/query/service/src/sql/planner/binder/mod.rs
- src/query/service/src/sql/planner/binder/project.rs
- src/query/service/src/sql/planner/binder/select.rs
- src/query/service/src/sql/planner/binder/table.rs
- src/query/service/src/sql/planner/mod.rs
- src/query/service/src/sql/planner/semantic/grouping_check.rs
- src/query/service/tests/it/evaluator.rs
- src/query/service/tests/it/sql/planner/format/mod.rs
- tests/logictest/suites/base/15_query/join.test
- tests/logictest/suites/crdb/join
column reference is ambiguous in using
Related: https://github.com/datafuselabs/databend-perf/issues/72
> fix(planner): column reference is ambiguous in using

- docs/doc/30-reference/30-sql/00-ddl/10-database/ddl-create-database.md
- docs/doc/30-reference/30-sql/00-ddl/90-share/01-create-share.md
- docs/doc/30-reference/30-sql/00-ddl/90-share/02-drop-share.md
- docs/doc/30-reference/30-sql/00-ddl/90-share/03-alter-share.md
- docs/doc/30-reference/30-sql/00-ddl/90-share/04-desc-share.md
- docs/doc/30-reference/30-sql/00-ddl/90-share/05-show-shares.md
- docs/doc/30-reference/30-sql/00-ddl/90-share/06-grant-privilege.md
- docs/doc/30-reference/30-sql/00-ddl/90-share/07-revoke-privilege.md
- docs/doc/30-reference/30-sql/00-ddl/90-share/08-show-grants.md
- docs/doc/30-reference/30-sql/00-ddl/90-share/_category_.json
- docs/doc/30-reference/30-sql/00-ddl/90-share/index.md
> docs: add share docs

- src/query/functions/src/scalars/conditionals/in_basic.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/result_blocks.rs
- tests/logictest/suites/base/02_function/02_0045_conditional_function_in
- tests/logictest/suites/base/15_query/join.test
> fix(query): fix hashset capacity overflow

- src/meta/sled-store/src/sled_tree.rs
- src/meta/types/src/meta_storage_errors.rs
> chore(meta/error): remove MetaStorageError::SerdeError

- src/query/service/src/pipelines/executor/pipeline_executor.rs
- src/query/service/src/pipelines/executor/pipeline_pulling_executor.rs
fix(processor): cancel task when pipeline is finished
Fixes #7509
> fix(processor): cancel task when pipeline is finished

- docs/doc/30-reference/20-functions/111-system-functions/_category_.json
- docs/doc/30-reference/20-functions/111-system-functions/clustering_information.md
- docs/doc/30-reference/20-functions/111-system-functions/fuse_segment.md
- docs/doc/30-reference/20-functions/111-system-functions/fuse_snapshot.md
- docs/doc/30-reference/30-sql/20-query-syntax/dml-at.md
This PR adds these system functions:
- CLUSTERING_INFORMATION
- FUSE_SEGMENT
- FUSE_SNAPSHOT
One more system function **sync_stage_file** is missing as we're not very clear about how it works yet. Wu is helping investigating the code.
Fixes #7409
> docs: system functions

- src/query/ast/src/parser/token.rs
- src/query/service/src/sql/planner/mod.rs
Bug introduced in https://github.com/datafuselabs/databend/pull/7530
> fix(query): add missing EOI

- src/meta/client/src/grpc_action.rs
- src/meta/service/src/executor/action_handler.rs
- src/meta/service/src/version.rs
> refactor(meta-service): remove unused feature. update MIN_METACLI_SEMVER to 0.7.59

- .github/workflows/build-sqllogic.yml
- .github/workflows/databend-release.yml
- tests/logictest/Dockerfile
> ci: do not release sqllogic docker image

- tests/logictest/Dockerfile
> ci: add more dependencies for sqllogic test image

- tests/logictest/Dockerfile
> ci: fix dockerfile for sqllogic test

- .github/actions/test_sqllogic_cluster_linux/action.yml
- .github/actions/test_sqllogic_standalone_linux/action.yml
- .github/workflows/databend-release.yml
> ci: run sqllogic test with docker image

- tests/logictest/Dockerfile
> ci: pin mysql-connector-python==8.0.28 for sqllogic test

- src/query/functions-v2/src/scalars/string.rs
- src/query/functions-v2/tests/it/scalars/string.rs
- src/query/functions-v2/tests/it/scalars/testdata/string.txt
> feat(query): add function v2 repeat

- src/query/service/src/servers/mysql/mysql_federated.rs
- tests/logictest/suites/base/10_drivers/10_0003_federated_query
> feat(query): fed /*! SET xx */

- docs/doc/30-reference/30-sql/00-ddl/70-clusterkey/_category_.json
- docs/doc/30-reference/30-sql/00-ddl/70-clusterkey/index.md
Explained why clusterkey.
Fixes #7417
> docs: clusterkey index page

- docs/doc/60-contributing/03-rfcs/20220809-share.md
docs: refactor share rfc, add select from db and show tables SQL
Fixes #issue
> docs: refactor share rfc, add select from db and show tables SQL

- Cargo.lock
- src/common/contexts/Cargo.toml
- src/common/contexts/src/dal/dal_context.rs
- src/common/contexts/src/dal/dal_runtime.rs
- src/common/storage/Cargo.toml
- src/query/catalog/Cargo.toml
- src/query/config/Cargo.toml
- src/query/pipeline/sources/Cargo.toml
- src/query/service/Cargo.toml
- src/query/service/tests/it/storages/fuse/io.rs
- src/query/storages/fuse/Cargo.toml
- src/query/storages/hive/Cargo.toml
- src/query/storages/preludes/Cargo.toml
- src/query/storages/share/Cargo.toml
- src/query/streams/Cargo.toml
Bump OpenDAL to v0.17
- https://github.com/datafuselabs/opendal/discussions/687
Fix some tracing-related issues.
> feat: Bump OpenDAL to v0.17

- src/query/storages/hive/src/hive_table.rs
- src/query/storages/hive/src/hive_table_source.rs
> feat(hive): delay start the worker for simple select hive query

- tests/logictest/suites/mode/cluster/exchange.test
Fixes https://github.com/datafuselabs/databend/pull/7662
> chore: fix test in cluster mode

- docs/doc/30-reference/30-sql/10-dml/dml-copy-into-location.md
- docs/doc/30-reference/30-sql/10-dml/dml-copy-into-table.md
This PR includes minor fixes for copy into.
Fixes #issue
> docs: minor fixes for copy into

- docs/doc/30-reference/20-functions/111-system-functions/fuse_snapshot.md
> docs: update fuse_snapshot.md

- src/query/service/src/api/rpc/exchange/exchange_manager.rs
- src/query/service/src/api/rpc/exchange/statistics_receiver.rs
- tests/logictest/suites/base/03_dml/03_0028_copy_into_stage
fix(cluster): add statistics receiver runtime
fixes #7620
> fix(cluster): add statistics receiver runtime

- .github/actions/test_stateful_cluster_linux/action.yml
- .github/mergify.yml
- .github/workflows/dev-linux.yml
- scripts/ci/ci-run-stateful-tests-cluster-s3.sh
ci: Add stateful tests for cluster
Fix #7665
> ci: Add stateful tests for cluster

- .github/workflows/dev-linux.yml
ci: Fix Github Action can't use matrix in uses
> ci: Fix Github Action can't use matrix in uses

- tests/logictest/logictest.py
refactor: Print suite name before running
> refactor: Print suite name before running

- src/query/service/src/interpreters/interpreter_factory.rs
- src/query/service/src/interpreters/interpreter_factory_v2.rs
* Log the access denied to the file with the `Access.denied` error.
Fixes #7700
> chore(query): log the access denied query to log file

- Cargo.lock
- src/meta/types/Cargo.toml
- src/meta/types/src/lib.rs
- src/meta/types/src/user_setting.rs
- src/meta/types/src/user_stage.rs
- src/query/datavalues/tests/it/types/viewer.rs
- src/query/management/tests/it/setting.rs
- src/query/service/src/context_function.rs
- src/query/service/src/interpreters/interpreter_query_log.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/src/sessions/session.rs
- src/query/service/src/sql/planner/semantic/type_check.rs
- src/query/settings/Cargo.toml
- src/query/settings/src/lib.rs
- src/query/storages/preludes/src/system/settings_table.rs
- tests/fuse-compat/compat-logictest/fuse_compat_write
Fixes #issue
make user setting depend on a lightweight UserSettingValue  instead of DataValue.
It's meta compatible with before.
> chore(query): make user setting depend on a lightweight UserSettingValue

- tests/fuse-compat/compat-logictest/fuse_compat_write
> chore(query): Update fuse_compat_write

- Cargo.lock
- src/common/contexts/Cargo.toml
- src/common/storage/Cargo.toml
- src/query/catalog/Cargo.toml
- src/query/config/Cargo.toml
- src/query/pipeline/sources/Cargo.toml
- src/query/service/Cargo.toml
- src/query/storages/fuse/Cargo.toml
- src/query/storages/hive/Cargo.toml
- src/query/storages/preludes/Cargo.toml
- src/query/storages/share/Cargo.toml
- src/query/streams/Cargo.toml
Bumps OpenDAL to 0.17.1
Fixes #7707
> chore: Bump OpenDAL to v0.17.1

- docker/debian/meta.Dockerfile
- docker/distroless/meta.Dockerfile
> ci: release databend meta image with metactl

- src/common/exception/src/exception.rs
- src/query/config/src/outer_v0.rs
- src/query/formats/src/output_format.rs
- src/query/legacy-planners/src/plan_copy.rs
- src/query/management/src/stage/stage_mgr.rs
- src/query/service/src/api/rpc/flight_client.rs
- src/query/service/src/interpreters/interpreter_query_log.rs
- src/query/service/src/sql/planner/plans/copy_v2.rs
- src/query/service/src/sql/statements/value_source.rs
- src/query/service/tests/it/servers/mysql/mysql_handler.rs
- src/query/storages/fuse/src/operations/operation_log.rs
- src/query/storages/util/src/retry.rs
chore(base): support error type for result
Fixes #issue
> chore(base): support error type for result

- src/query/service/src/servers/mysql/mysql_handler.rs
> chore(query): add logs when create session failed

- Cargo.lock
- src/query/settings/Cargo.toml
- src/query/settings/src/lib.rs
fixes(settings): fix server hang when concurrent requests http auth
Fixes #issue
> fix(settings): fix server hang when concurrent requests http auth

- docs/doc/30-reference/30-sql/80-setting-cmds/show-settings.md
added sql dialect setting to SHOW SETTINGS
Fixes #issue
> docs: add sql dialect

- src/common/jsonb/src/value.rs
- src/common/jsonb/tests/it/parser.rs
- src/query/functions-v2/src/scalars/variant.rs
> refactor(function): eliminate an allocation in parse_json()

- docs/doc/30-reference/20-functions/111-system-functions/fuse_block.md
> docs: fuse block updates

- scripts/setup/rust-toolchain.toml
> chore: upgrade build-tool to nightly-2022-09-18

- src/query/planner/src/metadata.rs
- src/query/service/src/sql/planner/metadata.rs
- src/query/service/src/sql/planner/mod.rs
- src/query/service/src/sql/planner/optimizer/heuristic/prune_columns.rs
refactor: Planner Code Cleanup
Code Cleanup
> refactor: Planner Code Cleanup

- src/query/pipeline/core/src/processors/processor.rs
- src/query/service/src/pipelines/executor/executor_graph.rs
- src/query/service/src/pipelines/executor/executor_worker_context.rs
- src/query/service/src/pipelines/executor/processor_async_task.rs
Reverts datafuselabs/databend#7486
```
MySQL [(none)]> select count() from numbers(1000000000) ;
+------------+
| count()    |
+------------+
| 1000000000 |
+------------+
1 row in set (0.031 sec)
MySQL [(none)]> select count() from numbers(1000000000) ;
+------------+
| count()    |
+------------+
| 1000000000 |
+------------+
1 row in set (0.234 sec)
```
> refactor(executor): reverts #7486

- src/query/functions/src/scalars/logics/and.rs
> refactor(query): fix index error

- src/meta/raft-store/src/state_machine/sm.rs
- src/meta/service/src/api/grpc/grpc_service.rs
- src/meta/service/src/meta_service/meta_leader.rs
- src/meta/types/src/applied_state.rs
- src/meta/types/src/change.rs
- src/meta/types/src/cmd.rs
- src/meta/types/src/log_entry.rs
- src/query/service/src/sql/executor/physical_plan_builder.rs
- src/query/service/src/storages/storage_table_read_plan.rs
> chore: minor refactor for extract_scan_fields_from_projection(); cleanup info log

- .github/actions/setup_docker/action.yml
- .github/workflows/databend-release.yml
> ci: publish service image to acr

- src/query/storages/fuse/src/pruning/bloom_pruner.rs
hot fix: disable bloom filter; by using dummy filter only
Fixes #7780
> fix: disable bloom filter

- .github/actions/setup_docker/action.yml
- .github/workflows/databend-release.yml
> ci: fix special char in acr login password

- src/query/datavalues/Cargo.toml
- src/query/functions-v2/Cargo.toml
Fix https://github.com/datafuselabs/databend/issues/7793
But I don't know why our CI doesn't detect this.
> fix: functions-v2 failed to build after bump

- scripts/setup/rust-tools.txt
ci: Bump version of rust tools
> ci: Bump version of rust tools

- Cargo.lock
- src/query/catalog/Cargo.toml
- src/query/catalog/src/lib.rs
- src/query/catalog/src/table.rs
> refactor: Cleanup Table trait

- website/docusaurus.config.js
> docs: List all blog at once

- src/query/service/src/pipelines/executor/pipeline_pulling_executor.rs
- src/query/service/src/sessions/session.rs
- src/query/service/tests/it/servers/http/http_query_handlers.rs
- src/query/service/tests/it/tests/sessions.rs
fix(test): try fix unit test failure
Fixes #issue
> fix(test): try fix unit test failure

- src/query/service/src/servers/mysql/mysql_federated.rs
pt-archive compatibility
pt-archive compatibility
> fix: mysql pt-archive compatibility

- Cargo.lock
- src/common/http/Cargo.toml
- src/meta/service/Cargo.toml
- src/query/service/Cargo.toml
fix: Remove out dated typed-headers dep
> fix: Remove out dated typed-headers dep

- src/meta/service/src/store/store_bare.rs
When adding replications to non-voter(learner), avoid loading membership
from log but just load it from state machine.
Non-committed membership that ony resides in log should not be
considered.
Only committed(applied to statemachine) membership should be used.
- #7878 
Scanning logs for membership slows down meta-rpc slightly.
> refactor(meta): load membership from statemachine instead of from log and statemachine

- src/query/service/src/sql/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
- tests/logictest/suites/crdb/join
> fix: filter push down for left/right join

- docs/doc/30-reference/30-sql/10-dml/dml-copy-into-table.md
This PR updates documentation about the usage of AWS S3 session token.
> docs: update documentations on temporary credential

- src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/join_hash_table.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/result_blocks.rs
- src/query/service/src/pipelines/processors/transforms/mod.rs
- src/query/service/src/pipelines/processors/transforms/transform_right_semi_anti_join.rs
- src/query/service/src/sql/executor/physical_plan.rs
- src/query/service/src/sql/executor/pipeline_builder.rs
- tests/logictest/suites/crdb/join
> feat(planner): support right semi/anti join

- src/query/service/src/sql/planner/optimizer/heuristic/prune_unused_columns.rs
- tests/logictest/suites/base/03_dml/03_0029_both_select_where_constant
Fix such case:
```sql
select 1 from t where 1; 
```
An addition to #7955.
> fix: fix bugs in finding smallest column for pruning unused columns.

- src/query/storages/fuse/src/operations/gc.rs
fix(processor): try fix cannot kill drop table
Fixes #7961
> fix(processor): try fix cannot kill drop table

- src/common/base/src/containers/pool.rs
- src/common/base/tests/it/main.rs
- src/common/base/tests/it/pool_retry.rs
Signed-off-by: Jun Zhang <jun@junz.org>
Fixes #3469
> refactor: Add a field in Pool to specify the retry times

- src/query/service/tests/it/storages/system/settings_table.rs
- src/query/service/tests/it/storages/system/testdata/settings.txt
1.  better diff
2.  no need for escape.
Fixes #issue
> refactor(settings): use golden file in unit test.

- src/query/service/tests/it/storages/system/testdata/settings.txt
- src/query/settings/src/lib.rs
1. use quote for strings
2. add `.`  at the end.
Fixes #issue
> chore(settings): unify formats of setting descriptions.

- src/query/expression/tests/it/expression.rs
- src/query/expression/tests/it/testdata/run-pass.txt
- src/query/expression/tests/it/testdata/tyck-fail.txt
- src/query/functions-v2/src/scalars/comparison.rs
- src/query/functions-v2/tests/it/scalars/testdata/comparison.txt
- refactor comparision functions
- fix unit test failure on main
> fix(query): reorder comparision funciton priority

- website/docusaurus.config.js
- website/src/pages/index.tsx
> docs: refine the slogan

- src/meta/raft-store/src/state_machine/sm.rs
- src/meta/raft-store/src/state_machine/snapshot.rs
- src/meta/service/src/store/store_bare.rs
> feat(meta/store): add snapshot_id codec support

- Cargo.lock
Fix https://github.com/datafuselabs/databend/issues/8008
> fix: Fix build broken by opendal

- src/common/base/src/base/catch_unwind.rs
- src/common/base/src/base/runtime.rs
- src/common/base/src/lib.rs
- src/query/service/src/interpreters/interpreter_common.rs
- src/query/service/src/interpreters/interpreter_copy_v2.rs
- src/query/service/src/interpreters/interpreter_insert_v2.rs
- src/query/settings/src/lib.rs
- src/query/storages/fuse/src/pruning/pruning_executor.rs
chore(executor): try remove some futures executor block on
Fixes #issue
> chore(executor): try remove some futures executor block on

- scripts/ci/ci-run-stateless-tests-cluster.sh
chore(test): don't skip 13_0005_q5 test
Fixes #issue
> chore(test): don't skip 13_0005_q5 test

- src/query/service/src/sql/planner/optimizer/rule/transform/rule_commute_join.rs
- src/query/service/src/sql/planner/plans/logical_join.rs
- tests/logictest/suites/crdb/join
- tests/logictest/suites/mode/standalone/explain/join_reorder/chain.test
- tests/logictest/suites/mode/standalone/explain/select_limit_offset.test
We have supported right join, right semi join, right anti join, so it's time to enable join commute rule for those join types
Fixes #issue
> feat: enable join commute for more join types

- tests/logictest/Dockerfile
- tests/logictest/README.md
- tests/logictest/requirements.txt
update mysql.connector version
Fixes #8038
> fix(ci): update mysql.connector version

- tests/logictest/Dockerfile
> fix(ci): update dockerfile

- Cargo.lock
- src/meta/protos/Cargo.toml
- src/meta/protos/build.rs
Fixes https://github.com/datafuselabs/databend/issues/8035
> fix: Build failure on newer versions of protoc

- src/meta/raft-store/src/state_machine/mod.rs
- src/meta/raft-store/src/state_machine/sm.rs
- src/meta/raft-store/src/state_machine/snapshot.rs
- src/meta/raft-store/src/state_machine/snapshot_id.rs
- src/meta/raft-store/tests/it/state_machine/mod.rs
- src/meta/service/src/store/store_bare.rs
> refactor(meta/service): structured snapshot id

- scripts/setup/dev_setup.sh
> feat(ci): update dev setup tools

- scripts/setup/dev_setup.sh
Reverts datafuselabs/databend#8057
> Revert "feat(ci): update dev setup tools"

- .github/workflows/databend-release.yml
Not yet verified, logically, it provides us with the ability to upload checksums
Fixes #6700
> chore(ci): try to upload checksums

- src/meta/types/src/user_stage.rs
> chore(format): fix error msg about unsupported input formats.

- src/meta/raft-store/src/log/raft_log.rs
- src/meta/raft-store/src/state/raft_state.rs
- src/meta/types/src/errors/meta_storage_errors.rs
- src/meta/types/src/lib.rs
> chore(meta/error): remove MetaStorageResult; use Result<, MetaStorageError>;

- src/query/service/src/pipelines/processors/transforms/hash_join/join_hash_table.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/result_blocks.rs
- tests/logictest/suites/base/20+_others/20_0001_planner_v2
> fix: right semi join returns wrong answer

- src/query/service/src/servers/http/clickhouse_handler.rs
> fix(clickhouse_handler): wrong slice end in gen_batches().

- src/meta/proto-conv/src/config_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/user_from_to_protobuf_impl.rs
- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/user_proto_conv.rs
- src/meta/proto-conv/tests/it/user_stage.rs
- src/meta/protos/proto/config.proto
- src/meta/protos/proto/user.proto
- src/query/config/src/outer_v0.rs
- src/query/service/tests/it/configs.rs
- src/query/service/tests/it/storages/testdata/system-tables.txt
This PR implements stage support for Aliyun Object Storage Service
Fixes: #8081 #8082
> feat: oss backend support

- website/blog/2022-08-08-benchmark-tpc-h.md
Fixes https://github.com/datafuselabs/databend/issues/8094
> docs(tpch): add prefix 'format_' for settings used in streaming_load.

- src/query/service/src/pipelines/executor/pipeline_executor.rs
Fixes https://github.com/datafuselabs/databend/issues/7839
> chore(pipeline): append message "while in processor thread" only in Trace level

- src/query/service/src/interpreters/fragments/v2/fragmenter.rs
- src/query/service/src/interpreters/fragments/v2/plan_fragment.rs
- src/query/service/src/storages/stage/stage_table_sink.rs
> chore(unload): update max_file_size from 5G to 64M.

- docs/doc/21-load-data/00-local.md
- docs/doc/30-reference/30-sql/00-ddl/80-presign/presign.md
Updated Presign by https://datafuselabs.feishu.cn/wiki/wikcnF1xA2lB5i4qXj7pl4x3tfc
Fixes #issue
> docs: presign updates

- docs/doc/30-reference/30-sql/10-dml/dml-copy-into-location.md
Added copyOptions paramters, SINGLE + MAX_FILE_SIZE.
Fixes #issue
> docs: unload copyoptions

- scripts/ci/ci-run-stateful-tests-cluster-s3.sh
chore(test): uncomment skip test
related #8113
> chore(test): uncomment skip test

- .editorconfig
- .licenserc.yaml
chore: Add editorconfig for databend
> chore: Add editorconfig for databend

- src/query/catalog/src/table.rs
- src/query/service/src/sql/planner/binder/table.rs
- src/query/service/src/table_functions/numbers_table.rs
- src/query/storages/fuse/src/fuse_table.rs
- src/query/storages/hive/src/hive_table.rs
- src/query/storages/preludes/src/system/tables_table.rs
outlines the table column statistics api
Fixes #8151
> feat: table column statistics api

- Cargo.lock
Bump to opendal to 0.19.2
https://github.com/datafuselabs/opendal/discussions/859
> feat: Bump to opendal to 0.19.2

- scripts/ci/ci-run-stateless-tests-cluster.sh
Need time to solve the flakey test, let's skip it temporarily.
Fixes #issue
> chore(test): skip tpch q4 in cluster mode

- Cargo.lock
Fix https://github.com/datafuselabs/databend/issues/8188
> fix: Write could panic during retry

- src/common/storage/src/operator.rs
fix: Make sure check is called inside global io runtime
Fix https://github.com/datafuselabs/databend/issues/8224
> fix: Make sure check is called inside global io runtime

- Cargo.lock
feat(storage): Enable DNS Cache for opendal
Fix https://github.com/datafuselabs/databend/issues/8234
> feat(storage): Enable DNS Cache for opendal

- src/query/service/src/sessions/session_mgr.rs
fix(sessions): fix dead lock when force kill sessions
Fixes #issue
> fix(sessions): fix dead lock when force kill sessions

- src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/right_mark.rs
- src/query/service/src/pipelines/processors/transforms/hash_join/result_blocks.rs
fix(processor): support abort for right mark join
part #8028
> fix(processor): support abort for right mark join

- docs/doc/30-reference/20-functions/30-datetime-functions/now.md
- src/query/expression/src/date_helper.rs
- src/query/functions-v2/src/scalars/datetime.rs
- now
- today
- yesterday
- tomorrow
Part of #8048
> feat(query): migrate real time functions to v2.

- src/query/storages/fuse/src/fuse_table.rs
- src/query/storages/fuse/src/operations/append.rs
- src/query/storages/fuse/src/operations/compact.rs
- src/query/storages/fuse/src/operations/read.rs
- src/query/storages/fuse/src/operations/read_partitions.rs
- src/query/storages/fuse/src/operations/recluster.rs
> chore: add more debug log to measure the time cost

- src/query/storages/fuse/src/io/files.rs
- src/query/storages/fuse/src/io/mod.rs
- src/query/storages/fuse/src/io/segments.rs
- src/query/storages/fuse/src/io/snapshots.rs
- src/query/storages/fuse/src/lib.rs
- src/query/storages/fuse/src/operations/gc.rs
- src/query/storages/fuse/src/operations/mutation/compact_mutator.rs
- src/query/storages/fuse/src/table_functions/fuse_blocks/fuse_block.rs
- src/query/storages/fuse/src/table_functions/fuse_segments/fuse_segment.rs
- src/query/storages/fuse/src/table_functions/fuse_snapshots/fuse_snapshot.rs
**Move IO related files from `src/` to `src/io`**
Fixes #issue
> chore: refine the fuse io files

- docs/doc/30-reference/30-sql/00-ddl/20-table/60-optimize-table.md
added tips for OPTIMIZE TABLE T PURGE
Fixes #8185
> docs: purge tips

- docs/doc/30-reference/30-sql/20-query-syntax/dml-join.md
- full outer join
- left semi/anti join
- right semi/anti join
Fixes #issue
> docs: joins

- src/query/expression/src/values.rs
- src/query/expression/tests/it/convert.rs
> refactor(expression): fix scalar repeat

- .github/actions/test_sqllogic_cluster_linux/action.yml
- .github/actions/test_sqllogic_standalone_linux/action.yml
> ci: add ulimit nofile for sqllogic test

- src/query/functions-v2/src/scalars/comparison.rs
The find cost 840.270221ms is faster than the contains cost 1.487372717s. Use find.
```rust
➜  ~/database/source-code/hello👆 git:(master) ⚡ cat src/main.rs
use std::time::Instant;
fn main() {
let needle = (0..100).map(|_| "b").collect::<String>();
let heystack = (0..100_000).map(|_| "a").collect::<String>();
println!("Data ready.");
let now = Instant::now();
for _ in 0..1_000_000 {
if heystack.find(&needle).is_some() { }
}
let ned = Instant::now();
println!("cost:{:?}", ned-now);
}
➜  ~/database/source-code/hello👆 git:(master) ⚡ cargo run -r          
Finished release [optimized] target(s) in 0.00s
Running `target/release/hello`
Data ready.
cost:840.270221ms
➜  ~/database/source-code/hello👆 …
```
> feat(query): modify function-v2 comparison like

- .github/actions/test_sqllogic_cluster_linux/action.yml
- .github/actions/test_sqllogic_standalone_linux/action.yml
- scripts/ci/ci-run-sqllogic-tests-cluster.sh
- scripts/ci/ci-run-sqllogic-tests.sh
> chore: check ulimit in sqllogic test

- src/query/storages/fuse/src/table_functions/fuse_blocks/fuse_block.rs
add fuse_block output row_count
> chore: add fuse_block output row_count

- src/query/pipeline/core/src/processors/resize_processor.rs
- src/query/service/tests/it/pipelines/processors/resize.rs
fix(processor): try fix data lost when resize multi outputs
Fixes #issue
> fix(processor): try fix data lost when resize multi outputs

- src/meta/api/src/schema_api_impl.rs
- src/query/service/src/interpreters/interpreter_copy_v2.rs
- tests/suites/1_stateful/00_copy/00_0000_copy_from_s3_location.sh
This reverts commit 4a99f21be2523eddeda37a6033d8d9a6652cef36, reversing changes made to bb8a27be8cd3c616ca57ef76419a275e2cb55096.
> fix: Stateful tests copy from s3 location will hang

- src/query/management/src/user/user_mgr.rs
- src/query/management/tests/it/user.rs
Fixes [#8155 ](https://github.com/datafuselabs/databend/issues/8155)
> feat: forbid creation of user with builtin username

- src/common/arrow/Cargo.toml
> feat(query): enable gzip_zlib_ng feature to have maximum performance 

- src/query/pipeline/core/src/processors/port.rs
- src/query/pipeline/transforms/src/processors/transforms/transform_compact.rs
fix(processor): try fix lost last message if finish at same time
Fixes #issue
> fix(processor): try fix lost last message if finish at same time

- docs/doc/10-deploy/02-deploying-databend.md
> docs: fix deploy

- Cargo.lock
- scripts/setup/rust-tools.txt
- src/binaries/Cargo.toml
- src/query/ast/fuzz/Cargo.toml
- src/query/config/Cargo.toml
- src/query/storages/index/Cargo.toml
- src/query/streams/Cargo.toml
> ci: Install cargo machete

- Cargo.lock
- src/query/service/src/catalogs/default/mutable_catalog.rs
- src/query/service/src/databases/default/default_database.rs
- src/query/service/src/databases/share/share_database.rs
- src/query/service/src/sessions/query_ctx.rs
- src/query/service/src/sessions/query_ctx_shared.rs
- src/query/service/tests/it/tests/context.rs
- src/query/storages/util/Cargo.toml
- src/query/storages/util/src/storage_context.rs
remove unused meta from StorageContext
Fixes #issue
> refactor(storages): remove unused meta from StorageContext

- .github/actions/check/action.yml
- scripts/setup/dev_setup.sh
- scripts/setup/rust-tools.txt
- src/workspace-hack/Cargo.toml
> ci: Let's use cargo machete

- .github/actions/check/action.yml
ci: Move the slowest task to the end of check list
> ci: Move the slowest task to the end of check list

- Cargo.lock
- src/query/service/src/catalogs/default/catalog_context.rs
- src/query/service/src/catalogs/default/mutable_catalog.rs
- src/query/service/src/databases/database_context.rs
- src/query/service/src/databases/default/default_database.rs
- src/query/service/src/databases/share/share_database.rs
- src/query/service/tests/it/tests/context.rs
- src/query/storages/context/Cargo.toml
- src/query/storages/context/src/context.rs
- src/query/storages/preludes/src/memory/memory_table.rs
refactor: Move in memory data out of storage context
> refactor: Move in memory data out of storage context

- src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/left_join.rs
fix(processor): fix full join panic
#8325
> fix(processor): fix full join panic

- src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_parquet.rs
- src/query/pipeline/sources/src/processors/sources/input_formats/input_format_text.rs
- src/query/pipeline/sources/src/processors/sources/input_formats/input_pipeline.rs
- src/query/pipeline/sources/src/processors/sources/input_formats/source_aligner.rs
- src/query/pipeline/sources/src/processors/sources/input_formats/source_deserializer.rs
Fixes https://github.com/datafuselabs/databend/issues/8178
> feat(input format): scan progress of copy into and streaming load.

- docs/doc/30-reference/30-sql/30-query-operators/operators-subquery.md
> docs: IN NOT IN subquery

- src/query/service/src/servers/http/v1/query/http_query.rs
- tests/logictest/clickhouse_connector.py
> fix(http handler): return session if request.session is null.

- src/query/storages/fuse/src/operations/fuse_source.rs
- src/query/storages/fuse/src/operations/mod.rs
- src/query/storages/fuse/src/operations/read_data.rs
> chore: move out FuseTableSource to fuse_source.rs from read_data.rs

- docs/doc/30-reference/30-sql/30-query-operators/operators-subquery.md
Added ANY and SOME to subquery
Fixes #issue
> docs: subquery ANY and SOME

- docs/doc/30-reference/30-sql/30-query-operators/operators-subquery.md
Added ALL to subquery.
Fixes #8297
> docs: subquery ALL

- Cargo.lock
- src/common/storage/Cargo.toml
- src/common/storage/src/metrics.rs
- src/common/storage/src/runtime_layer.rs
fix: OpenDAL layers doesn't pass not implemented methods correctly
> fix: OpenDAL layers doesn't pass not implemented methods correctly

- Cargo.lock
- src/query/datablocks/Cargo.toml
- src/query/datablocks/src/data_block.rs
- src/query/datablocks/src/lib.rs
- src/query/datablocks/src/meta_info.rs
> feat: Add metainfo in datablock

- src/query/sql/src/planner/plans/logical_join.rs
- tests/logictest/suites/mode/standalone/explain/join_reorder/star.test
Fixes #8219 #8413 https://github.com/datafuselabs/databend/issues/7587
> fix(planner): adjust join cardinality

- src/query/sql/src/planner/optimizer/heuristic/prune_unused_columns.rs
- src/query/sql/src/planner/optimizer/property/property.rs
- src/query/sql/src/planner/plans/aggregate.rs
- src/query/sql/src/planner/plans/dummy_table_scan.rs
- src/query/sql/src/planner/plans/eval_scalar.rs
- src/query/sql/src/planner/plans/filter.rs
- src/query/sql/src/planner/plans/limit.rs
- src/query/sql/src/planner/plans/logical_get.rs
- src/query/sql/src/planner/plans/logical_join.rs
- src/query/sql/src/planner/plans/union_all.rs
- tests/logictest/suites/mode/standalone/explain/prune_column.test
> fix(planner): Remove unnecessary required columns

- src/binaries/metactl/snapshot.rs
- tests/metactl/test-metactl.sh
> feat(metactl): support export from hostname

- docs/doc/30-reference/20-functions/111-system-functions/fuse_block.md
- docs/doc/30-reference/20-functions/111-system-functions/fuse_segment.md
- docs/doc/30-reference/20-functions/111-system-functions/fuse_snapshot.md
- docs/doc/30-reference/30-sql/00-ddl/20-table/60-optimize-table.md
> docs: more table optimization

- Cargo.lock
- src/query/datavalues/Cargo.toml
- src/query/datavalues/src/data_value.rs
- src/query/datavalues/src/variant_value.rs
- src/query/storages/fuse-meta/Cargo.toml
- src/query/storages/fuse-meta/src/meta/common.rs
- src/query/storages/fuse-meta/src/meta/v0/segment.rs
- src/query/storages/fuse-meta/src/meta/v1/segment.rs
- src/query/storages/fuse/Cargo.toml
- src/query/storages/fuse/src/operations/mutation/compact_mutator/full_compact_mutator.rs
> refactor(query): revert #8444

- src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs
Add a barrier to ensure all of the logs are applied before node quit.
Otherwise the next time node-2 starts it can not see the applied
membership and believes it has not yet joined into a cluster.
> chore(meta): fix flaky test `test_meta_node_join_with_state()`

- Cargo.lock
- src/meta/service/Cargo.toml
- src/meta/service/src/configs/outer_v0.rs
- src/query/config/Cargo.toml
- src/query/config/src/outer_v0.rs
fix: Throw errors while loading config failed
> fix: Throw errors while loading config failed

- Cargo.lock
- src/meta/raft-store/Cargo.toml
- src/meta/raft-store/tests/it/log.rs
- src/meta/raft-store/tests/it/state.rs
- src/meta/raft-store/tests/it/state_machine/mod.rs
- src/meta/raft-store/tests/it/state_machine/schema_api_impl.rs
- src/meta/raft-store/tests/it/testing.rs
> chore(meta/raft-store): fix span usage for tests

- src/binaries/meta/main.rs
- src/binaries/metactl/main.rs
- src/common/tracing/src/logging.rs
- src/meta/raft-store/tests/it/testing.rs
- src/meta/sled-store/tests/it/testing/mod.rs
And change tracing log dir
Fixes #issue
> chore: enable tracing log layer with env

- src/query/service/src/servers/mysql/mysql_federated.rs
support mysqldump 5.7.16
result :
```shell
build git:(mysql-5.7.16) ⚡ ./client/mysqldump  --user=u1 --password=123 --host=xx --port 3308 --set-gtid-purged=off --skip-triggers -t --where='k=1'  test t
mysqldump: [Warning] Using a password on the command line interface can be insecure.
-- MySQL dump 10.13  Distrib 5.7.16, for Linux (x86_64)
--
-- Host: xx    Database: test
-- ------------------------------------------------------
-- Server version	8.0.26-v0.8.43-nightly-d3422a8(rust-1.66.0-nightly-2022-10-26T11:30:33.768812168Z)
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET …
```
> feat(query): fed mysqldump 5.7.16 /*!code query

- src/query/functions/src/scalars/arithmetics/arithmetic_div.rs
- src/query/functions/tests/it/scalars/arithmetics.rs
- src/query/legacy-expression/tests/it/monotonicity.rs
- tests/logictest/suites/crdb/and_or
select 3/to_nullable(null) will return null
Fixes #8480
> fix(query): div nullable(Int) with null value should not err

- src/query/settings/Cargo.toml
- src/query/settings/src/lib.rs
- src/query/storages/hive/src/hive_block_filter.rs
- src/query/storages/hive/src/hive_blocks.rs
- src/query/storages/hive/src/hive_parquet_block_reader.rs
- src/query/storages/hive/src/hive_table.rs
- src/query/storages/hive/src/hive_table_source.rs
- src/query/storages/hive/src/lib.rs
- src/query/storages/index/src/range_filter.rs
1. get column stats from parquet file
2. use range filter to do the predict
original committed by lizhenwei
> feat(hive): hive predict pushdown

- scripts/ci/deploy/config/databend-query-node-1.toml
- scripts/ci/deploy/config/databend-query-node-2.toml
- scripts/ci/deploy/config/databend-query-node-3.toml
Fixes https://github.com/datafuselabs/databend/issues/8448
> chore: change databend query config address to endpoints

- src/query/service/src/api/rpc/exchange/exchange_manager.rs
fix: Move flight service client init to global io runtime
Related to https://github.com/datafuselabs/databend/issues/7986
Hyper client's connection is created upon runtime. If we start a HTTP client in current runtime (like query context runtime), this client could be dropped too early.
This PR is just for a non-harmful try. The root cause of #7986 is not identified.
> fix: Move flight service client init to global io runtime

- src/meta/proto-conv/src/util.rs
- src/meta/proto-conv/tests/it/user_stage.rs
> fix(meta): META_CHANGE_LOG add v18.

- docs/doc/30-reference/30-sql/40-show/show-settings.md
- docs/doc/30-reference/30-sql/70-system-tables/system-settings.md
- docs/doc/30-reference/30-sql/80-setting-cmds/show-settings.md
- src/query/ast/src/input.rs
- src/query/service/tests/it/storages/testdata/system-tables.txt
- src/query/settings/src/lib.rs
> feat(hive): add hive dialect

- Cargo.lock
- src/query/storages/index/Cargo.toml
> chore(filter): track xor-filter repo with tag

- src/query/ast/src/parser/expr.rs
- src/query/ast/src/parser/token.rs
- src/query/ast/tests/it/testdata/expr-error.txt
- src/query/functions-v2/src/scalars/comparison.rs
- src/query/functions-v2/src/scalars/string.rs
- src/query/functions-v2/tests/it/scalars/string.rs
- src/query/functions-v2/tests/it/scalars/testdata/string.txt
> feat(query): substr alias as substring

- src/meta/service/src/meta_service/raftmeta.rs
> chore(meta): avoid panic by treating error returned from an older version as string
