databendlabs/databend

common/datablocks/src/kernels/data_block_filter.rs
common/datablocks/tests/it/kernels/data_block_filter.rs
query/src/interpreters/interpreter_delete.rs
query/src/storages/fuse/io/read/block_reader.rs
query/src/storages/fuse/operations/mod.rs
query/src/storages/fuse/operations/mutation/block_filter.rs
query/src/storages/fuse/operations/mutation/mutations_collector.rs
tests/suites/0_stateless/03_dml/03_0025_delete_from.result
tests/suites/0_stateless/03_dml/03_0025_delete_from.sql
tests/suites/0_stateless/03_dml/03_0025_delete_from_v2.result
tests/suites/0_stateless/03_dml/03_0025_delete_from_v2.sql

fixing issue 
- https://github.com/datafuselabs/databend/issues/6275
by inverse the result of filter result, instead of the filter expression.
~~~sql
mysql> create table t(c int null);
Query OK, 0 rows affected (0.06 sec)
mysql> insert into t values(1), (2), (NULL);
Query OK, 0 rows affected (0.06 sec)
mysql> delete from t where c=1;
Query OK, 0 rows affected (0.06 sec)
mysql> select * from t;
+------+
| c    |
+------+
|    2 |
| NULL |
+------+
2 rows in set (0.03 sec)
Read 2 rows, 8.00 B in 0.006 sec., 346.05 rows/sec., 1.35 KiB/sec.
mysql> delete from t where c is null;
mysql> select * from t;
+------+
| c    |
+------+
|    2 |
+------+
1 row in set (0.06 …

fix: deletion of null values

---

docs/doc/70-performance/07-volcengine-tos-performance.md

Fix link 404 of volcengine ecs. ref: https://databend.rs/doc/performance/volcengine-tos-performance
Fixes #issue

[doc ] fix link 404 of volcengine ecs

---

.github/actions/build_linux/action.yml
.github/workflows/databend-release.yml
Cargo.lock
common/base/Cargo.toml

Reverts datafuselabs/databend#6268
The musl binary does not work properly with the new rustflags enabled

Revert "chore: try to bump jemalloc and fix musl link"

---

common/tracing/src/logging.rs
query/bin/databend-query.rs

feat: support to configure jaeger agent endpoint for tracing on databend-query

---

query/bin/databend-query.rs

Add some high cardinal tags for sentry to track on problem
1. tenant
2. cluster id
3. flight address
- Improvement
Fixes #issue

chore: add default tags for sentry

---

scripts/setup/rust-toolchain.toml

ci: Bump rust toolchain of build tools
Part of https://github.com/datafuselabs/databend/pull/6375

ci: Bump rust toolchain of build tools

---

scripts/setup/rust-toolchain.toml

This reverts commit 3a90b72c738f424b159a16ce94ca3288bd6a0a40.
Revert "ci: Bump rust toolchain of build tools"

Revert "ci: Bump rust toolchain of build tools"

---

common/ast/src/ast/statements/statement.rs
common/ast/src/parser/mod.rs
common/ast/src/parser/statement.rs
common/ast/tests/it/parser.rs
common/ast/tests/it/testdata/statement-error.txt
common/ast/tests/it/testdata/statement.txt
query/src/servers/http/clickhouse_handler.rs
query/src/servers/http/v1/query/execute_state.rs
query/src/sql/planner/binder/copy.rs
query/src/sql/planner/binder/show.rs
query/src/sql/planner/binder/table.rs
query/src/sql/planner/mod.rs
query/tests/it/interpreters/interpreter_table_create.rs
query/tests/it/interpreters/interpreter_table_show_create.rs
query/tests/it/sql/optimizer/heuristic/mod.rs

Actually we have three ideas:
1. For every should support format cause's query modify the planner but that will modify so many planner code.
2. In clickhouse handler token the SQL and use nom cut the FORMAT keyword and then get the format value. But it has a bad case like this: select `format` from default.`format` format xxx;
3. In this pr, all of the statement is #statment_body and the format is always at the last of the statement body. So we just need to modify the final rule.
- New Feature
Fixes #6298

show query support format

---

.github/workflows/databend-auto-tag.yml

ci: Fix databend release auto tag
This PR will generate correctly nightly tags for databend

ci: Fix databend release auto tag

---

Cargo.lock
common/meta/app/Cargo.toml
common/meta/sled-store/Cargo.toml
common/meta/types/Cargo.toml
tools/metactl/Cargo.toml

Fix: datafuselabs/openraft#424 wrong range when searching for membership entries: `[end-step, end)`.
The iterating range searching for membership log entries should be
`[end-step, end)`, not `[start, end)`.
With this bug it will return duplicated membership entries.
- Bug: datafuselabs/openraft#424
- Bug Fix

fix(metasrv): openraft: wrong range when searching for membership entries

---

.github/mergify.yml

ci: Add post checks for CLA and Semantic PR

ci: Add post checks for CLA and Semantic PR

---

.github/actions/build_linux/action.yml
.github/actions/build_linux_hive/action.yml
.github/actions/build_macos/action.yml
.github/actions/check/action.yml
.github/actions/test_unit/action.yml

This PR is a reply to [Call for testing: Cargo sparse-registry](https://blog.rust-lang.org/2022/06/22/sparse-registry-testing.html)
We will test:
- Whether sparse-registry works correctly
- If sparse-registry faster than git-based registry
- If sparse-registry works well with many git deps (we have about 15 git deps).
Let's go!

ci: Enable cargo sparse-registry

---

query/src/formats/output_format.rs
query/src/formats/output_format_json_each_row.rs
tests/suites/0_stateless/14_clickhouse_http_handler/14_0002_select_formats.result
tests/suites/0_stateless/14_clickhouse_http_handler/14_0002_select_formats.sh

- 2 basic dimensions:
-  STRINGS:  if true, write quoted string for all type of values.
-  COMPACT: true/false ->use array/dict for each row,
-  COMPACT formats  have extension types withNames and withNameAndFormats.
https://clickhouse.com/docs/en/interfaces/formats

feat(query): support all JsonEachRowOutputFormat variants.

---

metasrv/src/api/grpc/grpc_service.rs
metasrv/src/meta_service/raftmeta.rs
metasrv/src/network.rs
metasrv/src/store/meta_raft_store.rs
metasrv/src/watcher/watcher_manager.rs

refactor(metasrv): adjust some info level logging to debug or warn

---

common/tracing/src/logging.rs
docs/doc/100-faq/20-how-to-tracing.md

after https://github.com/datafuselabs/databend/pull/6340/,   "DATABEND_JAEGER" is replaced by  "DATABEND_JAEGER_AGENT_ENDPOINT" , we should update the doc and show how to use it.  for a newbie, may do't know how to set "DATABEND_JAEGER_AGENT_ENDPOINT"

docs(jaeger): update the doc how to use jaeger

---

.github/mergify.yml

ci: Disable merge queue to reduce CI usage
Merge queue is not suitable for our usage case, let's disable it.

ci: Disable merge queue to reduce CI usage

---

query/src/servers/http/v1/http_query_handlers.rs
query/src/storages/result/download.rs
query/src/storages/result/result_table.rs
query/tests/it/servers/http/http_query_handlers.rs

feat(query): /v1/download support limit number of rows.

---

query/src/sql/statements/query/query_normalizer.rs

fix: asc -> nulls first

---

query/src/storages/fuse/statistics/accumulator.rs
query/src/storages/fuse/statistics/reducers.rs
query/src/storages/index/range_filter.rs
query/tests/it/storages/fuse/misc.rs
query/tests/it/storages/fuse/mod.rs
query/tests/it/storages/fuse/operations/read_plan.rs
query/tests/it/storages/index/range_filter.rs

Fix fuse table meta data incompatibility introduced  by PR #6067, by
- rename `ColumnStatistics::unset_bits` to `ColumnStatistics:null_count`
- and serde alias `ColumnStatistics:null_count` as `ColumnStatistics::unset_bits`
so that filed named `null_count` or `unset_bits` can both be de-serialized
Manually checked, that binary of this PR can read data generated by the commits that brought the incompatibility and the commit before that.
Namely, the following two commits.
~~~
commit e267f7ac91a169b5d9baa86311041ca94d5f503f
Merge: fef12ed99 ee005fa80
Author: BohuTANG <overred.shuttler@gmail.com>
Date:   Thu Jul 7 11:38:27 2022 +0800
Merge pull request #6067 from …

fix: serde compatibility of null_count

---

query/src/api/rpc/exchange/exchange_manager.rs
query/src/api/rpc/exchange/exchange_source.rs

fix(cluster): use max threads as exchange source pipe size
Fixes #issue

fix(cluster): use max threads as exchange source pipe size

---

Cargo.lock
query/Cargo.toml
query/src/interpreters/interpreter_query_log.rs
scripts/ci/deploy/config/databend-query-node-1.toml

to make it consistent with schema of `system.query_log`
```
{"log_type":1,"handler_type":"MySQL","tenant_id":"test_tenant","cluster_id":"test_cluster","sql_user":"root","query_id":"41b25d04-f6a5-4cd5-abe4-d6dfca69bf0f","query_kind":"ShowPlan","query_text":"show databases","event_date":"2022-07-12","event_time":"2022-07-12 08:38:55.773809","current_database":"default","databases":"","tables":"","columns":"","projections":"","written_rows":0,"written_bytes":0,"written_io_bytes":0,"written_io_bytes_cost_ms":0,"scan_rows":0,"scan_bytes":0,"scan_io_bytes":0,"scan_io_bytes_cost_ms":0,"scan_partitions":0,"total_partitions":0,"result_rows":0,"result_bytes":0,"cpu_usage":10,"memory_usage":1666,"client_info":" …
```

feat(query): format date/datetime/enum in query log

---

query/src/servers/clickhouse/interactive_worker.rs
query/src/servers/clickhouse/interactive_worker_base.rs
query/src/servers/clickhouse/writers/query_writer.rs
query/tests/it/servers/clickhouse.rs

Now the big query that is executed with clickhouse tcp client will hang, we find it relates to the receiver buffer.
So set it to unbounded buffer.
Fixes #6535

fix: big query hang with clickhouse

---

tests/logictest/clickhouse_connector.py

in the patched clickhouse-sqlalchemy client carry the settings applied. 
need to reset for a new test file.
Fixes #issue
https://github.com/datafuselabs/databend/pull/6576#issuecomment-1182720631

fix(logictest): reset clickhouse sqlalchemy engine for each testfile.

---

common/ast/src/parser/expr.rs
common/exception/src/exception_code.rs
query/src/sql/planner/semantic/type_check.rs

Remove unsupported IntervalType in DateTrunc
Fixes #issue
_Originally posted by @sundy-li in https://github.com/datafuselabs/databend/issues/6528#issuecomment-1181498136_

fix: remove unsupported IntervalType in DateTrunc

---

query/src/storages/fuse/operations/delete.rs
query/src/storages/fuse/operations/mod.rs
query/src/storages/fuse/operations/mutation/block_filter.rs
query/src/storages/fuse/operations/mutation/deletion_mutator.rs
query/src/storages/fuse/operations/read_partitions.rs
query/src/storages/fuse/statistics/reducers.rs
query/tests/it/storages/fuse/operations/mod.rs
query/tests/it/storages/fuse/operations/mutation/deletion_mutator.rs
query/tests/it/storages/fuse/operations/mutation/mod.rs
query/tests/it/storages/fuse/operations/read_plan.rs
query/tests/it/storages/fuse/statistics.rs
tests/logictest/clickhouse_connector.py
tests/logictest/suites/gen/08_optimizer/08_0001_optimizer_statistics_exact
tests/logictest/suites/gen/09_fuse_engine/09_0012_pushdown_limit
tests/suites/0_stateless/08_optimizer/08_0001_optimizer_statistics_exact.result
tests/suites/0_stateless/08_optimizer/08_0001_optimizer_statistics_exact_cluster.result
tests/suites/0_stateless/09_fuse_engine/09_0009_remote_explain.result
tests/suites/0_stateless/09_fuse_engine/09_0009_remote_explain_cluster.result
tests/suites/0_stateless/09_fuse_engine/09_0012_pushdown_limit.result
tests/suites/0_stateless/09_fuse_engine/09_0012_pushdown_limit_cluster.result

- fix range deletion panic
> Dring deletion, multiple segments may become empty, while removing those segments from the snapshot, the index being used is NOT correct in some cases. this may lead to an index out of bound err, or even worse, silently deleting incorrect segments.
- incorrect statistics of block `in_memory_size`
compressed/unpressed size of block/segment/table are not effected
- use column size(length in bytes, of column persistent in file), instead of column's `in_memory_size` for statistics of read_plan phase
Fixes #6570

fix: range delete panic and incorrect statistics (of in_memory_size)

---

tests/metactl/test-metactl.sh

It looks like `metactl --export` already starts to run before
`databend-meta` finishing setup listening ports:
https://github.com/datafuselabs/databend/runs/7333992815?check_suite_focus=true
```text
export meta dir from remote: 127.0.0.1:9191
=== exported file data start...
=== exported file data end
=== check if there is a node record in it
...
2022-07-14T05:16:21.908938Z  INFO databend_meta::api::grpc_server: gRPC addr: 127.0.0.1:9191
2022-07-14T05:16:21.909459Z  INFO databend_meta::api::grpc_server: metasrv starts to wait for stop signal: 127.0.0.1:9191
2022-07-14T05:16:21.909477Z  INFO databend_meta::api::grpc_server: Done GrpcServer::start
```
To fix flaky test in: …

fix(metactl): extend sleep time before exporting data from a running databend-meta

---

docker/build-tool/musl/Dockerfile

This reverts commit 8ece4d6e39aac39bc2b0b18f5725d5cc9c6d9972.
Fixes #issue

chore(build-tool): revert to use symlink instead of env for musl CC

---

common/expression/src/display.rs
common/expression/src/evaluator.rs
common/expression/src/function.rs
common/expression/src/type_check.rs
common/expression/src/types.rs
common/expression/src/types/array.rs
common/expression/src/types/boolean.rs
common/expression/src/types/empty_array.rs
common/expression/src/types/generic.rs
common/expression/src/types/null.rs
common/expression/src/types/nullable.rs
common/expression/src/types/number.rs
common/expression/src/types/string.rs
common/expression/src/values.rs
common/expression/tests/it/main.rs
common/expression/tests/it/testdata/eval-fail.txt
common/expression/tests/it/testdata/tyck-fail.txt

- allow function to return runtime error
- `Column::index()` returns `Option` instead of panic
- test throwing error in `get(Array(T0), Int16) :: T0`

feat(expr): allow function to return runtime error

---

.github/mergify.yml

This PR adds a rule for docs PR.
After this change, our docs PR only needs to pass the `Vercel` check.

ci: Add rules for docs PR

---

docs/doc/60-contributing/03-rfcs/20220721-new-logging.md

[Rendered RFC](https://github.com/Xuanwo/databend/blob/rfc-the-new-logging/docs/doc/60-contributing/03-rfcs/20220721-new-logging.md)
This RFC intends to introduce a more user directly logging config.
After this RFC, we will not print logs to `stderr` by default. Instead, we will communicate with users via `stdout`:
```shell
Databend Server starting at xxxxxxx (took 0.3s)
Information
version: v0.7.128-xxxxx
logs:    
file:   enabled dir=./databend/logs level=DEBUG
stderr: disabled (set LOG_STDERR_ON=true to enable)
storage: s3://endpoint=127.0.0.1:1090,bucket=test,root=/path/to/data
metasrv: embed,max-compatible-version=2
Connection
MySQL: …
```

feat(RFC): The New Logging

---

.github/workflows/dev-macos.yml

Flaky error cause macos ci failed too much, disable it for now
issue here:  https://github.com/datafuselabs/databend/issues/6614
Fixes #issue

chore: disable macos logic test

---

Cargo.lock
common/ast/src/ast/expr.rs
common/ast/src/parser/expr.rs
common/ast/tests/it/parser.rs
common/ast/tests/it/testdata/expr-error.txt
common/ast/tests/it/testdata/expr.txt
common/ast/tests/it/testdata/statement-error.txt
common/expression/Cargo.toml
common/expression/src/display.rs
common/expression/src/evaluator.rs
common/expression/src/expression.rs
common/expression/src/function.rs
common/expression/src/lib.rs
common/expression/src/property.rs
common/expression/src/type_check.rs
common/expression/src/types.rs
common/expression/src/types/number.rs
common/expression/tests/it/main.rs
common/expression/tests/it/parser.rs
common/expression/tests/it/testdata/eval-fail.txt
common/expression/tests/it/testdata/run-pass.txt

- Add `RemoteExpr` which implements `Serialize` and `Deserialize`.
Blocked by https://github.com/datafuselabs/databend/pull/6663

feat(expr): add serializable expression

---

Cargo.lock
common/ast/src/ast/expr.rs
common/ast/src/parser/expr.rs
common/ast/tests/it/parser.rs
common/ast/tests/it/testdata/expr-error.txt
common/ast/tests/it/testdata/expr.txt
common/ast/tests/it/testdata/statement-error.txt
common/expression/Cargo.toml
common/expression/src/display.rs
common/expression/src/evaluator.rs
common/expression/src/expression.rs
common/expression/src/function.rs
common/expression/src/lib.rs
common/expression/src/property.rs
common/expression/src/type_check.rs
common/expression/src/types.rs
common/expression/src/types/number.rs
common/expression/tests/it/main.rs
common/expression/tests/it/parser.rs
common/expression/tests/it/testdata/eval-fail.txt
common/expression/tests/it/testdata/run-pass.txt

- Support `CAST` and `TRY_CAST`
- Allow cast between any number types. Once precision downgrade is detected during evaluation, while `CAST` will abort the execution and throw an error, `TRY_CAST` will just silently replace that single scalar with NULL.
- Note that `TRY_CAST` will wrap its dest type into nullable. For example, the return type of `TRY_CAST(a AS Int8)` is `Int8 NULL`, and the return type of `TRY_CAST(a AS Array(Int8))` is `Array(Int8 NULL) NULL`.

feat(expr): support user-defined `CAST` and `TRY_CAST`

---

common/ast/src/ast/expr.rs
common/ast/src/parser/expr.rs
common/ast/tests/it/testdata/statement.txt
query/src/sql/planner/binder/insert.rs
query/src/sql/statements/value_source.rs
tests/suites/0_stateless/05_ddl/05_0000_ddl_create_tables_v2.sql

1.  Fix values source `skip_to_next_row` escape flag bug.
2. Uniform `DateTime` & `Timestamp` in the new parser.
Fixes #6569

fix(query): Fix values source `skip_to_next_row`

---

.github/actions/test_sqllogic_standalone_linux/action.yml
.github/actions/test_sqllogic_standalone_macos/action.yml

Seems runner output is enough for debug including query debug logs and logic test stdout logs, logic test do not need to upload logs files when failed.
Fixes #issue

chore: disable logic test artifact upload

---

.github/workflows/production.yml

Github Hosted Runner always OOM while running unit test, let's use self-host runner instead.

ci: Use self-host runner for unit test

---

docs/doc/60-contributing/00-building-from-source.md

Cmake is needed when building from source

docs: Add cmake deps to building from source

---

Cargo.lock
common/catalog/Cargo.toml
common/config/Cargo.toml
common/contexts/Cargo.toml
common/settings/Cargo.toml
common/storage/Cargo.toml
common/streams/Cargo.toml
query/Cargo.toml

Fix https://github.com/datafuselabs/databend/issues/6614
This PR will bump opendal to the latest version to fix async runtime hang.
We apply this workaround for a quick fix. For root cause, please track https://github.com/datafuselabs/opendal/issues/473.

fix: Bump opendal to fix async runtime hang

---

tests/logictest/clickhouse_runner.py
tests/logictest/http_connector.py
tests/logictest/http_runner.py
tests/logictest/logictest.py
tests/logictest/main.py
tests/logictest/mysql_runner.py

add more args option to logictests
```
➜ python main.py -h
usage: main.py [-h] [--disable-mysql-test] [--disable-http-test] [--disable-clickhouse-test] [--test-runs [TEST_RUNS]] [--skip SKIP [SKIP ...]] [--skip-dir SKIP_DIR [SKIP_DIR ...]]
[--run-dir RUN_DIR [RUN_DIR ...]]
[pattern ...]
databend sqlogical tests
positional arguments:
pattern               Optional test case name regex
options:
-h, --help            show this help message and exit
--disable-mysql-test  Disable mysql handler test
--disable-http-test   Disable http handler test
--disable-clickhouse-test
Disable clickhouse handler test
--test-runs [TEST_RUNS]
Run each test many times (useful for e.g. flaky check) …
```

refactor(ci): add more args option to logictests

---

tests/logictest/logictest.py

The new way of arguments is inconsistent with the old way, use export SKIP_TEST_FILES=anythinghere  will skip all tests. this pr fix it.
Fixes #issue

chore: fix logic test skip argument by env

---

query/src/sql/optimizer/heuristic/decorrelate.rs
query/src/sql/optimizer/heuristic/subquery_rewriter.rs
query/src/sql/planner/binder/scalar_common.rs
query/tests/it/sql/optimizer/heuristic/testdata/subquery.test
tests/logictest/suites/query/subquery.test

For scalar subquery, we'll convert it to single join.
Single join is similar to left outer join, if there isn't matched row in the right side, we'll add **NULL** value for the right side.
But for **count** aggregation function, NULL values should be 0.
Fixes #issue

fix(planner): count aggregation function in subquery

---

query/src/sql/planner/binder/aggregate.rs
query/src/sql/planner/binder/having.rs
query/src/sql/planner/binder/mod.rs
query/src/sql/planner/binder/select.rs
tests/logictest/suites/query/having.test

Before this PR, we don't allow using `HAVING` clause in a non-aggregate query, which follows the behavior of standard SQL.
After this PR, `HAVING` will become the same as a `WHERE` clause if there is no aggregation, so we can support queries like `select * from t having a = 1`.

feat(planner): Support `HAVING` without aggregate

---

Cargo.lock
common/exception/Cargo.toml
common/exception/src/exception_into.rs
common/io/Cargo.toml
common/io/src/utils.rs
query/Cargo.toml
query/src/storages/index/bloom_filter.rs

This PR is the adoption of the `Upstream First` rule.
We will switch to `bincode-org/bincode` instead of our own fork. After this PR, we don't need to maintain our fork https://github.com/datafuse-extras/bincode anymore.
Reference: https://github.com/bincode-org/bincode/issues/564
Part of https://github.com/datafuselabs/databend/issues/6926

refactor: Switch to bincode-org/bincode

---

.cargo/audit.toml
Cargo.lock
common/meta/embedded/Cargo.toml
common/meta/raft-store/Cargo.toml
common/meta/sled-store/Cargo.toml
common/meta/store/Cargo.toml
common/users/Cargo.toml
metasrv/Cargo.toml
query/Cargo.toml
tools/metactl/Cargo.toml

try enable io-uring for meta, so add a feature named `io-uring`
- common-meta-sled-store
- common-meta-raft-store
- common-meta-embedded
- common-meta-store
- databend-meta
- databend-query
ref: https://github.com/datafuselabs/databend/issues/6910#issuecomment-1201016123
Fixes #issue

chore: try support io-uring for meta

---

Cargo.lock
common/catalog/Cargo.toml
common/config/Cargo.toml
common/contexts/Cargo.toml
common/settings/Cargo.toml
common/storage/Cargo.toml
common/streams/Cargo.toml
query/Cargo.toml

fix: Bump opendal to fix aws s3 continuation-token incorrect
FYI: https://github.com/datafuselabs/opendal/issues/490

fix: Bump opendal to fix aws s3 continuation-token incorrect

---

Cargo.lock
Cargo.toml
common/datavalues/Cargo.toml
common/io/Cargo.toml
query/Cargo.toml
tools/fuzz/Cargo.toml

Fixed https://github.com/datafuselabs/databend/issues/6928
Thanks for the hard work of `chrono`'s new maintainers: @djc and @esheppa.
We can remove our own fork and switch to `chronotope/chrono` now.
Let's go upstream first!

fix: Switch chrono upstream to chronotope/chrono

---

.github/mergify.yml
.github/release.yml
docs/doc/60-contributing/01-good-pr.md

ci: Add a new PR type for RFC which needs three approvals
Fix #7003

ci: Add a new PR type for RFC which needs three approvals

---

common/storages/hive/src/hive_table.rs

- The hive table keeps working even if `pushdown` passed in is `None` 
-  Part of 
- #6869
to avoid resolving merge conflicts in it
Fixes #issue

fix: hive table read when pushdowns is None

---

.github/actions/artifact_failure/action.yml
.github/actions/fuse_compat/action.yml
.github/workflows/dev-linux.yml
tests/fuse-compat/README.md
tests/fuse-compat/compat-logictest/fuse_compat_read
tests/fuse-compat/compat-logictest/fuse_compat_write
tests/fuse-compat/test-fuse-compat.sh

Fuse table compatability test
This script tests whether a newer version databend-query can read fuse table data written
by a older version databend-query.
Usage
```shell
tests/fuse-compat/test-fuse-compat.sh <old_ver>
```
E.g. `tests/fuse-compat/test-fuse-compat.sh 0.7.151` tests if the fuse-table written
by **databend-query-0.7.151** can be read by **current** version databend-qeury.
Prerequisites
- Current version of databend-query and databend-meta must reside in `./bins`:
- `./bins/current/databend-query`
- `./bins/current/databend-meta`
Since building a binary takes several minutes,
this step is usually done by the calling process, e.g., the CI script.
Testing data
- Suite …

ci(query): test fuse-table compatibility

---

query/src/sql/optimizer/heuristic/prune_columns.rs
query/tests/it/sql/optimizer/heuristic/prune_columns.rs
query/tests/it/sql/optimizer/heuristic/testdata/prune_columns.test
query/tests/it/sql/optimizer/heuristic/testdata/subquery.test
tests/logictest/suites/base/15_query/subquery.test

Keep at least one column for `Project` operator.

fix(planner): Fix prune projection

---

tests/fuse-compat/compat-logictest/fuse_compat_read
tests/fuse-compat/compat-logictest/fuse_compat_write

ci(fuse-table): add data types test to fuse-compat test

---

common/exception/src/exception_code.rs
common/meta/api/src/share_api.rs
common/meta/api/src/share_api_impl.rs
common/meta/api/src/share_api_test_suite.rs
common/meta/app/src/share/mod.rs
common/meta/app/src/share/share.rs
common/meta/types/src/app_error.rs

refactor: refactor add\remove share accounts API, support op more then one account per API.
Fixes #issue

refactor: refactor add\remove share accounts API

---

common/proto-conv/src/config_from_to_protobuf_impl.rs
common/proto-conv/src/user_from_to_protobuf_impl.rs

refactor(proto-conv): pb::S3StorageConfig should be decoded into StorageS3Config, instead of into enum StorageParams

---

common/management/src/serde/pb_serde.rs
common/meta/api/src/kv_api_utils.rs
common/meta/api/src/schema_api_test_suite.rs
common/proto-conv/src/config_from_to_protobuf_impl.rs
common/proto-conv/src/data_from_to_protobuf_impl.rs
common/proto-conv/src/database_from_to_protobuf_impl.rs
common/proto-conv/src/from_to_protobuf.rs
common/proto-conv/src/share_from_to_protobuf_impl.rs
common/proto-conv/src/table_from_to_protobuf_impl.rs
common/proto-conv/src/user_from_to_protobuf_impl.rs

Change trait signature `FromToProto<PB: prost::Message>` to
```rust
trait FromToProto {
type PB;
}
```
When impl `FromToProto` for a rust type, there should be only one
protobuf type that is convert from and to it. I.e, the protobuf type is
determined by rust type.
Thus `PB` should be a associated type.
Otherwise, there could be two protobuf types bounded to one rust type(e.g., `impl
FromToProto<A> for T` and `impl FromToProto<B> for T`), which is
potentially invalid: when converting rust type to protobuf type, it does
not know which it should be converted to.

refactor(proto-conv): trait FromToPB use associated type instead of type parameter

---

common/meta/api/src/id_generator.rs
common/meta/api/src/lib.rs
common/meta/api/src/schema_api_impl.rs
common/meta/api/src/schema_api_keys.rs
common/meta/api/src/share_api_impl.rs
common/meta/api/src/share_api_keys.rs

refactor(meta-api): merge TableIdGen, DatabaseIdGen and ShareIdGen into one id-generator key

---

common/planners/src/plan_node_extras.rs
common/storages/fuse/src/pruning/bloom_pruner.rs
common/storages/fuse/src/pruning/pruning_executor.rs
common/storages/fuse/src/pruning/range_pruner.rs
common/storages/hive/src/hive_partition_pruner.rs
common/storages/hive/src/hive_table.rs
common/storages/index/src/range_filter.rs
query/tests/it/storages/index/range_filter.rs

predicate push down support multi expressions
Fixes #issue

refactor(query): predicate push down support multi expressions

---

common/meta/api/src/share_api_impl.rs
common/meta/api/src/share_api_test_suite.rs
common/meta/app/src/share/mod.rs
common/meta/app/src/share/share.rs

refactor: get_share_grant_objects API should return name instead of id
Fixes #issue

refactor: get_share_grant_objects API should return name instead of id

---

Cargo.lock
src/binaries/Cargo.toml
src/common/formats/src/format_parquet.rs
src/meta/service/src/store/meta_raft_store.rs
src/meta/service/tests/it/store.rs
src/meta/sled-store/Cargo.toml
src/meta/types/Cargo.toml

Update openraft to [v0.7.0-alpha.3](https://github.com/datafuselabs/openraft/tree/v0.7.0-alpha.3);
When handling append-entries, if the local log at `prev_log_id.index` is
purged, a follower should not believe it is a **conflict** and should
not delete all logs. It will get committed log lost.
To fix this issue, use `last_applied` instead of `committed`:
`last_applied` is always the committed log id, while `committed` is not
persisted and may be smaller than the actually applied, when a follower
is restarted.
- Detail: https://github.com/datafuselabs/openraft/issues/511
- Part of #7112
- Fix: #7114

fix(meta): When handling append-entries, if prev_log_id is purged, it should not delete any logs

---

tests/logictest/logictest.py

Fix the following case when executing with an exception, only show exception without runner info.
Catch RuntimeError and convert to LogicError.
Fixes #issue

chore: catch RuntimeError exception convert to LogicError

---

Cargo.lock
src/binaries/Cargo.toml
src/binaries/metactl/snapshot.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/meta_service/meta_leader.rs
src/meta/service/src/meta_service/meta_node_kv_api_impl.rs
src/meta/service/src/network.rs
src/meta/service/src/store/store_bare.rs
src/meta/sled-store/Cargo.toml
src/meta/types/Cargo.toml
tests/logictest/complete.py

Upgrade openraft to [v0.7.0-alpha.5](https://github.com/datafuselabs/openraft/tree/v0.7.0-alpha.5), in which log level are adjusted too.
- Fix: #7116

refactor(meta-service): upgrade some critical debug level logging to info level

---

Cargo.lock
src/query/ast/Cargo.toml
src/query/ast/src/ast/expr.rs
src/query/ast/src/ast/format/mod.rs
src/query/ast/src/ast/format/syntax/ddl.rs
src/query/ast/src/ast/format/syntax/dml.rs
src/query/ast/src/ast/format/syntax/expr.rs
src/query/ast/src/ast/format/syntax/mod.rs
src/query/ast/src/ast/format/syntax/query.rs
src/query/ast/src/ast/mod.rs
src/query/ast/src/ast/statements/copy.rs
src/query/ast/src/ast/statements/explain.rs
src/query/ast/src/ast/statements/statement.rs
src/query/ast/src/ast/statements/table.rs
src/query/ast/src/parser/statement.rs
src/query/ast/src/parser/token.rs
src/query/ast/tests/it/testdata/statement.txt
src/query/service/src/interpreters/interpreter_explain_v2.rs
src/query/service/src/sql/optimizer/mod.rs
tests/logictest/suites/mode/standalone/04_0002_explain_v2

Support explain syntax.
Inspired by [forma](https://github.com/maxcountryman/forma), use [pretty](https://docs.rs/pretty/latest/pretty/) to output the formatted SQL
#7063

feat(planner): support explain syntax

---

scripts/ci/ci-run-sqllogic-tests.sh

The production workflow will run all suites, but we using mode dir to test cluster and standalone mode.
So the ci scripts need to control running arguments. 
Fixes #issue

chore: disable mode dir when running core suites

---

Cargo.lock
src/common/catalog/Cargo.toml
src/common/config/Cargo.toml
src/common/contexts/Cargo.toml
src/common/pipeline/sources/Cargo.toml
src/common/storage/Cargo.toml
src/common/storages/fuse/Cargo.toml
src/common/storages/hive/Cargo.toml
src/common/storages/preludes/Cargo.toml
src/common/streams/Cargo.toml
src/query/service/Cargo.toml
src/query/service/src/sessions/session_mgr.rs
tests/logictest/logictest.py

This PR will bump the dependency of OpenDAL to v0.13.0
Part of #7151

refactor: bump opendal to v0.13.0

---

.github/actions/test_sqllogic_standalone_macos/action.yml
.github/workflows/production.yml

Suites of crdb are still in progress, maybe impact the other test, and need to be fixed later.
Fixes #issue

chore: production logictest run base and ydb only

---

Cargo.lock
src/binaries/Cargo.toml
src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/src/network.rs
src/meta/sled-store/Cargo.toml
src/meta/types/Cargo.toml

Remove long info out of span.
Update openraft to 0.7.2-alpha.1, with normalized logging.

refactor(meta): reduce long span info

---

src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/src/network.rs
src/meta/types/src/endpoint.rs

RaftClient is a wrapper of grpc client: RaftServiceClient and auto
increase the metric active-peer and also decrease the value when client
is dropped.
- Fix: #7207

refactor(meta-service): RaftClient manages active peers metric

---

src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/tests/it/meta_node/meta_node_all.rs

Pass in a `Node` only when it needs to initialize a cluster.

refactor(meta-service): simplify open_create_boot()

---

src/query/service/src/sql/planner/binder/ddl/table.rs
tests/logictest/suites/base/05_ddl/05_0000_ddl_create_tables

fix(planner): Validate duplicated column name when creating table

---

docs/doc/10-deploy/02-deploying-databend.md

This PR tells how to deploy standalone databend service on GCS
Originally posted by @BohuTANG in #7171:
> It would be great to add a Google Cloud Storage tab to the deploy in the documentation:
> https://databend.rs/doc/deploy/deploying-databend

docs: add GCS tab for deploy standalone databend service

---

Cargo.lock

chore: Bump lz4-sys to address audit warning

chore: Bump lz4-sys to address audit warning

---

src/query/service/src/api/rpc/exchange/exchange_manager.rs
src/query/service/src/interpreters/async_insert_queue.rs
src/query/service/src/interpreters/interpreter_call.rs
src/query/service/src/interpreters/interpreter_common.rs
src/query/service/src/interpreters/interpreter_copy_v2.rs
src/query/service/src/interpreters/interpreter_select.rs
src/query/service/src/interpreters/interpreter_select_v2.rs
src/query/service/src/interpreters/interpreter_table_optimize.rs
src/query/service/src/pipelines/executor/executor_settings.rs
src/query/service/src/pipelines/executor/mod.rs
src/query/service/src/pipelines/executor/pipeline_complete_executor.rs
src/query/service/src/pipelines/executor/pipeline_executor.rs
src/query/service/src/pipelines/executor/pipeline_pulling_executor.rs
src/query/service/src/pipelines/executor/pipeline_pushing_executor.rs
src/query/service/src/servers/http/v1/query/execute_state.rs
src/query/service/src/storages/storage_table_read_wrap.rs
src/query/service/tests/it/storages/system/settings_table.rs
src/query/settings/src/lib.rs
tests/logictest/suites/base/06_show/06_0003_show_settings
tests/logictest/suites/base/20+_others/20_0008_max_execute_time

feat(processor): support max execute time settings
Parts of #6935

feat(processor): support max execute time settings

---

src/query/ast/src/ast/expr.rs
src/query/ast/src/ast/format/ast_format.rs
src/query/ast/src/ast/format/syntax/expr.rs
src/query/ast/src/ast/mod.rs
src/query/ast/src/ast/query.rs
src/query/ast/src/error.rs
src/query/ast/src/parser/expr.rs
src/query/ast/src/parser/query.rs
src/query/ast/src/parser/token.rs
src/query/ast/src/util.rs
src/query/ast/src/visitors/visitor.rs
src/query/ast/src/visitors/visitor_mut.rs
src/query/ast/src/visitors/walk.rs
src/query/ast/src/visitors/walk_mut.rs
src/query/ast/tests/it/testdata/expr-error.txt
src/query/ast/tests/it/testdata/expr.txt
src/query/ast/tests/it/testdata/query-error.txt
src/query/ast/tests/it/testdata/query.txt
src/query/ast/tests/it/testdata/statement.txt
src/query/service/src/sql/optimizer/heuristic/subquery_rewriter.rs
src/query/service/src/sql/planner/semantic/name_resolution.rs
src/query/service/src/sql/planner/semantic/type_check.rs
tests/logictest/suites/mode/standalone/explain/limit.test
tests/logictest/suites/mode/standalone/explain/subquery.test

- improve parsing speed for large query test case from 3ms to 700us
- remove unnecessary `NULLIF `, `IFNULL`, and `COALESCE` parser
- desugar functional calls like`is_null`, `database`, `current_user`, etc
Fixes https://github.com/datafuselabs/databend/issues/7225

refactor(parser): improve parsing speed

---

src/query/ast/src/ast/format/mod.rs
src/query/service/src/interpreters/fragments/v2/plan_fragment.rs
src/query/service/src/interpreters/interpreter_explain_v2.rs
src/query/service/src/sql/executor/format.rs
src/query/service/src/sql/executor/mod.rs
src/query/service/src/sql/executor/physical_plan.rs
src/query/service/src/sql/executor/physical_plan_builder.rs
src/query/service/src/sql/executor/physical_plan_visitor.rs
src/query/service/src/sql/executor/physical_scalar.rs
tests/logictest/suites/mode/cluster/04_0002_explain_v2
tests/logictest/suites/mode/cluster/exchange.test
tests/logictest/suites/mode/standalone/explain/explain.test
tests/logictest/suites/mode/standalone/explain/join.test
tests/logictest/suites/mode/standalone/explain/limit.test
tests/logictest/suites/mode/standalone/explain/prune_column.test
tests/logictest/suites/mode/standalone/explain/select.test
tests/logictest/suites/mode/standalone/explain/select_limit_offset.test
tests/logictest/suites/mode/standalone/explain/subquery.test
tests/logictest/suites/mode/standalone/explain/where_optimizaiton.test

Example:
```sql
mysql> explain select number+1 from numbers(10);
+----------------------------------------------------------+
| explain                                                  |
+----------------------------------------------------------+
| Project                                                  |
| ├── columns: [1]                                         |
| └── EvalScalar                                           |
|     ├── expressions: [+(numbers.number, 1)]              |
|     └── TableScan                                        |
|         ├── table: default.system.numbers                |
|         ├── read rows: 10                                |
|         ├── read bytes: 80 …
```

chore(planner): Add statistics info in explain result

---

src/query/functions/src/scalars/others/sleep.rs
src/query/service/src/servers/http/v1/http_query_handlers.rs
src/query/service/src/servers/http/v1/query/execute_state.rs
src/query/service/src/servers/http/v1/query/http_query.rs
src/query/service/src/servers/http/v1/query/http_query_manager.rs
src/query/service/tests/it/servers/http/http_query_handlers.rs

1. [feat(http_handler): the first request no longer wait for query to start.](https://github.com/datafuselabs/databend/commit/eace65b7f664af3f3bb970831694e44677fdd0ad) 
1. start query in the runtime of query context, and then polling for page just like the following request.   the starting of query may involve read and prune( with bloom filter) partitions
2. add a state of STARTING, only internal for now
2. [never clear expire time.](https://github.com/datafuselabs/databend/commit/26448b5a5abcc13370151be2f4c8c01745630076) 
1. because the handler future may be dropped without notice. https://github.com/hyperium/hyper/issues/707
2. base on the previous commit: all request (including the first) should …

feat(http_handler): the first request no longer wait for query to start

---

src/common/tracing/src/config.rs

Whenever I want to enable the stderr log for databend, I will search this PR for help:https://github.com/datafuselabs/databend/pull/6845
Fixes #issue

chore: add how to enable the stderr log

---

src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/src/metrics/meta_metrics.rs
src/meta/service/src/metrics/mod.rs

Other changes:
- Refactor: subscribe_metrics() does not need to watch another Receiver:
`MetaNode.running_rx` for shutting down event.
When MetaNode is shutting down, `metrics_rx.changed()` returns an
error indicating Raft is shutting down.
- Refactor: reduce indent `:()`
- Fix: #7395

feat(meta-service): add metrics `last_seq`

---

.github/actions/artifact_failure/action.yml
src/meta/service/src/meta_service/raftmeta.rs

ci(meta-service): extend timeout for join-cluster; fix path for artifact uploading

---

src/query/service/src/sql/executor/physical_plan_builder.rs

Refactor `PhysicalPlan`'s `build` method
Extract `push_downs` logic from `RelOperator::PhysicalScan` match branch to make code clearer.
Fixes #issue

refactor: `PhysicalPlan`'s `build` method

---

Cargo.lock
src/binaries/Cargo.toml
src/common/exception/Cargo.toml
src/common/grpc/Cargo.toml
src/meta/api/Cargo.toml
src/meta/grpc/Cargo.toml
src/meta/proto-conv/Cargo.toml
src/meta/service/Cargo.toml
src/meta/sled-store/Cargo.toml
src/meta/types/Cargo.toml
src/query/ast/Cargo.toml
src/query/service/Cargo.toml

- Lock thiserror to 1.0.31; The latest version 1.0.33 has been using
different std error API provided by latest nightly rust.
- Upgrade openraft to add feature to remove a learner.

chore(meta): update and lock deps: thiserror and openraft

---

docs/doc/30-reference/20-functions/10-aggregate-functions/aggregate-sum.md

```sql
MySQL [databend4]> select sum('sdf') from t1;
ERROR 1105 (HY000): Code: 1065, displayText = error:
--> SQL:1:8
|
1 | select sum('sdf') from t1
|        ^^^^^^^^^^ AggregateSumFunction does not support type 'String(String)'
.
```

docs: sum only supports numeric expressions

---

Cargo.lock
Cargo.toml
src/common/arrow/Cargo.toml
src/query/storages/fuse/src/io/read/block_reader.rs
src/query/storages/index/src/bloom_filter.rs

- deprecate legacy compression algo `lz4`
use `Lz4Raw` instead.
- use upstream parquet2 (instead patched version of our own)
**About backward compatibility:**
After this PR is merged, users who have legacy data that used legacy `Lz4`, will encounter runtime exceptions like this:
Deprecated compression algorithm [Lz4] detected.
The legacy compression algorithm [Lz4] is no longer supported.
To migrate data from the old format, please consider re-create the table, 
by using an old compatible version [v0.8.25-nightly … v0.7.12-nightly].
- Bring up the compatiable version of databend-query
- re-create the table
Suppose the name of the table is T
~~~
create table tmp_t as select * from T;
drop table T …

chore: switch to upstream parquet2

---

src/common/exception/src/exception_code.rs
src/meta/types/src/lib.rs
src/meta/types/src/meta_errors.rs
src/meta/types/src/meta_errors_into.rs
src/meta/types/src/meta_raft_errors.rs
src/meta/types/src/role_info.rs

- Remove unused `MetaError::ConcurrentSnapshotInstall`
- `RoleInfo` should have a type specific error, instead of using `MetaError`. `MetaError` is too big for `<RoleInfo as TryFrom>::Error`.

refactor(meta-error): cleanup abuse of MetaError:

---

src/query/storages/hive/src/hive_table.rs

after https://github.com/datafuselabs/opendal/pull/577,  we could use the file size from list() , avoid to fetch the meta from seperated files.  cc @Xuanwo

feat(hive): try to use the file size returned by list()

---

src/meta/service/src/api/grpc_server.rs
src/meta/service/src/meta_service/raftmeta.rs
src/meta/types/src/cluster.rs
src/meta/types/src/meta_errors.rs
src/meta/types/src/meta_errors_into.rs

- Remove unused error MetaError::IllegalUserInfoFormat
- Do not return error but just panic instead. Because if meta-service
fails to start up, nothing else can be done.
Similarly, just panic when failing to shut down.
- Cleanup some unnecessary error mappings.

refactor(meta-service): cleanup MetaError

---

src/query/service/src/sql/optimizer/cascades/explore_rules.rs
src/query/service/src/sql/optimizer/cascades/mod.rs
src/query/service/src/sql/optimizer/heuristic/decorrelate.rs
src/query/service/src/sql/optimizer/heuristic/mod.rs
src/query/service/src/sql/optimizer/heuristic/prune_columns.rs
src/query/service/src/sql/optimizer/heuristic/where_optimizer.rs
src/query/service/src/sql/optimizer/pattern_extractor.rs
src/query/service/src/sql/optimizer/property/builder.rs
src/query/service/src/sql/optimizer/property/enforcer.rs
src/query/service/src/sql/optimizer/property/mod.rs
src/query/service/src/sql/optimizer/rule/factory.rs
src/query/service/src/sql/optimizer/rule/mod.rs
src/query/service/src/sql/optimizer/rule/rewrite/rule_push_down_filter_join.rs
src/query/service/src/sql/optimizer/rule/rule_implement_hash_join.rs
src/query/service/src/sql/optimizer/rule/transform/mod.rs
src/query/service/src/sql/optimizer/rule/transform/rule_left_associate_join.rs
src/query/service/src/sql/optimizer/rule/transform/rule_right_associate_join.rs
src/query/service/src/sql/optimizer/rule/transform/util.rs
src/query/service/src/sql/optimizer/s_expr.rs
src/query/service/src/sql/planner/binder/scalar_common.rs
src/query/service/src/sql/planner/plans/logical_join.rs
tests/logictest/suites/mode/standalone/explain/join_reorder/chain.test
tests/logictest/suites/mode/standalone/explain/join_reorder/cycles.test
tests/logictest/suites/mode/standalone/explain/join_reorder/star.test

Introduce two exploration rules `LeftAssociateJoin` and `RightAssociateJoin` to enumerate join trees.
With the rules, we can exploit the associativity of join operator $\(A\bowtie B\) \bowtie C = A\bowtie \(B \bowtie C\)$.
In the current implementation, we only care about the reordering of inner joins and cross joins, which is the most common case.
Close #7440

feat(planner): Implement join reordering

---

src/query/functions-v2/src/scalars/math.rs
src/query/functions-v2/tests/it/scalars/math.rs
src/query/functions-v2/tests/it/scalars/testdata/math.txt

Fix `ceil` return type when arg is an integer.
Fixes #issue

fix: fix ceil return type

---

Cargo.lock
src/meta/proto-conv/Cargo.toml
src/meta/proto-conv/src/lib.rs
src/meta/proto-conv/src/util.rs
src/meta/proto-conv/tests/it/common.rs
src/meta/proto-conv/tests/it/main.rs
src/meta/proto-conv/tests/it/proto_conv.rs
src/meta/proto-conv/tests/it/user_proto_conv.rs
src/meta/proto-conv/tests/it/user_stage.rs

- Move the UserStageInfo test into separate files.
A backward compatibility test should not compare the decoded data with a
dedicated sample, but not with the data of the latest version.
- Doc: explain how to maintain `VER` and add a simple change-log for
`VER`, to make it clear when to remove a no longer supported feature
in the future.
- This is a supplementary PR for #7518, to complete metadata version management and provide test for the new feature introduced.

ci(proto): add compat test for CopyOptions::purge

---

src/meta/grpc/src/grpc_action.rs
src/meta/grpc/src/grpc_client.rs
src/meta/grpc/src/message.rs
src/meta/grpc/tests/it/grpc_server.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/tests/it/grpc/metasrv_grpc_get_client_info.rs
src/meta/service/tests/it/grpc/mod.rs
src/meta/types/proto/meta.proto

For a query node to find out its ip address without manually
maintaining it in config file.
- Related PR: #7510

feat(meta-service): new RPC to echo client ip

---

Cargo.lock
src/common/metrics/Cargo.toml
src/common/metrics/src/counter.rs
src/common/metrics/src/lib.rs
src/meta/service/Cargo.toml
src/meta/service/src/lib.rs
src/meta/service/src/network.rs
src/meta/service/src/raft_client.rs
src/meta/types/proto/meta.proto

- Add `WithCount` as a wrapper of every type `T` that needs to count the
active instances of it.
So that the mechanism of metrics reporting such as of live connection can be reused.
- Re-implement `RaftClient` with `WithCount`.

feat(metrics-count): abstract active instance counting

---

src/query/ast/src/ast/query.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/query.txt

Fix set operation err format.
Fixes #7573

feat(query): Fix set operation err format

---

src/query/service/src/api/rpc/exchange/statistics_receiver.rs
src/query/service/src/interpreters/interpreter_kill.rs
src/query/service/src/servers/http/v1/query/execute_state.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/service/src/sessions/session.rs

fix(cluster): do not to kill the query when the query recv finished.
Fixes #7585

fix(cluster): do not to kill the query when the query recv finished.

---

src/query/catalog/src/table_context.rs
src/query/service/src/api/http/v1/logs.rs
src/query/service/src/interpreters/interpreter_table_describe.rs
src/query/service/src/interpreters/interpreter_table_exists.rs
src/query/service/src/interpreters/interpreter_table_truncate.rs
src/query/service/src/optimizers/optimizer_statistics_exact.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sql/optimizer/heuristic/mod.rs
src/query/service/src/sql/optimizer/mod.rs
src/query/service/src/sql/planner/binder/copy.rs
src/query/service/src/sql/planner/binder/ddl/account.rs
src/query/service/src/sql/planner/binder/ddl/database.rs
src/query/service/src/sql/planner/binder/ddl/share.rs
src/query/service/src/sql/planner/binder/ddl/stage.rs
src/query/service/src/sql/planner/binder/ddl/table.rs
src/query/service/src/sql/planner/binder/ddl/view.rs
src/query/service/src/sql/planner/binder/delete.rs
src/query/service/src/sql/planner/binder/insert.rs
src/query/service/src/sql/planner/binder/join.rs
src/query/service/src/sql/planner/binder/mod.rs
src/query/service/src/sql/planner/binder/scalar.rs
src/query/service/src/sql/planner/binder/sort.rs
src/query/service/src/sql/planner/binder/table.rs
src/query/service/src/sql/planner/mod.rs
src/query/service/src/sql/planner/semantic/type_check.rs
src/query/service/src/sql/statements/statement_common.rs
src/query/service/tests/it/sql/statements/statement_common.rs

This PR depends on https://github.com/datafuselabs/databend/pull/7597. Please review after #7597 is merged.
---
This PR makes the planner depends on the `TableContext` trait instead of the `QueryContext` struct.
Make space for the future refactor.

refactor: Make planner depends on TableContext trait

---

.github/actions/fuse_compat/action.yml
tests/fuse-compat/compat-logictest/fuse_compat_read
tests/poetry.lock
tests/pyproject.toml

Fix https://github.com/datafuselabs/databend/issues/7626
I'm not familiar with this logic, but it seem to make sense to remove the trailing `0`:
```sql
statement ok
INSERT INTO fuse_compat_table VALUES(
0,
127,
3267,
2147483647,
9223372036854775807,
3.4,
1.7,
'9999-12-31',
'1991-01-01 00:00:00',
'varchar',
parse_json('[1,2,3,["a","b","c"]]'),
parse_json('{"a":1,"b":{"c":2}}'),
parse_json('[1,{"a":1,"b":{"c":2}}]')
);
statement query T
select c_timestamp FROM fuse_compat_table;
----
1991-01-01 00:00:00
```
Cc @TCeason, is this related to the MySQL connector's update?
~~Cc @drmingdrmer to confirm that this PR is right.~~

fix: Fix flaky test of fuse compat read

---

website/docusaurus.config.js

docs: Fix edit url link for blog
Fix https://github.com/datafuselabs/databend/issues/7619

docs: Fix edit url link for blog

---

src/meta/service/src/meta_service/meta_leader.rs
src/meta/service/src/meta_service/meta_service_impl.rs
src/meta/service/src/metrics/meta_metrics.rs
src/meta/service/src/metrics/mod.rs
src/meta/service/tests/it/meta_node/meta_node_request_forwarding.rs
src/meta/types/src/lib.rs
src/meta/types/src/meta_raft_errors.rs

- Meta-service replace returning error `MetaError` with
`RaftChangeMembershipError` and `RaftWriteError` for `join()`, `leave()`
and `write()`.
These three methods do not need to all the sub errors in MetaError.
- Also remove unnecessary error checking before changing membership.
The error will be returned by raft.
- Use RAII to report metrics of pending proposals.

refactor(meta-service): add RaftWriteError and RaftChangeMembershipError

---

scripts/kubernetes/meta-standalone.yaml
scripts/kubernetes/query-cluster.yaml

Use latest docker image tags
Fixes #7649

fix: Update k8s images to latest tag

---

.github/mergify.yml

ci: Fix test_sqllogic_base_cluster_linux not checked by mergify

ci: Fix test_sqllogic_base_cluster_linux not checked by mergify

---

src/query/storages/hive/src/hive_partition_filler.rs

use const column to represent hive partition data

feat(hive): use const column to represent hive partition data

---

Makefile
src/query/service/src/interpreters/access/accessor.rs
src/query/service/src/interpreters/access/management_mode_access.rs
src/query/service/src/interpreters/access/mod.rs
src/query/service/src/interpreters/interpreter_factory.rs
src/query/service/src/interpreters/interpreter_factory_interceptor.rs
src/query/service/src/interpreters/interpreter_factory_v2.rs
src/query/service/tests/it/interpreters/access/management_mode_access.rs

* Unify the accessor check: move all checks to the `AccessorChecker` trait for the interpreter
* Move up the `cargo clippy` in Makefile, to make the cargo work if the `yapf` is not work.
Fixes #issue

chore(query): unify the accessor check

---

.github/mergify.yml

ci: Add fuse_compat into mergify check list

ci: Add fuse_compat into mergify check list

---

src/query/service/src/pipelines/processors/mod.rs
src/query/service/src/pipelines/processors/transforms/hash_join/desc.rs
src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state.rs
src/query/service/src/pipelines/processors/transforms/hash_join/join_hash_table.rs
src/query/service/src/pipelines/processors/transforms/hash_join/result_blocks.rs
src/query/service/src/pipelines/processors/transforms/hash_join/row.rs
src/query/service/src/pipelines/processors/transforms/mod.rs
src/query/service/src/pipelines/processors/transforms/transform_right_join.rs
src/query/service/src/sql/executor/physical_plan.rs
src/query/service/src/sql/executor/pipeline_builder.rs
src/query/service/src/sql/planner/binder/join.rs
tests/logictest/suites/base/15_query/join.test
tests/logictest/suites/crdb/join

Support right join (won't convert into left join)
Fixes #7599

feat(planner): support independent right join

---

src/query/service/src/interpreters/access/accessor.rs
src/query/service/src/interpreters/access/mod.rs
src/query/service/src/interpreters/access/privilege_access.rs
src/query/service/src/interpreters/interpreter_cluster_key_alter.rs
src/query/service/src/interpreters/interpreter_cluster_key_drop.rs
src/query/service/src/interpreters/interpreter_database_create.rs
src/query/service/src/interpreters/interpreter_database_drop.rs
src/query/service/src/interpreters/interpreter_database_undrop.rs
src/query/service/src/interpreters/interpreter_kill.rs
src/query/service/src/interpreters/interpreter_table_create_v2.rs
src/query/service/src/interpreters/interpreter_table_drop.rs
src/query/service/src/interpreters/interpreter_table_truncate.rs
src/query/service/src/interpreters/interpreter_table_undrop.rs
src/query/service/src/interpreters/interpreter_view_alter.rs
src/query/service/src/interpreters/interpreter_view_create.rs
src/query/service/src/interpreters/interpreter_view_drop.rs

Move privilege checks from runtime `execute2` to access check.
`access/accessor` is a factory for all the checks now:
* management mode check
* privileges check
* shared table check?
It needs to bind the meta information in the binder.
Fixes #7697

chore(query): Move privilege check to access check

---

src/common/base/src/base/catch_unwind.rs
src/common/base/src/base/mod.rs
src/common/base/src/base/thread.rs
src/query/service/src/api/rpc/exchange/exchange_manager.rs
src/query/service/src/interpreters/async_insert_queue.rs
src/query/service/src/interpreters/interpreter.rs
src/query/service/src/interpreters/interpreter_common.rs
src/query/service/src/interpreters/interpreter_table_optimize.rs
src/query/service/src/interpreters/interpreter_table_recluster.rs
src/query/service/src/lib.rs
src/query/service/src/pipelines/executor/pipeline_complete_executor.rs
src/query/service/src/pipelines/executor/pipeline_executor.rs
src/query/service/src/pipelines/executor/pipeline_pulling_executor.rs
src/query/service/src/pipelines/executor/pipeline_pushing_executor.rs
src/query/service/src/servers/http/v1/query/execute_state.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/service/src/storages/storage_table_read_wrap.rs

refactor(processor): save pipeline executor into query context
Fixes #issue

refactor(processor): save pipeline executor into query context

---

src/query/service/src/interpreters/access/privilege_access.rs
src/query/service/src/interpreters/interpreter_factory.rs
src/query/service/src/interpreters/interpreter_factory_v2.rs
src/query/service/src/servers/mysql/mysql_interactive_worker.rs
src/query/service/src/sql/planner/binder/mod.rs
src/query/service/src/sql/planner/format/display_plan.rs
src/query/service/src/sql/planner/plans/mod.rs
tests/logictest/suites/mode/standalone/explain/explain.test

For the invalid queries like `select * from table_not_exists`, we should allow displaying the parsing results of the queries with `EXPLAIN AST` instead of raising an error.

fix(planner): Fix `EXPLAIN AST` for invalid query

---

Cargo.lock
src/query/formats/src/lib.rs
src/query/pipeline/sources/Cargo.toml
src/query/pipeline/sources/src/processors/sources/input_formats/delimiter.rs
src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_csv.rs
src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_ndjson.rs
src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_parquet.rs
src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_tsv.rs
src/query/pipeline/sources/src/processors/sources/input_formats/impls/mod.rs
src/query/pipeline/sources/src/processors/sources/input_formats/input_context.rs
src/query/pipeline/sources/src/processors/sources/input_formats/input_format.rs
src/query/pipeline/sources/src/processors/sources/input_formats/input_format_text.rs
src/query/pipeline/sources/src/processors/sources/input_formats/input_pipeline.rs
src/query/pipeline/sources/src/processors/sources/input_formats/mod.rs
src/query/pipeline/sources/src/processors/sources/input_formats/source_aligner.rs
src/query/pipeline/sources/src/processors/sources/input_formats/source_deserializer.rs
src/query/pipeline/sources/src/processors/sources/input_formats/transform_deserializer.rs
src/query/pipeline/sources/src/processors/sources/mod.rs
src/query/service/src/interpreters/interpreter_copy_v2.rs
src/query/service/src/storages/stage/stage_source.rs
src/query/service/src/storages/stage/stage_table.rs
src/query/service/tests/it/storages/system/settings_table.rs
src/query/settings/src/lib.rs
tests/logictest/suites/base/06_show/06_0003_show_settings
tests/suites/1_stateful/04_mini_dataset/04_0001_mini_hits.result
tests/suites/1_stateful/04_mini_dataset/04_0001_mini_hits.sh

part of https://github.com/datafuselabs/databend/issues/7732
unify pipeline for all input(copy into, streaming load, clickhouse insert with format)
the insight is that `sync Deserializer` can not do async read,  so it is better to feed it with aligned RowBatch (including those in Column format like RowGroup in parquet).
and these RowBatches  is independent.
prepare for a distributed copy:  split files to splits early
- big TSV/NDJSON without compression  and parquert/orc/arrow can be read in Parallel
for row-based format:
-  Reader(not Processor): each split has its own reader task, read small ReadBatch
-  Aligner(Processor): aligner small ReadBatch to small RowBatch
-  Deserializer(Processor): …

feat(query): unify pipeline for all inputs with format.

---

src/query/ast/src/ast/statements/table.rs
src/query/service/src/interpreters/interpreter_table_create_v2.rs
src/query/service/src/sql/planner/binder/ddl/table.rs
src/query/service/src/sql/planner/plans/create_table_v2.rs
src/query/service/tests/it/storages/fuse/pruning.rs
src/query/service/tests/it/storages/fuse/table.rs
src/query/service/tests/it/storages/fuse/table_test_fixture.rs

This PR is another try after https://github.com/datafuselabs/databend/pull/7800
By moving physical scalar build to interpreter, `Planner` don't need to depend on `PhysicalScalarBuilder` anymore.

refactor: Delay physical scalar build to interpreter

---

src/meta/proto-conv/src/table_from_to_protobuf_impl.rs
src/meta/protos/proto/table.proto

refactor(meta): Remove not used conv for TableInfo

refactor(meta): Remove not used conv for TableInfo

---

Cargo.lock
src/binaries/Cargo.toml
src/binaries/meta/main.rs
src/meta/sled-store/Cargo.toml
src/meta/types/Cargo.toml

Openraft v0.7.3
Changed:
-   Changed: [25e94c36](https://github.com/datafuselabs/openraft/commit/25e94c36e5c8ae640044196070f9a067d5f105a3) InstallSnapshotResponse: replies the last applied log id; Do not install a smaller snapshot; by 张炎泼; 2022-09-22
A snapshot may not be installed by a follower if it already has a higher
`last_applied` log id locally.
In such a case, it just ignores the snapshot and respond with its local
`last_applied` log id.
This way the applied state(i.e., `last_applied`) will never revert back.
Fixed:
-   Fixed: [21684bbd](https://github.com/datafuselabs/openraft/commit/21684bbdfdc54b18daa68f623afc2b0be6718c72) potential inconsistency when installing snapshot; by 张炎泼; …

refactor(meta/service): upgrade openraft v0.7.2..v0.7.3

---

src/meta/client/src/grpc_client.rs
src/meta/client/src/message.rs

Currently we have the metrics about grpc client for metasrv, however the current metrics did not include the name of request for metasrv, it makes hard to diagnose the latency percentiles, especially with some long calls like `WATCH` 
This PR adds an extra `request` label to the metrics, so we can get the different latencies of different requests.

chore(meta-grpc-client): add metric label about request name

---

src/query/storages/fuse-meta/src/caches/cache.rs

fix(storage): fix bloom filter index always missing
Fixes #issue

fix(storage): fix bloom filter index always missing

---

Cargo.lock
src/query/storages/index/Cargo.toml
src/query/storages/index/src/bloom/bloom.rs
src/query/storages/index/src/bloom/mod.rs
src/query/storages/index/src/bloom/xor8.rs
src/query/storages/index/src/lib.rs
src/query/storages/index/tests/it/bloom/mod.rs
src/query/storages/index/tests/it/bloom/xor.rs
src/query/storages/index/tests/it/main.rs

* Introduce a new bloom trait
* Use XOR instead of bloom filter
Test result(bitmap encode size / raw data size):
```
u64: 
bitmap enc:1230069, raw:8000000, ratio:0.15375863
bool:
bitmap enc:61, raw:1000000, ratio:0.000061
string:
string enc:123067, raw:3000000, ratio:0.041022334
100000 records of the same key:
string enc:61, raw:3000000, ratio:0.000020333333
```
Part of #7748

feat: add XOR bloom filter

---

src/meta/client/src/grpc_client.rs
src/meta/raft-store/src/state_machine/sm.rs

The start time should be set after a req is received, not before.
Otherwise the elapsed time includes the time spent on waiting for a req.
- Fix: #7871

chore(meta): fix slow-request timing

---

tests/logictest/suites/base/06_show/06_0003_show_settings

Signed-off-by: Yisong Han <yisong8686@gmail.com>
I think a simple test of show settings still needs to be added in case there is a functional failure.
eg. [show tables](https://github.com/datafuselabs/databend/blob/main/tests/logictest/suites/base/06_show/06_0004_show_tables#L85)
Fixes #7184

chore(sqllogic): add SHOW SETTINGS test

---

src/query/storages/fuse/src/pruning/pruning_executor.rs

Minor fix:
During pruning, use the shortcut path if the filter vector is empty.
For queries like "select * from t", which has no filter conditions, an `Some<V>` where `V:Vec<LegacyExpression>` is passed in, if the vectory `V` is empty, we should use the "shortcut", i.e. just return all the blocks locations as the targets of scan.
Fixes #issue

fix: use shortcut path if filter vector is empty during pruning

---

Cargo.lock
src/common/contexts/Cargo.toml
src/common/storage/Cargo.toml
src/query/catalog/Cargo.toml
src/query/config/Cargo.toml
src/query/service/Cargo.toml
src/query/streams/Cargo.toml

This PR bumps the OpenDAL dependency version to 0.17.2
Fixes #7896

chore: Bump OpenDAL version to 0.17.2

---

Cargo.lock

fix: Bump opendal to 0.17.4 to fix error retry

fix: Bump opendal to 0.17.4 to fix error retry

---

src/query/storages/fuse/src/pruning/pruning_executor.rs

Loading of segment data is too aggressive during pruning. this patch constrains the degree of parallelism according to the setting of `max_threads`.
Fixes #issue

fix: concurrency control of segment loading

---

src/query/datavalues/src/columns/array/mutable.rs
src/query/datavalues/src/columns/boolean/mutable.rs
src/query/datavalues/src/columns/mutable.rs
src/query/datavalues/src/columns/null/mutable.rs
src/query/datavalues/src/columns/nullable/mutable.rs
src/query/datavalues/src/columns/object/mutable.rs
src/query/datavalues/src/columns/primitive/mutable.rs
src/query/datavalues/src/columns/string/mutable.rs
src/query/datavalues/src/columns/struct_/mutable.rs
src/query/datavalues/src/types/deserializations/array.rs
src/query/datavalues/src/types/deserializations/boolean.rs
src/query/datavalues/src/types/deserializations/date.rs
src/query/datavalues/src/types/deserializations/mod.rs
src/query/datavalues/src/types/deserializations/null.rs
src/query/datavalues/src/types/deserializations/nullable.rs
src/query/datavalues/src/types/deserializations/number.rs
src/query/datavalues/src/types/deserializations/string.rs
src/query/datavalues/src/types/deserializations/struct_.rs
src/query/datavalues/src/types/deserializations/timestamp.rs
src/query/datavalues/src/types/deserializations/variant.rs
src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_csv.rs
src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_tsv.rs
src/query/pipeline/sources/src/processors/sources/input_formats/input_context.rs
src/query/pipeline/sources/src/processors/sources/input_formats/input_format_text.rs
src/query/pipeline/sources/src/processors/sources/input_formats/input_pipeline.rs
src/query/service/src/pipelines/executor/executor_graph.rs
tests/suites/0_stateless/14_clickhouse_http_handler/14_0007_http_clickhouse_input_format_diagnostic.sh

since estimating the size of the variant column is very expensive.
we use the size of bytes before json decode.
Fixes https://github.com/datafuselabs/databend/issues/7923
related to https://github.com/datafuselabs/databend/issues/7760

feat(intpu_format): check memory_size() for building data block.

---

src/query/storages/fuse/src/pruning/pruning_executor.rs

add `sync_prune` method for `BlockPruner`
Fixes #7913

feat: add sync_prune method for BlockPruner

---

Cargo.lock
src/query/config/Cargo.toml
src/query/service/Cargo.toml
src/query/storages/hive-meta-store/Cargo.toml
src/query/storages/hive/Cargo.toml
src/query/storages/preludes/Cargo.toml

Thrift 0.17 introduces new trait `TSerialize`.

refactor(query): upgrade thrift runtime 0.16..0.17

---

src/query/ast/src/ast/format/ast_format.rs
src/query/ast/src/ast/format/syntax/dml.rs
src/query/ast/src/ast/format/syntax/mod.rs
src/query/ast/src/ast/statements/mod.rs
src/query/ast/src/ast/statements/statement.rs
src/query/ast/src/ast/statements/update.rs
src/query/ast/src/parser/statement.rs
src/query/ast/src/visitors/visitor.rs
src/query/ast/src/visitors/visitor_mut.rs
src/query/ast/src/visitors/walk.rs
src/query/ast/src/visitors/walk_mut.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/statement.txt
src/query/service/src/interpreters/access/privilege_access.rs
src/query/service/src/interpreters/interpreter_factory.rs
src/query/service/src/sql/planner/binder/binder.rs
src/query/service/src/sql/planner/binder/update.rs
src/query/service/src/sql/planner/format/display_plan.rs
src/query/service/src/sql/planner/plans/mod.rs
src/query/service/src/sql/planner/plans/update.rs
tests/logictest/suites/duckdb/issues/monetdb/test_correlated_update.test

```
UPDATE <table> SET <column> = <expr> [, <column> = <expr> , ... ] [WHERE condition]
```

feat(planner): support update ast and planner

---

src/query/pipeline/core/src/pipeline_display.rs
src/query/pipeline/core/src/processors/processor.rs
src/query/pipeline/core/src/processors/resize_processor.rs
src/query/pipeline/sinks/src/processors/sinks/async_sink.rs
src/query/pipeline/sinks/src/processors/sinks/sync_sink.rs
src/query/pipeline/sources/src/processors/sources/async_source.rs
src/query/pipeline/sources/src/processors/sources/empty_source.rs
src/query/pipeline/sources/src/processors/sources/input_formats/source_aligner.rs
src/query/pipeline/sources/src/processors/sources/input_formats/source_deserializer.rs
src/query/pipeline/sources/src/processors/sources/input_formats/transform_deserializer.rs
src/query/pipeline/sources/src/processors/sources/one_block_source.rs
src/query/pipeline/sources/src/processors/sources/sync_source.rs
src/query/pipeline/transforms/src/processors/transforms/transform.rs
src/query/pipeline/transforms/src/processors/transforms/transform_compact.rs
src/query/service/src/api/rpc/exchange/exchange_sink_merge.rs
src/query/service/src/api/rpc/exchange/exchange_sink_shuffle.rs
src/query/service/src/api/rpc/exchange/exchange_transform.rs
src/query/service/src/api/rpc/exchange/exchange_transform_source.rs
src/query/service/src/pipelines/processors/transforms/chunk_operator.rs
src/query/service/src/pipelines/processors/transforms/transform_aggregator.rs
src/query/service/src/pipelines/processors/transforms/transform_create_sets.rs
src/query/service/src/pipelines/processors/transforms/transform_hash_join.rs
src/query/service/src/pipelines/processors/transforms/transform_limit.rs
src/query/service/src/pipelines/processors/transforms/transform_merge_block.rs
src/query/service/src/storages/result/result_table_sink.rs
src/query/service/src/storages/result/result_table_source.rs
src/query/service/src/storages/stage/stage_table_sink.rs
src/query/storages/fuse/src/operations/fuse_sink.rs
src/query/storages/fuse/src/operations/read.rs
src/query/storages/hive/src/hive_table_source.rs

Improve format of explain pipeline:
```sql
mysql> explain pipeline select number+1 from numbers(10) where number < 5;
+-----------------------------------------------------+
| explain                                             |
+-----------------------------------------------------+
| CompoundChunkOperator(Map) × 1 processor            |
|   CompoundChunkOperator(Filter) × 1 processor       |
|     CompoundChunkOperator(Rename) × 1 processor     |
|       CompoundChunkOperator(Project) × 1 processor  |
|         NumbersSourceTransform × 1 processor        |
+-----------------------------------------------------+
5 rows in set (0.11 sec)
Read 0 rows, 0.00 B in 0.003 sec., 0 rows/sec., 0.00 B/sec. …
```

chore(planner): Improve explain pipeline

---

src/meta/types/src/cluster.rs
src/meta/types/tests/it/cluster.rs
src/query/management/tests/it/cluster.rs
src/query/service/src/clusters/cluster.rs
src/query/service/src/storages/system/clusters_table.rs
src/query/service/tests/it/storages/system/clusters_table.rs
src/query/service/tests/it/tests/context.rs
tests/logictest/suites/base/01_system/01_0008_system_clusters

* Add binary commit version to system.clusters
```
mysql> select * from system.clusters;
+------------------------+-----------+------+------------------------------------------------------------------------------+
| name                   | host      | port | version                                                                      |
+------------------------+-----------+------+------------------------------------------------------------------------------+
| kOSA7yj0ULTreyQfmwoIH7 | 127.0.0.1 | 9090 | v0.8.54-nightly-fd32998-simd(rust-1.66.0-nightly-2022-09-30T00:39:13.36732Z) |
+------------------------+-----------+------+--------------------------------------------------------------------------- …
```

feat(clusters): add binary commit version to system.clusters

---

docs/doc/50-manage/00-metasrv/50-metasrv-metrics.md
src/common/metrics/src/counter.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/meta_service/meta_leader.rs
src/meta/service/src/metrics/meta_metrics.rs
src/meta/service/tests/it/api/http/metrics.rs

```
metasrv_meta_network_rpc_delay_seconds_sum 0.015056999000000001
metasrv_meta_network_rpc_delay_seconds{quantile="0"} 0.003751958
metasrv_meta_network_rpc_delay_seconds{quantile="0.5"} 0.005509397423424308
metasrv_meta_network_rpc_delay_seconds{quantile="0.9"} 0.005509397423424308
metasrv_meta_network_rpc_delay_seconds{quantile="0.95"} 0.005509397423424308
metasrv_meta_network_rpc_delay_seconds{quantile="0.99"} 0.005509397423424308
metasrv_meta_network_rpc_delay_seconds{quantile="0.999"} 0.005509397423424308
metasrv_meta_network_rpc_delay_seconds{quantile="1"} 0.005795875
```

feat(meta/service): add histogram metrics for rpc delay: metasrv_meta_network_rpc_delay_seconds

---

src/query/service/tests/it/storages/fuse/statistics.rs
src/query/service/tests/it/storages/index/range_filter.rs
src/query/storages/fuse-meta/src/meta/common.rs
src/query/storages/fuse/src/statistics/column_statistic.rs
src/query/storages/fuse/src/statistics/mod.rs
src/query/storages/index/src/filters/xor8.rs
src/query/storages/index/tests/it/filters/bloom_filter.rs

update : 2022-09-30
move task "customize ser/de of `DataValue::String` (in ser/de of segment info)" to dedicated pr
Fixes #7829

fix: shrink min max index

---

Cargo.lock
src/binaries/Cargo.toml
src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/src/store/store_bare.rs
src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs
src/meta/sled-store/Cargo.toml
src/meta/types/Cargo.toml

https://github.com/drmingdrmer/openraft/tree/v0.7.4-alpha.2
Openraft changes:
- Fix: changing membership should not remove replication to all learners
When changing membership, replications to the learners(non-voters) that
are not added as voter should be kept.
E.g.: with a cluster of voters `{0}` and learners `{1, 2, 3}`, changing
membership to `{0, 1, 2}` should not remove replication to node `3`.
Only replications to removed members should be removed.
- Change: remove AddLearnerError::Exists, which is not actually used
Other changes:
- Remove adding learner when leader established
- Fix: #7895

chore(meta): upgrade openraft 0.7.3..0.7.4-alpha.2

---

src/meta/raft-store/src/state_machine/sm.rs
src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/src/store/store_bare.rs
src/meta/sled-store/src/sled_tree.rs

Most methods in `RaftStoreBare` do not need to return `MetaError`, but just
`MetaStorageError`.
Other changes:
- Provides a method `get_nodes()` to simplify getting voter/non-voter
nodes.

refactor(meta/service): use MetaStorageError if possible

---

Cargo.lock
src/common/contexts/Cargo.toml
src/common/storage/Cargo.toml
src/query/catalog/Cargo.toml
src/query/config/Cargo.toml
src/query/pipeline/sources/Cargo.toml
src/query/service/Cargo.toml
src/query/service/src/interpreters/interpreter_common.rs
src/query/storages/fuse/Cargo.toml
src/query/storages/hive/Cargo.toml
src/query/storages/hive/src/hive_table.rs
src/query/storages/preludes/Cargo.toml
src/query/storages/share/Cargo.toml
src/query/streams/Cargo.toml

feat: Bump opendal to reuse metadata during list
Release note: https://github.com/datafuselabs/opendal/discussions/772
With this PR, `list_files` will be much faster than before by reducing an extra `metadata` call.

feat: Bump opendal to reuse metadata during list

---

src/query/service/src/sql/planner/binder/select.rs
tests/logictest/suites/base/15_query/union.test

The ticket processes the case that union needs more than one different coercion type.
For the case
```sql
SELECT 'Кирилл' as a, 'Müller' as b, 1.0 as c, 2 as id UNION SELECT NULL as a, NULL as b, 1 as c,  1 as id order by id;
```
coercion types contain two different types: `nullable` and `double`.
Fixes #issue

fix: union needs more than one coercion type

---

Cargo.lock
src/query/legacy-parser/Cargo.toml
src/query/legacy-parser/src/sql_common.rs

Use unicode_segmentation crate to extract graphemes to truncate big `INSERT` statements instead of directly indexing first 64 bytes of the statement, which is unsafe: it panics if a multibyte unicode character is spread between the 63th & 64th byte of the string. 
Fixes #8010

fix: Use unicode_segmentation to truncate INSERT statement

---

src/common/storage/src/operator.rs
src/query/service/src/sql/planner/binder/ddl/table.rs

Checking `StorageParams`(aka: storage connection params) correctness when create table with external location.
ref: #8022 
Fixes #issue

refactor: Checking StorageParams correctness when create table with external location.

---

src/query/service/src/pipelines/processors/transforms/hash_join/join_hash_table.rs
tests/logictest/suites/crdb/join

not a bug, but useless.
refactor with `match` to make code more readable
Fixes #issue

refactor(mark join): no need to init_markers in RightMark.

---

src/query/datavalues/src/columns/nullable/mod.rs
src/query/datavalues/src/scalars/viewer.rs
tests/logictest/suites/base/15_query/functions/cast.test
tests/logictest/suites/base/15_query/select.test

Fixes https://github.com/datafuselabs/databend/issues/8000

fix: `only_null` for nullable column should return false when column is empty

---

src/meta/service/src/meta_service/meta_leader.rs
src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs

feat(meta/service): cleanup replication to learner when a node leaves the cluster

---

Cargo.lock
src/common/contexts/Cargo.toml
src/common/contexts/src/dal/dal_context.rs
src/common/contexts/src/dal/dal_runtime.rs
src/common/storage/Cargo.toml
src/query/catalog/Cargo.toml
src/query/config/Cargo.toml
src/query/pipeline/sources/Cargo.toml
src/query/service/Cargo.toml
src/query/sharing/Cargo.toml
src/query/storages/fuse/Cargo.toml
src/query/storages/hive/Cargo.toml
src/query/storages/preludes/Cargo.toml
src/query/storages/share/Cargo.toml
src/query/streams/Cargo.toml

feat: Bump OpenDAL to 0.19 for new features
We can implement the backend on oss and redis now!
- https://github.com/datafuselabs/opendal/discussions/823

feat: Bump OpenDAL to 0.19 for new features

---

src/query/service/src/servers/http/v1/http_query_handlers.rs
src/query/service/src/servers/http/v1/query/execute_state.rs

```
curl  --header 'Content-Type: application/json'  --request POST '127.0.0.1:8001/v1/query/'  --data-raw '{"sql": "select 1"}' -u root:
```
result like
``` 
...
x-databend-query-id: c169d93c-babc-46a0-9d93-c9d218cd9025
x-databend-query-state: Succeeded
...
```
fixes https://github.com/datafuselabs/databend/issues/7992

feat(http_handler): return query id and state headers .

---

src/common/jsonb/src/error.rs
src/common/jsonb/src/from.rs
src/common/jsonb/src/functions.rs
src/common/jsonb/src/parser.rs
src/common/jsonb/src/value.rs
src/common/jsonb/tests/it/functions.rs
src/query/functions-v2/src/scalars/string.rs
src/query/functions-v2/src/scalars/string_multi_args.rs
src/query/functions-v2/src/scalars/variant.rs
src/query/functions-v2/tests/it/scalars/testdata/string.txt
src/query/functions-v2/tests/it/scalars/testdata/variant.txt
src/query/functions-v2/tests/it/scalars/variant.rs

migrate variant functions to functions-v2
```
parse_json
try_parse_json
check_json
length
object_keys
get
```
part of #7717

feat(query): migrate variant func to func-v2

---

src/common/storage/src/config.rs
src/common/storage/src/lib.rs
src/common/storage/src/location.rs
src/common/storage/src/operator.rs
src/common/storage/tests/location.rs

This PR allows you to copy from Aliyun OSS with its native API, for example:
```mysql
COPY INTO ontime FROM 'oss://example-bucket/ontime.csv' CONNECTION=( ENDPOINT_URL='https://oss-cn-litang.example.com' ACCESS_KEY_ID='<access_key_id>' ACCESS_KEY_SECRET='<access_key_secret>' OIDC_TOKEN='<oidc-token>' ROLE_ARN='<ROLE-ARN>' ) FILE_FORMAT=( TYPE = 'CSV' );
```
Fixes #8068

feat: support COPY INTO from oss backend

---

src/common/storage/src/operator.rs

Fixes https://github.com/datafuselabs/databend/issues/8069

fix: S3 operator's security_token is not set

---

docs/doc/21-load-data/01-s3.md

docs: fix typo in token docs

---

.github/workflows/databend-release.yml

for macos release, `sha256sum: command not found`
Fixes https://github.com/datafuselabs/databend/actions/runs/3214730421

chore: brew install coreutils to get sha256sum command

---

src/query/service/tests/it/storages/testdata/system-tables.txt
src/query/settings/src/lib.rs
src/query/storages/fuse/src/fuse_segment.rs
src/query/storages/fuse/src/lib.rs
src/query/storages/fuse/src/pruning/pruning_executor.rs
src/query/storages/fuse/src/table_functions/fuse_blocks/fuse_block.rs
src/query/storages/fuse/src/table_functions/fuse_segments/fuse_segment.rs

* Add `read_segments` for read all segments in concurrency, used in `fuse_segment` and `fuse_block`
* Rename `max_concurrent_prune` to `max_storage_io_requests`
Fixes #issue

feat: try get segments parallel

---

src/query/storages/fuse/src/fuse_segment.rs
src/query/storages/fuse/src/operations/gc.rs
src/query/storages/fuse/src/operations/mutation/compact_mutator.rs
src/query/storages/fuse/src/table_functions/fuse_segments/fuse_segment.rs

* `optimize table xx compact` is faster now by using `read_segments`
* `optimize table xx purge` is slowed by all the snapshot reads (a chain we can not parallel). I will try it in another PR
* Rename some gc.rs function names.
Fixes #7914

chore: try to fast the compact&purge

---

src/query/datavalues/tests/it/variant_value.rs

The memory size of `JSON` is different in different environments.
We can remove this test case. 
Fixes #issue

fix(query): fix variant memory test

---

src/query/service/src/interpreters/interpreter_query_log.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/tests/it/storages/testdata/system-tables.txt
src/query/storages/preludes/src/system/query_log_table.rs

Currently it's hard to calculate the query duration in the query log without aggregation by query id.
This PR adds a query_start_time and query_duration field to the query log, may make analyze query duration easier.
Fixes #issue

feat(log): Add query_start_time and query_duration to query log

---

src/query/users/src/role_mgr.rs
src/query/users/src/role_util.rs
tests/logictest/suites/base/06_show/06_0007_show_roles
tests/logictest/suites/base/06_show/06_0007_show_roles_v2

This PR adds another builtin role PUBLIC, which plays as the builtin role with the lowest privileges.
It's also a special role, which is the child by every other role by default. Thus every other role can access the data objects owned by PUBLIC role, any role can switch to PUBLIC role.
The opposite side is the ACCOUNT_ADMIN role, which plays as the highest builtin role. ACCOUNT_ADMIN can access every data objects owned by any role, and can be switched to any role.
Fixes #6827

feat(rbac): Add builtin PUBLIC role

---

src/query/storages/fuse-meta/src/meta/v1/snapshot.rs
src/query/storages/fuse/src/fuse_snapshot.rs
src/query/storages/fuse/src/table_functions/fuse_snapshots/fuse_snapshot.rs

**Make the TableSnapshotLite use less memory**
Fixes #issue

chore: try to reduce the snapshot read memory

---

Cargo.lock

fix: x-oss-security-token not set correctly

fix: x-oss-security-token not set correctly

---

src/query/catalog/src/table.rs
src/query/service/src/interpreters/interpreter_table_drop.rs
src/query/service/tests/it/storages/fuse/table.rs
src/query/service/tests/it/storages/memory.rs
src/query/service/tests/it/storages/null.rs
src/query/storages/fuse/src/operations/commit.rs
src/query/storages/preludes/src/null/null_table.rs
tests/logictest/suites/base/12_time_travel/12_0003_time_travel_undrop

during the execution of "drop table all", the table should refresh itself before truncating 
Fixes #8174

fix: undrop not working as expected if table is dropped by using "drop table t all"

---

Cargo.lock
src/meta/raft-store/src/state/raft_state_kv.rs
src/meta/raft-store/src/state_machine/log_meta.rs
src/meta/raft-store/src/state_machine/state_machine_meta.rs
src/meta/sled-store/Cargo.toml
src/meta/sled-store/src/bytes_error.rs
src/meta/sled-store/src/lib.rs
src/meta/sled-store/src/sled_key_space.rs
src/meta/sled-store/src/sled_serde.rs
src/meta/sled-store/tests/it/testing/fake_state_machine_meta.rs

Serialization/deserialization error should not be `MetaStorageError`.
Introduce a specific error `SledBytesError` and convert it to
`MetaStorageError` when needed.

feat(meta/sled): introduce SledBytesError

---

src/meta/raft-store/src/log/raft_log.rs
src/meta/sled-store/src/lib.rs
src/meta/sled-store/src/sled_serde.rs
src/meta/sled-store/src/sled_tree.rs
src/meta/sled-store/tests/it/sled_tree.rs

- `append()` and `append_values()` provides similar functions and can be
abstracted into one implementation.
- Rename `SledValueToKey` to `SledAsRef`. Now it provides API to get
either a ref to key or a ref to value.

refactor(meta/sled): merge method `append()` and `append_values()`

---

src/query/service/src/procedures/systems/fuse_snapshot.rs
src/query/service/tests/it/storages/fuse/operations/purge_drop.rs
src/query/service/tests/it/storages/fuse/operations/purge_truncate.rs
src/query/storages/fuse/src/fuse_file.rs
src/query/storages/fuse/src/fuse_snapshot.rs
src/query/storages/fuse/src/operations/gc.rs
src/query/storages/fuse/src/table_functions/fuse_snapshots/fuse_snapshot.rs
src/query/storages/fuse/src/table_functions/fuse_snapshots/fuse_snapshot_table.rs

**Push down the limit to fuse_snapshot to fast `select * from fuse_snapshot(db, table) limit 1`**
Fixes #8189 
Fixes #8181

feat: add limit push down to fuse_snapshot

---

src/meta/service/src/store/store_bare.rs
src/meta/sled-store/src/lib.rs
src/meta/sled-store/src/sled_tree.rs
src/meta/sled-store/tests/it/sled_tree.rs
src/meta/sled-store/tests/it/sled_txn_tree.rs

Remove unused API from `SledTree`, and merge APIs with similar
functions, such as `range_keys()`, `range_values()` and `range_kvs()`
and be replaced with a simple `range()`; `insert()` can be replaced with
`append()`.
Make `SledTree` APIs crate-public. Only leave key-space based API public.

refactor(meta/sled): simplify SledTree APIs

---

src/query/expression/src/util.rs

feat(expr): add util::eval_function(), a shortcut to call scalar fucntion

---

src/query/service/src/pipelines/processors/transforms/hash_join/common.rs
src/query/service/src/pipelines/processors/transforms/hash_join/desc.rs
src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state_impl.rs
src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/left_join.rs
src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/right_join.rs
src/query/service/src/pipelines/processors/transforms/hash_join/row.rs
src/query/service/src/sql/executor/pipeline_builder.rs

The ticket aims to optimize right join based tpch 13.
```sql
select
c_count,
count(*) as custdist
from
(
select
c_custkey,
count(o_orderkey) as c_count
from
customer
left outer join
orders
on c_custkey = o_custkey
and o_comment not like '%pending%deposits%'
group by
c_custkey
)
c_orders
group by
c_count
order by
custdist desc,
c_count desc;
```
Before:
Now:
After the ticket, tpch13 will speed up 2x and performance bottleneck will become https://github.com/datafuselabs/databend/issues/8118 (@TCeason is working on it).
Part of https://github.com/datafuselabs/databend/issues/8073

feat(planner): optimize right join

---

Cargo.lock
src/query/storages/index/Cargo.toml
src/query/storages/index/benches/build_from_block.rs

Add benchmark of current xor8 filter building for `i64` and `string` of
length 16 to 32.
Benchmark shows that with `Column::to_values()`, which potentially is an
unnecessary overhead, the time cost for every key is:
```
- i64:    210ns/key
- string: 240ns/key
```
And the benchmark of xor8-filter shows that building a `i64` key takes
about 180 ns/key, which means without modifying xor8-filter, the max
performance boost would be about 25%.
- Part of #8196

chore(storage/index): add benchmark

---

src/common/base/src/base/runtime.rs
src/common/base/tests/it/runtime.rs
src/query/storages/fuse/src/fuse_file.rs
src/query/storages/fuse/src/fuse_segment.rs
src/query/storages/fuse/src/fuse_snapshot.rs
src/query/storages/fuse/src/pruning/pruning_executor.rs

fix : dead lock caused by incorrect semaphore permit control 
by 
- introduce new spawn_batch method (of `Runtime`)
which passes the `OwnedSemaphorePermit` to the task, so that task may release it ontime.
~~~
pub async fn try_spawn_batch_with_owned_semaphore<F, Fut>(
&self,
semaphore: Arc<Semaphore>,
futures: impl IntoIterator<Item = F>,
) -> Result<Vec<JoinHandle<Fut::Output>>>
where
F: FnOnce(OwnedSemaphorePermit) -> Fut + Send + 'static,
Fut: Future + Send + 'static,
Fut::Output: Send + 'static,
~~~
- segment pruner releases the permit before pruning blocks
Fixes #8210

fix: dead lock caused by incorrect semaphore permit control

---

Cargo.lock
src/query/pipeline/sources/src/processors/sources/input_formats/transform_deserializer.rs
src/query/service/src/storages/result/writer.rs
src/query/service/src/storages/stage/stage_table_sink.rs
src/query/storages/fuse/src/io/write/block_writer.rs
src/query/storages/fuse/src/io/write/meta_writer.rs
src/query/storages/fuse/src/operations/commit.rs

* Change io retry from `debug` to `warn`
* Change `info` to `trace` for `transform_deserializer.rs` to less log
Fixes #issue

chore: change log level to warn for io retry

---

src/query/expression/src/date_helper.rs
src/query/functions-v2/src/scalars/datetime.rs
src/query/functions-v2/tests/it/scalars/datetime.rs
src/query/functions-v2/tests/it/scalars/testdata/datetime.txt

- to_yyyymm
- to_yyyymmdd
- to_yyyymmddhhmmss
- to_year
- to_month
- to_day_of_year
- to_day_of_month
- to_day_of_week
- to_hour
- to_minute
- to_second
Part of #8048

feat(query): migrate date to number functions to v2.

---

src/meta/api/src/schema_api.rs
src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs

`list_all_tables()` returns a list of every table that stored in
the meta-store.
It is meant for interanl usages such cleaning up garbage data(e.g.
cleaning up unreferenced object in s3).

feat(meta/schema_api): add API list_all_tables

---

src/query/service/src/servers/http/v1/http_query_handlers.rs
src/query/service/tests/it/servers/http/http_query_handlers.rs

distinguish the error message of  `running query` from  `query not exist`
only to make trouble shooting easier.

feat(http handler): return error when download result of a running query

---

src/query/storages/fuse/src/table_functions/fuse_blocks/fuse_block.rs

add fuse_block() output block file size
Fixes https://github.com/datafuselabs/databend/issues/8285

chore: output block file size

---

Cargo.lock
src/query/service/src/sql/planner/optimizer/heuristic/decorrelate.rs
src/query/service/src/sql/planner/plans/aggregate.rs
src/query/service/src/sql/planner/plans/dummy_table_scan.rs
src/query/service/src/sql/planner/plans/eval_scalar.rs
src/query/service/src/sql/planner/plans/filter.rs
src/query/service/src/sql/planner/plans/limit.rs
src/query/service/src/sql/planner/plans/logical_get.rs
src/query/service/src/sql/planner/plans/logical_join.rs
src/query/service/src/sql/planner/plans/operator.rs
src/query/service/src/sql/planner/plans/sort.rs
src/query/service/src/sql/planner/plans/union_all.rs
tests/logictest/suites/duckdb/sql/aggregate/having/test_having.test
tests/logictest/suites/mode/standalone/explain/limit.test
tests/logictest/suites/mode/standalone/explain/subquery.test

Optimize subquery by deleting redundancy join.
After the ticket, tpch q20 won't oom.
Fixes https://github.com/datafuselabs/databend/issues/8077

feat: optimize subquery by deleting redundancy join

---

Cargo.lock

fix: Query startup too slow for reqsign retry

fix: Query startup too slow for reqsign retry

---

src/query/storages/fuse/src/pruning/pruning_executor.rs
tests/logictest/http_connector.py
tests/logictest/logictest.py

failed to release the permits on time in the block pruner, which may lead to OOM, even if `max_storage_io_requests` is set to a small number,  if the number of blocks is large
Fixes #issue

fix: failed to release the permits on time in the block pruner

---

src/query/functions/src/scalars/comparisons/comparison.rs

Fixes #issue
```
MySQL [(none)]> select count() from numbers(1000000000) where to_string(number) =  10;
+---------+
| count() |
+---------+
|       1 |
+---------+
1 row in set (1.780 sec)
MySQL [(none)]> select count() from numbers(1000000000) where to_string(number) =  10;
ERROR 2013 (HY000): Lost connection to server during query
MySQL [(none)]> select count() from numbers(1000000000) where to_string(number) =  10;
ERROR 2006 (HY000): Server has gone away
No connection. Trying to reconnect...
Connection id:    9
Current database: *** NONE ***
+---------+
| count() |
+---------+
|       1 |
+---------+
1 row in set (0.775 sec)
```

refactor(query): improve comparison number with string

---

.github/actions/test_metactl/action.yml
src/binaries/metactl/snapshot.rs
src/meta/sled-store/src/sled_tree.rs
tests/metactl/test-metactl-restore-new-cluster.sh

fix(meta): import: AsKeySpace::clear() should not entire sled tree

---

src/query/storages/fuse/src/operations/mod.rs
src/query/storages/fuse/src/operations/read_data.rs
src/query/storages/fuse/src/operations/read_partitions.rs

There is no logic change, only code refinement, to make the code clear.
Prepare for #8270 
Fixes #issue

chore: refine the fuse read codes

---

src/meta/service/src/meta_service/meta_leader.rs
src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs

When leaving a node from a meta-service cluster, no matter the node is a
voter and non-voter(learner), it should try the best removing it with
the following step:
- Remove it from membership list.
- Stop replication to it.
- Remove its node info record from meta store.
Before this commit, if the node is not in membership list it won't do
anything, hense there is no way to clean up a dirty state, e.g., to
remove a non-voter(learner).

refactor(meta/service): try best to leave a cluster

---

src/query/pipeline/core/src/pipeline.rs
src/query/service/tests/it/storages/fuse/table_test_fixture.rs
src/query/storages/preludes/src/null/null_table.rs

There are many places to use `Source` or `Sink` builder like this:
```
let mut sink_pipeline_builder = SinkPipeBuilder::create();
for _ in 0..pipeline.output_len() {
let input_port = InputPort::create();
sink_pipeline_builder.add_sink(input_port.clone(), EmptySink::create(input_port));
}
pipeline.add_pipe(sink_pipeline_builder.finalize());
```
This PR adds the `add_source` and `add_sink` functions to simplify the usage.
```
pipeline.add_sink(|input| Ok(EmptySink::create(input)))?;
```
If these two functions are OK, I will move them all to the new in another PR.
Fixes #issue

feat: add_source and add_sink to pipeline to simple the usage

---

src/query/service/src/sql/planner/optimizer/property/property.rs
src/query/service/src/sql/planner/plans/aggregate.rs
tests/logictest/suites/base/15_query/aggregate.test

We derived the wrong data distribution of aggregation if there is more than one group key since we will actually use an internal column `_group_by_key` as the distribute key which cannot be recognized during planning for now.
This can be improved in the future.
Close #8290 
Close #8292

fix(planner): Fix aggregation in cluster mode

---

docs/doc/30-reference/00-api/00-rest.md
src/query/service/src/servers/http/v1/http_query_handlers.rs
src/query/service/src/servers/http/v1/query/http_query.rs
src/query/service/tests/it/servers/http/http_query_handlers.rs
tests/logictest/http_connector.py
tests/logictest/http_runner.py
tests/logictest/suites/mode/standalone/explain/join_reorder/chain.test

step 1 of https://github.com/datafuselabs/databend/issues/8271
a bug of  HTTP logic test is fixed：
`statement query `(compare results)  show `not equal` even if the SQL failed.

feat(http handler): no longer need to call `final_uri` explicitly.

---

src/query/service/tests/it/storages/fuse/table_functions/fuse_snapshot_table.rs
src/query/storages/fuse/src/io/snapshots.rs
src/query/storages/fuse/src/operations/gc.rs
src/query/storages/fuse/src/table_functions/fuse_snapshots/fuse_snapshot.rs
tests/logictest/http_connector.py
tests/logictest/http_runner.py

The "optimize table t purge" statement may incorrectly delete data of pending transactions.
While collecting snapshots from storage, snapshots that have bigger timestamps than  GC root's, should be excluded. 
Fixes #issue

fix: "optimize purge" may incorrectly delete data of pending txs

---

docs/doc/30-reference/30-sql/00-ddl/20-table/10-ddl-create-table.md

docs: create table with external location

---

src/query/ast/src/ast/statements/copy.rs
src/query/ast/src/parser/statement.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/statement.txt

Currently the options to the COPY statement requires order as:
```
~ ( FILES ~ "=" ~ "(" ~ #comma_separated_list0(literal_string) ~ ")")?
~ ( PATTERN ~ "=" ~ #literal_string)?
~ ( FILE_FORMAT ~ "=" ~ #options)?
~ ( VALIDATION_MODE ~ "=" ~ #literal_string)?
~ ( SIZE_LIMIT ~ "=" ~ #literal_u64)?
~ ( MAX_FILE_SIZE ~ "=" ~ #literal_u64)?
~ ( SPLIT_SIZE ~ "=" ~ #literal_u64)?
~ ( SINGLE ~ "=" ~ #literal_bool)?
~ ( PURGE ~ "=" ~ #literal_bool)?
~ ( FORCE ~ "=" ~ #literal_bool)?
```
If we put FORCE option in front of PURGE, we'll get a syntax error. The args order is hard to memorize, makes it hard for users to use the COPY statment.
This PR relax the order requirement about the COPY options, so we can put …

feat(parser): Relax the order requirement about the COPY options

---

src/query/functions-v2/src/scalars/comparison.rs
src/query/functions-v2/tests/it/scalars/comparison.rs
src/query/functions-v2/tests/it/scalars/testdata/comparison.txt
src/query/functions/src/scalars/comparisons/comparison_like.rs
tests/logictest/suites/base/02_function/02_0005_function_compare

Before this pr
query "select 'hello\n' like 'h%'; " will return false.
Because rust regexp lib : `. will match any valid UTF-8 encoded Unicode scalar value except for \n. (To also match \n, enable the s flag, e.g., (?s:.).)`
More description in #8354 
Fixes #8354

fix(query): StringSearchLike vector_vector can not match '\n'

---

src/query/storages/fuse/src/operations/read_data.rs

We can not get the block numbers, let's set the read block source pipe numbers always to max_storage_io_requests.
Fixes #issue

fix: adjust the max io requests with block number not segment number

---

src/query/config/src/inner.rs
src/query/config/src/outer_v0.rs
src/query/service/tests/it/configs.rs
src/query/service/tests/it/storages/testdata/system-tables.txt
src/query/storages/fuse-meta/src/caches/cache.rs

config options for bloom filter cache
- new config options for bloom index cache 
~~~
/// Max number of cached bloom index meta objects
#[clap(long, default_value = "3000")]
pub table_cache_bloom_index_meta_count: u64,
/// Max bytes of cached bloom index, default value is 1GB
#[clap(long, default_value = "1073741824")]
pub table_cache_bloom_index_data_bytes: u64,
~~~
- remove unused config options
~~~
/// Max number of cached table block meta
pub table_cache_block_meta_count: u64,
/// Table memory cache size (mb)
pub table_memory_cache_mb_size: u64,
/// Table disk cache folder root
pub table_disk_cache_root: String,
/// Table disk cache size (mb)
pub table_disk_cache_mb_size: u64,
~~~
Fixes #8279

feat: config options for bloom filter cache

---

Cargo.lock
src/meta/service/Cargo.toml
src/meta/service/src/meta_service/meta_service_impl.rs
src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/tests/it/grpc/metasrv_grpc_api.rs

refactor(meta/binary): record every error when joining/leaving

---

src/binaries/meta/main.rs
src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/tests/it/api/http/cluster_state_test.rs
src/meta/service/tests/it/api/http_service.rs
src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs
src/meta/service/tests/it/tests/service.rs

Databend-meta should allow to join a cluster if it has not yet joined a
cluster, i.e., its raft-log is empty.
Currently, it's only allowed only when the node is uninitialized. Thus
the problem is if the first attempt to join fails, a node can never be
joined.
- Fix: #8383

feat(meta/management): allow to join a cluster if a meta node has no log

---

.github/actions/artifact_download/action.yml
.github/actions/artifact_upload/action.yml
.github/actions/setup_docker/action.yml
.github/workflows/build-tool.yml
.github/workflows/databend-release.yml

Replace deprecating `set-output` command with `$GITHUB_OUTPUT`.
Closes #8342.

ci: migrate deprecating set-output commands

---

src/query/storages/fuse/src/io/snapshots.rs
src/query/storages/fuse/src/operations/gc.rs

should ignore `StorageNotFound` errors in concurrent GC as long as we follow the order of cleaning data, things will be ok
Fixes #issue

fix: should ignore `StorageNotFound` errors in concurrent GC

---

src/query/service/src/pipelines/executor/pipeline_executor.rs
src/query/service/src/pipelines/executor/pipeline_pulling_executor.rs

fix(processor): try fix incorrect error message
related #8352

fix(processor): try fix incorrect error message

---

src/query/ast/src/ast/format/ast_format.rs
src/query/ast/src/ast/statements/table.rs
src/query/ast/src/parser/statement.rs
src/query/catalog/src/table.rs
src/query/planner/src/plans/optimize_table.rs
src/query/service/src/interpreters/interpreter_table_optimize.rs
src/query/service/tests/it/storages/fuse/operations/mutation/full_compact_mutator.rs
src/query/service/tests/it/storages/fuse/operations/mutation/segments_compact_mutator.rs
src/query/service/tests/it/storages/fuse/operations/optimize.rs
src/query/sql/src/planner/binder/ddl/table.rs
src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/operations/compact.rs
src/query/storages/fuse/src/operations/mod.rs
src/query/storages/fuse/src/operations/mutation/abort_operation.rs
src/query/storages/fuse/src/operations/mutation/compact_mutator/full_compact_mutator.rs
src/query/storages/fuse/src/operations/mutation/compact_mutator/segment_compact_mutator.rs
tests/logictest/suites/base/09_fuse_engine/09_0008_fuse_optimize_table

Add a threshold 2 for compact blocks, if the selected blocks are less than 2*max_threads, compact is skipped.
Add a limit to batch compaction.
```
optimize table [database.]table_name compact [segment] [limit segment_count];
```
Fixes #8316 
Fixes #8241

fix: add a threshold for compact block

---

docs/doc/50-manage/00-metasrv/20-metasrv-add-remove-node.md
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs
tests/metactl/config/new-databend-meta-node-2.toml
tests/metactl/config/new-databend-meta-node-3.toml
tests/metactl/test-metactl-restore-new-cluster.sh

A databend-meta node may always be started with `--join` arg.
With this arg, meta node should decide whether to execute the
**join-to-a-cluster** process.
Before this commit it detect if there are logs. This way is not very
relliable: it's possible the leader has setup a replication to this new
node but not yet added it as a **voter**. In such a case, this node will
never be added into the cluster automatically.
In stead, in this commit it detect if there is a **membership** config
that includes this node to decide if to join a cluster. Thus only when a
node has already joined to a cluster(leader committed the membership and
has replicated it to this node), it skips the join process.
- Part of #8383

docs(meta/management): explain when to join a cluster

---

Cargo.lock
Cargo.toml
src/meta/service/src/meta_service/meta_leader.rs
src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/tests/it/grpc/metasrv_grpc_api.rs
src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs
src/meta/types/src/errors/meta_raft_errors.rs

- Upgrade openraft v0.7.4-alpha.2..v0.7.4-alpha.3:
Change-membership does not return error when replication lags.
If `blocking` is `true`, `Raft::change_membership(..., blocking)` will
block until repliication to new nodes become upto date.
But it won't return an error when proposing change-membership log.
- Join a node to cluster in non-blocking mode: the leader does not wait
replication to the new node to become up to date. In case there are a
logs to sync.
- `MetaNode::get_leader()` should have a max timeout. Otherwise it may
block for ever.
- Fix: #8386

refactor(meta/management): non blocking join

---

Cargo.lock
src/query/storages/fuse/Cargo.toml
src/query/storages/fuse/src/io/segments.rs

Read segments in the order of locations.
Fixes #issue

fix: read segments in the order of locations

---

src/query/service/src/pipelines/processors/transforms/hash_join/common.rs
src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state_impl.rs
src/query/service/src/pipelines/processors/transforms/hash_join/join_hash_table.rs
src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/right_mark.rs
src/query/service/src/pipelines/processors/transforms/hash_join/probe_state.rs
src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs
src/query/sql/src/planner/optimizer/heuristic/subquery_rewriter.rs
src/query/sql/src/planner/plans/logical_join.rs
tests/logictest/suites/mode/standalone/explain/subquery.test

The ticket contains two things:
- Right mark join is executed by streaming, there is no blocking pipeline operator. So use right mark join as default correlated subquery join type.
- Fix some bugs in right mark join
Fixes #issue

refactor(planner): use right mark join as subquery's default join type

---

Cargo.lock
src/query/datablocks/Cargo.toml
src/query/datablocks/src/meta_info.rs
src/query/datablocks/tests/it/main.rs
src/query/datablocks/tests/it/meta_info.rs

Add test for MetaInfo
Fixes #8430

ci: Add test for MetaInfo

---

Cargo.lock
src/meta/api/src/util.rs
src/meta/raft-store/Cargo.toml
src/meta/raft-store/src/sled_key_spaces.rs
src/meta/raft-store/src/state_machine/expire.rs
src/meta/raft-store/src/state_machine/mod.rs
src/meta/raft-store/src/state_machine/sm.rs
src/meta/service/src/meta_service/raftmeta.rs
src/meta/sled-store/src/lib.rs
src/meta/sled-store/src/sled_tree.rs

Introduce another key space to meta-store: `Expire` to store the
secondary index `(expire_time, seq) -> key`, as the key-value's primary
index is `key -> (seq, expire_time, value)`.
Because `seq` in the meta-store is globally unique, it may be used to
identify every update to every key.
With this index, cleaning up expired keys can be done in `O(1)` time.
Minor refinements:
- Simplify updating expire time when upsert kv
- Rename `AsTxnKeySpace` to `TxnKeySpace`
- Fix: #8440

feat(meta): add key space `Expire`

---

src/query/functions/src/scalars/comparisons/comparison.rs
tests/logictest/suites/base/02_function/02_0005_function_compare
tests/logictest/suites/base/02_function/02_0045_conditional_function_in
tests/logictest/suites/mode/standalone/explain/join.test

refactor(query): disable comparisions with string and integer

---

src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/operations/compact.rs
src/query/storages/fuse/src/operations/read_data.rs
src/query/storages/fuse/src/operations/recluster.rs

Set the max io requests to max threads when compact&recluster to avoid OOM.
Fixes #issue

fix: avoid oom when compact&recluster

---

src/meta/raft-store/src/state_machine/sm.rs
src/meta/sled-store/src/sled_tree.rs
src/meta/sled-store/src/store.rs
src/meta/sled-store/tests/it/sled_txn_tree.rs

Remove unused `TxnKeySpace::update_and_fetch()`: in a txn, it does not
have to use atomic update. A pair of `get()/set()` would be enough

refactor(meta): remove unused `TxnKeySpace::update_and_fetch()`

---

src/binaries/Cargo.toml
src/binaries/query/main.rs

If the open file limit is less than 65535, set it to 65535.
Fixes #8387

feat(query): get the system open file limits and set

---

src/query/storages/hive/src/hive_file_splitter.rs
src/query/storages/hive/src/hive_parquet_block_reader.rs
src/query/storages/hive/src/hive_partition.rs
src/query/storages/hive/src/hive_table_source.rs

if not passing filesize to parquet reader, opendal will do stat() to get it
original committed by  lizhenwei

feat(hive): add filesize to avoid stat operate in opendal

---

src/meta/raft-store/src/state_machine/expire.rs
src/meta/raft-store/src/state_machine/sm.rs

Prepare for next commit in which upsert-kv will write two records:
- the primary index `key->(seq, meta, value)`,
- and the secondary index for expiring keys: `(expire_time, seq)->key`.

chore(meta): add method get_log_time(): extract propose time from raft log

---

src/query/storages/fuse/src/operations/mutation/compact_mutator/full_compact_mutator.rs
src/query/storages/fuse/src/operations/mutation/compact_mutator/segment_compact_mutator.rs
tests/logictest/suites/base/09_fuse_engine/09_0008_fuse_optimize_table
tests/logictest/suites/base/09_fuse_engine/09_0018_issues

For example
```
optimize table t compact limit 100;
```
When the first 100 segments do not need to be optimized, continue to the next 100 segments. This allows all segments to be optimized.
Fixes #8474

fix(storage): compact limit

---

src/meta/raft-store/src/state_machine/sm.rs
src/meta/raft-store/src/state_machine/sm_kv_api_impl.rs

In order to clean up expired kv record, the already expired value should
also be returned and kept until it is cleaned.
`expire_seq_v()` expires an `SeqV` and returns:
- `(Some, None)` if it expires.
- `(None, Some)` if it does not.
- `(None, None)` if the input is None.
- Part of #8425

chore(meta): expire_seq_v() returns two value.

---

tests/metactl/test-metactl-restore-new-cluster.sh

Problem:
When a databend-meta node starts in **background** with `nohup
databend-meta &`, it does not block until a databend-meta process being
fully ready.
Thus actually all 3 nodes somehow start up simultaneously when bringing
up a testing cluster. Thus node-3 may try to join before the leader
commit the membership change log for node-2. So there is an error:
```
common_meta_types::errors::meta_api_errors::MetaAPIError: the cluster is already undergoing a configuration change at log 1-6 while: join via: 127.0.0.1:28103.
```
Which caused the flaky failure in:
https://github.com/datafuselabs/databend/actions/runs/3336536017/jobs/5521979303
To fix it, sleep a second before starting the next node.

chore(meta/test): fix test-metactl failure: "already undergoing a configuration change"

---

src/query/service/tests/it/storages/fuse/statistics.rs
src/query/storages/fuse/src/statistics/reducers.rs

incorrect index size during reducing blockmetas.
note: block data and index data not affected, only the statistics of accumulated size of index is incorrect
Fixes #issue

fix: incorrect index size during reducing block metas 

---

src/query/sql/src/planner/binder/table.rs
tests/logictest/suites/base/01_system/01_0003_information_schema

sql: select v1.c1 from view as v1 where v1.c1=1 
will not return err: column c1 not exists.
Fixes #8510

fix(planner): view alias

---

src/query/service/src/interpreters/interpreter_copy_v2.rs

feat: add table copied file key expire time
Fixes https://github.com/datafuselabs/databend/issues/8514

feat: add table copied file key expire time

---

Cargo.lock

fix(storage): Only update metrics while read finished
Release note of OpenDAL: https://github.com/datafuselabs/opendal/discussions/898

fix(storage): Only update metrics while read finished

---

src/query/sql/src/planner/binder/table.rs
tests/logictest/suites/base/05_ddl/05_0019_ddl_create_view

Fix this:
select v0.c0 from v0;
befor this pr, will return err `column not exists.`
Detials in #8542 
Fixes #8542

fix(planner): select view column not exists

---

src/meta/raft-store/src/state_machine/sm.rs
src/meta/raft-store/tests/it/state_machine/expire.rs
src/meta/raft-store/tests/it/state_machine/mod.rs
src/meta/service/tests/it/grpc/metasrv_grpc_watch.rs

- Clean up to 32 expired keys before applying a raft-log.
- When modifying(insert/update/delete) a kv record, it emits at most two events:
- If the existent key expires, emit a `delete` event because an
expired key is seen and removed.
- Then, the event of the update follows.
- Fix: #8489
- Fix: #8490
- Fix: #8540

feat(meta): auto-clean expired keys

---

src/meta/proto-conv/src/user_from_to_protobuf_impl.rs
src/meta/proto-conv/src/util.rs
src/meta/proto-conv/tests/it/user_proto_conv.rs
src/meta/proto-conv/tests/it/user_stage.rs
src/meta/protos/proto/user.proto
src/meta/types/src/user_stage.rs
src/query/storages/preludes/src/system/stages_table.rs

feat: Add User Stage Type

---

src/query/catalog/src/table_context.rs
src/query/service/src/auth.rs
src/query/service/src/interpreters/interpreter_role_set.rs
src/query/service/src/servers/mysql/mysql_interactive_worker.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/service/src/sessions/session.rs
src/query/service/src/sessions/session_ctx.rs
src/query/service/tests/it/api/http/status.rs
src/query/service/tests/it/context_function.rs
src/query/service/tests/it/servers/http/http_query_handlers.rs
src/query/service/tests/it/tests/context.rs
src/query/users/src/role_cache_mgr.rs

The behaviour about CURRENT ROLE with auth_role is broken, as the auth_role is set as "account_admin", but `SELECT current_role()` still gets "public".
The expected behaviour is that when the AUTH ROLE is set, it defaults as the CURRENT ROLE, except when X-DATABEND-ROLE is set (which must be one of the AUTH ROLE's children roles).
This PR also made a minor refactor: replace session.set_current_user to session.set_authed_user which plays as an unified entrypoint on authentication success. So instead of manage logics in different handlers, we can collect the works on authenticated success into this method.

fix(session): CURRENT ROLE behavior with AUTH ROLE is set

---

src/query/service/tests/it/storages/fuse/operations/mutation/deletion_mutator.rs
src/query/service/tests/it/storages/fuse/operations/mutation/recluster_mutator.rs
src/query/service/tests/it/storages/fuse/operations/read_plan.rs
src/query/service/tests/it/storages/fuse/pruning.rs
src/query/storages/fuse-meta/src/meta/v1/segment.rs
src/query/storages/fuse/src/operations/mutation/base_mutator.rs
src/query/storages/fuse/src/operations/mutation/compact_mutator/full_compact_mutator.rs
src/query/storages/fuse/src/operations/mutation/compact_mutator/segment_compact_mutator.rs
src/query/storages/fuse/src/operations/mutation/recluster_mutator.rs
src/query/storages/fuse/src/operations/read_partitions.rs
src/query/storages/fuse/src/operations/recluster.rs
src/query/storages/fuse/src/pruning/pruning_executor.rs
src/query/storages/fuse/src/pruning/topn_pruner.rs
src/query/storages/fuse/src/statistics/accumulator.rs
src/query/storages/fuse/src/statistics/reducers.rs
src/query/storages/fuse/src/table_functions/clustering_informations/clustering_information.rs
src/query/storages/fuse/src/table_functions/fuse_blocks/fuse_block.rs

After reading `SegmentInfo` from storage,  block meta is owned by an `Arc<SegmentInfo>` (which may be cached). 
For situations that need block metas only, like pruning, we have no choice but to clone the block meta, which hurts the performance.
In this PR, changes SegmentInfo from
~~~
pub struct SegmentInfo {
....
pub blocks: Vec<BlockMeta>,
....
}
~~~
to
~~~
pub struct SegmentInfo {
....
pub blocks: Vec<Arc<BlockMeta>>,
....
}
~~~
and refactor related components accordingly.
Fixes #issue

refactor: make block meta easier to be cloned

---

website/src/pages/download/index.tsx

fixed default versions, There was an '-nightly' missing

fix: Fix downloading the default version

---

src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/tests/it/meta_node/meta_node_seq_api.rs
src/meta/types/src/errors/kv_app_errors.rs
src/meta/types/src/errors/meta_api_errors.rs
src/meta/types/src/errors/meta_errors.rs
src/meta/types/src/message.rs

During upgrading, different version of databend-query/meta run in a same
cluster. If a message that can not be decoded received, return an
`InvalidReply` error instead of just panicking the program.
Returning such an error might make the cluster unable to operate while
upgrading, but data durability and consistency won't be compromised.

refactor(meta): return InvalidReply if fail to decode a message

---

src/query/service/src/interpreters/interpreter_common.rs
src/query/service/src/interpreters/interpreter_copy_v2.rs

Reuse the StageFile info when filtering the copied files.
List 300 files and do force copy:
```
--rows: 1000000, size: 100*43MB
mysql> COPY into bendlog.log from @log pattern='.*[.]csv$' FILE_FORMAT = (TYPE = 'CSV'  FIELD_DELIMITER = '\t' RECORD_DELIMITER = '\n' SKIP_HEADER=1 COMPRESSION=AUTO) force=true;
Query OK, 0 rows affected (17.80 sec)
--rows: 1000000, size: 100*23MB
mysql> COPY into bendlog.log from @log pattern='.*[.]csv.gz$' FILE_FORMAT = (TYPE = 'CSV'  FIELD_DELIMITER = '\t' RECORD_DELIMITER = '\n' SKIP_HEADER=1 COMPRESSION=AUTO) force=true;
Query OK, 0 rows affected (15.68 sec)
```
Fixes #8574

feat: improve the COPY filting copied files performance

---

src/binaries/query/main.rs
src/common/storage/src/config.rs
src/common/storage/src/operator.rs
src/query/service/src/global_services.rs
src/query/service/tests/it/tests/sessions.rs

feat: Add cache operator in global services

feat: Add cache operator in global services

---

docs/doc/30-reference/30-sql/40-show/show-settings.md
docs/doc/30-reference/30-sql/70-system-tables/system-settings.md
src/query/service/tests/it/storages/testdata/system-tables.txt
src/query/settings/src/lib.rs
tests/fuse-compat/compat-logictest/fuse_compat_write
tests/logictest/suites/base/20+_others/20_0007_random_engine
tests/logictest/suites/mode/standalone/explain/join_reorder/mark.test

Smaller block size gives better cache locality, but it causes much more overhead to schedule the query.
Now the new pipeline engine works better using larger value in memory table tests.
```
MySQL [(none)]> select sum(number) , avg(number)  from numbers_mt(1000000000);
+--------------------+-------------+
| sum(number)        | avg(number) |
+--------------------+-------------+
| 499999999500000000 | 499999999.5 |
+--------------------+-------------+
1 row in set (0.074 sec)
MySQL [(none)]> set  max_block_size = 65536;
Query OK, 0 rows affected (0.003 sec)
MySQL [(none)]> select sum(number) , avg(number)  from numbers_mt(1000000000);
+--------------------+-------------+
| …
```

chore(query): increase max_block_size default value to 65536

---

scripts/setup/rust-toolchain.toml
scripts/setup/rust-tools.txt

ci: Upgrade rust toolchain to 1.67-nightly

ci: Upgrade rust toolchain to 1.67-nightly

---

src/query/service/src/interpreters/interpreter_copy_v2.rs

Copy files in asc order of file last modification time.
Closes #issue

feat: copy files order by last modified time asc

---

Cargo.lock
src/common/arrow/Cargo.toml
src/query/expression/src/deserializations/boolean.rs
src/query/expression/src/deserializations/date.rs
src/query/expression/src/deserializations/empty_array.rs
src/query/expression/src/deserializations/mod.rs
src/query/expression/src/deserializations/null.rs
src/query/expression/src/deserializations/nullable.rs
src/query/expression/src/deserializations/number.rs
src/query/expression/src/deserializations/string.rs
src/query/expression/src/deserializations/timestamp.rs
src/query/expression/src/deserializations/variant.rs
src/query/expression/src/lib.rs
src/query/expression/src/serializations/array.rs
src/query/expression/src/serializations/date.rs
src/query/expression/src/types.rs
src/query/expression/src/types/number.rs
src/query/expression/src/types/string.rs

Migrate deserializations to expression. Since deserializations are still being modified, only some functions have been migrated.
Closes #issue

refactor(query): migrate deserializations to expression

---

website/src/pages/download/index.tsx

The download page is replaced with our own interface @ZhiHanZ @wubx 
Closes #[issue](https://github.com/datafuselabs/databend/pull/8563)

fix: The download page is replaced with our own interface

---

scripts/setup/rust-toolchain.toml

ci: Bump to nightly-2022-11-07 to address https://github.com/rust-lang/cargo/pull/11183

ci: Bump to nightly-2022-11-07 to address rust-lang/cargo#11183

---

rust-toolchain.toml

ci: Bump rust-toolchain to nightly-2022-11-07 instead

ci: Bump rust-toolchain to nightly-2022-11-07 instead

---

scripts/ci/ci-run-stateless-tests-cluster.sh

ci: Enable backtrace to debug cluster related issue
Enable backtrace to help debug https://github.com/datafuselabs/databend/issues/7986

ci: Enable backtrace to debug cluster related issue

---

src/binaries/meta/kvapi.rs
src/binaries/meta/main.rs
src/meta/raft-store/src/state_machine/sm.rs
src/meta/raft-store/src/state_machine/sm_kv_api_impl.rs
src/meta/raft-store/tests/it/state_machine/mod.rs
src/meta/sled-store/src/sled_tree.rs

Otherwise, pushing any events before a transaction being committed
potentially results in duplicated messages.
Replace `NotifyKVEvent` with `Change`, which is more generic to describe an event.

fix(meta): emit kv change events after committing a transaction

---

scripts/ci/ci-run-stateless-tests-cluster.sh

ci: Disable 13_0005_q5 to avoid breaking CI

ci: Disable 13_0005_q5 to avoid breaking CI

---

docker/build-tool/base/Dockerfile
scripts/setup/rust-tools.txt

ci: Install sccache in build-tool:base

ci: Install sccache in build-tool:base

---

src/query/pipeline/transforms/src/processors/transforms/transform_multi_sort_merge.rs

Simple improve:
If the last row in one block is smaller than the next cursor, we can drain the block direclty.
Fix bug:
If the cursor is finished but the input port is not finished, we need to pull new data from the input port.
(Old buggy version: if the cursor is finished, continue to drain the heap).

feat(query): add a simple improve and fix bug for sort.

---

docs/doc/30-reference/30-sql/40-show/show-settings.md
docs/doc/30-reference/30-sql/70-system-tables/system-settings.md
docs/doc/30-reference/30-sql/80-setting-cmds/show-settings.md
src/query/service/tests/it/storages/testdata/system-tables.txt
src/query/settings/src/lib.rs
tests/suites/1_stateful/05_formats/05_01_compact/05_01_02_load_compact_copy_max_size.result
tests/suites/1_stateful/05_formats/05_01_compact/05_01_02_load_compact_copy_max_size.sh

Fix max_threads can not determined automatically
The max_threads has default user_settings `user_setting: UserSetting::create("max_threads", UserSettingValue::UInt64(16)),`
If a connection connect to databend , it will set max_threads = 16, then this if branch will not cover.
```rust
// Overwrite settings from conf or global set.
{
// Set max threads.
if ret.get_max_threads()? == 0 {
let cpus = if conf.query.num_cpus == 0 {
num_cpus::get() as u64
} else {
conf.query.num_cpus
};
ret.set_max_threads(cpus)?;
}
}
```
```shell
➜  ~ cat /proc/cpuinfo|grep process|wc -l
24
➜  ~ mysql -uroot -P3307 -h127.0.0.1 -e "show settings like 'max_threads'"
+-------------+-------+---------+---------+------------------ …
```

fix(query): max_threads can not determined automatically

---

docker/build-tool/base/Dockerfile
scripts/setup/dev_setup.sh

ci: Install sccache in dev-setup to avoid large docker images

ci: Install sccache in dev-setup to avoid large docker images

---

src/query/storages/fuse/fuse/src/io/read/block_reader.rs

refactor: Use range_read instead of read_exact

refactor: Use range_read instead of read_exact

---

src/query/catalog/src/catalog.rs
src/query/catalog/src/catalog_kind.rs
src/query/service/src/api/http/v1/tenant_tables.rs
src/query/service/src/catalogs/catalog_manager.rs
src/query/service/tests/it/storages/fuse/table_test_fixture.rs
src/query/sql/src/executor/physical_plan_builder.rs
src/query/sql/src/planner/binder/table.rs
src/query/sql/src/planner/expression_parser.rs
src/query/storages/fuse/fuse/src/table_functions/clustering_informations/clustering_information_table.rs
src/query/storages/fuse/fuse/src/table_functions/fuse_blocks/fuse_block_table.rs
src/query/storages/fuse/fuse/src/table_functions/fuse_segments/fuse_segment_table.rs
src/query/storages/fuse/fuse/src/table_functions/fuse_snapshots/fuse_snapshot_table.rs
src/query/storages/hive/hive/src/hive_table.rs
src/query/storages/hive/hive/src/lib.rs
src/query/storages/system/src/columns_table.rs
src/query/storages/system/src/engines_table.rs
src/query/storages/system/src/tables_table.rs

unify the catalog name defination to catalog_kind: `default` and `hive`
Closes #issue

refactor(catalog): unify the catalog name defination to catalog_kind

---

src/query/expression/src/evaluator.rs
src/query/expression/src/type_check.rs
src/query/functions-v2/tests/it/scalars/testdata/cast.txt
src/query/functions-v2/tests/it/scalars/testdata/variant.txt

`Evaluator` does no need to call `type_checker` to search the simple cast function anymore, which maybe costable for each chunk.
Closes #issue

chore(query): improve cast in expression

---

Cargo.lock
src/query/functions-v2/Cargo.toml
src/query/functions-v2/src/scalars/comparison.rs
src/query/functions-v2/tests/it/scalars/comparison.rs
src/query/functions-v2/tests/it/scalars/testdata/comparison.txt
src/query/functions/src/scalars/comparisons/comparison_like.rs

Now `l_col like r_col` will generate a hashmap based on r_col, if r_col is huge, it will be oom kill.
sys environment:
> OS: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
> CPU: Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
> Memory: 30G
> Disk: 16G / 197G
```sql
-- databend
CREATE TABLE `orders` (
`o_orderkey` BIGINT,
`o_custkey` BIGINT,
`o_orderstatus` VARCHAR,
`o_totalprice` DOUBLE,
`o_orderdate` DATE,
`o_orderpriority` VARCHAR,
`o_clerk` VARCHAR,
`o_shippriority` INT,
`o_comment` VARCHAR
)
-- ck
SELECT version()
Query id: 73c60cca-5362-4765-b4fa-9e0a7a9cdd8b
┌─version()──┐
│ 22.10.2.11 │
└────────────┘
CREATE TABLE tpch.orders
(
`o_orderkey` Int64,
`o_custkey` Int32,
`o_orderstatus` String, …
```

fix(query): the hashmap will cause oom

---

src/query/settings/src/lib.rs
src/query/storages/hive/hive/src/hive_parquet_block_reader.rs
src/query/storages/hive/hive/src/hive_table.rs

hive parquet stream read should be enabled by default, use `hive_parquet_chunk_size` settings to replace `chunk_size` env.

chore(hive): add hive_parquet_chunk_size to enable stream read of parquet

---

Cargo.lock
src/common/storage/Cargo.toml
src/query/pipeline/sources/Cargo.toml
src/query/service/Cargo.toml
src/query/sql/Cargo.toml
src/query/storages/cache/Cargo.toml
src/query/storages/fuse/fuse-result/Cargo.toml
src/query/storages/fuse/fuse/Cargo.toml
src/query/storages/hive/hive/Cargo.toml
src/query/storages/information-schema/Cargo.toml
src/query/storages/memory/Cargo.toml
src/query/storages/null/Cargo.toml
src/query/storages/random/Cargo.toml
src/query/storages/share/Cargo.toml
src/query/storages/stage/Cargo.toml
src/query/storages/system/Cargo.toml

fix: Bump OpenDAL to 0.19.8
- Release note for opendal https://github.com/datafuselabs/opendal/discussions/924

fix: Bump OpenDAL to 0.19.8

---

src/query/datavalues/src/columns/column.rs
src/query/datavalues/tests/it/columns/array.rs
src/query/datavalues/tests/it/columns/boolean.rs
src/query/datavalues/tests/it/columns/object.rs
src/query/datavalues/tests/it/columns/primitive.rs
src/query/datavalues/tests/it/columns/string.rs

feat: add for_each in Column trait
Closes https://github.com/datafuselabs/databend/issues/8776

feat: add for_each in Column trait

---

src/query/expression/src/chunk.rs
src/query/expression/src/converts/from.rs
src/query/expression/src/converts/to.rs
src/query/expression/src/evaluator.rs
src/query/expression/src/kernels/concat.rs
src/query/expression/src/kernels/filter.rs
src/query/expression/src/kernels/scatter.rs
src/query/expression/src/kernels/take.rs
src/query/expression/src/kernels/take_chunks.rs
src/query/expression/src/lib.rs
src/query/expression/src/utils/display.rs
src/query/expression/src/utils/mod.rs
src/query/expression/src/values.rs
src/query/expression/tests/it/common.rs
src/query/expression/tests/it/kernel.rs
src/query/functions-v2/benches/bench.rs
src/query/functions-v2/tests/it/aggregates/mod.rs
src/query/functions-v2/tests/it/scalars/mod.rs

Columns in a `Chunk` has an individual column id that is not necessarily continuous.
When converting between `Chunk` and `DataBlock`, we assume the ids are continuous.

refactor(expr): allow sparse column id in chunk

---

src/query/service/src/interpreters/interpreter_explain_v2.rs
src/query/service/src/interpreters/interpreter_factory.rs
src/query/service/src/interpreters/mod.rs
tests/logictest/suites/crdb/join
tests/logictest/suites/mode/standalone/explain/fold_count.test
tests/logictest/suites/mode/standalone/explain/join_reorder/chain.test
tests/logictest/suites/mode/standalone/explain/join_reorder/cycles.test
tests/logictest/suites/mode/standalone/explain/join_reorder/star.test
tests/logictest/suites/mode/standalone/explain/nullable_prune.test
tests/logictest/suites/mode/standalone/explain/prune_column.test
tests/logictest/suites/mode/standalone/explain/select_limit_offset.test

refactor(query): disable distribute eval index when explain
fixes #8049

refactor(query): disable distribute eval index when explain

---

src/common/exception/src/exception_code.rs
src/meta/app/src/schema/catalog.rs
src/meta/app/src/schema/mod.rs
src/query/service/src/catalogs/catalog_manager.rs
src/query/service/src/interpreters/interpreter_catalog_drop.rs
src/query/service/src/interpreters/interpreter_factory.rs
src/query/service/src/interpreters/mod.rs
src/query/sql/src/planner/plans/ddl/catalog.rs
tests/logictest/logictest.py
tests/logictest/statistics.py

Signed-off-by: 蔡略 <cailue@bupt.edu.cn>
This PR implements the drop feature of multiple catalogs
Notes:
1. `default` catalog is not allowed to be dropped, a CatalogNotSupported error will be returned
2. dropping unknown catalogs without `IF EXISTS` will return a UnknownCatalog error
1. create and drop by SQL
2. drop unknown catalog
3. drop default catalog

feat: implement drop user defined catalog

---

Cargo.toml

Signed-off-by: 蔡略 <cailue@bupt.edu.cn>
This PR will disable incremental compilation on dev profiles.
Should be recovered when the [ICE](https://github.com/rust-lang/rust/issues/100142) got fixed.

ci: disable incremental compilation on dev

---

src/common/base/src/base/runtime.rs

chore(base): disable runtime block in release binary
fixes #8822

chore(base): disable runtime block in release binary

---

src/query/datavalues/src/types/type_nullable.rs
src/query/sql/src/planner/binder/table.rs
src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs
src/query/sql/src/planner/optimizer/heuristic/prune_unused_columns.rs
src/query/sql/src/planner/optimizer/mod.rs
src/query/sql/src/planner/optimizer/property/mod.rs
src/query/sql/src/planner/optimizer/property/property.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_fold_count_aggregate.rs
src/query/sql/src/planner/plans/aggregate.rs
src/query/sql/src/planner/plans/dummy_table_scan.rs
src/query/sql/src/planner/plans/eval_scalar.rs
src/query/sql/src/planner/plans/filter.rs
src/query/sql/src/planner/plans/limit.rs
src/query/sql/src/planner/plans/logical_get.rs
src/query/sql/src/planner/plans/logical_join.rs
src/query/sql/src/planner/plans/union_all.rs
tests/logictest/suites/base/03_dml/03_0032_select_null_count

If simple count(nullable(col)), fold it.
|now|before optimize|
|:--:|:--:|
| 0.002s | 0.091s |
```sql
CREATE TABLE orders
(
o_orderkey       BIGINT  null,
o_custkey        BIGINT  null,
o_orderstatus    STRING  null,
o_totalprice     DOUBLE  null,
o_orderdate      DATE  null,
o_orderpriority  STRING  null,  
o_clerk          STRING  null, 
o_shippriority   INTEGER  null,
o_comment        STRING  null
);
mysql> select count(o_clerk) from orders;
+----------------+
| count(o_clerk) |
+----------------+
|       15000000 |
+----------------+
1 row in set (0.02 sec)
Read 1 rows, 1.00 B in 0.002 sec., 469.46 rows/sec., 469.46 B/sec.
mysql> select count(o_clerk) from orders;
+----------------+
| …
```

feat(query): optimize count(Nullable(col))

---

docs/doc/14-sql-commands/90-explain-cmds/explain-memo.md
docs/doc/14-sql-commands/90-explain-cmds/explain-raw.md
src/query/sql/src/planner/binder/join.rs
src/query/sql/src/planner/format/display_rel_operator.rs
src/query/sql/src/planner/optimizer/format.rs
src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs
src/query/sql/src/planner/optimizer/heuristic/prune_unused_columns.rs
src/query/sql/src/planner/optimizer/heuristic/subquery_rewriter.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_limit_join.rs
src/query/sql/src/planner/optimizer/rule/rule_implement_hash_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_commute_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_left_associate_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_right_associate_join.rs
src/query/sql/src/planner/optimizer/rule/transform/util.rs
src/query/sql/src/planner/plans/logical_join.rs
src/query/sql/src/planner/plans/operator.rs
tests/logictest/suites/mode/standalone/explain/explain_memo.test

`LogicalInnerJoin` is out of date, it contains all kinds of join, so rename it to `LogicalJoin`
Closes #issue

refactor: rename `LogicalInnerJoin` to `LogicalJoin`

---

src/common/hashtable/src/unsized_hashtable.rs

fix(query): remove useless memcpy when group long string
Closes #issue

fix(query): remove useless memcpy when group long string

---

src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/storages/fuse/fuse/src/operations/commit.rs

if committing to the meta server failed, we can not remove the snapshot file being committed blindly.
only in the case that we are sure that the table state inside the meta server has not been modified, it is safe to delete the snapshot file from storage.
Closes #issue

fix: snapshot removed unsafely during meta commit failure

---

docs/doc/14-sql-commands/80-setting-cmds/show-settings.md
src/query/service/src/interpreters/interpreter_copy_v2.rs
src/query/service/tests/it/storages/testdata/system-tables.txt
src/query/settings/src/lib.rs

* Introduce new settings: `load_file_metadata_expire_hours`,  the COPY file metadata expires after N hours. The default is 24*7 = 7 Days.
* Change the `TableCopiedFileInfo.etag` from MD5 digest(32bytes) to short hash(7bytes).
Closes #8852

feat: add load_file_metadata_expire_hours settings

---

src/binaries/meta/main.rs
src/binaries/query/main.rs
src/common/base/src/base/mod.rs
src/common/base/src/base/runtime.rs
src/common/base/src/base/runtime_tracker.rs
src/common/base/src/base/thread.rs
src/common/base/src/mem_allocator/je_allocator.rs
src/query/service/src/sessions/session_info.rs

refactor(memory-tracker): remove RuntimeTracker, which is barely a wrapper of Arc of MemoryTracker

---

Cargo.lock
docs/doc/10-deploy/06-metasrv/70-metasrv-cli-api.md
src/meta/types/Cargo.toml

docs(meta/cli): CLI commands to access databend-meta KVApi

---

docs/doc/10-deploy/06-metasrv/70-metasrv-cli-api.md

docs(meta/cli): avoid using cli API if possible

---

src/query/expression/src/types.rs
src/query/expression/src/types/any.rs
src/query/expression/src/types/array.rs
src/query/expression/src/types/empty_array.rs
src/query/expression/src/types/generic.rs
src/query/expression/src/types/map.rs
src/query/expression/src/types/null.rs
src/query/expression/src/types/nullable.rs
src/query/expression/src/types/string.rs
src/query/expression/src/types/variant.rs
src/query/expression/src/values.rs

We need to know the memory size of `Scalar` and `Column` in the new expression framework.

feat(expression): Add methods to get memory size of `ValueType`s.

---

src/common/base/src/base/runtime_tracker.rs
src/common/base/src/lib.rs
src/common/base/src/mem_allocator/je_allocator.rs
src/common/base/src/mem_allocator/system_allocator.rs

- Memory tracker methods accept an pointer argument for debugging.
- In order to simplify tracker API, replace `grow_memory()` with
`alloc_memory()` followed by a `dealloc_memory()`,  the similar to
`shrink_memory()`.
- MemoryTracker tracks allocation stats and deallocation stats
respectively, instead of just the delta of them.
- Add missing tracking statements to Jemallocator.

refactor(mem-tracker): send pointer addresses to mem tracker

---

src/common/base/src/base/runtime_tracker.rs

refactor(mem-tracker): add StatBuffer to provide fine grained mem allocation stats buffer

---

src/query/service/src/servers/http/v1/query/execute_state.rs
src/query/service/src/servers/http/v1/query/http_query.rs
src/query/service/src/servers/http/v1/query/page_manager.rs

the original release session/query_context right after the computation is finished,  because only some result/status is useful, but a task is still running.
we can fix it first if this pr does not lead to other problems, and refactor the code later.
Closes  https://github.com/datafuselabs/databend/issues/7888

fix(http handler): avoid dropping runtime when task on it not finished.

---

src/common/base/src/base/mod.rs
src/common/base/src/base/runtime_tracker.rs

Stat of every alloc/dealloc is collected in a global tracker, which is
also backed with a thread local buffer for performance concern.

feat(mem-tracker): add global mem allocation tracker

---

src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_parquet.rs
src/query/pipeline/sources/src/processors/sources/input_formats/input_context.rs
src/query/pipeline/sources/src/processors/sources/input_formats/input_format.rs
src/query/pipeline/sources/src/processors/sources/input_formats/input_format_text.rs
src/query/service/src/interpreters/interpreter_copy_v2.rs

so we can use a split as a table partition later.
Closes #issue

refactor(format): enable get_splits() to be used independently.

---

src/query/service/tests/it/sql/planner/format/mod.rs
src/query/sql/src/executor/expression_builder.rs
src/query/sql/src/executor/format.rs
src/query/sql/src/executor/physical_plan_builder.rs
src/query/sql/src/planner/binder/aggregate.rs
src/query/sql/src/planner/binder/binder.rs
src/query/sql/src/planner/binder/select.rs
src/query/sql/src/planner/binder/table.rs
src/query/sql/src/planner/expression_parser.rs
src/query/sql/src/planner/format/display_rel_operator.rs
src/query/sql/src/planner/metadata.rs
src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs
src/query/sql/src/planner/optimizer/heuristic/subquery_rewriter.rs

In the new expression framework, we will use a `SchemaDataType` to represent data types of columns from a table, which has more information rather than `DataType`, e.g. decimal precision and tuple field names.
This PR changes `ColumnEntry` into an enum of `BaseTableColumn` and `DerivedColumn`.

chore(planner): Refactor Metadata to distinguish between base table column and derived column

---

src/query/storages/fuse/fuse/src/operations/read_data.rs

```
mysql> set max_storage_io_requests = 16;
mysql> create table t1(a int);
mysql> explain pipeline select * from t1;
+---------------------------------------------------------------------------------------------------+
| explain                                                                                           |
+---------------------------------------------------------------------------------------------------+
| CompoundChunkOperator(Rename) × 10 processors                                                     |
|   CompoundChunkOperator(Project) × 10 processors                                                  |
|     CompoundChunkOperator(Project->Rename) × 10 processors …
```

fix(fuse): remove unncessary pipeline merge when read data

---

src/query/service/src/sessions/session_mgr.rs

MySQL conns is added here:
https://github.com/datafuselabs/databend/blob/20bac71c72af8792fc002e202af8e94c6e104efd/src/query/service/src/sessions/session_mgr.rs#L110-L113
But if `Settings::try_create` gets some error from meta like: 
```
{"timestamp":"2022-11-23T18:18:59.683112Z","level":"ERROR","fields":{"message":"MetaGrpcClient error: MetaError(APIError(NetworkError(ConnectionError(ConnectionError { msg: \"address: 172.21.42.72:28103\", source: tonic::transport::error::Error: transport error source: error trying to connect: tcp connect error: Address not available (os error 99) source: tcp connect error: Address not available (os error 99) source: Address not available (os error 99) …
```

fix(mysql): fix mysql conns leak

---

src/query/datablocks/src/kernels/data_block_group_by_hash.rs
src/query/datavalues/src/types/deserializations/array.rs
src/query/datavalues/src/types/deserializations/boolean.rs
src/query/datavalues/src/types/deserializations/date.rs
src/query/datavalues/src/types/deserializations/mod.rs
src/query/datavalues/src/types/deserializations/null.rs
src/query/datavalues/src/types/deserializations/nullable.rs
src/query/datavalues/src/types/deserializations/number.rs
src/query/datavalues/src/types/deserializations/string.rs
src/query/datavalues/src/types/deserializations/struct_.rs
src/query/datavalues/src/types/deserializations/timestamp.rs
src/query/datavalues/src/types/deserializations/variant.rs
src/query/datavalues/tests/it/types/deserializations.rs
src/query/formats/src/field_decoder/json_ast.rs
src/query/formats/src/field_decoder/mod.rs
src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_ndjson.rs
src/query/service/src/interpreters/interpreter_insert_v2.rs
src/query/service/src/pipelines/processors/transforms/group_by/aggregator_groups_builder.rs

part1 of https://github.com/datafuselabs/databend/issues/8949
after this FormatSetting is used only in
```
pub trait TypeSerializer<'a>: Send + Sync {
fn serialize_json_values(&self, _format: &FormatSettings) -> Result<Vec<Value>>;
fn serialize_json_object(
&self,
_valids: Option<&Bitmap>,
_format: &FormatSettings,
) -> Result<Vec<Value>>;
fn serialize_json_object_suppress_error(
&self,
_format: &FormatSettings,
) -> Result<Vec<Option<Value>>>;
}
```

refactor: TypeDeserializer get rid of FormatSetting.

---

src/query/service/src/pipelines/processors/transforms/hash_join/common.rs
src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state_impl.rs
src/query/service/src/pipelines/processors/transforms/hash_join/join_hash_table.rs
src/query/service/src/pipelines/processors/transforms/hash_join/row.rs

The ticket aims to optimize join by merging build table input blocks to more giant blocks which will reduce cache miss during the probe phase.
A simple benchmark for tpch q9 which contains heavy join using 10G tpch data in my local:
**Before: 4s | Now:  2.6s**
Closes #issue

refactor: optimize join by merging build data block

---

src/common/base/src/base/runtime_tracker.rs

refactor(mem-tracker): disable mem-limit when panicking to build backtrace

---

docs/dev/policies/notice.md
src/query/datavalues/src/data_group_value.rs
src/query/datavalues/src/data_value.rs
src/query/storages/system/src/roles_table.rs

I find databend does not use datafusion. Delete the comment.
Closes #8970

chore: remove unused dependencies

---

src/query/functions-v2/src/aggregates/aggregate_approx_count_distinct.rs
src/query/functions-v2/src/aggregates/aggregate_function.rs
src/query/functions/src/aggregates/aggregate_approx_count_distinct.rs
src/query/functions/src/aggregates/aggregate_function.rs

`std::mem::needs_drop::<AggregateApproxCountDistinctState>` is true, so we should drop the state manually.
Closes #issue

fix(query): manually drop_state for ndv

---

src/query/config/src/outer_v0.rs

databend-query.toml:
```
[meta]
embedded_dir = "./.databend/meta_embedded_1"
address = "127.0.0.1:9191" -- deprecated
username = "root"
password = "root"
client_timeout_in_second = 60
auto_sync_interval = 60
```
Start:
```
./databend-query -c databend-query.toml
Databend Query start failure, cause: Code: 1002, displayText = unknown field `address`, expected one of `embedded_dir`, `endpoints`, `username`, `password`, `client_timeout_in_second`, `auto_sync_interval`, `rpc_tls_meta_server_root_ca_cert`, `rpc_tls_meta_service_domain_name` for key `meta` at line 67 column 2, source: None
unknown field `address`, expected one of `embedded_dir`, `endpoints`, `username`, `password`, …
```

fix(meta.config): add deny_unknown_fields

---

.github/workflows/i18n.yml
website/docusaurus.config.js
website/i18n/en-US/code.json
website/i18n/en-US/docusaurus-plugin-content-docs-dev/current.json
website/i18n/en-US/docusaurus-plugin-content-docs/current.json
website/i18n/en-US/docusaurus-theme-classic/navbar.json

This is precisely the first step towards internationalisation/localisation.
- Allows the build of multilingual websites, although no translations have been added.
- Update some json for en-US
- Fix PR title
---
The following tasks still need to be completed:
- Add a link/an edit button to Databend Crowdin.
- Temporarily populate all untranslated documents at once to ensure a build.
- Fix issues about images and links.
This work will be completed in the next PR.

docs: add i18n support 

---

src/common/arrow/Cargo.toml
src/common/hashtable/src/lib.rs
src/common/hashtable/src/table_empty.rs
src/common/hashtable/src/traits.rs
src/common/hashtable/src/unsized_hashtable.rs

migrate table0 to table_empty for unsized hashtable
Closes #issue

chore(query): migrate table0 to table_empty for unsized hashtable

---

docs/doc/10-deploy/07-query/10-query-config.md

Updated the meta configurations in databend-query.toml:
[meta]
endpoints = ["0.0.0.0:9191"]
username = "root"
password = "root"
client_timeout_in_second = 60
auto_sync_interval = 60
Closes #issue

docs: meta configurations in databend-query.toml

---

src/query/config/src/outer_v0.rs

Add `deny_unknown_fields` to QueryConfig, throwing an error during deserialization when encountering unknown fields.
For example:
After we rename `max_memory_usage` to `max_server_memory_usage`, if the user still using `max_memory_usage` in their query config file, it will throw an error.
Rust playground: 
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3bd3f496bf2fde57359b75c2f728723a
Closes #issue

feat(query config): add deny_unknown_fields to QueryConfig

---

src/query/storages/fuse/fuse/src/operations/read_data.rs

* Change the adjusted base block from 160MB to 300MB
* Remove the bloom filter index cache size from max_memory_usage
Test:
Settings:
```
max_memory_usage = 8GB
max_storage_io_requests=1000
```
Query:
```
create table hits1 as select * from hits;
```
```
select * from hits ignore_result;
```
```
INFO common_storages_fuse::operations::read_data: read block data adjust max io requests:23
```
Closes #issue

feat(fuse): Make adjust io requetsts more gentle

---

src/meta/api/src/schema_api_impl.rs

fix: remove TableCopiedFileLockKey protection of upsert_table_copied_file_info in case of copy file concurrently return TxnRetryMaxTimes.
`remove_table_copied_files` and `upsert_table_copied_file_info`all modify `TableCopiedFileInfo`,
so there used to has `TableCopiedFileLockKey` in these two functions to protect TableCopiedFileInfo modification.
In issue: https://github.com/datafuselabs/databend/issues/8897, there is chance that if copy files concurrently, `upsert_table_copied_file_info` may return `TxnRetryMaxTimes`.
So now, in case that `TableCopiedFileInfo` has expire time, remove `TableCopiedFileLockKey`
in each function. In this case there is chance that some `TableCopiedFileInfo` may not be …

fix: remove TableCopiedFileLockKey protection of upsert_table_copied_file_info

---

src/query/codegen/src/writes/register.rs
src/query/expression/src/evaluator.rs
src/query/expression/src/function.rs
src/query/expression/src/register.rs
src/query/expression/src/utils/mod.rs
src/query/functions-v2/benches/bench.rs
src/query/functions-v2/src/scalars/arithmetic_modulo.rs
src/query/functions-v2/src/scalars/comparison.rs
src/query/functions-v2/src/scalars/geo.rs
src/query/functions-v2/src/scalars/string.rs
src/query/functions-v2/src/scalars/string_multi_args.rs
src/query/functions-v2/tests/it/aggregates/mod.rs
src/query/functions-v2/tests/it/scalars/mod.rs

rename `FunctionContext` to `EvalContext`.

refactor(expr): rename FunctionContext

---

src/query/storages/fuse/fuse/src/pruning/topn_pruner.rs

disable string type topn pruning, because the min/max index may be truncated.
Closes #issue

fix(storage): disable string type topn pruning

---

Cargo.lock
src/binaries/query/main.rs
src/common/base/Cargo.toml
src/common/base/src/base/mod.rs
src/common/base/src/base/runtime.rs
src/common/base/src/base/runtime_tracker.rs
src/common/base/src/base/thread.rs
src/common/base/src/mem_allocator/je_allocator.rs
src/common/base/src/mem_allocator/mmap_allocator.rs
src/common/base/src/mem_allocator/system_allocator.rs
src/common/base/tests/it/runtime_tracker.rs

- Feature: add `GLOBAL_TRACKER` to track all memory.
- Refactor: Remove `on_thread_stop()`, use Drop to flush the buffered state.
- Refactor: Change thread local tracker from `Option<T>` to T: a thread
always has a tracker(`ThreadTracker`). A ThreadTracker reports the
allocation stat to a MemoryTracker, or the global tracker:
`GLOBAL_TRACKER`.
- Refactor: Reduce the scope in which it allows to allocated memory for `panic!`
Set a panicking flag to allow `panic!()` to allocate memory.
Use a **guard** to reset the thread-local panicking flag
Other changes:
- Refactor: Generalize `AsyncThreadTracker`: the inner future can be any Future impl.
- Test `AsyncThreadTracker`
- Refactor: remove decr(), use …

refactor(mem-tracker): keep tracker state consistent

---

src/query/functions/src/aggregates/aggregate_approx_count_distinct.rs
src/query/storages/index/src/bloom.rs
src/query/storages/index/src/filters/filter.rs
src/query/storages/index/src/filters/xor8.rs

* Expand `to_values` to loop when `aggregate_approx_count_distinct` accumulating
* Expand `to_values` to loop when xor filter building
Test:
`clid` and `hasgclid` is SMALLINT.
```
create table hits_1 as select clid, hasgclid from hits;
```
Main branch(`to_values`):
NDV:
Xor:
This PR(NDV and Xor memory is gone):
Closes #issue

feat(performance): try reduce aggregate_approx_count_distinct memory alloc when accumulate

---

src/query/service/src/servers/http/clickhouse_handler.rs

fix https://github.com/datafuselabs/databend/issues/8955#issuecomment-1333373881

fix(clickhouse handler): add space between param and body when concat them

---

src/query/sql/src/planner/binder/project.rs
src/query/sql/src/planner/semantic/mod.rs
src/query/sql/src/planner/semantic/name_resolution.rs
tests/logictest/suites/query/case_sensitivity/query.test

`select A.* from (WITH source2 AS (select 1 as e) SELECT * FROM source2) A;`
`A` will transfer to `a` and add to `ColumnBinding`, so the SQL won't find table `A` when `normalize_select_list`.
Introduce `compare_table_name` method to compare table name correctly.
Btw, the ticket also spilt `normalize_select_list` method
Closes #9049

fix: try to fix table name case sensibility

---

src/query/service/tests/it/servers/http/clickhouse_handler.rs

temporarily disable the following case, which currently blocking CI.  
~~~
{
let (status, body) = server.post("sel", "ect 1").await;
assert_eq!(status, StatusCode::OK);
assert_error!(body, "1\n");
}
~~~
Closes #issue

refactor: disable a special case of clickhouse handler

---

src/meta/service/src/configs/inner.rs
src/meta/service/src/configs/outer_v0.rs
src/meta/service/tests/it/configs.rs
src/query/config/src/inner.rs
src/query/config/src/lib.rs
src/query/config/src/outer_v0.rs
src/query/service/tests/it/configs.rs

fix: Add more tests for hive config loading
We should not load args during our unit tests, because clap will try to parse the input for `cargo test`.

fix: Add more tests for hive config loading

---

src/query/datablocks/src/kernels/data_block_sort.rs
tests/logictest/suites/query/join.test

Flaky test: `select * from (SELECT number AS a FROM numbers(10)) x right join (SELECT number AS a FROM numbers(5))  y using(a) order by x.a;`
For the query, it has four fragments:
```
+---------------------------------------------------------------------------------+
| Fragment 0:                                                                     |
|   DataExchange: Shuffle                                                         |
|   Exchange Sink: fragment id: [2]                                               |
|     TableScan: [''.'numbers']                                                   |
|                                                                                 |
| Fragment 1: …
```

fix: right join flaky test failed under cluster mode

---

src/common/base/src/base/runtime_tracker.rs

chore(base): use thread panicking to replace panicking flag
Closes #issue

chore(base): use thread panicking to replace panicking flag

---

scripts/ci/ci-run-stateless-tests-cluster.sh
src/query/service/src/api/rpc/exchange/exchange_transform.rs
src/query/service/src/api/rpc/exchange/exchange_transform_source.rs
src/query/service/src/api/rpc/exchange/statistics_receiver.rs
src/query/service/src/api/rpc/exchange/statistics_sender.rs
src/query/service/src/api/rpc/flight_client.rs
src/query/service/src/api/rpc/packets/packet_data.rs

fix(cluster): try fix broken pipe or connect reset
When we use two-way streaming grpc for data exchange, if the client side is closed and the server side reads data immediately. we will get a broken pipe or connect reset error.
In this pr: we use the ClosingClient to notify the server side to close the connection for avoid errors.
fixes #8221
fixes #7986

fix(cluster): try fix broken pipe or connect reset

---

docs/doc/10-deploy/06-metasrv/30-metasrv-backup-restore.md

docs(meta/service): export from a running service

---

src/query/service/src/servers/mysql/mysql_interactive_worker.rs

Insert SQL does not need to do MySQL federated check. When the amount of insert value is large, canceling this check can reduce the execution time.
Closes #issue

chore(query): insert SQL ignore mysql federated check

---

docs/doc/14-sql-commands/00-ddl/20-table/60-optimize-table.md
src/query/service/tests/it/storages/fuse/operations/optimize.rs
src/query/service/tests/it/storages/fuse/operations/purge_drop.rs
src/query/service/tests/it/storages/fuse/operations/purge_truncate.rs
src/query/service/tests/it/storages/fuse/table_test_fixture.rs
src/query/storages/fuse/fuse/src/io/snapshots.rs
src/query/storages/fuse/fuse/src/operations/gc.rs
src/query/storages/fuse/fuse/src/operations/statistic.rs

fix: purge table statistic files
add test case.
updated (by @dantengsky )
the main functionality of this PR is to purge table statistic files while doing `optimize table ... purge`.
pls correct me if I misunderstood @lichuang 
Closes https://github.com/datafuselabs/databend/issues/9054

fix: purge table statistic files

---

Cargo.lock
src/query/expression/src/chunk.rs
src/query/expression/src/evaluator.rs
src/query/expression/src/function.rs
src/query/expression/src/kernels/group_by.rs
src/query/expression/src/kernels/sort.rs
src/query/expression/src/type_check.rs
src/query/storages/fuse/fuse/src/pruning/pruner.rs
src/query/storages/fuse/fuse/src/pruning/range_pruner.rs
src/query/storages/index/Cargo.toml
src/query/storages/index/benches/build_from_block.rs
src/query/storages/index/src/bloom.rs
src/query/storages/index/src/filters/xor8.rs
src/query/storages/index/src/lib.rs
src/query/storages/index/src/range_filter.rs
src/query/storages/index/tests/it/filters/bloom_filter.rs
src/query/storages/index/tests/it/filters/xor8.rs

- Reimplement `RangeFilter` and `BloomFilter` with the new expression in the `expression` branch,
- Reimplement the tests and benchmark.
The benchmark result is 2x faster than the original implementation which seems too good to be true. 🤔  
Closes https://github.com/datafuselabs/databend/issues/9038

feat(expr): migrate storages/index

---

src/query/sql/src/planner/optimizer/heuristic/prewhere_optimization.rs
tests/logictest/suites/base/03_dml/03_0005_select_filter

```sql
select * from t1 where 's' not in ('x', 'b', 'c', 'd') or to_nullable(null);
-- return empty block
```
if in function args len()>3, the filter will be set with [(not(in('s', (x, b, c, d))) or NULL).
Now in this query prewhere_column is empty , the data_block will be empty; and because of NULL the predicate will be nullable(bool).
So, in cast_to_nonull_boolean will return boolean columnRef.
So in filter_exists, the count_zeros and rows is 0. 
the (!filter_exists) will return true, so generate on empty block.
The root cause is predicate is some,  prewhere_column is empty.
So if prewhere_column is empty, logical.prewhere_column will be set as the smallest column in get.columns.
Closes #9083

fix: prewhere_column empty and predicate is not const will return empty

---

src/query/storages/fuse/fuse/src/io/mod.rs
src/query/storages/fuse/fuse/src/io/segments.rs
src/query/storages/fuse/fuse/src/operations/mutation/compact/compact_transform.rs

This bug is due to the fact that compact transform reads and writes blocks concurrently, and there was no limit to the number of concurrent requests before, which may lead to excessive io requests and tcp connect error.
```
MySQL [(none)]> optimize table hits compact;
ERROR 1105 (HY000): Code: 4000, displayText = Unexpected (persistent) at read, context: { called: http_util::Client::send_async, service: s3, path: 1/94363/_b/02c89d8096504e4c97fde3e56sd17875_v0.parquet, range: 426216-426309 } => send async request, source: error sending request for url (http://127.0.0.1:9900/testbucket/local_7150/1/94363/_b/02c89d8096504e4c97fde3e56sd17875_v0.parquet): error trying to connect: tcp connect error: …
```

fix: too many io requests for read blocks during compact

---

src/binaries/query/main.rs

```
Version: v0.8.144-nightly-79623a7(rust-1.67.0-nightly-2022-12-08T06:49:43.133656246Z)
Logging:
file: enabled=true, level=ERROR, dir=./.databend/logs, format=json
stderr: enabled=false(To enable: LOG_STDERR_ON=true or RUST_LOG=info), level=INFO, format=text
Meta: connected to endpoints [
"172.16.172.42:9191",
]
Memory: unlimited
Cluster: standalone
Storage: s3 | bucket=bohusg,root=,endpoint=oss-ap-southeast-1-internal.aliyuncs.com
Cache: none
Builtin users:
Admin
listened at 0.0.0.0:8080
MySQL
listened at 0.0.0.0:3307
connect via: mysql -uroot -h0.0.0.0 -P3307
Clickhouse(http)
listened at 0.0.0.0:8124
usage:  echo 'create table test(foo string)' | curl -u root: '0.0.0.0:8124' --data-binary  @- …
```

feat: print memory limit and cluster info when query start

---

Makefile
scripts/setup/rust-toolchain.toml

- add miri check
- miri does not support SIMD, so with `--no-default-features` flags
Closes #issue

chore: add miri command

---

src/query/sql/src/executor/physical_plan.rs
src/query/sql/src/executor/physical_plan_builder.rs
src/query/sql/src/planner/optimizer/distributed/distributed.rs
tests/logictest/suites/mode/cluster/04_0002_explain_v2

The ticket contains two things:
1. A quick fix for https://github.com/datafuselabs/databend/issues/9178: don't push down topk to `Merge` when it's child is `Aggregate`
2. Remove some `unreachable!` to prevent panic and return specific error.
Closes https://github.com/datafuselabs/databend/issues/9178

fix: don't push down topk to `Merge` when it's child is `Aggregate`

---

scripts/ci/deploy/databend-query-cluster-3-nodes.sh

databend-meta is brought up in background, after listening established,
a testing script should give it some more time to let it finish the
cluster formation, i.e., joining the cluster.
- Fix: #9157

chore(testing): wait a second to let cluster formation complete

---

src/query/service/tests/it/storages/fuse/operations/analyze.rs
src/query/storages/fuse/fuse/src/operations/truncate.rs

fix: truncate fuse table reset ts location to None.
Closes #issue

fix: truncate reset ts location

---

src/common/jsonb/src/functions.rs
src/common/jsonb/tests/it/functions.rs

Bug fix double-quote in `get_path()` and add more test cases.

fix: double-quote in get_path

---

Cargo.lock
Cargo.toml
src/common/arrow/src/lib.rs
src/common/arrow/src/schema_projection.rs
src/query/storages/parquet/src/parquet_reader/deserialize.rs
src/query/storages/parquet/src/parquet_reader/filter.rs
src/query/storages/parquet/src/parquet_reader/meta.rs
src/query/storages/parquet/src/parquet_reader/mod.rs
src/query/storages/parquet/src/parquet_source.rs
src/query/storages/parquet/src/table_function/read.rs
src/query/storages/parquet/src/table_function/table.rs

- Push down filter to parquet reader.
- Convert `ArrowSchema` to `DataSchema` only when convert `ArrowChunk` to `DataBlock`.
Closes #9135

feat: push down filter to parquet reader.

---

src/meta/proto-conv/src/user_from_to_protobuf_impl.rs
src/meta/proto-conv/src/util.rs
src/meta/proto-conv/tests/it/user_proto_conv.rs
src/meta/proto-conv/tests/it/user_stage.rs
src/meta/protos/proto/user.proto
src/meta/types/src/user_stage.rs
src/query/formats/src/field_encoder/csv.rs
src/query/formats/src/file_format_type.rs
src/query/formats/src/format_option_checker.rs
src/query/formats/src/output_format/csv.rs
src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_csv.rs
src/query/sql/src/planner/binder/copy.rs
src/query/sql/src/planner/binder/table.rs
tests/logictest/suites/base/05_ddl/05_0016_ddl_stage
tests/logictest/suites/base/06_show/06_0011_show_stages

Add `quote` to FileFormatOptions so that we can move old streaming load syntax to new internally.
Closes #9212

feat: Add quote to FileFormatOptions

---

.github/workflows/databend-release.yml
.github/workflows/production.yml

For hive production and release, switching to github hosted runners
- no midnight shutdown
- with github cli for publish binary
For deb package release, remove sha256sums, since github releases seem to rename packages
Fixes #9218

ci: github hosted runner for hive release

---

Cargo.lock
src/common/io/Cargo.toml
src/common/io/src/cursor_ext/cursor_read_string_ext.rs
src/common/io/tests/it/cursor_ext/fast_read_text_ext.rs
src/common/io/tests/it/cursor_ext/mod.rs
src/query/formats/src/field_decoder/fast_values.rs
src/query/formats/src/field_decoder/mod.rs
src/query/formats/src/field_decoder/row_based.rs
src/query/service/Cargo.toml
src/query/service/src/interpreters/interpreter_insert_v2.rs

Using the `Aho-Corasick` algorithm to find all `'` and `\` positions and then use those positions to jump to the string text end, instead of step-by-step iterating over the buffer. Since the `Aho-Corasick` algorithm can use SIMD instructions to accelerate the search process, it can greatly speed up the process of reading strings.
Inserting 100M test data, the original `ValueSource::read` takes 8.23s, after optimization, the total time for `ValueSource::read` and `Aho-Corasick` algorithms to find positions is 3.97s, which reduces the time consumption by 4.26s.
Closes #issue

feat(query): fast parse insert values

---

src/query/service/src/pipelines/processors/transforms/hash_join/common.rs
tests/logictest/suites/mode/cluster/broadcast_join.test
tests/logictest/suites/query/join.test

create a const nullable column for an empty inner column with nonempty validity, to avoid the inconsistent length of the inner column and validity.
Closes #9163

fix(planner): fix nullable column validity not equal

---

src/meta/client/src/grpc_action.rs
src/meta/client/src/grpc_client.rs
src/meta/client/src/lib.rs
src/meta/client/tests/it/grpc_server.rs

refactor(meta): remove back compatability supporting code

---

src/meta/api/src/schema_api_impl.rs
src/meta/raft-store/src/state_machine/sm.rs
src/meta/raft-store/src/state_machine/sm_kv_api_impl.rs
src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/src/watcher/watcher_manager.rs
src/meta/service/tests/it/grpc/metasrv_grpc_kv_api_restart_cluster.rs
src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs
src/meta/service/tests/it/tests/meta_node.rs

refactor(meta/watcher): just use Change as event type

---

docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md

1.  desc options format by format
2.  add notices for CSV/TSV
3.  add some options
4.  add 'Data loading only' for some options.
5.  add 'Supported values'  for some options.
Closes https://github.com/datafuselabs/databend/issues/9216

docs(copy): update format_options.

---

src/common/base/src/mem_allocator/mmap_allocator.rs

fix(base): fix memory lost when mmap alloc panic
Closes #issue

fix(base): fix memory lost when mmap alloc panic 

---

Cargo.lock

fix(storage/s3): IMDS_v2 should be fallback after OIDC token

fix(storage/s3): IMDS_v2 should be fallback after OIDC token

---

src/query/functions/src/scalars/function_adapter.rs

Some functions need to get the first value but we did not ensure that the input column has at least one row.
Closes #issue

fix(query): short empty eval in adaptor

---

src/query/service/src/interpreters/interpreter_role_drop.rs
src/query/service/src/interpreters/interpreter_role_set.rs
src/query/service/src/sessions/session.rs
tests/logictest/suites/base/05_ddl/05_0015_ddl_drop_role

unset the current role when the role is dropped.
Closes #9229

fix(query): fix wrong current_role when drop the role

---

.github/workflows/databend-release.yml
src/binaries/query/main.rs

Most modern x86-64 based CPU has supported `sse4.2`, we can enable this feature flag.
Closes #issue

feat(query): enable sse4.2 in x86-64 releaser

---

src/query/ast/src/ast/expr.rs
src/query/ast/src/ast/format/syntax/expr.rs
src/query/ast/tests/it/testdata/expr.txt
src/query/ast/tests/it/testdata/query.txt
src/query/ast/tests/it/testdata/statement.txt
src/query/service/tests/it/sql/planner/semantic/name_resolution.rs
tests/logictest/suites/base/05_ddl/05_0015_ddl_drop_role
tests/logictest/suites/base/05_ddl/05_0019_ddl_create_view
tests/logictest/suites/base/06_show/06_0001_show_create_table
tests/logictest/suites/mode/standalone/explain/explain.test

Add parentheses for `Expr::UnaryOp` and `Expr::BinaryOp` to fix the wrong query in view.
Closes #9164

fix(query): fix create view with nestd UnaryOp and BinaryOp expression

---

.github/actions/artifact_failure/action.yml

It's too slow to upload files one by one.

ci: make tarball before upload failure artifact

---

Cargo.lock
Cargo.toml

chore: Use tagged opendal version instead

chore: Use tagged opendal version instead

---

src/query/sql/src/planner/binder/location.rs
src/query/sql/tests/location.rs

feat: Allow load credential from env if allow insecure
Use `allow-insecure` to control the credential loader logic. I will polish this part later at https://github.com/datafuselabs/opendal/issues/1088

feat: Allow load credential from env if allow insecure

---

src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_csv.rs
tests/suites/0_stateless/14_clickhouse_http_handler/14_0007_http_clickhouse_input_format_diagnostic.sh

the original `"CSV allow ending with ',', but should not have data after it"` is confusing most of the time, and `field_delimiter` should be an option.
related https://github.com/datafuselabs/databend/pull/9268#issuecomment-1358753069

fix(CSV): refine error message.

---

src/meta/client/src/grpc_client.rs
src/meta/service/src/api/grpc_server.rs
src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/src/watcher/mod.rs
src/meta/service/src/watcher/watcher_manager.rs
src/meta/service/src/watcher/watcher_stream.rs
src/meta/service/tests/it/grpc/metasrv_grpc_watch.rs

- Add `EventDispatcherHandle` as control handle of the meta node
internal event dispatcher. It provides a `request` method to let
users run a user-defined function with a mutable reference to
`EventDispatcher`.
- Re-organize event watcher attribuites into `WatcherInfo`.
- Test the count of watchers.

refactor(meta/watch): test watcher count

---

Cargo.lock
src/common/exception/Cargo.toml
src/common/storage/Cargo.toml
src/query/pipeline/sources/Cargo.toml
src/query/service/Cargo.toml
src/query/sharing-endpoint/Cargo.toml
src/query/sharing/Cargo.toml
src/query/sql/Cargo.toml
src/query/storages/cache/Cargo.toml
src/query/storages/fuse/Cargo.toml
src/query/storages/hive/hive/Cargo.toml
src/query/storages/information-schema/Cargo.toml
src/query/storages/memory/Cargo.toml
src/query/storages/null/Cargo.toml
src/query/storages/parquet/Cargo.toml
src/query/storages/random/Cargo.toml
src/query/storages/share/Cargo.toml
src/query/storages/stage/Cargo.toml
src/query/storages/system/Cargo.toml

chore: Bump opendal to 0.23 for hdfs blocking ops

chore: Bump opendal to 0.23 for hdfs blocking ops

---

Cargo.lock
src/query/functions/Cargo.toml
src/query/functions/src/scalars/comparisons/comparison_like.rs
tests/sqllogictests/suites/base/20+_others/20_00010_expression_string_like

- introduces new crate dependency `memchr`.
- for string search expression with pattern  `%NEEDLE%`, use `memchr::memmem::find`
Closes #issue

feat: use `memmem` for string search pattern `%needle%`

---

src/query/storages/fuse/src/io/read/block_reader.rs
src/query/storages/fuse/src/metrics/fuse_metrics.rs

* Introduce a new perf counter:remote_io_copy_milliseconds to measure the IO copy during read columns
Closes #issue

feat: add read column io copy perf counter

---

src/query/storages/fuse/src/io/read/block_reader.rs
src/query/storages/fuse/src/io/read/block_reader_native.rs
src/query/storages/fuse/src/io/read/block_reader_parquet.rs
src/query/storages/fuse/src/metrics/fuse_metrics.rs

* add native perf counter
* add new perf counter `remote_io_deserialize_milliseconds`
Closes #issue

feat: add fuse source deser perf counter

---

src/query/storages/table-meta/src/table/table_keys.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0001_remote_insert

Add logic test for table compression:
```
CREATE TABLE table ... Engine = fuse COMPRESSION = 'NONE|ZSTD|LZ4|SNAPPY';
```
Closes #issue

feat: add table compression logic test

---

tests/sqllogictests/src/client/http_client.rs
tests/sqllogictests/src/client/mod.rs
tests/sqllogictests/src/main.rs

1. One test file will have a new connection
2. Refactor some code
Closes #issue

feat: one test file one new connection

---

src/query/settings/src/lib.rs

chore(query): fix wrong setting value for parquet uncompressed buffer
Closes #issue

chore(query): fix wrong setting value for parquet uncompressed buffer

---

scripts/ci/deploy/config/databend-query-node-1.toml
scripts/ci/deploy/config/databend-query-node-2.toml
scripts/ci/deploy/config/databend-query-node-3.toml
scripts/ci/deploy/config/databend-query-node-shared.toml
src/query/config/src/inner.rs
src/query/config/src/outer_v0.rs
src/query/service/tests/it/configs.rs
src/query/service/tests/it/storages/testdata/configs_table_basic.txt
src/query/storages/fuse/src/operations/read_data.rs
src/query/storages/parquet/src/table_function/read.rs
src/query/storages/table-meta/src/caches/cache.rs

rename config item `table_cache_enabled` to `table_meta_cache_enabled`
Closes #issue

refactor: rename config item `table_cache_enabled` to `table_meta_cache_enabled`

---

website/docusaurus.config.js

Allows for broken links to exist at build time to facilitate moving forward with translation
This is only a temporary solution, possibly a bug in docusaurus, and will be followed up as soon as it is resolved upstream.
Closes #issue

docs(website): allow broken links

---

src/query/settings/src/lib.rs

use logical CPU number as default value of num_cpus
Closes #issue

fix: use logical CPU number as default value of num_cpus

---

src/query/storages/common/src/block.rs

disable parquet encoding due to performance issues (decoding consumes too many CPU resources)
Closes #issue

refactor: disable parquet encoding due to performance issue

---

website/blog/2022-12-29-sqllogictest-framework.md

Part of https://github.com/datafuselabs/databend/issues/9174

docs: blog for new sqllogictest framework

---

Cargo.lock
Cargo.toml

Using thiserror to replace failure
- https://github.com/datafuse-extras/limits-rs/tree/thiserror
- https://github.com/aesedepece/limits-rs/pull/1
Closes #9414

chore(deps): limits-rs with thiserror

---

src/query/storages/fuse/src/io/read/block_reader.rs
src/query/storages/fuse/src/io/read/block_reader_native.rs
src/query/storages/fuse/src/io/read/block_reader_parquet.rs
src/query/storages/fuse/src/operations/mutation/compact/compact_transform.rs
src/query/storages/fuse/src/operations/mutation/deletion/deletion_source.rs
src/query/storages/fuse/src/operations/read/parquet_data_source_deserializer.rs
src/query/storages/fuse/src/operations/read/parquet_data_source_reader.rs
src/query/storages/table-meta/src/meta/compression.rs
src/query/storages/table-meta/src/meta/mod.rs
src/query/storages/table-meta/src/meta/statistics.rs
src/query/storages/table-meta/src/meta/v0/segment.rs
src/query/storages/table-meta/src/meta/v1/segment.rs
src/query/storages/table-meta/src/meta/v1/snapshot.rs
src/query/storages/table-meta/src/meta/v1/table_snapshot_statistics.rs
src/query/storages/table-meta/src/meta/versions.rs

This PR only refactored, not logic changed.
* `table-meta/common.rs` -> `staticits.rs` and `compression.rs`
* make `block_reader_parquet.rs` function name more readable
Closes #issue

refactor(fuse): better table-meta and parquet reader function

---

.cargo/config.toml
.gitignore
Cargo.lock
Cargo.toml
src/binaries/Cargo.toml
src/binaries/query/main.rs
src/common/base/Cargo.toml
src/query/storages/system/Cargo.toml

introduces built-in malloc conf  `percpu_arena:percpu,oversize_threshold:0,muzzy_decay_ms:5000,dirty_decay_ms:5000`.
benchmarks(mainly on the test data set of `hits`) show that the above malloc conf can significantly reduce the system CPU usage (page faults) caused by the large size memory allocations, e.g. during decompression, etc.
thus we make this configuration as default during building. 
during startup of databend-query, malloc conf will be shown like this:
~~~
Databend Query
Version: v0.8.167-nightly-c32f0d1(rust-1.67.0-nightly-2022-12-30T07:38:55.015661976Z)
Logging:
...
Memory:
limit: unlimited
allocator config: percpu_arena:percpu,oversize_threshold:0,muzzy_decay_ms:5000,dirty_decay_ms:5000 …

feat: introduce built-in malloc conf

---

Cargo.lock
Cargo.toml
src/common/metrics/tests/it/main.rs
src/query/service/tests/it/storages/system.rs

use a patched version of crate `metrics`, which disables the histogram.
NOTE:
this is a temp workaround, histograms are highly likely to be back soon : )
Closes #issue

fix: memory leak due to histogram metrics

---

src/query/ast/src/ast/statements/copy.rs
src/query/ast/src/parser/stage.rs
src/query/ast/tests/it/testdata/statement.txt
src/query/sql/src/planner/binder/copy.rs
src/query/sql/src/planner/binder/ddl/stage.rs
src/query/sql/src/planner/binder/ddl/table.rs
src/query/sql/src/planner/binder/location.rs
src/query/sql/src/planner/binder/table.rs
src/query/sql/tests/location.rs
tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables

Check input connection params when do parse URI.
Closes #8380

feat: Check connection params

---

Cargo.lock
src/query/storages/cache/Cargo.toml
src/query/storages/cache/src/lib.rs
src/query/storages/cache/src/object.rs
src/query/storages/cache/src/providers/by_pass_cache.rs
src/query/storages/cache/src/providers/memory_items_cache.rs
src/query/storages/cache/src/settings.rs
src/query/storages/cache/tests/it/by_pass_cache.rs
src/query/storages/cache/tests/it/memory_items_cache.rs

Add to_bytes and from_bytes for CachedObject, and make the T provider define the serialize and deserialize.
Closes #issue

refactor(storage/cache): add to_bytes and from_bytes for CachedObject

---

.github/workflows/dev-linux.yml
.github/workflows/dev-macos.yml

We are developing on branch expression and expect no ci on it.
Closes #issue

ci: only run dev ci for pull request to main

---

src/query/service/src/auth.rs
src/query/service/src/servers/http/http_services.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/service/src/sessions/session.rs
src/query/service/tests/it/servers/http/clickhouse_handler.rs
src/query/service/tests/it/servers/http/http_query_handlers.rs
src/query/service/tests/it/tests/context.rs
src/query/users/src/jwt/authenticator.rs
src/query/users/src/jwt/jwk.rs

I runs an integration tests environment which runs a jwks endpoint and databend-query, but in the environment, it's hard to keep the start up order between databend-query and the jwks endpoint.
When databend-query started eariler than the jwks endpoint, it'd panic on start up with the following error:
```
Databend Query start failure, cause: Code: 1051, displayText = Could not download JWKS: error sending request for url (https://jwks.xxx.svc:8080/.well-known/jwks.json): error trying to connect: dns error: no record found for Query { name: Name("jwks.xxx.svc."), query_type: AAAA, query_class: IN }.
```
This PR makes the following changes:
- loading JWKS in a lazy manner, makes the JWKS endpoint not …

fix: Lazy load JWKS

---

docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md

added a note: "The parameter ON_ERROR currently does not work for parquet files." to COPY INTO.
Closes #issue

docs: on_error not for parquet

---

src/meta/app/src/schema/table.rs

chore(meta): use explicit import. avoid using prelude::*;

---

Cargo.lock

fix: OpenDAL range_read will return temporary error if possible

fix: OpenDAL range_read will return temporary error if possible

---

Cargo.lock
src/common/building/Cargo.toml
src/common/building/src/lib.rs
src/query/service/Cargo.toml
src/query/service/build.rs
src/query/service/src/databases/system/build_options_table.rs
src/query/service/src/databases/system/mod.rs
src/query/service/src/databases/system/system_database.rs
src/query/service/tests/it/storages/testdata/columns_table.txt

```bash
MySQL [(none)]> select * from system.build_options;
+------------------------+---------+
| available_features     | enabled |
+------------------------+---------+
| default                |       1 |
| io-uring               |       0 |
| thrift                 |       0 |
| hive                   |       0 |
| memory-profiling       |       0 |
| tokio-console          |       0 |
| simd                   |       1 |
| common-hive-meta-store |       0 |
| common-storages-hive   |       0 |
| storage-hdfs           |       0 |
| tempfile               |       0 |
+------------------------+---------+
11 rows in set (0.032 sec)
```
Closes #issue

feat(system): add build options table

---

src/query/service/tests/it/storages/fuse/statistics.rs
src/query/storages/fuse/src/operations/append.rs
src/query/storages/fuse/src/operations/delete.rs
src/query/storages/fuse/src/operations/mutation/compact/compact_transform.rs
src/query/storages/fuse/src/pruning/pruner.rs
src/query/storages/fuse/src/statistics/cluster_statistics.rs
src/query/storages/hive/hive/src/hive_table_source.rs

Now the FunctionContext::default only used in table_scan_to_format_tree.  
```
fn table_scan_to_format_tree(
plan: &TableScan,
metadata: &MetadataRef,
) -> Result<FormatTreeNode<String>> {
if plan.table_index == DUMMY_TABLE_INDEX {
return Ok(FormatTreeNode::new("DummyTableScan".to_string()));
}
let func_ctx = FunctionContext::default();
...
```
Closes #issue

feat: all func_ctx used by run or execute try get from tablectx

---

src/query/service/src/schedulers/fragments/fragmenter.rs
src/query/service/src/schedulers/fragments/plan_fragment.rs
src/query/sql/src/executor/explain.rs
src/query/sql/src/executor/format.rs
src/query/sql/src/executor/physical_plan.rs
src/query/sql/src/executor/physical_plan_builder.rs
src/query/sql/src/executor/physical_plan_visitor.rs
src/query/sql/src/planner/optimizer/property/datum.rs
tests/sqllogictests/suites/mode/cluster/04_0002_explain_v2.test
tests/sqllogictests/suites/mode/cluster/exchange.test
tests/sqllogictests/suites/mode/standalone/explain/explain.test
tests/sqllogictests/suites/mode/standalone/explain/fold_count.test
tests/sqllogictests/suites/mode/standalone/explain/join.test
tests/sqllogictests/suites/mode/standalone/explain/join_reorder/chain.test
tests/sqllogictests/suites/mode/standalone/explain/join_reorder/cycles.test
tests/sqllogictests/suites/mode/standalone/explain/join_reorder/mark.test
tests/sqllogictests/suites/mode/standalone/explain/join_reorder/star.test
tests/sqllogictests/suites/mode/standalone/explain/limit.test
tests/sqllogictests/suites/mode/standalone/explain/nullable_prune.test
tests/sqllogictests/suites/mode/standalone/explain/prune_column.test
tests/sqllogictests/suites/mode/standalone/explain/select.test
tests/sqllogictests/suites/mode/standalone/explain/select_limit_offset.test
tests/sqllogictests/suites/mode/standalone/explain/subquery.test
tests/sqllogictests/suites/mode/standalone/explain/union.test

Support display estimated rows information in explain result.
Example:
Closes #9397

feat(planner): Support display estimated rows in `EXPLAIN`

---

src/meta/proto-conv/src/config_from_to_protobuf_impl.rs
src/meta/proto-conv/src/data_from_to_protobuf_impl.rs
src/meta/proto-conv/src/database_from_to_protobuf_impl.rs
src/meta/proto-conv/src/lib.rs
src/meta/proto-conv/src/share_from_to_protobuf_impl.rs
src/meta/proto-conv/src/table_from_to_protobuf_impl.rs
src/meta/proto-conv/src/user_from_to_protobuf_impl.rs
src/meta/proto-conv/src/util.rs
src/meta/proto-conv/tests/it/proto_conv.rs
src/meta/proto-conv/tests/it/user_proto_conv.rs

This is a compatible change.
There should be two **backward compatible** version defined:
One for the reader to define the min version of message it can read
and the other for the message to define the min version of the reader
that can read it.
A message is written with the min-reader-ver in it, and a reader checks
`reader.ver` against `msg.min-reader-ver` and `msg.ver` and
`reader.min-message-ver` to assert compatibility.

feat(meta/proto-conv): add reader-min-msg-ver and msg-min-reader-ver

---

src/query/expression/src/function.rs
src/query/expression/src/property.rs
src/query/functions/src/scalars/datetime.rs

Same purpose as https://github.com/datafuselabs/databend/pull/9533, with domain calculation resolved.

refactor(expr): use error_to_null() to eval try_cast

---

src/meta/proto-conv/src/config_from_to_protobuf_impl.rs
src/meta/proto-conv/src/data_from_to_protobuf_impl.rs
src/meta/proto-conv/src/database_from_to_protobuf_impl.rs
src/meta/proto-conv/src/share_from_to_protobuf_impl.rs
src/meta/proto-conv/src/table_from_to_protobuf_impl.rs
src/meta/proto-conv/src/user_from_to_protobuf_impl.rs
src/meta/proto-conv/tests/it/proto_conv.rs
src/meta/proto-conv/tests/it/user_proto_conv.rs
src/meta/protos/proto/config.proto
src/meta/protos/proto/database.proto
src/meta/protos/proto/datatype.proto
src/meta/protos/proto/metadata.proto
src/meta/protos/proto/share.proto
src/meta/protos/proto/table.proto
src/meta/protos/proto/user.proto

chore(meta/proto): rename message.min_compatible to message.min_reader_ver to reflect its actual purpose

---

src/common/hashtable/src/unsized_hashtable.rs

fixes(query): fix memory leak for unsized hash table
Closes #issue

fix(query): fix memory leak for unsized hash table

---

src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_csv.rs
src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_tsv.rs
src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_xml.rs
src/query/pipeline/sources/src/processors/sources/input_formats/input_format_text.rs

used to call it at 4 places with subtle differences. 
Closes #issue

refactor(format): call csv_core::Reader at one place.

---

src/query/ast/src/parser/expr.rs
tests/sqllogictests/suites/query/02_function/02_0002_function_cast

```rust
let position = map(
rule! {
POSITION
~ ^"("
~ ^#subexpr(BETWEEN_PREC)
~ ^IN
~ ^#subexpr(0)
~ ^")"
},
|(_, _, substr_expr, _, str_expr, _)| ExprElement::Position {
substr_expr: Box::new(substr_expr),
str_expr: Box::new(str_expr),
},
);
```
will be expand to this:
```rust
let position = map(
nom::sequence::tuple((
crate::match_token(POSITION),
nom::combinator::cut(crate::match_text("(")),
nom::combinator::cut(subexpr(BETWEEN_PREC)),
nom::combinator::cut(crate::match_token(IN)),
nom::combinator::cut(subexpr(0)),
nom::combinator::cut(crate::match_text(")")),
)),
|(_, _, substr_expr, _, str_expr, _)| ExprElement::Position {
substr_expr: Box::new(substr_expr),
str_expr: Box::new(str_expr),
},
); …
```

fix(query): cast with keyword err

---

src/query/expression/src/utils/arrow.rs
src/query/service/src/pipelines/processors/transforms/hash_join/common.rs
src/query/service/src/pipelines/processors/transforms/hash_join/join_hash_table.rs
src/query/storages/common/index/src/range_filter.rs
src/query/storages/common/table-meta/src/meta/v2/segment.rs

chore(fuse): optimize the expr in range filter

---

src/query/service/src/servers/http/clickhouse_handler.rs

use context's runtime in clickhouse handler while executing interpreter
Closes #9558

fix: use context's runtime in clickhouse handler  while executing interpreter

---

src/query/sql/src/planner/optimizer/cascades/explore_rules.rs
src/query/sql/src/planner/optimizer/cascades/scheduler.rs
src/query/sql/src/planner/optimizer/heuristic/heuristic.rs
src/query/sql/src/planner/optimizer/m_expr.rs
src/query/sql/src/planner/optimizer/memo.rs
src/query/sql/src/planner/optimizer/rule/factory.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_limit_union.rs
src/query/sql/src/planner/optimizer/rule/rule.rs
src/query/sql/src/planner/optimizer/rule/transform/mod.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_commute_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_exchange_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_left_associate_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_left_exchange_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_right_exchange_join.rs
src/query/sql/src/planner/optimizer/s_expr.rs
tests/sqllogictests/suites/mode/standalone/explain/explain.test
tests/sqllogictests/suites/mode/standalone/explain/join.test
tests/sqllogictests/suites/mode/standalone/explain/join_reorder/chain.test
tests/sqllogictests/suites/mode/standalone/explain/join_reorder/star_multiple_tables.test

Introduce exchange rules to extend search space.
Also, introduce `AppliedRules` for `Memo` to reduce duplicated rule applications.
After this PR, the optimizer will generate bushy join trees.

chore(planner): Improve join reorder algorithm

---

src/query/service/src/servers/http/clickhouse_handler.rs

to avoid sqllogic test hanging in cluster mode, in the clickhouse handler, wraps resultset stream pulling action in  the "query-ctx" thread.
how to re-produce: pls see the summary of https://github.com/datafuselabs/databend/issues/9576
while execution queries:
1.  the clickhouse handler uses "global" the tokio runtime (the "tokio-runtime-workers" threads) to pull the  resultset datastream (SendableDataBlockStream). 
the pulling of `SendableDataBlockStream` , calls `PipelinePullingExecutor::pull_data` (for PipelinePullingExecutor)
https://github.com/datafuselabs/databend/blob/3b45a672222b5bc928810dd0b3a64803d18a590d/src/query/service/src/pipelines/executor/pipeline_pulling_executor.rs#L176-L185
note …

fix: sqllogic test hangs (cluster mod + clickhouse handler) 

---

src/query/storages/common/index/src/filters/xor8.rs

Bloom filter can support more base data type:
Data
Timestamp
Closes #issue

chore(query): add bloom filter supported data type

---

src/query/storages/parquet/src/pruning.rs

Arrow2 will not throw an error but panic when reading page indexes if there is no page index in the parquet file.
We should check if there is page index first.

fix: ensure there is page index while using page index to filter pages.

---

docs/doc/10-deploy/06-metasrv/20-metasrv-add-remove-node.md
docs/doc/10-deploy/07-query/10-query-config.md

This PR fixed vague descriptions spotted during the translation work.
Closes #issue

docs: fix vague description

---

src/query/service/src/interpreters/interpreter_call.rs
src/query/service/src/interpreters/interpreter_factory.rs
src/query/service/src/servers/http/clickhouse_handler.rs
src/query/service/src/servers/http/v1/query/execute_state.rs
src/query/sql/src/planner/plans/plan.rs

Plan's schema is incomplete, we should use InterpreterFactory to get the real schema now.
```
curl -u root: --request POST '127.0.0.1:8000/v1/query/' --header 'Content-Type: application/json' --data-raw '{"sql": "call system$search_tables('tables')"}' | jq .
{
"id": "6732ff08-5d4f-463a-b666-31a4dd235fd2",
"session_id": "530b8b6e-49ed-4522-b9ec-6173409fc7c9",
"session": {},
"schema": [
{
"name": "catalog",
"type": "String"
},
{
"name": "database",
"type": "String"
},
{
"name": "name",
"type": "String"
},
{
"name": "engine",
"type": "String"
},
{
"name": "cluster_by",
"type": "String"
},
{
"name": "created_on",
"type": "String"
},
{
"name": "dropped_on",
"type": "String"
},
{ …
```

fix(query): fix management empty schema

---

src/query/ast/src/parser/stage.rs
src/query/ast/src/parser/statement.rs
src/query/ast/src/parser/token.rs
src/query/ast/src/util.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/statement-error.txt
src/query/ast/tests/it/testdata/statement.txt
tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables
tests/sqllogictests/suites/base/05_ddl/05_0016_ddl_stage
website/blog/2022-08-08-benchmark-tpc-h.md

the problem is described in https://github.com/datafuselabs/databend/pull/9626
add `format_options`, `connection_options`, `credentails_options` which are more strict.
1. use keyword for option keys
2. use keyword for option values of `type` and `compression`, but allow `string literal ` for compatibility, forbidden `ident` 
3. check string/int/bool for literal values
Closes #issue

refactor(parser): more strict parser for format_options.

---

tests/sqllogictests/src/client/http_client.rs

This flaky test is difficult to reproduce locally, so add a log to the ci to diagnose when it occurs.
Related https://github.com/datafuselabs/databend/issues/9613

chore(sqllogictest): add log for http session

---

src/query/service/tests/it/storages/fuse/block_writer.rs
src/query/storages/common/index/Cargo.toml
src/query/storages/common/index/benches/build_from_block.rs
src/query/storages/common/index/src/bloom_index.rs
src/query/storages/common/index/src/filters/xor8.rs
src/query/storages/common/index/src/index.rs
src/query/storages/common/index/src/lib.rs
src/query/storages/common/index/src/range_index.rs
src/query/storages/common/index/tests/it/filters/bloom_filter.rs
src/query/storages/common/pruner/src/range_pruner.rs
src/query/storages/fuse/src/operations/fuse_sink.rs
src/query/storages/fuse/src/operations/mutation/compact/compact_transform.rs
src/query/storages/fuse/src/pruning/pruner.rs
src/query/storages/fuse/src/statistics/column_statistic.rs
src/query/storages/hive/hive/src/hive_block_filter.rs
src/query/storages/hive/hive/src/hive_partition_pruner.rs
src/query/storages/hive/hive/src/hive_table.rs

* rename file to `*_index.rs` and structure to `*Index`
* `supported_type` is a func of `pub trait Index`
* remove `MinMaxIndex`, using `RangeIndex` instead
Closes #issue

refactor(storage/index): make the storage/index more index

---

docs/doc/14-sql-commands/10-dml/dml-copy-into-location.md

updated CREDENTIALS to CONNECTION for [COPYINTO<location>](https://databend.rs/doc/sql-commands/dml/dml-copy-into-location).
Closes #issue

docs: update copyinto connection

---

src/query/sql/src/planner/binder/select.rs
src/query/sql/src/planner/planner.rs
tests/sqllogictests/suites/base/20+_others/20_0011_max_result_rows

https://github.com/datafuselabs/databend/pull/9406  add `max_result_rows`, but we may get wrong sql result if there are subqueries.  let's only limit the output results rows.

fix(query):  fix max_result_rows only limit output results nums

---

docker/Dockerfile
docker/README.md
docker/bootstrap.sh

ci: force using template when QUERY_CONFIG_FILE is not set for docker image

---

src/query/storages/common/cache/src/read/cached_reader.rs
src/query/storages/common/cache/src/read/loader.rs
src/query/storages/fuse/src/io/read/bloom_index/column_reader.rs
src/query/storages/fuse/src/io/read/column_data_loader.rs

This is a bug introduced in #9672 
BTW, the metric name should be lower case, PTAL @dantengsky 
```
+--------------------------------------------------------------+-------+--------+---------+                                                                                                                                  [245/98410]
| metric                                                       | kind  | labels | value   |
+--------------------------------------------------------------+-------+--------+---------+
| cache_BLOOM_INDEX_DATA_CACHE_access_count                    | gauge | {}     | 6048.0  |
| cache_BLOOM_INDEX_DATA_CACHE_miss_count                      | gauge | {} …
```

fix(storage): bloom filter is using wrong cache key

---

src/query/sql/src/planner/binder/aggregate.rs
src/query/sql/src/planner/binder/scalar_common.rs
src/query/sql/src/planner/binder/select.rs
tests/sqllogictests/suites/mode/standalone/explain/aggregate.test

eliminate extra group-by scalars 
continue #9678 
Closes #9611

feat(sql): eliminate extra group by scalars

---

tests/sqllogictests/suites/base/09_fuse_engine/09_0009_01_bloom_in_pruning
tests/sqllogictests/suites/base/09_fuse_engine/09_0009_02_limit_pruning
tests/sqllogictests/suites/base/09_fuse_engine/09_0009_03_orderby_limit_topn_pruning

* add fuse pruning sql logic tests for `limit` and `TopN(orderby+limit)` pruning
Parts of #9702

chore(fuse): add fuse pruning sql logic tests

---

src/query/storages/common/table-meta/src/meta/v2/segment.rs
src/query/storages/fuse/src/metrics/fuse_metrics.rs
src/query/storages/fuse/src/pruning/block_pruner.rs
src/query/storages/fuse/src/pruning/segment_pruner.rs

Add metrics:
```
gauge!(key!("segment_before_range_pruning_nums"), c);
gauge!(key!("segment_after_range_pruning_nums"), c);
gauge!(key!("block_before_range_pruning_nums"), c);
gauge!(key!("block_after_range_pruning_nums"), c);
gauge!(key!("block_before_bloom_pruning_nums"), c);
gauge!(key!("block_after_bloom_pruning_nums"), c);
gauge!(key!("bytes_before_segment_range_pruning"), c);
gauge!(key!("bytes_after_segment_range_pruning"), c);
gauge!(key!("bytes_before_block_range_pruning"), c);
gauge!(key!("bytes_after_block_range_pruning"), c);
gauge!(key!("bytes_before_block_bloom_pruning"), c);
gauge!(key!("bytes_after_block_bloom_pruning"), c);
```
Closes #9702

chore(fuse/metrics): add fuse pruning metrics

---

src/query/catalog/src/plan/partition_statistics.rs
src/query/catalog/src/plan/pruning_statistics.rs
src/query/sql/src/executor/format.rs
src/query/storages/fuse/src/operations/delete.rs
src/query/storages/fuse/src/operations/read_partitions.rs
src/query/storages/fuse/src/operations/recluster.rs
src/query/storages/fuse/src/pruning/block_pruner.rs
src/query/storages/fuse/src/pruning/fuse_pruner.rs
src/query/storages/fuse/src/pruning/mod.rs
src/query/storages/fuse/src/pruning/pruning_statistics.rs
src/query/storages/fuse/src/pruning/segment_pruner.rs
tests/sqllogictests/README.md
tests/sqllogictests/suites/mode/standalone/explain/explain.test
tests/sqllogictests/suites/mode/standalone/explain/fold_count.test
tests/sqllogictests/suites/mode/standalone/explain/join.test
tests/sqllogictests/suites/mode/standalone/explain/join_reorder/chain.test
tests/sqllogictests/suites/mode/standalone/explain/join_reorder/cycles.test
tests/sqllogictests/suites/mode/standalone/explain/join_reorder/star.test
tests/sqllogictests/suites/mode/standalone/explain/nullable_prune.test
tests/sqllogictests/suites/mode/standalone/explain/prune_column.test
tests/sqllogictests/suites/mode/standalone/explain/select_limit_offset.test
tests/sqllogictests/suites/mode/standalone/explain/union.test

Only works in standalone:
```
mysql> explain SELECT URLHash, EventDate, COUNT(*) AS PageViews FROM hits WHERE CounterID = 62 AND EventDate >= '2013-07-01' AND EventDate <= '2013-07-31' AND IsRefresh = 0 AND TraficSourceID IN (-1, 6) AND RefererHash = 3594120000172545465 GROUP BY URLHash, EventDate ORDER BY PageViews DESC LIMIT 10 OFFSET 100;
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

feat(pruning): add pruning stats to EXPLAIN

---

src/query/storages/common/table-meta/src/table/table_compression.rs
tests/sqllogictests/suites/base/01_system/01_0005_system_tables_data_size
tests/sqllogictests/suites/mode/standalone/explain/explain.test
tests/sqllogictests/suites/mode/standalone/explain/fold_count.test
tests/sqllogictests/suites/mode/standalone/explain/join.test
tests/sqllogictests/suites/mode/standalone/explain/join_reorder/chain.test
tests/sqllogictests/suites/mode/standalone/explain/join_reorder/cycles.test
tests/sqllogictests/suites/mode/standalone/explain/join_reorder/star.test
tests/sqllogictests/suites/mode/standalone/explain/nullable_prune.test
tests/sqllogictests/suites/mode/standalone/explain/prune_column.test
tests/sqllogictests/suites/mode/standalone/explain/select_limit_offset.test
tests/sqllogictests/suites/mode/standalone/explain/union.test

As benched in #9728, zstd has a better compression ratio, it's suite for cloud object storage.
From zstd readme:
| Compressor name         | Ratio | Compression| Decompress.|
| ---------------         | ------| -----------| ---------- |
| **zstd 1.5.1 -1**       | 2.887 |   530 MB/s |  1700 MB/s |
| [zlib] 1.2.11 -1        | 2.743 |    95 MB/s |   400 MB/s |
| brotli 1.0.9 -0         | 2.702 |   395 MB/s |   450 MB/s |
| **zstd 1.5.1 --fast=1** | 2.437 |   600 MB/s |  2150 MB/s |
| **zstd 1.5.1 --fast=3** | 2.239 |   670 MB/s |  2250 MB/s |
| quicklz 1.5.0 -1        | 2.238 |   540 MB/s |   760 MB/s |
| **zstd 1.5.1 --fast=4** | 2.148 |   710 MB/s |  2300 MB/s |
| lzo1x 2.10 -1           | 2.106 | …

feat(compression): change the table default compression from lz4 to zstd

---

src/query/storages/stage/src/stage_table_sink.rs
tests/sqllogictests/suites/base/05_ddl/05_0027_ddl_copy

* max_file_size max size is half of the max_memory_usage
* change default size from 64MB to 256MB
Closes #9736

fix(max_file_size): fix up max_file_size may oom

---

src/query/storages/fuse/src/io/read/meta/meta_readers.rs
src/query/storages/hive/hive/src/hive_meta_data_reader.rs

* fix fuse cache name to lowercase
Closes #issue

chore(cache): fix cache name to lowercase

---

scripts/ci/ci-run-sqllogic-tests.sh
src/query/ast/src/ast/statements/copy.rs
src/query/ast/src/parser/statement.rs
src/query/ast/tests/it/testdata/statement.txt
src/query/sql/src/planner/binder/copy.rs

Change `ON_ERROR` default value to `abort`.
Closes #issue

chore(copy): make on_error default to abort

---

src/query/storages/parquet/src/parquet_source.rs
src/query/storages/parquet/src/pruning.rs
src/query/storages/parquet/src/table_function/read.rs
src/query/storages/parquet/src/table_function/table.rs

- replace `std::File` with `opendal` for all IO operations. (TODO(Another PR): use `opendal` to do "glob").
- optimize prewhere logic. (do `resort` before filter).
- fix scan progress collection.
- TODO(Another PR): support remote location and async operations.
Closes #issue

feat(storages): `read_parquet` uses OpenDAL for all IO operations.

---

src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_tsv.rs
tests/data/field_white_space.tsv
tests/suites/1_stateful/00_copy/00_0001_copy_tsv.result
tests/suites/1_stateful/00_copy/00_0001_copy_tsv.sh

fix load tsv when the field contains whitespace.
Closes #9737

fix(tsv): fix tsv field with whitespace

---

src/binaries/metactl/main.rs
src/binaries/metactl/snapshot.rs
src/meta/client/src/grpc_client.rs
src/meta/protos/proto/datatype.proto

Otherwise nothing will be done and error returns, e.g., `Error: node id (0) has to be one of cluster member([1])`

fix(metactl): when import data to meta-service dir, the specified "id" has to be one of the "initial_cluster"

---

tests/sqllogictests/src/client/clickhouse_client.rs
tests/sqllogictests/src/client/http_client.rs
tests/sqllogictests/src/client/mysql_client.rs
tests/sqllogictests/src/main.rs

Add time cost to each query, sample:
```
MySQL client starts to run with: SqlLogicTestArgs { dir: Some("01_system"), file: None, skipped_dir: None, handlers: None, suites: "tests/sqllogictests/suites", complete: false, no_fail_fast: false, parallel: 1, enable_sandbox: true, debug: true }
Running MySQL test for file: tests/sqllogictests/suites/base/01_system/01_0001_system_tables ...
Running sql with mysql client: [SELECT * from system.tables where name = 'tables' and created_on > '2022-07-01 12:16:58.630 +0000'] (19.625208ms)
Completed MySQL test for file: tests/sqllogictests/suites/base/01_system/01_0001_system_tables ✅ (95.025083ms)
```
Closes #9718

chore(sqllogictest): add time cost

---

Cargo.lock
src/query/config/Cargo.toml
src/query/config/src/inner.rs
src/query/config/src/lib.rs
src/query/config/src/outer_v0.rs
src/query/config/tests/main.rs
src/query/service/tests/it/storages/testdata/configs_table_basic.txt

fix: Fix table_meta_cache can't be disabled

fix: Fix table_meta_cache can't be disabled

---

.cargo/config.toml

Enable `background_thread:true,metadata_thp:auto` to purge unused memory shifted to the dedicated background threads, making the memory return to OS faster.
Closes #9775

chore(jemalloc): background_thread:true,metadata_thp:auto

---

src/query/storages/fuse/src/io/read/block/block_reader_parquet.rs
src/query/storages/fuse/src/operations/mutation/mutation_source.rs

remove unnecessary column data copy in
- BlockReader::read_parquet_by_meta
- MutationSource
Closes #issue

refactor: remove unnecessary column data copy

---

src/meta/service/src/meta_service/meta_leader.rs
src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs

refactor(meta): do not remove the last node from a cluster

---

src/binaries/meta/kvapi.rs
src/meta/api/src/kv_api.rs
src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/api/src/share_api_impl.rs
src/meta/api/src/share_api_test_suite.rs
src/meta/api/src/testing.rs
src/meta/api/src/util.rs
src/meta/client/src/kv_api_impl.rs
src/meta/embedded/src/kv_api_impl.rs
src/meta/raft-store/src/state_machine/sm_kv_api_impl.rs
src/meta/service/src/meta_service/meta_node_kv_api_impl.rs
src/meta/store/src/lib.rs
src/query/management/src/quota/quota_mgr.rs
src/query/management/src/role/role_mgr.rs
src/query/management/src/setting/setting_mgr.rs
src/query/management/src/stage/stage_mgr.rs
src/query/management/src/udf/udf_mgr.rs
src/query/management/src/user/user_mgr.rs
src/query/management/tests/it/user.rs
src/query/users/src/user_api.rs

Implementations have their own error defined to fit their needs.
E.g., a remove KVApi impl returns network error or remote storage error.
A local KVApi impl just returns storage error.

refactor(meta/kvapi): KVApi should have an associated error type

---

src/common/base/src/mem_allocator/jemalloc.rs

Try to fix main branch macos test.
Closes #issue

fix(jemalloc): fix not linux and macos jemalloc fallback to std

---

src/meta/api/src/id_generator.rs
src/meta/api/src/kv_api_key.rs
src/meta/api/src/kv_api_test_suite.rs
src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_keys.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/api/src/share_api_keys.rs
src/meta/api/src/testing.rs
src/meta/api/src/util.rs
src/meta/raft-store/src/state_machine/sm.rs
src/meta/service/src/watcher/watcher_manager.rs
src/meta/types/src/lib.rs
src/meta/types/src/seq_value.rs

chore(meta): rename KVApiKey::to_key/from_key to to_string/from_str

---

src/query/functions/src/scalars/array.rs
src/query/functions/tests/it/scalars/array.rs
src/query/functions/tests/it/scalars/testdata/array.txt
src/query/functions/tests/it/scalars/testdata/function_list.txt
tests/sqllogictests/suites/base/11_data_type/11_0005_data_type_array

concat(list1, list2) | Concatenates two lists. | concat([2, 3], [4, 5, 6]) | [2, 3, 4, 5, 6]
-- | -- | -- | --
Closes #9803

feat(query): support array concat

---

tests/sqllogictests/src/main.rs

Verified by ad-hoc console tests.
```
./target/debug/databend-sqllogictests --run_file 05_0001_ddl_create_database --no-fail-fast
MySQL client starts to run with: SqlLogicTestArgs { dir: None, file: Some("05_0001_ddl_create_database"), skipped_dir: None, handlers: None, suites: "tests/sqllogictests/suites", complete: false, no_fail_fast: true, parallel: 1, enable_sandbox: false, debug: false }
Running MySQL test for file: tests/sqllogictests/suites/base/05_ddl/05_0001_ddl_create_database ...
Completed MySQL test for file: tests/sqllogictests/suites/base/05_ddl/05_0001_ddl_create_database ❌ (594.230131ms)
```
**Test finished, fail fast disabled, 2 out of 20 records failed to run**
```
0: statement is …
```

chore(test): Add total count to sqllogic test console output

---

src/meta/api/src/id_generator.rs
src/meta/app/src/schema/database.rs
src/meta/app/src/schema/table.rs
src/meta/app/src/share/share.rs
src/meta/kvapi/src/kvapi/key_parser.rs

refactor(kvapi): biuld key with KeyBuilder, instead of with raw "format!"

---

src/query/functions/src/scalars/array.rs
src/query/functions/tests/it/scalars/array.rs
src/query/functions/tests/it/scalars/testdata/array.txt
src/query/functions/tests/it/scalars/testdata/function_list.txt

Support array functions `prepend` and `append`
part of #7931

feat(query): Support array functions prepend and append

---

Cargo.lock
src/common/storage/Cargo.toml
src/common/storage/src/lib.rs
src/common/storage/src/stage.rs
src/query/catalog/Cargo.toml
src/query/catalog/src/catalog/interface.rs
src/query/catalog/src/plan/datasource/datasource_info/parquet.rs
src/query/service/src/catalogs/default/database_catalog.rs
src/query/service/src/table_functions/table_function_factory.rs
src/query/sql/src/planner/binder/table.rs
src/query/storages/parquet/Cargo.toml
src/query/storages/parquet/src/parquet_table/blocking.rs
src/query/storages/parquet/src/parquet_table/non_blocking.rs
src/query/storages/parquet/src/parquet_table/partition.rs
src/query/storages/parquet/src/parquet_table/table.rs

Closes #issue
part of https://github.com/datafuselabs/databend/issues/9847

refactor: ParquetTable list file in read_partition.

---

docs/doc/10-deploy/06-metasrv/30-metasrv-backup-restore.md
src/binaries/meta/main.rs
src/binaries/metactl/snapshot.rs
tests/metactl/test-metactl-restore-new-cluster.sh

refactor(metactl): when restoring a cluster from backup data, it does not require to specify grpc addresses

---

src/query/functions/src/scalars/array.rs
src/query/functions/tests/it/scalars/array.rs
src/query/functions/tests/it/scalars/testdata/array.txt
src/query/functions/tests/it/scalars/testdata/function_list.txt
tests/sqllogictests/suites/query/02_function/02_0061_function_array

rename some array functions add `array_` prefix
```
remove_first -> array_remove_first
remove_last -> array_remove_last
concat -> array_concat
prepend -> array_prepend
append -> array_append
indexof -> array_indexof
```
Closes #issue

refactor(query): rename some array functions add array_ prefix

---

src/meta/client/src/lib.rs
src/meta/client/tests/it/grpc_server.rs
src/meta/service/src/api/grpc/grpc_service.rs
src/meta/service/src/meta_service/meta_leader.rs
src/meta/service/src/meta_service/meta_node_kv_api_impl.rs
src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/src/version.rs
src/meta/service/tests/it/meta_node/meta_node_kv_api_expire.rs
src/meta/service/tests/it/meta_node/meta_node_replication.rs
src/meta/types/proto/meta.proto
src/meta/types/src/log_entry.rs
tests/compat/test-compat.sh
tests/fuse-compat/test-fuse-compat.sh

The `meta-server.min_client_ver` is increased from `0.7.59` to `0.8.80`.

refactor(meta): remove obsolete meta service api read_msg() and write_msg()

---

src/query/expression/src/types/number.rs
src/query/functions/src/scalars/array.rs
src/query/functions/tests/it/scalars/array.rs
src/query/functions/tests/it/scalars/testdata/array.txt
src/query/functions/tests/it/scalars/testdata/function_list.txt
tests/sqllogictests/suites/query/02_function/02_0061_function_array

support array aggregate functions
```
array_sum
array_avg
array_count
array_max
array_min
```
part of #7931

feat(query): support array aggregate functions

---

src/query/catalog/src/plan/datasource/datasource_plan.rs
src/query/catalog/src/table.rs
src/query/catalog/src/table_args.rs
src/query/service/src/catalogs/default/database_catalog.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/table_functions/async_crash_me.rs
src/query/service/src/table_functions/mod.rs
src/query/service/src/table_functions/numbers/numbers_table.rs
src/query/service/src/table_functions/sync_crash_me.rs
src/query/service/src/table_functions/table_function_factory.rs
src/query/service/tests/it/storages/fuse/table_functions/clustering_information_table.rs
src/query/service/tests/it/table_functions/numbers_table.rs
src/query/sql/src/planner/binder/mod.rs
src/query/sql/src/planner/binder/table.rs
src/query/sql/src/planner/binder/table_args.rs
src/query/storages/fuse/src/table_functions/clustering_informations/clustering_information_table.rs
src/query/storages/fuse/src/table_functions/clustering_informations/table_args.rs
src/query/storages/fuse/src/table_functions/fuse_blocks/fuse_block_table.rs
src/query/storages/fuse/src/table_functions/fuse_blocks/table_args.rs
src/query/storages/fuse/src/table_functions/fuse_segments/fuse_segment_table.rs
src/query/storages/fuse/src/table_functions/fuse_segments/table_args.rs
src/query/storages/fuse/src/table_functions/fuse_snapshots/fuse_snapshot_table.rs
src/query/storages/fuse/src/table_functions/fuse_snapshots/table_args.rs
src/query/storages/fuse/src/table_functions/fuse_statistics/fuse_statistic_table.rs
src/query/storages/hive/hive/src/hive_table.rs

1.  refactor as refactor: TableArgs preserve info of positioned and named args
2.  add some common functions to help parse/check
3.  small fixes.
Closes https://github.com/datafuselabs/databend/issues/9914

refactor: TableArgs preserve info of positioned and named args

---

src/query/service/src/api/rpc/flight_client.rs
src/query/service/src/api/rpc/flight_service.rs

refactor(cluster): use bounded channel for exchange
Closes #issue

refactor(cluster): use bounded channel for exchange

---

src/query/pipeline/transforms/src/processors/transforms/transform.rs

chore(processor): add on_start and on_finish for transform
Closes #issue

chore(processor): add on_start and on_finish for transform

---

docs/doc/15-sql-functions/30-datetime-functions/tostartofweek.md

`mode` was not included in sql syntax
Closes #9959

docs(query): Trivial doc fix for to_start_of_week 

---

src/query/functions/src/scalars/array.rs
src/query/functions/tests/it/scalars/array.rs
src/query/functions/tests/it/scalars/testdata/array.txt
src/query/functions/tests/it/scalars/testdata/function_list.txt
tests/sqllogictests/suites/query/02_function/02_0061_function_array

- Support `array_any` function
- Support `slice` function with two arguments
- Add some logical tests for array functions
part of #7931

feat(query): Support `array_any` functions

---

tests/metactl/test-metactl-restore-new-cluster.sh

chore(metactl/test): json output map keys in arbitrary order. Do not rely on the key order

---

src/meta/proto-conv/src/user_from_to_protobuf_impl.rs

* fix panic when unsupported type in `to_pb`
Closes #issue

chore(proto-conv): fix panic unsupported type in to_pb

---

src/query/service/src/interpreters/access/privilege_access.rs
src/query/service/src/interpreters/common/grant.rs
src/query/service/tests/it/sql/planner/format/mod.rs
src/query/sql/src/planner/binder/bind_context.rs
src/query/sql/src/planner/binder/table.rs
src/query/sql/src/planner/expression_parser.rs
src/query/sql/src/planner/metadata.rs
tests/suites/0_stateless/14_clickhouse_http_handler/14_0003_http_auth.sh
tests/suites/0_stateless/20+_others/20_0012_privilege_access.result
tests/suites/0_stateless/20+_others/20_0012_privilege_access.sh

feat(query): add privilege check for select

---

website/blog/2023-02-08-databend-weekly-80.md

docs(weekly): add this week in databend 80

---

src/meta/proto-conv/tests/it/main.rs
src/meta/proto-conv/tests/it/proto_conv.rs
src/meta/proto-conv/tests/it/v027_schema.rs
src/query/expression/src/kernels/group_by_hash.rs
src/query/expression/src/types.rs

1. Add meta tests of version 27
2. Improve single signed numerics keys in group aggregation
Closes #issue

feat(query): improve signed numeric keys

---

src/query/sql/src/executor/format.rs
src/query/sql/src/executor/physical_plan_builder.rs
src/query/sql/src/planner/binder/table.rs
src/query/sql/src/planner/expression_parser.rs
src/query/sql/src/planner/format/display_rel_operator.rs
src/query/sql/src/planner/metadata.rs
src/query/sql/src/planner/optimizer/cascades/tasks/apply_rule.rs
src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs
src/query/sql/src/planner/optimizer/heuristic/rule_list.rs
src/query/sql/src/planner/optimizer/optimizer.rs
src/query/sql/src/planner/optimizer/rule/factory.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
src/query/sql/src/planner/optimizer/rule/rule_set.rs
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/mode/standalone/explain/join.test

This SQL is an example: `SELECT t1.c0boolean, t0.c0varchar FROM t0 NATURAL LEFT JOIN t1 where t1.c0boolean`
Originally a left join, the column logical type of `t1` is converted to nullable at the binder stage. 
But if `outer join -> inner join`. where condition will be pushed down. However, the physical type of t1's column is not nullable. This results in a type mismatch.
(Note also that `t1` may have been of type `c0boolean` when the table was created)
Closes https://github.com/datafuselabs/databend/issues/9925

fix: enable outer join to inner join optimization

---

src/common/base/src/mem_allocator/mmap.rs
src/common/hashtable/src/hashtable.rs
src/common/hashtable/src/lookup_hashtable.rs
src/common/hashtable/src/short_string_hashtable.rs
src/common/hashtable/src/stack_hashtable.rs
src/common/hashtable/src/string_hashtable.rs

This is the part-1:
* change the mmap allocator inner allcator from GlobalAllocator to JEAllocator
* for JEAllocator: linux use jemalloc, not linux will fallback to std allocator
Part-2 will investigate try to change the GlobalAllocator from jemalloc to std.
Closes #issue

feat(mmap_allocator): change the mmap allocator inner allcator from GlobalAllocator to JEAllocator

---

.github/workflows/backport.yml
.github/workflows/build-tool.yml
.github/workflows/dev-linux.yml
.github/workflows/dev-macos.yml
.github/workflows/dev-perf.yml
.github/workflows/production.yml
scripts/setup/run_build_tool.sh

> [Incrementally compiled crates cannot be cached.](https://github.com/mozilla/sccache#rust)
@Xuanwo 
> Disable incremental compilation. CI builds often are closer to from-scratch builds, as changes are typically much bigger than from a local edit-compile cycle. For from-scratch builds, incremental adds an extra dependency-tracking overhead. It also significantly increases the amount of IO and the size of ./target, which make caching less effective.
https://matklad.github.io/2021/09/04/fast-rust-builds.html

ci: disable incremental build in CI

---

scripts/setup/dev_setup.sh

make install_protobuf install latest protobuf version, because databend only works on 3.x.
The package manager will install old version in some machine such as centos.
Closes #issue

chore(ci): make install_protobuf install latest protobuf version

---

Cargo.lock
src/binaries/Cargo.toml
src/binaries/query/main.rs
src/common/base/Cargo.toml
src/common/base/src/mem_allocator/global.rs
src/common/base/src/mem_allocator/jemalloc.rs
src/common/base/src/mem_allocator/std_.rs
src/query/catalog/Cargo.toml

```
Databend Query
Version: v0.9.33-nightly-f831463(rust-1.68.0-nightly-2023-02-12T01:41:54.835554Z)
Logging:
file: enabled=true, level=DEBUG, dir=./.databend/logs_meta_embedded, format=text
stderr: enabled=false(To enable: LOG_STDERR_ON=true or RUST_LOG=info), level=INFO, format=text
Meta: embedded at ./.databend/meta_embedded
Memory:
limit: unlimited
allocator: jemalloc
config: percpu_arena:percpu,oversize_threshold:0,background_thread:true,metadata_thp:auto,dirty_decay_ms:5000,muzzy_decay_ms:5000
Cluster: standalone
```
Closes #issue

feat(allocator): print global allocator when server start

---

src/query/storages/fuse/src/table_functions/infer_schema/infer_schema_table.rs
src/query/storages/fuse/src/table_functions/infer_schema/table_args.rs
tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_00_basic.sh
tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_04_infer_schema.result
tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_04_infer_schema.sh

e.g.
```
select * from infer_schema(location => '@s3', FILE_FORMAT => 'PARQUET', pattern => '.*parquet');
```
same usage as https://github.com/datafuselabs/databend/pull/9983#discussion_r1103620897
Closes #issue

feat: infer_schema support arg 'file_format'.

---

src/meta/api/src/schema_api.rs
src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/types/src/errors/app_error.rs

Add `drop_table_by_id ` api for a race condition issue in `drop all`.  We were dropping table by name, which may be error prone when there's table with same name created before we actually dropped the data. This change is the part 1/2 to introduce the api, then I'll update `drop all` in a separate change.
The api is simply get tenant, database, table count and MISC info from table_id, so that we can get ready to emit the transaction. The transaction is exactly same as `drop_table`.
ref #5626

feat(storagte): Add drop_table_by_id api

---

src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/derive_filter.rs
src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/mod.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_eliminate_filter.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
tests/sqllogictests/suites/mode/cluster/04_0002_explain_v2.test
tests/sqllogictests/suites/mode/standalone/explain/explain.test
tests/sqllogictests/suites/mode/standalone/explain/join.test
tests/sqllogictests/suites/mode/standalone/explain/limit.test
tests/sqllogictests/suites/mode/standalone/explain/subquery.test

```sql 
mysql> explain select nodm.locno,
->        sum(nodd.qty + 10)                    as d_boxes,
->        sum(nodd.qty * nodd.packing_qty + 100 ) as d_qty,
->        count(distinct nodd.article_no)  as skues,
->        count(distinct nodm.deliver_no)  as sheets
-> from ods_nwms.nwms_om_deliver_m nodm
->          inner join ods_nwms.nwms_om_deliver_d nodd on nodm.locno = nodd.locno and nodm.deliver_no = nodd.deliver_no
->   where nodm.locno = 'C52'
-> group by
->     nodm.locno
-> order by d_qty
->    ;
```
`nodm.locno = nodd.locno  + nodm.locno = 'C52' ⇒ nodd.locno = 'C52'`
For more cases, please see `join.test`.
Closes #9988

feat: derive new filter and push down

---

docs/doc/90-contributing/01-rfcs/20230213-query-result-cache.md

RFC of query result cache.
Closes #10011

rfc: query result cache.

---

src/query/expression/src/schema.rs
src/query/functions/src/aggregates/aggregate_count.rs
src/query/service/src/pipelines/processors/transforms/aggregator/aggregator_final_parallel.rs
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/base/03_dml/03_0026_insert_into_tuple

1. remove extra hashtable iter
2. fix tuple name index
Closes #issue

chore(query): remove extra hashtable iter

---

.github/workflows/benchmark.yml
.github/workflows/release.yml
.github/workflows/trusted-benchmark.yml

Releases are created by `github-actions` using `GITHUB_TOKEN`, which would trigger no other GitHub event, thus benchmark not running on release before.
Closes #issue

chore(ci): trigger benchmark on release manually

---

src/meta/app/src/principal/user_privilege.rs
src/query/service/src/interpreters/interpreter_role_create.rs
src/query/users/src/role_mgr.rs
tests/sqllogictests/suites/base/05_ddl/05_0006_ddl_grant_privilege
tests/sqllogictests/suites/base/05_ddl/05_0018_ddl_revoke
tests/sqllogictests/suites/base/05_ddl/05_0022_ddl_revoke
tests/sqllogictests/suites/base/05_ddl/05_0024_ddl_set_role
tests/sqllogictests/suites/base/06_show/06_0007_show_roles

This PR adds a SELECT privilege on system.one to the PUBLIC role, so the normal users can execute `SELECT 1` without hitting permission denied error.
Closes #10036

fix(privilege): add privileges on system.one to PUBLIC by default

---

src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_limit_join.rs
tests/sqllogictests/suites/mode/standalone/explain/select_limit_offset.test

1. Limit shouldn't push down full outer join
2. Support push down limit right join
3. fix limit push down left join
Closes https://github.com/datafuselabs/databend/issues/10012

fix: fix limit pushdown outer join

---

src/query/expression/src/schema.rs
src/query/service/src/interpreters/interpreter_table_add_column.rs
src/query/service/src/interpreters/interpreter_table_drop_column.rs
src/query/service/tests/it/storages/fuse/operations/alter_table.rs
src/query/service/tests/it/storages/fuse/operations/mod.rs
src/query/service/tests/it/storages/fuse/statistics.rs
src/query/storages/fuse/src/operations/commit.rs
src/query/storages/fuse/src/operations/mutation/compact/compact_transform.rs
src/query/storages/fuse/src/statistics/accumulator.rs
src/query/storages/fuse/src/statistics/reducers.rs

1. fix: ignore dropped column statistics by column id when reducing block statistics
2. add test case.
Closes https://github.com/datafuselabs/databend/issues/10020

fix: ignore dropped column statistics by column id when reducing block statistics

---

src/query/service/tests/it/storages/fuse/operations/alter_table.rs
src/query/service/tests/it/storages/fuse/operations/gc.rs
src/query/service/tests/it/storages/fuse/operations/mutation/segments_compact_mutator.rs
src/query/service/tests/it/storages/fuse/statistics.rs
src/query/service/tests/it/storages/statistics/column_statistics.rs
src/query/storages/fuse/src/operations/mutation/serialize_data_transform.rs
src/query/storages/fuse/src/statistics/block_statistics.rs
src/query/storages/fuse/src/statistics/column_statistic.rs

Use `to_leaf_column_ids` instead of `to_column_ids` when generate column statistics
Closes #10067

fix(storage): wrong column statistics when contain tuple type

---

.github/workflows/trusted-benchmark.yml

Report for nightly release will be avaiable at https://repo.databend.rs/benchmark/clickbench/release/index.html on next release.
Closes #issue

chore(ci): generate report for nightly on release

---

src/query/config/src/config.rs
src/query/service/tests/it/configs.rs

`table_cache_bloom_index_data_bytes` has been obsoleted in 
- PR #9712
checking for this obsoleted config added:
~~~
./target/debug/databend-query  --meta-embedded-dir .databend/meta  --table-cache-bloom-index-data-bytes 1
Databend Query start failure, cause: Code: 2002, displayText =
--------------------------------------------------------------
*** table-cache-bloom-index-data-bytes *** is obsoleted :
--------------------------------------------------------------
alternative command-line options : N/A
alternative environment variable : N/A
alternative toml config : N/A
--------------------------------------------------------------
~~~
Closes #issue

fix: config checking for obsoleted config options `table_cache_bloom_index_data_bytes`

---

src/query/service/src/api/rpc/exchange/statistics_receiver.rs

fix(cluster): fix wrong error message 'abort query'
#10070 https://github.com/datafuselabs/databend/actions/runs/4191538507/jobs/7266220445
Closes #issue

fix(cluster): fix wrong error message 'abort query'

---

.github/actions/publish_repository/action.yml
.github/workflows/release.yml
scripts/deb/conf/distributions

```shell
sudo curl -L -o /etc/apt/sources.list.d/datafuselabs.sources https://repo.databend.rs/deb/datafuselabs.sources
sudo apt update
sudo apt install databend
```
Closes #issue

ci: release deb repository

---

src/query/expression/src/types/decimal.rs
src/query/functions/src/aggregates/aggregate_min_max_any.rs
tests/sqllogictests/suites/base/11_data_type/11_0006_data_type_decimal

type decimal support agg func min/max
Closes #part of #10005

feat(query): type decimal support agg func min/max

---

src/query/config/src/config.rs
src/query/service/tests/it/configs.rs

implementation of  `Default` for config::CacheConfig should use values from `inner::CacheConfig`
after fix:
`CACHE_ENABLE_TABLE_META_CACHE=true ./target/debug/databend-query  --meta-embedded-dir .databend/meta`
default values of cache configs are as expected
~~~
mysql> select * from system.configs where "group" = 'cache';
+-------+----------------------------------------+--------------------+-------------+
| group | name                                   | value              | description |
+-------+----------------------------------------+--------------------+-------------+
| cache | enable_table_meta_cache                | true               |             |
| cache | table_meta_snapshot_count …

fix: implementation of  `Default` for config::CacheConfig should use values from `inner::CacheConfig`

---

docs/doc/14-sql-commands/00-ddl/50-udf/ddl-alter-function.md

changes docs example to make the function body reflect the name and match other doc examples

docs: changes alter functions example to make the function body reflect the name and match other doc examples

---

src/query/expression/src/function.rs
src/query/expression/src/type_check.rs
src/query/expression/src/types/number.rs
src/query/expression/src/utils/mod.rs
src/query/functions/src/scalars/datetime.rs
src/query/functions/src/scalars/hash.rs
src/query/functions/src/scalars/mod.rs
src/query/functions/src/scalars/other.rs
src/query/functions/tests/it/scalars/array.rs
src/query/functions/tests/it/scalars/cast.rs
src/query/functions/tests/it/scalars/testdata/array.txt
src/query/functions/tests/it/scalars/testdata/cast.txt
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/functions/tests/it/scalars/testdata/other.txt
src/query/sql/src/planner/binder/ddl/table.rs
src/query/sql/src/planner/binder/join.rs
src/query/sql/src/planner/binder/select.rs
src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs
src/query/sql/src/planner/optimizer/heuristic/subquery_rewriter.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/base/03_dml/03_0027_insert_default
tests/sqllogictests/suites/crdb/join
tests/sqllogictests/suites/mode/standalone/explain/subquery.test
tests/sqllogictests/suites/query/02_function/02_0010_function_if
tests/sqllogictests/suites/query/02_function/02_0061_function_array

fix(expr): no longer return Variant as common super type

---

src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/io/read/block/block_reader.rs
src/query/storages/fuse/src/operations/read_data.rs

refactor: save default values in FuseTable instead of BlockReader
Closes #issue

refactor: save default values in FuseTable instead of BlockReader

---

docs/doc/13-sql-reference/70-system-tables/system-configs.md
scripts/ci/deploy/config/databend-query-embedded-meta-hive.toml
scripts/ci/deploy/config/databend-query-embedded-meta.toml
scripts/ci/deploy/config/databend-query-node-1.toml
scripts/ci/deploy/config/databend-query-node-2.toml
scripts/ci/deploy/config/databend-query-node-3.toml
scripts/ci/deploy/config/databend-query-node-shared.toml
src/query/config/src/config.rs
src/query/config/src/lib.rs
src/query/config/src/obsolete.rs
src/query/service/tests/it/configs.rs
src/query/service/tests/it/storages/testdata/configs_table_basic.txt
src/query/storages/system/src/configs_table.rs

* If we have some obsoleted configs in `Meta/Cache` or others, now we can add them to `check_obsoleted`
* removed unused `database_engine_github_enabled`
Closes #issue

chore(config): make obsolete check from QueryConfig to Config

---

src/query/expression/src/block.rs

chore(query): check meta set twice for data block
Closes #issue

chore(query): check meta set twice for data block

---

src/query/formats/src/field_decoder/json_ast.rs
tests/sqllogictests/suites/base/03_dml/03_0016_insert_into_values

Fix json parse timestamp when input is an integer
Closes #10103

fix: fix json parse timestamp when input is an integer

---

src/meta/service/src/meta_service/meta_leader.rs
src/meta/service/src/meta_service/meta_service_impl.rs
src/meta/types/proto/meta.proto

refactor: remove unused RaftService API: write()

---

src/query/config/src/config.rs
src/query/config/src/inner.rs
src/query/service/tests/it/storages/testdata/configs_table_basic.txt

add new internal config option `internal_merge_on_read_mutation`,  by default `false`, disable the merge_on_read behaviors (read & mutation)
Closes #issue

feat: add internal_merge_on_read_mutation config option

---

Cargo.lock
src/query/expression/Cargo.toml
src/query/expression/src/kernels/group_by_hash.rs
src/query/service/src/pipelines/processors/transforms/aggregator/aggregator_final_parallel.rs
src/query/service/src/pipelines/processors/transforms/aggregator/aggregator_partial.rs
src/query/service/src/pipelines/processors/transforms/aggregator/aggregator_partitioned.rs
src/query/service/src/pipelines/processors/transforms/group_by/aggregator_polymorphic_keys.rs
src/query/service/src/pipelines/processors/transforms/group_by/mod.rs
src/query/service/src/pipelines/processors/transforms/transform_convert_grouping.rs

refactor(query): use HashMethodBounds to simplify generics bounds
Closes #issue

refactor(query): use HashMethodBounds to simplify generics bounds

---

src/query/pipeline/core/src/pipeline.rs
src/query/service/src/pipelines/executor/pipeline_executor.rs
src/query/service/src/pipelines/executor/pipeline_pulling_executor.rs

refactor(executor): destroy pull sink after pipeline finished
Closes #issue

refactor(executor): destroy pull sink after pipeline finished

---

tests/compat/test-compat.sh

refactor: load and run old test suites when test query-meta compatibility

---

src/query/service/src/api/rpc/flight_client.rs

fix(cluster): fix possible distributed deadlock when two nodes close input at same time.
Closes #issue

fix(cluster): possible distributed deadlock when two nodes close input at same time

---

Cargo.lock
Cargo.toml
src/query/storages/fuse/src/io/files.rs

Adopt OpenDAL's batch delete support for delete performance.
Closes https://github.com/datafuselabs/databend/issues/10148

feat: Adopt OpenDAL's batch delete support

---

src/query/catalog/src/table_context.rs
src/query/service/src/interpreters/interpreter_select_v2.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/sql/src/executor/table_read_plan.rs
src/query/storages/result_cache/src/common.rs
src/query/storages/result_cache/src/read/reader.rs
src/query/storages/result_cache/src/write/sink.rs
tests/sqllogictests/suites/base/20+_others/20_0013_query_result_cache

Store the SHA-256 values of partitions of each `TableScan` of the query in the query context.
Use these SHA-256 values to check if the query result cache is valid.
Tracking in #10010 .

feat(query): support multi-table query result cache.

---

src/query/service/src/interpreters/interpreter_copy_v2.rs
src/query/service/src/interpreters/interpreter_factory.rs
src/query/service/src/interpreters/interpreter_select_v2.rs
src/query/service/src/procedures/systems/search_tables.rs
src/query/service/src/sessions/query_ctx.rs
src/query/sql/src/planner/binder/binder.rs
src/query/sql/src/planner/optimizer/optimizer.rs
src/query/sql/src/planner/plans/plan.rs
src/query/storages/result_cache/src/common.rs
src/query/storages/result_cache/src/lib.rs
src/query/storages/result_cache/src/read/reader.rs
src/query/storages/result_cache/src/write/sink.rs
tests/sqllogictests/suites/base/20+_others/20_0013_query_result_cache

Use formatted AST to generate the result cache key. This make SQLs with different cases can use the same cache.
For example:
```sql
select * from t;
SELECT * FROM t;
```
These two SQLs can use the same cache.
Tacking in #10010

chore(query): use formatted AST to generate the result cache key.

---

scripts/setup/rust-tools.txt

ci: Fix typos-cli is not installed correctly

ci: Fix typos-cli is not installed correctly

---

src/query/ast/src/ast/query.rs
src/query/service/src/interpreters/interpreter_view_create.rs

In the past:
```sql
create view v as select * from @stage;
```
the inner SQL will be stored as 
```
select * from (@stage/);
```
This will let selecting from `system.columns` failed because the SQL text cannot be parsed by the planner.
In this PR, the SQL text stored will be changed to:
```
select * from @stage/;
```

chore: fix select from `system.columns` if there is a view from stage.

---

src/query/sql/src/planner/optimizer/rule/factory.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_scan.rs

Closes https://github.com/datafuselabs/databend/issues/10199

fix: don't push down filter that contains derived column

---

src/common/io/src/cursor_ext/cursor_read_number_ext.rs
src/query/formats/src/field_decoder/row_based.rs
tests/sqllogictests/suites/base/issues/issue_10103.test

Fix timestamp parsing for row-based formats.
Closes #10103

fix: fix parse timestamp for row based format

---

README.md
docs/doc/00-overview/index.md
docs/doc/02-cloud/index.md
docs/doc/15-sql-functions/112-table-functions/stage_table_function.md
scripts/distribution/release-readme.txt
website/blog/2022-11-30-databend-weekly-70.md
website/blog/2022-12-07-databend-weekly-71.md
website/blog/2022-12-14-databend-weekly-72.md
website/blog/2022-12-21-databend-weekly-73.md
website/blog/2022-12-28-databend-weekly-74.md
website/blog/2023-01-04-databend-weekly-75.md
website/blog/2023-01-11-databend-weekly-76.md
website/blog/2023-01-18-databend-weekly-77.md
website/blog/2023-01-25-databend-weekly-78.md
website/blog/2023-02-01-databend-weekly-79.md
website/blog/2023-02-08-databend-weekly-80.md
website/blog/2023-02-15-databend-weekly-81.md
website/blog/2023-02-22-databend-weekly-82.md
website/docusaurus.config.js
website/i18n/en-US/docusaurus-theme-classic/footer.json
website/src/pages/index.tsx

docs: twitter from Datafuse_Labs to DatabendLabs

---

src/query/catalog/src/plan/partition.rs
src/query/functions/src/scalars/decimal.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/storages/fuse/src/operations/read/fuse_source.rs
tests/sqllogictests/suites/base/11_data_type/11_0006_data_type_decimal

feat(query): add compare op for decimal types

---

Cargo.lock
Cargo.toml
src/meta/raft-store/src/applied_state.rs
src/meta/types/src/log_entry.rs

openraft released 0.7.4; Nothing really changed since 0.7.4-alpha.3

refactor(meta): upgrade openraft to 0.7.4

---

src/query/storages/common/table-meta/src/meta/v2/segment.rs
src/query/storages/fuse/src/operations/read/fuse_source.rs
src/query/storages/fuse/src/operations/read_partitions.rs

chore(storage): limit the scan threads if there are small parts

---

docs/doc/13-sql-reference/10-data-types/10-data-type-numeric-types.md
docs/doc/13-sql-reference/10-data-types/11-data-type-decimal-types.md
docs/doc/13-sql-reference/10-data-types/index.md

* Add more examples for decimal data type, including min and max
* Lift the decimal order
Closes #issue

docs: lift the decimal type under the number type

---

tests/meta-upgrade-09/test-meta-upgrade-09.sh

chore: fixup meta-upgrade-90 tests, the version expected is now 30

---

src/query/service/src/interpreters/interpreter_select_v2.rs
src/query/service/src/sessions/query_ctx_shared.rs
tests/sqllogictests/suites/base/01_system/01_0011_system_query_cache

system tables usually contain statistical information and should not be cached.
Closes #issue

fix(query): fix query result cache system table

---

src/query/ast/src/parser/expr.rs
src/query/ast/tests/it/testdata/expr.txt

before this pr, we got  `-1 + - 1 = -(1 + (- 1) )= 0`
see https://github.com/segeljakt/pratt/blob/master/examples/lalrpop-pratt/src/main.rs#L58
Closes #issue

fix: UnaryOp +/- should have high Precedence in PrattParser.

---

.github/workflows/trusted-benchmark.yml
benchmark/clickbench/update-results.sh

chore(ci): fix sync benchmark report for tpch

---

src/query/service/src/interpreters/interpreter_select.rs
tests/sqllogictests/suites/query/select.test

meta_key may not always have a value
Closes #issue

fix: result_scan not set query_id when meta_key is none

---

src/query/sql/src/planner/binder/table.rs
tests/sqllogictests/suites/base/20+_others/20_0014_result_scan

refine result_scan error messages, before this patch, if we do:
```sql
SELECT * FROM t1 ORDER BY a;
SET enable_query_result_cache = 1;
SELECT * FROM RESULT_SCAN(last_query_id()) ORDER BY a;
```
will get "column a doesn't exist". 
After this patch, we got "`RESULT_SCAN` could not find related cache key in current session for this query id: xxx"
Closes #issue

chore(query): refine result_scan error messages

---

src/query/expression/src/values.rs
src/query/sql/src/evaluator/block_operator.rs
src/query/sql/src/executor/physical_plan.rs
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/02_function/02_0062_function_unnest

If the original length of each column is different, the shorter ones will be padded with NULLs.
For example:
```
+---------+---------+
| origin1 | origin2 |
+---------+---------+
| [1,2]   | [1,2,3] |
| [3,4,5] | [4,5]   |
+---------+---------+
```
will be unnested to:
```
+---------+---------+
| unnest1 | unnest2 |
+------ --+---------+
| 1       | 1       |  -- From original row 1
| 2       | 2       |  -- From original row 1
| NULL    | 3       |  -- From original row 1
| 3       | 4       |  -- From original row 2
| 4       | 5       |  -- From original row 2
| 5       | NULL    |  -- From original row 2
+---------+---------+
```
Tracking in #10295

feat(query): support multiple unnest columns.

---

Cargo.lock
Cargo.toml
src/common/arrow/Cargo.toml
src/query/expression/src/utils/display.rs
tests/sqllogictests/suites/base/11_data_type/11_0006_data_type_decimal

support decimal256 select insert
Closes #10180

feat(query): support decimal256 select insert

---

src/query/catalog/src/table_context.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sessions/session_ctx.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/service/tests/it/storages/testdata/columns_table.txt
src/query/storages/result_cache/src/common.rs
src/query/storages/result_cache/src/write/sink.rs
src/query/storages/system/src/query_cache_table.rs

Add `query_id` and `active_result_scan` to `system.query_cache`.
`active_result_scan`is true to indicate that the associated query_id can be used by result_scan.
Closes #issue

refactor: add query_id and active_result_scan to system.query_cache

---

src/query/ast/src/parser/expr.rs
src/query/expression/src/property.rs
src/query/expression/src/types/empty_map.rs
src/query/expression/src/types/map.rs
src/query/expression/src/utils/display.rs
src/query/expression/src/values.rs
src/query/functions/src/scalars/map.rs
src/query/functions/tests/it/scalars/map.rs
src/query/functions/tests/it/scalars/parser.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/functions/tests/it/scalars/testdata/map.txt
tests/sqllogictests/suites/base/03_common/03_0037_insert_into_map

- Support Map type `get` function.
- Add `Domain::Map` for the `Map` type.
- Upgrade `Strawboat` to fix read native format nested `Array` failed.
Part of #10062

feat(function): Support Map type get function

---

src/query/expression/src/expression.rs
src/query/expression/src/schema.rs
src/query/expression/src/types.rs
src/query/expression/src/types/array.rs
src/query/service/src/pipelines/pipeline_builder.rs
src/query/sql/src/evaluator/block_operator.rs
src/query/sql/src/executor/physical_plan.rs
src/query/sql/src/executor/physical_plan_builder.rs
src/query/sql/src/executor/physical_plan_display.rs
src/query/sql/src/executor/physical_plan_visitor.rs
src/query/sql/src/planner/plans/scalar.rs
src/query/sql/src/planner/semantic/lowering.rs
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/02_function/02_0062_function_unnest

Examples:
For 1.
```sql
explain select unnest([1,2]) + 1;
+--------------------------------------------------------------+
| explain                                                      |
+--------------------------------------------------------------+
| EvalScalar                                                   |
| ├── expressions: [plus(_unnest, 1)]                          |
| ├── estimated rows: 0.00                                     |
| └── Unnest                                                   |
|     └── EvalScalar                                           |
|         ├── expressions: [[1, 2]]                            |
|         ├── estimated rows: 0.00                             | …
```

feat(query): support more advanced `unnest` operations.

---

src/common/tracing/src/panic_hook.rs

refactor: the panic hook should output error to stderr, not only to log, in case there is a panic when initializing logging

---

src/query/sql/src/planner/optimizer/heuristic/heuristic.rs
src/query/sql/src/planner/optimizer/heuristic/mod.rs
src/query/sql/src/planner/optimizer/rule/factory.rs
src/query/sql/src/planner/optimizer/rule/rewrite/mod.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_prewhere.rs
src/query/sql/src/planner/optimizer/rule/rule.rs

`PrewhereOptimizer` is no longer existing. Instead, it will become a rule.
Notice that `PushDownPrewhere` should be after all other rules except `PushDownSortScan`.
After this modification, we don't need to do optimization twice any more. This will also fix the failure of TPC-H Q19 for native format.

fix: make `PushDownPrewhere` as a rule.

---

src/query/pipeline/sinks/src/async_sink.rs
src/query/pipeline/sinks/src/sync_sink.rs

refactor(executor): always call sink on_finish
```
2023-03-04T18:44:31.819763Z  WARN databend_query::pipelines::executor::processor_async_task: src/query/service/src/pipelines/executor/processor_async_task.rs:77: Very slow processor async task, query_id:"b087d3f2-5516-4abd-896d-a395ec85d091", processor id: NodeIndex(106), name: "HashJoin", elapsed: 1620.419467644s
2023-03-04T18:44:36.821102Z  WARN databend_query::pipelines::executor::processor_async_task: src/query/service/src/pipelines/executor/processor_async_task.rs:77: Very slow processor async task, query_id:"b087d3f2-5516-4abd-896d-a395ec85d091", processor id: NodeIndex(106), name: "HashJoin", elapsed: 1625.420808724s …
```

refactor(executor): always call sink on_finish

---

src/query/functions/src/scalars/variant.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/functions/tests/it/scalars/testdata/variant.txt
src/query/functions/tests/it/scalars/variant.rs

- Support Variant function `object_construct` and `object_construct_keep_null`
- Add unit tests for variant `to_<type>` and `try_to_<type>` functions
- Fix `to_<type>` and `try_to_<type>` with null value 
Closes #4724
Closes #5425

feat(function): Support Variant function object_construct

---

src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs

Otherwise it has a chance to have read the stale applied log index.

chore: fixup: test_meta_node_restart: it should wait for the last log to be applied before writing a testing key

---

src/query/service/tests/it/servers/http/http_query_handlers.rs

fix ci failure to slow `create table` https://github.com/datafuselabs/databend/actions/runs/4362596845/jobs/7627675766
I will refactor tests like this later.
Closes #issue

ci: larger wait time for http handler long polling.

---

src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/statement.txt

forgot to add these tests when developing these features.
`@<stage>` and `'<uri>'` appear at the small place with the table identifier.
Closes #issue

ci(ast): add some unit test for AST of  stage table function and 'CREATE FILE FORMAT'

---

.github/actions/build_linux/action.yml
.github/workflows/release.yml
Cargo.lock
docker/build-tool/musl/Dockerfile
src/common/building/Cargo.toml
src/common/building/src/git.rs
src/common/building/src/lib.rs
src/meta/raft-store/src/config.rs
src/meta/service/src/version.rs
src/meta/types/src/config.rs
src/query/config/src/version.rs

`git2-sys` dose not do well with cross building, let's migrate to pure rust git implement `gix`.
Closes #issue

chore(building): upgrade vergen & replace git2 with gix

---

docs/doc/00-overview/index.md

Architucture -> Architecture
Just a simple typo fix - since it's in a header it is pretty glaring. 
Closes #issue
None, just fixing a typo.

docs: Fix Typo in Header

---

src/query/sql/src/planner/binder/sort.rs
tests/sqllogictests/suites/query/order.test

make sort respect index
```
MySQL [(none)]> select number  d , max(1-number) c from numbers(4) group by 1  order by 2;
+------+------+
| d    | c    |
+------+------+
|    3 |   -2 |
|    2 |   -1 |
|    1 |    0 |
|    0 |    1 |
+------+------+
4 rows in set (0.044 sec)
```
Closes #10453

fix(query): make sort respect index

---

Cargo.lock
Cargo.toml
src/binaries/Cargo.toml
src/common/metrics/Cargo.toml
src/meta/client/Cargo.toml
src/meta/service/Cargo.toml
src/query/service/Cargo.toml
src/query/storages/common/cache/Cargo.toml
src/query/storages/fuse/Cargo.toml
src/query/storages/system/Cargo.toml

introduce a new cargo feature `enable-histogram-metrics`,  which can enable the histogram metrics
- by default, it is disabled, metrics of histogram will be no-op 
- if enabled,  metrics of histogram will be "generated"
e.g.  `cargo b --features enable-histogram-metrics`
the "reason" of disabling histogram by default : https://github.com/metrics-rs/metrics/issues/245   
Closes #10428

feat: new feature `enable-histogram-metrics`

---

src/query/service/src/interpreters/interpreter_insert.rs
src/query/service/src/interpreters/interpreter_update.rs
src/query/service/tests/it/sql/planner/format/mod.rs
src/query/sql/src/executor/physical_plan_builder.rs
src/query/sql/src/planner/binder/aggregate.rs
src/query/sql/src/planner/binder/ddl/table.rs
src/query/sql/src/planner/binder/join.rs
src/query/sql/src/planner/binder/project.rs
src/query/sql/src/planner/binder/scalar_common.rs
src/query/sql/src/planner/binder/select.rs
src/query/sql/src/planner/binder/setting.rs
src/query/sql/src/planner/binder/sort.rs
src/query/sql/src/planner/format/display_rel_operator.rs
src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs
src/query/sql/src/planner/optimizer/heuristic/subquery_rewriter.rs
src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/extract_or_predicates.rs
src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/outer_join_to_inner_join.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_fold_count_aggregate.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_normalize_disjunctive_filter.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_union.rs
src/query/sql/src/planner/optimizer/rule/transform/util.rs
src/query/sql/src/planner/plans/scalar_expr.rs
src/query/sql/src/planner/semantic/grouping_check.rs
src/query/sql/src/planner/semantic/type_check.rs
src/query/storages/parquet/src/pruning.rs

Get data type of `ScalarExpr` with type checking to prevent unmatched data type.

chore(planner): Refactor data type of `ScalarExpr`

---

src/query/functions/src/scalars/variant.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/functions/tests/it/scalars/testdata/variant.txt
src/query/functions/tests/it/scalars/variant.rs

The `JSON` functions `object_construct` and `object_construct_keep_null` are too long and easily confused with other types of functions, so renamed them as follows:
- rename `object_keys` as `json_object_keys`, and use `object_keys` as alias for compatible
- rename `object_construct` as `json_object`
- rename `object_construct_keep_null` as `json_object_keep_null`
In order to distinguish `JSON` functions from the `Array` and `Map` related functions. New `JSON` functions added in the future will be named starting with `json_`, for example:
- `json_array` creates a `JSON` type `Array`
- `json_array_append` adds elements to a `JSON` type `Array`
- `json_array_contains` checks for the existence of an …

chore: rename json function `object_construct` as `json_object`

---

src/query/service/src/servers/http/http_services.rs

feat(query): add endpoint for healthcheck

---

Cargo.lock
src/query/expression/src/function.rs
src/query/expression/src/kernels/concat.rs
src/query/expression/src/kernels/filter.rs
src/query/expression/src/kernels/scatter.rs
src/query/expression/src/kernels/take.rs
src/query/expression/src/kernels/take_chunks.rs
src/query/storages/common/index/Cargo.toml
src/query/storages/common/index/src/bloom_index.rs
src/query/storages/common/index/src/lib.rs
src/query/storages/common/index/tests/it/filters/bloom_filter.rs
tests/sqllogictests/suites/base/03_common/03_0037_insert_into_map

Map data type support bloom filter
Part of #10062
From the test data example, we can see that the bloom filter is effective in reducing the query time if the value of the query does not exist.
```sql
MySQL root@127.0.0.1:default> select count(*) from test;
+----------+
| count(*) |
+----------+
| 100000   |
+----------+
1 row in set
Time: 0.153s
MySQL root@127.0.0.1:default> select * from test where log['ip'] = '205.91.162.148';
+----+----------------------------------------+
| id | log                                    |
+----+----------------------------------------+
| 1  | {'ip':'205.91.162.148','url':'test-1'} |
+----+----------------------------------------+
1 row in set
Time: 1.733s
MySQL …
```

feat(storage): Map data type support bloom filter

---

src/query/storages/fuse/src/io/files.rs
src/query/storages/fuse/src/io/mod.rs
src/query/storages/fuse/src/io/parallel.rs
src/query/storages/fuse/src/io/segments.rs
src/query/storages/fuse/src/io/snapshots.rs
src/query/storages/fuse/src/operations/merge_into/processors/transform_mutation_aggregator.rs
src/query/storages/fuse/src/operations/mutation/mutation_transform.rs

Old:
```
list @bomb;
292992 rows in set (18.23 sec)
mysql> remove @bomb;
Query OK, 0 rows affected (1 min 38.22 sec)
```
This PR:
```
list @bomb;
292992 rows in set (15.63 sec)
mysql> remove @bomb;
Query OK, 0 rows affected (16.99 sec)
```
How to test:
```
create stage bomb;
copy into @bomb from (select * from numbers(300000000)) file_format=(type=parquet) max_file_size=32;
remove @bomb;
```
Closes #issue

chore: make delete file in batch to parallel

---

Cargo.lock
src/common/storage/Cargo.toml
src/common/storage/src/metrics.rs
src/query/catalog/src/table_context.rs
src/query/service/src/interpreters/interpreter_copy.rs
src/query/service/src/interpreters/interpreter_list.rs
src/query/service/src/interpreters/interpreter_user_stage_remove.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/storages/fuse/src/operations/gc.rs
src/query/storages/stage/src/file.rs
src/query/storages/stage/src/stage_table.rs
src/query/storages/system/src/processes_table.rs

* change the storage status to TableContext
* add more status & info to COPY main operations (but this will work in another PR)
* add pattern to the `list_file`
Closes #issue

feat: add status for the operation in show processlist

---

src/query/service/src/api/rpc/flight_client.rs
src/query/service/src/api/rpc/flight_service.rs
src/query/service/src/sessions/session.rs
src/query/service/src/sessions/session_ctx.rs
src/query/service/tests/it/sessions/session_context.rs

- refactor(query): remove io shutdown block on
- fix(query): fix cluster hang when parallel execute query
Closes #issue

fix(query): fix cluster hang when parallel execute query

---

.github/actions/benchmark_cloud/action.yml
.github/actions/benchmark_local/action.yml
.github/actions/setup_bendsql/action.yml
.github/workflows/benchmark.yml
.github/workflows/release.yml
.github/workflows/trusted-benchmark.yml
benchmark/clickbench/benchmark_cloud.sh
benchmark/clickbench/benchmark_local.sh

ci(benchmark): run s3 clickbench with cloud

---

src/meta/app/src/principal/user_privilege.rs
src/query/ast/src/parser/statement.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/statement-error.txt
src/query/ast/tests/it/testdata/statement.txt

```sql
dd:root@localhost/default=> grant create stage on *.* to 'a'@'%';
error: databend: query has error: code: 1005, message: error: 
--> SQL:1:14
|
1 | grant create stage on *.* to 'a'@'%';
| ----- ------ ^^^^^ expected `ON` or `,`
| |     |       
| |     while parsing <privileges> ON <privileges_level>
| while parsing `GRANT { ROLE <role_name> | schemaObjectPrivileges | ALL [ PRIVILEGES ] ON <privileges_level> } TO { [ROLE <role_name>] | [USER] <user> }`
```
Closes #issue

fix(query): fix grant create user err

---

src/query/catalog/src/table_context.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/service/src/sessions/session_info.rs
src/query/storages/system/src/processes_table.rs

show process status info should use the status info of the process/query context being shown, not the query context of statement `show processlist`
Closes #issue

fix: show process status info

---

.github/workflows/trusted-benchmark.yml

```txt
The workflow is not valid. .github/workflows/release.yml (Line: 516, Col: 3): Error calling workflow 'datafuselabs/databend/.github/workflows/trusted-benchmark.yml@200bb85fb199265b5fce5a02ef219ea26101e7b0'. The workflow 'datafuselabs/databend/.github/workflows/trusted-benchmark.yml@200bb85fb199265b5fce5a02ef219ea26101e7b0' is requesting 'pull-requests: write', but is only allowed 'pull-requests: none'.
```
Our CI process is failing because of this error. I believe the solution would be to remove it.

ci: Remove pull-requests: write which is not allowed

---

src/common/io/src/cursor_ext/cursor_read_number_ext.rs
src/query/formats/src/field_decoder/fast_values.rs
src/query/formats/src/field_decoder/tsv.rs
src/query/formats/src/field_decoder/values.rs
src/query/service/src/interpreters/interpreter_insert.rs
tests/sqllogictests/suites/base/03_common/03_0023_insert_into_array
tests/sqllogictests/suites/base/03_common/03_0026_insert_into_tuple
tests/sqllogictests/suites/base/03_common/03_0037_insert_into_map
tests/suites/1_stateful/00_copy/00_0002_copy_from_fs_on_error.sh
tests/suites/1_stateful/05_formats/05_02_csv/05_02_02_csv_spaces.sh

- Pop values from the inner columns if found error to avoid duplicate values.
- Rollback reader to start position of the row if need a fallback
Closes #10486

fix(query): fix insert nested data types with expr

---

.github/actions/benchmark_cloud/action.yml
.github/actions/benchmark_local/action.yml
.github/actions/setup_bendsql/action.yml
.github/workflows/release.yml
.github/workflows/trusted-benchmark.yml
benchmark/clickbench/benchmark_cloud.sh

chore(ci): fix download artifact for benchmark

---

src/query/settings/src/lib.rs

chore(query): use num_cpu as default_max_storage_io_requests
Closes #issue

chore(query): use num_cpu as default_max_storage_io_requests

---

docs/doc/10-deploy/02-deploying-databend.md

docs(deploy): short the object storage provider name

---

src/query/service/tests/it/storages/testdata/columns_table.txt
src/query/storages/information-schema/src/columns_table.rs
tests/sqllogictests/suites/base/20+_others/20_0000_describe_table

Add the NULLABLE field to information_schema.columns
1 means is_nullable = 'YES'.
0 means is_nullable = 'NO'.
Closes #10557

feat(query): Add the NULLABLE field to information_schema.columns

---

.github/actions/benchmark_cloud/action.yml
.github/actions/publish_binary/action.yml
.github/actions/setup_docker/action.yml
.github/workflows/release.yml
.github/workflows/trusted-benchmark.yml

chore(ci): benchmark with large warehouse

---

docs/doc/14-sql-commands/00-ddl/20-table/60-optimize-table.md

This pr suggests user to check whether
compact segments(less than 100blocks per segment):
```
SELECT block_count, segment_count, 
IF(block_count/segment_count < 100, 'The table needs segment compact now', 'The table does not need segment compact now') AS advice 
FROM fuse_snapshot('your-database', 'your-table') LIMIT 1;
```
compact blocks(the uncompress size less than 50MB per block):
```
SELECT block_count, humanize_size(bytes_uncompressed/block_count) AS per_block_uncompressed_size,
IF(bytes_uncompressed/block_count/1024/1024<50, 'The table needs block compact now', 'The table does not need block compact now') as advice 
FROM fuse_snapshot('your-database', 'your-table') LIMIT 1;
```
Closes #issue

docs(compact): refine the compact

---

Cargo.lock
src/common/storage/Cargo.toml
src/common/storage/src/lib.rs
src/common/storage/src/stage.rs
src/query/service/src/interpreters/interpreter_list.rs
src/query/sql/src/planner/binder/copy.rs
src/query/storages/parquet/src/parquet_table/partition.rs
src/query/storages/stage/src/stage_table.rs

refactor: Merge FileWithMetadata into StageFileInfo

refactor: Merge FileWithMetadata into StageFileInfo

---

src/query/expression/src/schema.rs
src/query/expression/src/types.rs
src/query/expression/tests/it/schema.rs
src/query/storages/common/index/src/page_index.rs
src/query/storages/common/index/src/range_index.rs
src/query/storages/fuse/src/statistics/column_statistic.rs

- Store max/min values for all the leaf columns of nested data types
- Generate domain for nested data types and skip the block if the filter range does not match the domain 
From local test data, it can effectively reduce the query time when the filter ranges do not match
```sql
MySQL root@127.0.0.1:default> create table tt (a array(int), b map(string, int), c tuple(int, string));
Query OK, 0 rows affected
Time: 0.223s
MySQL root@127.0.0.1:default> select count(*) from tt;
+----------+
| count(*) |
+----------+
| 100000   |
+----------+
1 row in set
Time: 0.087s
MySQL root@127.0.0.1:default> select * from tt where a[1] >= 100;
+-------------------+---------------+----------------+
| a …
```

feat(storage): Support domain for nested data types

---

src/query/ast/src/ast/format/ast_format.rs
src/query/ast/src/ast/format/syntax/query.rs
src/query/ast/src/ast/query.rs
src/query/ast/src/parser/query.rs
src/query/ast/src/parser/token.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/statement.txt
src/query/sql/src/planner/binder/aggregate.rs
tests/sqllogictests/suites/duckdb/sql/aggregate/group/group_by_grouping_sets.test
tests/sqllogictests/suites/mode/standalone/explain/explain_grouping_sets.test

`ROLLUP` and `CUBE` are two syntactic sugars of `GROUPING SETS`.
We can just desugar them into `GROUPING SETS` when binding.
`ROLLUP(a,b,c)` => `GROUPING SETS ((a,b,c), (a,b), (a), ())` ；
`CUBE(a,b)` => `GROUPING SETS ((a,b),(a),(b),())` (subset combinations)
Tracking in #10492.

feat: support `CUBE` and `ROLLUP`.

---

Cargo.lock
docs/doc/14-sql-commands/20-query-syntax/02-dml-with.md
docs/doc/15-sql-functions/61-ai-functions/_category_.json
docs/doc/15-sql-functions/61-ai-functions/index.md
src/query/service/Cargo.toml
src/query/service/src/table_functions/openai/gpt_to_sql.rs
src/query/service/src/table_functions/openai/mod.rs
src/query/service/src/table_functions/table_function_factory.rs

```
CREATE DATABASE openai;
USE openai;
CREATE TABLE users(
id INT,
name VARCHAR,
age INT
);
SELECT * FROM ai_to_sql('List all users older than 30 years', '<openai-api-key>');
```
Output:
```
*************************** 1. row ***************************
database: simple_example
generated_sql:  SELECT * FROM users WHERE age > 30;
```
Closes #issue

feat: add `ai_to_sql` transalte natual lanauge to SQL based on your table schema

---

Cargo.lock
src/query/service/Cargo.toml

chore(async-openai): Come back to upstream

chore(async-openai): Come back to upstream

---

src/query/ast/src/ast/statements/copy.rs
src/query/ast/src/parser/stage.rs
src/query/ast/src/parser/token.rs
src/query/ast/tests/it/parser.rs
src/query/ast/tests/it/testdata/statement.txt
tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables

Fix https://github.com/datafuselabs/databend/issues/10653
We already have a runtime check here:
https://github.com/datafuselabs/databend/blob/048b72ac8c179f38e985d9370d44a70b586766dd/src/query/ast/src/ast/statements/copy.rs#L221-L239
For example:

refactor: AST check is not needed after static runtime check added

---

src/query/functions/src/scalars/other.rs
src/query/functions/tests/it/scalars/testdata/other.txt
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_scan.rs
tests/sqllogictests/suites/mode/standalone/explain/select.test
tests/sqllogictests/suites/mode/standalone/explain/sort.test

1. make sleep only accept scalar arg 
2. support multi filter pushdown into scan
Closes #10644 #10663

chore(planner): support multi filter pushdown into scan

---

src/query/users/src/user_api.rs

```
WARN common_users::user_api: src/query/users/src/user_api.rs:76: Reserved built-in user `root` will be ignored
```
Closes #issue

fix(query): warn about reserved built-in user

---

src/query/config/src/config.rs
src/query/config/src/inner.rs
src/query/service/src/databases/system/system_database.rs
src/query/service/tests/it/databases/mod.rs
src/query/service/tests/it/databases/system/mod.rs
src/query/service/tests/it/databases/system/system_database.rs
src/query/service/tests/it/storages/testdata/configs_table_basic.txt

For security, some system tables like `config/cluster` is no need to the SQL user query.
In this PR we introduce a new query.config:`disable_system_table_load` to control them.
Closes #issue

chore(system): add disable_system_table_load to allow disable load some system tables

---

src/meta/api/src/schema_api_impl.rs

patch of PR https://github.com/datafuselabs/databend/pull/10427
in copy force mode, files could be inserted unconditionally (no related conditions needed to be put in the `if condition`) .
that hurts the performance.
Closes #issue

fix: in copy force mode, files should be insert unconditionally

---

src/query/config/src/config.rs
src/query/config/src/inner.rs
src/query/config/src/lib.rs
src/query/config/src/mask.rs
src/query/service/src/table_functions/openai/gpt_to_sql.rs
src/query/service/tests/it/storages/testdata/configs_table_basic.txt
src/query/service/tests/it/table_functions/mod.rs
src/query/service/tests/it/table_functions/openai.rs
src/query/storages/system/src/configs_table.rs

Introduce a new query config: `openai_api_key`:
```
mysql> select * from ai_to_sql('how many hits');
+----------+---------------------------+
| database | generated_sql             |
+----------+---------------------------+
| hits     | SELECT count(*) FROM hits |
+----------+---------------------------+
```
In the system.configs:
```
query   | openai_api_key                           | ******                                   |             |
```
Closes #10654

feat(openai): add openai_api_key to config

---

src/query/service/src/interpreters/interpreter_view_create.rs
src/query/storages/hive/hive/src/hive_catalog.rs
src/query/storages/iceberg/src/catalog.rs
tests/sqllogictests/suites/base/05_ddl/05_0019_ddl_create_view

Like this:
```
postgres=# create view v_t as select * from v_t;
ERROR:  relation "v_t" does not exist
LINE 1: create view v_t as select * from v_t;
```
Note:
> QUERY can query table_functions but only DatabaseCatalog impl list_table_functions. HiveCatalog and IcebergCatalog are unimplemented!(). So I try to modify them to return `vec![]`.
Closes #10669

fix(query): create view check unknown table

---

src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_eval_scalar.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_scan.rs
tests/sqllogictests/suites/mode/standalone/explain/explain.test
tests/sqllogictests/suites/mode/standalone/explain/prune_column.test
tests/sqllogictests/suites/mode/standalone/explain/select.test

Replacing `DerivedColumn` in `Filter` with the column expression defined in the view, so that we can push down the `Filter` to the `Scan`.
Closes #9882

fix(query): fix view select filter can not push down to scan

---

src/query/service/src/interpreters/interpreter_copy.rs
src/query/service/src/interpreters/interpreter_select.rs

Do not build pipeline before checking cache.
Building pipeline will activate other cluster nodes.
Closes #10687.

fix: do not build pipeline before checking cache.

---

src/query/functions/src/aggregates/aggregate_quantile_cont.rs

Manual drop state to prevent memory leak
Closes #issue

fix: manual drop state to prevent memory leak

---

src/query/expression/src/types/string.rs
src/query/pipeline/sources/src/input_formats/input_format_text.rs

Test #10483 is leaked or not.
If the processor is leaked (unsafe codes in pipeline processor), object `BlockBuilder` will be memory leaked thus the builder will be memory leaked.
Closes #issue

chore(query): make flush returns empty builder

---

src/query/expression/src/property.rs
src/query/expression/src/types/string.rs
src/query/functions/src/scalars/comparison.rs
tests/sqllogictests/suites/mode/standalone/explain/range_pruner.test

1.  add compare domain for string types
2. add `SimpleDomainCmp` trait to used codes.
Closes #10735

chore(query): add compare domain for string types

---

src/query/functions/src/srfs/mod.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/sql/src/evaluator/block_operator.rs
tests/sqllogictests/suites/query/02_function/02_0062_function_unnest

unnest function support `NULL` value and `Nullable Array Column`
Closes #10758

fix(functions): fix unnest with null argument

---

src/query/service/src/auth.rs
src/query/service/src/servers/http/middleware.rs
src/query/service/tests/it/auth.rs
src/query/service/tests/it/servers/http/http_query_handlers.rs
src/query/service/tests/it/storages/testdata/roles_table.txt
src/query/users/src/jwt/authenticator.rs
src/query/users/src/jwt/jwk.rs
src/query/users/src/user_api.rs

Ensuring a user to MetaSrv is a painful cost, which make our JWT auth take up to 1s+ on every request.
Since we do not really need a user on MetaSrv with JWT auth, this PR
* create a virtual JWT user instead of ensuring on metasrv
* remove hostname for JWT auth & deny root user
* ensure_builtin_roles on GlobalService init for UserApiProvider
Closes #issue

fix(query): create a virtual JWT user instead of ensuring on metasrv

---

scripts/ci/deploy/config/databend-query-node-1.toml
scripts/ci/deploy/config/databend-query-node-2.toml
scripts/ci/deploy/config/databend-query-node-3.toml
scripts/ci/deploy/config/databend-query-node-shared.toml
src/query/config/src/config.rs
src/query/config/src/inner.rs
src/query/expression/src/convert_arrow_rs/array.rs
src/query/expression/src/convert_arrow_rs/record_batch.rs
src/query/expression/src/convert_arrow_rs/schema.rs
src/query/service/src/servers/flight_sql/flight_sql_service/query.rs
src/query/service/src/servers/flight_sql/flight_sql_service/service.rs
src/query/service/src/servers/flight_sql/flight_sql_service/session.rs
src/query/service/src/servers/mysql/mysql_interactive_worker.rs
src/query/service/tests/it/servers/flight_sql/flight_sql_handler.rs
src/query/service/tests/it/storages/testdata/configs_table_basic.txt
src/query/sql/src/planner/plans/plan.rs

part of https://github.com/datafuselabs/databend/issues/10745.
-  ddl/insert work well with JDBC, see https://github.com/youngsofun/test_flight_sql/blob/main/src/main/java/Test.java.
- but the official rs client has a bug (which is not used in production AFAIK),  so new unit test cases is commented out for now. however,  it uses a different interface of FlightSQL from JDBC(in JDBC, all statement is implemented as preparedStatement internally ).
- port change from 7000 to 8900 due to https://github.com/datafuselabs/databend/discussions/10741
- still only basic types are supported, I will go back to it after  impl meta related API  https://github.com/datafuselabs/databend/issues/10745.
Closes #issue

feat: FlightSQL support update (DDL and insert)

---

scripts/ci/ci-run-stateful-tests-standalone-minio.sh
src/query/service/src/auth.rs
src/query/service/src/global_services.rs
src/query/service/src/servers/http/http_services.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/service/src/sessions/session.rs
src/query/service/tests/it/auth.rs
src/query/service/tests/it/servers/http/clickhouse_handler.rs
src/query/service/tests/it/servers/http/http_query_handlers.rs
src/query/service/tests/it/tests/context.rs

* Avoid creating an `AuthMgr` instance on every session.
* Remove `auth_manager` from query ctx.
* Then `InnerConfig` is no longer needed by query ctx.
Closes #issue

fix(query): init AuthMgr with GlobalInstance

---

src/query/service/src/pipelines/processors/mod.rs
src/query/service/src/pipelines/processors/transforms/mod.rs
src/query/service/src/pipelines/processors/transforms/window/frame.rs
src/query/service/src/pipelines/processors/transforms/window/mod.rs
src/query/service/src/pipelines/processors/transforms/window/transform_window.rs
src/query/service/tests/it/pipelines/processors/mod.rs
src/query/service/tests/it/pipelines/processors/transforms/mod.rs
src/query/service/tests/it/pipelines/processors/transforms/transform_window.rs

Basic implementation of `TransformWindow`.
For each row, compute its window frame and apply aggregation.
Time complexity: O(n^2).
Window sliding logic will be improved in later PRs.

feat: basic implementation of `TransformWindow`.

---

src/query/service/src/servers/flight_sql/flight_sql_service/service.rs

more logs enable us to faster response when meeting problems, which may due to:
1. FlightSQL itself is not stable,  official client/server impls may not flow the spec exactly.
2. diff BI tools may have diff usage of the JDBC driver.
Closes #issue

chore(FlightSQL): log all req to unimplemented API.

---

src/query/service/src/interpreters/access/privilege_access.rs
tests/suites/0_stateless/20+_others/20_0012_privilege_access.result
tests/suites/0_stateless/20+_others/20_0012_privilege_access.sh

This PR is a quick fix about the users with PUBLIC role can not view the databases / tables / columns.
We can later add more checks among the privileges about the target databases, likewise an user can not SHOW TABLES on a databases which she don't have the SELECT privilege.
Closes #issue

fix: Allow PUBLIC role show databases / tables / columns

---

Cargo.lock
src/common/openai/Cargo.toml
src/common/openai/src/completion.rs
src/common/openai/src/embedding.rs
src/common/openai/src/metrics.rs

```
pub fn metrics_completion_count(c: u32) {
increment_gauge!("openai_completion_count", c as f64);
}
pub fn metrics_completion_token(c: u32) {
increment_gauge!("openai_completion_token", c as f64);
}
pub fn metrics_embedding_count(c: u32) {
increment_gauge!("openai_embedding_count", c as f64);
}
pub fn metrics_embedding_token(c: u32) {
increment_gauge!("openai_embedding_token", c as f64);
}
```
openai pricing:
```
completion $0.0200 / 1K tokens
embedding $0.0004 / 1K tokens
```
Closes #issue

feat: add metrics for openai invoke

---

Cargo.lock
src/query/service/Cargo.toml
src/query/service/src/servers/flight_sql/flight_sql_service/mod.rs
src/query/service/src/servers/flight_sql/flight_sql_service/service.rs
src/query/service/src/servers/flight_sql/flight_sql_service/sql_info.rs

we can now call 
```
String name = connection.getMetaData().getDatabaseProductName();
```
there are many a lot more  SqlInfos to add later.
the implement detail not found in spec but in the code or JAVA JDBC
Closes #issue

feat(FlightSQL): support basic SqlInfo.

---

src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/service/tests/it/storages/fuse/operations/mutation/block_compact_mutator.rs
src/query/service/tests/it/storages/fuse/operations/mutation/mod.rs
src/query/service/tests/it/storages/fuse/operations/mutation/segments_compact_mutator.rs
src/query/storages/fuse/src/operations/commit.rs

incorrect index size and count of perfect blocks during merge segments.
note: block data and index data not affected, only the statistics is incorrect.
Closes #issue

fix: incorrect index size and perfect_block_count during merge segments

---

src/query/storages/system/src/tables_table.rs

Currently SHOW TABLES is a rewrite to selecting `system.tables`.
However in `system.tables`, it tries to list all the tables from every databases. If any databases raises EmptyShareEndpointConfig, all SHOW TABLES to any database will met this error.
This PR tries to swallow the EmptyShareEndpointConfig on SHOW TABLES statement.

fix: EmptyShareEndpointConfig  error on any SHOW TABLES

---

src/binaries/Cargo.toml
src/binaries/metabench/main.rs
src/meta/service/Cargo.toml
src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/src/store/mod.rs
src/meta/service/src/store/store_inner.rs

This feature enables defensive check when accessing the raft store, e.g,
it check if the next log is at index of last index plus one, when
appending logs.
For optimal performance, this feature is disabled by default.
- New Feature

feat: add feature "raft-store-defensive" to enable defensive check

---

src/query/service/src/servers/flight_sql/flight_sql_service/service.rs

- `get_flight_info_xxx_keys` is not supported since we are not likely to support them later.
- other `get_flight_info_xxx_keys` is simple, and the corresponding feature will be ready after the corresponding `do_get_xxx ` is implemented one by one.

feat(FlightSQL): impl some get_flight_info_xxx.

---

src/query/service/src/catalogs/default/mutable_catalog.rs
src/query/service/src/interpreters/interpreter_copy.rs

during the execution of `copy-into`, if both purge and force are enabled, do not upsert the table's copied-files set in meta server.
NOTE:
since the table's copied-files set will NOT be upsert in meta service, if both `purge` and `force` are enabled.
later/parallel executions of `copy-into`  are taking the risk of data duplication.
Closes #10854

refactor: do not upsert copied-files set if both purge and force are enabled

---

Cargo.lock
Cargo.toml
src/binaries/metactl/snapshot.rs
src/meta/raft-store/src/log/raft_log.rs
src/meta/raft-store/tests/it/log.rs
src/meta/service/src/store/store_bare.rs
src/meta/service/tests/it/store.rs
src/meta/sled-store/src/sled_tree.rs
src/meta/sled-store/tests/it/sled_iter.rs
src/meta/sled-store/tests/it/sled_tree.rs
src/meta/types/src/raft_types.rs
tests/meta-data-compat-openraft-07/test-meta-data-compat-openraft-08.sh

-   Changed: [9ddb5715](https://github.com/datafuselabs/openraft/commit/9ddb5715a33902a83124f48ee33d75d490fcffa5) RaftState: make vote private. Accesses vote via 2 new public methods: `vote_ref()` and `vote_last_modified()`.; by 张炎泼; 2023-03-12
-   Changed: [3b4f4e18](https://github.com/datafuselabs/openraft/commit/3b4f4e186bca5404744d2940571974500d52734d) move log id related traits to mod `openraft::log_id`; by 张炎泼; 2023-03-14
-   Changed: [a92499f2](https://github.com/datafuselabs/openraft/commit/a92499f20360f0f6eba3452e6944702d6a50f56d) StoreBuilder does not need to run a test, it only needs to build a store; by 张炎泼; 2023-03-21
-   Changed: …

refactor(meta): upgrade openraft from 0.8.3-alpha.2 to 0.8.4-alpha.1

---

src/query/functions/src/scalars/vector.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/sql/src/planner/semantic/type_check.rs

This PR adds a new SQL function, ai_text_completion, which utilizes the OpenAI API to generate text completions. 
Users can call the function with a text input, and it will return an AI-generated text completion based on the given input.
This feature enables users to perform basic machine learning tasks using SQL, enhancing the capabilities of the database system.
Example usage:
```
query:
SELECT ai_text_completion('say this is a test again');
result:
This is a test indeed
```
Closes #issue

feat: add ai_text_completion function

---

Cargo.lock
src/common/openai/Cargo.toml
src/query/functions/src/scalars/vector.rs

* fix `openai-api` crate `buf_redux v0.8.4, multipart v0.18.0` build warning
* fix `ai_text_completion` commit_row
Closes #issue

chore: fix openai-api crate build warning and fix ai_text_completion

---

src/common/openai/src/completion.rs
src/common/openai/src/lib.rs
src/query/functions/src/scalars/vector.rs
src/query/service/src/table_functions/openai/ai_to_sql.rs

```
pub enum CompletionMode {
// SQL translate:
// max_tokens: 150, stop: ['#', ';']
SQL,
// Text completion:
// max_tokens: 250, stop: none
Text,
}
```
Closes #issue

chore: add completion mode for SQL or Text

---

Cargo.lock
src/common/storage/Cargo.toml
src/common/storage/src/operator.rs

feat: Allow setting connect timeout and timeout for s3
This PR adds a feature which allow users to set connect timeout and timeout for s3. This feature is internal used only. And we will make it public until we make sure that it works.
- `_DATABEND_INTERNAL_CONNECT_TIMEOUT`: configure the connect timeout, default to 30s
- `_DATABEND_INTERNAL_TIMEOUT`: configure the whole request's timeout, default to 120s

feat: Allow setting connect timeout and timeout for s3

---

src/common/storage/src/operator.rs

feat: Allow setting pool_max_idle_per_host for http client
- `_DATABEND_INTERNAL_POOL_MAX_IDLE_PER_HOST`: Pool max idle per host controls connection pool size. Default to no limit, set to `0` for disable it.

feat: Allow setting pool_max_idle_per_host for http client

---

src/query/expression/src/type_check.rs
src/query/functions/src/aggregates/adaptors/aggregate_null_unary_adaptor.rs
src/query/service/src/pipelines/pipeline_builder.rs
src/query/sql/src/planner/binder/aggregate.rs
src/query/sql/src/planner/binder/distinct.rs
src/query/sql/src/planner/binder/having.rs
src/query/sql/src/planner/binder/project.rs
src/query/sql/src/planner/binder/select.rs
src/query/sql/src/planner/binder/sort.rs
src/query/sql/src/planner/binder/window.rs
src/query/sql/src/planner/optimizer/heuristic/subquery_rewriter.rs
src/query/sql/src/planner/semantic/grouping_check.rs
src/query/sql/src/planner/semantic/type_check.rs
src/query/sql/src/planner/semantic/window_check.rs
tests/sqllogictests/suites/query/window_function/window_basic.test

- Support such SQLs:
```sql
select a, sum(a), sum(sum(a)) over (partition by sum(a) order by sum(a)) from t group by b;
select grouping(salary), grouping(depname), sum(grouping(salary)) over (partition by grouping(salary) + grouping(depname) order by grouping(depname) desc) from empsalary group by rollup (depname, salary);
```
- Fix checking function `grouping`, allow `grouping` appearing in nested exprs.
- Allow window function appearing in subquery.
- Fix window pipeline. `TransformWindow` should be a pipeline breaker, which means we should `pipeline.resize(1)` before concat `TransformWindow`.
Tracking in #10810

feat: support aggregation function in window clause.

---

src/common/openai/src/completion.rs

max_token from 250 to 512, make the openai response more contents.
Closes #issue

chore: make the completion more larger response

---

src/query/storages/fuse/src/operations/merge_into/mutator/merge_into_mutator.rs
src/query/storages/fuse/src/operations/merge_into/processors/processor_broadcast.rs
src/query/storages/fuse/src/operations/merge_into/processors/transform_append.rs
src/query/storages/fuse/src/operations/replace_into/processor_replace_into.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0024_replace_into_issue_10861

_broadcast processor_ and _replace_into processor_ used in the impl of `replace into` may lose data blocks,
and if that happened, data may be partially replaced into the target table.
Closes #10861

fix:  processors used in the impl of `replace into` may lose data

---

src/query/catalog/src/table_context.rs
src/query/service/src/servers/flight_sql/flight_sql_service/query.rs
src/query/service/src/servers/flight_sql/flight_sql_service/service.rs
src/query/service/src/servers/flight_sql/flight_sql_service/session.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/service/src/sessions/session_status.rs
src/query/service/src/stream/processor_executor_stream.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/sql/src/executor/table_read_plan.rs

https://github.com/datafuselabs/databend-client/pull/26
Style example:
Closes #issue

feat: flight sql support send progress into client

---

src/query/storages/fuse/src/pruning/fuse_pruner.rs

refactor: Switch to global IO runtime for pruning

refactor: Switch to global IO runtime for pruning

---

src/query/service/src/servers/mysql/mysql_interactive_worker.rs

mysql affected_rows should use write process value
Closes #10748

fix(query): mysql affected_rows should use write process value

---

src/meta/app/src/principal/file_format.rs
src/meta/app/src/principal/mod.rs
src/meta/proto-conv/src/file_format_from_to_protobuf_impl.rs
src/meta/proto-conv/src/stage_from_to_protobuf_impl.rs
src/meta/proto-conv/src/user_from_to_protobuf_impl.rs
src/meta/proto-conv/src/util.rs
src/meta/proto-conv/tests/it/main.rs
src/meta/proto-conv/tests/it/v032_file_format_params.rs
src/meta/protos/proto/file_format.proto

step 2  of  https://github.com/datafuselabs/databend/issues/10376
1. add enum FileFormatParams which is going to replace FileFormatOptions,  it`s corresponding PB def in meta, and the convs
2. func to trans FileFormatAst to FileFormatParams.
3. rename `skip_header` to `headers`, since it will be also used for OutputFormat later.
FileFormatParams is not really used, so this pr is safe.
There may be changes to  FileFormatParams in the following pr, but they won't be significant.

refactor(format): add FileFormatParams.

---

src/query/sql/src/planner/optimizer/rule/transform/rule_exchange_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_left_associate_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_left_exchange_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_right_associate_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_right_exchange_join.rs

Closes https://github.com/datafuselabs/databend/issues/10954

fix: non-equi condition is mistaken as equi condition

---

src/query/expression/src/kernels/group_by_hash.rs
src/query/storages/fuse/src/fuse_table.rs
tests/sqllogictests/suites/base/03_common/03_0003_select_group_by

fix: `fixed_hash` supports Decimal types.

---

src/query/service/src/api/http/v1/tenant_tables.rs
src/query/sharing/src/share_endpoint.rs

On accessing the tables info by admin api, I got a UnknownShareEndpoint error like this:
```
curl localhost:8080/v1/tenants/tnh2xmxsf/tables
Code: 2715, Text = UnknownShareEndpoint from "default" to "tncy3exa1".
```
Afeter investigation, I found that "default" tenant tries to access a shared database from tenant tncy3exa1, but the share endpoint endpoint is not set. A bad config on one database made all the databases infomation can not be shown at all.
This PR added a `warnings` field in the list_tenant_tables_handler, to swallow the errors but display them in the warnings field. So users can still get the most of table infomations and warning message without lose all the things by one bad config.

fix: skip errors on listing tables in admin api

---

src/query/expression/src/utils/date_helper.rs
src/query/functions/src/scalars/datetime.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
tests/sqllogictests/suites/query/02_function/02_0012_function_datetimes

Feature:
Now users can use `to_unix_timestamp()` function to convert Databend timestamp to unix timestamp.
```
mysql> select to_unix_timestamp(now());
+--------------------------+
| to_unix_timestamp(now()) |
+--------------------------+
|           unix_timestamp |
+--------------------------+
```
Closes #10902

feat(query): Add toUnixTimestamp function

---

src/query/storages/fuse/src/pruning/fuse_pruner.rs

This reverts commit 537c9f295dc28212e5c22fa3dc4094ab45bbce8c.
Revert #10941

refactor: Revert switch to global IO runtime for pruning

---

website/blog/2023-04-08-databend-weekly-88.md

docs(weekly): add this week in databend 88

---

src/query/service/src/table_functions/openai/ai_to_sql.rs

```
mysql> select * from ai_to_sql('how many visits');
+----------+--------------------------+
| database | generated_sql            |
+----------+--------------------------+
| hits     | SELECTCOUNT(*) FROM hits |
+----------+--------------------------+
```
Closes #issue

chore: fix ai_to_sql response miss blank

---

src/query/service/src/auth.rs
src/query/users/src/role_mgr.rs

Currently we're initializing the builtin roles on start up. However there're also cases we want to read the multi-tenant metadata before any warehouse get started. When you try access the metadata with a JWT token but without builtin roles initialized, you will get several permission denied error.
This PR tries to fix this issue via ensure builtin roles on every JWT check, and to avoid degrading the performance, it check the existence of the role before any write operation, which avoids most of the write operations.

fix: ensure builtin roles on JWT check

---

docs/doc/16-security/00-access-control/10-access-control-privileges.md

refactored the Access Control Privileges page.
Closes #issue

docs: Access Control Privileges

---

docs/doc/15-sql-functions/61-ai-functions/index.md

docs: add more example for ai functions

---

Cargo.lock
Cargo.toml
src/binaries/Cargo.toml
src/common/arrow/Cargo.toml
src/common/exception/Cargo.toml
src/common/grpc/Cargo.toml
src/common/tracing/Cargo.toml
src/meta/api/Cargo.toml
src/meta/client/Cargo.toml
src/meta/protos/Cargo.toml
src/meta/service/Cargo.toml
src/meta/types/Cargo.toml
src/query/expression/Cargo.toml
src/query/service/Cargo.toml

chore: Bump arrow-flight to 36 to make space fix version lock on proc-macro2

chore: Bump arrow-flight to 36 to make space fix version lock on proc-macro2

---

src/query/sql/src/planner/binder/join.rs
tests/sqllogictests/suites/mode/standalone/explain/join.test

```sql
explain SELECT o.x, t.y FROM onecolumn o INNER JOIN twocolumn t ON (o.x=t.x AND t.y=53);
```
Before
```
+--------------------------------------------------------------------------------------------------------------------------------+
| explain                                                                                                                        |
+--------------------------------------------------------------------------------------------------------------------------------+
| EvalScalar                                                                                                                     |
| ├── expressions: [o.x (#0), t.y (#2)] …
```

fix: join condition should push down

---

Cargo.lock
Cargo.toml
src/common/storage/Cargo.toml
src/common/storage/src/operator.rs
src/common/storage/src/stage.rs
src/query/service/src/interpreters/interpreter_presign.rs
src/query/sharing-endpoint/src/accessor/share_table_accessor.rs
src/query/sharing/src/layer.rs
src/query/sharing/src/share_endpoint.rs
src/query/sharing/src/signer.rs
src/query/sql/src/planner/binder/presign.rs
src/query/sql/src/planner/plans/presign.rs

This PR will bump OpenDAL to 0.31.
In this upgrade, opendal adopt async reqsign which removes all the block operations during auth.

refactor: Bump OpenDAL to v0.31

---

src/query/service/Cargo.toml

fix: tls feature for arrow-flight is missing

fix: tls feature for arrow-flight is missing

---

src/query/sql/src/planner/binder/scalar_common.rs
src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_exchange_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_left_associate_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_left_exchange_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_right_associate_join.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_right_exchange_join.rs

Store the comparison operator instead of boolean value `equal`

refactor(planner): Minor refactor of `JoinPredicate`

---

.github/workflows/release.yml

ci: use larger runner for hive release build [skip ci]

---

website/blog/2023-04-15-databend-weekly-89.md

docs(weekly): add this week in databend 89

---

src/query/functions/src/lib.rs
src/query/service/src/pipelines/processors/transforms/window/transform_window.rs
src/query/service/src/pipelines/processors/transforms/window/window_function.rs
src/query/sql/src/executor/physical_plan.rs
src/query/sql/src/executor/physical_plan_builder.rs
src/query/sql/src/planner/plans/window.rs
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/query/window_function/named_window_basic.test
tests/sqllogictests/suites/query/window_function/window_basic.test

percent_rank operate on the entire partition.
>>> Standard SQL specifies that window functions that operate on the entire partition should have no frame clause. MySQL permits a frame clause for such functions but ignores it. These functions use the entire partition even if a frame is specified
see https://dev.mysql.com/doc/refman/8.0/en/window-functions-frames.html
Postgres do exactly the same.
Tracking in https://github.com/datafuselabs/databend/issues/10810

feat(function): support window function percent_rank.

---

Cargo.lock

chore: Bump to reqsign 0.9.2 for helping debug

chore: Bump to reqsign 0.9.2 for helping debug

---

docs/doc/01-guides/_category_.json
docs/doc/01-guides/index.md

docs: refactor quick start materials

---

Cargo.lock
Cargo.toml
src/binaries/Cargo.toml
src/meta/raft-store/src/state_machine/sm.rs
src/meta/service/Cargo.toml
src/meta/service/src/api/http/v1/ctrl.rs
src/meta/service/src/api/http_service.rs
src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/src/network.rs
src/meta/service/src/store/mod.rs
src/meta/service/src/store/store.rs
src/meta/service/src/store/store_inner.rs
src/meta/service/tests/it/meta_node/meta_node_raft_api.rs
src/meta/service/tests/it/meta_node/mod.rs
src/meta/service/tests/it/store.rs
src/meta/types/src/lib.rs
src/meta/types/src/raft_types.rs

Separate the log store and state-machine store, in order to prevent
blocking of append-entries (heartbeat) when creating a snapshot.
Add a config for debugging that temporarily blocks snapshot building,
for testing purposes.
Add two tests that verify the leader's ability to write log entries
while a follower's snapshot building is blocked, in a 2-voter cluster.
[Openraft](https://github.com/datafuselabs/openraft/tree/release-0.8) changes since v0.8.4-alpha.1 to v0.8.4-alpha.2 :
`storage-v2`: enables `RaftLogStorage` and `RaftStateMachine` as the v2 storage
This is a temporary feature flag, and will be removed in the future, when v2 storage is stable.
This feature disables `Adapter`, which is for v1 …

feat(meta-service): Split log store and state-machine store

---

src/query/catalog/src/table.rs
src/query/service/src/interpreters/interpreter_copy.rs
src/query/service/src/interpreters/interpreter_replace.rs
src/query/service/src/servers/http/clickhouse_handler.rs
src/query/service/src/servers/http/v1/load.rs
src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/io/write/block_writer.rs
src/query/storages/fuse/src/operations/append.rs
src/query/storages/fuse/src/operations/compact.rs
src/query/storages/fuse/src/operations/delete.rs
src/query/storages/fuse/src/operations/fuse_sink.rs
src/query/storages/fuse/src/operations/merge_into/mutator/merge_into_mutator.rs
src/query/storages/fuse/src/operations/merge_into/processors/transform_append.rs
src/query/storages/fuse/src/operations/mutation/compact/compact_source.rs
src/query/storages/fuse/src/operations/recluster.rs
src/query/storages/fuse/src/operations/replace.rs
src/query/storages/fuse/src/statistics/cluster_statistics.rs
src/query/storages/stage/src/stage_table.rs
tests/sqllogictests/suites/base/09_fuse_engine/09_0023_replace_into

Support table with cluster key definition for Replace into statement
```
mysql> CREATE TABLE test(a int, b int) cluster by(a+1, b);
mysql> insert into test values(1, 1);
Query OK, 1 row affected (0.05 sec)
mysql> insert into test values(2, 2), (3, 2);
Query OK, 2 rows affected (0.04 sec)
mysql> replace into test on(a) values(3, 3), (4, 4);
Query OK, 3 rows affected (0.05 sec)
mysql> select a, b FROM test order by a;
+------+------+
| a    | b    |
+------+------+
|    1 |    1 |
|    2 |    2 |
|    3 |    3 |
|    4 |    4 |
+------+------+
4 rows in set (0.03 sec)
Read 4 rows, 32.00 B in 0.008 sec., 503.64 rows/sec., 3.93 KiB/sec.
mysql> select * FROM …
```

feat(storage): replace support cluster stats generator

---

docker/build-tool/musl/Dockerfile
scripts/setup/dev_setup.sh

Default bash version in macos is `3.2.57`, which does not have hash table support.
Closes #issue

chore(ci): fix do not use bash dict in dev_setup

---

src/binaries/meta/main.rs
src/meta/service/src/meta_service/raftmeta.rs
src/meta/service/src/store/store_inner.rs
src/meta/stoerr/src/meta_storage_errors.rs
src/meta/types/src/errors/meta_api_errors.rs

Just do not give up too quickly, retry when leader is not ready or when
there are concurrent membership changes on going.

refactor(meta-service): handle every error when joining into a cluster

---

docs/doc/14-sql-commands/00-ddl/20-table/10-ddl-create-table.md
docs/doc/14-sql-commands/00-ddl/20-table/90-alter-table-column.md
src/query/sql/src/planner/binder/ddl/table.rs

* better error msg when the default column value is not constant expression
* better the doc for create table and alter table add/drop column
Closes #issue

chore: refine the default column value error

---

docs/doc/15-sql-functions/110-semi-structured-functions/_category_.json
docs/doc/15-sql-functions/110-semi-structured-functions/as-type.md
docs/doc/15-sql-functions/110-semi-structured-functions/check-json.md
docs/doc/15-sql-functions/110-semi-structured-functions/get-ignore-case.md
docs/doc/15-sql-functions/110-semi-structured-functions/get-path.md
docs/doc/15-sql-functions/110-semi-structured-functions/get.md
docs/doc/15-sql-functions/110-semi-structured-functions/json-extract-path-text.md
docs/doc/15-sql-functions/110-semi-structured-functions/json-path-query-array.md
docs/doc/15-sql-functions/110-semi-structured-functions/json-path-query-first.md
docs/doc/15-sql-functions/110-semi-structured-functions/json-path-query.md
docs/doc/15-sql-functions/110-semi-structured-functions/object-keys.md
docs/doc/15-sql-functions/110-semi-structured-functions/parse-json.md

… func
* JSON_PATH_QUERY: Get all JSON items returned by JSON path for the specified JSON value.
* JSON_PATH_QUERY_ARRAY: Get all JSON items returned by JSON path for the specified JSON value and wrap a result into an array.
* JSON_PATH_QUERY_FIRST: Get the first JSON item returned by JSON path for the specified JSON value. 
Closes #issue

docs: add json_path_query

---

.github/actions/artifact_failure/action.yml
.github/actions/test_stateful_cluster_linux/action.yml
.github/actions/test_stateful_standalone_linux/action.yml
.github/workflows/dev-linux.yml
.github/workflows/production.yml
.github/workflows/trusted-benchmark.yml
benchmark/clickbench/hits/analyze.sql

ci: gather docker logs on upload failure

---

Cargo.lock
src/common/openai/Cargo.toml
src/common/openai/src/completion.rs
src/common/openai/src/embedding.rs

* add openai request timeout from 30s to 120s
* reduce the completion max token length from 1024 to 800
Closes #issue

chore: add openai http request timeout

---

Cargo.lock

fix: Fix OSS query sign with security token

fix: Fix OSS query sign with security token

---

src/query/storages/common/table-meta/src/meta/v1/segment.rs
src/query/storages/common/table-meta/src/meta/v1/snapshot.rs
src/query/storages/common/table-meta/src/meta/v1/table_snapshot_statistics.rs
src/query/storages/common/table-meta/src/meta/v2/segment.rs
src/query/storages/common/table-meta/src/meta/v2/snapshot.rs
src/query/storages/common/table-meta/src/meta/v3/segment.rs
src/query/storages/common/table-meta/src/meta/v3/snapshot.rs
src/query/storages/fuse/src/io/write/meta_writer.rs
src/query/storages/fuse/src/operations/read/fuse_row_fetcher.rs

as suggest by @zhyass (and @sundy-li @jun0315 )
https://github.com/datafuselabs/databend/pull/11015#discussion_r1171167453
we should consider allowing the value of `format_version` to be different from the Version number of the given table meta type.
let's take the current version of SegmentInfo for example:
~~~
impl Versioned<3> for v3::SegmentInfo {}
~~~
we allow that  a instance of  v3::SegementInfo `v3_seg: v3::SegmentInfo`,  has a value 2  `format_version` field. which indicates that this instance is converted from `v2::SegmentInfo`.
for the writing part, to ensure that only the current version of table meta are used:
or put it more specific way,  if `vn::SegemntInfo` is being persistent to …

refactor: table meta format_version

---

src/query/storages/common/table-meta/src/meta/v3/snapshot.rs
src/query/storages/fuse/src/operations/read/fuse_row_fetcher.rs
src/query/storages/fuse/src/operations/read_partitions.rs
src/query/storages/fuse/src/pruning/fuse_pruner.rs
src/query/storages/fuse/src/pruning/pruner_location.rs

- the map `build_segment_id_map` returns should contain format ver
i.e. instead of `HashMap<String, usize>`, we should use `HashMap<Location, usize>`
- `TransformRowsFetcher` should use the format version of segment to load the segment, not the version of the snapshot
- some minor refactor (avoid unnecessary cloning)
Closes #issue

fix:  the map `build_segment_id_map returns` should contain format ver

---

tests/fuse-compat/compat-logictest/01_meta_compression/fuse_compat_write
tests/fuse-compat/compat-stateless/01_flashback/01_0001_across_versions.result
tests/fuse-compat/compat-stateless/01_flashback/01_0001_across_versions.sh

- more fuse compact test cases
- test cases for issue #11204 
which verifies that table of old table metadata, after compaction, the history showed by `fuse_snapshot` is correct, and can be flashedback to. 
Closes #issue

chore: more  test cases of fuse compat

---

src/query/service/tests/it/storages/fuse/operations/analyze.rs
src/query/service/tests/it/storages/fuse/operations/optimize.rs
src/query/service/tests/it/storages/fuse/utils.rs
src/query/storages/fuse/src/operations/navigate.rs

fix: fix purge test bugs
bug reason: in function `navigate_for_purge` use `snapshot.timestamp` as purge timestamp, but in `list_files` use `last_modified` time to get file list, `last_modified` sometimes may bigger than `snapshot.timestamp`, so some files be ignored.
use `do_purge`  instead of sql.
Closes #issue

fix: fix purge test bugs

---

src/query/catalog/src/plan/pushdown.rs
src/query/sql/src/planner/binder/bind_context.rs
src/query/sql/src/planner/binder/scalar.rs
src/query/sql/src/planner/binder/select.rs
src/query/sql/src/planner/binder/setting.rs
src/query/sql/src/planner/binder/sort.rs
src/query/sql/src/planner/binder/table.rs
src/query/sql/src/planner/expression_parser.rs
src/query/sql/src/planner/semantic/type_check.rs
tests/sqllogictests/suites/base/03_common/03_0004_select_order_by_db_table_col

1. Refactor: simplify the logic of `analyze_order_items`.
2. Improvement: If a select item is the same with an order by item, their indices allocated by the binder will be the same.
The point 2. brings two benefits:
1. A simple common expression elimination
```sql
-- this PR:
mysql> explain select salary+1 as a from empsalary order by salary+1;
+------------------------------------------------------------------------------------------------------------------------------+
| explain                                                                                                                      |
+------------------------------------------------------------------------------------------------------- …
```

refactor: refactor order by clause analyzing and binding.

---

.github/mergify.yml
.github/workflows/dev-linux.yml

chore(ci): use larger runner for build aarch64 musl

---

src/query/storages/parquet/src/parquet_part.rs
src/query/storages/parquet/src/parquet_reader/deserialize.rs
src/query/storages/parquet/src/pruning.rs
tests/sqllogictests/suites/base/03_common/03_0040_parquet_list_field

for List Type,  `num_values` of a leaf column may be larger then num_rows.
page reader currently use `num_values` to decide whether all pages is readn.
this bug may lead to some pages not read, and result in less rows in this column than others and report error.
see: 
https://github.com/jorgecarleitao/parquet2/blob/main/src/read/page/reader.rs#L53
https://github.com/jorgecarleitao/parquet2/blob/main/src/read/page/reader.rs#L179
Closes #issue

fix: page reader should use num_values of chunk.

---

Cargo.lock
src/common/exception/src/exception_code.rs
src/common/license/Cargo.toml
src/common/license/src/license.rs
src/common/license/src/license_manager.rs
src/query/ee/Cargo.toml
src/query/ee/src/license/license_mgr.rs
src/query/ee/tests/it/license/license_mgr.rs
src/query/ee/tests/it/license/mod.rs
src/query/ee/tests/it/main.rs

feat: add license parsing function

---

src/query/service/tests/it/storages/fuse/operations/truncate.rs
src/query/storages/fuse/src/io/files.rs
src/query/storages/fuse/src/operations/commit.rs
src/query/storages/fuse/src/operations/fuse_sink.rs
src/query/storages/fuse/src/operations/truncate.rs

truncate should commit the new meta to meta-server first.
the principle should be: 
publish the new meta first, let the effects of `truncate` be visible to all the subsequent  txs (and parallel txs while committing), and purge the data later(in a best-effort manner) if the `purge` option is specified.
also, please consider removing the `purge` option from `truncate`, since
- it is not a safe operation, there is NO retention interval protection here
- it is somehow incompatible with time travel features
Closes #issue

fix: truncate should commit new meta to meta-server first

---

src/query/sql/src/planner/planner.rs

fix(planner): remove obsolete EOI token in insert probing

---

src/query/service/src/pipelines/processors/transforms/transform_hash_join.rs
tests/sqllogictests/suites/query/join.test

By limiting the size of the blocks processed by each probe thread, make the whole pipeline flow better and reduce the time of hash join blocking.
Closes #issue

feat: optimize join by reducing blocking at probe phase

---

src/query/storages/fuse/src/fuse_table.rs
src/query/storages/fuse/src/operations/commit.rs
src/query/storages/fuse/src/operations/truncate.rs
src/query/storages/fuse/src/table_functions/fuse_blocks/fuse_block.rs
src/query/storages/fuse/src/table_functions/fuse_segments/fuse_segment.rs

chore: refactor snapshot_format_version function, fix possible snapshot version missmatch bug
for shared-table, 
- the snapshot location and format version can not be determined at the time of construction (due to we do not support async table constructor yet).
- the method `Table::snapshot_loc` will read the table snapshot location from hint file **for each invocation**
- `snapshot_format_version` uses `snapshot_loc` method to get the location of snapshot, and parse the format version
- thus `read_table_snapshot` is taking the following risk
https://github.com/datafuselabs/databend/blob/aa97d2c5b57f1585abc8192e5fb76f9fc4157903/src/query/storages/fuse/src/fuse_table.rs#L252-L278
the `loc` we get at …

chore: refactor snapshot_format_version function, fix possible snapshot version missmatch bug

---

src/query/catalog/src/table_context.rs
src/query/service/src/interpreters/interpreter.rs
src/query/service/src/interpreters/interpreter_table_recluster.rs
src/query/service/src/interpreters/interpreter_user_stage_remove.rs
src/query/service/src/pipelines/executor/pipeline_executor.rs
src/query/service/src/sessions/query_ctx.rs
src/query/service/src/sessions/query_ctx_shared.rs
src/query/service/src/stream/table_read_block_stream.rs
src/query/service/src/test_kits/table_test_fixture.rs
src/query/service/tests/it/storages/fuse/operations/commit.rs
src/query/service/tests/it/storages/fuse/operations/mutation/block_compact_mutator.rs
src/query/service/tests/it/storages/fuse/operations/mutation/deletion.rs

before this pr,  query can only be killed after pipeline is started(` ctx.set_executor()`).
it will be better if long  binding/read_parttiion can be interrupted, which needs another pr.  
Closes  https://github.com/datafuselabs/databend/issues/11302

fix: enable kill query before pipeline started.

---

src/common/base/src/future.rs
src/common/base/src/lib.rs
src/meta/client/src/grpc_client.rs

Add a `TimingFuture` that wraps a future with spent time tracking.
To track the spent time for a future `fu`:
Replace `fu.await` with: `fu.timed(callback).await`
Or invoke callback if `fu` spends more than 200 ms with
`fu.timed_ge(Duration::from_millis(200), callback).await`

feat(meta): track the time spent on meta client methods

---

Cargo.lock
Cargo.toml
src/common/storage/src/metrics.rs
src/common/storage/src/runtime_layer.rs
src/query/service/tests/it/sessions/query_ctx.rs

This PR will bump opendal to 0.34.0.
Release Note: https://github.com/apache/incubator-opendal/releases/tag/v0.34.0
Notable Changes:
- Fix S3's retry logic for credential not loaded
- Improve the memory/moka backend's perf up to 160000%

feat: Bump OpenDAL to 0.34.0

---

src/meta/api/src/schema_api_impl.rs
src/meta/api/src/schema_api_test_suite.rs
src/meta/app/src/schema/table.rs
src/meta/client/src/lib.rs
src/query/service/src/interpreters/interpreter_copy.rs

`UpsertTableCopiedFileReq` is a sub-compoenent of `UpdateTableMetaReq`
and do not need `table_id`

refactor(meta): remove UpsertTableCopiedFileReq.table_id

---

Cargo.lock
Cargo.toml
src/meta/service/src/store/store.rs
src/meta/types/src/raft_types.rs
tests/sqllogictests/Cargo.toml

- Fix: replication should be able to shutdown when replicating snapshot to unreachable node.
- Feature: new RaftNetwork API with argument RCPOption.
- Feature: add `RaftMetrics.vote`, `Wait::vote()`.
- Feature: add Wait::purged() to wait for purged to become the expected.
- Feature: add RaftMetrics::purged to report the last purged log id.
- Feature: add backoff strategy for unreachable nodes.
- Improve: build snapshot in anohter task.
- Improve: Better performance with two channel: `256 clients, 3 node: 1 million rps`.
If a replication is sending a snapshot, it should
periodically verify the input channel's status. When the input channel
is closed during replication rebuilding, it should …

fix(meta): upgrade openraft to 0.8.4-alpha.3; bug fix, improve performance, etc

---

src/query/storages/system/src/catalogs_table.rs
src/query/storages/system/src/columns_table.rs
src/query/storages/system/src/databases_table.rs
src/query/storages/system/src/engines_table.rs
src/query/storages/system/src/functions_table.rs
src/query/storages/system/src/query_cache_table.rs
src/query/storages/system/src/roles_table.rs
src/query/storages/system/src/stages_table.rs
src/query/storages/system/src/table.rs
src/query/storages/system/src/tables_table.rs
src/query/storages/system/src/users_table.rs
tests/sqllogictests/suites/base/01_system/01_0006_system_columns

If query `system.columns` with push down filter Expr FunctionCall eq
and the eq arg has column name 'table' like this:
```
where table='tb1' and table='tb2' and table='tb3' and table = 'tb4'
```
will only get these tables.
BTW, not use field database and Expr or as filter. Because there maybe have some bad case:
```
where database='db1' or table='db2_tb1'
where database='db1' and table='db1_tb1' or table='db2_tb1'
```
Closes #https://github.com/datafuselabs/databend/issues/11355

feat(query): Optimize read system.columns data

---

tests/suites/5_ee/01_vacuum/01_0001_ee_vacuum_kill_randomly.result
tests/suites/5_ee/01_vacuum/01_0001_ee_vacuum_kill_randomly.sh
tests/suites/5_ee/01_vacuum/insert_vacuum_table_values

chore: add kill query randomly vacuum table test
Closes #issue

chore: add kill query randomly vacuum table test

---

src/query/service/src/servers/http/v1/query/http_query.rs
src/query/service/src/servers/http/v1/query/page_manager.rs

there is an extra instance of ctx to avoid dropping runtime when task on it is running,
this is solved better in https://github.com/datafuselabs/databend/pull/10501, so not need it any more.
Closes https://github.com/datafuselabs/databend/issues/11359

chore: http handler release context/session earlier.

---

src/query/storages/fuse/src/io/segments.rs
src/query/storages/fuse/src/operations/analyze.rs
src/query/storages/fuse/src/operations/commit.rs
src/query/storages/fuse/src/operations/gc.rs
src/query/storages/fuse/src/operations/merge_into/mutator/mutation_accumulator.rs
src/query/storages/fuse/src/operations/merge_into/processors/sink_commit.rs
src/query/storages/fuse/src/operations/mutation/compact/block_compact_mutator.rs
src/query/storages/fuse/src/operations/mutation/compact/segment_compact_mutator.rs
src/query/storages/fuse/src/table_functions/clustering_information/clustering_information.rs
src/query/storages/fuse/src/table_functions/fuse_blocks/fuse_block.rs
src/query/storages/fuse/src/table_functions/fuse_segments/fuse_segment.rs

Simple read segments
Closes #issue

chore: simple read segments

---

src/query/sql/src/planner/optimizer/rule/rewrite/rule_fold_count_aggregate.rs
src/query/sql/src/planner/optimizer/rule/rewrite/rule_normalize_disjunctive_filter.rs
src/query/sql/src/planner/optimizer/rule/transform/rule_eager_aggregation.rs

chore(planner): do not use data type in optimizer

---

src/query/functions/src/scalars/datetime.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
src/query/service/src/servers/http/clickhouse_handler.rs
tests/sqllogictests/suites/query/02_function/02_0012_function_datetimes

support function:
date_format(Timestamp, String) :: String NULL
date_format(Timestamp NULL, String NULL) :: String NULL
str_to_date(String, String) :: Date NULL
str_to_date(String NULL, String NULL) :: Date NULL
str_to_timestamp(String, String) :: Timestamp NULL
str_to_timestamp(String NULL, String NULL) :: Timestamp NULL
* If use str_to_timestamp , the string must contains timezone. Because we need to unique date and time. If not contains timezone will return null.
Closes #11125

feat(query): add func date_format and str_to_date and str_to_timestamp

---

src/query/ee/tests/it/storages/fuse/operations/vacuum.rs
tests/suites/5_ee/01_vacuum/01_0001_ee_vacuum_kill_randomly.sh

chore: add more vacuum table test
1. after enough time, all the orphan file which out of retention time will be purged; 
2. use a random sleep time in kill query vacuum tets.
Closes #issue

chore: add more vacuum table test

---

src/query/functions/src/scalars/datetime.rs
src/query/functions/tests/it/scalars/testdata/function_list.txt
tests/sqllogictests/suites/query/02_function/02_0012_function_datetimes

1. rename func name to_date, to_timestamp, add alias str_to_date, str_to_timestamp
2. return throw err
REF: https://github.com/datafuselabs/databend/pull/11442#discussion_r1193236422

feat(query): make date_format throw err

---

docs/doc/100-faq/10-how-to-get-server-logs.md
docs/doc/100-faq/20-how-to-tracing.md

added note: Databend uses [tokio-tracing](https://github.com/tokio-rs/tracing) to trace logs, where the default timezone is UTC and cannot be changed through the Databend timezone setting, therefore the time in the traced log will always be in UTC, and not reflect your local time.
Closes #11461

docs: utc timezone for logs

---

.github/workflows/bindings_python.yml

Actually we are not able to build from source, since most packages are not published to `crates.io`
Closes #issue

ci: do not release source for python binding [skip ci]

---

src/query/sql/src/planner/optimizer/property/enforcer.rs

If the child is join build side and join type is broadcast join, we should wrap the child with Broadcast exchange to make it available to all nodes.
Closes #issue

chore(planner): fix a bug in require_property

---

src/query/sql/src/planner/binder/project_set.rs
tests/sqllogictests/suites/query/02_function/02_0051_function_semi_structureds_get
tests/sqllogictests/suites/query/02_function/02_0062_function_unnest

fix SRF as arg of other function
Closes #11474

fix(query): fix SRF as arg of other function

---

src/query/settings/src/settings_getter_setter.rs

I got an error message like this when proxying to a databend intance:
```
time="2023-05-16T05:04:58Z" level=info msg="wrappedResponseWriter.Write: {\"error\":{\"code\":\"401\",\"message\":\"Value must be greater than 0\"}}"
```
after investigation, i found this error comes from:
https://github.com/datafuselabs/databend/blob/14871e27bf449c97277bb15dcc949e6281631610/src/query/settings/src/settings_getter_setter.rs#L130
i hope this pr may makes the error message more clear about what actually happens.

chore: tune the error message on setting max_storage_io_requests

---

src/query/storages/system/src/columns_table.rs
src/query/storages/system/src/lib.rs
src/query/storages/system/src/tables_table.rs
src/query/storages/system/src/util.rs

optimize show tables with pushdown filter only contain eq database
```
select count() from system.tables;
+---------+
| count() |
+---------+
|    4082 |
+---------+
1 row in set (0.509 sec)
MySQL [(none)]> show tables from a;
| tables_in_a |
| a           |
1 row in set (0.043 sec)
MySQL [(none)]> show tables from tpch;
+----------------+
| tables_in_tpch |
+----------------+
| customer       |
| lineitem       |
| nation         |
| orders         |
| part           |
| partsupp       |
| region         |
| supplier       |
+----------------+
8 rows in set (0.045 sec)
```
Closes #issue

feat(query): optimize show tables with pushdown filter only contain eq database

---

src/query/sql/src/planner/binder/ddl/database.rs
src/query/sql/src/planner/binder/ddl/table.rs
tests/sqllogictests/suites/base/06_show/06_0004_show_tables
tests/suites/0_stateless/14_clickhouse_http_handler/14_0001_clickhouse_http.result

show tables and show databases will be rewrite to select query.
If db name or catalog name have special name will cause parser err.
```
MySQL [rust-lang]> use rust-lang
Database changed
MySQL [rust-lang]> show tables;
ERROR 1105 (HY000): Code: 1005, Text = error: 
--> SQL:1:30
|
1 | SELECT name AS Tables_in_rust-lang FROM system.tables where database = 'rust-lang' ORDER BY catalog,database,name 
|                              ^ expected `,`, `FROM`, `WHERE`, `GROUP`, `HAVING`, `WINDOW`, or 12 more ...
```
need rewrite to 
```
SELECT name AS `Tables_in_rust-lang` FROM system.tables where database = 'rust-lang' ORDER BY catalog,database,name ;
```
Closes #11496

fix(query): fix show err with special name
