- .github/workflows/FuseQuery-Docker.yml
Must add some secrets vars in Settings: https://github.com/datafusedev/fuse-query/settings
- DOCKERHUB_USERNAME
- DOCKERHUB_TOKEN https://hub.docker.com/settings/security
- DOCKERHUB_NAMESPACE=datafusedev
only build with `master` branch
> [docker] add docker-build action

- src/contexts/options.rs
- src/servers/mysql/mysql_handler.rs
> [option]: add mysql_handler_thread_num

- src/datavalues/data_array_arithmetic.rs
- src/datavalues/data_type.rs
- src/datavalues/data_value_arithmetic.rs
- src/datavalues/data_value_operator.rs
- src/datavalues/macros.rs
- src/functions/arithmetics/arithmetic.rs
- src/functions/arithmetics/arithmetic_modulo.rs
- src/functions/arithmetics/arithmetic_test.rs
- src/functions/arithmetics/mod.rs
Support arithmetic operator modulo. 
```
mysql> select  10%3; 
+---------------+
| modulo(10, 3) |
+---------------+
|             1 |
+---------------+
```
> [functions] Add arithmetic operator modulo

- build.rs
- src/bin/fuse-query.rs
> [build] add git version to release target

- src/optimizers/optimizer_filter_push_down.rs
- src/planners/mod.rs
- src/planners/plan_aggregator_final.rs
- src/planners/plan_aggregator_partial.rs
- src/planners/plan_explain.rs
- src/planners/plan_filter.rs
- src/planners/plan_limit.rs
- src/planners/plan_node.rs
- src/planners/plan_projection.rs
- src/planners/plan_select.rs
- src/planners/plan_stage.rs
- src/planners/plan_walker.rs
- src/planners/plan_walker_test.rs
- src/processors/pipeline_builder.rs
This PR:
TODO:
Plan display will be rewritten in another patch using the new walk
Releated issue: #77
> New plan visitor part 1

- src/processors/macros.rs
- src/processors/mod.rs
- src/processors/pipe.rs
- src/processors/pipe_test.rs
- src/processors/pipeline.rs
- src/processors/pipeline_builder.rs
- src/processors/pipeline_display.rs
- src/processors/pipeline_walker.rs
- src/processors/pipeline_walker_test.rs
This patch including:
Add pipe for pipeline
Add downcast match for processor trait
> Add pipe for pipeline

- Makefile
- docs/development/coding-guidelines.md
- scripts/dev_codecov.sh
- scripts/dev_setup.sh
Add make coverage to view the html code coverage report.
No.
> [CI] add make coverage

- README.md
- docs/development/contributing.md
- docs/overview/building-and-running.md
> [docs] datafusedev -> datafuselabs

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/FuseQuery-Build.yml
- .github/workflows/FuseQuery-Coverage.yml
- .github/workflows/FuseQuery-Daily.yml
- .github/workflows/FuseQuery-Docker.yml
- .github/workflows/FuseQuery-Lint.yml
- .github/workflows/FuseQuery-Release.yml
- .github/workflows/FuseQuery-Tests.yml
- scripts/dev_codecov.sh
- scripts/dev_setup.sh
> [CI] add daily actions

- .github/workflows/FuseQuery-Coverage.yml
- .github/workflows/FuseQuery-Daily.yml
> try to fix the daily yml

- README.md
> [README] update ci badge

- .github/workflows/fusequery-unit-tests.yml
- scripts/dev_setup.sh
> [CI] remove grcov action

- .github/workflows/fusequery-unit-tests.yml
- New Feature
- Bug Fix
- Improvement
- Other
> [CI] revert coverage

- src/rpcs/rpc/executor/executor_service_test.rs
- src/rpcs/rpc/executor/mod.rs
> [executor] add test

- src/rpcs/rpc/executor/executor_service_test.rs
> [rpcs] fix up executor test

- src/error.rs
- src/processors/processor_merge.rs
- src/rpcs/rpc/flight_service.rs
- New Feature
Add stream fetch for do_get flight service
Unit Test
> [rpcs] add distributed query PART-2

- src/rpcs/rpc/flight_service.rs
- Improvement
Remove unused functions from flight service
None
> [rpcs] add distributed query PART-2-1

- .github/workflows/fusequery-unit-tests.yml
- scripts/dev_setup.sh
1. Add [miri check](https://github.com/rust-lang/miri) to detect the [ub](https://doc.rust-lang.org/reference/behavior-considered-undefined.html)
2. Add usage to dev_setup.sh
> [workflow] add usage to dev_setup.sh

- Cargo.toml
- src/bin/fuse-query.rs
Exit when the fuse-query panic
- Bug Fix
> [bin] fix fuse-query exit when panic

- README.md
> [README] Better README

- README.md
> Add slack invite link

- .github/PULL_REQUEST_TEMPLATE.md
> [.github] Update the pull request template

- src/executors/executor.rs
- src/executors/mod.rs
- src/executors/scheduler.rs
- src/lib.rs
> [executors] Remove executors

- .github/workflows/fusequery-unit-tests.yml
- scripts/dev_setup.sh
> [CI] Fix upload grcov

- .github/workflows/fusequery-unit-tests.yml
- Cargo.toml
Upgrade arrow version to latest.
- Other
None
> Upgrade arrow version

- .github/workflows/fusequery-lint.yml
- src/datasources/datasource.rs
- src/datasources/system/functions_table.rs
- src/datasources/system/mod.rs
- src/datasources/system/numbers_table.rs
- src/datasources/system/settings_table.rs
- src/datasources/system/system_factory.rs
- src/datasources/system/tables_table.rs
- src/datasources/system/tables_table_test.rs
- src/datasources/table.rs
- src/sessions/context.rs
- src/sql/plan_parser.rs
- tests/queries/0_stateless/00010_system_tables.reference
- tests/queries/0_stateless/00010_system_tables.sql
> [datasources] add system.tables engine

- src/planners/plan_scheduler.rs
- src/planners/plan_scheduler_test.rs
- src/processors/pipeline_builder_test.rs
- src/transforms/transform_remote_test.rs
Align distributed partitions with cluster number
- Improvement
#53 
UnitTest
> Align distributed partitions with cluster number

- src/datasources/system/clusters_table.rs
- src/datasources/system/clusters_table_test.rs
- src/datasources/system/mod.rs
- src/datasources/system/system_factory.rs
Add system.clusters table:
```
mysql> select * from system.clusters;
+------+----------------+------+
| name | address        | cpus |
+------+----------------+------+
| 9090 | 127.0.0.1:9090 |    8 |
+------+----------------+------+
```
- New Feature
#149 
Unit Test
> Add system.clusters table

- src/rpcs/rpc/flight_client.rs
- src/rpcs/rpc/flight_service.rs
- src/rpcs/rpc/macros.rs
Better the flight rpc map_err
- Improvement
> Better flight rpc map_err

- README.md
* Add more SQL status
* Add more Gerneral status
- Improvement
> Update README status

- build.rs
- proto/executor.proto
- proto/executor_flight.proto
- proto/fusestore.proto
- proto/fusestore_flight.proto
- src/error.rs
- src/lib.rs
- src/rpcs/rpc/error.rs
- src/rpcs/rpc/executor_service.rs
- src/rpcs/rpc/flight_client.rs
- src/rpcs/rpc/flight_service.rs
- src/rpcs/rpc/macros.rs
- src/rpcs/rpc/mod.rs
* Better flight rpc error
* Move flight to executor_flight
* Add FuseStore proto files
- Improvement
> Better rpc and errors

- build.rs
- proto/executor.proto
- proto/executor_flight.proto
- proto/fusestore.proto
- proto/fusestore_flight.proto
- src/error.rs
- src/lib.rs
- src/rpcs/rpc/error.rs
- src/rpcs/rpc/executor_service.rs
- src/rpcs/rpc/flight_client.rs
- src/rpcs/rpc/flight_service.rs
- src/rpcs/rpc/macros.rs
- src/rpcs/rpc/mod.rs
> Work-stealing scheduler

- Cargo.toml
- proto/executor.proto
- proto/executor_flight.proto
- proto/fusestore.proto
- proto/fusestore_flight.proto
- src/clusters/cluster.rs
- src/clusters/cluster_test.rs
- src/clusters/node.rs
- src/datasources/partition.rs
- src/lib.rs
- src/planners/plan_scheduler_test.rs
- src/processors/pipeline_builder_test.rs
- src/rpcs/http/v1/cluster.rs
- src/rpcs/http/v1/cluster_test.rs
- src/rpcs/rpc/executor_client.rs
- src/rpcs/rpc/executor_service.rs
- src/rpcs/rpc/executor_service_test.rs
- src/rpcs/rpc/mod.rs
- src/rpcs/rpc_service.rs
- src/sessions/context.rs
- src/sessions/session.rs
- src/tests/mod.rs
- src/tests/service.rs
> work-stealing for distributed query execution

- docs/store/store-v1.md
Design of single-node storage
Fix #171 
> [store/doc] v1: single-node storage design

- docs/overview/building-and-running.md
Change the commands of how to run fuse-query
> fix commands in building-and-running.md

- fusequery/query/src/clusters/cluster.rs
- fusequery/query/src/clusters/cluster_test.rs
- fusequery/query/src/clusters/node.rs
- fusequery/query/src/planners/plan_scheduler.rs
- fusequery/query/src/planners/plan_scheduler_test.rs
- fusequery/query/src/rpcs/http/v1/cluster.rs
- fusequery/query/src/rpcs/http/v1/cluster_test.rs
- fusequery/query/src/tests/mod.rs
- fusequery/query/src/tests/service.rs
Add priority to node definition and use priority to distribute work
- New Feature
> implement node priority and distribute partition proportionally

- .github/workflows/fusequery-unit-tests.yml
- fusequery/query/src/sessions/context.rs
- scripts/dev_setup.sh
* Work stealing not work well(it will hang the cluster executing), so remove it temporarily
* Fix grcov install failed(disable) in dev_setup.sh
- Improvement
#189 
N/A
> Remove work stealing

- .gitignore
- Cargo.lock
- README.md
- common/planners/Cargo.toml
- common/planners/src/plan_read_datasource.rs
- common/planners/src/plan_walker.rs
- common/planners/src/plan_walker_test.rs
- fusequery/example/cluster.sh
- fusequery/query/Cargo.toml
- fusequery/query/src/configs/config.rs
- fusequery/query/src/error.rs
- fusequery/query/src/planners/plan_scheduler.rs
- fusequery/query/src/processors/pipeline_builder.rs
- fusequery/query/src/rpcs/rpc/flight_service.rs
- fusequery/query/src/transforms/transform_aggregator_final.rs
- fusequery/query/src/transforms/transform_aggregator_partial.rs
* Remove anyhow error
* Add log info to executor
- Improvement
N/A
N/A
> Better error and log

- common/datavalues/src/data_type.rs
- fusequery/query/src/api/rpc/flight_service.rs
- fusequery/query/src/datasources/local/csv_table.rs
- fusequery/query/src/datasources/system/numbers_stream.rs
- fusequery/query/src/servers/mysql/mysql_stream.rs
* Change unwrap to  return result
- Improvement
N/A
N/A
> Remove unwrap

- Cargo.lock
- fusequery/query/Cargo.toml
* Removed unused depends in fusequery
* 
- Improvement
N/A
N/A
> Remove unused depends

- common/functions/src/aggregators/aggregator.rs
- common/functions/src/arithmetics/arithmetic.rs
- common/functions/src/comparisons/comparison.rs
- common/functions/src/function_factory.rs
- common/functions/src/logics/logic.rs
- common/functions/src/udfs/udf.rs
- common/infallible/src/lib.rs
- common/infallible/src/rwlock.rs
- common/infallible/src/rwlock_test.rs
- fusequery/query/src/datasources/local/csv_table.rs
- fusequery/query/src/datasources/local/null_table.rs
- fusequery/query/src/datasources/local/parquet_table.rs
- fusequery/query/src/datasources/system/tables_table.rs
- fusequery/query/src/datasources/table_factory.rs
- fusequery/query/src/interpreters/interpreter_create.rs
- fusequery/query/src/sessions/context.rs
- fusequery/query/src/sessions/session.rs
- fusequery/query/src/sessions/settings.rs
* Change Mutext to RwLock
* 
- Improvement
N/A
Unit  Tests
> Mutex -> RwLock

- README.md
> Upadte README

- common/functions/src/aggregators/aggregator_avg.rs
- common/functions/src/aggregators/aggregator_count.rs
- common/functions/src/aggregators/aggregator_max.rs
- common/functions/src/aggregators/aggregator_min.rs
- common/functions/src/aggregators/aggregator_sum.rs
- common/functions/src/aggregators/aggregator_test.rs
- common/functions/src/comparisons/comparison.rs
- common/functions/src/comparisons/comparison_test.rs
- common/functions/src/function.rs
- common/functions/src/function_column.rs
- common/functions/src/function_literal.rs
- common/functions/src/logics/logic.rs
- common/functions/src/udfs/to_type_name.rs
- common/functions/src/udfs/udf_example.rs
- fusequery/query/src/pipelines/transforms/transform_aggregator_test.rs
Impl group by.
* Improve the function trait
* Change the aggregator name to lower case
- New Feature
#5 
Unit Tests
> Group By Patch-1

- README.md
- fusequery/query/src/optimizers/optimizer_limit_push_down.rs
* Change unwrap to result return
- Improvement
N/A
Unit Tests
> [query/optimizers] fix unwrap to result return

- common/planners/src/plan_aggregator_test.rs
- common/planners/src/plan_display.rs
- common/planners/src/plan_explain_test.rs
- common/planners/src/plan_expression_test.rs
- common/planners/src/plan_filter_test.rs
- common/planners/src/plan_stage_test.rs
- fusequery/query/src/optimizers/optimizer_filter_push_down_test.rs
- fusequery/query/src/optimizers/optimizer_limit_push_down_test.rs
- fusequery/query/src/pipelines/transforms/transform_remote_test.rs
- fusequery/query/src/planners/plan_scheduler_test.rs
* Add schema display to ReadSourcePlan
- New Feature
#223 
Unit Tests
> Add schema display to ReadSource plan

- fusequery/query/src/bin/fuse-query.rs
* Add panic to tokio:spawn
* 
- Bug Fix
N/A
N/A
> Add error panic to tokio:spawn

- common/planners/src/lib.rs
- common/planners/src/plan_display.rs
- common/planners/src/plan_display_test.rs
> [common/planner] impl Display for CreateTable plan

- common/planners/src/plan_display.rs
- common/planners/src/plan_display_test.rs
- common/planners/src/plan_node.rs
- fusequery/query/src/interpreters/interpreter_create_table.rs
- fusequery/query/src/interpreters/interpreter_create_table_test.rs
- fusequery/query/src/interpreters/interpreter_factory.rs
- fusequery/query/src/interpreters/mod.rs
- fusequery/query/src/sql/plan_parser.rs
* Rename create to create_table
- Improvement
N/A
Unit Tests
> Rename create to create_table

- common/planners/src/plan_create_database.rs
- fusequery/query/src/interpreters/interpreter_create_database.rs
- fusequery/query/src/sql/plan_parser.rs
- fusestore/store/src/api/rpc/flight_service.rs
- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/api/rpc/mod.rs
- fusestore/store/src/lib.rs
- fusestore/store/src/tests/flight_client.rs
- fusestore/store/src/tests/mod.rs
- fusestore/store/src/tests/service.rs
Add store api test and fix metadata missing
#239 
Unit Tests
> Add store api test and fix metadata missing

- fusequery/query/src/configs/config.rs
- fusequery/query/src/datasources/datasource.rs
- fusequery/query/src/datasources/remote/remote_database.rs
- fusequery/query/src/rpcs/store/store_client.rs
- fusestore/store/src/api/rpc/flight_client.rs
- fusestore/store/src/api/rpc/flight_service.rs
- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/api/rpc/mod.rs
- fusestore/store/src/tests/mod.rs
- fusestore/store/src/tests/service.rs
* Add handshake impl between server and client
- New Feature
#261 
Unit Tests
> Support bearer token for flight RPC 

- common/planners/src/lib.rs
- common/planners/src/plan_scan_test.rs
add unit test for plan_scan.rs
- Testing
#220
> add unit test for plan_scan.rs

- Cargo.lock
- fusestore/store/Cargo.toml
- fusestore/store/build.rs
- fusestore/store/src/api/README.md
- fusestore/store/src/api/rpc/flight_service.rs
- fusestore/store/src/api/rpc/mod.rs
- fusestore/store/src/api/rpc_service.rs
- fusestore/store/src/engine/mem_engine.rs
- fusestore/store/src/engine/mem_engine_test.rs
- fusestore/store/src/engine/mod.rs
- fusestore/store/src/lib.rs
- proto/store_meta.proto
in-memory storage engine
- New Feature
> [store] in-memory storage engine

- .github/workflows/unit-tests.yml
Code grcov only run on master branch
N/A
N/A
> Code grcov only run on master branch

- common/flights/src/store_do_action.rs
- fusestore/store/src/api/rpc/flight_service.rs
Add read plan action for flight
- New Feature
N/A
Unit Tests
> Add read plan action for flight

- charts/README.md
- docs/overview/building-and-running.md
> Add README to charts

- Cargo.lock
- common/flights/Cargo.toml
- common/flights/src/lib.rs
- common/flights/src/store_client.rs
- common/flights/src/store_do_action.rs
- common/flights/src/util.rs
- fusequery/query/src/datasources/datasource.rs
- fusestore/store/src/api/rpc/flight_service.rs
- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/engine/mod.rs
> [store] impl store-client:create-database, send plan and write meta to store

- common/datavalues/src/data_value.rs
- common/functions/src/function.rs
- fusequery/query/src/pipelines/transforms/transform_aggregator_final.rs
- fusequery/query/src/pipelines/transforms/transform_aggregator_partial.rs
Change partitial result block from vector to columns
- Improvement
#5 
Unit Tests
> Change partitial result block from vector to columns

- Cargo.lock
- common/arrow/Cargo.toml
- common/functions/src/lib.rs
- common/planners/src/lib.rs
- common/streams/src/lib.rs
- fusequery/query/src/lib.rs
- fusequery/query/src/pipelines/processors/pipeline_builder.rs
- fusequery/query/src/pipelines/transforms/mod.rs
- fusequery/query/src/pipelines/transforms/transform_expression.rs
- fusequery/query/src/pipelines/transforms/transform_expression_test.rs
- fusequery/query/src/pipelines/transforms/transform_projection.rs
- fusequery/query/src/pipelines/transforms/transform_projection_test.rs
- fusequery/query/src/tests/macros.rs
- fusequery/query/src/tests/mod.rs
* Add expression transform certain for expression executing over block
* Add stream result check
- New Feature
N/A
Uint Tests
> Expression transform

- common/functions/src/aggregators/aggregator_avg.rs
- common/planners/src/lib.rs
- common/planners/src/plan_expression_function.rs
- fusequery/query/src/pipelines/transforms/mod.rs
- fusequery/query/src/pipelines/transforms/transform_aggregator_final_test.rs
- fusequery/query/src/pipelines/transforms/transform_aggregator_partial_test.rs
Add aggregator partial and final test
N/A
Unit Tests
> Add aggregator partial and final test

- common/datablocks/src/lib.rs
- common/datablocks/src/macros.rs
- fusequery/query/src/api/rpc/flight_service_test.rs
- fusequery/query/src/datasources/local/csv_table_test.rs
- fusequery/query/src/datasources/local/null_table_test.rs
- fusequery/query/src/datasources/system/clusters_table_test.rs
- fusequery/query/src/datasources/system/functions_table_test.rs
- fusequery/query/src/datasources/system/settings_table_test.rs
- fusequery/query/src/datasources/system/tables_table_test.rs
- fusequery/query/src/pipelines/processors/pipeline_builder.rs
- fusequery/query/src/pipelines/processors/processor_merge_test.rs
- fusequery/query/src/pipelines/transforms/transform_aggregator_final_test.rs
- fusequery/query/src/pipelines/transforms/transform_aggregator_partial_test.rs
- fusequery/query/src/pipelines/transforms/transform_expression.rs
- fusequery/query/src/pipelines/transforms/transform_expression_test.rs
- fusequery/query/src/pipelines/transforms/transform_filter_test.rs
- fusequery/query/src/pipelines/transforms/transform_limit_test.rs
- fusequery/query/src/pipelines/transforms/transform_projection.rs
- fusequery/query/src/pipelines/transforms/transform_projection_test.rs
- fusequery/query/src/pipelines/transforms/transform_remote_test.rs
- fusequery/query/src/pipelines/transforms/transform_source_test.rs
- fusequery/query/src/tests/macros.rs
* Move ExpressionTransform to ProjectionTransform internal
* Add stream result pretty assert for tests
- Improvement
N/A
Unit Tests
> Move ExpressionTransform to ProjectionTransform internal

- README.md
Minor docs change in the readme.
- Improvement
> minor docs change

- .github/workflows/contributors.yml
Add contributors bot
- New Feature
> Add contributors bot

- common/flights/src/lib.rs
- common/flights/src/store_client.rs
- common/flights/src/store_do_action.rs
- common/flights/src/util.rs
- fusestore/store/proto/store_meta.proto
- fusestore/store/src/api/rpc/flight_service.rs
- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/engine/mem_engine.rs
> [store] create-table: server and client side impl

- Makefile
- charts/datafuse/templates/NOTES.txt
- charts/datafuse/templates/configmap.yaml
- charts/datafuse/templates/deployment.yaml
- charts/datafuse/templates/service.yaml
- charts/datafuse/values.yaml
- docs/overview/building-and-running.md
helm enhancement
* enhance README and NOTE,
* make service port and env more configurable
- Improvement
https://github.com/datafuselabs/datafuse/pull/253
try `make runhelm`
> helm enhancement

- common/flights/src/store_client.rs
- fusestore/store/proto/store_meta.proto
- fusestore/store/src/api/rpc/flight_service.rs
- fusestore/store/src/engine/mem_engine.rs
- fusestore/store/src/engine/mem_engine_test.rs
Make life easier by extracting common codes.
- Refactor
> [store/flight] refactor: flight service communicates with meta store with Cmd

- fusestore/store/src/api/rpc/flight_service.rs
- fusestore/store/src/executor/action_handler.rs
- fusestore/store/src/executor/mod.rs
- fusestore/store/src/lib.rs
Pick action handler from #293 
Add `ActionHandler` as an executor of flight service.
- New Feature
- Improvement
> [store]: refactor: adopt action-handler proposed by @hulunbier

- Cargo.lock
- common/arrow/Cargo.toml
- fusequery/query/src/pipelines/transforms/transform_groupby_partial.rs
> Enable arrow simd by default

- docs/development/how-to-profile.md
> Add how to profile doc

- Cargo.lock
- fusestore/store/Cargo.toml
- fusestore/store/src/fs/ifs.rs
- fusestore/store/src/fs/list_result.rs
- fusestore/store/src/fs/localfs.rs
- fusestore/store/src/fs/localfs_test.rs
- fusestore/store/src/fs/mod.rs
- fusestore/store/src/lib.rs
> [store] add localfs as one of the abstract FS for meta and data

- .github/workflows/release.yml
- fusequery/query/build.rs
* Add rust toolchain channel to release
* Remove stable flag from release.yml (#327 )
* 
> Add rust toolchain channel to release

- Cargo.lock
- common/arrow/Cargo.toml
Try fix arrow SIMD feature override
#327
> Try fix arrow SIMD feature override

- Cargo.lock
- Cargo.toml
- common/arrow/Cargo.toml
- common/datablocks/src/data_block.rs
- common/progress/Cargo.toml
- common/progress/src/lib.rs
- common/progress/src/progress.rs
- common/progress/src/progress_test.rs
- common/streams/Cargo.toml
- common/streams/src/lib.rs
- common/streams/src/stream.rs
- common/streams/src/stream_csv.rs
- common/streams/src/stream_datablock.rs
- common/streams/src/stream_datablock_test.rs
- common/streams/src/stream_expression.rs
- common/streams/src/stream_limit.rs
- common/streams/src/stream_parquet.rs
- common/streams/src/stream_progress.rs
- common/streams/src/stream_progress_test.rs
- common/streams/src/stream_sort.rs
- fusequery/query/Cargo.toml
- fusequery/query/src/datasources/system/numbers_stream.rs
- fusequery/query/src/datasources/system/numbers_table_test.rs
- fusequery/query/src/sessions/context.rs
* Impl progress stream
- New Feature
#230 
Unit Tests
> Progress callback [Patch-1]

- Cargo.lock
- README.md
- common/arrow/Cargo.toml
Bumped arrow to arrow-rs
- Improvement
Unit Tests
> Bumped arrow to arrow-rs

- common/planners/src/lib.rs
- common/planners/src/plan_node.rs
- common/planners/src/plan_use_database.rs
- fusequery/query/src/datasources/datasource.rs
- fusequery/query/src/interpreters/interpreter_factory.rs
- fusequery/query/src/interpreters/interpreter_setting.rs
- fusequery/query/src/interpreters/interpreter_use_database.rs
- fusequery/query/src/interpreters/interpreter_use_database_test.rs
- fusequery/query/src/interpreters/mod.rs
- fusequery/query/src/sessions/context.rs
- fusequery/query/src/sql/plan_parser.rs
- fusequery/query/src/sql/sql_parser.rs
- fusequery/query/src/sql/sql_parser_test.rs
- fusequery/query/src/sql/sql_statement.rs
- tests/queries/0_stateless/00018_use_database.sql
Support `USE Database` statement
- New Feature
#335 
Unit Tests
> Use database

- fusequery/query/src/datasources/local/csv_table.rs
- fusequery/query/src/datasources/local/csv_table_test.rs
- tests/data/sample.csv
- tests/queries/0_stateless/00019_create_local_csv_table.reference
- tests/queries/0_stateless/00019_create_local_csv_table.sql
Add local csv table stateless tests
- Improvement
> Add local csv table stateless tests

- common/streams/src/stream_csv.rs
- fusequery/query/src/datasources/local/csv_table_test.rs
Throw csv parse error
- Improvement
Unit Tests
> Throw csv parse error

- common/flights/src/store_do_action.rs
- common/planners/src/plan_builder.rs
- common/planners/src/plan_scan.rs
- common/planners/src/plan_scan_test.rs
- fusequery/query/src/datasources/local/csv_table.rs
- fusequery/query/src/datasources/local/csv_table_test.rs
- fusequery/query/src/datasources/local/null_table.rs
- fusequery/query/src/datasources/local/null_table_test.rs
- fusequery/query/src/datasources/local/parquet_table.rs
- fusequery/query/src/datasources/local/parquet_table_test.rs
- fusequery/query/src/datasources/remote/remote_table.rs
- fusequery/query/src/datasources/system/clusters_table.rs
- fusequery/query/src/datasources/system/clusters_table_test.rs
- fusequery/query/src/datasources/system/functions_table.rs
- fusequery/query/src/datasources/system/functions_table_test.rs
- fusequery/query/src/datasources/system/numbers_table.rs
- fusequery/query/src/datasources/system/numbers_table_test.rs
- fusequery/query/src/datasources/system/one_table.rs
- fusequery/query/src/datasources/system/settings_table.rs
- fusequery/query/src/datasources/system/settings_table_test.rs
- fusequery/query/src/datasources/system/tables_table.rs
- fusequery/query/src/datasources/system/tables_table_test.rs
- fusequery/query/src/datasources/table.rs
- fusequery/query/src/sql/plan_parser.rs
- fusequery/query/src/tests/number.rs
Change read_plan argument type from PlanNode to ScanPlan
- Improvement
Unit Tests
> Change read_plan argument type from PlanNode to ScanPlan

- fusequery/query/src/datasources/system/databases_table.rs
- fusequery/query/src/datasources/system/databases_table_test.rs
- fusequery/query/src/datasources/system/mod.rs
- fusequery/query/src/datasources/system/system_database.rs
- fusequery/query/src/datasources/system/tables_table_test.rs
- fusequery/query/src/sql/plan_parser.rs
- fusequery/query/src/sql/sql_parser.rs
- fusequery/query/src/sql/sql_statement.rs
Support `SHOW DATABASES` statement;
- New Feature
fixes #335
> ISSUES-335 support SHOW DATABASES statement

- fusequery/query/src/datasources/system/databases_table.rs
Fix code lint
- Improvement
#353 
Unit Test
> Fix code lint

- fusequery/query/src/servers/clickhouse/clickhouse_handler.rs
Better datafuse version, disable suggestions.
- Improvement
#336
> [clickhouse] better datafuse version, disable suggestions

- .github/dependabot.yml
- README.md
Fix performance numbers and change dependsbot interval
> Fix performance numbers and change dependsbot interval

- .github/workflows/stateless-tests.yml
- tests/queries/0_stateless/00020_optimizer.sql
Change stateless tests to script instead of docker
- Improvement
#389
> Change stateless tests to script instead of docker

- .github/workflows/actions/labeler.yml
- .github/workflows/pr-labeler.yml
Add a bot for auto labeler for PR.
#393
> Add labeler bot

- fusequery/query/src/datasources/local/csv_table.rs
- fusequery/query/src/datasources/local/null_table.rs
- fusequery/query/src/datasources/local/parquet_table.rs
- fusequery/query/src/datasources/remote/remote_table.rs
- fusequery/query/src/datasources/system/clusters_table.rs
- fusequery/query/src/datasources/system/databases_table.rs
- fusequery/query/src/datasources/system/functions_table.rs
- fusequery/query/src/datasources/system/numbers_table.rs
- fusequery/query/src/datasources/system/one_table.rs
- fusequery/query/src/datasources/system/settings_table.rs
- fusequery/query/src/datasources/system/tables_table.rs
- fusequery/query/src/datasources/table.rs
- fusequery/query/src/pipelines/processors/pipeline_builder.rs
- fusequery/query/src/planners/plan_scheduler.rs
- fusequery/query/src/planners/plan_scheduler_test.rs
Check the table to run in Local or Cluster mode.
- New Feature
#392 
Unit Tests
> Add local mode check for plan scheduler

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/github-pages.yml
- website/datafuse/docs/rfcs/store/2021-04-22-store-design.md
- website/datafuse/sidebars.json
> Add RFCs to website

- .github/workflows/actions/labeler.yml
- website/datafuse/README.md
- website/datafuse/docusaurus.config.js
- website/datafuse/src/pages/index.js
Add README for datafuse.dev website
- Website
> Add README for datafuse.dev website

- .github/workflows/github-pages.yml
- website/datafuse/docs/overview/building-and-running.md
- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-avg.md
- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-count.md
- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-max.md
- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-min.md
- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-sum.md
- website/datafuse/docs/sqlstatement/data-definition-language-ddl/ddl-create-database.md
- website/datafuse/docs/sqlstatement/data-manipulation-language-dml/dml-select.md
- website/datafuse/docs/sqlstatement/information-functions/database.md
- website/datafuse/docs/sqlstatement/show-commands/show-databases.md
- website/datafuse/sidebars.json
Refactor docs directory structure
#421
> Better doc structure

- Cargo.lock
- common/arrow/Cargo.toml
Bump arrow-rs to latest version.
- Improvement
> Bump arrow-rs

- .github/actions-rs/grcov.yml
- Cargo.lock
- fusequery/query/Cargo.toml
- fusequery/query/conf/fusequery_config_spec.toml
- fusequery/query/src/bin/fuse-query.rs
- fusequery/query/src/configs/config.rs
- fusequery/query/src/configs/config_test.rs
- fusequery/query/src/configs/mod.rs
- fusequery/query/src/sql/sql_parser_test.rs
- scripts/ci/config/fusequery-cluster-1.toml
- scripts/ci/config/fusequery-cluster-2.toml
- scripts/ci/config/fusequery-cluster-3.toml
- scripts/ci/fusequery-cluster-3-nodes.sh
- scripts/ci/fusequery-standalone.sh
Add load configs from toml file
- New Feature
Fixes #435 
Unit Tests
> Add load configs from toml file

- .github/workflows/unit-tests.yml
- fusequery/query/src/sql/plan_parser_test.rs
Add more sql unit test for interval
- Improvement
> Add more sql unit test for interval

- Cargo.lock
- Cargo.toml
- common/ext/Cargo.toml
- common/ext/src/lib.rs
- common/ext/src/result_ext.rs
- fusequery/query/Cargo.toml
- fusequery/query/src/servers/mysql/endpoints/endpoint_on_query.rs
- fusequery/query/src/servers/mysql/mysql_handler.rs
Clean code for MySQLHandler
- Other
#364
> ISSUES-364 clean code for MySQLHandler

- Cargo.lock
- common/exception/Cargo.toml
- common/exception/src/exception.rs
- fusequery/query/src/configs/config_test.rs
- fusequery/query/src/datasources/tests.rs
- fusequery/query/src/interpreters/interpreter_setting_test.rs
- fusequery/query/src/interpreters/interpreter_use_database_test.rs
Display custom error backtrace in log
- Other
#364
> ISSUES-364 Display custom error backtrace in log

- fusequery/query/src/api/http/v1/cluster.rs
- fusequery/query/src/api/http/v1/cluster_test.rs
- fusequery/query/src/clusters/cluster.rs
- fusequery/query/src/clusters/cluster_test.rs
- fusequery/query/src/clusters/node.rs
- fusequery/query/src/datasources/system/clusters_table.rs
- fusequery/query/src/planners/plan_scheduler.rs
- fusequery/query/src/tests/service.rs
Remove cpus from cluster node
- Improvement
Fixes #443 
Unit Tests/Stateless Tests
> Remove cpus from cluster node

- tests/queries/0_stateless/README.md
- tests/queries/README.md
> Add README for stateless test

- fusequery/query/src/servers/mysql/endpoints/endpoint_on_init.rs
- fusequery/query/src/servers/mysql/endpoints/endpoint_on_query.rs
display error message for use database
- Bug Fix
fixes #447
> ISSUES-447 display error message for use database

- docs/rfcs/query/2021-05-01-join-framework-design.md
Signed-off-by: leiysky <leiysky@outlook.com>
Proposal for Join.
- New Feature
#319 
No test.
> RFC: join framework design

- docs/rfcs/query/2021-05-01-join-framework-design.md
Signed-off-by: leiysky <leiysky@outlook.com>
Add description about nested-loop join.
- New Feature
- Other
No test.
> RFC: add description about nested-loop join

- .github/workflows/stateless-tests-cluster.yml
- Cargo.lock
- common/progress/src/progress.rs
- common/streams/src/stream_progress.rs
- common/streams/src/stream_progress_test.rs
- fusequery/query/Cargo.toml
- fusequery/query/src/bin/fuse-query.rs
- fusequery/query/src/datasources/system/numbers_stream.rs
- fusequery/query/src/datasources/system/numbers_table.rs
- fusequery/query/src/servers/clickhouse/clickhouse_handler.rs
- fusequery/query/src/servers/clickhouse/clickhouse_stream.rs
- fusequery/query/src/servers/mysql/mysql_handler.rs
- fusequery/query/src/sessions/context.rs
1. Make clickhouse server support tokio based async io
2. Support send progress to clickhouse-client
- Improvement
#230
> [servers] clickhouse progress

- common/progress/src/progress.rs
- common/progress/src/progress_test.rs
- fusequery/query/src/sessions/context.rs
Remove rwlock for progress value update
> Remove rwlock for progress value update

- common/exception/src/exception.rs
- common/functions/src/function_column_test.rs
- fusequery/query/src/datasources/local/csv_table_stream.rs
- fusequery/query/src/datasources/system/numbers_stream.rs
- fusequery/query/src/pipelines/transforms/transform_expression_test.rs
- fusequery/query/src/pipelines/transforms/transform_filter_test.rs
- fusequery/query/src/sessions/macros.rs
support backtrace other error
- Improvement
#440
> ISSUES-440 support backtrace other error

- common/functions/src/aggregators/aggregator_avg.rs
- common/functions/src/aggregators/aggregator_count.rs
- common/functions/src/aggregators/aggregator_max.rs
- common/functions/src/aggregators/aggregator_min.rs
- common/functions/src/aggregators/aggregator_sum.rs
- common/functions/src/function.rs
- tests/suites/0_stateless/03_0007_select_alias.result
- tests/suites/0_stateless/03_0007_select_alias.sql
1. Throw exception for aggregator eval
2. Fix incorrect tests 
- Bug Fix
#480 
> [functions] Throw exception for aggregator eval

- fusestore/store/src/meta_service/meta_service_impl.rs
- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
> [store/meta] add RaftTxId to dedup logs

- common/datablocks/src/data_block_debug.rs
- fusequery/query/src/api/rpc/flight_service.rs
- fusequery/query/src/api/rpc/flight_service_test.rs
- fusequery/query/src/pipelines/transforms/transform_groupby_partial.rs
- tests/suites/0_stateless/03_0003_select_group_by.result
- tests/suites/0_stateless/03_0003_select_group_by.sql
fix unmatched block schema return from the partial group by
- Bug Fix
fixes #474 
Suit tests
> [transform] fix unmatched block schema return from partial group by

- fusestore/store/proto/store_meta.proto
- fusestore/store/src/dfs/distributed_fs.rs
- fusestore/store/src/dfs/distributed_fs_test.rs
- fusestore/store/src/meta_service/meta_service_impl.rs
- fusestore/store/src/meta_service/meta_service_impl_test.rs
- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
> [store] remove SetReq, use raft message for remote set.

- common/planners/src/plan_aggregator_test.rs
- common/planners/src/plan_builder.rs
- common/planners/src/plan_rewriter.rs
- tests/suites/0_stateless/03_0003_select_group_by.result
- tests/suites/0_stateless/03_0003_select_group_by.sql
* Move aggregate check function to plan rewriter
* Add stateless tests for aggregate function check
Cc @jyizheng 
- Improvement
#405 
UnitTests/StatelessTests
> Move aggregate check function to plan rewriter

- .github/workflows/cancel.yml
Add cancel to cancel the stale runners for github CI
fixes #509
> Add cancel to cancel the stale runners for github CI

- Cargo.toml
- common/progress/src/progress.rs
- common/progress/src/progress_test.rs
- common/streams/src/stream_progress.rs
- fusequery/query/src/datasources/system/numbers_table.rs
- fusequery/query/src/servers/clickhouse/clickhouse_handler.rs
- fusequery/query/src/sessions/context.rs
Interval progress send
- Improvement
fixes #482 
Unit tests
> Interval progress send

- Cargo.lock
- Cargo.toml
- common/runtime/Cargo.toml
- common/runtime/src/lib.rs
- common/runtime/src/runtime.rs
- common/runtime/src/runtime_test.rs
- fusequery/query/Cargo.toml
- fusequery/query/src/api/rpc/flight_service.rs
- fusequery/query/src/interpreters/interpreter_setting.rs
- fusequery/query/src/pipelines/processors/pipeline.rs
- fusequery/query/src/pipelines/processors/pipeline_builder.rs
- fusequery/query/src/pipelines/processors/processor_merge.rs
- fusequery/query/src/pipelines/processors/processor_merge_test.rs
- fusequery/query/src/pipelines/transforms/transform_aggregator_final_test.rs
- fusequery/query/src/pipelines/transforms/transform_aggregator_partial_test.rs
- fusequery/query/src/pipelines/transforms/transform_expression_test.rs
- fusequery/query/src/pipelines/transforms/transform_filter_test.rs
- fusequery/query/src/pipelines/transforms/transform_groupby_final_test.rs
- fusequery/query/src/pipelines/transforms/transform_groupby_partial_test.rs
- fusequery/query/src/pipelines/transforms/transform_limit_test.rs
- fusequery/query/src/pipelines/transforms/transform_projection_test.rs
- fusequery/query/src/pipelines/transforms/transform_sort_test.rs
- fusequery/query/src/pipelines/transforms/transform_source_test.rs
- fusequery/query/src/servers/clickhouse/clickhouse_handler.rs
- fusequery/query/src/servers/mysql/mysql_handler.rs
- fusequery/query/src/sessions/context.rs
- Improvement
fixes #515 
UnitTests/StatelssTests
> Binding tokio runtime to per context

- .github/workflows/welcome.yml
> Add welcome bot github action

- fusequery/query/src/servers/mysql/mysql_handler.rs
Try to fix cluster test tokio error
- Bug Fix
> Try to fix cluster test tokio error

- website/datafuse/material/partials/header.html
- website/datafuse/mkdocs.yml
- website/datafuse/src/partials/header.html
Add link to website home
- Website
#503
> Add link to website home

- .github/workflows/unit-tests.yml
Enable codecoverage for pull request
> Enable code coverage for pull request

- website/datafuse/docs/index.md
- website/datafuse/material/partials/header.html
- website/datafuse/material/partials/source.html
- website/datafuse/src/partials/source.html
- website/datafuse/tools/build/_/index.ts
Change to github icon for website
- Website
> Change to github icon for website

- website/datafuse/docs/overview/performance.md
> Add performance bench gif

- common/planners/src/plan_walker.rs
- common/planners/src/plan_walker_test.rs
Refactor plan walk
- Improvement
> Refactor plan walk

- Cargo.lock
- common/datablocks/src/data_block.rs
- fusestore/store/Cargo.toml
- fusestore/store/src/data_part/appender.rs
- fusestore/store/src/data_part/appender_test.rs
- fusestore/store/src/data_part/mod.rs
- fusestore/store/src/lib.rs
An initial version of the parquet file appender
none
Unit tests
> Parquet appender

- .github/workflows/cargo.yml
- .github/workflows/datafuse-build.yml
- .github/workflows/datafuse-release.yml
- .github/workflows/performance-tests-standalone.yml
- .github/workflows/stateless-tests-cluster.yml
- .github/workflows/stateless-tests-standalone.yml
- .github/workflows/unit-tests.yml
- fusequery/query/src/sql/plan_parser_test.rs
- rust-toolchain
- scripts/setup/dev_setup.sh
Bump rust-toolchain to nightly-2021-05-06
Fixes #575 
Unit Tests
> Bump rust-toolchain to nightly-2021-05-06

- common/datablocks/src/data_block.rs
- common/datablocks/src/data_block_debug.rs
- common/datablocks/src/data_block_kernel.rs
- common/datavalues/src/data_array.rs
- common/datavalues/src/data_array_merge_sort.rs
- common/datavalues/src/data_value_kernel.rs
- common/datavalues/src/macros.rs
- common/exception/src/exception.rs
- common/flights/src/query_client.rs
- common/functions/src/expressions/cast.rs
- common/functions/src/function_column.rs
- common/functions/src/strings/substring.rs
- fusequery/query/src/datasources/datasource.rs
- fusequery/query/src/datasources/local/csv_table.rs
- fusequery/query/src/datasources/local/csv_table_stream.rs
- fusequery/query/src/datasources/remote/remote_database.rs
- fusequery/query/src/datasources/system/numbers_stream.rs
- fusequery/query/src/interpreters/interpreter_setting.rs
- fusequery/query/src/pipelines/transforms/transform_aggregator_final.rs
- fusequery/query/src/pipelines/transforms/transform_aggregator_partial.rs
- fusequery/query/src/pipelines/transforms/transform_filter.rs
- fusequery/query/src/pipelines/transforms/transform_groupby_final.rs
- fusequery/query/src/pipelines/transforms/transform_groupby_partial.rs
- fusequery/query/src/pipelines/transforms/transform_remote.rs
- fusequery/query/src/servers/clickhouse/clickhouse_stream.rs
- fusequery/query/src/sessions/macros.rs
- fusequery/query/src/sql/sql_parser.rs
- Improvement
Fixes #577
Unit Tests
> [common/exception] make life easier by rewriting error conversion with trait From

- scripts/ci/ci-stateless-tests-cluster.sh
- website/datafuse/docs/development/contributing.md
Fix the wrong mode for cluster test
Unit Tests
> Fix the wrong mode for cluster test

- fusequery/query/src/pipelines/processors/processor_merge.rs
fix infinite loop for Merge Processor
- Bug Fix
#468
> ISSUES-468 fix infinite loop for Merge Processor

- fusequery/query/src/sql/plan_parser.rs
- fusequery/query/src/sql/plan_parser_test.rs
Add one unit test for plan parser and more comments for select_to_plan
- Improvement
Unit Tests
> Add one unit test for plan parser and more comments for select_to_plan

- website/datafuse/docs/rfcs/query/2021-05-22-plan-expression.md
- website/datafuse/mkdocs.yml
Add plan expression to RFCs
Fixes #621
> Add plan expression to RFCs

- website/datafuse/docs/development/contributing.md
> Remove a line, for auto merge

- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
adjust var names; normalize wait_for_xxx utils; add tracing log to key
steps.
#271
> [store] test 3 candidates cluster

- common/datavalues/src/data_array_logic.rs
Allow clippy::nonminimal_bool for data_array_negation
> Allow clippy::nonminimal_bool for data_array_negation

- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-argmax.md
- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-argmin.md
- website/datafuse/mkdocs.yml
> Add argMin/argMax docs

- fusestore/store/src/meta_service/mod.rs
- fusestore/store/src/meta_service/placement.rs
- fusestore/store/src/meta_service/placement_test.rs
> [store] add: choose n elts from m elts randomly

- fusestore/store/src/meta_service/meta.rs
- fusestore/store/src/meta_service/meta_test.rs
- fusestore/store/src/meta_service/mod.rs
> [store] add a slots initialization that randomly nodes to slot, as a simple file distribution algo

- fusestore/store/src/meta_service/meta.rs
- fusestore/store/src/meta_service/meta_test.rs
> [store] add Meta::builder() to customized building meta data

- Cargo.lock
- common/arrow/Cargo.toml
Bump arrow from 4.1.0 to 4.2.0
- Other
N/A
Unit Tests
> Bump arrow from 4.1.0 to 4.2.0

- Cargo.lock
- common/flights/Cargo.toml
- common/flights/src/dns_resolver.rs
- common/flights/src/dns_resolver_test.rs
- common/flights/src/lib.rs
- common/flights/src/store_client.rs
- fusequery/query/Cargo.toml
- fusequery/query/src/clusters/cluster.rs
- fusequery/query/src/clusters/node.rs
Support parse hostname for flight client
- Improvement
Fixes #675
> ISSUES-675 support parse hostname for flight client

- common/functions/src/hashes/siphash.rs
better code for siphash
- Other
> [common/functions] better code for siphash

- website/datafuse/docs/sqlstatement/hash-functions/siphash.md
- website/datafuse/docs/sqlstatement/other-functions/totypename.md
- website/datafuse/docs/sqlstatement/string-functions/substring.md
- website/datafuse/docs/system/system-tables.md
- website/datafuse/mkdocs.yml
Add hash and other function to docs
Fixes #695 
Unit Tests
> Add hash and other function to docs

- common/planners/src/plan_explain.rs
- common/planners/src/plan_explain_test.rs
[planners] Fix schema for explain plan
- Bug Fix
Fixes #703 
Unit Tests
> [planners] Fix schema for explain plan

- fusequery/query/src/sql/plan_parser.rs
- fusequery/query/src/sql/plan_parser_test.rs
Signed-off-by: tison <wander4096@gmail.com>
Return proper error if query contains CTE. We are planning to do on #514 .
- Not for changelog
Fixes #27 
Manually verify the output. I'd glad to know where to add tests.
> error on cte because it is nyi

- .github/workflows/license-checker.yml
- .licenserc.json
- common/functions/src/hashes/hash.rs
- fusequery/query/src/lib.rs
- fusequery/query/src/optimizers/optimizer_scatters.rs
- fusequery/query/src/optimizers/optimizer_test.rs
- fusequery/query/src/pipelines/transforms/transform_remote_test.rs
- fusequery/query/src/tests/service_new.rs
- fusestore/store/src/dfs/distributed_fs_test.rs
- fusestore/store/src/engine/mod.rs
- fusestore/store/src/executor/action_handler.rs
- fusestore/store/src/executor/action_handler_test.rs
- fusestore/store/src/executor/mod.rs
- fusestore/store/src/lib.rs
- fusestore/store/src/tests/logging.rs
Add a github action to check license comments.
Fixes #724
Unit Tests
> Add license comments checker.

- .github/PULL_REQUEST_TEMPLATE.md
- website/datafuse/docs/policies/cla.md
> [docs] Add CLA

- Cargo.lock
- common/aggregate_functions/Cargo.toml
- common/functions/Cargo.toml
- common/progress/Cargo.toml
- common/runtime/Cargo.toml
- common/streams/Cargo.toml
- fusestore/store/Cargo.toml
Remove unused deps which lint by cargo udeps
- Improvement
N/A
Unit Tests
> [common] Remove unused deps which lint by cargo udeps

- Cargo.lock
- common/arrow/Cargo.toml
- common/datavalues/src/data_array_arithmetic.rs
- common/datavalues/src/data_value_kernel.rs
- common/datavalues/src/macros.rs
Use SIMD modulus in latest arrow-rs version 
- Improvement
fixes https://github.com/datafuselabs/datafuse/issues/735
> add simd mod

- Cargo.lock
- common/exception/Cargo.toml
- fusequery/query/Cargo.toml
[dep] update thirdparty crates dep from datafuse-extras
- Improvement
Fixes #743
Unit Tests
> [dep] update thirdparty crates dep from datafuse-extras

- common/planners/src/plan_expression_function.rs
- fusequery/query/src/sql/plan_parser.rs
- tests/suites/0_stateless/02_0005_function_compare.result
- tests/suites/0_stateless/02_0005_function_compare.sql
[expressions] support expression between
- New Feature
#427 
Unit Tests
> [expressions] support expression between

- tests/fuse-test
Print test summary only once
Fixes #786
> ISSUE-786 print test summary only once

- Makefile
build first when running, to ensure that the deployment can be completed according to the documentation
Fixes #780
Just test it locally
> [deploy] build first when running

- Makefile
- deploy/charts/README.md
- tests/README.md
Fix some missing make command in the document.
> [docs] Fix some missing make command

- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- when current node is not leader, returns
`ClientWriteError::ForwardToLeader` instead of `anyhow::Error`.
- add test to ensure this behavior: Follower and NonVoter should both
returns this error.
- explicit `anyhow::Result` to avoid conflict with `std::Result`.
- Improvement
#271
> [store/meta]: test: non-leader raft node should returns ForwardToLeader error

- common/tracing/src/logging.rs
fix tracing log level check
- Bug Fix
Fixes #799
Unit Tests
> [tracing] fix tracing log level

- fusequery/query/src/optimizers/optimizer.rs
- fusequery/query/src/pipelines/processors/pipeline_builder.rs
- fusequery/query/src/pipelines/transforms/transform_aggregator_final.rs
- fusequery/query/src/pipelines/transforms/transform_aggregator_partial.rs
- fusequery/query/src/pipelines/transforms/transform_expression_executor.rs
- fusequery/query/src/pipelines/transforms/transform_filter.rs
- fusequery/query/src/pipelines/transforms/transform_groupby_final.rs
- fusequery/query/src/pipelines/transforms/transform_groupby_partial.rs
- fusequery/query/src/pipelines/transforms/transform_limit.rs
- fusequery/query/src/pipelines/transforms/transform_limit_by.rs
- fusequery/query/src/pipelines/transforms/transform_projection.rs
- fusequery/query/src/pipelines/transforms/transform_remote.rs
- fusequery/query/src/pipelines/transforms/transform_sort_merge.rs
- fusequery/query/src/pipelines/transforms/transform_sort_partial.rs
- fusequery/query/src/pipelines/transforms/transform_source.rs
- fusequery/query/src/sql/plan_parser.rs
- fusestore/store/src/meta_service/state_machine.rs
- website/datafuse/Makefile
- website/datafuse/docs/development/coding-guidelines.md
- website/datafuse/docs/development/tracing.md
- website/datafuse/mkdocs.yml
* Change the tracing level from INFO to DEBUG
* Add development to docs website
- Improvement
Fixes #806 
Unit Tests
> [query] Change the tracing level from INFO to DEBUG

- website/datafuse/docs/development/roadmap.md
- website/datafuse/docs/development/tracing.md
- website/datafuse/mkdocs.yml
> [docs] add roadmap

- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-combinator.md
- website/datafuse/mkdocs.yml
* add aggregate combinator to document
> [docs] add aggregate combinator

- fusequery/benchmarks/nyctaxi/src/bin/nyctaxi.rs
- fusequery/query/src/datasources/system/numbers_stream.rs
- fusequery/query/src/datasources/system/numbers_table.rs
- fusequery/query/src/datasources/system/settings_table.rs
- fusequery/query/src/interpreters/interpreter_select.rs
- fusequery/query/src/interpreters/interpreter_setting.rs
- fusequery/query/src/optimizers/optimizer_constant_folding_test.rs
- fusequery/query/src/optimizers/optimizer_projection_push_down_test.rs
- fusequery/query/src/optimizers/optimizer_scatters.rs
- fusequery/query/src/pipelines/transforms/transform_remote.rs
- fusequery/query/src/sessions/context.rs
- fusequery/query/src/sessions/macros.rs
- fusequery/query/src/sessions/settings.rs
Extract getter and setter of settings from context to setting
Fixes #827 
Related #704
> ISSUES-827 extract getter and setter of settings from context to setting

- docker/Dockerfile
- docker/bootstrap.sh
- docker/fusequery-docker.toml
Previously only fuse-store logs are presented in docker which is not desired, and we should also incorporate fuse-query logging in standalone docker 
Fixes #issue
Unit Tests
> [Build] better logging

- tests/perfs/perfs.py
support to control concurrency and iterations through command line
- New Feature
Fixes #issue
Unit Tests
> [performance] add concurrency and iteration flagging

- fusequery/query/src/servers/mysql/mysql_handler_test.rs
- fusequery/query/src/servers/mysql/mysql_session_test.rs
- fusequery/query/src/servers/mysql/writers/query_result_writer.rs
Remove compile warnings when run test
> Remove compile warnings when run test

- fusequery/query/src/servers/mysql/mysql_handler_test.rs
Try fix MySQLHandler flake test
Related #548
> ISSUES-548 try fix flake test for MySQLHandler

- fusestore/store/src/meta_service/meta.rs
- fusestore/store/src/meta_service/meta_test.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
According to the latest design, databases and tables are now a part of
meta data, no longer a DFS file.
- Add two seq number fields for generating globally unique database id
and table id.
E.g. a database may have the same id with a table.
But two databases or tables will never have the same id.
When adding database or table, the unique seq is generated by raft
state machine, when the AddDatabase log applies.
- Define Database and Table with serde.
- Add two BTreeMap to Meta to store databases and tables.
- If the database with the name to add present, nothing is done.
- Reading database is done by reading from the local raft state machine.
Thus there is chance the last added database can not be seen on …
> [store] feature: MetaNode suuport AddDatabase

- fusestore/store/src/api/rpc/flight_service.rs
- fusestore/store/src/api/rpc_service.rs
- fusestore/store/src/executor/action_handler.rs
- fusestore/store/src/executor/action_handler_test.rs
- Improvement
#271
also as a part of #774
> [store] test: add unit-test to ActionHandler::create_db()

- Cargo.lock
- Cargo.toml
- common/metatypes/Cargo.toml
- common/metatypes/src/lib.rs
- fusestore/store/Cargo.toml
- fusestore/store/src/meta_service/meta.rs
- fusestore/store/src/meta_service/meta_test.rs
- fusestore/store/src/meta_service/raftmeta.rs
- Improvement
#271
also as part of #774
> [store] refactor: move common meta data types into common/metatypes

- Cargo.lock
- common/exception/Cargo.toml
- fusequery/query/Cargo.toml
- fusequery/query/benches/suites/mod.rs
- fusequery/query/src/servers/mod.rs
- fusequery/query/src/servers/mysql/mod.rs
- bump sqlparser
- fix bench
Fixes #878 
Unit Tests
> [*] bump sqlparser and fix bench

- common/flights/src/lib.rs
- common/flights/src/store_do_action.rs
- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/executor/action_handler.rs
- fusestore/store/src/executor/action_handler_test.rs
- New Feature
#271
#774 
fix: #888
> [store] feature: add ActionHandler::get_db()

- .github/ISSUE_TEMPLATE/20_feature-request.md
- .github/ISSUE_TEMPLATE/30_bug-report.md
- .github/ISSUE_TEMPLATE/40_build-issue.md
- .github/ISSUE_TEMPLATE/50_documentation-issue.md
- .github/ISSUE_TEMPLATE/60_improvement-issue.md
- .github/ISSUE_TEMPLATE/70_performance-issue.md
- .github/ISSUE_TEMPLATE/80_other-issue.md
> GITHUB: better issue template

- website/datafuse/docs/development/roadmap.md
- website/datafuse/docs/sqlstatement/test-functions/crashme.md
- website/datafuse/docs/sqlstatement/test-functions/sleep.md
- website/datafuse/mkdocs.yml
add test functions to doc and update roadmap
Fixes #923
> ISSUE-923: add test functions to doc and update roadmap

- fusestore/store/src/executor/action_handler.rs
- fusestore/store/src/meta_service/meta.rs
- fusestore/store/src/meta_service/meta_test.rs
- fusestore/store/src/meta_service/raftmeta.rs
> [store] refactor: rename unclassified to generic/general-purpose

- Cargo.lock
- common/infallible/Cargo.toml
- common/infallible/src/mutex.rs
- common/infallible/src/rwlock.rs
- common/planners/Cargo.toml
- fusestore/store/src/engine/mem_engine.rs
- fusestore/store/src/engine/mem_engine_test.rs
- fusestore/store/src/executor/action_handler.rs
`Mutex` and `RwLock` provided by [parking_lock](https://crates.io/crates/parking_lot) , the benchmark performance improved by about ~10% on my laptop.
No
Bench Tests
> [perf,  common/infallible] intro parking_lot

- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-avg-if.md
- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-combinator.md
- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-count-if.md
- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-max-if.md
- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-min-if.md
- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-sum-if.md
- website/datafuse/mkdocs.yml
move aggregate if from combinator
> doc: move aggregate if from combinator

- common/datablocks/src/kernels/data_block_group_by.rs
- common/datavalues/src/columns/common.rs
- common/management/src/user/utils.rs
improve group by
Seems to make 20% ~ 40% improvement in my pc.
- Improvement
#520 
Unit Tests
> [kernels] improve group by

- README.md
- website/datafuse/docs/development/profiling.md
- website/datafuse/docs/development/roadmap.md
- website/datafuse/docs/overview/performance.md
update performance to datafuse-v0.4.40-nightly
> docs: update performance to datafuse-v0.4.40-nightly

- website/datafuse/docs/rfcs/store/0001-store-design.md
> fix doc typo

- common/flights/src/impls/storage_api_impl.rs
- common/flights/src/impls/storage_api_impl_utils.rs
- common/flights/src/impls/storage_api_impl_utils_test.rs
- common/store-api/src/meta_api.rs
- common/store-api/src/storage_api.rs
- fusestore/store/src/api/rpc/flight_service.rs
Remove unnecessary super traits and rename util function names
Fixes #969 
Unit Tests
> Remove unnecessary super traits and rename util function names

- Cargo.lock
- common/exception/Cargo.toml
- fusequery/query/Cargo.toml
- fusequery/query/src/sql/sql_common.rs
- tests/suites/0_stateless/02_0002_function_cast.result
- tests/suites/0_stateless/02_0002_function_cast.sql
more custom types parser support
- Improvement
Unit Tests
> [sql] more custom types parser support

- website/datafuse/docs/sqlstatement/show-commands/show-create-table.md
- website/datafuse/mkdocs.yml
add show create table to document
Fixes #1003
> docs: add show create table to document

- README.md
We should not show off.
But I just can't help.
- Improvement
> [doc] refine: add star gazers trend

- README.md
- website/datafuse/docs/overview/performance.md
- website/datafuse/docs/sqlstatement/hash-functions/siphash.md
update the rustc version for performance
> docs: update the rustc version

- .github/workflows/unit-tests.yml
remove  `~/.cargo/bin/` from cache
Fixes #1012 
No
> [ci] fix gcov install failed

- README.md
- website/datafuse/docs/overview/performance.md
Update performance with v0.4.48
> Update performance with v0.4.48

- tests/perfs/compare.py
- tests/perfs/perfs.py
Support to store performance tests to object storage endpoint
example link:
https://test-1306375239.cos.ap-nanjing.myqcloud.com/python3/compare/performance.html
- New Feature
fixes https://github.com/datafuselabs/datafuse/issues/1043
Unit Tests
> configure S3 storage for performance tests

- Cargo.lock
- fusequery/query/Cargo.toml
- fusequery/query/src/datasources/common_test.rs
Remove anyhow for FuseQuery
related #364
> ISSUE-364 remove anyhow for FuseQuery

- fusestore/store/src/meta_service/raftmeta_test.rs
> [store] test: move cluster setting up to setup_cluster()

- website/datafuse/docs/sqlstatement/show-commands/show-processlist.md
- website/datafuse/mkdocs.yml
add show processlist to doc website
Fixes #1072
> ISSUE-1072: add show processlist to doc website

- fusequery/query/src/sessions/sessions.rs
Try fix dead lock when destroy sessions
- Bug Fix
> Try fix dead lock when destroy sessions

- .github/workflows/rust-audit.yml
> ci: add rust audit check

- common/datavalues/src/arrays/ops/agg_test.rs
- common/datavalues/src/arrays/ops/mod.rs
Add unit test for common/datavalues/src/arrays/ops/agg.rs
Fixes #issue
Unit Tests
> [datavalue] Add unit test for agg.rs

- fusestore/store/src/meta_service/raft_log.rs
- fusestore/store/src/meta_service/raft_log_test.rs
> [store] feature: RaftLog::insert() to insert a single log

- common/datavalues/src/arrays/ops/apply_test.rs
- common/datavalues/src/arrays/ops/mod.rs
ommon/datavalues/src/arrays/ops/apply.rs
Fixes #issue
Unit Tests
> [datavalues] add unit tests for apply 

- fusestore/store/src/configs/config.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- Improvement
#271
fixes: #1117
> [store] add config of raft heartbeat and snapshot

- common/datavalues/src/lib.rs
- common/datavalues/src/vec.rs
- common/datavalues/src/vec_test.rs
common/datavalues/src/vec.rs
- Improvement
Fixes #issue
Unit Tests
> [datavalues] add basic test for AlignedVec and make it better

- common/flights/src/impls/meta_api_impl.rs
- common/flights/src/store_do_action.rs
- common/metatypes/src/lib.rs
- common/store-api/src/meta_api.rs
- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/engine/mem_engine.rs
- fusestore/store/src/executor/action_handler.rs
- fusestore/store/src/executor/action_handler_test.rs
- fusestore/store/src/executor/meta_handlers.rs
- fusestore/store/src/executor/storage_handlers.rs
- fusestore/store/src/meta_service/applied_state.rs
- fusestore/store/src/meta_service/cmd.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/meta_service/raftmeta_test.rs
- fusestore/store/src/meta_service/state_machine.rs
- fusestore/store/src/meta_service/state_machine_test.rs
change database, table and data parts operations from meta to meta_node
- Improvement
https://github.com/datafuselabs/datafuse/issues/993
https://github.com/datafuselabs/datafuse/issues/775
> Change database, table and data parts operations from meta to meta_node

- website/datafuse/docs/sqlstatement/conversion-functions/type-conversion.md
- website/datafuse/mkdocs.yml
add conversion functions
Fixes #1142 
Unit Tests
> DOC-1142: add conversion functions

- website/datafuse/docs/sqlstatement/conversion-functions/cast.md
- website/datafuse/mkdocs.yml
> DOC: add CAST

- common/datavalues/src/arrays/ops/downcast_test.rs
- common/datavalues/src/arrays/ops/mod.rs
- fusestore/store/src/tests/service.rs
add unit tests for common/datavalues/src/arrays/ops/downcast.rs
Fixes #1133 
Unit Tests
> [datavalues] add unit tests for downcast 

- Makefile
- scripts/setup/dev_setup.sh
Add miri check to Makefile to help improve code quality.
Fixes #issue
Local Tests
> [test] add miri check

- fusestore/store/src/data_part/appender_test.rs
- fusestore/store/src/executor/storage_handlers.rs
- fusestore/store/src/localfs/local_fs.rs
- fusestore/store/src/localfs/local_fs_test.rs
Refine the log format
- Improvement
Fixes N/A
Unit Tests
> STORE: refine the log format

- common/datavalues/src/arrays/ops/downcast_test.rs
- common/datavalues/src/arrays/ops/fill.rs
- common/datavalues/src/arrays/ops/fill_test.rs
- common/datavalues/src/arrays/ops/mod.rs
add unit tests for common/datavalues/src/arrays/ops/fill.rs
Unit Tests
> [datavalues] add unit tests for fill 

- Cargo.lock
- common/exception/Cargo.toml
- common/functions/Cargo.toml
- common/functions/src/aggregates/aggregate_function_factory.rs
- common/functions/src/aggregates/aggregator.rs
- common/functions/src/scalars/arithmetics/arithmetic.rs
- common/functions/src/scalars/comparisons/comparison.rs
- common/functions/src/scalars/expressions/expression.rs
- common/functions/src/scalars/function_factory.rs
- common/functions/src/scalars/hashes/hash.rs
- common/functions/src/scalars/logics/logic.rs
- common/functions/src/scalars/strings/string.rs
- common/functions/src/scalars/udfs/udf.rs
- fusequery/query/Cargo.toml
- tests/suites/0_stateless/02_0002_function_cast.result
- tests/suites/0_stateless/02_0002_function_cast.sql
- Improvement
Fixes #1146 
Unit Tests
> Add More Cast Functions

- website/datafuse/docs/sqlstatement/data-definition-language-ddl/ddl-create-table.md
- website/datafuse/docs/sqlstatement/data-definition-language-ddl/ddl-drop-table.md
- website/datafuse/mkdocs.yml
add create/drop table
Fixes #1163 
Unit Tests
> DOC-1163: add create/drop table

- common/planners/src/plan_display_test.rs
- common/planners/src/plan_table_create.rs
- fusequery/query/src/sql/sql_parser.rs
- fusequery/query/src/sql/sql_parser_test.rs
- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/executor/action_handler_test.rs
- website/datafuse/docs/sqlstatement/data-definition-language-ddl/ddl-create-table.md
[typo] JSONEachRaw => JSONEachRow
- Improvement
Fixes #issue
Unit Tests
> [typo] JSONEachRaw => JSONEachRow

- fusestore/store/src/api/rpc/flight_service_test.rs
> fix: typo not up to date

- website/datafuse/docs/sqlstatement/data-manipulation-language-dml/dml-insert.md
- website/datafuse/mkdocs.yml
Add `insert` to document, https://datafuse.rs
Fixes #1162
Unit Tests
> DOC-1162: add insert

- fusestore/store/src/api/rpc/flight_service_test.rs
> [store] refactor: fix lint issues in tests

- website/datafuse/mkdocs.yml
- website/datafuse/src/overrides/home.html
> WEBSITE: refine the desc

- common/datavalues/src/arrays/ops/group_hash_test.rs
- common/datavalues/src/arrays/ops/mod.rs
add a unit test for  common/datavalues/src/arrays/ops/group_hash.rs
Unit Tests
> [datavalues] unit test for group_hash

- common/datavalues/src/arrays/ops/mod.rs
- common/datavalues/src/arrays/ops/scatter.rs
- common/datavalues/src/arrays/ops/scatter_test.rs
Add unit tests for   common/datavalues/src/arrays/ops/scatter.rs
Unit Tests
> [datavalues] add unit test for scatter 

- common/datavalues/src/arrays/ops/scatter.rs
Correct the docs for scatter_unchecked.
- Bug Fix
Fixes #1195 
Unit Tests
> bug fix: correct the docs for scatter_unchecked

- tests/perfs/compare.py
- tests/perfs/perfs.py
Support to use global endpoint and retry for CI tests
Still has SSL issue for endpoint(because of limited support in accelerate endpoint)
Fixes https://github.com/datafuselabs/datafuse/issues/1213
Unit Tests
> [Testing/CI] better logging and support endpoint CDN

- common/tracing/src/logging.rs
> [common/logging] doc: explain how to adjust interval of batch tracing data send

- fusestore/store/src/meta_service/state_machine_test.rs
> [store] refactor: rename local vars in state machine test. Nothing really changed

- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/executor/action_handler.rs
- fusestore/store/src/meta_service/state_machine.rs
Minor refactoring to data_parts
- Improvement
Fixes #1102 
Unit Tests
> [Improvement] Refactor data parts

- common/runtime/src/runtime.rs
> [common/runtime] refactor: create handle outside runtime thread; remove select

- fusequery/query/src/servers/server.rs
Fix #1254 
- Bug Fix
Fixes #1254 
Unit Tests
> ISSUE 1254: fix race

- .gitignore
- Makefile
- docker/perf-tool/Dockerfile
- tests/perfs/perfs.yaml
Performance tool optimization for fuse-benchmark and shrink down perfs.yaml data volume
fixes https://github.com/datafuselabs/datafuse/issues/1238
Unit Tests
> [Build/Test] perf tool building optimization and downsize performance test data volume

- tests/perfs/compare.py
In desired, we should also integrate logs from benchmarking instances in performance report html
example
https://test-1306375239.cos.accelerate.myqcloud.com/benchmark/compare/performance.html
- Improvement
fixes https://github.com/datafuselabs/datafuse/issues/1269
Unit Tests
> [Improvement] show log in compare.html

- Cargo.lock
- common/arrow/Cargo.toml
- common/datablocks/src/kernels/data_block_sort.rs
[arrow2] update arrow2 version to improve sort
- Improvement
Fixes #1274
Unit Tests
> [arrow2] update arrow2 version to improve sort

- docker/perf-tool/Dockerfile
update dependencies for perf tool image build
Fixes #issue
Unit Tests
> [Build/Testing/CI] update docker perf tool dependencies

- .github/workflows/datafuse-performance-dispatch.yaml
Here we implemented cloud native datafuse performance test(standalone edition)
- New Feature
fixes https://github.com/datafuselabs/datafuse/issues/1259
fixes https://github.com/datafuselabs/datafuse/issues/1193
fixes https://github.com/datafuselabs/datafuse/issues/692
partially fix https://github.com/datafuselabs/datafuse/issues/748 except fuzz test part
Unit Tests
> [Test Infra]introduce alpha version performance tests

- fusestore/store/src/api/rpc/flight_service_test.rs
- fusestore/store/src/meta_service/state_machine.rs
Fix a  typo that makes the number of rows and bytes set incorrectly. 
- Bug Fix
Fixes #1221 
Unit Tests
> fix: Inaccurate Table Statistics

- .github/workflows/datafuse-performance-dispatch.yaml
Use customized label for perf runner
Fixes #issue
Unit Tests
> update runner label

- scripts/setup/dev_setup.sh
> dev_setup.sh: add libssl-dev

- common/arrow/Cargo.toml
Bump arrow2 from upstream
- Improvement
Fixes #issue
Unit Tests
> Bump arrow2

- .github/workflows/datafuse-performance-dispatch.yaml
- docker/cache/Dockerfile
Redirect all dispatches to labeled runners and add missing files for docker building stage
- Bug Fix
Fixes #issue
Unit Tests
> [Test Infra] dispatch updates

- docker/cache/Dockerfile
- website/datafuse/docs/rfcs/query/0004-performance-test.md
Update documentation and test on performance tests
- Website
Fixes #issue
Unit Tests
> [Doc] performance test api rfc

- Cargo.lock
- website/datafuse/docs/rfcs/query/0004-performance-test.md
- website/datafuse/mkdocs.yml
add performance test
Fixes #1300 
Unit Tests
> DOC-1300: add performance test

- fusestore/store/src/api/rpc_service.rs
- fusestore/store/src/configs/config.rs
- fusestore/store/src/tests/service.rs
solve #1250 
- Improvement
Fixes #1250 
Unit Tests
> ISSUE 1250: add config

- fusecli/cli/src/cmds/status.rs
> [cli] refactor: remove temp println

- fusestore/store/src/api/rpc_service.rs
- fusestore/store/src/executor/action_handler.rs
- fusestore/store/src/meta_service/network.rs
- fusestore/store/src/meta_service/raftmeta.rs
- fusestore/store/src/tests/service.rs
> [store] refactor: rename myid to id, reanme target-id to target

- common/functions/src/aggregates/aggregate_combinator_if.rs
- fusequery/query/src/pipelines/transforms/transform_filter.rs
pretty nohup.out when exec select * from numbers(10) where null;
- Bug Fix
Fixes #1307 
Unit Tests
> ISSUE-1307: pretty nohup.out when exec select * from numbers(10) where null;

- fusequery/query/src/pipelines/transforms/transform_filter.rs
Sorry, pull  error, re apply ,inspect BooleanArray exit true 
**Run sql:** 
`SELECT number FROM numbers_mt(100000000000) where number = 100 limit 1 ;`
**before:**
1 rows in set. Elapsed: 66.156 sec. Processed 100.00 billion rows, 800.00 GB (1.51 billion rows/s., 12.09 GB/s.)
**after:**
1 rows in set. Elapsed: 37.384 sec. Processed 100.00 billion rows, 800.00 GB (2.67 billion rows/s., 21.40 GB/s.)
> Improve filter performance

- Makefile
> Fix: make run-helm for Makefile

- tests/perfs/compare.py
- tests/perfs/perfs.yaml
- Add more perf sqls
- Fix perf htmls
- Improvement
Fixes #1347
Unit Tests
> [perf] Add more perf sqls

- fusestore/store/src/executor/action_handler_test.rs
solve #1366
- Improvement
Fixes #1366
Unit Tests
> ISSUE 1366

- common/datavalues/src/arrays/ops/take_random_test.rs
- common/datavalues/src/arrays/ops/take_test.rs
- New Feature
- Bug Fix
Fixes #issue
Unit Tests
> fix post merge error from datavalue unit test

- tests/perfs/perfs.yaml
Add sum modulo perf case
- Improvement
Fixes #issue
Unit Tests
> Add sum modulo perf case

- README.md
https://github.com/ClickHouse/ClickHouse/issues/27510
Fixes #issue
Unit Tests
> Remove performance in Readme

- .github/workflows/datafuse-release.yml
- Makefile
- docker/release/Dockerfile
- scripts/installer/install-datafuse.sh
Add release docker image after release binary uploaded
fixes https://github.com/datafuselabs/datafuse/issues/1151
Unit Tests
> [Build/Release/CI] add release docker image

- .github/workflows/datafuse-performance-dispatch.yaml
Using release build instead of debug build for performance image and loose wait time
Fixes #issue
Unit Tests
> [CI] release build

- fusestore/store/src/meta_service/sled_tree.rs
- fusestore/store/src/meta_service/sled_tree_test.rs
> [store] feature: SledTree: add range() to get a list of key-value pairs

- .github/workflows/datafuse-perf-docker.yml
- .github/workflows/datafuse-performance-dispatch.yaml
Fix perf-tool build failure
- Bug Fix
Fixes #issue
Unit Tests
> docker build fix

- .github/workflows/datafuse-performance-dispatch.yaml
> [CI] perf test suit self hosted

- common/tracing/src/logging.rs
uniform style, use Layer prefix.
https://github.com/datafuselabs/datafuse/blob/master/common/tracing/src/logging.rs#L44
https://github.com/datafuselabs/datafuse/blob/master/common/tracing/src/logging.rs#L80
None
Unit Tests
> [tracing] uniform style.

- store/src/dfs/distributed_fs.rs
- store/src/meta_service/meta_service_impl.rs
- store/src/meta_service/raftmeta.rs
- store/src/meta_service/raftmeta_test.rs
- store/src/meta_service/state_machine.rs
fix: #1385
- New Feature
- #271
- #1080
> [store]: feature: use sled to store DFS file meta.

- store/src/meta_service/sled_tree.rs
- store/src/meta_service/sled_tree_test.rs
> [store] feature: SledTree: add update_and_fetch() to perform an atomic conditional update

- website/datafuse/docs/rfcs/cli/0001-cli-design.md
- website/datafuse/mkdocs.yml
Design of fusectl
- Website
Fixes #issue
Unit Tests
> [RFC] fusectl RFC

- common/io/src/binary_read.rs
- common/io/src/binary_read_test.rs
Fix read_opt_scalar and add testing.
- Bug Fix
- Add test
> Fix read_opt_scalar and add test

- Cargo.lock
- cli/Cargo.toml
- common/datablocks/Cargo.toml
- common/datavalues/Cargo.toml
- query/Cargo.toml
- query/src/catalogs/impls/remote_meta_store_client_test.rs
- store/Cargo.toml
- store/src/meta_service/raftmeta_test.rs
- bump comfy-table
- mark some flaky test, run them 3 times (powered by [flaky_test](https://github.com/denoland/flaky_test))
Fixes #issue
Unit Tests
> [*] bump comfy-table and mark some flaky test

- query/src/catalogs/impls/remote_meta_store_client.rs
- query/src/catalogs/impls/remote_meta_store_client_test.rs
Fix flaky test in `remote_meta_store_client_test.rs `
when returning Error from Mocked StoreApiServiceProvider, the time of constructing the ErrorCode is flaky (mainly due to that backtrace::new() is time-consuming), in some cases, larger than the default rpc timeout setting.  
- Bug Fix
Fixes #1449
Unit Tests
> fix flaky test #1449

- .github/workflows/datafuse-performance-dispatch.yaml
- Improvement
fixes https://github.com/datafuselabs/datafuse/issues/1453
Unit Tests
> [CI] more iterations

- .github/workflows/datafuse-release.yml
Currently docker release need qemu simulator installed, otherwise error will occur https://github.com/datafuselabs/datafuse/actions/runs/1124568502
- Bug Fix
- Other 
Fixes #issue
Unit Tests
> [Release] fix qemu issue during release

- .github/workflows/datafuse-performance-dispatch.yaml
- .github/workflows/slack-notify.yml
fix lint issue in slack notification
Fixes #issue
Unit Tests
> [CI/BUG] fix lint issue in workflow

- store/src/meta_service/sled_tree.rs
- store/src/meta_service/sled_tree_test.rs
> [store] feature: SledTree: rename range() to range_kvs(); make range() return an iter

- common/datavalues/src/arrays/builders/boolean_test.rs
- common/datavalues/src/arrays/builders/mod.rs
- common/datavalues/src/arrays/builders/primitive_test.rs
- common/datavalues/src/arrays/builders/utf8_test.rs
Add test for data array and builder 
- Testing
> Add test for array builder

- README.md
- website/datafuse/docs/overview/architecture.md
Datafuse design
Fixes #1464
Unit Tests
> DOC-1464: Datafuse design

- README.md
- website/datafuse/docs/overview/architecture.md
- website/datafuse/mkdocs.yml
Add whitepapers to website
Fixes #issue
Unit Tests
> DOC: Add whitepapers to website

- common/management/src/user/user_mgr.rs
Unfold the value of the for loop in place
None
Unit Tests
> [common/management] style

- common/exception/src/exception.rs
- common/store-api/src/storage_api.rs
- store/src/executor/action_handler_test.rs
- store/src/executor/storage_handlers.rs
- store/src/meta_service/applied_state.rs
- store/src/meta_service/cmd.rs
- store/src/meta_service/state_machine.rs
solve #1349 
- Improvement
Fixes #1349 
Unit Tests
> issue 1349

- query/src/sql/mod.rs
- query/src/sql/parser/ast/ast_display_test.rs
- query/src/sql/parser/ast/expression.rs
- query/src/sql/parser/ast/mod.rs
- query/src/sql/parser/ast/query.rs
- query/src/sql/parser/ast/statement.rs
- query/src/sql/parser/mod.rs
- query/src/sql/parser/transformer/mod.rs
- query/src/sql/parser/transformer/transform_sqlparser.rs
- query/src/sql/parser/transformer/transform_sqlparser_test.rs
This PR introduce a set of SQL AST, and transformer from AST produced by `sqlparser-rs`.
- Improvement
Fixes #issue
Unit Tests
> sql: introduce datafuse standard AST and transformer from `sqlparser-rs`

- query/src/sql/plan_parser.rs
chore: improve plan_tables_with_joins error
- Improvement: chore: improve plan_tables_with_joins error
> chore: improve plan_tables_with_joins error

- tests/perfs/perfs.yaml
Larger data sets contribute to the stability of test results
> [Perf] Larger data sets contribute to the stability of test results

- tests/perfs/perfs.yaml
Add Group By Single Aggr perf test case
> Add Group By Single Aggr perf test case

- .github/workflows/datafuse-performance-dispatch.yaml
Add slack notification on report url and set validation and retry policies for report file uploading
- Improvement
fixes https://github.com/datafuselabs/datafuse/issues/1532
fixes https://github.com/datafuselabs/datafuse/issues/1533
Unit Tests
> fix performance test flaky and add more slack supports

- .github/workflows/datafuse-perf-docker.yml
- .github/workflows/datafuse-performance-dispatch.yaml
fixes https://github.com/datafuselabs/datafuse/issues/1535
Unit Tests
> [Performance] debugging perf

- common/datavalues/src/arrays/ops/cast.rs
- common/datavalues/src/types/data_type_coercion.rs
- tests/suites/0_stateless/02_0002_function_cast.result
- tests/suites/0_stateless/02_0002_function_cast.sql
> [datavalues] complete null array cast

- website/datafuse/docs/sqlstatement/show-commands/show-tables.md
document about `show tables`
Fixes #1528 
no code
> [improvement] Add SHOW TABLES LIKE pattern and Where expr to doc

- query/src/sql/plan_parser.rs
> remove unused annotation

- common/datablocks/src/data_block.rs
Fix the review comments:
https://github.com/datafuselabs/datafuse/pull/1437#pullrequestreview-735496699
- Improvement
Fixes #1428
Unit Tests
> Improve the datablock last/first comments in IDX-1428

- .github/workflows/unit-tests.yml
- query/src/catalogs/impls/remote_meta_store_client_test.rs
- store/src/meta_service/raftmeta_test.rs
> [store]: refactor: turn off flaky_test.

- Cargo.lock
- common/exception/Cargo.toml
- query/Cargo.toml
- query/src/sql/parser/ast/expression.rs
- query/src/sql/parser/transformer/transform_sqlparser.rs
- bump sqlparser-rs, sync with upstream
- fix term, `Modulus` -> `Modulo`, see https://github.com/sqlparser-rs/sqlparser-rs/pull/335
- Improvement
Fixes #issue
Unit Tests
> [deps] bump sqlparser-rs, fix term

- website/datafuse/docs/sqlstatement/show-commands/show-tables.md
> [DOC] add SHOW TABLES FROM to document website

- docker/bootstrap.sh
- Bug Fix
fixes https://github.com/datafuselabs/datafuse/issues/1584
Unit Tests
> fix bug in datafuse-store docker release

- common/dal/README.md
- common/dal/src/blob_accessor.rs
- common/dal/src/impls/aws_s3/mod.rs
- common/dal/src/impls/aws_s3/s3.rs
- common/dal/src/impls/aws_s3/s3_input_stream.rs
- common/dal/src/impls/aws_s3/s3_input_stream_test.rs
- common/dal/src/impls/azure_blob.rs
- common/dal/src/impls/fuse_dfs.rs
- common/dal/src/impls/local.rs
- common/dal/src/impls/mod.rs
- common/dal/src/lib.rs
Add common/dal README
- Improvement
Unit Tests
> Add common/dal README

- query/src/datasources/system/databases_table.rs
- query/src/datasources/system/tables_table.rs
- query/src/interpreters/interpreter_database_create.rs
- query/src/interpreters/interpreter_database_drop.rs
- query/src/interpreters/interpreter_insert_into.rs
- query/src/interpreters/interpreter_show_create_table.rs
- query/src/interpreters/interpreter_table_create.rs
- query/src/interpreters/interpreter_table_drop.rs
- query/src/sessions/context.rs
- query/src/sessions/context_shared.rs
- query/src/sessions/session.rs
- query/src/sessions/sessions.rs
- query/src/sql/plan_parser.rs
Rename datasource to catalog
- Improvement
Fixes #1635 
Unit Tests
> [1635]Rename datasource to catalog

- common/streams/src/stream_limit_by.rs
Use arrow2 bitmap to improve memory usage
- Improvement
None
Unit Tests
> [common/streams] use arrow2 bitmap to improve memory usage

- query/src/api/rpc_service.rs
- query/src/servers/clickhouse/clickhouse_handler.rs
- query/src/servers/mysql/mysql_handler.rs
Improve error msg for address in use
- Improvement
Fixes #1629 
Unit Tests
> [1629]Improve error msg for address in use

- query/src/servers/mysql/mysql_handler.rs
> Fix mysqlhandler log bug

- .github/workflows/unit-tests.yml
- cli/tests/integration_tests.rs
- scripts/ci/ci-run-unit-tests.sh
> Using #[ignore] to skip datafuse-cli tests

- .github/workflows/datafuse-release.yml
release broken when find openssl dependencies, manually reinstall them should fix the problem
- Bug Fix
fixes https://github.com/datafuselabs/datafuse/issues/1640
Unit Tests
> [CI/Bug Fix] Fix release cross build pipeline

- query/benches/suites/mod.rs
remove unused declaration `use datafuse_query::sessions::SessionManager;`
No issue
Unit Tests
> [query/benches] remove unused declaration

- common/streams/src/sources/source.rs
Code style: declaration paragraph separation
No issue
Unit Tests
> [common/streams] style

- .github/workflows/cargo.yml
- common/functions/src/aggregates/aggregate_stddev_pop.rs
enable lint workflow
- Improvement
Fixes #issue
Unit Tests
> enable lint workflow

- tests/datafuse-test
Add test name validator
- Improvement
Fixes #issue
Unit Tests
> Add test name validator

- scripts/deploy/datafuse-query-cluster-3-nodes.sh
- scripts/deploy/datafuse-query-standalone.sh
change store log level to ERROR
- Improvement
Fixes #1687 
Unit Tests
> CI-1687: change store log level to ERROR

- Cargo.lock
- query/Cargo.toml
- query/src/metrics/metric_service.rs
- query/src/metrics/metric_service_test.rs
Fully migrated from warp to axum in query part, 
Store needs to migrate in further works
- Improvement
fixes https://github.com/datafuselabs/datafuse/issues/1578
Unit Tests
> [Refactor] remove warp from query crate

- common/streams/src/lib.rs
- common/streams/src/stream_limit_by.rs
- common/streams/src/stream_limit_by_test.rs
1. A little optimization for the loop when limit value is reached (not necessary to visit every row)
2. Added unit test
- Improvement
- Testing
> A little optimization and unit test for LimitByStream

- common/dal/src/blob_accessor.rs
- common/dal/src/impls/aws_s3/s3.rs
- common/dal/src/impls/local.rs
Improvement:  Streaming put for DAL
- Improvement
Fixes #1598
Unit Tests
> Improvement:  Streaming put for DAL

- website/datafuse/docs/sqlstatement/datetime-functions/now.md
- website/datafuse/docs/sqlstatement/datetime-functions/today.md
- website/datafuse/docs/sqlstatement/datetime-functions/tomorrow.md
- website/datafuse/docs/sqlstatement/datetime-functions/yesterday.md
- website/datafuse/mkdocs.yml
document NOW/TODAY/TOMORROW/YESTERDAY function
#1706 
Unit Tests
> DOC-1706: document NOW/TODAY/TOMORROW/YESTERDAY function

- website/datafuse/docs/sqlstatement/aggregate-functions/aggregate-stddev-pop.md
- website/datafuse/mkdocs.yml
add STDDEV_POP function to list
Fixes N/A
Unit Tests
> DOC: add STDDEV_POP function to list

- common/exception/src/exception.rs
- common/management/src/namespace/mod.rs
- common/management/src/namespace/namespace_api.rs
- common/management/src/namespace/namespace_mgr.rs
- common/management/src/namespace/namespace_mgr_test.rs
- query/src/configs/config.rs
- query/src/configs/config_test.rs
1. Refine the Config ENV variable name to prefix with the Group name, `LOG_/QUERY_/META_/STORE_`
2. Add `tenant` and `namespace` to QueryConfig group
3. Add `common/management/namespace` mod
- Improvement
Part-1 of #1700 
Fixes #1724 
Unit Tests
> ISSUE-1700: user namespace API

- query/src/configs/config.rs
- query/src/datasources/system/configs_table.rs
- query/src/datasources/system/configs_table_test.rs
- query/src/datasources/system/mod.rs
- query/src/datasources/system/system_database.rs
- query/src/datasources/system/tables_table_test.rs
Add config table
- New Feature
Fixes #1630 
Unit Tests
> [Feature]Add config table

- common/datavalues/src/arrays/ops/agg.rs
- Improvement: Fix aggregation error message
fixes #1741
Unit Tests
> chore: fix ArrayAgg error message

- README.md
- website/datafuse/docs/sqlstatement/datetime-functions/toyyyymm.md
- website/datafuse/docs/sqlstatement/string-functions/substring.md
- website/datafuse/mkdocs.yml
* Add toYYYYMM date function
* Improve the substring function
Fixes #1706 
PR #1726 
Unit Tests
> DOC-1706: add toYYYYMM date function

- Cargo.lock
- common/arrow/Cargo.toml
- common/datavalues/src/arrays/list/mod.rs
- common/datavalues/src/arrays/ops/cast.rs
- common/datavalues/src/arrays/primitive/mod.rs
- common/datavalues/src/arrays/string/mod.rs
- common/datavalues/src/columns/data_column.rs
- common/datavalues/src/data_field.rs
- common/datavalues/src/data_value.rs
- common/datavalues/src/types/data_type.rs
- common/datavalues/src/types/data_type_coercion.rs
- common/datavalues/src/types/physical_data_type.rs
- common/datavalues/src/types/serializations/mod.rs
- common/functions/src/scalars/dates/date_function_test.rs
- common/functions/src/scalars/dates/now.rs
- common/functions/src/scalars/dates/number_function.rs
- common/functions/src/scalars/expressions/expression.rs
- common/functions/src/scalars/hashes/siphash.rs
- query/src/servers/clickhouse/writers/query_writer.rs
- query/src/servers/mysql/writers/query_result_writer.rs
- query/src/sql/sql_common.rs
- bump arrow2
- Add timezone support for DateTime32
- Improvement
Fixes #1680
Unit Tests
> Add timezone support for DateTime32

- query/src/datasources/system/engines_table.rs
- query/src/datasources/system/engines_table_test.rs
- query/src/datasources/system/mod.rs
- query/src/datasources/system/system_database.rs
- query/src/datasources/system/tables_table_test.rs
Support `system.engines` table
- New Feature
Fixes #1721
Unit Tests
> support system.engines table

- common/datablocks/src/data_block.rs
- common/datavalues/src/arrays/boolean/mod.rs
- common/datavalues/src/arrays/list/mod.rs
- common/datavalues/src/arrays/null/mod.rs
- common/datavalues/src/arrays/primitive/mod.rs
- common/datavalues/src/arrays/string/mod.rs
- common/datavalues/src/arrays/struct/mod.rs
- common/datavalues/src/columns/data_column.rs
- common/datavalues/src/series/series_impl.rs
- common/datavalues/src/series/wrap.rs
- Better datablock convert to RecordBatch
- Fix `bool(&self)` which matches Null DataType cc@yjhmelody
- Bug Fix
Fixes #issue
Unit Tests
> Improve recordbatch

- query/src/servers/mysql/writers/query_result_writer.rs
> Improve mysql query result writer

- README.md
Add note of ClickHouse/arrow in README
Fixes #issue
Unit Tests
> Add note of ClickHouse/arrow in README

- Cargo.lock
- query/Cargo.toml
- query/src/datasources/system/credits_table.rs
- query/src/datasources/system/credits_table_test.rs
- query/src/datasources/system/mod.rs
- query/src/datasources/system/system_database.rs
- query/src/datasources/system/tables_table_test.rs
- website/datafuse/docs/system/system-tables.md
add a basic credits table. i will submit a patch for upstream to bump deps.
**todo**
**example**
```
mysql> SELECT * FROM system.credits LIMIT 20;
+-------------------+---------+---------------------------+
| name              | version | license                   |
+-------------------+---------+---------------------------+
| addr2line         | 0.16.0  | Apache-2.0 OR MIT         |
| adler             | 1.0.2   | 0BSD OR Apache-2.0 OR MIT |
| ahash             | 0.6.3   | Apache-2.0 OR MIT         |
| ahash             | 0.7.4   | Apache-2.0 OR MIT         |
| aho-corasick      | 0.7.18  | MIT OR Unlicense          |
| ansi_term         | 0.9.0   | MIT …
```
> [feat] add basic credits table

- website/datafuse/mkdocs.yml
Fix toYYYYMMDD and toYYYYMMDDhhmmss function document.
PR #1767
> [DOC] Fix toYYYYMMDD and toYYYYMMDDhhmmss function doc

- common/datavalues/src/arrays/boolean/mod.rs
- common/datavalues/src/data_array_filter.rs
- common/datavalues/src/series/comparison.rs
- common/functions/src/aggregates/aggregate_combinator_if.rs
- common/functions/src/aggregates/aggregate_count.rs
- tests/suites/0_stateless/03_0003_select_group_by.result
- tests/suites/0_stateless/03_0003_select_group_by.sql
fix count function with not null column
- Bug Fix
fixes #1786
> ISSUE-1786 try fix count function with not null column

- website/datafuse/docs/sqlstatement/data-types/data-type-real-number.md
- website/datafuse/docs/sqlstatement/data-types/data-type-time-date-types.md
- website/datafuse/mkdocs.yml
> DOC-1315: add date and time types

- store/src/configs/config.rs
Similar to https://github.com/datafuselabs/databend/blob/master/query/src/configs/config.rs
- Improvement
Fixes #issue
Unit Tests
> [Store] support defaulting in store

- website/databend/docs/rfcs/query/0005-new-sql-planner-framework.md
> RFC: New SQL planner framework

- common/datavalues/src/columns/arithmetic.rs
- common/datavalues/src/series/arithmetic.rs
- common/datavalues/src/types/data_type_coercion.rs
- common/functions/src/scalars/arithmetics/arithmetic.rs
- query/src/sql/plan_parser.rs
- tests/suites/0_stateless/02_0000_function_arithmetic.result
- tests/suites/0_stateless/02_0000_function_arithmetic.sql
> ISSUE-1841: fix unary arithmetics function err

- docker/databend-query-docker.toml
Separate configuration file for docker into groups
- Bug Fix
fixes #1843 
Unit Tests
> [Bug Fix] update docker config toml

- .github/workflows/databend-release.yml
temporary Remove arm/v6 and arm/v7 release due to compiler issue https://github.com/datafuselabs/databend/issues/1859
works on arm64 architecture https://github.com/ZhiHanZ/databend/actions/runs/1242061922
- Bug Fix
Fixes #1850 
Unit Tests
> [Build/CI] Fix release ci

- query/src/pipelines/transforms/transform_aggregator_partial.rs
> prefer to use Vec::with_capacity instead of vec!

- query/src/catalogs/impls/catalog/metastore_catalog.rs
- Improvement
Fixes #1868
- issue #1868
Unit Tests
> using conf.meta to detect meta service mode

- store/README.md
After sepreating `store` to `store` and `metasvr`, the store/README is odd.
- Improvement
Fixes #1888
Unit Tests
> STORE-1888: improvement the readme

- common/management/src/user/user_api.rs
- common/management/src/user/user_mgr.rs
- common/management/src/user/user_mgr_test.rs
- common/management/src/user/utils.rs
This PR:
1. add tenant to user mgr api
- Improvement
Fixes #1864 
Unit Tests
> MANAGEMENT-1864: add tenant to user mgr api

- .github/workflows/databend-perf-docker.yml
Fix  performance tool building CI pipeline
Fixes #1907 
Unit Tests
> [CI] Fix performance(update dependencies)

- query/src/sql/parser/transformer/transform_sqlparser.rs
- query/src/sql/parser/transformer/transform_sqlparser_test.rs
solve #1512 
- New Feature
Fixes #1512 
Unit Tests
> issue-1512

- common/management/src/user/user_api.rs
- common/management/src/user/user_mgr.rs
- common/management/src/user/user_mgr_test.rs
fix 
-  #1931
- Improvement
Fixes #1931
Unit Tests
> ISSUE-1931: UserMgr no longer takes &mut self

- query/src/catalogs/impls/meta_backends/remote_meta_backend.rs
change the do_block to runtime block_on
- Improvement
Fixes #1933
Unit Tests
> CATALOGS-1933: change the do_block to runtime block_on

- .github/workflows/databend-perf-docker.yml
- docker/perf-tool/Dockerfile
fix qemu issue in perf-tool docker cross compile
Fixes #issue
Unit Tests
> [CI] fix qemu issue in perf-tool docker cross compile

- query/src/sql/parser/transformer/transform_sqlparser.rs
- query/src/sql/parser/transformer/transform_sqlparser_test.rs
- Bug Fix
Fixes a bug introduced in  #1916
Unit Tests
> fix get_database_and_table_from_idents

- common/planners/src/plan_expression_rewriter.rs
- common/planners/src/plan_expression_visitor.rs
> Adjust comment

- common/datavalues/src/columns/nullable.rs
- common/functions/src/scalars/function_factory.rs
- common/functions/src/scalars/mod.rs
- common/functions/src/scalars/nullables/is_not_null.rs
- common/functions/src/scalars/nullables/is_null.rs
- common/functions/src/scalars/nullables/mod.rs
- common/functions/src/scalars/nullables/nullable.rs
- common/functions/src/scalars/nullables/nullable_test.rs
- query/src/sql/plan_parser.rs
- tests/suites/0_stateless/02_0013_function_nullables.result
- tests/suites/0_stateless/02_0013_function_nullables.sql
support expr isNull and isNotNull
- New Feature
- Bug Fix
Fixes #1306 
Unit Tests
> ISSUE-1306: support expr isNull and isNotNull

- website/databend/docs/sqlstatement/nullable-functions/isnotnull.md
- website/databend/docs/sqlstatement/nullable-functions/isnull.md
- website/databend/mkdocs.yml
Add `isNull` and `isNotNull` docments
Fixes #1306
> docs: add nullable function docments

- .cargo/config
- .github/workflows/databend-performance-dispatch.yaml
- docker/cache/Dockerfile
- docker/databend-query-docker.toml
- tests/perfs/perfs.py
1. Updated docker comply with cluster mode management
2. Fix deployment issues happened in perf-tool
3. Striped arm release
Striped performance test result:
current image: striped release (datafuselabs/databend:perf-stripe)
reference image: v0.4.118 release(latest) (datafuselabs/databend:perf-v0.4.118-nightly)
result:
https://test-1306375239.cos.accelerate.myqcloud.com/report/1888//233/performance.html
- Improvement
followup https://github.com/datafuselabs/databend/pull/1959
Unit Tests
> [Build/CI/Release] Update docker and striped arm release

- common/management/Cargo.toml
- Improvement
- Fix the issue mentioned in #1940
> [common/management] refactor: management only need common-kv for test

- docker/databend-query-docker.toml
- query/src/configs/config.rs
- query/src/configs/config_test.rs
- query/src/datasources/database/system/configs_table_test.rs
- scripts/deploy/config/databend-query-node-1.toml
- scripts/deploy/config/databend-query-node-2.toml
- scripts/deploy/config/databend-query-node-3.toml
Signed-off-by: jyz0309 <45495947@qq.com>
Remove disable_local_database_engine config
- Improvement
Fixes #1977 
Unit Tests
> Remove disable_local_database_engine config

- Cargo.lock
- common/base/Cargo.toml
- common/base/src/lib.rs
- common/base/src/uniq_id.rs
- common/raft-store/src/testing.rs
- common/sled-store/src/sled_tree_test.rs
- dfs/src/tests/service.rs
- kvsrv/src/tests/service.rs
- query/src/clusters/cluster.rs
Extract uniq name to common base
> Extract uniq name to common base

- Cargo.lock
- common/arrow/Cargo.toml
- common/datavalues/src/arrays/boolean/mod.rs
- common/datavalues/src/arrays/comparison.rs
- common/datavalues/src/arrays/ops/agg.rs
- common/datavalues/src/arrays/ops/apply.rs
- common/datavalues/src/arrays/primitive/mod.rs
- common/datavalues/src/arrays/string/mod.rs
- common/datavalues/src/utils.rs
- common/exception/Cargo.toml
- common/functions/src/aggregates/aggregate_combinator_if.rs
- common/functions/src/scalars/dates/interval_function.rs
- query/Cargo.toml
- query/src/sql/parser/ast/ast_display_test.rs
- query/src/sql/parser/ast/expression.rs
- query/src/sql/parser/transformer/transform_sqlparser.rs
- query/src/sql/sql_common.rs
- query/src/sql/sql_parser_test.rs
> [deps] bump arrow2, parquet2, sqlparser

- query/src/catalogs/database.rs
- query/src/datasources/database/default/default_database.rs
- query/src/datasources/database/example/example_database.rs
- query/src/datasources/database/system/system_database.rs
> [query]: refactor: remove MetaBackend::exists_table

- query/src/catalogs/catalog.rs
- query/src/catalogs/impls/catalog/metastore_catalog.rs
- query/src/catalogs/impls/catalog/overlaid_catalog.rs
- query/src/catalogs/impls/catalog/system_catalog.rs
- query/src/catalogs/impls/meta_backends/embedded_meta_backend.rs
- query/src/catalogs/impls/meta_backends/remote_meta_backend.rs
- query/src/catalogs/meta_backend.rs
> [query] refactor: remove MetaBackend::exists_database

- common/meta-apis/api/src/meta_api.rs
- common/store-api-sdk/src/impl_flights/meta_api_impl.rs
> [query] refactor: remove unused MetaApi::commit_table

- common/meta-apis/api/src/meta_api.rs
- common/meta-apis/vo/src/lib.rs
- common/store-api-sdk/src/impl_flights/meta_api_impl.rs
- dfs/src/executor/action_handler_test.rs
- dfs/src/executor/meta_handlers.rs
- query/src/catalogs/impls/catalog/metastore_catalog.rs
- query/src/catalogs/impls/meta_backends/embedded_meta_backend.rs
- query/src/catalogs/impls/meta_backends/remote_meta_backend.rs
- query/src/catalogs/meta_backend.rs
- query/src/datasources/database/default/default_database_factory.rs
- query/src/datasources/database/example/example_databases.rs
- query/src/datasources/database_engine.rs
> [query] refactor: merge GetDatabaseActionResult and DatabaseInfo

- common/meta-apis/api/src/meta_api.rs
- common/meta-apis/vo/src/lib.rs
- query/src/catalogs/meta_backend.rs
> [common/meta-api] refactor: sort methods

- query/src/catalogs/catalog.rs
- query/src/catalogs/impls/catalog/metastore_catalog.rs
- query/src/catalogs/impls/catalog/overlaid_catalog.rs
- query/src/catalogs/impls/catalog/system_catalog.rs
- query/src/catalogs/impls/meta_backends/embedded_meta_backend.rs
- query/src/catalogs/impls/meta_backends/remote_meta_backend.rs
- query/src/catalogs/meta_backend.rs
- query/src/datasources/database/default/default_database.rs
- query/src/datasources/database/example/example_database.rs
> [query] refactor: create-table in MetaBackend and Catalog should return CreateDatabaseReply

- kvsrv/src/executor/meta_handlers.rs
resolve code conflicts
- Bug Fix
Fixes #issue
Unit Tests
> [fix] resolve code conflicts

- common/planners/src/plan_expression.rs
- query/src/optimizers/mod.rs
- query/src/optimizers/optimizer.rs
- query/src/optimizers/optimizer_constant_folding.rs
- query/src/optimizers/optimizer_expression_transform.rs
- query/src/optimizers/optimizer_expression_transform_test.rs
- query/src/optimizers/optimizer_projection_push_down.rs
- query/src/optimizers/utils.rs
- query/src/sql/plan_parser.rs
Add expression transform optimizer, support NOT transformer
- New Feature
- Improvement
Fixes #2037 
Unit Tests
> ISSUE-2037: add expression transform optimizer

- query/src/optimizers/optimizer_expression_transform.rs
- query/src/optimizers/optimizer_expression_transform_test.rs
- query/src/sql/plan_parser.rs
- Improvement
Fixes #2037
Unit Tests
> expression transformer case insenstive

- common/functions/src/aggregates/aggregate_arg_min_max.rs
- common/functions/src/aggregates/aggregate_avg.rs
- common/functions/src/aggregates/aggregate_combinator_distinct.rs
- common/functions/src/aggregates/aggregate_combinator_if.rs
- common/functions/src/aggregates/aggregate_combinator_test.rs
- common/functions/src/aggregates/aggregate_count.rs
- common/functions/src/aggregates/aggregate_function_factory.rs
- common/functions/src/aggregates/aggregate_function_test.rs
- common/functions/src/aggregates/aggregate_min_max.rs
- common/functions/src/aggregates/aggregate_stddev_pop.rs
- common/functions/src/aggregates/aggregate_sum.rs
- common/functions/src/aggregates/aggregate_window_funnel.rs
- common/functions/src/aggregates/aggregator.rs
- common/planners/src/plan_expression.rs
- common/planners/src/plan_expression_action.rs
- query/src/datasources/database/system/functions_table.rs
- query/src/functions/context_function.rs
- query/src/sql/plan_parser.rs
Remove IndexMap for AggregateFunctionFactory(same as FunctionFactory)
related #2043
> Remove IndexMap for AggregateFunctionFactory

- common/functions/src/scalars/function_factory.rs
- query/src/optimizers/optimizer_constant_folding.rs
- query/src/optimizers/optimizer_expression_transform.rs
- query/src/optimizers/optimizer_expression_transform_test.rs
Using function features for expression transform optimizer
related #2038
> Using function features for expression transform optimizer

- Makefile
- scripts/build/build-debug.sh
- scripts/build/build-native.sh
- scripts/build/build-release.sh
- scripts/deploy/databend-query-standalone.sh
rm meta first when stateless-test
- Bug Fix
Related #2049 
Unit Tests
> [temp-fix] rm meta first when stateless-test

- .github/workflows/github-pages.yml
- website/databend/.gitignore
- website/databend/Makefile
- website/databend/docs/policies/license.md
- website/databend/setup.py
- auto gen credits.md
- add license.md
- Website
Fixes #1955 
Unit Tests
> [docs] add license and credits

- common/functions/src/aggregates/aggregate_function.rs
- scripts/deploy/databend-query-standalone.sh
Fix script standalone
- Bug Fix
Unit Tests
> Fix script standalone

- common/dal/src/impls/aws_s3/s3.rs
- common/dal/src/impls/aws_s3/s3_input_stream_test.rs
new constructor of `Dal::S3`
```
pub fn with_credentials(
region: &str,
bucket: String,
access_key_id: String,
secret_accesses_key: String,
) -> Result<Self>
```
- Improvement
None
Unit Tests (with local s3 account, ignored in CI)
> new dal-s3 constructor (with_credentials)

- common/dal/src/schemes.rs
- common/dal/src/schemes_test.rs
- query/src/configs/config_storage.rs
- query/src/configs/config_test.rs
- query/src/configs/mod.rs
- query/src/datasources/common/dal_builder.rs
- query/src/datasources/common/dal_builder_test.rs
- scripts/deploy/config/databend-query-node-1.toml
- scripts/deploy/config/databend-query-node-2.toml
- scripts/deploy/config/databend-query-node-3.toml
- refactor 
Fixes #2517
Unit Tests
> refactor: refine the variable name for azure storage blob

- common/datavalues/src/arrays/arithmetic_test.rs
- common/functions/src/scalars/dates/date_function_test.rs
- common/functions/src/scalars/dates/number_function.rs
- Improvement
Fixed #2464
Unit Tests
> ISSUE-2464:Data-driven testing style improvement

- Cargo.lock
- Cargo.toml
- common/metrics/Cargo.toml
- common/metrics/src/recorder.rs
- common/tracing/Cargo.toml
- metasrv/Cargo.toml
bump tracing*
Fixes #2436 #2437 #2440 #2461
Unit Tests
> [deps] bump tracing*

- common/planners/src/lib.rs
- common/planners/src/plan_node.rs
- common/planners/src/plan_rewriter.rs
- common/planners/src/plan_user_create.rs
- common/planners/src/plan_visitor.rs
- query/src/sql/plan_parser.rs
- query/src/sql/sql_parser.rs
- query/src/sql/sql_parser_test.rs
- query/src/sql/sql_statement.rs
Make sql parser support create user statement 
- New Feature
Fixes #2160 
Unit Tests
> Support create user statement step one

- common/meta/embedded/src/meta_api_impl.rs
- common/meta/raft-store/src/sled_key_spaces.rs
- common/meta/raft-store/src/state_machine/applied_state.rs
- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/raft-store/src/state_machine/state_machine_test.rs
- common/meta/types/src/cmd.rs
- metasrv/src/executor/meta_handlers.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/meta_service/raftmeta_test.rs
> [common/meta]: meta-store only need to store an id for a database record.

- website/databend/docs/development/release-channels.md
- website/databend/docs/development/roadmap.md
- website/databend/docs/development/tracing.md
- website/databend/mkdocs.yml
1. Add databend release channels document
2. Re-order the development
3. Expand the `tracing` document show
4. Update roadmap
Fixes #issue
Unit Tests
> DOC: add databend release channels

- README.md
- website/databend/docs/overview/architecture.md
Introduce serveless
- Improvement
Fixes #issue
Unit Tests
> DOC: Introduce serveless

- cli/src/cmds/queries/query.rs
> In the query mode, we should pre-check the databend-query http handler API is alive or not.
after:
```
[local] [sql]> up
[failed] ❌ Query command precheck failed, error Unknown("cannot connect to healthiness probe: http://127.0.0.1:8080/v1/health"), please run `bendctl cluster create` to create a new local cluster or '\admin' switch to the admin mode
```
- Improvement
Fixes https://github.com/datafuselabs/databend/issues/2547
> [cli] precheck health of databend-query for cli query mode

- common/meta/raft-store/src/state/raft_state_kv.rs
- common/meta/raft-store/src/state_machine/client_last_resp.rs
- common/meta/raft-store/src/state_machine/state_machine_meta.rs
- common/meta/raft-store/src/state_machine/table_lookup.rs
- common/meta/sled-store/src/seq_num.rs
- common/meta/sled-store/src/seq_value.rs
- common/meta/sled-store/src/sled_key_space.rs
- common/meta/sled-store/src/sled_serde.rs
- common/meta/sled-store/src/testing/fake_key_spaces.rs
- common/meta/sled-store/src/testing/fake_state_machine_meta.rs
- common/meta/types/src/cluster.rs
> [common/meta] refactor: impl SledSerde for T; remove per-type impl of SledSerde

- .gitignore
Add OS-related git ignore files
- Other
> Add OS related gitignore

- query/src/servers/clickhouse/clickhouse_handler_test.rs
use unique table name in test case `test_clickhouse_insert_to_fuse_table`
- Bug Fix
Fixes #2589
Unit Tests
> ISSUE-2589: use unique table name in insertion test

- website/databend/docs/sqlstatement/numeric-functions/pi.md
- website/databend/mkdocs.yml
Add numeric functions category and pi doc
Fixes #2597 
Unit Tests
> DOC-2597: Add numeric functions category and pi doc

- query/src/catalogs/impls/catalog/metastore_catalog.rs
The data for in-memory tables has been moved to
`MetaStoreCatalog.in_memory_data` thus `db_instances` can be removed.
- Improvement
> [query] refactor: remove db_instances

- query/src/servers/http/v1/statement.rs
- query/src/servers/http/v1/statement_test.rs
Add db URL parameter for support specify the database, like: 
`curl --location --request POST 'localhost:8001/v1/statement/?db=system'`
- Improvement
Fixes https://github.com/datafuselabs/databend/issues/2575
Unit Tests
> [query] add db URL parameter for support specify the database

- website/databend/docs/sqlstatement/numeric-functions/cos.md
- website/databend/docs/sqlstatement/numeric-functions/cot.md
- website/databend/docs/sqlstatement/numeric-functions/sin.md
- website/databend/docs/sqlstatement/numeric-functions/tan.md
- website/databend/mkdocs.yml
Add doc for trigonometric function
Fixes https://github.com/datafuselabs/databend/issues/2618
Unit Tests
> [DOC] add doc for trigonometric function

- cli/src/cmds/processor.rs
- Improvement
Fixes https://github.com/datafuselabs/databend/issues/2571
Unit Tests
> [cli] ignore ctrl-c on sql-mode

- common/datavalues/src/types/serializations/number.rs
- tests/suites/0_stateless/09_0001_remote_insert.sql
- Improvement
Fixes #issue
Unit Tests
> Make deser support partial_parse from binary

- website/databend/docs/sqlstatement/numeric-functions/crc32.md
- website/databend/mkdocs.yml
Add doc for crc32 function
Fixes https://github.com/datafuselabs/databend/issues/2620
Unit Tests
> [DOC] add doc for crc32 function

- website/databend/docs/cli/cli.md
Add bendctl demo operation on AWS EC2
Fixes #issue
Unit Tests
> DOC: Add bendctl demo operation on AWS EC2

- Makefile
- cli/src/cmds/clusters/add.rs
- cli/src/cmds/clusters/cluster.rs
- cli/src/cmds/clusters/create.rs
- cli/src/cmds/clusters/mod.rs
- cli/src/cmds/clusters/view.rs
- cli/tests/it/clusters/create.rs
build a three node cluster, each has 2 cpu quote
```bash
ADD_NODES=2 make cluster
```
- New Feature
- Improvement
Fixes #https://github.com/datafuselabs/databend/issues/2511
Unit Tests
> [CLI] Support add api and support local deployment with a singe line of code

- common/datavalues/Cargo.toml
- common/datavalues/src/arrays/boolean/mod.rs
- common/datavalues/src/arrays/mod.rs
- common/datavalues/src/arrays/ops/mod.rs
- common/datavalues/src/arrays/primitive/mod.rs
- common/datavalues/src/arrays/string/mod.rs
- common/datavalues/src/lib.rs
- common/datavalues/tests/it/arrays/arithmetic.rs
- common/datavalues/tests/it/arrays/boolean.rs
- common/datavalues/tests/it/arrays/mod.rs
- common/datavalues/tests/it/arrays/ops/agg.rs
- common/datavalues/tests/it/arrays/ops/apply.rs
- common/datavalues/tests/it/arrays/ops/cast.rs
- common/datavalues/tests/it/arrays/ops/contain.rs
- common/datavalues/tests/it/arrays/ops/fill.rs
- common/datavalues/tests/it/arrays/ops/group_hash.rs
- common/datavalues/tests/it/arrays/ops/if.rs
- common/datavalues/tests/it/arrays/ops/mod.rs
- common/datavalues/tests/it/arrays/ops/scatter.rs
- common/datavalues/tests/it/arrays/ops/take.rs
- common/datavalues/tests/it/arrays/ops/take_random.rs
- common/datavalues/tests/it/arrays/primitive.rs
- common/datavalues/tests/it/arrays/string.rs
- common/datavalues/tests/it/data_array_filter.rs
- common/datavalues/tests/it/main.rs
- common/datavalues/tests/it/series.rs
apply the new test style to common_datavalues
Part of #1866 
Unit Tests
> [test] apply the new test style to common_datavalues

- common/management/src/user/user_api.rs
- common/management/src/user/user_mgr.rs
- common/management/src/user/user_mgr_test.rs
- query/src/interpreters/interpreter_user_create.rs
- query/src/users/user.rs
- query/src/users/user_mgr.rs
- query/src/users/user_mgr_test.rs
Add host_name in user struct
- New Feature
Fixes #2160 
Unit Tests
> [Feature]Add host_name field

- website/databend/docs/sqlstatement/numeric-functions/degrees.md
- website/databend/docs/sqlstatement/numeric-functions/radians.md
- website/databend/mkdocs.yml
Add doc for angle function.
Fixes https://github.com/datafuselabs/databend/issues/2658
Unit Tests
> [DOC] Add doc for angle function

- common/base/Cargo.toml
- common/base/src/lib.rs
- common/base/tests/it/main.rs
- common/base/tests/it/progress.rs
- common/base/tests/it/runtime.rs
- common/base/tests/it/stoppable.rs
apply the new test style to common_base
Part of #1866
Unit Tests
> [test] apply the new test style to common_base

- common/datavalues/src/arrays/ops/like.rs
Format code logic https://github.com/datafuselabs/databend/pull/2661#discussion_r743406762
> Format code

- Cargo.lock
- common/datavalues/src/arrays/ops/like.rs
- common/exception/Cargo.toml
- query/Cargo.toml
- tests/suites/0_stateless/00_0000_dummy_select_1.result
- tests/suites/0_stateless/00_0000_dummy_select_1.sql
- tests/suites/0_stateless/02_0005_function_compare.result
- tests/suites/0_stateless/02_0005_function_compare.sql
Add process escape character in quoted string.
- Bug Fix
Fixes #2626 
> ISSUE-2626: Bump sqlparser-rs

- common/management/src/user/user_api.rs
- common/management/src/user/user_mgr.rs
- common/management/src/user/user_mgr_test.rs
- common/planners/src/plan_user_create.rs
- query/src/catalogs/impls/catalog/system_catalog.rs
- query/src/datasources/database/system/mod.rs
- query/src/datasources/database/system/tables_table_test.rs
- query/src/datasources/database/system/users_table.rs
- query/src/datasources/database/system/users_table_test.rs
- query/src/interpreters/interpreter_user_create.rs
- query/src/sql/plan_parser.rs
- query/src/sql/sql_parser.rs
- query/src/sql/sql_parser_test.rs
- query/src/sql/sql_statement.rs
- query/src/users/user.rs
- query/src/users/user_mgr_test.rs
Add system users table
- New Feature
Fixes #2650 
Unit Tests
> [Feature]Add system users table

- website/databend/docs/sqlstatement/user-management/user-management-create-user.md
- website/databend/mkdocs.yml
Add user management create user
Fixes #2685 
Unit Tests
> DOC-2685: Add user management create user

- .github/workflows/databend-release.yml
> [Release] fix lint issue in release page

- .licenserc.yaml
- metasrv/build.rs
- metasrv/src/lib.rs
- metasrv/src/meta_service/meta_service_impl.rs
- metasrv/src/meta_service/meta_service_impl_test.rs
- metasrv/src/meta_service/network.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/proto/meta.rs
- metasrv/src/proto/mod.rs
- metasrv/src/tests/service.rs
> [metasrv] refactor: embed generated proto codes; make it easier to navigate

- website/databend/mkdocs.yml
> databend.rs: add weekly link

- .github/workflows/databend-release.yml
https://github.com/ZhiHanZ/databend/actions/runs/1435129123
Fixes #issue
Unit Tests
> [Release] lint on release

- Cargo.lock
- common/management/src/namespace/namespace_mgr_test.rs
- common/management/src/user/user_mgr.rs
- common/management/src/user/user_mgr_test.rs
- common/meta/api/src/kv_api_test_suite.rs
- common/meta/embedded/src/kv_api_impl.rs
- common/meta/embedded/src/meta_api_impl.rs
- common/meta/raft-store/Cargo.toml
- common/meta/raft-store/src/state_machine/mod.rs
- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/raft-store/src/state_machine/sm_kv_api_impl.rs
- common/meta/raft-store/src/state_machine/state_machine_test.rs
- common/meta/types/src/kv_reply.rs
- metasrv/Cargo.toml
- metasrv/src/executor/kv_handlers.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/tests/flight/metasrv_flight_api.rs
> [common/meta/raft-store] refactor: impl kv_api for StateMachine

- query/src/servers/clickhouse/clickhouse_handler_test.rs
> disable flaky test temporary

- .github/workflows/cargo.yml
- .github/workflows/databend-build.yml
- .github/workflows/databend-docker.yml
- .github/workflows/embedded-meta-test.yml
- .github/workflows/pr-audit.yml
- .github/workflows/stateless-tests-cluster.yml
- .github/workflows/stateless-tests-standalone.yml
- .github/workflows/unit-tests.yml
ci: ignore some paths
- website/
- *.md
Fixes #issue
Unit Tests
> [ci] ignore some paths

- common/management/src/user/user_api.rs
- common/management/src/user/user_mgr.rs
- common/management/src/user/user_mgr_test.rs
- query/src/datasources/database/system/users_table.rs
- query/src/servers/clickhouse/interactive_worker.rs
- query/src/servers/mysql/mysql_interactive_worker.rs
- query/src/users/user_mgr.rs
- query/src/users/user_mgr_test.rs
Fix create users with different hostnames.
- Bug Fix
Fixes https://github.com/datafuselabs/databend/issues/2695
Unit Tests
> [user] fix create users with different hostnames

- common/context/Cargo.toml
- common/context/src/lib.rs
- common/context/tests/it/main.rs
apply the new test style to common-context
- Improvement
Related #1866
Unit Tests
> [test] apply the new test style to common-context

- common/dal/Cargo.toml
- common/dal/README.md
- common/dal/src/impls/azure_blob/mod.rs
- common/dal/tests/it/impls/aws_s3.rs
- common/dal/tests/it/impls/azure_blob.rs
- common/dal/tests/it/impls/mod.rs
- common/dal/tests/it/main.rs
- common/dal/tests/it/schemes.rs
apply the new test style to common-dal
- Improvement
Related #1866
Unit Tests
> [test] apply the new test style to common-dal

- scripts/ci/ci-run-cli-unit-tests.sh
- scripts/deploy/databend-query-cluster-3-nodes.sh
Incorporate HA meta service into CI environment, and point out some problems in HA cluster
- Improvement
Fixes #issue
Unit Tests
> [CI] HA cluster (experimental) CI with some problematic issues replication

- common/flight-rpc/Cargo.toml
- common/flight-rpc/tests/it/dns_resolver.rs
- common/flight-rpc/tests/it/main.rs
apply the new test style to common-flight-rpc
- Improvement 
Related #1866 
Unit Tests
> [test] apply the new test style to common-flight-rpc

- common/io/Cargo.toml
- common/io/src/buf_read.rs
- common/io/src/prelude.rs
- common/io/tests/it/binary_read.rs
- common/io/tests/it/binary_write.rs
- common/io/tests/it/buf_read.rs
- common/io/tests/it/main.rs
- common/io/tests/it/marshal.rs
- common/io/tests/it/utils.rs
apply the new test style to common-io
- Improvement
Related #1866 
Unit Tests
> [test] apply the new test style to common-io

- common/management/src/user/user_api.rs
- common/planners/src/lib.rs
- common/planners/src/plan_node.rs
- common/planners/src/plan_rewriter.rs
- common/planners/src/plan_user_alter.rs
- common/planners/src/plan_visitor.rs
- query/src/interpreters/interpreter_factory.rs
- query/src/interpreters/interpreter_user_alter.rs
- query/src/interpreters/interpreter_user_alter_test.rs
- query/src/interpreters/mod.rs
- query/src/sql/plan_parser.rs
- query/src/sql/sql_parser.rs
- query/src/sql/sql_parser_test.rs
- query/src/sql/sql_statement.rs
- query/src/users/user_mgr.rs
- query/src/users/user_mgr_test.rs
- tests/suites/0_stateless/05_0005_ddl_alter_user.sql
Support alter user statement
- New Feature
Fixes #2657 
Unit Tests
> [Feature]Alter User Support

- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/http/v1/query/http_query.rs
- query/src/servers/http/v1/query/result_data_manager.rs
bug fix: /v1/query may fail,  reason: state mistakenly relying on tokio schedule order.
Fixes #2767 
Unit Tests
> bugfix: http_query fail.

- scripts/setup/dev_setup.sh
Needed for rust-analyzer in dev env.
- Improvement
Fixes #issue
Unit Tests
> Add `rust-src` in toolchain setup

- common/metrics/Cargo.toml
- common/metrics/src/lib.rs
- common/metrics/tests/it/main.rs
apply the new test style to common-metrics 
- Improvement
Related #1866 
Unit Tests
> [test] apply the new test style to common-metrics

- query/src/sessions/sessions.rs
try fix cluster connect and close session not match
- Bug Fix
fixes #2795
> ISSUE-2795 try fix cluster connect and close session not match

- common/planners/Cargo.toml
- common/planners/src/lib.rs
- common/planners/tests/it/main.rs
- common/planners/tests/it/plan_aggregator.rs
- common/planners/tests/it/plan_builder.rs
- common/planners/tests/it/plan_describe_table.rs
- common/planners/tests/it/plan_display.rs
- common/planners/tests/it/plan_explain.rs
- common/planners/tests/it/plan_expression.rs
- common/planners/tests/it/plan_extras.rs
- common/planners/tests/it/plan_filter.rs
- common/planners/tests/it/plan_having.rs
- common/planners/tests/it/plan_limit.rs
- common/planners/tests/it/plan_projection.rs
- common/planners/tests/it/plan_rewriter.rs
- common/planners/tests/it/plan_select.rs
- common/planners/tests/it/test.rs
[test] apply the new test style to common-planners
- Improvement
Related #1866
Unit Tests
> [test] apply the new test style to common-planners

- common/streams/Cargo.toml
- common/streams/src/sources/mod.rs
- common/streams/tests/it/main.rs
- common/streams/tests/it/source.rs
- common/streams/tests/it/stream_datablock.rs
- common/streams/tests/it/stream_limit_by.rs
- common/streams/tests/it/stream_progress.rs
- common/streams/tests/it/stream_skip.rs
[test] apply the new test style to common-streams
- Improvement
Related #1866
Unit Tests
> [test] apply the new test style to common-streams

- common/arrow/Cargo.toml
- common/building/Cargo.toml
- common/macros/Cargo.toml
- common/tracing/Cargo.toml
[test] apply the new test style to other common crates
Just edit *.toml files
- Improvement
Related #1866 
Unit Tests
> [test] apply the new test style to other common crates

- query/src/configs/config_query.rs
- query/src/configs/config_test.rs
- query/src/datasources/database/system/configs_table_test.rs
- query/src/sessions/context.rs
- scripts/deploy/config/databend-query-embedded-meta.toml
- scripts/deploy/config/databend-query-node-1.toml
- scripts/deploy/config/databend-query-node-2.toml
- scripts/deploy/config/databend-query-node-3.toml
add load timeout as config in QueryConfig
- Improvement
Fixes #2606 
Unit Tests
> add query load timeout config in QueryConfig

- metasrv/src/meta_service/raftmeta.rs
- metasrv/tests/it/meta_service/raftmeta.rs
- scripts/deploy/databend-query-cluster-3-nodes.sh
> [metasrv] test: test membership after restarting MetaNode; test join a node twice

- common/functions/src/scalars/maths/angle.rs
- common/functions/tests/it/scalars/maths/angle.rs
- Bug Fix
Fixes #issue
Unit Tests
> Fix a bug in refactoring angle function

- .github/ISSUE_TEMPLATE/30_bug-report.md
- website/databend/docs/development/how-to-get-server-logs.md
- website/databend/mkdocs.yml
> DOC-2838: Add how to get server logs doc

- common/flight-rpc/tests/it/flight_token.rs
- query/src/datasources/table/fuse/README.md
- website/databend/docs/sqlstatement/aggregate-functions/aggregate-covar-samp.md
- website/databend/mkdocs.yml
Just add doc for covar_samp function, a test for flight_token, and a typo fix
- Other 
Fixes #issue
Unit Tests
> [DOC] Add covariance doc and flight token test

- README.md
- website/databend/mkdocs.yml
> update the url of databend weekly

- .github/actions-rs/grcov.yml
- website/databend/mkdocs.yml
Ignore codecov for cli
Fixes #2191 
Unit Tests
> ignore codecov for cli

- website/databend/docs/sqlstatement/numeric-functions/ceil.md
- website/databend/docs/sqlstatement/numeric-functions/ceiling.md
- website/databend/docs/sqlstatement/numeric-functions/floor.md
- website/databend/mkdocs.yml
Fixes [#issue](https://github.com/datafuselabs/databend/issues/2851)
Unit Tests
> [Doc] add doc for ceil, ceiling, floor func

- query/src/interpreters/interpreter_factory.rs
- query/src/interpreters/interpreter_insert_into.rs
- query/src/interpreters/interpreter_truncate_table_test.rs
https://github.com/datafuselabs/databend/pull/2765#discussion_r751289300
- Improvement
Fixes #issue
Unit Tests
> Improve insert into select

- query/src/catalogs/catalog.rs
- query/src/catalogs/impls/catalog/metastore_catalog.rs
- query/src/catalogs/impls/catalog/overlaid_catalog.rs
- query/src/catalogs/impls/catalog/system_catalog.rs
- tests/suites/0_stateless/05_0001_ddl_create_database.sql
fix create duplicate database bug.
- Bug Fix
Fixes #2860 
Unit Tests
> [bugfix] check read_only when creating/dropping database

- website/databend/docs/sqlstatement/numeric-functions/exp.md
- website/databend/mkdocs.yml
https://github.com/datafuselabs/databend/pull/2847
Unit Tests
> [Doc] add doc for exp function

- common/functions/src/scalars/maths/math.rs
- common/functions/src/scalars/maths/mod.rs
- common/functions/src/scalars/maths/sign.rs
- common/functions/tests/it/scalars/maths/mod.rs
- common/functions/tests/it/scalars/maths/sign.rs
- website/databend/docs/sqlstatement/numeric-functions/sign.md
Add sign() function.
- New Feature
#2563
Unit Tests
> [function] Add sign function

- website/databend/docs/sqlstatement/numeric-functions/acos.md
- website/databend/docs/sqlstatement/numeric-functions/asin.md
- website/databend/docs/sqlstatement/numeric-functions/atan.md
- website/databend/docs/sqlstatement/numeric-functions/atan2.md
- website/databend/mkdocs.yml
https://github.com/datafuselabs/databend/pull/2888
Unit Tests
> [Doc] Add doc for arc trigonometric function

- common/datavalues/src/arrays/boolean/builder.rs
- common/datavalues/src/arrays/builder.rs
- common/datavalues/src/arrays/primitive/builder.rs
- common/datavalues/src/arrays/string/builder.rs
- common/functions/src/scalars/hashes/sha2hash.rs
- common/functions/tests/it/scalars/hashes.rs
- Improvement
#2881 
Unit Tests
> Support nullable value in sha2 func

- query/src/pipelines/transforms/transform_expression_executor.rs
remove some unnecessary clone in `transform_expression_executor.rs`
Unit Tests
> remove some unnecessary clone

- common/exception/src/exception.rs
- common/planners/src/lib.rs
- common/planners/src/plan_node.rs
- common/planners/src/plan_rewriter.rs
- common/planners/src/plan_user_drop.rs
- common/planners/src/plan_visitor.rs
- query/src/interpreters/interpreter_factory.rs
- query/src/interpreters/interpreter_user_drop.rs
- query/src/interpreters/interpreter_user_drop_test.rs
- query/src/interpreters/mod.rs
- query/src/sql/plan_parser.rs
- query/src/sql/sql_parser.rs
- query/src/sql/sql_parser_test.rs
- query/src/sql/sql_statement.rs
- query/src/users/user_mgr.rs
- query/src/users/user_mgr_test.rs
- tests/suites/0_stateless/05_0007_ddl_drop_user.sql
solve #2656 
- New Feature
Fixes #2656 
Unit Tests
> ISSUE 2656: Support drop user

- common/streams/src/stream_cast.rs
- query/src/interpreters/interpreter_insert_into_test.rs
- query/src/interpreters/mod.rs
Enable the interpreter_insert_into test
- Improvement
Fixes #issue
Unit Tests
> Enable the interpreter_insert_into test

- Cargo.lock
- common/meta/embedded/src/meta_api_impl.rs
- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/raft-store/tests/it/state_machine/mod.rs
- common/meta/types/Cargo.toml
- common/meta/types/src/cmd.rs
- common/meta/types/src/table.rs
- metasrv/src/executor/meta_handlers.rs
> [common/meta] refactor: Cmd embeds UpsertTableOptionReq

- query/src/api/http/v1/logs.rs
- query/src/interpreters/interpreter_describe_table.rs
- query/src/interpreters/interpreter_insert_into.rs
- query/src/interpreters/interpreter_truncate_table.rs
- query/src/interpreters/interpreter_use_database.rs
- query/src/optimizers/optimizer_statistics_exact.rs
- query/src/servers/http/v1/statement.rs
- query/src/sessions/context.rs
- query/src/sessions/context_shared.rs
- query/src/sql/statements/query/query_schema_joined_analyzer.rs
- query/src/sql/statements/statement_insert.rs
Async get_table and get_database for catalog
- Improvement
fixes #2612, related #1830
> ISSUE-2612 async get_table and get_database for catalog

- query/src/catalogs/impls/catalog/metastore_catalog.rs
- query/src/tests/catalog.rs
- query/src/tests/number.rs
Prepare to remove BlockingWait
- Improvement
fixes #2492
> ISSUE-2492 prepare to remove BlockingWait

- common/base/src/lib.rs
- common/base/src/runtime.rs
- common/base/tests/it/runtime.rs
Remove BlockingWait
- Improvement
Fixes #2492
> ISSUE-2492 remove BlockingWait

- query/src/sql/statements/statement_alter_user.rs
- query/src/sql/statements/statement_create_database.rs
- query/src/sql/statements/statement_create_table.rs
- query/src/sql/statements/statement_create_user.rs
- query/src/sql/statements/statement_describe_table.rs
- query/src/sql/statements/statement_drop_database.rs
- query/src/sql/statements/statement_drop_table.rs
- query/src/sql/statements/statement_drop_user.rs
- query/src/sql/statements/statement_explain.rs
- query/src/sql/statements/statement_grant.rs
- query/src/sql/statements/statement_insert.rs
- query/src/sql/statements/statement_kill.rs
- query/src/sql/statements/statement_select.rs
- query/src/sql/statements/statement_set_variable.rs
- query/src/sql/statements/statement_show_create_table.rs
- query/src/sql/statements/statement_show_databases.rs
- query/src/sql/statements/statement_show_metrics.rs
- query/src/sql/statements/statement_show_processlist.rs
- query/src/sql/statements/statement_show_settings.rs
- query/src/sql/statements/statement_show_tables.rs
- query/src/sql/statements/statement_show_users.rs
- query/src/sql/statements/statement_truncate_table.rs
- query/src/sql/statements/statement_use_database.rs
Add tracing for query statement
- Improvement
#2524 #2492 #1830
Unit Tests
> ISSUE-2524 add tracing for query statement

- query/src/interpreters/interpreter_grant_privilege.rs
> Fix catalog get table failed caused by conflicts

- query/src/servers/http/v1/http_query_handlers_test.rs
fix a test that depends on the execution time of a SQL.
Fixes #2828
Unit Tests
> fix http_handler test_async.

- website/databend/docs/sqlstatement/numeric-functions/sqrt.md
- website/databend/mkdocs.yml
Add doc for sqrt math function.
https://github.com/datafuselabs/databend/pull/2905
Unit Tests
> [Doc] Add doc for sqrt math function

- cli/src/cmds/command.rs
- common/cache/src/disk_cache.rs
- common/clickhouse-srv/src/types/block/mod.rs
- common/clickhouse-srv/src/types/column/factory.rs
- common/clickhouse-srv/src/types/column/iter.rs
- common/datavalues/src/arrays/ops/agg.rs
- common/datavalues/src/data_array_filter.rs
- common/exception/src/exception.rs
- common/functions/src/aggregates/aggregate_combinator_if.rs
- common/functions/src/aggregates/aggregate_covariance.rs
- common/functions/src/scalars/maths/sqrt.rs
- common/functions/src/scalars/maths/trigonometric.rs
- common/functions/src/scalars/others/inet_aton.rs
- common/functions/src/scalars/others/inet_ntoa.rs
- common/meta/raft-store/src/state/raft_state.rs
- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/types/src/match_seq.rs
- metasrv/src/any_error/any_error_impl.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/store/meta_raft_store.rs
- query/src/pipelines/processors/pipeline.rs
- query/src/pipelines/processors/pipeline_builder.rs
- query/src/servers/http/v1/http_query_handlers.rs
- query/src/servers/http/v1/query/result_data_manager.rs
- query/src/sessions/context_shared.rs
Format code by using the option function
- Improvement
Fixes #issue
> Format code by using the option function

- common/clickhouse-srv/src/types/block/mod.rs
- common/clickhouse-srv/src/types/column/factory.rs
- common/clickhouse-srv/src/types/column/mod.rs
- common/clickhouse-srv/src/types/column/tuple.rs
- common/clickhouse-srv/src/types/mod.rs
- common/clickhouse-srv/src/types/value.rs
- common/clickhouse-srv/src/types/value_ref.rs
- common/clickhouse-srv/tests/it/types/block/builder.rs
- common/clickhouse-srv/tests/it/types/column/factory.rs
- common/clickhouse-srv/tests/it/types/column/mod.rs
- common/clickhouse-srv/tests/it/types/column/tuple.rs
- common/clickhouse-srv/tests/it/types/value.rs
- common/clickhouse-srv/tests/it/types/value_ref.rs
- common/datavalues/src/series/series_impl.rs
- common/datavalues/src/series/wrap.rs
- common/functions/src/scalars/tuples/tuple.rs
- common/functions/tests/it/scalars/tuples.rs
- query/src/servers/clickhouse/writers/query_writer.rs
Add tuple sqltype in clickhouse-srv.
- Improvement
Fixes #2788 
Unit Tests
> ISSUE-2788: clickhouse-srv support tuple type

- website/databend/mkdocs.yml
Add link for sign/round/truncate. cc @mshauneu 
Fixes #issue
Unit Tests
> [Doc] Add link

- common/functions/src/scalars/maths/trigonometric.rs
cc @sundy-li 
- Improvement
https://github.com/datafuselabs/databend/pull/2949#discussion_r754123718
https://github.com/datafuselabs/databend/pull/2949#discussion_r753974050
Unit Tests
> [function] Optimize trigonometric func

- tests/helpers/client.py
- tests/suites/0_stateless/12_0000_insert_into_select2.py
- Improvement
Fixes #issue
Unit Tests
> Make python support custom output

- Makefile
- scripts/setup/dev_setup.sh
- tests/databend-test
- tests/helpers/client.py
- tests/perfs/compare.py
- tests/perfs/perfs.py
- tests/suites/0_stateless/00_0000_dummy_select_py.py
- tests/suites/0_stateless/12_0000_insert_into_select2.py
Add python pretty formatter
- Improvement
Fixes #issue
Unit Tests
> Add python pretty formatter

- website/databend/docs/sqlstatement/datetime-functions/tomorrow.md
- website/databend/mkdocs.yml
Fix tomorrow syntax
Fixes #issue
Unit Tests
> [Doc] Fix tomorrow syntax

- common/exception/src/exception.rs
- common/meta/embedded/src/meta_api_impl.rs
- common/meta/raft-store/src/sled_key_spaces.rs
- common/meta/raft-store/src/state_machine/applied_state.rs
- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/raft-store/tests/it/state_machine/mod.rs
- common/meta/types/src/cmd.rs
- common/meta/types/src/database.rs
- common/meta/types/src/lib.rs
- metasrv/src/executor/meta_handlers.rs
- metasrv/tests/it/meta_service/raftmeta.rs
store database engine in meta store
- Improvement
Fixes #2936 
Unit Tests
> [meta] store Database.engine to metasrv

- query/src/sql/plan_parser_test.rs
- query/src/sql/statements/statement_show_processlist.rs
this PR fixes the bug describes in #2987
- Bug Fix
Fixes #2987
Unit Tests
> ISSUE-2987: bugfix show processlist

- query/src/sessions/session.rs
- query/src/sessions/sessions.rs
- query/src/users/mod.rs
- query/src/users/user.rs
- query/src/users/user_api.rs
- query/src/users/user_mgr.rs
- query/src/users/user_mgr_test.rs
- query/src/users/user_stage.rs
- query/src/users/user_stage_test.rs
No changes to the logic, just a restructuring of the code, make `user` and `stage` in query/users more cleaner.
- Improvement
Fixes #issue
Unit Tests
> Refactor the query/users struct, make user and stage more cleaner

- metasrv/src/metrics/metric_service.rs
- query/src/api/http/debug/home.rs
- query/src/api/http/v1/cluster.rs
- query/src/api/http/v1/logs.rs
- query/src/metrics/metric_service.rs
- query/src/servers/http/v1/http_query_handlers.rs
Simplify the code related to HTTP API.
- Improvement
Unit Tests
> [meta/query] Simplify the code related to HTTP API.

- website/databend/docs/development/how-to-write-scalar-functions.md
- website/databend/mkdocs.yml
> Add how to write scalar functions

- common/meta/api/src/meta_api.rs
- common/meta/api/src/meta_api_test_suite.rs
- common/meta/embedded/src/meta_api_impl.rs
- common/meta/flight/src/flight_action.rs
- common/meta/flight/src/impls/meta_api_impl.rs
- common/meta/types/src/database.rs
- common/meta/types/src/lib.rs
- metasrv/src/executor/meta_handlers.rs
- query/src/catalogs/backends/impls/meta_remote.rs
- query/src/catalogs/impls/mutable_catalog.rs
> [common/meta/types] refactor: introduce universial type ListDatabaseReq for flight-server, MetaAPI etc

- metasrv/src/api/http/debug/pprof.rs
- metasrv/src/api/http/v1/health.rs
- query/src/api/http/debug/pprof.rs
- query/src/api/http/v1/health.rs
- query/src/servers/http/v1/statement.rs
Remove some useless code and `unwrap` calls.
- Improvement
Fixes #issue
Unit Tests
> [meta/query] Remove some useless code and `unwrap` calls.

- cli/src/cmds/loads/load.rs
- cli/src/cmds/queries/query.rs
- cli/tests/it/query.rs
- query/src/bin/databend-query.rs
- query/src/servers/http/http_services.rs
- query/src/servers/http/mod.rs
- query/src/servers/http/v1/http_query_handlers.rs
- query/src/servers/http/v1/http_query_handlers_test.rs
- query/src/servers/http/v1/mod.rs
- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/http/v1/statement.rs
- query/src/servers/http/v1/statement_test.rs
rewrite /v1/statement, build on top of  /v1/query.
Fixes #2557 
Fixes #2407
Unit Tests
> Http handler refactor

- metasrv/src/executor/meta_handlers.rs
> [metasrv] refactor: simplify action-handler by calling MetaApi reading methods provided by StateMachine

- common/meta/raft-store/src/state_machine/sm.rs
- metasrv/src/executor/meta_handlers.rs
- Fix: when dropping database, if db presents in `database_lookup`, also
clean DatabaseMeta.
- Improvement
> [common/meta/raft-store] refactor: internally DropDatabase returns DatabaseMeta

- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/http/v1/query/http_query.rs
Add time in http handler response.
the front end need it
Unit Tests
> Add time in http handler response.

- common/meta/raft-store/src/state_machine/sm.rs
> [common/meta/raft-store] refactor: respond with table-id for DropTable and UpsertTableOption

- common/datablocks/src/kernels/data_block_group_by.rs
- common/datablocks/src/kernels/data_block_group_by_hash.rs
- common/datavalues/src/types/data_type.rs
- common/datavalues/src/types/data_type_coercion.rs
- common/functions/src/scalars/arithmetics/arithmetic.rs
- common/functions/src/scalars/dates/interval_function.rs
- common/functions/src/scalars/maths/abs.rs
- common/functions/src/scalars/maths/angle.rs
- common/functions/src/scalars/maths/exp.rs
- common/functions/src/scalars/maths/pow.rs
- common/functions/src/scalars/maths/sqrt.rs
- common/functions/src/scalars/maths/trigonometric.rs
- common/functions/src/scalars/others/inet_ntoa.rs
- common/functions/src/scalars/udfs/sleep.rs
Fixes #issue
Unit Tests
cc @sunli829
> Uniform data_type functions

- docker/databend-query-docker.toml
update outdated docker toml. we need to maintain it as well, some CI should be helpful
- Bug Fix
Fixes #issue
Unit Tests
> [docker] update docker toml

- common/base/src/runtime_tracker.rs
- common/base/src/thread.rs
- common/mem-allocator/src/allocators.rs
- query/src/datasources/database/system/processes_table.rs
- query/src/sessions/session_info.rs
- query/src/sql/plan_parser_test.rs
Fix performance fallback
fixes #2942 
Unit Tests
> ISSUE-2942 fix performance fallback

- query/src/servers/http/v1/http_query_handlers.rs
Add wall_time_ms in http handler response.
Unit Tests
> Add wall_time_ms in http handler response.

- query/src/databases/default/default_database.rs
- query/src/databases/github/github_database.rs
With the latest rust version, a wanings happens.
- Improvement
Fixes #issue
Unit Tests
> Fix error: field is never read:db_engine

- website/databend/docs/development/how-to-write-aggregate-functions.md
- website/databend/docs/development/how-to-write-scalar-functions.md
There's no `FactoryFuncRef` since https://github.com/datafuselabs/databend/pull/2043, so I removed it to avoid confusion. 
> docs: fix doc about function factory

- common/datavalues/src/arrays/ops/agg.rs
- Improvement
Fixes #issue
Unit Tests
> Add target_arch cfg for min/max

- Makefile
> [ci] refactor: clean up all temp meta dir: "_meta*"

- query/src/table_functions/table_function_factory.rs
make table func case insensitive
- Bug Fix
Fixes #3190 
Unit Tests
> make table func case insensitive

- common/functions/src/scalars/strings/mod.rs
- common/functions/src/scalars/strings/string.rs
- common/functions/src/scalars/strings/trim.rs
- common/functions/tests/it/scalars/strings/mod.rs
- common/functions/tests/it/scalars/strings/trim.rs
- New Feature
Fixes #issue
Unit Tests
> add trim function, add ut for trim funcions

- cli/src/cmds/queries/query.rs
- query/src/servers/http/v1/http_query_handlers.rs
- query/src/servers/http/v1/http_query_handlers_test.rs
- website/databend/docs/api/http-handler.md
- website/databend/docs/overview/building-and-running.md
- website/databend/mkdocs.yml
add doc for HTTP handler.
Fixes #3143
> [docs] add doc for http handler.

- query/src/storages/github/mod.rs
- query/src/storages/github/repo_comments_table.rs
- query/src/storages/github/repo_info_table.rs
- query/src/storages/github/repo_issues_table.rs
- query/src/storages/github/repo_prs_table.rs
- query/src/storages/storage_factory.rs
Fix github table engine inits
- Bug Fix
Fixes #3203
Unit Tests
> STORAGE-3203: Fix github table engine inits

- query/src/interpreters/interpreter_insert_into.rs
- website/databend/docs/sqlstatement/data-manipulation-language-dml/dml-insert.md
docs for  DML `insert overwrite`
- Improvement
Fixes #3180
Unit Tests
> ISSUE-3180: docs for  `insert overwrite`

- Cargo.lock
- common/functions/src/aggregates/aggregate_function_state.rs
> [common/function] refactor: simplify get_layout_offsets

- query/benches/suites/mod.rs
build the SessionManager from the default config, eliminate possible warnings and decouple from `SessionManagerBuilder`.
Related #1866
Unit Tests
> [bench] build the SessionManager from the default config

- common/functions/src/scalars/strings/string.rs
- common/functions/src/scalars/strings/substring.rs
- common/functions/tests/it/scalars/strings/substring.rs
- tests/suites/0_stateless/02_0005_function_substring.result
- tests/suites/0_stateless/02_0005_function_substring.sql
- website/databend/docs/sqlstatement/string-functions/mid.md
- website/databend/docs/sqlstatement/string-functions/substr.md
- website/databend/docs/sqlstatement/string-functions/substring.md
- website/databend/mkdocs.yml
Impl of SUBSTRING(), SUBSTR(), MID() funcs
- New Feature
Fixes #3035
Fixes #3037
Fixes #3064
> SUBSTRING(), SUBSTR(), MID() funcs

- query/src/servers/mysql/mysql_interactive_worker.rs
- tests/suites/0_stateless/07_0000_use_database.sql
fix init_query for use_database, thanks @zhang2014 
I verified this fix locally and it works perfectly.
- Bug Fix
Fixes #3219 
Unit Tests
> [mysql-srv] fix init_query

- query/src/configs/config_query.rs
- query/src/configs/config_test.rs
- query/src/sessions/sessions.rs
- query/src/storages/mod.rs
- query/src/storages/system/configs_table_test.rs
- query/src/storages/system/database.rs
- query/src/storages/system/mod.rs
- query/src/storages/system/query_log_memory_store.rs
- query/src/storages/system/query_log_memory_store_test.rs
- query/src/storages/system/query_log_table.rs
- query/src/storages/system/query_log_table_test.rs
- query/src/storages/system/tables_table_test.rs
- tests/suites/0_stateless/01_0002_system_query_log.sql
solve #2978 
- New Feature
Unit Tests
> ISSUE #2978, Add system.query_log

- cli/src/cmds/queries/query.rs
- query/src/bin/databend-query.rs
- query/src/servers/http/http_services.rs
- query/src/servers/http/mod.rs
- query/src/servers/http/v1/http_query_handlers.rs
- query/src/servers/http/v1/http_query_handlers_test.rs
- query/src/servers/http/v1/mod.rs
- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/http/v1/query/http_query.rs
- query/src/servers/http/v1/query/http_query_manager.rs
- query/src/servers/http/v1/query/mod.rs
- query/src/servers/http/v1/query/result_data_manager.rs
- query/src/servers/http/v1/statement.rs
- query/src/servers/http/v1/statement_test.rs
- query/src/sessions/context.rs
- query/src/sessions/context_shared.rs
- query/src/sessions/sessions.rs
1. Refine the mod import
2. Add http usage function to make code cleaner
- Improvement
Fixes #issue
Unit Tests
> HTTP: Refine the mod import and add http usage function

- website/databend/docs/sqlstatement/string-functions/field.md
- website/databend/docs/sqlstatement/string-functions/instr.md
- website/databend/docs/sqlstatement/string-functions/mid.md
- website/databend/docs/sqlstatement/string-functions/substr.md
- website/databend/docs/sqlstatement/string-functions/substring.md
> adjust docs for docusaurus

- README.md
Fix logo image not found for README
Fixes #issue
Unit Tests
> Fix logo image not found for README

- common/functions/src/scalars/arithmetics/arithmetic_minus.rs
- common/functions/src/scalars/arithmetics/arithmetic_plus.rs
- common/functions/src/scalars/dates/interval_function.rs
- common/functions/src/scalars/dates/number_function.rs
- common/functions/src/scalars/dates/round_function.rs
- common/functions/src/scalars/dates/week_date.rs
- common/functions/src/scalars/maths/abs.rs
- query/src/optimizers/utils_test.rs
Add `FACTOR_OP`, check the factor eval value to get monotonicity.
- Improvement
Fixes #issue
Unit Tests
> Complete dates function monotonicity check

- common/functions/src/scalars/strings/mod.rs
- common/functions/src/scalars/strings/string.rs
- common/functions/src/scalars/strings/substring_index.rs
- tests/suites/0_stateless/02_0026_function_string_substring_index.result
- tests/suites/0_stateless/02_0026_function_string_substring_index.sql
- website/databend/docs/sqlstatement/string-functions/substring_index.md
Impl of SUBSTRING_INDEX() func
- New Feature
Fixes #3033 
> SUBSTRING_INDEX() func

- cli/src/cmds/command.rs
bendctl support multi space in the command
- Bug Fix
Fixes #3115 
Unit Tests
> bendctl support multi space in the command

- .github/workflows/databend-docker.yml
- .github/workflows/databend-release.yml
- Cross.toml
- Makefile
setup rustflags for aarch64
Fixes #3268 
Unit Tests
> [ci] setup rustflags to reduce binary size

- common/functions/src/scalars/strings/insert.rs
- common/functions/src/scalars/strings/replace.rs
Reuse Buf for REPLACE() and INSERT()
- Improvement
Unit Tests
> Reuse Buf for REPLACE() and INSERT()

- query/src/configs/config_query.rs
- query/src/configs/config_test.rs
- query/src/storages/storage_factory.rs
- query/src/storages/system/configs_table_test.rs
- scripts/deploy/config/databend-query-embedded-meta.toml
- scripts/deploy/config/databend-query-node-1.toml
- scripts/deploy/config/databend-query-node-2.toml
- scripts/deploy/config/databend-query-node-3.toml
- Add `table_engine_github_enabled` config.
- Uniform env config for table engine.
- New Feature
Fixes [#issue](https://github.com/datafuselabs/databend/issues/3205)
Unit Tests
> [query] Add config for enable/disable github table engine

- README.md
Add acknowledgement for vercel
> docs: Add acknowledgement for vercel

- website/databend/docusaurus.config.js
This PR just added a vercel logo in footer. We will revisit the design in the near future.
> website: Add powered by vercel in footer

- Cargo.lock
- common/arrow/Cargo.toml
- common/datavalues/src/arrays/string/transform.rs
- common/functions/src/scalars/strings/hex.rs
- common/functions/src/scalars/strings/space.rs
- common/functions/src/scalars/strings/unhex.rs
string func, `transform_from_primitive`
Fixes #3304 
Unit Tests
> [string improvement] transform from primitive

- common/meta/sled-store/src/sled_tree.rs
- common/meta/sled-store/tests/it/main.rs
- common/meta/sled-store/tests/it/sled_tree.rs
- common/meta/sled-store/tests/it/sled_txn_tree.rs
- common/meta/sled-store/tests/it/testing/mod.rs
> [common/meta/sled-store] feature: txn-tree: add update_and_fetch()

- query/src/storages/github/repo_issues_table.rs
- query/src/storages/github/repo_prs_table.rs
add `created_at`, `updated_at`, `closed_at` field in issues and prs table.
- Improvement
Fixes #3317 
Unit Tests
> github issues/prs table add `created/updated/closed` time

- common/meta/sled-store/tests/it/sled_txn_tree.rs
> [common/meta/sled-store] test: add unit test for sled-txn-tree-sub-key-space: insert, get, remove

- common/meta/api/src/meta_api_test_suite.rs
- metasrv/src/executor/meta_handlers.rs
- metasrv/src/meta_service/message.rs
- metasrv/src/meta_service/meta_leader.rs
- metasrv/tests/it/flight/metasrv_flight_meta_api_leader_follower.rs
forward `ListTables` req to leader
- Improvement
Fixes #3341 
Unit Tests
> follower forward ListTables request

- common/meta/api/src/meta_api_test_suite.rs
- metasrv/src/executor/meta_handlers.rs
- metasrv/src/meta_service/message.rs
- metasrv/src/meta_service/meta_leader.rs
- metasrv/tests/it/flight/metasrv_flight_meta_api_leader_follower.rs
forward follower ListDatabase and GetTableInfo requests to leader.
- Improvement
Fixes #3340 #3341 
Unit Tests
> follower forward ListDatabase and GetTableInfo requests

- Cargo.lock
- common/clickhouse-srv/Cargo.toml
- common/clickhouse-srv/examples/simple.rs
- common/meta/embedded/Cargo.toml
- query/Cargo.toml
- query/src/bin/databend-query.rs
Remove env_logger
- Improvement
Fixes #3365
Unit Tests
> ISSUE-3365: Remove env_logger

- website/databend/docs/user/sqlstatement/data-loading/ontime.md
Add ontime dataset test documention
Fixes #issue
Unit Tests
> DOC: Add ontime dataset test

- metasrv/tests/it/flight/metasrv_flight_meta_api_follower_follower.rs
> [metasrv] test: write on follower and read on another follower

- .github/workflows/databend-release.yml
Update cross patch for new ci pipeline
- Bug Fix
resolve https://github.com/datafuselabs/databend/issues/3388
Unit Tests
> [Release] bump cross patch

- metasrv/src/meta_service/meta_service_impl.rs
- metasrv/tests/it/metasrv/meta_srv.rs
> [metasrv] feature: MetaService::write() forward request if it is not leader

- metasrv/tests/it/metasrv/meta_srv.rs
- metasrv/tests/it/tests/service.rs
Nothing really changed
- Improvement
> [metasrv] test: add util functions

- website/databend/docs/user/sqlstatement/show-commands/show-tables.md
> Fix show tables example

- website/databend/docs/user/sqlstatement/show-commands/show-functions.md
Add documentation for `SHOW FUNCTIONS`
Fixes #3398
> Add documentation for `SHOW FUNCTIONS`

- metasrv/src/executor/meta_handlers.rs
- metasrv/src/meta_service/message.rs
- metasrv/src/meta_service/raftmeta.rs
> [metasrv] refactor: impl all consistent-read with a universal method consistent_read()

- common/meta/flight/src/flight_action.rs
- common/meta/flight/src/impls/meta_api_impl.rs
- metasrv/src/executor/meta_handlers.rs
- query/tests/it/metrics.rs
Remove unnecessary FlightReq wrapper
- Improvement
Fixes #3384 
Unit Tests
> [metasrv] remove FlightReq wrapper

- query/src/users/user_mgr.rs
- query/tests/it/users/user_mgr.rs
Grant all privileges to the root user of localhost.
- Grant all privileges to `default` or `root` if hostname is `127.0.0.1` or `localhost`.
Fixes #3348 
Unit Tests
> Grant all privileges to the root user of localhost

- .github/actions/publish_image/action.yml
- .github/workflows/production.yml
> ci: Fix docker build on arm64

- tests/databend-test
- tests/suites/0_stateless/06_0000_show_queries.result
- tests/suites/0_stateless/06_0000_show_queries.result_filter
This is not meant for merge but to solve a testing issue in  @GanZiheng 's  PR
- fix: #3319
> [test]: test: filter stdout to let result matching easier

- Cargo.lock
- common/arrow/Cargo.toml
- common/datavalues/src/types/data_df_type.rs
Latest arrow2 could build failed for `common-arrow`, this PR fix it.
- Bug Fix
Unit Tests
> common/arrow: Fix build on newer arrow2 commits

- .github/actions/publish_image/action.yml
- .github/workflows/production.yml
As mentioned in #3479, we didn't build the arm64 image correctly. This PR will fix it.
> ci: Fix contianer image build for aarch64-unknown-linux-gnu

- common/datavalues/src/series/arithmetic.rs
- common/datavalues/src/types/data_type_coercion.rs
- common/functions/src/aggregates/aggregate_sum.rs
- tests/suites/0_stateless/02_0000_function_arithmetic.sql
> ISSUE-3495: fix intdiv return type

- Cargo.lock
- common/base/Cargo.toml
- metasrv/Cargo.toml
- metasrv/src/api/http/debug/pprof.rs
- metasrv/src/api/http/v1/cluster_state.rs
- metasrv/tests/it/api/http/cluster_state_test.rs
- metasrv/tests/it/api/http/config.rs
- metasrv/tests/it/api/http/health.rs
- query/Cargo.toml
- query/src/api/http/debug/pprof.rs
- query/src/api/http/v1/cluster.rs
- query/src/api/http/v1/logs.rs
- query/src/servers/http/v1/http_query_handlers.rs
- query/src/servers/http/v1/load.rs
- query/src/servers/http/v1/statement.rs
- query/tests/it/api/http/cluster.rs
- query/tests/it/api/http/config.rs
- query/tests/it/api/http/health.rs
- query/tests/it/api/http/logs.rs
- query/tests/it/servers/http/http_query_handlers.rs
- query/tests/it/servers/http/statement.rs
Poem 1.2 contains some breaking changes.
- Improvement
Unit Tests
> Bump poem to `1.2.2`

- Cargo.lock
- cli/Cargo.toml
- common/base/Cargo.toml
- common/dal/Cargo.toml
- common/flight-rpc/Cargo.toml
- common/meta/embedded/Cargo.toml
- common/meta/flight/Cargo.toml
- common/meta/raft-store/Cargo.toml
- common/meta/sled-store/Cargo.toml
- common/meta/types/Cargo.toml
- common/metrics/Cargo.toml
- common/streams/Cargo.toml
- metasrv/Cargo.toml
- query/Cargo.toml
- remove useless deps checked by `cargo udeps`
- update some deps to prune duplicated deps
- Improvement
Unit Tests
> cleanup some deps

- common/functions/src/scalars/strings/lower.rs
This PR will reduce the extra memcopy during lower.
Unit Tests
> functions/lower: Reduce extra memcopy

- common/functions/src/scalars/strings/base_64.rs
> Remove unused codes

- common/functions/src/scalars/expressions/cast.rs
- Improvement
Fixes #3533
Unit Tests
> Lazy initialize the error to fix performance drawback

- common/functions/src/scalars/function.rs
- common/planners/src/plan_expression_action.rs
- common/planners/src/plan_expression_chain.rs
- query/src/pipelines/transforms/transform_expression_executor.rs
> ISSUE-3519: Improve expression executor

- common/base/src/lib.rs
- common/base/src/progress.rs
- common/streams/src/stream_progress.rs
- common/streams/tests/it/stream_progress.rs
- query/src/interpreters/interpreter_copy.rs
- query/src/interpreters/interpreter_insert_with_stream.rs
- query/src/interpreters/interpreter_interceptor.rs
- query/src/interpreters/interpreter_query_log.rs
- query/src/pipelines/transforms/transform_source.rs
- query/src/servers/clickhouse/interactive_worker_base.rs
- query/src/servers/http/v1/load.rs
- query/src/servers/http/v1/query/execute_state.rs
- query/src/servers/mysql/mysql_interactive_worker.rs
- query/src/sessions/context.rs
- query/src/sessions/context_shared.rs
Remove ProgressCallback
- Improvement
Fixes #3541
Unit Tests
> ISSUE-3541: Remove ProgressCallback

- query/src/catalogs/impls/database_catalog.rs
- query/src/catalogs/impls/immutable_catalog.rs
- tests/suites/0_stateless/05_0000_ddl_create_tables.sql
- tests/suites/0_stateless/05_0000_ddl_drop_tables.sql
- tests/suites/0_stateless/05_0001_ddl_create_database.sql
- Bug Fix
Fixes #3553 
Unit Tests
> Check create table of immutable catalog

- Cargo.lock
- metasrv/Cargo.toml
- metasrv/src/bin/metasrv.rs
- metasrv/src/configs/config.rs
- metasrv/tests/it/configs.rs
> [metasrv] refine: load configs from toml file

- common/functions/src/scalars/strings/mod.rs
- common/functions/src/scalars/strings/string.rs
- common/functions/src/scalars/strings/upper.rs
- common/functions/tests/it/scalars/strings/mod.rs
- common/functions/tests/it/scalars/strings/upper.rs
- tests/suites/0_stateless/02_0043_function_strings_upper.result
- tests/suites/0_stateless/02_0043_function_strings_upper.sql
- website/databend/docs/user/sqlstatement/string-functions/ucase.md
- website/databend/docs/user/sqlstatement/string-functions/upper.md
- Fix https://github.com/datafuselabs/databend/issues/3012
- Fix https://github.com/datafuselabs/databend/issues/3013 
- New Feature
Unit Tests
> functions: Add UPPER support

- query/src/sql/parser/ast/ast_visitor.rs
- Bug Fix
Fixes #issue
Unit Tests
> Hot fix merge error

- .github/actions/build_debug/action.yml
- .github/actions/build_release/action.yml
- .github/actions/check/action.yml
- .github/actions/publish_image/action.yml
- .github/actions/test_unit/action.yml
This PR is a workaround for runner no space left.
Fixes https://github.com/datafuselabs/databend/issues/3562
Unit Tests
> ci: Apply workaround for no space left

- common/functions/src/scalars/strings/soundex.rs
- Bug Fix
- Improvement
Fixes #3549  
Fixes #3548 
Unit Tests
> Improve soundex function

- common/exception/src/exception.rs
- common/meta/types/src/user_grant.rs
- common/meta/types/src/user_privilege.rs
- common/meta/types/tests/it/user_privilege.rs
- query/src/interpreters/interpreter_grant_privilege.rs
- query/src/sql/sql_parser.rs
- query/src/sql/statements/statement_grant.rs
- query/src/sql/statements/statement_revoke.rs
- query/src/users/user_mgr.rs
- query/tests/it/interpreters/interpreter_grant_privilege.rs
- query/tests/it/sql/sql_parser.rs
- query/tests/it/users/user_mgr.rs
- tests/suites/0_stateless/05_0006_ddl_grant_privilege.result
- adds the privileges which drafted in https://github.com/datafuselabs/databend/issues/3173#issuecomment-997934491
- parser about parsing the newly added privileges
- do not allow the admin privileges like SUPER, USAGE on a database or table
- tests on interpreter
- adapt the different ALL PRIVILEGES semantics between the different objects
- Improvement
Fixes #3173
Unit Tests
> Add more privileges

- common/datavalues/src/columns/data_column.rs
- common/datavalues/src/utils.rs
- common/functions/src/scalars/arithmetics/arithmetic.rs
- common/functions/src/scalars/conditionals/if.rs
- common/functions/src/scalars/function.rs
- common/functions/src/scalars/strings/concat.rs
- common/functions/src/scalars/strings/concat_ws.rs
- common/functions/src/scalars/strings/format.rs
- query/src/pipelines/transforms/transform_expression_executor.rs
- website/databend/docs/dev/contributing/how-to-write-scalar-functions.md
- Improvement
Fixes #issue
Unit Tests
> Move validity masking out from function to transform

- website/databend/docs/dev/contributing/how-to-write-scalar-functions.md
With PR #3543 checked in, update the doc of how to write a scalar function.
#3543
Unit Tests
> [Doc] update function doc

- README.md
> readme: Fix broken links

- .github/ISSUE_TEMPLATE/other.yml
- Improvement
Fixes #issue
Unit Tests
> Add other issue template

- website/databend/docusaurus.config.js
- website/databend/package.json
- website/databend/src/pages/index.module.scss
- website/databend/yarn.lock
This PR includes two functions
i.  Add google analytics 
ii.  old-path redirect
- New Feature
- Improvement
#3638
> Add google analytics and a old-path redirect

- common/functions/src/scalars/arithmetics/arithmetic_plus.rs
- common/functions/src/scalars/function_factory.rs
- common/functions/tests/it/scalars/arithmetics.rs
- common/planners/src/plan_expression.rs
- common/planners/src/plan_expression_action.rs
- common/planners/src/plan_expression_chain.rs
- query/src/optimizers/utils.rs
ISSUE-3615 remove useless DataField
#3615 #3603
Unit Tests
> ISSUE-3615 remove useless DataField

- common/datavalues/src/types/deserializations/mod.rs
- common/datavalues/src/types/deserializations/string.rs
- tests/suites/0_stateless/03_0003_select_group_by.result
- tests/suites/0_stateless/03_0003_select_group_by.sql
- Bug Fix
Fixes #3629 
Thanks @ygf11 
Unit Tests
> Fix de function for String hash key

- Cargo.lock
- common/exception/Cargo.toml
- common/functions/Cargo.toml
Update bincode version
cc @ygf11 
Fixes #issue
Unit Tests
> Update bincode version

- website/databend/docusaurus.config.js
DOC: Fix data loading menu link
- Improvement
Fixes #issue
Unit Tests
> DOC: Fix data loading menu link

- website/databend/docusaurus.config.js
Enable algolia for full-text search.
The API Key is a public key that is safe to be committed in code source.
> docs: Enable algolia support

- cli/docs/ontime/README.md
- cli/src/cmds/loads/load.rs
- cli/src/cmds/ups/up.rs
- query/src/pipelines/transforms/transform_expression_executor.rs
- query/src/pipelines/transforms/transform_filter.rs
- query/src/servers/clickhouse/writers/query_writer.rs
- Improvement
Fixes #issue
Unit Tests
> Cli up improvement

- query/src/sql/statements/analyzer_expr.rs
- query/src/users/user_api.rs
- query/src/users/user_udf.rs
1. Move `load_udfs`
2. Add OperatorKind to replace unary_operator and binary_operator
- Improvement
Fixes #issue
Unit Tests
> Refine udf

- query/tests/it/servers/clickhouse.rs
Fixes #issue
#3724 
Unit Tests
> Ignore flaky test again

- tools/benchmark/src/main.rs
- Bug Fix
Fixes #3723
Unit Tests
> Fix benchmark hang

- scripts/setup/dev_setup.sh
fix https://github.com/datafuselabs/databend/runs/4684978318?check_suite_focus=true#step:3:10
Related #3722
Sorry I forgot to update the dev_setup.sh
Unit Tests
> [scripts] fix install toolchain

- common/functions/src/scalars/arithmetics/arithmetic_minus.rs
- common/planners/src/plan_expression_monotonicity.rs
- common/planners/tests/it/plan_expression_monotonicity.rs
- query/src/optimizers/optimizer_top_n_push_down.rs
- query/src/storages/index/range_filter.rs
1. Add single point for expression monotonicity visitor
2. ExpressionMonotonicityVisitor support multi-column.
- Improvement
Fixes #issue
Unit Tests
> Improve for expression monotonicity visitor

- metasrv/src/configs/config.rs
- scripts/deploy/config/databend-meta-node-1.toml
- scripts/deploy/config/databend-meta-node-2.toml
- scripts/deploy/config/databend-meta-node-3.toml
- scripts/deploy/databend-query-cluster-3-nodes.sh
> [ci] startup metasrv with config file for stateless-cluster test

- common/functions/src/scalars/strings/bin.rs
- website/databend/docs/dev/rfcs/query/0006-new-datatype-system.md
Add RFC for new datatype design
Fixes #issue
Unit Tests
> RFC new datatype

- query/src/interpreters/interpreter_query_log.rs
- query/tests/it/interpreters/interpreter_interceptor.rs
Continue #3803 
- Improvement
Fixes #issue
Unit Tests
> CONTIMUE-3803: Fix user_quota column order

- Cargo.lock
- common/dal2/Cargo.toml
- common/dal2/src/credential.rs
- common/dal2/src/services/s3.rs
- common/dal2/tests/it/s3.rs
Part of https://github.com/datafuselabs/databend/issues/3774
- New Feature
Unit Tests
> dal2/s3: Implement unit tests

- README.md
Signed-off-by: tison <wander4096@gmail.com>
N/A
N/A
> Update RoadMap link in README.md

- common/datavalues/src/data_value_operator.rs
- common/functions/src/scalars/arithmetics/arithmetic_minus.rs
- common/functions/src/scalars/arithmetics/arithmetic_modulo.rs
- common/functions/src/scalars/arithmetics/arithmetic_mul.rs
- common/functions/src/scalars/arithmetics/arithmetic_negate.rs
- common/functions/src/scalars/arithmetics/arithmetic_plus.rs
- common/functions/src/scalars/arithmetics/binary_arithmetic.rs
- common/functions/src/scalars/arithmetics/unary_arithmetic.rs
- common/planners/src/plan_expression_common.rs
- common/planners/src/plan_expression_monotonicity.rs
- query/src/optimizers/optimizer_top_n_push_down.rs
- query/src/pipelines/transforms/transform_sort_partial.rs
Remove some unused codes, and change some logic.
- Improvement
https://github.com/datafuselabs/databend/pull/3783#discussion_r779316923
> Format some codes

- README.md
correct the url of databend logo
correct the url of databend logo
Fixes #issue3825
Unit Tests
> correct the url of databend logo

- common/meta/raft-store/src/state_machine/sm.rs
- common/meta/sled-store/src/sled_tree.rs
Refine transaction impl:
* handle error
* abort transaction
- Improvement
Unit Tests
> [metasrv] refine transaction impl

- common/dal2/Cargo.toml
- common/dal2/src/lib.rs
- common/dal2/src/ops/io.rs
- common/dal2/src/tests/ops/io.rs
This PR polish the implementations for `CallbackReader`.
- Improvement
Unit Tests
> dal2: Polish CallbackReader implement

- .github/actions/test_proxy_mode/action.yml
- .github/actions/test_stateless_cluster/action.yml
- .github/actions/test_stateless_standalone/action.yml
- scripts/setup/dev_setup.sh
- tests/suites/0_stateless/11_0002_driver_show_tables.py
Link to pr https://github.com/datafuselabs/databend/pull/3830
Add test for #3828.
> Add test case for pr-3830

- query/src/servers/mysql/mysql_interactive_worker.rs
**mysql_interactive_worker.rs**: MySQL 8.0 JDBC `mysql-connector-java-8.0.27.jar` will send query like SELECT @@session.xxx as xxx.
But now databend not support this query, so in this file if the query
like this, will return OK.
- Improvement
Fixes #3848
> ISSUE-3848 Fix MySQL 8.0 JDBC Compatibility Err

- website/src/pages/index.module.scss
Center the home page background at any resolution.
- Improvement
Unit Tests
> fix: Center the home page background image

- tests/suites/2_management_mode/00_0001_management_mode.result
Fix https://github.com/datafuselabs/databend/pull/3867 stateless management mode test result
- Improvement
Fixes #issue
Unit Tests
> Add tests/suites/2_management_mode/00_0001_management_mode.result

- common/meta/grpc/src/grpc_client.rs
Refine codes to avoid assigning every time. This should have been added to the previous PR, but @BohuTANG  merged too quickly 😂
- Improvement
Fixes #issue
Unit Tests
> [metasrv] Refine codes to avoid assigning every time

- website/src/plugins/pxToVw.js
Fix code that might be wrong.
- Bug Fix
Fixes #3881
> fix: Fix code that might be wrong.

- query/src/bin/databend-query.rs
- Improvement
Fixes #issue
Unit Tests
> Refine mysql hints on server startup

- common/datavalues2/src/columns/struct_/mod.rs
- common/datavalues2/src/data_value.rs
- common/datavalues2/src/types/serializations/array.rs
- common/datavalues2/src/types/serializations/mod.rs
- common/datavalues2/src/types/type_array.rs
- common/datavalues2/src/types/type_date32.rs
- common/datavalues2/src/types/type_id.rs
- common/datavalues2/tests/it/types/serializations.rs
- Improvement
Fixes #issue
Unit Tests
> Complete array and struct serializer

- query/src/pipelines/new/processors/sinks/sync_sink.rs
- query/src/pipelines/new/processors/sources/async_source.rs
- query/src/pipelines/new/processors/sources/mod.rs
- query/src/pipelines/new/processors/sources/sync_source.rs
- query/src/pipelines/new/processors/sources/sync_source_receiver.rs
- query/src/pipelines/new/processors/sources/table_source.rs
- query/tests/it/pipelines/new/executor/executor_graph.rs
Remove useless code for processor framework
Related #3379
Unit Tests
> Remove useless code for processor framework

- common/planners/src/plan_expression_monotonicity.rs
- common/planners/tests/it/plan_expression_monotonicity.rs
- query/src/storages/index/range_filter.rs
- query/tests/it/storages/fuse/pruning.rs
RangeFilter eval return true if the expression is not monotonic in the variables range.
- Bug Fix
Fixes #3941
Unit Tests
> Fix pruning get error when expression is not monotonic

- .github/actions/test_unit/action.yml
- .github/workflows/developing.yml
- query/tests/it/storages/index/bloom_filter.rs
> CI: set swap to 10G

- query/src/storages/index/bloom_filter.rs
- query/tests/it/storages/index/bloom_filter.rs
The unit-test is using random seeding, it may cause false positive and fail the test. Change random seeding to determistic seeding.
- Bug Fix
Fixes #3950
Unit Tests
> Fix flaky test, change random seeding to deterministic value

- common/meta/grpc/src/grpc_action.rs
> [metasrv] refactor: remove unused trait impl

- query/src/storages/fuse/README.md
Error in README.md
- New Feature
- Bug Fix
- Improvement
- Need Documentation (Need to add documentation to https://databend.rs)
- Other 
Fixes #issue
Unit Tests
> Fix error in README.md

- query/src/storages/fuse/README.md
Error in README.md,
Make it better and cleaner.
Changelog
Documentation
Related Issues
Fixes #issue
Test Plan
Unit Tests
> F fix doc bugs

- common/meta/grpc/src/grpc_client.rs
- common/meta/grpc/tests/it/grpc_server.rs
- common/meta/types/proto/meta.proto
- metasrv/src/api/grpc/grpc_service.rs
- metasrv/src/api/grpc_server.rs
Refactor: refactor protobuf service name
- Improvement
Fixes #issue
Unit Tests
> Refactor: refactor protobuf service name

- common/functions/src/scalars/conditionals/if.rs
use `aggregate_types` rather than `compare_coercion` in function if
- Improvement
Fixes #issue
Unit Tests
> use aggregate_type to merge type

- common/functions/src/scalars/dates/date.rs
- common/functions/src/scalars/dates/simple_date.rs
- common/functions/src/scalars/function2_factory.rs
- common/functions/src/scalars/function_factory.rs
Migrate some date functions into datavalues2
- New Feature
Fixes #3970 
Unit Tests
> Datavalues2: date: today yesterday and tomorrow

- query/tests/it/catalogs/catalogs.rs
- query/tests/it/catalogs/database_catalog.rs
- query/tests/it/catalogs/immutable_catalogs.rs
- query/tests/it/catalogs/mod.rs
- query/tests/it/main.rs
Add UT for catalog
Fixes #2919
Unit Tests
> tests: add UT for catalogs

- common/meta/sled-store/src/sled_serde.rs
> [common/meta/sled-store] refactor: sled-serde trait family need do Sized

- docs/user/01-sql-statement/08-system-tables/system-settings.md
Add Databend settings introduce and usage
https://github.com/datafuselabs/databend/issues/4010
> Add Databend settings introduce and usage

- query/src/storages/fuse/io/meta_readers.rs
Use buf reader for meta reader
Fixes #3938 
Unit Tests
> Use buf reader for meta reader

- scripts/setup/dev_setup.sh
Fix lint missing toml dep error
- Bug Fix
Fixes #4017 
Unit Tests
> Fix lint missing toml dep error

- tests/databend-test
**Chinese New Year 2022, 春节快乐，虎年大吉！**
- Improvement
Fixes #issue
Unit Tests
> Chinese New Year 2022, 春节快乐，虎年大吉！

- common/functions/src/scalars/arithmetics/arithmetic_div.rs
- common/functions/src/scalars/arithmetics/arithmetic_minus.rs
- common/functions/src/scalars/arithmetics/arithmetic_mul.rs
- common/functions/src/scalars/arithmetics/arithmetic_plus.rs
- common/functions/src/scalars/expressions/binary.rs
- common/functions/src/scalars/expressions/unary.rs
- common/functions/src/scalars/hashes/hash_base.rs
- Improvement
Fixes #issue
Unit Tests
> Experiment of Scalar functions

- query/src/sql/statements/analyzer_expr.rs
Small code change about variable name
- Improvement
Fixes #issue
None
Unit Tests
> Small code change about variable name

- common/functions/tests/it/scalars/scalar_function_test.rs
- query/src/sql/statements/analyzer_expr.rs
Improve readability
- Improvement
Parts of https://github.com/datafuselabs/databend/issues/4044
Unit Tests
> Improve readability

- common/datavalues/src/series/series_impl.rs
Improve readability, add some comments
- Improvement
https://github.com/datafuselabs/databend/issues/4044
Fixes #issue
Unit Tests
> F improve readability

- query/src/storages/fuse/README.md
Improve the README document.
- Improvement
https://github.com/datafuselabs/databend/issues/4044
Fixes #issue
Unit Tests
> Improve README doc

- common/meta/types/src/database.rs
- metasrv/tests/it/meta_node/meta_node_all.rs
- query/src/sql/statements/statement_create_database.rs
- Improvement
Fixes #4055 
Unit Tests
> Add created_on to DatabaseMeta

- query/src/catalogs/catalog.rs
- query/src/catalogs/impls/database_catalog.rs
- query/src/catalogs/impls/mutable_catalog.rs
- query/src/sql/statements/statement_show_engines.rs
- query/src/storages/fuse/table.rs
- query/src/storages/github/github_table.rs
- query/src/storages/memory/memory_table.rs
- query/src/storages/mod.rs
- query/src/storages/null/null_table.rs
- query/src/storages/storage_factory.rs
Summary about this PR：
1. **Refine the storage engine descriptor**
- Improvement
Fixes #issue
Unit Tests
> STORAGE: Refine the storage engine descriptor

- query/tests/it/servers/http/http_query_handlers.rs
> Disable http test_aync flaky test

- docs/dev/development/routine-maintenance.md
docs(dev): add routine maintenance steps
Fixes #3785 
Unit Tests
> docs(dev): add routine maintenance steps

- common/meta/raft-store/src/state_machine/sm.rs
make txn* funcs name consistent
- Improvement
Unit Tests
> [metasrv] Small refactor: make txn* funcs name consistent

- docs/overview/architecture.md
Modify some typos in architecture.md
> [docs](typo) modify some typos in architecture.md

- metasrv/src/api/http/debug/home.rs
- metasrv/src/api/http/v1/cluster_state.rs
- metasrv/src/executor/meta_handlers.rs
- metasrv/src/meta_service/meta_leader.rs
- metasrv/src/meta_service/meta_service_impl.rs
- metasrv/src/meta_service/raftmeta.rs
- metasrv/src/store/meta_raft_store.rs
* eliminate `unwrap` call as much as possible
* if `unwrap` call is safe or intentional, then comment on it.
- Improvement
Unit Tests
> [metasrv] Refactor: eliminate unwrap call as much as possible

- common/datavalues2/src/columns/series.rs
- common/functions/src/scalars/maths/log.rs
- common/functions/src/scalars/maths/math.rs
- common/functions/src/scalars/maths/pow.rs
- common/functions/src/scalars/maths/random.rs
- common/functions/src/scalars/maths/round.rs
- common/functions/src/scalars/maths/trigonometric.rs
- common/functions/tests/it/scalars/maths/log.rs
- common/functions/tests/it/scalars/maths/pow.rs
- common/functions/tests/it/scalars/maths/round.rs
- common/functions/tests/it/scalars/maths/trigonometric.rs
- tests/suites/0_stateless/02_function/02_0014_function_maths.result
- tests/suites/0_stateless/02_function/02_0014_function_maths.sql
- Improvement
Part of  #3972
Unit Tests
> Other maths functions to datavalues2

- docs/learn/lessons/02-analyze-ontime-with-databend-on-ec2-and-s3.md
This PR adds more detailed information on s3 related config.
Unit Tests
> docs: Update lessons for ontime on s3

- common/meta/raft-store/src/state_machine/sm.rs
- metasrv/src/meta_service/meta_leader.rs
With this fix, PR: #4175 should be passed.
- Improvement
Unit Tests
> [metasrv] fix drop table on unknown db test

- Cargo.toml
more codegen units for common-functions
This is not a formal solution, but it helps us alleviate the problem.
Part of #4186 
Unit Tests
> chore(Cargo.toml): more codegen units for common-functions

- common/meta/raft-store/src/sled_key_spaces.rs
- metasrv/src/bin/metactl.rs
- metasrv/src/export.rs
- metasrv/src/store/meta_raft_store.rs
- metasrv/tests/it/grpc/metasrv_grpc_export.rs
- tests/databend-test
- tests/helpers/client.py
- tests/suites/0_stateless/00_dummy/00_0002_dummy_select_py.py
> [metasrv] refactor: exported data should be type awared

- common/functions/src/scalars/arithmetics/arithmetic_div.rs
- common/functions/src/scalars/arithmetics/arithmetic_intdiv.rs
- common/functions/src/scalars/arithmetics/arithmetic_minus.rs
- common/functions/src/scalars/arithmetics/arithmetic_modulo.rs
- common/functions/src/scalars/arithmetics/arithmetic_mul.rs
- common/functions/src/scalars/arithmetics/arithmetic_negate.rs
- common/functions/src/scalars/arithmetics/arithmetic_plus.rs
- common/functions/src/scalars/dates/interval_function.rs
- common/functions/src/scalars/function_adapter.rs
- common/functions/src/scalars/function_factory.rs
- common/functions/src/scalars/mod.rs
- tests/suites/0_stateless/02_function/02_0000_function_arithmetic.result
- tests/suites/0_stateless/02_function/02_0000_function_arithmetic.sql
> ISSUE-4006: Fix arithmetic with null type bug

- website/docusaurus.config.js
> Move learn to the end of the menu bar

- query/src/storages/fuse/constants.rs
- tests/databend-test
- tests/helpers/client.py
- tests/suites/0_stateless/00_dummy/00_0002_dummy_select_py.py
- tests/suites/0_stateless/09_fuse_engine/09_0011_create_table_with_opt_loc.result
- tests/suites/0_stateless/09_fuse_engine/09_0011_create_table_with_opt_loc.sh
Use case insensitive table option keys
- Improvement
Unit Tests
> Improvement: Use case insensitive table option keys

- Cargo.lock
- common/contexts/Cargo.toml
- common/contexts/src/dal/dal_context.rs
- common/streams/Cargo.toml
- query/Cargo.toml
- query/tests/it/storages/fuse/io.rs
Bump opendal to the regular release
- Bug Fix
Unit Tests
> deps: Bump opendal to regular release

- query/src/configs/config_query.rs
- query/tests/it/configs.rs
- query/tests/it/storages/system/configs_table.rs
- Bug Fix
Fixes #4250 
Unit Tests
> Fix num cpu defaults to 8

- query/tests/it/tests/sessions.rs
> Fix the test_multi_page-test

- .cargo/audit.toml
temp fix  to https://github.com/datafuselabs/databend/issues/4335
related https://github.com/datafuselabs/databend/issues/4335
Unit Tests
> [audit] temporarily ignore arrow2 < 0.9.2

- query/src/interpreters/interpreter_query_log.rs
- query/src/servers/http/v1/block_to_json.rs
- query/src/servers/http/v1/query/result_data_manager.rs
- query/src/storages/system/processes_table.rs
- query/src/storages/system/users_table.rs
- query/tests/it/servers/http/http_query_handlers.rs
fix: `SELECT * from system.processes` failed when serialize_json in http hander
- Bug Fix
Fixes  issue https://github.com/datafuselabs/databend/issues/4302
Unit Tests
> fix system tables field datatype

- query/src/servers/mysql/mysql_interactive_worker.rs
- query/src/servers/mysql/mysql_session.rs
- Bug Fix
Fixes #issue
Unit Tests
> MySQLHandler: Make async executor running inside the right runtime

- Cargo.lock
- common/datablocks/src/kernels/data_block_group_by_hash.rs
- query/src/pipelines/transforms/transform_group_by_final.rs
- Bug Fix
Fixes #4349
Unit Tests
> Fix group by empty
