README.md
docs: Remove qingcloud from acknowledgement
=> docs: Remove qingcloud from acknowledgement

src/query/datavalues/src/columns/boolean/mod.rs, src/query/datavalues/src/columns/nullable/mod.rs
=> refactor(query): improve boolean filter

.github/actions/publish_binary/action.yml
=> ci(release): sync release results to repo

src/query/service/src/interpreters/interpreter_copy_v2.rs, src/query/storages/factory/src/stage/stage_table.rs
=> feat: change log level from info to debug for copy

src/meta/types/src/tenant_quota.rs, src/query/service/src/interpreters/interpreter_user_create.rs
Add max_user field in Tenant Quota, support to limit the maximum number of users to be created
Fixes #issue
=> feat: add user quota

docs/doc/10-deploy/00-understanding-deployment-modes.md, docs/doc/10-deploy/02-deploying-databend.md
1. added start.sh and stop.sh
2. updated the list of supported object storages
3. updated download scripts
Fixes #issue
=> docs: deploy updates

docs/doc/21-load-data/02-local.md
added allow_insecure to COPY FROM LOCAL FILE
Fixes #issue
=> docs: allow insecure

docs/doc/30-reference/30-sql/00-ddl/80-presign/presign.md
https://github.com/datafuselabs/databend/issues/8538#issuecomment-1296575589
Fixes #issue
=> docs: pressing upload

src/common/base/src/mem_allocator/mmap_allocator.rs
=> fix(query): fix linux_kernel_version detection

src/query/settings/src/lib.rs
Before:
the max_threads will be overwritten in settings::try_create.
Now:
Only when the user set global max_threads to 0, will overwrite the value.
```shell
➜  ~ mysql -uroot -P3307 -h127.0.0.1 -e'set global max_threads=200';
➜  ~ mysql -uroot -P3307 -h127.0.0.1 -e"show settings like 'max_threads'";
+-------------+-------+---------+--------+---------------------------------------------------------------------------------------------------+--------+
| name        | value | default | level  | description                                                                                       | type   |
+-------------+-------+---------+--------+-------------------------------------------------------------- …
```
=> fix(query): set global max_threads not work

src/query/functions-v2/tests/it/scalars/testdata/function_list.txt
=> feat(query): fix ut

src/query/pipeline/sources/src/processors/sources/input_formats/input_format_text.rs, src/query/pipeline/sources/src/processors/sources/input_formats/input_pipeline.rs
=> fix(copy): fix wrong asserts.

src/query/service/src/servers/http/v1/download.rs, src/query/service/src/servers/http/v1/http_query_handlers.rs, src/query/service/tests/it/servers/http/http_query_handlers.rs
add a unit test for this.
cc @Chasen-Zhang
=> feat(download): download support CsvWithNames.

.github/actions/artifact_failure/action.yml, .github/actions/test_stateful_cluster_linux/action.yml, .github/actions/test_stateful_standalone_linux/action.yml, scripts/ci/deploy/config/databend-query-embedded-meta.toml, scripts/ci/deploy/config/databend-query-management-mode.toml, scripts/ci/deploy/config/databend-query-node-1.toml, scripts/ci/deploy/config/databend-query-node-2.toml, scripts/ci/deploy/config/databend-query-node-3.toml
ci: Upload entire directory instead
=> ci: Upload entire directory instead

scripts/ci/deploy/config/databend-query-node-1.toml, scripts/ci/deploy/config/databend-query-node-2.toml, scripts/ci/deploy/config/databend-query-node-3.toml, src/query/service/src/servers/mysql/writers/query_result_writer.rs
chore: Add error message for mysql result writer
Related to https://github.com/datafuselabs/databend/issues/7986
The error happened at mysql result writer, we don't have any error logs.
=> chore: Add error message for mysql result writer

src/common/tracing/src/logging.rs, src/query/service/src/pipelines/executor/pipeline_pulling_executor.rs
chore: Print logging file and line number
=> chore: Print logging file and line number

src/query/service/src/api/rpc/packets/packet_data.rs, src/query/service/src/pipelines/executor/pipeline_pulling_executor.rs
=> chore: try to debug broken pipe

src/query/sql/src/planner/optimizer/property/builder.rs
=> refactor(optimizer): fix error info

scripts/setup/rust-tools.txt
ci: Install sccache for future use
=> ci: Install sccache for future use

scripts/ci/ci-run-fuzz-tests.sh, scripts/ci/ci-run-profile.sh, scripts/ci/ci-run-sqllogic-tests-cluster.sh, scripts/ci/ci-run-sqllogic-tests.sh, scripts/ci/ci-run-stateful-hive-tests-standalone-embed-meta.sh, scripts/ci/ci-run-stateful-tests-cluster-s3.sh, scripts/ci/ci-run-stateful-tests-standalone-s3-embed-meta.sh, scripts/ci/ci-run-stateful-tests-standalone-s3.sh, scripts/ci/ci-run-stateless-tests-cluster-tls.sh, scripts/ci/ci-run-stateless-tests-cluster.sh, scripts/ci/ci-run-stateless-tests-standalone.sh, scripts/ci/ci-run-tests-embedded-meta.sh, scripts/ci/ci-run-unit-tests.sh, scripts/ci/deploy/config/databend-query-node-1.toml, scripts/ci/deploy/databend-query-cluster-3-nodes.sh, scripts/ci/deploy/databend-query-management-mode.sh, scripts/ci/deploy/databend-query-standalone-embedded-meta.sh, scripts/ci/deploy/databend-query-standalone.sh, scripts/ci/wait_tcp.py
ci: Add set -e for all our ci scripts
=> ci: Add set -e for all our ci scripts

scripts/setup/dev_setup.sh
ci: Instal cccache v0.5 instead
Let's merge.
=> ci: Instal cccache v0.5 instead

scripts/setup/dev_setup.sh
chore: Fix cccache can't build
=> chore: Fix cccache can't build

Cargo.toml
ci: Disable incremental for dev profile
=> ci: Disable incremental for dev profile

src/query/service/src/pipelines/processors/transforms/transform_merge_block.rs
=> chore(log): remove logs in union processor

docs/doc/30-reference/30-sql/00-ddl/20-table/10-ddl-create-table.md
Unified connection option
Unified connection option
=> docs:Update 10-ddl-create-table.md

Cargo.lock, src/query/service/Cargo.toml, src/query/service/src/api/rpc/packets/packet_data_precommit.rs
change PrecommitBlock serde from serde_json to bincode
Closes #issue
=> feat: change PrecommitBlock serde from serde_json to bincode

Cargo.lock, src/query/config/Cargo.toml, src/query/service/Cargo.toml, src/query/sql/Cargo.toml, src/query/storages/hive/hive-meta-store/Cargo.toml, src/query/storages/hive/hive/Cargo.toml
Related to https://github.com/datafuselabs/databend/issues/8756
=> refactor: Use databend-thrift crate instead

src/query/service/src/pipelines/processors/transforms/aggregator/aggregator_two_level.rs
refactor(aggregator): try fix drop twice states
fixes #8765
=> refactor(aggregator): try fix drop twice states

scripts/setup/rust-toolchain.toml
ci: Bump rust-toolchain to fix ICE
=> ci: Bump rust-toolchain to fix ICE

Cargo.lock, src/common/arrow/Cargo.toml, src/query/service/src/pipelines/pipeline_builder.rs, tests/logictest/suites/base/03_dml/03_0003_select_group_by
=> chore(query): enable max threads for sort transform

Cargo.toml, rust-toolchain.toml
fix: Bump rust toolchain to fix ICE and incremental build
=> fix: Bump rust toolchain to fix ICE and incremental build

src/query/expression/src/chunk.rs, src/query/expression/src/converts/from.rs, src/query/expression/src/converts/to.rs, src/query/expression/src/evaluator.rs, src/query/expression/src/kernels/concat.rs, src/query/expression/src/kernels/filter.rs, src/query/expression/src/kernels/scatter.rs, src/query/expression/src/kernels/take.rs, src/query/expression/src/kernels/take_chunks.rs, src/query/expression/src/lib.rs, src/query/expression/src/utils/display.rs, src/query/expression/src/utils/mod.rs, src/query/expression/src/values.rs, src/query/expression/tests/it/common.rs, src/query/expression/tests/it/kernel.rs, src/query/functions-v2/benches/bench.rs, src/query/functions-v2/tests/it/aggregates/mod.rs, src/query/functions-v2/tests/it/scalars/mod.rs
Reverts datafuselabs/databend#8789
=> Revert "refactor(expr): allow sparse column id in chunk"

docs/doc/30-reference/30-sql/00-ddl/20-table/10-ddl-create-table.md
Updated connection parameters for CREATE TABLE.
Closes #issue
=> docs: update connection parameters

src/query/service/src/interpreters/fragments/fragmenter.rs, src/query/service/src/interpreters/fragments/plan_fragment.rs, src/query/sql/src/executor/physical_plan.rs, tests/logictest/suites/base/03_dml/03_0011_select_from_system_processes, tests/logictest/suites/query/join.test
=> chore: fix typo and skip flaky test

src/query/functions-v2/src/scalars/comparison.rs, src/query/functions-v2/tests/it/scalars/testdata/array.txt, src/query/functions-v2/tests/it/scalars/testdata/comparison.txt
=> feat(function-v2): Add calc domain for comparison.

src/query/expression/src/evaluator.rs, src/query/expression/src/property.rs, src/query/functions-v2/src/scalars/arithmetic.rs, src/query/functions-v2/src/scalars/array.rs, src/query/functions-v2/src/scalars/boolean.rs, src/query/functions-v2/src/scalars/comparison.rs, src/query/functions-v2/src/scalars/datetime.rs, src/query/functions-v2/src/scalars/math.rs, src/query/functions-v2/src/scalars/string.rs, src/query/functions-v2/src/scalars/string_multi_args.rs, src/query/functions-v2/src/scalars/variant.rs
Refer to https://github.com/datafuselabs/databend/pull/8754#discussion_r1021263965
=> refactor(function): rename FunctionDomain::NoThrow to FunctionDomain::Full

docs/doc/60-contributing/03-rfcs/20221017-multiple-catalog.md
=> docs(rfc): update multiple catalog rfc

docs/doc/30-reference/30-sql/00-ddl/20-table/60-optimize-table.md
After commit https://github.com/datafuselabs/databend/pull/8679 is merged, the number of blocks is no longer associated with max_threads.
Closes #issue
=> docs: update optimize compact docs

src/query/service/src/api/rpc/exchange/exchange_sink_merge.rs, src/query/service/src/api/rpc/exchange/exchange_sink_shuffle.rs, src/query/service/src/api/rpc/exchange/exchange_transform.rs, src/query/service/src/api/rpc/exchange/exchange_transform_source.rs, src/query/service/src/api/rpc/flight_scatter_hash.rs, src/query/service/src/api/rpc/packets/packet_data.rs
feat(query): parallel merge for distribute query
Closes #issue
=> feat(query): parallel merge for distribute query

src/query/service/src/servers/http/v1/query/execute_state.rs, src/query/service/src/servers/http/v1/query/http_query.rs, src/query/service/src/servers/http/v1/query/mod.rs, src/query/service/src/servers/http/v1/query/page_manager.rs, src/query/service/src/servers/http/v1/query/sized_spsc.rs, src/query/service/tests/it/servers/http/http_query_handlers.rs, src/query/storages/fuse/fuse-result/src/lib.rs
=> feat(http handler): disable result cache.

src/query/expression/src/chunk.rs, src/query/expression/src/evaluator.rs, src/query/expression/src/expression.rs, src/query/expression/src/kernels/concat.rs, src/query/expression/src/kernels/take_chunks.rs, src/query/expression/src/lib.rs, src/query/expression/src/utils/mod.rs, src/query/expression/src/values.rs, src/query/functions-v2/tests/it/scalars/mod.rs
Port the changes for the constant folder from https://github.com/datafuselabs/databend/pull/8789
=> refactor(function): allow sparse column id for constant folder

README.md
=> docs: update user defiend function link in readme

README.md
Fixed one more broken link in README
Closes #issue
=> docs: one more broken link

src/common/hashtable/src/container.rs, src/common/hashtable/src/hashtable.rs, src/common/hashtable/src/lookup_hashtable.rs, src/common/hashtable/src/table0.rs, src/common/hashtable/src/table1.rs, src/common/hashtable/src/traits.rs, src/common/hashtable/src/twolevel_hashtable.rs, src/common/hashtable/src/unsized_hashtable.rs
chore(base): add bytes len for hash table like
Closes #issue
=> chore(base): add bytes len for hash table like

src/query/service/src/servers/http/v1/http_query_handlers.rs
=> feat(http handler): return num of rows of current page in header.

src/query/service/src/interpreters/access/management_mode_access.rs
=> chore(query): enable SetVariable for ManagementModeAccess

src/query/sql/src/executor/format.rs, src/query/sql/src/planner/optimizer/heuristic/prune_unused_columns.rs, tests/logictest/suites/mode/cluster/04_0002_explain_v2, tests/logictest/suites/mode/standalone/explain/explain.test, tests/logictest/suites/mode/standalone/explain/prewhere_optimizaiton.test, tests/logictest/suites/mode/standalone/explain/prune_column.test
=> feat: prune unused columns for union

docs/doc/15-sql-functions/10-aggregate-functions/aggregate-approx_count-distinct.md, docs/doc/15-sql-functions/10-aggregate-functions/aggregate-count-distinct.md
APPROX_COUNT_DISTINCT
Closes #issue
=> docs: approx_count_distinct

website/src/pages/download/index.tsx
=> chore: Removing the Version Cache

src/common/base/src/base/runtime_tracker.rs
=> refactor(mem-tracker): universal tracker restore for normal quit and panic

src/common/base/src/base/runtime_tracker.rs, src/common/base/tests/it/runtime_tracker.rs, src/common/storage/src/runtime_layer.rs, src/query/service/src/pipelines/executor/executor_worker_context.rs
refactor(base): remove some unsafe code
Closes #issue
=> refactor(base): remove some unsafe code

.github/actions/setup_docker/action.yml, .github/workflows/databend-release.yml
=> chore: do not push docker image to acr when release

Cargo.lock, src/query/codegen/src/writes/register.rs, src/query/expression/src/function.rs, src/query/expression/src/register.rs, src/query/functions-v2/Cargo.toml, src/query/functions-v2/benches/bench.rs, src/query/functions-v2/src/scalars/mod.rs, src/query/functions-v2/tests/it/aggregates/mod.rs, src/query/functions-v2/tests/it/scalars/mod.rs
=> feat(function-v2): add a global builtin function registry

Cargo.lock
feat: Add aws regional sts support
Closes #8813
=> feat: Add aws regional sts support

src/query/service/src/interpreters/interpreter_unsetting.rs, src/query/settings/src/lib.rs
change try_drop_settings async
Closes #8898
=> fix(query): change try_drop_settings async

docs/doc/14-sql-commands/80-setting-cmds/set-global.md, docs/doc/14-sql-commands/80-setting-cmds/unset.md
added doc for UNSET.
Closes #issue
=> docs: unset

src/common/base/src/base/thread.rs
fix(base): try fix lost tracker
Closes #issue
=> fix(base): try fix lost tracker

src/binaries/query/main.rs, src/common/base/src/base/mod.rs, src/common/base/src/base/runtime_tracker.rs, src/query/config/src/outer_v0.rs
=> feat(mem-limit): limit global memory usage

docs/doc/10-deploy/07-query/10-query-config.md, docs/doc/10-deploy/07-query/20-query-metrics.md
=> docs: update document for query metrics

docs/doc/10-deploy/07-query/20-query-metrics.md
=> docs: update description for query metrics

src/common/base/src/mem_allocator/mmap_allocator.rs
fix(base): add track for mmap allocator
Closes #issue
=> fix(base): add track for mmap allocator

docs/doc/11-integrations/00-api/00-rest.md, src/query/service/src/servers/http/v1/json_block.rs, src/query/service/src/servers/http/v1/query/http_query.rs, src/query/service/src/servers/http/v1/query/page_manager.rs, src/query/service/tests/it/servers/http/json_block.rs
=> chore(http handler): clear code about string_fields.

src/query/sql/src/planner/binder/project.rs, tests/logictest/suites/base/03_dml/03_0033_select_list, tests/logictest/suites/crdb/select
Support 
select table.* from table 
and
select database.table.* from table 
Closes #8906
=> feat(query): QualifiedName support 'db.table.*' and 'table.*'

src/query/storages/fuse/fuse/src/operations/mutation/compact/compact_transform.rs
Add retry operation when write data. 
Fix out of memory bug.
Closes #issue
=> fix(storage): compact oom and write not retried

src/common/storage/src/config.rs, src/common/storage/src/operator.rs, src/query/config/src/outer_v0.rs, src/query/service/tests/it/configs.rs, src/query/service/tests/it/storages/testdata/system-tables.txt, src/query/storages/fuse/fuse/src/fuse_table.rs
fix: Disable moka cache by default
=> fix: Disable moka cache by default

.github/workflows/i18n.yml
include untranslated files, try to avoid broken links
Closes #issue
=> docs(l10n): include untranslated files

src/query/service/src/api/http/v1/instance_status.rs, src/query/service/src/sessions/session_mgr.rs, src/query/service/tests/it/api/http/status.rs, src/query/service/tests/it/tests/context.rs, src/query/service/tests/it/tests/mod.rs
=> chore(http): fix query num in v1/status

website/package.json
docs: Only export approved translations
=> docs: Only export approved translations

docker/Dockerfile, docker/bootstrap.sh, docker/databend-query-docker.toml, scripts/ci/deploy/config/databend-query-node-1.toml, scripts/ci/deploy/config/databend-query-node-2.toml, scripts/ci/deploy/config/databend-query-node-3.toml
So this image can be used as service image in Github Actions or other testing system.
Closes #issue
=> chore: support adding default user for combined docker image

website/blog/2022-11-28-hive.md
=> docs(hive): add docs about how to deploy and query hive sqls

src/common/io/src/consts.rs, src/query/formats/src/field_encoder/values.rs, src/query/service/src/servers/http/v1/json_block.rs, src/query/service/src/servers/mysql/writers/query_result_writer.rs
originally proposed by  @sandflee  https://github.com/datafuselabs/databend/pull/8929#issuecomment-1326221921
discussed in https://github.com/datafuselabs/databend/discussions/8941
=> feat(mysql handler): return "NaN"/"Infinity" instead of 'nan'/'inf'

tests/logictest/suites/query/join.test
Can't reproduce in my local. 
Run it in CI to see how's it going
Closes #8788
=> chore: enable flaky right join test

tests/logictest/suites/query/join.test
Reverts datafuselabs/databend#9007
=> Revert "chore: enable flaky right join test"

src/query/service/src/servers/http/v1/stage.rs
=> feat(query): support expanding ~ to usesr stage for upload_to_stage

src/query/pipeline/core/src/processors/port_trigger.rs
fix(processor): try fix update list memory leak
Closes #issue
=> fix(processor): try fix update list memory leak

src/meta/api/src/share_api_impl.rs
fix: Some database has been created before share, so they has no `DatabaseIdToName` for share, create DatabaseIdToName if need.
Closes #issue
=> fix: fix share db bug, create DatabaseIdToName if need

src/query/ast/src/ast/format/ast_format.rs, src/query/ast/src/ast/format/syntax/dml.rs, src/query/ast/src/ast/statements/copy.rs, src/query/ast/src/ast/statements/presign.rs, src/query/ast/src/parser/statement.rs, src/query/ast/tests/it/testdata/statement.txt, src/query/sql/src/planner/binder/copy.rs, src/query/sql/src/planner/binder/presign.rs
1.  reuse code
2. prepare to use stage_location and uri_location in `select from stage`.
Closes #issue
=> refactor(parser): extract struct StageLocation and  parser stage_location. 

Cargo.lock, src/query/sharing/Cargo.toml, src/query/sharing/src/layer.rs, src/query/sharing/src/lib.rs
feat: Add metrics/logging/tracing for sharing operator
=> feat: Add metrics/logging/tracing for sharing operator

Cargo.lock, src/query/sharing/Cargo.toml, src/query/sharing/src/layer.rs, src/query/sharing/src/signer.rs
refactor: Add logs for sharing endpoint presign
=> refactor: Add logs for sharing endpoint presign

src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_parquet.rs, src/query/pipeline/sources/src/processors/sources/input_formats/input_format.rs, src/query/pipeline/sources/src/processors/sources/input_formats/input_format_text.rs
A minimal impl to be used in the upcoming POC for `select from stage` https://github.com/datafuselabs/databend/issues/7211.
=> feat(format): add basic schema infer for parquet.

docs/doc/14-sql-commands/00-ddl/20-table/60-optimize-table.md, docs/doc/15-sql-functions/111-system-functions/fuse_statistic.md
- added explanations about "OPTIMIZE TABLE <table_name> STATISTIC".
- added function "FUSE_STATISTIC('<database_name>', '<table_name>')".
Closes #issue
=> docs: table statistics information

src/query/sql/src/planner/binder/bind_context.rs, src/query/sql/src/planner/binder/table.rs, src/query/sql/src/planner/semantic/name_resolution.rs, tests/logictest/suites/query/cte.test
=> fix: try to fix cte with duplicate name

website/blog/2022-11-30-databend-weekly-70.md
We will be updating *this week in databend* on our blog.
Closes #issue
=> docs(blog): add this week in databend 70

src/query/expression/src/chunk.rs, src/query/expression/src/converts/from.rs, src/query/expression/src/converts/to.rs, src/query/expression/src/evaluator.rs, src/query/expression/src/expression.rs, src/query/expression/src/kernels/concat.rs, src/query/expression/src/kernels/filter.rs, src/query/expression/src/kernels/scatter.rs, src/query/expression/src/kernels/take.rs, src/query/expression/src/kernels/take_chunks.rs, src/query/expression/src/utils/display.rs, src/query/functions-v2/tests/it/aggregates/mod.rs, src/query/functions-v2/tests/it/scalars/mod.rs
=> refactor(expr): add Index generic for Chunk

src/common/io/src/buffer/buffer_read_datetime_ext.rs, src/common/io/src/cursor_ext/cursor_read_datetime_ext.rs, src/query/expression/src/utils/date_helper.rs, tests/logictest/suites/query/02_function/02_0002_function_cast
=> fix(query): to_date respect tz

docs/doc/14-sql-commands/20-query-syntax/dml-select.md
added EXCLUDE to select statement
Closes #issue
=> docs: exclude parameter

src/query/storages/fuse/fuse/src/table_functions/fuse_snapshots/fuse_snapshot.rs
for limited selection from fuse_snapshot like this
~~~
select snapshot_id from fuse_snapshot('default','tb01') limit 10;
~~~
the `SnapshotIO` being used will collect a limited number of snapshots first, and then, try to build a chain of snapshots from them.  if the snapshots collected are not of a consecutive segment of the history chain, the number of items of the final resultset will not be as expected.
In this PR, for `select ... form fuse_snapshot(..) limit ...`,   `SnapshotHistoryReader` is used instead, which collects the history of snapshots by traversing the snapshot (instead of listing from object storage).
Closes #9102
=> fix: fuse_snapshot with limits may return less items

docs/doc/14-sql-commands/00-ddl/20-table/70-ddl-restore-table.md
added a new command "ALTER TABLE ... FLASHBACK".
Closes #issue
=> docs: flashback

src/query/functions-v2/src/aggregates/adaptors/aggregate_null_unary_adaptor.rs, src/query/functions-v2/src/aggregates/adaptors/aggregate_null_variadic_adaptor.rs, src/query/functions/src/aggregates/adaptors/aggregate_null_unary_adaptor.rs, src/query/functions/src/aggregates/adaptors/aggregate_null_variadic_adaptor.rs, src/query/sql/src/planner/semantic/type_check.rs
1. faster path for case-when to if function
2. don't merge states when `rhs` is in null flag
Closes #issue
=> chore(query): improve some trivial codes

docs/doc/14-sql-commands/90-explain-cmds/explain.md
Added descriptions for EXPLAIN operators and fields.
Closes #issue
=> docs: EXPLAIN operators

src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state_impl.rs, tests/logictest/suites/mode/cluster/issue_9018.test
fix: fix right join bug, issue 9018
Closes https://github.com/datafuselabs/databend/issues/9018
=> fix: fix right join bug, issue 9018

docs/doc/12-load-data/02-local.md
- Fixed argument names.
- Fixed a wrong link.
Closes #issue
=> docs: fix streaming load api

.github/actions/publish_binary/nfpm.yaml, .github/workflows/databend-release.yml
This is the first step towards releasing the packages with [nfpm](https://nfpm.goreleaser.com/)
1. download our release
2. unpack to a path
3. export env: `name` `version` `path`
4. combine `envsubst` and `nfpm`
```
export name="databend"
export version="0.1.0"
export path = "../../../assets"
nfpm pkg --packager deb -f <(envsubst '${nfpm} ${version} ${path}' < nfpm.yaml)
```
```
dpkg -X databend_0.1.0_amd64.deb check
./etc/
./etc/databend/
./etc/databend/databend-meta.toml
./etc/databend/databend-query.toml
./usr/
./usr/local/
./usr/local/bin/
./usr/local/bin/databend-meta
./usr/local/bin/databend-metabench
./usr/local/bin/databend-metactl
./usr/local/bin/databend-query
./usr/local/share/ …
```
=> ci: try to release deb package

website/blog/2022-12-07-databend-weekly-71.md
add this week in Databend 71
**What's On In Databend**
- RESTORE TABLE
**What's Up Next**
- Add Build Information to the Error Report
Closes #issue
=> docs(blog): add this week in Databend 71

website/blog/2022-12-07-databend-weekly-71.md
=> docs(fix): fix the url to issue 9117

src/query/service/src/servers/mysql/mysql_federated.rs
compatible with mysqldump file load
Closes https://github.com/datafuselabs/databend/issues/9151
=> fix:compatible with mysqldump file load

src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_tsv.rs
=> fix(TSV): custom field_delimiter.

docs/doc/00-overview/index.md
Fixed description about indexing in Overview.
Closes #issue
=> docs: fix description about indexing

src/query/ast/src/parser/mod.rs, src/query/ast/src/parser/query.rs, src/query/ast/src/parser/stage.rs, src/query/ast/src/parser/statement.rs
because they are used both in query.rs and statement.rs
make it a separate pr to avoid conflict.
Closes #issue
=> refactor(parser): extract stage related rules.

tests/suites/1_stateful/01_load_v2/01_0004_streaming_variant_load.sh, tests/suites/1_stateful/05_formats/05_03_xml/05_03_01_xml_v1.sh, tests/suites/1_stateful/05_formats/05_03_xml/05_03_02_xml_v2.sh, tests/suites/1_stateful/05_formats/05_03_xml/05_03_03_xml_v3.sh
`quote` and `row_tag` are landing, modify the remain tests.
Closes #issue
=> chore: modify the remaining tests

.github/actions/test_unit/action.yml, Cargo.lock, src/query/catalog/src/table_context.rs, src/query/service/tests/it/servers/http/http_query_handlers.rs, src/query/service/tests/it/tests/sessions.rs, src/query/settings/src/lib.rs
feat: Bump opendal to fix AWS IMDSv2 credential
- https://github.com/datafuselabs/opendal/discussions/1075
- https://github.com/datafuselabs/opendal/discussions/1078
=> feat: Bump opendal to fix aws IMDSv2 credential

.github/actions/publish_binary/action.yml, .github/workflows/databend-release.yml
- add release mode to distinguish between normal and hive
Closes #issue
=> ci: add release mode normal/hive

src/meta/service/src/api/grpc/grpc_service.rs, src/meta/service/src/meta_service/raftmeta.rs, src/meta/service/src/watcher/mod.rs, src/meta/service/src/watcher/watcher_manager.rs, src/meta/service/src/watcher/watcher_stream.rs
=> refactor(meta/watcher): remove WatcherManager, adjust type names

website/blog/2022-12-13-indexing.md
try to fix https://vercel.com/databend/databend/CNjJgoYSwBx4RsyKk3QFYj1xcFtb
Closes #issue
=> docs(fix): try to fix img path

src/common/base/src/base/singleton_instance.rs, src/query/service/src/sessions/session_mgr.rs, src/query/service/tests/it/servers/http/http_query_handlers.rs, src/query/service/tests/it/tests/sessions.rs
fix: Address unit tests hang on multi partition
=> fix: Address unit tests hang on multi partition

src/query/service/src/api/rpc/exchange/exchange_manager.rs, src/query/service/src/interpreters/interpreter.rs, src/query/service/src/interpreters/interpreter_delete.rs, src/query/service/src/interpreters/interpreter_table_optimize.rs, src/query/service/src/interpreters/interpreter_table_recluster.rs, src/query/service/src/pipelines/executor/executor_settings.rs, src/query/service/src/pipelines/executor/executor_worker_context.rs, src/query/service/src/pipelines/executor/pipeline_executor.rs, src/query/service/src/pipelines/executor/processor_async_task.rs, src/query/service/src/servers/http/v1/query/execute_state.rs, src/query/service/src/stream/table_read_block_stream.rs, src/query/service/tests/it/storages/fuse/operations/mutation/block_compact_mutator.rs, src/query/service/tests/it/storages/fuse/operations/mutation/deletion_mutator.rs, src/query/service/tests/it/storages/fuse/table_test_fixture.rs
=> chore(executor): add query id in slow log

docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
=> docs(copy): fix typo.

src/query/catalog/src/catalog/interface.rs, src/query/service/src/catalogs/default/database_catalog.rs, src/query/service/src/catalogs/default/immutable_catalog.rs, src/query/service/src/catalogs/default/mutable_catalog.rs, src/query/service/tests/it/storages/fuse/operations/commit.rs, src/query/storages/fuse/fuse/src/operations/truncate.rs, src/query/storages/hive/hive/src/hive_catalog.rs
=> fix: fix bug of delete from table

docs/doc/11-integrations/00-api/00-rest.md
thanks to @hantmac 
```
| pagination | Pagination | No | | a uniq query_id for this POST request |
```
Closes #issue
=> docs: fix typo.

tests/logictest/suites/base/05_ddl/05_0015_ddl_drop_role
fix(ci): try fix logic test failure
Closes #issue
=> fix(ci): try fix logic test failure

src/query/service/src/interpreters/interpreter_insert_v2.rs
Currently, when parse insert values, we use a fixed value(1024) as the capacity of `MutableColumn`. If the number of rows to insert is relatively small, a lot of allocated memory space will not be used. On the contrary, if the number of rows to insert is relatively large, the allocated memory space is not enough, which will lead to frequent resizing and affect performance.
Since we have used the `AhoCorasick` algorithm to find `'` and `\`, we can also find `(` at the same time, and use the number of `(` to estimate the number of rows to insert, so that we can allocate the required memory for insert values and avoid unnecessary resize.
Closes #issue
=> feat(query): estimate insert value rows

tests/sqllogictests/README.md
=> feat: add README for new sqllogictest framework

src/common/hashtable/src/container.rs
fix(base): use alloc error handler to handle hash map alloc error
Closes #issue
=> fix(base): use alloc error handler to handle hash map alloc error

src/common/base/src/rangemap/range_map.rs, src/common/base/src/rangemap/range_map_key.rs
=> feat(range-map): add keys(), values() and iter()

.github/workflows/production.yml
ci: Fix workflow for producation logictest
=> ci: Fix workflow for producation logictest

docs/doc/12-load-data/00-stage.md, docs/doc/14-sql-commands/10-dml/dml-insert.md
=> docs: add insert with stage attachment

src/common/base/src/runtime/runtime.rs, src/common/base/src/runtime/runtime_tracker.rs, src/common/base/src/runtime/thread.rs, src/common/base/tests/it/runtime_tracker.rs
feat(base): record peak memory usage and support log memory usage
Closes #issue
=> feat(base): record peak memory usage and support log memory usage

src/meta/proto-conv/src/user_from_to_protobuf_impl.rs, src/meta/types/src/user_stage.rs, src/query/formats/src/file_format_type.rs, src/query/service/src/interpreters/interpreter_insert_v2.rs, src/query/service/src/servers/http/v1/query/http_query.rs, src/query/sql/src/planner/binder/copy.rs, src/query/sql/src/planner/binder/ddl/stage.rs, src/query/sql/src/planner/binder/insert.rs, src/query/storages/stage/src/attachment.rs
=> refactor: unify apply_file_format_options for copy & insert

src/query/settings/src/lib.rs
=> chore(query): default num_physical_cpus can't be zero

Cargo.lock, src/query/service/tests/it/storages/index/range_filter.rs, src/query/storages/index/Cargo.toml, src/query/storages/index/src/range_filter.rs, tests/logictest/suites/base/09_fuse_engine/09_0009_range_filter
expr in list => max_expr >= min_list and min_expr <= max_list
Closes #9331
=> feat(storage): rangefilter support in

docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
added **on_error** to COPY INTO.
Closes #issue
=> docs: copy on errors

Cargo.lock, tests/sqllogictests/Cargo.toml
=> chore: replace sqllogictest-rs dep url

.github/actions/test_unit/action.yml, src/common/tracing/src/config.rs, src/query/service/tests/it/storages/testdata/configs_table_basic.txt
=> chore(logging): disabled debug log to stderr for sled

src/query/service/src/pipelines/processors/transforms/transform_addon.rs
Default expression columns are already added into the block by
```rust
block = self.expression_transform.transform(block)?;
```
so we don't need to add them again.
=> chore(query): remove rebundant codes.

tests/suites/1_stateful/07_insert_stage/00_0000_insert_with_stage.result, tests/suites/1_stateful/07_insert_stage/00_0000_insert_with_stage.sh
=> chore: add stateful tests for insert with stage

scripts/setup/dev_setup.sh
sccache has switched to opendal, let's dogfood it!
=> ci: Dogfood of sccache pre version for opendal

src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs, tests/sqllogictests/src/client/clickhouse_client.rs, tests/sqllogictests/src/main.rs, tests/sqllogictests/suites/base/09_fuse_engine/09_0001_remote_insert
1. fix native reader.
2. make `sqllogictest` file arg support substring match.
Closes #issue
=> chore(storage): fix native reader

.github/actions/build_linux/action.yml, scripts/setup/dev_setup.sh
=> ci: Switch to sccache

src/query/service/src/schedulers/fragments/fragmenter.rs, src/query/service/src/schedulers/fragments/plan_fragment.rs, src/query/service/src/schedulers/fragments/query_fragment_actions_display.rs, src/query/sql/src/planner/optimizer/property/enforcer.rs, src/query/sql/src/planner/plans/union_all.rs, tests/sqllogictests/suites/base/05_ddl/05_0019_ddl_create_view
I did simple benchmark: `select * from numbers(10000000) union all select * from numbers(10000000);`, there is ~2X improvement.
Closes #9211
=> feat: optimize union under cluster mode

src/query/service/src/servers/http/v1/query/http_query.rs, src/query/service/src/servers/http/v1/query/http_query_manager.rs
http query timeout checker not know query is deleted.
Closes #issue
=> fix(query): false alarm (warning log) about query not exists.

src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_csv.rs, src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_tsv.rs, src/query/pipeline/sources/src/processors/sources/input_formats/input_context.rs, src/query/pipeline/sources/src/processors/sources/input_formats/input_format_text.rs, src/query/service/src/servers/http/clickhouse_handler.rs
they are used only for some formats, should not appear here.
Closes #issue
=> refactor(format): rm row format options from InputContext.

website/package.json, website/yarn.lock
docs: Bump to latest version of docusaurus
=> docs: Bump to latest version of docusaurus

src/query/formats/src/file_format_type.rs, src/query/formats/tests/it/main.rs, src/query/formats/tests/it/output_format_json_each_row.rs, src/query/formats/tests/it/output_format_tcsv.rs, src/query/pipeline/sources/src/processors/sources/input_formats/input_context.rs, src/query/pipeline/sources/src/processors/sources/input_formats/input_format_text.rs, src/query/service/src/servers/http/clickhouse_handler.rs, src/query/storages/stage/src/stage_table_sink.rs
simplify/clear up the logics about old streaming load.
Closes #issue
=> refactor(format): adjust interface of FileFormatOptionsExt.

Cargo.lock, src/binaries/Cargo.toml, src/query/storages/fuse/src/io/read/block_reader.rs, src/query/storages/fuse/src/io/read/block_reader_parquet.rs, src/query/storages/fuse/src/io/read/bloom_index_reader.rs, src/query/storages/fuse/src/metrics/fuse_metrics.rs, src/query/storages/fuse/src/operations/fuse_sink.rs, src/query/storages/fuse/src/operations/mutation/compact/block_compact_mutator.rs, src/query/storages/fuse/src/operations/mutation/compact/compact_source.rs, src/query/storages/fuse/src/operations/mutation/compact/compact_transform.rs, src/query/storages/fuse/src/operations/read/parquet_data_source_deserializer.rs, src/query/storages/fuse/src/pruning/pruning_executor.rs
* add metrics for block and block index write
* add metrics for compact
* add metrics for pruning
* remove unused metrics
Closes #issue
=> feat: add more metrics for fuse compact and block write

src/query/storages/fuse/src/operations/read_partitions.rs, src/query/storages/fuse/src/pruning/pruning_executor.rs, tests/sqllogictests/suites/base/09_fuse_engine/09_0001_remote_insert
=> fix(fuse): disable limit pruner when there is filter

docs/doc/10-deploy/09-upgrade/50-upgrade.md
- Added a note about rollback.
- Removed duplicate details about checking compatibility and created a reference link to https://databend.rs/doc/deploy/upgrade/compatibility
- Refactored the other parts on the page.
Closes #issue
=> docs: downgrade notes

Cargo.lock, src/query/functions-v2/Cargo.toml, src/query/functions-v2/src/scalars/hash.rs, src/query/functions-v2/src/scalars/mod.rs, src/query/functions-v2/src/scalars/string.rs, src/query/functions-v2/tests/it/scalars/hash.rs, src/query/functions-v2/tests/it/scalars/mod.rs, src/query/functions-v2/tests/it/scalars/testdata/function_list.txt, src/query/functions-v2/tests/it/scalars/testdata/hash.txt
migrate hash func to func-v2
Closes #issue
=> feat: migrate hash func to func-v2

tests/sqllogictests/src/main.rs
fix(sqllogictest): Return error if meeting test error records
=> fix(sqllogictest): Return error if meeting test error records

scripts/ci/ci-run-sqllogic-tests-cluster.sh, scripts/ci/ci-run-sqllogic-tests.sh, tests/compat/test-compat.sh, tests/fuse-compat/test-fuse-compat.sh, tests/sqllogictests/src/arg.rs, tests/sqllogictests/src/main.rs, tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables
1.  add arg parallel
2. add arg enable_sandbox
Closes #issue
=> chore(test): add parallel to logictest

scripts/ci/ci-run-sqllogic-tests-cluster.sh, scripts/ci/ci-run-sqllogic-tests.sh, tests/compat/test-compat.sh, tests/fuse-compat/test-fuse-compat.sh, tests/sqllogictests/README.md, tests/sqllogictests/src/arg.rs
1. change default value of parallel to 1
2. add readme for how to enable parallel
Closes #issue
=> chore(sqllogictest): change parallel default value

Cargo.lock, src/query/storages/fuse/Cargo.toml, src/query/storages/fuse/src/fuse_table.rs, src/query/storages/fuse/src/operations/mod.rs, src/query/storages/fuse/src/operations/read_data.rs, src/query/storages/fuse/src/operations/recluster.rs, src/query/storages/parquet/src/table_function/read.rs
* change adjust_io_request to `max(max_threads, max_storage_io_requests)`
Closes #9418
=> refactor(io): change io request to max(max_threads, io_requests)

src/query/storages/fuse/src/io/read/block_reader_parquet.rs, src/query/storages/fuse/src/io/read/read_settings.rs, src/query/storages/fuse/src/operations/mutation/compact/compact_transform.rs, src/query/storages/fuse/src/operations/mutation/deletion/deletion_source.rs, src/query/storages/fuse/src/operations/read/parquet_data_source_reader.rs
refactor(query): use merge io for compact
Closes #issue
=> refactor(query): use merge io for compact

scripts/setup/dev_setup.sh
[ci: Specify tag for sccache](https://github.com/datafuselabs/databend/commit/21873ff93a8c4007162b86580aaa8fc362c65d88)
=> ci: Specify tag for sccache 

Cargo.lock, src/query/ast/Cargo.toml, src/query/ast/src/parser/mod.rs, src/query/ast/src/parser/token.rs, src/query/storages/information-schema/Cargo.toml, src/query/storages/information-schema/src/keywords_table.rs
- Add all reserved keywords in information_schema
Closes #https://github.com/datafuselabs/databend/issues/9047
=> feat: add all reserved keywords in information_schema

Cargo.lock, src/query/storages/cache/Cargo.toml, src/query/storages/cache/src/lib.rs, src/query/storages/cache/src/object.rs, src/query/storages/cache/src/providers/by_pass_cache.rs, src/query/storages/cache/src/providers/memory_bytes_cache.rs, src/query/storages/cache/src/providers/memory_items_cache.rs, src/query/storages/cache/src/providers/metrics.rs, src/query/storages/cache/src/providers/mod.rs
* add metrics for the cache
* add `Sync+Send` which backport from https://github.com/BohuTANG/databend/pull/39 by @dantengsky 
Closes #issue
=> feat(cache): add metrics for new cache

README.md, docs/doc/00-overview/index.md, docs/doc/90-contributing/02-roadmap.md
=> feat(readme): roadmap 2022 -> 2023

src/query/formats/src/file_format_type.rs, src/query/formats/src/output_format/json.rs, tests/suites/1_stateful/05_formats/05_06_json/05_06_01_json_output.result
=> feat(query): add schema to json output

.github/workflows/dev-macos.yml, src/query/formats/src/file_format_type.rs, src/query/formats/src/output_format/json.rs, tests/suites/1_stateful/05_formats/05_06_json/05_06_01_json_output.result
* fix content-type for json format response
Closes #issue
=> feat(query): add rows to json format response

docs/doc/90-contributing/01-good-pr.md
Made some language refactors to the beginning part of **Your First Databend Pull Request**, as it's linked to the Databend Home page.
Closes #issue
=> docs: refactor first pr page

docs/doc/10-deploy/06-metasrv/15-metasrv-config.md, docs/doc/10-deploy/07-query/10-query-config.md
Added a note to the toml configuration page about the sample files.
Closes #9372
=> docs: sample toml files

tests/sqllogictests/src/client/mod.rs, tests/sqllogictests/src/client/mysql_client.rs, tests/sqllogictests/src/main.rs
=> fix(sqllogictest): fix parallel behavior

Cargo.toml
reduce release compile time
Closes #issue
=> chore: add codegen-units

website/blog/2023-01-04-databend-weekly-75.md
=> docs(blog): add databend weekly 75

website/blog/2023-01-04-databend-weekly-75.md
=> docs(weekly-75): minor fix

.github/mergify.yml, .github/workflows/dev-linux.yml
=> ci: combine sqllogic test handlers to reduce jobs

src/binaries/metactl/snapshot.rs, src/meta/raft-store/src/key_spaces.rs, src/meta/raft-store/src/lib.rs, src/meta/raft-store/src/log/raft_log.rs, src/meta/raft-store/src/state/raft_state.rs, src/meta/raft-store/src/state_machine/sm.rs, src/meta/raft-store/tests/it/state_machine/expire.rs, src/meta/service/src/export.rs, src/meta/service/src/meta_service/raftmeta.rs
=> refactor(raft-store): move raft-store kv ser/de into common-raft-store

src/query/functions/src/aggregates/aggregate_combinator_distinct.rs, src/query/functions/src/aggregates/aggregate_distinct_state.rs
=> chore(query): use smaller distinct state

Cargo.lock, src/query/expression/src/kernels/filter.rs, src/query/expression/src/types/string.rs, src/query/functions/Cargo.toml, src/query/functions/src/aggregates/aggregate_distinct_state.rs, src/query/functions/src/scalars/comparison.rs, src/query/service/src/pipelines/processors/transforms/group_by/aggregator_groups_builder.rs, tests/sqllogictests/suites/base/20+_others/20_0010_expression_string_like
=> chore(query): use memchr to improve compare

src/query/service/tests/it/sql/planner/format/mod.rs, src/query/sql/src/executor/physical_plan_builder.rs, src/query/sql/src/executor/physical_scalar.rs, src/query/sql/src/planner/binder/aggregate.rs, src/query/sql/src/planner/binder/sort.rs, src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs, src/query/sql/src/planner/optimizer/heuristic/subquery_rewriter.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_union.rs, src/query/sql/src/planner/plans/scalar.rs, src/query/sql/src/planner/semantic/grouping_check.rs, src/query/sql/src/planner/semantic/lowering.rs, src/query/sql/src/planner/semantic/type_check.rs
=> feat(planner): support `tuple.1` and get(1)(tuple)

src/query/expression/src/types/string.rs, src/query/functions/src/scalars/string.rs, src/query/service/src/pipelines/processors/transforms/aggregator/aggregator_final_parallel.rs, src/query/service/src/pipelines/processors/transforms/group_by/aggregator_groups_builder.rs, src/query/service/src/pipelines/processors/transforms/group_by/aggregator_polymorphic_keys.rs
=> refactor(query): improve StringBuilder v2

Cargo.lock, src/common/exception/Cargo.toml, src/common/storage/Cargo.toml, src/common/storage/src/cache.rs, src/common/storage/src/metrics.rs, src/common/storage/src/runtime_layer.rs, src/query/pipeline/sources/Cargo.toml, src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_parquet.rs, src/query/service/Cargo.toml, src/query/sharing-endpoint/Cargo.toml, src/query/sharing/Cargo.toml, src/query/sharing/src/layer.rs, src/query/sql/Cargo.toml, src/query/storages/cache/Cargo.toml, src/query/storages/fuse/Cargo.toml, src/query/storages/fuse/src/io/read/meta_readers.rs, src/query/storages/hive/hive/Cargo.toml, src/query/storages/information-schema/Cargo.toml, src/query/storages/memory/Cargo.toml, src/query/storages/null/Cargo.toml, src/query/storages/parquet/Cargo.toml, src/query/storages/random/Cargo.toml, src/query/storages/share/Cargo.toml, src/query/storages/stage/Cargo.toml, src/query/storages/system/Cargo.toml, src/query/storages/table-meta/Cargo.toml, src/query/storages/table-meta/src/caches/memory_cache_reader.rs
refactor: Bump opendal for streaming read support
Release Note: https://github.com/datafuselabs/opendal/discussions/1147
=> refactor: Bump opendal for streaming read support

Cargo.lock, src/query/storages/fuse/src/io/read/block_reader.rs, src/query/storages/fuse/src/io/read/block_reader_native.rs, src/query/storages/hive/hive/Cargo.toml, src/query/storages/hive/hive/src/hive_parquet_block_reader.rs
feat: Retry range read request to tolerate UnexpectedEof
=> feat: Retry range read request to tolerate UnexpectedEof

src/query/storages/fuse/src/table_functions/fuse_blocks/fuse_block.rs
=> chore(query): fix fuse block unwrap

Cargo.lock
fix: Bump opendal to fix perf regression of range_read
=> fix: Bump opendal to fix perf regression of range_read

Cargo.lock, src/common/hashtable/src/traits.rs, src/query/storages/index/Cargo.toml
=> chore(hashtable): avoid RUSTFLAGS="-C target-feature=+sse4.2" warning

src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_csv.rs, src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_ndjson.rs, src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_tsv.rs, src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_xml.rs, src/query/pipeline/sources/src/processors/sources/input_formats/input_format_text.rs
purposes:
1. separate states of diff format
2. prepare for https://github.com/datafuselabs/databend/issues/9426
3. fix and simplify XMLInputFormat impl.
Closes #issue
=> refactor(format): extract AligningStateTextBased.

src/query/expression/src/block.rs, src/query/expression/src/values.rs
This can help in Q37/Q38 in hits dataset which reduces the memory cost.
Related #9483
=> chore(query): empty filter result will not share the column ref

Cargo.lock
feat: Allow retry ObjectReader IO operations
=> feat: Allow retry ObjectReader IO operations

src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_csv.rs, src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_ndjson.rs, src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_tsv.rs, src/query/pipeline/sources/src/processors/sources/input_formats/impls/input_format_xml.rs, src/query/pipeline/sources/src/processors/sources/input_formats/input_context.rs, src/query/pipeline/sources/src/processors/sources/input_formats/input_format_text.rs, src/query/pipeline/sources/src/processors/sources/input_formats/input_split.rs
Closes https://github.com/datafuselabs/databend/issues/9426
=> refactor(format): richer error context.

tests/sqllogictests/src/error.rs, tests/sqllogictests/src/main.rs
Change log output Mysql to MySQL
Closes #9538
=> chore:Change log output Mysql to MySQL

Cargo.lock, src/query/functions/Cargo.toml, src/query/functions/src/scalars/geo.rs
Signed-off-by: 蔡略 <cailue@bupt.edu.cn>
bump geo-types to 0.7.8, prepare for toolchain updates
Closes #issue
=> chore(function): bump geo-types version

scripts/setup/rust-toolchain.toml
Signed-off-by: 蔡略 <cailue@bupt.edu.cn>
This is part of #9540, need to build CI toolchain
Closes #issue
=> chore: bump rust version in CI

src/query/functions/src/scalars/string_multi_args.rs, tests/sqllogictests/suites/query/02_function/02_0054_function_string_regexp_replace, tests/suites/0_stateless/13_tpch/13_0000_prepare.sh
=> chore(function): update regexp_replace

src/query/catalog/src/table_context.rs, src/query/service/src/interpreters/interpreter_insert_v2.rs, src/query/service/src/servers/http/v1/query/http_query.rs
=> fix(query): replace if file_format_options for insert with stage attachment

src/query/expression/src/function.rs, src/query/expression/src/types/date.rs, src/query/expression/src/types/timestamp.rs, src/query/functions/src/scalars/arithmetic.rs, src/query/functions/src/scalars/boolean.rs, src/query/functions/src/scalars/datetime.rs, src/query/functions/src/scalars/variant.rs, src/query/functions/tests/it/scalars/cast.rs, src/query/functions/tests/it/scalars/testdata/arithmetic.txt, src/query/functions/tests/it/scalars/testdata/cast.txt, src/query/functions/tests/it/scalars/testdata/datetime.txt, src/query/functions/tests/it/scalars/testdata/other.txt, src/query/functions/tests/it/scalars/testdata/regexp.txt, src/query/functions/tests/it/scalars/testdata/string.txt, src/query/functions/tests/it/scalars/testdata/variant.txt
=> fix(expr): check_date() and to_string(boolean) may panic

src/query/ast/src/parser/expr.rs, src/query/functions/tests/it/scalars/testdata/cast.txt
=> fix breaking test since #9561

docs/doc/14-sql-commands/80-setting-cmds/set-global.md, src/query/ast/src/ast/format/ast_format.rs, src/query/ast/src/ast/statements/statement.rs, src/query/ast/src/parser/statement.rs, src/query/ast/src/visitors/visitor.rs, src/query/ast/src/visitors/visitor_mut.rs, src/query/ast/tests/it/parser.rs, src/query/ast/tests/it/testdata/statement.txt, src/query/expression/src/utils/display.rs, src/query/sql/src/planner/binder/setting.rs, tests/sqllogictests/suites/base/06_show/06_0003_show_settings
Support sql
```sql
set max_memory_usage = 1024*1024*1024*2
```
Closes #9456
=> feat(query): set setting support expr

docs/doc/11-integrations/00-api/10-put-to-stage.md
Fixed the doc bug #9573 
Closes #9573
=> docs: file upload api

docs/doc/12-load-data/02-local.md
=> docs: fix record delimiter

src/query/service/src/servers/http/v1/http_query_handlers.rs, src/query/service/tests/it/servers/http/http_query_handlers.rs
change schema in query response from `Option<DataSchemaRef>` to  `Vec<QueryResponseField>`
for: https://github.com/databendcloud/bendsql/issues/52
=> fix(query): format response schema fields

.github/actions/test_sqllogic_cluster_linux/action.yml, .github/actions/test_sqllogic_standalone_linux/action.yml, Cargo.lock, scripts/ci/ci-run-sqllogic-tests-cluster.sh, scripts/ci/ci-run-sqllogic-tests.sh, tests/compat/test-compat.sh, tests/fuse-compat/test-fuse-compat.sh, tests/sqllogictests/Cargo.toml, tests/sqllogictests/README.md, tests/sqllogictests/src/client/clickhouse_client.rs, tests/sqllogictests/src/client/http_client.rs, tests/sqllogictests/src/client/mod.rs, tests/sqllogictests/src/client/mysql_client.rs, tests/sqllogictests/src/error.rs, tests/sqllogictests/src/main.rs
Can be released as `databend-sqllogictest` later by @Xuanwo 
for: #9287
=> ci: run sqllogictests with binary

Cargo.toml, src/common/exception/Cargo.toml, src/common/hashtable/Cargo.toml, src/common/io/Cargo.toml, src/common/jsonb/Cargo.toml, src/common/storage/Cargo.toml, src/query/expression/Cargo.toml, src/query/formats/Cargo.toml, src/query/functions/Cargo.toml, src/query/pipeline/sources/Cargo.toml, src/query/service/Cargo.toml, src/query/sharing-endpoint/Cargo.toml, src/query/sql/Cargo.toml, src/query/storages/common/cache/Cargo.toml, src/query/storages/common/table-meta/Cargo.toml, src/query/storages/fuse/Cargo.toml, src/query/storages/hive/hive/Cargo.toml, src/query/storages/information-schema/Cargo.toml, src/query/storages/memory/Cargo.toml, src/query/storages/null/Cargo.toml, src/query/storages/parquet/Cargo.toml, src/query/storages/random/Cargo.toml, src/query/storages/share/Cargo.toml, src/query/storages/stage/Cargo.toml, src/query/storages/system/Cargo.toml
=> chore(query): make opendal be workspace dep

.github/workflows/production.yml
=> ci: add `test_stateful_cluster_linux` for production

docs/doc/21-use-cases/01-analyze-ontime-with-databend-on-ec2-and-s3.md, docs/doc/21-use-cases/02-analyze-nginx-logs-with-databend-and-vector.md, docs/doc/21-use-cases/03-analyze-user-retention-with-databend.md, docs/doc/21-use-cases/04-analyze-funnel-with-databend.md, docs/doc/21-use-cases/05-analyze-hits-dataset-with-databend.md
This PR fixed vague descriptions spotted during the translation work.
Closes #issue
=> docs: fix usecases

docs/doc/10-deploy/06-metasrv/10-metasrv-deploy.md, docs/doc/10-deploy/06-metasrv/60-metasrv-status.md, website/docusaurus.config.js
=> docs: add versioned dropdown

src/query/functions/tests/it/scalars/testdata/geo.txt
Hot fix: regenerate test data
Closes #issue
=> chore: regenerate test data

src/query/sql/src/planner/plans/aggregate.rs
Improve aggregator cardinality by ndv
Because ndv will be update during query execution, so we don't need use histogram for it.
Closes https://github.com/datafuselabs/databend/issues/9410
=> feat: enhance aggregator cardinality evaluation

src/query/sql/src/planner/optimizer/cost/cost_model.rs
The issue will help tpch18 (which will be converted to right semi join before the ticket)
Due to implementation reasons, right semi join is more expensive than left semi join.
So if join type is right anti or right semi, cost needs multiply three (an approximate value).
```sql
mysql> select count() from (select * from numbers(10000000) as t1) right semi join (select * from numbers(10000000) as t2) on t1.number = t2.number;
+---------+
| count() |
+---------+
| 9475712 |
+---------+
1 row in set (2.35 sec)
Read 20000000 rows, 152.59 MiB in 2.350 sec., 8.51 million rows/sec., 64.92 MiB/sec.
mysql> select count() from (select * from numbers(10000000) as t1) left semi join (select * from …
```
=> fix: change cost of right semi join

.github/workflows/release.yml, docker/Dockerfile, docker/README.md, docker/bootstrap.sh, docker/cache/Dockerfile, docker/query-config.toml
=> ci: support setup minio storage & external s3 storage in docker image

docs/doc/13-sql-reference/70-system-tables/system-build-options.md, src/query/service/src/databases/system/mod.rs, src/query/service/src/databases/system/system_database.rs, src/query/service/tests/it/storages/system.rs, src/query/storages/system/src/build_options_table.rs, src/query/storages/system/src/lib.rs
- move to storages/system
- add unit tests
- add docs
Closes #issue
=> refactor: move build options table & add unit test

src/query/service/src/interpreters/access/privilege_access.rs, src/query/service/src/interpreters/interpreter_delete.rs, src/query/service/src/interpreters/interpreter_update.rs, tests/suites/0_stateless/20+_others/20_0012_privilege_access.result, tests/suites/0_stateless/20+_others/20_0012_privilege_access.sh
Add privilege check for insert/delete/optimize
Closes #issue
=> feat: Add privilege check for insert/delete/optimize

src/query/ast/src/ast/format/pretty_format.rs, src/query/service/src/interpreters/interpreter_explain_v2.rs, src/query/service/src/schedulers/fragments/query_fragment_actions_display.rs, src/query/sql/src/executor/format.rs, tests/sqllogictests/suites/mode/cluster/exchange.test
=> chore(planner): unify format of `EXPLAIN FRAGMENTS`

src/query/service/src/pipelines/pipeline_builder.rs, src/query/service/src/pipelines/processors/transforms/transform_convert_grouping.rs, tests/sqllogictests/suites/base/03_dml/03_0036_two_level_efficiently_memory_aggregator
fix(query): fix efficiently_memory_final_aggregator result is not stable
Closes #9673
=> fix(query): fix efficiently_memory_final_aggregator result is not stable

docker/README.md, docker/bootstrap.sh
* add note for MinIO download.
* fix bucket empty for external s3 storage.
Closes #issue
=> ci: fix env mismatch with docs in docker image

src/query/ast/src/parser/expr.rs, src/query/ast/src/parser/token.rs, src/query/ast/tests/it/testdata/expr-error.txt, src/query/ast/tests/it/testdata/statement-error.txt, src/query/expression/src/schema.rs, src/query/expression/src/utils/display.rs, src/query/functions/tests/it/scalars/testdata/array.txt, src/query/functions/tests/it/scalars/testdata/cast.txt, src/query/functions/tests/it/scalars/testdata/comparison.txt, src/query/functions/tests/it/scalars/testdata/function_list.txt, src/query/functions/tests/it/scalars/testdata/geo.txt, src/query/functions/tests/it/scalars/testdata/tuple.txt, src/query/functions/tests/it/scalars/testdata/variant.txt, tests/suites/1_stateful/05_formats/05_06_json/05_06_01_json_output.result, tests/suites/1_stateful/05_formats/05_06_json/05_06_01_json_output.sh
=> feat(query): improve wrapped display

src/query/expression/src/kernels/group_by_hash.rs, src/query/sql/src/planner/semantic/distinct_to_groupby.rs, tests/sqllogictests/suites/base/03_dml/03_0022_select_distinct
1. fix count distinct rewrite bug
2. improve group by unsigned number's deserialization
Closes #issue
=> chore(query): fix count distinct rewrite bug

src/query/storages/fuse/src/operations/gc.rs
cleanup unused code
Closes #9705
=> chore: cleanup commented code (gc.rs)

src/query/storages/fuse/src/io/read/bloom_index/filter_reader.rs, src/query/storages/fuse/src/io/read/bloom_index/loader.rs, src/query/storages/fuse/src/pruning/fuse_bloom_pruner.rs, src/query/storages/fuse/src/pruning/mod.rs, src/query/storages/fuse/src/pruning/pruning_executor.rs
* `pruner.rs` -> `fuse_bloom_pruner.rs`
* remove unused `TableContext` from bloom io
Parts #9702
=> refactor(pruning):pruner.rs -> fuse_bloom_pruner.rs

src/query/service/src/pipelines/processors/transforms/transform_convert_grouping.rs
fix(query): fix query hang in two level aggregator(hits dataset query 10)
Closes #issue
=> fix(query): fix query hang in two level aggregator

src/query/storages/fuse/src/pruning/block_pruner.rs, src/query/storages/fuse/src/pruning/fuse_pruner.rs, src/query/storages/fuse/src/pruning/pruning_statistics.rs, src/query/storages/fuse/src/pruning/segment_pruner.rs
* make the pruning stats more readable
Closes #issue
=> chore(fuse): refine the pruning stats

website/blog/2023-01-25-databend-weekly-78.md
=> docs(weekly): add this week in databend 78

Cargo.lock, Cargo.toml
Release Note of opendal: https://github.com/datafuselabs/opendal/discussions/1234
=> refactor: Avoid register_error_count in MetricsReader

Cargo.lock, Cargo.toml, src/query/functions/Cargo.toml, src/query/service/Cargo.toml, src/query/sql/Cargo.toml
=> chore(bumpalo): make bumpalo to workspace and bump to latest 3.12.0

docs/doc/10-deploy/02-deploying-databend.md
Added a note to minio deploy.
Closes #9682
=> docs: add note to minio deploy

tests/sqllogictests/suites/mode/standalone/explain/join_reorder/cycles.test, tests/sqllogictests/suites/mode/standalone/explain/join_reorder/star.test, tests/sqllogictests/suites/mode/standalone/explain/join_reorder/star_multiple_tables.test
=> fix(chore): Fix flaky tests

README.md, docs/doc/00-overview/index.md
* add feature-rich to README
Closes #issue
=> docs(readme): add feature rich

Cargo.lock, src/query/pipeline/core/Cargo.toml, src/query/pipeline/core/src/processors/port.rs, src/query/pipeline/core/tests/it/pipelines/processors/port_test.rs, src/query/service/src/pipelines/executor/executor_graph.rs, src/query/service/src/pipelines/executor/executor_tasks.rs, src/query/service/src/pipelines/executor/pipeline_executor.rs, src/query/service/src/pipelines/executor/processor_async_task.rs
fix(query): fix memory leak for data port
Closes #issue
=> fix(query): fix memory leak for data port

docs/doc/15-sql-functions/130-geo-functions/geohash_decode.md, docs/doc/15-sql-functions/130-geo-functions/geohash_encode.md, docs/doc/15-sql-functions/130-geo-functions/point_in_polygon.md
- GEO_TO_H3
- GEOHASH_DECODE
- GEOHASH_ENCODE
- POINT_IN_POLYGON
Closes #issue
=> docs: geo functions

.github/actions/artifact_download/action.yml, .github/actions/artifact_upload/action.yml, .github/actions/build_linux/action.yml, .github/actions/setup_build_tool/action.yml, .github/workflows/dev-linux.yml, .github/workflows/production.yml, scripts/setup/run_build_tool.sh
=> ci: use IMDSv2 & show stats for sccache

docs/doc/14-sql-commands/10-dml/dml-update.md
Minor fixes to https://databend.rs/doc/sql-commands/dml/dml-update
Closes #issue
=> docs: update command

src/query/service/src/servers/http/v1/json_block.rs
Closes [#issue](https://github.com/datafuselabs/databend/issues/9807)
=> feat: http handler not check utf8 when serialize results.

src/common/jsonb/src/functions.rs, tests/sqllogictests/suites/query/02_function/02_0002_function_try_cast
=> fix(query): fix panic when cast jsonb to string

src/query/ast/src/parser/stage.rs, src/query/ast/src/parser/token.rs
=> fix: add connection options ACCESS_KEY_SECRET.

Cargo.lock, src/common/metrics/Cargo.toml, src/common/metrics/src/dump.rs, src/query/storages/system/src/metrics_table.rs
Closes #9843 
Other metrics could be add if needed.
=> chore(query): add proc io stats

src/common/metrics/src/dump.rs
=> chore(query): fix macos build

src/common/metrics/Cargo.toml, src/common/metrics/src/dump.rs
=> fix(procfs): fix on macos

docs/doc/00-overview/index.md, docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md, docs/doc/14-sql-commands/10-dml/dml-delete-from.md, docs/doc/14-sql-commands/10-dml/dml-insert.md
=> docs: atomic and idempotency notes

docs/doc/14-sql-commands/10-dml/dml-delete-from.md, docs/doc/14-sql-commands/10-dml/dml-insert.md, docs/doc/14-sql-commands/10-dml/dml-update.md
=> docs: added note for UPDATE

Cargo.lock, src/query/service/tests/it/storages/testdata/columns_table.txt, src/query/storages/system/Cargo.toml, src/query/storages/system/src/columns_table.rs, tests/sqllogictests/suites/base/01_system/01_0006_system_columns
=> feat(query): Support view in system.columns

src/query/sql/src/planner/optimizer/property/histogram.rs
fix(query): fix slow planner when ndv error backtrace
Closes #issue
=> fix(query): fix slow planner when ndv error backtrace

src/query/functions/src/scalars/array.rs, src/query/functions/tests/it/scalars/array.rs, src/query/functions/tests/it/scalars/testdata/array.txt, src/query/functions/tests/it/scalars/testdata/function_list.txt, tests/sqllogictests/suites/query/02_function/02_0061_function_array
support array function `array_unique`, `array_distinct`
part of #7931
=> feat(query): support array function array_unique, array_distinct

src/query/sql/src/planner/binder/sort.rs, tests/sqllogictests/suites/query/aggregate.test
Closes https://github.com/datafuselabs/databend/issues/9866
=> fix: order by contains aggregation function

src/query/service/src/pipelines/processors/transforms/transform_convert_grouping.rs
fix(query): remove finished flag for avoid lost block
Closes #issue
=> fix(query): remove finished flag for avoid lost block

.licenserc.yaml, benchmark/tpch/README.md, benchmark/tpch/gen_data.sh, benchmark/tpch/prepare.sh, tests/sqllogictests/src/arg.rs, tests/sqllogictests/src/client/mysql_client.rs, tests/sqllogictests/src/main.rs, tests/sqllogictests/suites/tpch/queries.test
leverage sqllogictest to benchmark tpch and make benchmark easier
Closes #issue
=> feat: leverage sqllogictest to benchmark tpch

src/query/expression/src/kernels/topk.rs
=> chore(query): remove extra clone

src/query/pipeline/sources/src/input_formats/input_pipeline.rs
DO NOT ignore errors on copy
Closes #9900
=> fix(copy): fix not return error when copy

src/query/service/src/interpreters/interpreter_update.rs, src/query/storages/fuse/src/operations/delete.rs, src/query/storages/fuse/src/operations/update.rs
filed -> field
block_purning -> block_pruning
=> chore: fix typo

tests/sqllogictests/suites/base/03_dml/03_0025_delete_from
=> chore: add test for delete with subquery

benchmark/tpch/README.md, benchmark/tpch/create_table_s3.sh
=> chore(benchmark):add steps to benchmark databend on s3

tests/sqllogictests/src/client/mysql_client.rs, tests/sqllogictests/suites/tpch/queries.test
=> chore(benchmark): add analyze table before run benchmark

.github/workflows/dev-perf.yml, .github/workflows/trusted-perf.yml
* run benchmark with warm 2 and count 5 for faster perf
* fix missing GH_TOKEN on downloading artifacts
Closes #issue
=> chore: upgrade bendsql to 0.3.0 for perf

src/query/service/src/pipelines/pipeline_builder.rs, src/query/service/src/pipelines/processors/transforms/hash_join/desc.rs, src/query/storages/common/index/src/page_index.rs, src/query/storages/common/index/src/range_index.rs, src/query/storages/fuse/src/pruning/bloom_pruner.rs
Reverts datafuselabs/databend#9932
=> Revert "fix(functions): use and_filters instead of and in predicate"

docs/doc/15-sql-functions/112-table-functions/_category_.json, docs/doc/15-sql-functions/112-table-functions/infer_schema.md
=> docs(infer_schmea): add infer_schema to table functions catagory

src/meta/app/src/principal/user_stage.rs, tests/sqllogictests/suites/base/03_dml/03_0028_copy_into_stage, tests/sqllogictests/suites/base/03_dml/03_0031_copy_into_user_stage, tests/sqllogictests/suites/base/06_show/06_0011_show_stages, tests/suites/1_stateful/07_insert_stage/00_0000_insert_with_stage.sh
https://github.com/datafuselabs/databend/issues/9946
there are multi place in doc need to update/ refactor.
doc in another pr https://github.com/datafuselabs/databend/pull/9957
=> feat: default file format to Parquet.

.github/workflows/dev-perf.yml
=> chore(ci): fix check github event name for perf

website/blog/2023-02-08-databend-weekly-80.md
=> docs(weekly): updated based by comments from eric

src/query/storages/fuse/src/io/write/write_settings.rs
* change WriteSettings default compression to TableCompression::default()
Closes #issue
=> fix(write_settings): change compression to TableCompression::default()

src/query/ast/src/ast/statements/stage.rs, src/query/ast/src/parser/stage.rs, src/query/sql/src/planner/binder/table.rs, tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_00_basic.result, tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_00_basic.sh
```
select * from @stage1  (FILE_FORMAT => 'PARQUET')
```
Closes #issue
=> feat: stage table function support option FILE_FORMAT.

Cargo.lock, Cargo.toml, src/common/storage/Cargo.toml, src/common/storage/src/metrics.rs, src/common/storage/src/operator.rs, src/common/storage/src/runtime_layer.rs, src/common/storage/src/stage.rs, src/meta/service/Cargo.toml, src/meta/service/src/network.rs, src/query/service/Cargo.toml, src/query/service/src/interpreters/interpreter_presign.rs, src/query/sharing/Cargo.toml, src/query/sharing/src/layer.rs, src/query/sql/Cargo.toml, src/query/storages/fuse/Cargo.toml, src/query/storages/fuse/src/io/write/block_writer.rs, src/query/storages/fuse/src/io/write/meta_writer.rs, src/query/storages/fuse/src/operations/commit.rs, src/query/storages/information-schema/Cargo.toml, src/query/storages/memory/Cargo.toml, src/query/storages/null/Cargo.toml, src/query/storages/random/Cargo.toml, src/query/storages/stage/Cargo.toml, src/query/storages/stage/src/file.rs, src/query/storages/stage/src/stage_table_sink.rs, src/query/storages/system/Cargo.toml, tests/suites/1_stateful/01_load_v2/01_0001_upload_to_stage.result
feat: Adopt OpenDAL's native scan support
This PR will bump OpenDAL to v0.27 to use the native scan feature.
Changelogs: https://opendal.databend.rs/opendal/docs/changelog/index.html#v0270---2023-02-11
=> feat: Adopt OpenDAL's native scan support

README.md, docs/doc/00-overview/index.md, docs/doc/01-guides/index.md, docs/doc/12-load-data/_category_.json, docs/doc/12-load-data/index.md, docs/doc/12-unload-data/_category_.json, docs/doc/12-unload-data/index.md
* add unloading data from databend
Closes #issue
=> docs(unloading data): add unloading data from databend

Cargo.lock, src/common/arrow/Cargo.toml
Do not initialize zero values when reading buffers, because jemalloc's alloc_zeroed is slower than the std allocator.
Closes #issue
=> feat: bump up strawboat

docs/doc/15-sql-functions/04-array-functions/_category_.json, docs/doc/15-sql-functions/04-array-functions/index.md
=> docs(array): add docs about array function

docs/doc/12-unload-data/index.md
updated the unload chapter.
Closes #issue
=> docs: unload updates

src/common/hashtable/src/hashtable.rs, src/common/hashtable/src/lib.rs, src/common/hashtable/src/lookup_hashtable.rs, src/common/hashtable/src/partitioned_hashtable.rs, src/common/hashtable/src/short_string_hashtable.rs, src/common/hashtable/src/string_hashtable.rs, src/common/hashtable/src/table0.rs, src/common/hashtable/src/table_empty.rs, src/common/hashtable/src/traits.rs, src/query/functions/src/aggregates/aggregate_function.rs, src/query/service/src/pipelines/processors/transforms/aggregator/aggregator_final_parallel.rs
=> chore(query): make hashtable support TrustedLen trait

.github/actions/artifact_failure/action.yml
=> chore(ci): try force kill before upload

Cargo.lock, Cargo.toml, src/query/sharing/Cargo.toml
fix: Reduce the extra stat API in list operations
Changelogs: https://github.com/datafuselabs/opendal/discussions/1337
This PR will fix the performance of list opreations. Dropped from 58.50s to 0.5s.
=> fix: Reduce the extra stat API in list operations

docs/doc/14-sql-commands/90-explain-cmds/explain-analyze.md
* add EXPLAIN ANALYZE doc
Closes #issue
=> docs(EXPLAIN): add EXPLAIN ANALYZE doc

website/docusaurus.config.js, website/src/pages/index.tsx
* Simple the index menu
Closes #issue
=> docs(website): refine the menu

.github/workflows/trusted-benchmark.yml
=> chore(ci): add permission to trusted workflow

.github/workflows/benchmark.yml
=> chore(ci): fix remove redundant arg recursive

website/blog/2023-02-14-pgo.md
For users, they should build to suit their workload. It's worth noting that PGO doesn't always lead to performance optimization.
Closes #9387
=> docs(blog): add profile-guided optimization

docs/doc/90-contributing/08-how-to-write-scalar-functions.md
=> docs(scalar-functions): work with new expression

.github/workflows/release.yml, benchmark/clickbench/index.html, benchmark/clickbench/run.sh
=> chore(ci): select min from more result values

.github/workflows/trusted-benchmark.yml
=> chore(ci): fix download benchmark artifacts

.github/actions/benchmark/action.yml
=> chore(ci): fix checking benchmark source release

.github/actions/benchmark/action.yml, .github/workflows/trusted-benchmark.yml, benchmark/clickbench/index.html
=> chore(ci): add storage type to bench mark system

.github/actions/benchmark/action.yml
=> chore(ci): change benchmark storage to machine instead of system

docs/doc/90-contributing/08-how-to-write-scalar-functions.md, docs/doc/90-contributing/09-how-to-write-aggregate-functions.md
=> docs(agg-functions): work with new expression

docs/doc/90-contributing/08-how-to-write-scalar-functions.md, docs/doc/90-contributing/09-how-to-write-aggregate-functions.md
=> docs(scalar-function): polished with eric's comments

.github/actions/artifact_failure/action.yml
=> chore(ci): ignore file change error on uploading failure artifact

src/query/catalog/src/table.rs, tests/sqllogictests/suites/crdb/delete
=> chore: enable delete tests for crdb suit

src/common/storage/src/column_node.rs, src/query/catalog/src/plan/projection.rs, src/query/storages/fuse/src/io/read/block/block_reader_parquet_deserialize.rs
refactor: refactor is_nested column node
Closes #issue
=> refactor: refactor is_nested column node

.github/actions/test_sqllogic_cluster_linux/action.yml, .github/actions/test_sqllogic_management_mode_linux/action.yml, .github/actions/test_sqllogic_standalone_linux/action.yml, .github/actions/test_sqllogic_standalone_macos/action.yml, .github/workflows/release.yml
=> chore(ci): upload failure for sqllogic test

docs/doc/15-sql-functions/04-array-functions/index.md
Minor fixes and updates to the Array Functions page
Closes #9977
=> docs: array function updates

website/blog/2023-02-15-databend-weekly-81.md
=> docs(weekly): add this week in databend 81

docker/README.md
=> docs(docker): add section how to connect

docs/doc/14-sql-commands/00-ddl/20-table/90-alter-table-column.md
docs: add alter table add\drop column doc
Closes https://github.com/datafuselabs/databend/issues/9992
=> docs: add alter table add\drop column doc

docs/doc/13-sql-reference/10-data-types/43-data-type-decimal-types.md, docs/doc/13-sql-reference/10-data-types/index.md
=> feat(doc): add decimal docs

README.md, docs/doc/01-guides/index.md, website/src/pages/index.tsx
=> docs: refine the docs, analysis -> analytics

docs/doc/10-deploy/01-installing-databend.md, scripts/build/build-website.sh, website/src/pages/download/index.tsx, website/src/pages/download/styles.module.scss
* add install document with deb repo
* add docker image instructions
Closes #issue
=> docs(install): add install document with deb repo

docker/README.md
=> chore(docs): remove clickhouse-cli in docs

docs/doc/00-overview/index.md
- categorized the features into 4 tabs.
- Updated the heading and beginning part. 
Closes #issue
=> docs: databend overview page

.github/actions/test_sqllogic_cluster_linux/action.yml, .github/actions/test_sqllogic_standalone_linux/action.yml, .github/workflows/dev-linux.yml
ci: Fix log missing while timeout happened
=> ci: Fix log missing while timeout happened

src/query/service/src/api/mod.rs, src/query/service/src/api/rpc/exchange/exchange_manager.rs, src/query/service/src/api/rpc/flight_client.rs, src/query/service/src/api/rpc/mod.rs, src/query/service/src/api/rpc/packets/mod.rs, src/query/service/src/api/rpc/packets/packet_fragment.rs, src/query/service/src/schedulers/fragments/query_fragment_actions.rs, src/query/service/src/schedulers/fragments/query_fragment_actions_display.rs
- remove FragmentPayload
- using new future send packet to remote for avoid blocking recv data
Closes #issue
=> refactor(cluster): remove useless code

.github/actions/artifact_failure/action.yml
ci: Create artifacts tar inside target
=> ci: Create artifacts tar inside target

src/query/service/src/api/rpc/flight_actions.rs, src/query/service/src/lib.rs
refactor(cluster): serde packet without utf-8 in cluster
Closes #issue
=> refactor(cluster): serde packet without utf-8 in cluster

.github/actions/artifact_failure/action.yml
ci: Make sure query and meta has been killed before upload
=> ci: Make sure query and meta has been killed before upload

src/query/pipeline/transforms/src/processors/transforms/mod.rs, src/query/service/src/pipelines/processors/transforms/aggregator/aggregator_final_parallel.rs, src/query/service/src/pipelines/processors/transforms/aggregator/aggregator_partial.rs, src/query/service/src/pipelines/processors/transforms/aggregator/aggregator_partitioned.rs, src/query/service/src/pipelines/processors/transforms/group_by/aggregator_polymorphic_keys.rs, src/query/service/src/pipelines/processors/transforms/transform_aggregator.rs
refactor(query): generic for aggregate hash table
Closes #issue
=> refactor(query): generic for aggregate hash table

docs/doc/10-deploy/09-upgrade/10-compatibility.md
=> chore(meta): explain meta - query compatibility

docs/doc/10-deploy/01-installing-databend.md
=> docs(install): fix debian repo format for old version

src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state_impl.rs, tests/sqllogictests/suites/query/join.test
=> fix: join build phase concurrency problem

docs/doc/00-overview/index.md
- Updated the layer explanations in Databend Architecture section on the Welcome page.
- Updated the two EXPLAIN examples with the newest results. 
Closes #issue
=> docs: databend layers

website/blog/2023-02-15-databend-weekly-81.md, website/i18n/en-US/docusaurus-theme-classic/footer.json
=> docs: copyright 2023 and minor update

src/query/service/src/api/rpc/exchange/exchange_manager.rs, src/query/service/src/api/rpc/exchange/exchange_params.rs, src/query/service/src/api/rpc/exchange/exchange_sink.rs, src/query/service/src/api/rpc/exchange/exchange_sorting.rs, src/query/service/src/api/rpc/exchange/exchange_transform_shuffle.rs, src/query/service/src/api/rpc/exchange/mod.rs, src/query/service/src/api/rpc/exchange/serde/exchange_serializer_with_sorting.rs, src/query/service/src/api/rpc/exchange/serde/mod.rs
refactor(query): support exchange sorting
Closes #issue
=> refactor(cluster): support exchange sorting

.github/actions/build_linux/action.yml, .github/workflows/release.yml
=> chore(ci): fix build linux release flags

.github/release-report.jq, .github/workflows/release.yml
=> chore(ci): notify release build result

src/query/service/src/pipelines/executor/executor_graph.rs, src/query/service/src/pipelines/executor/pipeline_executor.rs, src/query/service/src/pipelines/executor/pipeline_pulling_executor.rs
refactor(executor): add check processor graph completed
Closes #issue
=> refactor(executor): add check processor graph completed

src/common/base/src/base/singleton_instance.rs
chore: Add more detailed panic info about Singleton dropping
=> chore: Add more detailed panic information about singleton drops

src/query/service/tests/it/storages/fuse/operations/mutation/segments_compact_mutator.rs, src/query/service/tests/it/storages/fuse/statistics.rs, src/query/storages/fuse/src/io/read/bloom/block_filter_reader.rs, src/query/storages/fuse/src/io/read/meta/meta_readers.rs, src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs, src/query/storages/fuse/src/statistics/accumulator.rs
=> chore(storage): remove unused codes and format some codes

.github/workflows/release.yml
=> chore(ci): fix missing checkout for release notify

src/query/expression/src/deserializations/decimal.rs, src/query/expression/src/deserializations/mod.rs, src/query/expression/src/schema.rs, src/query/expression/src/types.rs, src/query/expression/src/types/decimal.rs, src/query/expression/src/utils/display.rs, src/query/expression/tests/it/decimal.rs, src/query/expression/tests/it/main.rs, src/query/formats/src/field_decoder/fast_values.rs, src/query/formats/src/field_decoder/json_ast.rs, src/query/formats/src/field_decoder/row_based.rs, src/query/formats/src/lib.rs, tests/sqllogictests/suites/base/11_data_type/11_0006_data_type_decimal
the first step of  `Decimal literal/encoding` in https://github.com/datafuselabs/databend/issues/2931
also fix the decimal display (tested in insert tests)
Closes #issue
=> feat: support insert decimal.

.github/workflows/backport.yml, .github/workflows/build-tool.yml, .github/workflows/dev-linux.yml, .github/workflows/dev-macos.yml, .github/workflows/production.yml, .typos.toml, scripts/setup/dev_setup.sh, scripts/setup/rust-tools.txt
ci: Install typos for databend CI
=> ci: Install typos for databend CI

src/query/pipeline/transforms/Cargo.toml
=> ci: Fix cargo machete config

.github/actions/check/action.yml, .github/actions/setup_build_tool/action.yml, Makefile, docs/doc/16-table-engines/00-fuse.md, docs/doc/90-contributing/01-rfcs/20230213-query-result-cache.md, src/query/config/src/config.rs, src/query/functions/src/scalars/mod.rs, src/query/storages/fuse/src/fuse_table.rs, src/query/storages/fuse/src/io/files.rs, src/query/storages/fuse/src/operations/read/fuse_source.rs, src/query/storages/fuse/src/operations/read_data.rs, src/query/storages/fuse/src/operations/read_partitions.rs, src/query/storages/iceberg/src/lib.rs, src/query/storages/iceberg/src/table.rs, src/query/storages/result_cache/src/write/sink.rs
=> ci: Add typos check in CI

docs/doc/15-sql-functions/112-table-functions/stage_table_funtion.md
=> docs(query stage): add more example

docs/doc/14-sql-commands/00-ddl/40-stage/01-ddl-create-stage.md, docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
=> docs(copy uri): add tab for URL/URI of COPY

docs/doc/13-sql-reference/10-data-types/00-data-type-logical-types.md, docs/doc/13-sql-reference/10-data-types/10-data-type-numeric-types.md, website/docusaurus.config.js
=> docs: remove i18n support

.github/release.yml
=> chore(release): show chore label to release note

src/query/storages/fuse/src/fuse_table.rs, src/query/storages/fuse/src/operations/append.rs, src/query/storages/fuse/src/operations/delete.rs, src/query/storages/fuse/src/operations/recluster.rs
=> chore(fuse): add get_max_page_size function to FuseTable

docs/doc/02-cloud/index.md
=> docs: fix link and improve some chapter

src/query/expression/src/block.rs, src/query/pipeline/core/tests/it/pipelines/processors/port_test.rs, src/query/pipeline/transforms/src/processors/transforms/transform.rs, src/query/pipeline/transforms/src/processors/transforms/transform_accumulating.rs, src/query/service/src/api/rpc/exchange/exchange_sink.rs, src/query/service/src/api/rpc/exchange/exchange_sink_writer.rs, src/query/service/src/api/rpc/exchange/exchange_transform_shuffle.rs, src/query/service/src/api/rpc/exchange/serde/exchange_deserializer.rs, src/query/service/src/api/rpc/exchange/serde/exchange_serializer.rs, src/query/service/src/pipelines/processors/transforms/aggregator/aggregate_exchange_sorting.rs, src/query/service/src/pipelines/processors/transforms/aggregator/aggregate_hashstate_info.rs, src/query/service/src/pipelines/processors/transforms/aggregator/aggregate_info.rs, src/query/service/src/pipelines/processors/transforms/aggregator/aggregator_final_parallel.rs, src/query/service/src/pipelines/processors/transforms/transform_convert_grouping.rs, src/query/storages/fuse/src/operations/mutation/compact/compact_meta.rs, src/query/storages/fuse/src/operations/mutation/mutation_meta.rs, src/query/storages/fuse/src/operations/operation_log.rs, src/query/storages/fuse/src/operations/read/native_data_source.rs, src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs, src/query/storages/fuse/src/operations/read/parquet_data_source.rs, src/query/storages/fuse/src/operations/read/parquet_data_source_deserializer.rs, src/query/storages/parquet/src/deserialize_transform.rs, src/query/storages/parquet/src/parquet_source.rs
refactor(query): refactor block meta and add block meta transform
Closes #issue
=> refactor(query): refactor block meta and add block meta transform

scripts/ci/deploy/config/databend-query-node-1.toml, scripts/ci/deploy/config/databend-query-node-2.toml, scripts/ci/deploy/config/databend-query-node-3.toml
chore(query): enable info level log for ci
Closes #issue
=> chore(query): enable info level log for ci

docs/doc/10-deploy/06-metasrv/15-metasrv-config.md
=> docs:Update 15-metasrv-config.md

docs/doc/03-develop/00-golang.md, docs/doc/03-develop/01-python.md, docs/doc/03-develop/03-java.md
Considering that we now have our own driver, I replaced the outdated content.
- databend-go
- databend-py databend-sqlalchemy
- databend-java
Closes #issue
=> docs(develop): work with Databend driver

website/blog/2023-02-24-Deploy-databend-on-minio.md
fix typos in blog 
Closes #issue
=> docs: fix typos

website/src/css/custom.scss, website/src/pages/index.module.scss, website/src/pages/index.tsx
=> feat(website): update website index styles #10175

docs/doc/13-sql-reference/10-data-types/index.md
=> docs: remove array and tuple from variant

src/query/sql/src/planner/optimizer/distributed/distributed.rs, src/query/sql/src/planner/optimizer/s_expr.rs
=> chore: reduce clone cost for `SExpr`

docker/it-hive/hadoop-hive.env
this PR will offer a valid hadoop-hive.env file
This PR removes invalid environment option in CI.
=> ci: fix hadoop-hive.env

tests/sqllogictests/src/error.rs
=> chore: improve `DSqlLogicTestError` code

docs/doc/13-sql-reference/10-data-types/index.md
=> docs: Update decimal description

docs/doc/03-develop/00-golang.md
- Made it into a tutorial.
- Added repo information.
- Language refactor.
Closes #issue
=> docs: update Golang development guide

docs/doc/90-contributing/01-rfcs/20230213-query-result-cache.md
Add references into the RFC of query result cache.
=> fix(rfc): add references.

docs/doc/03-develop/00-golang.md, docs/doc/03-develop/01-python.md, docs/doc/03-develop/02-nodejs.md, docs/doc/03-develop/03-java.md
- Fixed comments from @PsiACE 
- Refactor remaining developer guides: Python, Java, and Node.js
Closes #issue
=> docs: update developer guides

README.md, docs/doc/00-overview/index.md, docs/doc/01-guides/index.md, docs/doc/11-integrations/00-api/02-clickhouse-handler.md, docs/doc/13-sql-reference/10-data-types/11-data-type-decimal-types.md, docs/doc/90-contributing/01-rfcs/20230213-query-result-cache.md, tests/sqllogictests/src/client/clickhouse_client.rs
ClickHouse does not support clickhouse client, it's just HTTP handler.
Closes #issue
=> chore(docs): update docs

docs/doc/13-sql-reference/40-sql-identifiers.md
=> docs(IDENTIFIERS): add more example for the SQL IDENTIFIERS

src/query/functions/src/scalars/datetime.rs, src/query/functions/src/scalars/mod.rs, src/query/functions/tests/it/scalars/testdata/function_list.txt, tests/sqllogictests/suites/base/11_data_type/11_0001_data_type_date_time
=> chore(query): add register_additional_cast_rules for timestamp/date

src/query/service/tests/it/storages/testdata/columns_table.txt, src/query/storages/information-schema/src/schemata_table.rs
=> chore(tool): support navicat for mysql 16 connect to databend

scripts/benchmark/query/load/tpch.sh, src/query/sql/src/planner/optimizer/rule/rewrite/rule_eliminate_eval_scalar.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_eliminate_filter.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_fold_count_aggregate.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_merge_eval_scalar.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_merge_filter.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_normalize_disjunctive_filter.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_normalize_scalar.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_eval_scalar.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_scan.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_union.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_limit_aggregate.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_limit_expression.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_limit_join.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_limit_scan.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_limit_sort.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_limit_union.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_sort_scan.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_split_aggregate.rs, src/query/sql/src/planner/optimizer/rule/rule.rs
=> chore(query): fix merge Rule, add default transformation to be true

src/query/sql/src/planner/optimizer/cascades/cascade.rs, src/query/sql/src/planner/optimizer/cascades/explore_rules.rs
Follow up https://github.com/datafuselabs/databend/pull/10024#discussion_r1118378902
Closes #issue
=> chore: delete useless code

docs/doc/10-deploy/01-installing-databend.md
- Renamed the title from **Install Databend** to **Download Databend**: The old name was too big for the content it included. 
- Reorganized the content. 
Closes #issue
=> docs: refactor download instructions

docs/doc/00-overview/index.md
=> docs: fix typo

website/blog/2023-02-24-Deploy-databend-on-minio.md
=> docs: Update 2023-02-24-Deploy-databend-on-minio.md

.github/workflows/trusted-benchmark.yml
=> chore(ci): fix update results for release benchmark

docs/doc/10-deploy/01-installing-databend.md, src/query/sql/src/planner/binder/bind_context.rs
=> chore(query): add more error messages of binder

website/package.json, website/src/components/CustomBlog/BlogList.js, website/src/components/CustomBlog/BlogPostDetails.js, website/src/components/CustomBlog/PopularTags.js, website/src/components/CustomBlog/Tagtest.js, website/src/components/CustomBlog/styles.module.scss
Some styling tweaks for Blog
Closes #issue
=> chore(website): Some styling tweaks for Blog

src/query/sql/src/planner/optimizer/heuristic/heuristic.rs, src/query/sql/src/planner/plans/operator.rs
=> chore(planer): correct transrormation to transformation

website/blog/2023-02-24-Deploy-databend-on-minio.md, website/src/components/CustomBlog/BlogPostDetails.js, website/src/components/CustomBlog/styles.module.scss, website/src/components/Icons/Label.js, website/src/components/Icons/Pencil.js, website/src/components/Icons/index.js, website/src/pages/index.module.scss
=> docs: Some styling tweaks for Blog 

website/docusaurus.config.js
=> docs: move blog ahead download

website/blog/2023-03-02-bendsql.md
=> fix(doc): typo.

.github/actions/check/action.yml, .github/workflows/typos.yml, website/package.json
=> ci: Add seperated typos check

docs/doc/10-deploy/02-deploying-databend.md, docs/doc/10-deploy/05-deploying-local.md
added linux commands as a tip to fix errors on starting Databend, as discussed in #10292 .
=> docs: tips for install errors

.github/workflows/trusted-benchmark.yml
=> chore(ci): fix download release benchmark report

website/src/components/CustomBlog/Connectwithus.js, website/src/components/CustomBlog/styles.module.scss
=> docs: Fixed some styling issues the Blog contacted us with

src/query/functions/src/scalars/geo.rs
=> fix: function point_in_polygon require float64.

Cargo.lock, src/query/expression/Cargo.toml, src/query/expression/src/property.rs, src/query/expression/src/types/decimal.rs
=> fix(expression): fix MAX/MIN of Decimal.

website/src/components/CustomBlog/Connectwithus.js
=> docs: refine the blog Connect With Us

src/binaries/Cargo.toml, src/binaries/query/main.rs
refactor(query): not supported embedded meta deployment
Closes #issue
=> refactor(query): not supported embedded meta deployment

website/src/pages/index.module.scss, website/src/theme/Footer/index.module.scss
Fix the adaptation problem of <Footer/> on the mobile side
Closes #issue
=> docs: Fix the adaptation problem of <Footer/> on the mobile side

docs/doc/15-sql-functions/04-array-functions/index.md, src/query/expression/src/values.rs, src/query/service/src/table_functions/mod.rs, src/query/service/src/table_functions/table_function_factory.rs, src/query/service/src/table_functions/unnest.rs, src/query/sql/src/evaluator/block_operator.rs, src/query/sql/src/planner/binder/scalar.rs, src/query/sql/src/planner/binder/table_args.rs, tests/sqllogictests/suites/query/02_function/02_0062_function_unnest
Unnest can also be a table function.
Tracking #10295
=> feat(query): table function unnest.

docs/doc/80-releases/96-v1.0.0.md
=> docs: add v1.0.0 change release

Cargo.lock, src/meta/store/Cargo.toml, src/meta/store/src/lib.rs
refactor(meta): pub watch api for metastore
Closes #issue
=> refactor(meta): pub watch api for metastore

src/query/expression/src/schema.rs, src/query/expression/src/values.rs, src/query/service/src/interpreters/interpreter_table_create.rs, tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables, tests/sqllogictests/suites/base/09_fuse_engine/09_0021_read_tuple_array
- Support creating nested data types with nullable
- Merge `Struct` validity with inner fields  validity and set inner fields as nullable
Closes #10344
=> fix(query): Support creating nested data types with nullable

docs/doc/10-deploy/04-deploying-databend-on-kubernetes.md, website/yarn.lock
=> docs(deploy): fix meta bootstrap note for k8s deploy

website/blog/2022-11-30-databend-weekly-70.md, website/blog/2022-12-07-databend-weekly-71.md, website/blog/2022-12-14-databend-weekly-72.md, website/blog/2022-12-21-databend-weekly-73.md, website/blog/2022-12-28-databend-weekly-74.md, website/blog/2023-01-04-databend-weekly-75.md, website/blog/2023-01-11-databend-weekly-76.md, website/blog/2023-01-18-databend-weekly-77.md, website/blog/2023-01-25-databend-weekly-78.md, website/blog/2023-02-01-databend-weekly-79.md, website/blog/2023-02-08-databend-weekly-80.md, website/blog/2023-02-15-databend-weekly-81.md, website/blog/2023-02-22-databend-weekly-82.md, website/blog/2023-02-24-Deploy-databend-on-minio.md, website/blog/2023-03-03-databend-weekly-83.md
=> docs(blog): remove connect with us

src/query/ast/src/ast/statements/replace.rs, src/query/ast/src/parser/statement.rs, src/query/catalog/src/table.rs, src/query/service/src/interpreters/interpreter_replace.rs, src/query/sql/src/planner/binder/replace.rs, src/query/sql/src/planner/plans/replace.rs, src/query/storages/fuse/src/fuse_table.rs, src/query/storages/fuse/src/operations/merge_into/mod.rs, src/query/storages/fuse/src/operations/merge_into/mutation_meta/merge_into_operation_meta.rs, src/query/storages/fuse/src/operations/merge_into/mutator/merge_into_mutator.rs, src/query/storages/fuse/src/operations/merge_into/processors/mod.rs, src/query/storages/fuse/src/operations/replace.rs, src/query/storages/fuse/src/operations/replace_into/mutator_replace_into.rs, src/query/storages/fuse/src/operations/replace_into/processor_replace_into.rs, tests/sqllogictests/suites/base/09_fuse_engine/09_0023_replace_into
=> feat: replace into on multiple columns

docs/doc/14-sql-commands/10-dml/dml-replace.md
=> docs(replace): add replace

scripts/ci/deploy/config/databend-query-node-1.toml, scripts/ci/deploy/config/databend-query-node-2.toml, scripts/ci/deploy/config/databend-query-node-3.toml, scripts/ci/deploy/config/databend-query-node-shared.toml
correct disk cache path in CI config files
Closes #issue
=> fix: correct disk cache path in CI config files

README.md, docs/doc/00-overview/index.md, docs/doc/01-guides/index.md
=> docs: add managing data part

docs/doc/90-contributing/01-rfcs/20230307-stage-with-schema.md
=> rfc: add 20230307-stage-with-schema.md

src/query/catalog/src/table_context.rs, src/query/service/src/interpreters/interpreter_select.rs, src/query/service/src/sessions/query_ctx.rs, src/query/service/src/sessions/query_ctx_shared.rs, src/query/service/tests/it/storages/fuse/operations/commit.rs, src/query/sql/src/planner/binder/table.rs, src/query/sql/src/planner/semantic/type_check.rs
Do not cache non-deterministic queries.
=> chore: do not cache non-deterministic queries.

src/common/base/src/lib.rs, src/common/base/src/runtime/mod.rs, src/common/base/src/runtime/runtime.rs, src/query/service/src/api/rpc/exchange/exchange_manager.rs, src/query/service/src/api/rpc/flight_client.rs, src/query/service/src/api/rpc/flight_service.rs, src/query/service/src/pipelines/executor/executor_condvar.rs, src/query/service/src/pipelines/executor/executor_tasks.rs, src/query/service/src/pipelines/executor/pipeline_executor.rs, src/query/service/src/pipelines/executor/processor_async_task.rs
fix(cluster): use ctx runtime spawn flight action
Closes #issue
=> fix(cluster): use ctx runtime spawn flight action

docs/doc/90-contributing/01-rfcs/20230308-transform-during-load.md
it is already under development, it seems to me that an RFC is needed to clarify some details. 
Closes #issue
=> docs(stage): RFC:  Transform During Load.

src/query/expression/src/expression.rs, tests/sqllogictests/suites/mode/cluster/04_0002_explain_v2.test, tests/sqllogictests/suites/mode/cluster/exchange.test, tests/sqllogictests/suites/mode/standalone/explain/aggregate.test, tests/sqllogictests/suites/mode/standalone/explain/join.test, tests/sqllogictests/suites/mode/standalone/explain/prune_column.test, tests/sqllogictests/suites/mode/standalone/explain/select.test
=> chore(expr): pretty print more expressions in explain

src/meta/raft-store/src/key_spaces.rs, src/meta/raft-store/src/state/raft_state.rs, src/meta/raft-store/tests/it/state.rs, src/meta/service/src/store/store_bare.rs, src/meta/service/tests/it/meta_node/meta_node_lifecycle.rs
=> chore: rename hard-state to vote

website/src/css/custom.scss
Adjust the 'code' style overflow under <TabItem/>
Closes #issue
=> docs: Adjust the 'code' style overflow under <TabItem/>

Cargo.toml, src/common/storage/Cargo.toml, src/query/service/Cargo.toml, src/query/sql/Cargo.toml, src/query/storages/stage/Cargo.toml
fix(query): unify features for opendal
Closes #issue
=> fix(query): unify features for opendal

src/query/service/src/interpreters/interpreter_table_show_create.rs, tests/sqllogictests/suites/base/06_show/06_0001_show_create_table
show create view will return the `create view xx as QUERY`
Closes #10445
=> fix(query): fix show create view result

src/query/service/src/pipelines/executor/executor_condvar.rs, src/query/service/src/pipelines/executor/executor_tasks.rs
fix(executor): fix wrong memory order
Closes #issue
=> fix(executor): fix wrong memory order

benchmark/clickbench/tpch/create.sql, benchmark/clickbench/tpch/create_local.sql, src/common/building/src/lib.rs, src/common/tracing/src/macros.rs, src/meta/client/src/lib.rs, src/meta/service/src/version.rs, src/meta/types/src/config.rs, src/query/config/src/version.rs
=> ci(bench): fix cluster key for tpch bench

src/query/service/src/interpreters/interpreter_view_alter.rs, src/query/service/src/interpreters/interpreter_view_create.rs, src/query/service/src/interpreters/interpreter_view_drop.rs, src/query/sql/src/planner/binder/binder.rs, src/query/sql/src/planner/binder/copy.rs, src/query/sql/src/planner/binder/ddl/table.rs, src/query/sql/src/planner/binder/ddl/view.rs, src/query/sql/src/planner/binder/delete.rs, src/query/sql/src/planner/binder/insert.rs, src/query/sql/src/planner/binder/table.rs, src/query/sql/src/planner/plans/ddl/view.rs
=> refactor(binder): extract util fn normalize_object_identifier_triple.

src/query/expression/src/type_check.rs, src/query/expression/src/types.rs, src/query/functions/src/scalars/array.rs, src/query/functions/src/scalars/tuple.rs, src/query/functions/tests/it/scalars/array.rs, src/query/functions/tests/it/scalars/testdata/array.txt, src/query/functions/tests/it/scalars/testdata/function_list.txt, src/query/functions/tests/it/scalars/testdata/tuple.txt, src/query/functions/tests/it/scalars/tuple.rs
Closes https://github.com/datafuselabs/databend/issues/10468
=> fix(expr): get(tuple) may return nested Nullable

scripts/setup/rust-toolchain.toml
ci: Bump toolchain to start rockets
=> ci: Bump toolchain to start rockets

website/blog/2023-03-10-databend-weekly-84.md
Writing weekly still takes some effort, but at least we have more content to show. 
The new style of weekly is still evolving, and we welcome your comments to help us improve in the future.
- SQL: `REPLACE INTO`
- RFC: Transform During Load, cc @youngsofun  for kindly review
- Rust Toolchain: 🦀 v1.70.0-nightly (03-10)
- Announcing OpenDAL v0.30, cc @Xuanwo  for kindly review
- Support More Mathematical Operators like PostgreSQL
Closes #issue
=> docs(weekly): add this week in databend 84

Cargo.lock, src/query/service/src/interpreters/interpreter_copy.rs, src/query/service/src/interpreters/interpreter_user_stage_remove.rs
* Improve the `remove @stage` with batch
* Improve the `COPY ...  PURGE=true` , move the deletion of the files to the end of the `COPY`
Closes #issue
=> chore: remove stage files to batch

src/query/pipeline/sources/src/input_formats/impls/input_format_parquet.rs, src/query/pipeline/sources/src/input_formats/input_format.rs, src/query/pipeline/sources/src/input_formats/input_format_text.rs, src/query/service/src/interpreters/interpreter_copy.rs, src/query/storages/stage/src/stage_table.rs, src/query/storages/stage/src/stage_table_sink.rs
* avoid unnecessary `op.stat` call
Closes #issue
=> chore(get_splits): change get_splits from Vec<String> to Vec<StageFileInfo>

src/meta/api/src/schema_api_impl.rs
refactor: use mget_pb_values instead of get_pb_values in upsert_table_copied_file_info impl to do batch refine
Closes #issue
=> refactor: use mget_pb_values instead of get_pb_values in upsert_table_copied_file_info impl to do batch refine

.github/workflows/release.yml, .github/workflows/trusted-benchmark.yml
=> chore(ci): checkout before download artifacts

.github/actions/benchmark_local/action.yml, .github/workflows/benchmark.yml, .github/workflows/release.yml, .github/workflows/trusted-benchmark.yml, benchmark/clickbench/benchmark_cloud.sh
=> chore(ci): fix download artifacts for benchmark

src/query/service/tests/it/servers/http/http_query_handlers.rs, src/query/service/tests/it/storages/testdata/columns_table.txt, src/query/storages/system/src/tables_table.rs
=> feat(query): system.tables add engine_full column

src/query/service/src/interpreters/interpreter_copy.rs
=> chore(copy): refine the copy status info

.github/actions/benchmark_cloud/action.yml, .github/actions/publish_binary/action.yml, .github/actions/publish_deb/action.yml, .github/actions/setup_docker/action.yml, .github/workflows/dev-macos.yml, .github/workflows/production.yml, .github/workflows/release.yml, .github/workflows/trusted-benchmark.yml
=> chore(ci): upgrade aws-actions/configure-aws-credentials to v2

docs/doc/90-contributing/02-building-from-source.md
refactor the doc 
Closes https://github.com/datafuselabs/databend/issues/10522
=> docs: build source code

src/query/sql/src/planner/binder/bind_context.rs, src/query/sql/src/planner/binder/select.rs, src/query/sql/src/planner/binder/table.rs, tests/sqllogictests/suites/query/cte.test
Closes https://github.com/datafuselabs/databend/issues/10429
=> fix: ambiguous column reference with reused CTE

Cargo.lock, src/query/ast/benches/bench.rs, src/query/ast/src/parser/parser.rs, src/query/ast/tests/it/parser.rs, src/query/functions/tests/it/scalars/parser.rs, src/query/service/src/interpreters/interpreter_insert.rs, src/query/service/src/pipelines/processors/transforms/transform_resort_addon.rs, src/query/service/tests/it/sql/planner/semantic/name_resolution.rs, src/query/service/tests/it/storages/fuse/pruning.rs, src/query/sql/src/planner/binder/binder.rs, src/query/sql/src/planner/binder/copy.rs, src/query/sql/src/planner/binder/ddl/table.rs, src/query/sql/src/planner/binder/table.rs, src/query/sql/src/planner/expression_parser.rs, src/query/sql/src/planner/planner.rs, src/query/sql/src/planner/semantic/aggregate_rewriter.rs, src/query/sql/src/planner/semantic/type_check.rs, src/query/storages/fuse/src/fuse_table.rs, src/query/storages/fuse/src/table_functions/clustering_information/table_args.rs, src/query/storages/fuse/src/table_functions/mod.rs
=> chore(ast): make backtrace private

src/query/functions/src/aggregates/aggregate_quantile_cont.rs, src/query/functions/src/aggregates/aggregator_common.rs, tests/sqllogictests/suites/query/02_function/02_0000_function_aggregate_mix
fix comparison of quantile level
Closes #issue
=> fix: fix comparison of quantile level

docs/doc/14-sql-commands/00-ddl/40-stage/01-ddl-create-stage.md
added a note about the ENDPOINT_URL parameter.
Closes #issue
=> docs: create stagee

.github/actions/create_check_status/action.yml, .github/workflows/benchmark.yml, .github/workflows/release.yml, .github/workflows/trusted-benchmark.yml
=> chore(ci): fix benchmark job step id

.github/actions/benchmark_cloud/action.yml, .github/actions/benchmark_local/action.yml, .github/workflows/trusted-benchmark.yml
=> chore(ci): add benchmark result for large

docs/doc/12-load-data/00-stage.md, docs/doc/12-load-data/01-s3.md, docs/doc/12-load-data/02-local.md, docs/doc/12-load-data/04-http.md, docs/doc/12-load-data/05-data-load-transform.md
Add docs for #10561 
Closes #issue
=> docs(transforming): add data load transform

.github/actions/benchmark_cloud/action.yml, .github/actions/benchmark_local/action.yml, .github/actions/create_check_status/action.yml
=> chore(ci): fix typo in comment pr for benchmark

src/query/sql/src/executor/format.rs
=> chore: fix compile error.

.github/actions/create_check_status/action.yml, .github/workflows/trusted-benchmark.yml, benchmark/clickbench/benchmark_cloud.sh
=> chore(ci): fix benchmark checks

website/src/css/custom.scss
Adjust the unordered list style
Closes #issue
=> docs: Adjust the unordered list style

src/query/expression/src/kernels/group_by_hash.rs, src/query/service/src/pipelines/processors/transforms/group_by/aggregator_groups_builder.rs, tests/sqllogictests/suites/base/03_common/03_0003_select_group_by
=> feat(query): support group by variant

docs/doc/13-sql-reference/30-table-engines/02-random.md
=> chore(docs): add random engine doc

docs/doc/16-security/00-access-control/10-access-control-privileges.rs, docs/doc/16-security/00-access-control/_category_.json, docs/doc/16-security/_category_.json
add doc about access control privileges
Closes #issue
=> docs(query): add doc about access control privileges

.github/actions/benchmark_cloud/action.yml, .github/actions/benchmark_local/action.yml, .github/workflows/trusted-benchmark.yml
Allow failure for cloud bench.
Closes #issue
=> chore(ci): fix benchmark result artifacts

scripts/benchmark/query/load/tpch100.sh, src/query/ast/src/ast/expr.rs, src/query/sql/src/lib.rs, src/query/sql/src/planner/binder/aggregate.rs, src/query/sql/src/planner/binder/bind_context.rs, src/query/sql/src/planner/binder/mod.rs, src/query/sql/src/planner/binder/scalar_common.rs, src/query/sql/src/planner/binder/scalar_visitor.rs, src/query/sql/src/planner/binder/select.rs, src/query/sql/src/planner/binder/sort.rs, src/query/sql/src/planner/binder/table.rs, src/query/sql/src/planner/binder/window.rs, src/query/sql/src/planner/format/display_rel_operator.rs, src/query/sql/src/planner/optimizer/format.rs, src/query/sql/src/planner/optimizer/heuristic/subquery_rewriter.rs, src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/derive_filter.rs, src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/outer_join_to_inner_join.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_union.rs, src/query/sql/src/planner/optimizer/s_expr.rs, src/query/sql/src/planner/plans/mod.rs, src/query/sql/src/planner/plans/operator.rs, src/query/sql/src/planner/plans/scalar_expr.rs, src/query/sql/src/planner/plans/window.rs, src/query/sql/src/planner/semantic/grouping_check.rs, src/query/sql/src/planner/semantic/lowering.rs, src/query/sql/src/planner/semantic/type_check.rs
initial impl of window function plan.
Closes #issue
=> feat(planner): plan window function

src/meta/api/src/schema_api_impl.rs
refactor: batch meta request using mget_pb_values
Closes #issue
=> refactor: batch meta request using mget_pb_values

docs/doc/14-sql-commands/20-query-syntax/01-dml-select.md, docs/doc/14-sql-commands/20-query-syntax/_category_.json, docs/doc/14-sql-commands/20-query-syntax/index.md
=> docs(query): add query syntax index

.github/actions/artifact_download/action.yml, .github/workflows/backport.yml, .github/workflows/release.yml, src/query/service/src/interpreters/interpreter_query_log.rs
=> chore(query): do not write duplicate query log

docs/doc/14-sql-commands/20-query-syntax/02-dml-with.md
=> docs(query): refine the with syntax

Cargo.lock, src/query/ast/tests/it/testdata/statement.txt, src/query/service/tests/it/storages/testdata/columns_table.txt, src/query/storages/system/Cargo.toml, src/query/storages/system/src/columns_table.rs, tests/sqllogictests/suites/base/01_system/01_0006_system_columns
system.columns filter view engine fields
Closes #10632
=> feat(query): system.columns filter view engine fields

src/query/sql/src/planner/binder/scalar.rs, src/query/sql/src/planner/binder/setting.rs, src/query/sql/src/planner/binder/table.rs, src/query/sql/src/planner/expression_parser.rs, src/query/sql/src/planner/semantic/type_check.rs
=> refactor(planner): remove required_type in TypeChecker

docs/doc/14-sql-commands/20-query-syntax/01-dml-select.md, docs/doc/14-sql-commands/20-query-syntax/21-grouping-sets.md, docs/doc/15-sql-functions/120-other-functions/grouping.md
=> docs: add docs for grouping sets.

website/blog/2023-03-17-databend-weekly-85.md, website/src/components/BaseComponents/AvatarGroup/index.js
=> docs(weekly): add this week in databend 85

src/query/service/src/table_functions/openai/gpt_to_sql.rs, src/query/service/src/table_functions/openai/mod.rs, src/query/service/src/table_functions/openai/openai.rs
=> chore(openai): add openai.rs to prepare more AI functions

website/src/components/GetLatest/index.js, website/src/hooks/useGetReleases.ts, website/src/pages/download/index.tsx, website/src/pages/download/styles.module.scss, website/src/plugins/fetch-databend-releases.js
x86_64-unknown-linux-musl => x86_64-unknown-linux-gnu
Closes #issue
=> fix(replaced): x86_64-unknown-linux-musl => x86_64-unknown-linux-gnu

website/src/pages/download/index.tsx
remove "LTS" and release tag
Closes #issue
=> fix(text): remove "LTS" and release tag

src/query/sql/src/planner/binder/aggregate.rs, tests/sqllogictests/suites/duckdb/sql/aggregate/group/group_by_grouping_sets.test
Support grouping sets with posititions.
Closes #10651
=> fix: support positions in grouping sets.

docs/doc/10-deploy/01-installing-databend.md
=> docs: note to linux packages

src/query/functions/src/aggregates/adaptors/aggregate_ornull_adaptor.rs, tests/sqllogictests/suites/base/03_common/03_0008_select_aggregator_combinator
fix multiple `SUM_IF` functions return incorrect results
Closes #10639
=> fix(functions): fix multiple SUM_IF functions return incorrect results

src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_state_impl.rs
fix(query): fix missing notify for TransformHashJoinProbe
Closes #issue
=> fix(query): fix missing notify for TransformHashJoinProbe

src/query/service/src/api/rpc/exchange/exchange_manager.rs, src/query/service/src/api/rpc/exchange/statistics_receiver.rs, src/query/service/src/api/rpc/exchange/statistics_sender.rs, src/query/service/src/api/rpc/flight_client.rs, src/query/service/src/api/rpc/flight_service.rs
refactor(cluster): rename new_flight to flight
Closes #issue
=> refactor(cluster): rename new_flight to flight

tests/sqllogictests/suites/base/05_ddl/05_0006_ddl_grant_privilege
add more test for grant privileges
Closes #issue
=> ci(query): add more test for grant privileges

docs/doc/15-sql-functions/61-ai-functions/01-ai-to-sql.md
added openai-api-key to ai2sql function
Closes #issue
=> docs: openai-api-key

src/query/service/src/api/rpc/exchange/exchange_source_reader.rs, src/query/service/src/api/rpc/flight_client.rs, src/query/service/src/api/rpc/flight_service.rs, src/query/service/src/sessions/query_ctx.rs
chore(cluster): close flight receiver in event
Closes #issue
=> chore(cluster): close flight receiver in event

src/query/service/src/pipelines/pipeline_builder.rs, src/query/service/src/pipelines/processors/transforms/transform_left_join.rs
=> chore: add some annotations for bugfix

.github/workflows/release.yml
=> chore(ci): run release in self-hosted runner

src/query/pipeline/core/src/processors/duplicate_processor.rs, src/query/pipeline/core/tests/it/pipelines/processors/duplicate.rs
=> fix: fix duplicate processor.

.github/workflows/release.yml
=> chore(ci): build release on larger runner

scripts/ci/ci-run-sqllogic-tests-cluster.sh, scripts/ci/ci-run-sqllogic-tests.sh, scripts/ci/ci-run-stateful-hive-tests-standalone.sh, scripts/ci/ci-run-stateful-tests-cluster-minio.sh, scripts/ci/ci-run-stateful-tests-standalone-minio.sh, scripts/ci/ci-run-stateless-tests-cluster.sh, scripts/ci/ci-run-stateless-tests-standalone.sh
chore(test): revert repeat 3 time for each pr
Closes #issue
=> chore(test): revert repeat 3 time for each pr

.github/actions/test_sqllogic_standalone_linux/action.yml, .github/workflows/release.yml, .github/workflows/trusted-benchmark.yml
=> chore(ci): download binaries before setup docker

.github/actions/test_sqllogic_standalone_linux/action.yml, tests/sqllogictests/src/util.rs
=> ci: fix allow run_dir and skipped_dir work together for sqllogictest

.github/actions/test_unit/action.yml, .github/workflows/dev-linux.yml, .github/workflows/production.yml, .github/workflows/release.yml, .github/workflows/trusted-benchmark.yml
=> ci: fix benchmark check run_id on pr & cleanup

website/blog/2023-03-24-databend-weekly-86.md
=> docs(weekly): add this week in databend 86

.github/mergify.yml, .github/workflows/dev-linux.yml, .github/workflows/release.yml, tests/databend-test
=> ci: fix typo in release workflow

docs/doc/14-sql-commands/00-ddl/20-table/50-describe-table.md, docs/doc/14-sql-commands/40-show/show-full-columns.md
=> docs: SHOW COLUMNS

tests/sqllogictests/README.md
Embedded meta is an deployment method and will not be supported since March 2023
Closes #issue
=> docs: update sqllogictest readme

src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_scan.rs, tests/sqllogictests/suites/base/06_show/06_0015_show_columns, tests/sqllogictests/suites/mode/standalone/explain/explain.test, tests/sqllogictests/suites/mode/standalone/explain/union.test
fix view select filter using source table column
Part of #9882
=> fix(query): fix view select filter using source table column

src/query/service/src/servers/flight_sql/flight_sql_service/service.rs, src/query/service/tests/it/servers/flight_sql/flight_sql_handler.rs
=> ci(FlightSQL): fix panic when dropping singleton.

Cargo.lock, src/query/formats/tests/it/main.rs, src/query/formats/tests/it/output_format_tcsv.rs, src/query/service/src/api/rpc/flight_service.rs, src/query/service/src/api/rpc/packets/packet_executor.rs, src/query/service/src/schedulers/fragments/query_fragment_actions.rs, src/query/service/src/sessions/session_mgr.rs, src/query/service/tests/it/sessions/session_context.rs, src/query/settings/Cargo.toml, src/query/settings/src/settings.rs, src/query/sql/src/planner/expression_parser.rs, tests/sqllogictests/suites/base/03_common/03_0037_spill_aggregator
feat(cluster): support cluster session settings
Closes #issue
=> feat(cluster): support cluster session settings

Cargo.lock, src/common/openai/Cargo.toml, src/common/openai/src/embedding.rs, src/common/openai/src/lib.rs, src/common/openai/src/openai.rs, src/query/functions/Cargo.toml, src/query/functions/src/scalars/vector.rs, src/query/functions/tests/it/scalars/testdata/function_list.txt, src/query/sql/src/planner/semantic/type_check.rs
* `select ai_embedding_vector('hello')` returns 1536 dimension f32 vectors.
part #10689
=> feat(functions): ai_embedding_vector

Cargo.lock, Cargo.toml, src/common/arrow/Cargo.toml
=> chore(query): bump arrow2

src/query/service/src/pipelines/executor/pipeline_executor.rs
chore(executor): add query id for log
Closes #issue
=> chore(executor): add query id for log

.github/workflows/benchmark.yml, .github/workflows/dev-linux.yml, .github/workflows/production.yml, .github/workflows/release.yml, .github/workflows/trusted-benchmark.yml, scripts/benchmark/run-meta-benchmark.sh, scripts/ci/deploy/databend-query-management-mode.sh, scripts/ci/deploy/databend-query-sharing.sh, scripts/ci/deploy/databend-query-standalone-hive.sh, scripts/ci/deploy/databend-query-standalone-native.sh, scripts/ci/deploy/databend-query-standalone.sh, tests/compat/test-compat.sh, tests/fuse-compat/test-fuse-compat.sh, tests/meta-cluster/test-meta-cluster.sh, tests/metactl/test-metactl-restore-new-cluster.sh, tests/metactl/test-metactl.sh
=> chore: adjust runner labels

.github/workflows/trusted-benchmark.yml
=> fix(ci): remove old arg run_id for benchmark

src/query/sql/src/planner/binder/select.rs, tests/sqllogictests/suites/query/union.test
=> fix(query): union type not match just need return err

.github/actions/create_check_status/action.yml
=> ci: fix adding check with gh api

.github/actions/create_check_status/action.yml, .github/workflows/trusted-benchmark.yml
=> ci: fix create check status input [skip ci]

src/query/settings/src/settings.rs, src/query/settings/src/settings_global.rs, tests/sqllogictests/suites/base/20+_others/20_0015_set_unknown_setting
fix(query): report error when set unknown setting 
Closes #10859
=> fix(query): report error when set unknown setting

src/query/service/src/interpreters/interpreter_table_show_create.rs, src/query/service/tests/it/servers/http/http_query_handlers.rs, src/query/service/tests/it/storages/testdata/columns_table.txt, src/query/service/tests/it/storages/testdata/databases_table.txt, src/query/storages/system/src/databases_table.rs, src/query/storages/system/src/lib.rs, src/query/storages/system/src/tables_table.rs
=> feat(query): system table add some info && fix TRANSIENT table show err

src/query/service/src/servers/flight_sql/flight_sql_service/catalog.rs, src/query/service/src/servers/flight_sql/flight_sql_service/mod.rs, src/query/service/src/servers/flight_sql/flight_sql_service/service.rs
=> feat(FlightSQL): support do_get_tables.

docs/doc/14-sql-commands/40-show/show-full-columns.md
fixed comments from @TCeason 
Closes #issue
=> docs: fix comments on SHOW COLUMNS

benchmark/clickbench/update_results.py
=> ci(benchmark): fix glob results [skip ci]

.github/actions/benchmark_cloud/action.yml, .github/actions/benchmark_local/action.yml, benchmark/clickbench/benchmark_cloud.sh, benchmark/clickbench/benchmark_local.sh, benchmark/clickbench/index.jinja, benchmark/clickbench/update_results.py
=> ci(benchmark): detect machine with IMDSv2 [skip ci]

src/query/sql/src/planner/plans/scalar_expr.rs
=> chore: fix main build error

docs/doc/14-sql-commands/00-ddl/20-table/10-ddl-create-table.md
=> docs: added notes and example for CREATE TABLE LIKE

docs/doc/14-sql-commands/00-ddl/20-table/90-alter-table-column.md
- added links to pages about clustering and reclustering
- updated the example
Closes #10857
=> docs: alter table

benchmark/clickbench/benchmark_cloud.sh, benchmark/clickbench/benchmark_local.sh, scripts/ci/deploy/databend-query-cluster-3-nodes.sh, scripts/ci/deploy/databend-query-management-mode.sh, scripts/ci/deploy/databend-query-sharing.sh, scripts/ci/deploy/databend-query-standalone-hive.sh, scripts/ci/deploy/databend-query-standalone-native.sh, scripts/ci/deploy/databend-query-standalone.sh
=> ci: wait longer for query start

src/query/sql/src/planner/optimizer/heuristic/prune_unused_columns.rs, tests/sqllogictests/suites/mode/standalone/explain/project_set.test
Add some tests about unused column pruning for `ProjectSet`.
=> chore(planner): Add more tests for `ProjectSet`

.github/actions/artifact_failure/action.yml, .github/actions/fuse_compat/action.yml, .github/actions/test_compat/action.yml, .github/actions/test_fuzz_standalone_linux/action.yml, .github/actions/test_meta_cluster/action.yml, .github/actions/test_stateless_cluster_linux/action.yml, .github/actions/test_stateless_standalone_linux/action.yml, .github/workflows/build-tool.yml, .github/workflows/dev-linux.yml, .github/workflows/release.yml, benchmark/clickbench/benchmark_local.sh, scripts/setup/dev_setup.sh, tests/compat/test-compat.sh, tests/meta-cluster/test-meta-cluster.sh
=> ci: separate x86_64 gnu build for dev-linux

README.md, docs/doc/01-guides/index.md, docs/doc/15-sql-functions/61-ai-functions/02-ai-embedding-vector.md, docs/doc/15-sql-functions/61-ai-functions/03-ai-cosine-distance.md, docs/doc/15-sql-functions/61-ai-functions/04-ai-text-completion.md, docs/doc/15-sql-functions/61-ai-functions/index.md
=> docs: add ai function

.github/workflows/trusted-benchmark.yml
=> ci: fix typo for update benchmark result [skip ci]

src/query/sql/src/planner/binder/ddl/column.rs
=> chore(query): show full columns print filed: comment -> Comment

docs/doc/01-guides/index.md, docs/doc/15-sql-functions/61-ai-functions/01-ai-to-sql.md, docs/doc/15-sql-functions/61-ai-functions/02-ai-embedding-vector.md, docs/doc/15-sql-functions/61-ai-functions/03-ai-text-completion.md, docs/doc/15-sql-functions/61-ai-functions/04-ai-cosine-distance.md, docs/doc/15-sql-functions/61-ai-functions/index.md
=> docs: add more caution for the OpenAI api

docs/doc/15-sql-functions/10-aggregate-functions/index.md
Function summarization of KURTOSIS, SKEWNESS are added.
Also, I reorder the functions, making it consistent with function order in the navigation bar.
Closes #10905
=> docs(Aggregate functions index page): Function summarization of KURTOSIS, SKEWNESS are added.

docs/doc/14-sql-commands/00-ddl/20-table/10-ddl-create-table.md
Added more details about how to get back `TRANSIENT` and `COMPRESSION`.
Closes #issue
=> docs: create table attributes

src/query/service/src/servers/http/v1/query/execute_state.rs
=> chore(http_handler): log panic reason.

scripts/setup/dev_setup.sh
for: https://github.com/datafuselabs/databend/pull/10921
=> ci: add python3 as build dependency

docs/doc/90-contributing/01-rfcs/20221013-iceberg-catalog.md
=> docs: better iceberg-catalog.md sql format

scripts/setup/dev_setup.sh
=> ci: fix install python3 for dev_setup

docs/doc/21-use-cases/03-analyze-user-retention-with-databend.md
retention return is an array, In Databend array from the offset: 1
=> docs: Update 03-analyze-user-retention-with-databend.md

.github/actions/build_linux/action.yml, .github/actions/build_linux_hive/action.yml, .github/actions/setup_build_tool/action.yml, .github/workflows/backport.yml, .github/workflows/dev-linux.yml, .github/workflows/release.yml, docker/build-tool/base/Dockerfile, docker/build-tool/musl/Dockerfile, scripts/setup/run_build_tool.sh
=> ci: fix build tool for musl

docker/build-tool/gnu/Dockerfile, docker/build-tool/musl/Dockerfile
for: https://github.com/datafuselabs/databend/pull/10921
=> ci: install g++ for cross build

src/binaries/query/main.rs
feat: Output internal config while starting
=> feat: Output internal config while starting

docker/build-tool/musl/Dockerfile
for: https://github.com/datafuselabs/databend/pull/10921
=> ci: symlink musl ar for linking

tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_07_list_stage.result, tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_07_list_stage.sh
=> ci(stage): fix flaky test #10939

src/query/service/src/pipelines/pipeline_builder.rs, src/query/sql/src/executor/physical_plan.rs
=> fix: don't map trivial columns in block operator

src/query/sql/src/planner/optimizer/hyper_dp/dphyp.rs
=> fix: missing filter operators in dphyp

src/query/constraint/src/declare.rs, src/query/constraint/src/lib.rs, src/query/constraint/src/prelude.rs, src/query/constraint/src/problem.rs, src/query/constraint/tests/it/declare.rs, src/query/constraint/tests/it/main.rs, src/query/constraint/tests/it/problem.rs
=> feat(planner): introduce a utility to check if a variable is not null

src/query/service/tests/it/sql/planner/format/mod.rs, src/query/sql/src/planner/binder/table.rs, src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs, src/query/sql/src/planner/optimizer/property/property.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_fold_count_aggregate.rs, src/query/sql/src/planner/plans/aggregate.rs, src/query/sql/src/planner/plans/dummy_table_scan.rs, src/query/sql/src/planner/plans/eval_scalar.rs, src/query/sql/src/planner/plans/filter.rs, src/query/sql/src/planner/plans/join.rs, src/query/sql/src/planner/plans/limit.rs, src/query/sql/src/planner/plans/runtime_filter_source.rs, src/query/sql/src/planner/plans/scan.rs, src/query/sql/src/planner/plans/union_all.rs, src/query/sql/src/planner/plans/window.rs
=> refactor(query): delete is_accurate in Statistics

src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/inner_join.rs, tests/sqllogictests/suites/query/join.test
Will fix tpcds 46/95/64 🚀 
Closes #issue
=> fix: join condition may be nullable

docs/doc/13-sql-reference/10-data-types/40-data-type-array-types.md
- fixed error in the example
- added a note about 1-based numbering 
Closes #issue
=> docs: fix array

src/query/service/src/api/rpc/exchange/serde/exchange_deserializer.rs, src/query/service/src/api/rpc/exchange/statistics_receiver.rs, src/query/service/src/api/rpc/exchange/statistics_sender.rs, src/query/service/src/api/rpc/packets/packet_data.rs
chore(cluster): remove useless code
Closes #issue
=> chore(cluster): remove useless code

docker/Dockerfile, docker/query-config.toml, scripts/distribution/configs/databend-query.toml
=> chore: expose flight sql port in docker

src/query/sql/src/executor/physical_plan_builder.rs, src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs
=> fix: subquery derived column type

src/query/service/src/pipelines/executor/pipeline_executor.rs
fix(executor): catch unwind for executor on_init and on_finished
Closes #issue
=> fix(executor): catch unwind for executor on_init and on_finished

src/query/pipeline/core/src/pipeline.rs, src/query/service/src/api/rpc/exchange/exchange_manager.rs, src/query/service/src/api/rpc/flight_service.rs, src/query/service/src/pipelines/executor/executor_settings.rs, src/query/service/src/pipelines/executor/pipeline_executor.rs, src/query/service/tests/it/main.rs, src/query/service/tests/it/pipelines/executor/mod.rs, src/query/service/tests/it/pipelines/executor/pipeline_executor.rs
fix(cluster): try fix cluster session leak
Closes #issue
=> fix(cluster): try fix cluster session leak

docs/doc/15-sql-functions/61-ai-functions/index.md
=> docs: add example to ai funtions

.github/workflows/release.yml
=> chore(ci): fix release dockerhub description [skip ci]

website/blog/2023-04-08-databend-weekly-88.md
=> docs(weekly): fix url

website/blog/2023-04-08-databend-weekly-88.md
=> docs(weekly): improve according to eric's comments

docs/doc/15-sql-functions/30-datetime-functions/tounixtimestamp.md
added TO_UNIX_TIMESTAMP function
Closes #issue
=> docs: TO_UNIX_TIMESTAMP

src/query/service/src/servers/http/v1/query/execute_state.rs
for progress showing in http client
Closes #issue
=> feat(query): add total_scan to ExecuteState

src/query/service/src/interpreters/interpreter_table_drop.rs, src/query/service/src/interpreters/interpreter_table_drop_column.rs, src/query/service/src/interpreters/interpreter_view_drop.rs, tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_drop_tables, tests/sqllogictests/suites/base/05_ddl/05_0003_ddl_alter_table, tests/sqllogictests/suites/base/05_ddl/05_0020_ddl_drop_view, tests/sqllogictests/suites/base/11_data_type/11_0006_data_type_decimal, tests/suites/0_stateless/20+_others/20_0013_pretty_error.result
=> fix(query): drop table unknown table should return error

docs/doc/10-deploy/06-manage-settings.md, docs/doc/10-deploy/_category_.json
added a page describing system settings, default values, and how to configure them.
Closes #issue
=> docs: Manage settings

website/blog/2023-04-11-benchmark-tpc-ds.md
=> docs: tpcds benchmark

Cargo.lock, src/query/constraint/src/lib.rs, src/query/constraint/src/problem.rs, src/query/constraint/tests/it/problem.rs, src/query/sql/Cargo.toml, src/query/sql/src/planner/binder/mod.rs, src/query/sql/src/planner/mod.rs, src/query/sql/src/planner/optimizer/property/constraint.rs, src/query/sql/src/planner/optimizer/property/datum.rs, src/query/sql/src/planner/optimizer/property/mod.rs, src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/mod.rs, src/query/sql/src/planner/optimizer/rule/rewrite/filter_join/outer_join_to_inner_join.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_push_down_filter_join.rs, src/query/sql/src/planner/plans/scan.rs, tests/sqllogictests/suites/mode/standalone/explain/eliminate_outer_join.test, tests/sqllogictests/suites/mode/standalone/explain_native/select.test
Use constraint to eliminate outer joins.
=> feat(planner): Refactor outer join elimination with constraint

docs/doc/13-sql-reference/10-data-types/42-data-type-map.md, docs/doc/13-sql-reference/10-data-types/43-data-type-variant.md
=> docs: add more example to variant&map data type

src/query/service/src/pipelines/pipeline_builder.rs, src/query/service/src/pipelines/processors/transforms/aggregator/aggregate_exchange_injector.rs, src/query/service/src/pipelines/processors/transforms/aggregator/transform_partition_bucket.rs, src/query/service/src/schedulers/fragments/query_fragment_actions.rs
chore(cluster): reduce pipeline
Closes #issue
=> chore(cluster): reduce pipeline

src/query/expression/src/block.rs, src/query/pipeline/transforms/src/processors/transforms/mod.rs, src/query/pipeline/transforms/src/processors/transforms/transform_block_compact.rs, src/query/pipeline/transforms/src/processors/transforms/transform_block_compact_for_copy.rs, src/query/storages/fuse/src/operations/append.rs
=> feat: split large block during load.

benchmark/clickbench/hits/load.sql, benchmark/clickbench/tpch/load.sql
=> ci: fix load data for benchmark

.github/actions/publish_deb/action.yml
=> ci: include bendsql for deb repo [skip ci]

.github/workflows/release.yml, benchmark/clickbench/hits/load.sql, benchmark/clickbench/tpch/load.sql
=> ci: fix load data for benchmark [skip ci]

scripts/ci/ci-run-sharding-tests.sh
chore: disable share statefull test and check bugs
Closes #issue
=> chore: disable share statefull test and check bugs

tests/sqllogictests/suites/mode/standalone/explain/window.test, tests/sqllogictests/suites/query/window_function/window_basic.test
=> ci(function): test explain window function.

Cargo.lock, src/query/constraint/Cargo.toml, src/query/constraint/benches/bench.rs
=> chore(planner): Add benchmark utility for constraint

src/query/storages/fuse/src/io/snapshots.rs, src/query/storages/fuse/src/operations/gc.rs, src/query/storages/fuse/src/table_functions/fuse_snapshots/fuse_snapshot.rs
[Summary about this PR](https://github.com/datafuselabs/databend/pull/11015#issuecomment-1511364239)
Closes #11098
=> fix(storage): read snapshot with wrong version

website/src/components/CustomBlog/BlogPostDetails.js
=> fix: Highlight blog code

src/query/ast/src/parser/expr.rs, src/query/ast/src/parser/token.rs, src/query/ast/tests/it/parser.rs, src/query/ast/tests/it/testdata/expr-error.txt, src/query/ast/tests/it/testdata/statement-error.txt, src/query/ast/tests/it/testdata/statement.txt
=> feat: support parse varbinary as String Type

Cargo.lock, Cargo.toml, src/common/storage/src/metrics.rs, src/common/storage/src/runtime_layer.rs
fix: Storage Service OSS's env is not loaded
=> fix: Storage Service OSS's env is not loaded

src/meta/client/src/grpc_client.rs
Previously, the meta-grpc-client would eliminate the unhealthy endpoints
if the candidate endpoints contained more than one element.
However, it is still probable to obtain an empty list after filtering
out the unhealthy endpoints. The correct way should be to first
filter out the unhealthy endpoints and then verify if the list is empty.
If it is empty, it should revert to using all the endpoints,
regardless of their health status.
And the cached endpoints does not need an `async` lock.
- Part of: #10829
- Improvement
=> refactor: revert to using all endpoints if all are unhealthy.

.github/workflows/release.yml
=> ci: add basic sqllogic test before release binaries [skip ci]

src/query/ast/src/ast/query.rs, src/query/ast/src/parser/query.rs, src/query/ast/src/parser/statement.rs, src/query/ast/tests/it/parser.rs, src/query/ast/tests/it/testdata/query-error.txt, src/query/ast/tests/it/testdata/query.txt, src/query/ast/tests/it/testdata/statement-error.txt, src/query/ast/tests/it/testdata/statement.txt
Closes https://github.com/datafuselabs/databend/issues/11004
=> chore(ast): merge parsers for query and set_operation

docs/doc/00-overview/index.md
added LinkedIn and YouTube.
Closes #issue
=> docs: Update social media links

README.md, docs/doc/01-guides/index.md
=> docs: make README more shrink

src/query/expression/src/block.rs, src/query/pipeline/sources/src/input_formats/impls/input_format_parquet.rs, src/query/pipeline/sources/src/input_formats/input_pipeline.rs, src/query/pipeline/transforms/src/processors/transforms/transform_block_compact_for_copy.rs
=> fix: copy from parquet oom

.github/workflows/release.yml
=> ci: tmp allow failure for release sqllogictest [skip ci]

.github/workflows/release.yml
=> ci: fix continue on error for linux release

src/query/catalog/src/plan/pushdown.rs, src/query/service/src/api/http_service.rs, src/query/service/src/servers/http/http_services.rs, src/query/service/tests/it/storages/fuse/operations/read_plan.rs, src/query/sql/src/executor/physical_plan_builder.rs, src/query/storages/fuse/src/operations/read_partitions.rs
1. add timeout in shutdown service
2. add `is_deterministic` in push_down
Closes #issue
=> feat: add timeout in shutdown service

docker/build-tool/musl/Dockerfile, docker/build-tool/musl/linker.sh, scripts/setup/dev_setup.sh
and install sccache with binary in `dev_setup.sh`
Closes #issue
=> ci: fix static link with libstdc++ for musl build

scripts/setup/run_build_tool.sh
=> chore(ci): fix sccache path

docs/doc/11-integrations/00-api/10-put-to-stage.md
- added an example: upload to the user stage
- other refactors
Closes #issue
=> docs: refactor FILE UPLOAD API

docs/doc/15-sql-functions/120-other-functions/to_nullable.md
=> docs:  display to_nullable return type

Cargo.lock
chore: Bump reqsign to fix token not encoded
=> chore: Bump reqsign to fix token not encoded

docs/doc/11-integrations/30-access-tool/02-jdbc.md
update databend-jdbc driver 0.0.6 to 0.0.7
Closes #issue
=> docs: Update 02-jdbc.md

Cargo.lock, Cargo.toml, src/common/storage/src/metrics.rs, src/query/sharing/src/layer.rs
Fix https://github.com/datafuselabs/databend/issues/11180
=> fix: Fix COS could return "Invalid Argument" while starting

.github/actions/artifact_failure/action.yml, .github/workflows/dev-linux.yml, .github/workflows/production.yml
=> ci: fix upload failure for stateful test cluster [skip ci]

.github/actions/artifact_failure/action.yml
=> ci: only pack .databend for upload failure [skip ci]

benchmark/clickbench/benchmark_cloud.sh, benchmark/clickbench/benchmark_local.sh
Three times are enough
Closes #issue
=> chore: reduce benchmark round to 3

src/query/ast/src/parser/query.rs, src/query/expression/src/evaluator.rs, src/query/expression/src/function.rs, src/query/functions/src/scalars/datetime.rs, src/query/functions/src/scalars/decimal.rs, src/query/functions/src/scalars/variant.rs, src/query/functions/tests/it/scalars/testdata/function_list.txt
=> chore(function): simplify TryAdaptor

docs/doc/02-cloud/index.md
updated the Databend Cloud page on doc.rs
Closes #issue
=> docs: New cloud page

docs/doc/15-sql-functions/40-string-functions/soundex.md, docs/doc/15-sql-functions/40-string-functions/soundslike.md
- added "sounds like" function.
- refactored soundex.
Closes #issue
=> docs: sounds like

.github/actions/test_stateful_cluster_linux/action.yml, .github/actions/test_stateful_standalone_linux/action.yml, src/query/service/src/interpreters/access/privilege_access.rs, src/query/service/src/interpreters/interpreter_copy.rs, src/query/sql/src/planner/binder/copy.rs, src/query/sql/src/planner/plans/copy.rs, tests/suites/1_stateful/00_copy/00_0000_copy_from_stage.sh, tests/suites/1_stateful/00_copy/00_0005_copy_from_stage_max_files.result, tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_06_transform.result
tracked in https://github.com/datafuselabs/databend/issues/11158
=> refactor(copy): rewrite copy into table for parquet.

docs/doc/14-sql-commands/10-dml/dml-copy-into-table.md
=> docs: refine the copy

docs/doc/15-sql-functions/61-ai-functions/01-ai-to-sql.md, docs/doc/15-sql-functions/61-ai-functions/02-ai-embedding-vector.md, docs/doc/15-sql-functions/61-ai-functions/04-ai-cosine-distance.md, docs/doc/15-sql-functions/61-ai-functions/index.md
* refine the AI functions example
Closes #issue
=> docs: refine the AI functions

docs/doc/14-sql-commands/00-ddl/20-table/60-optimize-table.md
* format the SQL
Closes #issue
=> docs: improve optimize table

docs/doc/14-sql-commands/00-ddl/20-table/10-ddl-create-table.md, docs/doc/14-sql-commands/00-ddl/20-table/90-alter-table-column.md, docs/doc/14-sql-commands/00-ddl/70-clusterkey/index.md
* update table default column value to expression
* remove cluster key from create table
* mark cluster key is a experimetal feature
Closes #issue
=> docs: update table default value

docs/doc/03-develop/_category_.json, docs/doc/03-develop/index.md
* add drivers page to developer chapter
Closes #issue
=> docs: add drivers index page

.github/actions/benchmark_cloud/action.yml, .github/actions/setup_bendsql/action.yml, .github/workflows/trusted-benchmark.yml, benchmark/clickbench/benchmark_cloud.sh, benchmark/clickbench/benchmark_local.sh, docker/README.md, docker/bootstrap.sh, docs/doc/11-integrations/20-gui-tool/02-grafana.md, scripts/benchmark/query/load/hits.sh, scripts/benchmark/query/load/tpch10.sh, scripts/benchmark/query/load/tpch100.sh, website/blog/2023-02-24-Deploy-databend-on-minio.md, website/blog/2023-03-02-bendsql.md, website/blog/2023-04-15-databend-weekly-89.md
=> ci(benchmark): update to use new bendsql

.github/workflows/release.yml, .github/workflows/trusted-benchmark.yml
=> ci: do not ignore error on benchmark & release [skip ci]

docs/doc/11-integrations/30-access-tool/01-bendsql.md, docs/doc/12-load-data/02-local.md
=> docs: add more example & instruction for bendsql

docs/doc/01-guides/index.md, docs/doc/03-develop/04-rust.md, docs/doc/10-deploy/05-deploying-local.md, docs/doc/11-integrations/20-gui-tool/02-grafana.md, docs/doc/11-integrations/30-access-tool/01-bendsql.md, docs/doc/12-load-data/02-local.md
As confirmed: https://github.com/datafuselabs/databend/pull/11230#discussion_r1176565608
Closes #issue
=> docs: renamed bendsql to BendSQL

src/query/service/src/interpreters/interpreter_copy.rs
=> fix: expire_at in upsert_copied_files_request

.github/actions/setup_bendsql/action.yml, .github/actions/setup_build_tool/action.yml
=> ci: add cache for cargo registry

.github/actions/setup_bendsql/action.yml
=> chore(ci): upgrade bendsql to v0.3.4 [skip ci]

Cargo.lock, src/query/ast/src/parser/token.rs, src/query/ast/tests/it/testdata/lexer.txt
filter invalid hintsuffix also need check the EOI token
Closes #11245
=> fix(query): filter hintsuffix need check the EOI token

src/query/sql/src/planner/binder/binder.rs
chore(query): try fix build failure
Closes #issue
=> chore(query): try fix build failure

docs/doc/11-integrations/30-access-tool/00-mysql.md, docs/doc/11-integrations/30-access-tool/01-bendsql.md, docs/doc/11-integrations/30-access-tool/02-jdbc.md
Added YouTube video: https://youtu.be/3cFmGvtU-ws
Closes #issue
=> docs: added YouTube video

tests/suites/0_stateless/05_hints/05_0001_set_var.sh
=> fix(ci): add order by to fix flaky test

.github/actions/artifact_download/action.yml, .github/actions/benchmark_local/action.yml
=> chore(ci): check disk before & after download [skip ci]

tests/sqllogictests/suites/base/03_common/03_0037_efficiently_memory_group_by
https://github.com/datafuselabs/databend/actions/runs/4832540697/jobs/8619577627#step:7:195
this test caused release 1.1.22 ci run failed.
Closes #issue
=> fix(ci): comment a test

docker/build-tool/base/Dockerfile, docker/build-tool/musl/linker.sh
=> chore(build-tool): link musl with mold [skip ci]

scripts/setup/run_build_tool.sh, scripts/setup/rust-tools.txt
=> chore(build-tool): fixes for shellcheck

docs/doc/13-sql-reference/10-data-types/index.md
=> docs: add link to data types

.github/actions/build_linux/action.yml, .github/actions/build_macos/action.yml, .github/actions/publish_binary/action.yml, .github/backup/dev-macos.yml, .github/workflows/benchmark.yml, .github/workflows/production.yml, .github/workflows/release.yml, .github/workflows/trusted-cancel.yml, scripts/distribution/nfpm.yaml
=> ci: include metactl in release

website/blog/2023-04-30-databend-weekly-91.md
=> docs: Update 2023-04-30-databend-weekly-91.md

rust-toolchain.toml, scripts/setup/rust-toolchain.toml, src/query/service/src/pipelines/processors/transforms/window/transform_window.rs
ci: Add rust-analyzer in rust toolchain
=> ci: Add rust-analyzer in rust toolchain

src/query/functions/src/scalars/decimal.rs, src/query/service/src/pipelines/processors/transforms/window/transform_window.rs, tests/sqllogictests/suites/base/11_data_type/11_0006_data_type_decimal
=> chore: enable cast decimal 256 to 128

docs/doc/14-sql-commands/80-setting-cmds/01-set-global.md, docs/doc/14-sql-commands/80-setting-cmds/03-set-var.md
added optimize hint SET_VAR.
Closes #issue
=> docs: set_var

docs/doc/12-load-data/02-local.md, docs/doc/12-load-data/04-http.md, docs/doc/12-load-data/05-querying-stage.md, docs/doc/12-load-data/06-data-load-transform.md, docs/doc/12-load-data/index.md
=> docs: Load data

docs/doc/03-develop/01-python.md
=> docs(develop/python): add close connect

docs/doc/14-sql-commands/00-ddl/20-table/60-optimize-table.md
fixed vague description found at https://databend.rs/doc/sql-commands/ddl/table/optimize-table
Closes #issue
=> docs: why Optimize

docs/doc/12-load-data/06-data-load-transform.md
added tutorials to https://databend.rs/doc/load-data/data-load-transform
Closes #issue
=> docs: data transform tutorials

.github/workflows/trusted-benchmark.yml
=> ci: run tpch benchmark on Medium

src/query/service/src/test_kits/mod.rs, src/query/service/src/test_kits/sessions.rs
fix: fix test_kits release mod build fail
Closes #issue
=> fix: fix test_kits release mod build fail

.github/actions/build_linux/action.yml, .github/actions/setup_build_tool/action.yml
=> chore(ci): use larger JEMALLOC_SYS_WITH_LG_PAGE for aarch64 build

.github/actions/artifact_download/action.yml, .github/actions/fuse_compat/action.yml, .github/actions/test_compat/action.yml, .github/actions/test_meta-upgrade-09/action.yml, .github/actions/test_meta_data_compat_openraft_07/action.yml, .github/actions/test_metactl/action.yml, .github/actions/test_sqllogic_cluster_linux/action.yml, .github/actions/test_sqllogic_management_mode_linux/action.yml, .github/actions/test_sqllogic_standalone_linux/action.yml, .github/actions/test_stateful_sharing/action.yml, .github/workflows/benchmark.yml, .github/workflows/cancel.yml
=> ci: fetch only needed binaries for test

Cargo.lock, Cargo.toml, src/query/service/src/api/rpc_service.rs
fix(cluster): add max message size config for server
Closes #issue
=> fix(cluster): add max message size config for server

.github/workflows/release.yml
=> ci: fix workflow benchmark in release [skip ci]

.github/actions/artifact_download/action.yml
=> ci: fix make binary executable for github artifacts

website/blog/2023-04-30-databend-weekly-91.md, website/blog/2023-05-07-databend-weekly-92.md
=> docs(weekly): add this week in databend 92

.github/workflows/dev-linux.yml, scripts/ci/ci-run-sqllogic-tests-cluster.sh, scripts/ci/ci-run-stateless-tests-cluster.sh, src/query/sql/src/planner/plans/join.rs, tests/sqllogictests/src/arg.rs, tests/sqllogictests/src/main.rs, tests/sqllogictests/suites/tpcds/queries.test, tests/sqllogictests/suites/tpcds/tpcds_q64.test
Following https://github.com/datafuselabs/databend/pull/11306, I forgot cluster mode
- add arg `--skip_file`
Closes #issue
=> chore: add tpch, tpcds test to cluster

src/query/settings/src/settings_getter_setter.rs
Validate max_storage_io_requests which checks it's greater than 0 or throw an error .
Closes #11361
=> feat: validates the value of max_storage_io_requests being

.github/workflows/benchmark.yml
=> ci: fix concurrency group for benchmark with head_ref [skip ci]

.github/actions/test_sqllogic_standalone_macos/action.yml
=> ci: fix download artifacts for sqllogic test macos [skip ci]

docs/doc/14-sql-commands/20-query-syntax/01-query-select.md, website/blog/2023-05-07-databend-weekly-92.md
Using column alias in the WHERE clause
Closes #issue
=> docs: column alias in WHERE

src/query/storages/fuse/src/operations/read_partitions.rs
chore(query): call by name for prune cache key
Closes #issue
=> chore(query): call by name for prune cache key

docs/doc/14-sql-commands/00-ddl/20-table/10-ddl-create-table.md, docs/doc/14-sql-commands/20-query-syntax/01-query-select.md
Added description about auto lowercase conversion & how to handle special characters.
Closes #11384
=> docs: column name & alias conventions

README.md
=> docs: display the license FAQ link in the README

src/query/pipeline/sources/src/input_formats/input_format_text.rs
Closes https://github.com/datafuselabs/databend/issues/11397
=> fix:  oom when load CSV with many columns.

Cargo.lock, src/common/storage/Cargo.toml, src/meta/service/Cargo.toml, src/meta/types/Cargo.toml, src/query/ast/Cargo.toml, src/query/functions/Cargo.toml, src/query/service/Cargo.toml, src/query/sql/Cargo.toml, tests/sqllogictests/Cargo.toml
upgrade regex crate .
Closes #11162
=> chore: new release regex

src/query/sql/src/planner/binder/table.rs, src/query/sql/src/planner/optimizer/heuristic/decorrelate.rs, src/query/sql/src/planner/optimizer/heuristic/heuristic.rs, src/query/sql/src/planner/optimizer/rule/factory.rs, src/query/sql/src/planner/optimizer/rule/rewrite/mod.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_try_apply_agg_index.rs, src/query/sql/src/planner/optimizer/rule/rule.rs, src/query/sql/src/planner/plans/aggregate.rs, src/query/sql/src/planner/plans/scan.rs
Pre task: #11232
Use RBO framework to rewrite the query plan.
Next task: introduce index scan to pipeline.
Only support query like:
```sql
SELECT ...
FROM ...
WHERE ...
GROUP BY ...
```
**NOT** support `order by` and `having clause`.
=> feat: auto query rewriting for aggregation index.

Cargo.lock, src/query/expression/src/evaluator.rs, src/query/expression/src/expression.rs, src/query/sql/src/planner/optimizer/rule/rewrite/rule_fold_constant.rs
=> chore(planner): allow untrustworthy column ref type of constant folding rule

src/query/service/src/interpreters/interpreter_table_create.rs, tests/sqllogictests/suites/base/05_ddl/05_0000_ddl_create_tables
1. If max_tables_per_database != 0 and then , try to list tables.
2. If same name exists, Check whether the engine supports. 
Closes #11425
=> feat(query): try optimize create table

.github/actions/artifact_upload/action.yml, .github/workflows/bindings_python.yml, .github/workflows/dev-linux.yml, .github/workflows/release.yml, Cargo.lock, scripts/setup/dev_setup.sh, src/bendpy/Cargo.toml
=> ci: test & release python binding
